### DISCUSSION TITLE
issue while trying to have multiple form_login authenticators

### DISCUSSION THREAD

**Discussion by W2AlharbiMe** [symfony/symfony#42429] [Q&A] [answered]
Hello, so recently i'm trying to add another `form_login` authenticator for specific host 

i got this error:
```
Because you have multiple authenticators in firewall "main", you need to set the "entry_point" key to one of your authenticators 
("App\Security\AppAuthenticator", "App\Security\BloggerAuthenticator") or a service ID implementing 
"Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface". The "entry_point" determines what should 
happen (e.g. redirect to "/login") when an anonymous user tries to access a protected page.
```

so i have created class that implements `Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface::start`

this is the custom entry point:

```php
<?php

namespace App\Security;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface;


class CustomEntryAuthenticator implements AuthenticationEntryPointInterface {

  // this method never get called
  public function start(Request $request, AuthenticationException $authException = null)
  {
    dd($request);

    return new RedirectResponse('/login');
  }
}
```

my `security.yaml` looks like this:

```yaml
security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

    app_blogger_provider:
      entity:
        class: App\Entity\Blogger
        property: username

  firewalls:
    main:
      lazy: true

      providers:       # not sure about this config
        - app_user_provider
        - app_blogger_provider
      
      custom_authenticators: # not sure about this config
        - App\Security\AppAuthenticator
        - App\Security\BloggerAuthenticator

      entry_point: App\Security\CustomEntryAuthenticator # not sure about this config

      logout:
        path: app_logout
```

but still i have the same issue,
does my security configurations correct ?
