### DISCUSSION TITLE
[Symfony 5.3] New authenticator

### DISCUSSION THREAD

**Discussion by meiyasan** [symfony/symfony#42435] [Q&A] [answered]
Hello guys,

I am trying to use the new authenticator system with Symfony 5.3.6.
My security.yaml is the following (nb: I enabled the new authenticator manager):

```yaml
security:
    enable_authenticator_manager: true
    password_hashers:
        xKzl\MyBundle\Entity\User:
            algorithm: auto

    providers: # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
        users: { entity: { class: App\Entity\User, property: 'username' } } # User entity
        hwi: { id: xKzl\MyBundle\Security\UserProvider } # Social networks
        #in_memory: { memory: null }

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: users
            lazy: true
            
            # allow authentication using a form or HTTP basic
            http_basic: ~
            entry_point: xKzl\MyBundle\Security\LoginFormAuthenticator
            form_login: 
                always_use_default_target_path: true
                use_referer: true

            logout:
                path: base_logout_request
                target: base_logout
                invalidate_session: false

```

Right now, I have been able to update my classes implementing my own LoginFormAuthenticator, but this one is not called, when I am in my "base_login" route. My class is implemented in a bundle, so I added it in the service.xml file.
I wondered if I was supposed to add a special tag for that service.

Please, can you advice ? :-)
Thank you so much

Marco
