### DISCUSSION TITLE
Twig config outside config/packages/twig.yaml

### DISCUSSION THREAD

**Discussion by machacjan** [symfony/symfony#42463] [Q&A] [answered]
Hello, I'm trying to define custom Twig templates namespace. I'm able to do just that in the `config/packages/twig.yaml` file:

```yaml
# config/packages/twig.yaml

twig:
    paths:
        '%kernel.project_dir%/src/foo/Resources/views': 'bar'
```

However, when using config file in the foo path `src/foo/Resources/config/config.yaml` I get the following error: `There are no registered paths for namespace "bar".` 

Is it even possible to define Twig config outside the main file?
