### DISCUSSION TITLE
Doctrine xml mapping files for value objects not working

### DISCUSSION THREAD

**Discussion by jesteban1972** [symfony/symfony#42477] [Q&A]
Hi there! I'm newbie in Symfony/Doctrine and I'm stuck with something I guess should have an easy solution:

I have an entity 'Product', and all its attributes are value objects. For DB mapping I'm using xml files, *NOT* annotations (I want the domain to be agnostic to the infrastructure -DDD approach).

The issue is, in the file  'Product.orm.xml' all fields should be `<embedded>` (value objects), but I can't do the same for field id, since it is necessary to define a `<id />` tag. So I created a custom type 'IdType' for the primary key, and mapping files for the other attributes e.g. 'ValueObject.Code.orm.xml'. Apparently it works (every instance of my entity has id, code etc. which are V.O. with an attribute 'value'), but the behavior is different: In the repository, to retrieve id value I simply do 'products.id' -as it should be-, but for the other attributes I must do: 'products.code.value'. What am I doing wrong?

These are (excerpts of) my configuration/mapping files:
```
<!-- Product.orm.xml -->
<id name="id" type="id_type" column="aid" length="11">
   <generator strategy="AUTO" />
</id>
<embedded
   name="code"
   class="Sales\Domain\Model\Product\ValueObject\Code"
   use-column-prefix="false" />
...

<!-- ValueObject.Code.orm.xml -->
<embeddable name="Sales\Domain\Model\Product\ValueObject\Code" >
  <field name="value" column="adescr" length="150" />
</embeddable>
...
```
Is it maybe a wrong definition in 'ValueObject.Code.orm.xml'? I tried 'name="code"' (I get 'Property Sales\Domain\Model\Product\ValueObject\Code::$code does not exist'); I tried to left out attribute 'column' (obviously it doesn't work). Is it maybe a wrong configuration in 'config/packages/doctrine.yaml'?:
```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            id_type : Sales\Infrastructure\Persistence\Doctrine\Product\Mapping\IdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Sales\Product:
                type: xml
                dir: '%kernel.project_dir%/src/Sales/Infrastructure/Persistence/Doctrine/Product/Mapping'
                prefix: 'Sales\Domain\Model\Product'
                alias: 'Sales:Product'
```

Am I neglecting something obvious? Please help!
