### DISCUSSION TITLE
How to change Controller folder path ?

### DISCUSSION THREAD

**Discussion by MohamedZogh** [symfony/symfony#42487] [Q&A] [answered]
Hello,

On Symfony 5.3 we can no longer configure the Controller folder path in the 'config / services.yaml' file as before. 

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\UserInterface\Controller\:
        resource: '../src/UserInterface/Controller'
        tags: ['controller.service_arguments']
```

Where should we now change it?

Thanks.
