### DISCUSSION TITLE
Pass Parameter of Class to Service via Dependency Injection

### DISCUSSION THREAD

**Discussion by Lowkey2224** [symfony/symfony#42617] [Q&A] [answered]
Hey there. I want to pass some variables into a service that I want to put into a class because those are quite a few.
Can you point me to a direction on how I can do that?
For example. My `FooService` is  expecting an Argument of Class `Foo` which has the fields `$a` and `$b`.
How can I inject an instance of class `Foo` which contains `$a` & `$b` from parameters.yml

**Comment by Jeroeny** [comment, marked as answer]
You'd have to configure a service of `Foo` with those arguments, e.g in `config/services.yaml`:
```yaml

Foo:
    arguments:
        $a: 'myvalue'
        $b: 'something'

FooService:
    arguments:
        $foo: '@Foo'
```

or if the `FooService` has `Foo` typehinted in the constructor argument, then explicitly defining the `@Foo` service isn't even needed.

If you expect multiple different services for `Foo`, they can have unique IDs:
```yaml
foo.myvalue:
    class: Foo
    arguments:
        $a: 'myvalue'
        $b: 'something'

foo.othervalue:
    class: Foo
    arguments:
        $a: 'othervalue'
        $b: 'something'

FooService:
    arguments:
        $foo: '@foo.myvalue'
```


See also: https://symfony.com/doc/current/components/dependency_injection.html
