### DISCUSSION TITLE
Better documents on password_hashers for SF 5.4

### DISCUSSION THREAD

**Discussion by yellow1912** [symfony/symfony#42674] [Q&A]
Hi all,

I'm trying to upgrade my application from 4.4 to the new 5.4 version, and I run into the issue with password_hashers.

My previous security config was like this:

```
encoders:
    My\AccountComponent\Model\AccountInterface: sha512
```

I believe that I have to change it to:

```
  password_hashers:
    legacy:
      algorithm: sha512

    My\AccountComponent\Model\AccountInterface:
      algorithm: 'auto'
      migrate_from:
        - bcrypt
        - legacy
```

(I also tried auto)

That did not work, however. I cannot login in to any account. I looked at the password migrations, but was not sure how that work: https://symfony.com/doc/current/security/password_migration.html

I'm using a custom UserProvider, I followed the instruction to add the method upgradePassword. Not sure if I'm doing something wrong here. The document seems missing some parts.
