### DISCUSSION TITLE
`FormLoginAuthenticator` produces logs even though fingers corssed action_level is set to warning

### DISCUSSION THREAD

**Discussion by tPl0ch** [symfony/symfony#42687] [Q&A]
Hello there, I have just migrated to the new authentication system with SF 5.3 with a simple form_login.

Now I am receiving a lot of the following logs whenever a public endpoint is requested:

```json
{
    "service": "api-marketplace",
	"message": "Authenticator does not support the request.",
	"attributes": {
		"service": "api-marketplace",
		"level": 100,
		"timestamp": 1629443802822,
		"datetime": "2021-08-20T07:16:42.821536+00:00",
		"source": "stderr",
		"context": {
			"authenticator": "Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator",
			"firewall_name": "main"
		},
		"level_name": "DEBUG",
		"channel": "security"
	}
}
```

`security.yml`

```yaml
security:
    enable_authenticator_manager: true

    # ...SNIP
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            form_login:
                enable_csrf: true
                check_path: /login
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login
            entry_point: form_login

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }
 ```

Another weird behaviour is that these logs are actually published even though my fingers crossed handler has warning as an action_level defined:

`prod/monolog.yml`

```yaml
services:
    json_formatter:
        class: Monolog\Formatter\JsonFormatter

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "php://stderr"
            level: debug
            formatter: json_formatter
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
```
