### DISCUSSION TITLE
How to use dependency injection in a command

### DISCUSSION THREAD

**Discussion by CJDennis** [symfony/symfony#42694] [Q&A] [answered]
I'm slowly upgrading our project from Symfony 2.8 to 4.4 (I'm trying to jump only to TLS versions). I've successfully taken it to 3.4 and I'm now making the changes needed to get it working under 4.0 before going to 4.4.

I need to change my Commands so that instead of fetching services from the container (which is no longer allowed), they use dependency injection (DI). DI is working just fine in my Controllers and Services, but I can't get it working in Commands.

services.yaml
```yaml

    HMRX\AppBundle\Controller\:
        resource: '../../src/HMRX/AppBundle/Controller'
        tags: ['controller.service_arguments']

    HMRX\AppBundle\Command\:
        resource: '../../src/HMRX/AppBundle/Command'
        tags:
            - 'console.command'
            - 'controller.service_arguments' # I've added this line to try to solve the problem
```

IncomingFileCheckCommand.php
```php
//class IncomingFileCheckCommand extends \Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand {
class IncomingFileCheckCommand extends \Symfony\Component\Console\Command\Command {
  /** @var EmailService */
  protected $email_service;

  public function __construct(\HMRX\CoreBundle\Services\EmailService $email_service) {
    $this->email_service = $email_service;
    parent::__construct();
  }
```

```
[ArgumentCountError] Too few arguments to function HMRX\AppBundle\Command\IncomingFileCheckCommand::__construct(), 0 passed in D:\server\Apache24\htdocs\hmr\app\HMRX_App\tests\unit\HMRX\AppBundle\Command\IncomingFileCheckCommandTest.php on line 54 and exactly 1 expected
```

I've also looked all over the internet in the usual places, Symfony docs, Stack Overflow, etc. How do you get DI to work in Commands?

**Comment by faizanakram99** [comment, marked as answer]
Just remove `'controller.service_arguments'` tag from `Command` namespace and all is good.

It should work out of the box assuming you're using default `services.yaml` configuration, i.e. autoconfigure and autowire enabled

Could u also post whole `services.yaml` file ?

**Reply by CJDennis** [reply]
It doesn't work with just `'console.command'` which is why I tried added the extra option. The `services.yaml` file is very messy due to being only partly converted from 2.8 to 4.0.

These are the relevant bits:
```yaml
# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    ## makes classes in src/ available to be used as services
    ## this creates a service per class whose id is the fully-qualified class name
    HMRX\CoreBundle\:
        resource: '../../src/HMRX/CoreBundle/*'
        exclude: '../../src/HMRX/CoreBundle/{Controller,DataMigrations,DependencyInjection,Entity,Tests,Utils,Kernel.php}'

    #HMRX\AppBundle\Controller\AccountController:
    #    bind:
    #        $encoder_factory: '@security.encoder_factory'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    HMRX\AppBundle\Controller\:
        resource: '../../src/HMRX/AppBundle/Controller'
        tags: ['controller.service_arguments']

    HMRX\AppBundle\Command\:
        resource: '../../src/HMRX/AppBundle/Command'
        tags: ['console.command']
```
