### DISCUSSION TITLE
Symfony serializer with GetSetMethodNormalizer returns an empty arrays instead of dates

### DISCUSSION THREAD

**Discussion by osavchenko** [symfony/symfony#42734] [Q&A] [answered]
I configured service for using `GetSetMethodNormalizer`

```yaml
services:
    Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer:
        arguments: [ '@Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface', '@serializer.name_converter.camel_case_to_snake_case' ]
        tags: [serializer.normalizer]
```

And when I call `$serializer->serialize()` I got an empty array as a value for serialized date variable.

Could you please advise how it can be fixed?

**Comment by osavchenko** [comment, marked as answer]
The problem was in the priority of normalizers. Here is a solution:

```yaml
services:
    Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer:
        arguments: ['@Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface', '@serializer.name_converter.camel_case_to_snake_case']
        tags:
            - { name: 'serializer.normalizer', priority: -1100 }
```

The new priority will put this normalizer right after all standard ones and serialization will works as expected.
