### DISCUSSION TITLE
Prefix all routes in production

### DISCUSSION THREAD

**Discussion by thedomeffm** [symfony/symfony#42817] [Q&A] [answered]
I want to prefix routes in dev/production.

e.g.

`APP_ENV=dev`
```
/api/data
/api/user
```
and
`APP_ENV=prod`
```
/api/prod/data
/api/prod/user
```
Is this possible to set a "prefix" conditional to the env?

I already tried to adjust the `/config/routes/annotations.yaml`
```
controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: '%env(resolve:URL_PREFIX)%'
    name_prefix: 'api_'
```
```
#.env
URL_PREFIX="/prod"
```
But I get following error:
`In Router.php line 178: Using "%env(resolve:URL_PREFIX)%" is not allowed in routing configuration. `

**EDIT - Solution**
`/config/routes/annotations.yaml`
```
controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: '/'
    name_prefix: 'api_'

when@prod:
    controllers:
        resource: ../../src/Controller/
        type: annotation
        prefix: '/prod'
        name_prefix: 'api_'
```
