### DISCUSSION TITLE
`doctrine/annotations` is forced to be installed

### DISCUSSION THREAD

**Discussion by karaka200** [symfony/symfony#42838] [Q&A] [answered]
I use Symfony 5.3.7 and PHP 8.0.10.

When I install doctrine orm pack with this command:

`composer require symfony/orm-pack`

`doctrine/annotations` is forced to be installed.

But I use `attributes` and do not use `annotations`.

If I delete `doctrine/annotations` package, will there be a problem with the Symfony and Doctrine?

**Comment by mbabker** [comment, marked as answer]
It depends on the packages you use.  The Doctrine ORM and Symfony framework packages support attributes.  However, some third-party packages may still require annotations and not yet support attributes.

**Reply by karaka200** [reply]
So in `config\routes\annotations.yaml` file show this:

```
controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
```

Can I change `type: annotation` to `type: attribute`?
