### DISCUSSION TITLE
HTTP/1.1 401 Unauthorized returned for "http://172.17.0.1:9200/_bulk".

### DISCUSSION THREAD

**Discussion by CedLP** [symfony/symfony#42951] [Q&A]
Hello Friends, 

I have successfuly install ELK with docker and send all login into Kiana Dashboard and Logstash.
For More security I add login and it's work fine. But now when I try to connect to my application Symfony I have a error message HTTP/1.1 401 Unauthorized returned for "http://172.17.0.1:9200/_bulk".

I know that issues is caused by login but I don't know where I can add User and Password for login to ElasticSearch into Monolog.yml or Service.yml symfony.

This is my monolog file
```
monolog:
  channels: [ 'course' , 'slack', 'sms', 'woop', 'deliverect' ]
  handlers:
    elasticsearch:
      type: service
      id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler
      level: debug
```

And my service.yml contains 
```
services:
  Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler:
    arguments:
      $endpoint: '%app.elasticsearch.host%'
```

I have try to add something like this into Monolog.yml but nothing changed

```
    elasticsearch:
      type: service
      id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler
      level: debug
      elasticsearch:
        user: 'elastic'
        password: 'testest'
        host: 'elasticsearch'
        port: '9200'
```
If someone can help me please. Thanks for your answered
