### DISCUSSION TITLE
Configuring lazy service for existing service

### DISCUSSION THREAD

**Discussion by ghost** [symfony/symfony#43027] [Q&A] [answered]
I have a service my_service. 
```yaml
my_service:
    class: App\MyService
    arguments:
        - '@service1'
        - '@service2'
    calls: # some calls
    tags: # some tags
```
Now I want to have a lazy equivalent but I don't want to duplicate the whole configuration just to add
```yaml
lazy: true
```
Is there a way to make it simple? Pseudo code:
```yaml
my_service.lazy:
  xyz: '@my_service'
  lazy: true
```

Thanks for any help.
