### DISCUSSION TITLE
Injecting a controller inside a service.

### DISCUSSION THREAD

**Discussion by Niavo** [symfony/symfony#43035] [Q&A] [answered]
Hi ,
Why i have the message "maybe you forgot to register the controller as a service or missed tagging it with the "controller.service_arguments"?" when injecting a controller into a service . (Symfony 5) .
THanks for your help .

**Comment by jfsenechal** [comment, marked as answer]
Hi

controller files are tagged automatically with this in services.yaml    

```yaml
App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
```

if you have a controller outside the directory you have to add it manually

```yaml
    App\Dir\CartController:
        tags: ['controller.service_arguments']
```
