### DISCUSSION TITLE
How to delete or invalidate doctrine result cache?

### DISCUSSION THREAD

**Discussion by fd6130** [symfony/symfony#43132] [Q&A] [answered]
Hi, how can i delete or invalidate one or many result in doctrine result cache?

```yaml
# config/framework.yaml
framework:
    cache:
       pools:
            doctrine.result_cache_pool:
                adapter: cache.app
```

```yaml
# config/doctrine.yaml
orm:
    result_cache_driver:
       type: pool
       pool: doctrine.result_cache_pool
```

```
$queryBuilder->createQueryBuilder('qb')->getQuery()->enableResultCache(3600, 'custom_id);
```
