### DISCUSSION TITLE
How to manually register abstractController in a third party bundle

### DISCUSSION THREAD

**Discussion by acrobat** [symfony/symfony#43289] [Q&A] [answered]
As [noted in the best practices](https://symfony.com/doc/current/bundles/best_practices.html#services) a third party bundle shouldn't use autowiring/autoconfigure but explicit service definitions instead. But when I register a controller extending from the AbstractController with all the necessary tags it doesn't work the same way as it would we the controller is autowired. 

By just registering the services manually the controller receives the full container where possible private services are not avialable (or specific in this case the parameter_bag service is not available). But when the controller is autorwired (`autowire:true`) the `setContainer` method receives a serviceLocator of the services defined in `getSubscribedServices`. 

How can this behaviour be used in a third party bundle with explicit configuration?

Example:

```php
namespace ExternalBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ExampleController extends AbstractController
{
//...
}
```

```yaml
ExternalBundle\Controller\ExampleController:
    calls:
        -   setContainer: [ '@service_container' ] # Without this method call a deprecation is triggered
    tags: ['controller.service_arguments', 'container.service_subscriber']
```
