### DISCUSSION TITLE
[Yaml] How to remove a inherit key?

### DISCUSSION THREAD

**Discussion by benjaminmal** [symfony/symfony#43382] [Q&A]
I am trying to override a bundle configuration of another bundle and I need to remove a key from an array. 

Note that the config (treeBuilder) is not created in `VendorBundle` but in `MasterBundle`.

Bundle config:
```yaml
# /vendor/custom_vendor/VendorBundle/src/Resources/config/config.yaml
master_bundle:
  product:
    name: 'T-Shirt'
    options:
      color: 'yellow'
      size: 'M' # I want to remove completely this key
```
You may say to do this:
```yaml
# /config/packages/master_bundle.yaml
master_bundle:
  product:
    name: 'T-Shirt'
    options:
      color: 'yellow'
      size: ~
```

But in my case the bundle throws an exception if `size` is null.  So I need the `options` array to be like this:
```php
['options' => ['color' => 'yellow']]
```

So how to completely remove this key?

### Edit ###
I tried to [prepend](https://symfony.com/doc/current/bundles/prepend_extension.html) the extension:
```php
// src/DependencyInjection/VendorExtension.php
public function prepend(ContainerBuilder $container): void
{
    $configs = $container->getExtensionConfig('master_bundle');
    $config = $this->processConfiguration(new MasterConfiguration(), $configs);
    if (isset($config['product']['options']['size']) {
        unset($config['product']['options']['size']);
    }

    $container->prependExtensionConfig('master_bundle', $config);
}
```

Or add a compiler pass:
```php
// src/DependencyInjection/Compiler/MyCompilerPass.php
public function process(ContainerBuilder $container): void
{
    $configs = $container->getExtensionConfig('master_bundle');
    foreach ($configs as $key => $config) {
        if (isset($config['product']['options']['size'])) {
            unset($config['product']['options']['size']);
            $configOverriden = $configs[$key];
        }
    }

    if (isset($configOverriden)) {
        // Don't know other way to change the config... Do you?
        $container->prependExtensionConfig('master_bundle', $configOverriden);
    }
}
```

The config keeps `size` key :(
