### DISCUSSION TITLE
How can I create two login pages for administrators and users in the firewall?

### DISCUSSION THREAD

**Discussion by karaka200** [symfony/symfony#43670] [Q&A]
Hi all

Can I create a login link in a firewall for several separate sections? For example, users use `/user-login` page and administrators use `/admin-login` page

And is the following command correct for the firewall? If it is correct, how can I give a path to each of them?

```
# config/packages/security.yaml
security:
    # ...
    firewalls:
        main:
            # ...
            admin_login:
            	# ...
            user_login:
            	# ...
```

And Is it better to use two separate firewalls for more security? (main for users and secured_area for admins)
