### DISCUSSION TITLE
Difference between _controller and controller

### DISCUSSION THREAD

**Discussion by lamasfoker** [symfony/symfony#43777] [Q&A] [answered]
Which are the differences between [_controller](https://symfony.com/doc/current/routing.html#special-parameters) and [controller](https://symfony.com/doc/current/routing.html#creating-routes-in-yaml-xml-or-php-files)?

**Comment by stof** [comment, marked as answer]
The `controller` key in route definitions is a shortcut for setting a default for the `_controller` special parameter.

Note that `controller` is not a route parameter (you won't have a `controller` key in the matched route params). It is a setting of the route definition processed by the loader (as a sibling of other settings like `defaults`, `requirement`, `path`, etc...)

**Reply by stof** [reply]
Note that the other special parameters (except `_fragment` which only makes sense for url generation) have similar configuration settings (as explained in the doc about them, btw)

**Comment by lamasfoker** [comment]
So there are no differences between:
```yaml
blog_list:
    path: /blog
    controller: App\Controller\BlogController::list
```
and:
```yaml
blog_list:
    path: /blog
    defaults:
        _controller: App\Controller\BlogController::list
```

If so, why is there 2 way to do the same things?
