### DISCUSSION TITLE
[Messenger] Redis transport consumer in Supervisor

### DISCUSSION THREAD

**Discussion by SVillette** [symfony/symfony#43902] [Q&A] [answered]
Hi everyone,
I'm using Redis Transport for messenger and Supervisor to run 2 messenger procs.

But there is something I don't get in the docs:
"If you use the Redis Transport, note that each worker needs a unique consumer name to avoid the same message being handled by multiple workers."

The docs says I shoud add this config line to Supervisor:
`environment=MESSENGER_CONSUMER_NAME=%(program_name)s_%(process_num)02d`

And in my transport config I have this :

```yaml
async_high:
    dsn: "%env(resolve:MESSENGER_TRANSPORT_DSN)%"
    options:
        queue_name: async_high
        consumer: "%env(MESSENGER_CONSUMER_NAME)%"
        delete_after_ack: true
```

But when a message is dispatched from my application, the env variable `MESSENGER_CONSUMER_NAME` is not set and I get an error. But I don't understand what value to set in .env
