### DISCUSSION TITLE
Failed to start the session because headers have already been sent by "phpunit/phpunit-9.5-0/src/Util/Printer.php"

### DISCUSSION THREAD

**Discussion by lugosium** [symfony/symfony#43950] [Q&A]
Hello,

My test env does not work with PHPUnit functional tests, i got this error:

`
{"message":"Uncaught PHP Exception RuntimeException: \"Failed to start the session because headers have already been sent by \"/var/www/html/foo/vendor/bin/.phpunit/phpunit-9.5-0/src/Util/Printer.php\" at line 104.\" at /var/www/html/foo/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 152","context":{"exception":{"class":"RuntimeException","message":"Failed to start the session because headers have already been sent by \"/var/www/html/foo/vendor/bin/.phpunit/phpunit-9.5-0/src/Util/Printer.php\" at line 104.","code":0,"file":"/var/www/html/foo/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:152"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2021-11-06T15:18:41.329807+01:00","extra":{}}
`

But my test env correctly works with Cypress. I can log in etc...

I try to log manually or using `loginUser` method, i got the same error. 
Searched in issue but don't find anything.
If i add for test env this setting:

```
session:
    handler_id: null
    storage_factory_id: session.storage.factory.mock_file
```

It's working with phpunit functional tests.

settings not working with phpunit (but working for Cypress):

```
    session:
    handler_id: my.handler.session.redis
    storage_factory_id: session.storage.factory.native
    cookie_secure: true
    cookie_samesite: strict
    cookie_httponly: true
```

I tried many things but i can't get it works with phpunit. 
And i need my redis session for some reason.

Thank you.
