### DISCUSSION TITLE
New authenticator manager: excluding endpoints from authentication

### DISCUSSION THREAD

**Discussion by NorthNick** [symfony/symfony#44008] [Q&A]
I recently migrated to the new authenticator manager for a Symfony REST API and have run into some problems trying to reproduce
the old setup.

The API has a mix of endpoints: some are open access, but most are authenticated using a token in the Authorization HTTP header. The open access endpoints should ignore any token that might happen to be present. This is fairly straightforward with the old security mechanism, using a security.yaml setup like this:
```yaml
security:
    firewalls:
        open:
            pattern: ^/(route1|route2|...|routen)
            anonymous: true
        main:
            guard:
                authenticators:
                    - App\Security\MyTokenAuthenticator
```
Because firewalls are checked in order the open access routes can be put in the `open` section and the token authenticator is never invoked for them.

Using the new authenticator, anonymous authentication no longer exists, so I have a setup like this:
```yaml
security:
    enable_authenticator_manager: true

    firewalls:
        main:
            custom_authenticators:
                - App\Security\MyNewTokenAuthenticator

    access_control:
        - { path: ^/(route1|route2|...|routen), roles: PUBLIC_ACCESS }
```
`MyNewTokenAuthenticator` has a `supports` method that checks for an Authorization HTTP header.

The problem is that firewalls seem to be checked before access_control, so any incoming request with an Authorization header is passed to `MyNewTokenAuthenticator`, even if it is for an open endpoint.
In particular this means that requests with a bad token cause authentication failure which in turn means that, if the user's token is invalidated
due to, say, their password being changed, they can no longer get to the open access /login endpoint to get a new token.

It is possible to put a pattern on the `main` firewall, but this pattern is the negation of the one in `access_control` and it feels wrong
to have to maintain two almost identical patterns.
It would also be possible to switch to a PHP security configuration file, make the `access_control` pattern a PHP string, and then
check in `MyNewTokenAuthenticator.supports` that the URL does not match that string; that would mean only maintaining one
pattern, but it feels a clumsy way of achieving something that should be quite simple.
Another option might be to have an `open` section in firewalls which reproduces that section from the old mechanism, but then
I'd just be recreating anonymous authentication, which surely goes against the intentions of the Symfony designers.

Does anyone have a simple configuration that achieves what I want? Thanks in advance for your help.
