### DISCUSSION TITLE
Blocking users unauthenticated by my firewall

### DISCUSSION THREAD

**Discussion by TristanPouliquen** [symfony/symfony#44025] [Q&A] [answered]
Hi,

I'm trying to update my authenticators from deprecated Guards to the new Authenticators. 

Because of legacy code & various authentication methods, I actually have 4 different authenticators, one of which is the LexikJWTAuthenticationBundle Authenticator.

My `security.yaml` is therefore following this format:
```yaml
        // ...
        api_token:
            request_matcher: App\Security\RequestMatcher\ApiKeyAuthenticationRequestMatcher
            stateless: true
            provider: 'api_keys'
            custom_authenticators:
                    - App\Security\Authenticator\ApiKeyAuthenticator
        api:
            pattern: ^/graphql|^/api/v1/(?!tokens)
            stateless: true
            provider: 'users'
            entry_point: App\Security\Authenticator\ApiAuthenticationEntryPoint
            jwt:
                authenticator: app.custom_jwt_authenticator
            custom_authenticators:
                     - App\Security\Authenticator\LegacyJwtTokenAuthenticator
                     - App\Security\Authenticator\OAuthAuthenticator
```

If I try logging in, all is good & I am correctly authenticated with the right user.

However, I've noticed that if I request API urls without logging in, I either can access them if no specific roles are needed or I get exceptions in my voters because the `TokenInterface` passed through is obviously null.

This is a regression from my previous configuration using GuardAuthenticators, where if I was not authenticated I was correctly blocked by a HTTP_UNAUTHORIZED error.

The `VoterInterface` doesn't specify a nullable `TokenInterface` on the `vote` method, which means for me that a token should always be present when reaching the authorization layer.

How can I enforce that if no authenticators support the given request for a firewall my users get a HTTP_UNAUTHORIZED exception?

Should the `entry_point` configuration allow for this use case? Mine returns a `JsonResponse($data, Response::HTTP_UNAUTHORIZED)` already but from what I've read, this method is called if there is an authentication failure (which I don't have as no Authenticators are actually called).

Is there no other way than implementing access controls? If so, I've read that behind the screen, these generate a `RequestMatcher` object, but it seems that we can only configure static properties (pattern, port, ip...) and not pass a `RequestMatcherInterface` service directly as we can do in a firewall configuration. Is it true? normal? 

My firewalls already are, or will soon be, relying on their dedicated RequestMatchers, that are more complex than just a regex, and I don't see how I can implement the same rules in the access controls then (eg: if I tag a URL as public & excluded from a given RequestMatcher, I don't want to have to define it explicitly also in my `security.yaml` file, as this would be highly prone to human error).

Thanks in advance for any answers/hints/advice you can give me on this topic :-)
Cheers!
