### DISCUSSION TITLE
Custom cache adapter gives "Service "http.cache": The argument "0" doesn't exist."

### DISCUSSION THREAD

**Discussion by pbowyer** [symfony/symfony#44132] [Q&A]
I wanted to create a persistent cache to hold the results of HTTP requests, so I'm not hitting remote endpoints after the first time. I created a data directory, and added to `services.yaml`:
```yaml
services:
    app.http_cache_adapter:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            $namespace: 'http_cache'
            $defaultLifetime: 0
            $directory: '%kernel.project_dir%/data/cache_persistent'
```

To `cache.yaml` I added:
```yaml
framework:
    cache:
        pools:
            http.cache:
                adapter: app.http_cache_adapter
```

When I try to run, I get the error
> Service "http.cache": The argument "0" doesn't exist.

Looking at the Symfony exception it references the dependency injection:
```
Definition->replaceArgument(0, 'ttpOG7kFcI')
in D:\projects\project\vendor\symfony\dependency-injection\Compiler\ResolveChildDefinitionsPass.php (line 168)
```
I've tried a bunch of variations but none have changed the error. What have I got wrong with the cache pool definition?

FWIW the service itself works great; if I do
```yaml
services:
    _defaults:
        bind:
            $httpCache: '@app.http_cache_adapter'
```
comment out the `cache.yaml` changes and inject `CacheInterface $httpCache` into my code it works perfectly.
