### DISCUSSION TITLE
Has security authentication order changed?

### DISCUSSION THREAD

**Discussion by darthf1** [symfony/symfony#44349] [Q&A] [answered]
Hi!

I'm trying to update from `5.3` to `5.4`.

I have my `security.yaml` defined as:
```yaml
main:
  pattern: ^/
  stateless: true
  user_checker: ...
  json_login:
    check_path: /v1/login
    success_handler: ...
    failure_handler: ...
  login_link:
    check_route: api_login_check
    lifetime: 2630000
    signature_properties: ['id', 'userIdentifier']
    success_handler: ...
    failure_handler: ...
  login_throttling:
    limiter: app.login_rate_limiter
  jwt: ~
```

On 5.4, when I authenticate via `/v1/login`: 
```php
$client->request('POST', '/v1/login', [
    'json' => [
        'username' => $identifier,
        'password' => $password,
    ],
]);
```
I get:
```json
{"code":401,"message":"Invalid or expired login link."}
```

On `5.3` I get:
```json
{"code":200,"message":"null"}
```
 It looks like `json_login` takes precedence over `login_link`. 

I wouldn't expect anything to change between `5.3` and `5.4` and cant find anything in the changelog related.
