### DISCUSSION TITLE
How to render the default debug-error page from symfony when overriding the error controller.

### DISCUSSION THREAD

**Discussion by VincentLanglet** [symfony/symfony#44389] [Q&A] [answered]
In Symfony 4, we used the `twig.exception_controller` config to provide on own error controller with this logic:

```
    public function showAction(Request $request, FlattenException $exception, ?DebugLoggerInterface $logger = null)
    {
        $code = $exception->getStatusCode();

        if ($this->debug || $someSpecialCasesWeWantTheExceptionDisplayedInProduction)
        {
            $currentContent = $this->getAndCleanOutputBuffering((int) $request->headers->get('X-Php-Ob-Level', '-1'));

            return $this->render('@Twig/Exception/exception_full.html.twig', [
                'status_code'    => $code,
                'status_text'    => Response::$statusTexts[$code] ?? '',
                'exception'      => $exception,
                'logger'         => $logger,
                'currentContent' => $currentContent,
            ]);
        }

        return $this->renderACustomErrorPageWithTonsOfLogicExecuted;
    }
```

When bumping to Symfony 5 the `@Twig/Exception/exception_full.html.twig` was removed in favor of a `html.php` view in the ErrorHandler component. What I basically would like to do is

```
    public function showAction(Request $request, FlattenException $exception, ?DebugLoggerInterface $logger = null)
    {
        $code = $exception->getStatusCode();

        if ($this->debug || $someSpecialCasesWeWantTheExceptionDisplayedInProduction)
        {
            $reflection = new \ReflectionClass(HtmlErrorRenderer::class);
            $method     = $reflection->getMethod('renderException');
            $method->setAccessible(true);

            return new Response($method->invokeArgs(new HtmlErrorRenderer(true), [$exception]));
        }

        return $this->renderACustomErrorPageWithTonsOfLogicExecuted;
    }
```

But I don't think using a reflection class to use a private method can be considered as a good solution.
The issue with `render` is that it expects a `Throwable` and I already have the (transformed Throwable) FlattenException.

If a default ErrorController was provided, I could basically call
```
    public function showAction(Request $request, FlattenException $exception, ?DebugLoggerInterface $logger = null)
    {
        $code = $exception->getStatusCode();

        if ($this->debug || $someSpecialCasesWeWantTheExceptionDisplayedInProduction)
        {
            return parent::showAction($request, $exception, $logger);
        }

        return $this->renderACustomErrorPageWithTonsOfLogicExecuted;
    }
```

Is there any solution to do what I'm looking for to do ?

**Comment by yceruto** [comment, marked as answer]
Since Symfony 4.4 there is a new rendering layer you can use instead (ErrorRenderer):
 * The error occurs and `KernelEvents::EXCEPTION` was dispatched
 * ErrorListener catches that event and handles a new subrequest using the `framework.error_controller` configured
 * ErrorController takes care of preview and converting the throwable error into a Response using the proper error renderer
 * ErrorRenderer converts the throwable error into a FlattenException with the string representation of this error (HTML, JSON, etc. depending on the request format/content negociation)

If you want to render a custom error page and you're using Twig, decorating `TwigErrorRenderer` service is the simplest solution to add custom logic before rendering the error template and/or passing more variables. If Twig is not a dependency on your app, decorating `HtmlErrorRenderer` service would be the simplest one instead. For all cases, injecting the inner decorated service and falling back to it in debug-mode is the proper way to keep displaying the debug exception page.

To display the exception page on production mode, you can modify the debug condition by injecting a new callable as `$debug` argument in the ErrorRenderer service definition:
```php
    // see TwigErrorRenderer
    public static function isDebug(RequestStack $requestStack, bool $debug): \Closure
    {
        return static function () use ($requestStack, $debug): bool {
            if (!$request = $requestStack->getCurrentRequest()) {
                return $debug;
            }

            return ($debug && $request->attributes->getBoolean('showException', true)) 
                || $someSpecialCasesWeWantTheExceptionDisplayedInProduction;
        };
    }
```
You shouldn't have to deal with `ErrorController` unless you want a new error rendering system.

**Reply by VincentLanglet** [reply]
Thanks @yceruto.

> ```
>     // see TwigErrorRenderer
>     public static function isDebug(RequestStack $requestStack, bool $debug): \Closure
>     {
>         return static function () use ($requestStack, $debug): bool {
>             if (!$request = $requestStack->getCurrentRequest()) {
>                 return $debug;
>             }
> 
>             return ($debug && $request->attributes->getBoolean('showException', true)) 
>                 || $someSpecialCasesWeWantTheExceptionDisplayedInProduction;
>         };
>     }
> ```

How do I say symfony to use my own `isDebug` method ?
I've tried to follow https://symfony.com/doc/current/service_container/factories.html#invokable-factories
``` 
    twig.error_renderer.html:
        class: Symfony\Bridge\Twig\ErrorRenderer\TwigErrorRenderer
        arguments:
            $debug: '@App\Front\Factory\ErrorRendererDebugFactory' #invokable factory
```
But it doesn't change anything

**Reply by yceruto** [reply]
You might need to do the same for `$debug` argument on `error_handler.error_renderer.html` service and make sure the services and the new factory have all required dependencies.

Here is an example:
```yaml
    error_handler.error_renderer.html:
        class: Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer
        arguments:
            - !service
                factory: [App\DebugFactory, 'isDebug']
                arguments: ['@request_stack', '%kernel.debug%']
            - '%kernel.charset%'
            - '@?debug.file_link_formatter'
            - '%kernel.project_dir%'
            - !service
                factory: [Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer, 'getAndCleanOutputBuffer']
                arguments: ['@request_stack']
            - '@?logger'

    twig.error_renderer.html:
        class: Symfony\Bridge\Twig\ErrorRenderer\TwigErrorRenderer
        arguments:
            - '@twig'
            - '@error_renderer.html'
            - !service
                factory: [App\DebugFactory, 'isDebug']
                arguments: ['@request_stack', '%kernel.debug%']
```
