### DISCUSSION TITLE
Clearing doctrine query cache from bin/console not working

### DISCUSSION THREAD

**Discussion by fd6130** [symfony/symfony#44468] [Q&A]
After I modify an entity(remove an attribute), the DQL from query builder keep telling me `An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'p3_.user_id' in 'field list'`.

I recall that I'm using query cache in my Symfony config, so i try to clear the cache using `php bin/console doctrine:cache:clear-query` but it doesn't work at all. Then I have to go and comment out the line of my query cache config in `doctrine.yaml` and no more error from the query builder.

```yaml
#doctrine.yaml
doctrine:
    orm:
       
        # query_cache_driver: 
        #     type: pool
        #     pool: doctrine.query_cache_pool
```

```yaml
#cache.yaml
framework:
    cache:
        pools:
            doctrine.query_cache_pool:
                adapter: cache.app
```

Any idea why? Thanks.
