### DISCUSSION TITLE
We are having issues with legacy sessions and CSRF token

### DISCUSSION THREAD

**Discussion by marcmorente** [symfony/symfony#44493] [Q&A]
We are using Symfony 5.4 and we are using a Front Controller with Legacy Bridge, we are migrating an old legacy code base using sessions a lot, is like another DB, so during the migration we need to deal with some variables set from the legacy code.
We are having issues with legacy sessions and CSRF token in forms as well as flash messages.
We set session.storage.factory.php_bridge in config/packages/framework.yaml  as the documentation said.
```
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: ~
    http_method_override: false

    http_client:
        max_host_connections: 10
        default_options:
            http_version: '2.0'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        storage_factory_id: session.storage.factory.php_bridge
        handler_id: ~
```
And instantiating the Session class as the documentation said, Integrating with Legacy Sessions.
Now with these settings, forms with CSRF protection enabled are not working. It says that the CSRF token is invalid. I checked the request and the _token is send on form submit. I found out that the token submitted with the form, and the token stored in session mismatch. The token in session is regenerated on every request and it does not match with the one I send with form information.
