### DISCUSSION TITLE
Unset yaml configuration when@dev

### DISCUSSION THREAD

**Discussion by SimonVanacco** [symfony/symfony#44845] [Q&A] [answered]
Hi ! 

I maintain a project that has a yaml configuration as follows: 
```
monolog:
    handlers:
        my_handler:
            type: service
            id: monolog.gelf_handler
            level: error
            
``` 
I would like to **disable the my_handler handler when in dev or test environment**. I have tried to following configuration but it does not work :

``` 
when@dev:
    monolog:
        handlers:
            my_handler: null

when@test:
    monolog:
        handlers:
            my_handler: null
``` 

I cannot enable the handler with the when@prod shorthand as i need to be compatible with custom production environments (where the env name is different than "prod")

Have you any idea how i could achieve this ? It seems impossible to override this handler. 
Thanks !
