### DISCUSSION TITLE
[Messenger][Redis] Empty message when using SERIALIZER_JSON

### DISCUSSION THREAD

**Discussion by jeanatpi** [symfony/symfony#45014] [Q&A]
Hi,

First message here so apologize if I'm not following some rules.

Trying to setup Redis transport for messenger and I'm wondering how I can have JSON serialized data in Redis.

Default serializer (SERIALIZER_PHP) is working well but as soon I start using SERIALIZER_JSON I end with an empty JSON string in Redis:
```
{message: ""}
```

My conf:

```
redis_high_priority:
  dsn: '%env(MESSENGER_TRANSPORT_DSN_HIGH_PRIORITY)%'
  options:
     auto_setup: true
     delete_after_ack: true
     serializer: !php/const Redis::SERIALIZER_JSON
     #serializer: 1 # SERIALIZER_JSON = 4 || SERIALIZER_PHP = 1
```
with 

`MESSENGER_TRANSPORT_DSN_HIGH_PRIORITY=redis://localhost:6379/high_priority/sds`

My Message:
```
class MyMessage{
   public $id;
   public function __construct($id) { $this->id = $id;}
}
```

Versions:
- Symfony: 5.4
- Redis: 6

Any idea?

**Comment by ghost** [comment]
The `serializer` option in your example is not the same as `serializer` option for messenger transport. The first sets how the final payload sent from symfony messenger to Redis will be serialized when storing inside Redis instance. The latter is the option that you are interested in and it is set one level higher:
```yml
redis_high_priority:
  dsn: '%env(MESSENGER_TRANSPORT_DSN_HIGH_PRIORITY)%'
  options: # here you set a connection options. This is the same as if you set options inside dsn string
  serializer: # this is the serializer you are interested in, e.g. a default one messenger.transport.symfony_serializer
             # see more on https://symfony.com/doc/current/messenger.html#serializing-messages

```

**Reply by ghost** [reply]
After thinking about it further, my first comment is not a solution for your problem actually.
You end up with a "message" key inside Redis which equals to an empty string but should be a json with two keys: "body" and "headers" (see https://github.com/symfony/redis-messenger/blob/b4bf15c6b735eeb52fbbe3c402aa4428d83f9794/Transport/Connection.php#L486) where body is a serialized message from your application. You didn't include the full messenger.yaml config so I don't know what kind of serializer the transport uses but regardless of that it should be some string value.

Please inspect what happens with the message inside RedisSender.php and Connection.php from symfony/redis-messenger after dispatching MyMessage message.

**Reply by jeanatpi** [reply]
@javaDeveloperKid first thank you for your reply!

To complete my question here is the rest of messenger.yaml configuration:

```
framework:
    messenger:
        reset_on_message: true
        failure_transport: failed
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
```

Also tried yesterday to debug the message in RedisSender.php and if was ok.
```
$encodedMessage['body'] contains a json string of MyMessage
$encodedMessage['headers'] contains a corrrect json string.
```

In Connection.php $message contains:
```
{"body":"{\"id\":\"144\",\"retryCount\":null,\"redeliveredAt\":null}","headers":{"type":"App\\Message\\MyMessage","X-Message-Stamp-Symfony\\Component\\Messenger\\Stamp\\BusNameStamp":"[{\"busName\":
\"messenger.bus.default\"}]","Content-Type":"application\/json"}}
```

Then there is the xadd method:
```$added = $this->connection->xadd($this->stream, '*', ['message' => $message]);```

Which results in this empty {message:""} in redis.


Also I want to try this approach on a complete "clean" SF project to see if it works well with "default" configuration.
