### DISCUSSION TITLE
Remember me dont work

### DISCUSSION THREAD

**Discussion by amigian74** [symfony/symfony#45348] [Q&A] [answered]
Hi,
I've a page with form login and "remember me" functionality enabled. Unfortunately the remember me" wont work.

The security panel doesn't show any authenticators. Interestingly after closing the browser and trying to get on the page again, the security panel shows the correct authenticated user, but redirects always to the login page. 

Can anybody help?

Here part of my security.yml

```
security:
    enable_authenticator_manager: true
    role_hierarchy:
        ROLE_SUPPORT: ROLE_USER
        ROLE_ADMIN: [ROLE_SUPPORT, ROLE_ALLOWED_TO_SWITCH]

    password_hashers:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
            logout:
                path:   /logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
         
    access_control:
        - { path: ^/public, roles: PUBLIC_ACCESS }
        - { path: ^/others, roles: IS_AUTHENTICATED_FULLY  }
```

Thx in advance

**UPDATE**

With lazy: true the security panel now shows authenticators:

<html>
<body>

"Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator" |   | 0.00 ms | (none)
-- | -- | -- | --
"Symfony\Component\Security\Http\Authenticator\RememberMeAuthenticator" |   | 0.00 ms | (none)

</body>
