### DISCUSSION TITLE
PdoSessionHandler lifetime not working

### DISCUSSION THREAD

**Discussion by vasilvestre** [symfony/symfony#45419] [Q&A] [answered]
I'm using the Pdo session handler, thanks to [the documentation](https://symfony.com/doc/current/session/database.html#store-sessions-in-a-relational-database-mariadb-mysql-postgresql) it was made easy.

However, sessions expire quickly despite the week I've set ([see here](https://github.com/artandor/multistream-tools/blob/main/config/packages/framework.yaml#L12)), [I've declared the service too ](https://github.com/artandor/multistream-tools/blob/main/config/services.yaml#L27) so I think I've done what should be done.

I think [the statement ](https://symfony.com/doc/current/components/http_foundation/session_configuration.html#configuring-garbage-collection) in documentation  `However, some operating systems (e.g. Debian) do their own session handling and set the session.gc_probability directive to 0 to stop PHP doing garbage collection. That's why Symfony now overwrites this value to 1.` may be wrong or not work in this specific case.

**Comment by chyshyya** [comment, marked as answer]
Works like expected in our projects setting with `gc_maxlifetime: 172800`
 `config/packages/framework.yaml`
```
framework:
    ...
    session:
        enabled: true
        handler_id: 'Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler'
        gc_maxlifetime: 172800
    ...
```
