### DISCUSSION TITLE
Binding global services guidelines

### DISCUSSION THREAD

**Discussion by kardi31** [symfony/symfony#45467] [Q&A]
Hi,
I was looking for some guidelines in terms of binding services. I attach a couple of examples below. 

Example 1: 
```
services:
    _defaults:
        bind:
            $paymentRepository: '@thirdparty_my_payment_repository'

    App\PaymentProvider: ~
    App\PaymentResolver: ~
    App\PaymentHandler: ~
```

Example 2: 
```
services:
    App\PaymentProvider:
        arguments:
            $paymentRepository: '@thirdparty_my_payment_repository'

    App\PaymentResolver:
        arguments:
            $paymentRepository: '@thirdparty_my_payment_repository'

    App\PaymentHandler:
        arguments:
            $paymentRepository: '@thirdparty_my_payment_repository'
```

In this example we have a legacy 3rdParty service definition called `thirdparty_my_payment_repository` which is not autowired and three classes having argument `$paymentRepository` in their constructors.
Are there any guidelines which solution should be used? We are running a large application and some minor tests showcased there might be significant performance difference between both solutions but I failed to find any written confirmation
