### DISCUSSION TITLE
HTTP basic authentication with LDAP in Symfony 5.4

### DISCUSSION THREAD

**Discussion by kralge** [symfony/symfony#45493] [Q&A] [answered]
Hi, I am having a hard time setting up HTTP basic authentication with LDAP. I read through the documentation and I just cannot see what is wrong. The result in the log:
```
[2022-02-20T19:48:56.261160+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2022-02-20T19:48:56.261336+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Ldap\\Security\\LdapAuthenticator"} []
[2022-02-20T19:48:56.261443+01:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Ldap\\Security\\LdapAuthenticator"} []
```
And the LuckyController page loads fine without authentication. The browser first tries to load the page without authentication, so the authenticator not supporting the request may be fine, but it should respond to the browser so it starts initiating the authentication and it never happens.

I have spent a full day trying to check the source code, but I am lost. Any idea is appreciated.

EDIT: just found that by setting `enable_authenticator_manager: false` the authentication starts working. Still, why doesn't it work when the manager is enabled? What do I need to change?

What I did:

1. `# symfony new huba_teszt --version=5.4 --webapp`
2. Create `src/Controller/LuckyController.php` and modify `config/routes.yaml` as specified in the documentation.
3. `# composer require symfony/ldap`
4. `# php bin/console make:user`
5. Modified `config/services.yaml` and `config/packages/security.yaml` as the followings:

config/services.yaml:
```
parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            -   host: localhost
                port: 389
                encryption: none
                options:
                    protocol_version: 3
                    referrals: false
```
config/packages/security.yaml:
```
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            id: App\Security\UserProvider
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: dc=mydomain,dc=hu
                search_dn: null
                search_password: null
                default_roles: ROLE_USER
                uid_key: uid
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
             provider: my_ldap
             stateless: true
             http_basic_ldap:
                 realm: Otthon Web
                 service: Symfony\Component\Ldap\Ldap
                 dn_string: 'uid={username},ou=People,dc=mydomain,dc=hu'
    access_control:

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
```
