### DISCUSSION TITLE
Get value set in cache from another application

### DISCUSSION THREAD

**Discussion by bmovi** [symfony/symfony#45514] [Q&A] [answered]
Hello, I am trying to get a value in Memcached (but I think it's the same with another cache provider).
This value is set from another application.

I created a cache service with no namespace:
```yaml
framework:
    cache:
        app: cache.adapter.memcached
        system: cache.adapter.memcached
        default_memcached_provider: '%env(MEMCACHED_DSN)%'

        pools:
            app.memcached.shared:
                adapter: app.cache.shared.memcached

services:
    app.cache.shared.memcached:
        parent: 'cache.adapter.memcached'
        tags:
            - { name: 'cache.pool', namespace: '' }
```

In my class, I autowire my cache pool:
```php
    public function __construct(private CacheItemPoolInterface $appMemcachedShared)
    {
    }
```

And I'm trying to get the value:
```
$value = $this->appMemcachedShared->getItem('my_key');
```
I always get null.

I already checked that the key did exist in memcached via telnet.

When I try this command, I got my value:
```php
php -r '$c = new Memcached(); $c->addServer("localhost", 11211); var_dump( $c->get("my_key") );'
```

Does Symfony automatically prefix all keys?
If I want to retrieve a key already set elsewhere, do I have to create a Memcached instance myself?

Thank you for your help ! 🙏
