### DISCUSSION TITLE
Localized routes and fallback path

### DISCUSSION THREAD

**Discussion by devnix** [symfony/symfony#45562] [Q&A]
Hi! Quick question about localized routes.

Having this route defined as an example:
```yaml
pro_license_sporting_events_list:
    controller: App\Controller\Legacy\ProLicense\SportEventsListController
    path:
        en: /sporting-events-list/{page<\d+>?1}
        es: /listado-eventos-deportivos/{page<\d+>?1}
        it: /lista-eventi-sportivi/{page<\d+>?1}
    defaults:
        _locale: 'en'
```

Now let's that I have dozens and dozens of routes like these, and that I add a new language to my application:  now if I call to `$router->generate('pro_license_sporting_events_list')` with a new locale loaded in the request, the router will throw an `Unable to generate a URL for the named route "pro_license_sporting_events_list" as such route does not exist.` exception.

While I totally understand this behavior, it surprises me to not find any resource neither in the Symfony documentation, nor anywhere on the internet.

Maybe I'm missing something and there is a builtin way to generate a route with the default locale suggested for that route? Or should I build my own service, catching this kind of exceptions and retrying the route generation with a default locale by myself?

PD: I've just tried to decorate the router service to add some kind of fallback behavior to values configured in `translations.yaml`, but  it would take an important refactoring because I already have a lot of services receiving with the `Router` type.

**Comment by chyshyya** [comment]
remove 
```yaml
    defaults:
        _locale: 'en'
```
and from docs:
```yaml
A common requirement for internationalized applications is to prefix all routes with a locale. This can be done by defining a different prefix for each locale (and setting an empty prefix for your default locale if you prefer it):

 Copy
# config/routes/annotations.yaml
controllers:
    resource: '../../src/Controller/'
    type: annotation
    prefix:
        en: '' # don't prefix URLs for English, the default locale
        nl: '/nl'
```
or with hosts for locales.
Try that.
