### DISCUSSION TITLE
Can i move my entities to other folder instead of src/Entity?

### DISCUSSION THREAD

**Discussion by fd6130** [symfony/symfony#45632] [Q&A]
Hi, I tries to move my entities from src/Entity to src/Domain/Entity and I have updated my doctrine.yaml as well:

```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'App\Domain\Entity'
                alias: App
```

However, when i try to `php bin/console cache:clear` its just prompt me this:

> // Clearing the cache for the dev environment with debug true   

And it stuck at there until my ram exhausted.  Any solution for this case? Thanks.

_**Update:**_ It seems the above issue is cause by entity event subscriber, not sure why.  After removing those entity event subscriber, my command works again.
