### DISCUSSION TITLE
"message": "Unable to find key \"username\" in the token payload." => symfony6 and postman

### DISCUSSION THREAD

**Discussion by Alfonsogreat** [symfony/symfony#45706] [Q&A] [answered]
hello everyone, in my case i have just generate a token , by sending request to 127.0.0.1:8000/api/login with credentials , username (which is email) and password , all work fine for now , the token has been generated successfully , but after i want to get access to 127.0.0.1:8000/api , i have copied the token to put it in Bearer Token , and after that i send the request 127.0.0.1:8000/api/ , but i get this error in Postman
 **{
    "code": 401,
    "message": "Unable to find key \"username\" in the token payload."
}**

>ps : i am using symfony 6

config/packages/lexik_jwt_authentication.yaml file
```
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl : 36000

```
config/packages/security.yaml file

```
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

```

routes.yaml file 

```
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login
```

> any help please i will be grateful
