### DISCUSSION TITLE
Problem with custom authenticator and PUBLIC_ACCESS route exclusion

### DISCUSSION THREAD

**Discussion by costeaalex** [symfony/symfony#45842] [Q&A]
Hey,

the problem is as follows:

security.yaml:

```
security:
  enable_authenticator_manager: true
  firewalls:
    main:
      provider: keycloak
      custom_authenticators:
        - App\Security\CustomAuthenticator
  access_control:
    - { path: ^/app, roles: PUBLIC_ACCESS }
```

The issue is that whenever I acces a route like /app/{whatever} I am not getting that page loaded but the CustomAuthenticator engages and I am taken to the unauthenticated flow. As I understand it the access_control directive for my ^/app path should punch through the firewall and actually expose publicly to unauthenticated users these routes, no?

I am on Symfony 5.4
