### DISCUSSION TITLE
symfony5.4 framework.error_controller It works fine in dev mode but not in prod mode. Why?

### DISCUSSION THREAD

**Discussion by CJayHe** [symfony/symfony#45843] [Q&A]
symfony5.4 framework.error_controller It works fine in dev mode but not in prod mode. Why?
```yaml
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    error_controller: App\Controller\Home\DocController::page

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```
