### DISCUSSION TITLE
Disable middleware for specific command

### DISCUSSION THREAD

**Discussion by grztofdev** [symfony/symfony#45954] [Q&A] [answered]
My `config/packages/messenger.yaml` looks like: 
```yaml
framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware: 'Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware'
            query.bus: ~
        transports:
             async: 'doctrine://default'
        routing:
            App\Application\Command\AsynchronousCommand: async

```

I have one command that is fetching a lot of data called for instance `FetchDataFromApi`.
I am sending it to `command.bus`.
I need to remove middleware `DoctrineTransactionMiddleware` for that specific command, because I need to manually do `->flush()`.

How can I do this?
