### DISCUSSION TITLE
How to handle migrations with multiple entity managers in DoctrineMigrationsBundle 3

### DISCUSSION THREAD

**Discussion by mattsbennett** [symfony/symfony#45961] [Q&A] [answered]
On doctrine/doctrine-migrations-bundle 2.* this was relatively simple - use the --em option (and use ContainerAwareInterface to skip any migrations from a different em/connection).

Now (on doctrine/doctrine-migrations-bundle 3.2.2), it seems this approach is no longer feasible (deprecation of ContainerAware).

There is a lot of conflicting information on how to set this up, some suggesting it should "just work" (Symfony Docs) and other describing workarounds (Issue):

https://symfony.com/doc/current/doctrine/multiple_entity_managers.html https://github.com/doctrine/DoctrineMigrationsBundle/issues/38

How does one configure this as in doctrine/doctrine-migrations-bundle 2 to apply migrations only to their matching entity/db?

**Comment by mattsbennett** [comment, marked as answer]
Reposting my self-answer from a SO post:

Also mentioned in my question, there is an open issue on the `DoctrineMigrationsBundle` from 2012 describing the problem of dealing with migrations when using multiple entity managers: https://github.com/doctrine/DoctrineMigrationsBundle/issues/38. It seems there are several options for workarounds to this issue as described there, we just needed to dig and try each of them to find the best one for our situation.

## Container Aware Migrations

On Symfony 3, we were using the `ContainerAwareInterface` approach. Described in the above issue:

> Currently this can be achieved by using Container Aware Migrations. If one can have the service container injected, he can obtain an instance of some entity manager and its connection.

This is no longer really a valid solution when moving to Symfony 4 however, due to `ContainerAware` classes being deprecated in favor of dependency injection.

## Pass configuration directly

Another approach mentioned in the github issue above. The idea here is to have a separate configuration file for each entity manager like the following:

```
# config/packages/migrations/base.yaml
em: default
transactional: false
migrations_paths:
    Hyra\Migrations\Base: src/Migrations/Base
table_storage:
    table_name: migration_versions
```

This is passed directly to the command, along with the entity manager like this: `bin/console doctrine:migrations:migrate --em default --configuration config/packages/migrations/base.yaml`. These separate config files replace the single `config/packages/doctrine_migrations.yaml` configuration file.

This was also not viable for us, as we still needed to inject services into our migrations using the `services` configuration option of `DoctrineMigrationsBundle`, and `--configuration` only passes configuration options directly through to `doctrine/migrations`, which doesn't support the `services` configuration option.

Initially on `DoctrineMigrationsBundle` 3.0, this approach was complicated by the fact that the `--em` and `--conn` options were dropped completely, so it was also necessary to create a wrapper on top of the `DoctrineMigrationsBundle` commands to re-implement these options ([described in more detail here](https://jmsche.fr/en/blog/upgrade-doctrine-migrations-from-2-x-to-3-0)). This is no longer necessary on `DoctrineMigrationsBundle` 3.1+ (which restored these options).

## Use `DoctrineMigrationsMultipleDatabaseBundle`

Also mentioned in the github issue thread, [this bundle](https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle) implements what we needed exactly (and ended up using) - per-entity configuration for `DoctrineMigrationsBundle`, so we can also include our `services` config for migration dependency injection. Initially I misconfigured this - it's important that the base `doctrine_migrations.yaml` config only includes config for the default entity manager. Sample working config provided by the package author (version 0.3.3):

```
# doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: mariadb-10.1.26
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string
            geonames:
                url: '%env(resolve:GEONAMES_DATABASE_URL)%'
                server_version: mariadb-10.1.26
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/App/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            geonames:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: geonames
                mappings:
                    Geonames:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/App/Entity/Geonames'
                        prefix: 'App\Entity\Geonames'
                        alias: Geonames
```
```
# doctrine_migrations.yaml
doctrine_migrations:
    em: default
    migrations_paths:
        DoctrineMigrations: '%kernel.project_dir%/migrations/Main'
```
```
# doctrine_migrations_multiple_database.yaml
doctrine_migrations_multiple_database:
    entity_managers:
        default:
            migrations_paths:
                DoctrineMigrations\Main: '%kernel.project_dir%/migrations/Main'
        geonames:
            migrations_paths:
                DoctrineMigrations\Geonames: '%kernel.project_dir%/migrations/Geonames'
```

**Reply by Vegas97** [reply]
Man you are the best! Super explanatory! tnx

**Reply by jdevinemt** [reply]
Thanks for the detailed self-answer. Looks like the bundle you are using just got archived recently though :( Not that it still can't be used, but I don't tend to use archived packages unless I know exactly how they are working so I can understand the potential issues that may arise as it's dependencies get updated.

[This option in the DoctrineMigrationBundle docs](https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html#migration-dependencies) may be a more sustainable option. It is more manual setup, but is less likely to break when upgrading dependencies. In the example provided they are injecting the whole container based on the existence of the `ContainerAwareInterface` interface. But you could just as easily create your own interface(s) for injecting more specific dependencies. Or instead of using interfaces, you could use a custom migration class that extends doctrine's `AbstractMigration` class if you have dependencies you know you are going to need in most of your migrations.

It's a shame that multi-database setups are such a pain in doctrine. Of course if I was starting a project from scratch it wouldn't be an issue. But it is such a big hurdle when trying to move  brownfield projects to use symfony/doctrine.

**Reply by mattsbennett** [reply]
We noticed the archiving as well when upgrading to Symfony 6 recently :-( I'm not sure I follow the dependency injection approach. We've forked it for now, but are planning to look into removing it via the original package author's suggestions here: https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle/issues/24#issuecomment-2007937431 before upgrading Symfony again.

**Reply by jdevinemt** [reply]
@mattsbennett I misinterpreted your original issue. I think the `DoctrineMigrationsMultipleDatabaseBundle` author's comment about using a makefile is probably the easiest solution if you can get it to work for your project.

Since I had already started writing out this explanation, I'm just going to leave it here in case anyone else has a similar issue to me.

The issue I am trying to resolve is somewhat related, but not quite the same. I'm working on a brownfield project that has multiple databases, which seem to have been created simply for the sake of namespacing 🤷 The goal is to combine these into a single database eventually, but that is no small feat. Ideally we could move tables into the new 'main' database via migrations so we can just deploy without fiddling with production databases manually. But there are cases where we might need to only run a sql query during a migration if a certain database or table exists that is not in the 'main' database. The schema and schema manager doctrine provides only has visibility for tables in a single database (for whichever database the connection the migrations use is associated to). You can check for the existence of another database via the `Schema`'s `listDatabases()`, but not tables in another database. Sooo.. we'd have to somehow get at the connection for a second database to see if a table exists in that database.

Here's an example:

Let's assume we need to be able to use another connection for a different database. In this example we will assume it is some legacy database that you are slowly migrating into a new main database. Instead of injecting the whole container based on the `ContainerAwareInterface` interface, create your own interface for the connection you need:

```php
namespace App\Migrations;

use ...;

interface LegacyConnectionAwareInterface
{
    public function setLegacyConnection(Connection $legacyConnection): void;
}
```
Set up your custom migration factory service:

```php
namespace App\Migrations\Factory;

use ...;

class MigrationFactoryDecorator implements MigrationFactory
{
    private MigrationFactory $migrationFactory;
    private Connection $legacyConnection;

    public function __construct(MigrationFactory $migrationFactory, Connection $legacyConnection)
    {
        $this->migrationFactory = $migrationFactory;
        $this->legacyConnection = $legacyConnection;
    }

    public function createVersion(string $migrationClassName): AbstractMigration
    {
        $instance = $this->migrationFactory->createVersion($migrationClassName);

        if ($instance instanceof LegacyConnectionAwareInterface) {
            $instance->setLegacyConnection($this->legacyConnection);
        }

        return $instance;
    }
}
```
Wire it up:

```yaml
# config/packages/doctrine_migrations.yaml
doctrine_migrations:
    services:
         'Doctrine\Migrations\Version\MigrationFactory': 'App\Migrations\Factory\MigrationFactoryDecorator'

# config/services.yaml
services:
    App\Migrations\Factory\MigrationFactoryDecorator:
        decorates: 'doctrine.migrations.migrations_factory'
        arguments: ['@.inner', '@doctrine.dbal.legacy_connection']
```

Create your migration:

```php
namespace DoctrineMigrations;

use ...;

final class Version999999 extends AbstractMigration implements LegacyConnectionAwareInterface
{
    private Connection $legacyConnection;

    public function setLegacyConnection(Connection $legacyConnection): void
    {
        $this->legacyConnection = $legacyConnection;
    }

    public function getDescription() : string
    {
        return 'Doing something that requires the legacy database connection.';
    }

    public function up(Schema $schema) : void
    {
        if($this->legacyConnection->createSchemaManager()->introspectSchema()->hasTable('some_legacy_table')){
            // do something
        }
    }

    public function down(Schema $schema) : void
    {
        // undo something
    }
}
```

This method could be used to inject whatever service you need into your migrations, not just connections. I don't know if that's a great idea or not. I recommend only using this option as a workaround when there's really no other option.

**UPDATE**: In the use case above, if the legacy database is on the same server, it would be much easier to just run something like this to check whether a table exists in another database.
```php
$this->connection->executeSql(
    'SELECT COUNT(*) '.
    'FROM information_schema.TABLES '
    .'WHERE TABLE_SCHEMA = "legacy" '.
        'AND TABLE_NAME  = "some_legacy_table"'
    )->fetchOne() === "1";
```
