### DISCUSSION TITLE
When@env doesn't work inside bundle prepend()

### DISCUSSION THREAD

**Discussion by 99hops** [symfony/symfony#46005] [Q&A] [answered]
### Symfony version(s) affected

6.0.7

### Description

Using when@env in bundle prepend method doesn't seem to work for some reason. If I put the configuration outside when@ everything is fine but that's not desired. Is this a bug or I am doing something wrong?

### How to reproduce

```
class FooExtension extends Extension implements PrependExtensionInterface
{
    public function prepend(ContainerBuilder $container)
    {
        $fileLoader = new YamlFileLoader(
            $container,
            new FileLocator(__DIR__.'/../../config')
        );

        $fileLoader->load('packages/monolog.yaml');
    }
}
```
monolog.yaml
```
when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: ["!event"]
when@prod:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: warning
        channels: ["!event"]
```
