### DISCUSSION TITLE
DoctrineTokenProvider lastUpdate is not updated

### DISCUSSION THREAD

**Discussion by rebruCH** [symfony/symfony#46136] [Q&A]
Specs:

- Symfony 5.4.8
- Authentication as default no CustomAuthenticator
- Using RememberMe with DoctrineTokenProvider

Problem:

- Authentication is working like expected
- Entry in rememberme_token is generated on the first login
- The lastUsed column will then never be updated
- The lifetime is not respected (configured for 28 days, but logoff is approx 3-4 hours after the initial token is generated)

Have someone a hint, what the problem can be and why the lastUsed is not updated? I did follow the documentation, but the documentation or in better words, the dependency is not well documented (if you have to use CustomAuth to update it, because in the default, the RememberMeBadge is not populated)

Attachmments:

```yaml
#Services
# Remember Token
    Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider: ~
    
#Security
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User\User:
            id: App\Security\Hasher\DotNetIdentityHasher

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email
    firewalls:
        api:
            pattern:  ^/api
            stateless: true
            jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                username_parameter: email
                password_parameter: password
                login_path: app.login
                check_path: app.login

            logout:
                path: app.logout
                # where to redirect after logout
                # target: app_any_route
            remember_me:
                token_provider: 'Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider'
                secret: '%kernel.secret%'
                lifetime: 2419200 #1 Month
                path: /
                remember_me_parameter: '_remember_me'

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
                
```
