### DISCUSSION TITLE
Security Component, HTTP 401 and two pages on the same URL

### DISCUSSION THREAD

**Discussion by pbowyer** [symfony/symfony#46162] [Q&A]
We've recently upgraded a SaaS to Symfony 6.0 and the new security system.

The SaaS works by showing an informational & login screen at `/` (up to now, the security component's login page), and then their dashboard also at `/` after logging in.

Previously this worked fine, but after updating anonymous users were served a HTTP 401 when they accessed `/`, which was preventing Google from indexing the login screen. This is not desired behaviour on this specific URL (it's fine for other protected pages like `/foo/bar/12345` which must not be indexed).

To fix this I changed the route to be public and the homepage controller to check if the user was authenticated, and if not it forwarded them to the login screen. It works and gives a HTTP 200, but using a subrequest is having other side-effects (`app.request.get('_route')` isn't populated for starters).

What would be a better way to do this?

This is the security config for this firewall:
```
        main:
            lazy: true
            user_checker: App\Security\CustomerUserChecker
            form_login:
                provider: customer_provider
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                use_forward: true
                remember_me: true
                require_previous_session: false
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                enable_csrf: false
                post_only: true
                form_only: false
                always_use_default_target_path: false
                default_target_path: /
                target_path_parameter: _target_path
                use_referer: false
                failure_path: null
                failure_forward: false
                failure_path_parameter: _failure_path
            logout:
                path: app_logout
                csrf_parameter: _csrf_token
                csrf_token_id: logout
                target: /
                invalidate_session: true
                delete_cookies: {  }
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 2630000
                path: /
                always_remember_me: true
                user_providers: {  }
                catch_exceptions: true
                signature_properties:
                    - password
                name: REMEMBERME
                domain: null
                secure: null
                httponly: true
                samesite: lax
                remember_me_parameter: _remember_me
            methods: {  }
            security: true
            stateless: false
            required_badges: {  }
```
