### DISCUSSION TITLE
Remember me and new authenticator not working

### DISCUSSION THREAD

**Discussion by Jean-Gian** [symfony/symfony#46185] [Q&A]
Hi
On S 6.0.7 i implemented a custom login authenticator based on the docs and all works perfectly
I'm trying to add the "remember me" feature to my custom authenticator which extends `AbstractLoginFormAuthenticator`  as explained in here https://symfony.com/doc/current/security/remember_me.html
The remember me feature doesn't work though. The cookie gets dropped, the token gets created in the DB but for some reason after few min the users gets logged out anyway and session and token get cleared.
In my profiler i don't have anything listed in the authenticators (see 1st screenshot) but remember_me and LoginFormAuthenticator are listed in the firewalls (see 2nd screenshot)
Something seems to go wrong here https://symfony.com/doc/current/security/remember_me.html#add-remember-me-support-to-the-authenticator where it says **_"Without this badge, remember me will be not be activated (regardless of all other settings)"_**
As i said, as things are everything works fine, just the remember me feature doesn't

Here is the security.yaml
```
security:
    enable_authenticator_manager: true
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            entry_point: form_login
            pattern: ^/
            user_checker: App\Security\UserChecker
            lazy: true
            provider: users_in_memory
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: home_page
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 7776000 # 90 days week in seconds
                always_remember_me: true
                token_provider:
                    doctrine: true
            login_throttling:
                max_attempts: 3
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
```

Here is the authenticate function in `App\Security\LoginFormAuthenticator`:
```
    public function authenticate(Request $request): Passport
    {
        $this->validateRequest($request);

        $email = $request->request->get('email', '');

        $request->getSession()->set(Security::LAST_USERNAME, $email);

        return new Passport(
            new UserBadge($email, function ($userIdentifier) {
                return $this->entityManager->getRepository(User::class)->findOneBy(['email' => $userIdentifier]);
            }),
            new PasswordCredentials($request->request->get('password', '')),
            [
                new CsrfTokenBadge('authenticate', $request->get('_csrf_token')),
                new RememberMeBadge(),
            ]
        );
    }
```

![image](https://user-images.githubusercontent.com/47142468/165485204-3f79e73d-80c0-4a71-9f65-e602b65625b0.png)
![image](https://user-images.githubusercontent.com/47142468/165489123-ea6e9419-8fd8-4d80-9589-240d5c87e773.png)
