### DISCUSSION TITLE
[Mailer] Using  multiple transports

### DISCUSSION THREAD

**Discussion by TristanPouliquen** [symfony/symfony#46372] [Q&A]
Hello,

At my company we want to rely on the Mailer component to handle all our emails. 

Because of our business constraints, we need to:
- send emails asynchronously through Messenger
- send emails through different transports

I have set up my Mailer configuration as follows:
```yaml
framework:
    mailer:
        transports:
          # Define the corresponding MAILER service in TransactionalEmail
          assoconnect_transactional: '%env(ASSOCONNECT_TRANSACTIONAL_MAILER_DSN)%'
          assoconnect_emailing: '%env(ASSOCONNECT_EMAILING_MAILER_DSN)%'
          springly_transactional: '%env(SPRINGLY_TRANSACTIONAL_MAILER_DSN)%'
          springly_emailing: '%env(SPRINGLY_EMAILING_MAILER_DSN)%'
        headers:
          bcc: 'archive@assoconnect.com'

when@dev:
  framework:
    mailer:
      envelope:
        recipients: ['%env(email)%']
```

I am adding a `X-Transport` text header to my emails containing one of the configure values (`assoconnect_transactional`, `springly_transactional`, ....)

However, all my emails are sent through the first (and default) `assoconect_transactional` transport.

I noticed that the `X-Transport` header was not removed from our emails.

I have overridden the default `Symfony\Component\Mailer\Messenger\MessageHandler` handler to add some business logic, injecting in it the `TransportInterface` as it was done and calling `$transport->send(...)`.

And here is the problem. When I dump the class of the `TransportInterface` I get, I have `MailgunHttpTransport` directly.

If I understand the multiple transport logic, I should pass at one moment inside `Symfony\Component\Mailer\Transport\Transports` class where the logic is done to choose the transport based on the `X-Transport` header.

However, if I try to inject the `Transports` class as a type hint, I get an error saying I need to use the `TransportInterface`.

How should I go around this issue to be able to manage both asynchronous & multiple transports sending?

Cheers

---
## Update: The problem resides only in using multiple transports.

But I still don"t get why, as I seem to be following the documentation usecase :/
