### DISCUSSION TITLE
Workflow/State Machine, guard event is triggered with the wrong transition

### DISCUSSION THREAD

**Discussion by netstrada-master** [symfony/symfony#46381] [Q&A] [answered]
### Symfony version(s) affected

6.0.8

### Description

I want to implement a state machine for a membership subscription.
Here is the diagram:
<img width="1244" alt="Screen Shot 2022-05-16 at 23 54 05" src="https://user-images.githubusercontent.com/71973201/168688669-7510a881-3878-43c9-887f-5878288a3e15.png">

And here the workflow config:
```yml
framework:
    workflows:
        membership:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Membership
            initial_marking: requested
            places:
                - requested
                - accepted
                - pending_payment
                - pending_information
                - approved
                - expired
                - declined
            transitions:
                submit:
                    from: requested
                    to: accepted
                approve:
                    from: requested
                    to: accepted
                decline:
                    from: requested
                    to: declined
                start_payment:
                    from: accepted
                    to: pending_payment
                complete_payment:
                    from: pending_payment
                    to: pending_information
                fill_information:
                    from: pending_information
                    to: approved
                dismiss:
                    from: approved
                    to: expired
```

I wanted to create a guard event for the transition **complete_payment** where I would check if in the context array there is a token that eventually I would use to validate the payment (like validating the token of an _instant payment notification_).
To do so I've created an Event Subscriber and listen to:
```
 'workflow.membership.guard.complete_payment' => ['guardPaymentCheck'],
```
Surprisingly, when I apply the transition **start_payment** I see that the guard is triggered.
Also, once I apply **complete_payment** with or without the context argument, in the Event Subscriber I still get an empty array.

### src/EventSubscriber/MembershipPaymentCheckSubscriber.php
```php
<?php
namespace App\EventSubscriber;

use App\Entity\Membership;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Workflow\Event\GuardEvent;

class MembershipPaymentCheckSubscriber implements EventSubscriberInterface
{
    public function guardPaymentCheck(GuardEvent $event)
    {

        /** @var Membership $membership */
        $membership = $event->getSubject();
        $context = $event->getContext();
        echo "TRIGGERED Context: ".serialize($context)." ";
        if (empty($context['token'])) {
            $event->setBlocked(true, 'Payment failed.');
        }
    }

    public static function getSubscribedEvents()
    {
        return [
            'workflow.membership.guard.complete_payment' => ['guardPaymentCheck'],
        ];
    }
}
```

Here is an action of a controller I use for testing:
```php
#[Route("/test", name: "membership_test")]
    public function test(Request $request, EntityManagerInterface $entityManager, WorkflowInterface $membershipStateMachine)
    {
        /** @var Membership $m */
        $m = $entityManager->find(Membership::class, 1);
        try {
            echo " #1 ";
            $membershipStateMachine->apply($m, 'submit');
            echo " #2 ";
            $membershipStateMachine->apply($m, 'start_payment');
            echo " #3 ";
            $membershipStateMachine->apply($m, 'complete_payment');
            echo " #4 ";
//            $membershipStateMachine->apply($m, 'complete_payment', ['token' => 'test']);
        } catch (\Exception $exception) {
            die($exception->getMessage());

        }

        echo " || done : ";
        die($m->getState());

        return $this->redirectToRoute("membership_index");
    }
```
and this is what I get when I visit the action page
```
 #1  #2 TRIGGERED Context: a:0:{}  #3 TRIGGERED Context: a:0:{} Transition "complete_payment" is not enabled for workflow "membership".
```

As you can see after `#2` the guard is executed, as well after the `#3` .
Please note that, decommenting the line after `echo " #4 ";` I still get 
```
#1  #2 TRIGGERED Context: a:0:{}  #3 TRIGGERED Context: a:0:{} Transition "complete_payment" is not enabled for workflow "membership".
```
since the exception rise from the first `apply` in complete payment.

Instead, decommenting only the line after `echo " #3 ";` this is what I got:
```
 #1  #2 TRIGGERED Context: a:0:{}  #3  #4 TRIGGERED Context: a:0:{} Transition "complete_payment" is not enabled for workflow "membership".
 ```
So still not data into context.

### How to reproduce

To reproduce it, simply create a symfony project and use the configuration I have pasted and create a controller with that action.
