### DISCUSSION TITLE
Access/expose framework-bundle configuration values (default_locale, enabled_locales)

### DISCUSSION THREAD

**Discussion by MichaelBrauner** [symfony/symfony#46400] [Q&A] [answered]
I wrote a [Bundle](https://github.com/Braunstetter/localized-routes#installation). 

It uses parameters for configuration yet.

```yaml
parameters:
  app_locales: de|en
  locale: en
```

I wonder if I can access the existing default_locale and enabled_locales from framework-bundle and inject it into my services.

That would make much more sense than defining it again.
