### DISCUSSION TITLE
Strange issue with Symfony Console pcntl_signal on PHP 8.0

### DISCUSSION THREAD

**Discussion by Awilum** [symfony/symfony#46540] [Q&A] [answered]
My Unit Tests start falling specifically for PHP 8.0 because of this issue

https://github.com/glowyphp/strings/runs/6685047425?check_suite_focus=true#step:8:11

It says that there is a syntax error, but it is related to https://github.com/symfony/console/blob/6.1/SignalRegistry/SignalRegistry.php#L37

Error:
```
syntax error, unexpected token ")"
```

My composer.json
```json
{
    "name": "glowy/strings",
    "description": "Strings Component provide a fluent, object-oriented interface for working with multibyte string, allowing you to chain multiple string operations together using a more readable syntax compared to traditional PHP strings functions.",
    "license": "MIT",
    "keywords": [
        "Strings", "strings", "php-strings", "php", "glowy", "glowyphp", "strings-manipulation"
    ],
    "support": {
      "source": "https://github.com/glowyphp/strings",
      "issues": "https://github.com/glowyphp/strings/issues"
    },
    "authors": [
        {
            "name": "Sergey Romanenko",
            "email": "sergey.romanenko@flextype.org",
            "homepage": "https://github.com/Awilum"
        }
    ],
    "require": {
        "php": "^7.4 || ^8.0",
        "ext-json": "*",
        "ext-mbstring": "*",
        "glowy/macroable": "^3.0"
    },
    "autoload":{
        "psr-4": {
            "Glowy\\Strings\\": "src/"
        },
        "files": [
            "src/helpers.php"
        ]
    },
    "require-dev": {
        "doctrine/coding-standard": "9.0.0",
        "pestphp/pest": "^1.21.3",
        "phpstan/phpstan": "^1.4.5",
        "symfony/var-dumper": "^5.4.9"
    },
    "config": {
        "platform-check": false,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "dealerdirect/phpcodesniffer-composer-installer": true
        }
    }
}
```

My ci.yml
```yaml
name: CI
on: ['push', 'pull_request']
jobs:
  phpstan:
    name: PHP Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse src/ -c phpstan.neon
  tests:
    name: Unit Tests for PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['7.4', '8.0', '8.1']
        dependency-version: [prefer-stable]

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions:  fileinfo, spl, json, dom, mbstring, pcntl
        ini-values: disable_functions, error_reporting=E_ALL
        tools: composer:v2
        coverage: xdebug

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP 7 dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
      if: "matrix.php < 8"

    - name: Install PHP 8 dependencies
      if: "matrix.php >= 8"
      run: composer update --${{ matrix.dependency-version }} --ignore-platform-req=php --no-interaction --no-progress

    - name: Run Tests for PHP 7.4
      if: "matrix.php == 7.4"
      run: ./vendor/bin/pest --coverage

    - name: Run Tests for PHP 8.0
      if: "matrix.php == 8.0"
      run: ./vendor/bin/pest

    - name: Run Tests for PHP 8.1
      if: "matrix.php == 8.1"
      run: ./vendor/bin/pest --coverage
```
