### DISCUSSION TITLE
Install of symfony/polyfill-mbstring failed

### DISCUSSION THREAD

**Discussion by Awilum** [symfony/symfony#46552] [Q&A] [answered]
Today I got another strange random issue, yesterday it is was okey, but today for some reason it's failed randomly.

https://github.com/glowyphp/strings/runs/6702669039?check_suite_focus=true

**my composer.json**
```json
{
    "name": "glowy/strings",
    "description": "Strings Component provide a fluent, object-oriented interface for working with multibyte string, allowing you to chain multiple string operations together using a more readable syntax compared to traditional PHP strings functions.",
    "license": "MIT",
    "keywords": [
        "Strings", "strings", "php-strings", "php", "glowy", "glowyphp", "strings-manipulation"
    ],
    "support": {
      "source": "https://github.com/glowyphp/strings",
      "issues": "https://github.com/glowyphp/strings/issues"
    },
    "authors": [
        {
            "name": "Sergey Romanenko",
            "email": "sergey.romanenko@flextype.org",
            "homepage": "https://github.com/Awilum"
        }
    ],
    "require": {
        "php": "^7.4 || ^8.0",
        "ext-json": "*",
        "ext-mbstring": "*",
        "glowy/macroable": "^3.0"
    },
    "autoload":{
        "psr-4": {
            "Glowy\\Strings\\": "src/"
        },
        "files": [
            "src/helpers.php"
        ]
    },
    "require-dev": {
        "doctrine/coding-standard": "9.0.0",
        "pestphp/pest": "^1.21.3",
        "phpstan/phpstan": "^1.4.5",
        "symfony/var-dumper": "^5.4.9"
    },
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "dealerdirect/phpcodesniffer-composer-installer": true
        }
    },
    "prefer-stable": true
}
```

**my ci.yml**
```
name: CI
on: ['push', 'pull_request']
jobs:
  phpstan:
    name: PHP Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse src/ -c phpstan.neon
  tests:
    name: Unit Tests for PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ['7.4', '8.0', '8.1']
        dependency-version: [prefer-stable]

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions:  fileinfo, spl, json, dom, mbstring, pcntl
        ini-values: disable_functions, error_reporting=E_ALL
        tools: composer:v2
        coverage: xdebug

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP 7 dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
      if: "matrix.php < 8"

    - name: Install PHP 8 dependencies
      if: "matrix.php >= 8"
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress

    - name: Run Tests for PHP 7.4
      if: "matrix.php == 7.4"
      run: ./vendor/bin/pest --coverage

    - name: Run Tests for PHP 8.0
      if: "matrix.php == 8.0"
      run: ./vendor/bin/pest --coverage

    - name: Run Tests for PHP 8.1
      if: "matrix.php == 8.1"
      run: ./vendor/bin/pest --coverage
      
  support:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: sebastianpopp/discord-action@releases/v1
        with:
          webhook: ${{ secrets.WEBHOOK_TOKEN }}
          message: "**❤️ SUPPORT ONGOING DEVELOPMENT**\n➡️ https://github.com/Awilum#support-me"
```

<img width="943" alt="Screenshot 2022-06-02 at 08 20 37" src="https://user-images.githubusercontent.com/477114/171558820-0fa86918-e26b-4ac9-8e64-edba57f70f94.png">
<img width="324" alt="Screenshot 2022-06-02 at 08 20 43" src="https://user-images.githubusercontent.com/477114/171558823-19a0c4a5-f9b4-479b-bc49-93cac006d5d7.png">
