### DISCUSSION TITLE
Pattern in custom authenticator

### DISCUSSION THREAD

**Discussion by adsazad** [symfony/symfony#46582] [Q&A]
does pattern attribute distinguish custom authenticator?
I have to authenticate two different API for different types of users from different entities, and I am not sure whether the pattern attribute in security distinguishes them.
```
service_provider_area:
            #            logout_on_user_change: true
            # switch_user: true
            pattern: ^/service/provider/mobile/api
            custom_authenticators:
                - App\Security\ServiceProviderMobileTokenAuthenticator   
            provider:   mobile_service_provider
```
