### DISCUSSION TITLE
How %env(VAR)% differs from %env(resolve:VAR)% ?

### DISCUSSION THREAD

**Discussion by HongKilDong** [symfony/symfony#46598] [Q&A] [answered]
How `%env(VAR)%` differs from `%env(resolve:VAR)%` ?

**Comment by DylanKas** [comment, marked as answer]
`%env(resolve:VAR)%` will replace the container parameter string with its value, whereas `%env(VAR)%` will just return you the plain string.

Example (from [symfony doc](https://symfony.com/doc/current/configuration/env_var_processors.html))

```
# config/packages/sentry.yaml
parameters:
    env(HOST): '10.0.0.1'
    sentry_host: '%env(HOST)%'
    env(SENTRY_DSN): 'http://%sentry_host%/project'
sentry:
    dsn: '%env(resolve:SENTRY_DSN)%'
```

In this example, dsn is using resolve because inside `SENTRY_DSN` we have a container parameter (sentry_host), so dsn become:

`http://10.0.0.1/project`

Whereas with `%env(SENTRY_DSN)%` we would get:

`http://%sentry_host%/project`
