### DISCUSSION TITLE
Master Password on Symfony

### DISCUSSION THREAD

**Discussion by ioneu** [symfony/symfony#46634] [Q&A] [answered]
Hi everyone,

I wonder, is it possible to create a "Master Password" on Symfony?
So that there is a normal user and password for authentication, and there is also a hard-coded hashed password for Admin to login as normal user (and also generate JWT Token as normal user). I am fully aware of the security risk regarding master password feature.

Symfony already have an impersonation method to login as normal user, but I found that impersonation method cannot work to generate JWT Token for the impersonated user (I have already reported it at: https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1012 ).

I am on a process to rewrite a legacy app to symfony app, on the legacy app, there is a master password feature and the employer insist on making the master password as a requirement on the new symfony app.

Current implementation on the legacy app is that "the master password"  hash is hardcoded on the app, and when there is authentication event, app will check whether the hash of the inputted password === the master password hash, if it's true, then user will be logged in with master password, if false, continue with the normal authentication process.

How can I achieve the functionality of this master password with current Symfony Authentication?
PS. I use Symfony 6.1

Thank you.

**Comment by IonBazan** [comment]
You could create a custom user password hasher implementing `UserPasswordHasherInterface` which would be a copy of `UserPasswordHasher` with extra step validating the password against a "hardcoded" hashed value for master password.

```php
class MasterPasswordUserPasswordHasher implements UserPasswordHasherInterface
{
    public function __construct(private readonly PasswordHasherFactoryInterface $hasherFactory, private readonly string $masterPassword)
    {
    }

    public function hashPassword(PasswordAuthenticatedUserInterface $user, string $plainPassword): string
    {
        $salt = null;
        if ($user instanceof LegacyPasswordAuthenticatedUserInterface) {
            $salt = $user->getSalt();
        }

        $hasher = $this->hasherFactory->getPasswordHasher($user);

        return $hasher->hash($plainPassword, $salt);
    }

    public function isPasswordValid(PasswordAuthenticatedUserInterface $user, string $plainPassword): bool
    {
        $salt = null;
        if ($user instanceof LegacyPasswordAuthenticatedUserInterface) {
            $salt = $user->getSalt();
        }

        if (null === $user->getPassword()) {
            return false;
        }

        $hasher = $this->hasherFactory->getPasswordHasher($user);
        // This is the added part
        return $hasher->verify($user->getPassword(), $plainPassword, $salt) || $hasher->verify($this->masterPassword, $plainPassword, $salt);
    }

    public function needsRehash(PasswordAuthenticatedUserInterface $user): bool
    {
        if (null === $user->getPassword()) {
            return false;
        }

        $hasher = $this->hasherFactory->getPasswordHasher($user);

        return $hasher->needsRehash($user->getPassword());
    }
}
```

You can refer to https://symfony.com/doc/current/security/passwords.html#hashing-the-password for more details.

Please note that this is **NOT SECURE** and should never be deployed to production. Therefore, I suggest aliasing this service only in `dev` environment (`services_dev.yaml`) and making sure the master password can be changed using environment variable.

**Comment by lyrixx** [comment, marked as answer]
Hello,

You can use the [in memory user](https://symfony.com/doc/current/security/user_providers.html#memory-user-provider) provider to achieve that.

Of course, you must hash your password in order to store it in the `security.yaml` file.

Example:

```yaml
# app/config/security.yml                                                                                                                                                                  
security:                                                                                                                                                                                  
    password_hashers:                                                                                                                                                                      
        Symfony\Component\Security\Core\User\InMemoryUser: auto                                                                                                                              
```

```
bin/console security:hash-password foobar 'Symfony\Component\Security\Core\User\InMemoryUser' -n

 --------------- ----------------------------------------------------------------- 
  Key             Value                                                            
 --------------- ----------------------------------------------------------------- 
  Hasher used     Symfony\Component\PasswordHasher\Hasher\MigratingPasswordHasher  
  Password hash   $2y$13$RWVi6os8YJUTFiAEPF/SQec/1bc58ArItKZSygwJEQcr4OLp1DTv.     
 --------------- ----------------------------------------------------------------- 
```

Then store it in the configuration

```yaml
security
    providers:
        backend_users:
            memory:
                users:
                    admin: { password: '$2y$13$RWVi6os8YJUTFiAEPF/SQec/1bc58ArItKZSygwJEQcr4OLp1DTv.', roles: ['ROLE_ADMIN'] }
```

---

If there are two firewall, use one user provider in each one.

If there is only one firewall, you can use a [chain user provider](https://symfony.com/doc/current/security/user_providers.html#chain-user-provider)

see [this answer](https://github.com/symfony/symfony/discussions/46641#discussioncomment-2948646) for more information
