### DISCUSSION TITLE
Login with multiple entity

### DISCUSSION THREAD

**Discussion by abradi1** [symfony/symfony#46641] [Q&A] [answered]
Hello, i have two tables User and Student and i want to connect multiple entities from a single form to achieve this i see that i have to create users providers for each entity but I struggled to find a solution for hours but nothing works if someone can help me please i really need the solution. To create the user provider i just update the security.yaml file, there is another file to update ?

```
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_apprenant_provider:
            entity:
                class: App\Entity\Apprenant
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            form_login: ~
            provider: 
                chain_provider:
                    chain:
                        providers: [app_user_provider, app_apprenant_provider]
            custom_authenticator:
                - App\Security\CustomAuthenticator
            entry_point: form_login

            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

```

**Comment by lyrixx** [comment, marked as answer]
Hi.

You need something like this:

```yaml
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_apprenant_provider:
            entity:
                class: App\Entity\Apprenant
                property: email
        chain_provider:
            chain: 
                providers: [app_user_provider, app_apprenant_provider]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            form_login: ~
            provider: chain_provider
            custom_authenticator:
                - App\Security\CustomAuthenticator
            entry_point: form_login

            logout:
                path: app_logout
```

see the [documentation](https://symfony.com/doc/current/security/user_providers.html#chain-user-provider) for more information
