### DISCUSSION TITLE
Where do we put our own classes ?

### DISCUSSION THREAD

**Discussion by Asmitta-01** [symfony/symfony#46653] [Q&A] [answered]
As said in the title i want to know where is the location for own classes. Neither controller nor entity, just simple classes.
I created a folder `Helper` where a store my class, and in this this i have this on the top :
```php
<?php

namespace App\Helper;
```
When i launch my app or running any php command i have an error(Illegal offset type): 

> Executing script cache:clear [KO]
>  [KO]
> Script cache:clear returned with error code 255
> !!  TypeError {#1902
> !!    #message: "Illegal offset type"
> !!    #code: 0
> ...
When i remove the namespace in my class it works now but i can't use this class. Where should i store my class with his namespace or what should i do to stop getting this error from php ?

**Comment by craigh** [comment, marked as answer]
`namespace App\Helper;` inside of `src/Helper/` should be just fine ... assuming you have set up `composer.json` and `config/services.yaml` with the standard recipes. Perhaps share those files if you aren't sure, but a quick way to compare is to create a new project quickly with standard settings and compare those file.

**Reply by Asmitta-01** [reply]
> ` Perhaps share those files if you aren't sure, but a quick way to compare is to create a new project quickly with standard settings and compare those file.

I have created a new project `symfony new testapp` where i added my class( in src\Helper). I got the same error :illegal offset type, even if i change Helper to Utils or whatever same error. Any idea ?

**Reply by Asmitta-01** [reply]
My services.yaml file :
```yaml
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    messages_directory: '%kernel.project_dir%/public/uploads/messages'
    crypto_directory: '%kernel.project_dir%/public/images/crypto'
    product_directory: '%kernel.project_dir%/public/images/store'
    app_url: '%env(APP_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
```
It is still having default config. And my composer.json
```json
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "composer/package-versions-deprecated": "1.11.99.4",
        [...]
        "twig/intl-extra": "^3.4"
    },
    "config": {
        "allow-plugins": {
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        [...]
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.0.*"
        }
    },
    "require-dev": {
        [...]
    }
}
```
i don't see something causing problem, hope someone will see. Do you any other way to include my classes if i can't with the classic method(up)
