### DISCUSSION TITLE
GitHub pipeline is failing on symfony/var-dumper 6.1.0 installation

### DISCUSSION THREAD

**Discussion by Awilum** [symfony/symfony#46829] [Q&A] [answered]
Hello!

I have this issue when I run GitHub actions for my package on PHP 8.1.

>[PHP Static Analysis](https://github.com/glowyphp/macroable/runs/7163639802?check_suite_focus=true#step:4:20)
Your requirements could not be resolved to an installable set of packages.
>  Problem 1
>    - Root composer.json requires php ^8.1 but your php version (8.0.20) does not satisfy that requirement.
>  Problem 2
>    - Root composer.json requires symfony/var-dumper ^6.1.0 -> satisfiable by symfony/var-dumper[v6.1.0].
>    - symfony/var-dumper v6.1.0 requires php >=8.1 -> your php version (8.0.20) does not satisfy that requirement.

I am not 100% that it's related to symfony/var-dumper v6.1.0 but its starts failing after updating to PHP 8.1 and symfony/var-dumper to v6.1.0

my ci.yaml https://github.com/glowyphp/macroable/blob/4.x/.github/workflows/ci.yml
my composer.json https://github.com/glowyphp/macroable/blob/4.x/composer.json

Any ideas how to fix this?

**Comment by stloyd** [comment]
Don't use Symfony in version 6.1 on PHP 8.0, as it requires PHP 8.1.

You can fix your `composer.json` by limiting to `6.0.x`, IIRC by: `^6.0 || <6.1`.

**Reply by Awilum** [reply]
But I'm not using PHP 8.0 https://github.com/glowyphp/macroable/blob/4.x/.github/workflows/ci.yml but for some reason It's says that its trying to run on 8.0.20 that I am not requiring.

**Reply by stloyd** [reply]
My guess would be that Mac run is using default version not the one pushed by action from GH.

**Comment by Awilum** [comment, marked as answer]
seems issue resolved by removing this action

```
  phpstan:
     name: PHP Static Analysis
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: PHPStan
       uses: docker://oskarstark/phpstan-ga
       with:
         args: analyse src/ -c phpstan.neon
```

for some reason, it doesn't work on php 8.1         

so I decided to run phpstan just with a command 
```
    - name: PHP Static Analysis for PHP 8.1
      run: ./vendor/bin/phpstan
```
