### DISCUSSION TITLE
Share one connection with PdoSessionHandler

### DISCUSSION THREAD

**Discussion by jwage** [symfony/symfony#46910] [Q&A] [answered]
UPDATE: I think the reason it needs a separate PDO connection is because PdoSessionHandler begins a transaction and does not commit it until the end of the request. So any transactions made in the controller, etc. will fail saying a transaction is already started.

Hi,

Quick question, is there any reason to use a separate PDO connection with PdoSessionHandler?

I am working on adding connection pooling to my app using pgbouncer and I noticed on each request I was getting two connections open and closed.

It is because of this configuration passing in the DSN:

```
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_CONNECTION_POOL_URL)%'
```

It was easy enough for me to fix this in my app with this:

```
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - !service
                class: PDO
                factory: ['@Doctrine\DBAL\Connection', 'getWrappedConnection']
```

The above causes issues with other transactions that happen in the controller. Since PdoSessionHandler beings a transaction and does not commit it until the end of the request, your other transactions will fail with an error. You can use advisory locks instead to workaround the issue:

```
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - !service
                class: PDO
                factory: ['@Doctrine\DBAL\Connection', 'getWrappedConnection']
            - {lock_mode: 1} # advisory locks
```

However, all the documentation shows doing it the first way so most apps that use PDO sessions are probably making two database connections per request.

Is there any good reason to use a separate connection that I am missing? If no, is this something we should try to improve with a `DoctrineSessionHandler` or maybe just a documentation change initially?
