### DISCUSSION TITLE
How to instruct Symfony's serializer to inject properties in an entity's constructor

### DISCUSSION THREAD

**Discussion by NotionCommotion** [symfony/symfony#46928] [Q&A]
Instead of having Symfony's serializer use setters to denormalize an entity, I wish to have the serializer inject them in the entity's constructor.  My reasoning for wishing to do so are as follows:

I have the Asset entity which contains a Money object which is also a Doctrine embeddable.

src/Entity/Asset.php
```php
namespace App\Entity;
use ApiPlatform\Metadata\ApiResource;
use Money\Money;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
#[ApiResource]
#[ORM\Entity]
class Asset
{
     //ID, other properties, and cost setter and getter exists but are just not shown.
    #[Groups(['asset:read', 'asset:write'])]
    #[ORM\Embedded(class: Money::class)]
    private Money $cost;
}
```

src/Resources/config/doctrine/Money.orm.xml
```xml
<?xml version="1.0"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping" xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
  <embeddable name="Money\Money">
    <field name="amount" type="bigint" nullable="false"/>
    <field name="currency" type="currency" nullable="false"/>
  </embeddable>
</doctrine-mapping>
```
config/packages/doctrine.yaml
```yaml
dctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            currency:  App\Doctrine\Types\CurrencyType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Money:
                type: xml
                dir: '%kernel.project_dir%/src/Resources/config/doctrine'
                prefix: Money
```
I am using API-Platform and Symfony's serializer, and all works with GET requests as desired, however, when attempting to perform a POST or PUT requests, I get the following error:

`Cannot create an instance of "Money\Money" from serialized data because its constructor requires parameter "amount" to be present
`

Looking at Money, it is obvious why it is happening and I need help regarding what to do about it.  One option is to make `MyMoney` instead of `Money` the embeddable and have Money instantiated within it after `MyMoney`'s `setAmount()` and `setCurrency()` methods are executed by the serializer.  Or maybe use a custom normalizer to handle the serialization of the Money embeddable.  Or ideally instruct Symfony "somehow" to not use setters but inject `$amount` and `$currency`.  Or maybe something else?

Appreciate any advice.  Thanks!

```php
namespace Money;
final class Money implements JsonSerializable
{
    public function __construct(int|string $amount, Currency $currency) {}
}
```
