### DISCUSSION TITLE
Class "" used for service "security.listener.user_checker.integration" cannot be found

### DISCUSSION THREAD

**Discussion by tooeo** [symfony/symfony#47089] [Q&A]
I'm trying to update symfony from 3.4 to 6.0.1

And I got an error

`Class "" used for service "security.listener.user_checker.integration" cannot be found.`

I have this error for each blocks in firewalls section

```
        integration:
            pattern: ^/integration
            host: %base_host%
            stateless: true
            custom_authenticators:
                - integration.authenticator.token
            provider: integration_provider
```
I checked https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/EventDispatcher/DependencyInjection/RegisterListenersPass.php#L119

and

https://github.com/symfony/symfony/blob/6.0/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L472

So ChildDefinition has no class(but has parent)

And I can't understand how it should work. Which class should be returned in RegisterListenersPass and where it should be set

I understand that it's hard to jump over so many versions. But I just want to figure out how it should work.
