### DISCUSSION TITLE
[HttpClient] Unable to inject container parameters into scoped client

### DISCUSSION THREAD

**Discussion by buffcode** [symfony/symfony#47365] [Q&A] [answered]
Symfony 4.4

I have a bundle configuration to configure multiple endpoints. The bundle's extension transforms those options into container parameters.

Multiple `framework.http_client.scoped_clients` are configured and should then use those parameters.

But all I receive is: 
```
In ParameterBag.php line 95:

  You have requested a non-existent parameter "company.api.endpoint".
```

I tried to clear the cache, dumped the configuration within my extension, but the error already comes up before my extension's `loadInternal` is called.

```php
// Configuration.php
$rootNode
    ->children()
        ->arrayNode('company')
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('endpoint')
                    ->cannotBeEmpty()
                    ->defaultValue('https://example.org/rest/')
                ->end()
                ->scalarNode('username')
                    ->defaultNull()
                    ->cannotBeEmpty()
                ->end()
                ->scalarNode('password')
                    ->defaultNull()
                    ->cannotBeEmpty()
                ->end()
            ->end()
        ->end()
    ->end()
;
```

```yaml
# bundle-configuration.yaml
my_bundle:
  company:
    username: '%env(API_USERNAME)%'
    password: '%env(API_PASSWORD)%'
```

```php
// Extension.php
class AppExtension extends ConfigurableExtension
{
    protected function loadInternal(array $mergedConfig, ContainerBuilder $container)
    {
        $container->setParameter('company.api.endpoint', $mergedConfig['company']['endpoint']);
        $container->setParameter('company.api.username', $mergedConfig['company']['username']);
        $container->setParameter('company.api.password', $mergedConfig['company']['password']);
    }
}
```

```yaml
# framework.yaml
framework:
  http_client:
    scoped_clients:
      company.client:
        base_uri: '%company.api.endpoint%'
        max_redirects: 0
        auth_basic: '%company.api.username%:%company.api.password%'
        headers:
          Accept: 'application/json'
```

Maybe related:
- https://github.com/symfony/symfony/issues/31223
