### DISCUSSION TITLE
Could not find the entity manager for class "App\Country\Entity\Country". Check your Doctrine configuration to make sure it is configured to load this entity’s metadata.

### DISCUSSION THREAD

**Discussion by SV552** [symfony/symfony#47376] [Q&A]
Hey i moved my Local Symfony project to Server and now im getting this error 

Could not find the entity manager for class "App\Country\Entity\Country". Check your Doctrine configuration to make sure it is configured to load this entity’s metadata.

` public function __construct    (  ManagerRegistry $registry,  StatusGateway $statusGateway ) { 
 parent::__construct($registry, Country::class); 
 $this->statusGateway = $statusGateway;    }`

and this is my doctrine.yaml

```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            enum: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/'
                prefix: 'App\'
                alias: App
```

maybe someone has an idea?
