### DISCUSSION TITLE
Forcing Content-type everywhere

### DISCUSSION THREAD

**Discussion by Jean85** [symfony/symfony#47471] [Q&A]
What's the easiest way to force your Symfony (API) app to respond with the same format everywhere? Maybe even when hitting 404s.

I want to force `Content-type: application/json` everywhere; I tried
```yaml
framework:
    request:
        formats:
            json: 'application/json'
```
but it doesn't work. Anything else that I can try?
