### DISCUSSION TITLE
[Cache] Disable versioning in memcached adapter

### DISCUSSION THREAD

**Discussion by glengemann** [symfony/symfony#47659] [Q&A]
Hi! Is it possible to disable key versioning when using the **memcached** adapter? I need to integrate with a server populated by another application.

I have this config:
```
framework:
    cache:
        pools:
            fimemcached:
                adapter: cache.adapter.memcached
                provider: memcached_provider

services:
    fimemcached:
        parent: 'cache.adapter.memcached'
        tags:
            - { name: 'cache.pool', namespace: '' }
    memcached_provider:
        class: \Memcached
        factory: ['Symfony\Component\Cache\Adapter\MemcachedAdapter', 'createConnection']
        arguments:
            - 'memcached://memcached:11211'
            - { prefix_key: 'PREFIXKEY' }
```

With this line ` - { name: 'cache.pool', namespace: '' }`, I am trying that the component does not add any prefix to the key. Unfortunately, a prefix is still added. The reason for this is that in the `MemcachedAdapter` constructor the `enableVersioning()` method is called.

I think I have solved the problem by editing the file in the vendor folder and change the method call from **$this->enableVersioning()** to **$this->enableVersioning(false)**:

```
// vendor/symfony/cache/Adapter/MemcachedAdapter.php
public function __construct(... more code ...)
{
    ... more code ...
    $this->enableVersioning(false);
    ... more code ...
}
```
But, is it possible to disable the key versioning from config file?

Postscript: I think that the response to this answer is wrong: [Get value set in cache from another application #45514](https://github.com/symfony/symfony/discussions/45514). In that case, the problem is not the [prefix-seed](https://symfony.com/doc/current/reference/configuration/framework.html#prefix-seed) option.
