### DISCUSSION TITLE
How to check if a user is enabled during the "form login authentication"

### DISCUSSION THREAD

**Discussion by sdespont** [symfony/symfony#47866] [Q&A] [answered]
I am using the recommended [form login authenticator](https://symfony.com/doc/5.4/security.html#form-login) as described in the documentation for authenticating the users.

In addition, I have added a database field `enabled` to my `User` entity to disable it depending on businesses conditions.

How can I check if the `User` is enabled in my database using the form login authenticator? Do I need checking this in the onAuthenticationSuccess handler and throw an exception or there is another way ?

**Comment by asuri0n** [comment]
inside `authenticate()` function you can add custom callback to the Passport (that's how we are dealing with)

something like this should work
```
return new Passport(
       new UserBadge($email, function ($userIdentifier) {
                // optionally pass a callback to load the User manually
                $user = $this->userRepository->loadUserByIdentifier($userIdentifier);
                if (!$user->isEnabled()) {
                        throw new UserNotFoundException();
                }

                return $user;
            }),
      , new PasswordCredentials($plaintextPassword)
);
```

**Reply by sdespont** [reply]
Thanks for your answer ! Sorry for the silly question, but how can I overwrite `authenticate()` method of the form login authentication process?

**Reply by asuri0n** [reply]
same as for `onAuthenticationSuccess`
see https://symfony.com/doc/current/security/custom_authenticator.html#security-passports

**Reply by sdespont** [reply]
Not really, to use the form login authentication, `success_handler` is defined as an handler in the firewall config.
```
firewalls:
    main:
        form_login:
            success_handler: App\Security\User\Authentication\Handler\AuthenticationSuccessHandler
            ...
```
Have you created a custom authentication method to implement the behavior like this?
```
    firewalls:
        main:
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator
```

**Reply by asuri0n** [reply]
oh yes it's a custom authenticator ;)

**Reply by sdespont** [reply]
Ok, thanks. Sorry to bother you, but after reading the documentation several times today, I really don't understand how to create a custom authentication based on the form loging authentication. The `custom_authenticators` expect only a class, and `form_login` has a lot of options I would like to use the same way. My first idea was to extend [Symfony FormLoginAuthenticator](https://github.com/symfony/symfony/blob/6c8c93d542103656a37b8cda1d293c29d083ed51/src/Symfony/Component/Security/Http/Authenticator/FormLoginAuthenticator.php) but I don't understand how to define options in the firewall config.

Perhapas you could help me showing a part of your firewall config?

**Comment by asuri0n** [comment]
```
            form_login:
                login_path: route_login
                check_path: route_login
            entry_point: form_login
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
                - App\Security\ApiKeyFormAuthenticator
```
