### DISCUSSION TITLE
Injecting a controller into a bundle

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#47891] [Q&A] [answered]
This used to work, but recently stopped for me, which means it was likely not completely correct in the first place.

I want to make a controller in my Symfony 6.1 bundle public.  

```php
/// src/SurvosWorkflowBundle.php

class SurvosWorkflowBundle extends AbstractBundle
{
    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {

        $workflowControllerId = 'survos_workflow_bundle.workflow_controller';
        $container->services()->alias(WorkflowController::class, $workflowControllerId);
        $builder->autowire($workflowControllerId, WorkflowController::class)
            ->addTag('container.service_subscriber')
            ->addTag('controller.service_arguments')
            ->setPublic(true)
        ;
```

```yaml
# routing.yaml

survos_workflows: {path: /workflows, controller: 'Survos\WorkflowBundle\Controller\WorkflowController::workflows'}
survos_workflow: {path: "/workflow/{flowCode}", controller: 'Survos\WorkflowBundle\Controller\WorkflowController::workflow'}
```

The error
> 
The controller for URI "/workflow/printQueue" is not callable: Controller "Survos\WorkflowBundle\Controller\WorkflowController" cannot be fetched from the container because it is private. Did you forget to tag the service with "controller.service_arguments"?

Admittedly, I'm guessing a bit of how the serviceID and alias work together.  I've also tried to setAutoconfigured(true).  And have cleared the cache, and dumped the classmap, many times.
