### DISCUSSION TITLE
Register multiple services for single class with non-autowirable arguments

### DISCUSSION THREAD

**Discussion by ToshY** [symfony/symfony#47957] [Q&A] [answered]
I will try to explain my situation with the following example, as it seems I lack basic knowledge regarding autowiring / autowirable arguments.

---

I have 1 class `App\Service\CommonService`, which requires only a single (string) argument `$secret`.

```php
<?php

declare(strict_types=1);

namespace App\Service\CommonService;

final class CommonService
{    
    public function __construct(
        private readonly string $secret
    ) {
    }
}
```

Now I want to create 2 services based on this class and use it in the controller `App\Service\MainController`.

```php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Service\CommonService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    public function __construct(
        private readonly CommonService $commonServiceAdmin,
        private readonly CommonService $commonServiceUser,
    ) {
    }
}
```

So when it comes to configuring, looking at the documentation, I thought the [following example](https://symfony.com/doc/current/service_container.html#explicitly-configuring-services-and-arguments) comes quite close to what I think I want to accomplish.

```yaml
parameters:
  secret.admin: '%env(SECRET_ADMIN)%'
  secret.user: '%env(SECRET_USER)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $messengerAuditLogger: '@monolog.logger.messenger_audit'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  # It concerns this part here:
  common.service.admin:
    class: App\Service\CommonService
    arguments:
      - '%secret.admin%'
   
  App\Service\CommonService: '@common.service.admin'
```

If I understand it correctly, right now `App\Service\CommonService` will always point to `common.service.admin`. Okay, so this works for just the one service, but how should I go about for the second one then (?)

```yaml
  common.service.admin:
    class: App\Service\CommonService
    arguments:
      - '%secret.admin%'
   
  App\Service\CommonService: '@common.service.admin'

  common.service.user:
    class: App\Service\CommonService
    arguments:
      - '%secret.user%'
   
  App\Service\CommonService: '@common.service.user'
```

Well the above doesn't work, as `App\Service\CommonService` can't be defined two times like so. Okay, understandable. 
Now I thought maybe this would work:

```yaml
  common.service.admin:
    class: App\Service\CommonService
    arguments:
      - '%secret.admin%'
   
  App\Service\CommonService $commonServiceAdmin: '@common.service.admin'

  common.service.user:
    class: App\Service\CommonService
    arguments:
      - '%secret.user%'
   
  App\Service\CommonService $commonServiceUser: '@common.service.user'
```

Now this doesn't work which throws me autowire exception regarding the type-hinted string.

```
Cannot autowire service "App\Service\CommonService": argument "$secret" of method "__construct()" is type-hinted "string", you should configure its value explicitly.
```

So I though maybe this then:

```yaml
  common.service.admin:
    class: App\Service\CommonService
    arguments:
      - '%secret.admin%'

  common.service.user:
    class: App\Service\CommonService
    arguments:
      - '%secret.user%'
   
  App\Controller\MainController:
    class: App\Controller\MainController
    bind:
      $commonServiceAdmin: '@common.service.admin'
      $commonServiceUser: '@common.service.user'
```

Resulting in the same exception.

---

I'm at a loss on what to do next, as I can't seem to find anymore examples in the docs or SymfonyCast that come close to what I'm trying to accomplish. 

Any examples and/or explanation on what I'm possible misunderstanding would be very much appreciated 🙂 

---
Version: Symfony 6.1.6
PHP: 8.1.10

**Comment by ahundiak** [comment, marked as answer]
You were so close.  You just forgot to exclude your class from autowire:
```
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Service/CommonService.php'
```
Autowire does not care that you are manually define services with the class.  It still wants to autowire it.

After that, your named aliases:
```
    App\Service\CommonService $commonServiceAdmin: '@common.service.admin'
    App\Service\CommonService $commonServiceUser:  '@common.service.user'
```
Should work as desired.  No need for additional binding or whatever.

**Reply by ToshY** [reply]
@ahundiak I can't thank you enough 😄 This actually works like a charm.

After your response I realised there seems to be 2 approaches to this:

1. Like you stated, either putting class it in the `exclude` of `App\` to disable autowiring. This also allows the use of `bind` instead of `arguments` in the service alias as well.

```yaml
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'
      - '../src/Service/CommonService.php'

  common.service.admin:
    class: App\Service\CommonService
    bind:
      $secret: '%secret.admin%'
   
  App\Service\CommonService $commonServiceAdmin: '@common.service.admin'

  common.service.user:
    class: App\Service\CommonService
    bind:
      $secret: '%secret.user%'
   
  App\Service\CommonService $commonServiceUser: '@common.service.user'
```

2. Use the `autowire: false` on the service alias itself and use `arguments` instead.

```yaml
  common.service.admin:
    class: App\Service\CommonService
    autowire: false
    arguments:
      - '%secret.admin%'
   
  App\Service\CommonService $commonServiceAdmin: '@common.service.admin'

  common.service.user:
    class: App\Service\CommonService
    autowire: false
    arguments:
      - '%secret.user%'
   
  App\Service\CommonService $commonServiceUser: '@common.service.user'
```
