### DISCUSSION TITLE
Override logger in listener with abstract parameter

### DISCUSSION THREAD

**Discussion by annuh** [symfony/symfony#48134] [Q&A]
Hi,

I'm trying to pass a customer logger to the `SendFailedMessageForRetryListener` which should log the "Sending for retry..." messages with a lower severity.

This listener is configured with an abstract service locator (first constructor argument) and therefore I don't know how to configure this service properly.

Related Symfony source code:
- https://github.com/symfony/messenger/blob/6.1/EventListener/SendFailedMessageForRetryListener.php#L42
- https://github.com/symfony/framework-bundle/blob/6.1/Resources/config/messenger.php#L163
- https://github.com/symfony/framework-bundle/blob/6.1/DependencyInjection/FrameworkExtension.php#L2171

Here is the output from the `debug:container` command:
```
❯ php bin/console debug:container messenger.retry.send_failed_message_for_retry_listener  --show-arguments

Information for Service "messenger.retry.send_failed_message_for_retry_listener"
================================================================================

 ---------------- ----------------------------------------------------------------------------- 
  Option           Value                                                                        
 ---------------- ----------------------------------------------------------------------------- 
  Service ID       messenger.retry.send_failed_message_for_retry_listener                       
  Class            Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener  
  Tags             kernel.event_subscriber                                                      
                   monolog.logger (channel: messenger)                                          
  Public           no                                                                           
  Synthetic        no                                                                           
  Lazy             no                                                                           
  Shared           yes                                                                          
  Abstract         no                                                                           
  Autowired        no                                                                           
  Autoconfigured   no                                                                           
  Arguments        Service(.service_locator.cz2Dkuv)                                            
                   Service(messenger.retry_strategy_locator)                                    
                   Service(monolog.logger.messenger)                                            
                   Service(debug.event_dispatcher)
```

So far I have the following:
```yaml
# services.yaml
    messenger.muted_failed_message_logger :
        class: App\Logger\MutedLogger

    Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener:
        arguments:
            $sendersLocator: !abstract senders service locator # this is not working
            $retryStrategyLocator: '@messenger.retry_strategy_locator'
            $logger: 'messenger.muted_failed_message_logger'
            $eventDispatcher: '@event_dispatcher'
```

Can you help me configure this listener properly? Or should I another solution to use a different logger for this listener?
Thanks!
