### DISCUSSION TITLE
Symfony 6 seems to ignore the security.yaml

### DISCUSSION THREAD

**Discussion by ManuelSagorski** [symfony/symfony#48153] [Q&A]
I have the problem that on my new symfony 6 installation the login does not work. – It’s my first attempt to use symfony…

I installed the security-bundle (`composer require symfony/security-bundle`), and I’m using the default configuration.

This is what my security.yaml is looking like (app\config\packages\security.yaml):

```
security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      form_login:
        login_path: app_login
        check_path: app_login
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
      guard:
        authenticators:
          - App\src\Security\LoginFormAuthenticator
        # where to redirect after logout
        # target: app_any_route

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#the-firewall

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
  # - { path: ^/admin, roles: ROLE_ADMIN }
  # - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
    # By default, password hashers are resource intensive and take time. This is
    # important to generate secure password hashes. In tests however, secure hashes
    # are not important, waste resources and increase test times. The following
    # reduces the work factor to the lowest possible values.
```

But the authentication does not work because symfony always trys to use the users_in_memory Provider to authenticate users.

When I'm making a `debug:config security` on the console I'm getting the following result:

```
Current configuration for extension with alias "security"
=========================================================

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            migrate_from: {  }
            hash_algorithm: sha512
            key_length: 40
            ignore_case: false
            encode_as_base64: true
            iterations: 5000
            cost: null
            memory_cost: null
            time_cost: null
    providers:
        users_in_memory:
            memory:
                users: {  }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            methods: {  }
            user_checker: security.user_checker
            stateless: false
            lazy: false
            required_badges: {  }
        main:
            lazy: true
            provider: users_in_memory
            logout:
                path: app_logout
                csrf_parameter: _csrf_token
                csrf_token_id: logout
                target: /
                invalidate_session: true
                delete_cookies: {  }
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            methods: {  }
            security: true
            user_checker: security.user_checker
            stateless: false
            required_badges: {  }
    access_control: {  }
    access_denied_url: null
    session_fixation_strategy: migrate
    hide_user_not_found: true
    erase_credentials: true
    enable_authenticator_manager: true
    access_decision_manager:
        allow_if_all_abstain: false
        allow_if_equal_granted_denied: true
    role_hierarchy: {  }
```

So he completly ignores my security.yaml file... Can anyone tell me where I'm wrong??
