### DISCUSSION TITLE
[Messenger][amqp] Use the flag AMQP_AUTOACK

### DISCUSSION THREAD

**Discussion by Txemens** [symfony/symfony#48236] [Q&A]
Hello all,

Is there an option to use AMQP_AUTOACK when you get the events from the queue? 

In a context, I have  a queue that runs for a long time. And could be nice If just getting the message from the queue, send the ack.

Maybe could works like:

```yaml
    transports:
      async:
        ...
        options:
          ...
          queues:
            q.queue:
              binding_keys: [ 'routingKey' ]
              flags: AMQP_AUTOACK
```
later, in connection something like that 
```php
# \Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::get
   /**
     * Gets a message from the specified queue.
     *
     * @throws \AMQPException
     */
    public function get(string $queueName, $flag = AMQP_NOPARAM): ?\AMQPEnvelope
    {
        ...
        if (false !== $message = $this->queue($queueName)->get($flag)) {
            return $message;
        }

        return null;
    }

```
and, if the queue is AUTOACK not send the ACK when is handled or mark the queue with NoAutoAckStamp::class

I could do some PR but first I need to know if this is possible.

Many thanks
