### DISCUSSION TITLE
How to use switch user with a custom authenticator (pre-authenticated SSO user)?

### DISCUSSION THREAD

**Discussion by cctgteddy** [symfony/symfony#48317] [Q&A]
Hi, my organization uses Apereo CAS for SSO.  In the past I've used [BeSimpleSsoAuthBundle](https://github.com/BeSimple/BeSimpleSsoAuthBundle) (stopped working after Symfony 2), and [PRayno/CasAuthBundle](https://github.com/PRayno/CasAuthBundle) which kinda works on Symfony 5 but doesn't seem to be actively developed anymore.

After the above two bundles I decided to just write my authenticator which wraps around the official [phpCAS](https://github.com/apereo/phpCAS) library which we utilize for non-Symfony apps. 

Below is my custom authenticator and security.yaml file with my org name replaced with Acme.  We have a shared bundle that we install via a local composer repository in all of our apps. 

Interestingly, the switch user DOES work but it doesn't stick.  I have intercept redirects turned on.  Adding the ?_switch_user=targetuser to the URL brings me to the intercepted redirect page but then when I continue I'm back to my original user.

I've tried monkeying around by adding the RememberMe badge but has not assisted.

```php
<?php

declare(strict_types=1);

namespace Acme\AcmeBundle\Security;

use phpCAS;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\RememberMeBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\SelfValidatingPassport;

/**
 * Authenticates to the  CAS Server.
 */
class CasAuthenticator extends AbstractAuthenticator
{
    public function supports(Request $request): ?bool
    {
        return true;
    }

    public function authenticate(Request $request)
    {
        phpCAS::client(CAS_VERSION_2_0, 'cas-hostname', 443, '/cas');
        phpCAS::setNoCasServerValidation();
        phpCAS::handleLogoutRequests(true);
        phpCAS::forceAuthentication();

        $userBadge = new UserBadge(phpCAS::getUser());
        $passport = new SelfValidatingPassport($userBadge);
        $passport->addBadge(new RememberMeBadge());

        return $passport;
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        return new Response('<!doctype html><html><head></head><body>Unauthorized</body></html>', Response::HTTP_UNAUTHORIZED);
    }
}
```

```yaml
security:
    enable_authenticator_manager: true
    providers:
        acme:
            id: acme.user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: true
            lazy: true
            custom_authenticators:
                - acme.cas_auth
```

This is showing that the switch user does work briefly.  Screenshot from the profiler bar during the intercepted redirect.
![image](https://user-images.githubusercontent.com/60752051/203865339-65658474-6804-4db2-ba0c-b28a2a18f10a.png)
