### DISCUSSION TITLE
About symfony new bundle system

### DISCUSSION THREAD

**Discussion by langziyang** [symfony/symfony#48465] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/2345387/205468344-8fe31748-fd84-4705-9826-bf82fd5f3c39.png)

for new bundle system, the config/ is outside  src/ 

blog/config/services.yaml
```
services:

  Jinber\Blog\Controller\BlogController:
    autoconfigure: true
    autowire: true
    tags:
      - { name: controller.service_arguments}

  Jinber\Blog\EventSubscriber\RequestSubscriber:
    tags:
      - { name: kernel.event_subscriber}

  Jinber\Blog\EventSubscriber\ResponseListener:
    tags:
      - { name: kernel.event_listener, event: 'kernel.response', method: onResponse}
```
  
blog/config/routing.yaml
```
jinber_blog_list:
  path: /blog
  controller: Jinber\Blog\Controller\BlogController::list
```

the RequestSubscriber and ResponseListener is work fine.

now,i add routing.yaml to symfony project config/routes.yaml

```
jinber_blog:
    resource: '@JinberBlogBundle/../config/routing.yaml'
```
 i get this error:
![image](https://user-images.githubusercontent.com/2345387/205468422-db8b6c9d-3bc6-4d85-beca-c1d356373732.png)

if i move blog/config/routing.yaml to blog/Resource/config/routing.yaml
and change symfony project/config/routes.yaml like:

```
jinber_blog:
    resource: '@JinberBlogBundle/Resource/config/routing.yaml'
```

then the route is work fine.

and according to the symfony bundle doc:

```
// src/AcmeTestBundle.php
namespace Acme\TestBundle;

use Symfony\Component\HttpKernel\Bundle\AbstractBundle;

class AcmeTestBundle extends AbstractBundle
{
}
```
if i  change extends Bundle to extends AbstractBundle
subscriber and controller not work

so i have two questions

1: extends Bundle or extends AbstractBundle?

2: bundle/config/ or bundle/Resource/config/

which one is correct？
