### DISCUSSION TITLE
[RateLimiter][ServiceContainer] Configure `RateLimiterFactory` with PHP 8 attribute

### DISCUSSION THREAD

**Discussion by keichinger** [symfony/symfony#48640] [Q&A] [answered]
### Description

Currently, the docs define that you need to name your argument in camelCase to match the underlying `rate_limiter` configuration (see https://symfony.com/doc/current/rate_limiter.html#rate-limiting-in-action). In my opinion, this comes with a few problems:

- It's not very refactoring friendly
- The name of the variable is directly tied to an underlying, hidden system
- Some developers who don't know about this, may accidentally break it due to the nature of this auto-wiring magic
- There is no clear relationship between the `RateLimiterFactory` and the config that is being used

Which is why I'd like to propose a new PHP 8 attribute `RateLimiter`, which will take care of wiring up the `RateLimiterFactory` with its corresponding configuration. Users could still opt-in for the naming convention if they'd like and enjoy the convenience, or make it more explicit and gain some other benefits for free.

What do you think?

#### Config

```yaml
# config/packages/rate_limiter.yaml
framework:
    rate_limiter:
        anonymous_api:
            # use 'sliding_window' if you prefer that policy
            policy: 'fixed_window'
            limit: 100
            interval: '60 minutes'
        authenticated_api:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }
```

#### Usage

```php
// src/Controller/ApiController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException;
use Symfony\Component\RateLimiter\RateLimiterFactory;

class ApiController extends AbstractController
{
    public function index(
        Request $request,
        #[RateLimiter("anonymous_api")]
        RateLimiterFactory $limiter
    )
    {
        // do something with $limiter
    }
}

```
