### DISCUSSION TITLE
Messenger AMQP RabbitMQ Queue A works, Queue B with same connection doesn't. Why?

### DISCUSSION THREAD

**Discussion by jerrac** [symfony/symfony#48648] [Q&A]
Hey all,
I'm not even sure what to search on for this one. So far my queries have not found anything similar.

To sum up my issue, one queue works just fine, the other one doesn't. The only difference between the two is the queue name... Exact same connection info. Yet queue B gives me `Could not connect to the AMQP server. Please verify the provided DSN.` error.

I'm in dev here, so no issue sharing my config:

.env:
```
INCOMING_QUEUE_DSN=amqp://guest:guest@127.0.0.1:9264/%2f/incoming_queue
OUTGOING_QUEUE_DSN=amqp://guest:guest@127.0.0.1:9264/%2f/outgoing_queue
LOG_QUEUE_DSN=amqp://guest:guest@127.0.0.1:9264/%2f/log_queue
EXAMPLE_TARGET_QUEUE_DSN=amqp://guest:guest@127.0.0.1:9264/%2f/example_target_queue
```
messenger.yaml:
```yaml
framework:
  messenger:
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'
      log_queue:
        dsn: '%env(LOG_QUEUE_DSN)%'
        options:
          auto_setup: true
          persistent: true
      incoming_queue:
        dsn: '%env(INCOMING_QUEUE_DSN)%'
        options:
          auto_setup: true
          persistent: "true"
      outgoing_queue:
        dsn: '%env(OUTGOING_QUEUE_DSN)%'
        options:
          auto_setup: true
          persistent: "true"
      example_target_queue:
        dsn: '%env(EXAMPLE_TARGET_QUEUE_DSN)%'
        options:
          auto_setup: true
          persistent: "true"

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async
      App\Message\IncomingMessage: incoming_queue
      App\Message\OutgoingMessage: outgoing_queue
      App\Message\AuditLogMessage: log_queue
      App\Message\Target\ExampleTargetMessage: example_target_queue

      # Route your messages to the transports
      # 'App\Message\YourMessage': async
```

`incoming_queue` and `log_queue` both work just fine. `outgoing_queue` does not work.

`example_target_queue` would be hit after `outgoing_queue` so I have no idea if it is working or not.

dev.log has messages like (the location data at the bottom is randomly generated.):
```
[2022-12-14T07:25:47.354979-08:00] messenger.INFO: Sending message App\Message\OutgoingMessage with outgoing_queue sender using Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpTransport {"class":"App\\Message\\OutgoingMessage","alias":"outgoing_queue","sender":"Symfony\\Component\\Messenger\\Bridge\\Amqp\\Transport\\AmqpTransport"} []
[2022-12-14T07:25:47.357386-08:00] app.ERROR: Failed to process incoming data. Exception thrown. {"type":"Exception","msg":"Could not connect to the AMQP server. Please verify the provided DSN.","trace":"
#0 /path/to/project/vendor/symfony/amqp-messenger/Transport/AmqpTransport.php(75): Symfony\\Component\\Messenger\\Bridge\\Amqp\\Transport\\AmqpSender->send()\n
#1 /path/to/project/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(66): Symfony\\Component\\Messenger\\Bridge\\Amqp\\Transport\\AmqpTransport->send()\n
#2 /path/to/project/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n
#3 /path/to/project/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(61): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n
#4 /path/to/project/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n
#5 /path/to/project/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n
#6 /path/to/project/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(43): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n
#7 /path/to/project/vendor/symfony/messenger/MessageBus.php(73): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n
#8 /path/to/project/vendor/symfony/messenger/TraceableMessageBus.php(41): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n
#9 /path/to/project/src/Logging/Logger.php(111): Symfony\\Component\\Messenger\\TraceableMessageBus->dispatch()\n
#10 /path/to/project/src/EventSubscriber/FieldEventSubscriber.php(52): App\\Logging\\Logger->info()\n
#11 /path/to/project/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): App\\EventSubscriber\\FieldEventSubscriber->onAcIncomingChangeField()\n
#12 /path/to/project/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke()\n
#13 /path/to/project/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()\n
#14 /path/to/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(153): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n
#15 /path/to/project/src/Processor/Core/IncomingProcessor.php(322): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch()\n
#16 /path/to/project/src/MessageHandler/IncomingMessageHandler.php(78): App\\Processor\\Core\\IncomingProcessor->process()\n
#17 /path/to/project/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(97): App\\MessageHandler\\IncomingMessageHandler->__invoke()\n
#18 /path/to/project/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(71): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n
#19 /path/to/project/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n
#20 /path/to/project/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n
#21 /path/to/project/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n
#22 /path/to/project/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n
#23 /path/to/project/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(43): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n
#24 /path/to/project/vendor/symfony/messenger/MessageBus.php(73): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n
#25 /path/to/project/vendor/symfony/messenger/TraceableMessageBus.php(41): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n
#26 /path/to/project/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\TraceableMessageBus->dispatch()\n
#27 /path/to/project/vendor/symfony/messenger/Worker.php(156): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n
#28 /path/to/project/vendor/symfony/messenger/Worker.php(105): Symfony\\Component\\Messenger\\Worker->handleMessage()\n
#29 /path/to/project/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(232): Symfony\\Component\\Messenger\\Worker->run()\n
#30 /path/to/project/vendor/symfony/console/Command/Command.php(308): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n
#31 /path/to/project/vendor/symfony/console/Application.php(1032): Symfony\\Component\\Console\\Command\\Command->run()\n
#32 /path/to/project/vendor/symfony/framework-bundle/Console/Application.php(94): Symfony\\Component\\Console\\Application->doRunCommand()\n
#33 /path/to/project/vendor/symfony/console/Application.php(301): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n
#34 /path/to/project/vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\\Component\\Console\\Application->doRun()\n
#35 /path/to/project/vendor/symfony/console/Application.php(171): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n
#36 /path/to/project/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\\Component\\Console\\Application->run()\n
#37 /path/to/project/vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\ConsoleApplicationRunner->run()\n
#38 /path/to/project/bin/console(11): require_once('...')\n
#39 {main}","data":{"sourceName":"example_csv","uniqueKeyFieldName":"example_csv_guid","uniqueKeyFieldValue":"9524E1EA-682F-1EE4-98FA-2458FF4E1F44","fieldValue":{"address_lines":["Ap 
#114-5385 Egestas. Rd.","Ap 
#206-5439 Purus St."],"city":"Mexicali","postal_code":"448434","country":"Bhutan"},"fieldName":"location"}} []
```

All I see in rabbitmq's logs are lines like:
```
rabbitmq  | 2022-12-14 15:25:46.409261+00:00 [info] <0.698.0> accepting AMQP connection <0.698.0> (172.18.0.1:45414 -> 172.18.0.3:5672)
rabbitmq  | 2022-12-14 15:25:46.410481+00:00 [info] <0.698.0> connection <0.698.0> (172.18.0.1:45414 -> 172.18.0.3:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq  | 2022-12-14 15:25:46.711048+00:00 [info] <0.698.0> closing AMQP connection <0.698.0> (172.18.0.1:45414 -> 172.18.0.3:5672, vhost: '/', user: 'guest')
```
RabbitMQ is in a container. And I have tried restarting it. Though I haven't tried clearing out the persistence data yet. Not sure it would mean anything since I don't see any authentication errors in the logs...

Anyone have any ideas?
