### DISCUSSION TITLE
Optimize asset management in the `framework-bundle`?

### DISCUSSION THREAD

**Discussion by evertharmeling** [symfony/symfony#48778] [Q&A]
I'm wondering if we could optimize the functionality in the `symfony/framework-bundle` on the `assets` part.

Current as per the [docs](https://symfony.com/doc/current/reference/configuration/framework.html#assets); you may either define the `base_path` OR `base_url` as when defining both would throw an [error](https://github.com/symfony/framework-bundle/blob/6.2/DependencyInjection/FrameworkExtension.php#L1256).

Because I would love to see the following example being possible:

```yaml
# config/packages/framework.yaml
framework:
    assets:
        base_urls:
            - 'https://assets.mydomain.tld'
        base_path: '/uploads'
        packages:
            blog_article:
                base_path: '/blog-article'
                base_url: 'https://assets2.mydomain.tld'
            blog_article_thumb:
                base_path: '/blog-article/thumb'
```
Having `base_path` next to `base_url` is discussable, but having `base_url` in the root and `base_path` in the package seems like a winner to me.

```twig
...
<img src="{{ asset('article_1.jpg', 'blog_article_thumb') }}"/>
...
```
Which would result in `<img src="https://assets.mydomain.tld/uploads/blog-article/thumb/article_1.jpg"/>`

Currently the above could only be done via 
```yaml
framework:
    assets:
        base_urls:
            - 'https://assets.mydomain.tld' # or define per package
```
```twig
...
# base url is handled via the config, but the path needs to be added every time, this is cumbersome and sensitive to errors and more error prone when refactoring
<img src="{{ asset('uploads/blog-article/thumb/article_1.jpg') }}"/>
...
```
OR
```yaml
framework:
    assets:
        packages:
            blog_article:
                base_path: '/blog-article'
            blog_article_thumb:
                base_path: '/blog-article/thumb'
```
```twig
...
# base path is handled via the config, but the base url needs to be added every time, this is cumbersome and sensitive to errors and more error prone when refactoring
<img src="{{ 'https://assets.mydomain.tld' ~ asset('uploads/blog-article/thumb/article_1.jpg', 'blog_article_thumb') }}"/>
...
```
OR you could introduce a new custom `Twig`-function in your project, which handles some config for you, but it's partly already there in the `asset()` `Twig`-function.

Is there a (technical) reason why we would not allow defining both? Or anybody for or against this approach, would love to hear it. Could give a go on implementing this if wanted.

Edit: 
Just found out that the versioning (when using `webpack` for example is bypassed when using 'full urls'. Which is kinda logical, however when you would like to use a dedicated CDN for your assets, it could still be valid to have them versioned. It would only make sense to make use of the `asset()` function when the assets are externally to ease on the configuration. Maybe a workaround would be to add a `versioned` option (which is `false` by default to remain BC)

**Comment by MatTheCat** [comment]
> having `base_url` in the root and `base_path` in the package seems like a winner to me.

The root configuration is the default package’s, not one you can inherit from.

> Having `base_path` next to `base_url` is discussable

You can put a path in a URL, so your example would be written

```yaml
# config/packages/framework.yaml
framework:
    assets:
        base_urls: 'https://assets.mydomain.tld/uploads'
        packages:
            blog_article:
                base_urls: 'https://assets2.mydomain.tld/blog-article'
            blog_article_thumb:
                base_urls: 'https://assets.mydomain.tld/blog-article/thumb'
```
