### DISCUSSION TITLE
HTTP Client using Operating System proxy

### DISCUSSION THREAD

**Discussion by Cyanat** [symfony/symfony#49020] [Q&A] [answered]
Hello!
I try to use an http client using a proxy. Using this declaration is working:
```
http_client:
    scoped_clients:
        mytest.client:
            base_uri: "%env(mytest)%"
            proxy: 'http://my.proxy.com:3128'
```

However, i read in the [documentation](https://symfony.com/doc/current/http_client.html#http-proxies) that

> By default, this component honors the standard environment variables that your Operating System defines to direct the HTTP traffic through your local proxy.

So I have modified my http client definition as follows:
```
http_client:
    scoped_clients:
        mytest.client:
            base_uri: "%env(mytest)%"
```
and try to configure proxy on the OS side. My app is running on a Windows server. For me, to set a proxy in a Windows, we have to use "Internet Options", panel "Connections". However, this create no environment variables, and so my http client isn't using a proxy but directly call the requested URL.
How can I define a proxy in a Windows OS in order to be taken in account in my Symfony HTTP client?
Thanks!
