### DISCUSSION TITLE
EnvVarProcessor - nullable env

### DISCUSSION THREAD

**Discussion by Hricer** [symfony/symfony#49037] [Q&A]
```` yaml
parameters:
    env(SOME_ENV): ~ // SOME_ENV is null

    bar: '%env(int:SOME_ENV)%' // null
    bar: '%env(string:SOME_ENV)%' // null
    bar: '%env(bool:SOME_ENV)%' // null
    bar: '%env(not:SOME_ENV)%' // null
    bar: '%env(float:SOME_ENV)%' // null
    bar: '%env(const:SOME_ENV)%' // null
    bar: '%env(base64:SOME_ENV)%' // null
    bar: '%env(json:SOME_ENV)%' // null
    bar: '%env(resolve:SOME_ENV)%' // null
    bar: '%env(csv:SOME_ENV)%' // null
    bar: '%env(shuffle:SOME_ENV)%' // null
    bar: '%env(file:SOME_ENV)%' // Invalid file name: env var "SOME_ENV" is non-scalar.
    bar: '%env(require:SOME_ENV)%' // Invalid file name: env var "SOME_ENV" is non-scalar.
    bar: '%env(trim:SOME_ENV)%' // null
    bar: '%env(default::SOME_ENV)%' // null
    bar: '%env(url:SOME_ENV)%' // null
    bar: '%env(query_string:SOME_ENV)%' // null
    bar: '%env(enum:App\Enum\MyEnum:SOME_ENV)%' // error: Resolved value of "SOME_ENV" did not result in a string or int value.
````

Why `file`, `require` and `enum` behave differently? Or how do them nullable?

**Comment by MatTheCat** [comment]
Well `file` and `require` require a file name, and `enum` requires a `BackedEnum` FQCN. If you want to get `null`, just don’t use them?

**Comment by Hricer** [comment]
@MatTheCat example for enum:

```` yaml
parameters:
    env(APP_SSO): ~
    sso: '%env(enum:App\Enum\SingleSignOn:APP_SSO)%'
````

```` php
namespace App\Enum;

enum SingleSignOn: string
{
    case OAUTH = 'oauth';
    case SAML = 'saml';
}
````

.env
```` env
APP_SSO=oauth // Ok
APP_SSO=saml  // Ok
APP_SSO=      // Not ok, but empty value (or omit variable) means no active SSO
````

In my opinion, the enum processor should return null if env is null. Just like other env processors (int, bool, json, url, base64 etc.).
