### DISCUSSION TITLE
[Messenger] BusNameStamp is not resseted when the message enters in a different bus

### DISCUSSION THREAD

**Discussion by dem3trio** [symfony/symfony#49204] [Q&A] [answered]
Hi, I have an issue but I don't know how to solve it with my current configuration. 

I have a quite complex configuration between symfony messenger and rabbit mq.

I am using the rabbitmq Shovel plugin to duplicate the messages that enter an exchange to other virtualhosts, to process them in other applications.

I have multiple buses declared:

```
framework:
     messenger:
        default_bus: event.bus
        failure_transport: failed

        buses:
            command.bus:
                default_middleware: true
                middleware:
                   .... specific of middleware for commands ...
            query.bus:
                default_middleware: true
                middleware:
                   .... specific of middleware for queries ...
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                          .... specific of middleware for commands ...
            broker.bus:
                default_middleware: allow_no_handlers
                middleware:
                          .... specific of middleware for this bus ...

```

The commands and events that must go to a transport, we put them in the "broker bus", which also has specific middleware for traceability.

So the broker bus sends the commands and events.

I am not interested in putting the commands and events in their respective buses from the beginning because there are middlewares that would be running unnecessarily (like doctrine's transaction middleware) when the message is going to be sent to a transport. In addition, all messages that enter here are forced to be treated synchronously.

Then I consume the events and commands from rabbit and put them in the specific bus.

The problem comes when the message processing fails after the corresponding retries.

The message is stored in the database, via the doctrine transport. Here the message has the BusNameStamp, but with the "broker.bus".

So if I retry the message from the `messenger:failed:retry` command, it would be thrown back to the "broker.bus", therefore:
- The traceability middlewares would be executed (duplicating information).
- And also (and this is worse), having the rabbit mq "shovel" plugin activated, the message would be sent again to the exchange, and it could duplicate information in other systems.

I have tried to put a middleware in the event and command buses to remove the BusNameStamp and change it for another one. But I have seen that when a message fails, any stamps added during execution are ignored.

Does anyone know what I can do?

Thanks!
