### DISCUSSION TITLE
Options to catch NotFoundHttpException

### DISCUSSION THREAD

**Discussion by kAlvaro** [symfony/symfony#49307] [Q&A] [answered]
We're using Symfony/4.4 (to be upgraded later this year). Invalid URL requests end up in our logs as uncaught exceptions (and also submitted to Sentry):

> request.ERROR Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /this-page-does-not-exist/"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136

It's fine to have them logged so we can investigate, but they're almost never an error on our side and we're afraid they can mask actual errors. I've found two ways to have a custom log entry (event subscriber and listener both work for that) but I still get the default uncaught exception entry. The only way to avoid that is to craft a response in the subscriber/listener, but that means losing the default Twig template.

What are my options handle this? Namely:
- Get NotFoundHttpException logged as e.g. notice with a custom text.
- Make Symfony use the default templates.

**Comment by lyrixx** [comment]
You can configure monolog to ignore all 404. https://symfony.com/doc/current/logging/monolog_exclude_http_codes.html

**Reply by kAlvaro** [reply]
This looks exactly what I want, but:

> You can only use excluded_http_codes/excluded_404s with a FingersCrossedHandler definition

I currently have `type: stream`. Do I need `type: fingers_crossed`?

**Edit 1:** oh, it seems easy to set up: https://symfony.com/doc/current/logging.html

**Edit 2:** It isn't. I could use some example. My current settings are:

```yaml
monolog:
  handlers:
    file_log:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      channels: ['!event']
      formatter: Reacted\Namespace\LoggerFormatterHelper
    console:
      type: console
      channels: ['!event', '!doctrine']
```




`
