### DISCUSSION TITLE
SecurityBundle - json_login as entry_point

### DISCUSSION THREAD

**Discussion by s01cy** [symfony/symfony#49324] [Q&A]
Hi everyone!
I'm trying to set up multiple authenticators, one of the firewalls looks like this:
```
eshop:
    pattern: ^/api/v1
    provider: eshop_user_provider
    json_login:
        check_path: user_login
        username_path: email
        password_path: password
    custom_authenticators:
        - App\Security\FacebookAuthenticator
        - App\Security\GoogleAuthenticator
```
I need to set an entry_point here as error suggest, but when trying to set 'json_login' there, I get
` The service "security.exception_listener.eshop" has a dependency on a non-existent service "json_login". Did you mean this: "security.authenticator.json_login.eshop"? `
When trying to use the suggested one, I get
`Argument #5 ($authenticationEntryPoint) must be of type ?Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface, Symfony\Component\Security\Http\Authenticator\JsonLoginAuthenticator given` (well, JsonLoginAuthenticator does not implement it)
Also looked there - https://symfony.com/doc/current/security/entry_point.html, _form_login_ is used without problems
Is it possible to use json_login as entry_point? Or do I need to rewrite it as a custom authenticator?
Sf 5.4.9, security bundle 5.4.9
Many thanks!
