### DISCUSSION TITLE
PDO Cache with SQLite

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#49322] [Q&A]
Instantiating the cache in a service works as expected:

```php
        $dsn = 'sqlite:/tmp/mydb.sq3';
        $cache = new PdoAdapter($dsn);
```

But I'd like to not hard-code the cache location, but when I set it up in services, it fails:

Unsupported DSN: "sqlite:/tmp/mydb.sq3".
ExceptionLogs 1Stack Trace
Symfony\Component\Cache\Exception\
InvalidArgumentException
in [vendor/symfony/cache/Adapter/AbstractAdapter.php ](https://ac.wip/_profiler/open?file=vendor/symfony/cache/Adapter/AbstractAdapter.php&line=129#line129)(line 129)

```yaml
# cache.yaml
framework:
    cache:
        default_pdo_provider: '%env(TRANSLATION_CACHE_DSN)%'
        pools:
            # creates a "custom_thing.cache" service
            translation.cache:
                adapter: cache.adapter.pdo
```

and in .env:

```
TRANSLATION_CACHE_DSN="sqlite:/tmp/mydb.sq3"
```

Seems so basic, but I'm stuck.  Thanks for any help.
