### DISCUSSION TITLE
Can't persist entity with multiple entity manager Doctrine

### DISCUSSION THREAD

**Discussion by JoDrm** [symfony/symfony#49350] [Q&A]
I follow this manual to configure my multiple entity manager: https://symfony.com/doc/current/doctrine/multiple_entity_managers.html

My manager "customer" manage entity Client who is reference for client details.

My manager "workspace" manage entity User who is reference "uuid" of Client only.

So my doctrine.yml look like this : 
```
doctrine:
  dbal:
    default_connection: customer
    types:
      datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
      datetime: \Carbon\Doctrine\DateTimeType
    connections:
      workspace:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '13'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        wrapper_class: App\Doctrine\DynamicWorkspaceConnection
        logging: false
      customer:
        # configure these for your database server
        url: '%env(resolve:DATABASE_CAS_URL)%'
        driver: 'pdo_pgsql'
        server_version: '13'
        charset: utf8
  orm:
    default_entity_manager: customer
    entity_managers:
      workspace:
        connection: workspace
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          Main:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Main'
            prefix: 'App\Entity\Main'
        filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true
          userteam_allowed:
            class: App\Filter\SQLFilter\AllowedByConnectedUserFilter
          user_allowed:
            class: App\Filter\SQLFilter\LicenceUserFilter
      customer:
        connection: customer
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          Customer:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Cas'
            prefix: 'App\Entity\Cas'

```

My security.yml look like this :

```
security:
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
  password_hashers:
    App\Entity\Cas\Client: 'auto'
  providers:
    clients:
      entity:
        class: App\Entity\Cas\Client
        manager_name: customer

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    auth:
      pattern: ^/
      stateless: true
      provider: clients
      user_checker: App\Security\Cas\ClientChecker
      entry_point: jwt
      json_login:
        check_path: login # The name in routes.yaml is enough for mapping
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~
      refresh_jwt:
        check_path: api_refresh_token
```

**Signup Case :** 

When I signup in my app I use entity manager "customer" to persist Client object in database. It's work FINE.

**Login Cas :** 

When I login in my app it use entity manager "customer" to logged user with Client object. It's work FINE.

**Using "workspace" entity manager :** 

When I try to persist any object manage by "workspace" entity manager, I have this error

`Class 'App\\Entity\\Cas\\Client' was not found in namespaces configured in string App\\Entity\\Main.`

I think it's because when I authenticate the user on my API, the entity that's used to do that is Client, and it's handled only by my "customer" entity manager.

I don't know how to handle this problem, because if I cast $security->getUser() to type User, I can't persist with client entity manager.

Can I just switch the $security->getUser() dynamically when using "customer" or "workspace" manager ?

Do I use a chained provider ? Or custom provider ? Or use custom_authenticators fields ? 

Anyone have an idea to solve this problem?
