### DISCUSSION TITLE
Symfony - switch from php-ampqlib RabbitMQ bundle to messenger - which is the way?

### DISCUSSION THREAD

**Discussion by darius1706** [symfony/symfony#49362] [Q&A] [answered]
I am trying to change switch to symfony messenger, but documentation doesnt show me way. Lets have old configuration for php-ampqlib. This is rabbit configuration and I want to have the same settings for messenger. Is it possible? If yes - how?

```
    mail_queue:
        connection: message
        exchange_options: { name: 'mail_queue', type: direct }
        queue_options: { name: 'mail_queue',arguments: { 'x-dead-letter-exchange': [ 'S', 'mail_queue_failed' ],'x-dead-letter-routing-key': [ 'S', '' ],'x-max-priority': [ 'I',10 ] } }
        callback: AppBundle\Consumer\MailQueueConsumer
        qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    mail_queue_failed:
        connection: message
        exchange_options: { name: 'mail_queue_failed', type: direct }
        queue_options: { name: 'mail_queue_failed', arguments: { 'x-message-ttl': [ 'I', 20000 ], 'x-dead-letter-exchange': [ 'S', 'mail_queue' ],'x-dead-letter-routing-key': [ 'S', '' ] } }
        callback: AppBundle\Consumer\DoingNothingConsumer
```

I have spended a lot of hours without success.

Thank you very much. D
