### DISCUSSION TITLE
Got warning: 'WARNING [cache] Failed to save key' after update doctrine configuration on Symfony 3.4

### DISCUSSION THREAD

**Discussion by aliusmn** [symfony/symfony#49550] [Q&A]
I tried updating the doctrine configuration to get rid of the deprecation warning I got. Previously my doctrine configuration was like this:

```
orm:
    entity_managers:
        default:
            metadata_cache_driver: apcu
       session:
            metadata_cache_driver: apcu
```
with this configuration there are no errors or warnings that I get. there is only a deprecation notice. then I try to update the configuration to be like this:

```
orm:
    entity_managers:
        default:
            metadata_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool

framework:
    cache:
      pools:
            doctrine.system_cache_pool:
                adapter: cache.adapter.apcu
```
and i got 'WARNING [cache] Failed to save key' when i run cli command. 

How do you deal with this problem, or do you have any advice for me?

**Comment by aliusmn** [comment]
after I debugged again for this setting
```
orm:
    entity_managers:
        default:
            metadata_cache_driver: apcu
       session:
            metadata_cache_driver: apcu
```
the metadata is not saved when running the cli command and `apc.enable_cli = 0`. that's why there is no error. but why is this setting trying to save the metadata to the cache?
```
orm:
    entity_managers:
        default:
            metadata_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool

framework:
    cache:
      pools:
            doctrine.system_cache_pool:
                adapter: cache.adapter.apcu
```
