### DISCUSSION TITLE
symfony 6 testings, dependency injection and parameters

### DISCUSSION THREAD

**Discussion by logosur** [symfony/symfony#49712] [Q&A]
Hi, 

I'm trying to build Integration tests where a service has injected parameters and dependencies.
I can't see anything related in the documentation.

I've tried my best, but by last, I'm getting errors like this:
Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The parameter "app.my_param" has a dependency on a non-existent parameter "3DAME7I9d4uA4".

I'd really appreciate any help on this matter.

```
#config\services.yaml
parameters:
    app.my_param: 'my text

App\Service\MyService:
        arguments:
            $baseUrl: '%app.my_param%'

#config\services_test.yaml
parameters:
    app.my_param: 'my text

App\Service\MyService:
        arguments:
            $baseUrl: '%app.my_param%'
```

Thanks!
