### DISCUSSION TITLE
Migrating to Attributes in Symfony 6.0 - Routing broken

### DISCUSSION THREAD

**Discussion by Aweptimum** [symfony/symfony#49723] [Q&A] [answered]
I figured attributes are in a stable enough state to just migrate everything over today with rector. Having done it, I'm now facing an issue where the routes won't load.
`Cannot load resource "../../src/Controller/". Make sure there is a loader supporting the "attribute" type.`

I replaced `annotations.yaml` with `attributes.yaml`, and this is all it contains:
```yaml
controllers:
    resource: ../../src/Controller/
    type: attribute

kernel:
    resource: ../../src/Kernel.php
    type: attribute
```

I'm pretty sure something is off with my `routes.yaml`, though. The contents don't seem right (like why does each thing have a `type` key?) but it's worked thus far (the types were of annotation).
```yaml
controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

api:
    resource: ../src/Controller/API/
    prefix: /api
    type: attribute

api_login_check:
    path: /api/login_check
```
I can't find any similar issues or a full documentation of the routing config. Any help would be much appreciated!
