### DISCUSSION TITLE
How to configure application services using  DefinitionConfigurator

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#49827] [Q&A] [answered]
Is it possible to define a configuration for an application service using the DefinitionConfigurator?

For example, suppose I wanted to move the messages from https://symfony.com/doc/current/service_container.html#creating-configuring-services-in-the-container to a configuration file:

```php
// src/Service/MessageGenerator.php
namespace App\Service;

class MessageGenerator
{
    public function getHappyMessage(): string
    {
        $messages = [
            'You did it! You updated the system! Amazing!',
            'That was one of the coolest updates I\'ve seen all day!',
            'Great work! Keep going!',
        ];

        $index = array_rand($messages);

        return $messages[$index];
    }
}
```

I want to instead have

```yaml
# config/packages/happy_message.yaml
happy_message:
    messages:
            - 'You did it! You updated the system! Amazing!'
            - 'That was one of the coolest updates I\'ve seen all day!'
            - 'Great work! Keep going!'
```

I'm missing the step of injecting the  DefinitionConfigurator during the setup and accessing it within the service.  If this were within a bundle (instead of an application service), there are lots of examples to follow.  But I'm missing the step for how to do the same thing within an application service.
