### DISCUSSION TITLE
class DoctrineProvider not found

### DISCUSSION THREAD

**Discussion by pcmanprogrammeur** [symfony/symfony#49885] [Q&A] [answered]
Hi all,
When i set environnement variable APP_ENV=prod and `composer install --no-dev --optimize-autoloader`, i have a problem with doctrine : 
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Cache\DoctrineProvider" not found in /var/www/app/var/cache/prod/ContainerCsN2fhb/App_KernelProdContainer.php:605

In my doctrine.yaml, i have :
```
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
```

What is the problem please ?

**Comment by amavis442** [comment, marked as answer]
I had the same issue when upgrading from symfony 5 to 6. If you upgraded from symfony 5 to 6.2 and still have some **/config/packages/[dev,prod,test]** dirs, remove those dirs. That fixed it for me. They now use the _when@prod_ in de _doctrine.yaml_ file, so no need for those obsolete dirs.

**Reply by yastin** [reply]
Thank you! config/packages/[dev,prod,test]  removed and system working

**Reply by faheemhameed** [reply]
Thanks a lot!! Life saver....

**Comment by pcmanprogrammeur** [comment]
Exactly,  i deleted config/prod/doctrine_mongodb.yaml file and i added this in my doctrine_mongodb.yaml :
```
when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes: false
        auto_generate_hydrator_classes: false
        document_managers:
            api:
                metadata_cache_driver:
                    type: service
                    id: doctrine_mongodb.system_cache_pool

    framework:
        cache:
            pools:
                doctrine_mongodb.system_cache_pool:
                    adapter: cache.system
```
Thank you for your help !
