### DISCUSSION TITLE
Login Link Authentication doesn't work

### DISCUSSION THREAD

**Discussion by hitriyvalenok** [symfony/symfony#49892] [Q&A]
I am trying to implement [Login Link Authentication][1]. Unfortunately, I am stuck with it. When I am following the generated link I am getting the next exception: 

> InvalidLoginLinkAuthenticationException: Login link could not be validated

authentication doesn't work too: I can't visit secured area (*IS_AUTHENTICATED*). What I am doing wrong? Thanks!

**security.yaml**
```yaml
security:
    providers:
        users_in_memory: { memory: null }
        users:
            entity:
                class: 'App\Entity\User'
                property: 'id'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            login_link:
                check_route: login_check
                signature_properties: [ 'id' ]

    access_control:
        - { path: '/secured_area', roles: IS_AUTHENTICATED }
```

**LoginController.php**
```php
class LoginController extends AbstractController
{
    #[Route( '/login_check', name: 'login_check' )]
    public function loginCheck()
    {
        throw new \LogicException( 'This code should never be reached' );
    }

    #[Route( '/login', name: 'login' )]
    public function login( UserRepository $users, EntityManagerInterface $em,
                           LoginLinkHandlerInterface $loginLinkHandler, AuthenticationUtils $helper )
    {
        $userExisted = $users->findOneBy( [ 'id' => 771492419 ] );
        $loginLinkDetails = $loginLinkHandler->createLoginLink( $userExisted );
        $loginLink = $loginLinkDetails->getUrl();
        echo '<pre>' . $helper->getLastAuthenticationError() . '<br></pre>';
        return new Response( "<a href='{$loginLink}'>Click to authorize</a>" );
    }
}
```

  [1]: https://symfony.com/doc/current/security/login_link.html
