### DISCUSSION TITLE
Security, Custom Authenticators: how to get UserProvider?

### DISCUSSION THREAD

**Discussion by Amegatron** [symfony/symfony#50079] [Q&A] [answered]
I have a security config which defines multiple firewalls and multiple user providers. But some of the firewalls use the same custom authenticator, specified in the corresponding field, for example:

```
security:
  providers:
    provider1:
      ...
    provider2:
      ...
  firewalls:
    api1:
      ....
      custom_authenticators:
        - MyCustomAuthneticator
      provider: provider1
    api2:
      ....
      custom_authenticators:
        - MyCustomAuthneticator
      provider: provider2
```
The problem is that the corresponding UserProvider is not injected into MyCustomAuthenticator (which has UserProviderInterface in constructor). How can I get it from this custom authenticator? As I see in some authneticators shipped with symfony, they expect the UserProvider be injected, so I believe this is how it is intended to work. But are custom_authenticators a separate thing?

I'm using Symfony 6.0.
