### DISCUSSION TITLE
Own service to valueResolvers

### DISCUSSION THREAD

**Discussion by themark147** [symfony/symfony#50159] [Q&A] [answered]
Hi,

I am testing new symfony 6.3 and I really love new MapRequestPayload attribute but is there any possibility to replace Serializer in resolver: RequestPayloadValueResolver with mine own? override in services.yaml doesnt works
```
argument_resolver.request_payload:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver
        arguments:
            $serializer: '@jms_serializer.serializer'
```

thanks

**Comment by ghost** [comment, marked as answer]
you have to tag it with `controller.targeted_value_resolver` and attribute `name: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver`

**Reply by themark147** [reply]
thanks @javaDeveloperKid but still doesnt work it like that :(( Still getting error: You have requested a non-existent resolver \"Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolver\\RequestPayloadValueResolver

```
    argument_resolver.request_payload:
        class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver
        arguments:
            $serializer: '@jms_serializer.serializer'
        tags:
            - { name: 'controller.targeted_value_resolver', alias: [ name: 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver' ] }
```
