### DISCUSSION TITLE
User authentication with multiple entity managers

### DISCUSSION THREAD

**Discussion by radar3301** [symfony/symfony#50167] [Q&A] [answered]
I have the need for two entity managers/connections, one for accessing a "shared" database, and another for accessing an application specific database.

```
doctrine:
    dbal:
        connections:
            shared:
                url: '...'
            app:
                url: '...'
        default_connection: shared
    orm:
        default_entity_manager: shared
        entity_managers:
            default:
                connection: shared
                mappings:
                    SharedModel:
                        is_bundle: false
                        dir: '../vendor/path/to/shared/src/Entity'
                        prefix: 'Shared\Entity'
                        alias: SharedModel
            app:
                connection: app
                mappings:
                    AppModel:
                        is_bundle: false
                        dir: '../src/Entity'
                        prefix: 'App\Entity'
                        alias: AppModel
```

As far as I can tell, this follows the configuration outlined in [How to Work with Multiple Entity Managers and Connections](https://symfony.com/doc/current/doctrine/multiple_entity_managers.html)

I also have the following security configuration:
```
security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\AppUser
                property: name
```

However, upon submitting the login form, I get the error "The class 'App\Entity\AppUser' was not found in the chain configured namespaces Shared\Entity"

I'm not sure what I'm doing wrong... Any help?
