### DISCUSSION TITLE
Optional firewall with Auth0?

### DISCUSSION THREAD

**Discussion by edent** [symfony/symfony#50250] [Q&A]
I have a page which can be accessed by logged-in *and* logged-out users.

I've followed the [setup guide for Auth0](https://github.com/auth0/symfony) and have a firewall which looks something like this:

```yaml
providers:
        users_in_memory: { memory: null }
        auth0_provider:
            id: Auth0\Symfony\Security\UserProvider

    firewalls:
        private:
            pattern: ^/add$
            context: user
            stateless: false
            provider: auth0_provider
            custom_authenticators:
                - auth0.authenticator
        main:
            lazy: true
            provider: users_in_memory

access_control:
        - { path: ^/add$, roles: PUBLIC_ACCESS }
```

It was my understanding that `PUBLIC_ACCESS` meant that anyone could visit the page. But whenever an anonymous user opens the page, the firewall takes them through the Auth0 login process.

Once they've logged in, I can `getUser()` successfully. But I want people who aren't logged in to be able to see the page as well.

I'm using Symfony 6.2, PHP 8.1, and the latest version of the Auth0 SDK.
