### DISCUSSION TITLE
Error rendering "alerts:alert" component: Unknown component "alerts:alert". The registered components are: alert

### DISCUSSION THREAD

**Discussion by mina20088** [symfony/symfony#50336] [Q&A] [answered]
hi i have a problem in reading this component i am using namespce in here and i made a configration as the documentation said but i stil have error below are the code as shown in my screen
```php

        {{ component("alerts:alert",{
            message:"Welcome Back",
            type: 'success'
        }) }}
```
```
twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/components': 'components'
        '%kernel.project_dir%/templates/components/alert': 'alerts'

when@test:
    twig:
        strict_variables: true
```

> Error rendering "alerts:alert" component: Unknown component "alerts:alert". The registered components are: alert
