### DISCUSSION TITLE
Is there any way to modify RabbitMQ's prefetch_count using messenger?

### DISCUSSION THREAD

**Discussion by antoniovj1** [symfony/symfony#50419] [Q&A]
I've seen that the [`prefetch_count`](https://www.rabbitmq.com/consumer-prefetch.html) parameter has been removed since it was usseles but for latency reason it would be very useful for me to increase the value.

Is there a way to modify the `prefetch_count` value using the Messenger library? 
 
Its posible to implement a custom way of message fetching?

Thanks!

**Comment by ghost** [comment]
`options` key is for defining transport specific options
```yaml
framework:
    messenger:
        transports:
            my_rabbit_transport:
                dsn: my_dsn
                options:
                    exchange: ...
                    queues: ...
                    prefetch_count: 1
```
