### DISCUSSION TITLE
Monolog's non-console handlers are used in console commands

### DISCUSSION THREAD

**Discussion by someniatko** [symfony/symfony#50635] [Q&A]
Consider the following config with `symfony/monolog-bundle` installed:

```yaml
# config/packages/monolog.yaml
monolog:
    channels:
        - deprecation
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            channels: [deprecation]
            path: php://stderr
            formatter: monolog.formatter.json
```

This is similar to default `prod` environment configuration, except for missing `fingers_crossed` handler for simplicity. Notice `path` for `main` and `deprecations` is set to `php://stderr`. This is fine when executing HTTP requests. However, the very same handlers fire up when executing console commands.

Say I just execute `php bin/console` in my project in a Bash shell. Suppose there is some 3rdparty bundle with deprecations. These deprecations will show up interleaved with the actual stdout of the command. Not only that, but regular Symfony events and stuff will also show up (coming from the `main` handler this time). To filter these messages, I would have to redirect them somewhere like `php bin/console 2> /dev/null` .

But I don't want them to show up in my command's output in the first place! I only want to see the `console` handler's output, not the `main`'s or `deprecation`'s. The reason I want to see only `console` handler's messages is that I can filter them based on `-vvv` flag provided to the console command, but I cannot do it with other handlers. How can I achive that?

**Comment by someniatko** [comment]
I've tried put the `console` handler first in the list, and not to "bubble" the messages like that:

```yaml
monolog:
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            bubble: false # <-- this
```

But that didn't help neither. Other handlers are still fired. It seems console handler only is used when the appropriate `-vvv` flag is set, and logs will be silently forwarded to another handler otherwise.
