### DISCUSSION TITLE
UidProcessor monolog and custom error templates

### DISCUSSION THREAD

**Discussion by Shotman** [symfony/symfony#50803] [Q&A]
Hello, I would like to be able to display monolog's unique ID from the UidProcessor inside the Twig errors templates to help with user support, with a message along the lines of : If the problem persist contact the app admin with the code xxxx, so they can grep the log files and get more efficient.

I can already  have it in the log files with the `%%extra.uid%%` but I would also like to have it inside a custom error template (especially for error500.html.twig) but the `exception` variable inside the template doesn't have the `extra.uid` data.

Any input on what I'm doing wrong or if it's possible at all ?

services.yaml 
```yaml
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.uid%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
    Monolog\Processor\UidProcessor:
        tags:
            - { name: monolog.processor }
```

monolog.yaml
```yaml
monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [ "!event"]
            formatter: monolog.formatter.session_request
```
