### DISCUSSION TITLE
Monolog UidProcessor extra data in Twig error template

### DISCUSSION THREAD

**Discussion by Shotman** [symfony/symfony#50802] [Q&A] [answered]
Hello, 
I managed to implement monolog UidProcessor to symfony logs and by using `%%extra.uid%%` in my log string I have the unique ID on every log line but now the problem is that in my custom error pages like the official documentation says I can't get this extra data from the available `exception` twig variable. 
Doing something like `{{ exception.message }}` displays the error message but `{{ exception.extra.uid }}` gives me null and when I dump the exception in my twig template it's nowhere to be found.
I would like to be able to link that code in my exception page for support prupose, tell users : If the issue happens again please contact the app support and provide them with the code xxxx 
Any input on what I might do wrong ? 

service.yaml 
```yaml
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.uid%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
    Monolog\Processor\UidProcessor:
        tags:
            - { name: monolog.processor }
```

monolog.yaml

```yaml
monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [ "!event"]
            formatter: monolog.formatter.session_request
```
