### DISCUSSION TITLE
After Upgrade 4.3 -> 4.4 PDOSessionHandler not working

### DISCUSSION THREAD

**Discussion by lbm-services** [symfony/symfony#50835] [Q&A] [answered]
Configuration of Symfony 4.3 does not work anymore in 4.4:

`Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler::connect(): Argument #1 ($dsn) must be of type string, Doctrine\DBAL\Logging\Connection given, `

Service definition:
```
framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: 'Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler'
        cookie_lifetime: 3600
        cookie_secure: auto
        cookie_samesite: lax
```
services.yml

```
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            # see https://symfony.com/doc/master/doctrine/pdo_session_storage.html
            # If you're using Doctrine & want to re-use that connection, then:
            # comment-out the above 2 lines and uncomment the line below
            - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }
            # If you get transaction issues (e.g. after login) uncomment the line below
            - { lock_mode: 1 }
```
