### DISCUSSION TITLE
Nginx Web Server does asset react compiled files not found.

### DISCUSSION THREAD

**Discussion by chris576** [symfony/symfony#50840] [Q&A] [answered]
I am trying to develop a symfony application in a docker container with react as frontend. 

When I open the page on the browser, nothing is shown. The page source code links to the correct java script compiled files, but the web server does not find them. 

This is shown, when I try to open them from browser: 
`<!-- No route found for &quot;GET http://localhost/build/app.453344f3.js&quot; (from &quot;http://localhost/&quot;) (404 Not Found) -->`

When I log in to the nginx container via console, I do find the correct files. BUT: There are two directories (public, public/build), that should not be there and I am confused, why they are generated. 

My docker-compose file: 

```
version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    volumes:
      - shared:/var/www/html/assets/public/build:ro
    networks:
      - app-network

  assets:
    build:
      context: ./assets
      dockerfile: ../Docker/assets/Dockerfile
    volumes:
      - shared:/var/www/html/assets/public/build
    depends_on:
      php:
        condition: service_started
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - shared:/var/www/html/assets/public/build:ro
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:
  shared:

networks:
  app-network:
```

My assets docker file:

```
# Base image
FROM node:14

# Set the working directory inside the container
WORKDIR /var/www/html/assets/

COPY . .

RUN yarn install

# Set the command to run for the asset service
CMD ["yarn", "build"]
```

My php docker file: 

```
# Basisimage
FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    libicu-dev \
    libonig-dev \
    libzip-dev

# Installiere die PHP-Erweiterungen
RUN docker-php-ext-install \
    pdo_mysql \
    intl \
    zip

WORKDIR /var/www/html/

COPY . .

# Installiere Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Installiere die Composer-Abhängigkeiten
RUN composer install

# Generiere den Autoloader
RUN composer dump-autoload --optimize

# Setze die Dateiberechtigungen
RUN chown -R www-data:www-data ./var

# Exponiere den Container-Port
EXPOSE 9000

# Starte den PHP-FPM-Server
CMD ["php-fpm"]
```
