### DISCUSSION TITLE
Using CachingHttpClient in combination with ScopingHttpClient

### DISCUSSION THREAD

**Discussion by Pazns** [symfony/symfony#50984] [Q&A]
I'm trying to implement caching of third-party HTTP responses in my application, following the documentation : https://symfony.com/doc/5.4/http_client.html#caching-requests-and-responses

However, as I'm using the ScopingHttpClient system,
I can't understand how to insert properly a CachingHttpClient in the service factory chain.

Because of the way ScopingHttpClient works, constructing the host URL very late, 
the CachingHttpClient decorator must be inserted *below* it, to be able to see the host,
it must be the last decorator to ever handle the request before the actual Http transaction begins (through the Curl client for example).

I don't get it. Is it possible at all ?
I tried a few things but I don't understand what part of the container definition I should override, the ScopingHttpClient factory confuses me.

I feel like the documentation could benefit from an additional paragraph.

**Comment by MatTheCat** [comment]
I don’t understand why you’re stuck :sweat_smile: but this seems to be a use-case for [stacking decorators](https://symfony.com/doc/5.4/service_container/service_decoration.html#stacking-decorators). Does this help?

**Reply by Pazns** [reply]
I indeed use stacking decorators, stacking them on top of the scoped clients.

The issue comes from the fact the URL is unknown until the scoped client decorator is the one adding the base_uri at the end,
and therefore I need to add my CachingHttpClient decorator *below* that one.

I don't understand what to override.
I tried decorating the default "http_client" service like depicted in this old thread : https://github.com/symfony/symfony/issues/40644#issuecomment-818270405, it has no effect.

I have 45 scoped clients defined, overriding the entire service definition of each one is widely impractical.

**Reply by MatTheCat** [reply]
Oh okay I guess your issue is that you can only configure `ScopingHttpClient` from the configuration so it’s already too late to insert a `CachingHttpClient`?

You’d have to define every client yourself in that case, without relying on `framework.http_client`. Something like

```yaml
services:
    some_client:
        stack:
            - class: Symfony\Component\HttpClient\ScopingHttpClient
              factory: [Symfony\Component\HttpClient\ScopingHttpClient, forBaseUri]
              arguments:
                  - '@.inner'
                  - base_uri

            - class: Symfony\Component\HttpClient\CachingHttpClient
              arguments:
                  - '@.inner'
                  - '@http_cache.store'

            - class: Symfony\Component\HttpClient\HttpClient
              factory: [Symfony\Component\HttpClient\HttpClient, create]
```
