### DISCUSSION TITLE
Unused bind exception "inconsistency"

### DISCUSSION THREAD

**Discussion by bortomar** [symfony/symfony#51429] [Q&A]
Hi, I'm new in Symfony and I love it. I am just learning basics with  SymfonyCast which is great and very helpful. 
I noticed slight inconsistency in throwing "unused bind" exceptions.
If I define _defaults bind a service specific bind with different names in the same time, I have to use only the service specific one to avoid exception. If I remove the service specific bind, Symfony throws exception.
Is this only my misunderstanding of binding or is there any reason for this behavior?

###### (assume only DefaultController is existing in this example)
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true 
        bind:
            string $dir: '%kernel.project_dir%' 
    App\Controller\DefaultController:
        bind:
            bool $debug: '%kernel.debug%'
```

```php
class DefaultController extends AbstractController
{
    public function __construct(
        private bool $debug
    ) {
    }
}
```
###### (assume only DefaultController is existing in this example)
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true 
        bind:
            string $dir: '%kernel.project_dir%' 
```

```php
class DefaultController extends AbstractController
{
    public function __construct() {
    }
}
```
