### DISCUSSION TITLE
Route Configuration by attributes for FosRestBundle

### DISCUSSION THREAD

**Discussion by jgauthi** [symfony/symfony#51513] [Q&A]
On my current project (Symfony 6.2, FosRestBundle 3.5), I have a config file for the FosRest route:

:heavy_check_mark: Annotation version:

```yaml
# config/routes/fos_rest.yaml
api:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: /api
```

:x: I want to edit this file for attribute support, but it's not work :(.

```yaml
# config/routes/fos_rest.yaml
api:
    resource: ../../src/Controller/Api
    type: attribute
    prefix: /api

# -- OR ---
api:
  resource:
    path: ../../src/Controller/Api
    namespace: App\Controller\Api
  type: attribute
  prefix: /api
```

The symfony config/routes.yaml use the standard code from Symfony 6, [exemple](https://github.com/jgauthi/poc_symfony6_messenger/blob/a40f8cf0ab87d0456d26eac5172b8e8a04f99eb1/config/routes.yaml).

When I check with `php bin/console debug:router`, the routes does not use the Api prefix in url:

```shell
 -------------------------------- ---------- -------- ------ ----------------------------------- 
  Name                             Method     Scheme   Host   Path                               
 -------------------------------- ---------- -------- ------ -----------------------------------  
  app_api_dossierrest_getall       GET        ANY      ANY    /dossier/     <-- Instead of /api/dossier/                 
  app_api_dossierrest_getone       GET        ANY      ANY    /dossier/{id} <-- Instead of /api/dossier/{id}       
 -------------------------------- ---------- -------- ------ -----------------------------------
```

The Rest controller:

```php
<?php
// src/Controller/Api/DossierRestController.php
namespace App\Controller\Api;

use FOS\RestBundle\Controller\{AbstractFOSRestController, Annotations as Rest};
use FOS\RestBundle\View\View;
use Symfony\Component\HttpFoundation\Request;

#[Rest\Route('/dossier')]
class DossierRestController extends AbstractFOSRestController
{
    #[Rest\Get('/'), Rest\View(serializerGroups: ['Dossier'])]
    public function getAll(Request $request): View
    {
```

How to edit the "config/routes/fos_rest.yaml" file for support attributes and prefix ?

P.S: I've asked this question before on [FOSRestBundle issues](https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2394).
