### DISCUSSION TITLE
Symfony 6 - unexpected EOF when saving entity

### DISCUSSION THREAD

**Discussion by Kellorn** [symfony/symfony#51561] [Q&A]
### Symfony version(s) affected
6.3.3 and higher

### Description
I'm using Symfony server on a macbook and a postgres docker database.
Here's my docker-compose.yml : 
```
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: "${PROJECT_NAME}_postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    labels:
      com.symfony.server.service-prefix: 'DATABASE'
    ports:
      - "5432:5432"

  adminer:
    container_name: "${PROJECT_NAME}_adminer"
    image: adminer
    ports:
      - 8080:8080
    restart: always

  mailcatcher:
#    image: schickling/mailcatcher
    image: marlonb/mailcrab
    container_name: "${PROJECT_NAME}_mailhog"
    ports:
      - "1080:1080"
      - "1025:1025"
```

By submitting a form, i'm saving all datas into an entity with doctrine.
Here's my entity : 

```
class customEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $entity = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $customer_reference = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $timestamp_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comments = null;

    #[ORM\Column(length: 255)]
    private ?string $file = null;

  // With all getters and setters
```

However when I want to populate datas into my DB, "unexpected EOF" error appears.

Here's code section who generate the error : 
```
                        $customEntity = new customEntity();
                        $customEntity
                            ->setEntity('entity')
                            ->setTimestampType('type')
                            ->setTitle('title')
                            ->setName('name')
                            ->setCustomerReference('123456789')
                            ->setDate($today)
                            ->setNumber(1234)
                            ->setEmail('test@test.com')
                            ->setComments(['comments'])
                            ->setFile($file)
                        ;

                        $this->entityManager->persist($customEntity);
                        $this->entityManager->flush();
```

I tried to change some env variable as DATABASE_URL like this : 
`DATABASE_URL="postgresql://user:password@127.0.0.1:5432/db_name?serverVersion=15&charset=utf8"`

With this variable, `php bin/console doctrine:database:create` work well and init my DB.
I can even do all my migrations.
Thats why I don't think it's a connexion problem with docker.

Do you have any ideas / tips ? 

### Possible Solution

No solutions find yet

### Additional Context
php version is 8.2.9

``
