### DISCUSSION TITLE
Ability to create a custom translation provider

### DISCUSSION THREAD

**Discussion by lgreitis** [symfony/symfony#51737] [Q&A]
### Description

I've been trying to add a custom translation provider for handling translations from an external API endpoint. However, it seems that all of the translation providers seem to be hard-coded inside the Symfony framework-bundle. By adding extra code inside FrameworkExtension.php and translation_providers.php files, I've managed to run my own provider class. 

I haven't completed the implementation of the provider, it just throws a "not implemented" exception as I just tried to make a proof of concept. I probably won't go further on finishing the provider until there's an official way of creating a custom provider.

It would be great if I could simply specify the class inside the translation.yaml file to get the custom provider up and running.

Additionally, I welcome any other ideas for obtaining translations from an API endpoint.

### Example

translation.yaml
```
framework:
  default_locale: "%locale%"
  translator:
    default_path: "%kernel.project_dir%/translations/%locale%"
    fallbacks: ["%locale%"]
    providers:
      CustomProvider:
        locales: ["en", "lt"]
        domains: ["messages"]
```
