### DISCUSSION TITLE
Need help with Crowdin integration

### DISCUSSION THREAD

**Discussion by d47081** [symfony/symfony#51840] [Q&A] [answered]
Hello there, I'm beginner in Symfony and trying to export my project to Crowdin platform using `crowdin-translation-provider` by following official docs 
https://symfony.com/doc/current/translation.html#translation-providers

I have installed provider and created API keys
```
composer require symfony/crowdin-translation-provider
```

Then, generated translation files with
```
symfony console translation:extract
```
But on the final step, trying to push generated xlf files with command bellow and nothing happened on the project page (language sections still empty there),

even tool execution debug returns the 200 response codes (that means I have connected successfully)

```
php bin/console translation:push --force -vvv
15:05:57 INFO      [http_client] Request: "GET https://api.crowdin.com/api/v2/projects/.../files"
15:05:58 INFO      [http_client] Response: "200 https://api.crowdin.com/api/v2/projects/.../files"

[OK] All local translations has been sent to "crowdin" (for "fr, de, en, uk" locale(s), and "messages" domain(s)).
```

Crowdin support answered that I should upload project sources first, maybe I misunderstand the `translation:push` command?

What exactly this command do - it uploads translation meta packages generated or I really should to upload all project sources on Crowdin website manually before running `translation:push`?

**Comment by d47081** [comment, marked as answer]
Solved by providing locale code in the push command:

```
php bin/console translation:push --locales=uk
```

**Reply by d47081** [reply]
anyway, it's bit strange because locales provided in the config file by default

```
framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
            crowdin:
                dsn: '%env(CROWDIN_DSN)%'
                domains: ['messages']
                locales: ['fr', 'de', 'en', 'uk']
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
#            phrase:
#                dsn: '%env(PHRASE_DSN)%'
```
