### DISCUSSION TITLE
[Messenger] Is there a way to consume all transports without providing their names (?)

### DISCUSSION THREAD

**Discussion by VincentLanglet** [symfony/symfony#51989] [Q&A]
Hi, I'm trying a migration from enqueue (https://github.com/php-enqueue/enqueue) to symfony messenger.

When running the consumer, I was using
```
bin/console enqueue:consume
```
which was consuming all the queues, thanks to this code
https://github.com/php-enqueue/enqueue/blob/master/Symfony/Client/ConsumeCommand.php#L118-L120

When running
```
bin/console messenger:consume
```
I'm getting prompt about which transport I want to consume, isnt a way to run something like `--all` in order to consume everything ? I know I can list
```
bin/console messenger:consume foo1,foo2,...
```
but this means I have to update every time this command when I add new transport.

For the record, I'm using different transports in order to put messages in different queue, following the doc
```
framework:
    messenger:
        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: high
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: low

        routing:
            'App\Message\SmsNotification': async_priority_low
            'App\Message\NewUserWelcomeEmail': async_priority_high
```
