### DISCUSSION TITLE
Routing website in subfolder

### DISCUSSION THREAD

**Discussion by d47081** [symfony/symfony#52052] [Q&A] [answered]
My app running in web sub-folder like `domain/folder/uri`

so links generated by the `path()` method looks like `domain/uri`, without `folder` prefix

How can I properly setup  `folder` prefix for all addresses?

Thanks

**Comment by gordinskiy** [comment, marked as answer]
If the folder is the same for the entire application - "prefix" option can be used for this:
https://symfony.com/doc/current/routing.html#route-groups-and-prefixes

**Comment by d47081** [comment]
Thanks for reply, solved by `prefix: '/folder'` in `config/routes.yaml`

```
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/folder'

```
