### DISCUSSION TITLE
Symfony http client default_options are not modified by test config

### DISCUSSION THREAD

**Discussion by spolischook** [symfony/symfony#52109] [Q&A]
I have enabled `framework.http_client.default_options.retry_failed` with configuration for default configuration, and then I tried disable it in test like:
```
when@test:
    framework:
        test: true
        http_client:
            default_options:
                retry_failed: false
```
but it doesn't apply to test env, so I need to go into each individual HTTP client and disable it  
I imagine that I can enable retry only for prod, but still I would like to know why `default_options` does not merged
