### DISCUSSION TITLE
[Monolog] Passing channel name as parameter in path option

### DISCUSSION THREAD

**Discussion by SiestaCat** [symfony/symfony#52250] [Q&A]
Hello

To avoid redundancy, is possible to pass channel name as parameter in path option?

`path: "%kernel.logs_dir%/%channel%.log"`

My config:

```
group_fingers_crossed:
            type: group
            members: [fingers_crossed_syslog, fingers_crossed_stream]
        fingers_crossed_stream:
            type: rotating_file
            max_files: 50
            path: "%kernel.logs_dir%/%channel%.log"
        fingers_crossed_syslog:
            type: syslogudp
            host: '%syslog_hostname%'
            port: '%syslog_port%'
        channel1_handler:
            level: debug
            type: fingers_crossed
            handler: group_fingers_crossed
            channels: ["channel1"]
        channel2_handler:
            level: debug
            type: fingers_crossed
            handler: group_fingers_crossed
            channels: ["channel2"]
```

Thanks
