### DISCUSSION TITLE
Symfony Workflow Component with multiple status required to complete a transition

### DISCUSSION THREAD

**Discussion by deanilvincent** [symfony/symfony#52341] [Q&A] [answered]
Hi,

We're using the Symfony workflow component in our application specifically the `state machine`. Using the type `state machine`, we can prevent the changing of transition if the `currentPlace` isn't allowed to change which is perfectly working in some of our entities. But when we use the type `workflow` in a different requirement to allow multiple statuses in a property, I get an error.

Here's the sample workflow yaml.
```
framework:
  workflows:
    order_place:
      type: 'workflow'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'orderStatus'
      supports:
        - App\Entity\Order
      initial_marking: order
      places:
        - order
        - paid
        - cancel
        - refund
        - deliver
     transitions:
        ...
        to_refund:
            from: [ paid, cancel ]
            to: refund
        ...
```

The `orderStatus` is an Doctrine ORM array and it could be `["order"]` or `["paid", "cancel"]` What we want to do is, only allow the transition to `refund` if the `orderStatus` has 2 statuses present which is `["paid", "cancel"]`. I'm thinking of using `guard` for this but first, I'd like to ask if it's possible to use array as the property in symfony workflow?

I tried calling this to my service but I got an error: 
![image](https://github.com/symfony/symfony/assets/10904957/a83a361c-c844-448e-afda-c6e58e3cbff5)

Any thoughts?
