### DISCUSSION TITLE
routing.yaml for bundles with #[Route()] attributes in Controller

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#52386] [Q&A]
I'm trying to define a bundle routing file, but am getting errors.

```
Cannot load resource "{"path":"@SurvosCrawlerBundle\/src\/Controller\/","
namespace":"Survos\\CrawlerBundle\\Controller","type":"attribute","prefix":"\/crawler"}".
```

```php
// bundles.php
return [
    Survos\CrawlerBundle\SurvosCrawlerBundle::class => ['all' => true],
...
```

standard layout for the bundle, controller in vendor/survos/crawler-bundle/src/Controller/CrawlerController.php 

```php
namespace Survos\CrawlerBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CrawlerController extends AbstractController
```

```yaml
survos_crawler:
  resource:
    path: '@SurvosCrawlerBundle/src/Controller/'
    namespace: Survos\CrawlerBundle\Controller
    type: attribute
    prefix: /crawler
```

Is there a way to see what my available loader names are?  bin/console debug:twig tells me where the @SurvosCrawler path is for templates.  Gut feeling is that the path: property is wrong, but I can't figure out what it's supposed to be.  Thanks.
