### DISCUSSION TITLE
Multiple transports with custom mailer

### DISCUSSION THREAD

**Discussion by clemcoder** [symfony/symfony#52453] [Q&A]
### Symfony version(s) affected

5.4

### Description

Hello,

```
I try to have Multiple Email Transports like in the documentation : 
framework:
    mailer:
        transports:
            main: '%env(MAILER_DSN)%'
            alternative: '%env(MAILER_DSN_IMPORTANT)%'
```

It works when I use the native MailerInterface, but not with my CustomMailer who implements MailerInterface.
Even if I copy the entire Mailer class code in my CustomMailer.

Is there an other way to have a CustomMailer working with multiple transports ?
Thank you for your help.

### How to reproduce

Multiple Email Transports with CustomMailer
