### DISCUSSION TITLE
Trying to use multiple normalizers in one serializer symfonyphp.

### DISCUSSION THREAD

**Discussion by MarinosTBH** [symfony/symfony#52635] [Symfony Book: The Fast Track]
Hi, hope you are doing good! 
I'm trying to use multiple **normalizers** in my _**serializer.yaml**_ file! 
But i'm managing to only get the first normalizer in the array! any help please ? 
```
services:
  Symfony\Component\Serializer\Serializer $entitySerializer: '@app.entity.serializer'

  App\Serializer\Normalizer\ClientNormalizer:
    arguments:
      - '@App\Repository\SmartWork\ClientRepository'
      
  App\Serializer\Normalizer\OrderNormalizer:
    arguments:
      - '@App\Repository\SmartWork\OrderRepository'

  App\Serializer\Normalizer\ItemNormalizer:
    arguments:
      - '@App\Repository\SmartWork\ArticleRepository'

  app.entity.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      -
        - '@App\Serializer\Normalizer\ClientNormalizer' // this
        - '@App\Serializer\Normalizer\OrderNormalizer'
        - '@App\Serializer\Normalizer\
```

Only         - '@App\Serializer\Normalizer\ClientNormalizer' is accessed by this way and always the first element in the array gets accessed ?

And this is how i call them in my 
```
public function getByFilters(
    Request $request,
    Serializer $entitySerializer,
    CreditNoteRepository $creditNoteRepository
): JsonResponse {
    $creditNotes = $creditNoteRepository->getCreditNotes($request->query->all());
    return $this->json($entitySerializer->normalize($creditNotes)); // this 
}
```

**Comment by stof** [comment]
What is the actual issue you have ? Without an error message and without a reproducing case (which could allow us to figure out the error message, even though that would not be friendly to people helping to force them to discover the error message), there is no way for us to even know what you are having as issue (and so no way to help)

**Comment by ghost** [comment]
The code looks fine. We need more details.
Make sure the method `supportsNormalization` is implemented correctly.

**Comment by MarinosTBH** [comment]
it's like that i want to use ClientNormalizer then OrderNormalizer then ItemNormalizer and on ... 
for example : 
```
public function getByFilters(
    Request $request,
    Serializer $clientNormalizer,
    Serializer $orderSerializer,
    Serializer $itemNormalizer,
    CreditNoteRepository $creditNoteRepository
): JsonResponse {
    $creditNotes = $creditNoteRepository->getCreditNotes($request->query->all());
    
    $clientNormalization = $clientSerializer->normalize($creditNotes);
    $orderNormalization = $orderSerializer->normalize($clientNormalization);
    $itemNormalization = $itemSerializer->normalize($orderNormalization);
    
    return $this->json($itemNormalization);  
}
```
to make chainNormalizer like chainEncoder does for example 
my solution in the top does only pass by the first elemnt in the array which is ClientNormalizer

**Reply by stof** [reply]
There is no reason to run normalizers on the output of the previous normalization. That's not how things are supposed to work.

but without sharing your object structure and the implementation of normalizers, we cannot tell you what was done wrong.

**Reply by MarinosTBH** [reply]
i'm trying to simplify, just to not share bulk code : 
so this is what my normalizers structure looks like : 
ClientNormalizer : 
 ```
 <?php

namespace App\Serializer\Normalizer;

use App\Repository\SmartWork\ClientRepository;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ClientNormalizer implements NormalizerInterface
{
    use NormalizerAwareTrait;

    public function __construct(
        private readonly ClientRepository $clientRepository,
    ) {}

    public function normalize($object, string $format = null, array $context = [])
    {
        $normalizedData = normalizerObject($object);
        return $normalizedData;
    }

    private function normalizeObject(array $result): array
    {
        //Normalizer process
        return $result;
    }

    /**
     * {@inheritdoc}
     */
    public function supportsNormalization($object, string $format = null)
    {
        return true;
    }
}
```
item and order normalizer have the same structure just with different process ...

**Reply by stof** [reply]
`supportsNormalization` return `true` is the culprint. A ClientNormalizer responsible for normalizing a Client object should report support only for `$object instanceof Client`. Otherwise, it indeed has to support normalization for **anything**.
The serializer will use find the first normalizer that reports that it supports the input and use that one to perform the normalization.

**Reply by MarinosTBH** [reply]
That's true but it would be the same result 
bcz i want to pass supportNormalization and go to the next "ItemNormalizer" and later to the "ClientNormalizer" 
Like an aggregatorNormalizer that does all of them in a chain 
Searching the symfony docs i didnt find something like ChainNormalizer and i think that's not possible ? 
So i think the only solution is to do all the normalization in one Normalizer class and check manually if it is a client, an item or an order ...

**Reply by ghost** [reply]
Your ClientNormalizer has to have OrderNormalizer injected as a dependency. Then OrderNormalizer has to have ItemNormalizer injected as a dependency. Of course use NormalizerInterface as a TH.
Use them to normalize fields of type Order and Item (arrays of those I believe) respectively.

**Reply by MarinosTBH** [reply]
isn't that gonna cause a circular dependency ?
for now i used some primitive logic
```
services:
  Symfony\Component\Serializer\Serializer $clientSerializer: '@app.client.serializer'
  Symfony\Component\Serializer\Serializer $supplierSerializer: '@app.supplier.serializer'
  Symfony\Component\Serializer\Serializer $quoteSerializer: '@app.quote.serializer'
  Symfony\Component\Serializer\Serializer $orderNoteSerializer: '@app.orderNote.serializer'
  Symfony\Component\Serializer\Serializer $orderSerializer: '@app.order.serializer'
  Symfony\Component\Serializer\Serializer $itemSerializer: '@app.item.serializer'

  #Normalizers
  App\Serializer\Normalizer\ClientNormalizer:
    arguments:
      - '@App\Repository\SmartWork\ClientRepository'

  App\Serializer\Normalizer\SupplierNormalizer:
    arguments:
      - '@App\Repository\SmartWork\SupplierRepository'

  App\Serializer\Normalizer\QuoteNormalizer:
    arguments:
      - '@App\Repository\SmartWork\QuoteRepository'

  App\Serializer\Normalizer\OrderNoteNormalizer:
    arguments:
      - '@App\Repository\SmartWork\OrderNoteRepository'

  App\Serializer\Normalizer\OrderNormalizer:
    arguments:
      - '@App\Repository\SmartWork\OrderRepository'

  App\Serializer\Normalizer\ItemNormalizer:
    arguments:
      - '@App\Repository\SmartWork\ArticleRepository'

  #Serializers
  app.client.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - - '@App\Serializer\Normalizer\ClientNormalizer'

  app.quote.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - - '@App\Serializer\Normalizer\QuoteNormalizer'

  app.supplier.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - - '@App\Serializer\Normalizer\SupplierNormalizer'

  app.orderNote.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - - '@App\Serializer\Normalizer\OrderNoteNormalizer'

  app.order.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - - '@App\Serializer\Normalizer\OrderNormalizer'
  
  app.item.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - - '@App\Serializer\Normalizer\ItemNormalizer'

```

and for every normalizer class i make it this way 
```
<?php

namespace App\Serializer\Normalizer;

use App\Repository\SmartWork\OrderRepository;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class OrderNormalizer implements NormalizerInterface
{
    public function __construct(
        private readonly OrderRepository $orderRepository,
    ) {
    }

    public function normalize($object, string $format = null, array $context = [])
    {
        $type = $context['type'] ?? null;

        $transformedObject = $object;

        if (isset($object['results'])) {
            if (count($object['results']) === 0) {
                return $object;
            }

            $transformedObject['results'] = $this->transformArrayOfObject($object['results'], $type);
        } else {
            $transformedObject = $this->transformObject($object);
        }

        return $transformedObject;
    }

    /**
     * Transform object
     * 
     * @param array $object
     * @return array
     * 
     */
    private function transformObject($object): array
    {
        if (isset($object['orderId'])) {
            $object['order'] = $this->orderRepository->getOrderById($object['orderId']);
        }
        return $object;
    }

    /**
     * Normalize array of objects
     * 
     * @param array $objects
     * @return array
     * 
     */
    private function transformArrayOfObject(array $objects, $type): array
    {
        $orderIds = [];

        foreach ($objects as $object) {
            if (isset($object['orderId'])) {
                $orderIds[] = $object['orderId'];
            }
        }

        $orders = $this->orderRepository->getOrders(['type' => $type, 'orderIds' => $orderIds]);

        $transformedQuotes = array_map(function ($object) use ($orders) {
            if (!isset($object['orderId'])) {
                return $object;
            }
            return [...$object, 'order' => array_column($orders['results'], null, 'id')[$object['orderId']] ?? false];
        }, $objects);
        return $transformedQuotes;
    }

    /**
     * {@inheritdoc}
     */
    public function supportsNormalization($object, string $format = null)
    {
        return true;
    }
}
```
Calling them in the controller is like : 
```
    #[Route(path: '', name: 'app_order_get_by_filters', methods: 'GET')]
    public function getByFilters(
        Request $request,
        Serializer $itemSerializer,
        Serializer $clientSerializer,
        Serializer $orderNoteSerializer,
        Serializer $supplierSerializer,
        OrderRepository $orderRepository
    ): JsonResponse {
        $orders = $orderRepository->getOrders($request->query->all());
        $normalizedOrders = $itemSerializer
            ->normalize($supplierSerializer
                ->normalize($clientSerializer
                    ->normalize($orderNoteSerializer
                        ->normalize($orders, null, ['type' => $request->get('type')]))));

        return $this->json($normalizedOrders);
    }
```
It does the job but that's not the cleanest code i think 
I will try to use your solution in the next attempt !
