### DISCUSSION TITLE
Bug on Namespace with vendor modules

### DISCUSSION THREAD

**Discussion by luizkim** [symfony/symfony#52739] [Q&A] [answered]
### Symfony version(s) affected

*

### Description

I use Symfony with Api-Platform, and I'm creating separate modules to integrate into the project. These modules need to be added, but in the file api\vendor\symfony\dependency-injection\Loader\FileLoader.php, I receive the following error:

```
!!
!!  In FileLoader.php line 174:
!!
!!    Expected to find class "ControleOnline\Repository\products\src\Repository\P
!!    roductCategoryRepository" in file "/home/control2/sistemas/controleonline/a
!!    pi/vendor/controleonline/products/src/Repository/ProductCategoryRepository.
!!    php" while importing services from resource "../vendor/controleonline/*/src
!!    /Repository", but it was not found! Check the namespace prefix used with th
!!    e resource in /home/control2/sistemas/controleonline/api/config/services.ya
!!    ml (which is loaded in resource "/home/control2/sistemas/controleonline/api
!!    /config/services.yaml").
!!
!!
!!  In FileLoader.php line 224:
!!
!!    Expected to find class "ControleOnline\Repository\products\src\Repository\P
!!    roductCategoryRepository" in file "/home/control2/sistemas/controleonline/a
!!    pi/vendor/controleonline/products/src/Repository/ProductCategoryRepository.
!!    php" while importing services from resource "../vendor/controleonline/*/src
!!    /Repository", but it was not found! Check the namespace prefix used with th
!!    e resource.
!!
!!
```

### How to reproduce

This is my services.yaml file:

```YAML

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    timezone: "%env(APP_TIMEZONE)%"
    app_name: "%env(APP_NAME)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/*"
        exclude: "../src/{DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}"

    ControleOnline\:
        resource: "../vendor/controleonline/*/src/*"
        exclude: "../vendor/controleonline/*/src/{Security,Controller,Repository,DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}"
    ControleOnline\Repository\:
        resource: "../vendor/controleonline/*/src/Repository"
        tags: ['doctrine.repository_service']
    ControleOnline\Controller\:
        resource: "../vendor/controleonline/*/src/Controller"
        tags: ["controller.service_arguments"]
    ControleOnline\Security\:
        resource: "../vendor/controleonline/*/src/Security"

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: "../src/Controller"
        tags: ["controller.service_arguments"]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    prepersist_company_expense:
        class: \App\EventListener\PersistCompanyExpenseListener
        tags:
            - name: doctrine.orm.entity_listener
              event: prePersist
              entity: App\Entity\CompanyExpense
              lazy: true

```

These are the repositories involved:

https://github.com/ControleOnline/api-platform-products
https://github.com/ControleOnline/api-community
