### DISCUSSION TITLE
JsonEnvVarLoader

### DISCUSSION THREAD

**Discussion by themayna** [symfony/symfony#52733] [Q&A] [answered]
### Symfony version(s) affected

6.3

### Description

Sorry if i'm stupid and this is not a bug but i can't make JsonEnvVarLoader work following the doc https://symfony.com/doc/current/configuration.html#creating-your-own-logic-to-load-env-vars

this is my env loader class:
```

<?php
namespace App\DependencyInjection;

use Symfony\Component\DependencyInjection\EnvVarLoaderInterface;

final class JsonEnvVarLoader implements EnvVarLoaderInterface
{
    private const ENV_VARS_FILE = '/var/www/html/env.json';

    public function loadEnvVars(): array
    {
        $fileName = self::ENV_VARS_FILE;
        if (!is_file($fileName)) {
            // throw an exception or just ignore this loader, depending on your needs
        }

        $content = json_decode(file_get_contents($fileName), true);

        return $content['vars'];
    }
}

```
this is my services.yaml

```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:

            - '../src/Entity/'
            - '../src/Kernel.php'

...

    App\DependencyInjection\JsonEnvVarLoader:
        tags: [ 'container.env_var_loader' ]

```

but somehow i can't get this to work, cand enyone tell me what am i doing wrong?

Thanks.

### How to reproduce

follow instructions from https://symfony.com/doc/current/configuration.html#creating-your-own-logic-to-load-env-vars
