### DISCUSSION TITLE
Using 2 databases with Symfony and Api Platform

### DISCUSSION THREAD

**Discussion by flibouk** [symfony/symfony#52779] [Q&A]
Hello everyone,

I've created an API with Symfony using Api Platform, and it works fine. However, I need to add a second database. So, I configured my doctrine file as follows:

```
`doctrine:
    dbal:
        default_connection: glpi
        connections:
            mabase1:
                url: '%env(resolve:_DATABASE1_URL)%'
            mabase2:
              url: '%env(resolve:_DATABASE2_URL)%'       
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            mabase1:
                connection: mabase1
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        date_format: DoctrineExtensions\Query\Mysql\DateFormat
            mabase2:
                connection: mabase2
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/EntityBDD2'
                        prefix: 'App\EntityBDD2'
                        alias: AppGlpi
```

I've successfully retrieved the tables from my second database (mabase2), so the database connection works fine. However, my entities in the EntityBDD2 folder don't connect to mabase2. It's as if Api Platform is using the first connection configured in doctrine.

While searching, I tried adding this to my entity:

```
/**
 * Tickets
 *
 * @ORM\Table(name="tickets", schema="mabase2")
 * @ORM\Entity
 */
```

But it doesn't change anything.

Do you have any ideas?

The Api Platform version is 2.6.

Thanks in advance.
