### DISCUSSION TITLE
Is it possible to group or cascade/prioritize translation files?

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#52866] [Q&A]
I'd like to use a service like Google Translate to translate my message files, and keep the manually translated files separate, and of course prioritize the manual one.

For example

```yaml
# messages_automatic_translation.es.yaml
home: casa
```

```yaml
# messages.es.yaml
home: página principal
```

It appears that domain is a single string in translation, I guess what I'd like is an array that returns the first translation that was found.

```twig
<a href="/">{{ 'home'|trans(domain=messages,messages_automatic_translation) }}</a>
```

Est-ce possible?

**Comment by tacman** [comment]
I think the answer is in the translation configuration.

```yaml
framework:
    default_locale: en
    enabled_locales: ['en', 'es', 'fr', 'de', 'uk', 'hi', 'hu']
    translator:
        default_path: '%kernel.project_dir%/translations/manual'
        paths:
            - '%kernel.project_dir%/translations/manual'
            - '%kernel.project_dir%/translations/automatic'
```
