### DISCUSSION TITLE
Redis Sentinel DSN leads to no supporting transport

### DISCUSSION THREAD

**Discussion by freswa** [symfony/symfony#52892] [Q&A] [answered]
I'm trying to use redis as a messenger transport. According to the docs, this connection string should be correct:
```
redis:?host[host1:5000]&host[host2:5000]&host[host3:5000]&sentinel_master=test&dbindex=1
```

But with that I get 
```
In TransportFactory.php line 54:

  [Symfony\Component\Messenger\Exception\InvalidArgumentException]
  No transport supports the given Messenger DSN.
```

Looking at the code, I see https://github.com/symfony/redis-messenger/blob/7.0/Transport/RedisTransportFactory.php#L35 and I wonder how `redis:?` is even supposed to work?

Other relevant config sections:
```yaml
framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'

            complete_order_email:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 10
                    delay: 60000
                    multiplier: 1
                options: ~
```

Redis module version:
```
$ php --ri redis

redis

Redis Support => enabled
Redis Version => 6.0.2
Redis Sentinel Version => 1.0
Available serializers => php, json
Available compression => lzf, zstd, lz4
```
