### DISCUSSION TITLE
Upgrading from 4.4 to 5.4/6.4, the NotFoundHTTPException does not return json

### DISCUSSION THREAD

**Discussion by imjma** [symfony/symfony#53001] [Q&A] [answered]
I am upgrading symfony from 4.4 to 6.4

the  `throw new NotFoundHttpException('Not Found');` returns 

```
string(9) "Not Found"
{"code":404,"message":"Not Found"}
```

with an extra string line. 

I tried to add `composer require symfony/serializer-pack` but still not fix.

also this is my monolog.yaml

```
monolog:
    channels: [deprecation]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!deprecation"]
            formatter: 'monolog.formatter.json'
        deprecation:
          type: rotating_file
          path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
          max_files: 2
          channels: [deprecation]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
            formatter: 'monolog.formatter.json'

```

Anyone can help ? Thanks
