### DISCUSSION TITLE
Proper way to configure bundle routes via php attributes in bundle controller

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#53063] [Q&A] [answered]
I finally have a working version of a routing.yaml file that gets its routes from bundle attributes:

```yaml
survos_api_grid:
  prefix: /admin/grid
  type: attribute
  resource:
    path: ../../vendor/survos/api-grid-bundle/src/Controller/
    namespace: Survos\ApiGrid\Controller
```

but the path part doesn't "feel" right.  I tried following other patterns I saw, but they didn't work.

```yaml
#  resource: 'Survos\ApiGrid\Controller/GridController.php'
#  resource: '@SurvosApiGridBundle/Controller/GridController.php'
```

Is it okay to have the resource defined as above with ../../vendor in the path? Or is there a better way?
