### DISCUSSION TITLE
Unauthenticated Request JWT throw 403 instead of 401

### DISCUSSION THREAD

**Discussion by ArtGM** [symfony/symfony#53907] [Q&A] [answered]
Hello,

I've set up en backend api with this config in symfony 5.4 
I'm using the new authentication system (upgrading from guard system) to be able to upgrade to sf 6.4

I'm using the lexik jwt bundle and gesdinet refresh token bundle

```yaml
    api:
      pattern: ^/api/
      stateless: true
      security: true
      provider: user_provider
      user_checker: App\Core\Security\UserChecker
      entry_point: jwt
      jwt: ~
      refresh_jwt:
        check_path: /api/token/refresh
```

The problem: When i request and /api/XXX endpoint without token, the security system is bypassed and this is the access decision who handle the unauthenticated request and throw an AccesDenied 403 exception instead of 401. I suspect that the entry point is not taken into account. (JWTAuthenticator implements AuthenticationEntryPointInterface) 

Am i missing something? 

If you need more information, don't hesitate to ask. Actually, I don't know what to share to help. 🙏
