### DISCUSSION TITLE
How to migrate from AbstractGuardAuthenticator to AccessTokenHandlerInterface (or symfony7)

### DISCUSSION THREAD

**Discussion by c33s** [symfony/symfony#53933] [Q&A] [answered]
in my symfony 5 project i used the `GuardAuthenticator` in combination with the in_memory provider which i use as a simple token storage. in the symfony docs there is only an example with a database backend and not with the in memory provider.  what is the right upgrade path here if i want to stay with the in memory provider?

`security.yaml`:
```yaml
security:
    encoders:
        Symfony\Component\Security\Core\User\User: { algorithm: "bcrypt", cost: 15 }
    providers:
        in_memory:
            memory:
                users:
                    api_token:
                        password: ....
                        roles: [ROLE_READ_API]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            logout: ~
            guard:
                provider:   in_memory
                authenticators:
                    - App\Security\TokenAuthenticator
  access_control:
        - { path: ^/api, roles: ROLE_READ_API }
```

`TokenAuthenticator.php`:
```php
<?php

final class TokenAuthenticator extends AbstractGuardAuthenticator
{
    private readonly UserPasswordEncoderInterface $passwordEncoder;
    private readonly string $activeTokenName; //username
    private readonly Security $security;

    public function __construct(
        UserPasswordEncoderInterface $passwordEncoder,
        Security $security
    ) {
        $this->passwordEncoder = $passwordEncoder;
        $this->security = $security;
    }

    public function supports(Request $request): bool
    {
        if ($this->security->getUser()) {
            return false;
        }

        if (!$this->isRouteSupported($request)) {
            return false;
        }

        return $request->headers->has(self::API_TOKEN_HEADER_NAME);
    }

    public function getCredentials(Request $request)
    {
        return $request->headers->get(self::API_TOKEN_HEADER_NAME);
    }

    /**
     * Returns null on empty credentials, which results in  accessCode 401 "Unauthorized".
     */
    public function getUser(mixed $credentials, UserProviderInterface $userProvider): ?UserInterface
    {
        if (null === $credentials) {
            return null;
        }

        return $userProvider->loadUserByUsername($this->activeTokenName);
    }

    public function checkCredentials($credentials, UserInterface $user): bool
    {
        return $this->passwordEncoder->isPasswordValid($user, $credentials);
    }

    /**
     * Returns null on success, to let the request continue.
     */
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, mixed $providerKey): ?Response
    {
        return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        return new JsonResponse($data, Response::HTTP_UNAUTHORIZED);
    }

    public function start(Request $request, AuthenticationException $authException = null): Response
    {
        $data = [
            'message' => 'Authentication Required',
            'error' => true,
        ];

        return new JsonResponse($data, Response::HTTP_UNAUTHORIZED);
    }

    public function supportsRememberMe(): bool
    {
        return false;
    }
}
```

**Comment by c33s** [comment, marked as answer]
`AccessTokenHandler.php`:
```php
<?php

namespace App\Security;

use Psr\Log\LoggerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\User\InMemoryUser;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Http\AccessToken\AccessTokenHandlerInterface;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;

class AccessTokenHandler implements AccessTokenHandlerInterface
{
    final public const TOKEN_NAME = 'api_token';
    public function __construct(
        private UserProviderInterface $userProvider,
        private UserPasswordHasherInterface $passwordHasher,
        private LoggerInterface $logger,
    ) {
    }

    public function getUserBadgeFrom(?string $accessToken): UserBadge
    {
        if (null === $accessToken || !$this->verifyCredentials($accessToken)) {
            throw new BadCredentialsException('Invalid credentials.');
        }

        return new UserBadge(self::TOKEN_NAME);
    }

    private function verifyCredentials(string $accessToken): bool
    {
        $user = $this->userProvider->loadUserByIdentifier(self::TOKEN_NAME);

        if (get_class($user) !== InMemoryUser::class) {
            $userClass = get_class($user);
            $requiredUserClass = InMemoryUser::class;
            $this->logger->error("Invalid User Class for access token authentication. Got $userClass but require $requiredUserClass");

            return false;
        }

        return $this->passwordHasher->isPasswordValid($user, $accessToken);
    }
}
```

`security.yaml`:
```yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory:
            memory:
                users:
                    api_token:
                        password: <hashed password>
                        roles: [ROLE_API]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            access_token:
                token_handler: App\Security\AccessTokenHandler
                token_extractors:
                    - 'header'
    role_hierarchy:
        ROLE_API:               ~
        ROLE_ADMIN:             ROLE_API
        ROLE_SUPER_ADMIN:       [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
```
