### DISCUSSION TITLE
monolog excluded_http_codes 5xx

### DISCUSSION THREAD

**Discussion by hasslerf-infoflora** [symfony/symfony#54058] [Q&A]
Symfony version : 5.4.34
Monolog-bundle : 3.10 

I have a specific use case in an application where, for a specific monolog handler, i don't want to handle 5xx errors.
To do this, i simply use the `excluded_http_codes` attribute but it seems to works well with 4xx codes but not with 5xx codes (see the exemples above).

Working exemple with 4xx errors
```yaml
# monolog.yaml
            mail:
                type: fingers_crossed
                action_level: error
                handler: deduplicated
                excluded_http_codes: [403, 404, 405] # This works fine and does not send email when these http code occured
```

Non working exemple with 5xx errors 
```yaml
# monolog.yaml
            mail:
                type: fingers_crossed
                action_level: error
                handler: deduplicated
                excluded_http_codes: [500] # This does not work and always send an email no matter what
```

To test it in a controller : 
```php
 // this produce a 404 http code
 throw  $this->createNotFoundException();
```

```php
 // this produce a 500 http code
 throw  new Exception("test HTTP 500");
```

I didn't seen anything in the documentation that specify that only http codes < 500  can be excluded.
Am I missing something ? Or should i report a bug ?
