### DISCUSSION TITLE
Separate loggers when running on web and CLI

### DISCUSSION THREAD

**Discussion by iCantSneed** [symfony/symfony#54118] [Q&A] [answered]
In my prod environment, I have my logs written to apache's error_log when my app is accessed over the web.
I also have a command I run from a cronjob through `bin/console`. I would like to store the logs in a separate file, preferably with a rotating_file handler.
I tried defining a different environment and running the command using the new environment, but it looks like Symfony doesn't like when more than one environment is used at a time.

**Comment by MatTheCat** [comment]
Don't know much about apache but it seems you just have to inject a different logger into your command? Did you read https://symfony.com/doc/current/logging/channels_handlers.html?

**Reply by iCantSneed** [reply]
I don't understand how channels will help. Only the command class itself will run under the `command` channel, but the rest of the code runs on different channels, e.g. `app`, `doctrine`, `http_client`, etc.
I also can't figure out how to autowire custom loggers to *all* of the classes being used, but only when running from the CLI.

**Reply by MatTheCat** [reply, marked as answer]
Indeed I misunderstood your use-case.

Using a specific environment sounds like a solution then; what do you mean by “Symfony doesn't like when more than one environment is used at a time.”?

Thinking out loud, but maybe you could check having a [CLI-specific kernel
](https://symfony.com/doc/current/configuration/multiple_kernels.html) or [configuring the logger at runtime](https://symfony.com/doc/current/service_container/configurators.html) 🤔

**Reply by iCantSneed** [reply]
Thank You! I used your suggestions and made a configurator to change the loggers at runtime. I didn't like the multi-kernel solution, primarily because I would need to have two separate caches, which seems wasteful.

**Comment by iCantSneed** [comment]
Here's a brief overview of what I ended up doing. It's not the best solution, but it works for my needs:
1. Create the desired handler and assign it to an unused channel:
```yaml
monolog:
    channels:
        - unused
    handlers:
        command:
            type: rotating_file
            path: "%kernel.logs_dir%/console.log"
            level: info
            max_files: 7
            channels: [unused]
```
2. Make a configurator to replace the logger's handlers when some global flag is set:
```php
<?php

declare(strict_types=1);

namespace App;

use Monolog\Handler\HandlerInterface;
use Monolog\Logger;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class CommandLoggerConfigurator
{
  public const OVERRIDE_LOGGER_GLOBAL = 'command_override_logger';

  private bool $overrideLogger;

  public function __construct(
    #[Autowire(service: 'monolog.handler.command')]
    private HandlerInterface $commandHandler
  ) {
    $this->overrideLogger = ($GLOBALS[self::OVERRIDE_LOGGER_GLOBAL] ?? false) === true;
  }

  public function configure(Logger $logger): void
  {
    if ($this->overrideLogger) {
      $logger->setHandlers([$this->commandHandler]);
    }
  }
}
```
3. Set the configurator for every logger instance:
```yaml
services:
    Monolog\Logger:
        arguments:
            -
        configurator: ['@App\CommandLoggerConfigurator', 'configure']
    monolog.logger_prototype: '@Monolog\Logger'
```
4. When running a command, set the global flag before creating the kernel (in bin/console):
```php
return function (array $context) {
    $GLOBALS[CommandLoggerConfigurator::OVERRIDE_LOGGER_GLOBAL] = true;
    $kernel = new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);

    return new Application($kernel);
};
```
