### DISCUSSION TITLE
[Configuration] How to avoid nesting in configuration in symfony/config?

### DISCUSSION THREAD

**Discussion by bertoost** [symfony/symfony#54156] [Q&A]
Hi there,

This is a difficult situation to explain. Hope I can illustrate the situation...
Sorry for this long description, but I have to explain this, to let you understand the situation.

## Explanation / Examples

Our application is meant to import CSV files (a lot) and map data to entity-fields. We have created "configurations" (as parameters) to describe what column in the csv file is mapped to which field of the entity.

This is an example configuration;

```yaml
a_random_name:
  filename: 'some-filename-definition.csv'
  entity: App\Enitty\Person
# inside mapper configuration: entityField: csvColumn
  mapper:
    id: id
    firstName: first_name
    lastName: last_name
    email: email_address
```

Above are simple mappings, between a column of the entity and a column in de csv file. We'd like to call that a `DataFieldMapper`
Therefore, we also have some more simple and advanced mappers, for example (only concentrating on the `mapper:` part from here);

```yaml
id: id
firstName: first_name
lastName: last_name
email: email_address
active:
  type: fixed
  value: true
```

As you can imagine; the value of the `active` property of the entity is fixed set to a boolean true value.
The `type: fixed` is also a mapper, which ends up as `FixedValueMapper`.

> Each shorthand like "fixed" is in a list, mapped to a class. So, we know that "fixed" should become "FixedValueMapper".

To make life easier, I am normalizing this structure to something that looks like this;

```php
$config = [
    'id' => [
        'App\...\DataFieldMapper' => [
            'value' => 'id',
        ],
    ],
    'firstName' => [
        'App\...\DataFieldMapper' => [
            'value' => 'first_name',
        ],
    ],
    'lastName' => [
        'App\...\DataFieldMapper' => [
            'value' => 'last_name',
        ],
    ],
    'email' => [
        'App\...\DataFieldMapper' => [
            'value' => 'email_address',
        ],
    ],
    'active' => [
        'App\...\FixedValueMapper' => [
            'value' => true,
        ],
    ],
];
```

Each "mapper class" receives the CSV-data-row and receives the values of the above array as $options.
One more example (just one in the case);

```yaml
someField:
  type: value_to_value
  column: a_csv_source_column
  values:
    - from: 'A'
      to: 'Z'
    - from: 'B'
      to: 'Y'
```

which wil be normalized to this;

```php
'someField' => [
    'App\...\ValueToValueMapper' => [
        'column' => 'a_csv_source_column',
        'values' => [
            [
                'from' => 'A',
                'to' => 'B',
            ], [
                'from' => 'B',
                'to' => 'Y',
            ]
        ],
    ],
],
```

This way, we have about 12 different mappers doing their own way of mapping.
For example; we could retrieve a value from another entity, or combine-values together as new value for the entity (eq. concatenate first-name and last-name as full-name). Etc. etc.

## The configuration prototype

To allow an entity property inside the mapper configuration to have any mapper, with their own options (values), I have to add all mappers as possible array-nodes to the configuration. So basically I am prototyping the configuration like this;

```php
->arrayNode('mapper')
    ->useAttributeAsKey('name')
    ->arrayPrototype()
        /* all mapper-classes are appended here */
    ->end()
->end()
```

So, I am telling the configuration that any key below "mapper" can be any mapper we know, like

```yaml
array-node: any-field:
  array-node: App\...\DataFieldMapper:
    scalar-node: value
  array-node: App\...\FixedValueMapper:
    scalar-node: value
  array-node: App\...\ValueToValueMapper:
    scalar-node: column
    array-prototype-node: values
     scalar-node: from
     scalar-node: to
  array-node: ANY-NEXT-MAPPER-CLASS:
```

To append all the options, we have a "getOptionsConfiguration()" inside the mapper-class which will be called inside a foreach and appended to the array-node of each mapper-class iteration.
Each field below the mapper can have one of the mappers below them, each mapper with their own configuration-options.

## The problem...

Now comes the beauty of all of this;
Any mapper can decide to allow options to be a mapper again (nesting)...
So for example; the ValueToValueMapper, has an option `default_value` which can be a mapper again
But every `from` and `to` from the examples above, could be a mapper as well. 
So, nesting occurs here. Since you don't know which mapper is going to be configured, you should allow all mappers to exists below the property.

> To make this work, I have created a `MapperNodeDefinition` class which extends from the `ArrayNodeDefinition` and which applies the normalization and which adds all possible mappers with their options.
> I have used `->setNodeClass()` and using `->node(..., 'mapper')` to add the custom node definition.

This will cause nesting recursion, since a mapper can have options, which can be mappers again. All the mappers are added again with the same options as before, but those options can be mappers again, with the same options, same mappers over and over again...

I want to restrict this nesting level to a maximum number, like for example; 5 levels.
So, when you define a 6th level over mappers-in-mappers, an error occurs.
This is basically not going to happen. 

Therefore; the `->node()` call is starting new node instances, and leaving the parent set to NULL.
So, the code is not aware of the nesting level, and I can't figure out how to stop adding mappers to the configuration nodes, and stop nesting..

Really appreciate you have made it to here ;-) and many thanks for reading this.
If you have any idea or suggestion, I'd really like to hear.

Kind regards, Bert
