### DISCUSSION TITLE
Handling Messages Synchronously -- incorrect transport consumer?

### DISCUSSION THREAD

**Discussion by NiklasBr** [symfony/symfony#54195] [Q&A]
Got this configuration:

```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            app_urgent: 'sync://'
```

I'm using `Symfony\Component\Messenger\HandleTrait;` in the class and calling it:

```php
$this->handle(
    new MyMessage($fileName, $params)
);
```

```php
public function __invoke(MyMessage $message): void
{
// ...
```

However, when the invoke method is called it appears as it is not being called from the expected transport consumer even though I have `messenger:consume app_urgent` running. How do I get this synchronous transport working?

**Comment by MatTheCat** [comment]
`sync` is a fake transport: it will forward messages directly to their handler. As such it doesn’t need a consumer to run.

**Reply by NiklasBr** [reply]
Do you know how I should configure it to need a consumer?

**Reply by MatTheCat** [reply]
This is all explained in the documentation: https://symfony.com/doc/current/messenger.html#transports-async-queued-messages

**Reply by NiklasBr** [reply]
Is it a bug then? Because I followed this to the letter:

> In some cases (like when [binding handlers to different transports](https://symfony.com/doc/current/messenger.html#binding-handlers-to-different-transports)), it's easier or more flexible to handle this explicitly: by creating a sync transport and "sending" messages there to be handled immediately

```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            # ... other transports

            sync: 'sync://'

        routing:
            App\Message\SmsNotification: sync
```
