### DISCUSSION TITLE
Dependency type error when using "tags: [cache.pool]"

### DISCUSSION THREAD

**Discussion by elevado** [symfony/symfony#54205] [Q&A]
Hi,

I have a `StorageCacheService` that centrally manages access to the cache. This also works.

```php
use Psr\Cache\InvalidArgumentException;
use Symfony\Component\Cache\Adapter\TagAwareAdapterInterface;

class StorageCacheService
{
    // Properties

    public function __construct(
        private readonly TagAwareAdapterInterface $cache,
        int $ttl = 0,
        string $cachePrefix = ''
    ) {
        // Stuff
    }
        
    // Methods
}
```

```yaml
App\Service\StorageCacheService:
    arguments:
        - '@app.cache_adapter'
        - '%env(int:STORAGE_CACHE_TTL)%'
        - '%kernel.environment%'
    tags: [cache.pool]

app.cache_adapter:
    class: Symfony\Component\Cache\Adapter\FilesystemTagAwareAdapter
    arguments:
        - '%kernel.environment%'
        - 0
        - '%kernel.cache_dir%/.app.cache_adapter'
```

I would like to extend the `StorageCacheService` with the `PruneableInterface`. 

```php
use Symfony\Component\Cache\Adapter\TagAwareAdapterInterface;
use Symfony\Component\Cache\PruneableInterface;

class StorageCacheService implements PruneableInterface
{
    // Constructor
    // Methods
    public function prune(): bool
    {
        return true;
    }
}
```

If I now add `tags: [cache.pool]` to the service configuration, I get the following error.

```yaml
App\Service\StorageCacheService:
    arguments:
        - '@app.cache_adapter'
        - '%env(int:STORAGE_CACHE_TTL)%'
        - '%kernel.environment%'
    tags: [cache.pool]
```

**#message: "App\Service\StorageCacheService::__construct(): Argument #1 ($cache) must be of type Symfony\Component\Cache\Adapter\TagAwareAdapterInterface, string given, called in /var/www/html/var/cache/dev/ContainerObUMt8s/App_KernelDevDebugContainer.php on line 1024"**

This is line 1024 and the first parameter there is: 'B1EbhEFjH+'. A String.

```php
return $container->privates['App\\Service\\StorageCacheService'] = new \Symfony\Component\Cache\Adapter\TraceableAdapter(new \App\Service\StorageCacheService('B1EbhEFjH+', $container->getEnv('int:STORAGE_CACHE_TTL'), 'dev'));
```

I can see that the class `App\Service\StorageCacheService` is being processed in CachePoolPrunerPass::process(). But later the exception is thrown.    

What could be the error?
