### DISCUSSION TITLE
PHPUnit 11.0.5: Test code or tested code did not remove its own exception handlers

### DISCUSSION THREAD

**Discussion by disceney** [symfony/symfony#54241] [Q&A] [answered]
Hello,

I've been trying to solve an issue for several hours now. Indeed, I'm not sure if this is an error or if it's normal behavior. However, I expect my test to be completely okay without any risks. Let me explain.

I'm trying to set up a unit test that will simply verify my application on a URL. So, I'm trying it like this:

```php
<?php

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class LoginTest extends WebTestCase
{
	public function testLoginAdmin () : void
	{
		$client = static::createClient([], [
			"HTTP_HOST" => "admin.example.com",
			"HTTPS" => true
		]);

		$client->catchExceptions(false);

		$client->request("GET", "/login");

		$this->assertEquals(200, $client->getResponse()->getStatusCode());
	}
}

```

Up to this point, I think it's correct (or not). I specify the HOST to "createClient" because in my Symfony routing.yaml file, I explicitly provide the host (I have several) like this:

```yaml
controller_admin:
    resource: ../src/Controller/Admin
    type: attribute
    host: admin.example.com
    schemes: [ https ]

controller_app:
    resource: ../src/Controller/App
    type: attribute
    host: example.com
    schemes: [ https ]
```

However, when I run my test, it gives me this result:

```text
PHPUnit 11.0.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.3
Configuration: Example/phpunit.xml.dist

R                                                                   1 / 1 (100%)

Time: 00:01.023, Memory: 58.50 MB

There was 1 risky test:

1) App\Tests\LoginTest::testLoginAdmin
Test code or tested code did not remove its own exception handlers

Example/tests/LoginTest.php:9

OK, but there were issues!
Tests: 1, Assertions: 1, Risky: 1.
```

I tried to check my code in my controller; however, it's a simple code from Symfony's documentation:

```php
		$authenticationException = $authenticationUtils->getLastAuthenticationError();
		$lastUsername = $authenticationUtils->getLastUsername();

		return $this->render("admin/security/login.html.twig", [
			"last_username" => $lastUsername,
			"error" => $authenticationException
		]);
```
		
After several searches, I couldn't find a solution to fix this and remove the "Risky: 1". Is this normal behavior, or is there a missing configuration?

Thank you :)
