### DISCUSSION TITLE
Two factor authentication

### DISCUSSION THREAD

**Discussion by Serhii75** [symfony/symfony#54245] [Q&A]
Hi,
I'm trying to implement 2fa using scheb/2fa-bundle and scheb/2fa-google-authenticator. Also I used as a guide these docs:
https://symfony.com/bundles/SchebTwoFactorBundle/current/api.html
https://symfony.com/bundles/SchebTwoFactorBundle/current/index.html

So, I added ApiLoginController and AuthenticationSuccessHandler, but it seems like $token that I get in the AuthenticationSuccessHandler::onAuthenticationSuccess is not an instance of TwoFactorTokenInterface and I can't understand what I'm doing wrong. Guess, the problem is somewhere in configs. For now, I'm out of ideas. Could you please help? 

packages/security.yaml
```yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            stateless: false

            two_factor:
                prepare_on_login: true
                prepare_on_access_denied: true
                success_handler: App\Security\TwoFactorAuthenticationSuccessHandler
                failure_handler: App\Security\TwoFactorAuthenticationFailureHandler

            json_login:
                check_path: api_login
                username_path: login
                password_path: password
                success_handler: App\Security\AuthenticationSuccessHandler
                authentication_required_handler: App\Security\TwoFactorAuthenticationRequiredHandler

    access_control:
        - { route: 'api_login', roles: [ PUBLIC_ACCESS ] }                
```

config/packages/sheb_2fa.yaml
```yaml
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    google:
        enabled: true                  
        server_name: Server Name       
        issuer: Issuer Name            
        digits: 6                      
        leeway: 0 
```

src/Controller/ApiLoginController.php
```php
class ApiLoginController extends AbstractController
{
    #[Route('/api/login', name: 'api_login', methods: ['POST'])]
    public function index(#[CurrentUser] ?User $user): JsonResponse
    {
        if (null === $user) {
            return $this->json([
                'message' => 'missing credentials'
            ], Response::HTTP_UNAUTHORIZED);
        }

        return $this->json([
            'user' => $user->getUserIdentifier(),
        ]);
    }
}
```

src/Security/AuthenticationSuccessHandler.php
```php
class AuthenticationSuccessHandler implements AuthenticationSuccessHandlerInterface
{
    public function onAuthenticationSuccess(Request $request, TokenInterface $token): ?Response
    {
        if ($token instanceof TwoFactorTokenInterface) {
            return new Response('{"login": "success", "two_factor_complete": false}');
        }

        /** @var User $user */
        $user = $token->getUser();

        return new JsonResponse(['login' => 'success', 'user' => [
            'id' => $user->getId(),
            'roles' => $user->getRoles(),
            'username' => $user->getUsername(),
        ]]);
    }
}
```
I would be appreciate for any help
