### DISCUSSION TITLE
symfony workflow,get current user guard

### DISCUSSION THREAD

**Discussion by langziyang** [symfony/symfony#54436] [Q&A]
```
framework:
    workflows:
        post_request:
            type: 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Post
            initial_marking: draft
            places:
                - draft
                - wait
                - organize_approved
                - organize_reject
                - office_approved
                - office_reject
                - leadership_approved
                - leadership_reject
                - director_approved
                - director_reject
            transitions:
                submit: #发起人提交
                    from: draft
                    to: wait
                organize_approved: #单位批过
                    guard: "is_granted('ROLE_ORGANIZE') and user.isManager()"
                    from: wait
                    to: organize_approved
                organize_reject: #单位批不通过
                    guard: "is_granted('ROLE_ORGANIZE') and user.isManager()"
                    from: wait
                    to: organize_reject
                office_approved: #办公室批过
                    guard: "is_granted('ROLE_OFFICE') and user.isManager()"
                    from: organize_approved
                    to: office_approved
                office_reject: #办公室不通过
                    guard: "is_granted('ROLE_OFFICE') and user.isManager()"
                    from: organize_approved
                    to: office_reject
                leadership_approved:
                    guard: "is_granted('ROLE_LEADERSHIP') and user.isManager()"
                    from: office_approved
                    to: leadership_approved
                leadership_reject:
                    guard: "is_granted('ROLE_LEADERSHIP') and user.isManager()"
                    from: office_approved
                    to: leadership_reject
                director_approved:
                    guard: "is_granted('ROLE_DIRECTOR') and subject.getProcess()==1"
                    from: leadership_approved
                    to: director_approved
                director_reject:
                    guard: "is_granted('ROLE_DIRECTOR') and subject.getProcess()==1 and user.isManager()"
                    from: leadership_approved
                    to: director_reject
```

I have defined a workflow where, after a user logs in, on the Post list page, I only need to fetch the posts that this user needs to operate on. For example, if a user with ROLE_DIRECTOR logs in, I only need to find posts with process equal to 1 to display to the user, and those with process equal to 0 should not be retrieved from the database. How can I achieve this? I am unable to find the guard in the workflow.
