### DISCUSSION TITLE
Problem to use secret

### DISCUSSION THREAD

**Discussion by karaka200** [symfony/symfony#57218] [Q&A]
Hello. I use `https://symfony.com/doc/current/configuration/secrets.html` to encrypt username and password and database name. With the `php bin/console secrets:list --reveal` command, the information in the `prod` is displayed correctly.
But when I try to use it in the host, this error displays:

> An exception has been thrown during the rendering of a template ("An exception occurred in the driver: SQLSTATE[28000] [1045] Access denied for user 'hjkfsiuyui'@'localhost' (using password: NO)").

doctrine.yaml :
```
doctrine:
    dbal:
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        server_version: '8.0.35'		
...
```

php bin/console secrets:list --reveal :
```
 // Use "%env(<name>)%" to reference a secret in a config file.

 ------------------- ---------------------- -------------
  Secret              Value                  Local Value
 ------------------- ---------------------- -------------
  DATABASE_NAME       "hjkfsiuyui_newAminp"
  DATABASE_PASSWORD   "z3TiOruit98fMmh"
  DATABASE_USER       "hjkfsiuyui"
 ------------------- ---------------------- -------------
```

 But when I enter directly, it works correctly!
```
 doctrine:
    dbal:
        dbname: 'hjkfsiuyui_newAminp'
        user: 'hjkfsiuyui'
        password: 'z3TiOruit98fMmh'
        server_version: '8.0.35'		
...
```

How can I fix this problem?

** I should also say that since I am using a shared host, I have uploaded the Symfony files in the `symfony` and `public_html` folders in the root.
