### DISCUSSION TITLE
Render 404 as json/html based on the URL given, when no matching route is found

### DISCUSSION THREAD

**Discussion by VincentLanglet** [symfony/symfony#57247] [Q&A] [answered]
I have a security which basically say

```
firewalls:
    api:
       pattern: ^/api
    dashboard:
       pattern: ^/(?!api)
```

And a routing
```
api:
    resource: "routes/api.yaml"
    prefix:   /api
    format: json
dashboard:
    resource: "routes/dashboard.yaml"
    prefix:   /
    format: html
```

The issue I encounter is the fact that if someone try to reach `/api/not-found` he gets a 404 page in html when I'd like he gets a json error page ; but still render my custom HTML error page in the dashboard.

Is there a way to achieve this ?
