### DISCUSSION TITLE
[Messenger] Failed external messages

### DISCUSSION THREAD

**Discussion by etshy** [symfony/symfony#57586] [Q&A]
I have a configuration issue for consuming external Messages.
(I'm using symfony 5.4)
I followed the symfonycast tutorial to consume the message with a custom serializer, everything is fine.
If an error occurred on my code (Throwable) I'd like the message to be put in my `failed_transport` (doctrine) to be able to retry it later once the code is fixed.
But Symfony Messenger try to push the message on the external queue instead of my `failed_transport` configured

Here is my messenger config
```yaml
framework:
    messenger:
        failure_transport: failed
        transports:
            failed: 'doctrine://default?queue_name=failed'
            external_tansport:
                dsn: <DSN>
                serializer: custom_serializer
                options:
                    auto_setup: false
                    exchange:
                        name: messages
                        type: direct
                        #routing and binding_keys must match:
                        #https://symfonycasts.com/screencast/messenger/external-transport#codeblock-5b68cfa12a
                        default_publish_routing_key: from_external
                    queue:
                        messages:
                            binding_keys: [from_external]
```

I tried to change the exchange name (if I'm not wrong, th eexchange is for pushing message) to `failed`, the `default_publish_routing_key`, etc. but it still tries to push on my external DSN.

Anyone could help me with the config to push failed messages to my failed_transport even if they come from an external queue ?

Additional question: I integrated the external queue name in the DSN, but in the config I could set the `queue` with `messages` and it worked. Is it normal for the real queue name to not be needed in the `transports.external_tansport.options.queue.<queue_name>` ?
