### DISCUSSION TITLE
[Symfony 6.2] Security - `access_control` have more importance than `#[IsGranted()]` attribute

### DISCUSSION THREAD

**Discussion by etshy** [symfony/symfony#57718] [Q&A] [answered]
I upgrade symfony version up to 6.4 on a few projects and on one projet I have the following `access_control` in `security.yaml`

```yaml
security:
  access_control:
    // ... other path checks
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```

Then on a controller I have an `#[IsGranted("USR")]` attribute to  make more precise check on a specific role.

On my Voter to check this role, I only get `IS_AUTHENTICATED_FULLY` in the attributes, not the `USR` role I added in the attributes.

Is that the intended behaviour ?

ps : It worked great before upgrading to 6.2, my unit test using `Browser` to check roles access passed with success
