### DISCUSSION TITLE
Rationale of transport filter in integration test mailer

### DISCUSSION THREAD

**Discussion by kAlvaro** [symfony/symfony#57737] [Q&A]
I'm writing an integration test with Symfony/6 and PHUnit/11 where I need to verify email messages. If I don't filter by transport when I call `$this->getMailerMessages()`, I get each message twice (apparently the same object instance): one for `[main]` (?) and one for `null://`.

So I'm using `$this->getMailerMessages('null://')` because that's the transport set for `test` environment.

- `symfony/config/packages/mailer.yaml`

   ```yaml
   framework:
       mailer:
           dsn: '%mailer_transport%://%mailer_user%:%mailer_password%@%mailer_host%:%mailer_port%'
   ```

   Variables are populated from our secrets manager, `%mailer_transport%` in particular is `smtp`.

- `symfony/config/packages/test/mailer.yaml`

   ```yaml
   framework:
       mailer:
           dsn: null://null
   ```

Is this correct/robust, or there's some misconfiguration in our project email settings?
