### DISCUSSION TITLE
Chain form_login with form_login_ldap

### DISCUSSION THREAD

**Discussion by keichitokuna** [symfony/symfony#57754] [Q&A]
Hello,
I have an issue with form_login and form_login_ldap. What i am trying to do :

- one login form (username and password)
- check inside the user entity if username/password are valid
- if not : check on ldap server AND return a Entity\User object (if the user exits or create it in database with a 'ldap' password to not store the real one)

It was working with a CredentialsCheckListener :
```
public function onCheckPassport(CheckPassportEvent $event)
    {
            try {
                $this->checkCredentialsListener->checkPassport($event);
                // We have to mark the ldap badge as resolved. Otherwise an exception will be thrown.
                /** @var LdapBadge $ldapBadge */
                $ldapBadge = $event->getPassport()->getBadge(LdapBadge::class);
                $ldapBadge->markResolved();
            } catch(BadCredentialsException $e) {
                $this->checkLdapCredentialsListener->onCheckPassport($event);
            }
    }
```

But now, i need to allow people to deactivate the ldap connection with a env var :
`LDAP_ACTIVATION=true (or false)`

And it is not working if a ldap server is not present.So i check the documentation and go another way, in security.yaml :

```
providers:
        local_users:
            entity:
                class: App\Entity\User
                property: username
        ldap_users:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(LDAP_BASE_DN)%'
                search_dn: '%env(LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'
                uid_key: "uid"
        all_users:
            chain:
                providers: ['ldap_users', 'local_users']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            entry_point: form_login
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                dn_string: '%env(LDAP_BASE_DN)%'
                query_string: '(uid={user_identifier})'
                search_dn: '%env(LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: trueBut it is not working.
```

After two days of trying, i searched on Github and found : https://github.com/symfony/symfony/issues/41892
I am unsure if it is the same situation as myself.

Can you provide some assistance ?

Thanks

K.
