### DISCUSSION TITLE
Using CHIPS / Partitioned cookies for the session cookie

### DISCUSSION THREAD

**Discussion by jondavidpass** [symfony/symfony#57786] [Q&A] [answered]
Has anyone had any success with this and can point me in the direction of something helpful?

I can see 6.4 adds CHIPS cookies support but there's only mention of cookies that you instantiate within your own code in the examples. I'm wondering if anyone has had any success setting this up for the session cookie?

**Comment by MatTheCat** [comment]
See https://github.com/php/php-src/issues/12646: PHP still doesn’t support CHIPS cookies but it seems you can hack your way by messing with the `cookie_samesite` option:

```yaml
framework:
    session:
        cookie_samesite: lax; partitioned
```

Does it work?

**Reply by jondavidpass** [reply]
I had tried a similar approach but using `ini_set`. Symfony's Cookie class seems to check samesite against a list of accepted values and rejects it.

I haven't tried this particular setting though—will give it a go. Thanks!

EDIT: Similar error but seems to reject it at a config level
```
The value "none; partitioned" is not allowed for path "framework.session.cookie_samesite". Permissible values: null, "lax", "strict", "none"
```

**Comment by jondavidpass** [comment]
What almost works is using onKernelResponse to try hack in a Partitioned using something like:
```
        $sessionCookie = SessionUtils::popSessionCookie(session_name(), session_id());
        if (null !== $sessionCookie) {
            header(sprintf('%s; Partitioned', $sessionCookie), false);
        }
```

Something else seems to run later than this and do something with the session cookie / set cookie header though as the response never has the Partitioned param.

**Reply by MatTheCat** [reply]
The `SessionListener` subscribes to `kernel.response` with a `-1000` priority; is your listener’s lower?

**Reply by jondavidpass** [reply]
This is exactly what I was looking for! Thank you so much. I'll see if I can get this hack working.

**Reply by jondavidpass** [reply]
I set the priority lower (-1500) and I saw it working for like one request but then it went back to the partitioned attribute getting scrubbed at some point. I'll keep trying to figure out what is running after my listener—thus far this seems like the most promising solution.

```
    company.security.session_cookie_listener:
        class: Company\SecurityBundle\EventListener\SessionCookieListener
        tags:
            - { name: kernel.event_subscriber, event: kernel.response, method: onKernelResponse, priority: -1500 }
```

Also tried setting priority here
```
    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::RESPONSE => ['onKernelResponse', -1001],
        ];
    }
```

EDIT: Seems like the session cookie is no longer in the headers at that priority. Not sure if they're sent already by that point?
