### DISCUSSION TITLE
How to redirect to previous URL after login?

### DISCUSSION THREAD

**Discussion by Elikill58** [symfony/symfony#57813] [Q&A]
Hello,
I'm using Symfony 7.1.2. I want let user that want to access to `/some/link` but are not logged, be redirect to the given URL after login.

I have a firewall like that:
```yml
firewalls:
    main:
        pattern: ^/
        custom_authenticator: App\Security\LoginFormAuthenticator
        entry_point: form_login
        form_login:
            login_path: login
            check_path: login
            use_referer: true
        logout:
            path: logout
        remote_user:
            provider: user_provider

access_control:
- { path: ^/login, role: PUBLIC_ACCESS }
- { path: ^/, role: ROLE_USER }
```
On my `LoginFormAuthenticator`, here is the relevant part:
```php
public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response {
    $target = (string)$request->request->get('_target_path');
    return new RedirectResponse($target && $target != "" ? $target : $this->urlGenerator->generate('index'));
}
```
And in my login form, I'm using `'back_to_your_page' => $request->headers->get('referer')` and I put `back_to_your_page` on the html form. When the value is set, it works fine (the `onAuthenticationSuccess` well redirect). The variable is set only when you are already logged, and you logout...

When trying to access to `/some/link`, you are directly redirected to `/login`, and the refer is empty. I failed to get a way to get the refer or anything else useful.

Can you help me to manage the redirection after login?
