### DISCUSSION TITLE
Prod monolog config override with custom file

### DISCUSSION THREAD

**Discussion by dorcurreli** [symfony/symfony#57922] [Q&A]
Hi everyone, I am trying to override the Monolog configurations through a custom file. (Symfony 5.4)
First, I defined the import in `services.yaml`.

imports:

    `- { resource: 'custom/monolog.yaml', ignore_errors: not_found }`

This is the base configuration file:
```
config/packages/monolog.yaml

monolog:
    channels: [deprecation]
    handlers:
        deprecation:
            type: noop
            channels: [deprecation]
            level: warning

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                max_files: 20
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event", "!doctrine", "!deprecation" ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console", "!deprecation" ]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event", "!deprecation" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!deprecation" ]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50
                channels: [ "!deprecation" ]
            nested:
                type: rotating_file
                max_files: 0
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                formatter: monolog.formatter.json
                include_stacktraces: true
                channels: [ "!deprecation" ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!deprecation" ]
            rotating_file:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                max_files: 10
                channels: [ "!event", "!doctrine", "!deprecation" ]
```
This is my custom file where I define the desired override:

```
config/custom/monolog.yaml

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: debug
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50
                channels: [ "!deprecation" ]
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
                include_stacktraces: true
                channels: [ "!deprecation" ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!deprecation" ]
            rotating_file:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                max_files: 10
                channels: [ "!event", "!doctrine", "!deprecation" ]
```
I've noticed that the custom file is imported correctly, but not all properties are overridden properly. For example, the main handler is only partially overridden, and some property values are merged together (`excluded_php_codes` ):

```
php bin/console debug:config monolog --env=prod 


main:
            type: fingers_crossed
            action_level: debug
            handler: nested
            excluded_http_codes:
                -
                    code: 404
                    urls: {  }
                -
                    code: 405
                    urls: {  }
                -
                    code: 404
                    urls: {  }
                -
                    code: 405
                    urls: {  }
            buffer_size: 50
            channels:
                type: exclusive
                elements:
                    - deprecation
```
Does anyone have an idea of how this might happen?
