### DISCUSSION TITLE
What is "[main]" transport in mail?

### DISCUSSION THREAD

**Discussion by kAlvaro** [symfony/symfony#58091] [Q&A] [answered]
I always see two transports active when I send email: whatever I configure in `mailer.yaml` and a hard-coded `[main]` one. Both get a copy of each message sent. What is the latter?

![image](https://github.com/user-attachments/assets/a2d6211e-468e-479a-a14f-9841fde60a2f)

I'm writing [tests for email](https://symfony.com/doc/6.4/mailer.html#write-a-functional-test) in Symfony/6.4 if that matters.

**Comment by MatTheCat** [comment]
This is your `[main]` transport: https://github.com/symfony/symfony/blob/ffe40c6289374cccc28806714a705e335bdd1b2e/src/Symfony/Component/Mailer/Transport/Transports.php

See https://github.com/symfony/symfony/pull/33409; when you configure a single transport using `dsn` its key will be `main`: https://github.com/symfony/symfony/blob/ffe40c6289374cccc28806714a705e335bdd1b2e/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2657

**Comment by kAlvaro** [comment]
That suggests I've inadvertently configured two transports when I only need one, but I can't see my mistake. I have `config/packages/mailer.yaml` for `dev` and `prod` environments:

```yaml
framework:
    mailer:
        dsn: '%mailer_transport%://%mailer_user%:%mailer_password%@%mailer_host%:%mailer_port%'
```

... and `config/packages/test/mailer.yaml` for tests:

```yaml
framework:
    mailer:
        dsn: null://null
```

Setting a named transport just replaces `[main]` with `[foo]` but `null://` is still appended. And if I get rid of `config/packages/test/mailer.yaml` altogether I still get two transports, `[main]` and `smtp://smtp.mailtrap.io:587`.
