### DISCUSSION TITLE
Cache - How to override default table name and columns for DoctrineDbalAdapter?

### DISCUSSION THREAD

**Discussion by pauljura** [symfony/symfony#58168] [Q&A] [answered]
Hi all, I'm adding login throttling to my website and using DoctrineDbalAdapter for the cache. I would like to change the default table name & columns to align with the naming conventions of our existing database. It looks like it supports an $options array, but I can't figure out how to supply this.

The documentation for DoctrineDbalAdapter (https://symfony.com/doc/current/components/cache/adapters/doctrine_dbal_adapter.html) is not helpful as I'm not creating a new DoctrineDbalAdapter object in my own code; it gets created automatically by Symfony.

I was expecting to be able to use autowiring similar to how I can specify the $options for PdoSessionHandler in my services.yaml file, but I just can't get it to work.

This is my setup:

```
framework:
    cache:
        app: cache.adapter.doctrine_dbal
        pools:
            login_throttling.cache:
                adapter: cache.adapter.doctrine_dbal

    rate_limiter:
        username_ip_login:
            policy: token_bucket
            limit: 5
            rate:
                amount: 1
                interval: '5 minutes'
            cache_pool: login_throttling.cache
        ip_login:
            policy: sliding_window
            limit: 50
            interval: '15 minutes'
            cache_pool: login_throttling.cache
```

I've tried the following in services.yaml:

```
services:
    Symfony\Component\Cache\Adapter\DoctrineDbalAdapter:
        arguments:
            $options: { 'db_table': 'my_custom_table' }
```

but this has no effect.

Then I tried:
```
services:
    cache.adapter.doctrine_dbal:
        class: Symfony\Component\Cache\Adapter\DoctrineDbalAdapter
        arguments:
            $options: { 'db_table': 'my_custom_table' }
```
but that results in error: Service "cache.app": The argument "0" doesn't exist in class "Symfony\Component\Cache\Adapter\DoctrineDbalAdapter".

Then I tried:
```
services:
    cache.adapter.doctrine_dbal:
        class: Symfony\Component\Cache\Adapter\DoctrineDbalAdapter
        arguments:
            - '%env(DATABASE_URL)%'
            - 'namespace'
            - '0'
            - { db_table: 'my_custom_table' }
```
which is a little better, but it still doesn't work because I'm not setting the correct values for the arguments (I would like to leave all values as they are, just override the $options argument).

This page: https://symfony.com/doc/current/cache.html#custom-provider-options shows how to set custom options for Redis, but I tried that approach for DoctrineDbalAdapter and ran into the same issues: I still can't get the correct arguments while setting a custom $options array.

Could someone help, or tell me this is not possible?

**Comment by MatTheCat** [comment, marked as answer]
Hello,

indeed the documentation could be more helpful on that point; note that you can open issues: https://github.com/symfony/symfony-docs/issues/new

If you want to configure the dbal adapter you have to do it yourself by creating the service and configuring it as `cache.app`:

```yaml
# config/packages/cache.yaml
framework:
  cache:
    app: my_adapter
```

```yaml
# config/services.yaml
services:
  my_adapter:
    parent: cache.adapter.doctrine_dbal
    arguments:
      $connOrDsn: '@database_connection'
      $options:
        db_table: my_adapter_table
```

**Reply by pauljura** [reply]
Hi, thanks for your response. I wasn't sure whether to raise this as a bug report or a feature request or a documentation update, so I settled on a question here :)

I did what you wrote, but it doesn't seem to be working 100%.

I added a breakpoint in DoctrineDbalAdapter::__construct and in a single request it gets invoked 4 times. The first time, all arguments are the same as default and $options is an empty array. The second and third look correct, with my custom $options. The fourth has my custom $options, but an empty string for namespace.

I also added a breakpoint in DoctrineDbalAdapter::createTable and it gets invoked after the 4 calls to __construct. But $sql is "CREATE TABLE cache_items ..." not my custom table name.

Is this a bug or am I missing something?

**Reply by pauljura** [reply]
Nevermind, I figured it out. Had to set my custom adapter for "pools" as well.

```
framework:
    cache:
        app: custom_cache_adapter

        pools:
            login_throttling.cache:
                adapter: custom_cache_adapter
```
