### DISCUSSION TITLE
PasswordStrength custom estimator

### DISCUSSION THREAD

**Discussion by justin-oh** [symfony/symfony#58247] [Q&A]
I was looking at the `PasswordStrength` constraint and noticed the validator constructor is defined as follows:

```php
    /**
     * @param (\Closure(string):PasswordStrength::STRENGTH_*)|null $passwordStrengthEstimator
     */
    public function __construct(
        private readonly ?\Closure $passwordStrengthEstimator = null,
    ) {
    }
```

Is there any way to pass in a custom closure? My goal is to bypass strong passwords in dev environments so developers can have easy passwords to remember.

**Comment by MatTheCat** [comment]
This was more complex that I thought so beware, I may have overcomplexified this answer.

First you have to create your own invokable estimator as a service, e.g.

```php
<?php

namespace App;

use Symfony\Component\Validator\Constraints\PasswordStrength;

class StrongPasswordStrengthEstimator
{
    public function __invoke(string $password): int
    {
        return PasswordStrength::STRENGTH_STRONG;
    }
}
```

Then you need to “convert” it to a closure:

```yaml
when@dev:
    services:
        app.password_strength_estimator.strong:
            class: Closure
            factory: ['Closure', 'fromCallable']
            arguments: ['@App\StrongPasswordStrengthEstimator']
```

Now you can reconfigure the `PasswordStrengthValidator`:

```yaml
when@dev:
    services:
        # …
        Symfony\Component\Validator\Constraints\PasswordStrengthValidator:
            arguments: ['@app.password_strength_estimator.strong']
```
