### DISCUSSION TITLE
Symfony workflow allow transition from any state

### DISCUSSION THREAD

**Discussion by leoleva** [symfony/symfony#58301] [Q&A] [answered]
Hey, I'm wondering if there is an available configuration option that would allow me to make a transition from any state.

In my implementation, I have xx amount of transitions and few of them can go to a particular transition from any state.  To allow so I have to repeat the same `from` configuration in all of those special cases. Example:
```
framework:
    workflows:
        custom:
            transitions:
                to_failure:
                    from: [list of xx states]
                    to:   failed
               to_deleted:
                    from: [same list of xx states]
                    to:   deleted
                to_canceled:
                    from: [again same list of xx states]
                    to:   canceled
```

I'm wondering if there is a way to configure it so it would be allowed to go from any state. Something like this:
```
framework:
    workflows:
        custom:
            transitions:
                to_failure:
                    from: __any__
                    to:   failed
               to_deleted:
                    from: __any__
                    to:   deleted
                to_canceled:
                    from: __any__
                    to:   canceled
```

Maybe there is a different way to optimize it? 

Thanks
