### DISCUSSION TITLE
[RateLimiter] Multiple intervals

### DISCUSSION THREAD

**Discussion by Donder172** [symfony/symfony#58417] [Q&A]
I have been looking around for a while, but can't find anything on it.

What I'm looking for is to be able to have two or more intervals for multiple failed attempts at logging in. To give an example:

If a user fails to log in 5 times in a row, they get an interval of 5 minutes. If they, after those 5 minutes, fail to log in 5 times in a row again, they get an interval of 10 minutes etc.

**Comment by DylanKas** [comment]
Symfony documentation gives you hint on [how to implement this](https://symfony.com/doc/current/security.html#limiting-login-attempts).

From the documentation:

> If you need a more complex limiting algorithm, create a class that implements [RequestRateLimiterInterface](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpFoundation/RateLimiter/RequestRateLimiterInterface.php) (or use [DefaultLoginRateLimiter](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Security/Http/RateLimiter/DefaultLoginRateLimiter.php)) and set the limiter option to its service ID:


So you should be able to create your own algorithm using the rate limiter component. You can then use it with your login throttling as mentioned in the documentation.

Like this:

```
services:
    # our custom login rate limiter
    app.login_rate_limiter:
        class: Symfony\Component\Security\Http\RateLimiter\DefaultLoginRateLimiter
        arguments:
            # globalFactory is the limiter for IP
            $globalFactory: '@limiter.ip_login'
            # localFactory is the limiter for username+IP
            $localFactory: '@limiter.username_ip_login'
            $secret: '%kernel.secret%'

security:
    firewalls:
        main:
            # use a custom rate limiter via its service ID
            login_throttling:
                limiter: app.login_rate_limiter
```
