### DISCUSSION TITLE
[Scheduler] Symfony Command Console Running in SQL Transaction with Doctrine Middleware During Scheduler Execution

### DISCUSSION THREAD

**Discussion by yagami271** [symfony/symfony#58737] [Q&A]
### Symfony version(s) affected

7.1

### Description

I hope you’re well. I’d like to report a potential issue with my current Symfony Scheduler configuration, 
specifically related to SQL transactions when using messenger.bus.command as the default_bus.

###  Configuration Overview
Here's my Messenger configuration for reference:

```yaml 
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
             failed: 'doctrine://default?queue_name=failed'
             sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
        default_bus: messenger.bus.command
        buses:
            messenger.bus.default:
            messenger.bus.command:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_transaction
            messenger.event.bus:
                default_middleware:
                    enabled: true
                    # set "allow_no_handlers" to true (default is false) to allow having
                    # no handler configured for this bus without throwing an exception
                    allow_no_handlers: true
```

### Issue Description 1

I'm running a Symfony command, scheduled as a cron job to execute every minute. When I run the following command:

```bash
php bin/console messenger:consume scheduler_default -vvv
```

I observe that the entire Symfony command is encapsulated in an SQL transaction due to the default bus being set to messenger.bus.command.

Problem Scenario

If, for example, a command dispatches 100 messages, and an exception occurs on message 99, everything up to that point is rolled back. This behavior could cause significant issues with long-running commands or those processing numerous messages. I've attached a screenshot for reference.

<img width="1642" alt="capture_1" src="https://github.com/user-attachments/assets/b1446a45-5920-4c1a-aec4-ed2c2a2b628c">

Could you advise if there’s a way to handle partial failures or an alternative configuration to avoid full transaction rollback?

Thank you in advance for your guidance!

### Issue Description 2

I configured **default_bus** with **messenger.bus.default" without any middleware, and this works as expected—there is no transaction involved.

<img width="1638" alt="capture_2" src="https://github.com/user-attachments/assets/5273b3b8-ff00-4b48-bfa0-3db01699a7d0">

However, I’m encountering an issue with DispatchAfterCurrentBusMiddleware. For instance, if a Symfony command dispatches 100 messages and each message then triggers an event using the DispatchAfterCurrentBusStamp, an error on message 99 will cause all 98 previous events to be lost. This appears to be due to how DispatchAfterCurrentBusStamp handles events in this context.

Could you advise on how to prevent event loss in this scenario?

### How to reproduce

Here is link for small project that reproduce the issues https://github.com/yagami271/scheduler-issue/tree/main 

### Possible Solution

We've configured a default_bus with all the default Symfony Messenger middleware, except for DispatchAfterCurrentBusMiddleware.

```yaml 
        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                default_middleware: false
                middleware:
                    - 'add_bus_name_stamp_middleware': [ 'messenger.bus.default' ]
                    - failed_message_processing_middleware
                    - send_message
                    - handle_message
```

**Comment by RosskoDCA** [comment]
Have you come up with a solution? I currently need a scheduler completely outside of doctrine transactions, but I can't find in the documentation how to set which bus the scheduler should use and my default bus should use transaction.

**Reply by DrIsmaileAbdallah** [reply]
the solution i found is 
to configure a default bus like that 
```yaml 
default_bus: messenger.bus.default
 messenger.bus.default:
    default_middleware: false
    middleware:
        - 'add_bus_name_stamp_middleware': [ 'messenger.bus.default' ]
        - failed_message_processing_middleware
        - send_message
        - handle_message
```

So my scheduler will handle each message in each transaction
