### DISCUSSION TITLE
Making scoped HTTP clients a public service

### DISCUSSION THREAD

**Discussion by danrot** [symfony/symfony#58770] [Q&A] [answered]
Hey, I have a a problem regarding scoped HTTP clients and my testing setup... I have configured a scope client like the following (replaced some sensitive data):

```yaml
framework:
    http_client:
        scoped_clients:
            <some_service>.client:
                base_uri: '%env(<SOME_SERVICE>_URL)%'
```

This works as expected, however, I am having some issues with my tests. I get errors like these:

```
ServiceNotFoundException: The "<some_service>.client.uri_template" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

I've seen that issue before, so I thought that should be as easy as marking this service public (since using dependency injection is not really an option in my test setup):

```yaml
when@test:
    services:
        <some_service>.client.uri_template:
            public: true
```

However, then I get the following error:

```
The definition for "<some_service>.client.uri_template" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.
```

But now I am a bit confused... I don't really know how this service is built under the hood, but the way I remember it, is that just marking that service as `public` should not get rid of the class...

So my question is: how can I make that scoped HTTP client service public?

**Comment by danrot** [comment, marked as answer]
Ah, my bad, looks I have remembered that wrong... When defining services like this it indeed overrides the other stuff (like `class`) as well... What needs to be done is to make a public alias to avoid that the service is removed from the container:

```
when@test:
    services:
        test.<some_service>.client:
            alias: <some_service>.client
            public: true
```
