### DISCUSSION TITLE
type setting in doctrine.yaml when using a custom mapping driver

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#58811] [Q&A]
related to https://github.com/symfony/symfony/issues/58738

If I create my own MappingDriver, how to I configure that in doctrine.yaml?

https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/metadata-drivers.html#implementing-metadata-drivers

Can I simply set type to the name of my class?  Or do I need to somehow register my MappingDriver class and set a name or alias somewhere?

**Comment by tacman** [comment]
Ah, I'm starting to see -- that is what the 'php' type is for.  So staticphp looks for a static class in the entity itself, where php looks for classes that extend the FileDriver class?

**Comment by tacman** [comment]
I've implement my driver, copying from https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/metadata-drivers.html

```php
namespace App\Service;

use Doctrine\Persistence\Mapping\ClassMetadata;
use Doctrine\Persistence\Mapping\Driver\FileDriver;

class MyMetadataDriverService extends FileDriver
{
    /**
     * {@inheritDoc}
     */
    protected $_fileExtension = '.dcm.yml';

    /**
     * {@inheritDoc}
     */
    public function loadMetadataForClass($className, ClassMetadata $metadata)
    {
        dd($className, $metadata);
        $data = $this->_loadMappingFile($file);

        // populate ClassMetadata instance from $data
    }


    protected function loadMappingFile(string $file)
    {
        dd($file);
        // TODO: Implement loadMappingFile() method.
    }
}
```

i've defined my Entity in doctrine/config:

```yaml
# my custom configuration, doctrine/config/Entity.AlbumRoot.dcm.yml
id:
  type: int
  identity: true
```

I've set doctrine.yaml, following https://symfony.com/doc/current/reference/configuration/doctrine.html#mapping-configuration

```yaml
    orm:
        mappings:
            App:
                type: php
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
                alias: App
```

And I have my Entity itself in src/Entity, like I normally do with Attribute definitions:

```php
namespace App\Entity;

final class AlbumRoot
{
	public int $id;
	public string $label;

}
```

I think I'm close.  Gut feeling is there's something missing relating the App\Entity class (now a Plain PHP class) and the metadata definition in Entity.AlbumRoot.dcm.yml.  Or perhaps the MyMappingDriverService isn't being picked up.

FWIW, I've also tried pointing the dir to src/Entity in doctrine.yaml

```yaml
                dir: '%kernel.project_dir%/src/Entity'
#                dir: '%kernel.project_dir%/config/doctrine'
```
