### DISCUSSION TITLE
Best practices for require/require-dev symfony components/bundles

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#58979] [Q&A]
A lot of bundles reference 6.0 in their requirements, e.g.

```json
       "symfony/cache": "^5.4|^6.0|^7.0",
       "symfony/framework-bundle": "^5.4|^6.0|^7.0",
```

Wouldn't it be better to only allow supported Symfony, none of the red in https://symfony.com/releases#symfony-releases-calendar

```json
       "symfony/cache": "^5.4|^6.4|^7.1",
       "symfony/framework-bundle": "^5.4|^6.4|^7.1",
```

![image](https://github.com/user-attachments/assets/68084af1-76b3-4b4f-8ee4-0c0757b69b37)

That should also make the CI matrix for github actions smaller, otherwise you'd properly need to test all everything, right.

```yaml
jobs:
  test:
    name: PHP ${{ matrix.php }}, SF ${{ matrix.symfony }} - ${{ matrix.deps }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        deps: [highest]
        symfony: [5.4.*, 6.4.*, 7.1.*, 7.2.*]
        include:
          - php: 8.1
            deps: lowest
            symfony: '*'
        exclude:
          - php: 8.1
            symfony: 7.1.*
          - php: 8.1
            symfony: 7.2.*
```
