### DISCUSSION TITLE
[Profiler] Logs missing when using the profiler with a phpunit Test

### DISCUSSION THREAD

**Discussion by epitre** [symfony/symfony#59034] [Q&A]
Hello,  
I'm using symfony 7 and I want to be able to use the profiler with a phpunit Test.  
It works. I can see all the calls from a phpunit test, except one thing, the logs !  
I cannot see any logs in the profiler of a request from a phpunit test.  
If it's a profile from a request of the dev env, no problem.  
But from the test env, the logs do not appear in the profiler. Yet, I see the logs in the file var/log/test.log  

Here is the config in config/packages/test/monolog.yaml

```
monolog:
    handlers:
        test:
            type: test
            level: debug
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!php"]
        console:
            type: console
            level: info
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation_stream:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation_stream
            max_level: debug
            channels: ["php"]
```

Here is the config in config/packages/test/web_profiler.yaml

```
web_profiler:
    intercept_redirects: false

framework:
    test: true
    profiler: { enabled: true, collect: true, only_exceptions: false }
```

Any Idea why I can't see any logs from the test environment in the profiler ?
