### DISCUSSION TITLE
[Symfony Messenger] Unexpected behavior while setting rate limiter

### DISCUSSION THREAD

**Discussion by Gasjki** [symfony/symfony#59147] [Q&A]
Hello everyone! In our production environment we are using Symfony Messenger. Since, we are connected to a 3rd-party which cannot support too many requests in a minute, we decided to use Rate Limiter so we won't put any pressure on it. 

config/packages/rate_limiter.yaml
```yaml
framework:
  cache:
    pools:
      cache.worker_rate_limiter:
        adapter: cache.adapter.redis
        provider: snc_redis.worker_rate_limiter

  rate_limiter:
    queue_name_worker:
      policy: 'sliding_window'
      limit: 120
      interval: '60 seconds'
      cache_pool: 'cache.worker_rate_limiter'
```

config/packages/messenger.yaml
```yaml
            app_queue_name:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: app_queue_name_failure
                rate_limiter: queue_name_worker
                retry_strategy:
                    max_retries: 5
                    delay: 5000
                    multiplier: 5
                options:
                    auto_setup: true
                    vhost: '%env(MESSENGER_VHOST)%'
                    exchange:
                        name: app_queue_name
                    queues:
                        app_queue_name: ~
```

Note: Before configuring rate limiter, our application was in production for about 4 months and no unexpected error occurred while running the workers.

I installed everything, then I configure my rate limiter to write in Redis and I set that configuration to our queue. However, after less than 24 hours I observed a strange behavior. Multiple messages were marked with "Redelivered message from AMQP detected that will be rejected and trigger the retry logic." and they ended up on failure queue. I reproduced this behavior on localhost by setting `sleep(60)` in my worker and closing it before that time expired. My message on queue got that redelivered flag set as true.

We don't see any logs reported for errors, so that's what makes this behavior even stranger. 

Have you occurred this behavior before? How you solved it?

All the best!

Infrastructure information:
- Symfony 6.4 LTS
- MySQL 8.1
- RabbitMQ 
- AWS ECS for workers

LE: I just rechecked our logs and what's strange is that even at the first read from MQ we will get this error.
