### DISCUSSION TITLE
[DependencyInjection] `Autoconfigure` attribute does not auto-tag services

### DISCUSSION THREAD

**Discussion by kozlice** [symfony/symfony#59217] [Q&A]
**Symfony version(s) affected**: 5.3.0-BETA4

**Description**
[The announcement in blog]() says that the new `Autoconfigure` attribute can be used to tag services instead of using `registerForAutoconfiguration` in the kernel.

**How to reproduce**
- Clone the repository: https://github.com/kozlice/symfony-autoconfigure-bug
- Run `bin/console debug:container --tag=app.my_service`. Command shows there are no services with this tag despite `App\Service\MyServiceInterface` having the attribute.
- Go to the `Kernel`, uncomment the line with `registerForAutoconfiguration`. Run CLI command again. The services are now tagged properly.

**Possible Solution**
The `RegisterAutoconfigureAttributesPass` uses Reflection API to fetch attributes:
```php
$class->getAttributes(Autoconfigure::class, \ReflectionAttribute::IS_INSTANCEOF)
```
Apparently, the second parameter does not traverse up the class hierarchy searching for attributes. The php.net manual [doesn't even mention it](https://www.php.net/manual/en/language.attributes.reflection.php). And that's weird, because phpStorm provides suggestions about it which say pretty much the same as [the article on php.watch](https://php.watch/articles/php-attributes#reflection-filtering).

**Additional context**
Reproduces in PHP 8.0.1 and 8.0.6.

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer!

The reason is that the interface is not discovered by the container, this does it:
```diff
--- a/config/services.yaml
+++ b/config/services.yaml
@@ -5,5 +5,6 @@ services:
         autowire: true
         autoconfigure: true
 
+    App\Service\MyServiceInterface: ~
     App\Service\MyServiceA: ~
     App\Service\MyServiceB: ~
```

Not sure if this is the best behavior or not, but this how it works right now :)

**Comment by kozlice** [comment]
Oh, okay, got it now. Thanks!

Do you mind if I try to make it work without explicit interface mentioning? On the one hand, I think it would provide better developer experience, but on the other hand I see how implementing it might become an issue. Maybe you already know if this is futile :)

**Comment by nicolas-grekas** [comment]
I don't know :)
Which means to me that we'd better wait to gain some more experience on the topic before acting.

**Comment by n0rbyt3** [comment]
@kozlice By default, the services.yaml registers all classes in the ```App``` namespace as service. Did you remove these lines by accident?

services.yaml
```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
```
You don't need to register your services manually then.

**Comment by nicolas-grekas** [comment]
Closing for now as this has been answered. Thanks for opening.

**Comment by melkamar** [comment]
Note for future readers, the behavior is different when declaring services through the `resource` config vs when listing the classes one by one. 

Taking the following interface and class:

```php
namespace App;

#[AutoconfigureTag]
interface TaggedInterface {}

class ImplementingClass implements TaggedInterface {}
```

Let's go through the scenarios of what is in `services.yaml`:

## Only ImplementingClass is explicitly registered as a service
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\ImplementingClass: ~
```

This case is what OP describes. `ImplementingClass` will _not_ be tagged, because Symfony does not know anything about `TaggedInterface`.

## Both ImplementingClass and TaggedInterface are explicitly registered as services
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\ImplementingClass: ~
    App\TaggedInterface: ~
```

In this case _both_ `ImplementingClass` and `TaggedInterface` are registered as services and both have tags. This is a problem if you then try to iterate through the tagged services with e.g. `#[AutowireIterator()]` because you will be given the interface there and PHP will crash with

```
Cannot instantiate interface App\TaggedInterface
```

## Services are registered through the "wildcard" resource key

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App:
      resource: .
```

This is the only variant that works. Even when the `TaggedInterface` is in the same directory as `ImplementingClass`, when they are picked up through the `resource` yaml key, only `ImplementingClass` will end up being registered. 

The scenarios can be confirmed with `bin/console debug:container --tag TaggedInterface`

**Comment by stof** [comment]
@melkamar this is because the PSR-4 discovery will register interfaces and abstract classes as abstract services (and AutowireIterator excludes abstract services when collecting the tagged services), while your code using explicit registration did not mark the interface service as abstract

**Comment by melkamar** [comment]
@stof thanks, I have tried your suggestion, used the explicit YAML, but now I am getting an error:

```yaml
# services.yml

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\ImplementingClass: ~
    App\TaggedInterface:
        abstract: true
```

```
The service "App\TaggedInterface" tagged "App\TaggedInterface" must not be abstract.
```
