### DISCUSSION TITLE
CSRF: Generated HTML value is `"csrf_token"` in Dev

### DISCUSSION THREAD

**Discussion by Menelion** [symfony/symfony#59382] [Q&A] [answered]
Folks, I'm developing a Symfony 7.2 app and I'm having a stupid error. I definitely missed something but I don't know what.
When I try to log in (I use slightly tweaked output of `make:security:login-form`), it says "Invalid CSRF token". and of course it is invalid, because HTML field generated by Twig looks like this:

```html
<input type="hidden" name="_csrf_token"
value="csrf-token"
        >
```

So, the value of the token is, well, `csrf-token`. Although Twig is correct:

```twig
        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >
```

Here is the firewall:

```yaml
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: /
```

It's a Windows machine, environment is `Dev`, debug is on.
Any ideas are hugely appreciated.

**Comment by MatTheCat** [comment]
7.2 recipes configure some [stateless CSRF](https://symfony.com/blog/new-in-symfony-7-2-stateless-csrf) token IDs like `authenticate`.

The [StimulusBundle’s recipe has been updated](https://github.com/symfony/recipes/pull/1337/files#diff-a92209d6ca70e2bd935a6eb29f494d2b409f3980cb50a29cb94dac0c418900db) as well to generate the token client-side, but if you’re not using it you have two options:
- unconfigure stateless token IDs
- implement the token generation and cookie creation yourself

**Comment by Menelion** [comment]
Sorry @MatTheCat, but I still don't understand. I have no such things in the configuration, so should I add it manually? In my `framework` node I have:

```yaml
framework:
    secret: '%env(APP_SECRET)%'
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```

So nothing related to CSRF in the Framework node. Should I re-add it or?.. It's a clear new 7.2 installation, so I'm confused.

**Reply by MatTheCat** [reply]
The corresponding config got moved in `csrf.yaml` by https://github.com/symfony/recipes/pull/1361 so you should find this one?

**Comment by Menelion** [comment]
Yepp, `csrf.yaml` is like this:

```yaml
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
```

So what am I missing here? Here's the login template:

```twig
{% extends 'base.html.twig' %}

{% block title %}Please Sign In{% endblock %}

{% block content %}
    <form method="post">
        {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}

        {% if app.user %}
            <div class="mb-3" role="contentinfo">
                You are logged in as {{ app.user.displayName}}, <a href="{{ path('app_logout') }}">Logout</a>
            </div>
        {% endif %}

        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="username">Username</label>
        <input type="text" value="{{ last_username }}" name="_username" id="username" class="form-control" autocomplete="username" required autofocus>
        <label for="password">Password</label>
        <input type="password" name="_password" id="password" class="form-control" autocomplete="current-password" required>

        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >

        <button class="btn btn-default" type="submit">
            Sign in
        </button>
    </form>
{% endblock %}
```
