### DISCUSSION TITLE
Unable to login programmatically, authenticator Main not found

### DISCUSSION THREAD

**Discussion by Menelion** [symfony/symfony#59455] [Q&A] [answered]
In a Symfony 7.2 app, in my dev environment, I want my users to be logged in automatically after setting a password. Obviously, in my controller I have:

```php
return $security->login($user, 'form_login', 'main');
```

Here's what I get when hitting this:

```
Unable to find an authenticator named "form_login" for the firewall "main". Available authenticators: "debug.security.authenticator.form_login.main", "debug.security.authenticator.remember_me.main".
```

Firewall in security.yaml:

```yaml
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                target: /
            remember_me:
                lifetime: 2624016 # 1 month in seconds
                secure: true
                signature_properties: ['email', 'password']
```

So firewall.main is in place, and usual login works as expected.
Is it a Symfony bug or am I missing something? thanks.
