### DISCUSSION TITLE
User session not maintained after successful login

### DISCUSSION THREAD

**Discussion by DocFX** [symfony/symfony#59452] [Q&A]
Hi, I have a small problem that has to have an obvious solution with Security.

I have a website with a VERY classic and simple form for logging in, generated by the MakerBundle. Works like a charm. 
It pulls users from a User Doctrine entity, as I suppose many many websites do. Works like a charm. 
It gets the user name from a username property. Again, can't be more classic!

The generated Authenticator was barely edited so as to choose the redirect after login route.

Now, User entities also have a generated ULID on their account, which they can use to log in, provided they didn't lose it, instead of password authentication. They first have to log in in their account and note it down (less secure than passwords).

So I created a simple form which checks and asks for their email, username and unique code. Works like a charm: it's found in the database, bringing a User entity back and if it passes all checks, the Controller action logs the user in.

----

Problem: 
Whether I use login() method from Security or authenticateUser(), they both, success, but this is what happens:
- the anonymous user had no Cookie set (good)
- the anonymous user becomes logged in, Response contains a PHPSESSID cookie (good)
- the browser send requests for assets after the response that logged them in, it sends the correct cookie in requests (good)
- then if the user goes to ANY Symfony backend request, it sends TWO PHPSESSID tokens, the wrong one being the first, and hence become immediately logged out and their session is invalidated.

Code that might help:

The controller action that logs the user in:

```php
    #[Route(path: '/login-with-unique-code', name: 'app_login_code')]
    public function loginWithCode(EntityManagerInterface $entityManager, Request $request, TranslatorInterface $translator, UserAuthenticatorInterface $userAuthenticator, ESFAuthenticator $authenticator): Response
    {
        if ($this->getUser() !== null) {
            return $this->redirectToRoute('front_user_account', [], Response::HTTP_SEE_OTHER);
        }

        $form = $this->createForm(LogInWithCodeType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if(Ulid::isValid(preg_replace(
                '/[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]/',
                '',
                $form->get('uniqueCode')->getData(),
            ))) {
                $queriedUser = $entityManager->getRepository(User::class)->findOneBy([
                    'username'       => $form->get('username')->getData(),
                    'email'          => $form->get('email')->getData(),
                    'uniqueCode'     => Ulid::fromString(
                        preg_replace(
                            '/[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]/',
                            '',
                            $form->get('uniqueCode')->getData(),
                        )
                    ),
                ]);

                if($queriedUser === null) {
                    $this->addFlash('error', $translator->trans('user.loginwithcode.error'));
                    $form->addError(new FormError($translator->trans('user.loginwithcode.error')));
                } elseif ($queriedUser instanceof User) {
                    $userAuthenticator->authenticateUser($queriedUser, $authenticator, $request);
                    // Same result with:
                    // $security->login($queriedUser);
                }
            } else {
                $this->addFlash('error', $translator->trans('user.loginwithcode.error'));
                $form->addError(new FormError($translator->trans('user.loginwithcode.error')));
            }
        }

        return $this->render(
            'front/security/login_with_code.html.twig',
            [
                'form'         => $form->createView(),
            ],
            new Response(null, $form->isSubmitted() && ! $form->isValid() ? 422 : 200)
        );
    }
```

The `src/Security/ESFAuthenticator` file:
```php
<?php

declare(strict_types = 1);

namespace App\Security;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\CsrfTokenBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\RememberMeBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Http\SecurityRequestAttributes;
use Symfony\Component\Security\Http\Util\TargetPathTrait;
use Symfony\Contracts\Translation\TranslatorInterface;

class ESFAuthenticator extends AbstractLoginFormAuthenticator
{
    use TargetPathTrait;

    public const string LOGIN_ROUTE = 'app_login';

    public function __construct(private UrlGeneratorInterface $urlGenerator, private TranslatorInterface $translator)
    {
    }

    public function authenticate(Request $request): Passport
    {
        $username = $request->getPayload()->getString('username');

        $request->getSession()->set(SecurityRequestAttributes::LAST_USERNAME, $username);

        return new Passport(
            new UserBadge($username),
            new PasswordCredentials($request->getPayload()->getString('password')),
            [
                new CsrfTokenBadge('authenticate', $request->getPayload()->getString('_csrf_token')),
                new RememberMeBadge(),
            ]
        );
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        if(method_exists($request->getSession(), 'getFlashBag')) {
            $request->getSession()->getFlashBag()->add('success', $this->translator->trans('user.login.success', ['username' => $token->getUser()?->getUserIdentifier()]));
        }

        if ($targetPath = $this->getTargetPath($request->getSession(), $firewallName)) {
            return new RedirectResponse($targetPath);
        }

        return new RedirectResponse($this->urlGenerator->generate('front_user_account'));
    }

    protected function getLoginUrl(Request $request): string
    {
        return $this->urlGenerator->generate(self::LOGIN_ROUTE);
    }
}

``` 

The `config/packages/security.yaml` file:
```yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\ESFAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/(%app.supported_locales_route_requirement%)/admin, roles: ROLE_ADMIN }
        - { path: ^/(%app.supported_locales_route_requirement%)/account, roles: ROLE_USER }
    role_hierarchy:
        ROLE_ADMIN: ROLE_ORGANIZER
        ROLE_ORGANIZER: ROLE_USER

when@test:
    security:
        password_hashers: 
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
```

Any clue? I mean, this HAS to be that I have a problem with User comparison or Session refresh, that has to be so simple I can't see it. Is that `EquatableInterface` related?
