### DISCUSSION TITLE
Proper way to use kernel.project_dir in PDO DNS

### DISCUSSION THREAD

**Discussion by tacman** [symfony/symfony#59569] [Q&A]
in cache.yaml

```yaml
        pools:
            # control adapter's configuration
            translation.cache:
                adapter: cache.adapter.pdo
                provider: '%env(TRANSLATION_CACHE_DSN)%'
```

in .env
```
TRANSLATION_CACHE_DSN="sqlite:/%kernel.project_dir%/translation.db"
```

This fails (unable to open) but this works:

```
TRANSLATION_CACHE_DSN="sqlite:../translation.db"
```

I've tried wrapping the kernel.project_dir in %env()%, but that wasn't it.  How can I use an environment variable in defining a PDO DNS?

Thanks.
