### DISCUSSION TITLE
[HTMLSanitizer] How to allow all data-* attributes on A elements

### DISCUSSION THREAD

**Discussion by virtualize** [symfony/symfony#59583] [Q&A] [answered]
Is there a way to allow all data- attributes? I did not found anything in the documentation.
This does not seem to work.

```yaml
framework:
    html_sanitizer:
        sanitizers:
            alert_link:
                allow_safe_elements: true
                allow_relative_links: true
                allow_attributes:
                    a: ['href', 'title', 'target', 'data-*']
```
