### DISCUSSION TITLE
Translations: enable pseudo-localization conditionally

### DISCUSSION THREAD

**Discussion by kAlvaro** [symfony/symfony#60093] [Q&A] [answered]
[Docs](https://symfony.com/doc/current/translation.html#pseudo-localization-translator) explain you can enable pseudo-localization in your YAML settings file:

```yaml
# config/packages/translation.yaml
framework:
    translator:
        pseudo_localization:
            # replace characters by their accented version
            accents: true
            # wrap strings with brackets
            brackets: true
            # controls how many extra characters are added to make text longer
            expansion_factor: 1.4
            # maintain the original HTML tags of the translated contents
            parse_html: true
            # also translate the contents of these HTML attributes
            localizable_html_attributes: ['title']
```

Is there a way to have it disabled by default, but be able to enable it by setting a parameter? I can read such parameter with `%localization.pseudo_localization_enabled%` but I'm unsure about having conditional clauses in YAML files.

**Comment by MatTheCat** [comment, marked as answer]
Yes: `pseudo_localization` can be enabled by configuring any of its options like you did, but it also has an `enabled` option you can set to `false` to disable it. So you could write something like

```yaml
# config/packages/translation.yaml
framework:
    translator:
        pseudo_localization:
            enabled: '%localization.pseudo_localization_enabled%'
            expansion_factor: 1.4
            parse_html: true
            localizable_html_attributes: ['title']
```

Note that if enabling the pseudo-localization only depends on the environment you should leverage Symfony’s way: https://symfony.com/doc/current/configuration.html#configuration-environments
