### DISCUSSION TITLE
Routing _defaults from yaml configuration overrides format from Route attribute

### DISCUSSION THREAD

**Discussion by ian-zunderdorp** [symfony/symfony#60309] [Q&A] [answered]
We're trying to configure our application to use `json` format by default and override the format for specific routes to be plain text (Prometheus metrics endpoint for example). Our expectation was that using the format parameter in the Route attribute would overwrite the format in the configuration defaults.

Configuration (`routes.yaml`):
```yaml
controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  defaults:
    _format: json
```

Route attribute:
```php
#[Route('/metrics', format: 'txt')]
public function metrics(): Response {
    return new Response(content: '# HELP');
}
```

When calling this route, the response contains the header `Content-Type: application/json` instead of the expected `Content-Type: text/plain`. We can work around this issue by explicitly setting the `Content-Type` header on the returned `Response`, but are wondering whether it is by design that the `routes.yaml` configuration overwrites the Route attribute format parameter.
