### ISSUE TITLE
[Doctrine] RegisterMappingsPass should take the  "doctrine.orm.mappings" config into account.

### ISSUE THREAD

**Issue by docteurklein** [symfony/symfony#10169]
Currently, it's not possible to unregister (or to not map) a third party bundle (f.e) that uses it.

**Comment by Chris-Bitler** [comment]
What versions of the project is this issue relevant to? I'm looking for an issue for my first contribution and this one looked like it could be a good issue to work on.

**Comment by xabbuh** [comment]
@Chris-Bitler New features are always merged into the branch for the next minor version which is the `master` branch right now.

**Comment by michaelKaefer** [comment]
If it should be done should the configuration look like this?
```yaml
# config/packages/doctrine.yaml
doctrine:
    orm:
        disabled_mappings: [Acme\Bundle\Model, Foo\Bundle\Entity]
```

And if there are multiple entity managers:
```yaml
# config/packages/doctrine.yaml
doctrine:
    orm:
        entity_managers:
            default:
                disabled_mappings: [Acme\Bundle\Model]
            customer:
                disabled_mappings: [Acme\Bundle\Model, Foo\Bundle\Entity]
```

But this has to be done in `doctrine/doctrine-bundle`, or not?

Or should there be a general solution for `doctrine/doctrine-bundle`, `doctrine/mongodb-odm-bundle`, etc.?
