### ISSUE TITLE
login_path, check_path still validated when authentication provider is not via form

### ISSUE THREAD

**Issue by gggeek** [symfony/symfony#10463]
I have a custom auth provider, similar to the WSSE example (but not stateless), and set it up for a certain path.

``` yaml
security:
    firewalls:
        my_rest_session:
            pattern: ^/api/rest_with_session/v1
            xxx: true
```

An exception gets thrown by Symfony, telling me that:

```
The check_path "/login_check" for login method "xxx" is not matched by the firewall pattern.
```

I think that in this case there should be no validation done of `check_path` and `login_path`
