### ISSUE TITLE
DIC parameters should be resolved in Aliases and arguments of type=service

### ISSUE THREAD

**Issue by checat** [symfony/symfony#10503]
Unsupported features are shown in this config:

```yaml
parameters:
  service_id: service_a
services:
  service_a:
    class: \Acme\ServiceA
  service_b:
    class: \Acme\ServiceB
    arguments:
      - "@%service_id%" # this does not work
  service_c:
    alias: "%service_id%" # this does not work
  service_d: "@%service_id%" # this does not work
```
Also, for calls' arguments I assume they does not work too, not checked.

I did not found references in the documentation that parameters must or must not be resolved in these places.

There are relevant question on SO showing that people assume they should be resolved but find they are not resolved by trial:
http://stackoverflow.com/questions/15614929/dynamic-service-id-in-an-argument-in-symfony2
http://stackoverflow.com/questions/13235140/selecting-one-of-many-services-as-the-service-to-use
http://stackoverflow.com/questions/22367057/injecting-parameter-based-service-into-other-service
http://stackoverflow.com/questions/19352417/using-service-aliases-for-dependency-injection

There is a line in the compiler pass showing that for aliases parameters were assumed to be resolved
https://github.com/symfony/symfony/blob/v2.4.2/src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php#L57
But the right part does not work because `$parameterBag->resolveValue($target)` is supplied with Alias, but `resolveValue()` works only with strings and arrays of strings.

For "arguments" and "method call arguments", References are not resolved on lines
https://github.com/symfony/symfony/blob/v2.4.2/src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php#L39
and
https://github.com/symfony/symfony/blob/v2.4.2/src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php#L43

Also the same changes are required in ContainerBuilder
https://github.com/symfony/symfony/blob/v2.4.2/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L477
https://github.com/symfony/symfony/blob/v2.4.2/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L946
https://github.com/symfony/symfony/blob/v2.4.2/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L1137

If those changes are too big, I assume, this should be fixed for aliases at least. That fix would provide a workaround for other cases, that could be documented:
```yaml
parameters:
  service_id: service_a
services:
  service_a:
    class: \Acme\ServiceA
  service_b:
    class: \Acme\ServiceB
    arguments:
      - "@service_alias"
  service_alias: "@%service_id%"
```

Currently workarounds are: change aliases directly instead of using parameters, fetch the service from the container using parameter, replace required alias or argument using custom compiler pass.
