### ISSUE TITLE
[3.0] [Form] Set default options on form types

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#10505]
Form types currently support only one way of defining default options: The `setDefaultOptions()` method, which configures an options resolver. However, especially when registering types in the DIC, it can be helpful to set default options on the type from the outside (see #10327).

This should be supported in one way or another.

**Comment by thomas-koch-comsolit** [comment]
+1
I just lost like an hour searching for a way to globally change the "widget" option of all Date form fields in my application to "single_text". I expected that there must be a way to set some configuration parameter and than all my forms will be rendered the way I want.

It seems that's not possible. The only solution that I see is to overwrite the `form.type.date` service, extend the DateType class and override the `configureOptions` method.

A naive implementation strategy might be: The Formbuilder looks in the configuration whether there is any config for the current type and uses those as default values. So the precedence would be:

 * default values defined in the type
 * default values defined in the apps configuration
 * option values defined for this field

**Comment by stof** [comment]
@thomas-koch-comsolit the solution is to register a FormTypeExtension to change the default value:

```php
namespace AppBundle\Form\TypeExtension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SingleTextDateExtension extends AbstractTypeExtension
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array('widget' => 'single_text'));
    }

    public function getExtendedType()
    {
        return 'date';
    }
}
```

and then register it:

```yaml
# app/config/services.yml
services:
    # ...
    app.form.type_extension.single_text_date:
        class: AppBundle\Form\TypeExtension\SingleTextDateExtension
        tags:
            - { name: 'form.type_extension', alias: date }
```
