### ISSUE TITLE
Yaml parse fails to understand or allow %YAML

### ISSUE THREAD

**Issue by Dragonrun1** [symfony/symfony#10597]
Directly from the docs at http://www.yaml.org/spec/1.2/spec.html#id2781553
 __A version 1.2 YAML processor _must_ accept documents with an explicit “%YAML 1.2” directive, as well as documents lacking a “YAML” directive.__

example yaml file:
```yaml
%YAML 1.2
---
yapeal:
    application_agent: ""
    registered_mode: "optional"
```

Using:
```php
$handler = new Yaml();
$result = $handler->parse($yapealYaml);
var_dump($result);
print PHP_EOL;
```

Expect:
```
Array
(
    [yapeal] => Array
        (
            [application_agent] =>
            [registered_mode] => optional
)

```

Get:
```
NULL
```
If I use %YAML 1.1 also get the same result. This is also covered in the above spec about how it should be handled.
