### ISSUE TITLE
simple_preauth and anonymous

### ISSUE THREAD

**Issue by samsamm777** [symfony/symfony#10659]
I have a firewall configuration like below. The anonymous statement does not work when using simple_preauth. I'm not sure if that is intended behavior?

``` yaml
        secured_area:
            pattern:    ^/(.+)
            stateless: true
            anonymous: ~
            simple_preauth:
                authenticator: apikey_authenticator
```
