### ISSUE TITLE
Route with default value for query string param causes param to get eaten

### ISSUE THREAD

**Issue by nickshanks** [symfony/symfony#10940]
Given a route like this:

```yaml
book:
    path: /book
    defaults:
        page: 1
````

I would expect `generate('book', {'page': $page})` to generate these routes:
1) `/book` when `$page == 1`
2) `/book?page=2` when `$page == 2`

What actually happens is that when a parameter has a default value, but is not present in the route path, it just gets eaten by Symfony. Both of the above values for `$page` result in the path `/page` being generated.
