### ISSUE TITLE
[FrameworkBundle] Form data collector should be loaded only if form config is enabled

### ISSUE THREAD

**Issue by hason** [symfony/symfony#11407]
Similar to: #6238, #7373, #9137

Config:
```yaml
framework:
  profiler:
    enabled: true
```

Result:
```
Fatal Error: Class 'Symfony\Component\Form\Extension\DataCollector\FormDataCollector' not found
```
