### ISSUE TITLE
Sharing security context across multiple firewalls

### ISSUE THREAD

**Issue by seb0zz** [symfony/symfony#11836]
Analogous to http://symfony.com/doc/current/reference/configuration/security.html#reference-security-firewall-context I tried to use the same security context across two firewalls. The problem is if I login behind the `api_secured` firewall I am still not allowed to visit sites that are secured by the `main` firewall. 

I also tried to check stackoverflow. Seems that other people already had the same problem: 
http://stackoverflow.com/questions/11801622/how-to-authenticate-on-2-different-symfony2-firewalls-at-the-same-time

My configuration looks like:

```yaml
    firewalls:
        api_secured:
            context: my_security_context
            pattern: ^/api/.*
            api:
                check_path: /api/security/login
        main:
            context: my_security_context
            pattern: ^/
            remember_me:
                key: %secret%
                name: MYREMEMBERME_%kernel.environment%
                remember_me_parameter: remember_me
                always_remember_me: true
            form_login:
                provider: fos_userbundle_provider
                csrf_provider: form.csrf_provider
                login_path: /login
                use_forward: false
                check_path: /login_check
                default_target_path: /
                failure_path: null
                success_handler: my.security.authentication_success_handler
                failure_handler: my.security.authentication_failure_chain_handler
                remember_me: true
            logout:
                path: /logout
                target: /
                csrf_provider: form.csrf_provider
                csrf_parameter: token
            anonymous: true

    access_control:
        - { path: ^/api/security/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_AUTHENTICATED_REMEMBERED }
        ...
```
