### ISSUE TITLE
Have a common way to collect services and inject it into a single one

### ISSUE THREAD

**Issue by dawehner** [symfony/symfony#12269]
Similar issue to (in the sense of having a similar context) than https://github.com/symfony/symfony/issues/11460

In Drupal we have a lot of tagged services which are injected into a single one. When we started most of them had custom Compiler Passed, but than we realized that we can easily extract that into a common service:

This would be the "collector" service:

```
  breadcrumb:
    class: Drupal\Core\Breadcrumb\BreadcrumbManager
    arguments: ['@module_handler']
    tags:
      - { name: service_collector, tag: breadcrumb_builder, call: addBuilder }
```

and then you do something like that in the client service:

```
  forum.breadcrumb.listing:
    class: Drupal\forum\Breadcrumb\ForumListingBreadcrumbBuilder
    arguments: ['@entity.manager', '@config.factory', '@forum_manager']
    tags:
      - { name: breadcrumb_builder, priority: 314 }
```

Any oppinions?

**Comment by dosten** [comment]
Any feedback about this? I like the idea because is a common use case of the compiler passes, with this we can reduce the code necessary to do something like this.

**Comment by TomasVotruba** [comment]
@Crell Thanks for implementation. This would be really great in standalone bundle.

Also it would be really nice to have this as an option. 
Already done internally by:

- event dispatcher

```yaml
services:
    app.exception_subscriber:
        class: AppBundle\EventSubscriber\ExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }
```

- console commands

```yaml
services:
    app.command.my_command:
        class: AppBundle\Command\MyCommand
        tags:
            -  { name: console.command }
```

Externally by any tag system as written by @dosten and @dawehner
