### ISSUE TITLE
[Routing] Access requirements MUST be strings, and this behavior cannot be overridden

### ISSUE THREAD

**Issue by phenaproxima** [symfony/symfony#12430]
Right now, it's impossible for a route requirement to be anything besides a string, due 
to regex enforcement.

It's literally first thing in Route::sanitizeRequirement():

```php
private function sanitizeRequirement($key, $regex)
{
    if (!is_string($regex)) {
        throw new \InvalidArgumentException(sprintf('Routing requirement for "%s" must be a string.', $key));
    }
    
    // ...etc.
}
```

In Drupal 8, we have built a great deal more complexity on top of the Symfony routing
system, and we have many routes that look like this:

```
comment.reply:
  path: '/comment/reply/{entity_type}/{entity}/{field_name}/{pid}'
  defaults:
    _content: '\Drupal\comment\Controller\CommentController::getReplyForm'
    _title: 'Add new comment'
    pid: ~
  requirements:
    # _access is a Drupal extension to Symfony.
    # It defines an absolute access condition (always accessible, or never accessible) 
    # using a boolean value. This route should always be accessible.
    _access: true
  options:
    parameters:
      entity:
        type: entity:{entity_type}
```

Due to the logic in sanitizeRequirement(), we need to write ```_access: 'TRUE'```. This is less-than-ideal DX, because it's unintuitive and very likely to throw Drupal module developers for a loop. It's all too easy to look at ```_access: 'TRUE'``` and assume we meant ```_access: true```.

The path of least resistance, it seems to me, would be to make sanitizeRequirement() a protected method so it can be overridden by Drupal core. Is that possible?
