### ISSUE TITLE
Validation Groups Not working As Expected with getters

### ISSUE THREAD

**Issue by stewartianj** [symfony/symfony#12467]
When using getter validation constraints with validation groups, multiple getters must be declared to seperate constraints by validation groups.  If there are two getter constraints in one block, the groups from one will also apply to the other.  I don't believe this is intended behavior.  

Here is an example for clarification

Works as intended, adminRegistration group gets the emailVerify getter constraint applied, newRegistration gets the usernameVerify getter applied:

```yaml
Acme\DemoBundle\Entity\User:
    getters:
        usernameVerify:
            - "True" : { groups: [newRegistration], message: user.usernameVerify.invalid }
    getters:
        emailVerify:
            - "True" : { groups: [ adminRegistration ], message: user.usernameVerify.invalid }
```

Issue, adding any of these validation groups makes both getters apply ie adding adminRegistration validation group applies both constraints to the form:

```yaml
Acme\DemoBundle\Entity\User:
    getters:
        usernameVerify:
            - "True" : { groups: [newRegistration], message: user.usernameVerify.invalid }
        emailVerify:
            - "True" : { groups: [ adminRegistration ], message: user.usernameVerify.invalid }
```
