### ISSUE TITLE
Symfony 2.5 group_sequence_provider flag is not inherited.

### ISSUE THREAD

**Issue by apolev** [symfony/symfony#12480]
Good afternoon. 
Actually I'm not truly sure, that this is a bug, but it's strange behavior anyway.

I have an Adress entity in my repository, with couple of validation groups:
validation.yml:
```
Company\CoreBundle\Entity\Address:
    group_sequence_provider: true
    properties:
        oksm:
            - NotBlank: {message: 'заполните поле', groups: [Default]}
        postalCode:
            - NotBlank: {message: 'заполните поле', groups: [RussianAddress]}
            - Regex: {message: 'индекс должен состоять из шести цифр', pattern: '/^[0-9]{6}$/', groups: [RussianAddress]}
        region:
            - NotBlank: {message: 'заполните поле', groups: [RussianAddress]}
        looselyTypedAddress:
            - NotBlank: {message: 'заполните поле', groups: [ForeignAddress]}
```

I implemented GroupSequenceProviderInterface and define getGroupSequence function:
```
/**
 * @ORM\Table(name="addresses")
 * @ORM\Entity
 */
class Address extends AbstractBase implements GroupSequenceProviderInterface
{

    // ...
    // tldr
    // ...

    public function getGroupSequence()
    {
        $groups = [];

        if ($this->oksm->isRussia()) {
            $groups[] = 'RussianAddress';
        } else {
            $groups[] = 'ForeignAddress';
        }

        return $groups;
    }
}
```

When I edit existed object all constraints with non default validation group(RussianAddress, ForeignAddress)  does not work.

It's happened because Doctrine wraps my object to Proxies\__CG__\Company\CoreBundle\Entity\Address.

In Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory::getMetadataFor is written code, which loads metadata from parent:
```
        // Include constraints from the parent class
        if ($parent = $metadata->getReflectionClass()->getParentClass()) {
            $metadata->mergeConstraints($this->getMetadataFor($parent->name));
        }
```
It works well for constraints but does not care about group_sequence_provider flag.
Sure, I've fixed that, just adding 
```
Proxies\__CG__\Company\CoreBundle\Entity\Address:
    group_sequence_provider: true
```
to my validation xml. 
But I think it'll be much more convenient if symfony inherits flags and other stuff from superclass as default.  

Regards, Alex.

P.S. Guys, thanks for this framework, it's absolutely amazing!
