### ISSUE TITLE
[DX] Controller as a service, favoring tags over class level @Route()

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#12915]
Currently when using [Controller as a Service with the SensioFrameworkExtraBundle](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html#controller-as-service), you will have to add an `@Route(service="acme_hello.controller.my_controller")`. This feels unnatural, as it has nothing to do with routes. 

As of 2.4, [Command as a Service](http://symfony.com/doc/current/cookbook/console/commands_as_services.html) was introduced. That made configuring the command really easy, you only have to add a tag to your service: `-  { name: console.command }`.

My suggestion is to drop support for the `service` option in the `@Route` (and make both possible in 2.7) in favor of a tag on the service. The configuration could look like:

```yaml
services:
    acme_hello.controller.my_controller:
        class: Acme\HelloBundle\Controller\MyController
        tags:
            -  { name: framework.controller } # or perhaps: request.controller
```

This configuration feels far more natural and is in line with command configuration. I know this is supposed to be part if the SensioFrameworkExtraBundle, but getting feedback there is hard.
