### ISSUE TITLE
[Translator] Does not make use of `request.locale` anymore?

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony#12988]
When upgrading from `2.5.8` to `2.6.1` the `Translator` component does not seem to be compatible with the ["sticky locale" from the cookbook article](http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html).

The difference with my implementation is that I use `services.yml` in order to make the call, instead of implementing the `EventSubscriberInterface`.

```yaml
services:
    acme.locale_listener:
        class: Acme\DemoBundle\EventListener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocaleForUnauthenticatedUser }
```

Injecting the `Translator` into the `Listener` and setting the locale manually does solve the problem. Re-adding the code that is removed by [this commit of Sept 26](https://github.com/symfony/FrameworkBundle/commit/4544028b94e0da17d67b607b68d765b610e787ad) also does result in the expected behaviour again.

Has the behaviour changed, or is this behaviour wanted?

**Comment by Rvanlaak** [comment]
You are right @xelaris , but the main point is that the `defaultLocale` is hardcoded to `en` in the [`Request`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L208), which makes it impossible to check or it is `null` when using [`Request->getLocale()`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L1451-L1459).

When visiting `.com` I can not do checks against it. The framework config having `en` as a default value is no problem to me. Being unable to configure framework as `null` (with priority 17 as you mention) results into problems to me.

**Comment by xelaris** [comment]
It is useless to call Request::getLocale() in an event listener with Prio 17, since it isn't set at this time. If your usecase/Listener requires the locale to be set on the Request (thats the difference to the cookbook entry, where it is not the case), then register your Listener with Prio 11 to 15. The LocaleListener with Prio 16 just reads the actual locale from the `_locale` routing attribute (if any) and stets Request::$locale to that value. It also sets the Request::defaultLocale from the config, which is also available via the container parameter `kernel.default_locale`.

**Comment by solazs** [comment]
I've ran into the issue as well, but in a different environment.
We're developing a REST API in symfony, so all our requests are stateless. We have to send multilingual e-mails, so I'm trying to set the local in the controller (using `$request->setLocale('en_US')` or `$request->setLocale('hu_HU')`), but the translator (and the twig) ignores it altogether and uses the fallback locale from config. 
messages.hu.yml and messages.en.yml are in the correct place and have the correct labels.

**Comment by stof** [comment]
@solazs the translator reads the request locale during the kernel.request event. So changing it in the controller is too late, and you indeed need to set it directly in the translator

**Comment by solazs** [comment]
Then the section in the translation documentation about setting the locale in the controller shoud definetly mention this, as a developer trying to achive stateless (sessionless) locale setting would not read the section about the "Sticky" locale listener.
http://symfony.com/doc/current/book/translation.html#handling-the-user-s-locale

**Comment by javiereguiluz** [comment]
Closing it as fixed because the translator documentation already added a note about this:

![locale_note](https://cloud.githubusercontent.com/assets/73419/12619744/bc92816e-c519-11e5-831c-53e731f6cf06.png)

**Comment by rvanlaak** [comment]
Yes can be closed, :+1: for the doc note

**Comment by solazs** [comment]
I forgot to post about the PR here
https://github.com/symfony/symfony-docs/pull/5099

**Comment by Manupucelano** [comment]
I am quite interested in this operation, and I do not get it to work. I have modified the priorities and it still does not work. What modifications do I need to make?

The open thread in stackoverflow is [Stackoverflow](https://stackoverflow.com/questions/45450807/symfony-2-8-fosuserbundle-user-locale-internacionalization-doesnt-work)

And the modification that I thought and did not work was:

```
services:
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, priority: 15, event: security.interactive_login, method: onInteractiveLogin }
```
