### ISSUE TITLE
LoggingTranslator does not implement TranslatorBagInterface

### ISSUE THREAD

**Issue by cmfcmf** [symfony/symfony#13632]
The LoggingTranslator does not implement the TranslatorBagInterface but should implement it, Right?https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/LoggingTranslator.php#L19.

**Comment by fabpot** [comment]
ping @aitboudad

**Comment by aitboudad** [comment]
@fabpot, @cmfcmf What do you think add a new option to skip logging for some domains ?
```yaml
logging_domaines: ~    # Log all the domaines

logging_domaines: foo  # Log only domaine "foo"
logging_domaines: "!foo" # Log all domaines, except "foo"

logging_domaines: [foo, bar]   # Log only domaines "foo" and "bar"
logging_domaines: ["!foo", "!bar"] # Log all domaines, except "foo" and "bar"
```
