### ISSUE TITLE
[DX][Routing] Host requirement on imported routes

### ISSUE THREAD

**Issue by hackzilla** [symfony/symfony#13689]
I'm trying to setup the following

domain -> AppBundle routing
www.domain -> redirect to domain
*.domain -> HackzillaSitesBundle routing

I expected the following to work.

```yaml
hackzilla_main:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

hackzilla_www_redirect:
    path:     /
    host:     "www.{domain}"
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: main_homepage
        permanent: false
    defaults:
        domain: %domain%
    requirements:
        domain: %domain%

hackzilla_sites:
    resource: "@HackzillaSitesBundle/Resources/config/routing.yml"
    host:     "*.{domain}"
    prefix:   /
    defaults:
        tld: %domain%
    requirements:
        tld: %domain%
```

However it seems host is only expecting a literal string, and the documentation seems to suggest this.

I can get round this by moving the host, defaults and requirements on to each route, but it makes more sense to me to put this limit on the imported routes.

**Comment by Nek-** [comment]
By literal string you mean "without parameter" ? Because I use in prod this feature (domain as parameter `%domain%`) and it works great.

**Comment by Tobion** [comment]
What do you have configured for `%domain%`? And what should `*.{domain}` do?

**Comment by hackzilla** [comment]
Didn't know %variables% worked in the host. :+1: 

Maybe a note here would help: http://symfony.com/doc/current/components/routing/hostname_pattern.html#using-host-matching-of-imported-routes

```yaml
hackzilla_main:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    host: "%domain%"

hackzilla_www_redirect:
    path:     /
    host:     "www.%domain%"
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: main_homepage
        permanent: false

hackzilla_sites:
    resource: "@HackzillaSitesBundle/Resources/config/routing.yml"
    prefix:   /
    host: "*.%domain%"
```

Lets say %domain% contains "site.com", I'd expect *.{domain} or *.%domain%. to allow things like the following

* sub1.site.com
* sub2.site.com
* sub3.site.com

**Comment by Nek-** [comment]
Sure, but you can close this issue and make a pull request on the [symfony doc](https://github.com/symfony/symfony-docs/) :-) .

Anyway I don't understand what's wrong with your last point.

**Comment by hackzilla** [comment]
ok, I'll have a look at doing a PR :smirk:

My last point was following doesn't work.

```yaml
hackzilla_sites:
    resource: "@HackzillaSitesBundle/Resources/config/routing.yml"
    prefix:   /
    host: "*.%domain%"
```

if host is "sub1.%domain%", then it'll work, but I'm after a wildcard.
