### ISSUE TITLE
Change default feature config to disabled

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#13703]
What about disabling all components by default in symfony 3.0.
I think it's really confusing that some things are enabled by default and others are disabled by default. This way it's really hard to configure a symfony where only the stuff you need is enabled because you have to figure out all the defaults first.

> Indeed, having everything disabled by default would be better; and Symfony SE can enable the most important things and add comments to enable less important features. Anyone willing to work on this for 3.0?
fabpot

https://github.com/symfony/symfony/pull/13672#issuecomment-74162125

**Comment by sstok** [comment]
:+1:

**Comment by weaverryan** [comment]
I like it a lot :+1:

**Comment by JHGitty** [comment]
:+1:

**Comment by Ener-Getick** [comment]
I looked the FrameworkBundle configuration and I didn't see any components activated by default. Which one are you talking about?

Not completely related, but sometime ``canBeUnset`` is used and sometime ``canBeEnabled`` is used and it doesn't always make sense so IMO we should also make this less confusing.

**Comment by Tobion** [comment]
It's true that things that can be configured are disabled by default. But alot of stuff is loaded without being able to disable it:

- property_access
- annotations
- fragment_renderer
- translation

And the inconsistency with`canBeUnset` and `canBeEnabled` between alot of configurations as you said.

```yaml
# both behave the same for each config value
framework:
    form: false | true | null
    session: false | true | null

framework:
    form: 
        enabled :false # works
    session:
        enabled :false # does not work (Unrecognized option "enabled" under "framework.session")
```
```
