### ISSUE TITLE
Symfony\Bridge\Doctrine\ContainerAwareEventManager doesn't allow custom method names

### ISSUE THREAD

**Issue by avltree** [symfony/symfony#13720]
It would be a nice feature if the `ContainerAwareEventManager` would allow to specify custom methods for handling different Doctrine events, e.g.:

```yaml
services:
    my.listener:
        class: Acme\SearchBundle\EventListener\SearchIndexer
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: customPostPersist }
```

The above configuration won't work as expected, since the `method` is ignored and the manager only tries to use methods of the listeners named exactly as the event to which they are listening:

```php
$listener->$eventName($eventArgs);
```
