### ISSUE TITLE
[DX] Improve error message when security.yml is incomplete

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#13949]
The other day I had some problems helping a Symfony newcomer debug her first application. She configured the `security.yml` file, created the user entity, etc. but when she tried to log in the application, she got the following error message:

```
security.INFO: Authentication request failed: Your session has timed out, or you
have disabled cookies.
```

After discovering the error, I tried to reproduced it in a fresh Symfony installation and this was the error message that I got:

```
Authentication request could not be processed due to a system problem.
```

Which was the problem? She configured her user provider as follows:

```yaml
security:
    providers:
        users:
            entity: { class: AppBundle:User }
```

Do you see the problem? The `property` option is missing:

```yaml
security:
    providers:
        users:
            entity: { class: AppBundle:User, property: email }
```

Could we improve the error message in this case? Has anyone faced other security problems with misleading error messages?
