### ISSUE TITLE
parameterised Redirect::urlRedirect

### ISSUE THREAD

**Issue by devzer01** [symfony/symfony#13958]
I can't seem to define a route as follows. Is there a fundamental reason for not supporting this?
```
foo_route:
    locales:
        en: %foo.config.en%/foo/{barVar}-bar
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /{barVar}-foo 
        permanent: true
    requirements:
        _method: GET
        barVar: a|b|c|d
```

so that i don't have to define `n` routes for all possible values of `barVar`
