### ISSUE TITLE
[Yaml] namespaces ending with y followed by P (y\P) needs escaping

### ISSUE THREAD

**Issue by skollro** [symfony/symfony#14094]
Hello,
today I found an unexpected behavior with Yaml. When I use the following service definition, I get: MappingException in MappingException.php line 96: Class 'Es\AppBundle\Entity ermissionRole' does not exist.
10. at EntityManager->getRepository('Es\AppBundle\Entity ermissionRole') in appDevDebugProjectContainer.php line 319

```
app.entity.permission_role_repository:
    class: AppBundle\Entity\Repository\PermissionRoleRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ["Es\AppBundle\Entity\PermissionRole"]
```

When I use the following code it works.

```
arguments: ["Es\AppBundle\Entity\\PermissionRole"]
```

Is this a bug?
