### ISSUE TITLE
[Translator] First occurence in yml not read

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#14297]
Over the last few months occasionally a quite weird bug occurs. Seems to be occurring since the `2.6` branch, but don't tested that yet. Will make a reproducible test case later on.

```twig
{{ 'step'|trans({'%step%': stepNo}) }}
```

__Not working__
```yml
step: Schritt %step%
to_step: Zu Schritt %step% »
```
__Working__
```yml
stub: - empty -
step: Schritt %step%
to_step: Zu Schritt %step% »
```
The first translation occurrence in the yml file is not read, so the fallback message is shown. Clearing the cache does not solve it, putting a "stub" translation on top of the file does solve it.
