### ISSUE TITLE
[Security][Doctrine ORM] Always authenticated as user #1

### ISSUE THREAD

**Issue by yann-eugone** [symfony/symfony#14334]
Hi all,

I'm facing a very weird problem with user fetching during my authentication process.

I have a very simple use case :

A `User` entity with basic properties :

```php
/**
 * @ORM\Entity(repositoryClass="AppBundle\Entity\Repository\UserRepository")
 * @ORM\Table(name="user")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="username", type="string", unique=true)
     */
    protected $username;

    /**
     * @ORM\Column(name="password", type="string")
     */
    protected $password;

    public function getId()
    {
        return $this->id;
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
        // nothing to do
    }
}
```

A simple security configuration :

```
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        orm_by_username:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: ~
            form_login:
                check_path: security_login_check
                login_path: security_login_form
            logout:
                path: security_logout
                target: homepage

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
```

I got 2 users in database :

    ID | USERNAME | PASSWORD
    1  | admin    | admin
    2  | john     | john

When I try to log in with `admin` everything is fine. But when I try with `john`... I'm authenticated with `admin`!

What I did understand already :

- In `EntityUserProvider` the good user is fetched and returned
- In `UserAuthenticationProvider` a token is created and filled with good user information

But in `EntityUserProvider` :

```php
public function refreshUser(UserInterface $user)
{
    if (!$user instanceof $this->class) {
        throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', get_class($user)));
    }

    if ($this->repository instanceof UserProviderInterface) {
        $refreshedUser = $this->repository->refreshUser($user);
    } else {
        // The user must be reloaded via the primary key as all other data
        // might have changed without proper persistence in the database.
        // That's the case when the user has been changed by a form with
        // validation errors.
        if (!$id = $this->metadata->getIdentifierValues($user)) {
            throw new \InvalidArgumentException('You cannot refresh a user '.
                'from the EntityUserProvider that does not contain an identifier. '.
                'The user object has to be serialized with its own identifier '.
                'mapped by Doctrine.'
            );
        }

        $refreshedUser = $this->repository->find($id);
        if (null === $refreshedUser) {
            throw new UsernameNotFoundException(sprintf('User with id %s not found', json_encode($id)));
        }
    }

    return $refreshedUser;
}
```

The instruction `$this->metadata->getIdentifierValues($user)` is returning  `array( 'id' = 2 )` and this is the problem... because the next instruction is using this result as is.
The `find` repository method is expecting a scalar parameter, so `array( 'id' = 2 )` is converted by Doctrine to an integer (because the identifier of my entity is configured as an integer), so it is converted to 1 and here is the problem...

Did something is missing in my configuration to make it right ? Or something is really wrong about this?
