### ISSUE TITLE
Indexed arrays have no definitive representation in config definitions

### ISSUE THREAD

**Issue by jeskew** [symfony/symfony#14459]
To add a collection of values to a config, one must currently add a prototyped array node:

``` php
->arrayNode('a_node')
    ->prototype('scalar')->end()
->end()
```

However, this construct could also indicate that you wish to allow a map with arbitrary keys. The resulting value could either be a vector or a map, which can be problematic if Symfony is managing configs for a polyglot project.

Would it be possible to add a new node definition type for indexed arrays?

**Comment by iltar** [comment]
I ran into this issue not too long ago, I wanted something like this:
```
my_extension:
    something_variable: ["foo", "bar", 100]
    something_else: ["sheep", "cow", 110]
    <key>: [<string>, <string>, <int>]
```

I was unable to get this to work, even when combining existing symfony code.
