### ISSUE TITLE
Performance issue on nested collection when using allow_add

### ISSUE THREAD

**Issue by webdevilopers** [symfony/symfony#14492]
I have a more or less complex form setup with collections and dynamically generated subforms.
Everything works fine but the request takes some time. I could bring it down to the `allow_add` option set to `true` on my collection:
https://gist.github.com/webdevilopers/c4b43188e1773526b000#file-timekeepingentryusertype-php

This is the profiler result for time with `allow_add` set to true:
![bildschirmfoto vom 2015-04-28 14 57 45](https://cloud.githubusercontent.com/assets/3479626/7370115/05687978-edb8-11e4-9983-b27fed95fbf9.png)

And the much faster request result with set to `false`:
![bildschirmfoto vom 2015-04-28 14 57 15](https://cloud.githubusercontent.com/assets/3479626/7370134/1bbd1490-edb8-11e4-87e4-79851092cf42.png)

My full form and controller setup (excluding non-performance impacting code):
https://gist.github.com/webdevilopers/c4b43188e1773526b000

Since I'm using a `prototype` to add the forms via AJAX I thought this would cause the impact.
But setting `prototype` to false and excluding it from my template didn't change anything.

Next I started populating the form with e.g. 7 Entities. Allthough `allow_add` was set to `false` I got antoher impact:
![bildschirmfoto vom 2015-04-28 15 17 47](https://cloud.githubusercontent.com/assets/3479626/7370328/94a0f060-edb9-11e4-9b9d-722a343271c3.png)

Is my nested form setup "bad"?

**Comment by stof** [comment]
**Never** pass a type instance to the ``type`` option of a collection. Anytime Symfony receives a type object, it must drop the existing resolved form type and resolve it again, which means forgetting all optimizations done in Symfony 2.1.
you should register the form type in the form registry and reference it by name instead, to reuse the resolved form type all the time.

``allow_add`` is not the reason for the main performance bottleneck. If you have a collection field without ``allow_add`` but with lots of elements in it, you will also see the same performance issue. ``allow_add`` just lets you add more elements dynamically when submitting

**Comment by webdevilopers** [comment]
Thanks @stof. I just added my form types to services:
```yaml
services:
    timekeeping.form.type.timekeeping_entry_week:
        class: Plusquam\Bundle\TimekeepingBundle\Form\TimekeepingEntryWeekType
        tags:
            - { name: form.type, alias: timekeeping_entry_week }

    timekeeping.form.type.timekeeping_entry_day:
        class: Plusquam\Bundle\TimekeepingBundle\Form\TimekeepingEntryDayType
        tags:
            - { name: form.type, alias: timekeeping_entry_day }
```

and replaced every new TimekeepingEntryFooType() with `timkeeping_entry_foo`.
But this makes it only a little bit more performant:
![bildschirmfoto vom 2015-04-28 15 41 16](https://cloud.githubusercontent.com/assets/3479626/7370778/ba7722de-edbc-11e4-884a-94f3b793e1b4.png)

Having a quick look at my form setup you think everything looks optimized and the amount of elements and subforms will cause the issue?
