### ISSUE TITLE
[DI] use decorated service as parent doesn't work.

### ISSUE THREAD

**Issue by aitboudad** [symfony/symfony#14543]
```yml
bar:
  class: stdClass
  decorates: foo
  parent: "bar.inner"
```

I get the following error:
```console
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]                                      
  The parent definition "bar.inner" defined for definition "bar" does not exist. 
```
