### ISSUE TITLE
Priority of event listener is ignored

### ISSUE THREAD

**Issue by Tocacar** [symfony/symfony#14547]
I have a doctrine.event_listener configured in my services.yml:

```
  ams.cage_listener:
      class: AMS\ColonyBundle\EventListener\CageListener
      tags:
          - { name: doctrine.event_listener, event: onFlush }
```
In that event listener, I am looking for Cage entities and conditionally updating a 'number' property.  The Cage::number entity property also happens to be the field used for a StofDoctrineExtentions Gedmo/Sluggable property ($slug is in the same entity class):

```
    /**
     * @var string $slug
     *
     * @Gedmo\Slug(fields={"number"}, updatable=true)
     * @ORM\Column(name="slug", type="string", length=20, unique=true)
     */
    private $slug;
```

This means I need the slug to be regenerated. if my onFlush listener method changes the Cage::number property.

Unfortunately, Sluggable also listens for the onFlush event and executes before my own listener method.  I tried adding a priority tag to my service definition to make it execute first:

```
  ams.cage_listener:
      class: AMS\ColonyBundle\EventListener\CageListener
      tags:
          - { name: doctrine.event_listener, event: onFlush, priority: 100000 }
```

But this has no effect (Gedmo's onFlush listener still executes first).  Is this a bug? Or is there any way I can make my own listener method execute before Gedmo's?

**Comment by stof** [comment]
The issue in your case is that Doctrine itself does not have a concept of priority. The compiler pass in the Doctrine bridge adds such concept to give more control on the order when registering listeners. However, it currently sort listeners and subscribers independently (all subscribers are registered first)

**Comment by Tocacar** [comment]
@stof  OK, thanks very much for your quick reply. Changing my listener to a subscriber and setting the priority tag has got my slug working again.  Thank you!

**Comment by CruzyCruz** [comment]
@Tocacar 

Hi,

I have the same problem with my doctrine subscriber (using Sluggable extension and listening to onFlush event). As this subscriber implements *Doctrine\Common\EventSubscriber* and not *Symfony\Component\EventDispatcher\EventSubscriberInterface*, how can you introduce a priority level in *getSubscribedEvents()* method ?

Thank you for your help.

**Comment by xabbuh** [comment]
@CruzyCruz You have to set the priority on the service tag. All subscribers will be called in the order of the priority and subscribers being called first are registered first.

**Comment by CruzyCruz** [comment]
@xabbuh

Thank you. I didn't know that setting priority at tag level was possible for subscribers also. I try it in my code asap.

**Comment by CruzyCruz** [comment]
@xabbuh 

It works perfectly:

```yaml
    fbn_guide.doctrine_listener:
        class : FBN\GuideBundle\EventListener\DoctrineListener
        arguments: [@fbn_guide.image_manager]
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -10000 }
```

**Comment by brunocombodo** [comment]
Hello,

I'm willing to use the slug value to name an uploaded file, 
I've tried both listener and subscriber with negative priority, it didn't worked : 

```yaml
    acme_file_uploader.carrousel_item:
        class: Acme\CmsBundle\FileUploader\CarrouselIemFileUploader
        arguments:
          - "%kernel.root_dir%"
        tags:
          - { name: doctrine.event_listener, event: prePersist  , priority: -10000000}
```

```yaml
    acme_file_uploader.carrousel_item_subscriber:
        class: Acme\CmsBundle\FileUploader\CarrouselIemFileUploaderSuscriber
        tags:
            - { name: doctrine.event_subscriber , priority: -10000000} 
```

the `->getSlug()` return null value in both cases : 
```php
    public function prePersist(LifecycleEventArgs $args) {
        $entity = $args->getEntity();

        if (!$entity instanceof CarrouselItem) {
            return;
        }
        if (null === $file = $entity->getFile()) {
            return;
        }

        var_dump($entity->getSlug()); // NULL
    }
```
