### ISSUE TITLE
[Routing] app_dev.php when generating "externals" urls on dev environment

### ISSUE THREAD

**Issue by snoob** [symfony/symfony#14615]
Hi. I wanted to use the router to generate "externals" url. 
Here is my config : 
``` yml
#routing.yml
external:
    resource: "@MyBundle/Resources/config/routing/external.yml"
    host: "external.host.com"

#external.yml
route1:
    path: "/path1.html"
route2:
    path: "/path2.html"
```
`{{ url('route1', {language: 'app.request.locale'}) }}`  on my twig template generates an unexisting  url : http://external.host.com/app_dev.php/path1.html

An easy fix will be to force `baseUrl` to be empty after the test the `$routeHost !== $host` on the `UrlGenerator` (line 252) but if we use a symfony application hostname we will lose the app_dev.php so i think it's a bad idea.

I found 2 others solutions :
- Be able to override some `RequestContext` values.
- Force a route to be generated without app_dev.php

I'm aware that few developers use the router for this but i think these solutions can profit to the others.
What do you think about this? 

PS : I've solved my problem with a parameter `_external` on my routes and an `UrlGenerator:doGenerate` override. This solution doesn't satisfy me at all. I store the `basePath` on a variable, i override it, i generate my route and i put the old `basePath` back.
