### ISSUE TITLE
[DX][Form] Make it easier to register form types as services

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony#14653]
## The Problem

Currently, if you want to register your form types as services, you'll always have to create service definitions in your applications that are very similar like this:

```yaml
services:
    app.form.type.task:
        class: AppBundle\Form\Type\TaskType
        tags:
            - { name: form.type, alias: app_task }
```

Of course, when you are used to creating Symfony applications, you will probably be able to that blindly, but nonetheless it's a lot of characters to type for this simple task.

## The Solution

Make it possible to register new form types under the `form` key of the FrameworkBundle configuration like this:

```yaml
framework:
    form:
        types:
            app_task: AppBundle\Form\Type\TaskType
```

The new `types` key will accept a hash where the key is the name and the value is the FQCN.

**Comment by javiereguiluz** [comment]
:+1: not only this makes a lot of sense, but it's also very consistent with they way we define new types in other sections, such as Doctrine/DBAL:

```yaml
# app/config/config.yml
doctrine:
    dbal:
        types:
            custom_first:  AppBundle\Type\CustomFirst
            custom_second: AppBundle\Type\CustomSecond
```
