### ISSUE TITLE
[MonologBridge] monolog memory usage increases as log increases

### ISSUE THREAD

**Issue by squarerliao** [symfony/symfony#14717]
when I changed something from:

<code>$logger = new \Monolog\Logger('logger');</code>

to:

<code>$logger = $this->get('logger');</code>

the memory usage increases while each time <code>$logger->addInfo()</code> was called,
but with original syntax the memory usage just stay the same.

my <code>config.yml</code> refer to http://symfony.com/doc/current/cookbook/logging/monolog.html:
with handler type is <code>stream</code>,
so I wonder if there's a way to prevent the increasing memory issue, thx!

**Comment by dosten** [comment]
Can you paste your "monolog" section of your config.yml?

**Comment by squarerliao** [comment]
here is my monolog section in config.yml
```
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.mylog.log"
            level: debug
            channels: ~
```
