### ISSUE TITLE
Make the log level of match route log configurable

### ISSUE THREAD

**Issue by tdesvenain** [symfony/symfony#14747]
I think it would be fine if we can set the "Matched route..." log level to DEBUG.
On some projects, INFO may not be the accurate level for this information.

**Comment by Tobion** [comment]
Just change the injected logger. You can for example use a custom decorator that changes `info` to `debug`. There is no point in making such things configurable in the framework itself.

**Comment by geri777** [comment]
Some lines of sample code would be appreciated

**Comment by jt2k** [comment]
I know this issue is closed and a few years old, but I was looking to accomplish this and thought I would share my solution (application is using framework-bundle 4.4).

You can find the default router_listener service (`Symfony\Component\HttpKernel\EventListener\RouterListener`) configured here: https://github.com/symfony/symfony/blob/3619661d65711901852c6c2ba0b33c3d273593ca/src/Symfony/Bundle/FrameworkBundle/Resources/config/routing.xml#L108-L117

To override, I converted this definition to YAML and added it to my application's `services.yaml` file:
```yaml
services:
    router_listener:
        class: Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments:
            - '@router'
            - '@request_stack'
            - '@?router.request_context'
            - null
            - '%kernel.project_dir%'
            - '%kernel.debug%'
```

This definition is identical, except that `null` is passed for the logger. As mentioned above, perhaps a better solution is to implement a custom logger that adjusts the level down, but since the only logging happening in the RouterListener is the info-level match log that I want to suppress, I decided to take the easy way out. Hopefully I won't regret this in the future!

Also, using named arguments might be better/clearer, but my goal was to match the XML configuration as close as possible.

**Comment by elnur** [comment]
Here's my solution:

```php
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class RouterListenerLoggingSilencerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        $definition = $container->getDefinition('router_listener');

        foreach ($definition->getArguments() as $index => $argument) {
            if ('logger' != $argument) {
                continue;
            }

            $definition->replaceArgument($index, null);
        }
    }
}
```

**Comment by renepupil** [comment]
@Tobion 6 people disagree with you.

Will you reconsider?

**Comment by renepupil** [comment]
I came to the conclusion that we can also just ignore the `request` channel in the monolog handler:

```yaml
monolog:
  handlers:
    console:
      type: console
      channels: [ "!event", "!doctrine", "!console", "!request"]
```
