### ISSUE TITLE
after upgrade to 2.7.0 , kpnpaginator complains  service "templating.helper.router" is non-existent

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#14790]
the exact error message being 

  The service "knp_paginator.helper.processor" has a dependency on a non-existent service "templating.helper.router".  

is it a problem on symfony or in the bundle side ? I see nothing related to that service in the upgrade file to 2.7

**Comment by allan-simon** [comment]
is it related to  #13354 ?

**Comment by dosten** [comment]
Add `php` as a engine in your framework config:

```yaml
framework:
    templating:
        engines: [twig, php]
```
