### ISSUE TITLE
Passing Arguments to the YAML Factory Method in Symfony 2.7

### ISSUE THREAD

**Issue by zdenekdrahos** [symfony/symfony#14812]
We have troubles with upgrading service container to new [factory syntax](http://symfony.com/doc/current/components/dependency_injection/factories.html#passing-arguments-to-the-factory-method). For example we have:
```
    acme.repository.article:
        class: AppBundle\ArticleRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:Article"
```
When I try:
```
    acme.repository.article:
        class: AppBundle\ArticleRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - "AppBundle:Article"
```
Then I get error 
```
ServiceNotFoundException in ParameterProcessor.php line 48:
Service not found for Doctrine\ORM\Mapping\ClassMetadata used in Gedmo\Tree\Entity\Repository\AbstractTreeRepository
```
I get similar error when factory method has no arguments, but factory service has arguments (`CannotResolveParameterException`).

XML configuration works:
```
        <service id="acme.repository.article"
            class="AppBundle\ArticleRepository"
        >
            <factory service="doctrine.orm.entity_manager" method="getRepository"/>
            <argument>AppBundle:Article</argument>
        </service>
```
