### ISSUE TITLE
Regex validation constraint doesn't work against "repeated" field type

### ISSUE THREAD

**Issue by iHedgehog** [symfony/symfony#14826]
I'am trying to validate repeated field against Regex.
```php
# RegistrationType.php
//...
        ->add('password', 'repeated', [
                'type' => 'password',
                'first_name' => 'password',
                'first_options' => ['label' => "Password"],
                'second_name' => 'confirmation',
                'second_options' => ['label' => 'Password confirmation'],
                'invalid_message' => 'Password and Password confirmation must match.'
            ])
//...
```
```yml
# validation.yml
#...
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 64
            - Regex:
                pattern: "/^[a-z]+$/"
#...
```
After I enter in password field something suitable like `asdasd` and submit it, validation doesn't pass.

Or if I change regex pattern like this `/[a-z]/` and then enter something not suitable like `123123` to the field, it passed.
It seems there is no logic.
