### ISSUE TITLE
 [2.7][Asset] Empty version strategy for package

### ISSUE THREAD

**Issue by badlamer** [symfony/symfony#14832]
Hello! In ~2.6 version was EmptyVersionStrategy for images package. In 2.7 replaced default version from framework.assets

```yaml
framework:
    assets:
        version: %assets_version%
        base_urls: %cdn_urls%
        packages:
            images:
                version:              ~
                version_format:       null
                base_urls: %cdn_urls%
```

From app/cache/prod/appProdProjectContainer.php

```php
    protected function getAssets_VersionDefaultService()
    {
        return $this->services['assets._version__default'] = new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('test', '%s?%s');
    }
    protected function getAssets_ContextService()
    {
        return $this->services['assets.context'] = new \Symfony\Component\Asset\Context\RequestStackContext($this->get('request_stack'));
    }
    protected function getAssets_PackagesService()
    {
        $a = $this->get('assets._version__default');
        $b = $this->get('assets.context');
        return $this->services['assets.packages'] = new \Symfony\Component\Asset\Packages(new \Symfony\Component\Asset\UrlPackage(array(0 => 'http://s1.cdn.ru', 1 => 'http://s2.cdn.ru'), $a, $b), array('images' => new \Symfony\Component\Asset\UrlPackage(array(0 => 'http://s1.cdn.ru', 1 => 'http://s2.cdn.ru'), $a, $b)));
    }

```

**Comment by XWB** [comment]
I'm having the same issue.

Prior to Symfony 2.7, the above configuration would result into:

{{ asset('test.png', 'images') }} => http://localhost.com/test.png

Since Symfony 2.7 the query parameter is always appended, even if the value is empty:

{{ asset('test.png', 'images') }} => http://localhost.com/test.png?v=

Ping @fabpot @stof

**Comment by stof** [comment]
@XWB are you using ``null`` or an empty string as asset version ?

**Comment by XWB** [comment]
@stof I'm using the following config:

```
framework:
    assets:
        assets_version: %app_version%
        assets_version_format: "%%s?v=%%s"
        packages:
            images:
                version: ~
                version_format: ~
```
