### ISSUE TITLE
Validate expanded multiple choice

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#14957]
Is there a way to validate an expanded multiple choice? I have the following choice in a form:

``` php
$builder
            ->add('action', 'choice', array(
                'required'    => true,
                'empty_value' => 'Select an action',
                'choices'     => array(
                    BulkEmailModel::ACTION_SEND   => 'Send emails',
                    BulkEmailModel::ACTION_DELETE => 'Delete emails',
                )
            ))
            ->add('emails', 'choice', array(
                'multiple'    => true,
                'expanded'    => true,
                'choice_list' => new ObjectChoiceList($emailEntities, 'id', array(), null, 'id'),
            ))
        ;
```

Validation:

``` yaml
Acme\Demo\Form\Model\BulkEmailModel:
    properties:
        action:
            - NotBlank: ~
        quotes:
            - Count:
                min: 1
                minMessage: 'Please select at least 1 email.'
            - All:
                - NotBlank: ~
                - Blank: ~
```

It appears as though the choice does validate. However, the errors are in the wrong location. It looks like it use using the index based on the selected choices (not all the choices). See screenshot below:

![screen shot 2015-06-12 at 3 04 47 pm](https://cloud.githubusercontent.com/assets/869933/8123912/450ab50c-1115-11e5-8786-187467e50497.png)
