### ISSUE TITLE
TEST environment only: The database schema is not in sync with the current mapping file

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#15044]
There are some similar questions regarding to this issue but I haven't seen anything in particular to TEST environment and sqlite. I cannot validate schema for TEST environment which uses sqlite however I can validate schemas for DEV environment which uses mysql. Does anyone know what could be the reason and the possible solution? Whole application works fine in both DEV and TEST environments though. Only my phing and CI build is broken.
```
php app/console doctrine:schema:update --force --env=test
Updating database schema...
Database schema updated successfully! "9" queries were executed
php app/console doctrine:schema:validate --env=test
[Mapping]  OK - The mapping files are correct.
[Database] FAIL - The database schema is not in sync with the current mapping file.
```

confing_test.yml

```
imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        connections:
            default:
                driver: pdo_sqlite
                path: %kernel.cache_dir%/default.db
                charset: UTF8
```
