### ISSUE TITLE
[Validation] payload inaccessible in Callback validator

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#15092]
The `payload` element was added to attach arbitrary data to any constraint.

If I now write a constraint and the related validator, I can access the constraint in the validator and therefore the payload from it.

The `Callback` validator is something special: it executes custom validation code, but is limited in that it has no access to the constraint object itself – and so no access to the payload.

Quesiton: should we pass the `payload` (or even the complete `Callback` constraint to be forward-compatible for future additional fields) into the validation method?

**Comment by xabbuh** [comment]
Passing the constraint to the callback sounds like a good idea to me.

**Comment by boite** [comment]
Would it be useful to instead add getConstraint to Symfony\Component\Validator\Context\ExecutionContextInterface?

**Comment by conradkleinespel** [comment]
I recently realised, I could use a getter to validate what I needed validated. This seems concise and avoids hacking around the callback validator.

Here's a fictitious example of what I use in the `validation.yml` file:

```yaml
SocialNetwork\MainBundle\Entity\Group:
    getters:
        membersHaveUniqueEmails:
            - IsTrue:
               message: "Email addresses of group members must be unique."
```

In the class `SocialNetwork\MainBundle\Entity\Group`, I have something like this:

```php
class Group
{
    public static function getMembersHaveUniqueEmails()
    {
        return true; // put your own logic here
    }
}
```

I hope this helps.
