### ISSUE TITLE
[Form][Twig] form_theme in the view doesn't select the correct theme

### ISSUE THREAD

**Issue by coudenysj** [symfony/symfony#15162]
I have multiple form themes in a project, but I'm struggling with the "selection" process of the correct theme.

In my `config.yml` file I've registered all themes (without this, the `form_theme` selection is ignored al together):
```yml
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        asset_version: %asset_version%
    form_themes:
        - form_div_layout.html.twig
        - bootstrap_3_horizontal_layout.html.twig
        - common/form/forms.html.twig
        - SyliusWebBundle:Common:forms.html.twig
        - SyliusResourceBundle::forms.html.twig
```

In the twig views, I use `{% form_theme form 'common/form/forms.html.twig' %}` and `{% form_theme form 'SyliusWebBundle:Backend:forms.html.twig' %}` to select the correct theme, but this is not working.
