### ISSUE TITLE
[Router] 'options' added in in parent route definition are forwarded to child routes, but cached routing doesn't reflect them

### ISSUE THREAD

**Issue by Rbn3D** [symfony/symfony#15189]
I have a problem when setting options for a group of routes by declaring 'options' on the parent definition:

**routing.yml**
```yml
my_api:
    resource: "@MyApi/Controller/Api"
    type:     annotation
    prefix:   /api/v1
    options:
        groups: ['my_api']

#Other routes ...
```

Then I want to know, given a route name, if it is tagged as a certain group, something like:

```php
    protected function isAccessibleRouteName($routeName)
    {
        $routeCollection = $this->get('router')->getRouteCollection();
        $route = $routeCollection->get($routeName);
        return $route->hasOption('groups') &&
        (in_array('my_api', $route->getOption('groups')));
    }
```

But options array doesn't contain my custom option at runtime. If I debug the route loader (while warming cache) the options are added to each route correctly, the problem is that the cached UrlMatcher/Generator doesn't contain this info.

I'm using symfony 2.7, not sure if happens in other versions.

**Comment by stof** [comment]
you should not use ``->getRouteCollection()`` on the router as this will be a performance killer (it is not cached).

route options are meant to provide hints to the route compiler only. If you want something available after matching, putting it in the ``defaults`` is a better solution.

**Comment by Rbn3D** [comment]
@stof Same problem with defaults, the only default that the route contains after getting it from ->getRouteCollection() it's '_controller'. I'm using the same setup as above but using defaults instead of groups, also tried string values instead of arrays.

**Comment by xabbuh** [comment]
@Rbn3D Can you provide some steps to reproduce your issue with route defaults (or even better provide a fork of the Symfony Standard Edition)?

**Comment by Rbn3D** [comment]
Finally started over again on a clean branch, making sure I flush cached after each change, and it worked. 

There are the most important parts of my setup (I renamed some things):

**app/config/routing.yml**
```yml
my_web:
    resource: "@MyBundle/Controller/Web"
    type:     annotation
    prefix:   /
    host: 'www.%app.domain%'
    defaults:
        group: "my_web"
my_api:
    resource: "@MyBundle/Controller/Api"
    type:     annotation
    prefix:   /api/v1
    host: 'www.%app.domain%'
    defaults:
        group: "my_api"

# Other definitions with no 'group'
```

**@MyBundle/Controller/Api**
```php
    protected function isAccessibleRouteName($routeName)
    {
        $route = $this->get('router')->getRouteCollection()->get($routeName);
        return $route->hasDefault('group') && in_array($route->getDefault('group'), ['my_web', 'my_api']);
    }
```

Then I use this method on a RouteController that provides info of these tagged routes...

Sorry guys about the confusion and thanks for all.
