### ISSUE TITLE
Symfony 2.7 Translating Constraint Messages not supporting locale

### ISSUE THREAD

**Issue by nothingaa** [symfony/symfony#15213]
I just updated my Symfony from 2.5 to 2.7. I have an Entity, in this case `Product` that has a some properties with some constraints, for example `year`.

```
class Product {

    /**
    * @ORM\Column(type="float", nullable=true, options={"default" = 0.00})
    * @Assert\NotBlank( message = "product.year.notBlank")
    */
    private $year;
}
```

My message is getting translated from the `app/Resources/translations/validators.en.yml` file. But now, it doesn't respect the locale anymore. I have 2 files the `en` version and the `fr` version but now it only gets the `en` version.

I don't know if this is related but if I call a translation before I render an action it doesn't get translated. The action is empty, all it does is `return new Response('');`
```
{{ 'base.menu'|trans }} // Displays "This is my menu"
{{ render(controller('AcmeDemoBundle:Lightbox:empty')) }}
{{ 'base.menu'|trans }} // Displays "Ceci est mon menu"
```

If I look in  the `__construct` of the `vendor/symfony/symfony/src/Symfony/Component/Validator/Context/ExecutionContext` class and I dump the `$translator->getLocale()` it returns `en` and should display `fr` since I am on a french locale.

**Comment by nothingaa** [comment]
If I look in the Translation section of my Profiler, a part of the translation are in English and the rest is in French.

**Comment by xabbuh** [comment]
Do you somehow change the locale in your own code? Can you reproduce your issue on a fresh Symfony Standard Edition or can you provide a fork of it with the necessary changes to reproduce your issue?

**Comment by nothingaa** [comment]
I was using a version of the code on http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html in the "Setting the Locale Based on the User's Preferences" section. I tried with the original code. When I dump the `$this->session->get('_locale')` after the `if`, it displays `fr` but part of my site is still loading in `en`.

On 2.5, the following code and it was working fine
```
class UserLocaleListener
{
    private $session;
    private $langs;
    
    public function __construct(Session $session) {
        $this->langs = array('fr','en');
        $this->session = $session;
    }
	
    public function onInteractiveLogin(InteractiveLoginEvent $event)
    {
        $request = $event->getRequest();
        $user = $event->getAuthenticationToken()->getUser();

        $userLang = $user->getLanguage();
        if ($userLang == null) {
            $cookies = $request->cookies->all();
            if ($cookies != null && !empty($cookies) && isset($cookies['lang'])) {
                $lang = $cookies['lang'];
            } else {
                $lang = $request->getPreferredLanguage($this->langs);
            }
            $request->setLocale($lang);
        } else {
            $lang = $userLang->getKey();
        }

        $this->session->set('_locale', $lang);
    }
}
```
I will try to reproduce on a fresh Symfony version.

**Comment by nothingaa** [comment]
It seems to be working now. The problem was that I was calling this listener
```
projet_user.language.kernel_request_listener:
    class: iPlannedit\UserBundle\EventListener\LanguageListener
    tags:
        - { name: kernel.event_listener, event: kernel.request, method: setLocaleForUnauthenticatedUser }
```
and now I moved the content of the `setLocaleForUnauthenticatedUser` function in the `onKernelRequest` function of the listerner.
```
projet_user.locale_listener:
        class: iPlannedit\UserBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
```
It seems like the request that I was using for unauthenticated users is now called later and was impacting the locale defined by the users preferences. I'm gonna do some more tests and close the ticket.
