### ISSUE TITLE
InsufficientAuthenticationException is thrown and results in a 500 when I expect a 403

### ISSUE THREAD

**Issue by hvt** [symfony/symfony#15236]
I'm using Symfony 2.3 and written something very similar to this cookbook entry (http://symfony.com/doc/2.3/cookbook/security/voters.html). I think my issue very much looks like https://github.com/symfony/symfony/issues/8467, although I believe my use case is different, as I am not using a user provider at all.

Now, `InsufficientAuthenticationException` is thrown with `AccessDeniedException` as a previous exception when I've denied access in my custom voter. I do not see why this first exception is thrown, since I just expect to return a 403 as a response and not a fatal 500.

Some more info: I've got two firewalls. One is ignoring all dev related paths. The other simply allows anonymous users. My `security.yml` looks like this:

```yml
security:
    encoders:
        Acme\DemoBundle\Entity\Person:
            id: acme.demo.blowfish_password_encoder

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    access_decision_manager:
        strategy: unanimous
```

Can anyone elaborate on this?

**Comment by jakzal** [comment]
@hvt I think your voter might be at fault. Could you please fork the [symfony/symfony-standard](https://github.com/symfony/symfony-standard) edition, and reproduce your problem on a new branch?

**Comment by hvt** [comment]
@jakzal Here you go: https://github.com/hvt/symfony-standard/tree/issue-15236

You probably want to look at `security.yml` and `IpAccessVoter.php`. (Or just peek at the only commit I've added ;].)

**Comment by hvt** [comment]
Looking at `Symfony\Component\Security\Http\Firewall\ExceptionListener`, the `AccessDeniedException` (thrown by `Symfony\Component\Security\Http\Firewall\AccessListener`) is handled by the `handleAccessDeniedException` method.

Here, it is checked whether the security token is fully fledged, i.e. is not anonymous *and* not a 'remember-me' token. So in my configuration, a user is never fully fledged, because I only have anonymous firewalls.

I believe this to be a bug. Although, one can argue that mentioning - that using a security voter requires a non-anonymous firewall - in the docs would be enough...

**Comment by jakzal** [comment]
@hvt Looks like you've hit an edge case. Most of the time, if there's an AccessDeniedException it makes sense to fully authenticate the user to give him a chance to access the resource. There's no issue with anonymous firewalls, but the fact that you never fully authenticate your users.

**Comment by hvt** [comment]
@jakzal So how should I fully authenticate an anonymous user?

**Comment by backbone87** [comment]
This case isnt that edgy. I have come across the same issue too in my project too.

Lets call our 3 states (anon, remembered, full) the "authentication strength". The common case IMO is that the authentication strength from the authorization point of view is completely orthogonal to the access decision.

For a given user and set of permission attributes (and a permission object) a voter/an access decision manager should always make the same access decision regardless of the strength of the current authentication.

But the final authorization decision is made in the controller (or access control config): you check the permissions **and** that the required authentication strength is given, **but** you throw in both cases just an AccessDeniedException. The user can't change the outcome of the access decision (made by the AccessDecisionManager) just by promoting his authentication, so it makes no sense to redirect on every AccessDeniedException.

**Comment by backbone87** [comment]
My proposal is to offer 2 new (security specific) exceptions:
WeakAuthenticationException -> redirects to login form, if available, else gets transformed into a regular 403 response
PermissionDeniedException -> just converts into 403

Also the behavior of AccessDeniedException stays the same for symfony 2, but the security system interception gets removed in symfony 3

**Comment by backbone87** [comment]
Another interesting thought:
Make the available authentication strength states configurable, for example:
```yaml
x509:
    strength: 3
form_login:
    strength: 2
remember_me:
    strength: 1
anonymous:
    strength: 0
```

So one can require its desired strength for authorization decisions.
