### ISSUE TITLE
[2.7][Asset] unwanted ? at the end of path if 2.6 config is used

### ISSUE THREAD

**Issue by cfuerst** [symfony/symfony#15235]
Hi

In Symfony 2.7.1 if i have no specific version settings enabled there is a issue when just using:
`
{{ asset('foldername/cat.gif', 'packagename') }}
`

this will result in:
`
somepath/foldername/cat.gif?
`

this is especialy a problem when just rendering the path to a folder
`
somepath/foldername/?
`

for me the usecase is a angular js template where the actual asset (cat.gif) is added by angular js.

Thnx

**Comment by cfuerst** [comment]
the problem only occured with the old 2.6 config for templating assets:

```
# Symfony 2.6
# app/config/config.yml
framework:
    templating:
        assets_version: 'v5'
        assets_version_format: '%%s?version=%%s'
        assets_base_urls:
            http: ['http://cdn.example.com']
            ssl:  ['https://secure.example.com']
        packages:
            # ...

# Symfony 2.7
# app/config/config.yml
framework:
    assets:
        version: 'v5'
        version_format: '%%s?version=%%s'
        base_path: ~
        base_urls: ['http://cdn.example.com', 'https://secure.example.com']
        packages:
            # ...
```

changing to framework assets fixed the issue
