### ISSUE TITLE
[2.7][Asset] ssl vs http asset package urls

### ISSUE THREAD

**Issue by cfuerst** [symfony/symfony#15244]
Hi,

Im not really sure if its a bug or not, but i dont really understand the meaning of how this code behaves.

Lets assume following config where both SSL and HTTP urls are defined:

```
framework:
    assets:
        packages:
            frontend:
                base_urls:
                  - http://cdn.foo.bar/assets/
                  - https://cdn.foo.bar/assets/
```

Now the ```Symfony\Component\Asset\UrlPackage``` collects ALL base urls into ```$this->baseUrls ``` in [see code](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Asset/UrlPackage.php#L59)
and at the other hand all SSL urls into the ```sslPackage->baseUrls``` in [see code](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Asset/UrlPackage.php#L65)

Now when it comes to render asset urls for non secure contexts [see code](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Asset/UrlPackage.php#L88) the method ```chooseBaseUrl``` will choose any SSL or HTTP url in the whole ```$this->baseUrls``` array [see code](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Asset/UrlPackage.php#L117)

Of course this makes sense for multiple cdn's to distribute your content across those urls. This works fine in secure context (```sslPackage->baseUrls``` holds only multiple ssl urls then).

But in non secure context any url defined in base_urls is chosen no matter what context the url itself has.

For me the expected behaviour would be to only use non ssl urls in non secure context if there are defined ssl and http urls.

Kind Regards 

Christian
