### ISSUE TITLE
DynamoDB Session Handling

### ISSUE THREAD

**Issue by bassrock** [symfony/symfony#15259]
I am currently using AWS DynamoDb as my session handler with the following config:

```yml
services:
    aws_dynamo.client:
        class: Aws\DynamoDb\DynamoDbClient
        factory_class: Aws\DynamoDb\DynamoDbClient
        factory_method: 'factory'
        arguments:
            -
                credentials:
                    key: %dynamodb_aws_key%
                    secret: %dynamodb_aws_secret%
                region: 'us-east-1'
                version: 'latest'
    aws_dynamo.session:
       class: Aws\DynamoDb\SessionHandler
       factory_class: Aws\DynamoDb\SessionHandler
       factory_method: 'fromClient'
       arguments:
           - "@aws_dynamo.client"
           -
            table_name: %dynamodb_table_name%
            hash_key: 'id'
            locking: true
            max_lock_wait_time: 10
            min_lock_retry_microtime: 500
            max_lock_retry_microtime: 5000
```

AWS recommends disabling locking as with AJAX requests it can cause a lot of write requests to DynamoDB and increase the pricing. 

However with locking enabled my ajax requests end up timing out and redirecting to the login page. 

With locking disabled, my ajax forms end up with CSRF invalid errors on submission because only one of the forms end up saving it's CSRF token to the session, due to my guess a race condition.

Is there a way to use Symfony2 sessions without locking, or is my only solution to turn off CSRF form protection, which I would rather not do.
