### ISSUE TITLE
Override a symfony service tag with a compiler pass does not work for data collectors

### ISSUE THREAD

**Issue by christian-kolb** [symfony/symfony#15256]
I'm trying to override a tag in a symfony service definition with a compiler pass. The service as an example would be `data_collector.translation`.

The goal is to deactivate the data collector service to disable the element in the symfony web developer toolbar. To do this, I have to set the `priority` of the `data_collector` tag to `0`.

I could also override it in my own service definition:
```yml
services:
    data_collector.translation:
        class: 'Symfony\Component\Translation\DataCollector\TranslationDataCollector'
        tags:
           - {name: 'data_collector', priority: '0'}
        arguments: [@translator.data_collector]
```
But as I want to do this for a few of the data collectors, I would need to know the mandatory arguments for the data collector definition. The priority works the same for all collectors and therefore I would only need the name of the collector to disable it.

So I wrote the following compiler pass:
```php
class DataCollectorCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        if (!$container->hasDefinition('data_collector.translation')) {
            return;
        }
        $definition = $container->getDefinition('data_collector.translation');

        $tags = $definition->getTags();

        $tags['data_collector'][0]['priority'] = 0;

        $definition->setTags($tags);

        $container->setDefinition('data_collector.translation', $definition);
    }
}
```
To make things more wired: When I run this command:
```bash
$ php app/console container:debug --show-private --tag='data_collector'
```
I get the following output:
```bash
data_collector.translation @WebProfiler/Collector/translation.html.twig translation 0 Symfony\Component\Translation\DataCollector\TranslationDataCollector
```
So the priority even in the debugger is set to `0`.

But for which reason ever the element is still shown in the toolbar.

Is this a bug in Symfony or did I do anything wrong?

_The compiler pass does run (tested it with printing out stuff)_
_I'm using Symfony 2.7.1_
