### ISSUE TITLE
Make kernel.root_dir usable in routing.yml to support bundleless apps.

### ISSUE THREAD

**Issue by nesl247** [symfony/symfony#15296]
When using Symfony without bundles, the only thing making it difficult is that in `routing.yml`, you can't reference the `kernel.root_dir` parameter. Without this, you have to always have your resource definitions be relative to the config file, which is pretty ugly.

**Comment by weaverryan** [comment]
The idea would be to add something like this:

```yml
# app/config/routing.yml
app:
    # resolves to app/Controller, assuming a normal setup
    resource: "@Kernel/Controller/"
    type:     annotation
```
