### ISSUE TITLE
[AsseticBundle] Infitite loop when output path is long

### ISSUE THREAD

**Issue by aurelijusrozenas** [symfony/symfony#15400]
Spent half a day debugging why assetic won't work with bootstrap's glyphicons in dev mode and there is why:
1. If asset output filename is very long in template, in dev mode it will throw 'Error: Maximum function nesting level of '100' reached, aborting! '. Change it to `1.css`, and it will work.
````
{% stylesheets 'bundles/app/css/default.css' output='0123456789/123456789/123456789/123456789/123456789/123456789/12.css' %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ asset_url }}"/>
{% endstylesheets %}
````
2. With named assets it is the same, just the output filename must be shorter. Change it to `0.ttf` and it will work.
````
assets:
   bootstrap_zs_ttf:
       inputs:
           - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
       output: "0123456789/123456789/123456789/12345678/01.ttf"
````
**Steps to reproduce:**
- `symfony new symfony 2.6.11`
- `cd symfony`
- `composer require twitter/bootstrap 3.3.*`
- add asset config from above
- clear cache and dump assets
- open in production mode - **works**
- open in dev mode - **does not work**, display error 'Error: Maximum function nesting level of '100' reached, aborting! '
