### ISSUE TITLE
Cannot enable profiler from test case

### ISSUE THREAD

**Issue by egosselin1** [symfony/symfony#15419]
Hello,

I'm testing a registration case where the user fill a form, then submit-it and get an email with his credentials while being logged and redirected to his personal space.

So I need to check the sent email to verify the credentials, I setup my config_test.yml like this

```
framework:
    profiler:
        enabled: true
        collect: true
    test: ~
    session:
        storage_id: session.storage.mock_file        

web_profiler:
    toolbar: false
    intercept_redirects: true
```

Everything works fine I successfully recover the email content, but I want to disable the profiller collection on my other test cases so I setup the "collect: " parameters to false and added a call to enable the profiler from the test case (see http://symfony.com/doc/current/cookbook/testing/profiling.html) but it doesn't work.

A snippet of my code:

```
public function testRegistration()
{
    $client = static::createClient();
    $client->enableProfiler();

    $crawler = $client->request('GET', '/registration');
    $this->assertTrue($client->getResponse()->isSuccessful());

    $boutonForm = $crawler->selectButton('InscriptionParticulier_envoyer');
        $formulaire = $boutonForm->form(array(
            'InscriptionParticulier[prenom]' => 'Hermes',
            'InscriptionParticulier[nom]' => 'Conrad',
    ));
    $client->submit($formulaire);

    var_dump((boolean)$client->getKernel()->getContainer()->has('profiler'));
    var_dump((boolean)$client->getProfile());
}
```

With the collect parameter (from config) set to true I get :

```
bool(true)
bool(true)
```

With the collect parameter (from config) set to false I get :

```
bool(true)
bool(false)
```

I ckecked everything, i just can't enable the profile from the test case
