### ISSUE TITLE
[Yaml] Wrong line number when comments are inserted in the middle of a block

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#15437]
This yaml:
```yaml
foo:
    -
        # bar
        bar: "123",
```
triggers:
`Unexpected characters near "," at line 3 (near "bar: "123",").`

The line number is wrong (it should be 4).
This is because `Parser::getNextEmbedBlock()` removes the comment line before the parse error occurs.
