### ISSUE TITLE
[Validator] Add support for SVG files to image validation constraint

### ISSUE THREAD

**Issue by keichinger** [symfony/symfony#15460]
With the rise of SVG images all over the web I think it's pretty fair to say that having support for the already existing [Image validator constraint](http://symfony.com/doc/current/reference/constraints/Image.html) would benefit everyone.

Let's have a look at the following scenario where we'd like to give the opportunity to someone to upload either a GIF, JPEG, PNG or an SVG. 

``` yaml
# validation.yml

AppBundle\Entity\MyEntity:
    properties:
        # ...
        file:
            - Image:
                mimeTypes:
                    - image/gif
                    - image/jpeg
                    - image/png
                    - image/svg+xml
                minWidth: 1920
                minHeight: 1080
                # ...
```

The MIME type Google Chrome is sending matches _images/svg+xml_ and still I'm getting the following error message: _"This file is not a valid image."_

A solution to this problem would be to write a custom validation constraint. However, I'm pretty sure that this is one of the things that might be needed more often in the future so the best place for it is inside the Symfony Core.

Opinions?

**Comment by apfelbox** [comment]
The problem seems to lie in the current `MimeTypeGuesser`s. It currently doesn't sufficiently support SVG. Regular SVG files are recognized correctly and everything works, but minimized SVGs produce an error.

Simple test script:

```php
use Symfony\Component\HttpFoundation\File\File;


$svg = new File("example.svg");
var_dump($svg->getMimeType()); // string 'image/svg+xml' (length=13)

// example_after_svgo.svg is a minified SVG file, created with the following command
//
//      $ svgo --output=example_after_svgo.svg example.svg
//
// https://www.npmjs.com/package/svgo

$svgMin = new File("example_after_svgo.svg");
var_dump($svgMin->getMimeType()); // string 'text/plain' (length=10)
```

I think a way to solve this is to register another guesser, [a specialized `SvgMimeTypeGuesser` (or something like that…)](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeGuesser.php#L78-L90). This mime type guesser checks whether the file is valid XML and the single root node is `<svg ..></svg>` (a suggested [here](http://stackoverflow.com/questions/15136264/how-can-i-say-a-file-is-svg-without-using-a-magic-number)).

That way both the form would work correctly and the mimetype guessing would be improved globally.

Thoughts?

**Comment by yguedidi** [comment]
@cH40z-Lord Just to be sure, is it a typo in your PR description or Google Chrome send you image**s**/svg+xml? (note the "s")

**Comment by cH40z-Lord** [comment]
@yguedidi sorry, it is *indeed* a typo.

**Comment by apfelbox** [comment]
@yguedidi @cH40z-Lord right, but keep in mind that the mimetype as provided from the browser is discarded and instead the mimetype is fetched from the actual uploaded file. 

This is necessary as the mimetype of the request can be altered to be anything and doesn't have to be connected to the file itself.

**Comment by apfelbox** [comment]
@xabbuh as I read it, you should add the `HttpFoundation` and/or `Filesystem` label too, as the actual error lies in `Symfony\Component\HttpFoundation\File\File` (if I read that correctly).

**Comment by cH40z-Lord** [comment]
I've started to implement a first rough prototype that addresses the issues discussed here.

Right now I've got a working `SvgMimeTypeGuesser` that reads the file's contents and checks for an `<svg ...>` root node, as recommended by @apfelbox.

Now I wanted to have a look at the Image constraint and think about how to integrate SVG images (and possibly other vector formats for the future) into it.

My proposed changes would look like this:

## 1) `VectorImage` and `BitmapImage` constraints

* Rename `Image` constraint to `BitmapImage`
* Add `VectorImage` constraint (right now only validates SVG but is open for extensions)

That way everything is nice and separated from each other.
What I'm wondering about is how we could make it possible that the user could upload **either** a bitmap image **or** a vector image.

Given my example from above:

```yaml
# validation.yml

AppBundle\Entity\MyEntity:
    properties:
        file:
            # formerly Image
            - BitmapImage:
                # ....
            # New!
            - VectorImage:
                # ....
```

Obviously that would require the uploaded file to pass both validators, which is very unlikely to happen. So we would need to extend Symfony in a way to have allow **or**-constraints.

Maybe it can be easily done by creating a new `AnyConstraint` class which then can be used like this:

```yaml
# validation.yml

AppBundle\Entity\MyEntity:
    properties:
        file:
            - Any:
                MustPass:
                    # formerly Image
                    - BitmapImage:
                        # ....
                    # New!
                    - VectorImage:
                        # ....
```

This new `AnyConstraint` class would of course work with any `Constraint` class. If we want to take it a step further we could add an `AllConstraint` class for the same behaviour that we have now: all validators must pass.

## 2) Extend `Image` constraint

* Extend `Image` constraint to be able to parse any kind of vector images
* Add a lot of new properties to `Image` constraint for each feature we want to support for vector graphics
* Add a switch inside the `validate()` function to either parse Bitmap based images or vector images

- - -

## Conclusion

I'd love to hear your opinions on both proposals. Personally I'd probably go for the first one as it seems to be the most straight forward way to solve it.

/cc @stof @webmozart
