### ISSUE TITLE
Defining namespace for memcached cache in config.yml

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#15461]
Hi,

Is there a way of defining key-value pair for `namespace` for individual caches for memcached? E.g. `namespace: my/special/memcache`

Thanks

**config.yml**

```
framework:
    validation:
        cache: validator.mapping.cache.my_memcached_cache_1

doctrine_cache:
    providers:
        my_memcached_cache_1:
            memcached:
                servers:
                    memcached01:
                        host: %memcache_server%
                        port: %memcache_port%
        my_memcached_cache_2:
            memcached:
                servers:
                    memcached02:
                        host: %memcache_server%
                        port: %memcache_port%
```

**services.xml**

```
<service id="validator.mapping.cache.my_memcached_cache_1" class="Symfony\Component\Validator\Mapping\Cache\DoctrineCache">
     <argument type="service" id="doctrine_cache.providers.my_memcached_cache_1" />
</service>
```
