### ISSUE TITLE
kernel.response event listener gets not found with HTTP/200 instead of HTTP/404

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#15600]
While working with with [`kernel.response`](http://symfony.com/doc/current/components/http_kernel/introduction.html#the-kernel-response-event) HttpKernel event I observed one strange behaviour. Symfony automatically generates 404 pages for missing routes, they have proper `404 Not Found` code sent to the browser, but `kernel.response` listener receives it two times - first with `200 OK` code and than with with `404 Not Found` code.

### The code
To fully understand my problem let's start with code. I downloaded [Symfony installer](http://symfony.com/installer) and created fresh project by executing `./symfony.phar new myproject`. Next I created class under `src/AppBundle/DependencyInjection/KernelListener.php`:
```php
<?php
namespace AppBundle\DependencyInjection;

use Symfony\Component\HttpKernel\Event\FilterResponseEvent;

class KernelListener
{
    public function onResponse(FilterResponseEvent $event)
    {
        var_dump($event->getRequest()->getPathInfo(), $event->getResponse()->getStatusCode());
    }
}
```

Finally I added require service entry:
```yaml
services:
  app.kernel_listener:
    class: AppBundle\DependencyInjection\KernelListener
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onResponse, priority: -2147483647 }
```

### Results
After visiting `/` route I've got expected result:
```
string '/' (length=1)
int 200

Welcome to.....

string '/_wdt/5e1edc' (length=12)
int 200
```

However visiting unknown route, e.g. `/foobar` gives strange result:
```
string '/foobar' (length=7)
int 200
string '/foobar' (length=7)
int 404

No route found for "GET /foobar"....

string '/_wdt/b6190a' (length=12)
int 200
```

Is there a bug or I missed something?
I've tried attaching to [`kernel.terminate`](http://symfony.com/doc/current/components/http_kernel/introduction.html#the-kernel-terminate-event) - it works as expected, but since response was already sent I cannot add headers which is rather important for my use case.
