### ISSUE TITLE
Duplicated error message using the validator component

### ISSUE THREAD

**Issue by Ideneal** [symfony/symfony#15636]
Hi to all :)

I'm using Symfony 2.7 and I have a trouble with the Validator component.
I wrote a configuration yaml and php code to validate a Test model:

```yaml
Acme\Bundle\AcmeBundle\Model\Test:
    properties:
        message:
            - Type:
                type: string
                message: 'The message must be a string.'
            - Length:
                max: 10
                maxMessage: 'The message cannot be longer than {{ limit }} characters'
```

```php
$validator = $this->get('validator');

$model = new \Acme\Bundle\AcmeBundle\Model\Test();
$model
    ->setMessage('aaaaaaaaaaaaaaaaaaaa');

$errors = $validator->validate($model);

if ($errors->count() > 0)
{
    echo 'Errors num: '. $errors->count(). "\n";
    $errorMessages = array();

    foreach ($errors as $error) 
    {
        $field = $error->getPropertyPath();

        if (!isset($errorMessages[$field]))
            $errorMessages[$field] = [];

        $errorMessages[$field][] = $error->getMessage();
    }

    var_dump($errorMessages);
}
```

The output should show an error but I'm getting the same error message twice:

```
Errors num: 2
array(1) {
  ["message"]=>
  array(2) {
    [0]=>
    string(53) "The message cannot be longer than 10 characters"
    [1]=>
    string(53) "The message cannot be longer than 10 characters"
  }
}
```

What am I doing wrong?
