### ISSUE TITLE
Yaml parser 

### ISSUE THREAD

**Issue by igormukhingmailcom** [symfony/symfony#15674]
Hi.

Have next situation... 
I've got yaml file from my colleague and this file parsed not successfully:

```
# fixture.yml
table.inventory:
    inventory1:
        name: First Inventory
        description: Information about first inventory
        filename: first_inventory.txt
```

Parsed data:

```bash
# bash output from var_dump
array(2) {
  'table.inventory' =>
  NULL # <----------------------------- THIS IS NOT RIGHT
  '  inventory1' =>
  array(3) {
    'name' =>
    string(15) "First Inventory"
    'description' =>
    string(33) "Information about first inventory"
    'filename' =>
    string(19) "first_inventory.txt"
  }
}
```

So I have a look to this file and found that some looks-like-space characters is not spaces.
When I've converted this looks-like-space character into html code I've got `&ensp;`.

(When I replaced it with spaces characters - all become work fine).

How can we prevent that situations... When parser see `tab` character - it throws error. Maybe we can also throw exceptions with another looks-like-space characters?

Thank you.
