### ISSUE TITLE
[YAML] Multiline object support

### ISSUE THREAD

**Issue by qlcorp** [symfony/symfony#15700]
objectMap support was added to 2.6, but there is currently no support for multi-line objects:
```
object: {
    attr1: 10,
    attr2: 20
}
```

**Comment by iltar** [comment]
What's the difference with this then?
```yml
object: 
    attr1: 10
    attr2: 20
```
