### ISSUE TITLE
[DependencyInjection] Possibility to update an alias

### ISSUE THREAD

**Issue by paq85** [symfony/symfony#15735]
It's possible to define an alias (http://symfony.com/doc/current/components/dependency_injection/advanced.html#aliasing)
but it's not possible to update it.

Eg. having such a configuration:
```yaml
  doctrine.club_repository:
    class: X\AppBundle\Repository\Doctrine\ORM\ClubRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - X\AppBundle\Model\Club\Club
  in_memory.club_repository:
    class: X\AppBundle\Repository\InMemory\ClubRepository
  repo.club:
    alias: doctrine.club_repository
```

Following PHPUnit test fails:
```php
public function testDicAlias()
    {
        $client = static::createClient();
        $alias = $client->getContainer()->get('repo.club');
        $doctrine = $client->getContainer()->get('doctrine.club_repository');
        $inMemory = $client->getContainer()->get('in_memory.club_repository');
        $this->assertSame($alias, $doctrine);
        $this->assertNotSame($alias, $inMemory);

        $client->getContainer()->set('repo.club', $inMemory);
// FIXME: this one fails
        $this->assertSame($client->getContainer()->get('repo.club'), $inMemory); 
        $this->assertNotSame($client->getContainer()->get('repo.club'), $doctrine);
    }
```

Having possibility to update an alias would be useful for me as I can use an alias all over the place and simply switch the implementation when needed.

Perhaps it would be also useful also for others?
