### ISSUE TITLE
Add a switch to the debug:route command to enumerate the associated views --show-view-name

### ISSUE THREAD

**Issue by anis-marrouchi** [symfony/symfony#15768]
I'm having a project where i felt the need for a command that will list all the routes with associated controller actions and view names. I know that i can display the controller action using the --show-controller switch along the php app/console debug:route command.
I could not find a method that sets the view name for retrieval within my supposed command, so my idea is adding a setter and getter in Symfony\Bundle\FrameworkBundle\Controller\Controller.
Let me know if i'm missing somthing and what i'm looking for could be achieved otherwise.

**Comment by anis-marrouchi** [comment]
Alternative title for this issue: Add Setter/Getter for the view name in Symfony\Bundle\FrameworkBundle\Controller\Controller

**Comment by iltar** [comment]
@anis-marrouchi how would you resolve the template name of a controller?

**Comment by anis-marrouchi** [comment]
Using the routing config file 'routing.yml' for example like so:
```yml
    blog_show:
       path:   /blog/{slug}
       defaults:  { _controller: AcmeBlogBundle:Blog:show, _view: AcmeBlogBundle:Blog:show.html.twig }
```
Then a rewrite to the base controller render method to handle the introduced changes. or better a new render method renderDefault for example.
