### ISSUE TITLE
[Yaml] Parse error when comment on another indent level

### ISSUE THREAD

**Issue by PeterFour** [symfony/symfony#16065]
New merge commit 2ff0f97c60c5c3573978559d5565c5626eb60925 
(from parent commit 150f52f3aa8eab56c15d2e830660e85f387ce533 and issue #15860 )
just cause an error on Yaml file with different comment level.

This file will throw an exception :
```yaml
services:
# Session Handler (Inactivity Logout)
    app.handler.session_idle:
        class: AppBundle\Handler\SessionIdleHandler
        arguments: ["@session", "@security.token_storage", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
```

but this one is not (note the comment position):

```yaml
services:
    # Session Handler (Inactivity Logout)
    app.handler.session_idle:
        class: AppBundle\Handler\SessionIdleHandler
        arguments: ["@session", "@security.token_storage", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
```

I think the error is caused especially if you put a comment between two entries, but you keep the comment on root level

Is it a changes in Yaml syntax ?

**Comment by fabpot** [comment]
has been reverted

**Comment by ogizanagi** [comment]
I tried to reproduce it in a regression test along with the changes that were reverted, but it didn't failed :/

So I tried with the exact code you gave:
```php
    public function testCommentAtTheRootIndent()
    {
        $this->assertEquals(array (
            'services' =>
                array (
                    'app.handler.session_idle' =>
                        array (
                            'class' => 'AppBundle\\Handler\\SessionIdleHandler',
                            'arguments' =>
                                array (
                                    0 => '@session',
                                    1 => '@security.token_storage',
                                    2 => '@router',
                                    3 => '%session_max_idle_time%',
                                ),
                            'tags' =>
                                array (
                                    0 =>
                                        array (
                                            'name' => 'kernel.event_listener',
                                            'event' => 'kernel.request',
                                            'method' => 'onKernelRequest',
                                        ),
                                ),
                        ),
                ),
        ), Yaml::parse(<<<EOF
services:
# Session Handler (Inactivity Logout)
    app.handler.session_idle:
        class: AppBundle\Handler\SessionIdleHandler
        arguments: ["@session", "@security.token_storage", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
EOF
        ));
    }
```

but doesn't fail either :/

Any hint ?

**Comment by PeterFour** [comment]
Ok let me try with a more complete version, the thing is the problem is caused when you have several definition and a comment back on root level in between like so :

```yaml
services:

# Custom Services
    app.service.client:
        class: AppBundle\Service\ClientService
        arguments:
            container: "@service_container"

# Validator
    app.validator.sort_code_validator:
        class: AppBundle\Validator\Constraints\SortCodeValidator
        arguments:
                bv: "@app.service.bankval"
        tags:
            - { name: validator.constraint_validator, alias: sort_validator }
```
