### ISSUE TITLE
Proposal: Conditional service resolving

### ISSUE THREAD

**Issue by ewgRa** [symfony/symfony#16326]
Lets say I have Bundle and want use it in my app.

Bundle have services like this:

```yaml
foo:
        class: FooService
        arguments: [%foo_param%]

bar: 
        class: BarService
```

My app want use only bar service and don't want know anything about foo_param.

For now I will have exception like 'param not found' and can work on it like:
make in Bundle services.yml and services_with_param.yml and in extension check container->hasParam. And if param exists - load services_with_param.yml.

It is not friendly, because it is not split services by functionality, that can be acceptable.

What about: 

```yaml
foo:
        condition: expression
        class: FooService
        arguments: [%foo_param%]

bar: 
        class: BarService
```

If condition is false - than skip create this service.

Lazy in this case - not a solution on my mind.
Optional parameters and services - also not a solution, because this arguments really needed for service.
