### ISSUE TITLE
[2.7][Asset] Backward-incompatible change in assets base_urls in Symfony >=2.7

### ISSUE THREAD

**Issue by lividgreen** [symfony/symfony#16447]
We are using following config to place assetic results to a `web/subdir`.

```yaml
framework:
  templating:
    assets_base_paths: "/subdir"

assetic:
    read_from:      "%kernel.root_dir%/../web/subdir"
    write_to:       "%kernel.root_dir%/../web/subdir"
```
It works for Symfony 2.6 but broken for Symfony >=2.7 with error:

```
[Symfony\Component\Asset\Exception\InvalidArgumentException]
"/subdir" is not a valid URL
```
thrown during container initialization.

Is this a BC break or did we miss something?

**Comment by xabbuh** [comment]
@lividgreen Can you post the complete stack trace?

**Comment by stof** [comment]
this is because ``assets_base_urls`` was meant to contain base URLs in older versions, not base paths (btw, ``assets_base_paths`` does not exist). there was no supported way to provide a base path in 2.6 and older (your workaround could trigger weird behaviors in some cases AFAIK).
As such, the BC layer is rewriting this setting to the ``base_urls`` setting of the new system, which validates the input more strictly than the old system was. In the new asset system, there is a way to configure a base path though (but you need to use the new configuration format)

**Comment by javiereguiluz** [comment]
@lividgreen this config should fo the trick:

```yaml
framework:
    templating:
        # ...
    assets:
        base_path: "/subdir"
        # ...
```
