### ISSUE TITLE
Create service methods

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#16492]
it would be nice to have a command that reads the services configuration and generates methods based on the definition

**Comment by TomasVotruba** [comment]
I'm not sure I understand. Could you give some example?

**Comment by flip111** [comment]
```yaml
services:
    my_mailer:
        class:        Acme\HelloBundle\SomeService
        arguments:    [@logger]
```

into

```php
<?php

namespace Acme\HelloBundle;

use Psr\Log\LoggerInterface;

class Mailer {
  protected $logger;

  public function __construct(LoggerInterface $logger) {
    $this->logger = $logger;
  }
}
```
