### ISSUE TITLE
[Form][Validation] Using a validation group has the opposite effect

### ISSUE THREAD

**Issue by Tykzz** [symfony/symfony#16526]
I have multiple forms on one page and each uses only a part of fields of the entity.
The first one contains inputs for *username*, *first name* and *last name*. Therefore I want to validate only these three.
Unfortunately when I specify a group for a constraint, it gets excluded from the validation process instead of being included as the only one to check.

For example I want only *NotBlank* to be checked:
```yml
     lastName:
            - NotBlank:
                groups: [UserBasicInformation]
                message: 'lastName.blank'
            - Regex:
                match: false
                message: 'lastName.invalid_characters'
                pattern: '/[^\p{L}\-]/u'
```
Here is the group in the form class:
```php
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\AppUser',
            'validation_groups' => array('UserBasicInformation')
        ));
    }
```
The effect of this is that everything else is checked but NotBlank.
More of the code is [here](https://gist.github.com/Tykzz/a38c7379f2662d5f2a5b).
