### ISSUE TITLE
[Yaml][Parser] Mapping misdetected in quote

### ISSUE THREAD

**Issue by GawainLynch** [symfony/symfony#16562]
**Version:** symfony/yaml v2.8.0-BETA1

The following snippet of YAML is causing the parser to misdetect the comment `# Note:` as a mapping.
```yaml
showcases:
    fields:
        image:
            type: image
            attrib: title # Note: retrieve this in your template with {{ record.values.image.title }}
            extensions: [ gif, jpg, png ]
```

The error thrown in PHPUnit is:
```
Using a colon in an unquoted mapping value in line 133 is deprecated since Symfony 2.8 and will throw a ParseException in 3.0:
```

Changing the `attrib:` line above to below suppresses the deprecation warning
```yaml
attrib: title # 'Note:' retrieve this in your template with {{ record.values.image.title }}
```
