### ISSUE TITLE
[FrameworkBundle] Config diff between 2.8 and 3.0.

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#16570]
Just to mention [the issue we encountered while updating EasyAdminBundle for 3.0 support](https://github.com/javiereguiluz/EasyAdminBundle/pull/566#issuecomment-155535288), keeping the exact same configuration (in tests):

```yml
framework:
    secret:          secret
    translator:      ~
    default_locale:  "%locale%"
    test:            ~
    router:          { resource: "%kernel.root_dir%/config/routing_base.yml" }
    form:            true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    profiler:
        collect: true
    session:
        storage_id: session.storage.mock_file
```

This is the diff between the 2.8 and 3.0 processed configuration:

```diff
< array:23 [
---
> array:21 [
22,23c22,23
<       "enabled" => null
<       "field_name" => null
---
>       "enabled" => false
>       "field_name" => "_token"
47c47
<   "profiler" => array:8 [
---
>   "profiler" => array:5 [
53,55d52
<     "username" => ""
<     "password" => ""
<     "lifetime" => 86400
69,72d65
<   "csrf_protection" => array:2 [
<     "enabled" => false
<     "field_name" => "_token"
<   ]
99,105d91
<   "assets" => array:5 [
<     "version" => null
<     "version_format" => "%%s?%%s"
<     "base_path" => ""
<     "base_urls" => []
<     "packages" => []
<   ]
111c97
```

The issue we encountered was about the `asset` twig function, which isn't loaded in 3.0, because the `framework.assets` key doesn't have the "default values" it used to anymore, due to the framework bundle's [Configuration class](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L48-L122) (the highlighted part is removed in 3.0).

I don't think it was mentioned anywhere. What do you think should be done about that ?
