### ISSUE TITLE
Autowire does not inject monolog

### ISSUE THREAD

**Issue by chinmayshah24** [symfony/symfony#16639]
I am able to inject monolog using this:

```
services:
    service_demo:
        class:  AppBundle\Services\ServiceDemo
    service_consumer_demo:
        class:  AppBundle\Services\ServiceConsumerDemo
        arguments:  ["@doctrine.orm.entity_manager", "@service_demo"]
    controllers.home:
        class:  AppBundle\Controller\HomeController
        arguments:  ["@doctrine.orm.entity_manager", "@service_consumer_demo", "@service_demo", "@monolog.logger"]
```

But not using this:

```
services:
    controllers.home:
        class:  AppBundle\Controller\HomeController
        autowire:   true
```
