### ISSUE TITLE
Yaml: Constant as array key?

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#16771]
Hi,

I want to do:

```yaml
    my_service:
        class: AppBundle\MyService
        arguments:
            - # here are the dragons
                @=constant("AppBundle\\MyService::KEY1"): value1
                @=constant("AppBundle\\MyService::KEY1"): value2
```

But it gives me:

```php
array (size=2)
  '@=constant("AppBundle\\MyService::KEY1")' => string 'value1' (length=6)
  '@=constant("AppBundle\\MyService::KEY2")' => string 'value2' (length=6)
```

Constants as values of course work:

```yaml
    my_service:
        class: AppBundle\MyService
        arguments:
            - # here are the dragons
                key1: @=constant("AppBundle\\MyService::VALUE1")
                key2: @=constant("AppBundle\\MyService::VALUE2")
```

Which gives me:

```php
array (size=2)
  'key1' => string 'value1' (length=6)
  'key2' => string 'value2' (length=6)
```
---

Is it on purpose? A bug? Could be a new feature?
