### ISSUE TITLE
[Validator] Remove necessity to set constraint_validator alias

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#16805]
Right now, when adding a constraint validator to the DI configuration, you need to do:

```yaml
services:
    my_validator:
        class: Acme\Constraints\MyValidator
        tags:
            - { name: validator.constraint_validator, alias: Acme\Constraints\MyValidator }
```

It should not be necessary to pass that alias, but right now it is.
