### ISSUE TITLE
Add a way to parse route options in Framework bundle

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony#17016]
Hi,

let's take a look at a very simple example of route declaration:

``` yaml
foo_bar_baz:
   path: /foo/{bar}
   host: "%baz%" # successfuly parsed and get the right value
   defaults:
       _controller: Foo\Bar::bazAction
   options:
       _http_host: "%baz%:%baz%" # not parsed, only string is returned
       api_client: "client"
```

After a review on how the parameters are retrieved by Symfony framework, (https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L87), any chance to see the `options` property parsed ? Else, why  :) ?

Regards,
