### ISSUE TITLE
Expressions in routing conditions don't support array parameters

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17027]
### Context

In the Symfony Demo app we define the supported languages as a parameter:

```yaml
parameters:
    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca
```

And then we set routing conditions as follows:

```yaml
homepage:
    path: /{_locale}
    requirements:
        _locale: %app_locales%
```

### Problem

The locales param should be an array. Using a string separated with `|` looks wrong. I want to define locales as follows:

```yaml
parameters:
    app_locales: ['ca', 'cs', 'de', 'en', 'es', 'fr', 'id', 'it', 'ja', 'nl', 'pl', 'pt_BR', 'ro', 'ru', 'uk']
```

And then, I want to define this routing condition:

```yaml
homepage:
    path: /{_locale}
    condition: "context.getLocale() in '%app_locales%'"
```

But I get this error, which I don't understand because I'm using the `in` operator with an array parameter:

![routing_error](https://cloud.githubusercontent.com/assets/73419/11836432/fb39e8b8-a3da-11e5-93e6-c97dcee8c94a.png)
