### ISSUE TITLE
Add support for no alias in Doctrine ORM mapping

### ISSUE THREAD

**Issue by elnur** [symfony/symfony#17076]
In the case of entities out of bundles, I want to be able to have no alias at all. So that instead of `AppBundle:User` or `App:User` I could just use `User`. It just doesn't make sense to require an alias just for the sake of having one when you don't really need it. Doctrine itself supports it, so it should be possible to make it work with Symfony too.

Here's an example of what the configuration would look like:

``` yaml
doctrine:
    orm:
        mappings:
            entity:
                type: annotation
                dir: %kernel.root_dir%/../src/Entity
                is_bundle: false
                prefix: App\Entity
                alias: ~
```

Setting `alias` to `~` should mean _no alias_ instead of _default to the `prefix` value_. If it's bad for BC, the other option is setting `alias` to `false`.
