### ISSUE TITLE
[2.8][Form] Form type as a service in a controller

### ISSUE THREAD

**Issue by david-fanin** [symfony/symfony#17081]
Hello!

I updated a Symfony Project version 2.7 to version 2.8 and try to resolve all deprecations  by following this guide : https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md

I have this deprecation:
> Passing type instances to FormBuilder::add(), Form::add() or the FormFactory is deprecated since version 2.8 and will not be supported in 3.0. Use the fully-qualified type class name instead.

Due to the following code:
```
class MyController extends Controller
{
    public function myAction()
    {
        $myService = $this->get('my_service');

        $myFormType = new MyFormType($myService);// Type Instance

        $form = $this->createForm($myFormType, $myObject);
    }
}
```

To remove this deprecation, I must indicate the FQCN like this:
```
$form = $this->createForm('\ME\MyBundle\Form\Type\MyFormType', $myObject);
```

But I need to pass a service to my form type.

So I tried to turn my form type as a service:
```
services:
    my_form_type:
        class: '\ME\MyBundle\Form\Type\MyFormType'
        arguments:
            - '@my_service'
        tags:
            - {name: 'form.type'}
```

But now I have the following error:
> Catchable Fatal Error: Argument 1 passed to \ME\MyBundle\Form\Type\MyFormType::__construct() must be an instance of \ME\MyBundle\Service\MyService, none given, called in /root/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php on line 90 and defined

Symfony instantiate my form type without worrying about my service declaration.

Is this a bug? Or an error on my part?

Thanks!
