### ISSUE TITLE
Yaml comments no longer parsing

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#17116]
```yaml
  ImportSource:
#    none:
#      display: No data source
#      dataType: other
#    sdo:
#      display: Data Objects
    url_list:
      display: List of image URLs
      dataTypeCode: image
```

This used to parse just fine, now I'm getting

![image](https://cloud.githubusercontent.com/assets/619585/11968125/e53f76e4-a8d6-11e5-92f5-3a2162ee10fd.png)

```
tac@zalaptop:/var/www/Posse$ app/console survey:load-fixtures --statuses --types --verbose

                                                       
  [Symfony\Component\Yaml\Exception\ParseException]    
  Unable to parse at line 261 (near "    url_list:").  
                                                       

Exception trace:
 () at /var/www/Posse/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php:298
 Symfony\Component\Yaml\Parser->parse() at /var/www/Posse/vendor/symfony/symfony/src/Symfony/Component/Yaml/Yaml.php:68
 Symfony\Component\Yaml\Yaml::parse() at /var/www/Posse/src/Posse/SurveyBundle/Command/LoadFixturesCommand.php:145
 Posse\SurveyBundle\Command\LoadFixturesCommand->execute() at /var/www/Posse/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/www/Posse/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:856
 Symfony\Component\Console\Application->doRunCommand() at /var/www/Posse/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /var/www/Posse/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:98
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/Posse/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /var/www/Posse/app/console:26

**Comment by Nek-** [comment]
Hello,

I just tested your yaml on symfony 2.7 and it works.
![capture du 2015-12-23 09 13 47](https://cloud.githubusercontent.com/assets/972456/11973084/836250de-a955-11e5-97f5-5eb2fb221d79.png)

What is your Sf version ?

**Comment by Nek-** [comment]
Status: Works for me

**Comment by xabbuh** [comment]
I think this is caused by the changes made in #16860 which is not included in any stable release yet. I'll work on a fix.

Status: Reviewed

**Comment by artjomsimon** [comment]
FYI 2.7.8 got released which included this issue :(
Broke some of our YMLs, which is how I found this.

**Comment by xabbuh** [comment]
@artjomsimon Sorry about that. :( I was blocked by Christmas but working on a patch right now.

**Comment by xabbuh** [comment]
@artjomsimon Can you give an example string that isn't parsed for you?

**Comment by artjomsimon** [comment]
Yes, the problem seems when the hash symbol (''#') is the first character in a line.
As a workaround, moving the # to the right so that the parser sees the indentation before the #, seems to help. Example from OP's code:

Broken:
```
  ImportSource:
#    none:
```

Workaround:
```
  ImportSource:
    #none:
```

Thank you!

**Comment by xabbuh** [comment]
@artjomsimon I try to create a failing test case, but the thing with that example is that the parser doesn't get to the comment line because of the whitespace before `ImportSource`.

**Comment by xabbuh** [comment]
@tacman @artjomsimon If you cannot extract a failing example, you can just create a gist containing the whole file content.

**Comment by artjomsimon** [comment]
@xabbuh here's a MWE:
```
sonata_admin:
    dashboard:
        blocks:
            -
                settings:
                    content: >
                        <h2>Minimal example</h2>
                        <p>of parser having problems parsign comments</p>
    extensions:
#        cmf_core.admin_extension.publish_workflow.publishable:
#            implements:
#                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_core.admin_extension.translatable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Translatable\TranslatableInterface
```

**Comment by xabbuh** [comment]
@artjomsimon Thank you very much. This is indeed really useful.

**Comment by xabbuh** [comment]
@tacman @artjomsimon Can you please check if #17159 fixes your issues?

**Comment by tgabi333** [comment]
i have the same problem after upgrading to 2.8.1.

**Comment by xabbuh** [comment]
@tgabi333 Can you also check the changes in #17159?

**Comment by tgabi333** [comment]
@xabbuh No, I'm sorry, #17159 does not fix all of my issues, i still have exceptions for literal and folded styles:

```
a:
    b: hello
#    c: |
#        first row
#        second row
    d: hello
``` 

Can i use sf 2.8.1 with a working yaml component somehow?
