### ISSUE TITLE
Session save_path not working

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#17157]
```yaml
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
```

The directory ``var/sessions`` exist.

I use Windows 10 x64 with Xampp 3.2.2 (PHP 7).

Symfony use the ``session.save_path`` from the ``php.ini`` file and not from my configuration. Why?
