### ISSUE TITLE
generate:doctrine:crud

### ISSUE THREAD

**Issue by pleamon** [symfony/symfony#17155]
I want generate crud by oneToOne entity, but console tell me is error.
```
Manager\AssetsBundle\Entity\Server:
    type: entity
    table: server
    id:
        id:
            generator:
                strategy: AUTO
    oneToOne:
        contact:
            targetEntity: ServerContact
            inversedBy: server
            joinColumn:
                name: contact_id
                referencedColumnName: id

    fields:
        provider:
            type: string
            length: 20
...
```

```
Manager\AssetsBundle\Entity\ServerContact:
    type: entity
    table: server_contact
    id:
        id:
            generator:
                strategy: AUTO

    oneToOne:
        server:
            targetEntity: Server
            mappedBy: contact
...
```

```
[Twig_Error_Runtime]
  Key "contact" for array with keys "id, provider, telecomIp, unicomIp, mobileIp, netcomIp, privateIp, hostname, cpuModel, cpuCore, memory, diskTotal, diskCound, bandwidth, price, remark" does no
  t exist in "form/FormType.php.twig" at line 29
```

i found the error is here
vendor/sensio/generator-bundle/Generate/DoctrineFormCommand.php:103
```
private function getFieldsFromMetadata(ClassMetadataInfo $metadata)
    {
        $fields = (array) $metadata->fieldNames;

        // Remove the primary key field if it's not managed manually
        if (!$metadata->isIdentifierNatural()) {
            $fields = array_diff($fields, $metadata->identifier);
        }

        _foreach ($metadata->associationMappings as $fieldName => $relation) {
            if ($relation['type'] !== ClassMetadataInfo::ONE_TO_MANY) {
                $fields[] = $fieldName;
            }
        }_

        return $fields;
    }
```

vendor/sensio/generator-bundle/Resources/skeleton/form/FormType.php:29
```
{%- if fields_mapping[field]['type'] in ['date', 'time', 'datetime'] %}
```

oneToOne field is not in metadata->fieldMappings.
