### ISSUE TITLE
files in cache/env/annotation do not respect umask anymore

### ISSUE THREAD

**Issue by rejinka** [symfony/symfony#17492]
As of version 2.8/3.0 the set umask isn't respected anymore. I already identified the problem in doctrine/cache's FilesystemCache having a umask in the used version. This is a problem for our deployment currently. The problem could easily be solved by injecting umask() to the service "annotations.filesystem_cache".

I'd like to create a PR for this, but need to know, whether this *should* be fixed.

**Comment by Tobion** [comment]
Do you use `umask(0)`? See http://www.doctrine-project.org/2015/08/31/security_misconfiguration_vulnerability_in_various_doctrine_projects.html

**Comment by ureimers** [comment]
Thanks for the link @Tobion!

We use ``umask(0)``, because our hosting partner doesn't allow us to be in the www-data group, let alone changing the user of apache. At least for the time being. I hope to convince them that this is pretty archaic.

But nevertheless: Right now we have a problem, because we can't clear our cache anymore. As we are the only user who have access to the cache directory, is there any way to temporarily set the umask for doctrine caches to 0 again?

**Comment by nullziu** [comment]
I ran into this issue today. @rejinka @ureimers did you find a workaround?

**Comment by rejinka** [comment]
Sorry @nullziu, forgot to answer. Yeah i worked around that issue by redefining the service:

```yaml
services:
    # Force doctrine to not use 0664 (i.e. 0666 ~ umask(0002)) for annotation cache files
    annotations.filesystem_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        public: false
        arguments:
            - "%kernel.cache_dir%/annotations"
            - null
            - 0
```

I opened this issue more than half a year ago and no core member responded. So I'll close this ticket.
