### ISSUE TITLE
 Dependency Injection: 'simple injection' or @service_container

### ISSUE THREAD

**Issue by nietzcheson** [symfony/symfony#17548]
Hi all. A greeting. 

I do not know where is the place to do it . But I want to share it and discuss it.

I doubt has arisen . We know the great power of the injection of dependencies within the program ( and Symfony).

What followed? In Symfony I can create a service and injecting it into another . But I can also inject the service_container and have all services in a single variable. Does this last sentence the application performance ? Is it advisable to use only the services I need ?

```yml

services:
  service:
    class: AppBundle\Service;
  
  service.utils:
    class: AppBundle\ServiceUtils;
    arguments:
      - @service

service.container:
    class: AppBundle\ServiceContainer;
    calls:
      - [setContainer, [‘@service_container']]

```

Cheers...
