### ISSUE TITLE
simple_preauth is successful, yet it checks other validators too

### ISSUE THREAD

**Issue by iBasit** [symfony/symfony#17547]
My simple_preauth validate user, after successful PreAuthenticatedToken, then it goes fos_oauth validation. It should have stopped, since user is successful authenticated. 

Can someone guide me on how I can stop it going to fos_oauth, if it was successful login with simple_preauth

```yml
api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            simple_preauth:
                authenticator: session_authenticator
            provider: user
```
