### ISSUE TITLE
add support for composite environment variables

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#17689]
I'm considering switching to environment variables for defining machine specific settings, but I have some trouble figuring out how I should define composite environment variables.

For instance, I use clustering for my ES nodes in production, but in dev, I only have one node, which means I need to be able to do something like this in my configuration : 

```yml
fos_elastica:
    clients:
        default:
            connections: %search_engine.connections%
```

and have symfony inject an array in the `search_engine.connections` container parameter. At the moment, a workaround would be to do some custom treatment to deserialize the content of my environment variable and overwrite what is found in `$_SERVER` so that Symfony injects an array instead of a string in the container parameter.

Support for some serialization format would be nice. The format could default to yaml or json (or whatever you see fit), so that something like that could be done : 

```
export SYMFONY__SEARCH_ENGINE__CONNECTIONS="[ 'searchengine1:9200', 'searchengine2:9200' ]"
sfcl
```

At the moment, this outputs the following : 

> Invalid type for path "fos_elastica.clients.default.connections". Expected array, but got string

**Comment by Jean85** [comment]
Why couldn't you use an array with a single value inside?

**Comment by greg0ire** [comment]
@Jean85 : I don't understand your question. If I use an array with a single value inside, I'm no longer using my two ES nodes. If one falls down, the second one will be useless even though it is up and running.

**Comment by Jean85** [comment]
@greg0ire sorry, I didn't specify that, but I was talking about your `search_engine.connections` parameter in the dev enviromnent... If you still inject an array, but with just one value inside, isn't that feasible?

**Comment by greg0ire** [comment]
That's the problem, I can't inject an array, only strings. "[value]" is considered a string.

**Comment by jmcclell** [comment]
I've not seen anyone try to use a bash array as an environment variable before in this context. I'm not sure why it never occurred to me to try. A quick google brings me this [StackOverflow post](http://stackoverflow.com/questions/18128536/bash-how-to-define-an-array-as-environment-variable-before-calling-a-bash-scrip), but, in general, environment variables *are* simply strings. The `%parameters%` as defined by Symfony seem to be in the spirit of string-based, shell-level environment variables.

There *is*, however, the Expression component which, from what a quick Google search tells me, might let you execute expressons in your configuration. I've never actually tried it, but here's a possible solution for you (totally untested, writing it as a I go. The rest will be up to you):

**Example of expression language in a configuration file**

```yml
services:
    session.handler.memcache:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ["@=service('myapp.parameters').get('memcached')"]
```

**Possible Solution**

```yml
# file: app/config/services.yml
services:
    myapp.parameters:
        class: MyAppBundle\Parameters
        # MY_APP_PARAMETERS_FILE would be defined as an environment variable on the server
        # In my example, it would point to a valid Yaml document with your parameters defined
        # e.g. $ export MY_APP_PARAMETERS_FILE=/path/to/params.yml
        arguments: ["%MY_APP_PARAMETERS_FILE%"]
```

```yml
# file: /path/to/params.yml
search_engine_connections:
  - searchengine1:9200
  - searchengine2:9200
```

```php
<?php
// file: src/MyAppBundle/Parameters.php
namespace MyAppBundle;

use Symfony\Component\HttpFoundation\ParameterBag;
use Symfony\Component\Yaml\Yaml;

class Parameters extends ParameterBag
{
    public function __construct($paramFile = null)
    {
        if ($paramFile) {
            $params = $this->loadParamsFromFile($paramFile);
        } else {
            $params = [];
        }
        parent::__construct($params);
    }

    protected function loadParamsFromFile($paramFile)
    {
        if (file_exists($paramFile)) {
            return Yaml::parse(file_get_contents($paramFile));
        } else {
            // throw an exception or something maybe
        }       
}
```

```yml
# file: app/config.yml
fos_elastica:
    clients:
        default:
            connections: "@=service('myapp.parameters').get('search_engine_connections', [])"
```


I have **no** idea if this will work, but your question piqued my interest because I also have wished for a more dynamic way to load configuration from the environment. Otherwise, I'd head to **StackOverflow** because I'm doubting the Symfony devs are going to be keen on changing the concept of `%parameters%` beyond being string-based environment variables - but, I could be wrong!
