### ISSUE TITLE
Autowiring confuses argument order in some cases

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#17724]
Hi guys!

Take the following class:

```php
class ProductRepository
{
    private $client;
    private $logger;

    public function __construct(Client $client, LoggerInterface $logger)
    {
        $this->client = $client;
        $this->logger = $logger;
    }
}
```

Since `LoggerInterface` can't be injected yet (we're waiting on a MonologBundle tag), I wired it like this:

```yml
services:
    product_repository:
        class: AppBundle\Repository\ProductRepository
        autowire: true
        arguments:
            1: '@logger'
```

Sure, it's weird to have the "1" in there, but I thought it would work. It *almost* did, but it reversed the arguments. In the cached container, this becomes:

```php
new ProductRepository($this->get('logger'), $this->get('api_client'));
```

In YAML, I believe this is the only way to set *one* specific argument, without specifying *all* of them, and it looks like a bug :).

Especially because non-services can't be autowired yet, this probably the biggest issue left with autowiring (along with not being able to globally map a class/interface to a specific service id).

ping @dunglas 

Thanks!

**Comment by iltar** [comment]
Might be a weird brainfart, but what about allowing a map of `<number>: <argument>` under autowire additionally to true? This would leave the arguments as is without modifications but allows any edge-cases configurable under the autowire key.

**Comment by weaverryan** [comment]
@iltar So first, there *is* still a bug here - I want to make sure we keep that focus :).

But, your idea is interesting. Well actually, if it weren't for this bug, you *can* already do what you're saying, just under the `arguments` keys using indexes 0, 1, 2, etc. However, it *might* be interesting with autowiring to allow named arguments - as it's a bit weird to specify your "argument index 1" value. So then:

```yml
services:
    product_repository:
        class: AppBundle\Repository\ProductRepository
        autowire:
            logger: '@logger'
```

In theory, this could also still just be done under `arguments` (it's just a different way of specifying arguments), but autowiring is the only thing currently that uses reflection (needed to get the arg name)... so I'm not sure if it would make sense there. But maybe :)

**Comment by dunglas** [comment]
@weaverryan this use case is already supported (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L75)

The following snippet should work:

```yaml
services:
    product_repository:
        class: AppBundle\Repository\ProductRepository
        autowire: true
        arguments: [ '', '@logger' ]
```

**Comment by dunglas** [comment]
It looks weird in YAML (but works), it's far better in XML:

```xml
<service id="product_repository" class="AppBundle\Repository\ProductRepository" autowire="true">
    <argument />
    <argument type="service" id="logger" />
</service>
```

**Comment by weaverryan** [comment]
@dunglas 

You're right - but it's odd: if I use your same syntax but with `null`, it'll fail:

```yml
services:
    product_repository:
        class: AppBundle\Repository\ProductRepository
        autowire: true
        arguments:
            - ~
            - '@logger'
```

Anyways, with your working example, it just doesn't *feel* right. One day, autowiring might work great. Then suddenly I add a 4th constructor argument that can't be autowired. Suddenly I need to add 5 lines (`arguments` and the lines below) to make the service work again:

```yml
services:
    product_repository:
        class: AppBundle\Repository\ProductRepository
        autowire: true
        arguments:
            - ''
            - ''
            - ''
            - ''
            - '%kernel.root_dir%'
```

And if we change the order of the args (something autowiring should allow), it'll break.

What do you think about my previous suggestion? https://github.com/symfony/symfony/issues/17724#issuecomment-181848815

**Comment by dunglas** [comment]
@weaverryan it makes a lot of sense to enhance this feature. I personally prefer you're proposal of using: 

```yaml
services:
    product_repository:
        class: AppBundle\Repository\ProductRepository
        autowire: true
        arguments:
            1: '@logger'
```

Because it couples less the code with the configuration. With named parameters, if you rename a constructor parameter, it breaks the app. With numbers as keys, the only way to break the app is to change the order of parameters (and it's already considered a BC break).
