### ISSUE TITLE
Improve formatting of `debug:config`

### ISSUE THREAD

**Issue by ianfp** [symfony/symfony#17756]
When I run, eg, `debug:config doctrine`, I get something that looks like this:

```
doctrine:
    dbal:
        default_connection: default
        connections: { default: { driver: pdo_mysql, host: localhost, dbname: XXX, user: XXX, password: XXX, charset: UTF8, logging: true, port: null, profiling: true, options: {  }, mapping_types: {  }, default_table_options: {  }, slaves: {  }, shards: {  } } }
        types: {  }
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers: { default: { auto_mapping: true, connection: null, dql: { string_functions: { IFNULL: DoctrineExtensions\Query\Mysql\IfNull, IF: DoctrineExtensions\Query\Mysql\IfElse, GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat, REPLACE: DoctrineExtensions\Query\Mysql\Replace }, datetime_functions: { TIMESTAMPDIFF: DoctrineExtensions\Query\Mysql\TimestampDiff }, numeric_functions: {  } }, query_cache_driver: { type: array, namespace: null, cache_provider: null }, metadata_cache_driver: { type: array, namespace: null, cache_provider: null }, result_cache_driver: { type: array, namespace: null, cache_provider: null }, class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory, default_repository_class: Doctrine\ORM\EntityRepository, naming_strategy: doctrine.orm.naming_strategy.default, quote_strategy: doctrine.orm.quote_strategy.default, entity_listener_resolver: null, repository_factory: null, hydrators: {  }, mappings: {  }, filters: {  } } }
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

(It looks even worse when word-wrapped on my console.)

It would be nice if the entire thing were presented in "block" style (ie, without the curly-brace syntax).
