### ISSUE TITLE
EntityManager Service Auto Wiring

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#17850]
Hi,

I am trying to use the new [auto wiring feature](http://symfony.com/blog/new-in-symfony-2-8-service-auto-wiring) to automatically load the entity manager to my service:

```yaml
my_test_service.test:
      class: MyTestBundle\Service\TestService
      autowire: true
```

```php
use Doctrine\ORM\EntityManager;
class TestService
{
    public function __construct(EntityManager $em)
    {
    }
}
```

Result is:

```
RuntimeException in AutowirePass.php line 231: Unable to autowire argument
of type "Doctrine\ORM\EntityManager" for the service "my_test_service.test".
```

Any idea?

Thanks

Seb

**Comment by Tobion** [comment]
You probably want to typehint `EntityManagerInterface`

**Comment by Seb33300** [comment]
Same error:

> Unable to autowire argument of type "Doctrine\ORM\EntityManagerInterface" for the service

**Comment by iltar** [comment]
You want an entity manager but of which connection? For which Entity? This is nearly impossible to determine if you have more than 1 entity manager.

**Comment by maryo** [comment]
Exactly. But I guess it should autowire the default one if there is only one in the application. Otherwise you'd have to specify autowiring_types. But looks it is not possible to specify autowiring types for services you "don't own".

I created an issue for this few days ago
https://github.com/symfony/symfony/issues/17783

What do you think @Tobion ?

**Comment by Seb33300** [comment]
Actually, I am passing manually the entity manager service with:
```
my_test_service.test:
      class: MyTestBundle\Service\TestService
      arguments:
          em: "@doctrine.orm.entity_manager"
```

I only want to do that by auto wiring.
