### ISSUE TITLE
Symfony 3 - Create own user provider - Error Service

### ISSUE THREAD

**Issue by DRaineri** [symfony/symfony#17871]
Hi !

I don't use FOSUserBundle and try to implement the FOAOAuthServerBundle, so I need to create my own user provider (if I'm right ^^)

I want to get token for user with 
`http://myWebsite.com/web/app_dev.php/oauth/v2/token?client_id=CLIENTID&client_secret=SECRET&grant_type=password&username=mylogin&password=mypassword`

so I have a class user

```
class User implements AdvancedUserInterface, \Serializable
{
 /* id, username, password, email, etc */
}
```
and my UserRepository

```
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
```
and my UserProvider

```
<?php
  // src/MyAwesomeBundle/Provider/UserProvider.php

  namespace MyAwesomeBundle\Provider;

  use Symfony\Component\Security\Core\User\UserInterface;
  use Symfony\Component\Security\Core\User\UserProviderInterface;
  use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
  use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
  use Doctrine\Common\Persistence\ObjectRepository;
  use Doctrine\ORM\NoResultException;

  class UserProvider implements UserProviderInterface
  {
      protected $userRepository;

      public function __construct(ObjectRepository $userRepository){
          $this->userRepository = $userRepository;
      }

      public function loadUserByUsername($username)
      {
          $q = $this->userRepository
              ->createQueryBuilder('u')
              ->where('u.username = :username OR u.email = :email')
              ->setParameter('username', $username)
              ->setParameter('email', $username)
              ->getQuery();

          try {
              $user = $q->getSingleResult();
          } catch (NoResultException $e) {
              $message = sprintf(
                  'Unable to find an active admin MyAwesomeBundle:User object identified by "%s".',
                  $username
              );
              throw new UsernameNotFoundException($message, 0, $e);
          }

          return $user;
      }

      public function refreshUser(UserInterface $user)
      {
          $class = get_class($user);
          if (!$this->supportsClass($class)) {
              throw new UnsupportedUserException(
                  sprintf(
                      'Instances of "%s" are not supported.',
                      $class
                  )
              );
          }

          return $this->userRepository->find($user->getId());
      }

      public function supportsClass($class)
      {
          return $this->userRepository->getClassName() === $class
          || is_subclass_of($class, $this->userRepository->getClassName());
      }
  }
```
I register it into MyAwesomeBundle\Resources\config\services.yml

```
services:
    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManagerForClass
        arguments: ['MyAwesomeBundle\Entity\User']
    platform.user.repository:
        class: StreetGamesBundle\Repository\UserRepository
        factory_service: platform.user.manager
        factory_method: getRepository
        arguments: ['MyAwesomeBundle\Entity\User']
    platform.user.provider:
        class: MyAwesomeBundle\Provider\UserProvider
        arguments: ['@platform.user.repository']
```
But when I try to access to my glorious token ....

`Catchable Fatal Error: Argument 2 passed to Doctrine\ORM\EntityRepository::__construct() must be an instance of Doctrine\ORM\Mapping\ClassMetadata, none given, called in C:\wamp\www\MyAnwsomeWebSite\var\cache\dev\appDevDebugProjectContainer.php on line 1906 and defined`

I give you my config file too, just in case if I miss something

```
#FOSOAuth Configuration
fos_oauth_server:
db_driver: orm
client_class: MyAwesomeBundle\Entity\Client
access_token_class: MyAwesomeBundle\Entity\AccessToken
refresh_token_class: MyAwesomeBundle\Entity\RefreshToken
auth_code_class: MyAwesomeBundle\Entity\AuthCode
service:
user_provider: platform.user.provider
options:
supported_scopes: user
```

Thank you for your help. I'm stuck on this since too much time ...

PS: If it can help, documentations used
[Tankist blog](http://blog.tankist.de/blog/2013/07/17/oauth2-explained-part-2-setting-up-oauth2-with-symfony2-using-fosoauthserverbundle/)
[Bitgandteer wordpress](https://bitgandtter.wordpress.com/2015/09/10/symfony-a-restful-app-security-fosoauthserverbundle/)

UPDATE : Has noticed [here ](https://github.com/symfony/symfony/issues/14687) the factory_service and factory_method is deprecated since 2.8.

My new services.yml

services:
    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine','getManagerForClass']
        arguments: ['MyAwesomeBundle\Entity\User']
    platform.user.repository:
        class: MyAwesomeBundle\Repository\UserRepository
        factory: ['@platform.user.manager','getRepository']
        arguments: ['MyAwesomeBundle\Entity\User']
    platform.user.provider:
        class: MyAwesomeBundle\Provider\UserProvider
        arguments: ['@platform.user.repository']
And It works !! Thanks ^^
