### ISSUE TITLE
[Security] [Bug] Force login without any password provided

### ISSUE THREAD

**Issue by ihsanudin** [symfony/symfony#17897]
My Security

```yaml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_BENDAHARA: [ROLE_BENDAHARA, ROLE_USER]
        ROLE_REVIEWER: [ROLE_REVIEWER, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_BENDAHARA, ROLE_REVIEWER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                require_previous_session: true
                always_use_default_target_path: true
                default_target_path: home
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous: true
            remember_me:
                secret:   "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

    access_control:
        - { path: ^/bundles*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/img*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fonts*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/plugins*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [ROLE_USER, IS_AUTHENTICATED_FULLY] }
```

After i'm upgraded Symfony to 3.0.2, i have a problem. After logout, i can access /admin without provide any credential.

I try to change the config and also try login using others browser and i got same problem.

My application run behind varnish but previously i never found this problem
