### ISSUE TITLE
Symfony 3.0.2 : Problem of authentification Login form

### ISSUE THREAD

**Issue by falexis77** [symfony/symfony#17896]
For several days I have this problem of authentication by a login form. When I enter the username 'john' and the password 'fury', I still have the same message : Bad credentials

This is my user entity

```php
class User implements UserInterface
{
    private $id;
    private $email;
    private $username;
    private $plainPassword;
    private $password;
    private $roles = array();

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;
    }

    public function getUsername()
    {
        return $this->username;
    }
    
     public function setUsername($username)
    {
        $this->username = $username;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }
    
    public function getPassword() {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }
    
     public function getSalt()
    {
        return null;
    }
    
    public function eraseCredentials() {
        
    }

    public function setRoles($roles) {
        $this->roles = $roles;

        return $this;
    }

    public function getRoles() {
        return $this->roles;
    }

    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
        ));
    }

    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
        ) = unserialize($serialized);
    }
}
```

I'm use data fixtures to register a user

```php
public function load(ObjectManager $manager) {
$user = new User;
      $user->setUsername('john');
      $user->setRoles(array('ROLE_ADMIN'));
      $user->setEmail('john.doe@marvel.com');
      $user->setPlainPassword('fury');
      $password = $this->container->get('security.password_encoder')->encodePassword($user, $user->getPlainPassword());
      $user->setPassword($password);

      $manager->persist($user);

       $manager->flush();
}
```

Security.yml

```yaml
encoders: 
        UserBundle\Entity\User:
            algorithm: pbkdf2
            hash_algorithm: sha512
            encode_as_base64: true
            iterations: 1000
           providers:
             manager:
               entity:
                class: UserBundle\Entity\User
                property: username

main:
            pattern: ^/
            anonymous: true
            provider:  manager
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /login
            logout:
                path: logout
                target: /login
            remember_me:
                secret:      "%secret%"
                lifetime: 1209600
```

On the login action 

```php
public function loginAction(Request $request) {
        
        $helper = $this->get('security.authentication_utils');

        return $this->render('UserBundle:Access:login.html.twig', array(
                'last_username' => $helper->getLastUsername(),
                'error' => $helper->getLastAuthenticationError(),
        ));
    }
```

the template twig for login 

```twig
<div class="input-group input-group-lg">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                <input type="text" id="username" name="_username" class="form-control" placeholder="{{ 'form.field_username'|trans }}" value="{{ last_username }}">
            </div>

            <div class="input-group input-group-lg">
                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                <input type="password" id="password" name="_password" class="form-control" placeholder="{{ 'form.field_password'|trans }}">
            </div>
            
            <p class="forgot-password"><a href="{{ path('forgot_password') }}">{{ 'form.forgot_password'|trans }}</a></p>

            <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

            <button type="submit" name="submit" class="float">{{ 'form.submit'|trans }}</button>
        </form>
            
    </div>
</div>
```

**Comment by backbone87** [comment]
please cleanup your ticket, your posted code is mostly unformatted

**Comment by javiereguiluz** [comment]
@falexis77 in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

---

In any case, here is something you might try. In your security.yml file, change this:

```yaml
encoders: 
        UserBundle\Entity\User:
            algorithm: pbkdf2
            hash_algorithm: sha512
            encode_as_base64: true
            iterations: 1000
```

by this:

```yaml
encoders: 
        UserBundle\Entity\User: plaintext
```

Reload the fixtures and check the login form again. If it works, the problem might be that the database column that stores the hashed password is not long enough to store it and the password is truncated when saving it. For `sha512`you need at least `chat(128)` columns.
