### ISSUE TITLE
DEV toolbar crashing when trying to get user from token storage in kernel.request listener

### ISSUE THREAD

**Issue by clytemnestra** [symfony/symfony#18056]
Using SF 2.8.3 and having the following class and its configuration:
```php
class ThemeRequestListener
{

    private $sam;

    public function __construct(TokenStorage $sam)
    {

        $this->sam = $sam;
    }

    /**
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        $a = $this->sam->getToken()->getUser();
    }

}
```

```yaml
    liip_theme.theme_request_listener:
        class: Application\Liip\ThemeBundle\EventListener\ThemeRequestListener
        arguments: [ @security.token_storage ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -1 }
```

My DEV environment always crashes with the toolbar asking me to be opened in a dialog. However, PROD works just fine, so the problem is with the Symfony toolbar

```php
Error: Call to a member function getUser() on null
```

I've tried with a fresh new 2.8.3 project with no vendor bundle aside the standard ones, just this listener and getting the same error.
