### ISSUE TITLE
Unable to use apcu to cache validator mappings

### ISSUE THREAD

**Issue by videni** [symfony/symfony#18083]
As we know apc is deprecated,  I try to use apcu cache using following steps , it works in dev environment ,   but no matter what I try , it doesn't work in production.  I  removed app/cache/prod using  `app/console cache:clear --env=prod --no-debug` command. it still shows this error:

> Unable to use ApcCache to cache validator mappings as APC is not enabled.  

```xml
 <service id="validator_mapping_cache" class="Symfony\Component\Validator\Mapping\Cache\DoctrineCache" public="false">
            <argument type="service">
                <service class="Doctrine\Common\Cache\ApcuCache">
                    <call method="setNamespace">
                        <argument>%validator.mapping.cache.prefix%</argument>
                    </call>
                </service>
            </argument>
        </service>
```

```yaml
framework:
    validation:
        enable_annotations: true
        cache: validator_mapping_cache
```
