### ISSUE TITLE
How to enable the debug toolbar/profiler in production mode?

### ISSUE THREAD

**Issue by yellow1912** [symfony/symfony#18097]
I understand this should not be done, but I'm having a very weird issue:

Recently, I have just upgraded to PHP7 and since then my application refuses to run without at least 1GB memory_limit in php. This only happens in production mode however, the dev mode runs fine with 1/4 of the memory (which seems to be against normal thinking)

So I need to be able to view the profile in production mode without actually setting the debug mode to true in AppKernel. So far I cannot seem to do that even after placing this in my config.yml and include the profiler bundle ready in AppKernel

  ```yml
framework:
    profiler:
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: true

```

I also added the routings as well.
