### ISSUE TITLE
Symfony DI cannot factory a service with SessionHandlerInterface in class definition

### ISSUE THREAD

**Issue by devsdmf** [symfony/symfony#18158]
Hello everyone,

In my current production build I have a custom session handler to manage my sessions between development, stagging and production environments, and in my current application I have a working service that overwrite the default symfony framework session handler that uses the DI component to inject the custom handler, my service is configured like other factories but just in this case I'm having a trouble with the DI component.

This is my sample services.yml file:
```yaml
services:

    vendor.core.session.handler_factory:
        class: Vendor\Component\Core\Session\Handler\HandlerFactory

    vendor.core.session.handler:
        class: \SessionHandlerInterface
        factory_service: vendor.core.session.handler_factory
        factory_method: factory
        arguments:
            - "@kernel"
            - "@service_container"

    vendor.core.session.storage:
        class: Vendor\Component\Core\Session\Storage
        arguments:
            - %session.storage.options%
            - "@vendor.core.session.handler"
            - "@service_container"
```

And I'm getting the error message below:
```
[Symfony\Component\DependencyInjection\Exception\RuntimeException]
  Cannot dump definition because of invalid class name ('\\SessionHandlerInterface')
```

Here's another service configured like this, that works fine:
```yaml
services:

    vendor.environment.factory:
        class: Vendor\Component\Environment\Services\EnvironmentFactory

    vendor.environment:
        class: Vendor\Component\Environment\EnvironmentInterface
        factory_service: vendor.environment.factory
        factory_method: factory
        arguments:
            - "@kernel"
```

My current PHP version:
```
PHP 5.6.18 (cli) (built: Feb 22 2016 11:26:08)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

The current production build uses Symfony 2.7 and we're migrating to 3.x.

**Comment by xabbuh** [comment]
Does the issue persist when you remove the leading backslash from the interface name?

**Comment by devsdmf** [comment]
No, in that case, it throws a different error:
```
PHP Fatal error:  Cannot instantiate interface SessionHandlerInterface in /Users/devsdmf/Projects/ishp-mobile/var/cache/dev/appDevDebugProjectContainer.php on line 1162
```

**Comment by xabbuh** [comment]
This looks weird. Can you please fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by devsdmf** [comment]
@xabbuh I found a way. I changed the service definition like the Symfony 3.0 documentation and that worked.

```yaml
services:

    vendor.core.session.handler.factory:
        class: Vendor\Component\Core\Session\Handler\HandlerFactory

    vendor.core.session.handler:
        class: \SessionHandlerInterface
        factory: ["@vendor.core.session.handler.factory", factory]
        arguments:
            - "@kernel"
            - "@service_container"

    vendor.core.session.storage:
        class: Vendor\Component\Core\Session\Storage
        arguments:
            - %session.storage.options%
            - "@vendor.core.session.handler"
            - "@service_container"
```
