### ISSUE TITLE
error handler does not catch deprecated notice in production environment

### ISSUE THREAD

**Issue by fritzmg** [symfony/symfony#18163]
I have created a Symfony app (initialized using `composer create-project`) and for some reason deprecated notices are shown in the frontend for the _production environment_. As far as I know, this shouldn't happen by default. I am using the default monolog settings (generated by the `create-project` command). So for the dev environment the following settings are used:
```
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
```
and for the production environment, the following settings are used:
```
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
```
When using the dev environment via `app_dev.php`, deprecated notices are not shown in the frontend, but they get logged to `app/logs/dev.log`, e.g.
```
[2016-03-14 13:35:13] php.INFO: JSMinPlus is deprecated. This will be removed in Minify 3.0 {"type":16384,"file":"…/vendor/mrclay/minify/min/lib/JSMinPlus.php","line":202,"level":-1,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"…/vendor/mrclay/minify/min/lib/JSMinPlus.php","line":202,"function":"trigger_error"},{"function":"minify","class":"JSMinPlus","type":"::"}…
```
However, in the production environment via `app.php`, the deprecated notices are displayed in the frontend (and not logged at all). As far as I have tested it, Symfony's error handler is not invoked at all.

With this configuration, the deprecated notices should not show up at all anywhere (neither in the log, nor in the frontend), or am I mistaken?
