### ISSUE TITLE
[Form] Cannot use setter injection in FormType ?

### ISSUE THREAD

**Issue by Alsatian67** [symfony/symfony#18231]
I'm using Symfony 3.0

Is it not possible to use setter injection within the method configureOptions on a FormType.

I wanted to inject the router through a setter injection :
```yaml
services:    
    form_type.router:
        class: AppBundle\Form\RouterType
        calls:
            - [setRouter,["@router"]]
        tags:
            - { name: form.type }
```

Here I tested it at several positions :

```php
abstract class AbstractRoutableType extends AbstractType
{
    protected $router;
        
    public function setRouter($router) // Setter injection
    {
        $this->router = $router;
    }
    
    public function configureOptions(OptionsResolver $resolver)
    {  
        $this->setRouter();      // <--- Tested : Don't work (not in a closure should work)
        $resolver->setDefault('route',false);        
        $resolver->setDefault('attr', function(Options $options, $attr){
           
            if($options['route']){
                $this->setRouter();      // <--- Where I want to use id  : Don't work (Normal in a closure ?)
                $attr['data-ajax--url']=$this->router->generate($options['route']);
            }
            
            return $attr;
        });
    }
}
```

It throws error 'missing argument 1 for setRouter' ...

Bug or normal behaviour ?

EDIT : Just see that it is the same in a service tagged 'doctrine.event_listener'

Say me if I should reproduce the bug in a symfony-standard fork.

Thanks.

**Comment by HeahDude** [comment]
Hi @Alsatian67, I see two issues with your sample code.

- First you should remove the constructor which currently calls the setter with no arguments.

- You cannot use `$this` in a closure, you should pass the object you need with `use`:
  ```php
  // in configureOptions()

  $router = $this->router; // should have been set by the DI

  $resolver->setDefault('attr', function (Options $options, $attr) use ($router) {
      if($options['route']){
          $attr['data-ajax--url'] = $router->generate($options['route']);
      }

      return $attr;
  });
```

**Comment by Alsatian67** [comment]
Thank you for your response. Forget the constructor that was just a test to try it in another place.

OK for the closure, but why can I access to $this->router in the closure when I inject the router with a constructor injection ?

**Comment by Alsatian67** [comment]
Same problem with a doctrine event_listener :

```yaml
services:
    places.listener:
        class: AppBundle\EventListener\PlacesPostLoadListener
        calls:
            - [setDocumentManager,["@doctrine.odm.mongodb.document_manager"]]
            - [setRequest,["@request_stack"]]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
```

```php
<?php
namespace AppBundle\EventListener;

use Doctrine\ORM\Event\LifecycleEventArgs;

use AppBundle\Entity\Places;

class PlacesPostLoadListener
{
    private $dm;
    private $requestStack;

    public function setDocumentManager($dm)
    {
        $this->dm = $dm;
    }
 
	public function setRequest($requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function postLoad(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
		
        if($entity instanceOf Places){
		    if(!$city = $entity->getCity()){return;}

			$this->setDocumentManager();
			$this->setRequest();

		    $cityDoc = $this->dm->getRepository('AlsatianGeoBundle:Levels')->findOneById($city);
		    
		    $entity->setCityDocPostLoad($cityDoc);
		    $entity->setCityLanguage($this->requestStack->getMasterRequest()->getLocale());
        }
    }
}
```

Same issue ...
