### ISSUE TITLE
[Translator] Reuse translation values?

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#18266]
I often have some general translations, like:

```yaml
app:
    errors:
        not_authorized: You are not authorized
```

I also have some more specific translation keys:

```yaml
app:
    foo:
        bar:
            not_authorized_error: You are not authorized
```

Is there a way to reuse the general value in the "specific" key? As far as I can see, there isn't.

My proposition:

```yaml
app:
    errors:
        not_authorized: You are not authorized
    foo:
        bar:
            not_authorized_error: @app.errors.not_authorized
```
