### ISSUE TITLE
[Feature] configure the log directory in container paramters

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#18476]
My application has two parts:
1. a web app (built by Symfony)
2. a daemon (written by Python)

I want all of log files are in on directory (the directory was configured in a public YAML file).

**Comment by iltar** [comment]
Can you explain what the feature is you are proposing?

**Comment by javiereguiluz** [comment]
@zacharyzh that's what Symfony does by default. Look at your config file:

```yaml
# app/config/config_dev.yml
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
```

To make it configurable with a parameter, do this:

```yaml
# app/config/parameters.yml
parameters:
    app.log_file: "..."

# app/config/config_dev.yml
monolog:
    handlers:
        main:
            type: stream
            path: "%app.log_file%"
```

@zacharyzh in any case, in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
