### ISSUE TITLE
Store Uploaded Images outside Web Directory

### ISSUE THREAD

**Issue by TaqiOfficial** [symfony/symfony#18480]
I want to store the symofny uploaded images/documents in the User Home Directory ~/home/muhammadtaqi/Pictures.  I have set the this parameters in my config.yml file as; below

```yaml
# Twig Configuration
twig:
    form:
            resources:
                - 'JbFileUploaderBundle:Form:fields.html.twig'

    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        media_directory: ~/home/muhammadtaqi/Pictures/
```

```yaml
# This file is auto-generated during the composer install
parameters:
    media_directory: '/home/muhammadtaqi/Pictures/'
```

and in the templates Em showing the images like this, 

```twig
<img src="{{ asset(media_directory~ user.avatar  )}}"
     alt="" class="img-media">
```

> **but it is still pointing to the web directory?
> How can it  fix this?**
