### ISSUE TITLE
[Symfony 2.8][Security] the default_target_path does not works if you have logged in

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#18622]
security.yml

``` yaml
    providers:
        ......
    firewalls:
        admin:
            pattern: ^/admin/
            provider: someid
            form_login:
                login_path: app_login
                check_path: app_login_check
                default_target_path: app_dashboard
            logout:
                 ......
            anonymous: ~
```

routing.yml

``` yaml
    app_login:
        path: /login
        defaults: { _controller: ... }
    app_login_check:
        path: /login_check
```

I was tried to login, but I did not notice I have logged in, and then I got this exception:

```
Unable to find the controller for path “/login_check”
```

The firewall would redirect me to the default_target_path in my mind, because I have logged in. But it didn't.

---

How to reproduce:
1. log in from your login form
2. back to the login form and log in again
3. got exception
