### ISSUE TITLE
[Guard] Locking with concurrent requests

### ISSUE THREAD

**Issue by smartpierre** [symfony/symfony#18713]
Hello everyone,

I have a REST API built with with Symfony 3.0.4. 
When I am working on my laptop on the dev environment, I encouter a weird issue...
I have a front-end built with VueJS making requests to the API. When loading a new vue I make up to 5 simultaneous requests to the API and I have some serious blockage : I have at least 20 seconds delay for the requests and a lot of time it just timeout and I have to reboot php-fpm, nginx and clear the SF3 cache.
In the profiler I see that the blockage happens in the Guard component. I have two guess :
 - there's a lock on the Guard level
 - there's a lock happening at the database level (could be Doctrine, php-mysql or just mysql itself)

Because it's a stateless API, it fetch the API token and the user profile from the database on each request (I know it's bad, but I only managed to cache half of it so far).

Here are screenshots of two requests done at the same time : 

![screenshot from 2016-05-05 14-59-30](https://cloud.githubusercontent.com/assets/8858750/15044011/0772a690-12d2-11e6-826a-87d3090a9510.png)

![screenshot from 2016-05-05 14-59-10](https://cloud.githubusercontent.com/assets/8858750/15044012/0b56e244-12d2-11e6-925a-6b5fb0684828.png)

And here are the logs of one the request : 

![screenshot from 2016-05-05 15-01-05](https://cloud.githubusercontent.com/assets/8858750/15044035/43b976e2-12d2-11e6-9936-34a31bea3659.png)

For comparison, if I do my requests one at a time I rarely have more than 1000ms for the response.
I do not have this problem on the production server or the pre-production server...

So if anyone has an idea, I'm open !

Pierre.

**Comment by iltar** [comment]
Missing indexes in your mysql? full table locking? Could be anything really, but I highly doubt this is related to Symfony

**Comment by Nicofuma** [comment]
It could also be due to the session itself if you have any kind of session locking (like in the PdoSessionHandler). Because configuring a firewall as stateless doesn't prevent the creation of a session, it will only deactivate the ContextListener which try to restore an authenticated token from the session.

**Comment by stof** [comment]
If you API is stateless, you should also disable the session entirely in FrameworkBundle

**Comment by stof** [comment]
> I do not have this problem on the production server or the pre-production server

This really looks like a session locking. Your prod server probably uses a different session storage (redis maybe) which does not implement locking.

**Comment by smartpierre** [comment]
First, a **BIG** thank you taking the time to look after my issue !

Here the session configured in my config.yml : 
```yaml
framework:
    session:
        gc_probability: 0
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.null
```
My services.yml : 
```yaml
services:
    # SessionHandler that will not write any session => we are stateless
    session.handler.null:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\NullSessionHandler
        public: false
```

And my security.yml : 
```yaml
security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            logout: ~
            anonymous: ~
            guard:
                authenticators:
                    - app.token_authenticator
```

As far as I know, I don't have any session storage occurring with that configuration. Or maybe I missed something ?
I use the same configuration in DEV and PROD for the sessions.
I am currently investigating on mysql, I even switched to the latest version of mariadb in the hope of making a difference (it did not). But if we could at least get Guard off the table, that could be great.
