### ISSUE TITLE
[DependencyInjection][Debug] Fatal error: Cannot declare class when clearing cache

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony#18769]
Error message when doing `bin/console cache:clear`:

```
Fatal error: Cannot declare class AppBundleEventListenerOrderStatusChangeTrackingDoctrineListener_0000000000e83129000000005c3397c6257cf4332315f2adc80479a9d1836499, because the name is already in use in /srv/tripviss-api/var/cache/de_/ap_DevDebugProjectContainer.php on line 6744

    [Symfony\Component\Debug\Exception\FatalErrorException]
    Compile Error: Cannot declare class AppBundleEventListenerOrderStatusChange
    TrackingDoctrineListener_0000000000e83129000000005c3397c6257cf4332315f2adc8
    0479a9d1836499, because the name is already in use
```

The service in question:

```yml
app.listener.order_status_change_tracking_doctrine:
    class: 'AppBundle\EventListener\OrderStatusChangeTrackingDoctrineListener'
    lazy: true
    tags:
        - name: 'doctrine.event_listener'
          event: 'onFlush'
          priority: 100
```

Along with other Doctrine event listeners and subscribers: https://gist.github.com/teohhanhui/3628c086ad277897f7ce6aafdb25aad1
