### ISSUE TITLE
[Yaml] Multiline line return

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#18784]
If you have a YAML file with the following content:

```yaml
username: |
    Bob
```

The parsed result will be:

```php
[
  "username" => "Bob\n"
]
```

Which is expected. If you use instead:

```yaml
username: |-
    Bob
```

The result will be:

```php
[
  "username" => "Bob"
]
```

Up to that point, no problem. Now if I have:

```yaml
User:
    foo:
        username: |
            Bob
    bar:
        username: |
            Bob
        group: ~
```

I would expect:

```php
[
  "User" => [
    "foo" => [
      "username" => "Bob\n"
    ],
    "bar" => [
      "username" => "Bob\n",
      "group" => null,
    ],
  ]
]
```

But instead, of having `"Bob\n"` for `"foo"`, I get `"Bob"` instead.

I'm not sure if it's the expected behaviour, but looks odd to me. Bug reproduced [here](https://github.com/theofidry/demo-yaml-bug). Tested on the the version `v3.0.6`.
