### ISSUE TITLE
[RFC][Ldap][Security] Use of LDAP-based storage for RBAC

### ISSUE THREAD

**Issue by csarrazi** [symfony/symfony#18803]
Currently, the Ldap user provider is only able to fetch basic user information.

In the medium/long term (Symfony 3.2+), we want to be able to support user roles (Role-Based Access Control – RBAC) stored in an LDAP server.

We definitely want to do this using a standard way, in order to be able to integrate with popular LDAP-based identity providers.

This issue will be used in order to track the discussion about the future implementation, and the improvement which need to be done to the `LdapUserProvider`.

**Comment by iltar** [comment]
I would love to see a RoleProvider implementation for this. The part that provides the ldap roles could be created in a generic fashion, but it could also simply be a database role provider:

```yml
security:
    firewalls:

        # default ldap provider
        secured_area:
            role_provider: ldap.role_provider

        # default database provider
        secured_area:
            role_provider: dbal.role_provider

        # or maybe chain them 
        secured_area:
            role_provider: app.my_chained_role_provider
```

Just like my PR with user-checkers, this is one of the limitations I hit when writing my application's security.

**Comment by csarrazi** [comment]
The idea is not bad, but the main issue is that the roles should actually be fetched using the UserProvider. As roles are tied to users, I don't think it makes sense to actually have the `role_provider` in the `firewalls` section. And having different roles depending on the section of the site you're in seems awkward for me. Whenever that's the case, you would actually also go for a different user provider.

So instead of the `firewalls` section, I actually put the config for this in the provider section.

**Comment by csarrazi** [comment]
However, this is not the main topic here. First and foremost, we need to identify which standard RBAC strategies exist within LDAP implementations, which will be a start.

**Comment by Adirelle** [comment]
I am not sure there are many RBAC strategies in LDAP. However, they are group membership schemas:
* OpenLDAP core: groupOfNames objectClass + member attribute,
* OpenLDAP NIS: posixGroup objectClass + memberUid attribute,
* Active Directory : memberOf attribute.

**Comment by csarrazi** [comment]
Actually, there are quite a few papers about this.

See
* http://profsandhu.com/journals/tissec/ANSI+INCITS+359-2004.pdf
* http://csrc.nist.gov/groups/SNS/rbac/documents/sandhu-ferraiolo-kuhn-00.pdf
* http://csrc.nist.gov/groups/SNS/rbac/documents/sandhu96.pdf

Regardless, as strategies are different for different implementations, it means that we need at least 4 different implementations for fetching roles from an LDAP server:
* OpenLdap core
* OpenLDAP NIS
* Active Directory
* Third-party storage

I don't really think this would be helpful for other user providers. I mean, what is the actual chance that you need to fetch roles from a third-party storage if you're already using a database (entity, propel) for managing your users? Maybe in the case where you are using web services to authenticate, but these would actually return the correct information in the user endpoint (`/me` or `/users/123abc`, for example).

**Comment by Adirelle** [comment]
@csarrazi These documents seem very theorical. Do they provide any LDAP schema nor implementation ?

**Comment by csarrazi** [comment]
There are actually quite a few. It is actually the case for some Oracle products (Management Services, for example), Apache Fortress, and a few others.

**Comment by ChadSikorra** [comment]
I think in the vast majority of cases you really only need some way of mapping LDAP group membership to roles, as mentioned by @Adirelle. The way I have handled this in an LDAP bundle I have is to map role names to specific group names in the config such as:

```
ldap
    security:
        roles:
            SUPER_ADMIN: [ 'Domain Admins' ]
            ROLE_APP_USER: [ 'Network Team', 'HelpDesk' ]
```
Then the user provider retrieves all of the user's groups recursively (if possible -- easier to do in AD), and checks what roles they map to.

Then there would also need to be a config option to map the group membership attribute for the query in the user provider. Currently there is already a config option for mapping both the UID and password attributes.

Anyway, just my two cents on this.

**Comment by Adirelle** [comment]
You'd better use group DNs than just their names.

**Comment by ChadSikorra** [comment]
Good point, a name can be duplicated in the domain. Though that is highly confusing to begin with. A name itself is easier/more flexible, but I see the security perspective you're getting at.

**Comment by ofbeaton** [comment]
Before it stopped working with Symfony 2.8, I was using https://github.com/BorisMorel/LdapBundle

in `security.yml`
```
security:
  providers:
    ldap:
      id: imag_ldap.security.user.provider

imag_ldap:
  client:
    host: your.host.foo
    port: 389
#    version: 3 # Optional
#    username: foo # Optional
#    password: bar # Optional
#    network_timeout: 10 # Optional
#    referrals_enabled: true # Optional
#    bind_username_before: true # Optional
#    skip_roles: false # Optional

  user:
    base_dn: ou=people,dc=host,dc=foo
#    filter: (&(foo=bar)(ObjectClass=Person)) #Optional
    name_attribute: uid
  role:
    base_dn: ou=group, dc=host, dc=foo
#    filter: (ou=group) #Optional
    name_attribute: cn
    user_attribute: member
    user_id: [ dn or username ]

#  user_class: IMAG\LdapBundle\User\LdapUser # Optiona
```

This allowed me to import my Active Directory groups and use them directly in my firewall, without even needing to map them to existing manually defined roles. They just got a `ROLE_` prefix.

Here was my config `security.yml` for example:
```
security:
  providers:
    ldap:
      id: imag_ldap.security.user.provider
  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_MY_AD_GROUP }

imag_ldap:
  client:
    host: ldaps://myldapserver.mydomain.com
    port: 636
    version: 3
    username: cn=myreadonlyuser,cn=Users,dc=mydomain,dc=com
    password: mypassword
    referrals_enabled: 0
  user:
    base_dn: dc=mydomain,dc=com
    name_attribute: sAMAccountName
  role:
    base_dn: dc=mydomain,dc=com
    user_attribute: member
    user_id: dn
```

Worked great until 2.8 broke the bundle, which is no longer maintained. With the new LDAP component in Symfony 3.1 I am just not authenticated against groups at all right now.

Would love to be able to do this again.Is there any plans to get this in for 3.2?
