### ISSUE TITLE
Symfony 2.8.* - assetic:dump non-existent parameter bug

### ISSUE THREAD

**Issue by ok2uec** [symfony/symfony#18921]
Hi, I have a problem

In the whole path I have small and normal works, but when you start assetic: dump pops up error.

```
martin@martin:/data/www/xxx$ php app/console assetic:dump --env=prod
                                                                         
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  You have requested a non-existent parameter "filepath.uploadavatarweb".
```

Originally the name was filePath.uploadAvatarWebFile, but I changed it into small letters because I thought that the new Symfony 2.8 has been modified. But no changes..

```
martin@martin:/data/www/datalife$ php app/console assets:install --symlink
 Trying to install assets as absolute symbolic links.                                                                                                         
 [OK] All assets were successfully installed.      
``` 

and go to website over browser is functionality OK.  

CONFIG:
```
 /data/www/xxx/app/config/filePath_dev.yml
parameters: 
    filepath.uploadavatar: upload/profile
    filepath.uploadavatarweb: http://localhost/xxx/web/app_dev.php/upload/profile
```

```
/data/www/xxx/app/config/filePath.yml
twig: 
    globals:
        filepath:
            uploadavatarweb: "%filepath.uploadavatarweb%"

```
```
/data/www/xxx/app/config/config.yml
imports:
    - { resource: parameters.yml } 
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: assets.yml }
    - { resource: global.yml }
    - { resource: global_twig.yml }
    - { resource: filePath.yml }
    - { resource: certificate.yml }
```

Thanks for the info.
Martin
