### ISSUE TITLE
Array GET parameter not rendered properly using {{ url() }}

### ISSUE THREAD

**Issue by xDaizu** [symfony/symfony#18929]
I have this route defined:

```yaml
ajax_list_people:
    path:     /AJAX/list/
    defaults: { _controller: LicensePersonBundle:AJAX:listPeople, organizational_groups: all, output: json }

```

where organizational_groups can be a string or an array of strings.

But when I render the route using:

```twig
{{ url('ajax_list_people', {"organizational_group":["no_group", "student"]}) }}
```

I get:

```
http://acme.license.com/app_dev.php/AJAX/list/?organizational_group[0]=no_group&amp;organizational_group[1]=student
```

which, of course, get interpreted back at the server as:

```twig
{"organizational_group": "no_group", "amp;organizational_group": {"1": "student"} }
```

which is not the expected result, expected:

```twig
{"organizational_group": ["no_group", "student"] }
```

which is what I get if I use this other route:

```yaml
ajax_list_student:
    path:     /AJAX/list/students
    defaults: { _controller: LicensePersonBundle:AJAX:listPeople, organizational_groups: [student, no_group], output: json }
```
