### ISSUE TITLE
Using useAttributeAsKey causes differences in config on test environment

### ISSUE THREAD

**Issue by matigda** [symfony/symfony#18988]
When passing to 'useAttributeAsKey' function key that is not used in below config, in the test environment the side effect is that $config in [Bundle]Extension.php contains settings only for this env. When this method is not being used at all, the $config contains config for each env.

**Bundle\DependencyInjection\Configuration::getConfigTreeBuilder():**

```
$root->children()
            ->arrayNode('some_config')
                ->prototype('array')
                    ->children()
                        ->scalarNode('some_key')->end()
                    ->end()
                ->end()
            ->end()
        ->end();
```

**config_dev:**

```

my_app:
    some_config:
        Option1:
            some_key: yyyy
        Option2:
            some_key: xxx
```

**config_test:**

```

my_app:
    some_config:
        Option1:
            some_key: aaaaa
        Option2:
            some_key: bbbbb
```

**Bundle\DependencyInjection\BundleExtension::load():**

```
....

var_dump($config['some_config'])
....
```
## Expected result on test env:

```
array (size=2)
        Option1 =>
            some_key: aaaaa
        Option2 =>
            some_key: bbbbb

```
## Actual result:

```
array (size=4)
        Option1 =>
            some_key: yyyy
        Option2 =>
            some_key: xxx
        0 =>
            some_key: aaaaa
        1 =>
            some_key: bbbbb
```
## How to fix that?

**Bundle\DependencyInjection\Configuration::getConfigTreeBuilder():**

```
$root->children()
            ->arrayNode('some_config')
            ->useAttributeAsKey('some_not_existing_key_to_prevent_associative_array_in_different_env_SYMFONY_BUG')
                ->prototype('array')
                    ->children()
                        ->scalarNode('some_key')->end()
                    ->end()
                ->end()
            ->end()
        ->end();
```

Then:

**Bundle\DependencyInjection\BundleExtension::load():**

```
....
var_dump($config['some_config'])
....
```
## Actual result on test env after fixing:

```
array (size=2)
        Option1 =>
            some_key: aaaaa
        Option2 =>
            some_key: bbbbb
```

But I don't think it's a proper behaviour.
