### ISSUE TITLE
Incorrect encoding of cyrillic characters in route parameters with IIS 10

### ISSUE THREAD

**Issue by pyatnitsev** [symfony/symfony#18985]
Hi!
I created question at stackoverflow http://stackoverflow.com/questions/37618164/how-to-use-cyrillic-characters-in-route-parameters-without-transliteration and now I think, that it's bug in symfony. 

I have route:

``` yaml
group_content:
path:     /{name}/{subgroup}
defaults: { _controller: "AppBundle:Group:showSchedule", subgroup: 1 }
methods:  [ GET ]
requirements:
      name: ".+"
```

and next controller's method:

``` php
public function showScheduleAction($name, $subgroup)
{
    dump($name); 
    // other unimportant code goes here
}
```

I pass 'тест' as name parameter and dump shows me next:

![z74xf 1](https://cloud.githubusercontent.com/assets/4361764/15846457/2a41e672-2c9f-11e6-90ca-f53fba4cafb8.png)

this issue related only for Windows + IIS, in Linux with Apache symfony works well.
