### ISSUE TITLE
Yaml::dump() needs more flexibility with inlining levels

### ISSUE THREAD

**Issue by joachim-n** [symfony/symfony#19014]
I'd like to be able to generate something like this with Yaml::dump():

```yaml
services:
  node.route_subscriber:
    class: Drupal\node\Routing\RouteSubscriber
    tags:
      - { name: event_subscriber }
  node.grant_storage:
    class: Drupal\node\NodeGrantDatabaseStorage
    arguments: ['@database', '@module_handler', '@language_manager']
    tags:
      - { name: backend_overridable }
```

However, it seems to me that the 'arguments' and 'tags' properties are inlining at different levels.
