### ISSUE TITLE
SecurityBundle debug.security.access.decision_manager missing in collectors.xml when kernel.debug false

### ISSUE THREAD

**Issue by msarris** [symfony/symfony#19022]
Service "debug.security.access.decision_manager" is defined in file security_debug.xml (in SecurityBundle) which is only loaded when kernel.debug is true. However, this service is also used in collectors.xml, which is always loaded.

In env=prod this will give the following error:

 [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                       
      The service "profiler" has a dependency on a non-existent service "debug.security.access.decision_manager".

This issue was introduced in Symfony 3.1. I temp fixed it by overriding the service and removing the argument.

**Comment by javiereguiluz** [comment]
@msarris thanks for reporting this error. We are trying to fix it in #18934.

**Comment by iquito** [comment]
Would be great if this would be fixed soon - cache:clear in my application does not work correctly anymore because of this bug and is leading to a lot of problems.

**Comment by st0at** [comment]
Hello everyone,
So what is the solution? I'm still getting errors when running phpunit.

**Comment by msarris** [comment]
@st0at I think the fix will be released in 3.1.2.

My temporary fix is to add this definition to app/config/services.yml (which just removed the last argument):

```
    data_collector.security:
        class: Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector
        public: false
        tags:
            - {name: data_collector, template: "@Security/Collector/security.html.twig", id: "security", priority: 270}
        arguments:
            - "@security.token_storage"
            - "@security.role_hierarchy"
            - "@security.logout_url_generator"
```
