### ISSUE TITLE
PR #19048 breaks PDO backed session storage on PGSQL 9.5

### ISSUE THREAD

**Issue by aashley** [symfony/symfony#19057]
Testing the upgrade from Symfony 3.0 to 3.1 with our code base that uses the session.handler.pdo with the stock config as recommended by http://symfony.com/doc/current/cookbook/doctrine/pdo_session_storage.html.

Our config snippets:
```
framework:
    session:
        handler_id:  session.handler.pdo
services:
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public: false
        arguments:
            - 'pgsql:host=%database_host%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%' }

```

When attempting to resume an existing session get the follow error:
SQLSTATE[42702]: Ambiguous column: 7 ERROR: column reference "sess_id" is ambiguous
LINE 1: ...a, sess_lifetime, sess_time) = ($2, $3, $4) WHERE sess_id = ...

triggered by line 336 in vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php

This is using the Ubuntu 16.04 package postgresql-9.5 package version 9.5.3-0ubuntu0.16.04, with php 7.0.7-4+deb.sury.org~xenial+1.
