### ISSUE TITLE
Doctrine schema update filter problem

### ISSUE THREAD

**Issue by PlamenVasilev** [symfony/symfony#19076]
I have a problem with excluding table from schema with symfony 2.8.5

According to this http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#manual-tables
I can exclude tables form schema diff and ignore them

When I set this filter to specific table 

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                schema_filter: ~^(?!table_name)~
```

and then run `php app/console doctrine:schema:update --dump-sql`

I see SQL for creation of the excluded table.
When I comment the schema_filter .. no DB changes will be made.

This option should not produce create/alter/drop statements for excluded tables or I'm wrong?

**Comment by sawmurai** [comment]
Just an idea after browsing the linked documentation: 

``` yaml
doctrine:
   dbal:
      schema_filter: ~^(?!table_name)~
```
