### ISSUE TITLE
Support ControllerNameParser Extension

### ISSUE THREAD

**Issue by coryjamesfisher** [symfony/symfony#19340]
When migrating from a custom MVC framework to Symfony there is a challenge in that the controller & action postfixes in the Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser class are hard coded to 'Controller' and 'Action' respectively. I would like to modify these to be static members of the class so that they can be overridden. This would allow easier migration from homebrewed MVCs that use different URL -> Controller+Action routing patterns.

**Comment by WouterJ** [comment]
You can just use the FQCN + method name in your routing:

```yaml
homepage:
    path: /
    defaults: { _controller: AppBundle\Controller\Static::homeController }
```
