### ISSUE TITLE
Double validation for constraints on Interface

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#19516]
Hi !

I have this kind of code :
```php
interface FooInterface {}
abstract class AbstractBar implements FooInterface{}
class Baz extends AbstractBar {}

$object = new Baz();
$validator->validate($object, null, ['validator_group']);
```
If i create a constraints validator on AbstractBar, like this :
```yml
AbstractBar:
    constraints:
        - MyConstraint:
            groups: [validator_group]
```
MyConstraint is called once.

But if i just change AbstractBar by FooInterface in config :
```yml
FooInterface:
    constraints:
        - MyConstraint:
            groups: [validator_group]
```
MyConstraint is called twice !

I can't search why for now, someone could do it please ?
