### ISSUE TITLE
[YAML] Arrays of objects fail to parse when separated by empty line

### ISSUE THREAD

**Issue by kleijnweb** [symfony/symfony#19600]
```yaml
parameters:
- name: id
  type: string

- name: user
  in: body
```

> Symfony\Component\Yaml\Exception\ParseException: You cannot define a sequence item when in a mapping at line 5 (near "- name: user")

Without the space between the two array items, it parses fine. Also parses when I indent the empty line with 2 spaces.

In 3.1.3 *and* master.

**Comment by jameshalsall** [comment]
Shouldn't they be indented by 2 or 4 spaces?

**Comment by kleijnweb** [comment]
Not per se. The issue, as the error describes, is that the parser thinks the current context is an object node, when it should still be the same array as the previous item was declared in. An empty line should not affect that.

**Comment by jameshalsall** [comment]
An empty line doesn't affect that, both of the following work fine for me and evaluate to the same:

```yaml
something:
      - foo: 1
        bar: 1

      - foo: 2
        bar: 2
```

```yaml
something:
      - foo: 1
        bar: 1
      - foo: 2
        bar: 2
```

However if I don't indent my properties then I get an exception in the file loader due to bad YAML.
