### ISSUE TITLE
group_sequence_provider not working if parent validation_groups setted

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#19613]
example:

Class **Article** has oneToMany **Tag**
Class **Tag** is implementing GroupSequenceProviderInterface and function **getGroupSequence** still return ['validate_if_id']
in ArticleForm there is form 'tags' with type CollectionType

``` yaml
validation:

    Article:
        properties:
            - tags:
                - Valid:  ~

    Tag:
        group_sequence_provider: true
        properties:
            value:
                - NotBlank:
                    groups: [validate_if_id]
```

When I set option validation_groups to **['whatever']** while building ArticleForm, then "group_sequence_provider" will **not be called**

When I set option validation_groups to **[]** while building ArticleForm, then "group_sequence_provider" **will be called**
