### ISSUE TITLE
[Yaml] Missing new line break at the end of folded style

### ISSUE THREAD

**Issue by TiMESPLiNTER** [symfony/symfony#19670]
A folded style block should always have a line break at the end (as long as there is no [chomping operator](http://yaml.org/spec/1.2/spec.html#id2794534) set like `>-`). So the follwong folded style block in YAML:

``` yaml
service:
    user_provider: user_provider
    options:
        supported_scopes: >
            user_basic_information
            internal
db_driver: orm
```

should (according to the YAML lang spec) end up in:

```
user_basic_information internal

```

(with a line break at the end)

but actually ends up in:

```
user_basic_information internal
```

(without line break at the end)
