### ISSUE TITLE
EntityType with manytoMany does not call setters

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#19698]
Hi !

I have 2 entities, Site and Tag, linked with a multidirectional manyToMany. Site is the owning side, tag is the inverse side :
```php
<?php
namespace Foo\Bar\Entity;
class Site
{
    protected $tags;
    public function setTags(Collection $tags)
    {
        var_dump(__FUNCTION__);
        exit();
    }
}
```

```yml
Foo\Bar\Entity\Site:
    type: entity
    table: site

    manyToMany:
        tags:
            targetEntity: Foo\Bar\Entity\Tag
            inversedBy: sites
            joinTable:
                name: sites_tags
                joinColumns:
                    site_id:
                        nullable: false
                inverseJoinColumns:
                    tag_id:
                        nullable: false
```
```php
<?php
namespace Foo\Bar\Entity;
class Tag
{
    protected $sites;
    public function setSites(Collection $sites)
    {
        var_dump(__FUNCTION__);
        exit();
    }
}
```

```yml
Foo\Bar\Entity\Tag:
    type: entity
    table: tag

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            options: { unsigned: true }

    manyToMany:
        sites:
            targetEntity: Foo\Bar\Entity\Site
            mappedBy: tags
```

I have a simple FomType, like this one :
```php
<?php
class TagType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('sites', EntityType::class, [
            'class' => Site::class,
            'choice_label' => 'name',
            'label' => 'form.sites.label',
            'multiple' => true,
            'query_builder' => function() {...}
        ]);
    }
}
```

When i call
```php
$this->createForm(new TagType(), $entity)->handleRequest($request)
```
Tag::setSites() is not called.
But in FormEvents::POST_SUBMIT event, i have selected Site in Tag.

Problem : as Tag is not the owning side of the relation, linked Site are not saved in database when i flush.

If i have almost same FormType, but from Site to Tag (class SiteType, 'class' => Tag::class, etc), same : Site::setTags() is not called, but as Site is the owning side, linked Site / Tag are saved.

Why Site::setTags() and Tag::setSites() are not called ?
