### ISSUE TITLE
 Circular reference detected for service "doctrine.dbal.default_connection", path: "doctrine.dbal.default_connection". 

### ISSUE THREAD

**Issue by happynessTony** [symfony/symfony#19783]
```yaml
#service.yml
app.resource_upload_listener:
   class: AppBundle\EventListener\ResourceUploadListener
   arguments: ['@app.resource.service']
   tags:
       - {name: doctrine.event_listener, event: prePersist}
       - {name: doctrine.event_listener, event: preUpdate}
```

```php
#listener
    private $uploader;

    public function __construct(ResourceService $uploader)
    {
        $this->uploader = $uploader;
    }

    public function prePersist(LifecycleEventArgs $args){

        $entity = $args->getEntity();
        $this->uploadFile($entity);
    }

    public function preUpdate(PreUpdateEventArgs $args)
    {
        $entity = $args->getEntity();

        $this->uploadFile($entity);
    }

    private function uploadFile($entity)
    {
        $file = $entity->getBrochure();

        if(!$file instanceof UploadedFile){

            return;
        }

        $fileName = $this->uploader->upload($file);

        $entity->setBrochure($fileName);
    }
```

I use the event listener to cooperate the upload file, But when start the web server , it thrown an error:  Circular reference detected for service "doctrine.dbal.default_connection", path: "doctrine.dbal.default_connection". 

Help
