### ISSUE TITLE
built-in webserver should stream logs sent to error_log

### ISSUE THREAD

**Issue by marfillaster** [symfony/symfony#19787]
If using this configuration
```
monolog:
    handlers:
        main:
            type:   error_log
            level:  debug
```
