### ISSUE TITLE
Process setTty does not test for device existence

### ISSUE THREAD

**Issue by marfillaster** [symfony/symfony#19792]
```
[Symfony\Component\Debug\Exception\ContextErrorException]                       
Warning: proc_open(/dev/tty): failed to open stream: No such device or address 
```

Caught this when I was running the builtin webserver in docker and have not enabled tty. 
To replicate run `server:run -v` against 7cc6161

``` bash
cd project
PROJECT_ROOT=./ docker-compose up dev
```

``` yaml
# docker-compose.yml
version: '2'
services:
  dev:
    build: .
    command: bash -c "php composer.phar install -o --prefer-dist && app/console -v server:run 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - $PROJECT_ROOT:/code
#    tty: true
```

```
# Dockerfile
FROM php:5.6-fpm

RUN apt-get update && apt-get install -y \
    git libicu-dev zlib1g-dev libxslt-dev --no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql intl zip xsl pcntl && \
    pecl install apcu-4.0.11 &&  \
    docker-php-ext-enable apcu

RUN echo "date.timezone = Asia/Manila" >> /usr/local/etc/php/php.ini

WORKDIR /code
```
