### ISSUE TITLE
Add an alias to a service

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#19832]
As of now, the declaration of an alias is done like so:

```yaml
services:
   app.phpmailer:
     class: AppBundle\Mail\PhpMailer

   app.mailer:
     alias: app.phpmailer
```

([example taken from the doc](http://symfony.com/doc/current/service_container/alias_private.html#aliasing)).

This means you needs to register *two* services definitions. IMO this is unnecessary and could be done in one service declaration:

```yaml
services:
   app.phpmailer:
     alias: app.phpmail
     class: AppBundle\Mail\PhpMailer
```

Now because of the BC promise and because it would change the current behaviour, another key than `alias` should be found for that (`aliases` that could be an array to register several aliases at once?), but I find it more intuitive than having the two service declarations and I think this can be the source of confusion as you may think of `alias` as "this service has this alias" and not "this service is an alias declaration". I've recently seen two peoples tricked by that realising it only because of the recent deprecation notices and I remember being confused by it at first as well when I started Symfony.

WDYT?

**Comment by ogizanagi** [comment]
Did you mean:

```diff
services:
   app.phpmailer:
-     alias: app.phpmailer
+     alias: app.mailer
     class: AppBundle\Mail\PhpMailer
```

?

If so, I think it'll be really confusing, as the `alias`/`aliases` key will behaves differently. So as you said, we could try to think about another key name. But I don't really feel this need, considering you've got a more readable yaml annotation for aliases:

```yml
services:
   app.phpmailer:
     class: AppBundle\Mail\PhpMailer

    app.mailer: '@app.phpmailer' # Creates a "app.mailer" alias of the "app.phpmailer" service
```

I do agree the current notation can be tricky for newcomers, though.

**Comment by theofidry** [comment]
@ogizanagi yeah my bad.

Yeah it's a pity but after sleeping on it I don't think it would be a good idea either to create a new key for it. That said I believe the current message is far from being clear: you only get a deprecation warning saying additional properties to the alias are deprecated. It doesn't tell you why or points you to anything, for someone how misunderstood what the alias key is in Symfony will only get even more confused.

**Comment by Ener-Getick** [comment]
What do you think about using yaml tags for that?
Something like:
```yml
services:
    app.phpmailer: 
        # ...
    
    app.mailer: !alias "app.phpmailer"

    # We could even support a more verbose syntax:
    app.mailer: !alias { id: app.phpmailer, public: false }
```

WDYT?

**Comment by theofidry** [comment]
@Ener-Getick I find the syntax a bit confusing and bear in mind that such usage of alias would be used for more complex services as well:

```yaml
services:
  app.phpmailer:
    class: PhpMailer
    arguments:
      - #...
      - #...
    tags:
      - #...
```

So it doesn't feel like the more verbose syntax would sit well with it.

**Comment by Ener-Getick** [comment]
@theofidry what do you mean? We could support both syntaxes imo.
If we support yaml spec fully, the following should be possible:
```yml
services:
    app.phpmailer: !service
        class: PhpMailer

   app.mailer: !alias
       id: app.phpmailer

**Comment by theofidry** [comment]
Oh I see. Why the `!service` though? in the example above would rather translate to:

```yaml
services:
   app.mailer: !alias
       id: app.phpmailer
        class: PhpMailer
```

As the point was to reduce the number of service to declare.

And how would you translate it in PHP/XML?
