### ISSUE TITLE
[RFC][Yaml] Consider colon not followed by spaces as a value

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#19874]
[According to the spec](http://www.yaml.org/spec/1.2/spec.html#ns-plain-char%28c%29), colon not followed by flow indicators (`[]{},`) should be considered as part of the key and not throw an exception which is gonna be the 4.0 behavior [according to the deprecation](https://symfony.com/blog/new-in-symfony-3-2-yaml-deprecations#deprecated-missing-spaces-after-map-keys).

For example, `foo:{foo:bar}` should be valid but it won't be in the current state.

BTW we can also consider fixing other inconsistensies:
- `[]` is allowed in sf mapping values but not in the spec `{fo[o: bar}`
- `{}` is allowed in sf sequence values but not in the spec `[fo{o}: quz]`
- mapping values not followed by `:` (i.e. `{value}`) is allowed and should be converted to `{value: null}` (i fixed this one in https://github.com/symfony/symfony/pull/19750, in https://github.com/symfony/symfony/pull/19750/commits/51b87f7a3a103ee8e8e0be3d767394c20ef476ff)

WDYT?

cc @xabbuh

**Comment by xabbuh** [comment]
The first example you gave (`foo:{foo:bar}`) will correctly be parsed as a string.

For the other examples you are right and we should look into how we can improve the parser to detect these edge cases.

**Comment by Ener-Getick** [comment]
What about `{foo:{bar}}`? The inner mapping should be parsed correctly but according to the deprecation, it will throw an exception.

**Comment by mvrhov** [comment]
BTW the pomm bundle uses this 

```yaml
pomm:
    configuration:
        my_db1:
            dsn: 'pgsql://%db_user1%:%db_password1%@%db_host1%:%db_port1%/%db_name1%'
            pomm:default: true
        my_db2:
            dsn: 'pgsql://%db_user2%:%db_password2%@%db_host2%:%db_port2%/%db_name2%'
            class:session_builder: '\PommProject\ModelManager\SessionBuilder'
```

so this should stay valid.
