### ISSUE TITLE
[Security] access_control host option can't be trusted?

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#19907]
There's a few options to match the `access_control` rule and host is one of them: http://symfony.com/doc/current/security/access_control.html#matching-options

This all looks fine but it gives the impression you can grant or deny access by matching the host. Sadly this value can be spoofed and doesn't do a reverse dns lookup (which would probably slow everything down by a lot).

While matching on host can be nice, especially for routing, I don't think this has any place in the `access_control` as it can lead to security issues.

_**Case:**_ I had a page which should've only been visible from the internal network. Someone added `ROLE_NO_ACCESS` unless a certain host was matched. Example from the docs (with host instead of IP):

``` yml
# app/config/security.yml
security:
    # ...
    access_control:
        #
        - { path: ^/internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: some-internal-domain\.com }
        - { path: ^/internal, roles: ROLE_NO_ACCESS }
```

This looks secure and would mean you don't have to work with IPs (as they can change in theory). The problem comes when you have this on a public website (think of liip monitor bundle for example). While it looks safe, with a simple hostname spoof, you're in. I don't think this option should be in the `access_control` as is (and possibly not even the firewall).

_Or am I mistaken and did I miss something?_

**Comment by sstok** [comment]
If the hostname is only internal (accessible from the local network) it should be possible to use an IP restriction like `allow_if: "'request.getClientIp() matches '^192\.168\.'"`.

But I agree there should a be warning about this use-case.

**Comment by iltar** [comment]
If the host option cannot be trusted, then it should either be removed or verify if the hostname matches the IP.

**Comment by patrick-mcdougle** [comment]
I think this feature is more for granting/denying access based on the REQUESTED host that comes in via headers. It's for specifying different access rules based on the domain. For example if your international site had some reason for adding roles based on TLD. Anything on the hostname.fr domain would get a FRENCH_USER role or something. This option/config is less about trusting the host that comes in, but making decisions based on the host passed from the request. Perhaps a documentation update?

**Comment by iltar** [comment]
That sounds like identification and not authorisation. That means that it should be done via the firewall.

**Comment by sstok** [comment]
@iltar well yes and no, when you have access_roles for one firewall, you don't want to match those for other firewalls.

```yaml
security:
    # ...
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN, host: admin.example.com }
        - { path: ^/, roles: ROLE_USER, host: example.com }
```

But there should a warning about using a hostname to GRANT access to a specific uri.
