### ISSUE TITLE
[Workflow][question] multiple markings?

### ISSUE THREAD

**Issue by karser** [symfony/symfony#19936]
Is that possible to specify marking field name in `workflow.yml` or any other way in order to have many marking fields? e.g:
```
    workflows:
        my_workflow:
            marking_store:
                field: marking
                type: property_accessor
            supports: ~
            places: ~
            transitions: ~
```
I see that it's supposed to specify marking field name in [PropertyAccessorMarkingStore constructor](https://github.com/symfony/workflow/blob/master/MarkingStore/PropertyAccessorMarkingStore.php#L34) but there is no such info in the Workflow documentation.
```
public function __construct($property = 'marking', ...)
```

**Comment by Sigzegv** [comment]
I also need a way to specify a custom marking field name, model is not supposed to suit workflow's component requirements.

**Comment by stof** [comment]
the PropertyAccessorMarkingStore expects to have a property path allowing to access an array for the marking (this can be a public property containing an array or a getter returning an array).

If you don't want to have a method returning such array in your model, you would need to build your own implementation of the MarkingStoreInterface building the mapping from several sources

**Comment by stof** [comment]
Configuring the arguments of the builtin marking store is possible though:

```yaml
framework:
    workflows:
        my_workflow:
            marking_store:
                type: property_accessor
                arguments:
                    - marking # first arg is the property path
            supports: ~
            places: ~
            transitions: ~
```
