### ISSUE TITLE
[Validator] Double validation when an interface extends another

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#19943]
I have this kind of code : 

classes
```php
interface PriceInterface {}
interface VariablePriceInterface extends PriceInterface {}
class ProductPrice implements VariablePriceInterface {}
```

validation
```yaml
PriceInterface:
    constraints:
        - MyConstraint: ~
```

If I validate a `ProductPrice` object, `MyConstraint` is checked twice.

This is very similar to https://github.com/symfony/symfony/issues/19516.
