### ISSUE TITLE
Invalid password in RedisAdapter

### ISSUE THREAD

**Issue by ErikSaunier** [symfony/symfony#20025]
Symfony 3.1

When I use my proper cache backend such as Redis in the **Cache component** and provide a `default_redis_provider` like as below, the **password** use to establish the connection is wrong :

````
# app/config/config_prod.yml
framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: "redis://e:password@ec2-23-217-18-82.eu-west-1.compute.amazonaws.com:21039"
````

`e:password` is used as the password insteed of `password`.
