### ISSUE TITLE
[DX] Make the user providers configuration more concise

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20046]
### Problem

I've always found that the `security.providers` configuration is a bit verbose.

### Solution

Let's make the configuration more concise. Proposal:

#### Before

```yaml
security:
    providers:
        administrators:
            memory:
                users:
                    ryan: { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
        users:
            entity:
                class: AppBundle\Entity\User
                property: email
```

#### After

```yaml
security:
    providers:
        administrators:
            ryan: { password: ryanpass, roles: 'ROLE_USER' }
            admin: { password: kitten, roles: 'ROLE_ADMIN' }
        users:
            entity: AppBundle\Entity\User
            property: email
```

**Comment by wouterj** [comment]
👎 there is no way to see which user provider is configured here.

**Comment by javiereguiluz** [comment]
@wouterj are you saying that a human cannot know which type of user provider the config is using ... or that Symfony cannot unequivocally know which user provider type you are using in each case?

**Comment by wouterj** [comment]
Well, yeah, I don't see how we can do the implementation of this request (as user providers need to have unique sets of settings and we loose setting validation by the Config component). But the core team + sf contributors have always surprised me with nice implementations, so I don't worry about this that much.

However, it also creates confusion for the humans. It's no longer clear by looking at the config that the `administrators` are using the built-in in_memory provider and `users` are using the built in entity provider.

**Comment by iltar** [comment]
This will become confusing if you ask me. Every key that does not get matched with a configured provider, would become a dynamic provider. Not impossible to make, but not sure if it's not confusing at all. Not sure if anything other than "users" is ever used here so why not make it something like this:

```yml
security:
    providers:
        memory: # would become a pre-defined option and the sub key of users is not needed
            ryan: { password: ryanpass, roles: 'ROLE_USER' }
            admin: { password: kitten, roles: 'ROLE_ADMIN' }
        users:
            entity:
                class: AppBundle\Entity\User
                property: email
```
The only times I've really used this is for applications and http-basic auth between them (small apis within websites). While I think it's nice to always work on DX, I'm not entirely sure this is a feature that should be used too often in the first place due to how passwords need to be defined.

**Comment by ro0NL** [comment]
I'd say `admins.memory.users` could become `admins.memory` as `users` is the only property available anyway, however it allows for future optimizations. And im not sure BC allows this change...

Personally i'd prefer the config structure representing the object graph more or less.

**Comment by backbone87** [comment]
what about

```yaml
security:
    providers:
        administrators:
            type: memory #or class: MemoryProvider
            users:
                ryan: { password: ryanpass, roles: 'ROLE_USER' }
                admin: { password: kitten, roles: 'ROLE_ADMIN' }
        users:
            type: entity #or class: EntityProvider
            class: AppBundle\Entity\User
            property: email
```
