### ISSUE TITLE
[RFC][DI] extend definition "inheritance" (parent) with definition "traits"?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#20050]
Just saw this in Drupal8:

``` yaml
container.trait:
   abstract: true
   calls:
     - [setContainer, ['@service_container']]
```

Then they reuse this "trait" by using "parent", e.g.:

``` yaml
  update.post_update_registry_factory:
    class: Drupal\Core\Update\UpdateRegistryFactory
    parent: container.trait
```

This looks nice, yet a definition can only have one "parent", but why shouldn't we allow more, calling this "trait"? e.g. have "logger.trait" and "container.trait" and reuse the corresponding definition trait to create new ones?

I dunno how this could effectively work nor be implemented, so if someone wants to give it a try, please do :)
