### ISSUE TITLE
When will symfony resolve "@" as an object ? 

### ISSUE THREAD

**Issue by videni** [symfony/symfony#20098]
We used "@" to  presents a service in config.yml  a lot, but when "@" will be resolved an object? 
```
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: "FOS\\RestBundle\\Controller\\ExceptionController::showAction"
    globals:
         shopperContext: "@sylius.context.shopper"
````

I ask this question is because I got a thought that everything starts with @ would be treats as service , but when try to debug it , it is simply a string.
```
payum:
    gateways:
       test_gateway:
          factory: wechat_pay_js
          payum.http_client: @guzzle_http.client
          options_resolver: @acme.options_resolver  
```

```
//$config['options_resolver'] is "@acme.options_resolver "
 if ($config['options_resolver'] instanceof OptionsResolverInterface) { 
}
```

**Comment by iltar** [comment]
`@service` is nothing more than a way of saying: This is a reference to "service" when building the container. To me it makes no sense to refer to services with an `@` in any other config, simply because it's specific to the `services` part of your config. You can read `@service` as `new Reference('service')` in terms of the services config.

But this is not really an issue for on github, more of a question you could ask on Stack Overflow or on IRC :smile:

**Comment by videni** [comment]
@iltar ,I see , thank you.   putting  a "@"  before a  service name in confyg.yml , which won't be resolved , I have to turn `@acme.options_resolver ` to object myself.

```
payum:
    gateways:
       test_gateway:
          options_resolver: @acme.options_resolver  
```
