### ISSUE TITLE
Multiple connections causing "Circular reference detected for service 'doctrine.dbal.default_connection', path: 'doctrine.dbal.default_connection'"

### ISSUE THREAD

**Issue by VersatilityWerks** [symfony/symfony#20162]
Used the instructions here:
https://symfony.com/doc/current/doctrine/multiple_entity_managers.html

Got this exception:
"Circular reference detected for service 'doctrine.dbal.default_connection', path: 'doctrine.dbal.default_connection'"

This looks like a similar issue from a year ago, but I want to avoid outdated workarounds (and workarounds in general): https://gist.github.com/webdevilopers/c94295b790b3ea5d3043

This error occurs when using multiple connections. The issue seems to be stemming from the auth services.

The part where I'm passing arguments to services (default_entity_manager) used to be 

```yaml
autowire: true
```
I changed it assuming that would fix the problem but it instead caused the circular reference one.

Here's my config.yml
```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
          default:
              driver:   pdo_mysql
              host:     "%database_host%"
              port:     "%database_port%"
              dbname:   "%database_name%"
              user:     "%database_user%"
              password: "%database_password%"
              charset:  UTF8
              # if using pdo_sqlite as your database driver:
              #   1. add the path in parameters.yml
              #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
              #   2. Uncomment database_path in parameters.yml.dist
              #   3. Uncomment next line:
              #     path:     "%database_path%"
          cb911:
              driver:   pdo_mysql
              host:     "%database_host2%"
              port:     "%database_port2%"
              dbname:   "%database_name2%"
              user:     "%database_user2%"
              password: "%database_password2%"
              charset:  UTF8

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: false
                connection: default
                mappings:
                    AppBundle: ~
            cb911:
                auto_mapping: false
                connection: cb911
                mappings:
                    CB911Bundle: ~
```

and here's my services.yml 

```yaml
parameters:

services:
  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator
    arguments: ["@doctrine.orm.default_entity_manager"]

  app.doctrine.hash_password_listener:
    class: AppBundle\Doctrine\HashPasswordListener
    arguments: ["@doctrine.orm.default_entity_manager"]
    tags:
      - { name: doctrine.event_subscriber }
```

**Comment by iltar** [comment]
The problem is that you have a dependency on doctrine and doctrine a dependency on you. Injecting the EM in that hash_password_listener isn't going to work. I think you rather listen to either a security event of successful logging in or (re-)hash the password when it's actually changed (please avoid listeners for this).

**Comment by stof** [comment]
btw, you don't need to inject the entity manager if a Doctrine listener: the event object gives you access to the entity manager already

**Comment by VersatilityWerks** [comment]
To further specify:

If you take out the 2nd connection/entity manager, it still throws that error.

If I put it back to autowire: true with a single db connection, it works fine (as originally architected), but when I add a 2nd db connection, it doesn't know which one to use. That's why I specified in the arguments and removed autowire.

I'm trying to hack together some stuff a coworker grabbed from a tutorial and instructions straight from Symfony's docs, so forgive me if I sound like a complete noob. I've never worked in Symfony before and a lot of these concepts are foreign to me.

**Comment by VersatilityWerks** [comment]
Here's the error when I go back to autowire: true

```php
[Symfony\Component\DependencyInjection\Exception\RuntimeException]             
  Unable to autowire argument of type "Doctrine\ORM\EntityManager" for the serv  
  ice "app.security.login_form_authenticator". Multiple services exist for this  
   class (doctrine.orm.default_entity_manager, doctrine.orm.cb911_entity_manage  
  r).   
```

**Comment by VersatilityWerks** [comment]
So...it works to send that entity manager like this:

```yml

services:
  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator
    arguments:
      ["@doctrine.orm.default_entity_manager"]
```

But now I have to figure out how to send the other parameters that are/were autowired.

Those are:
```php
public function __construct(FormFactoryInterface $formFactory, EntityManager $em, RouterInterface $router, UserPasswordEncoder $passwordEncoder)
```
