### ISSUE TITLE
[Routing][DX] Reusable requirement definitions

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#20176]
Hi,

sorry for the weird title, I couldn't think of anything better.

When writing apps, one frequently has to reuse requirements for route definitions.

Example `routing.yml` when using slugs for identifying clients / users / blog articles in your app:
```yml
client:
    path: /client/{client}/
    requirements:
        client: '[a-z0-9]+'

user:
    path: /user/{user}/
    requirements:
        user: '[a-z0-9]+'

blog_article:
    path: /blog-article/{blogArticle}/
    requirements:
        blogArticle: '[a-z0-9]+'
```

The copy & pasting of the requirements is error prone and tedious.
I would propose to add a feature to define a list of predefined regexes.

*Please note: I would like to keep the discussion on the feature, not (yet) on the actual syntax or where to put these definitions.* 

`config.yml`:
```yml
framework:
    routing:
        requirements:
            id: '\d+'
            slug: '[a-z0-9]+'
```

and in your `routing.yml`:

```yml
client:
    path: /client/{client}/
    requirements:
        client: ':slug:'

user:
    path: /user/{user}/
    requirements:
        user: ':slug:'

blog_article:
    path: /blog-article/{blogArticle}/
    requirements:
        blogArticle: ':slug:'
```

(or something else, not thought about a concrete syntax yet - it mustn't conflict with valid requirements, though)

A bonus would be to expose these predefined requirements in PHP.

Use case:
You want to build a blog with articles that are using slugs. It would be nice to use the route regex in the validator when CRUD-ing the blog articles as well as using the regex in the routing itself.
This way the definitions would always be in sync.

Thoughts?
