### ISSUE TITLE
AddConstraintValidatorsPass - problem with decorated validator

### ISSUE THREAD

**Issue by sgehrig** [symfony/symfony#20195]
In `dev` environment we're using a custom email constraint validator that's being created by decorating the shipped email constraint validator:

```
    app.dev.validator.email:
        class: AppBundle\Validator\DevelopmentEmailValidator
        public: false
        decorates: validator.email
        arguments: ["@app.dev.validator.email.inner"]
```

After updating to 3.1.5 we're running into problems with the missing class `InvalidArgumentException` because it enters the `$definition->isPublic()` if in line 33 of `AddConstraintValidatorsPass.php`. That has been fixed with commit [#32451b1a092181b793ee6bd186eeb7a3ca039491](https://github.com/symfony/symfony/commit/32451b1a092181b793ee6bd186eeb7a3ca039491). But the underlying problem still persists. Due to the service decoration the `$definition->isPublic()`-check fails on the `app.dev.validator.email.inner` service. 

Don't know whether this is the expected behavior. If so, what would be the *new* way to replace shipped constraint validators?
