### ISSUE TITLE
Error 500 rose on 'AccessDeniedException'

### ISSUE THREAD

**Issue by Cypaubr** [symfony/symfony#20233]
When the user tries to access a route needing an user authentication using the Anonymous account, a HTTP 500 error is rose. Why not a 403? Is there any way to rise a 403?

**Comment by xabbuh** [comment]
You should not see a 500 response. Are you sure that this is triggered by Symfony core and not by one of your own exceptions? Can you show an example that reproduces your issue (best by forking the Symfony Standard Edition and making the necessary changes)?

**Comment by Cypaubr** [comment]
The controller for this route only returns a 'Hello World' message so the exception is triggered by Symfony. In my security.yml I just set up a simple firewall on this route disabling anonymous auth and enabling security like this : 
```
app:
            pattern: ^/(fr|en)/app$
            anonymous: false
            security: true
            provider: db
            form_login:
                login_path: one_day_connect
                check_path: user_connect
            logout:
                path: one_day_logout
                target: one_day_homepage
```
