### ISSUE TITLE
[FrameworkBundle] cache annotations using DoctrineCacheBundle

### ISSUE THREAD

**Issue by IndraGunawan** [symfony/symfony#20234]
``` yml
# config.yml
framework:
    annotations:
        cache: doctrine_cache.providers.annotation_cache

doctrine_cache:
    providers:
        annotation_cache:
            redis:
                host: "%redis_host%"
                port: "%redis_port%"
                database: "%redis_elasticsearch_db%"
            namespace: 'annotation_cache:'
```

when i ran i got

``` bash
  [ReflectionException]
  Class  does not exist
```
