### ISSUE TITLE
[LDAP] How can I retrieve password symfony 2.8

### ISSUE THREAD

**Issue by blb78** [symfony/symfony#20293]
Hi !
My LDAP authentication works like a charm.

```yaml
providers:
        ldapservice:
            id: app.ldap_user_provider

        app_users:
            ldap:
                service: app.ldap
                base_dn: dc=test,dc=com
                search_dn: null
                search_password: null
                filter: (uid={username})
                default_roles: ROLE_USER
firewalls:
       main:
            anonymous: true
            provider: ldapservice
            pattern: ^/
            logout:
                path:   /logout
                target: login
            form_login_ldap:
                service: app.ldap
                dn_string: uid={username},ou=Users,dc=test,dc=com
                check_path: login
                login_path: login
                default_target_path: /

services:
        app.ldap:
            class: Symfony\Component\Ldap\LdapClient
            arguments: [ "toto.test.com",389,3,false,true ]
```

In my project, I have to authenticate users on a LDAP server.
If this one return a success, I have to create a new user in my mysql database (if he doesn't exist yet).

My problem is that I don't know how retrieve user password in my loadUserByUsername function.

How can I do that ?

Thx
