### ISSUE TITLE
Event Dispatcher ignore method tag with Doctrine event Listener

### ISSUE THREAD

**Issue by Dean79000** [symfony/symfony#20360]
Method tag (onCustomEvent) is ignored and try to call default method name (prePersist)

services.yml
```
mybundle.listener.events:
        class: MyNamespace\MyBundle\Listener\EventsListener
        arguments: []
        tags:
            - { name: doctrine.event_listener, entity: MyBundle\Entity\MyEntity, event: prePersist, method: onCustomEvent }
```

When i persist entity, i got :
`UndefinedMethodException in ContainerAwareEventManager.php line 63: Attempted to call an undefined method named "prePersist" of class "MyNamespace\MyBundle\Listener\EventsListener".`

But if i create method "prePersist", is work.

Tested on Symfony 3.1.5 & 3.1.6
