### ISSUE TITLE
Variable "this" has value of null in an "Expression" validation constraint inside an "All" validation constraint

### ISSUE THREAD

**Issue by zsolt-racz** [symfony/symfony#20477]
I have possibly found a bug in the Validator component when combining these two constraints: Expression and All. I'm going to show it on an example:

Considering these two classes:
```php
namespace AppBundle;
class ParentClass {

	private $name;
	private $children;

	public function __construct(){
		$this->children = new ArrayCollection();
	}

	public function getName() {
		return $this->name;
	}

	public function setName( $name ) {
		$this->name = $name;
	}

	public function getChildren() {
		return $this->children;
	}

	public function addChild( $child ) {
		$this->children->add($child);
	}
}
```
and 
```php
namespace AppBundle;
class ChildClass {

	private $name;

	public function getName() {
		return $this->name;
	}

	public function setName( $name ) {
		$this->name = $name;
	}

}
```
With the following validation rules stored in `validation.yml`:
```yaml
AppBundle\ParentClass:
    properties:
        children:
            - NotBlank: ~
            - Valid: ~
            - All:
                - Expression:
                    expression: "this.getName() != value.getName()"

AppBundle\ChildClass:
    properties:
        name:
            - NotBlank: ~
```

I would like to achieve to forbid assigning the parent's name to children. So the `getName()` method of the parent should return a distinct value from `getName()` methods of all children.

However after trying to validate an instance of `ParentClass` constructed like this:
```php
    $validator = $this->get('validator');

    $parent = new ParentClass();
    $parent->setName("foo");

    $child = new ChildClass();
    $child->setName("bar");

    $parent->addChild($child);
    $validator->validate($parent);
```
A RuntimeException is thrown with the following message:
```
Unable to get a property on a non-object. 
```

As I figured out, the variable _value_ is correctly assigned to child objects, however the variable _this_ in the expression has a value of  _null_. I would expect a reference to the parent object in this variable, regarding to the [documentation](http://symfony.com/doc/current/reference/constraints/Expression.html#reference-constraint-expression-option): 

> `this`: The object being validated (e.g. an instance of BlogPost);

---
Symfony 3.1.6, PHP 7.0.8, Linux Mint 18

**Comment by stof** [comment]
``this`` is populated when you apply an Expression constraint on a property of an object, to be able to access the whole object (as ``value`` will be the property value).
For class-level constraint, there are only 2 possibilities: assign null, or assign the object, i.e. the same than ``value`` (which could be worse as it could hide things).

In your case, getting the ParentClass instance would be wrong. When the ``All`` constraint applies the constraints on all items of the array, we are not validating the ParentClass instance. We are validating the array item.

**Comment by zsolt-racz** [comment]
@stof Well, it makes sense and I agree with your reasoning. However I think the variable `this` should never be null - this is also what the [documentation](http://symfony.com/doc/current/reference/constraints/Expression.html#reference-constraint-expression-option) implicitly states.

Also I found out, that the expression variables in class-level constraints are assigned inconsistently depending if they are defined within the `All` constraint, or outside the `All` constraint. For example, if I define a class-level constraint like this:
```
AppBundle\ChildClass:
    constraints:
        - Expression:
            expression: "this == value"
```
The validation passes, since the expression is evaluated as `true`. In this case a the value of `this` and the value of `value` is the same: the `ChildClass` object. 

Then it would be expectable for the next constraint to pass too:
```
AppBundle\ParentClass:
    properties:
        children:
            - All:
                - Expression:
                    expression: "this == value"
```
However, it's definitely not, since in this case `this` get assigned to the value `null`.

I think in both cases, `this` should hold the reference to the direct parent object, and `value` should have the same value or be assigned to `null`.
