### ISSUE TITLE
Routing match api category tree

### ISSUE THREAD

**Issue by ReenExe** [symfony/symfony#20631]
It is possible merge 3 to 1 in native config&
```yaml
api_filter_list:
    path: /list.{_format}
    defaults: { _controller: AppBundle:ApiFilter:list }
    methods: [ 'GET' ]

api_filter_list_gender:
    path: /list/{genderCategory}.{_format}
    defaults: { _controller: AppBundle:ApiFilter:list }
    methods: [ 'GET' ]
    requirements:
        genderCategory: 'men|women|kids|home'

api_filter_list_gender_category:
    path: /list/{genderCategory}/{childCategory}.{_format}
    defaults: { _controller: AppBundle:ApiFilter:list }
    methods: [ 'GET' ]
    requirements:
        genderCategory: 'men|women|kids|home'
        childCategory: '[A-z-]+'
```
Searched in:
https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Component/Routing/Tests/Matcher/UrlMatcherTest.php#L241

**Comment by javiereguiluz** [comment]
I don't fully understand the question: do you want to define just 1 route which is equivalent to the 3 routes that you showed?

**Comment by ReenExe** [comment]
@javiereguiluz, ye

**Comment by Tobion** [comment]
It's currently no possible because `{_format}` is required in your case. Optional, multiple parts only work at the end of the path.

So the following should work without the format and defaults for each variable:

```
api_filter_list_gender_category:
    path: /list/{genderCategory}/{childCategory}
    defaults: { _controller: AppBundle:ApiFilter:list, genderCategory: null, childCategory:  null }
    methods: [ 'GET' ]
    requirements:
        genderCategory: 'men|women|kids|home'
        childCategory: '[A-z-]+'
```

Then you would only need one route. Your use-case would be covered with #5424
