### ISSUE TITLE
[BUG] - Extra parameters in parameters.yml are deleted when updating composer

### ISSUE THREAD

**Issue by nietzcheson** [symfony/symfony#20719]
I'm using Symfony 2.8.*.

The parameters into an normal applications the Symfony are:

```
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: symfony
    database_password: symfony
    mailer_transport: smtp
    mailer_host: mail.host
    mailer_user: mail.user
    mailer_password: mail.pass
    secret: secret

    paypal.username: TEST
    paypal.sandbox: TEST
```

If I add an extra parameter when updating the project with *composer update* these parameters are deleted from this file. 

Any ideas?
