### ISSUE TITLE
[FrameworkBundle] Is TagAwareAdapter declared as a service?

### ISSUE THREAD

**Issue by tifabien** [symfony/symfony#20764]
After upgrading in 3.2 I'm trying to use the new cache tag based invalidation in the fullstack framework.
My first thought was to inject the default cache.app service and call the new invalidateTags method but it seems the default cache.app didn't change.
So I tried to use the TagAwareAdapter but there is no service declared for the Symfony\Component\Cache\Adapter\TagAwareAdapter class.

My question is how can I use the new TagAwareAdapter. Do I need to declare my side the TagAwareAdapter service and change the default cache.app adapter in my config.yml file or maybe the service declaration misses in the FrameworkBundle cache.xml? 

Thanks!

**Comment by nicolas-grekas** [comment]
You're right, there is no existing service using it, so if you need it, it's up to you to wire it.
Maybe using a decorated service?
http://symfony.com/doc/current/service_container/service_decoration.html

**Comment by tifabien** [comment]
Thanks @nicolas-grekas it works when I decorate the cache.app service. Btw I think it's weird to have access to the tag method in CacheItem without having the possibility to invalidate items in the default cache.app adapter.
I would expect to have the invalidateTags method by default. What do you think?

**Comment by nicolas-grekas** [comment]
Having the method always present would mean checking for tags for any single cache check, thus hurting performance even when no tags are expected.
Glad it works, thanks for the feedback!

**Comment by tifabien** [comment]
Understood for the performance impact.
Thanks again for your help!

**Comment by Wirone** [comment]
@nicolas-grekas I don't understand.

I have this configuration:

```yaml
framework:
    # ...
    cache:
        # Default cache engine
        app: cache.adapter.filesystem
        pools:
            # Custom cache for storing user's group access rules
            my.cool.cache:
                adapter: cache.app
                default_lifetime: "%my.cool.cache.lifetime%"
```

I have to decorate `cache.app` somewhere in my bundle's config in order to use `TagAwareAdapter`?

Shouldn't `FrameworkBundle` support this out-of-the-box?

**Comment by xabbuh** [comment]
@Wirone You can just do that in your custom service configuration: http://symfony.com/doc/current/service_container/service_decoration.html

**Comment by Wirone** [comment]
I know, I've only asked about it because I didn't believe it's not a built-in, configuration feature.

**Comment by xabbuh** [comment]
@Wirone Ah, I misunderstood your last comment then. And indeed, for now you have to decorate this for yourself.

**Comment by pascalwacker** [comment]
@xabbuh could you provide an example decoration for the `TagAwareAdaper` overwriting `cache.app`

My current implementation is:
```
    app.cache:
      class: Symfony\Component\Cache\Adapter\TagAwareAdapter
      public: true
      decorates: cache.app
      arguments: ['@app.cache.inner', '@app.cache.inner']
```

What I also thought about was an singleton class like
```
<?php

namespace AppBundle\Utils;

use Symfony\Component\Cache\Adapter\TagAwareAdapter;
use Symfony\Component\Cache\Adapter\TraceableAdapter;

class Cache
{
    protected static $_cache = null;

    public static function setInstance(TraceableAdapter $cache)
    {
        if (null === self::$_cache) {
            self::$_cache = new TagAwareAdapter($cache, $cache);
        }
    }

    public static function getInstance(TraceableAdapter $cache = null): TagAwareAdapter
    {
        if (null !== $cache && null === self::$_cache) {
            self::$_cache = new TagAwareAdapter($cache, $cache);
        }

        return self::$_cache;
    }
}
```

but that didn't seam like a good idea to me. Is the first implementation the correct one?
