### ISSUE TITLE
Workflow "can" function checks only first valid transition

### ISSUE THREAD

**Issue by ggabrovski** [symfony/symfony#20788]
Function can($subject, $transitionName) in Workflow.php need to returns true if the transition is enabled, 
but getTransitionForSubject return only the first transition in transitions that is valid for the object.
And in the example below the only valid transition is "feedback". The other two "review" and "close" are missing. If the initial place is "opened".
![test1](https://cloud.githubusercontent.com/assets/24413349/20931482/e28ee044-bbd9-11e6-90e6-1c9acb631ed5.png)

Example:
```yaml
framework:
    workflows:
        pull_request:
            marking_store:
                type: single_state
                arguments:
                    - marking
            supports:
                - AppBundle\Entity\PullRequest
            places:
                - opened
                - closed
                - needs_review
                - reviewed
                - merged
            initial_place: opened
            transitions:
                feedback:
                    from: opened
                    to:   needs_review
                review:
                    from: [opened, needs_review]
                    to:   reviewed
                merge:
                    from: reviewed
                    to:   merged
                close:
                    from: [opened, needs_review, reviewed]
                    to:   closed
```

**Comment by Padam87** [comment]
Are you sure? `getTransitionForSubject` recieves an array of transitions already filtered by the name, so this should not be a problem...

I wrote a test locally that confirms this

```
    public function testCanWithMultipleTransitions()
    {
        $definition = $this->createComplexWorkflowDefinition();
        $subject = new \stdClass();
        $subject->marking = array('d' => 1);
        $workflow = new Workflow($definition, new MultipleStateMarkingStore());

        $this->assertTrue($workflow->can($subject, 't3'));
        $this->assertTrue($workflow->can($subject, 't4'));
    }
```

**Comment by Padam87** [comment]
@ggabrovski Oh, i just took a second look at your config.

All from states are evaluated, so in your case `review` and `close` are not applicable, if your marking only has `opened`.

**Comment by Padam87** [comment]
I believe this needs a new feature: ability set the match type of from states to `one` or `all` ... on it

**Comment by lyrixx** [comment]
Hello.

There is no bug here.
In your case, you should use a StateMachine if you want to perform all transitions.
By default, The workflow use a PetriNet implementation and rules to be able to transition are more complex: You need to be in all states "from" a transition.

So you should update your config like that:
```yaml
framework:
    workflows:
        pull_request:
            marking_store:
                type: single_state
                arguments:
                    - marking
            type: state_machine
// ...
```

In invite you to read the [documentation on wikipedia](https://en.wikipedia.org/wiki/Petri_net#Execution_semantics) because the document on symfony.com is not complet yet ;)
