### ISSUE TITLE
[Workflow] No ability to implement my own MarkingStore?

### ISSUE THREAD

**Issue by laurensvandeput** [symfony/symfony#20815]
It seems I cannot implement my own MarkingStore in Symfony 3.2, besides using SingleStateMarkingStore and MultipleStateMarkingStore. 

Our use case (which is a state machine) requires some mapping of the places within the state machine. In our domain, the workflow which sets a "status" is an enumeration while our entity holds numeric values (due to legacy reasons) for this status.

Implementing a MarkingStore, such as the one below seems the cleanest solution. 

```
    public function getMarking($subject)
    {
        $value = $this->propertyAccessor->getValue($subject, $this->property); // should return 3
        $placeName = $this->converter->convertToEnum($value); // should return FOR_SALE

        if (!$placeName) {
            return new Marking();
        }

        return new Marking(array($placeName => 1));
    }

    public function setMarking($subject, Marking $marking)
    {
        $value = key($marking->getPlaces()); // should return FOR_SALE
        $placeName = $this->converter->convertToInt($value); //should return 3
        $this->propertyAccessor->setValue($subject, $this->property, $placeName);
    }
```

Adding new MarkingStores is avoided by the configuration, which defines the following:
```
...
->arrayNode('marking_store')
  ->fixXmlConfig('argument')
  ->children()
    ->enumNode('type')
      ->values(array('multiple_state', 'single_state'))
    ->end()
...
```
Am I missing something here?

**Comment by lyrixx** [comment]
Hello @laurensvandeput 

Sorry for the late reply.

You can see all allowed configuration with the following command 
`bin/console config:dump framework`.

```yaml
    workflows:

        # Prototype
        name:
            type:                 workflow # One of "workflow"; "state_machine"
            marking_store:
                type:                 ~ # One of "multiple_state"; "single_state"
                arguments:            []
                service:              ~
            supports:             [] # Required
            initial_place:        null
            places:               [] # Required
            transitions:          # Required

                # Prototype
                name:
                    from:                 []
                    to:                   []
```

So in your case, you have to register a new symfony service, and use it like
that:

```yaml
    workflows:
        # Prototype
        name:
            type: state_machine

            marking_store:
                service: app.workflow.marking_store.enum # <- the "id" of your service
```

**Comment by laurensvandeput** [comment]
Thanks @lyrixx!

**Comment by laurensvandeput** [comment]
When adding a service to a state machine, I get the following exception:
`[InvalidArgumentException] "arguments" and "service" cannot be used together.`

The culprit seems to be the following code: 
```
->validate()
  ->ifTrue(function ($v) { return isset($v['arguments']) && isset($v['service']); })
  ->thenInvalid('"arguments" and "service" cannot be used together.')
```

A possible fix could be:
```
->validate()
  ->ifTrue(function ($v) { return !empty($v['arguments']) && isset($v['service']); })
  ->thenInvalid('"arguments" and "service" cannot be used together.')
```

**Comment by mvar** [comment]
Is it ability if it's not working? IMHO, this issue should be left open until problem mentioned by @laurensvandeput will be fixed.

CC @lyrixx

**Comment by HeahDude** [comment]
@laurensvandeput This is expected. `arguments` is used for injection in default marking stores. If you use a service you can handle the injection in its own definition.

**Comment by laurensvandeput** [comment]
@HeahDude Agreed, but if you define a service within the context of a workflow, the arguments array seems to be empty which results in firing the exception. The following snippet reproduces the issue:

```
framework:
    workflows:
        property_status:
            type: 'state_machine'
            supports:
                - My\Class
            marking_store:
                service: api.workflow.marking_store.enum.status
```
