### ISSUE TITLE
[FrameworkBundle]   Incompatible use of dynamic environment variables when configuring framework.cache.default_redis_provider

### ISSUE THREAD

**Issue by robinvdvleuten** [symfony/symfony#20850]
Hi there,

When I am trying to configure the default cache provider for the new cache implementation;

```yml
parameters:
    env(REDIS_URL): 'redis://localhost'

framework:
    cache:
        default_redis_provider: "%env(REDIS_URL)%"
        pools:
            cache.tickets:
                adapter: cache.adapter.redis
                default_lifetime: 300 # 5 minutes in seconds
```

I get the following exception when clearing the cache;

```
[Symfony\Component\DependencyInjection\Exception\EnvParameterException]             
Incompatible use of dynamic environment variables "REDIS_URL" found in parameters.
                                                                                                                                                                                    
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                  
The service "cache.tickets" has a dependency on a non-existent service "%env(REDIS_URL)%".  
```

Which is a bit strange as it seems to look like a very good use case of using the new env functionality to me.

**Comment by nicolas-grekas** [comment]
You need to have the redis:// out of the env param, e.g.:
`default_redis_provider: "redis://%env(REDIS_HOST)%"`

**Comment by nicolas-grekas** [comment]
closing since this is not a bug, see http://symfony.com/support
(but you should have the answer anyway  :) )

**Comment by robinvdvleuten** [comment]
Thanks @nicolas-grekas for the explanation! I thought I stumbled upon a bug, so please excuse me for that :)

**Comment by HeahDude** [comment]
@nicolas-grekas I got the same error trying to use an env variable to define `mailer_transport`, I'm not sure this is not a bug though.

**Comment by nicolas-grekas** [comment]
it's not a bug for sure, it's what it says, an incompatible use of dynamic environment. You can't inject an env var anywhere. Any place that is reading the value of a parameter at compile time (in a DI ext or a compiler pass) is not compatible with env vars.
See e.g. for a PR that move using the value of a param from compile to runtime to allow using env vars there:
https://github.com/symfony/symfony/pull/19843

**Comment by HeahDude** [comment]
Understood! Thank you for the explanation :)

**Comment by robinvdvleuten** [comment]
@nicolas-grekas ok so you suggest to create a PR to have this functionality on runtime for the default cache provider? As it is very required to have because Heroku and other SAAS providers out there prepend `redis://` to their urls.

**Comment by stof** [comment]
@nicolas-grekas it would indeed be useful to support env variables for redis URLs for the cache, as this is a common case for using URLs on PaaS

**Comment by nicolas-grekas** [comment]
We could have a new `default_redis_url` to do that yes. @robinvdvleuten if you'd like to submit a PR for that, please do.
Meanwhile, you can define the service yourself:
```yaml
services:
    cache.default_redis_provider:
        class: Redis
        public: false
        arguments:
            - %env(REDIS_URL)%
```
