### ISSUE TITLE
Environment variables get REDIRECT_ appended in prod but not dev

### ISSUE THREAD

**Issue by MicWit** [symfony/symfony#20947]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

When using an environment variable set by Apache, if it is coming from a redirect (like in the case of a user login), it adds REDIRECT_ to the variable name in prod, but not dev.

To test this out:
1) Set up the following in security.yml:
```
security:
  firewalls:
    firewall_name:
      anonymous: ~
      form_login:
        login_path: /symfonylogin
  access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
  encoders:
    AppBundle\Security\User\WebserviceUser: bcrypt
```
2) Leave the default route and set up an extra route for /admin

3) Set up a route for /symfonylogin and do a `print_r($_SERVER)` to dump all environment variables directly from PHP

4) In /web/.htaccess add a line with the following:
`SetEnv REMOTE_USER adminblah`

Now if you were to go to site/app_dev.php/admin it would redirect you to /symfonylogin and print the environment variables. You will see that there is a REMOTE_USER variable, but no REDIRECT_REMOTE_USER variable. If you then go to site/admin (to see the prod version) it will have a variable REDIRECT_REMOTE_USER as well. Note that in our case, the only reason that REMOTE_USER is also there is because it is being set every time a page loads (including when loading /symfonylogin). When an external source is setting this, you only get the REDIRECT_REMOTE_USER variable.

Because we are pulling this directly from the PHP variable $_SERVER I thought it was a PHP thing, but the fact that it only does it when you load the prod environment and not dev means it has to be Symfony doing this.

This should be set up the same between prod and dev as it makes development very hard if the 2 environments act so differently. I would suggest changing the behavior of the dev environment to match production.
