### ISSUE TITLE
Web Debug Toolbar not showing logs on 2.8

### ISSUE THREAD

**Issue by jordisala1991** [symfony/symfony#21014]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.15

Symfony 2.8.15 always shows an empty logger on the debug toolbar (and I know there are some deprecations on my code). I tried to update to Symfony 3.2.0 and it shows the logs.

I tried to find a lower version where it works but it was imposible for 2.8 atleast.

My config_dev.php:

```yaml
imports:
    - { resource: config.yml }

framework:
    router:
        resource: %kernel.root_dir%/config/routing_dev.yml
        strict_requirements: true
    profiler:
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            channels: [!event]
        console:
            type: console
            channels: [!event, !doctrine]
```
