### ISSUE TITLE
Dependency injection - abstract service definition not found

### ISSUE THREAD

**Issue by kptLucek** [symfony/symfony#21127]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.7

Hi there

Im facing issue when trying to use *abstract service definition* in my project.

```yml
    abstract_service_definition:
        class: Acme\DemoBundle\AbstractService
        abstract: true
        arguments:
            - '@router'

    service_definition:
        class: Acme\DemoBundle\Service
        public: false
        parent: '@abstract_service_definition'
```

Error im getting is:
`[Symfony\Component\DependencyInjection\Exception\RuntimeException]                                                                                                  
  The parent definition "@abstract_service_definition" defined for definition "service_definition" does not exist.  `

**Comment by xabbuh** [comment]
The `parent` option literally refers to the service id. Thus, in your example it expects the `@`character to be part of the id. This indicator character is only needed in case where the loader cannot guess whether you refer to a string or a service id depending on the context (for example, when defining arguments for a service constructor/method).

Changing your example as follows will solve your issue:

```yaml
abstract_service_definition:
        class: Acme\DemoBundle\AbstractService
        abstract: true
        arguments:
            - '@router'

    service_definition:
        class: Acme\DemoBundle\Service
        public: false
        parent: 'abstract_service_definition'
```
