### ISSUE TITLE
Simplify configuration registration

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#21173]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

I guess it's not everyone, but I personally use _a lot_ of configuration files. I like to split them when it makes sense and avoid having config files that are too big. On my last 3 good sized projects (not all from me actually) the average was ~50 files.

I personally find very cumbersome to have to manually include them via `config*.yml` files, so I've done a small locator which register my config files automatically. It works as follow:

- scan the config dir to get all the files there
- filter files: some should not be included at all, e.g. `routing` and `parameters.dist` and other are environment specific
- load each of those files 

So you basically have the following:

```
app/config/
    parameters.yml
    parameters.yml.dist  # ignored (like any `*.dist`)
    routing.yml          # ignored
    security.yml         # included for any environment
    security_prod.yml    # included only for the env `prod`
    framework.yml
    framework_prod.yml
    ...
    services/
        foo.yml
        foo_dev.yml
        foo_prod.yml
```

I would like to suggest to have that feature directly in the core (I can work on it), WDYT?

/cc DX master @weaverryan

**Comment by javiereguiluz** [comment]
In 2.8 we introduced a feature to load recursively all config files in directories. Would that help you?

```yaml
    # Before Symfony 2.8
    imports:
        - { resource: acme/parameters.yml }
        - { resource: acme/security.yml }
        - { resource: acme/services.yml }

    # In Symfony 2.8
    imports:
        - { resource: acme/ }
```

See http://symfony.com/blog/new-in-symfony-2-8-dx-improvements#recursive-directory-loading-for-configuration-and-routing
