### ISSUE TITLE
Domain required in Phpunit test when redirecting

### ISSUE THREAD

**Issue by c33s** [symfony/symfony#21189]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

- PHPUnit 5.7.4
- PHP 7.0.13
- Windows7x64
- Symfony 3.2.1

the following test, taken from https://symfony.com/doc/current/testing.html#working-with-the-test-client (scroll up to Useful Assertions), shows the example without domain:

```php
// Assert that the response is a redirect to /demo/contact
$this->assertTrue(
    $client->getResponse()->isRedirect('/demo/contact'),
    'response is a redirect to /demo/contact'
);
```

doing the same in my tests fails:

```php
    public function testPressRedirect()
    {
        $client = static::createClient();
        $client->request('GET', '/press');
        $this->assertTrue($client->getResponse()->isRedirect('/en/press')); //fails
    }
```

routing.yml

```yaml
_press_redirect:
    path: /press
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/press
        permanent: true
```

I have to include the domain and the protocol to make it work:

```php
    public function testPressRedirect()
    {
        $client = static::createClient();
        $client->request('GET', '/press');
        $this->assertTrue($client->getResponse()->isRedirect('http://localhost/en/press')); //works
    }
```
