### ISSUE TITLE
system cache set namespace doctrine provider adapter

### ISSUE THREAD

**Issue by agrisvv** [symfony/symfony#21181]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

example config

```yaml
#config.yml
cache: 
        app: cache.adapter.doctrine
        system: cache.adapter.doctrine
        default-doctrine-provider: app_doctrine_cache
```

```yaml
doctrine_cache:
    aliases:
        app_doctrine_cache: app_redis_cache
    providers:
        app_redis_cache:
            namespace: "test_namespace:"
            type: redis
```
Then in code get namespace:

```php
$cache = $this->container->get('app_doctrine_cache');
$namepsace = $cache->getNamespace(); 
```

RESULT namespace

| PROD                | DEV
| ---------------- | -----
| NcV0bhGeDK     | test_namespace:

So doctrine provider namespace are overwrite. and can't delete keys by namespace.

Workaround  - symfony system cache set to use direct redis adapter not doctrine provider.
