### ISSUE TITLE
[RFC][Yaml] Add custom tags support

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#21185]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.0

Custom tags support is a very important feature imo that currently lacks to the yaml component.
It is basically allowing things like:
```yml
services:
    square_printer:
        arguments: [ !color red ]
```

By having a dedicated system for tags, we could centralize their management and avoid duplication ([here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Yaml/Inline.php#L576-L616) and [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Yaml/Parser.php#L561-L568)).
If wanted, it could also be used in the core to remove reserved keys in config files.
For example,
```yml
services:
    _defaults:
        autowire: true

    my_service:
        class: FooBar
        arguments:
            - '@service1'
            - =iterator:
                - '@service2'
                - '@service3'

# could become
services:
    !defaults:
        autowire: true

    my_service:
        class: FooBar
        arguments:
            - '@service1'
            - !iterator
                - '@service2'
                - '@service3'
```

WDYT?
