### ISSUE TITLE
Fatal error: SessionHandlerProxy

### ISSUE THREAD

**Issue by fleskalebas** [symfony/symfony#21213]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

After upgrading to PHP 7.1 and symfony 3.2.1 I sometimes (once a week, random) get the following error:

> FatalErrorException in classes.php line 347:
> Error: Class Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (SessionHandlerInterface::write)

I changed the following lines in config.yml to the new Symfony 3 style:
```
session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
```

But it still happened.

After reading http://stackoverflow.com/questions/36088683/php-7-symfony-3-fatal-error-1-abstract-method-and-must-therefore-be-declared-a
The solution is indeed to restart Apache.

I have no clue what can be the cause, maybe PHP 7.1, but Symfony 3 is compatible with 7.1 right?

Maybe someone here can point me in the right direction to solve this :)
