### ISSUE TITLE
[FrameworkBundle] Add new "routing.annotated_controller" service tag

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#21282]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| RFC?             | yes
| Symfony version  | 3.3

When one defines a controller as a service, it would be nice to be able to wire it with routing in a snap of a tag.
eg
```yaml
services:
    Controller\SomeController:
        tags:
            - name: routing.annotated_controller
              prefix: /foo #optional, maybe the other route params as other tag attributes if worth it?
```

Using this tag, the routes would be specified as annotations on the related class+methods (which means moving [AnnotatedRouteControllerLoader](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/3.0/Routing/AnnotatedRouteControllerLoader.php) to FrameworkBundle.

This would allow bundles to take control of the wiring of their routing configuration. This means that just by enabling a bundle, its routing config would be done. Of course, each bundle could provide config to change the prefix, disable/enable routes conditionally, etc.

I also think that this would mean one less file to look at for new comers (I mean routing.yml.)

If someone would like to give it a try, please do :)

**Comment by iltar** [comment]
You have my vote for sure! See #12915

**Comment by HeahDude** [comment]
Although the approach in #12915 was refused, this sounds more reasonable today now that Tobion's comment is resolved and regarding the direction symfony is taking for controllers and bundless apps 👍.

**Comment by ro0NL** [comment]
I'd prefer keeping the trigger and app specific route config in `routing.yml` (prefix, enabled, etc.)

But the concept of annotated controllers as a service sounds good :+1:

**Comment by sstok** [comment]
I prefer to keep routes in the routing itself, using tags feels to magical and less conventional.
Unless you register them as services and then "import" those service definitions.

To automatically register routes to a pool (for manual importing) you can have a look at https://github.com/rollerworks/RouteAutowiringBundle (and it would be great if this could be moved to the Symfony framework itself, and improved where possible 👍 )

**Comment by iltar** [comment]
> Unless you register them as services and then "import" those service definitions.

This would be nothing more than aggregating the services and then reading the annotations during cache warmup. Instead of having to guess the service id for the class based on annotation, this is probably injected during container compilation.

**Comment by dunglas** [comment]
> Secondly, using Annotations will couple you to the Framework (again) where registering Controllers are service is to prevent that.

There is several use cases for controller as a service. One can be decoupling actions form the framework. Another unrelated usage is too enable autowiring on controllers, so you can inject services without defining them in a config file.

The suggestion of @nicolas-grekas makes sense in the 2nd context. The goal is to make the framework easy to use for newcomers, not to decouple from the framework. A more experimented developper can easily switch to framework-agnostic actions later.

I like the idea.

**Comment by chalasr** [comment]
This may fit quite well with what is proposed in #21289 I guess:

```yaml
App\Controller\:
    autowire: true
    psr4: ../Controller # equals the "resource" routing attribute
    tags:
        - { name: routing.annotated_controller}
```
