### ISSUE TITLE
Feature: Allow extensions on the workflow definitions

### ISSUE THREAD

**Issue by meDavid** [symfony/symfony#21358]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | >=3.2

I would like to extends the workflow definitions with extra properties such as schedule information. Currently the implementation of the workflow Definition is marked as final in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Definition.php#L22 and the workflow implementation is tightly coupled to this implementation. 

My proposal is to:
* Make the Workflow class dependend on an interface instead of a class 
or 
* Make the Definition class no longer final

If a pullrequest is welcome, I would be glad to provide one.

**Comment by lyrixx** [comment]
Hello  @meDavid

Before starting on the PR, could you show us how you would configure it / use it. The example don't have to be working, I just want to understand the use case, and how it could work.

Thanks.

**Comment by lyrixx** [comment]
Hello @meDavid

Without feedback from you, I will have to close this issue.

**Comment by meDavid** [comment]
Hello @lyrixx 
Sorry for the delay. My case is extending the workflow definition without rebuilding the workflow implementation. The workflow definition consists of the places and transitions. The Transitions can be extended, but places are only plain strings, limiting possible extensions.

```
my_workflow_extension:
  workflow_1:
    places:
      myplace_1: 
        label: 'My Nice label'
        type: 'parallel_gateway'
    transitions:
      transition_1:
        actor: system
        guard_expression: 'some expession with the subject'
        from: myplace_1
        to: myplace_2
      transition_2:
        actor: system
        offset: 'PT3D'
        from: myplace_2
        to: myplace_2

```

I might also be able to work around it implementing Place.__toString()
