### ISSUE TITLE
[Security][Guard] Per authenticator provider

### ISSUE THREAD

**Issue by fbourigault** [symfony/symfony#21391]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

Guard is the new way to do authentication, and it does the job really well. But unlike, "old school" AuthenticationListeners, you can't configure the user provider to be used.

Should we allow to configure the userProvider per authenticator with something like this:
```yaml
security:
    firewall:
        main:
            guard:
                authenticators:
                    - authenticator.which.use.firewall.user.provider
                    - service: authenticator.which.use.own.provider
                      provider: authenticator.own.provider
```
or should we just inject the right provider in the authenticator constructor and ignore the `$userProvider` argument in `GuardAuthenticatorInterface::getUser` method? The latter looks bad for DX as the developer will have to ignore this provided argument and won't be able to use a framework configured provider as he need to inject it in the authenticator constructor.

**Comment by chalasr** [comment]
> Guard is the new way to do authentication

Not sure :) Guard is a (great) alternative to the normal authentication system, providing an easy way to solve from the most basic needs to more complex ones. But there're still use cases where a normal authentication listener+provider is useful, as they are a lot more flexible (they can have a config tree, that I would love to have for Guard though, so that not only the provider could be custom per authenticator, but everything).

> unlike, "old school" AuthenticationListeners, you can't configure the user provider to be used.

Right now you can't configure a provider _per authenticator_, but you can still configure a provider _per firewall_:

```yaml
providers:
   in_memory:
        memory:
            # ...
    database:
        entity:
            # ...

firewalls:
    main:
        provider: database
        guard:
            # ...
```

If you have multiple authenticators e.g. one being able to authenticate users from a specific provider, and another from a second specific provider, what you can do is to configure a [chain provider](https://symfony.com/doc/current/security/multiple_user_providers.html):

```yaml
providers:
   in_memory:
            # ...
    database:
        # ...
    chain_provider:
        chain:
            providers: [in_memory, database]

firewalls:
    main:
        provider: chain_provider
        guard:
            # ...
```

Like this, when calling `$userProvider->loadUserByUsername()` from your authenticator, the chain provider will try to load the user from both `in_memory` and `database` providers (in this order) before returning the result.

It is indeed less flexible than explicitly setting a provider per authenticator, but it should be enough in most cases (maybe all with a bit of custom logic).

**Comment by fbourigault** [comment]
I don't feel safe by using a chain_provider for the authentication. Let me explain why.

Imagine we have a guard authenticator like this one (which is more or less the same from the [Guard docs](http://symfony.com/doc/current/security/guard_authentication.html#step-1-create-the-authenticator-class):
```php
    /**
     * {@inheritdoc}
     */
    public function getCredentials(Request $request)
    {
        $header = $request->headers->get('Authorization');
        if (empty($header)) {
            return;
        }

        if (!preg_match('#^Bearer (?<bearer>.+)$#', $header, $matches)) {
            return;
        }

        return [
            'bearer' => $matches['bearer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        return $userProvider->loadUserByUsername($credentials['bearer']);
    }

    /**
     * {@inheritdoc}
     */
    public function checkCredentials($credentials, UserInterface $user)
    {
        return true;
    }
```

If we use an chain_provider, an attacker could send a request with an `Authorization: Bearer admin@example.com`. Then, as we use a `return true` statement in `GuardAuthenticatorInterface::checkCredentials`, the attacker has the ability to became any user if he knows his username or email.

This is a major flaw. We probably need to update the Symfony documentation to warn about use of ChainUserProvider. I only use this latter on the firewall for user refreshing.

**Comment by chalasr** [comment]
Well, I don't think there is any security issue in the chain provider itself.

You're responsible for checking the credentials before calling your provider.

> If we use an chain_provider, an attacker could send a request with an Authorization: Bearer admin@example.com. Then, as we use a return true statement in GuardAuthenticatorInterface::checkCredentials, the attacker has the ability to became any user if he knows his username or email.

A Bearer token should always be decoded, verified and validated before calling any user provider, an email address as Bearer should be  rejected immediately. Btw, you can perfectly validate it in getCredentials(), it's common since APIs are a specific context. See the [LexikJWTAuthenticationBundle JWT authenticator](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Guard/JWTTokenAuthenticator.php) for instance.

Anyone can create security holes by trying to load an user from given credentials without ensuring these credentials are valid according to the context, it is up to you to do it right, not the provided system to prevent it.

Apart from that, I think the feature is interesting. Would you like to send a PR? Otherwise I would be glad to do it.

**Comment by chalasr** [comment]
I propose to allow:

```yml
firewall_1:
    provider: default_firewall_provider
    guard:
        authenticators:
            - "first_authenticator_using_default_provider"
            - { id: "second_authenticator_using_given_provider", provider: "given_provider" }
```

WDYT?
