### ISSUE TITLE
Cache is not invalidated for routes with container parameters

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#21426]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

While using a `@Route` annotation in the controller, the `dev` cache is properly invalidated, if the route requirements are written directly in the annotation. But when using [container parameters in requirements](http://symfony.com/doc/current/routing/service_container_parameters.html), the cache is not invalidated automatically and you need to delete `cache/dev` directory manually.

See the example: If another option is added to config, the route is not matched until the cache directory is manually deleted:

```yaml
# config.yml
parameters:
    routing.type_slug: article|category
```

```php
// DefaultController.php
/**
 * @Route("/{typeSlug}/", name="homepage", requirements={"typeSlug": "%routing.type_slug%"})
 */
public function indexAction(string $typeSlug, Request $request)
```

**Comment by iltar** [comment]
I think this is a limitation, as otherwise every single change in your controller would cause a rebuild of the container.

**Comment by mhujer** [comment]
Could it be the other way around? Change in the container (`config.yml`) should cause a rebuild of a routing cache.

Before:
```yaml
# config.yml
parameters:
    routing.type_slug: article|category
```


After (added `comment`, which does not work without removing the cache):
```yaml
# config.yml
parameters:
    routing.type_slug: article|category|comment
```

I understand that it is trade-off between fast page load in development environment and cache freshness. If it can't be easily fixed, maybe mentioning it in the docs would be enough (as it isn't widely used feature).
