### ISSUE TITLE
Globally assigning correct error code for NotFoundHttpException and MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#21422]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.4

I'm not sure if a similar thing is in place or not so suggesting a global setting for `@Route` and `@Method` annotation exceptions in controllers.

Currently if I call a non-existent endpoint or an end-point with a wrong method, I get errors below.

**NotFoundHttpException**
```
{
  "error": {
    "code": 0,
    "message": "No route found for \"GET \/1\/whatever\""
  }
}
```

**MethodNotAllowedHttpException**
```
{
  "error": {
    "code": 0,
    "message": "No route found for \"PUT \/1\/whatever\": Method Not Allowed (Allow: POST)"
  }
}
```

I'm currently manually correcting `code` with an EventListener but something like below would be ideal.

**app/config/routing.yml**
```
my_api:
    resource:   "@MyApiBundle/Controller/"
    type:   annotation
    prefix: /1/
    errors:
        method: 405
        route: 404
```

Or maybe something like below per controller.

```
    /**
     * @Method({"GET"}, error_code="405")
     * @Route("/{id}}", requirements={"id"=.....}, error_code="404")
     */
```
Thanks
