### ISSUE TITLE
ChainUserProvider: match UserProvider to Authenticator?

### ISSUE THREAD

**Issue by MalteWunsch** [symfony/symfony#21479]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.8.0 - 3.2.2

In my application, I have several authentication mechanisms and each one has it's own UserProvider. The security.yml looks like this:

```yml
security:
    providers:
        chain_provider:
            chain:
                providers: [provider1, provider2]
        provider1: ...
        provider2: ...

    firewalls:
        main:
            guard:
                authenticators:
                    - authenticator1
                    - authenticator2
                entry_point: authenticator1
```

Now, as far as I understand, [ChainUserProvider::loadUserByUsername](https://github.com/symfony/symfony/blob/v3.2.2/src/Symfony/Component/Security/Core/User/ChainUserProvider.php#L45-L58) lets each chained provider try to load a user with the provided credentials until one user is found or all providers have tried unsuccessfully. I.e. provider1 will eventually try to load a user with the credentials provided by authenticator2. If user1's credentials for authenticator1 are the same as user2's credentials for authenticator2, user2 would be logged in as user1 due to the order of the chained user providers. I think this should be prevented.

My idea to work around that problem was to tie providers to authenticators, so that a provider would only accept credentials from it's corresponding authenticator(s). If loadUserByUsername would not only have one parameter for the username, but a second one for the calling authenticator, I could've implemented that check in this method.

Makes sense? Is there a already a better way to tie the both of them? Or am I missing another concept here?

**Comment by chalasr** [comment]
Related to #21391 (a duplicate in fact). 
There is currently no way to define one provider per authenticator. IMHO it makes sense to remove this limitation by allowing e.g:

```yml
firewall_1:
    provider: default_firewall_provider
    guard:
        authenticators:
            - "first_authenticator_using_default_provider"
            - { id: "second_authenticator_using_given_provider", provider: "given_provider" }
```

I have this ready to propose, just waiting for a maintainer thought on the related ticket.
