### ISSUE TITLE
With 3.2.4 I can't inject AnnotationReader anymore

### ISSUE THREAD

**Issue by lbayerl** [symfony/symfony#21648]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.4

Trying to inject `AnnotationReader $reader` in a service with `arguments: ['@annotation_reader'] worked fine in Symfony 3.2.3 but since upgrading to 3.2.4 it fails with:

```
construct() must be an instance of Doctrine\Common\Annotations\AnnotationReader, instance of Doctrine\Common\Annotations\CachedReader given
```

Might be worth mentioning that I am trying to inject it in an EventListener:

```yml
    request_cache_listener:
        class: MyCompany\MyBundle\EventListener\MyRequestListener
        arguments: ['@annotation_reader']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
```

This is probably caused by: https://github.com/symfony/symfony/pull/21556
