### ISSUE TITLE
Blank or null assets:packages:*:version_strategy does not override default version_strategy

### ISSUE THREAD

**Issue by AaronM-Cloudtek** [symfony/symfony#21683]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

With the following asset package config:

```yaml
    framework:
        assets:
            version_strategy: 'app.asset.versioning.my_strategy'
            packages:
                alternate:
                    version_strategy: ~    #also tried '' here with the same result
```

Calls to twig helper `asset('path/to/asset.css', 'alternate')` are still piped through app.asset.versioning.my_strategy.

I was only able to get the desired behavior by specifying `version_strategy: 'assets.empty_version_strategy'` for the alternate package.
