### ISSUE TITLE
[DI] Autowire arguments that are container parameters

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21699]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

These days we're updating the Symfony Demo app to use the new service configuration proposed for Symfony 3.3. See https://github.com/symfony/symfony-demo/pull/483/files

One of the things I like the least is this config:

```yaml
services:
    AppBundle\Twig\AppExtension:
        $locales: '%app_locales%'

    AppBundle\EventListener\RedirectToPreferredLocaleSubscriber:
        $locales: '%app_locales%'

    AppBundle\EventListener\CommentNotificationSubscriber:
        $sender: '%app.notifications.email_sender%'
```

Having to create that boring config just to pass some container parameters destroys the purpose of this new config being RAD, etc.

### Proposal

Would it make any sense to "autowire the parameters"?

#### Before

```php
class AppExtension extends \Twig_Extension
{
    // ...

    public function __construct(Markdown $parser, $locales)
    {
        // ...
    }

    // ...
}
```

```yaml
services:
    AppBundle\Twig\AppExtension:
        $locales: '%app_locales%'
```

#### After

```php
class AppExtension extends \Twig_Extension
{
    // ...

    public function __construct(Markdown $parser, $locales = '%app_locales%')
    {
        // ...
    }

    // ...
}
```

**Comment by nicolas-grekas** [comment]
Unless I didn't understand well, this has been tried in #20738 and abandoned.

**Comment by nicolas-grekas** [comment]
Hum, that's not exactly the same - then I have an objection: the class is not usable anymore with Symfony's DIC, which is the one supposed to resolve the `%app_locales%`.
An annotation would be better, by providing decoupling.

**Comment by GuilhemN** [comment]
What about using named arguments like that?
```yml
services:
    AppBundle\Controller\:
        resource: '../../src/AppBundle/{EventListener,Form/Type,Security,Twig,Utils}'
        arguments:
            $locales: '%app_locales%'
            $sender: '%app.notifications.email_sender%'
```

**Comment by GuilhemN** [comment]
Oops [looks like it's not possible](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/ResolveNamedArgumentsPass.php#L67)... Maybe we should allow it then?

**Comment by nicolas-grekas** [comment]
@GuilhemN see https://github.com/symfony/symfony/projects/2#card-1770476 - which to be made to work should apply these conditionally

**Comment by GuilhemN** [comment]
What do you mean by "conditionally"?

**Comment by nicolas-grekas** [comment]
Dunno yet, this is only a project card, needs more thought :)
We could also handle a conditional syntax, eg. `$?locales: '%app_locales%'`

**Comment by GuilhemN** [comment]
Ok I'll give it a try, seems great :)

**Comment by iltar** [comment]
While this may seem like a nice solution, there's a few drawbacks:
 - What if you want an int? You'll never be able to type-hint that
 - What if the value was not found with auto-wiring? I will end up with `%app_locales%`

```
public function __construct(Markdown $parser, $locales = '%app_locales%');
```

**Comment by magarzon** [comment]
What about a custom annotation?

Makes sense? It's something that I can't see against using annotation for this?

**Comment by dunglas** [comment]
@magarzon I'm not a found of using (non-standard) annotations for DI: https://github.com/symfony/symfony/issues/21103#issuecomment-270062867

But while this PR is nice, I don't like having to add Symfony specific syntaxes (`'%locales%'`) in the code itself, the code (especially in a service) should be framework agnostic. From that POV, https://github.com/symfony/symfony/pull/20738 is better (IMO).

**Comment by TomasVotruba** [comment]
With bold news in Symfony 3.3 like PSR-4 service autodiscovery, I think this makes more sense to current coding context now.


Why? Because I cannot use this awesome PSR-4 autodiscovery on most of my services :(

Instead, I have to write them manually all one by one.

```yaml
parameters:
    twitter_name: 'VotrubaT'
    site_ur: 'https://tomasvotruba.com'
    source_directory: '%kernel.project_dir%/../../../source'
    minimal_gap_in_days: 4 # how many days to wait before publishing another Tweet

    twitter_consumer_key: "..."
    twitter_consumer_secret: "..."
    twitter_oauth_access_token: "..."
    twitter_oauth_access_token_secret: "..."

services:
    TomasVotruba\Website\TweetPublisher\PostTweetsProvider:
        arguments:
            - '%site_url%'
            - '%source_directory%'

    TomasVotruba\Website\TweetPublisher\PostsProvider:
        arguments:
            - '%source_directory%'

    TomasVotruba\Website\TweetPublisher\TwitterApi\TwitterApiWrapper:
        arguments:
            - '%twitter_name%'

    TomasVotruba\Website\TweetPublisher\TweetPublisher:
        public: true # for bin/tweet-new-posts container fetch
        arguments:
            - '%minimal_gap_in_days%'

    # Twitter API
    TomasVotruba\Website\TweetPublisher\TwitterApi\TwitterApiFactory:
        arguments:
            - '%twitter_consumer_key%'
            - '%twitter_consumer_secret%'
            - '%twitter_oauth_access_token%'
            - '%twitter_oauth_access_token_secret%'
```


### I'd love something like this

- explicit
- time-saving
- typo-proof
- make use of PSR-4 way

```yaml
services:
    _defaults:
        autowire_arguments: true

    TomasVotruba\Website\TweetPublisher\:
        resource: ../
```

What do you think?
