### ISSUE TITLE
Fragment support can't be disabled entirely?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21733]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| Symfony version  | all

### Context

In a Symfony app I'm disabling anything that I don't need. Fragments are one of those features.

I have this config:

```yaml
framework:
    fragments:
        enabled: false
    #esi: ~
```

### Problem

In the `appProdProjectContainer.php` container I still see a lot of things related to fragments:

**1. Services**

```php
'fragment.handler' => 'getFragment_HandlerService',
'fragment.renderer.esi' => 'getFragment_Renderer_EsiService',
'fragment.renderer.hinclude' => 'getFragment_Renderer_HincludeService',
'fragment.renderer.inline' => 'getFragment_Renderer_InlineService',
'fragment.renderer.ssi' => 'getFragment_Renderer_SsiService',
```

**2. Parameters**

```php
'fragment.renderer.hinclude.global_template' => NULL,
'fragment.path' => '/_fragment',
```

Moreover, there are some services that consider fragments mandatory:

```xml
<!-- @TwigBundle/Resources/config/twig.xml -->
<service id="twig.runtime.httpkernel" class="Symfony\Bridge\Twig\Extension\HttpKernelRuntime">
    <argument type="service" id="fragment.handler" />
    <tag name="twig.runtime" />
</service>
```

### Solution

I expected all the fragment methods/params gone and the Twig service to use `on-invalid="null"`.

**Comment by javiereguiluz** [comment]
I've just checked this again and the problem persists. In a Symfony Flex app, where fragment support is disabled:

```yaml
framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: null
    #http_method_override: true
    #trusted_hosts: null
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    #session:
    #    handler_id: session.handler.native_file
    #    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
```

I see this in the compiled container:

```php
            'fragment.handler' => 'getFragment_HandlerService',
            'fragment.renderer.esi' => 'getFragment_Renderer_EsiService',
            'fragment.renderer.hinclude' => 'getFragment_Renderer_HincludeService',
            'fragment.renderer.inline' => 'getFragment_Renderer_InlineService',
            'fragment.renderer.ssi' => 'getFragment_Renderer_SsiService',
```

And those services are like this:

```php
    protected function getFragment_HandlerService()
    {
        return $this->services['fragment.handler'] = new \Symfony\Component\HttpKernel\DependencyInjection\LazyLoadingFragmentHandler(${($_ = isset($this->services['service_locator.e64d23c3bf770e2cf44b71643280668d']) ? $this->services['service_locator.e64d23c3bf770e2cf44b71643280668d'] : $this->getServiceLocator_E64d23c3bf770e2cf44b71643280668dService()) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->get('request_stack')) && false ?: '_'}, true);
    }
```
