### ISSUE TITLE
Add support for using vairable from "path" in template

### ISSUE THREAD

**Issue by Cach** [symfony/symfony#21732]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

Hello. Can you add pls support for using vairable from "path" in template

I mean:

```yaml
my_route_name:
    path: /pages/{name}
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    AppBundle:Templates:{name}.html.twig
```

Thx!

**Comment by evo9** [comment]
It would be very useful

**Comment by planv** [comment]
That would be fine for me too. Thx

**Comment by iltar** [comment]
Why would you add view related config to your routing config?

**Comment by javiereguiluz** [comment]
@iltar because for static pages (terms & conditions, privacy, about us, etc.) is very boring to create:

1. One route for each of them
2. A simple controller that takes the page slug and renders the page: for `/pages/privacy`, render `pages/privacy.html.twig`, etc.

**Comment by iltar** [comment]
That looks like something needing to resolve the template existence and throw a 404 if it doesn't exist. Sounds fragile and more of a CMF/CMS thing to me to be honest.

I'd rather see something like:
```php
public function __invoke(string $name, /* or via PC */ Page $page)
{
    return new Template('AppBundle:Templates:'.$name.'.html.twig');
    // or
    return new Template('AppBundle:Templates:'.$page->getName().'.html.twig');
}
```

A mix between `@Template` and return new response. Advantage here is that you could even do something like a custom template object and resolve the logic of a 404 if the template doesn't exist in there.
```php
public function __invoke(Page $page)
{
    return new DynamicPageTemplate($page);
}
```

_Maybe a nice feature for Symfony? I would prefer this over the annotation and still saves me from injecting the templating when not using the base controller_

**Comment by stof** [comment]
@javiereguiluz you can keep using a single route and a single controller. Just not the FrameworkBundle one:

```yaml
my_route_name:
    path: /pages/{name}
    methods: GET
    defaults:
        _controller: AppBundle:Static:page
    # you probably don't want to allow using arbitrary templates, so you need to restrict
    # the names being supported.
    requirements:
        name: privacy|about|terms
```

```php
namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class StaticController extends Controller
{
    public function pageAction($name)
    {
        return $this->render('static_pages/'.$name.'.html.twig');
    }
}
```
