### ISSUE TITLE
Symfony ERR_CONNECTION_RESET?

### ISSUE THREAD

**Issue by Cypaubr** [symfony/symfony#21812]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

Hello, I recently experienced a "symfony maximum function nesting level of 256..." error on my project after updating it via composer.
To "fix" this issue, I added the `xdebug.max_nesting_level = 1000` in my php.ini file.

Now when I try to access a firewall protected route, an ERR_CONNECTION_RESET error is thrown by my browser.

Some lines of my PHP error log refers to a firewall exception but I never touche my firewall config.

Thanks.

**Comment by Incognito** [comment]
Are you able to share the call stack? I'm using 3.2.4 and do not encounter this error.

**Comment by Cypaubr** [comment]
Here is the callstack from php_error.log : [http://pastebin.com/nCQ1NUTV](http://pastebin.com/nCQ1NUTV)

**Comment by Incognito** [comment]
In the past I've been mislead by apache logs, are you also looking at the apache process log in addition to your vhost's error log? Do you see more meaningful errors using the symfony server `bin/console server:start` ?

Based on the callstack you've provided it looks like the Security component exception listener is handling an auth exception and attempting authentication again.

I can't really rule out your implementation of the security configuration file not being an issue, have you followed the upgrading guide on this topic, and if so, are you willing to share that file?

**Comment by Cypaubr** [comment]
The Symfony server does not gives further information about the issue.

Sure, here is my security.yml:
```yml
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        PlayBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db:
            entity:
                class: PlayBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        register:
            pattern: ^/register
            anonymous: true

        main:
            pattern: ^/
            anonymous: false
            security: true
            provider: db
            form_login:
                login_path: play_login
                check_path: play_login_check
                use_forward: true
                post_only: true
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path: play_logout
                target: play_homepage
                invalidate_session: true
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                secure: true
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: [IS_ANONYMOUS,IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/register, roles: [IS_ANONYMOUS,IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/, roles: ROLE_USER }
```
