### ISSUE TITLE
Custom Matcher

### ISSUE THREAD

**Issue by ben29** [symfony/symfony#21944]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.x

trying to do:
http://symfony.com/doc/current/profiler/matchers.html

```yaml
config.yml:
    profiler:
        matcher:
          service: app.super_admin_matcher
```

when trying to logout on my website.
i'm getting

> ERR_CONNECTION_RESET

also i try on last symfony 3.2.5
still not work

**Comment by xabbuh** [comment]
Are you sure that this is related to the profiler configuration? I mean does the problem go away when you revert your changes to the profiler config?

**Comment by ben29** [comment]
sure:
services.yml

  app.super_admin_matcher:
      class: AppBundle\Profiler\SuperAdminMatcher
      arguments: ['@security.authorization_checker']
      public: false

SuperAdminMatcher.php:

```
<?php
namespace AppBundle\Profiler;

use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestMatcherInterface;

class SuperAdminMatcher implements RequestMatcherInterface{
    protected $authorizationChecker;
    public function __construct(AuthorizationCheckerInterface $authorizationChecker){
        $this->authorizationChecker = $authorizationChecker;
    }
    public function matches(Request $request){
        return $this->authorizationChecker->isGranted('ROLE_SUPER_ADMIN');
    }
```
}

**Comment by Nek-** [comment]
Hello,

I tested with Symfony 3.2.5 and FOSUser with a simple matcher:

```php
namespace AppBundle;

use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestMatcherInterface;

class TestMatcher implements RequestMatcherInterface
{
    protected $authorizationChecker;

    public function __construct(AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    public function matches(Request $request)
    {
        return $this->authorizationChecker->isGranted('ROLE_SUPER_ADMIN');
    }
}
```

I'm successfully logged with `ROLE_SUPER_ADMIN` and I have my profile data in the cache directory. This issue doesn't look related to Symfony but to your code.

**Comment by ben29** [comment]
everything works before i did this.
only when i add the service it's stop to work

**Comment by Nek-** [comment]
Here is the project I tested with. Can you run it to see if it's related to your system configuration ?

```
php bin/console ca:cl --env=prod
php bin/console ser:run --env=prod
```

Thanks.
[TestProfilerMatcher.zip](https://github.com/symfony/symfony/files/830820/TestProfilerMatcher.zip)

**Comment by Nek-** [comment]
Using FOS or not is not the point but this demonstrates that it works perfectly with user role data. Sorry, this is not a support forum. Feel free to give information about your problem on stack overflow so people can help you to solve it!

(here is not the good place and we don't have any information that may help us to find what's your problem)

**Comment by ben29** [comment]
but it's problem on symfony. issue with symfony
i report a problem to symfony

**Comment by Pierstoval** [comment]
@ben29 your problem sounds more related to how you implemented the matcher and not to symfony itself.

If you want support for Symfony, go to stackoverflow or IRC channel.

Symfony issues are used bugs _in Symfony core_, not to support.

=> http://symfony.com/doc/current/contributing/code/bugs.html

**Comment by ben29** [comment]
1. again it's symfony doc for that i did 100% copy past like the doc
2. how can i trace the error if it's going to connection reset?
3. only this service not working anymore. when i use symfony 3.1 it's worked perfect!

**Comment by xabbuh** [comment]
Well, without being able to reproduce your issue it will be hard to help you. Do you see anything else in the logs (either in the application logs, the web server's log or in the logs of PHP FPM)? Can you try to reproduce your issue on the Symfony Standard Edition and push such an example to GitHub?

**Comment by ben29** [comment]
i did error_reporting i check few times on error log apache
nothing

**Comment by ben29** [comment]
I try this on my computer:

> [Thu Mar 09 22:23:44.682505 2017] [:error] [pid 58549] [client 127.0.0.1:60273] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 77 bytes) in /Library/WebServer/Documents/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php on line 57

i put memmory limit to php 512MB!

the wired thing.
when i doing

```
    public function matches(Request $request)
    {
        die("dead");
        return $this->authorizationChecker->isGranted('ROLE_SUPER_ADMIN');
    }
```

it's shows dead...

try anothr thing:

```
    public function matches(Request $request)
    {
        if ($this->authorizationChecker->isGranted('ROLE_SUPER_ADMIN')){
            die("true...");
        }
        else{
            die("false.....");
        }
    }
```

it's stuck

doing:

```
    public function matches(Request $request)
    {
        return true;
    }
```

works!
it's means problem here:
$this->authorizationChecker->isGranted('ROLE_SUPER_ADMIN')

try also ROLE_ADMIN

**Comment by ben29** [comment]
my security.yml
```
    role_hierarchy:
        ROLE_USER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER,ROLE_EVENT_CREATE]
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]
```

**Comment by ben29** [comment]
login : 
` Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /Library/WebServer/Documents/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php on line 57, referer: https://127.0.0.1/app_dev.php/`

so only the problem it's on 
AuthorizationChecker.php

thanks!

**Comment by ben29** [comment]
@xabbuh - see all the comment i did big debug

**Comment by xabbuh** [comment]
Can you show your complete security config?

**Comment by ben29** [comment]
yes:
```
security:
    #access_denied_url: '/'
    #session_fixation_strategy: migrate
    #always_authenticate_before_granting: true
    #erase_credentials: true
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 15
    providers:
        users_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            provider: users_provider
            anonymous: ~
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_generator: security.csrf.token_manager
                use_forward: true
                always_use_default_target_path: false
                use_referer: false
                username_parameter: _username
                password_parameter: _password
                post_only: true
                remember_me: true
                require_previous_session: true
            logout:
                path: app_logout
                invalidate_session: false
            remember_me:
                secret: "%secret%"
                lifetime: 3600
                path: /foo
                secure: true
                httponly: true
                always_remember_me: false
                remember_me_parameter: _remember_me
    role_hierarchy:
        ROLE_USER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER,ROLE_EVENT_CREATE]
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/logout, roles: ROLE_USER }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/, requires_channel: https }
```

**Comment by ben29** [comment]
i get the problem!!!
when i removed the 
`use_forward: true`
everything is working!!

why it's give : 

> [Fri Mar 10 00:16:46.630402 2017] [:error] [pid 58654] [client 127.0.0.1:60781] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in /Library/WebServer/Documents/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php on line 57, referer: https://127.0.0.1/app_dev.php/login


just beacuse this option ?
something wired!
@xabbuh

**Comment by ben29** [comment]
so the bug happen when i enable use_foward
can it be fixed?

**Comment by javiereguiluz** [comment]
@ben29 thanks for all the debugging that you did and thanks to all the reviewers for your help.

So, in summary, if you use the `use_forward: true` option, the application goes out of memory and when you don't use it, everything works perfectly. So this definitely looks like a Symfony bug.

**Comment by xabbuh** [comment]
Is someone able to fork the Symfony Standard Edition, and make these changes so that we can reproduce the issue and investigate how to fix it?

**Comment by ben29** [comment]
@javiereguiluz yea it's goes to out of memory just when i set this setting.
@xabbuh i did it in 5 projects on symfony-demo , symfony standard-edition.
both same problem
as i said to you it's bug and i prove it =]

**Comment by ben29** [comment]
found second problem...
my user now is : ROLE_SUPER_ADMIN

security yml:
```
    role_hierarchy:
        ROLE_USER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER,ROLE_EVENT_CREATE]
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/logout, roles: ROLE_USER }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: https }
```
config.yml - about profiler

    profiler:
        matcher:
          service: app.super_admin_matcher

SuperAdminMatcher.php:
```
<?php
namespace AppBundle\Profiler;

use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestMatcherInterface;

class SuperAdminMatcher implements RequestMatcherInterface
{
    protected $authorizationChecker;

    public function __construct(AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    public function matches(Request $request)
    {
        return $this->authorizationChecker->isGranted('ROLE_SUPER_ADMIN');
    }
}
```
trying to login in : 
https://127.0.0.1/app_dev.php/login

no errors. and don't do any login

no errors on dev.log:

> 
> [2017-03-12 18:14:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_controller":"AppBundle\\Controller\\SecurityController::loginAction","_route":"app_login"},"request_uri":"https://127.0.0.1/app_dev.php/login","method":"GET"} []
> [2017-03-12 18:14:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
> 

and no errors on apache
