### ISSUE TITLE
Routing : Giving {placeholders} a Default Value not work in yml

### ISSUE THREAD

**Issue by Thibault34** [symfony/symfony#21963]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

Hello,
When I use YML for routing, Giving {placeholders} a Default Value not work

```yaml
 test_page:
    path:      /test/{page}
    defaults:  { _controller: DDMAppBundle:AdminDevice:index, page: 1 }
    requirements:
        page: '\d+'
```

`/test/1` found but `/test` and `/test/` not found : `No route found for "GET /test/"`

When I use annotation :

```php
    /**
     * @Route("/test/{page}", name="test_page", requirements={"page": "\d+"})
     */
```

`/test/1` and `/test/` found.
