### ISSUE TITLE
[HttpFoundation] Wrong media_type returned when using Accept header. API Versioning unusable when using media_type resolver.

### ISSUE THREAD

**Issue by vpassapera** [symfony/symfony#21974]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x

Using the latest FOSRestBundle, JMSSerializer and Symfony.

Given the following configuration:

```yml

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ 'html', 'json', 'application/javascript', 'text/css', '*/*'], fallback_format: html, prefer_extension: true }
    body_converter:
        enabled: true
        validate: true
    view:
        mime_types:
            json:
              - 'application/json'
              - 'application/json;version=1.0'
              - 'application/json;version=1.1'
        view_response_listener: 'force'
        formats:
            xml:  false
            json: true
        templating_formats:
            html: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    versioning:
        enabled: true
        resolvers:
            query:
                enabled: false
            custom_header:
                enabled: false
            media_type:
                enabled: true
```

**Expected Result:**

When making a request with the following header:
```
Accept: application/json;version=1.1
```

The version chosen should be 1.1 (This comes from the Request object)

**Actual Result:**

Symfony selects the first element in the media_type array regardless of the Accept header.

In the previous case, it returns 'application/json'.

---

I believe this is due to line 1335 inside of Request.php

```php
return isset(static::$formats[$format]) ? static::$formats[$format][0] : null;
```

As we can see, it is hard-coding the first element of the array as the result value, when it should be looking to see if the one requested is actually supported.

This could be handled by a custom RequestListener, but this is not what the documents say to do. Which leads me to believe this is a bug.

The Symfony documents (Especially for FOSRest) do not list a special requirement of a custom request listener. In fact, it very explicitly says the following:

https://symfony.com/doc/master/bundles/FOSRestBundle/versioning.html#configure-fosrestbundle-to-use-the-api-versioning
```
If you want to version by Accept header, you will need to do the following:

The format listener must be enabled
See Format Listener

The client must pass the requested version in his header like this :
Accept:application/json;version=1.0

You must configure the possible mime types for all supported versions:
fos_rest:
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']

Use the JMSSerializer with the API versioning

You should have tagged your entities with version information (@Since, @Until ...)

See this JMS Serializer article for details about versioning objects.

That's it, it should work now.
```
PR opened.
