### ISSUE TITLE
[DI] PSR4 loader suggestions

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#22016]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.0 (master)

After playing a bit with https://github.com/symfony/symfony/pull/21289 I would like to make a few suggestions :)

The first suggestion would be to allow the usage of parameters to define the path of the resource. If I take the following example:

``` yaml
# app/config/services.yml

services:
    App\:
        resource: '../../src/Bundle/{Action,Console}'
```

Instead of that, I would prefer:

``` yaml
# app/config/services.yml

services:
    App\:
        resource: '%kernel.root_dir%/../src/Bundle/{Action,Console}'
```

I personally find it better, as it makes it easier to follow even if you are deeper in a hierarchy (I have an example where I have `../../../../src/blabla`... it's not very readable). 

Second suggestion (nitpicking) is about the syntax. The following doesn't work:

``` yaml
# app/config/services.yml

services:
    App\:
        resource: '../../src/Bundle/{Action, Console}'
```

Because of the extra space. I find that "stupid". I think if it doesn't cost much to do so, users should be free to add an extra space to make things more readable if they find it more readable that way.

Third suggestion (minor), let's take the following example:

``` yaml
# app/config/services.yml

services:
    App\:
        resource: '../../src/Bundle/{Action}'
```

why the brackets? You shouldn't IMO.

/cc @nicolas-grekas @dunglas (I remember requesting something similar with in https://github.com/dunglas/DunglasActionBundle/issues/52, but maybe you have a different opinion for this one).

**Comment by robfrawley** [comment]
I am completely in agreeance on point one. I disagree with the second am indifferent toward the third, though.

**Comment by GuilhemN** [comment]
Your first point seems complicated to realize as prototypes are resolved in the loaders, so not all parameters are defined yet (though it would work for `%kernel.root_dir%`).

**Comment by nicolas-grekas** [comment]
> allow the usage of parameters to define the path of the resource

note that the mechanism uses the locators of the config component so special notations should work (`@MyBundle...`). This could work only with parameters that are defined at the time the loader is used. If you'd like to give it a try, would calling `$container->getParameterBag()->resolveValue()` in `DependencyInjection\Loader\FileLoader::findClasses()` make it possible?

> extra space

two issues that make this suggestions impossible: technically we use the native `glob` function and we're not going to re-implement it. More importantly, space is a legal character in file names, so this could create an ambiguity (which is why the native glob doesn't behave like you describe.)

> 3rd point: 

just do deeper psr-4 mappings
```yaml
services:
    App\Action\:
        resource: '../../src/Bundle/Action'
```

**Comment by theofidry** [comment]
For the first point: let's do this. Will see if I have time this weekend for this as I already have a few other Symfony issues to deal with :)

**Comment by sstok** [comment]
If it's unlikely to ever register files with a space simply removing them would solve it.
But I agree we shouldn't complete things.

**Comment by nicolas-grekas** [comment]
See #22372

**Comment by kbond** [comment]
Not sure how feasible this would be but I would like to have multiple declarations with the same psr4 prefix. Example:

```yaml
services:
    command_handlers:
        psr4_prefix: App\Domain
        resource: ../../src/Domain/*/CommandHandler
        tags: [command_handler]

    event_subscribers:
        psr4_prefix: App\Domain
        resource: ../../src/Domain/*/EventSubscriber
        tags: [event_subscriber]
```
