### ISSUE TITLE
[Validator] Argument 1 passed to Validator (as a service) is null

### ISSUE THREAD

**Issue by thomas2411** [symfony/symfony#22077]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

Based on http://symfony.com/doc/current/validation/custom_constraint.html I have prepared a Custom Validator as a service, like this:
```
    mm_user.contains_import_validator:
        class: MyBundle\UserBundle\Validator\Constraints\ImportValidator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@kernel"
            - "@monolog.logger.mm"
        tags:
            - { name: validator.constraint_validator }
````
My Validator __construct looks like this:

```
    /**
     * @var EntityManager
     */
    protected $em;

    /**
     * @var KernelInterface
     */
    protected $kernel;

    /**
     * @var Logger
     */
    protected $logger;

    public function __construct(EntityManager $em, KernelInterface $kernel, Logger $logger)
    {
        $this->em = $em;
        $this->kernel = $kernel;
        $this->logger = $logger;
    }
```

And this issue this error:

```
Catchable Fatal Error: Argument 1 passed to MyBundle\UserBundle\Validator\Constraints\ImportValidator::__construct() must be an instance of Doctrine\ORM\EntityManager, null given, called in /.../vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php on line 89 and defined
```

The same situation is when I want to pass my own service to Validator service.

Btw in the docs in Service example only XML implementation shows that we can pass service as an argument.
