### ISSUE TITLE
[Route] Route files not loaded from directory

### ISSUE THREAD

**Issue by BabakMN** [symfony/symfony#22092]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

> The resource key loads the given routing resource. In this example the resource is a directory, where the @AppBundle shortcut syntax resolves to the full path of the AppBundle. **When pointing to a directory, all files in that directory are parsed and put into the routing.**

I have,
```yaml
# app/config/routing.yml
public:
    resource: '@AppBundle/Resources/config/routing/public/'
```

And in `@AppBundle/Resources/config/routing/public/` there are more yaml files with routes inside of them.

```yaml
# src/AppBundle/Resources/config/routing/public/homepage.yml
homepage:
    path: /
    defaults:
        _controller: AppBundle:HomePage:show
```

If I make the first file point to the route file directly it works.

```yaml
# app/config/routing.yml
# works (loads one route as expected)
public:
    resource: '@AppBundle/Resources/config/routing/public/homepage.yml'
```

I tried a few variations but no luck. Am I misunderstanding or is this a bug?

**Comment by xabbuh** [comment]
In your example, you are missing the `type: annotation` part.

**Comment by BabakMN** [comment]
Just tried with `type: annotation` and it still didn't work. I thought that was for PHP files with route annotations? In this case I just want to load a bunch of route files in yaml format from a directory.

**Comment by jakzal** [comment]
@BabakMN if you use the yaml format you should add `type: yaml`.

**Comment by BabakMN** [comment]
@jakzal thanks I just tried that but it didn't work either.

```yaml
# app/config/routing.yml
public:
    resource: '@AppBundle/Resources/config/routing/public'
    type: yaml
```

Tried with both `yaml` and `yml`. Tried with both `@AppBundle/Resources/config/routing/public` and `@AppBundle/Resources/config/routing/public/` (trailing slash).

> Cannot load resource "@AppBundle/Resources/config/routing/public/". Make sure the "AppBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@AppBundle/Resources/config/routing/public/" is not empty.

`FileLoaderLoadException`
