### ISSUE TITLE
[Yaml] file with nested arrays is dumping with keys where inappropriate

### ISSUE THREAD

**Issue by vaneatona** [symfony/symfony#22100]
| Q                           | A
| ----------------- | -----
| Bug report?          | yes
| Symfony version  | ^3.2"

I am working with the following array. I want to convert it to yaml.

        $finalArray = [
            'enabled' => [
                '\Helper\Api',
                '\Helper\Data'
            ]
        ];

`Yaml::dump($finalArray, 3);` This will produce...

```
enabled:
    - \Helper\Api
    - \Helper\Data
```
Perfect. That's what I want. Now, I need to add to that same array.

```
        $finalArray = [
            'enabled' => [
                '\Helper\Api',
                '\Helper\Data',
                'REST' => [
                    'url' => 'http://devel.membership.api.naiadsystems.com',
                    'depends' => 'PhpBrowser',
                    'part' => 'Json'
                ]
            ]
        ];
```
`Yaml::dump($finalArray, 3);` This will produce...
```
enabled:
    0: \Helper\Api
    1: \Helper\Data
    REST:
        url: 'http://devel.membership.api.naiadsystems.com'
        depends: PhpBrowser
        part: Json
```
Now my Yaml file is wrong. This is not what I want. I should be able to produce
```
enabled:
    - \Helper\Api
    - \Helper\Data
    REST:
        url: 'http://devel.membership.api.naiadsystems.com'
        depends: PhpBrowser
        part: Json
```

**Comment by GuilhemN** [comment]
Afaik this is not valid yaml.
You should instead update your array to not mix numeric and alphabetical keys.

**Comment by vaneatona** [comment]
Can you show me where in the yaml spec it states this is not allowed? I couldn't find it. Also, the yaml parsers are fine with it.

**Comment by fabpot** [comment]
You are mixing two concepts: YAML sequences and YAML mappings. PHP is probably the only language where both concepts are possible in a single data structure, an array.

**Comment by vaneatona** [comment]
Is this not a php yaml interpreter? I can't find anywhere in the yaml spec where this is not allowed. In fact, I've found this format used in examples.

Is this closed because ya'll refuse to fix or because you don't want to do it yourself?

**Comment by fabpot** [comment]
@vaneatona Can you link to such examples?

**Comment by vaneatona** [comment]
https://learnxinyminutes.com/docs/yaml/ <--- Not official
http://www.yaml.org/spec/1.2/spec.html#id2790320 <--- Official

**Comment by fabpot** [comment]
I don't see any mix of a mapping and a sequence in the examples you referenced.

**Comment by vaneatona** [comment]
Official: Ex. 7.14

and...
```# Sequences (equivalent to lists or arrays) look like this:
a_sequence:
    - Item 1
    - Item 2
    - 0.5 # sequences can contain disparate types.
    - Item 4
    - key: value
      another_key: another_value
    -
        - This is a sequence
        - inside another sequence
```

**Comment by fabpot** [comment]
The value under `a_sequence` is a sequence. The `key`/`another key` is a mapping in the sequence. There is no mix between a sequence and a mapping here.

**Comment by vaneatona** [comment]
Perfect. Then we agree the above should be possible.
```
    $foo = [
        'a_sequence' => [
            'Item 1',
            'Item 2',
            '0.5',
            'Item 4',
            'key' => 'value'
        ]
    ];
```
The above array will produce
```
a_sequence:
    0: 'Item 1'
    1: 'Item 2'
    2: '0.5'
    3: 'Item 4'
    key: value
```

**Comment by fabpot** [comment]
No, the YAML you pasted is equivalent to:

```php
    $foo = [
        'a_sequence' => [
            'Item 1',
            'Item 2',
            '0.5',
            'Item 4',
            ['key' => 'value', 'another_key' => 'another_value'],
        ]
    ];
```

**Comment by vaneatona** [comment]
No. I pasted this:
```a_sequence:
    - Item 1
    - Item 2
    - 0.5 # sequences can contain disparate types.
    - Item 4
    - key: value
```

Which your array does not reproduce.

**Comment by GuilhemN** [comment]
```php
    $foo = [
        'a_sequence' => [
            'Item 1',
            'Item 2',
            '0.5',
            'Item 4',
            ['key' => 'value'],
        ]
    ];
```
If you prefer, the conclusion is the same.

**Comment by vaneatona** [comment]
Okay, I concede that point. I was focusing on formatting and missed the similarity.

I still have yet to see anywhere in the yaml documentation where you can't have a sequence and a key-value pair together.

It comes to the question of whether this is intentionally not supported or whether you'll accept a pull request to fix this oversight.

**Comment by GuilhemN** [comment]
It is intentional because probably only PHP supports mixing "sequences" and "mappings". Yaml is a cross-platform language.

**Comment by vaneatona** [comment]
It is cross platform but at the same time, it is not against the docs and this is indeed a php specific parser.

**Comment by GuilhemN** [comment]
Yes it is, mixing a mapping and a sequence block is not allowed by the spec.
e.g.
```yml
enabled:
    0: \Helper\Api
    1: \Helper\Data
    REST:
        url: 'http://devel.membership.api.naiadsystems.com'
        depends: PhpBrowser
        part: Json
```
Is not allowed.

**Comment by GuilhemN** [comment]
Yes, it is mixing a sequence ang a

**Comment by vaneatona** [comment]
Oh, well I asked you to show me where it said that from the beginning. I did look at it, couldn't find.

**Comment by GuilhemN** [comment]
Searching in the spec is time consuming.

http://www.yaml.org/spec/1.2/spec.html#id2797382
Sequence and mapping blocks are managed separately based on the one detected the first.

**Comment by vaneatona** [comment]
Anyhow, I get the feeling regardless of the spec explicitly disregarding or not the answer will be the same.

Thank you for taking the time to have this conversation. I truly appreciate it.

**Comment by GuilhemN** [comment]
It is a bit hard to explain why it is not allowed, the yaml spec is complex and to understand something you quickly have to read half of it.
Here it explains a block is either a mapping or a sequence but it can't be both, and their pattern (or whatever it is called) don't allow mixing their syntaxes.

**Comment by vaneatona** [comment]
I would like to suggest updating the symfony yaml parser to take exception to just that then.

**Comment by xabbuh** [comment]
> I would like to suggest updating the symfony yaml parser to take exception to just that then.

Not sure I understand what you mean. Can you explain?

**Comment by vaneatona** [comment]
Using `use Symfony\Component\Yaml\Command\LintCommand` to parse the above Yaml, which we decided was not valid Yaml, returns that the yaml is valid.

**Comment by xabbuh** [comment]
Not sure what you mean. The YAML format produced by the dumper is valid. That's true. Or which example do you mean that does not end up in a liniting error?

**Comment by vaneatona** [comment]
The first. The one I could not get the dumper to reproduce. The mixing of mapping and sequences.

**Comment by vaneatona** [comment]
Specifically...

```
modules:
    config:
        Db:
            dsn: 'mysql:host=host'
            user: user
            password: password
    enabled:
        - \Helper\Api
        - Db
        - Asserts
        - \Helper\Data
        - REST:
            url: http://url.com/
            depends: PhpBrowser
            part: Json
```

Will yield this result when the linter is run:
` [OK] All 1 YAML files contain valid syntax.`

**Comment by GuilhemN** [comment]
```yml
modules:
    config:
        Db:
            dsn: 'mysql:host=host'
            user: user
            password: password
    enabled:
        - \Helper\Api
        - Db
        - Asserts
        - \Helper\Data
        - REST:
            url: http://url.com/
            depends: PhpBrowser
            part: Json
```
Should already be recognized as valid yaml.
