### ISSUE TITLE
[DependencyInjection] Support local interface/class bindings

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#22167]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3 ? probably 3.4

A great idea came out on Slack about local bindings.
We could allow injecting services based on type hints on a per service/file basis:
```yml
services:
    _defaults:
        bindings:
            BarInterface: '@alternative_bar'

    Foo:
        bindings:
            BarInterface: '@bar'
            $quz: 'quzvalue'
```

This way, `@bar` will be injected in any parameter type hinted as `BarInterface` (in a constructor or a method signature), but only for this service/file.
Note that bindings could be unused, giving a better solution than https://github.com/symfony/symfony/pull/22152 to https://github.com/symfony/symfony/pull/21711.

As named parameters are usable in arguments, bindings could be too:
```yml
services:
    Foo:
        arguments:
            BarInterface: '@bar'
```

ping @nicolas-grekas, @lunetics

**Comment by lunetics** [comment]
I think this is a real useful addition, especially when different configurations/configfiles need different implementations of an interface.

**Comment by ro0NL** [comment]
Nice.

Not sure about

```yml
services:
    Foo:
        arguments:
            BarInterface: '@bar'
```

This more or less violates the fact we chose `$` as a prefix in the first place right? Shouldnt it be prefixed as well? Besides, how does it differ from defining it as a binding... does it override a single bound argument at that position?
