### ISSUE TITLE
[Routing] Using glob Pattern in routing configuration breaks

### ISSUE THREAD

**Issue by lunetics** [symfony/symfony#22160]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | dev-master

Using the glob pattern in the routing component breaks the YamlFileLoader:

e.g. given following config with routing.yml files in the directory
```yaml
domain:
    resource: '../src/Project/**/Infrastructure/Resources/Routing/routing.yml'
    prefix: /
```
results that https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/YamlFileLoader.php#L148 receives an array of RouteCollection and not a single RouteCollection, which results in a fatal error:
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function addPrefix() on array         
```
