### ISSUE TITLE
[DI] Enable factory attribute in service defaults

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#22189]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

Following up on https://github.com/symfony/symfony/issues/22143, the lack of proper error is solved now in https://github.com/symfony/symfony/pull/22185, but the use case for `factory` still seems valid:
```yaml
services:
    _defaults:
        factory:        [ "@doctrine", getRepository ]

    AppBundle\RoleRepository:
        arguments:      [ "AppBundle:Role" ]
    AppBundle\UserRepository:
        arguments:      [ "AppBundle:User" ]
```
It was decided in https://github.com/symfony/symfony/pull/21071#discussion_r94062689 to consider the `factory` attribute a detector flag for real services, but this [has become obsolete](https://github.com/symfony/symfony/pull/22185), and the use case for [default factory settings is there](https://github.com/symfony/symfony/pull/21071#issuecomment-269835047).

Therefore I propose to reallow `factory` in `_defaults` sections.
