### ISSUE TITLE
[Yaml] Inconsistent tag parsing

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#22198]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.x

Seems like the YAML parser doesnt recognize tagged scalar nodes really well;

```yml
a: !foo bar
b: !foo 'bar'
c: !foo
    bar
d: !foo [1, 2, 3]
```

```
array:4 [▼
  "a" => "!foo bar"
  "b" => "!foo 'bar'"
  "c" => TaggedValue {#254 ▶}
  "d" => TaggedValue {#221 ▶}
]
```

Considering DI; both `!iterator foo` and `!iterator [foo]` produce a valid container, but a different value.
