### ISSUE TITLE
[DI] controller.service_arguments does not handle invokable controllers

### ISSUE THREAD

**Issue by BPScott** [symfony/symfony#22202]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0-dev

#21771 added support for the `controller.service_arguments` tag to let you stop using `$this->get()` and instead use autowired arguments for Controller actions. This works great when the controller is a regular method, e.g.:

A services YAML: 
```yaml
services:
    _defaults:
        autowire: true
        public: false

    AppBundle\Controller\:
        resource: '../../src/Controller'
        public: true # Mandatory
        tags: ['controller.service_arguments']
```

A routing YAML:
```yaml
home:
    path: /home
    defaults: { _controller: AppBundle\Controller\HomeController::homeAction }
```

Controller:
```php
class HomeController extends Controller
{
    public function homeAction(Request $request, ProgrammesService $programmesService)
    {
        $programmeCount = $programmesService->countAll();
        // ...
    }
}
```

However it does not work when I attempt to use an invokable Controller:

A routing YAML:
```yaml
home:
    path: /home
    defaults: { _controller: AppBundle\Controller\HomeController }
```

Controller:
```php
class HomeController extends Controller
{
    public function __invoke(Request $request, ProgrammesService $programmesService)
    {
        $programmeCount = $programmesService->countAll();
        // ...
    }
}
```

Using this configuration I get the error:

'Controller "AppBundle\Controller\HomeController" requires that you provide a value for the "$programmesService" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.' in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php at line 78

---

I can solve this using constructor injection, by making the Controller look like this:

```php
class HomeController extends Controller
{
    private $programmesService;

    public function __construct(ProgrammesService $programmesService)
    {
        $this->programmesService = $programmesService;
    }

    public function __invoke(Request $request)
    {
        $programmeCount = $this->programmesService->countAll();
        // ...
    }
}
```

But having to setup that constructor and instance variable seems like boilerplate that could be sidestepped by using parameters within the `__invoke` function.

I spent quite a bit of time assuming that invokable controllers would be equivalent to `*Action`-style controllers in all but name and how they are referenced in the routing and think this symmetry would be useful.

Are there any performance reasons why using constructor injection is preferable to adding the arguments to the action method?

### Expected Behaviour:
I expect the arguments on __invoke would be autowired in the same way as they would be on other class functions (e.g. one named `homeAction`) so that my notion of symmetry between invokable controllers and "an Action method in a Controller class" is preserved.

Alternatively, I expect exception messaging making it clear that invokable controllers are not supported when using controller.service_arguments and that I should use constructor injection instead.

/cc @nicolas-grekas

**Comment by mvrhov** [comment]
AFAIR they are equivalent. It just seems that Nicolas missed that.

**Comment by chalasr** [comment]
The problem is that when using the tag, a service is created for each (wirable) action of the controller and, when come the moment for the ServiceValueResolver to resolve arguments, it is looking for e.g. `App\Controller\DefaultController` while only `App\Controller\DefaultController::__invoke` exists.

I think supporting this should be done at compile time by creating an "alias" for the invoke action in the action service locator, using the FQCN as identifier so both `FQCN` and `FQCN::__invoke` can be used to retrieve the service.

Since using the FQCN is supported in the `_controller` of a route, I think this should be supported.
Status: reviewed

**Comment by chalasr** [comment]
See #22330

**Comment by BPScott** [comment]
Huh, I somehow missed checking it before but this routing works (i.e. service arguments are correctly bound):

```yaml
home:
    path: home
    defaults: { _controller: AppBundle\Controller\HomeController::__invoke }
```

The ::__invoke feels like unneeded noise and removing it would be a nicer DX imo.
