### ISSUE TITLE
[DI] Cannot autowire service error

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22305]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.3

I'm testing the new DI/autowiring stuff with the Symfony Demo app. I have problems with this Twig extension:

```php
use App\Utils\Markdown;

class AppExtension extends \Twig_Extension
{
    public function __construct(Markdown $parser, $locales)
    {
        $this->parser = $parser;
        $this->locales = $locales;
    }

    // ...
}
```

This is the relevant service config:

```yaml
services:
    _defaults:
        autowire: by_id
        public: false

    _instanceof:
        Twig_ExtensionInterface:
            tags: ['twig.extension']

    App\:
        resource: '../../src/{Command,Form,EventSubscriber,Twig,Voter}'
```

This is the error I get:

```
RuntimeException in AutowirePass.php line 262:
Cannot autowire service "App\Twig\AppExtension": argument $parser of method
__construct() references class "App\Utils\Markdown" but no such service exists.
```

---

If I add this, it works:

```yaml
services:
    App\Twig\AppExtension:
        $parser: 'App\Utils\Markdown'
        $locales: '%app_locales%'
```

But I don't want to add the `$parser` config. Why isn't `Markdown` autowired? Is this a possible Symfony error ... or is this something that I should ask in https://symfony.com/support? Thanks!
