### ISSUE TITLE
Need example for proper workflow.yml to avoid deprecation Warning

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#22310]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | ?
| Symfony version  | 3.2

Following the sample workflow.yml file at http://symfony.com/blog/new-in-symfony-3-2-workflow-component, I'm still getting deprecation warnings:

```yaml
framework:
    workflows:
        article_publishing:
            marking_store:
                type: property_accessor
            supports:
                - AppBundle\Entity\Article
            places:
                - draft
```

```
Support of class name string was deprecated after version 3.2 and won't work anymore in 4.0.
line	33
code	16384
file	/data/www/survos/vendor/symfony/workflow/Registry.php
```

What should "supports" be changed to for using in Symfony 4.0 (and to get rid of the warnings in 3.2).
