### ISSUE TITLE
[DI] PSR4 loader suggestion

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#22397]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.0 (master)

I'm really enjoying the new PSR4 loader but have a suggestion. It would be nice if I could declare multiple definitions with the same prefix. Example:

```yaml
services:
    command_handlers:
        psr4_prefix: App\Domain\
        resource: ../../src/Domain/*/CommandHandler
        tags: [command_handler]

    event_subscribers:
        psr4_prefix: App\Domain\
        resource: ../../src/Domain/*/EventSubscriber
        tags: [event_subscriber]
```

I can't use `instanceof` here because my handlers/subscribers don't have interfaces.

Ref: https://github.com/symfony/symfony/issues/22016#issuecomment-293281597

**Comment by nicolas-grekas** [comment]
Adding new syntax adds complexity so better not if can.
Yet, if someone wants to implement this, what about this alternative:

```yaml
services:
    App\Domain\*\CommandHandler
        resource: ../../src/Domain/*/CommandHandler
        tags: [command_handler]

    App\Domain\*\EventSubscriber
        resource: ../../src/Domain/*/EventSubscriber
        tags: [event_subscriber]
```
