### ISSUE TITLE
[YAML] Adding blank line between levels

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#22421]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Yaml dumper allows configuration of indentation and array collapse level, however I wasn't able to locate functionality to add blank lines to pretty-format file.

### Example
Currently I can generate following structure:

```YML
services:
    Foo\Bar\Test:
        autowire: true
        public: false
        tags:
            - { name: legacy_service }
    Foo\Bar\Test2:
        autowire: true
        public: false
        tags:
            - { name: legacy_service }
    Foo\Bar\Test3:
        autowire: true
        public: false
        tags:
            - { name: legacy_service }
```

However normally while writing e.g. services file blank lines are useful for readability:
```YML
services:
    Foo\Bar\Test:
        autowire: true
        public: false
        tags:
            - { name: legacy_service }

    Foo\Bar\Test2:
        autowire: true
        public: false
        tags:
            - { name: legacy_service }

    Foo\Bar\Test3:
        autowire: true
        public: false
        tags:
            - { name: legacy_service }
```

### Solution
Currently I can hack result YAML with regex but it's completely wrong way of doing that. Is there a way to archive such result with current YAML dumper?

**Comment by xabbuh** [comment]
Currently that's not possible and honestly I am not convinced that we should complicate the dumper's code just to achieve this.

**Comment by fabpot** [comment]
I'm 👎 as well on adding this feature.

**Comment by theofidry** [comment]
Best way to go: decorate the dumper and add the blank line where you want.

**Comment by curry684** [comment]
I like the idea (I've missed it myself while generating configs) but the biggest problem is how to implement it. Just adding blanks between objects would also add blanks between the separate properties like `autowire` and `public`. The human has his own ways of applying patterns like this.

**Comment by kiler129** [comment]
@theofidry: any suggestions how to approach that without hacking Yaml component?
@curry684: maybe it can be implemented in a way array syntax is chcoosen - you'll get blank lines after 2nd, 5th and say 7th levels?

**Comment by curry684** [comment]
@kiler129 if any such behavior were to be implemented it would have to be predictable, understandable and configurable. Arbitrary preselected levels are none of those. Open a random `config.yml` for a big project with lots of bundles and note that you applied the blank lines at completely different levels for every bundle's part. Which is immediately what makes it impossible to properly implement in any generic way.

**Comment by ErichHartmann** [comment]
I doubt you will ever find a consensus if you try to chase this rabbit with a feature. Best to let individuals customize their own solutions.

**Comment by kiler129** [comment]
@ErichHartmann: I'm open for that, however I don't see any sane way to customize dumper.

**Comment by ErichHartmann** [comment]
@kiler129 I'm sorry, I would use the Yaml component as a template to build my own custom version. Symfony is an outstanding teacher and example in that way.

**Comment by javiereguiluz** [comment]
I'm closing this proposal because at least two Core Team members voted against it. @kiler129 I'm sorry this time your proposal didn't make it, but please keep proposing new features and changes. Thanks!

**Comment by TomasVotruba** [comment]
Any working solution to this? Decorator or reg-ex one

**Comment by TomasVotruba** [comment]
My current solution best so far:

```php
/**
 * @param mixed[] $data
 */
public function getStringFromData(array $data): string
{
    $result = Yaml::dump($data,10);

    return $this->addEmptyLinesBetweenItems($result);
}

private function addEmptyLinesBetweenItems(string $result): string
{
    $i = 0;
    return preg_replace_callback('#^[\s]{4}[a-zA-Z_]+#m', function ($match) use (&$i) {
        ++$i;
        if ($i === 1) {
            return $match[0];
        }

        return PHP_EOL . $match[0];
    }, $result);
}
```

Produces:

```yaml
services:
    _defaults:
        key: value

    SomeService: ~
```
