### ISSUE TITLE
multiple configurators

### ISSUE THREAD

**Issue by matthbull** [symfony/symfony#22495]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.x

Having recently stumbled upon configurators I'm starting to use them more and more.  

However, I'm starting to get use cases where I would like to use more than one configurator on the same service

Currently we have something like this:

```yaml
app.player_manager:
        class: AppBundle\Services\PlayerManager
        autowire: true
        configurator: 'app.logger_configurator:configure'
```
but it can only take a single configurator definition on the configurator key.

It would be really useful if we could specify multiple configurators, something like this:

```yaml
app.player_manager:
        class: AppBundle\Services\PlayerManager
        autowire: true
        configurator: 
            - 'app.logger_configurator:configure'
            - 'app.redis_configurator:configure'
```

I could code around it and have one configurator setting up 2 different properties on a class, but that feels messy to me and I'd rather keep them decoupled.
