### ISSUE TITLE
GetToken() from TokenStorage returns null in some cases

### ISSUE THREAD

**Issue by rsaenen** [symfony/symfony#22513]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.3

Hi,
The function `getToken` from `tokenStorage` returns in some cases `null`.

```
namespace AppBundle\Security;

use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class CurrentUserProvider
{
    private $tokenStorage;
 
    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }
 
    /**
     * Get the logged in user or null.
     *
     * @return User
     */
    public function getUser()
    {
        $user = null;
        $token = $this->tokenStorage->getToken();

        if ($token !== null) {
            $user = $token->getUser();
        }
 
        return $user;
    }
}
```
In my controller `POST` method works but `DELETE` doesn't...
```
class ImageController extends Controller
{
    /**
     * @Rest\View(statusCode=Response::HTTP_CREATED, serializerGroups={"image"})
     */
    public function postImagesAction(Request $request)
    { 
        $currentUser = $this->get('current_user');  // OK
        ... 
    }

    /**
     * @Rest\View(statusCode=Response::HTTP_NO_CONTENT)
     * @Rest\Delete("/images/{id}")
     */
    public function deleteImagesAction(Request $request) 
    { 
        $currentUser = $this->get('current_user');  // KO
        ... 
    }
}
```

**Comment by stof** [comment]
it can return null if your method is not behind the firewall. Check your security.yml for a firewall pattern disabling the firewall for these URLs

**Comment by rsaenen** [comment]
True, my provider is not called when I use `DELETE`...
```
providers:
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~
```
But the pattern match, am I doing it wrong?
