### ISSUE TITLE
[DependencyInjection] Silent failure on unexpected service definition keys

### ISSUE THREAD

**Issue by skafandri** [symfony/symfony#22540]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | possible
| RFC?             | yes
| Symfony version  | 3.2.7

Today I spent some time to figure out why this service was dumped incorrectly.

````
service_id:
    class: \Class
    argumets:
      - '@another_service_id'
````
Note the `argumets` typo. 

Some suggestions:
1. Log a notice/warning if a logger is available
2. Throw an exception
3. Output a warning when run from cli

Throwing an exception might cause a BC break if some people added custom keys to the service definition.
