### ISSUE TITLE
[SecurityBundle] Guard - default route configurations

### ISSUE THREAD

**Issue by twifty** [symfony/symfony#22691]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

I have recently started using the Guard component to handle formless authentication. Great addition BTW (Thanks @weaverryan).

With the traditional `'form_login'`, we have the option to add many routes directly under the `'firewalls'` key. For example the `'default_target_path'`. Using `'guard'` we don't have these options. I understand that any key/value pairs can be defined under the implementing bundle, but IMO bundle configuration and firewall configurations should be separate.

Would it be possible to add the configurations, under 'guard',  for `'default_target_path`', `'always_use_default_target_path`', `'use_referer`', `'login_path`' and `'failure_path`'. Then make these configurations available, as possibly a container parameter, so they can be passed into our 'GuardAuthenticator' constructor?

This will keep firewall configuration nice and tidy, and also allow for the easier development of 3rd party bundles.

**Comment by chalasr** [comment]
duplicate of https://github.com/symfony/symfony/issues/22071, also relates to https://github.com/symfony/symfony/issues/21391

**Comment by ChadSikorra** [comment]
Instead of passing options to a Guard constructor, maybe it would be cleaner for a new interface called something like `OptionsAwareGuardInterface` with a method `setOptions(array $options)`? Then a new SecurityBundle option for the guard called `options` which could accept an array of key => value pairs.

Then the guard factory could pass it to the guard authentication provider and that could determine if the guard implements the interface and pass it the options (or maybe just done in the guard factory?). Though it would do that for all authenticators defined. So maybe the guard option config would need to be something like:

```yaml
    firewalls:
        somename:
            guard:
                authenticators:
                    - some.guard_authenticator
                options:
                    some.guard_authenticator:
                        default_target_path: /foo
                        login_path: /bar
```

**Comment by twifty** [comment]
Having a per-authenticator set of options was a bit beyond what I was suggesting, but I can see how it may be beneficial.

How about this, instead of hard coding a list of valid key names, just use a `variableNode`. The `GuardAuthenticationProvider` can pass the array to the relevant `OptionsAwareGuardInterface::setOptions` method. Each authenticator is then in total control of documenting its required/default options. It would also maintain BC.

If enough people want this functionality, and nobody else has the time, I will fork and submit the required changes.

**Comment by ChadSikorra** [comment]
Yeah, in my example, I meant that the key => value pairs under the authenticator name would be variable. I just used existing option names as an example. I still think there's benefit to having the options be variable by authenticator. You may want very different options depending on what the authenticator does. Maybe I'm just in the minority in that opinion?

**Comment by weaverryan** [comment]
One of the goals of Guard was to keep the configuration out of the firewall and into your own code. You're responsible for wiring your authenticator (in PHP) and that gives you the power to configure it how you'd like (in PHP, not in YAML).

If you're building a bundle that exposes an authenticator services, and you want your end user to be able to configure it, that configuration should be built into the configuration of your bundle. In other words, you configure the bundle, which exposes one or more guard authenticator services that you can then use in your firewall.

This does put the burden on third-party bundle owners, but I think that makes sense: they know exactly what kind of config they do and don't need. They can also properly validate their config via the `Configuration` class (versus needing to use a `variableNode` and then validating it inside some `setOptions()` method of your authenticator at runtime).

Cheers!

**Comment by twifty** [comment]
@weaverryan I understand what you're saying, but I have to disagree. Taking firewall configuration out of the firewall is stepping backwards. Take for example an OAuth2 authenticator. Sure, the individual provider configurations (the secret keys, scopes etc.) should be under the owning bundles configuration. But, items like login routes, where we are specifying which roles can access what and where users should be redirected to, should all be in one place, under the firewall.

I agree in that the config needs to be properly validated. If our own authenticators could supply or add to the config tree, there would be no need for a `variableNode` and `setOptions`. Having the ability to add our own 'Factory' to `GuardAuthenticationFactory` would solve all problems. The end developer can then decide which options pertain to the firewall and which are more specific to their bundle, then add the configuration accordingly.

**Comment by weaverryan** [comment]
> I understand what you're saying, but I have to disagree.

Fair enough :)

> But, items like login routes, where we are specifying which roles can access what and where users should be redirected to, should all be in one place, under the firewall.

So is the real problem / request that we want to make sure that the login path, success path and failure path all exist inside `security.yml` like everything else? If that's important, could it be solved by using parameters in `security.yml`?

```yml
parameters:
    # use these parameters below, and also reference them in services.yml where your
    # authenticator is configured (or, if you really want, you could even add a `services` key
    # in this file, and configure your authenticator right here
    login_route_name: security_login
    default_target_path: homepage
    failure_path: /login-failed

security:
    # ... then use these parameters below, like in `form_login`
```

It's not super sexy, but if the issue is just that we want to keep security-related stuff in `security.yml` (fair enough), then we could use parameters in security.yml, or even configure the authenticator(s) themselves there.

Cheers!
