### ISSUE TITLE
Env() parameter placeholder breaks config

### ISSUE THREAD

**Issue by felds** [symfony/symfony#22738]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-DEV

When trying to use an env() placeholder on a config option that is being validated, it takes the placeholder literally and it fails the validation.

Here's a fresh new project replicating the error: 
https://github.com/symfony/symfony-standard/compare/master...felds:config-vs-env?expand=1

Relevant changes:

```yaml
# app/config/config.yml
parameters:
    env(SMTP_HOST): smtp.example.com
    env(SMTP_ENCRYPTION): tls
swiftmailer:
    host: "%env(SMTP_HOST)%" # <-- this works…
    encryption: "%env(SMTP_ENCRYPTION)%" # <-- but this breaks
```
