### ISSUE TITLE
[DependencyInjection] Suggestion for autowiring parameters

### ISSUE THREAD

**Issue by wjbLabs** [symfony/symfony#22755]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

When services are autowired, parameter values still needs to be declared in definition like:
```yaml
    app.my_service:
        class: AppBundle\Service\MyService
        arguments: 
            - $clientHostParameter: "%client_host%"
```
What about guessing them based on variable name? For example:

```php
class MyService
{
    public function __construct(TwigEngine $twigEngine, $clientHostParameter)
    {
        //...
    }
```

So if variable ends with word ``parameter``, S3 would tableize ``clientHost``, look for parameter ``client_host`` and inject it.

An example taken from [Symfony Flex demo](https://www.youtube.com/watch?v=oJUSOK4cT78&feature=youtu.be&t=49m58s) would then become:

```php
class RecipeLoader
{
    public function __construct(LoggerInterface $logger, $kernelDebugParameter)
    {
        //...
    }
```

What do you think?

---
Sorry if someone posted this idea before.
