### ISSUE TITLE
twig asset() is somehow broken in symfony 2.8.20

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony#22778]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.20

Updating symfony/symfony from 2.8.19 to 2.8.20 breaks the link generated in twig by asset($asset, $package) is broken form some files. Reverting the version makes it working again.

I do not yet see any pattern which links are broken. Some file from the same directory do work, other do not.
The generated link is "/js/some.js" instead of "/path/to/installation/js/some.js" (in dev and prod).

Any idea how I can find out more details?

**Comment by apfelbox** [comment]
See #22528

**Comment by SimonHeimberg** [comment]
Thanks.

For the failing assets, there was configured a package with a base_path containing a leading slash.
```yml
    assets:
        version: '123'
        packages:
            img:
                base_path: /bundles/app/images/
            css:
                base_path: /css/
```
It seems to work when I remove the leading slash.

But this still not explains why some files from 'css' package were working and some did not.
