### ISSUE TITLE
[DI] Some Twig extensions work automatically, others don't

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22849]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.3

In https://github.com/symfony/symfony-demo/pull/562 we're updating the Symfony Demo app to 3.3.0 RC1 and all the new DI features. During the upgrade I saw this error:

```
Unknown "localizeddate" filter.
```

The reason is that I removed the original service definition for the Intl Twig extension:

```yaml
app.twig.intl_extension:
    public: false
    class:  Twig_Extensions_Extension_Intl
    tags:
        - { name: twig.extension }
```

If I put the config back, everything works again. I think it's confusing that "auto-services" work for our own Twig extensions but not for Symfony's extensions. Is there anything we can do to improve this situation? Thanks

**Comment by stof** [comment]
Well, what we could do is having TwigBundle registering this extension automatically when the twig-extensions package is installed (but keeping it an optional dependency of the bundle). I think this would fit the Flex idea of activating things by default when the package is installed.
What do you think @symfony/deciders ?

**Comment by weaverryan** [comment]
>  I think it's confusing that "auto-services" work for our own Twig extensions but not for Symfony's extensions

The explanation we need to "push" (and is accurate) is that we're auto-registering & tagging things in `src/AppBundle` only. 

> Well, what we could do is having TwigBundle registering this extension automatically when the twig-extensions package is installed (but keeping it an optional dependency of the bundle).

I like this! But, wouldn't we need to register *all* the extensions in that library then? That could be wasteful. Could we - as an alternative in Flex - add service configuration for all of the Twig extensions when `twig-extension` is installed... but commented-out (so you would need to go then activate each one).

**Comment by nicolas-grekas** [comment]
See https://github.com/twigphp/Twig-extensions/pull/204

**Comment by nicolas-grekas** [comment]
Should we move this issue to the 3.4 milestone?

**Comment by weaverryan** [comment]
I just changed to 3.4 milestone. If we're going to do anything in this repo, it would be a new feature to auto-register the Twig extensions in TwigBundle... so a new feature I think

**Comment by fabpot** [comment]
1.5.0 is out now.

**Comment by fabpot** [comment]
It works, but you need to explicitly enable the extension:

```yaml
Twig\Extensions\IntlExtension: ~
```

**Comment by fabpot** [comment]
Not sure if registering all extensions automatically is a good idea. Some filters/functions could collide with some created by the developer locally,  and it adds some overhead. Moreover, Flex is really all about adding only what you need. What we could do is adding a recipe that adds a file for those configurations, all commented, to ease discovery. See symfony/recipes#173

**Comment by weaverryan** [comment]
+1

So, no changes to core needed. Any Twig extensions that *you* create in your `src/` dir are auto-registered and tagged of course. And thanks to symfony/recipes#173, if you install twig-extensions, it gives you the code you need to opt-in. I love it :)

**Comment by Laurent3170** [comment]
I came there with Google and it seems to me, that's the good place to post the following.
In a standalone bundle, I have added in its `services.yml` the following config code
```yml
services:
    twig.intl_extension:
        class: Twig_Extensions_Extension_Intl
        tags:
            - name: twig.extension
```
But I receive the following error

> Unable to register extension "Twig_Extensions_Extension_Intl" as it is already registered.

As this configuration is already done in the `services.yml` file of the app using the bundle. I have the same message when using `Twig\Extensions\IntlExtension: ~`.

The only way is to keep only one declaration, but this will lead to an error if the `Twig_Extensions_Extension_Intl` is not defined in the app.

Furthermore, if I do the same with `Twig_Extensions_Extension_Text` using 
```yml
services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
```
It works! Even if declared on both app + bundle.

**Comment by curry684** [comment]
A standalone bundle should not declare services that it is not providing itself. Your bundle should either degrade gracefully if the extension is not installed by the end user, or provide the services you use from them yourself (if needed by wrapping the originally provided extensions), or last resort depend hard on the TwigExtensions package and use a late-phase compiler pass to register the service *only if the end user did not already do this on application level*.

**Comment by Laurent3170** [comment]
I will need some time (to understand) how to implement the bundle to degrade gracefully, if the extension is not installed, as I am just using `localizeddate`, but thanks for your explanation!
Symfony provides a lot of features and concepts that are easy when you understand them, but not so easy when you don't ;-)

**Comment by Laurent3170** [comment]
In fact my misunderstanding came because in the `app/Resources/config/services.yml` we define the services we **use and provide**, while in a standalone bundle `Resources/config/services.yml` we only define the services we **provide**, except if I'm still wrong.

**Comment by stof** [comment]
well, in project-level, you still provide some services (using them is not happening in this file). The difference is that you can also provide services for some third-party classes, if these classes don't have a bundle providing the service.
The issue happens when multiple places are trying to provide similar services (Twig does not like multiple registrations of an extension, as it might lead to weird behavior sometimes)

**Comment by LaurentMarquet** [comment]
1 year and 4 days later I'm facing another problem with Twig Extensions and by googling I came there again ;-)
In my dev server I have in `config/packages/twig_extensions.yaml`
```yml
services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    # Uncomment any lines below to activate that Twig extension
    #Twig\Extensions\ArrayExtension: ~
    Twig\Extensions\DateExtension: ~
    Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~
```
where it works well. But on my production server, having the same file as it's in a Git repo, it can't find the `truncate` filter.
I've tried to remove the # in front of TextExtension on production and it worked... Do you have any idea why? And how I can solve it?
