### ISSUE TITLE
[DI] Sometimes, "class FQCN as service IDs" doesn't work

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22851]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.3

In https://github.com/symfony/symfony-demo/pull/562 we're updating the Symfony Demo app to 3.3.0 RC1 and all the new DI features. During the upgrade, @weaverryan suggested to use this config for the Twig Intl extension:

```yaml
Twig_Extensions_Extension_Intl: ~
```

When I did that, I saw this error:

```
RuntimeException in CheckDefinitionValidityPass.php line 52:

The definition for "Twig_Extensions_Extension_Intl" has no class attribute, and
appears to reference a class or interface in the global namespace. Leaving out
the "class" attribute is only allowed for namespaced classes. Please specify the
class attribute explicitly to get rid of this error.
```

I needed to use this old config to make it work again:

```yaml
app.twig.intl_extension:
    public: false
    class:  Twig_Extensions_Extension_Intl
    tags:
        - { name: twig.extension }
```

Ryan seemed very convinced that this should work. So, my question: is this a bug or just an unsupported feature? Thanks!
