### ISSUE TITLE
[3.3] Glob loader breaks loading inline YAML resources

### ISSUE THREAD

**Issue by alcaeus** [symfony/symfony#22938]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.0-RC1

First of all, I'm not sure if this is issue or if this "just shouldn't be done this way".

Upgrading to Symfony 3.3.0-RC1 in Sylius causes an error as indicated in Sylius/Sylius#7896. After additional investigation I figured this is caused due to Sylius using a [custom loader](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php) to load config files with inline YAML as a `resource` (example shortened):
```
sylius_admin_admin_user:
    resource: |
        alias: sylius.admin_user
        except: ['show']
    type: sylius.resource
```

The custom loader generates routes based on the configuration given in the `resource` key, so it's a nice way to avoid writing lots of boilerplate code for the same thing over and over. Using the `resource` key also reduces the amount of files needed: without this, there would have to be one routing file and another file containing the actual specification (now contained in `resource`).

With this comes the issue: the introduction of glob loaders in #21635 broke this completely, while #22621 partially fixed it: it no longer breaks for config files that don't contain any of the characters triggering the glob loader (removing the `except` directive in the config above fixes the error for this file).

Would you consider this a valid use-case of the `resource` key in a config file? If so, should the check for the glob pattern be hardened? In this case, adding a check against newlines would help, but who knows what else is out there. Another option would be to fall back to the default behavior if the glob loader didn't load anything, but I'm also not sure what side-effects this might have. Last but not least, this could also be fixed on the Sylius side; I just wanted to check here before doing that.

**Comment by nicolas-grekas** [comment]
@alcaeus it's a BC break in 3.3 for sure, but one we want to do IMHO. Still, we can enhance the glob-detection logic to make it more specific. Detecting newlines as you suggested.
Just wondering: why using a string in resource? Does something prevent using Yaml directly instead of Yaml-in-a-string? That'd be even better to allow it if it doesn't work yet.

**Comment by alcaeus** [comment]
You'd have to ask one of the Sylius core devs that, maybe @pamil or @lchrusciel can answer that. Don't tell me you could actually write this like so:
```
sylius_admin_admin_user:
  resource:
    alias: sylius.user
    except: ['show']
  type: sylius.resource
```

**Comment by xabbuh** [comment]
@nicolas-grekas Currently, `resource` must be a string, right? It will probably break the loading process (or violate one of our interfaces) somewhere, won't it?

**Comment by nicolas-grekas** [comment]
@xabbuh the type hint on LoaderInterface and LoaderResolverInterface says "mixed", so should be good, isn't it?

**Comment by xabbuh** [comment]
Oh indeed, the loaders should still work fine. However, you will run into issues when defining routes with XML as the `resource` attribute there is limited to be a string.

**Comment by nicolas-grekas** [comment]
See #22940.

**Comment by alcaeus** [comment]
That was quick, thanks!

**Comment by lchrusciel** [comment]
@alcaeus @nicolas-grekas it was a hacky solution to allow defining nested yaml instead of string only. Otherwise, something has been broken. @pjedrzejewski has implemented this feature, so he will have the best knowledge about it.

**Comment by liverbool** [comment]
Still can't use with something like this:

```yaml
sylius_admin_user:
    resource: |
        alias: sylius.admin_user
        section: admin
        path: users
        templates: AppBundle:Resouce/Crud
    type: sylius.resource
```

It's work when remove
  - `templates: AppBundle:Resouce/Crud` or change to
  - `templates: AppBundle:ResouceCrud`

Other example:

```yaml
# Not work
sylius_admin_api_carts:
    resource: |
        alias: sylius.order
        path: '/'
        only: [index]
        grid: sylius_admin_api_cart
        section: admin_api
        serialization_version: $version
    type: sylius.resource_api


# Work
sylius_admin_api_carts:
    resource: |
        alias: sylius.order
        #path: '/'
        only: [index]
        grid: sylius_admin_api_cart
        section: admin_api
        serialization_version: $version
    type: sylius.resource_api
```

**Conclusion** We can't use `/` in `inline` yaml.

PS. Got error when `php bin/console cache:clear` but have no error when `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache` after composer install or update.
