### ISSUE TITLE
[Security] Decoupling password from UserInterface

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#23081]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x

I think we should decouple password from **UserInterface** (having a **PasswordInterface** for example) in order to be able to use them with the password encoding system. Currently, you need to pass a whole **UserInterface** for encoding password, while a simple password/salt is enough.

This would be usefull to implement some system where you manager password history. Right now, you need the "**PasswordHistory**" object to implement **UserInterface** in order to be used with the **PasswordEncoder**. But having a username or roles into a **PasswordHistory** object doesn't make any sense...

**Comment by Hanmac** [comment]
i find your idea interesting but i would have used the UserName with the Password in the Password history like:
[id] [user] [password] [salt]

for that i would have used a UserToken that just implements `UserInterface`.
`getRoles` returns empty string and `eraseCredentials` does nothing.

hm with that you can also use it to tell the user that he already used a password like that (with same hash)

**Comment by ogizanagi** [comment]
@Vinorcola : The [`PasswordEncoderInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Encoder/PasswordEncoderInterface.php) does not require a `UserInterface` instance on the contrary of the [`UserPasswordEncoderInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Encoder/UserPasswordEncoderInterface.php).

Instead of using `UserPasswordEncoderInterface` or the `security.password_encoder` service, try using the `security.encoder_factory` to create the encoder you expect to inject in your services:

```yml
services:
    Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface:
        factory: 'Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface:getEncoder'
        # or
        factory: 'security.encoder_factory:getEncoder'
        arguments: ['AppBundle\Entity\User']
```
