### ISSUE TITLE
Placeholder for route in YML doesn't match route

### ISSUE THREAD

**Issue by Roshyo** [symfony/symfony#23102]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

Hi, 
When I try to map my routes in YML, I'm encountering an issue. Here is the complete YML : 
```
document_create:
    path: /documents/create
    defaults: { _controller: AppBundle:Document:create }

documents_home:
    path: /documents/{tags}
    defaults: { _controller: AppBundle:Document:home, tags: '' }

homepage:
    path: /
    defaults: { _controller: AppBundle:Home:index }
```

And when I go to the URL : /documents/ , I got this Issue : No route found for "GET /documents/"

Here is the bin/console debug:router : 

```
  document_create                     ANY        ANY      ANY    /documents/create
  documents_home                      ANY        ANY      ANY    /documents/{tags}
  homepage                            ANY        ANY      ANY    /

```

Any Idea of what I might be missing ? or is this a real bug ?
