### ISSUE TITLE
Improve the exception page when there is no message

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23135]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

It's uncommon, but sometimes exceptions don't contain any error message. For example, with this route definition:

```yaml
my_route:
    path: '...'
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '', permanent: true }
```

When the `route` is empty, the RedirectController throws this exception:

```php
        if ('' == $route) {
            throw new HttpException($permanent ? 410 : 404);
        }
```

Which looks like this in the browser:

![before-exception](https://user-images.githubusercontent.com/73419/27012727-32e6867a-4ed6-11e7-905a-8f3f3051c260.png)

---

What do you think if we hide the message section when it's empty? Something like this:

![after-exception](https://user-images.githubusercontent.com/73419/27012731-40157a18-4ed6-11e7-8075-fe7d158f41de.png)
