### ISSUE TITLE
Trait fails in serialization (YAML)

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#23178]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

Allows traits to be included in serialization.yml

```yaml
#serialization.yml
Gedmo\Timestampable\Traits\TimestampableEntity:
    attributes:
        createdAt:
            groups: [Default]
```
