### ISSUE TITLE
Cannot access the container from inside a controller

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#23200]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| Symfony version  | 3.3.2

I'm migrating my app from Symfony 2.8 to Symfony 3.3.

_NOTE: I'm not upgrading the 2.8 version, but installed a fresh project of Symfony 3.3 and moving all relvant files to it from the old 2.8 Symfony project._

From inside a controller of mine I have this:

    public function indexAction()
    {
        $email = new Email();

        $form = $this->createForm(GetStartedType::class, $email, [
            'action' => $this->generateUrl('get_started_end'),
            'method' => 'POST',
        ]);

        return [
            'form' => $form->createView(),
        ];
    }

But I receive this exception:

> Call to a member function get() on null

My controller extends `Symfony\Bundle\FrameworkBundle\Controller\Controller`:

    /**
     * {@inheritdoc}
     */
    class DefaultController extends Controller
    {
    ...
    }

So I have access to the container.

Putting some dumps around in the Symfony's code, I see that the container is correctly set:

    namespace Symfony\Component\DependencyInjection;
    
    /**
     * ContainerAware trait.
     *
     * @author Fabien Potencier <fabien@symfony.com>
     */
    trait ContainerAwareTrait
    {
        /**
         * @var ContainerInterface
         */
        protected $container;
    
        /**
         * Sets the container.
         *
         * @param ContainerInterface|null $container A ContainerInterface instance or null
         */
        public function setContainer(ContainerInterface $container = null)
        {
            dump('Here in the ContainerAwareTrait');
            dump(null === $container);
            $this->container = $container;
        }
    }

This dumps

    Here in the ContainerAwareTrait
    false

So the autowiring works well and sets the container.

But in the `ControllerTrait` I have this:

    trait ControllerTrait
    {
        /**
         * Generates a URL from the given parameters.
         *
         * @param string $route         The name of the route
         * @param mixed  $parameters    An array of parameters
         * @param int    $referenceType The type of reference (one of the constants in UrlGeneratorInterface)
         *
         * @return string The generated URL
         *
         * @see UrlGeneratorInterface
         */
        protected function generateUrl($route, $parameters = array(), $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
        {
            dump('Here in the ControllerTrait');
            die(dump(null === $this->container));
            return $this->container->get('router')->generate($route, $parameters, $referenceType);
        }
    
        ...

this is the dump:

    Here in the ControllerTrait
    true

**So here the `container` is `null` and this causes the error.**

**Anyone can help me solve this issue?**

**Why is the `container` null?**

If may help, this is the `services.yml` configuration (the default that cames with Symfony):

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

This issue is a copy and paste of a [Stackoverflow question I opened](https://stackoverflow.com/q/44571013/1399706).

**Comment by stof** [comment]
Can you provide a reproducing case ?

**Comment by Aerendir** [comment]
Reproducing case? How I could? Is an entire app!

More than the code of the controller I cannot give... It is a lot of code!

Maybe you know some fine details I can check other than the involved traits (`ContainerAwareTrait` and `ControllerTrait`)...

**Comment by stof** [comment]
Well, if you cannot recreate the issue in a project you can share with us (create a new Symfony 3.3 project and add the code needing to reproduce the issue), we don't have any way to debug the issue as we don't have access to your app (you are the first one reporting this issue, so you probably have something special in the way you use Symfony).

**Comment by Aerendir** [comment]
But to recreate the issue I should already know which the cause is, and this is exactly what I'm trying to understand! o.O

How can I reproduce something of which I don't know the cause?

Just because is something specific to my way of using Symfony (that, anyway, is the "normal" way of using it, relying on its built-in functionalities) is something that I cannot reproduce in a fresh installation of the framework.

For this reason I were asking for some suggestions on how to debug the issue.

For example, I will do the following two things:
1. Disable the autowiring at all to understand if the cause is the autowiring itself or not;
2. Enabling the autowiring again and dump the class assigned ID, both in `ContainerAwareTrait` and 
 in `ControllerTrait` to understand if the autowired class is the same I'm using in my controller;

I'm asking for this kind of advice, that can help me debug the issue in _my_ project, with _my_ way of using Symfony, also to understand if it really is a bug to fix or if it is a mistake of mine.

**Comment by Aerendir** [comment]
**TEST 1: Disable the autowiring**
_Expected result: the controller works as expected._

To disable the autowiring functionality on controllers I did this in my `services.yml`:

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Controller,Entity,Repository,Tests,EventListener,Validator,Twig}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    #AppBundle\Controller\:
    #    resource: '../../src/AppBundle/Controller'
    #    public: true
    #    tags: ['controller.service_arguments']

```

1. I added the `AppBundle/Controller` folder to the `exclude` of `AppBundle\` node;
2. Commented all the section related to `AppBundle\Controllers`.

**RESULT: The controller worked as expected showing the page. The Exception is gone away.**
**CONCLUSION: The problem is somthing related to the autowire functionality.**

**Comment by Aerendir** [comment]
TEST 2: Skipped

**TEST 3: Try to explicitly call the `setContainer` method on the controllers**
_Expected result: The controller action works as expected_

With this configuration in `services.yml`:

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests,EventListener,Validator,Twig}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
```

The issue is resolved: the controller shows the page and no exception is thrown.

So the problem, I think, is with the tag `controller.service_arguments`: this should call automatically the `setContainer` method on controllers that implements the `ContainerAwareInterface`, doesn't it?

It doesn't, but I don't know if this is the right behavior or not.

**Comment by vincentpazeller** [comment]
I just upgraded from 3.2.x to v3.3.0 and I encountered that exact same problem. Adding 
```
calls:
        - [setContainer, ["@service_container"]]
```

Fixed the problem immediately (thanks for the trick). So I guess there is something broken in the service_container automatic injection

Best Regards

**Comment by xabbuh** [comment]
@vincentpazeller Are you able to provide a small reproducer?

**Comment by Aerendir** [comment]
@xabbuh On my side, I'm not able to provide it. Maybe is the default behavior with any new Symfony 3.3 installation... Did you try (I have t ask, forgive me!)...

**Comment by ogizanagi** [comment]
I did try with both symfony-demo and a fresh install using `symfony new`, but I'm unable to reproduce the issue on my side.

**Comment by vincentpazeller** [comment]
I just created a dummy new project and, unfortunately, I could not reproduce the problem easily (this works well with the new project)... I am sorry, I don't have much time to assign to this issue...

**Comment by Aerendir** [comment]
So, the correct behavior would be to automatically inject the container into controllers tagged as `controller.service_arguments`, is it?

**Comment by vincentpazeller** [comment]
Yes, thats right. The problem was that the Controller's container property was null and when invoking the get method on it, an exception was triggered...

**Comment by Aerendir** [comment]
@vincentpazeller yes, and this is not the correct behavior... I'll investigate deeper ASAP... Maybe I'll discover the problem... Fingers crossed...

**Comment by nicolas-grekas** [comment]
There is a misunderstanding here: `controller.service_arguments` does NOT mean "inject the container".
The things that trigger automatic injection of the container are implementing the `ContainerAwareInterface` or implementing the `ServiceSubscriberInterface` one basically.

**Comment by ogizanagi** [comment]
I may have found the issue and reproduced it in https://github.com/ogizanagi/sf-issue-23200.
See https://travis-ci.org/ogizanagi/sf-issue-23200
The issue happen when using the `service:method` notation from routing: https://github.com/ogizanagi/sf-issue-23200/commit/c19c0eeb87f87a6eb54e551a1fc33cc1ed4ad39f, while it works perfectly when using the `a:b:c` (`AppBundle:Default:index`) one.

Do you think it's related to your issue?

I can suggest [a fix](https://github.com/symfony/symfony/compare/master...ogizanagi:fix/base_controller_required_call) to allow autowiring to properly add the `setContainer` method call by marking it as `@required` but I'm not sure it really make sense. If you're using your controller as a service, you'll probably avoid extending the base `Controller` and inject the container, or you'll rely on the new `AbstractController`, in which the method call is already required.

**Comment by Aerendir** [comment]
@nicolas-grekas , my controllers extend `Symfony\Bundle\FrameworkBundle\Controller\Controller` that implements `Symfony\Component\DependencyInjection\ContainerAwareInterface`, so the autowired injection could happen... Doesn't it?

@ogizanagi I'll investigate if this is my case and I'll tell you...

**Comment by Aerendir** [comment]
@ogizanagi 

My `routing.yml` file is this:

```yaml
app:
    resource: '@AppBundle/Controller/'
    type: annotation
```

And the annotations on controller are these:

```php
    /**
     * This has to be the last method, as it is the most generic of all.Fix.
     *
     * @Route("/", name="page_homepage")
     * @Template()
     */
    public function indexAction()
    {
        $email = new Email();

        $form = $this->createForm(GetStartedType::class, $email, [
            'action' => $this->generateUrl('get_started_end'),
            'method' => 'POST',
        ]);

        return [
            'form' => $form->createView(),
        ];
    }
```

So, I think it's not the same as the reproduction you provided...

Anyway you hit the point and demonstrated that a bug exists...

Maybe that the routing mechanism does something that in concrete creates the same sistuation you reproduced...
