### ISSUE TITLE
[DependencyInjection] Disabling _instanceof and _defaults rules for concrete service definition

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#23225]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | 3.3.2

Is it possible to ignore `_instanceof` and `_defaults` for service definition (like `autoconfigure: false`)?

```yaml
_instanceof:
    FooInterface:
        tags: ['foo']

Foo:
    tags: 
        - { name: 'foo', parameter: 'bar' } # overriding _instanceof definition
        - { name: 'foo', parameter: 'baz' } # new tag
```

In this case tags will be like this:
foo (parameter: bar)
foo (parameter: baz)
foo
