### ISSUE TITLE
Create validator from builder and UniqueEntity contraint

### ISSUE THREAD

**Issue by k20human** [symfony/symfony#23246]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

Hi,

I try to use validator in a service manage as an handler with [SimpleBus/MessageBus](https://github.com/SimpleBus/MessageBus)

I create my validator like this:
```
$this->validator = Validation::createValidatorBuilder()
            ->addYamlMapping(__DIR__.'/../../Resources/config/validation/Directory.Person.yml')
            ->getValidator();
```
My Directory.Person.yml:
```
I360\DomainBundle\Entity\Directory\Person:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [gender, type]
            ignoreNull: false
    properties:
        lastname:
            - NotBlank: ~
        gender:
            - NotBlank: ~
```
And finally i validate my entity with:
`$this->validator->validate($contact);` ($contact is an instance of Person class)

Validation of properties works but validation of UniqueEntity throws this error; 
> Attempted to load class "doctrine.orm.validator.unique" from the global namespace. Did you forget a "use" statement?"

I also try with annotions, the same problem occurs.
This problem doesn't occur when i try to validate my entiy in a controller.

Does i miss something? Or do something wrong?
