### ISSUE TITLE
[Workflow] Allow to define arbitrary data for states/transitions

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#23257]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.*

I wanted to switch over to Symfony Workflow component from FSM library we use, but I found out Symfony one doesn't support to easily specify descriptions for states/transitions, which is pretty vital for us, because it allows us to generate documentation for user like this:

![screenshot from 2017-06-22 00-33-16](https://user-images.githubusercontent.com/496233/27409629-bb1a8000-56e2-11e7-992f-8a4e51870671.png)

Maybe configuration for that could look something like this:

```yml
framework:
    workflows:
        blog_publishing:
            type: 'workflow' # or 'state_machine'
            marking_store:
                type: 'multiple_state' # or 'single_state'
                arguments:
                    - 'currentPlace'
            supports:
                - AppBundle\Entity\BlogPost
            places:
                draft: blabla
                review: blabla
                rejected: blabla
                published: blabla
            transitions:
                to_review:
                    from: draft
                    to:   review
                    description: blabla
                publish:
                    from: review
                    to:   published
                    description: blabla
                reject:
                    from: review
                    to:   rejected
                    description: blabla
```

**Comment by netsuo** [comment]
Or allow a "data" node or something to define any additional informations

**Comment by lyrixx** [comment]
Few people already ask for a similar feature. It's was not about description but about (random) "data".
I always rejected it before because I though it was not the workflow responsibility to hold some "data".

But now, with your use-case, I found it legit to have this feature in the core.
I would go with "data", an arbitrary set of data. I should be easy to implement in the component, in the bundle for the config in PHP + YAML. But it will be very hard in XML as XML do not support "generated on the fly keys". (not related: that's why I opened #22870 ping @fabpot)

So, I'm +0.5 for this feature. 

@ostrolucky  If other peoples are OK with your proposal, do you want to work on this new feature?

**Comment by ostrolucky** [comment]
Not sure, I would need to investigate the xml issue and I think acceptable workaround for this can be [extension prepending](https://symfony.com/doc/current/bundles/prepend_extension.html) which normalizes the custom configuration.

**Comment by lyrixx** [comment]
About the XML issue, we can not supported in the first time.

**Comment by stof** [comment]
@lyrixx we can support XML as long as your values are scalar ones. The `data` node would be a prototyped array node, and so XML would look like this:

```xml
<transition name="foo">
    <from>a</from>
    <to>b</to>
    <extra key="description">This comes from a to b</extra>
    <extra key="documented">true</extra>
</transition>
```

**Comment by userdude** [comment]
Here's my +1: This would help with seeding twig routes related to the transition. Like:

```
to_edit:
    from: [published,archived]
    to: editing
    data:
        - route: edit_foobar_route_whatever
```

And then later in Twig:

`<a href="{{ path(transition.data.route, { id: foobar.id }) }}"`

This would make looping over the transition names for a workflow a bit easier to use; right now I end up with something like:

```
{% if workflow_can(artwork, 'to_republish') %}
    <a href="#" class="btn btn-primary btn-xs">{{ 'to_republish'|trans }}</a>
{% endif %}
{% if workflow_can(artwork, 'to_disable_use') %}
    <a href="{{ path('disable_artwork', { id: artwork.id }) }}" class="btn btn-primary btn-xs">{{ 'to_disable_use'|trans }}</a>
{% endif %}
{% if workflow_can(artwork, 'to_archive') %}
    <a href="#" class="btn btn-primary btn-xs">{{ 'to_archive'|trans }}</a>
{% endif %}
```

Instead of calling the list of available transitions and looping over them like:

```
{% for transition in workflow_transitions(post) %}
    <a href="{{ path(transition.data.route, { id: artwork.id }) }}">{{ transition.name|trans }}</a>
{% endfor %}
```

I'm open to suggestions about other, possibly better ways of looking at it too. I would just rather not have to check each transition if I just want to show some action buttons.

**Comment by ostrolucky** [comment]
My issue with implementing this is that I need such thing not only for transitions, but places too. For that we would need to turn Place into object. I don't see how to migrate component into such change in acceptable way. Biggest problem is that Workflow::getPlaces returns string[]. Too bad this component didn't take inspiration from [yohang/Finite](https://github.com/yohang/Finite). Any ideas @lyrixx ?

**Comment by userdude** [comment]
@ostrolucky I was actually thinking at first it was a peer to places/transitions/etc:

```
...
supports:
    - AppBundle\Entity\BlogPost
data: # Or maybe "related" key?
    places:
         draft: { description: "Editing the thing currently, please come back." }
    transitions
         to_edit: { route: edit_route_name, description: "The thing needs something." }
places:
    draft
    review
    ...
transitions:
    to_edit:
        from: whatever
        to: wherever
    ...
```

Apologies for any mangled yaml, having not done it much.

Then maybe:
 
`workflow_data(blogPost, {transition.to_edit.route})`

Would that make more or less sense?

**Comment by ostrolucky** [comment]
I don't like that because:
1. You are forced to repeat names of transitions/places when configuring 
1. You are forced to call something else and supply to it transition/place and data key when retrieving this data
1. For retrieving this data you need to introduce new dependency. No longer is it sufficient to provide place/transition alone. 
1. Implementation is problematic because component would need to store transitions/places associated to data in separate location than data itself and make sure they are in sync (or not and let user fall on its face)

<table>
<tr>
	<th>This is the ideal DX I would like:</th>
	<th>Not good</th>
</tr>
<tr>
	<td valign="top"><pre>
blog_publishing:
    supports:
        - AppBundle\Entity\BlogPost
    data:
         label: Blog publishing
         description: Manages blog publishing
    places:
        draft:
             description: Blog has just been created
             color: grey
        review:
             description: Blog is waiting for review
             color: blue
    transitions:
        to_review:
            from: draft
            to: review
            label: Submit for review
            route: admin.blog.review</pre></td>
	<td><pre>blog_publishing:
    supports:
        - AppBundle\Entity\BlogPost
    data:
        label: Blog publishing
        description: Manages blog publishing
        places:
	        draft:
	             description: Blog has just been created
	             color: grey
	        review:
	             description: Blog is waiting for review
	             color: blue
	    transitions:
	        to_review:
	            label: Submit for review
	            route: admin.blog.review
    places:
        - draft:
        - review:
    transitions:
        to_review:
            from: draft
            to: review</pre></td>
</tr>
	<td valign="top"><pre>public function onReview(Event $event) {
    foreach ($event->getTransition()->getTos() as $place) {
        $this->flashbag->add('info', $place->getData('description'));
    }
}</pre></td>
	<td><pre>public function onReview(Event $event) {
    $workflowPlacesData = $event->getWorkflowData()['places'];
    foreach ($event->getTransition()->getTos() as $place) {
        $this->flashbag->add('info', $workflowPlacesData[$place]['description']);
    }
}</pre></td>
</tr>
	<td valign="top"><pre>{% for transition in workflow_transitions(post) %}
    &lt;a href="{{ path(transition.data.route) }}">
         {{ transition.label }}
    &lt;/a>
{% endfor %}</pre></td>
	<td><pre>{% for transition in workflow_transitions(post) %}
    {% set transition_data = get_workflow_data_definition_from_subject(post).transitions[transition.name] }%
    &lt;a href="{{ path(transition_data.route) }}">
         {{ transition_data.label }}
   &lt;/a>
{% endfor %}</pre></td>
</tr>
</table>

**Comment by userdude** [comment]
#1 - that already happens, using the places in to/from; I don't see that as a big deal, if a compromise nonetheless. #2-4 could be obviated by the way the data key was loaded in/accessed (e.g., `{{ transition }}` calls `toString()` but `{{ transition.route }}` returns the key). Especially if `workflow.data.transitions` and `workflow.data.places` were "handled" discretely as parts of the other keys. That would beg the question of why separate them in the first place, so of course it doesn't seem any "better" than just putting it together as in your last example. 

Then, I would tend to agree. ;) 

My original thought when I heard about the coming improvement was it was data associated to the *workflow*, not the specific parts of the workflow, so that the workflow configuration could include metadata where the parts are defined. My first (route) example specifically was about having it somewhere sane instead of inferring it from elsewhere other than configuration (where?). I would hope we agree on that. :)

One thing that occurs to me is that having arbitrary keys loaded with functional keys like `transition.route` could one day cause issues with anyone who may have created a key that then becomes it's own functionality. So maybe `transition.related.route` or `place.meta.label` would be more flexible without hemming anyone in.

**Comment by ostrolucky** [comment]
> that already happens, using the places in to/from

This is because there is literally no other way how to define it. With data we have a choice though.

> toString()

I don't see this relevant for the thing we are talking in this issue. We don't have a problem with calling `transition.name`. `toString()` might be useful in reducing impact of BC break when turning place into object though.

> My original thought when I heard about the coming improvement was it was data associated to the workflow, not the specific parts of the workflow

This strategy is used in my second example, that I called "data locator", you see how it's not very nice to use. First example still allows to define arbitrary data for workflow not related to transitions/places though. However, I think most useful use cases in application domain would tie these data to transitions/places anyway.

> So maybe transition.related.route or place.meta.label would be more flexible without hemming anyone in

Oh yeah for sure, that's why I used in my example `transition.data.route`, not `transition.route`

**Comment by userdude** [comment]
There is a way: Read the unique places from the transition definitions (but that would reduce it to stupidity). And quoted from *ideal DX*:

```
    transitions:
        to_review:
            from: draft
            to: review
            label: Submit for review
            route: admin.blog.review
```

Looks like `transitions.to_review.route` to me, this explicitly is what I was referring to (arbitrary `route` definition collides with future `route` functionality). Should be:

```
    transitions:
        to_review:
            from: draft
            to: review
            data:
                label: Submit for review
                route: admin.blog.review
```

Or better (IMO): `meta`, `props`, `attributes`, `related`. `data` is too wishy-washy, IMO.

So. Let's not argue anymore and agree to agree. I don't have a pull request to offer. Is there one to review/like?

**Comment by ostrolucky** [comment]
Oh yeah, makes sense. Good suggestion!

There isn't a PR. I'm not going to work on one until some maintainer speak in and suggest what implementation has potential to be accepted. 

Also still waiting for resolution of https://github.com/symfony/symfony/pull/23310. If even such simple change won't be accepted I don't see a reason to waste effort in more complicated thing like this.

**Comment by lyrixx** [comment]
Hi, obviously the first thing that came in my mind was the very last solution.

```yaml
    transitions:
        to_review:
            from: draft
            to: review
            data:
                label: Submit for review
                route: admin.blog.review
```

Where data is what ever you want ;)

I already rejected this idea but I think I have to change my mind and accept this.

But I'm still very reluctant to let users add whatever they want to the place and the transition because I think users will add too many information in it. Theses information will not be really related to the workflow and so it will create dirty code. And I would like to avoid that at maximum.

What solution I propose: 

* in the Workflow listener => inject whatever you need. Then with the transition name / place name you will be able to fetch the data you need.
* in the Serializer component => create a normalizer and you can inject the data there
* in the Form component => create a form type and inject the data there
* in a template => create a macro or a twig ext to do that (not really DX but it create a clean separation between the workflow and the display)
* in pure PHP code => inject what you need ;)

---

**BUT** I do understand it needs a bit more work and it can seems boring and useless. 

So I'm asking to everyone here: What do you think: should we let user add more information in places and transitions?
