### ISSUE TITLE
[WebProfilerBundle] The debug toolbar is displayed in the printed version

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#23303]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8

```css
/***** Media query print: Do not print the Toolbar. *****/
@media print {
    .sf-toolbar {
        display: none;
        visibility: hidden;
    }
}
```
[This style is present in 2.7](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar.css.twig#L436-L442) but [was removed since 2.8](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar.css.twig) so the toolbar is displayed in the printed version.

Ported from #23274: @javiereguiluz's [comment](https://github.com/symfony/symfony/pull/23274#issuecomment-310926662), @ogizanagi's [comment](https://github.com/symfony/symfony/pull/23274#issuecomment-311037967).
