### ISSUE TITLE
[DependencyInjection] lowercased parameter are inconsistent: config <=> ParametersBag

### ISSUE THREAD

**Issue by TomasVotruba** [symfony/symfony#23381]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

I switched from Nette\DI to Symfony\DI. I use config  `statie.neon` with this parameter setup:

```yaml
parameters:
     basePath: "https://tomasvotruba.cz"
```

I put all parameters to template: 

```php
# pseudo-code

foreach ($this->container->getParameterBag()->all() as $key => $value) {
    $this->template->addValue($key, $value);
}
```

But when I try to render:

```twig
<!-- file.latte -->

{$basePath}
```

I get error, because only `{$base**p**ath}` is available. Parameter names [are lowercased](https://github.com/symfony/symfony/blob/06e21f7597487a354dbaaa441b494e13a438cd8e/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php#L52) in `ParameterBag::add()` method.

I'd expect to keep the name same and not change it in any way. 

What's the reason for this? How can I make it work?

Thank you

**Comment by nicolas-grekas** [comment]
Parameter names are lowercased indeed, that won't change immediately even if we talked about make them case sensitive.
You should use arrays, where keys are preserved, and expose that vaue instead of the full bag:
```yaml
parameters:
  some_name:
    aBc: def
```

**Comment by TomasVotruba** [comment]
> Parameter names are lowercased indeed.

Do you know why?

> You should use arrays, where keys are preserved, and expose that vaue instead of the full bag:

Well that's a workaround. It doesn't make sense to me, just like:

```yaml
parameters:
  parameters:
    aBc: def
```

And neither this override:

```yaml
parameters:
  basePath: value

  # somewhere far away, in another included file 
  basepath: another_value
```

I look at the code and don't see any reason for this.
Could that be removed?
