### ISSUE TITLE
[3.3] Glob loader breaks loading inline YAML resources

### ISSUE THREAD

**Issue by pamil** [symfony/symfony#23412]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes (kind of)
| RFC?             | no
| Symfony version  | 3.3.*

Background for this issue is provided in #22938.

Glob loader breaks Sylius' usage of passing autogenerated routing configuration as `resource` contents:

```yaml
# Not work
sylius_admin_api_carts:
    resource: |
        alias: sylius.order
        path: '/'
        only: [index]
        grid: sylius_admin_api_cart
        section: admin_api
        serialization_version: $version
    type: sylius.resource_api


# Work
sylius_admin_api_carts:
    resource: |
        alias: sylius.order
        #path: '/'
        only: [index]
        grid: sylius_admin_api_cart
        section: admin_api
        serialization_version: $version
    type: sylius.resource_api
```

Given the first config, it tries to use `alias: sylius.order\npath: '` as prefix path.
