### ISSUE TITLE
Autoconfigure for `instanceof` shouldn't configure the abstract instance

### ISSUE THREAD

**Issue by AlmogBaku** [symfony/symfony#23447]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.4

```yaml
services:
    _instanceof:
        App\Admin\AbstractAdmin:
            public: true
            tags: [{ name: sonata.admin, manager_type: orm }]

    App\Admin\AbstractAdmin:
      autoconfigure: false
      autowire: false
      public: false
      abstract: true
```

The autoconfigure shouldn't configure the abstract itself. This issue breaks other bundles since it's trying to also detect the Abstract class as an instance of the tag

**Comment by stof** [comment]
`_instanceof` is not related to `autoconfigure` (even though internal implementations are similar)

**Comment by nicolas-grekas** [comment]
I think the way things work now is the correct way.
If you define an abstract, it means you plan to use child/parent inheritance.
But this doesn't play together with instanceof/defaults inheritance.
You should either use one, or the other. Mixing boths creates dilemna in the resolving logic that can be solved only case by case. e.g. you want your abstract to not have the tag.

Why don't you just define the service as non-abstract?
Setting it as private would make it go:
```
services:
    _instanceof:
        App\Admin\AbstractAdmin:
            autoconfigure: false
            autowire: false
            public: true
            tags: [{ name: sonata.admin, manager_type: orm }]

    App\Admin\AbstractAdmin:
      public: false
```

**Comment by nicolas-grekas** [comment]
Closing as explained - another option is no move the definition of the abstract service in another file. That's already what we suggest when using "parent" inside a file that also have "_instanceof" or "_default".

**Comment by 9ae8sdf76** [comment]
@nicolas-grekas 

My apologies for digging up an old ticket. But, my question is directly related to your comment on [Aug 5](https://github.com/symfony/symfony/issues/23447#issuecomment-320445452) where you state that you shouldn't use `_instanceof` on an abstract service.

However, in my case I do have abstract services that are used with concrete services, and I want to set up `_instanceof` to auto tag unrelated services:

```yaml
services:
    _instanceof:
       My\Custom\ServiceInterface:
            tags: ['my.custom.service']

    my.unrelated.service.abstract:
        abstract: true
        class: My\Unrelated\Service\Abstract

    my.unrelated.service.concrete:
        class: My\Unrelated\Service\Concrete
        parent: 'my.unrelated.service.abstract'
```

Given this definition, I'm getting the following exception:

> The service "my.unrelated.service.concrete" cannot use the "parent" option in the same file where "_instanceof" configuration is defined as using both is not supported. Move your child definitions to a separate file.

I understand what you're saying if I were trying to couple `_instanceof` to `my.unrelated.service.concrete`, but I'm not trying to do that in this use case. It seems almost that whatever checks for `_instanceof` and `parent` in the same config is not actually inspecting `_instanceof` for what's being defined and just assuming that whatever service is using `parent` is also a part of `_instanceof` - which in my case, it's not.

Now I did try and separate the `_instanceof` from my other service definitions, but I can't seem to get the new config file into my container -- I simply added a new `$loader->load()` call in my extension's `load()` method where I loaded the `services.yaml`. Obviously I'm not doing it correctly, but I cannot seem to find any documentation or examples that demonstrate the correct way to do this.

If need be I can create a new ticket, but at the same time I didn't want to incorrectly file another bug report if it's not a bug. I did post in the support channel on Slack, but unfortunately the folks there must not know how to answer this question at this time (that's not a complaint at all). 

Thank you!
