### ISSUE TITLE
[DI] Service deprecation gets lost for privates

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#23536]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

Deprecations seem to get lost when a service is private, consider;

```yaml
a:
    class: stdClass
    public: false
    deprecated: '%service_id% IS DEPRECATED'
b:
    class: stdClass
    public: true
    properties:
        a: '@a'

```

Calling `get('b')->a` works fine, however no deprecation is triggered. Making `a` public fixes the issue.
