### ISSUE TITLE
[DI] Random failures when autowiring classes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23564]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

I'm upgrading a real application to Symfony 3.3 + Flex + autowiring. I'm using the default `app.yaml` config with full autowiring. The problem is that autowiring "randomly" fails.

Yesterday, I saw this error:

```
Expected to find class "App\Controller\AdminController" in file "/Users/javier/<my-
project>/src/Controller/AdminController.php" while importing services from resource
"../../src/*", but it was not found! Check the namespace prefix used with the
resource in /Users/javier/<my-project>/config/packages/app.yaml (which is loaded
in resource "/Users/javier/<my-project>/config/packages/app.yaml").
```

I've checked 100 times: the class exists in that file. Moreover, there are more than 10 controllers in the same location with the same namespace. All of them work, except this one.

Then I removed that AdminController, but I saw this:

```
Expected to find class "App\Test\AbstractTestCase" in file "/Users/javier/<my-
project>/src/Test/AbstractTestCase.php" while importing services from resource
"../../src/*", but it was not found! Check the namespace prefix used with the
resource in /Users/javier/<my-project>/config/packages/app.yaml (which is loaded
in resource "/Users/javier/<my-project>/config/packages/app.yaml").
```

Again, I've checked 100 times. Everything is correct ... but it fails. If I remove that PHP class, the application works perfectly. At least with Symfony 3.3.4.

-----

Today I've just upgraded the application to 3.3.5 ... and I see this error message:

```
Expected to find class "App\Form\Type\AcmeType" in file "/Users/javier/<my-
project>/src/Form/Type/AcmeType.php" while importing services from resource
"../../src/*", but it was not found! Check the namespace prefix used with the
resource in /Users/javier/<my-project>/config/packages/app.yaml (which is loaded
in resource "/Users/javier/<my-project>/config/packages/app.yaml").
```

If I remove that class (which is perfectly fine, including the namespace, and yesterday it worked) the application works again.

-----

I'm sorry I can't give you a better error report, but this is all I know for now: autowiring randomly fails for some classes and makes the app unusable.

**Comment by nicolas-grekas** [comment]
To be accurate, this is unrelated to autowiring.
This exception is triggered in `src/Symfony/Component/DependencyInjection/Loader/FileLoader.php`, in the part responsible for PSR-4 auto-discovery.

A reason for this failure might be that while the class exists, it is not autoloadable, because of eg a missing parent class or something like that.

Before the line calling "getReflectionClass" (L132?), can you add something like:
```
if ('App\Form\Type\AcmeType' === $class) {
    new \ReflectionClass($class);
}
```
Does it throw an exception? Which one?

**Comment by nicolas-grekas** [comment]
can you try this patch? does it report a different error?
```diff
--- a/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
+++ b/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
@@ -129,7 +129,7 @@ abstract class FileLoader extends BaseFileLoader
                 continue;
             }
             // check to make sure the expected class exists
-            if (!$r = $this->container->getReflectionClass($class)) {
+            if (!class_exists($class) || !$r = $this->container->getReflectionClass($class)) {
                 throw new InvalidArgumentException(sprintf('Expected to find class "%s" in file "%s" while importing services from resource "%s", but it was not found! Check the namespace prefix used with the resource.', $class, $path, $pattern));
             }
```

**Comment by javiereguiluz** [comment]
If I make any of the changes you asked for, I see an HTTP 500 error in the browser. I can't reach the Symfony app and no log message is generated.

-----

However, I opened the Apache error log (which I never look at because Symfony provides all the logs I need) and I saw this:

```
[Tue Jul 18 09:22:15.730764 2017] [php7:error] [pid 3379] [client ::1:52886] PHP
Fatal error:  Class 'PHPUnit\\Framework\\TestCase' not found in /Users/javier
/<my-project>/vendor/symfony/framework-bundle/Test/KernelTestCase.php on line 24
```

And I saw a similar error for the AdminController.php

The error about Form types disappeared but I don't know how.

-----

**Summary**: it was all my fault, and there are no random errors. However, when a class is missing, Symfony fails, no log message is generated and I can only find those messages in the error log of my web server.

**Comment by nicolas-grekas** [comment]
I'm sorry I don't get what you say: at first, you describe error message. Then, with a patched file, you get a 500 and find the message in Apache's logs.
But of course, the patched Symfony is not the native Symfony, and of course it behaves in a not perfect way since the patch is intended to debug things, not to define of Symfony behaves or should behave.
Especially since your first description tells about accurate messages.
So, my interrogation resolves to: what was useful in the latest messages that weren't in the first ones that made you realize that *you* had a mistake?

**Comment by javiereguiluz** [comment]
I'm sorry. I'll try to explain better.

The **real cause** of the error is this: *"Class 'PHPUnit\\Framework\\TestCase' not found in ..."*

1) When I reported the problem, I saw this error message in Symfony app:

```
Expected to find class "App\Test\AbstractTestCase" in file "/Users/javier/<my-
project>/src/Test/AbstractTestCase.php" while importing services from resource
"../../src/*", but it was not found! Check the namespace prefix used with the
resource in /Users/javier/<my-project>/config/packages/app.yaml (which is loaded
in resource "/Users/javier/<my-project>/config/packages/app.yaml").
```

In the web server log there's nothing else.

As you can see, Symfony's error message is confusing and doesn't describe the problem well.

2) Then I added this:

```diff
--- a/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
+++ b/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
@@ -129,7 +129,7 @@ abstract class FileLoader extends BaseFileLoader
                 continue;
             }
             // check to make sure the expected class exists
-            if (!$r = $this->container->getReflectionClass($class)) {
+            if (!class_exists($class) || !$r = $this->container->getReflectionClass($class)) {
                 throw new InvalidArgumentException(sprintf('Expected to find class "%s" in file "%s" while importing services from resource "%s", but it was not found! Check the namespace prefix used with the resource.', $class, $path, $pattern));
             }
```

Now the Symfony app doesn't work at all. This is what I see in the browser:

![browser-crash](https://user-images.githubusercontent.com/73419/28306387-64df56e4-6b9f-11e7-8c97-077c4e0e143d.png)

No error message is added to the Symfony log ... but I can see this in the web server error log:

```
[Tue Jul 18 09:22:15.730764 2017] [php7:error] [pid 3379] [client ::1:52886] PHP
Fatal error:  Class 'PHPUnit\\Framework\\TestCase' not found in /Users/javier
/<my-project>/vendor/symfony/framework-bundle/Test/KernelTestCase.php on line 24
```

-----

**Summary**: your patch woks perfectly because it generates the right error message ... but it doesn't generate it in Symfony but in the web server log.

**Comment by nicolas-grekas** [comment]
@javiereguiluz Can you please check #23573?

**Comment by ad3n** [comment]
I have this issue with Symfony 4.0.2

```
Expected to find class "<prefix>\Form\DataTransformer\RoleTransformer" in file "Cms/src/Form/DataTransformer/RoleTransformer.php" while importing services from re  
  source "../src/*", but it was not found! Check the namespace prefix used with the resource.  
```

I'm sure the class is exist and having right namespace...

**Comment by stof** [comment]
please show the content of this file

**Comment by ad3n** [comment]
```
<?php

declare(strict_types=1);

namespace KejawenLab\Application\SemartHris\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;

/**
 * @author Muhamad Surya Iksanudin <surya.iksanudin@kejawenlab.com>
 */
class RoleTransformer implements DataTransformerInterface
{
    /**
     * @param array $roles
     *
     * @return string
     */
    public function transform($roles): string
    {
        if (is_array($roles) && isset($roles[0])) {
            return $roles[0];
        }

        return '';
    }

    /**
     * @param string $roles
     *
     * @return array
     */
    public function reverseTransform($roles)
    {
        return [$roles];
    }
}

```

**Comment by ad3n** [comment]
only like that @stof  and i call in controller as construct parameter

**Comment by xabbuh** [comment]
Please show how you configured your services. Since you are not using the `App` namespace there must be a customised config.

**Comment by ad3n** [comment]
```
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    KejawenLab\Application\SemartHris\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    KejawenLab\Application\SemartHris\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```

I just change the `App` to `KejawenLab\Application\SemartHris`
