### ISSUE TITLE
[Security Bundle][Route] Hash _fragment is lost during generation of login_path

### ISSUE THREAD

**Issue by KateSyrotchuk** [symfony/symfony#23675]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.3

How to reproduce:  Being non-logged in I go to secure area, for example, /admin, it has to redirect to login_path which in my case contains `#`(for example /index#login), but url generated is `/index`.  That’s because an additional attribute “_firewall_context” has been introduced in symfony 3.3.3 (https://github.com/symfony/symfony/pull/22943). 
During generation of login_path url (in Symfony\Component\Routing\Generator\UrlGenerator.php) my _fragment added after parameters (http://index?_firewall_context=security.firewall.map.context.main#login) and lost after `_firewall_context` param is removed

**Comment by javiereguiluz** [comment]
I can't reproduce this error with Symfony 3.3.5. Using the Symfony Demo and this config:

```yaml
form_login:
    default_target_path: /en/blog/search#results
    always_use_default_target_path: true
```

The redirected URL after the login contains the `#results` fragment. Please create a bug reproducer as explained in https://symfony.com/doc/current/contributing/code/reproducer.html and share it with us. Thanks!

**Comment by KateSyrotchuk** [comment]
There is reproducer https://github.com/KateSyrotchuk/symfony-standard/tree/issue_23675 .  You have to type in browser /admin, and system must redirect you to http://localhost:8000#login, but you get http://localhost:8000. During debug, I see that this url is generated as http://localhost:8000/?_controller=AppBundle%5CController%5CDefaultController%3A%3AadminAction&_route=admin&_firewall_context=security.firewall.map.context.main#login  . Fragment added after all system parameters.

**Comment by desmax** [comment]
@javiereguiluz

**Comment by javiereguiluz** [comment]
Thanks to the bug reproducer I can confirm that

1) If you define the URL fragment in a route attribute, **it doesn't work**:

```yaml
# app/config/security.yml
security:
    firewalls:
        main:
            anonymous: true
            form_login:
                login_path: user_security_login

# app/config/routing.yml
user_security_login:
    path:  /whatever
    defaults: { _controller: AppBundle:Default:index, _fragment: 'login' }
```

2) If you use a URL + fragment in `security.yml` instead of a Symfony route, **it works**:

```yaml
# app/config/security.yml
security:
    firewalls:
        main:
            anonymous: true
            form_login:
                login_path: /whatever#login
```
