### ISSUE TITLE
[Yaml] Compact output for Yaml::dump with no wrapping in quotes

### ISSUE THREAD

**Issue by ivangretsky** [symfony/symfony#23681]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

Good day!

I use symfony\yaml module to make some automatic adjustments to multiple yaml configs which are initially written by hand. Everything works fine, bit the output is formatted differently. Is there an option to format the output in "compact" mode and not wrap the values in quotes? Can it be easily added?

Example:
I have this comming into `Yaml::parse`:
```
- name: Комплектация дома
  values:
    - name: Фундамент
      href: /uslugi/stroitel-stvo-fundamenta/
      values:
        - name: Столбчатый из блоков 20х20х40 см ( по 4 блока в опоре )
```
...and this comming out of `Yaml::dump($values, 10)`
```
-
    name: 'Комплектация дома'
    href: '/uslugi/stroitel-stvo-fundamenta/'
    values:
        -
            name: Фундамент
                -
                    name: 'Столбчатый из блоков 20х20х40 см ( по 4 блока в опоре )'
```
