### ISSUE TITLE
[FrameworkBundle] Autoconfigure instances of ArgumentValueResolverInterface

### ISSUE THREAD

**Issue by BPScott** [symfony/symfony#23701]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

Currently the [FrameworkBundle autoconfigures certain interfaces to automatically add tags to them](https://github.com/symfony/symfony/blob/03af7b93ad32eea1fdda91b349a56805f26c939c/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L246).

I'd like to propose instances of `Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface` get the `controller.argument_value_resolver` tag automatically added to them.

This would avoid having to tag each resolver or add an `_instanceof` configuration such as
```yaml
_instanceof:
    Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
        tags: [controller.argument_value_resolver]
```
