### ISSUE TITLE
Autowiring cache pools

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23727]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

In a Symfony app, I have this cache pool config:

```yaml
framework:
    # ...
    cache:
        pools:
            app.cache.stats:
                public: true
```

The app follows old Symfony practices, so the controller does this:

```php
public function statsAction()
{
    $item = $this->get('app.cache.stats')->getItem('...');
    // ...
}
```

-----

I'm moving this app to modern Symfony practices, so I want to autowire everything. In the Symfony Slack chat they told me that this doesn't work and you can't autowire the cache pools. But I'd like to use something like this:

```php
public function statsAction(Cache $cache)
{
    $item = $cache->getPool('app.cache.stats')->getItem('...');
    // ...
}
```

**Comment by GuilhemN** [comment]
Bindings could also help here 😅

You could have a file `stats.yml` for example and inject `app.cache.stats` in all your controllers defined there:
```yml
services:
    _defaults:
        bind:
            Psr\Cache\CacheItemPoolInterface: "@app.cache.stats"

    # ...
```
