### ISSUE TITLE
Could not inject current locale for a service

### ISSUE THREAD

**Issue by funcphp** [symfony/symfony#23726]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.5

I want to use current locale in my service but could not take it

services.yml
```yml
services:
    ...
    app.settings:
        public: true
        class: AppBundle\Repository\SettingRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - 'AppBundle:Setting'
        calls:
            - method: setLocale
              arguments: [ "@=service('request_stack').getCurrentRequest().get('_locale')" ]
    ...
```

SettingRepository.php
```php
    ...
    public function setLocale($locale)
    {
        dump($locale); // output: `null`

        $this->locale = $locale;

        return $this;
    }
    ...
```

Note: I can access current locale in controller with `$this->get('request_stack')->getCurrentRequest()->get('_locale')` or `$request->getLocale()`
