### ISSUE TITLE
Custom ParamConverter bug

### ISSUE THREAD

**Issue by skornev** [symfony/symfony#23751]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | 
| Symfony version  | 3.3.6

It still uses Doctrine converter even the annotation explicitly says to use the custom converter.  I think it's not how it supposed to be. 

action annotation:

`   @ParamConverter(name="id",  converter="custom_converter", class="AppBundle\Entity\MyEntity")
`
services ()

```
   custom_converter:
        class: AppBundle\Request\ParamConverter\CustomConverter
        tags:
            - { name: request.param_converter, priority: -2, converter: custom_converter }

```

```
