### ISSUE TITLE
[Config] YamlReferenceDumper dumps invalid YAML examples for array

### ISSUE THREAD

**Issue by scaytrase** [symfony/symfony#23784]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

Not sure about version, reproduced with latest and some time ago, like 3.1 and 3.2. Did not check 2.x

Reproducing:

```php
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\Definition\Dumper\YamlReferenceDumper;

require_once __DIR__ . '/vendor/autoload.php';

$config = new class implements ConfigurationInterface
{
    /** {@inheritdoc} */
    public function getConfigTreeBuilder()
    {
        $builder = new TreeBuilder();
        $root    = $builder->root('dump_example');

        $root->children()->scalarNode('scalar_value')
             ->example(
                 [
                     'valid value',
                     'another valid value',
                 ]
             );

        
        return $builder;
    }
};

$dumper = new YamlReferenceDumper();

echo $dumper->dump($config);
```

Actual output:
```yaml
dump_example:
    scalar_value:         ~

        # Examples:
        - valid value
        - another valid value

```

Expected output:
```yaml
dump_example:
    scalar_value:         ~

        # Examples:
        # - valid value
        # - another valid value
```

The main idea for me is that reference dumper should generate output, which is 100% valid to be copy-pasted as YAML configuration, isn't it?

**Comment by javiereguiluz** [comment]
@scaytrase definitely this looks like a bug. Let's see if your YAML experts (@xabbuh and @GuilhemN ) can confirm this. Thanks!

**Comment by GuilhemN** [comment]
@javiereguiluz that's valid yaml, just not a valid config file :) it seems more related to the Config Component than to the Yaml Component.

**Comment by javiereguiluz** [comment]
@GuilhemN you are right. It's valid YAML but it's clearly a bug because some contents that should be commented are displayed uncommented. I'm going to add the `config` label. Thanks.

**Comment by scaytrase** [comment]
@GuilhemN how it's valid if the map has both null value (see `~` in output example) and named children?

**Comment by GuilhemN** [comment]
@scaytrase it's not, I just missed the `~` (hard to see on a phone screen 😶).

**Comment by stof** [comment]
I think the issue here is that you are putting an array value as example for a scalar node, and the dumper does not properly deal with this broken example (a scalar node cannot contain an array)

**Comment by scaytrase** [comment]
@stof The dump clearly says, that these are Example**S**, so they can be an array. If not, dump should be constistent with description

**Comment by xabbuh** [comment]
@scaytrase I think the examples would be more precise if they looked like this:

```yaml
dump_example:
    scalar_value:         ~

    # Examples:
    # scalar_value: valid value
    # scalar_value: another valid value
```

Otherwise, you get the impression that you *could* pass sequences while only scalar values are allowed.
