### ISSUE TITLE
sharing two custom authentication methods with the same firewall section

### ISSUE THREAD

**Issue by licarigianluca** [symfony/symfony#23850]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? |yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.9

Hi,
I have two custom authenticators in my application and I'd like to share both with the same firewall pattern. The two authentication methods share the same provider. Is this possible?

This is a fragment of my security.yml
```
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        webservice:
              id: webservice_user_provider

    encoders:
       AppBundle\Entity\WebserviceUser: bcrypt


    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        arpa_basic_auth:
            pattern: ^/
            stateless: false
            anonymous: false
            simple_preauth:
                  authenticator: arpa_basic_auth_authenticator
            provider: webservice
            logout:
                path:   /logout
                target: /


        arpa_legacy:
            pattern: ^/
            stateless: false
            anonymous: false
            simple_preauth:
                  authenticator: arpa_legacy_authenticator
            provider: webservice
            logout:
                path:   /logout
                target: /
```

**Comment by Oliboy50** [comment]
don't know if this could help, but you could take a look at the [Guard authentication](http://symfony.com/doc/current/security/guard_authentication.html), it accepts a list of authenticators:

```yml

        arpa_basic_auth:
            pattern: ^/
            stateless: false
            anonymous: false
            guard:
                authenticators:
                    - AppBundle\Security\BasicAuthAuthenticator
                    - AppBundle\Security\LegacyAuthenticator
            provider: webservice
            logout:
                path:   /logout
                target: /
```

(your authenticators classes will probably need some refactoring)

**Comment by derrabus** [comment]
If you register two firewalls on overlapping or identical patters, the first firewall will win. So, you need to register both of your authenticators on the same firewall and make sure they don't conflict. Migrating them to guard as @Oliboy50 suggested could be the way to go.

**Comment by licarigianluca** [comment]
I followed the instructions of @Oliboy50 and made some refactoring.

 ```
   arpa:
            anonymous: false
            logout: ~
            provider: webservice
            guard:
              entry_point: arpa_basic_auth_guard_authenticator
              authenticators:
                  - arpa_basic_auth_guard_authenticator
                  - arpa_legacy_guard_authenticator`

```
as @derrabus said:

> you need to register both of your authenticators on the same firewall and make sure they don't conflict


Infact I needed an 'OR' mechanism between the two authenticator methods but in this solution, when we use a multiple authenticator mechanism it means that we use both mechanisms symultaneously.
So I have to modify my **getCredentials()** methos of the authenticator and to do so I followed 
this solution https://stackoverflow.com/a/34728682 



```
class MyAuthenticator extends AbstractGuardAuthenticator {
    private $tokenStorage;

    public function __construct(TokenStorageInterface $tokenStorage) {
        $this->tokenStorage = $tokenStorage;
    }

    public function getCredentials(Request $request) {
        if ($this->isAlreadyAuthenticated()) {
            return null; // Skip this authenticator
        }
        // Get the credentials and continue with this authenticator
    }

    protected function isAlreadyAuthenticated() {
        $token = $this->tokenStorage->getToken();
        return $token && $token->isAuthenticated();
    }
```

Thanks to all
