### ISSUE TITLE
[DI] Replace @, @= and @? in yaml

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#23875]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

As pointed by @javiereguiluz in https://github.com/symfony/recipes/pull/144, Symfony 4 aims at making things self explained.
So imo, it's time to replace special syntaxes in yaml by proper tags.

@ could be replaced by ~`!reference`~ `!ref`. @? could be replaced by ~`!expression`~ `!expr`. @? could be replaced by ~`!optional_reference`~ `!?ref`.

Arguments would be a bit more verbose in yaml but I don't think that's a problem as 3.3 and 3.4 provided solutions to make them much lighter and avoid arguments definition in most cases.

What do you think ?

An example to see the difference:
```yml
services:
    App\Mailer:
        # Before
        arguments:
            $mailGenerator: "@App\\MailGenerator"
            $sender: "@=get('App\\MailManager').getSender()"
            $logger: "@?logger"

       # After
        arguments:
            $mailGenerator: !ref App\MailGenerator
            $sender: !expr get('App\MailManager').getSender()
            $logger: !?ref logger
```

~We could even allow `!ref` if we prefer shortcuts.~
