### ISSUE TITLE
Multiple Guards and bad refresh Provider after authentication

### ISSUE THREAD

**Issue by jcodt** [symfony/symfony#23900]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 2.8.26

I implement 2 guards authentification with 2 specifics provider.

```
providers:
        usersecurity:
            id: user_security.user_provider
        apisecurity:
            id: api_security.user_provider
...

 admin_area:
          pattern: ^/admin/
          provider: apisecurity
          guard:
            authenticators:
              - api_security.authenticator
          logout:
            path: /admin/logout
            target: /admin/finish
        front_area:
            pattern: ^/
            anonymous: ~
            provider: usersecurity
            guard:
              authenticators:
                - user_security.authenticator
            logout:
              path: /logout

```

I read
 http://symfony.com/doc/current/security/multiple_guard_authenticators.html 
http://symfony.com/doc/2.8/security/multiple_user_providers.html

My first provider refresh user with database
My second provider refresh user without database

I can authenticate user, but after the first redirection, the security use the provider (default) declare in the first line to refresh User, not the provider declare in the firewall pattern, and so, in my exemple a user authenticated with api_security throw a AuthenticationExpiredException because the provider usersecurity refresh user with database.

When i dump my token the provider key is the name of my firewall pattern "front_area" or "admin_area"

 I try to implement createAuthenticatedToken and specific the name of the providerKey "usersecurity" or "apisecurity" but is the same....

I think the guards config is good because when getUser is call, is the good provider send and i can authenticate user, but i don't know why, after authentication, only first provider declare is use to refresh user.

Do you have similar cases ?
