### ISSUE TITLE
RuntimeException app/console not found on Composer in CI

### ISSUE THREAD

**Issue by Cypaubr** [symfony/symfony#23923]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

Hello, I am using CircleCI with my Symfony project but for a few days this exception appears when `composer update` is executed. The error does neither occur on my dev environment nor on my preprod.

Here is my circle.yml:
```yml
machine:
  php:
    version: 7.0.17

dependencies:
  pre:
    - pecl install mongodb
    - echo "extension=mongodb.so" >> /opt/circleci/php/$(phpenv global)/etc/conf.d/mongodb.ini
    - composer clear-cache

test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
    - phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml tests
```
Thanks in advance.
