### ISSUE TITLE
DI, Tag overwrite and exclude parameters does not work

### ISSUE THREAD

**Issue by esynaps** [symfony/symfony#24005]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

Hi, I use the new DI component of Symfony 3.3.4 and i want to create an abstract class inherited by my controllers. The class is in the Controller folder of my bundle and I'm trying to declare it as a service.

The problem : 

> The service "MyBundle\Controller\AbstractController" tagged "controller.service_arguments" must not be abstract.

```
MyBundle\Controller\:
       resource: '../../Controller'
       exclude: '../../Controller/AbstractController.php'
       public: true
       tags: ['controller.service_arguments']

   MyBundle\Controller\AbstractController:
       abstract: true
       calls:
         - [setRequestService, [MyBundle\Services\RequestService]]
       tags: []
```

The error should not occur because I excluded the file and I overwrited the tag parameter.
