### ISSUE TITLE
3.3.7 killed DotEnv :( 

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony#24015]
3.3.6 working fine.

Composer update to 3.3.7, cleared all caches.. 

config.yml like:

```
snc_redis:
    session:
        client: session
        prefix: "session"
        ttl: 604800
    clients:
        default:
            type: predis
            alias: default
            dsn: "redis://%env(redis_server1)%/%env(redis_db)%"
            logging: "%kernel.debug%"
        cache:
            type: predis
            alias: cache
            dsn: "redis://%env(redis_server1)%/%env(redis_db)%"
            options:
                connection_timeout: 10
                read_write_timeout: 30
```

turns into 

![screen shot 2017-08-28 at 22 20 04](https://user-images.githubusercontent.com/400092/29794263-2a4897f0-8c3f-11e7-90d7-914b42406f33.png)

note the:

`[tcp://env_redis_server_b4db6b8d7bb2020da1133e356d30a3e5:6379]`

that is NOT a server name :(
