### ISSUE TITLE
[DependencyInjection] env var support broken in 3.3.7 and 3.3.8

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#24020]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.7, 3.3.8

I'm using sf flex with propel. This is part of my config:

```yaml
propel:
    database:
        connections:
            default:
                adapter:  pdo_mysql
                user:     '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                dsn:      'pdo_mysql:host=%env(DATABASE_HOST)%;dbname=%env(DATABASE_NAME)%;charset=utf8'
```

With symfony/dependency-injection 3.3.7 and 3.3.8 I get this exception:

![screenshot 2017-08-29 11 20 52](https://user-images.githubusercontent.com/330436/29814010-266f3680-8cac-11e7-80c5-e30478bc4baa.png)

https://github.com/symfony/symfony/pull/24016 didn't fix this case.

When I switch back to 3.3.6 it works again.

ping @nicolas-grekas
