### ISSUE TITLE
[DependencyInjection] Factory limitation when using the new syntax on the same class

### ISSUE THREAD

**Issue by mykiwi** [symfony/symfony#24042]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | ?
| Symfony version  | 3.1 I guess

When you create a service with a factory, using the same class to create it, you will have a circular reference. Example:

```yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Gitlab\Client:
        factory: 'Gitlab\Client:create'
        arguments: ["http://my.gitlab"]
```

>   [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]               
>  Circular reference detected for service "Gitlab\Client", path: "Gitlab\Client -> Gitlab\Client".  
 

To fix this, I must used the old syntax:
```yaml
    Gitlab\Client:
        factory: ['Gitlab\Client', create]
        arguments: ["http://my.gitlab"]
```
