### ISSUE TITLE
composer install Exception with Doctrine custom Mapping Type in config.yml

### ISSUE THREAD

**Issue by dlee3** [symfony/symfony#24069]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| RFC?             | no
| Symfony version  | 3.3.6 & 3.3.8

I followed the documentation on the Symfony & Doctrine sites to create a Doctrine custom Mapping Type. The custom type functions as expected when using it to access the database. I'm able to save to the field and I get no errors.

However, when trying to do a new install of the app using `composer install` it errors out when trying to clear the cache. If I comment out the type my custom Mapping Type in the config.yml, the composer install runs without a problem, however, the install will not complete properly with the custom Mapping Type listed in the yml.

Here is what the doctrine dbal section of my config.yml file looks like:
```yaml
doctrine:
    dbal:
        default_connection: default
        types:
            datetimeold: AppBundle\Doctrine\Type\DateTimeSqlServer
        connections:
            default:
                driver:   pdo_sqlsrv
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
            los:
                driver:   pdo_sqlsrv
                host:     "%los_host%"
                port:     "%los_port%"
                dbname:   "%los_name%"
                user:     "%los_user%"
                password: "%los_password%"
```

Here's the composer install verbose output:
 ```                          
> symfony-scripts: Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
                                                 
  [Doctrine\DBAL\Driver\PDOException]                                          
  SQLSTATE[HY000]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]SSPI P  
  rovider:  The operation or option is not available                           
                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]SSPI P  
  rovider:  The operation or option is not available                           
                                                                               
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception
                                                                                   
  [RuntimeException]                                                               
  An error occurred when executing the "'cache:clear --no-warmup'" command:        
                                                                                   
    [Doctrine\DBAL\Driver\PDOException]                                            
    SQLSTATE[HY000]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]SSPI P    
    rovider:  The operation or option is not available                                                                                                 
                                                                                   
    [PDOException]                                                                 
    SQLSTATE[HY000]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]SSPI P    
    rovider:  The operation or option is not available                 

Exception trace:
 () at ~/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php:293
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::executeCommand() at ~/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php:143
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:282
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:205
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:81
 Composer\EventDispatcher\EventDispatcher->dispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:189
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:307
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:54
 require() at /usr/local/bin/composer:24            
```

Links to the documentation I followed to setup my custom Mapping Type:
https://symfony.com/doc/current/doctrine/dbal.html
http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#custom-mapping-types
