### ISSUE TITLE
[DI] Default autowiring settings are lost for a Controller when arguments are explicitly set, and the controller doesn't extends the FrameworkBundle Controller class

### ISSUE THREAD

**Issue by magarzon** [symfony/symfony#24124]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

When a controller has a dependency to a parameter instead of a service, you have to explicitly set that arguments this way:

```yaml
services:
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: [controller.service_arguments]

    AppBundle\Controller\AdminController:
        arguments:
            $adminEmail: 'manager@example.com'
```
The issue is that when doing this, if the controller doesn't extend FrameworkBundle Controller class, it lost all default configuration, as in this example, AdminController doesn't have `controller.service_arguments` tag nor `public: true` setting anymore, and you must explicitly set also.
