### ISSUE TITLE
doctrine reverse engineering fields options fixed: true bug

### ISSUE THREAD

**Issue by lcp0578** [symfony/symfony#24211]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.12

```
php bin/console doctrine:mapping:import --force KitAdminBundle yml  --filter="UserTest"
Importing mapping information from "default" entity manager
  > writing D:\xampp\htdocs\kitlabs\KitPHP\src\KitAdminBundle/Resources/config/doctrine/UserTest.orm.yml
```
UserTest.orm.yml
```
KitAdminBundle\Entity\UserTest:
    type: entity
    table: user_test
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        mobile:
            type: string
            nullable: false
            length: 11
            options:
                fixed: true  # this is true
```
convert annotation
```
php bin/console doctrine:mapping:convert annotation ./src --filter=UserTest
Processing entity "KitAdminBundle\Entity\UserTest"
```
UserTest.php
```
class UserTest
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=32, nullable=false)
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="mobile", type="string", length=11, nullable=false)
     */
    private $mobile;
}
```
but @ORM\Column(name="mobile", type="string", length=11, nullable=false) not **filxed=true**
thx
