### ISSUE TITLE
Bug in twig function workflow_transitions

### ISSUE THREAD

**Issue by mjrsanders** [symfony/symfony#24217]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

I have the following workflow:

![worksheet](https://user-images.githubusercontent.com/19168634/30485627-523a9158-9a2e-11e7-9571-b9700f1c0407.png)

```
framework:
    workflows:
        worksheet:
            supports: Content\ContentBundle\Entity\Worksheet\Worksheet
            places:
                - draft
                - unconnected_ws
                - connected_ws
                - wait_for_peer_review
                - wait_for_admin_review
                - approved_by_peer
                - approved_by_admin
                - published
            transitions:
                first_save:
                    guard: "is_granted('ROLE_EDITOR')"
                    from: draft
                    to: unconnected_ws
                add_connections:
                    guard: "is_granted('ROLE_EDITOR')"
                    from: unconnected_ws
                    to: connected_ws
                remove_connections:
                    guard: "is_granted('ROLE_EDITOR')"
                    from: connected_ws
                    to: unconnected_ws
                request_review:
                    guard: "is_granted('ROLE_EDITOR')"
                    from: connected_ws
                    to:
                        - wait_for_peer_review
                        - wait_for_admin_review
                approve_worksheet_by_peer:
                    guard: "is_granted('ROLE_EDITOR')"
                    from: wait_for_peer_review
                    to: approved_by_peer
                reject_worksheet_by_peer:
                     guard: "is_granted('ROLE_EDITOR')"
                     from: wait_for_peer_review
                     to:
                        - unconnected_ws
                        - connected_ws
                approve_worksheet_by_admin:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: wait_for_admin_review
                    to: approved_by_admin
                publish_worksheet_by_admin:
                    guard: "is_granted('ROLE_ADMIN')"
                    from:
                        - unconnected_ws
                        - connected_ws
                        - wait_for_admin_review
                    to: published
                reject_worksheet_by_admin:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: wait_for_admin_review
                    to:
                        - unconnected_ws
                        - connected_ws
                publish:
                    guard: "is_granted('ROLE_ADMIN')"
                    from:
                        - approved_by_peer
                        - approved_by_admin
                    to: published
```

I am logged in as Admin. The object is in 'connected_ws'. When I use the twig function workflow_transitions(object). I expect the get 3 possible transitions: remove_connections, request_review, publish_worksheet_by_admin. I get only 2 (remove_connections, request_review).

When I change the transition publish_worksheet_by_admin to:

```
                publish_worksheet_by_admin:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: connected_ws
                    to: published
```

all works as expected.

**Comment by xabbuh** [comment]
This looks expected to me. The workflow must be in the `unconnected_ws`, `connected_ws` **and** `wait_for_admin_review` places for the `publish_worksheet_by_admin` to be applicable.

**Comment by mjrsanders** [comment]
Yes, but publish_worksheet_by_admin is not available when I am logged in as Admin and the object is in connected_ws.

**Comment by mjrsanders** [comment]
The bug is in Symfony/Component/Workflow/Workflow.php in

```php
private function doCan($subject, Marking $marking, Transition $transition)
{
    foreach ($transition->getFroms() as $place) {
        if (!$marking->has($place)) {
            return false;
        }
    }

    if (true === $this->guardTransition($subject, $marking, $transition)) {
        return false;
    }

    return true;
}
```
changed to 
```php
private function doCan($subject, Marking $marking, Transition $transition)
{
    $return = false;
    foreach ($transition->getFroms() as $place) {
        if ($marking->has($place)) {
            $return = true;
        }
    }

    if (true === $this->guardTransition($subject, $marking, $transition)) {
        return false;
    }

    return $return;
}
```
fixes the problem.

**Comment by xabbuh** [comment]
Because your workflow is neither in the `unconnected_ws` nor the `wait_for_admin_review` place.

**Comment by mjrsanders** [comment]
Ok so basically, how I've set this up is wrong then? 

My goal was to have a transition for the admin to bypass all places and directly publish. 

Any advice on how to accomplish this?

**Comment by xabbuh** [comment]
Duplicating what you were trying to do looks like the solution to me:

```yaml
publish_unconnected_worksheet_by_admin:
    guard: "is_granted('ROLE_ADMIN')"
    from: unconnected_ws
    to: published
publish_connected_worksheet_by_admin:
    guard: "is_granted('ROLE_ADMIN')"
    from: connected_ws
    to: published
publish_waiting_for_review_worksheet_by_admin:
    guard: "is_granted('ROLE_ADMIN')"
    from: wait_for_admin_review
    to: published
```
