### ISSUE TITLE
Is Guard authenticator considering access_control?

### ISSUE THREAD

**Issue by Cypaubr** [symfony/symfony#24252]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

Hello, I created a basic TokenAuthenticator extending the *AbstractGuardAuthenticator* class by following [this tutorial](https://symfony.com/doc/current/security/guard_authentication.html).

The problem is that the firewall using this TokenAuthenticator does not care about the access_control.

Is there a way to make it using access_control?

**Comment by iltar** [comment]
As written in the template for new issues:
```
<!--
- Please fill in this template according to your issue.
- For support request or how-tos, visit https://symfony.com/support
- Otherwise, replace this comment by the description of your issue.
-->
```

**Comment by xabbuh** [comment]
Can you create a small example project or show some code that allows to reproduce your issue?

**Comment by Cypaubr** [comment]
@xabbuh I just created a TokenAuthenticator like the one of the tutorial:

```php
<?php

namespace CityfidAPIBundle\Security;

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Guard\AbstractGuardAuthenticator;

class TokenAuthenticator extends AbstractGuardAuthenticator
{
    public function getCredentials(Request $request)
    {
        if (!$token = $request -> headers -> get('X-AUTH-TOKEN')){
            $token = null;
        }
        return array(
            'token' => $token
        );
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $apiKey = $credentials['token'];
        if (null === $apiKey){
            return;
        }
        return $userProvider -> loadUserByUsername($apiKey);
    }

    public function checkCredentials($credentials, UserInterface $user)
    {
        return true;
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
       return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        $data = array(
            'message' => strtr($exception -> getMessageKey(),$exception -> getMessageData())
        );
        return new JsonResponse($data,Response::HTTP_FORBIDDEN);
    }

    public function start(Request $request, AuthenticationException $authException = null)
    {
        $data = array(
            'message' => 'Authentication Required'
        );
        return new JsonResponse($data,Response::HTTP_UNAUTHORIZED);
    }

    public function supportsRememberMe()
    {
        return false;
    }
}
```

And of course my security.yml:

```yaml
# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
services:
    cityfid.mongodb.driver:
        parent: doctrine_mongodb.odm.security.user.provider
        arguments: [CityfidCoreBundle\Document\User, email]
    cityfid.api.mongodb.driver:
        parent: doctrine_mongodb.odm.security.user.provider
        arguments: [CityfidCoreBundle\Document\User, apiKey]
    cityfid.api.tokenauthenticator:
        class: CityfidAPIBundle\Security\TokenAuthenticator

security:
    role_hierarchy:
        ROLE_SELLER: ROLE_USER
        ROLE_ADMIN: ROLE_USER, ROLE_SELLER, ROLE_ALLOWED_TO_SWITCH

    encoders:
        CityfidCoreBundle\Document\User:
            algorithm: bcrypt
        CityfidAPIBundle\Document\ApiUser:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        mongodb:
            id: cityfid.mongodb.driver
        mongodb_api:
            id: cityfid.api.mongodb.driver

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/
            anonymous: ~
            security: true
            stateless: true
            guard:
                provider: mongodb_api
                authenticators:
                    - cityfid.api.tokenauthenticator

        backoffice:
            pattern: ^/manage/
            anonymous: ~
            security: true
            provider: mongodb
            form_login:
                login_path: cityfid_backoffice_connect
                check_path: cityfid_backoffice_connect_check
                use_forward: true
                post_only: true
            logout:
                path: cityfid_backoffice_logout
                invalidate_session: true
            remember_me:
                secret: "%secret%"
                secure: true
                lifetime: 604800

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/api/add/business$, role: ROLE_ADMIN }
        - { path: ^/api/ping$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: ROLE_USER }

        - { path: ^/manage/connect$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manage/printapikey$, roles: [ROLE_USER,IS_AUTHENTICATED_FULLY] }
        - { path: ^/manage/recover/password$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manage, roles: [ROLE_SELLER] }
```

As I said, the problem is that this authentication method does not follow the *access_control* rules, for example, the route */api/ping* gives me a 403.
