### ISSUE TITLE
using env var fails in framework.translator.paths (cache)

### ISSUE THREAD

**Issue by mathroc** [symfony/symfony#24270]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

when using an env var inside the value of a framework.translator.paths, the env var value is not resolved, and instead its placeholder is given to the translator

```yml
parameters:
  active_site: '%env(ACTIVE_SITE)%'

framework:
    translator:
        paths:
            - "%kernel.root_dir%/../src/ST/AppBundle/Resources/translations_sites/%active_site%"
```

>  UnexpectedValueException
> /var/www/app/../src/ST/AppBundle/Resources/translations_sites/env_ACTIVE_SITE_1210a6ec49918eebfffc01fc4f72ca65 defined in translator.paths does not exist or is not a directory

note: same thing happen if I use the env directly like that:

```yml
framework:
    translator:
        paths:
            - "%kernel.root_dir%/../src/ST/AppBundle/Resources/translations_sites/%env(ACTIVE_SITE)%"
```

**Comment by ro0NL** [comment]
Yep, we're working on it :) see #23888 

What's happening here is crucial; with this config you opt-in to _dynamic values_, fetched during runtime. Their real current value is not compiled into the container.

So imagine in your case the application runs with 

```
$_ENV['ACTIVE_SITE'] = 'env_ACTIVE_SITE_1210a6ec49918eebfffc01fc4f72ca65';
```

(or any other value really).  Given that, the error starts making sense. Basically we cant assume what the real value is, this remains even with #23888. But feedback is welcome very much :)

So to make this truly work config needs lax validation.

**Comment by mathroc** [comment]
thx @ro0NL

I kinda understand why I have `env_ACTIVE_SITE_1210a6ec49918eebfffc01fc4f72ca65` inside the string, my guess is that env vars are not extrapolated until runtime and instead placeholder are placed inside the compiled container. Since the translator paths are used to build the translation cache, I figure this happen before the env vars are fetched so the build of the cache still have the placeholders.

So I understand that in this case Symfony would not pick up if the ACTIVE_SITE var changed once the cache is built and I’m fine with this (but I guess this can be source of confusion too)

my use case is that when I’m deploying my app I want to build the cache once and keep it for later, the env var is already set when composer runs `clear:cache` so I expected `%env(ACTIVE_SITE)%` to get its value.

for now I’m using `incenteev/dynamic-parameters-bundle` instead but I’d hope to get rid of it eventually as it’s unmaintained and #23901 solves my others use cases that I’m using `incenteev/dynamic-parameters-bundle` for

but I’m not sure what will change with #23888, it seems to change the behavior of the container compilation, so I don’t know what to expect because the container compilation seems fine to me. here it fails on cache warmup. maybe env vars are not supposed to be used at that point, in that case an error message saying so should be added. or env vars can be used when warming up the cache and . maybe it should explicitly be declared in the config to avoid confusion:

```yml
framework:
    translator:
        paths:
            - "%this_value_can_be_saved_to_cache(%kernel.root_dir%/../src/ST/AppBundle/Resources/translations_sites/%active_site%)%"
```

I hope I’m not completely off the mark here and that I didn’t misunderstood what is achieved by #23888
