### ISSUE TITLE
Cannot call static method on factory class

### ISSUE THREAD

**Issue by ansidev** [symfony/symfony#24315]
| Q | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8, 3.3.9

I am using factory to create Symfony service but I cannot call static method on factory class as described at [Using a Factory to Create Services](http://symfony.com/doc/current/service_container/factories.html).

Error looks like this:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]    
  You have requested a non-existent service "AppBundle\Email\NewsletterManagerStaticFactory"
```

Please help me! Thank you very much!

**Comment by iltar** [comment]
Seems more of a support issue rather than a bug report. Your class is simply not registered as service.

For support, please check https://symfony.com/support (as mentioned in the issue template).

**Comment by ansidev** [comment]
@iltar: I don't think so.
You don't need register factory class as a service when you call its static method to create other service.

> Part of tutorial:

Suppose you have a factory that configures and returns a new ``NewsletterManager``
object by calling the static ``createNewsletterManager()`` method::

    class NewsletterManagerStaticFactory
    {
        public static function createNewsletterManager()
        {
            $newsletterManager = new NewsletterManager();

            // ...

            return $newsletterManager;
        }
    }

To make the ``NewsletterManager`` object available as a service, you can
configure the service container to use the
``NewsletterManagerStaticFactory::createNewsletterManager()`` factory method:

```yaml
        # app/config/services.yml
        services:
            # ...

            AppBundle\Email\NewsletterManager:
                # call the static method
                factory: ['AppBundle\Email\NewsletterManagerStaticFactory', createNewsletterManager]
```

When using a factory to create services, the value chosen for class has no effect on the resulting service. The actual class name only depends on the object that is returned by the factory. However, the configured class name may be used by compiler passes and therefore should be set to a sensible value.
