### ISSUE TITLE
[DependencyInjection] Service defaults by trait

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#24327]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

## Description

It would be great to define default service definition by trait usage.

This could be a great alternative for some auto-wiring setter like parameters, instead of manual definition.

## Concrete case

Here is my `KernelRootDirTrait`:

```php
trait KernelRootDirTrait
{
    /**
     * @var string
     */
    private $kernelRootDir;

    /**
     * @return string
     */
    public function getKernelRootDir(): string
    {
        return $this->kernelRootDir;
    }

    /**
     * @param string $kernelRootDir
     */
    public function setKernelRootDir(string $kernelRootDir)
    {
        $this->kernelRootDir = $kernelRootDir;
    }
}
```

And the service:

```php
class MyService
{
    use KernelRootDirTrait;
}
```

If we could define the default by trait usage like this:

```yaml
services:
    _trait:
        AppBundle\PropertyTrait\KernelRootDirTrait:
            calls:
                - [setKernelRootDir, ['%kernel.root_dir%']]
```

With that, the `MyService` service will automatically have the `%kernerl.root_dir%` parameter. :-)

The interest of trait is the re-usability of them. This will remove lot of manual parameter definition lines.

What do you think?

**Comment by nicolas-grekas** [comment]
If we can workaround adding this, that'd be better IMHO, because that's adding complexity where we already have some :)
So, I see two work arounds:
- using instanceof/autoconfiguration - that currently needs a "type" to check for but that maybe still OK. if not, I see no reason why it we shouldn't extend it to match traits
- but maybe we need nothing, because we already have bindings, which would allow you to define that any argument named `$kernelRootDir` should get the "%kernel.root_dir%" value automatically. That's a single line in you config file, see #22187

**Comment by Soullivaneuh** [comment]
Hi @nicolas-grekas,

So you are telling me if I write:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $kernelRootDir: '%kernel.root_dir%'
```

Each service having `$kernelRootDir` on a constructor or a setter will be filled by `%kernel.root_dir%`?

This may be indeed a good alternative in this case.

> because that's adding complexity where we already have some :)

Well, how this would be more complex than `instanceof` detection? :-)
