### ISSUE TITLE
Session restarted at every request

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#24370]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Flex version  | latest

Hi everyone, 

I met a small (in fact, big problem) problem using Flex, I've configured the session to be available and the service is injected into the container, problem is, the session restart on every page/request and all the "variables" passed into it are deleted, here's the config from Flex : 

```yaml
framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true
    #trusted_hosts: ~
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    assets:
        base_urls: '%env(BASE_URLS)%'
```

As you can see, the session is configured and ready to be used, problem is, when I call it from the controller, she's restarted every time : 

```php
<?php 

namespace App\Controller;

use App\Form\Login;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;

class IndexController extends Controller
{
    public function home()
    {
        $this->get('session')->set('sdsqdq','hello');

        return $this->render('home.html.twig');
    }

    public function login(Request $request)
    {
        $view = $this->get('form.factory')->create(Login::class);
       dump($request->getSession()->get('sdsqdq'));
        return $this->render(
            'connectionForms.html.twig',
            ['form' => $view->createView()]
        );
    }

    public function register(Request $request)
    {
        $view = $this->get('App\Services\Register')->registerUser($request);
        if($view === 'home')
        {
            return $this->redirectToRoute($view);
        }
        return $this->render(
            'connectionForms.html.twig',
            ['form' => $view[0]]
        );
    }
 // ...
```

When I call the dump into the login method, the dump return null even if my session has stored the value 'hello'. If I open the var/sessions folder, I see as much sess file as requests I've build then the file linked to the login 'session' doesn't show the hello value, any thoughts about this? 

_PS : I call the session via the Request objet but even with $this->get('session'), the problem stay the same._

I've try to clean the cache and the sessions but the problem stay the same :/ 

Thanks again for the help.
