### ISSUE TITLE
Autowiring fails with argument explicitly set

### ISSUE THREAD

**Issue by InputOutput** [symfony/symfony#24404]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

Autowiring seems to be failing on detecting an explictly set argument to a RequestListener. Interestingly enough, the DatabaseSynchronizerService, which is defined in the same services.yml and also has a combination of Services and parameters injected, is not causing any exceptions on startup.

```
 root@cf5a76d38063:/srv/k2go-backend-symfony# bin/console

                                                                                                                                                                                                          
  [Symfony\Component\DependencyInjection\Exception\AutowiringFailedException]                                                                                                                             
  Cannot autowire service "K2Go\AppBundle\EventListener\RequestListener": argument "$availableLocales" of method "__construct()" must have a type-hint or be given a value explicitly.                    
  Cannot autowire service "K2Go\CmsBundle\Service\SidebarService": argument "$requestListener" of method "__construct()" references class "K2Go\AppBundle\EventListener\RequestListener" but no such ser  
  vice exists.                                                                                                                                                                                            
                                                                                                                                                                                                          

 ```

Relevant part of services.yml:
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    K2Go\AppBundle\Service\DatabaseSynchronizerService:
        arguments: ["@doctrine", "@K2Go\\AppBundle\\Service\\AWSS3Service", "%database_host%", "%database_port%", "%database_user%", "%database_password%", "%database_name%"]

    K2Go\AppBundle\EventListener\RequestListener:
        arguments:
            $availableLocales: '%available_locales%'
        tags:
            - { name: kernel.event_listener, event: kernel.request }
```

Relevant part of config.yml:
```
parameters:
    locale: nl_NL
    default_locale: nl_NL
    available_locales:
        - nl_NL
        - nl_BE
```

RequestListener::__construct:
```
<?php
namespace K2Go\AppBundle\EventListener;

use Symfony\Component\HttpKernel\Event\GetResponseEvent;

class RequestListener
{
    private $availableLocales;
    private $currentLocale;

    /**
     * @param array $availableLocales
     */
    public function __construct(array $availableLocales) {
        $this->availableLocales = $availableLocales;
    }
```

I've tried removing the request_listener tag, setting a hardcoded value for available_locales, using the old-style notation (as in DatabaseSynchronizerService), clearing cache both via console and manually (rm -rf var/cache/dev), moving the offending service around in the services.yml and a few other things I forget ;)
