### ISSUE TITLE
Allow to overwrite security config

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#24461]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

Recall for https://github.com/symfony/symfony/issues/22308 :)

```yaml
# security.yaml
firewalls:
    # ....
    api:
        pattern: ^/api
        stateless: true
        anonymous: true
    # ...
```

```php
# bundle extension
public function prepend(ContainerBuilder $container)
{
    $security = $container->getExtensionConfig('security');
    $security[0]['firewalls']['api']['anonymous'] = false;
    $security[0]['firewalls']['api']['fos_oauth'] = true;

    $container->loadFromExtension('security', $security[0]);
}
```

Result
```
Configuration path "security.access_control" cannot be overwritten. You have to define all options for this path, and any of its sub-paths in one configuration section.
```

I understand `loadFromExtension` adds a new config branch (`$configs[] = $config`). But im trying to fake 1 config branch, so i guess i need reflection to clear current branch first.

Can we create API for that? Or what about allowing overwrites on existing elements?

Thx!
