### ISSUE TITLE
[DI] 3.4 Service definitions with line breaks in arguments/properties dumped incorrectly when as_files option used

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#24470]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.x

Assume we have a service with multi-line string used as value for property:

```yaml
    some_service_id:
        class: stdClass
        properties:
            test1: 1
            test2: >
                Text (
                    Inner Text
                )
            test3: 321
```

This is how this definition dumped to php code when `PhpDumper` used with `as_files` option (default):

```php
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'some_service_id' shared service.

$this->services['some_service_id'] = $instance = new \stdClass();

$instance->test1 = 1;
$instance->test2 = 'Text (
r Text


$instance->test3 = 321;

return $instance;
```

This file contains incorrect `test2` property, and incorrect syntax.
