### ISSUE TITLE
[HttpFoundation] RequestStack::getCurrentRequest doesn't work

### ISSUE THREAD

**Issue by TonyFenton** [symfony/symfony#24492]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.1

After upgrade symfony/symfony from 3.3.0 to 3.3.1 RequestStack::getCurrentRequest return null instead of  Request.
I follow the http://symfony.com/doc/current/service_container/request.html

So, I have:

```yaml
#app/config/services.yml
services:
    app_bundle.fosuser_redirect:
        class: AppBundle\EventListener\FOSUserRedirectListner
        arguments: [ '@request_stack']
        tags:
            - { name: kernel.event_subscriber }
```

And:

```php
// src/AppBundle/EventListener/FOSUserRedirectListner.php

namespace AppBundle\EventListener;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\RequestStack;

class FOSUserRedirectListner implements EventSubscriberInterface
{
    private $locale;

    public function __construct(RequestStack $requestStack)
    {
        $this->locale = $requestStack->getCurrentRequest()->getLocale();
    }

    // ...
}
```
