### ISSUE TITLE
Monolog logger autowires default channel logger

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#24496]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Given

```php
use Psr\Log\LoggerInterface;
class Some {
    public function __construct(LoggerInterface $logger) { }
}
```

```yaml
services:
    _defaults: { autowire: true, autoconfigure: true, public: false }
    Ns\Some:
        tags: [ { name: monolog.logger, channel: my_channel } ]
```

I get the `app` channel logger. However if i add 

```yaml
Ns\Some:
    arguments: { '$logger' : '@logger' }
    tags: [ { name: monolog.logger, channel: my_channel } ]
```

I get the `my_channel` logger. Can we improve that?
