### ISSUE TITLE
APCu Cache Data not cleared under Symfony 3.1

### ISSUE THREAD

**Issue by pascalwacker** [symfony/symfony#24545]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.3

```
// app/config/config_prod.yml
[...]
framework:
    validation:
        cache: validator.mapping.cache.doctrine.apcu
    serializer:
        cache: serializer.mapping.cache.apcu

doctrine:
    orm:
        metadata_cache_driver: apcu
        query_cache_driver: apcu
        result_cache_driver: apcu
        second_level_cache:
            enabled: true
```

We're using APCu to speed up our Symfony application. When changing an Entity field the server throws an `Uncaught PHP Exception ReflectionException`.

let's say we have an Entity in `AppBundle\Entity\Foo.php` which has a field `$bar` that field has type text and is present in the prod MySQL db. If we now go on and change the name of `$bar` to `$baz` (and also the name for the db as well as the getter and setter methods), apply the changes to the live system, run `cache:clear --env=prod --no-debug`, `cache:warmup --env=prod --no-debug` and `doctrine:schema:update --force` and then visit the page, we'll get an `500 Internal Server Error`.

Checking the prod logs we get:
```
[2017-10-13 11:01:30] request.CRITICAL: Uncaught PHP Exception ReflectionException: "Property AppBundle\Entity\Foo::$bar does not exist" at /home/userfoobar/www/pagename/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php line 80 {"exception":"[object] (ReflectionException(code: 0): Property AppBundle\\Entity\\Foo::$bar does not exist at /home/userfoobar/www/pagename/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80)"} []
```

Which is not surprising, as we removed `AppBundle\Entity\Foo::$bar` and changed it to `AppBundle\Entity\Foo::$baz`. It seams that the `cache:clear` command didn't clear the APCu cache.

I would expect the `cache:clear` command to take care of all caches. Am I wrong in this assumption?

Note: I also tried to use the following commands: `doctrine:cache:clear-metadata  --env=prod`, `doctrine:cache:clear-query  --env=prod` and `doctrine:cache:clear-result --env=prod`, unfortunately without luck.
Note: I'm not sure if it is fixable however, as mentioned in this thread: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2355 it seams that there are different APCu caches for the CLI version of PHP as well as FPM/fast-cgi

**Comment by nicolas-grekas** [comment]
When you clear the cache, the dumped factory method should contain a random version string that should prevent this issue. Can you please check your dumper container file and find this string (search for "new ApcuAdapter"). Does the version change when you clear the cache?

**Comment by pascalwacker** [comment]
So I ran a grep on the server with enabled caching (like stated in the sniped above). The result was:

```
[user@server:~/www] $ grep -irn "new ApcuAdapter" pagename/
pagename/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:81:        $apcu = new ApcuAdapter($namespace, $defaultLifetime / 5, $version);
pagename/vendor/symfony/symfony/src/Symfony/Component/Cache/Tests/Adapter/ApcuAdapterTest.php:30:        return new ApcuAdapter(str_replace('\\', '.', __CLASS__), $defaultLifetime);
pagename/vendor/symfony/symfony/src/Symfony/Component/Cache/Tests/Adapter/ApcuAdapterTest.php:50:        $pool1 = new ApcuAdapter($namespace, 0, 'p1');
pagename/vendor/symfony/symfony/src/Symfony/Component/Cache/Tests/Adapter/ApcuAdapterTest.php:60:        $pool2 = new ApcuAdapter($namespace, 0, 'p2');
```
I'm guessing you're talking about the `$namespace` in `pagename/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:81`

**Comment by nicolas-grekas** [comment]
I mean `$version` (the namespace is stable, $version is not).
can you grep var/cache for "ApcuAdapter"? before and after clear?

**Comment by pascalwacker** [comment]
Didn't produce any result.
`grep -irn "ApcuAdapter" var/cache/` didn't return anything
`php bin/console cache:clear --env=prod --no-debug`
`php bin/console cache:warmup --env=prod --no-debug`
`grep -irn "ApcuAdapter" var/cache/` didn't return anything

Do I need to enable the `ApcuAdapter` somewhere? If so where? `app/AppKernel.php` or `web/app.php`

This would be the content of my `web/app.php` file:
```
<?php

use Symfony\Component\HttpFoundation\Request;

/**
 * @var Composer\Autoload\ClassLoader
 */
$loader = require __DIR__.'/../app/autoload.php';
include_once __DIR__.'/../var/bootstrap.php.cache';

$kernel = new AppKernel('prod', false);
$kernel->loadClassCache();
//$kernel = new AppCache($kernel);

// When using the HttpCache, you need to call the method in your front controller instead of relying on the configuration parameter
//Request::enableHttpMethodParameterOverride();
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
```

**Comment by nicolas-grekas** [comment]
Oh sorry I read to fast. So yes, the behavior is expected: doctrine's integration with apcu doesn't handle this situation, as described in FriendsOfSymfony/FOSUserBundle#2355

You'd need to wire a Symfony cache pool to do so (and replace "apcu" in the config).
Here is an example:

```yaml
# first create a PSR-6 pool for our cache items, derived from cache.system
framework:
    cache:
        pools:
            app.cache.doctrine_orm:
                adapter: cache.system

# then create a Doctrine cache provider out of this PSR-6 pool
services:
    app.doctrine_orm.cache:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments:
            - '@app.cache.doctrine_orm'

# and use it in doctrine
doctrine:
   orm:
       metadata_cache_driver:
           type: service
           id: app.doctrine_orm.cache
```
