### ISSUE TITLE
[HttpKernel] Bindings scalar named arguments to action method does not work

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#24555]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

I have this controller/action with a scalar argument `$env`:
```php
public function postShowAction(Post $post, string $env): Response
{
    // do something with $env
}
```

My configuration to bind this argument:
```yaml
services:
    _defaults:
        # ...
        bind:
            $env: '%kernel.environment%'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```

`> bin/console cache:clear`:
> Type error: Argument 1 passed to Symfony\Component\DependencyInjection\Argument\ServiceClosureArgument::__construct() must be an instance of Symfony\Component\DependencyInjection\Reference, string given, called in /home/yceruto/github/symfony/symfony-demo/vendor/symfony/dependency-injection/Compiler/ServiceLocatorTagPass.php on line 81

Setting a plain string value (`$args[$p->name] = $bindingValue;` -> `'%kernel.environment%'`)...
https://github.com/symfony/symfony/blob/42390a2b00cf9c48af37137bdc9ada8255b275b4/src/Symfony/Component/HttpKernel/DependencyInjection/RegisterControllerArgumentLocatorsPass.php#L137-L139

...that later will be passed to `ServiceLocatorTagPass::register()` which expects a `Reference` instance for each arg:
https://github.com/symfony/symfony/blob/42390a2b00cf9c48af37137bdc9ada8255b275b4/src/Symfony/Component/HttpKernel/DependencyInjection/RegisterControllerArgumentLocatorsPass.php#L160-L162

I don't have idea how it should be solved, so repo/branch to reproduce the bug:
* https://github.com/yceruto/symfony-demo/tree/upgrade_to_34

Note: This work fine with constructor arguments (as `__constructor` method is not included in the previous _"pass"_ but `ResolveBindingsPass`).

ping @nicolas-grekas, @GuilhemN
