### ISSUE TITLE
[DI] with ability to use constructor

### ISSUE THREAD

**Issue by Karthons** [symfony/symfony#24584]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Maybe this is already implemented and I did not figure out how to do it. Basically I want to create new instances of my custom object with the logger as Dependency Injection AND I want to be able to use the constructor. According to the documentation, I should be able to use the setter Dependency Injection to achieve it.

```php
// src/AppBundle/Service
namespace AppBundle\Service;

use Psr\Log\LoggerInterface;

  class CustomObject {

  private $logger;

  /**
   * @param mixed $logger
   */
  public function setLogger(LoggerInterface $logger)
  {
    $this->logger=$logger;
  }

  public function log() {
    // for debugging purposes here
    dump($this->logger);
  }
}
```

services.yml

```yaml    
services:
    AppBundle\Service\Test:
        public: true
        calls:
            - method: setLogger
              arguments:
                  - '@logger'
```

```php
// Custom Controller
$test = new CustomObject ()
$test->log();
```

Expected behaviour:
The new instance of CustomObject has the logger.

Result:
The new instance does not have it.
