### ISSUE TITLE
session not working when security disabled

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#24588]
hello

when I disable security in one of my firewall, then I can not get service session or variable $_SESSION
it's not initialised

**Comment by stof** [comment]
well, have you enabled the session layer in FrameworkBundle or no ?

**Comment by poolerMF** [comment]
normally I can access to service "session" and it's initialised/not empty  ... or I can access to global variable $_SESSION

@stof I do not understand ... but I think, I have it enabled

**Comment by xabbuh** [comment]
@poolerMF Can you create a small example then that allows to reproduce your issue?

**Comment by poolerMF** [comment]
symfony v 3.3.10


security.yml
````
security:

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public:
            pattern: /public/.*
            security: false

        main:
            anonymous: ~
````


DefaultController:
````
class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        dump($_SESSION);

        return $this->render('default/index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.project_dir')).DIRECTORY_SEPARATOR,
        ]);
    }

    /**
     * @Route("/public/test", name="test")
     */
    public function testAction(Request $request)
    {
        dump($_SESSION);

        return $this->render('default/index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.project_dir')).DIRECTORY_SEPARATOR,
        ]);
    }
}
````


Result:
**indexAction** -> OK
**testAction** -> Undefined variable: _SESSION
