### ISSUE TITLE
[DX][FrameworkBundle] Simpler route configuration for templates and redirections 

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24640]
## Context

In #23227 we made this change:

```yaml
# BEFORE ----------------------------------------------------------------------
blog_show:
    path:     /blog/{slug}
    defaults: { _controller: App\Controller\BlogController::showAction }

# AFTER -----------------------------------------------------------------------
blog_show:
    path:       /blog/{slug}
    controller: App\Controller\BlogController::showAction
```

In #24637 we improved a bit the routes that render a template directly, but I don't think that's enough.

## Proposal

Let's finish #23227 by adding shortcuts for templates and redirections:

### Templates

```yaml
# BEFORE ----------------------------------------------------------------------
blog_show:
    path:     /blog/{slug}
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: blog/show.html.twig

# AFTER -----------------------------------------------------------------------
blog_show:
    path:     /blog/{slug}
    template: blog/show.html.twig
```

### Redirections

If the value of `redirect_to` starts with `/` or `//` or `http://` or `https://`, it's considered a URL redirect. Otherwise, it's a route redirect:

```yaml
# BEFORE ----------------------------------------------------------------------
blog_show:
    path:     /blog/{slug}
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
        path: /some-relative-url
        permanent: true

# AFTER -----------------------------------------------------------------------
blog_show:
    path:        /blog/{slug}
    redirect_to: /some-relative-url
    permanent:   true
```

```yaml
# BEFORE ----------------------------------------------------------------------
blog_show:
    path:     /blog/{slug}
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: some-other-route

# AFTER -----------------------------------------------------------------------
blog_show:
    path:        /blog/{slug}
    redirect_to: some-other-route
```

**Comment by chalasr** [comment]
👍

**Comment by Simperfit** [comment]
👍

**Comment by stof** [comment]
These would require making the routing component depend on FrameworkBundle (these special controllers are part of the bundle, but route definitions are handled in the component)

**Comment by javiereguiluz** [comment]
@stof there's no need for that. If you have router + frameworkbundle, you can use this feature. If you don't have frameworkbundle and try to use this feature, you'll see an exception. We already do that for lots of Symfony features.

**Comment by kiler129** [comment]
This is indeed a great simplification. Huge :+1:

**Comment by sroze** [comment]
Proposed a PR for the redirection in #25145

**Comment by nicolas-grekas** [comment]
> If you don't have frameworkbundle and try to use this feature, you'll see an exception

I'm really not sure about that part. And I'm not sure we do it for any Symfony features. High-level can adapt to changing low level stuffs. But having a low level stuff (Routing) know about a high level one (FrameworkBundle) looks strange to me.

**Comment by nicolas-grekas** [comment]
Instead, I would do it differently: instead of setting a controller, the `redirect_to` entry could just set a new entry in "defaults", named eg "_redirect_to" instead of "_controller". Then it'd be up to high level layers to act upon it.

**Comment by sroze** [comment]
Yep, I agree it would be a better option. Let's discuss the implementation details within the PR :)

**Comment by dunglas** [comment]
Or maybe can we just pass unknown keys (or even all keys) as request's attributes. It solves all issues and provides a great extension point for new usages.

**Comment by sroze** [comment]
But this increases the risk of a bad DX because of typos and things like that... I'd prefer having a proper validation around it tbh

**Comment by voronkovich** [comment]
I think we don't need the `template` keyword to configure templates. We can set the template using the `controller`:
```yaml
about:
    path: /about
    controller: static/about.html.twig
```
This feature can be implemented with a simple event subscriber, like this:
```php
<?php

namespace App\EventSubscriber;

use Symfony\Bundle\FrameworkBundle\Controller\TemplateController;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Twig\Environment;

class TemplateControllerSubscriber implements EventSubscriberInterface
{
    private $container;
    private $twig;
    private $templating;

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => 'onKernelRequest',
        ];
    }

    public function __construct(ContainerInterface $container, Environment $twig = null, EngineInterface $templating = null)
    {
        $this->container = $container;
        $this->twig = $twig;
        $this->templating = $templating;
    }

    public function onKernelRequest(GetResponseEvent $event): void
    {
        $request = $event->getRequest();

        $controller = $request->attributes->get('_controller');

        if (null === $controller || $this->container->has($controller) || is_callable($controller)) {
            return;
        }

        if ($this->templateExists($controller)) {
            $request->attributes->set('_controller', TemplateController::class);
            $request->attributes->set('template', $controller);
        }
    }

    private function templateExists(string $name): bool
    {
        if ($this->twig && $this->twig->getLoader()->exists($name)) {
            return true;
        }

        if ($this->templating && $this->templating->has($name)) {
            return true;
        }

        return false;
    }
}
```
