### ISSUE TITLE
[DI] Monolog Tag + _instanceof with autowiring fails

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#24675]
| Q                | A
| ---------------- | -----
| Bug report?      | yes ?
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

This is a bit related to https://github.com/symfony/monolog-bundle/issues/218 and https://github.com/symfony/monolog-bundle/issues/228. With a service having a `Psr\Log\LoggerInterface` dependency, if the `monolog.logger` tag with the appropriate channel is not given, it works as intended. But once we add said tag, the DI complains that the `Psr\Log\LoggerInterface` cannot be found.

Another precision is that the tag is added on a `_instanceof` section, as following :

```php
<?php
namespace Acme;

use Psr\Log\LoggerInterface;

class Foo implements Bar
{
    public function __construct(?LoggerInterface $logger)
    {
    }
}
```

```yaml
_instanceof:
    Acme\Bar:
        tags:
            - { name: "monolog.logger", channel: "foo" }

Acme\Foo: ~
```
