### ISSUE TITLE
Command logging configuration for dockerized Symfony

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#24788]
Currently there is no good way to configure logging from Commands for a dockerized Symfony.

If you run Symfony in a PHP-FPM docker container, you will most likely log to stderr for FPM invocations (and therefore forward to docker log deamon with the following default FPM configuration from the official PHP docker images https://github.com/docker-library/php/blob/05fe6f9eb601984e5f95057578ce830a21d11716/7.1/alpine3.4/fpm/Dockerfile#L160 ).

The problem with this is, that if you run a Command from CLI, you will always see the log output in stderr and there is currently either no simple or documented way to prevent this.

Lets take the following logging config for dev env:
```yml
monolog:
    handlers:
        main:
            type:         group
            members:      [file, stderr]
        file:
            type:         rotating_file
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
            channels:     ["!event"]
            max_files:    3
        stderr: # gets caught by FPM process and forwarded to docker log deamon
            type:         stream
            path:         "php://stderr"
            level:        info
            channels:     ["!event"]

        console:
            type:         console
            channels:     ["!event", "!doctrine"]
```
Basically the `stderr` handler needs to be completely removed/silenced, when using the console.

It would be nice, if Symfony would provide a solution to this.

One that comes to my mind, is to provide a `ConsoleFilterHandler`, that listens to the console events like the `ConsoleHandler`, but insteadof writing to an output, when a command gets executed, it just throws away the log messages and only forwards them, if no command is running. Then a configuration like this could work:
```yml
monolog:
    handlers:
        main:
            type:         group
            members:      [file, stderr_filter]
        file:
            type:         rotating_file
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
            channels:     ["!event"]
            max_files:    3
        stderr_filter:
            type:         console_filter
            handler:      stderr
        stderr: # gets caught by FPM process and forwarded to docker log deamon
            type:         stream
            path:         "php://stderr"
            level:        info
            channels:     ["!event"]

        console:
            type:         console
            channels:     ["!event", "!doctrine"]
```

**Comment by backbone87** [comment]
I have noticed that the approach with the console events dont work, because log messages are already trigger during container compilation before the events are triggered.

An alternative i came up with is using the `PHP_SAPI` constant:
```php
class SapiFilterHandler extends FilterHandler
{
    private $enabled;

    public function __construct(HandlerInterface $handler, array $sapis, bool $negate = false, bool $bubble = true)
    {
        parent::__construct($handler, Logger::DEBUG, Logger::EMERGENCY, $bubble);

        $this->enabled = in_array(PHP_SAPI, $sapis);
        $negate && $this->enabled = !$this->enabled;
    }

    public function isHandling(array $record): bool
    {
        return $this->enabled && parent::isHandling($record);
    }
}
```

**Comment by carsonbot** [comment]
Thank you for this issue.
There has not been a lot of activity here for a while. Has this been resolved?

**Comment by carsonbot** [comment]
Friendly ping? Should this still be open? I will close if I don't hear anything.

**Comment by carsonbot** [comment]
Hey,

I didn't hear anything so I'm going to close it. Feel free to comment if this is still relevant, I can always reopen!

**Comment by PawelSuwinski** [comment]
I handled it on config level:
```
parameters:
    env(SAPI): 'PHP_SAPI'

services:
    monolog.handler.app:
        class: Monolog\Handler\Handler
        factory: >
            @=env("const:SAPI") == "cli"
                ? service("monolog.handler.null")
                : service("monolog.handler.stderr")
    monolog.handler.null:
        class: Monolog\Handler\NullHandler
        arguments: ['info']
    monolog.handler.stderr:
        class: Monolog\Handler\StreamHandler
        arguments: ['php://stderr', 'info']

monolog:
    handlers:
        console:
            type: console
           (...)
        # should go last
        app:
            type: service
            id: app.monolog.handler.app
```
