### ISSUE TITLE
Cookie_domain randomly log me in some unused account?

### ISSUE THREAD

**Issue by milosmoto** [symfony/symfony#24843]
Bug report?  yes
Symfony version   2.7.3

I have security issue on my symfony website. I am using wildcard subdomains:

*.example.com

My config.yml configuration is:

```
    session:
        handler_id:  session.handler.redis
        cookie_domain: .example.com
        cookie_lifetime: 0
```

It happens randomly that I am logged in with another account that I never used before. So I just type sub.example.com and I am logged in as some other user?
