### ISSUE TITLE
[WebProfilerBundle]: hard-coded route path leads to incorrect URL

### ISSUE THREAD

**Issue by mtibben** [symfony/symfony#24868]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.3.10

https://github.com/symfony/symfony/pull/19973 added a default IDE file link web view, however the URL it uses is [hard-coded in `Resources/config/profiler.xml`](https://github.com/symfony/symfony/pull/19973/files#diff-887163fa008beee125295c3f16ef7489R56) rather than using the [route at `Resources/config/routing/profiler.xml`](https://github.com/symfony/symfony/pull/19973/files#diff-5fc2fa4ee96c1246c01adcac692c1ae7R31).

This means that if you use a route prefix e.g.
```yaml
_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /my-prefix/_profiler
```
the URL produced by `debug.file_link_formatter` is `/_profiler/open` instead of `/my-prefix/_profiler/open`
