### ISSUE TITLE
Auto register some rational required services and parameters ...

### ISSUE THREAD

**Issue by pmpr-ir** [symfony/symfony#24911]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.10

I am somehow new to Symfony, started reading the documentation a few weeks ago, but as it [has around 3.6 million words, more than three times the word count of the entire Harry Potter series](https://symfony.com/blog/the-new-symfony-documentation-search-engine), it must take a while to get important details about this beautiful work (thanks to @fabpot and others...).

As of now, I think something useful could be added to the framework, maybe in future:

Some basic assumptions:

| p                | => | q
| ---------------- | -- | -----
| **Symfony framework** | is | often an infrastructure for **business logic** 
| A good architectural pattern for **business logic** | is | **MVC** |
| **Model** in MVC | has | a **Handler** section (responsible for model layer requests) |
| A **Handler** | should | rationally have access to the persistence layer (**Entity Manager** and **Entity**) |

Thanks to the [new symfony service container since 3.3](https://symfony.com/doc/current/service_container/3.3-di-changes.html), it is now much easier than before to register a new handler service:

```
parameters:
    acme_app_entity_feedback: Acme\Bundle\AppBundle\Model\Entity\Feedback

services:
    Acme\Bundle\AppBundle\Model\Handler\FeedbackHandler:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $dataClass: '%narmafzam_app_entity_feedback%'
```
But still you need to provide the entity class as an argument. that could harm RAD to register every single entity handler. I think this is should get refactored somewhere to help developers, rapidly develop business logic without any need to do these sort of repeating stuff.

 I think there should be an OutOfTheBox functionality to support that.

**Comment by jakzal** [comment]
Thank you for dedicating your time to contribute to the framework with your improvement idea.

Why do you need to make the Feedback class configurable for the FeedbackHandler? It seems that the handler is a concrete implementation and can only work with a single entity, so I don't really understand why it needs to be configurable.

It looks like you're describing a very specific (custom) approach. Since it's custom, or not a well established approach, imo it doesn't belong to the core framework.

**Comment by peyman-mohamadpour** [comment]
Thank you for your reply.

I think a **Handler**, should be able to handle persistence layer requests, without any information about concrete entity class address. Assume that you want to develop a distributable & reusable package, which should be configurable (using DependencyInjection) with user provided information about the concrete entity class.

According to the provided snippet, I can inject user provided entity class address into my Handler.

I hope you can get my point, as I am not a native English speaker

**Comment by iltar** [comment]
Symfony is Configuration over Convention though, so you won't be seeing that in the core.

What you can  to make autowiring possible:
```yml
services:
    Doctrine\ORM\EntityManagerInterface:
        alias: doctrine.orm.entity_manager
```

Please don't mistake Symfony for an MVC framework though (nor any other php framework).
