### ISSUE TITLE
[RFC] Make the 'resource: .' config optional for custom routing loaders

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24977]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Not a big deal because using custom routing loaders is uncommon, but it's strange to have to add this fake `resource: .` config when using a custom loader. See https://symfony.com/doc/current/routing/custom_route_loader.html.

```yaml
# app/config/routing.yml
app_extra:
    resource: .
    type: extra
```

We could make `.` the default value of `resource` ... or make that only when not using one of the built-in loaders provided by Symfony.
