### ISSUE TITLE
[RFC] Make the 'Action' suffix optional in controllers-as-services

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24976]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

In this page: https://symfony.com/doc/current/controller/service.html we explain an alternative syntax to use controllers-as-services in route definitions:

```yaml
hello:
    path:     /hello
    defaults: { _controller: app.hello_controller:indexAction }
```

My concern is the note below that example:

```
You cannot drop the Action part of the method name when using
the single colon notation.
```

If this is still true, isn't it a bit arbitrary? Could we make the `Action` suffix optional?
