### ISSUE TITLE
[Workflow][DX] Config silently transforms transition names in keys

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#24981]
Given the following workflow config:
```yml
            transitions:
                some-transition:
                    from: some-state
                    to:   some-other-state
```
Causes the transition to be created with the name `some_transition` without any warning whatsoever. I guess its the `Configuration`'s `fixXmlConfig` that does this, so i guess it would affect other config areas as well, where you are free to choose a key and the configured component/bundle/module allows for `-` in such names.

Transitions explicitly allow the usage of `-` in transition names.
Currently this can be avoided by not using the keyed transition config, but the array like config
```yml
            transitions:
                -   name: some-transition
                    from: some-state
                    to:   some-other-state
```

If this cant be fixed, it would be nice to deprecate the keyed transition config and only allow the array style.

**Comment by chalasr** [comment]
These keys should not be normalized. PR welcomed on master, see #24018 for inspiration.

**Comment by MarioBlazek** [comment]
@chalasr I've created PR for this one. I would appreciate your comments there. Thanks.

**Comment by lyrixx** [comment]
I'm sorry, I'm going to close your issue because there are no **really easy** way to deal with BC.
More over there is already a way to fix this issue (as you state in the description, but I put it here again, just in case):

before:

```yaml
transitions:
    request-review: # Does not work because it's normalized
        from: draft
        to:
            - wait_for_journalist
            - wait_for_spellchecker


```

after:

```yaml
transitions:
    -
        name: request-review
        from: draft
        to:
            - wait_for_journalist
            - wait_for_spellchecker

```
