### ISSUE TITLE
[Router][DX] Relative resource references should resolve against the config file's location

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#24982]
When using relative route resource references, these references are resolved against the kernel root dir and not like all other config files against the file's location itself.
This is also mentioned in the ticket implementing relative route resource references: https://github.com/symfony/symfony/pull/21231#issuecomment-272418629

This is especially painful because using file relative references *sometimes* work:
```yml
app:
    resource: ../../src/Action/
    type:     annotation
```
This config works for me in one project, but in another project, i had to use:
```yml
app:
    resource: Action/
    type:     annotation
```
And i dont know why it works in one and not the other, both use the 3.4-BETA2 and are bundle less apps with kernel at `/src/Kernel.php` and config file at `/etc/_common/_routing.yml`
