### ISSUE TITLE
[DependencyInjection] argument of method "__construct()" must have a type-hint or be given a value explicitly. 

### ISSUE THREAD

**Issue by peyman-mohamadpour** [symfony/symfony#25020]
| Q                | A
| ---------------- | -----
| Bug report?      | **yes**
| Feature request? | **no**
| BC Break report? | **no**
| RFC?             | **no**
| Symfony version  | 3.3.13

## Command

```shell
bin/console c:c
```

## Error

> Cannot autowire service "Acme\AppBundle\Form\AbstractEntityType": argument "$dataClass" of method "__construct()" must have a type-hint or be given a value explicitly. 

## Bundle's configuration

```yml
services:
    Acme\AppBundle\Form\ConversionType:
        arguments:
            $dataClass: Acme\AppBundle\Entity\Conversion
        tags:
            - {name: form.type}
```

## Form Service
```php
class ConversionType extends AbstractEntityType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->('title', TextType::class);
    }
}
```

## AbstractEntityType

```php
class AbstractEntityType extends AbstractType
{
    protected $dataClass;

    public function __construct(string $dataClass)
    {
        $this->dataClass = $dataClass;
    }

    public function getDataClass()
    {
        return $this->dataClass;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => $this->getDataClass()
        ));
    }
}
```

Its weird, because `AbstractEntityType` is not a service, but `ConversionType` is. The **PhpStorm Symfony plugin**, wrongly detects `AbstractEntityType` as a service, too.
