### ISSUE TITLE
Memcached Error since 3.4.0 BETA 4

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#25036]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-BETA4

Since i upgraded from 3.4.0-BETA3 to 3.4.0-BETA4 i got the error message: 

```
Fatal error: Uncaught ErrorException: constant(): Couldn't find constant Memcached::OPT_LAZY in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php:147
Stack trace: #0 [internal function]: Symfony\Component\Cache\Adapter\MemcachedAdapter::Symfony\Component\Cache\Traits\{closure}(2, 'constant(): Cou...', '/var/www/html/v...', 147, Array) 
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php(147): constant('Memcached::OPT_...') 
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php(138): Symfony\Component\Cache\Adapter\MemcachedAdapter::createConnection(Array, Array) 
#3 /var/www/html/var/cache/dev/ContainerFgwxh3x/appDevDebugProjectContainer.php(667): Symfony\Component\Cache\Adapter\AbstractAdapter::createConnection('memcached://cac...', Array) 
#4 /var/www/html/var/cache/dev/ContainerFgwxh3x/appDevDebugProjectContainer.php(748): ContainerFgwxh3x\appDevDebugProjectContainer->getCache_AppService() 
#5 /var/ww in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 147
```
I found out its the cache pool definition in config.yml

```yaml
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
        packages:
            static:
                version: "%revision%"
    php_errors:
        log: true
    web_link:
        enabled: true
    cache:
        app: cache.adapter.memcached
        default_memcached_provider: "memcached://%memcached_server%"
```
I could't found where the lazy option is set, but when i downgrade to BETA 3 its working. So i guess there is a issue with the beta4.
