### ISSUE TITLE
[DI][Improvement] Allow to define a default value on environment variables

### ISSUE THREAD

**Issue by vincentchalamon** [symfony/symfony#25129]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Since Symfony 3.4, it's now possible to parse environment variables using `%env()%` tool: https://goo.gl/8Zsed6

But in some environment, I don't have the right environment variables set, so the application is not bootable (on Insight analysis for instance). To fix it, I need to define the environment variable on a parameter key:
```yml
parameters:
    db_hostname: '%env(DB_HOSTNAME)%'
    env(DB_HOSTNAME): db

doctrine:
    dbal:
        host: '%db_hostname%'
```

It should be interesting to parse a default value directly on the `%env()%` tool:
```yml
doctrine:
    dbal:
        host: '%env(default:db:DB_HOSTNAME)%'
```

**Comment by nicolas-grekas** [comment]
That should actually be quite easy, as a new processor. The actual syntax would need a swap:
`%env(default:FOO:defaultvalue)%`, so that the default value could contain a colon.
BUT, this would actually be of limited use, since the allowed characters between `env(...)` is quite limited (and it shouldn't be widened.)

You can simplify your example a bit if you want:
```
parameters:
    env(DB_HOSTNAME): db

doctrine:
    dbal:
        host: '%env(DB_HOSTNAME)%'
```

**Comment by vincentchalamon** [comment]
But what about `resolve` (for instance)? Should I declare exactly the same in parameters?:
```yml
parameters:
    env(resolve:DB_HOSTNAME): db

doctrine:
    dbal:
        host: '%env(resolve:DB_HOSTNAME)%'
```

This also ask a good question: if we allow `default` keyword, we should also allow multiple _keywords_ usage, like: `%env(default:resolve:DB_HOSTNAME:defaultvalue)%`

**Comment by nicolas-grekas** [comment]
> Should I declare exactly the same in parameter

nope

> should also allow multiple keywords usage

it's already allowed

**Comment by nicolas-grekas** [comment]
> should also allow multiple keywords usage

OK, no, in fact it should be reversed: `resolve:default:DB_HOSTNAME:defaultvalue`

**Comment by vincentchalamon** [comment]
OK, thanks for your feedback. I'll try to open a PR soon for this default value improvement

**Comment by javiereguiluz** [comment]
@vincentchalamon I don't understand this:

> But what about resolve (for instance)? Should I declare exactly the same in parameters?:

Resolve is needed in env vars because they can't interpolate the container parameters. But that's not a problem in your example:

```yaml
parameters:
    # use container params here without doing anything special
    env(DB_HOSTNAME): '%kernel.project_dir%/db'

doctrine:
    dbal:
        host: '%env(resolve:DB_HOSTNAME)%'
```
 I don't think Symfony needs to change anything about this behavior. Could you please share some realistic config that it's impossible to do with Symfony? Thanks!

**Comment by vincentchalamon** [comment]
@javiereguiluz
> But what about resolve (for instance)? Should I declare exactly the same in parameters?:

I was thinking about following syntax:
```yml
parameters:
    env(resolve:DB_HOSTNAME): 'foo'
```
But I was wrong, the right syntax is what you wrote. Thanks :-)

In this improvement/question issue, the idea is to simplify the configuration and not having to declare a parameter key for the default value:
```yml
doctrine:
    dbal:
        host: '%env(resolve:default:DB_HOSTNAME:%kernel.project_dir%/db)%'
```

**Comment by nicolas-grekas** [comment]
`host: '%env(resolve:default:DB_HOSTNAME:%kernel.project_dir%/db)%'`

What I said before: this won't work, as `/` is not allowed between `env()`.
Which means I'm personally not sure it's a good idea.

**Comment by vincentchalamon** [comment]
In this case, you're right (I was also afraid about `%` or other characters not allowed in `env()`), and I should declare a parameter as default value of my environment variable.

But I think the default value in `env()` could be useful for more simple variables to don't declare them all as parameters just for a default value. For instance, in my current project, I should declare 18 parameters as default values for my 18 environment variables. So the ideal configuration should be like (using `env(default…)` idea):
```yml
parameters:
    locale: en
    env(DB_HOST): %kernel.project_dir%/db

doctrine:
    dbal:
        driver:   "%env(default:DATABASE_DRIVER:pdo_mysql)%"
        host:     "%env(resolve:DATABASE_HOSTNAME)%"
        port:     "%env(int:default:DATABASE_PORT:3306)%"
        dbname:   "%env(default:DATABASE_NAME:api_platform)%"
        user:     "%env(default:DATABASE_USER:api_platform)%"
        password: "%env(default:DATABASE_PASSWORD:api_platform)%"
        charset: "%env(default:DATABASE_CHARSET:utf-8)%"
        server_version: "%env(default:DATABASE_SERVER_VERSION:5.7)%"

swiftmailer:
    transport: '%env(default:MAILER_TRANSPORT:smtp)%'
    host: '%env(default:MAILER_HOST:127.0.0.1)%'
    username: '%env(default:MAILER_USER:null)%'
    password: '%env(default:MAILER_PASSWORD:null)%'
```
etc. for each environment variable used in my configuration (JWT Token Paths, CORS Allow Origin…).
