### ISSUE TITLE
[DI] Prevent an infinite loop when using env vars in service names

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#25123]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.11

Related to this thread: https://github.com/symfony/symfony/pull/24673

With this commit it's not possible anymore to use an environment parameter as name of in_memory providers. It's not really a big problem but it's a BC break when upgrading from 3.3.10 to 3.3.11. Is it wanted?

Example:

```yml
parameters:
    admin_username: '%env(ADMIN_USERNAME)%'
    admin_password: '%env(ADMIN_PASSWORD)%'

providers:
    in_memory:
        memory:
            users:
                - { name: "%admin_username%", password: "%admin_password%", roles: 'ADMIN' }
```

Lead to this exception:
```
[Symfony\Component\DependencyInjection\Exception\EnvParameterException]        
    A service name ("security.user.provider.concrete.in_memory_%env(ADMIN_USER    
    NAME)%") cannot contain dynamic values.  
```

**Comment by nicolas-grekas** [comment]
How did it work previously? A service name cannot be dynamic, so maybe it just didn't work as you expected, and you didn't notice? That's what we thought when adding the exception: this will tell ppl they did a misconfig.

**Comment by raziel057** [comment]
I can tell you it worked because I use JWT to authenticate real users (stored in my application) and a specific digest authentication to access the API documentation. I used a different ``username`` and ``password`` in the different environment we have (qa, uat, prod) and it worked as expected taking the defined ENV parameters. I think the service name is not directly used for authentication in ``in_memory`` provider. So the service name was ``security.user.provider.concrete.in_memory_%env(ADMIN_USER    
    NAME)%`` but the name was resolved at authentication level.

```yml
security:
    firewalls:
        api:
            pattern:   ^/api
            stateless: true
            entry_point: app.digest_entry_point
            http_digest:
                provider: in_memory
                realm:    "%digest_realm%"
                secret:   "%kernel.secret%"
            guard:
                provider: default
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

services:

    app.digest_entry_point:
        class: Symfony\Component\Security\Http\EntryPoint\DigestAuthenticationEntryPoint
        arguments:
            - '%digest_realm%'
            - '%kernel.secret%'
```
