### ISSUE TITLE
ajax login 302

### ISSUE THREAD

**Issue by lcp0578** [symfony/symfony#25144]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

security.yml

```
security:
    encoders:
        RbacBundle\Entity\User:
            algorithm: bcrypt
    providers:
        database_admin_users:
            entity:
                class: RbacBundle:User
                property: username
    firewalls:
        admin_firewalls:
            pattern:   ^/admin
            anonymous: ~
            provider: database_admin_users
            guard:
                authenticators:
                    - admin.admin_form_login_authenticator
            form_login:
                login_path: admin_login_index
                check_path: admin_login_check
                default_target_path: /admin
                username_parameter: _username
                password_parameter: _password
                failure_path: kit_admin_login
            logout:
                handlers: [rbac.logout_handler]
                path: admin_login_logout
                target: admin_login_index
        mobile_firewalls:
            pattern: ^/mobile
            anonymous: ~
            provider: database_admin_users
            guard:
                authenticators:
                    - admin.mobile_form_login_authenticator
            form_login:
                login_path: member_index
                check_path: member_login
                default_target_path: member_index
                username_parameter: _username
                password_parameter: _password
                failure_path: member_index
            logout:
                path: member_logout
                target: member_index
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/forget, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/mobile/member, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mobile, roles: ROLE_ADMIN }
```
ajax login
![qq 20171124191413](https://user-images.githubusercontent.com/10859621/33208256-d023f2d6-d14b-11e7-8253-0575ce24c764.png)

direct access
![qq 20171124191441](https://user-images.githubusercontent.com/10859621/33208290-ec5ecf02-d14b-11e7-85f1-cd919558010e.png)

what's wrong?
thx
