### ISSUE TITLE
security access_control bug

### ISSUE THREAD

**Issue by lcp0578** [symfony/symfony#25154]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.13

security.yml
```
firewalls:
        mobile_firewalls:
            pattern: ^/mobile
            methods: [GET, POST]
            anonymous: ~
            provider: database_admin_users
            guard:
                authenticators:
                    - admin.mobile_form_login_authenticator
            form_login:
                login_path: member_index
                check_path: member_login
                default_target_path: member_index
                username_parameter: _username
                password_parameter: _password
                failure_path: member_index
            logout:
                path: member_logout
                target: member_index
security:
    ....
    access_control:
        - { path: ^/mobile/member, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mobile, roles: ROLE_ADMIN }
```
when GET is right. 
![1](https://user-images.githubusercontent.com/10859621/33226086-2a6861d6-d1c0-11e7-8f6d-33b70c500a96.png)
but,when POST,it is redirect to login page.
![2](https://user-images.githubusercontent.com/10859621/33226101-5cf1c6f6-d1c0-11e7-8193-c2b3e6ebb2d4.png)
I read symfony doc. modify security.yml

```
 mobile_firewalls:
            pattern: ^/mobile
            methods: [GET, POST] # add this line
            anonymous: ~
            provider: database_admin_users
            guard:
                authenticators:
                    - admin.mobile_form_login_authenticator
            form_login:
                login_path: member_index
                check_path: member_login
                default_target_path: member_index
                username_parameter: _username
                password_parameter: _password
                failure_path: member_index
            logout:
                path: member_logout
                target: member_index
```
but it didn't work.
thx
