### ISSUE TITLE
debug:container output not correct when trailing slash in services.yaml.

### ISSUE THREAD

**Issue by Rubinum** [symfony/symfony#25193]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0RC2

The output of `bin/console debug:container` displays a `</fg=cyan>` after services declared in the services.yaml with a trailing slash. 

Example:

```
# config/services.yaml
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{DataFixtures,Entity,Migrations,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # here is the trailing slash
    App\Services\Test\:
        class: 'App\Service\Test'
        public: true

```
Output of `bin/console debug:container` 
![screenshot from 2017-11-28 16-42-13](https://user-images.githubusercontent.com/5645798/33329021-da338238-d45b-11e7-9a7c-79904589c51b.png)

If I remove the trailing slash at `App\Services\Test\`, then `</fg=cyan>`  disappears.
I could reproduce it on PHPStorms terminal and on Ubuntu 16.04 terminal. It seems to be not a terminal issue. 

Steps to Reproduce:

1. Checkout newest Symfony 4 RC2 Version
`composer create-project symfony/skeleton -s beta`
2. Create a new Service 
3. Add the service entry in `config/service.yaml` with a trailing slash at the service ID Key
4. Execute `bin/console debug:container`
