### ISSUE TITLE
Psr6CacheClearer try clean null pool and get error

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#25326]
Q | A
-- | --
Bug report? | yes
Feature request? | no
BC Break report? | yes
RFC? | no
Symfony version | 3.4.0

After update from version 3.3 to 3.4 _cache:clear_ command starts throwing an error 
`Call to a member function clear() on null`  in file
_Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer:54_.
I don't know why, not investigate this moment yet, but _pools_ passed to the constructor contains null values:

```
array:7 [
  "cache.app" => null
  "cache.system" => null
  "cache.validator" => null
  "cache.serializer" => null
  "cache.annotations" => null
  "cache.app.configuration" => null
  "cache.app.menu" => null
]
```

Maybe I forgot to migrate something to the new version? 

--- 
Also, I need to mention my config, as you can see I got some pools configured.

```
framework:
    cache:
        prefix_seed: only
        app: cache.adapter.redis
        system: cache.adapter.apcu
        pools:
            cache.app.configuration:
                adapter: cache.app
                name: cache.app.configuration
                default_lifetime: 3600 #60*60 = 1 hour
            cache.app.menu:
                name: cache.app.menu
                adapter: cache.app
                default_lifetime: 3600
```
