### ISSUE TITLE
YAML parser: No Escaping of single quotes before newline?

### ISSUE THREAD

**Issue by dbankmann** [symfony/symfony#25379]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  |  dcf3a9dfac146a0e10757a91de0b541fcd79de4f

Hi, with the following yaml file
```
key:
    fields:
        title: 'bla. Users''
            Guide'
```
I get the  Malformed inline YAML string exception. The file should be valid yaml though.
