### ISSUE TITLE
[DependencyInjection] Couldn't inject autowired service into ServiceLocator

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#25468]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.1

We have created `App\Report\BasicGenerator` class and trying to register it inside service locator:
```yaml
    app.report_generator_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']
        arguments:
            -
                App\Report\BasicGenerator: '@App\Report\BasicGenerator'
```

But this produces an exception: `The "App\Report\BasicGenerator" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.`. Is this behavior expected @nicolas-grekas ? As workaround we register this service explictly and marked them public:

```yaml
    App\Report\BasicGenerator:
        public: true
```
