### ISSUE TITLE
Logout removes all session active providers 

### ISSUE THREAD

**Issue by unckleg** [symfony/symfony#25527]
**Security.yml** configuration is below
```yaml
security:
    encoders:
        entity_admin:
            class: AdminBundle\Model\Entity\AdminUser
            algorithm: bcrypt
            iterations: 5000
            encode_as_base64: false
        entity_user:
            class:  AdminBundle\Model\Entity\User
            algorithm: bcrypt
            iterations: 5000
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        entity_admin:
            entity:
                class: AdminBundle\Model\Entity\AdminUser
                property: email
        entity_user:
            entity:
                class: AdminBundle\Model\Entity\User
                property: email

    firewalls:
        admin_secured_area:
            anonymous: ~
            pattern: /admin/.*
            provider: entity_admin
            guard:
                authenticators:
                    - app.admin_authenticator
            logout:
                path: admin_logout
                target: admin_login
        user_secured_area:
            anonymous: ~
            pattern: ^/((?!admin).)*$
            provider: entity_user
            guard:
                authenticators:
                    - app.front_authenticator
            logout:
                path: front_logout
                target: front_login
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:

        # FRONT
        - { path: ^/user/login,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*,              role: [ROLE_USER]                  }

        # ADMIN
        - { path: ^/admin/login,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*,             role: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
```

Login for Admin and Front providers works correctly, but if I'am logged in on both providers and logout let's say from admin provider I got logged out also from Front provider, If I logout from Front provider I got logged out from Admin provider also.

I think the problem is with the provider **regex** patter, but I'm not sure.

**Comment by unckleg** [comment]
**invalidate_session** did the trick.

By default, when users log out from any firewall, their sessions are invalidated. This means that logging out from one firewall automatically logs them out from all the other firewalls.

The invalidate_session option allows to redefine this behavior. Set this option to false in every firewall and the user will only be logged out from the current firewall and not the other ones.
http://symfony.com/doc/3.3/reference/configuration/security.html

Code:
```yaml
user_secured_area:
            ...
    logout: 
         path: front_logout
         target: front_login
         invalidate_session: false
```
