### ISSUE TITLE
SF4 doctrine.orm.namig_strategy is always underscore in prod environment

### ISSUE THREAD

**Issue by netbull** [symfony/symfony#25563]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

*naming_strategy* is always *underscore* in production if *doctrine.orm.metadata_cache_driver* is set.

Currently I changed packages/doctrine.yaml to:
```yaml
doctrine:
    ...
    orm:
        ...
        naming_strategy: doctrine.orm.naming_strategy.default
```

and it works as expected under dev environment, but on prod it's always *doctrine.orm.naming_strategy.underscore*
