### ISSUE TITLE
[DependencyInjection] Services decoration doesn't work for FQCN as decoration service id

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#25598]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.2

I've tryed to decorate some service:
```yaml
    'App\Api\AllowEmptyItemIriConverter':
        decorates: 'api_platform.iri_converter'
        arguments: ['@App\Api\AllowEmptyItemIriConverter.inner']

```
but this doesn't work. My newly created service is just removed as non used private service. I've tryed old way and it works as expected:

```yaml
    'app.api.allow_empty_item_iri_converter':
        class: App\Api\AllowEmptyItemIriConverter
        decorates: 'api_platform.iri_converter'
        arguments: ['@app.api.allow_empty_item_iri_converter.inner']
```

Is it ok?
