### ISSUE TITLE
Attribute "autowire" on service "SERVICE_NAME" cannot be inherited from "_defaults" when a "parent" is set. Move your child definitions to a separate file

### ISSUE THREAD

**Issue by kironet** [symfony/symfony#25621]
Hi,

I'm not sure if this is a bug or I'm just dumb, but how and where could I define new services2.yml file in symfony 3.4? Because I'm trying to create service that has a parent but getting this error:

> Attribute "autowire" on service "SERVICE_NAME" cannot be inherited from "_defaults" when a "parent" is set. Move your child definitions to a separate file or define this attribute explicitly in /config/services.yaml (which is loaded in resource "/config/services.yaml").

My service:

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        
    App\Form\Checkout\CheckoutFlow:
        parent: craue.form.flow
        public: true



```

**Comment by xabbuh** [comment]
You need to be a bit more explicit here like this:

```yaml
services:
    # ...

    App\Form\Checkout\CheckoutFlow:
        parent: craue.form.flow
        public: true
        autowire: true
        autoconfigure: false
```

I am closing here as there is no bug.
