### ISSUE TITLE
[DI] Service autodiscovery + autowire conflicting with non-fqcn services declaration

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#25740]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.3

I have the psr-4 discovery feature activated with the following services.yaml :

```yaml
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Event,**/*Event.php}'

    app.decorated:
        decorates: 'some.decorated'
        class: 'App\Foo\EventDecorator'

        arguments:
            $decorated: '@app.decorated.inner'
```

But then, it tries to register the `App\Foo\EventDecorator` service and doesn't know what to do with the `$decorated` argument, as it's an interface. My goal here is to have as many `app.decorated` services, each of them declared on the `App\Foo\EventDecorator` class.

Shouldn't the autodiscovery ignore the fqcn name found and not register it as a service if there is at least one service based on the class ?

It works if I add an alias `App\Foo\EventDecorator`. but then if I have another service decorating something and using that class, that would be incorrect... even if the fqcn service is never used and will be removed because of private optimizations.
