### ISSUE TITLE
[Question] !tagged service circular reference

### ISSUE THREAD

**Issue by grachevko** [symfony/symfony#25840]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.3

```php
class SomeInterface 
{
    public function supports(object $obj);
}

class ChainSome implements SomeInterface 
{
    /*
    * @var SomeInterface[]
    */
    private $somes;

    public function __construct(iterable $somes) 
    {
        $this->somes = $somes;
    }

    public function supports(object $obj)
    {
        foreach ($this->somes as $some) {
            if ($some->supports($obj)) {
                return true;
            }
        }        
    }
}
```

```yaml
services:
    _instanceof:
        SomeInterface:
            tags:
                - { name: 'app.some' }

    ChainSome:
        arguments:
            $somes: !tagged app.some
```

In this example `ChainSome` receive instance of self and code reach infinity loop. 
Is this behavior is valid? 
Maybe possible exclude self injection?
