### ISSUE TITLE
Problem processing a configuration from multiple files

### ISSUE THREAD

**Issue by damijank** [symfony/symfony#25889]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.13

There is a problem **processing** (_not_ loading) a configuration with the same root across **multiple** YAML files. Some array indices turn numeric opposed to as defined in the YAML file.

Configuration definition:
```PHP
$treeBuilder = new TreeBuilder();
$rootNode = $treeBuilder->root('work');
$rootNode
    ->children()
        ->arrayNode('entities')
            ->arrayPrototype()
                ->children()
                    ->arrayNode('tasks')
                        ->arrayPrototype()
                            ->children()
                                ->enumNode('type')->values(['auto', 'manual'])
                                    ->isRequired()->cannotBeEmpty()
                                    ->defaultValue('auto')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ->end()
    ->end();
```

If I define for example all configurations in one YAML file, all goes fine:

```YAML
work:
    entities:
        video:
            tasks:
                preview:
                    type: manual
                process:
                    type: auto
        image:
            tasks:
                import:
                    type: auto
                upload:
                    type: manual
        article:
            tasks:
                edit:
                    type: manual
                publish:
                    type: manual
```
But, if I break down configurations across multiple files, only the configuration from the first file is processed correctly. Again, the *read* is okay, the `$configs` param passed to `WorkExtension#load` has everything loaded correctly. Only after **processing**, the "unified" config is faulty like this:

Two YAML config files:

```YAML
# loaded as first file
work:
    entities:
        video:
            tasks:
                preview:
                    type: manual
                process:
                    type: auto
```
```YAML
# loaded second
work:
    entities:
        image:
            tasks:
                import:
                    type: auto
                upload:
                    type: manual
        article:
            tasks:
                edit:
                    type: manual
                publish:
                    type: manual
```

... the input `$configs` is fine:
```

Array (
    [0] => Array (
        [entities] => Array (
            [video] => Array (
                [tasks] => Array (
                    [preview] => Array (
                        [type] => manual )
                    [process] => Array (
                        [type] => auto ) ) )
        )
    )
    [1] => Array (
        [entities] => Array (
            [image] => Array (
                [tasks] => Array (
                    [import] => Array (
                        [type] => auto )
                    [upload] => Array (
                        [type] => manual ) ) )
            [article] => Array (
                [tasks] => Array (
                    [edit] => Array (
                        [type] => manual )
                    [publish] => Array (
                        [type] => manual ) ) )
        )
    )
)
```

but the resulting `$config` looks like this:

```
Array (
    [entities] => Array (
        [video] => Array (
            [tasks] => Array (
                [preview] => Array (
                    [type] => manual )
                [process] => Array (
                    [type] => auto ) ) )
        [0] => Array (
            [tasks] => Array (
                [import] => Array (
                    [type] => auto )
                [upload] => Array (
                    [type] => manual ) ) )
        [1] => Array (
            [tasks] => Array (
                [edit] => Array (
                    [type] => manual )
                [publish] => Array (
                    [type] => manual ) ) )
    )
)
```

If I reverse the load order (by renaming the files accordingly) then the `image` and `article` indices would be fine in the resulting configuration, but the `video` would have turned into index `0`.

I pretty sure I'm not doing anything wrong here.
