### ISSUE TITLE
in_memory UserProvider causes exception in test-environment 

### ISSUE THREAD

**Issue by floriansemm** [symfony/symfony#25895]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

I am currently migrate a SF3.4 application to SF4.0. The only part which is still broken are our tests. When I run phpunit then I get this error:

`Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Not configuring explicitly the provider for the "remember_me" listener on "main" firewall is ambiguous as there is more than one registered provider.`

Can not find anything a `provider` config-option for the remember_me section in the last docs.

The affected test is a controller-test. This is our `config/packages/test/security.yaml`

```yaml
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    test-user:
                        password: '8*zYKR)tBYyaN}qd'
                        roles: 'ROLE_USER'

    firewalls:
        main:
            http_basic:
                provider: in_memory
```

**Comment by stof** [comment]
Well, your main security.yml might still be imported, which would be the place where you would have the remember_me configuration and the other user providers.

One option would be to keep the same name for your user provider (overriding it) instead of naming it `in_memory`. Another option is to put the explicit configuration.

**Comment by floriansemm** [comment]
If I add `remember_me: false` under firewall.main then everything works fine.

**Comment by chalasr** [comment]
Either redefine the original user provider (the one you have in dev/prod) rather than defining a new `in_memory` one (just make the original one a memory provider as suggested by @stof above, that will remove the ambiguity) or set the `provider` key at the firewall level in your test config:

```yaml
firewalls:
    main:
        provider: in_memory
        # ...
```
