### ISSUE TITLE
orm doctrine driver

### ISSUE THREAD

**Issue by ouerghi** [symfony/symfony#25944]
after config of .en with DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name
(i changed the db_user with the user root and the password also the db_name
php.ini the pdo is enabled 
I run the command php bin/console doctrine:database:create i have this error

```
In PDOConnection.php line 43:
PS C:sf4\v4> php bin/console doctrine:database:create
In AbstractMySQLDriver.php line 121:
An exception occurred in driver: could not find driver
In PDOConnection.php line 47:
could not find driver
In PDOConnection.php line 43:
could not find driver
```
my doctrine.yaml
```yaml
doctrine:
dbal:
# configure these for your database server
driver: 'pdo_mysql'
server_version: '5.7'
charset: utf8mb4

    # With Symfony 3.3, remove the `resolve:` prefix
    url: '%env(resolve:DATABASE_URL)%'
orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
        App:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
```
