### ISSUE TITLE
Symfony won't fallback to next authentication method

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#25951]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Hi,

I am not even sure if this is bug or me at all.

I have two firewalls (`basic` and `api`) to authenticate users for same pattern (`^/`). If the `basic` auth fails, it should fallback to `api` auth. However, if `basic` fails, I get `401 Unauthorized` so it doesn't fallback to `api`. If I swop `basic` and `api` blocks in "security.yml", problem continues so this time `api` doesn't fallback to `basic` (in this case commenting out `throw new BadCredentialsException();` and adding `return null;` will return `AuthenticationCredentialsNotFoundException` error).

What am I missing here?

Thanks

```
security:

    encoders:
        SportsBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_BASIC_USER: ROLE_USER
        ROLE_API_USER: ROLE_USER

    providers:
        basic_provider:
            entity:
                class: SportsBundle:User
                property: username
        api_provider:
            id: sports.security.api_provider

    firewalls:
        basic:
            pattern: ^/
            stateless: true
            http_basic:
                realm: "Basic Security"
            provider: basic_provider
        api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: sports.security.api_authenticator
            provider: api_provider
```

```
namespace SportsBundle\Security;

use SportsBundle\Entity\ApiUser;
use InvalidArgumentException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\PreAuthenticatedToken;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;
use Symfony\Component\Security\Core\Exception\CustomUserMessageAuthenticationException;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationFailureHandlerInterface;
use Symfony\Component\Security\Http\Authentication\SimplePreAuthenticatorInterface;

class ApiKeyAuthenticator implements SimplePreAuthenticatorInterface, AuthenticationFailureHandlerInterface
{
    public function createToken(Request $request, $providerKey)
    {
        $apiKey = $request->headers->get('x-auth-token');
        if (!$apiKey) {
            throw new BadCredentialsException();
        }

        return new PreAuthenticatedToken('anon.', $apiKey, $providerKey);
    }

    public function supportsToken(TokenInterface $token, $providerKey)
    {
        return $token instanceof PreAuthenticatedToken && $token->getProviderKey() === $providerKey;
    }

    public function authenticateToken(TokenInterface $token, UserProviderInterface $userProvider, $providerKey)
    {
        if (!$userProvider instanceof ApiKeyUserProvider) {
            throw new InvalidArgumentException(
                sprintf(
                    'The user provider must be an instance of ApiKeyUserProvider. The "%s" was given.',
                    get_class($userProvider)
                )
            );
        }

        $user = $userProvider->loadUserByUsername($token->getCredentials());
        if (!$user instanceof ApiUser) {
            throw new CustomUserMessageAuthenticationException('Invalid API key.');
        }

        return new PreAuthenticatedToken($user, $user->getApiKey(), $providerKey, $user->getRoles());
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        return new Response($exception->getMessageKey(), Response::HTTP_UNAUTHORIZED);
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return null;
    }
}
```
