### ISSUE TITLE
[RFC] Bring the gap between service locators and !tagged arguments

### ISSUE THREAD

**Issue by sroze** [symfony/symfony#25968]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

More or less recently, [service locators](https://symfony.com/blog/new-in-symfony-3-3-service-locators) and [`!tagged` arguments](https://symfony.com/blog/new-in-symfony-3-4-simpler-injection-of-tagged-services) have landed in Symfony to 1) improve the performance of applications and 2) ease the development experience (i.e. remove the need of a compiler pass).

These two features seem to be ideal for creating "registry" type of services. Unfortunately, we can't yet use them together:
```yaml
services:
    app.message_receivers:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']
        arguments: [!tagged message_receivers]
```

This would be fantastic to manage to have such example working. WDYT?

To have this working, I believe that "all we need" is the [`findAndSortTaggedServices` method](https://github.com/symfony/symfony/blob/d024d795593bfa0773e312c5d5aa1cec4159d3d9/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php#L39) to return the services indexed by their name, instead of numeric keys. 

I don't think changing this would be considered as a BC break.
