### ISSUE TITLE
SF4, Cannot write logs to a specific file

### ISSUE THREAD

**Issue by blackbart420** [symfony/symfony#25973]
Symfony version  | 4.0.4

Hi,

can someone help me with this please ?
I guess it is not a bug and it is a common configuration.

I just need to write logs in a file named music.log.
I use Symfony 4

I tried to follow the documentation without success:
https://symfony.com/doc/master/logging/channels_handlers.html#monolog-channels-config

So here is what I did:

```
// config/packages/monolog.yaml
monolog:
    channels: [music]
    handlers:
        music:
            type: stream
            path: "%kernel.logs_dir%/music.log"
            level: debug
            channels: [music]
```
In my controller I try to write a log like this:

`$container->get('monolog.logger.music')->log("test");`

But I get this error:

The "monolog.logger.music" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

So I am confused...
