### ISSUE TITLE
Upgrading 3.3 to 3.4 and 4.0: overwriting core services with parent logic

### ISSUE THREAD

**Issue by ReSpawN** [symfony/symfony#26064]
| Q                | A
| ---------------- | -----
| Bug report?      | 
| Feature request? | 
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | 3.4.4

We're upgrading a big application built on Symfony 2.8 through to 3.3.x to 3.4 with autowiring logic, following some tutorials from KNP (by @weaverryan) and we're running into a problem with a overwriting parent service. 

We're overwriting `Symfony\Component\Security\Http\Firewall\SwitchUserListener` with our own `AppBundle\EventListener\SwitchUserListener`, which looked like this:

```
    security.authentication.switchuser_listener:
        class: AppBundle\EventListener\SwitchUserListener
        arguments:
            - "@security.token_storage"
            - "@app.webservice_user_provider"
            - "@security.user_checker"
            - 'main'
            - "@security.access.decision_manager"
            - "@?monolog.logger.security"
            - '_impersonate'
            - 'ROLE_ALLOWED_TO_SWITCH'
            - "@?debug.event_dispatcher"
            - ['email1@domain.tld', 'email2@domain.tld']
        tags:
            - { name: monolog.logger, channel: security }
```

Naturally, we've upgraded the logic to suit the new format, but using `autoconfigure` with `parent` is not allowed in 3.4. Thus we've configured it like this:

```
    Symfony\Component\Security\Http\Firewall\SwitchUserListener:
        class: AppBundle\EventListener\SwitchUserListener
        parent: Symfony\Component\Security\Http\Firewall\SwitchUserListener
        arguments:
            $restricted: ['email1@domain.tld', 'email2@domain.tld']
```

Even with the entire argument stack from the first block we're getting memory exhaustion after a couple of seconds, implicating some sort of loop. We've tried `alias`in the entire thing to no avail and currently we're at a loss as to how to get it working. Have we stumbled upon some sort of bug?
