### ISSUE TITLE
Missing argument / circular logic when defining custom session handler proxy

### ISSUE THREAD

**Issue by dariodevito** [symfony/symfony#26153]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.1

I have been trying to register a custom session handler proxy in order to encrypt / decrypt session data. Seems fairly straight forward and I've been using the example provided here https://symfony.com/doc/2.8/session/proxy_examples.html

However if I define the service as per the example, I get a fatal error as the class construct is expecting an instance of the session handler as an argument:

```
Type error: Too few arguments to function CoreBundle\Session\EncryptedSessionHandlerProxy::__construct(), 0 passed in
```

This implies that I need to pass the session handler to the service as an argument however, if I do this then I receive the following error:

```
Circular reference detected for service "app.session_handler", path: "app.session_handler -> session -> session.storage.native -> app.session_handler".
```

My yaml config looks as follows:

```
//  app/config/services.yml
services:
    app.session_handler:
        class: CoreBundle\Session\EncryptedSessionHandlerProxy
        arguments:
            - "@session"
```
OR
```
//  app/config/services.yml
services:
    app.session_handler:
        class: CoreBundle\Session\EncryptedSessionHandlerProxy
        arguments:
            - "@app.session_handler"
```

```
//  app/config/config.yml
session:
    handler_id: app.session_handler
```

Class is defined as follows:

```
namespace CoreBundle\Session;

use Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy;

/**
 * Proxy to encrypt / decrypt session data
 */
class EncryptedSessionHandlerProxy extends SessionHandlerProxy
{
    private $key;

    /**
     * Construct
     *
     * @param SessionHandlerInterface $handler
     */
    public function __construct(SessionHandlerInterface $handler)
    {...
```

The errors seem logical however I am unsure how to pass the session handler in via the service config? The implementation is the docs example doesn't appear correct and I've looked through the codebase to identify a similar implementation but can't find anything.

Any advise on the correct implementation / confirmation if this is a bug would be of much help. 

Thanks

**Comment by dariodevito** [comment]
Class is defined as follows:

`
<?php

namespace CoreBundle\Session;

use Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy;

/**
 * Proxy to encrypt / decrypt session data
 */
class EncryptedSessionHandlerProxy extends SessionHandlerProxy
{
    private $key;

    /**
     * Construct
     *
     * @param SessionHandlerInterface $handler
     */
    public function __construct(SessionHandlerInterface $handler)
    {...
`

The errors seem logical however I am unsure how to pass the session handler in via the service config? The implementation is the docs example doesn't appear correct and I've looked through the codebase to identify a similar implementation but can't find anything.

Any advise on the correct implementation / confirmation if this is a bug would be of much help. 

Thanks

**Comment by stof** [comment]
if you want to decorate the code session handler, you should use the service decoration feature instead of overriding the `app.session_handler` entirely (which makes the original session handler definition disappear and you are indeed referencing yourselves). See http://symfony.com/doc/current/service_container/service_decoration.html for the documentation

**Comment by stof** [comment]
And the original session handler service is not the `session` service btw.

**Comment by dariodevito** [comment]
Thanks for the help :)

I have tried defining the service using service decoration as follows:

```
    app.encrypt_session_handler:
        class: CoreBundle\Session\EncryptedSessionHandlerProxy
        decorates: "session.handler"
        arguments:
            - "@app.encrypt_session_handler.inner"
```

However I still get the circular logic error:

`Circular reference detected for service "app.encrypt_session_handler", path: "app.encrypt_session_handler -> app.encrypt_session_handler"`.

**Comment by stof** [comment]
but then, don't configure `app.encrypt_session_handler` as the session handler in your  config file (so that FrameworkBundle still configures the original service that you want to decorate). Otherwise, you will still decorates yourselves

**Comment by dariodevito** [comment]
That makes sense, thanks for the advice

**Comment by dariodevito** [comment]
Sorry to be a pain...

I have tried the decorates implementation and removed the config as you have suggested however I am still unsure how to pass the session handler through.

```
    app.encrypt_session_handler:
        class: CoreBundle\Session\EncryptedSessionHandlerProxy
        decorates: "session"
        arguments:
            - "@app.encrypt_session_handler.inner"
```

This returns an error indicating that session is not an instance of session handler interface, which is to be expected however I cannot find a service for the session handler interface.

I can't see a session_handler when using `php app/console debug:container`

**Comment by dmaicher** [comment]
@dariodevito Normally the alias is `session.handler`

So this here should work **without the** `handler_id: app.session_handler` config:

```yml
app.encrypt_session_handler:
    class: CoreBundle\Session\EncryptedSessionHandlerProxy
    decorates: "session.handler"
    arguments:
        - "@app.encrypt_session_handler.inner"
```

**Comment by dariodevito** [comment]
Thats what I thought however, I receive `You have requested a non-existent service "session.handler".` if I set the config as follows:

```
    session:
        handler_id: ~
```

If I remove the `handler_id` config entirely, I receive `CoreBundle\Session\EncryptedSessionHandlerProxy::__construct() must be an instance of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerInterface, instance of Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler given, called in /var/www/app/cache/dev/appDevDebugProjectContainer.php on line 377`

**Comment by dmaicher** [comment]
This seems correct to me:

> CoreBundle\Session\EncryptedSessionHandlerProxy::__construct() must be an instance of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerInterface, instance of Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler given, called in /var/www/app/cache/dev/appDevDebugProjectContainer.php on line 377

`Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerInterface` does not seem to exist?

It should be `Symfony\Component\HttpFoundation\Session\Storage\SessionStorageInterface`?

**Comment by dariodevito** [comment]
Unfortunately it even correcting the namespace does not resolve the issue, however I have managed to resolve.

As I am storing my sessions in Redis using the my default php.ini config ( ~ session_handler), the session.handler alias does not appear to be made available.

To resolve the issue I had to register an alias for the Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler class and inject this into my service. The following config gets this working:

```
// app/config/services.yml
     native_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler

    app.session_handler:
        class: CoreBundle\Session\EncryptedSessionHandlerProxy
        arguments:
            - "@native_handler"
```

```
//app/config/config.yml
    session:
        handler_id: app.session_handler
```

**Comment by dariodevito** [comment]
Data is now going through my class before being put into the session, and the session is going into Redis as expected.

**Comment by kick-the-bucket** [comment]
A more elegant way to allow for autowiring:
```yaml
# app/config/services.yml
services:
    SessionHandlerInterface:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler
```

**Comment by vilius-g** [comment]
If you want to use native sessions with `SessionHandlerProxy` and for `framework.session.save_path` to work correctly, you need to alias `SessionHandlerInterface` to `session.handler.native_file` otherwise `save_path` will not be set.

```
# config/services.yaml
services:
    SessionHandlerInterface:
        alias: 'session.handler.native_file'
```
