### ISSUE TITLE
ServiceLocators' tags are not autoconfigured

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#26187]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

Hi,

in a service definition with:

```yaml
services:
    _defaults:
        autoconfigure: true

    locator.abc:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator'] # <- add this automatically
        arguments:
            -   ...
```

I would have assumed, that the (required) tag `container.service_locator` is autoconfigured as the class is a `ServiceLocator` and probably needs the tag. Is there a specific reason, why this isn't configured automatically?
