### ISSUE TITLE
BC SwitchUserListener Symfony 3.3 to 3.4

### ISSUE THREAD

**Issue by g-trinh** [symfony/symfony#26197]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4

[Stackoverflow thread](https://stackoverflow.com/questions/48810512/bc-break-symfony-3-3-to-3-4)

Hello,

I recently tried to upgrade my Symfony application from version 3.3.x to 3.4.x. Everything was ok until it came to container compiling. The problem is that i have a completely custom SwitchUserListener (constructor included), but changes made [here](https://github.com/symfony/security-http/commit/f1720c6dd0844450cd134e2a5fc8319f492d56f1#diff-3eea7218d9978bdd41e254e67047ca92R54) and [here](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L723) throw the following error :

```
[Symfony\Component\DependencyInjection\Exception\OutOfBoundsException] 
Service "security.authentication.switchuser_listener.main": The index "9" is not in the range [0, 8]. 

```
In fact I had to override everything in the custom listener as almost everything in the Symfony SwitchUserListener are marked as private. In Symfony 3.3, the latter used only 9 parameters in its constructor, but it now uses 10.
Plus, there is no way to re-use the Symfony base Listener, nor to override it without breaking BC.

Tried solutions :

- Extending the base SwitchUserListener
- Decorating base SwitchUserListener with custom SwitchUserListener

For the moment, I added the $stateless parameter to my custom SwitchUserListener, and changed the declaration of my service.

**Comment by xabbuh** [comment]
How exactly did you replace the core listener?

**Comment by g-trinh** [comment]
I just created a new one, with my own custom logic and declared it as a service with the security.authentication.switchuser_listener ID.

My constructor and attributes :

```
class SwitchUserListener implements ListenerInterface
{
    private $tokenStorage;
    private $provider;
    private $userChecker;
    private $providerKey;
    private $accessDecisionManager;
    private $usernameParameter;
    private $role;
    private $apiScheme;

    /**
     * @var ClientManager
     */
    private $clientManager;

    /**
     * @var ResourceMapper
     */
    private $resourceMapper;

    public function __construct(TokenStorageInterface $tokenStorage,
                                UserProviderInterface $provider,
                                UserCheckerInterface $userChecker,
                                $providerKey, AccessDecisionManagerInterface
                                $accessDecisionManager,
                                LoggerInterface $logger = null, 
                                $usernameParameter = '_switch_user', 
                                $role = 'ROLE_ALLOWED_TO_SWITCH', 
                                EventDispatcherInterface $dispatcher = null)
    {
        if (empty($providerKey)) {
            throw new \InvalidArgumentException('$providerKey must not be empty.');
        }

        $this->tokenStorage = $tokenStorage;
        $this->provider = $provider;
        $this->userChecker = $userChecker;
        $this->providerKey = $providerKey;
        $this->accessDecisionManager = $accessDecisionManager;
        $this->usernameParameter = $usernameParameter;
        $this->role = $role;
        $this->logger = $logger;
        $this->dispatcher = $dispatcher;
    }

    public function setClientManager(ClientManager $clientManager)
    {
        $this->clientManager = $clientManager;
    }

    public function setResourceMapper(ResourceMapper $resourceMapper)
    {
        $this->resourceMapper = $resourceMapper;
    }
}
```

I added some setters so I was sure the constructor was left untouched (for BC). And declared my service :

```
security.authentication.switchuser_listener:
        class: AppBundle\Listener\Http\SwitchUserListener
        arguments:
            - '@security.token_storage'
            - ~
            - ~
            - ~
            - '@security.access.decision_manager'
            - '@logger'
            - ''
            - '%api_scheme%'
            - '@event_dispatcher'
        calls:
            - ['setClientManager', ['@surf_utils.http.manager.client']]
            - ['setResourceMapper', ['@surf_utils.helper.resource_mapper']]
        tags:
            - { name: monolog.logger, channel: security }
```
