### ISSUE TITLE
Importing configuration from other yaml file to config/services.yaml doesn't work

### ISSUE THREAD

**Issue by ttskch** [symfony/symfony#26200]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

Importing configuration from other yaml file to `config/services.yaml` doesn't work well. I made simple reproducer codebase [here](https://github.com/ttskch/symfony4-config-import-malfunction-reproducer). Maybe seeing [commit logs](https://github.com/ttskch/symfony4-config-import-malfunction-reproducer/commits/master) helps you to understand about my reporting. Thanks.

**Comment by Simperfit** [comment]
If you want this to work IMHO, is to remove the `_defaults` from the services.yaml and add it in the sample.yaml.

This is what i'm doing.

I can't tell if it's really a bug or a missusage.

Status: Needs Review

**Comment by xabbuh** [comment]
This is expected. Imports are parsed first. Thus, your services configured in the main `services.yaml` file override the ones from imported files.

**Comment by ttskch** [comment]
@xabbuh Now I understand that [`App\:` definition](https://github.com/ttskch/symfony4-config-import-malfunction-reproducer/blob/master/config/services.yaml#L19-L21) in `services/yaml` overwrites [`App\Service:` definition](https://github.com/ttskch/symfony4-config-import-malfunction-reproducer/blob/master/config/sample.yaml#L2-L4) in `sample.yaml` because `imports` are parsed first (even if put it the end of `services.yaml`). Thanks a lot!

**Comment by ttskch** [comment]
And now, following works well 👍

```diff
# config/services.yaml

    App\:
        resource: '../src/*'
-       exclude: '../src/{Entity,Migrations,Tests}'
+       exclude: '../src/{Entity,Migrations,Tests,Service.php}'
```

**Comment by sitetester** [comment]
I noticed some weird some Symfony behaviour during import. When services are defined in config/services.yaml file, they are loading properly, but when I configure them in config/services/services.yaml, they start give error like 

Cannot autowire service "App\Command\***\XyzCommand": argument "$env" of method "__construct()" is type-hinted "string", you should configure its   
  value explicitly.

**Comment by xabbuh** [comment]
You need to remove the pre-defined definitions from the `config/services.yaml` file if you put your custom config in a different file. Otherwise they will overwrite your config.

**Comment by AcerxX** [comment]
I have the same problem as sitetester. I have a new services-xyz.yaml  file imported in services.yaml. Everything defined in services-xyz.yaml is not working. I get the same error:

In DefinitionErrorExceptionPass.php line 54:                                                                                                                                                                             
  Cannot autowire service "App\Service\SomeService": argument "$someString" of method "__construct()" is type-hinted "string", you should configure its value explicitly.

**Comment by xabbuh** [comment]
https://github.com/symfony/symfony/issues/26200#issuecomment-475386643 applies as well. If you still think there is a bug, we need a concrete example that allows to reproduce.

**Comment by 24HOURSMEDIA** [comment]
Just put your .yaml file in the dir config/services,
and add to src/Kernel.php, at the end of the configureContainer method:

`$loader->load($confDir.'/services/*'.self::CONFIG_EXTS, 'glob');`

**Comment by ssaki** [comment]
This feels a bit counter-intuitive behavior to me as we are used to expect more specific definitions to override more generic ones. While the roots of the issue are quite clear once you spent some time to grasp it then the vague suggestion in documentation and few issues on github (this included) suggest more explicit filtering in the global auto-wiring definition in `services.yaml` and this looks a bit tedious and error prone process.

Is it possible to call it a documentation bug instead and opt in for documenting the following (or similar) approach (or rather a suggestion) in the dedicated doc page (How to Import Configuration Files/Resources):

Once you decide to split into multiple service definition files one just needs to extract the golbal auto-wiring definition as well and just beware to import it first. E.g.

```yaml
# config/services/default_autowire.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/*'
        exclude: '../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']
```

and then 
```yaml

# config/service.yaml

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
    - { resource: services/default_autowire.yaml }
    - { resource: services/something.yaml }
    - { resource: services/other_thing.yaml }

parameters:
    # anything you decided not to split and with highest precedence

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # anything else you decided not to split and with highest precedence
```

IMO even if only a soft suggestion it will immediately rise awareness of what is going on. Alternative example with filtering out services could also be provided for verbosity.

 I could try to provide a PR for the docs if it looks like something less confusing and "nice to have"?
CC @xabbuh
