### ISSUE TITLE
Unrecognized option "form_login" under "security.firewalls.main"

### ISSUE THREAD

**Issue by wiselh** [symfony/symfony#26216]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | ?
| Symfony version  | 3.4.4

Hey Guys, i need help i got this error even it was working before.
i can't access to any pages except if i `remove ` the `form_login` from `security.yml`

## Bug

>  (1/1) InvalidConfigurationException
> Unrecognized option "form_login" under "security.firewalls.main"

## Security.yml

```yaml
security:

    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                     login_path: login
                     check_path: login
```

## Controller

```php
class UserController extends Controller
{

    /**
     * @Route("/login" ,name="login")
     */

    public function indexAction()
    {
        return $this->render('@User\Login\login.html.twig');
    }
}
```
