### ISSUE TITLE
Importing yml config files from bundle and enabling autowiring

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#26224]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

Hi,

When I place `resource: '@AppBundle/Resources/config/'` into `app/config/services.yml` the autowiring won't work. However, if I place it into `app/config.yml` it works fine. When I use it this way, `_defaults` options is not inherited from `app/config/services.yml` within my customer configuration files in the AppBundle.

Is this is a bug or am I missing something?

Thanks

**app/config.yml**

```
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
```

**app/config/services.yml**

```
imports:
    - { resource: '@AppBundle/Resources/config/' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
```

**AppBundle/Resources/config/controllers.yml**

```
services:
    _defaults:
        autowire: true

    AppBundle\Controller\CacheController:
        arguments:
            $cacheTypes: '%cache_types%'
```

**Comment by nicolas-grekas** [comment]
`_default` is never inherited, it applies only to the current file

**Comment by BentCoder** [comment]
@nicolas-grekas That's fine! I can add `_default` to my custom yml files but I still get an error.

> Cannot autowire service "AppBundle\Controller\CacheController": argument "$cacheTypes" of method "__construct()" must have a type-hint or be given a value explicitly.

**app/config/parameters.yml**

```
parameters:
    cache_types:
        - file
        - memcached
        - redis
```
**app/config/config.yml**
```
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
```

**app/config/services.yml**
```
imports:
    - { resource: '@AppBundle/Resources/config/' } # I have many yml files under here

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
```

**AppBundle/Resources/config/controllers.yml**
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\Controller\CacheController:
        arguments:
            $cacheTypes: '%cache_types%'
```

**CacheController**

```
declare(strict_types=1);

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/caches")
 */
class CacheController
{
    private $cacheTypes;

    public function __construct(iterable $cacheTypes)
    {
        $this->cacheTypes = $cacheTypes;
    }

    /**
     * @Method({"GET"})
     * @Route("")
     */
    public function indexAction()
    {
        return new Response(json_encode($this->cacheTypes));
    }
}
```

**Comment by xabbuh** [comment]
The `AppBundle\Controller\CacheController` service is overridden by the implicitly registered definition coming from PSR-4 based loader in `services.yaml` (imports are processed first). You could exclude this particular file from the PSR-4 loader in `services.yaml`, but I suggest to not deal with services in other config files that are created by a PSR-4 loader in another file to not make it too hard to understand what is going on in your config. Closing here as there is no bug.

**Comment by BentCoder** [comment]
Sorry but you got me confused. Is there an example somewhere you can link me to?

**Comment by xabbuh** [comment]
The exclude could look like this:

```yaml
imports:
    - { resource: '@AppBundle/Resources/config/' } # I have many yml files under here

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Controller/CacheController.php}'

    # ...
```
