### ISSUE TITLE
Translator default path not overriden

### ISSUE THREAD

**Issue by sauls** [symfony/symfony#26272]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

I have this config:

```yaml
framework:
    translator:
        default_path: '%kernel.project_dir%/custom/path/translations'
```
`kernel.project_dir` point to `/my-project`

And I get this error message

```bash
$ In FrameworkExtension.php line 916:
                                                                                                                     
  /my-project/translations defined in translator.paths does not exist or is not a directory   
```
Still I couldn't find where the paths are set with the `/my-project/translations`. If I do  

```yaml
framework:
    translator:
        default_path: '%kernel.project_dir%/custom/path/translations'
        paths: ['%kernel.project_dir%/custom/path/translations']
```
I get that array `$config['paths']` in `/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php:912` looks like:

```php
[
    '/my-project/custom/path/translations',
    '/my-project/translations',
]
```
I don't have directory under `/my-project/translations`  as I suppose the `default_path` should override it..

I am a bit lost here now ... from where the `%kernel.project_dir%/translations` still persists here??

**Comment by xabbuh** [comment]
Can you create a small example project that allows to reproduce your issue?

**Comment by sauls** [comment]
@xabbuh you can do the following:

```bash
$ composer create-project symfony/website-skeleton myproject
```

then do

```bash
$ cd myproject
$ mkdir -vp custom/path/translations
$ rm -fr translations
```
and update `config/packages/framework.yml file`

```yaml
framework:
    translator:
        default_path: '%kernel.project_dir%/custom/path/translations'
```

and running the command
```bash
$ php bin/console 
```
should throw you 

```text
In FrameworkExtension.php line 916:                                                                              
/myproject/translations defined in translator.paths does not exist or is not a directory 
```
