### ISSUE TITLE
LDAP Form Authentication dn_string substitution broken?

### ISSUE THREAD

**Issue by ChrOst** [symfony/symfony#26316]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ???
| RFC?             | no
| Symfony version  | 3.4
Due to deprecation warnings I replaced stuff in security/firewalls, security/providers.
Actually the substitutuion of '{username}' in dn_string of the firewalls doesn't seem to have any effect anymore.

https://symfony.com/doc/3.4/security/ldap.html suggests the following:
```
# app/config/security.yml
security:
    # ...

    firewalls:
        main:
            # ...
            form_login_ldap:
                # ...
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'uid={username},dc=example,dc=com'
```
if I place 
```
dn_string: 'CN={username},OU=Users,DC=my,DC=domain,DC=de'
```
```{username}``` won't be replaced.

see the Exception:
```
LdapException
HTTP 500 Internal Server Error
Could not complete search with dn "CN={username},OU=Users,DC=my,DC=domain,DC=de", query "(&(memberof:1.2.840.113556.1.4.1941:=CN=MyGroup,OU=Groups,DC=my,DC=domain,DC=de))" and filters "*".
```

Looking at the code there is something different happening to ```dn_string``` then to ```query_string```.

https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginLdapFactory.php#L37

For now I'm fine with removing ```CN={username},``` from the config, but either it's a bug/issue or a wrong documentation.

**Comment by nicolas-grekas** [comment]
@csarrazi maybe you'd like to have a look here?

**Comment by csarrazi** [comment]
Hi @ChrOst. As a matter of fact, the query_string should only be used if you want to perform user search *prior to binding* to the provided password. In this case, the `dn_string` should *not* contain the placeholder.

This also means that only servers which provide anonymous search are supported for now if you want to use the search before bind strategy.

If you don't need to do a search query prior to binding (if you can already infer the DN from the username), then you should use `dn_string` without `query_string`.

@lsmith77, as you implemented that feature in #21402, could you confirm that this is the expected behaviour?

Thanks!

**Comment by csarrazi** [comment]
By the way, the documentation does not seem to be up to date, as the search before bind feature was never documented.

**Comment by ChrOst** [comment]
But even then it messes it up. The default, according to the documentation, of ```dn_string``` is ```{username}``` which will end in the same exception.

So I set the ```dn_string``` to ```OU=Users,DC=my,DC=domain,DC=de``` that it works properly.

See Code here: https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginLdapFactory.php#L53


If it's intended, a documentation fix and a condition on the default value of ```dn_string``` should do it (-> only set ```dn_string``` if ```query_string``` is NULL)

**Comment by csarrazi** [comment]
@lsmith77 Could you confirm how this feature is supposed to work?

Thanks!

**Comment by csarrazi** [comment]
@ChrOst I agree, this should be documented better. The current documentation is outdated, and predates this feature.

**Comment by lsmith77** [comment]
I extract an example from a production application.

```
services:

    app.ldap.client:
        class: Symfony\Component\Ldap\Ldap
        factory: ['Symfony\Component\Ldap\Ldap', create]
        arguments:
            - 'ext_ldap'
            - {host: "%ldap_host%", port: "%ldap_port%", encryption: "%ldap_encryption%"}

security:
    providers:
        ldap_provider:
            ldap:
                service: app.ldap.client
                base_dn: ''DC=acme'
                search_dn: 'cn=foobar,OU=Users,DC=acme'
                search_password: 'barfoo'

    firewalls:
        main:
            provider: 'ldap_provider'
            form_login_ldap:
                login_path: login
                check_path: login
                service: app.ldap.client
                dn_string: 'ou=Users,dc=acme'
                query_string: '(&(AccountName={username})(|(memberof=CN=foo,OU=Groups,DC=acme)(memberof=barOU=Groups,DC=acme))'
```

The key part is of course: `query_string: '(&(AccountName={username})(|(memberof=CN=foo,OU=Groups,DC=acme)(memberof=bar,OU=Groups,DC=acme))'`

Basically with this I can further filter in this case to ensure that the user is either a member of `foo` or `bar` groups. Hope this helps.
