### ISSUE TITLE
Authentication request could not be processed due to a system problem. Symfony EasyAdminBundle Focuserbundle

### ISSUE THREAD

**Issue by pedramham** [symfony/symfony#26385]
I am using Symfony 3.4 with FOSUserBundle~2.0 and EasyAdminBundle^1.17.everything works fine.i can login on localHost.but when I upload my application in server .when i want to login in system i have this error 
`Authentication request could not be processed due to a system problem.`
this is my security.yml
```yaml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
```
i have this error on dev.log

```
[2018-03-03 10:04:20] security.DEBUG: User was reloaded from a user provider. {"provider":"FOS\\UserBundle\\Security\\UserProvider","username":"rrrr"} []
[2018-03-03 10:04:21] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
```
