### ISSUE TITLE
Using :: to separate classes and methods in service factories

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26453]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

I was reviewing this article about service factories https://symfony.com/doc/current/service_container/factories.html and found this example:

```yaml
# config/services.yaml
App\Email\NewsletterManager:
    # new syntax
    factory: 'App\Email\NewsletterManagerFactory:createNewsletterManager'
```

We recently made some changes (https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-bundle-notation) to always allow using `::` to separate the class and the method name instead of using `:` sometimes and `::` others.

@Tobion can you remember if your recent PR also took care of this service factory case? If not, do you think you could work on this before the 4.1 feature freeze (which starts in 23 days)? Thanks!

**Comment by Tobion** [comment]
I didn't touch this. I'll look into it.

**Comment by derrabus** [comment]
So, your target syntax would be this?

```YAML
App\Email\NewsletterManager:
    # new syntax
    factory: 'App\Email\NewsletterManagerFactory::createNewsletterManager'
```

If you write it like this currently, Symfony would compile it as a static call to the method `createNewsletterManager` of class `App\Email\NewsletterManagerFactory`. If we allow service IDs in that syntax, we might create ambiguity.

**Comment by javiereguiluz** [comment]
@derrabus thanks! I see now that we can't make this change and we must keep this inconsistency. Because of this, the "old" syntax is better than the "new" one to me:

```yaml
# config/services.yaml
AppBundle\Email\NewsletterManager:
    # new syntax
    factory: 'App\Email\NewsletterManagerFactory:createNewsletterManager'
    # old syntax
    factory: ['@App\Email\NewsletterManagerFactory', createNewsletterManager]
```

**Comment by stof** [comment]
the issue is that `'App\Email\NewsletterManagerFactory::createNewsletterManager'` is also a valid syntax, but does a different thing: it uses a static method as factory (as this is the PHP notation for a static method callable).

**Comment by javiereguiluz** [comment]
Let's close this as "we can't fix this ugly inconsistency" 😢  Thanks all for the info and the discussion.

**Comment by Tobion** [comment]
There are two different approaches here. The controller syntax does not distinguish between services/classes and static7non-static methods. It just uses what works automatically. This makes sense to me as you don't need to change your routing just because you change the controller to a service.

The factory syntax does distinguish between those things. I think that is fine as factories rarely change in that regard. So there is no need to add the same fallback-logic there.
But IMO the inconsistency is in the YAML syntax for factories. The XML config explicitly distinguishes those like

````xml
<factory class="App\Email\NewsletterManagerStaticFactory" method="createNewsletterManager" />
<factory service="App\Email\NewsletterManagerFactory" method="createNewsletterManager" />
```

but in yaml it's not clear what means what. IMO it would be better to also use something like

```yml
factory: 
    service: App\Email\NewsletterManagerFactory
    method: createNewsletterManager
```

or the old syntax that also makes it explicit with the `@`

```yml
 factory: ['@App\Email\NewsletterManagerFactory', createNewsletterManager]
```

**Comment by javiereguiluz** [comment]
The `service`/`class` & `method` config was the original config before Symfony 2.7:

```yaml
services:
    newsletter_manager:
        class:          NewsletterManager
        factory_class:  NewsletterManagerFactory
        factory_method: createNewsletterManager
```

https://symfony.com/doc/2.3/components/dependency_injection/factories.html
