### ISSUE TITLE
Migration 3.4 (with bundles) to 4.0 : services autowire issue

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#26468]
I am trying to migrate a Symfony 3.4 application to Symfony 4.0.

The Symfony 3.4 application was made with bundles, so the src folder looks like:
```
-src/
-- CoreBundle/
-- Feature1Bundle/
-- Feature2Bundle/
...
```

In Symfony 4, I kept the same directory structure, and I modified the `services.yaml` to autowire services on all bundles:
``` yaml
App\CoreBundle\:
    resource: '../src/CoreBundle/*'
    exclude: '../src/CoreBundle/{Entity,Migrations,Tests,Kernel.php}'

App\CoreBundle\Controller\:
    resource: '../src/CoreBundle/Controller'
    tags: ['controller.service_arguments']

App\Feature1Bundle\:
    resource: '../src/Feature1Bundle/*'
    exclude: '../src/Feature1Bundle/{Entity,Migrations,Tests,Kernel.php}'

App\Feature1Bundle\Controller\:
    resource: '../src/Feature1Bundle/Controller'
    tags: ['controller.service_arguments']

App\Feature2Bundle\:
    resource: '../src/Feature2Bundle/*'
    exclude: '../src/Feature2Bundle/{Entity,Migrations,Tests,Kernel.php}'

App\Feature2Bundle\Controller\:
    resource: '../src/Feature2Bundle/Controller'
    tags: ['controller.service_arguments']
```

But I am encountering the issue maybe related to https://github.com/symfony/symfony/issues/23564:

> In FileLoader.php line 168:
> Expected to find class "App\CoreBundle\Controller\DefaultController" in file "Z:\...\src\CoreBundle/Controller\DefaultController.php" while importing services from resource "../src/CoreBundle/*", but it was not found! Check the namespace prefix used with the resource in Z:\...\config/services.yaml (which is loaded in resource "Z:\...\config/services.yaml").

Of course, the file exists with the correct namespace.

Maybe this is because bundles are extending classes from others bundles of the project?
