### ISSUE TITLE
[BUG] Unable to set/use asset manifest: Unrecognized option "json_manifest_strategy"

### ISSUE THREAD

**Issue by hal869** [symfony/symfony#26483]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6

I have a SF4 project

```
bin/console --version
	Symfony 4.0.6 (kernel: src, env: dev, debug: true)
```

I've genetated an asset manifest

```
./public/build/manifest.json
```

Per docs at

http://symfony.com/doc/master/reference/configuration/framework.html#reference-assets-json-manifest-path

I add
```
config/packages/framework.yaml
	framework:
	    assets:
	        json_manifest_strategy:
	            json_manifest_path: "%kernel.project_dir%/public/build/manifest.json"
```

on next exec
```
bin/console --version
	In ArrayNode.php line 319:

	  Unrecognized option "json_manifest_strategy" under "framework.assets"
```

**Comment by hal869** [comment]
cref:

**Comment by sstok** [comment]
The correct structure is (default):

```yaml
assets:
        enabled: true
        version_strategy: null
        version: null
        version_format: '%%s?%%s'
        json_manifest_path: null
        base_path: ''
        base_urls: {  }
        packages: {  }`
```

For your configuration it should be:

```yaml
framework:
    assets:
        # json_manifest_strategy: # This option doesn't exist and is nowhere mentioned in the documentation 
        # https://symfony.com/doc/current/reference/configuration/framework.html#json-manifest-path
        json_manifest_path: "%kernel.project_dir%/public/build/manifest.json"
```

https://symfony.com/doc/current/reference/configuration/framework.html#version-strategy is only required if you use a different strategy then json-manifest 

If you think the documentation could improved at this point please open an issue in https://github.com/symfony/symfony-docs/issues 👍
