### ISSUE TITLE
Env variable usage with suffix interpolation does not work

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#26510]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.6

With the following env var:

```
###> snc/redis-bundle ###
REDIS_URL=redis://redis
###< snc/redis-bundle ###
```

And the following configuration:

```yaml
snc_redis:
    clients:
        default:
            type: '%redis_client_type%'
            alias: default
            dsn: '%env(REDIS_URL)%'
            logging: '%kernel.debug%'
        session:
            type: '%redis_client_type%'
            alias: session
            dsn: '%env(REDIS_URL)%/1'
            logging: '%kernel.debug%'
        mailer:
            type: '%redis_client_type%'
            alias: mailer
            dsn: '%env(REDIS_URL)%/2'
            logging: '%kernel.debug%'
    session:
        client: session
        ttl: 3600
        locking: true
    swiftmailer:
        client: mailer
        key: '%redis_mailer_key%'
```

I have the following error on cache:clear command:

```
Script cache:clear returned with error code 1
!!  
!!  In Compiler.php line 158:
!!                                                                                 
!!    [Symfony\Component\DependencyInjection\Exception\EnvParameterException]      
!!    Incompatible use of dynamic environment variables "REDIS_URL" found in para  
!!    meters.                                                                      
!!                                                                                 
!!  
!!  Exception trace:
!!   Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /code/vendor/symfony/dependency-injection/ContainerBuilder.php:759
!!   Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /code/vendor/symfony/http-kernel/Kernel.php:643
!!   Symfony\Component\HttpKernel\Kernel->initializeContainer() at /code/vendor/symfony/http-kernel/Kernel.php:137
!!   Symfony\Component\HttpKernel\Kernel->boot() at /code/vendor/symfony/framework-bundle/Console/Application.php:64
!!   Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /code/vendor/symfony/console/Application.php:148
!!   Symfony\Component\Console\Application->run() at /code/bin/console:34
!!  
!!  In BaseNode.php line 348:
!!                                                                                   
!!    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
!!    Invalid configuration for path "snc_redis.clients.session.dsns.0": The redi    
!!    s DSN "%env(REDIS_URL)%\/1" is invalid.                                        
!!                                                                                   
!!  
!!  Exception trace:
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/PrototypedArrayNode.php:199
!!   Symfony\Component\Config\Definition\PrototypedArrayNode->finalizeValue() at /code/vendor/symfony/config/Definition/BaseNode.php:338
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/ArrayNode.php:256
!!   Symfony\Component\Config\Definition\ArrayNode->finalizeValue() at /code/vendor/symfony/config/Definition/BaseNode.php:338
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/PrototypedArrayNode.php:199
!!   Symfony\Component\Config\Definition\PrototypedArrayNode->finalizeValue() at /code/vendor/symfony/config/Definition/BaseNode.php:338
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/ArrayNode.php:256
!!   Symfony\Component\Config\Definition\ArrayNode->finalizeValue() at /code/vendor/symfony/config/Definition/BaseNode.php:338
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/Processor.php:37
!!   Symfony\Component\Config\Definition\Processor->process() at /code/vendor/symfony/config/Definition/Processor.php:50
!!   Symfony\Component\Config\Definition\Processor->processConfiguration() at /code/vendor/symfony/dependency-injection/Extension/Extension.php:96
!!   Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration() at /code/vendor/snc/redis-bundle/DependencyInjection/SncRedisExtension.php:45
!!   Snc\RedisBundle\DependencyInjection\SncRedisExtension->load() at /code/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:71
!!   Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at /code/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
!!   Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at /code/vendor/symfony/dependency-injection/Compiler/Compiler.php:141
!!   Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /code/vendor/symfony/dependency-injection/ContainerBuilder.php:759
!!   Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /code/vendor/symfony/http-kernel/Kernel.php:643
!!   Symfony\Component\HttpKernel\Kernel->initializeContainer() at /code/vendor/symfony/http-kernel/Kernel.php:137
!!   Symfony\Component\HttpKernel\Kernel->boot() at /code/vendor/symfony/framework-bundle/Console/Application.php:64
!!   Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /code/vendor/symfony/console/Application.php:148
!!   Symfony\Component\Console\Application->run() at /code/bin/console:34
!!  
!!  In ExprBuilder.php line 189:
!!                                                     
!!    [InvalidArgumentException]                       
!!    The redis DSN "%env(REDIS_URL)%\/1" is invalid.  
!!                                                     
!!  
!!  Exception trace:
!!   Symfony\Component\Config\Definition\Builder\ExprBuilder->Symfony\Component\Config\Definition\Builder\{closure}() at /code/vendor/symfony/config/Definition/Builder/ExprBuilder.php:241
!!   Symfony\Component\Config\Definition\Builder\ExprBuilder::Symfony\Component\Config\Definition\Builder\{closure}() at /code/vendor/symfony/config/Definition/BaseNode.php:344
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/PrototypedArrayNode.php:199
!!   Symfony\Component\Config\Definition\PrototypedArrayNode->finalizeValue() at /code/vendor/symfony/config/Definition/BaseNode.php:338
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/ArrayNode.php:256
!!   Symfony\Component\Config\Definition\ArrayNode->finalizeValue() at /code/vendor/symfony/config/Definition/BaseNode.php:338
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/PrototypedArrayNode.php:199
!!   Symfony\Component\Config\Definition\PrototypedArrayNode->finalizeValue() at /code/vendor/symfony/config/Definition/BaseNode.php:338
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/ArrayNode.php:256
!!   Symfony\Component\Config\Definition\ArrayNode->finalizeValue() at /code/vendor/symfony/config/Definition/BaseNode.php:338
!!   Symfony\Component\Config\Definition\BaseNode->finalize() at /code/vendor/symfony/config/Definition/Processor.php:37
!!   Symfony\Component\Config\Definition\Processor->process() at /code/vendor/symfony/config/Definition/Processor.php:50
!!   Symfony\Component\Config\Definition\Processor->processConfiguration() at /code/vendor/symfony/dependency-injection/Extension/Extension.php:96
!!   Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration() at /code/vendor/snc/redis-bundle/DependencyInjection/SncRedisExtension.php:45
!!   Snc\RedisBundle\DependencyInjection\SncRedisExtension->load() at /code/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:71
!!   Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at /code/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
!!   Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at /code/vendor/symfony/dependency-injection/Compiler/Compiler.php:141
!!   Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /code/vendor/symfony/dependency-injection/ContainerBuilder.php:759
!!   Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /code/vendor/symfony/http-kernel/Kernel.php:643
!!   Symfony\Component\HttpKernel\Kernel->initializeContainer() at /code/vendor/symfony/http-kernel/Kernel.php:137
!!   Symfony\Component\HttpKernel\Kernel->boot() at /code/vendor/symfony/framework-bundle/Console/Application.php:64
!!   Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /code/vendor/symfony/console/Application.php:148
!!   Symfony\Component\Console\Application->run() at /code/bin/console:34
!!  
!!  
```

Note: The following configuration with only host as env var works:

```
REDIS_HOST=redis
```

```yaml
snc_redis:
    clients:
        default:
            type: '%redis_client_type%'
            alias: default
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: '%kernel.debug%'
        session:
            type: '%redis_client_type%'
            alias: session
            dsn: 'redis://%env(REDIS_HOST)%/1'
            logging: '%kernel.debug%'
        mailer:
            type: '%redis_client_type%'
            alias: mailer
            dsn: 'redis://%env(REDIS_HOST)%/2'
            logging: '%kernel.debug%'
```
