### ISSUE TITLE
[Question] Autowiring priorities and binding

### ISSUE THREAD

**Issue by flohw** [symfony/symfony#26556]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.6

I would like to know if there is some kind of priority for autowiring.
I set my services.yml like this :
```yaml
services:
    _defaults:
         bind:
             $appContext: '%app_context%'
```
I have a class `AppBundle\Context\AppContext` (wich is a service) I want to use in my controller's action so I inject it via method argument: `public function indexAction(AppContext $appContext) {}` but I get this error:
`Controller "AppBundle\Controller\DefaultController::indexAction()" requires that you provide a value for the "$appContext" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.`
Just like if autowiring can't resolve my service or try to use the binded `$appContext` value.

So does autowiring has priorities or something ? Or did I misunderstood something else ?

**Comment by iltar** [comment]
Afaik, it's currently not possible to use this kind of binding for argument values. You have 2 other options:
 - Inject it via the constructor, which I recommend for injections in general, keep your method arguments stateful and the stateless in your constructor
 - [Write a custom ArgumentValueResolver](https://symfony.com/doc/current/controller/argument_value_resolver.html) to solve this for your particular class

**Comment by derrabus** [comment]
If `AppBundle\Context\AppContext` is already a service, then you simply need to tag your controllers with `controller.service_arguments`. The `_defaults` block in your example can be removed.

https://symfony.com/doc/current/service_container/3.3-di-changes.html#controllers-are-registered-as-services

**Comment by flohw** [comment]
It is possible to inject via argument as my controller is tagged with `controller.servic_arguments`.

I tried to inject with the controller constructor but I get a type error: string given instead of AppBundle\Context\AppContext instance.

**Comment by javiereguiluz** [comment]
@flohw this looks a bit strange to me:

```yaml
services:
    _defaults:
         bind:
             $appContext: '%app_context%'
```

```php
public function indexAction(AppContext $appContext) {}
```

The binding looks like you are binding a normal container param but you controller is expecting a service. That's why you see this error: `string given instead of AppBundle\Context\AppContext instance.`

Change your binding to something like this:

```yaml
services:
    _defaults:
         bind:
             $appContext: 'App\Some\NamespaceAppContext'
```

**Comment by flohw** [comment]
Yes, that's my point. I want to know if it's possible to name a variable `$appContext` wich is binded to a container parameter and use the service when parameter is typhinted. To be more explicit:
```php
// My service
class AppContext
{
    public function __construct($appContext) {} // inject app_context parameter because _defaults.bind.$appContext: '%app_context%'
}

// My controller
class DefaultController
{
    public function indexAction(AppContext $appContext) {} // Inject AppContext instance instead of app_context parameter because it's typehinted with class name
}
```

**Comment by nicolas-grekas** [comment]
bindings have higher priority than autowiring, so you'll get the binding all the time if you set it

**Comment by javiereguiluz** [comment]
Try with this to default to the container param ... but override it just for this controller:

```yaml
services:
    _defaults:
         bind:
             $appContext: '%app_context%'

    App\Controller\DefaultController:
        $appContext: '@App\Some\Namespace\AppContext'
```

Unrelated comment: my guess is that one of the two variables could change its name. A string and an object rarely are the same thing. So, if the object is the "appContext", then the string is the app context name or the app context path or the serialized app context or ...
