### ISSUE TITLE
[Workflow] Dynamic workflow feature proposal

### ISSUE THREAD

**Issue by yann-eugone** [symfony/symfony#26561]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.x

I recently faced some difficulties with the workflow component.
I've spent some time trying to figure out what was missing, so my goal was covered out of the box.
I'm posting this issue because I really want some advices before I open a pull request.

## Static workflows

There is my problem : **workflows are static**.

Let's clarify this sentence : a workflow is registered within the configuration, so you write YAML to define places and transitions.
When the container is dumped, it contains an **ended list** of available workflow, each one covered with a _support strategy_ and a _definition_.

This is a problem _to me_, because I assume that in real life examples, **nothing is static**.

## Real life example

Let's take an example (THE (_almost_) unique example you can find in every blog post) : a pull request.

```yaml
framework:
    workflows:
        pull_request:
            type: state_machine
            marking_store:
                type: single_state
                arguments:
                    - place
            supports:
                - App\Entity\PullRequest
            places:
                - opened
                - pending_review
                - merged
                - closed
            initial_place: opened
            transitions:
                start_review:
                    from: opened
                    to:   pending_review
                merge:
                    from: pending_review
                    to:   merged
                close:
                    from: pending_review
                    to:   closed
```

This is one of the common structure I've found on the different blog post. But, this is not `true` !
A better structure could be :

```yaml
framework:
    workflows:
        pull_request:
            type: workflow
            marking_store:
                type: multiple_state
                arguments:
                    - places
            supports:
                - App\Entity\PullRequest
            places:
                - opened
                - pending_travis
                - succeed_travis
                - failed_travis
                - pending_appveyor
                - succeed_appveyor
                - failed_appveyor
                - pending_lyrixx_review
                - approved_lyrixx_review
                - disapproved_lyrixx_review
                - pending_fabpot_review
                - approved_fabpot_review
                - disapproved_fabpot_review
                - merged
                - closed
            # ...
            transitions:
                start_review:
                    from: opened
                    to:   [pending_travis, pending_appveyor, pending_lyrixx_review, pending_fabpot_review]
                travis_success:
                    from: pending_travis
                    to:   succeed_travis
                travis_failure:
                    from: pending_travis
                    to:   failed_travis
                appveyor_success:
                    from: pending_appveyor
                    to:   succeed_appveyor
                appveyor_failure:
                    from: pending_appveyor
                    to:   failed_appveyor
                lyrixx_approve_review:
                    from: pending_lyrixx_review
                    to:   approved_lyrixx_review
                lyrixx_disapprove_review:
                    from: pending_lyrixx_review
                    to:   disapproved_lyrixx_review
                fabpot_approve_review:
                    from: pending_fabpot_review
                    to:   approved_fabpot_review
                fabpot_disapprove_review:
                    from: pending_fabpot_review
                    to:   disapproved_fabpot_review
                merge:
                    from: [succeed_travis, succeed_appveyor, approved_lyrixx_review, approved_fabpot_review]
                    to:   merged
                # ...
```

When a pull request is `opened`, some automated tests are triggered, and some responsible teammates's approval are requested, in the same time.
These feedback usually come from some configuration, which depends on the repository itself.
So your model type : `PullRequest` ; is under a workflow. But the definition depends on each `Repository` (an other model).

This is the problem I've been facing with : how to work these "dynamic" workflows.

### How to build workflow and definition ?

`Workflow` and `Definition` are pretty simple objects. Still, we miss a class to help creating instances of these classes.
I've been looking at `DefinitionBuilder` but I think this is not enough. 

I feel myself more comfortable with a config tree (like the one in the framework config), so you can create workflow like this : 

```php
<?php

$workflowName = sprintf('merge_request_%d', $pullRequest->getId());
$places = ['opened', 'merged', 'closed'];
$transitions = [
    'start_review' => ['from' => 'opened', 'to' => []],
    'merge' => ['from' => [], 'to' => 'merged'],
];

foreach ($pullRequest->getRepository()->getReviewers() as $user) {
    $places[] = $pendingPlace = sprintf('pending_%s_review', $user->getNormalizedName());
    $places[] = $approvedPlace = sprintf('approved_%s_review', $user->getNormalizedName());
    $places[] = $disapprovedPlace = sprintf('disapproved_%s_review', $user->getNormalizedName());

    $approveTransition = sprintf('%s_approve_review', $user->getNormalizedName());
    $disapproveTransition = sprintf('%s_disapprove_review', $user->getNormalizedName());

    $transitions['start_review']['to'][] = $pendingPlace;
    $transitions['merge']['from'][] = $approvedPlace;
    $transitions[$approveTransition] = ['from' => $pendingPlace, 'to' => $approvedPlace];
    $transitions[$disapproveTransition] = ['from' => $pendingPlace, 'to' => $disapprovedPlace];
}

foreach ($pullRequest->getRepository()->getAutomatedTools() as $tool) {
    $places[] = $pendingPlace = sprintf('pending_%s', $tool->getNormalizedName());
    $places[] = $succeedPlace = sprintf('succeed_%s', $tool->getNormalizedName());
    $places[] = $failedPlace = sprintf('failed_%s', $tool->getNormalizedName());

    $successTransition = sprintf('%s_success', $tool->getNormalizedName());
    $failureTransition = sprintf('%s_failure', $tool->getNormalizedName());

    $transitions['start_review']['to'][] = $pendingPlace;
    $transitions['merge']['from'][] = $succeedPlace;
    $transitions[$successTransition] = ['from' => $pendingPlace, 'to' => $succeedPlace];
    $transitions[$failureTransition] = ['from' => $pendingPlace, 'to' => $failedPlace];
}

$workflowFactory->create(
    $workflowName,
    [
        'type' => 'workflow',
        'marking_store' => [
            'type' => 'multiple_state',
            'property' => 'places',
        ],
        'initial_place' => 'opened',
        'places' => $places,
        'transitions' => $transitions,
    ]
);
```

Basically, this will create (and return) a `Workflow` object (containing a `Definition`) which is usable as is.

### How and when to add it to the registry ?

This is _to me_ the hardest part of the this feature.
I really want my "dynamic" workflows to be retrieved from the `Registry`, so I can use `Twig` functions and other bridges.
I've found several ways to do it, each method has pros and cons.

My favorite one is using an event listener to register a missing workflow.
Workflow registry has to be updated to ensure this feature :

```php
<?php

namespace Symfony\Component\Workflow;

class Registry
{
    public function get($subject, $workflowName = null)
    {
        try {
            return $this->doGet($subject, $workflowName);
        } catch (InvalidArgumentException $exception) {
            $this->eventDispatcher->dispatch('workflow.missing', $event = new Event($subject, $workflowName));

            if (!$event->hasRegisteredWorkflow()) {
                throw $exception;
            }

            $this->add($event->getWorkflow(), $event->getSupportStrategy());

            return $event->getWorkflow();
        }
    }
}
```

The registry is asked for an unknown workflow, it triggers an event on which your application can subscribe.
Your listener is asked to create the missing workflow. It can use the factory (we talked about), and add the created workflow to the event.

### How to guard transitions ?

The `approve` or `disapprove` review transitions are performed by authenticated users.
I expect that that only `fabpot` can apply `fabpot_approve_review` and `fabpot_disapprove_review`.

So I need to be able to configure a guard expression for these transition.
Something like :

```php
<?php

    //...
    $guardReviewTransition = 'user.getId() == '.$user->getId();
    $transitions[$approveTransition] = ['from' => $pendingPlace, 'to' => $approvedPlace, 'guard' => $guardReviewTransition];
    $transitions[$disapproveTransition] = ['from' => $pendingPlace, 'to' => $disapprovedPlace, 'guard' => $guardReviewTransition];
    //...
```

Then I need to configure and register `GuardListener` for my transitions events.

This listener has to be modified, so it accept configuration at runtime.
Something like :

```php
<?php

namespace Symfony\Component\Workflow\EventListener;

class GuardListener
{
    private $configuration;

    public function setConfig(string $eventName, string $guardExpression): void
    {
        $this->configuration[$eventName] = $guardExpression;
    }
}
```

So in my workflow factory I can configure it like this :

```php
<?php

$eventName = sprintf('workflow.%s.guard.%s', $workflowName, $transition['name']);
$this->guardListener->setConfig($eventName, $transition['guard']);
$this->eventDispatcher->addListener($eventName, [$this->guardListener, 'onTransition']);
```
