### ISSUE TITLE
Could not resolve %env()%

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#26624]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

I have a working Symfony 3 application, and wanted to use [environment variables](https://symfony.com/doc/3.4/configuration/external_parameters.html#environment-variables)

Added this to `parameters.yml`:

```yaml
parameters:
    database_host: '%env(DATABASE_HOST)%'
    env(DATABASE_HOST): localhost
```

Getting:

```
./app/console debug:container --parameters | grep database_host
  database_host    %env(DATABASE_HOST)%    
```

Looks like `%env()` is not processing for some reason. Am I missing something?

**Comment by ostrolucky** [comment]
Confirmed on 4.0.6. However, this is a bug of debug:container command. Inside application, it resolves correct value.

**Comment by umpirsky** [comment]
True, but still, it does not resolve environment variable value.

```yaml
parameters:
    database_host: '%env(DATABASE_HOST)%'
    env(DATABASE_HOST): localhost
```

```bash
$ export DATABASE_HOST=myhost
$ echo $DATABASE_HOST 
myhost
```

```
$this->getParameter('database_host'); // "localhost"
```

If I remove `env(DATABASE_HOST): localhost` I'm getting `EnvNotFoundException `:

```
Symfony\Component\DependencyInjection\Exception\EnvNotFoundException:
Environment variable not found: "DATABASE_HOST".
```
