### ISSUE TITLE
[DependencyInjection] Autowiring does not inject test.doctrine.orm.default_entity_manager 

### ISSUE THREAD

**Issue by choonge** [symfony/symfony#26631]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6

I have a Command which gets two services injected: a private service, and the default entity manager. The entity manager gets injected through autowiring.

```
// src/Command/SomeCommand.php
class SomeCommand
{
    public function __construct(PrivateService $privateService, EntityManagerInterface $entityManager)
    {
        // ...
    }
}
```

```
# config/services.yaml
App\Command\SomeCommand:
    arguments:
        - '@App\Service\PrivateService'
```

I want to write tests for this Command, and mock both the private service and the entity manager. Following the comments in `config/services_test.yaml` I come to the following config:

```
# config/services_test.yaml
services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'
    test.App\Service\PrivateService: '@App\Service\PrivateService'
    test.doctrine.orm.default_entity_manager: '@doctrine.orm.default_entity_manager'
```

In my test, I create mocks for the `test.` services and then use the `CommandTester`:

```
        static::$kernel = static::createKernel();
        static::$kernel->boot();

        $application = new Application(static::$kernel);

        $command = $application->find('app:some-command');
        $this->subject = new CommandTester($command);
```

But apparently only the private service mock gets injected. The entity manager is still the 'real' entity manager. Looking in the cache files generated by the DI component, I see:

```
// var/cache/test/ContainerF18H4dm/getSomeCommandService.php
$this->privates['App\Command\SomeCommand'] = $instance = new \App\Command\SomeCommand(($this->services['test.App\Service\PrivateService'] ?? $this->load(__DIR__.'/getTest_App_Service_PrivateService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')));
```

So for the private service, it uses the `test.` one if it exists. But for the entity manager server, it always just uses `doctrine.orm.default_entity_manager`.

Unsure whether this is expected behaviour, but I would expect to have my `test.doctrine.orm.default_entity_manager` service injected there if I have defined it.
