### ISSUE TITLE
Dump function from 3.4.5 produces ugly result

### ISSUE THREAD

**Issue by ahilles107** [symfony/symfony#26640]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.5

After updating symfony to 3.4.5 (from 3.4.4) i get ugly (simple) dumps from twig templates. 

3.4.4 result: 
<img width="321" alt="zrzut ekranu 2018-03-22 o 18 16 46" src="https://user-images.githubusercontent.com/298610/37786544-431bf780-2dfd-11e8-9d2e-3e7ccf0e2195.png">

3.4.5 result:
<img width="938" alt="zrzut ekranu 2018-03-22 o 18 18 45" src="https://user-images.githubusercontent.com/298610/37786658-7f5393ac-2dfd-11e8-95de-b137fd0230ca.png">

Dump's from php files (controller, listener) looks ok. Only twig is affected. Switching back to 3.4.4 solves issue. 3.4.6 is also affected.

**Comment by ahilles107** [comment]
[Solved] For some reason twig dump (`Twig_Extension_Debug`) extension from 3.4.5 is more important that var-dumper. IMO it can be treated as BC break.

We had `Twig_Extension_Debug` enabled in project and so far it was ignored. From 3.4.5 it's loaded instead var-dumper.
```
services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
                - { name: 'twig.extension' }
```

Maybe it's connected to https://github.com/symfony/symfony/pull/25756 ?

**Comment by xabbuh** [comment]
Can you create a small example project that allows to reproduce your issue?

**Comment by ahilles107** [comment]
Hey, you need repo with example? It's very simple i reproduce it with:

`symfony new test_dump 3.4.4` in `app/Resources/views/base.html.twig` i added `{{ dump(app.request) }}`. Then in `app/config/services.yml` i added to services section:
```
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
                - { name: 'twig.extension' }
```
Now it renders dump ok. When i change in `composer.json` `"symfony/symfony": "3.4.4",` to `"symfony/symfony": "3.4.5",` and call `composer update --prefer-dist --prefer-stable` after installation dump is wrong (rendered by `Twig_Extension_Debug`). Looks like with var-dump we don't need this extension anymore, but it SF shouldn't change so much in minor release.
