### ISSUE TITLE
[Messenger] Allow different types of busses

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#26652]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

I want to have multiple buses with different features. Example of different buses might be: 

#### Default bus

- Allows zero or more handlers
- Supports both sync and async
- Return values are optional

#### Command bus

- Exactly one handler required
- Supports both sync and async
- No return values from handlers

#### Event bus

- Allows zero or more handlers
- Supports both sync and async
- No return values from handlers

#### Query bus

- Exactly one handler required
- Supports only sync
- Return values required

------

Example config: 

```yaml
framework:
  messenger:
    middlewares: ~ # default middlewares
    bus_foo:
      type: foo
      routing:
        'App\Bar': ['sender.bar', 'sender.biz']
        'App\Foo': 'sender.foo'
      middlewares:  # bus specific middlewares
        - 'custom_service'
        - validation: true
```

**Comment by mvrhov** [comment]
The Whole Event bus with recorder taken from Simple bus package PR is still on sroze's fork of symfony

**Comment by sroze** [comment]
I think here there are two topics here.

1. **Letting FrameworkBundle create multiple buses**
    It might be a good idea, but obviously increases the complexity. I have no idea whether it will be a common need (i.e. more than the "20%") or not. Therefore, before deciding anything like that, I'd argue we should wait a bit :) 

2. **Apply certain rules for each of these buses**
    I think that this should typically live outside of Symfony Core for the time being. These topics are opinionated and most will have different opinions depending on the use-case. IMHO, a very good contribution would be a library providing a set of middlewares enforcing these rules. I'm planning to work on these as well but if you want to get started before, that would be 👌

**Comment by romaricdrigon** [comment]
Hello, 
Being able to easily declare multiple buses would be great (at least having some documented YAML configuration you can add). It is pretty much required for using the `Messenger` component as a command bus. Plus I see having middleware declared on all buses as possibly surprising and causing issues.
An approach like [Tactician](https://github.com/thephpleague/tactician-bundle) would be great: having some sane defaults, easy to get started, and being able to override and configure when you want to go further.

**Comment by sroze** [comment]
As a first step, I suggest we allow to define multiple buses like that:

```yaml
framework:
    messenger:
        buses:
            default: ~
            command: ~
            query: ~
```

1. Each of these bus configurations will a `messenger.bus.$name` service. If there is a bus named `default` then we create an alias `message_bus` (as it is right now).

2. We keep defining the middlewares via tags (for now at least). If the middleware tag (to be renamed `messenger.bus_middleware` IMHO) has a `bus` attribute (names of the buses, comma separated) it is only configured for those buses. If no, then it's applied for all the buses.

We would have the "calling handler" and "routing the sender" middlewares tagged without a given bus so they would be shared across all the buses.

**Comment by mvrhov** [comment]
@sroze: This is not enough. e.g for event bus you need a middleware registered, that won't throw if there is no handler for a specific command

**Comment by romaricdrigon** [comment]
That seems to be a robust start 👍 

Later, what about adding middleware in the YAML configuration, instead of using tags? 
I may not be up-to-date with the "latest Symfony style", but it looks clearer to me.
In example:
```yaml
framework:
    messenger:
        buses:
             all:
                 middlewares:
                  - "Symfony\\Messenger\\HandlerMiddleware"
            default: ~
            command:
                middlewares:
                    - "App\\MyMiddleware"
```

Another option would be a to use a Doctrine-bundle style configuration, though I find it more ambiguous (are middlewares on the top overriden? Then we should re-add them?...).
```yaml
framework:
    messenger:
        middlewares: # Will apply to all, Doctrine-bundle configuration style
            - "Symfony\\Messenger\\HandlerMiddleware"
        buses:
            default: ~
            command:
                 middlewares:
                     - "Symfony\\Messenger\\HandlerMiddleware"
                     - "App\\MyMiddleware"
```
