### ISSUE TITLE
[DI] Autowiring, argument not passed with abstract class inheritance

### ISSUE THREAD

**Issue by XavierVallot** [symfony/symfony#26680]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

I have an abstract class (aka the parent) : 
```php
abstract class AbstractContentType extends AbstractType
{
    protected $titleLevels;
    protected $fieldTranslationType;

    public function __construct(AbstractFieldTranslationType $fieldTranslationType)
    {
        $this->fieldTranslationType = $fieldTranslationType;
    }

    public function setTitleLevels(array $titleLevels): void
    {
        $this->titleLevels = array_combine($titleLevels, $titleLevels);
    }
```
And that other class (the child) : 
```php
class ArticleContentType extends AbstractContentType
{
    protected $articleRepository;

    public function __construct(AbstractFieldTranslationType $fieldTranslationType, ArticleRepository $articleRepository)
    {
        parent::__construct($fieldTranslationType);
        $this->articleRepository = $articleRepository;
    }
```
My services.yaml looks like this (following instructions from [that doc page](https://symfony.com/doc/3.4/service_container/parent_services.html)) :

```yaml
Yprox\Bundle\Common\ExtensionBundle\Form\Type\AbstractContentType:
        abstract: true
        calls:
            - [setTitleLevels, ['%article.header_types%']]
        autowire: true
        autoconfigure: false
        public: false

Yprox\Bundle\Admin\ArticleBundle\Form\Type\ArticleContentType:
        parent: Yprox\Bundle\Common\ExtensionBundle\Form\Type\AbstractContentType
        autowire: true
        public: false
        autoconfigure: false
```
And, after running `debug:container` with the --show-arguments flag for my two services :
```
Information for Service "Yprox\Bundle\Common\ExtensionBundle\Form\Type\AbstractContentType"
===========================================================================================

 ---------------- ------------------------------------------------------------------- 
  Option           Value                                                              
 ---------------- ------------------------------------------------------------------- 
  Service ID       Yprox\Bundle\Common\ExtensionBundle\Form\Type\AbstractContentType  
  Class            Yprox\Bundle\Common\ExtensionBundle\Form\Type\AbstractContentType  
  Tags             -                                                                  
  Calls            setTitleLevels                                                     
  Public           no                                                                 
  Synthetic        no                                                                 
  Lazy             no                                                                 
  Shared           yes                                                                
  Abstract         yes                                                                
  Autowired        yes                                                                
  Autoconfigured   no                                                                 
 ---------------- ------------------------------------------------------------------- 
```
And : 
```
Information for Service "Yprox\Bundle\Admin\ArticleBundle\Form\Type\ArticleContentType"
=======================================================================================

 ---------------- ----------------------------------------------------------------------- 
  Option           Value                                                                  
 ---------------- ----------------------------------------------------------------------- 
  Service ID       Yprox\Bundle\Admin\ArticleBundle\Form\Type\ArticleContentType          
  Class            Yprox\Bundle\Admin\ArticleBundle\Form\Type\ArticleContentType          
  Tags             -                                                                      
  Calls            setTitleLevels                                                         
  Public           no                                                                     
  Synthetic        no                                                                     
  Lazy             no                                                                     
  Shared           yes                                                                    
  Abstract         no                                                                     
  Autowired        yes                                                                    
  Autoconfigured   no                                                                     
  Arguments        Yprox\Bundle\Common\CoreBundle\Form\Type\AbstractFieldTranslationType  
                   Yprox\Model\Repository\ArticleRepository                               
 ---------------- ----------------------------------------------------------------------- 
```
Everything seems quite normal until then, but I have this error at the end : 
```php
Type error: Too few arguments to function Yprox\Bundle\Admin\ArticleBundle\Form\Type\ArticleContentType::__construct(), 0 passed in /srv/app/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php on line 92 and exactly 2 expected
```
I can't figure out what's happening here...

**Comment by iltar** [comment]
As illustrated by the [docs](https://symfony.com/doc/current/form/form_dependencies.html#define-your-form-as-a-service), you still have to add the `form.type` tag unless you have `autoconfigure: true`, which I don't see in your pasted configuration.

**Comment by XavierVallot** [comment]
I tried adding the `form.type` tag, but now I have this : `The service "Yprox\Bundle\Common\ExtensionBundle\Form\Type\AbstractContentType" tagged "form.type" must not be abstract.`

**Comment by iltar** [comment]
The tag should be added to child service definitions only (or use `autoconfigure: true`)

**Comment by XavierVallot** [comment]
So, adding `autoconfigure: true` on child leads us to : 
```php 
The service "Yprox\Bundle\Admin\ArticleBundle\Form\Type\ArticleContentType" cannot have a "parent" and also have "autoconfigure". Try setting "autoconfigure: false" for the service in /srv/app/apps/admin/config/services.yaml (which is being imported from "/srv/app/apps/admin/config/config.yml").
```
But ! if i set `autoconfigure: false` and manually add the `form.type` tag, everything works fine !
So, to sum up, in that particular case : 

**Parent class configuration :** 
```yaml
Yprox\Bundle\Common\ExtensionBundle\Form\Type\AbstractContentType:
        abstract: true
        calls:
            - [setTitleLevels, ['%article.header_types%']]
        autowire: true
        autoconfigure: false
        public: false
```

**Child class configuration**
```yaml
Yprox\Bundle\Admin\ArticleBundle\Form\Type\ArticleContentType:
        parent: Yprox\Bundle\Common\ExtensionBundle\Form\Type\AbstractContentType
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - {name: form.type}
```

Thanks @iltar for your help !
