### ISSUE TITLE
[Messenger] Configure the component out of the "framework" config key

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26690]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Before Symfony 4, it was common to configure everything under the main `framework` key:

```yaml
framework:
    workflow:
        # ...
    validation:
        # ...
    translation:
        # ...
```

But now with Symfony 4, this looks odd, specially now that each component is configured using its own recipe and config file:

```yaml
# config/packages/workflow.yaml
framework:
    workflow:
        # ...
```

So, shouldn't we slowly go towards components configured out of the `framework` key? If you agree, we could start with the unreleased Messenger component: `framework.messenger.` -> `messenger.` ?
