### ISSUE TITLE
[DI][Config] How to allow to merge parameters from parent configs?

### ISSUE THREAD

**Issue by TomasVotruba** [symfony/symfony#26713]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I have a question that arose from https://github.com/symfony/symfony/pull/26686

I have parent config and I need to merge all imported parameters together.

This works in [Nette/DI](https://github.com/nette/di) by default, so it was a big surprise for me that in Symfony, parameters in Symfony are overidden:

- https://github.com/symfony/symfony/blob/6bfc082b8751db05e32d72270989a2847b708dab/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L135

With no other way to reach them :(. Here is a simple example:

```yaml
# first.yml
parameters:
    another_key:
       - skip_this
```

```yaml
# second.yml
imports:
    - { resource: 'first.yml' }

parameters:
    another_key:
       - skip_that_too
```

```yaml
# => result
parameters:
    another_key:
       - skip_this
       - skip_that_too
```

It caused many troubles that are described in these issues:

- https://github.com/Symplify/Symplify/issues/719
- https://github.com/Symplify/Symplify/issues/736
- https://github.com/Symplify/Symplify/issues/696

### How to solve this?

At the moment the only workaround is to use reflection and [call many private methods](https://github.com/Symplify/Symplify/blob/efe794cb99f5fe0955213a00423acd4ae1176096/packages/EasyCodingStandard/src/Yaml/CheckerTolerantYamlFileLoader.php#L58-L101).

Using Extension class, Bundle class and Configuraiton class (suggested in https://github.com/symfony/symfony/pull/26686) is overkill for 3 line modification.

Wha about `protected` method in `YamlFileLoader`?

https://github.com/symfony/symfony/blob/6bfc082b8751db05e32d72270989a2847b708dab/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L135

**Before**

```php
foreach ($content['parameters'] as $key => $value) {
    $this->container->setParameter($key, $this->resolveServices($value, $path, true));
}
```

**After**

```php
foreach ($content['parameters'] as $key => $value) {
    $this->addParameter($key, $this->resolveServices($value, $path, true));
}
    
//...

protected function addParameter($key, $value)
{
    $this->container->setParameter($key, $value);
}
```

How can I solve it?

**Comment by ostrolucky** [comment]
I don't think giving library authors option to easily override this behavior is desirable. Parameter overriding is what users are used to and expect. 

This expectation breaks if library authors start to change this and suddenly users will need to differentiate YAML in which context is going to have parameters merged and in which replaced.

Having option to merge is good. But it should be clearly marked in YAML, not allow library authors to change default behaviour.

I suggest instead of 
```yaml
# second.yml
imports:
    - { resource: 'first.yml' }

parameters:
    exclude:
       - skip_that_too
```

And expecting values will be merged, to do that only when specified so via special syntax, e.g.

```yaml
imports:
    - { resource: 'first.yml', merge_keys: 'parameters.exclude' }


parameters:
    exclude:
       - skip_that_too
```

or
```yaml
# second.yml
imports:
    - { resource: 'first.yml' }

parameters:
    exclude (merge):
       - skip_that_too
```

**Comment by nicolas-grekas** [comment]
I still think this is just something that on a bundle's responsibility. Make a configuration key that behaves as you want, that'll be plain explicit. I don't understand why this would be at a lower level.

**Comment by fabpot** [comment]
Agree with @nicolas-grekas

**Comment by TomasVotruba** [comment]
So to merge parameters, I need to create 4 extra classes?

**Comment by TomasVotruba** [comment]
@ostrolucky I like the custom option :+1:

**Comment by ostrolucky** [comment]
> Can extension get to global parameters? How would the override of main parameter service work? 

Idea is that you should not do this in `parameters:` key. Create your own key.

> Make a configuration key that behaves as you want, that'll be plain explicit.

**Comment by TomasVotruba** [comment]
> Idea is that you should not do this in parameters: key. Create your own key.

I know the idea, but it's just workaround. Not solution.

> You should really give a go in ECS to a traditional approach, like bundles do.

I did, it only caused troubles for this simple use case. It's no go. See references issues.
**I really need to merge parameters, that's all**. Your solution is valid in situations like [DotrineBundle](http://symfony.com/doc/master/bundles/DoctrineBundle/configuration.html):

```yaml
doctrine:
    dbal:
        default_connection:           default

        # A collection of custom types
        types:
            # example
            some_custom_type:
                class:                Acme\HelloBundle\MyCustomType
                commented:            true

        connections:
            # A collection of different named connections (e.g. default, conn2, etc)
            default:
                dbname:               ~
                host:                 localhost
                port:                 ~
                user:                 root
                password:             ~
                charset:              "UTF8"
```

There is many strings, many keys, many services to create or not create in extension etc. Cyclocmatic complexity of such config and all it's possible paths is at least over 100.

Output of 1 parameter is cyclocmatic complexity of 1.

```yaml
$skip = $this->parameterBag->get('skip');
var_dump($skip); // array
```

**Comment by ostrolucky** [comment]
Yes it's easy for you, but like I said, you don't do any validation. You also don't seem to realize that due to your merging default strategy, it's impossible to not exclude something that was already excluded by an import. This is going to be another problem you will need to solve in future.

> I really need to merge parameters, that's all

No, you need to merge values for configuration keys. This feature already works in Symfony. Ever needed to partially change configuration of some bundle for certain environment? Just stuff part you want to change into `packages/dev/{package}.yaml`. Now, your job is to figure out how to utilize this in ECS. Symfony already has this feature.

**Comment by TomasVotruba** [comment]
> Yes it's easy for you, but like I said, you don't do any validation. You also don't seem to realize that due to your merging default strategy, it's impossible to not exclude something that was already excluded by an import. This is going to be another problem you will need to solve in future.

When half of the parameters are missing without you knowing and application is broken, the rest of problem is not relevant. Also, validation is mater of service and could be added. It doesn't depend on any of these 2 architectures.

Also, with parameters, I can make use of this great feature [local service binding](https://symfony.com/blog/new-in-symfony-3-4-local-service-binding): https://github.com/Symplify/Symplify/pull/754/files#diff-a86717d97edc88614f0c9e050b85a046

**Comment by TomasVotruba** [comment]
Another WTF case is loading files in import with glob. Imagine there are many code snippets you want to render and you'd like to have them grouped by some theme in smaller files, rather than one big 1000-line long that is hard to maintain and go through.

For that reasons you split it into more files:

```yaml
imports:
    - { resources: 'code-examples/*' }
```
   
```yaml
# code-examples/symfony.yml
parameters:
    framework:
        symfony:
            -
                name: controller
                code: "<some php snippet>"
```

```yaml
# code-examples/laravel.yml
parameters:
    framework:
        laravel:
            -
                name: controller
                code: "<some php snippet>"
```

In the end, you would like to render all code snippets for all the framework. Instead, all except one is lost. Do you know which one? :)

**Comment by xabbuh** [comment]
I'd say if you really have the need for such a complex parameter handling, you will indeed be better off with using a semantic configuration with a DI extension handling the merging of the different values.

**Comment by TomasVotruba** [comment]
@xabbuh That was already suggested before, see: https://github.com/symfony/symfony/issues/26713#issuecomment-377692464

Do you have some other more DX friendly idea?

**Comment by fabpot** [comment]
Merging would be the worst DX ever, that's what most comments are trying to say.

**Comment by TomasVotruba** [comment]
@fabpot Why?

**Comment by nicolas-grekas** [comment]
@TomasVotruba there are existing mechanism that behave with some merging behavior (eg translation, routing). They are all managed by a dedicated loader-based mechanism. And each of them has some specific behavior that wouldn't fit any generic merging logic. It looks like this is what you'd like to achieve: some custom loading mechanism that fits your domain and your configuration layout. Looking at comments here, this is something you need to build on your side, not something we can add/want in core.

**Comment by TomasVotruba** [comment]
@nicolas-grekas I understand there is a way to achieve the same. I did that before and it caused me only troubles, as I already wrote. Repeating the same over and over again does not really solve the issue. Also I miss answers to my questions: https://github.com/symfony/symfony/issues/26713#issuecomment-377736147

I understand that's status quo at the moment.

I don't ask for how, I ask for **why**. Why there should not be a way to manage merged parameters, if there already as a way to change everything in the main config, see comment: https://github.com/symfony/symfony/issues/26713#issuecomment-377692464

> ...this is something you need to build on your side

I already did, as I wrote in the issue description in *How to solve this?*

> ...not something we can add/want in core

Please forget the PR, it was not properly communicated on my side. That is not my intention, **I just look for a better solution**.

**Comment by xabbuh** [comment]
Basically, I do not see how we could implement the feature without BC breaks and without rewriting large parts of the parameter handling to achieve this. So my suggestion would be to close here as from my point of view this use case is not common enough and there already existing ways to solve the problem.

**Comment by nicolas-grekas** [comment]
Closing as discussed: this doesn't belong to the DI component itself, but to a custom loader that a bundle could manage.

**Comment by TomasVotruba** [comment]
That's not a solution, as discussed.

**Comment by nicolas-grekas** [comment]
Not all solutions to all problems are on Symfony core's shoulders...

**Comment by TomasVotruba** [comment]
That's ok. It's not ok to propose irelevant path as a solution.

**Comment by TomasVotruba** [comment]
Here is solution for those in need: https://github.com/symplify/packagebuilder#10-do-you-need-to-merge-parameters-in-yaml-files-instead-of-override

**Comment by yoander** [comment]
> @fabpot For me it is the opposite. Why do you think so?

I'm agree with you, I think the **import** should work as expected: keeps parent parameters and overrides those defined in child configuration as a matter of fact Apache, NGINX and MySQL behave in this way.

**Comment by Wirone** [comment]
@nicolas-grekas @fabpot Today I found this issue while I was looking for a way in which I wouldn't need to copy&paste whole Enqueue config just to add one additional transport option for `dev` environment.

Real world case:

```
# api/config/packages/enqueue.yaml

enqueue:
    default:
        transport:
            dsn: "rdkafka://"
            global:
                bootstrap.servers: '%env(KAFKA_BOOTSTRAP_SERVERS)%'
                security.protocol: ssl
                group.id: '%env(KAFKA_GROUP_ID)%'
                ssl.ca.location: '%env(KAFKA_ROOT_CA)%'
                ssl.certificate.location: '%env(KAFKA_CERT)%'
                ssl.key.location: '%env(KAFKA_KEY)%'
                enable.ssl.certificate.verification: 'false'
                ssl.endpoint.identification.algorithm: 'none'
                enable.auto.commit: 'true'
            topic:
                auto.offset.reset: latest
        client: ~
```

and in `api/config/packages/dev/enqueue.yaml` we wanted to add `debug: all` to the transport. Right now, whole config has to be copied and then overidden in a required way.

It's error-prone redundancy → today we changed file locations for SSL files (migrated to Rancher secrets) and, because why not, we changed it only in main config, not in `dev`... Of course it was catched on code review, but next time can be overlooked.

This is NOT convenient way of building reusable configurations.

IMHO Symfony, as framework, should offer tools for loading configuration with recursive merge option, so specific configurations (per-environment) could expand/override common configs (the same for all environments).

Could you reconsider your opinion on this topic?

**Comment by c33s** [comment]
the current behavior has really a bad UX/DX. trying to be DRY in the config is nearly impossible with the current situation.

using the yaml merge feature, i want the config to be merged:
```yaml
liip_imagine:
    filter_sets:
        portfolio_normal: &portfolio
            quality: 75
            filters: &portfolio_filters
                thumbnail: { size: !php/const App\Entity\PortfolioItem::SIZE_MAP_NORMAL, mode: inset, allow_upscale: true }
                grayscale: ~
                strip: ~
        portfolio_wide:
            << : *portfolio
            filters:
                thumbnail: { size: !php/const App\Entity\PortfolioItem::SIZE_MAP_WIDE }
```

dumping the config in `LiipImagineExtension`:
```php
    public function load(array $configs, ContainerBuilder $container)
    {
        dump($configs);
```
leads to
```
      "portfolio_normal" => array:2 [▼
        "quality" => 75
        "filters" => array:5 [▼
          "thumbnail" => array:3 [▼
            "size" => array:2 [▼
              0 => 320
              1 => 304
            ]
            "mode" => "inset"
            "allow_upscale" => true
          ]
          "grayscale" => null
          "strip" => null
        ]
      ]
      "portfolio_wide" => array:2 [▼
        "quality" => 75
        "filters" => array:1 [▼
          "thumbnail" => array:1 [▼
            "size" => array:2 [▼
              0 => 640
              1 => 304
            ]
          ]
        ]
      ]
```
where i would assume that i would get a fully merged parameter config set.

my suggestion would be to handle it like puppet which uses `hiera.yaml` for configuartion, where i can define how a specific key/parameter should be merged. 

https://puppet.com/docs/puppet/6.17/hiera_merging.html

```
Merge behaviors

There are four merge behaviors to choose from: first, unique, hash, and deep.

When specifying a merge behavior, use one of the following identifiers:

    'first', {'strategy' => 'first'}, or nothing.
    'unique' or {'strategy' => 'unique'}.
    'hash' or {'strategy' => 'hash'}.
    'deep' or {'strategy' => 'deep', <OPTION> => <VALUE>, ...}. Valid options:
        'knockout_prefix' - string or undef; disabled by default.
        'sort_merged_arrays' - Boolean; default is false
        'merge_hash_arrays' - Boolean; default is false
```

analog to puppet the config in symfony for liip would look like that:

```yaml
lookup_options:
    liip_imagine:filter_sets: { merge: { strategy: deep } }
```
with this config, all `filter_sets` in liip_imagine would be deep merged.

with that we would give the control back to the user what should be merged and how. the current behavior is really unhandy and promotes an anti pattern with not being able to keep the config dry.
