### ISSUE TITLE
Environment variables lack type

### ISSUE THREAD

**Issue by peter-gribanov** [symfony/symfony#26812]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.7

I have a problem with the type of environment variables:

> Invalid type for path "framework.ssi.enabled". Expected boolean, but got string.

My config

```yml
parameters:
    env(NGINX_SSI): 0

framework:
    ssi:
        enabled: '%env(bool:NGINX_SSI)%'
```

Based on this #23901 PR (in [blog](https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables)), everything should work, but no.

I tried this:

```yml
parameters:
    env(NGINX_SSI): false

framework:
    ssi:
        enabled: '%env(bool:NGINX_SSI)%'
```

And this:

```yml
parameters:
    env(NGINX_SSI): 0
    ssi_enabled: '%env(bool:NGINX_SSI)%'

framework:
    ssi:
        enabled: '%ssi_enabled%'
```

But result does not changed.
What am i doing wrong?
