### ISSUE TITLE
You must either make the "AppBundle:User" entity Doctrine Repository ("Doctrine\ORM\EntityRepository") implement "Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface" or set the "property" option in the corresponding entity provider configuration.

### ISSUE THREAD

**Issue by grzegorztomasiak** [symfony/symfony#26854]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.8

Yesterday I have upgraded from 3.4.6 to 3.4.8 and the API (Symfony + FOSRestBundle) throws error: 

> You must either make the "AppBundle:User" entity Doctrine Repository ("Doctrine\ORM\EntityRepository") implement "Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface" or set the "property" option in the corresponding entity provider configuration.

The problem is that I don't use anywhere `UserLoaderInterface` or `loadUserByUsername` method since I have custom solutions. Anybody knows how to make it work again? Symfony v3.4.6 works fine and no such error is thrown.

**Comment by iltar** [comment]
Can you share your security config?

**Comment by grzegorztomasiak** [comment]
Sure

```
security:
    encoders:
        AppBundle\Entity\User:
          id: security.password.encoder
        AppBundle\Entity\AppAdmin:
          id: security.password.encoder


    providers:
        frontoffice:
            entity: { class: AppBundle:User }
        admin:
            entity: { class: AppBundle:AppAdmin }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/g
            security: false
        api_private_area:
            pattern:   ^/.+/api/
            stateless: true
            anonymous: ~
            simple_preauth:
                authenticator: security.authenticator.api
        admin_area:
            entry_point: security.admin.authentication.handler.entry_point
            pattern: ^/admin
            anonymous: ~
            simple_form:
                authenticator: security.authenticator.admin
                login_path: admin.login
                check_path: admin.validate
                success_handler: security.admin.authentication.handler.login
                failure_handler: security.admin.authentication.handler.login
                use_referer: true
            switch_user: true
            context: primary_auth
        frontoffice_area:
            pattern:   ^/
            anonymous: ~
            simple_form:
                authenticator: security.authenticator.user
                check_path: app.auth.check
                success_handler: security.authenticator.user.handler.login
                failure_handler: security.authenticator.user.handler.login
                use_referer: true
            switch_user: true
            context: primary_auth
```
