### ISSUE TITLE
[RFC][Help] Where to validate config params coming from .env file?

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#26882]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? |yes/no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.4 and 4.x

I developed a bundle to manage SES notifications through SNS.

I configure it this way:

```yaml
# Aws Ses Monitor
shq_aws_ses_monitor:
    aws_config:
        credentials_service_name: 'Aws\Credentials\Credentials'
        region: '%env(AWS_REGION)%'
    bounces:
        topic:
            name: '%env(AWS_SES_TOPIC_BOUNCES)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
    complaints:
        topic:
            name: '%env(AWS_SES_TOPIC_COMPLAINTS)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
    deliveries:
        topic:
            name: '%env(AWS_SES_TOPIC_DELIVERIES)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
```

But this throws the following errors:

> (3/3) EnvParameterException
> Incompatible use of dynamic environment variables "APP_SCHEME" found in parameters.
> (2/3) InvalidConfigurationException
> Invalid configuration for path "shq_aws_ses_monitor.bounces.topic.endpoint.protocol": The protocol "%env(APP_SCHEME)%" is not supported. Please choose one of ["HTTP","HTTPS","http","https"]
> (1/3) InvalidArgumentException
> The protocol "%env(APP_SCHEME)%" is not supported. Please choose one of ["HTTP","HTTPS","http","https"]

This is due the fact that my `Configuration` checks that the passed `schema` is one of the ones allowed (`http` or `https`):

```php
    /**
     * Adds the section about endpoint configuration.
     *
     * @param string $endpointName The endpoint name to use
     *
     * @return ArrayNodeDefinition|NodeDefinition The root node (as an ArrayNodeDefinition when the type is 'array')
     */
    public function addTopicSection($endpointName)
    {
        $builder = new TreeBuilder();
        $node    = $builder->root('topic')->addDefaultsIfNotSet();

        $node
            ->children()
                ->scalarNode('name')->defaultValue('not_set')->cannotBeEmpty()->end()
                ->arrayNode('endpoint')
                    ->children()
                        ->scalarNode('route_name')->defaultValue($endpointName)->cannotBeEmpty()->end()
                        ->scalarNode('protocol')
                            ->validate()
                            ->ifNotInArray(self::getSupportedProtocols())
                            ->thenInvalid('The protocol %s is not supported. Please choose one of ' . json_encode(self::getSupportedProtocols()))->end()
                            ->defaultValue('http')->cannotBeEmpty()
                        ->end()
                        ->scalarNode('host')->isRequired()->cannotBeEmpty()->end()
                    ->end()
                ->end()
            ->end();

        return $node;
    }
```

Now, reading this https://github.com/symfony/symfony/issues/20850#issuecomment-266049681 I understand that probably I cannot check the value of given configurations in the `Configuration` if the parameters are passed as environment variables provided by an `.env` file as this check happens at compile time.

I'm I understanding right?

**So, where should have I to move the validation logic?**

Because the values are not available anywhere in any file contained in the `DependencyInjection` folder...

Any ideas about?

And given this incompatibility, isn't it a big limitation as basically the `validate()` method cannot be used in `Configuration` if it has to validate values coming from environment?

cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
I suppose you need to validate at runtime, that's the only way with env vars. To pass the Config barrier, I think you can add a check since 4.1 to bypass placeholders. Ping @ro0NL WDYT?

**Comment by Aerendir** [comment]
@nicolas-grekas , but this is a really big limitation: any bundle that uses the `validate()` method to validate the passed configuration is _de facto_  unable to be used with environment variables, isn't it?

**Comment by nicolas-grekas** [comment]
That's correct but I don't know any way around that doesn't require some work from bundle authors, o here is the only solution I can think of. It doesn't feel like a limitation but a fact we have to do with. If you have any idea around, please submit some code we'd be happy to discuss.

**Comment by ro0NL** [comment]
Question is what's the point of using an env for a node that is validated during compile-time. At first i'd say either lax/remove validation or dont use an env :)

> I think you can add a check since 4.1 to bypass placeholders

Not at the builder level, only at the node type class level.  Not sure how it should look like...

```php
->skipPlaceholders()
->validate()
    // ...
->end()
```

Still.. it defeats validation :)

**Comment by Aerendir** [comment]
The point is that in my case I've set two env variables:

- `APP_SCHEME`
- `APP_HOST`

Those variables are used in many parts of my app, for example:

```yaml
# services.yaml
parameters:
    # This is required to generate valid URLs in commands as the default behavior is to create them using http://localhost
    # See http://symfony.com/doc/current/console/request_context.html
    router.request_context.scheme: '%env(APP_SCHEME)%'
    router.request_context.host: '%env(APP_HOST)%'
    base_url: '%env(APP_SCHEME)%://%env(APP_HOST)%/'

# packages/framework.yaml
framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        base_urls:
            # To correctly build URLs
            - '%base_url%'

# packages/shq_aws_ses_monitor.yaml
shq_aws_ses_monitor:
    aws_config:
        credentials_service_name: 'Aws\Credentials\Credentials'
        region: '%env(AWS_REGION)%'
    bounces:
        topic:
            name: '%env(AWS_SES_TOPIC_BOUNCES)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
    complaints:
        topic:
            name: '%env(AWS_SES_TOPIC_COMPLAINTS)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
    deliveries:
        topic:
            name: '%env(AWS_SES_TOPIC_DELIVERIES)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'

```

As you can see I need both the `schema` and the `host` in many places in my configurations, for this reason I need them.

Now, in the last example - SHQAwsSesMonitor - I'm using the same environment variables to set the values of the required parameters.

The bundle checks that a correct `scheme` is passed to avoid stupid errors difficult to spot, so it checks the schema is one between http or https.

Now, for sure I can modify my bundle to make the check at runtime instead at compile time: this is not an issue.

Maybe I can move the logic inside the service that uses the config params (your comments are confirming that this is a valid way of dealing with the validation).

But, now, the point is broader: any bundle, basically, have to move this logic outside the `Configuration`.

Not a great problem for sure, but if this can be easily fixed maybe it is worth the effort.

While if this is a big challenge, then a better approach is to simply move the validation logic in some places doing the validation at runtime.
