### ISSUE TITLE
YAML route prefix not working at all.

### ISSUE THREAD

**Issue by mackou** [symfony/symfony#26949]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.8

Hello everyone.
YAML route prefix are not working at all, here's an exemple :

```yaml
# config/routes/routes.yaml

app_security:
    resource: 'security.yaml'
    prefix: /security
```

```yaml
# config/routes/security.yaml

app_security_login:
    path: /login
    controller: App\Controller\SecurityController:login

app_security_logout:
    path: /logout
    controller: App\Controller\SecurityController:logout
```

Here's the route debug : 
```
 -------------------------- -------- -------- ------ -----------------------------------
  Name                       Method   Scheme   Host   Path
 -------------------------- -------- -------- ------ -----------------------------------
  app_main_route             ANY      ANY      ANY    /
  app_security_login         ANY      ANY      ANY    /login
  app_security_logout        ANY      ANY      ANY    /logout
  _twig_error_test           ANY      ANY      ANY    /_error/{code}.{_format}
  _wdt                       ANY      ANY      ANY    /_wdt/{token}
  _profiler_home             ANY      ANY      ANY    /_profiler/
  _profiler_search           ANY      ANY      ANY    /_profiler/search
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results
  _profiler_open_file        ANY      ANY      ANY    /_profiler/open
  _profiler                  ANY      ANY      ANY    /_profiler/{token}
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css
 -------------------------- -------- -------- ------ -----------------------------------

```

If this feature is not supported for YAML files, I think it should be written in the the documentation here : (YAML tab)
http://symfony.com/doc/current/routing/external_resources.html#prefixing-the-urls-of-imported-routes

Thanks for your time.

**Comment by zairigimad** [comment]
Hi @mackou,

I'm not sure but I think that in the documentation the key prefix is used to the class as a target, not the action. so that we prefix all the actions in the controller, or in other routing configuration.

**Comment by xabbuh** [comment]
This is working fine for me. Can you create a small example application that allows to reproduce your issue?

**Comment by mackou** [comment]
I made further testing and I can detail a bit more. 

It seems that all routing files in config/routes are loaded automatically and it will ignore the prefix.
But if the file is in an other directory, it's fine, here's an exemple : 

This is working
----------------
```yaml
app_security:
    resource: 'security/security.yaml'
    prefix: /security
```
![image](https://user-images.githubusercontent.com/38428205/38811961-488dc904-418b-11e8-8a70-1782a280bb89.png)

This is not working
-----------------
```yaml
app_security:
    resource: 'security.yaml'
    prefix: /security
```
![image](https://user-images.githubusercontent.com/38428205/38812044-7d1c46fa-418b-11e8-93bf-86ff6791c409.png)

Whar do you think ?
