### ISSUE TITLE
[MESSENGER] Service "messenger.default_sender" not found

### ISSUE THREAD

**Issue by fpondepeyre** [symfony/symfony#26962]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1.0-DEV

I wanted to test component "Messenger" like @sroze has presented to Symfony Live (I tried to reproduce exactly his amazing [demo](https://www.slideshare.net/samuelroze/symfony-messenger-queues-workers-more))  but I get this error:

```
(1/1) ServiceNotFoundException
Service "messenger.default_sender" not found: the container inside "Symfony\Component\Messenger\Asynchronous\Routing\SenderLocator" is a smaller service locator that only knows about the "default" and "messenger.sender.default" services.
```
Here the PR "https://github.com/fpondepeyre/poc-messenger" with the configuration and code. I do maybe something wrong, i do not know...

```php
#src/Controller/DefaultController.php
public function index(MessageBusInterface $bus, Request $request)
{
        $users = ['pierre', 'paulette'];
        $message = $request->query->get('message', 'Something.');

        $bus->dispatch(new SendNotification($message, $users));

        return new Response(
            '<html><body>Ok.</body></html>'
        );
}
```

```php
#src/MessageHandler/SendNotificationHandler.php
class SendNotificationHandler
{
    public function __invoke(SendNotification $message)
    {
        foreach ($message->getUsers() as $user) {
            echo "Send notification to...".$user."\n";
        }
    }
}
```

```php
#src/Message/SendNotification.php
class SendNotification
{
    /**
     * @var string
     */
    private $message;

    /**
     * @var array
     */
    private $users = [];

    /**
     * SendNotification constructor.
     * @param string $message
     * @param array $users
     */
    public function __construct(string $message, array $users = [])
    {
        $this->message = $message;
        $this->users = $users;
    }

    /**
     * @return string
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * @param string $message
     *
     * @return SendNotification
     */
    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * @return array
     */
    public function getUsers(): array
    {
        return $this->users;
    }

    /**
     * @param array $users
     *
     * @return SendNotification
     */
    public function setUsers(array $users): self
    {
        $this->users = $users;

        return $this;
    }
}
```

```yaml
#config/services.yaml
App\MessageHandler\:
    resource: '../src/MessageHandler/*'
    tags: [messenger.message_handler]
```

```yaml
#config/packages/framework.yaml
messenger:
    adapters:
        default: '%env(MESSENGER_DSN)%'
    routing:
        'App\Message\SendNotification': messenger.default_sender
```

Thank you.

--

**Comment by sroze** [comment]
@fpondepeyre the slides needs to be updated. The sender service is now `messenger.sender.default` instead of `messenger.default_sender`. Alternatively, you can just use the adapter name:
```yaml
#config/packages/framework.yaml
messenger:
    adapters:
        default: '%env(MESSENGER_DSN)%'
    routing:
        'App\Message\SendNotification': default
```
