### ISSUE TITLE
[DI] Autowiring, calls functions not called

### ISSUE THREAD

**Issue by jbdelhommeau** [symfony/symfony#26985]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.8

I have an abstract class (aka parent) : 

```yml
    TradeEasy\Document\Component\DocumentTemplate:
      abstract: true
      arguments:
        - '@templating.engine.twig'
        - '%document_client_code%'
```

This parent extend  `PfiDocumentTemplate`

With old syntax with no FCQN we can see with `bin/console debug:container` calls function `setTemplateDataFactory` is callable.

```yml
    document_template.pfi:
      class: TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate
      parent: TradeEasy\Document\Component\DocumentTemplate
      calls:
        - [setTemplateDataFactory, ['@TradeEasy\Document\Bundle\TemplateData\PfiTemplateDataFactory']]
```

```
Information for Service "document_template.pfi"
===============================================

 ---------------- ---------------------------------------------------------------- 
  Option           Value                                                           
 ---------------- ---------------------------------------------------------------- 
  Service ID       document_template.pfi                                           
  Class            TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate  
  Tags             -                                                               
  Calls            setTemplateDataFactory                                          
  Public           no                                                              
  Synthetic        no                                                              
  Lazy             no                                                              
  Shared           yes                                                             
  Abstract         no                                                              
  Autowired        no                                                              
  Autoconfigured   no                                                              
  Arguments        Service(templating.engine.twig)                                 
                   %env(CLIENT_CODE)%                                              
 ---------------- ---------------------------------------------------------------- 
```

With new syntax  FCQN we can see with `bin/console debug:container` no calls function. Why ?

```yml
    TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate:
      parent: TradeEasy\Document\Component\DocumentTemplate
      calls:
        - [setTemplateDataFactory, ['@TradeEasy\Document\Bundle\TemplateData\PfiTemplateDataFactory']]
```

```
Information for Service "TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate"
========================================================================================

 ---------------- ---------------------------------------------------------------- 
  Option           Value                                                           
 ---------------- ---------------------------------------------------------------- 
  Service ID       TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate  
  Class            TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate  
  Tags             -                                                               
  Public           no                                                              
  Synthetic        no                                                              
  Lazy             no                                                              
  Shared           yes                                                             
  Abstract         no                                                              
  Autowired        yes                                                             
  Autoconfigured   yes                                                             
  Arguments        Service(templating.engine.twig)                                 
                   %env(CLIENT_CODE)%                                              
 ---------------- ---------------------------------------------------------------- 
```

Can it be a global concern ?

```yml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $webDir : "%web_dir%"
            $documentClientCode: '%document_client_code%'

    # makes classes in src/AppBundle available to be used as services
    TradeEasy\:
        resource: '../../src/TradeEasy/*/Bundle'
```
