### ISSUE TITLE
CompilerPass and private services

### ISSUE THREAD

**Issue by fpaterno** [symfony/symfony#27022]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.6

Hello Everyone !

My problem concerns CompilerPass and tagged services.
Exactly as here : https://symfony.com/doc/3.4/service_container/tags.html).

Strange behavior occurs when CompilerPass is registered on my project.
I have configured my services as private :
```
services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Repository\RepositoryRegistry: ~

    App\Repository\ArticleRepository: ~
```

And I add my compiler pass :
```
    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        // Autoconfigure tags
        $container->registerForAutoconfiguration(RepositoryInterface::class)
            ->addTag(RepositoryCompilerPass::DEFINITION_TAG);

        $container->addCompilerPass(new RepositoryCompilerPass());
    }
```

In this configuration, from controller, container give me access to these services.
No exceptions are raised with this call : `$lastArticles = $this->get(ArticleRepository::class)`

But when I comment `addCompilerPass` method my services becomes really private ...
Is it a bug ?

Thanks for your answer !
