### ISSUE TITLE
[Asset] Missing manifest file throws an exception

### ISSUE THREAD

**Issue by Seikyo** [symfony/symfony#27033]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.8

Currently, missing manifest file when using *asset()* will throw an exception and generate a server error. In my opinion this should not be the case in production but should stay in dev.

--- 

## Detail

We are using webpack with encore for assets management and generating multiple manifest files. We happened to deploy without the building assets step on a stage server and noticed that the default behaviour for the twig asset loader if to throw an exception if the file is not found.

Here the current setup for twig and assets : 

 *config.yml* 

``` yml
assets:
    packages:
        apps:
            json_manifest_path: '%kernel.project_dir%/var/assets/apps-manifest.json'
        backend:
            json_manifest_path: '%kernel.project_dir%/var/assets/backend-manifest.json'
        frontend:
            json_manifest_path: '%kernel.project_dir%/var/assets/frontend-manifest.json'
```

And in a template, this call generated a 500 because the manifest file did not exist 

```twig
<script src="{{ asset('js/app.js', 'frontend') }}"></script>
```

I expected that the *asset()* function to behave more like *source()* with it's flag *ignore_missing*. Did I miss some configuration somewhere ? In that case sorry about the noise.

## Work around

For now i have done the following to avoid a 500 if anything happens to the build step during the deployment : 

Since we are using versioning, I made a copy of *JsonManifestVersionStrategy* class in my bundle with a second constructor argument for allowing missing manifest and replaced the default service by mine.

*services.yml*
```yml
    AppBundle\Component\Asset\VersionStrategy\JsonManifestVersionStrategy:
        abstract: true
        arguments: [$manifestPath, true]

    assets.json_manifest_version_strategy: '@AppBundle\Component\Asset\VersionStrategy\JsonManifestVersionStrategy'
```

*JsonManifestVersionStrategy.php*
```php
class JsonManifestVersionStrategy implements VersionStrategyInterface
{
    private $manifestPath;
    private $manifestData;
    private $ignoreMissing;

    /**
     * @param string $manifestPath Absolute path to the manifest file
     */
    public function __construct($manifestPath, $ignoreMissing)
    {
        $this->manifestPath = $manifestPath;
        $this->ignoreMissing = $ignoreMissing;
    }

    /**
     * With a manifest, we don't really know or care about what
     * the version is. Instead, this returns the path to the
     * versioned file.
     */
    public function getVersion($path)
    {
        return $this->applyVersion($path);
    }

    public function applyVersion($path)
    {
        return $this->getManifestPath($path) ?: $path;
    }

    private function getManifestPath($path)
    {
        if (null === $this->manifestData) {
            if (!file_exists($this->manifestPath)) {

                if ($this->ignoreMissing) {
                    $this->manifestData = [];
                    return null;
                } else {
                    throw new \RuntimeException(sprintf('Asset manifest file "%s" does not exist.', $this->manifestPath));
                }
            }

            $this->manifestData = json_decode(file_get_contents($this->manifestPath), true);
            if (0 < json_last_error()) {
                throw new \RuntimeException(sprintf('Error parsing JSON from asset manifest file "%s" - %s', $this->manifestPath, json_last_error_msg()));
            }
        }

        return isset($this->manifestData[$path]) ? $this->manifestData[$path] : null;
    }
}
```
