### ISSUE TITLE
[DI] pass service name to configurator

### ISSUE THREAD

**Issue by SpacePossum** [symfony/symfony#27041]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.y.z

I've a setup like this:
```yml
#services.yml
    channel.local:
        public: true
        class: App\Service\X\Channel
        configurator: 'App\Service\X\ChannelConfigurator:configure'

    channel.remote:
        public: true
        class: App\Service\X\Channel
        configurator: 'App\Service\X\ChannelConfigurator:configure'
```

Which results in a call to something like `->configure($instance);` where the instance is the service.
This makes it not possible for the Configurator to known which service it is configuring, only of which type. The workarounds could be to inject an identifier in the service so the Configurator can check it, or call different methods on the Configurator (`configureRemote()`, `configureLocal()` etc.).

However I would like to make a RFC request to pass the service name to the Configurator as well.
So the new call would be; `->configure($instance, $serviceName)` 

Not sure if this is possible already, I'm in the process of porting from Silex to SF so a lot of new things ;)
