### ISSUE TITLE
Symfony 3.4.7 no homepage defined and JMS I18N Routing prefix

### ISSUE THREAD

**Issue by odie2** [symfony/symfony#27057]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.4.7

I just updated Symfony from 3.4.6 and now can't get default locale prefix redirect, while it was working like a charm before. It displays Welcome Page as changed in #26041, while it should autoprefix with default locale like before.

composer.json

`"jms/i18n-routing-bundle": "2.0.x-dev",`

routing.yml

```
main_index:
    path:     /
    defaults: { _controller: AppBundle:Main:index }
    methods:  [GET]
```

config.yml

```
parameters:
    locale: pl
    app.languagesSlugs: [ en, pl ]

framework:
    default_locale:  "%locale%"

# JMS I18N Routing
jms_i18n_routing:
    default_locale: pl
    locales: "%app.languagesSlugs%"
    strategy: prefix
```

`http://localhost:8000/` - Welcome Page (before redirect to `http://localhost:8000/pl/`)

My question is: should I wait to fix by JMS I18N Routing bundle or by Symfony or is there any workaround to force default language redirect?
