### ISSUE TITLE
Using services in a bundle configuration

### ISSUE THREAD

**Issue by emr** [symfony/symfony#27078]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.4

—

```yml
easy_admin:
    entities:
        MyEntity:
            class: "@my_config_service.getMyEntityClass()"
            ...
```

Does not compiled expressions in bundle configuration.

I tried to make php configuration:
```php
$container->loadFromExtension('easy_admin', [
    'entities' => [
        'MyEntity' => [
            'class' => $container->get('my_config_service')->getMyEntityClass()
        ]
    ]
]);
```
I take this error: **`You have requested a non-existent service "my_config_service". `**

—

How to inject my service in a bundle configuration?
Is there an alternative way?

(btw, sorry for my bad english)
