### ISSUE TITLE
[Messenger] can no longer use wildcard (*) in routing

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#27081]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

#27032 broke the ability to use `*` in your routing.

The configuration:

```yaml
framework:
    messenger:
        routing:
            '*': amqp
```

Gives the following error:

`Messenger routing configuration contains a mistake: message "*" does not exist. It needs to match an existing class or interface.`
