### ISSUE TITLE
multiple entity managers are all the same

### ISSUE THREAD

**Issue by jtleon** [symfony/symfony#27125]
| Q                | A
| ---------------- | -----
| Bug report?      | vague
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.8

I have two databases. There are same in structure. So they have the same entity. 
I follow the steps [Multiple Entity Managers](http://symfony.com/doc/current/doctrine/multiple_entity_managers.html)

but not expected

### doctrine config
```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                url: '%env(resolve:DATABASE_URL)%'
            abroad:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                url: '%env(resolve:DATABASE_ABROAD)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    DefaultApp:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: App\Entity
                        alias: DefaultApp
                    DefaultBsw:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Bsw/Entity'
                        prefix: App\Bsw\Entity
                        alias: DefaultBsw
            abroad:
                connection: abroad
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AbroadApp:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: App\Entity
                        alias: AbroadApp
                    AbroadBsw:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Bsw/Entity'
                        prefix: App\Bsw\Entity
                        alias: AbroadBsw
```

### controller
```php
class TestController extends MasterController
{
    /**
     * For test
     *
     * @Route("/users", name="app_users")
     * @AccessControl()
     */
    public function users()
    {
        $emA = $this->getDoctrine()->getManager('default');
        $emB = $this->getDoctrine()->getManager('abroad');

        dump($emA, $emB);

        $listA = $emA->getRepository(AdminInfo::class)->find(1);
        $listB = $emB->getRepository(AdminInfo::class)->find(1);

        dump($listA, $listB);
        die;
    }
}
```

#### got diff entity
![a](https://user-images.githubusercontent.com/9757844/39524348-42f9d268-4e4b-11e8-920f-41f9661eef5c.png)

#### but got same result
![b](https://user-images.githubusercontent.com/9757844/39524345-3e5b8a26-4e4b-11e8-924b-43b9dd210a6b.png)

what wrong with my config?
