### ISSUE TITLE
[Security] JSON login is not working as expected

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27124]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.8

This was originally reported by @Guikingone in https://github.com/symfony/symfony-docs/pull/9611.

-----

With a code like this, the Security Layer should intercept the request and return a dedicated response along with the credentials:

![Code](https://image.noelshack.com/fichiers/2018/16/5/1524225767-capture-d-ecran-2018-04-20-a-13-59-29.png)

But with this response, I see the following exception:

![insomnia](https://image.noelshack.com/fichiers/2018/16/5/1524225770-capture-d-ecran-2018-04-20-a-13-59-35.png)

If I add `return new JsonResponse();` to the method, the exception is gone.

**Comment by stof** [comment]
Well, without the firewall config, it is hard to debug it

**Comment by Guikingone** [comment]
@stof Yes, sorry, here's the `security.yaml` file : 

```yaml
security:
    encoders:
        App\Domain\Models\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Domain\Models\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: db_provider
            logout_on_user_change: true
            form_login:
                login_path: web_login
                check_path: web_login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: index
            json_login:
                check_path: api_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```

Lexik has been added for JWT generation purpose.

**Comment by Oliboy50** [comment]
I don't know if it's a bug or not, but I don't have to make my own controller to make it works using LexikJWT.

I think that the only thing you have to do is to define a route such as:
```yaml
api_login:
  path: /api/login
```

and it should work as expected using `json_login`

if it doesn't, then maybe there's an issue with having both `form_login` and `json_login` on the same firewall 🤷‍♂️

**Comment by chalasr** [comment]
The first problem is that `access_control` is missing in your config. If you look at your logs, you'll see `Populated the TokenStorage with an anonymous Token.` because you're allowing anonymous for the whole firewall. 
Secondly, the `LoginAction` is not necessary, you should remove it and configure your `api_login` without defining a controller for it, it does not need a controller at all, that's caught by the security layer.
Then, you may face some issues with both `form_login` and `json_login`, but I'm not sure.

Better split your firewall into multiple ones, one for your api and one for your web app. 
You should find some inspiration here https://github.com/chalasr/lexik-jwt-authentication-sandbox/blob/flex/config/packages/security.yaml.
 
I suggest to close here, it's a security misconfiguration.
We should keep a documentation issue opened about the `json_login` though, it is outdated.

**Comment by agarb7** [comment]
I have same issue. (Symfony version: 4.0.9)
But route without controller as suggested above is not available.
route.yaml:
```yaml
login:
    path: /b/login
```
security.yaml
```yaml
security:
    encoders:
        App\Entity\Person\User:
            algorithm: bcrypt
    providers:
        database_users:
            entity:
                class: App\Entity\Person\User
    firewalls:
        main:
            pattern: ^/b/
            anonymous: ~
            json_login:
                check_path: login
    access_control:
        - { path: ^/b/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

On
`curl -X POST -H "Content-Type: application/json" http://site.test/b/login -d '{"username":"user","password":"pass"}'`
we get an exception
`Unable to find the controller for path &quot;/b/login&quot;. The route is wrongly configured. (404 Not Found)`
