### ISSUE TITLE
Symfony Doctrine config custom types not taken into account after cache is built on console

### ISSUE THREAD

**Issue by DJPOC** [symfony/symfony#27260]
**Symfony version(s) affected**: 4.0.9 (may happen in other ones, haven't tested)

**Description**  
In the console, after the cache was generated by a first run of some command (in a dev environment) the custom types defined in config/packages/doctrine.yml are no longer taken into account.

**How to reproduce**  
Create a custom type in src/DBAL/CustomType.php (let's use this as an example) :
```php
# src/DBAL/CustomType.php
<?php
namespace App\DBAL;

use Doctrine\DBAL\Types\Type;
use Doctrine\DBAL\Platforms\AbstractPlatform;

class CustomType extends Type
{
    protected $name = 'customtype';

    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return "VARCHAR(255) COMMENT '(DC2Type:".$this->name.")'";
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return $value;
    }

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {   
        
        return $value;
    }

    public function getName()
    {
        return $this->name;
    }
}
```
Register this type in Doctrine config config/packages/doctrine.yaml (I think you know how to do it but just in case) :
```yaml
# config/packages/doctrine.yaml
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        server_version: '3.15'
        charset: utf8mb4

        url: '%env(resolve:DATABASE_URL)%'
        types:
            customtype: 'App\DBAL\CustomType'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```
And finally create a command in src/Command (since it only happens in the console, the web part works as expected) :
```php
# src/Command/InfoDBALTypesCommand.php
<?php
namespace App\Command;
class InfoDBALTypesCommand extends \Symfony\Component\Console\Command\Command
{
    protected function configure()
    {
        $this
            ->setName('app:dbal:typesinfo')

            ->setDescription('Prints Doctrine loaded types')

            ->setHelp('This command prints the currently loaded types for Doctrine DBAL');
    }

    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output)
    {
        $output->writeln(var_dump(\Doctrine\DBAL\Types\Type::getTypesMap()));
    }
}
```
Now clear the cache folder by deleting all the files in var/cache/dev, open a terminal and run `php bin/console app:dbal:typesinfo` a first time then a second one and you should see the custom type appear the first time but not the second time: because the cache has been built.
**Possible Solution**  
All I know is that this issue only appears when the cache is built.

**Additional context**  
Running on Debian 9.4 with PHP 7.2.5-1+0\~20180505045740.21+stretch\~1.gbpca2fa6 (packages from deb.sury.org) on WSL (Windows Subsytem for Linux)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by DJPOC** [comment]
Here is the exemple application: https://github.com/DJPOC/SymfonyBugReproducer-27260
To reproduce: clone, composer install, run `php bin/console app:dbal:typesinfo` 2 times, the second one will print only the Doctrine included types, without the custom one

**Comment by xabbuh** [comment]
I am not convinced that the way you are using the `Type` class is actually the way it is supposed to be. I mean how should the static type map in that example actually be populated?

**Comment by DJPOC** [comment]
It follows the Doctrine documentation on custom types definitions I think... Does it matter in the registering process of the custom type ?

**Comment by xabbuh** [comment]
Can you point me to the part of the documentation that you were following? Was it possibly the part about using Doctrine standalone where you would be responsible to register the types manually?

**Comment by ogizanagi** [comment]
I think you have to create a connection in order to get the types from `Types::getTypesMap`. Otherwise types aren't initialized.
Or you can probably use the [`doctrine.dbal.connection_factory.types`](https://github.com/doctrine/DoctrineBundle/blob/703fad32e4c8cbe609caf45a71a1d4266c830f0f/Resources/config/dbal.xml#L46) parameter instead.

**Comment by DJPOC** [comment]
I was following this : https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/types.html#custom-mapping-types to write the code for the custom type class, but Symfony docs recommend this way for registering custom Doctrine DBAL types: https://symfony.com/doc/current/doctrine/dbal.html#registering-custom-mapping-types

**Comment by jvasseur** [comment]
Types declared using the doctrine bundle config are lazily, meaning they will be added to the TypeMap only on the first use of the connection. If you want the type to be always available you should call `Type::addType` yourself on boot.

**Comment by stof** [comment]
The registration is done lazily. So if you don't instantiate the DBAL connection service, the custom type is not registered.
This is done on purpose, to avoid paying a cost in case your request does not use DBAL at all. We haven't considered the usage of the Type system without using DBAL as a supported use case for the bundle.

**Comment by DJPOC** [comment]
Okay, but then it's impossible to create the database schema because Doctrine says the types doesn't exist when performing a `php bin/console doctrine:schema:update` (or even `php bin/console doctrine:schema:validate` after the cache has been built. Because my original problem was that I had an Entity using a custom type on one of its properties and because of this bug I can't build my database schema

**Comment by xabbuh** [comment]
Then your problem is probably something else. Can you update the example to let it reproduce the actual error you experienced?

**Comment by DJPOC** [comment]
Okay the problem somehow disappeared so I'm closing the issue, thanks for your time...

**Comment by jhonatanTeixeira** [comment]
im experiencing this very same issue right now, i have the following scenario:

symfony 4.2
php 7.2

doctrine.yaml
```yml
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            PerfilEnum: App\Entity\Enum\PerfilEnum
```
entity:
```php

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsuarioRepository")
 */
class Usuario implements UserInterface
{
    .......

    /**
     * @ORM\Column(type="PerfilEnum")
     *
     * @var PerfilEnum
     */
    private $perfil;
   
    ........
}
```

The type:

```php
class PerfilEnum extends IntegerType
{
    .........

    public function getName()
    {
        return 'PerfilEnum';
    }
}
```

when i run a command that tries to save a Usuario entity passing a integer value to the setPerfil i get this error

```
 Unknown column type "PerfilEnum" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL
  \Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If
   this error occurs during database introspection then you might have forgotten to register all database types for a
   Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMapp
  edDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping informa
  tion.
```

however if i delete the cache first with a rm -rf var/cache, it runs just fine
