### ISSUE TITLE
 autoconfigure not working in custom bundle

### ISSUE THREAD

**Issue by videni** [symfony/symfony#27324]
I register services with the following ways in a custom bundle AcmeTestBundle, but none of the services registered.  but it works int  application level config. 

Resources/config/services.yaml
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
   Acme\Bundle\TestBundle\:
        resource: '../../{Repository, DataFixtures, Controller, Command}'
```
the above file is loaded
```
final class AcmeTestExtension extends Extension
{
    /**
     * {@inheritdoc}
     */
    public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);

        $loader = new YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('services.yaml');
    }
}
```
