### ISSUE TITLE
[Serializer] Set default normalizer for serializer service

### ISSUE THREAD

**Issue by florianajir** [symfony/symfony#27425]
**Symfony version(s) affected**: 4.0.9

**Description**  

The [doc about serializer](http://symfony.com/doc/current/serializer.html) say 

> Custom normalizers and/or encoders can also be loaded by tagging them as serializer.normalizer and serializer.encoder. It's also possible to set the priority of the tag in order to decide the matching order.

So I looked at the [service tag documentation](http://symfony.com/doc/current/reference/dic_tags.html#reference-dic-tags-serializer-normalizer) which say 

> The priorities of the default normalizers can be found in the [registerSerializerConfiguration()](https://api.symfony.com/4.0/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.html#method_registerSerializerConfiguration) method.

The doc link is outdated so there is no documentation about how to priorize a normalizer for serializer as a service.

Finally the only part explaining how to declare normalizer service is

```
#    property_normalizer:
#        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
#        public: false
#        tags: [serializer.normalizer]
```

But this way, the serializer name_converter config part is overwritten.. 
```
config:
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
```

**Comment by florianajir** [comment]
I found a solution to configure serializer with normalizer alongside nameConverter, for this usage the serializer configuration is useless, it's only about service configuration:

```
services:
    property_normalizer:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        public: false
        tags: [serializer.normalizer]
        arguments:
            $nameConverter: '@serializer.name_converter.camel_case_to_snake_case'
```
