### ISSUE TITLE
[BUG][4.1] TwigBundle : Class "twig.controller.exception" does not exist

### ISSUE THREAD

**Issue by macintoshplus** [symfony/symfony#27438]
**Symfony version(s) affected**: 4.1.0

**Description**  
After upgrade to Symfony 4.1.0, this error `Class "twig.controller.exception" does not exist.` is displayed when an exception is not catched by the user code.

**How to reproduce**  

```php
<?php

namespace App\Controller;

class FailController
{
    public function __invoke()
    {
        throw new \Exception("Error Processing Request", 1);
    }
}
```

**Possible Solution**  

When I add this configuration, the exception handler work fine:
```yaml
# config/packages/twig.yaml
twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # I have add this line:
    exception_controller: Symfony\Bundle\TwigBundle\Controller\ExceptionController::showAction
```
And this service configuration
```yaml
# config/services.yaml
services:

    Symfony\Bundle\TwigBundle\Controller\ExceptionController:
        alias: twig.controller.exception
        public: true
```

**Additional context**  

The full error screenshot:
![image](https://user-images.githubusercontent.com/814683/40770597-751998d8-64bb-11e8-827c-6209a0964e2d.png)
