### ISSUE TITLE
CircularReferenceException when serializing AccessDeniedHttpException using PropertyNormalizer

### ISSUE THREAD

**Issue by florianajir** [symfony/symfony#27446]
**Symfony version(s) affected**: 4.1.0

**Description**  

Error 500 when using PropertyNormalizer and throw AccessDeniedHttpException or BadRequestHttpException to json format

```
CircularReferenceException A circular reference has been detected when serializing the object of class "Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException"
```

**How to reproduce**  

**services.yaml**

```
services:
    property_normalizer:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        public: false
        tags: [serializer.normalizer]
        arguments:
            $nameConverter: '@serializer.name_converter.camel_case_to_snake_case'
```

**Controller.php**

```
         $this->denyAccessUnlessGranted(
            'ROLE_IMPOSSIBLE',
            null,
            'IMPOSSIBLE ROLE REQUIRED')
        );
```

**Additional context**  

Symfony rest API with json default response format
