### ISSUE TITLE
[4.1] Routes duplicates using "name_prefix" config option

### ISSUE THREAD

**Issue by StevioStudio** [symfony/symfony#27465]
**Symfony version(s) affected**: 4.1.0

**Description**  
When using the new `name_prefix` option, routes will be generate both with prefix and without prefix.

**How to reproduce**  
In `config/routes.yaml` add a prefix for a controller folder
```
admin:
    resource: ../src/Controller
    type: annotation
    name_prefix: admin_
```
And, by using `debug:router` command, you will see that a router named `dashboard` will be created 2 times.
```
------------------------------------------------------ -------- -------- ------ -----------------------------------------
  Name                                                   Method   Scheme   Host   Path
 ------------------------------------------------------ -------- -------- ------ -----------------------------------------
  dashboard                                              ANY      ANY      ANY    /
  admin_dashboard_index                                  ANY      ANY      ANY    /
```

**Comment by tony-tran** [comment]
Hi,

Maybe you can add your name_prefix only in `config/routes/annotations.yaml` file ? WDYT ?

**Comment by StevioStudio** [comment]
In that case, why am I able to use this (wrong) way and obtain this weird result?
And also, is there another way to add a name_prefix to all the controllers in a folder?

**Comment by yceruto** [comment]
> In that case, why am I able to use this (wrong) way and obtain this weird result?

Hi @StevioStudio, because you've imported this resource twice, one with name_prefix and another one without it.

> And also, is there another way to add a name_prefix to all the controllers in a folder?

Likely in `config/routes/annotations.yaml` only to avoid this issue.

**Comment by StevioStudio** [comment]
Hi @yceruto, so I guess FrameworkBundle is automatically importing all `@Route` annotations from Controller directory (because I didn't configure that). Is there a way to turn this off? In that way I will not import routes 2 times

**Comment by yceruto** [comment]
Have not installed the annotation pack? Do not you have another route configuration somewhere else?

**Comment by StevioStudio** [comment]
@yceruto @tony-tran 
Thanks for the support. I'm new to symfony 4 (I was using 3.2) and I believed I didn't have `config/routes/annotations.yaml` file. I was wrong. 
I solve the problem and this is not a bug.
The bug was me :)

**Comment by maximsamoilov** [comment]
I have one question. Seems symfony 4 load all routes from files which located in config/routes folder?

```
//config/routes.yaml
feedback:
    resource: ./routes/feedback.yaml
    prefix: /feedback
    name_prefix: feedback_

//config/routes/feedback.yaml
index:
    path: /
    controller: App\Controller\FeedbackController::index
    methods: GET

new:
    path: /new
    controller: App\Controller\FeedbackController::new
    methods: GET|POST

edit:
    path: /{id}/edit
    controller: App\Controller\FeedbackController::edit
    methods: GET|POST

delete:
    path: /{id}/delete
    controller: App\Controller\FeedbackController::delete
    methods: POST
```
```
index                      GET        ANY      ANY    /
new                        GET|POST   ANY      ANY    /new
edit                       GET|POST   ANY      ANY    /{id}/edit
delete                     POST       ANY      ANY    /{id}/delete
feedback_index             GET        ANY      ANY    /feedback/
feedback_new               GET|POST   ANY      ANY    /feedback/new
feedback_edit              GET|POST   ANY      ANY    /feedback/{id}/edit
feedback_delete            POST       ANY      ANY    /feedback/{id}/delete
```
