### ISSUE TITLE
Environment variables "bool:FRAMEWORK_PROFILE" are never used. Please, check your container's configuration. 

### ISSUE THREAD

**Issue by lvillarino** [symfony/symfony#27526]
**Symfony version(s) affected**: 4.1

**Description**  
I want to set an external BOOLEAN Parameter in the Service Container and I'm getting and error

```
Environment variables "bool:FRAMEWORK_PROFILE" are never used. Please, check your container's configuration.   
```

**How to reproduce**  
Update the web_profiler.yaml
```
parameters:
  env(FRAMEWORK_PROFILE): "true"

web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler:
      enabled: '%env(bool:FRAMEWORK_PROFILE)%'
      only_exceptions: false
```

Run 'bin/console cache:clear'

```
Environment variables "bool:FRAMEWORK_PROFILE" are never used. Please, chec  
  k your container's configuration. 
```
