### ISSUE TITLE
AbstractObjectNormalizer ignores the property types of discriminated classes

### ISSUE THREAD

**Issue by timostamm** [symfony/symfony#27607]
**Symfony version(s) affected**: 4.0.1

**Description**  

When deserializing a discriminated (abstract) type, the AbstractObjectNormalizer correctly instantiates the mapped class. 

It also correctly deserializes the properties declared on the abstract type. But for properties declared on the mapped class, it ignores the property type. 

Example:

```php
/**
 * @DiscriminatorMap(
 *   typeProperty="discr",
 *   mapping={ "concrete" = ConcreteSubject::class }
 * )
 */
abstract class AbstractSubject {
    public function setA(Value $v) … // Value is correctly deserialized
}

class ConcreteSubject extends AbstractSubject {
    public function setB(Value $v) … // Value is NOT denormalized, serializer tries to set an array
}
```

**How to reproduce**  

https://github.com/timostamm/symfony-serializer-discriminator-repro/blob/master/tests/DeserializerDiscriminatorTest.php

- testDeserializePropertyOnAbstract is okay
- testDeserializePropertyOnConcrete fails with `InvalidArgumentException: Expected argument of type "App\Tests\DummySubject", "array" given.`

**Possible Solution**  

`denormalize()` currently calls `validateAndDenormalize()` with the unresolved abstract class.
`validateAndDenormalize()` then immediately exits because it cannot detect the type of the property.

A possible solution would be to pass the resolved classname to `validateAndDenormalize()` instead of the abstract classname. 

See [Patched_AbstractObjectNormalizer.php](https://github.com/timostamm/symfony-serializer-discriminator-repro/blob/524415f0dc5bcfd1e9864f728d6effe64e5fbf29/tests/Patched_AbstractObjectNormalizer.php)

Maybe the normalizer should just resolve the class at the start of denormalization. This means that `instantiateObject()` would already receive the resolved class and the override of AbstractNormalizer::intantiateObject() could be dropped.

See [second commit](https://github.com/timostamm/symfony-serializer-discriminator-repro/commit/ddbb05c910152363ae003c3fff7b0b2a936c2fbc#diff-c07412237c1200cb5c606b51dba278df)

**Additional context**

**Comment by voodoo-dn** [comment]
Hi. The same problem. On deserialization only abstract class properties filled by desirializer, concrete properties of objects are empty.
I use Symfony 4.1 + API Platform. Pass descriminator and some properties by api and receive not fully constructed concrete object. 

```
App\Domain\Entity\Prize\AbstractPrize:
    attributes:
        id:
            groups: ['admin_read']
        place:
            groups: ['admin_read', 'admin_write']
    discriminator_map:
        type_property: 'discriminator'
        mapping:
            money: 'App\Domain\Entity\Prize\Money\MoneyPrize'
            points: 'App\Domain\Entity\Prize\PointPrize'

App\Domain\Entity\Prize\Money\MoneyPrize:
    attributes:
        wager:
            groups: ['admin_read', 'admin_write']
        amounts:
            groups: ['admin_read', 'admin_write']

App\Domain\Entity\Prize\Money\Amount:
    attributes:
        amount:
            groups: ['admin_read', 'admin_write']
        currency:
            groups: ['admin_read', 'admin_write']

App\Domain\Entity\Prize\PointPrize:
    attributes:
        count:
            groups: ['admin_read', 'admin_write']
```

**Comment by timostamm** [comment]
@voodoo-dn could you test if my patch fixes the issue for you?

Copy [Patched_ObjectNormalizer.php](https://github.com/timostamm/symfony-serializer-discriminator-repro/blob/master/tests/Patched_ObjectNormalizer.php) and [Patched_AbstractObjectNormalizer.php](https://github.com/timostamm/symfony-serializer-discriminator-repro/blob/master/tests/Patched_AbstractObjectNormalizer.php) into <project>/src/Tests/ and add this to your service.yml:
```yaml
# patch AbstractObjectNormalizer, see https://github.com/symfony/symfony/issues/27607
App\Tests\Patched_ObjectNormalizer:
  arguments:
    - '@serializer.mapping.class_metadata_factory'
    - ~
    - '@serializer.property_accessor'
    - '@property_info'
    - '@serializer.mapping.class_discriminator_resolver'
  tags:
    - {name: serializer.normalizer, priority: -999}
```
