### ISSUE TITLE
Proposals to make the anonymous security config simpler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27610]
**Description**  
After having delivered some introductory Symfony workshops lately, I'd like to propose some changes to make anonymous-related security config easier to explain/understand.

**Example**  
My first petition is a DX-related change. The `IS_AUTHENTICATED_ANONYMOUSLY` "role" is always strange for newcomers. It's not a role, but we use it in the `roles` option ... and its name is too long and easy to mistype:

**Before**:

```yaml
security:
    access_control:
        - { path: "^/something/login", roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

**After**:

```yaml
security:
    access_control:
        - { path: "^/something/login", anonymous: true }
```

By the way, the Spring security system we took inspiration from, use allow to use `ROLE_ANONYMOUS` in addition to `IS_AUTHENTICATED_ANONYMOUSLY`. So maybe this can be enough:

```yaml
security:
    access_control:
        - { path: "^/something/login", roles: ROLE_ANONYMOUS }
```

-----

My second petition is about the `anonymous` setting in the firewall. It's always confusing to understand ... and it's not documented in the [Symfony Security Config Reference](https://symfony.com/doc/current/reference/configuration/security.html).

As soon as some `access_control` URL allows to access anonymous users, you must set it to `anonymous: ~`. What's the point of not adding it? Users won't be able to access to the login form and nothing will work. Can we remove this option or make it smarter and auto-detect when you need to allow anonymous users for some URLs?

Thanks!
