### ISSUE TITLE
[Security] Ability to set SameSite attribute for session and remember me cookie

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#27631]
**Description**  
It would be useful if we could expose SameSite attribute for session and remember me cookie via yaml config.

**Example**  
```yaml
framework:
    session:
        name: NameOfTheCookie
        cookie_samesite: lax
```

```yaml
security:
    firewalls:
        remember_me:
            name: NameOfTheCookie
            samesite: lax
```

Currently it's extremely painful to override it (unless I'm missing something?).

**Comment by umpirsky** [comment]
@javiereguiluz I'm interested into contributing this. Just need feedback to see if we are on the right track.

**Comment by javiereguiluz** [comment]
I think it would make sense to add this option, although I'd prefer if we use `cookie_samesite` as the name of the two options, instead of `cookie_samesite` and `samesite`.

But let's ask first to people with lots of experience in the Security component, such as @iltar and @chalasr. Thanks!

**Comment by stof** [comment]
now that we support samesite cookies in HttpFoundation, it indeed makes sense to support them here.

**Comment by umpirsky** [comment]
@javiereguiluz See https://symfony.com/doc/current/reference/configuration/security.html

```yaml
remember_me:
                token_provider: name
                secret: "%secret%"
                name: NameOfTheCookie
                lifetime: 3600 # in seconds
                path: /foo
                domain: somedomain.foo
                secure: false
                httponly: true
                always_remember_me: false
                remember_me_parameter: _remember_me
```

`cookie_` prefix there would lead to naming inconsistency. A bigger inconsistency then the one I proposed in the issue description.
