### ISSUE TITLE
Serializer not fill properties on class which extended from abstract class.

### ISSUE THREAD

**Issue by voodoo-dn** [symfony/symfony#27641]
**Symfony version(s) affected**: v4.1.0

**Description**  
Serializer on deserialization fill only properties on abstract class, not on concrete class.
I have AbstractPrizeClass which extended by MoneyPrize and PointPrize.

```yaml
App\Domain\Entity\Prize\AbstractPrize:
    attributes:
        id:
            groups: ['admin_read']
        place:
            groups: ['admin_read', 'admin_write']
    discriminator_map:
        type_property: 'discriminator'
        mapping:
            money: 'App\Domain\Entity\Prize\Money\MoneyPrize'
            points: 'App\Domain\Entity\Prize\PointPrize'

App\Domain\Entity\Prize\Money\MoneyPrize:
    attributes:
        wager:
            groups: ['admin_read', 'admin_write']
        amounts:
            groups: ['frontapi', 'admin_read', 'admin_write']

App\Domain\Entity\Prize\Money\Amount:
    attributes:
        amount:
            groups: ['frontapi', 'admin_read', 'admin_write']
        currency:
            groups: ['frontapi', 'admin_read', 'admin_write']

App\Domain\Entity\Prize\PointPrize:
    attributes:
        count:
            groups: ['frontapi', 'admin_read', 'admin_write']
```
AbstractPrize have `place` property. MoneyPrize have `amounts`, etc. properties. PointPrize have `count` property.

If I try desirialize next json: {"discriminator": "points", "count": 1000 }, serializer return PointPrize only with `place` property filled, other properties are null.

**How to reproduce**  

```yaml
App\A:
    attributes:
        a:
            groups: ['test']
    discriminator_map:
        type_property: 'discriminator'
        mapping:
            b: 'App\B'

App\B:
    attributes:
        b:
            groups: ['test']
```

```php
abstract class A { private $a; public getA() { return $a; } public setA($a) { $this->a = $a; }}

class B extends A { private $b; public getB() { return $b; } public setB($b) { $this->b = $b; }}

$b = $container->get('serializer')->deserialize('{"discriminator": "b", "a": 1000, "b": 2000 }', App\A::class, 'json');

$b->getA() === 1000
$b->getB() === null
```
Sorry for my english =|

**Comment by javiereguiluz** [comment]
@voodoo-dn don't apologize for your English. Your issue was perfectly clear and it contained lot of useful information 👍. Also, it's cool that you picked the Symfony repository to create your first issue on GitHub!

Now let's wait for some Serializer expert to look into it and they'll ask for more information if needed. Thanks!

**Comment by voodoo-dn** [comment]
This problem only when I'm using Doctrine Class Table Inheritance.

AbstractObjectNormalizer::denormalize(), line 239

$allowedAttributes always return properties which contains only in Abstract class(in example above its property A). And after constructing concrete object(line 244), will be cycle by $normalizedData array. All data except "a" property will be ignored by line 251. After that method denormalize return half filled object.

```
namespace App\Domain\Entity;

/**
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *     "b" = "App\Domain\Entity\B"
 * })
 */
abstract class A {
    //some doctrine mapping
    private $a;
    public getA() { return $a; }
    public setA($a) { $this->a = $a; }
}
```

```
namespace App\Domain\Entity;

class B extends A {
    //some doctrine mapping
    private $b;
    public getB() { return $b; }
    public setB($b) { $this->b = $b; }
}
```

```
App\Domain\Entity\A:
    attributes:
        a:
            groups: ['test']
    discriminator_map:
        type_property: 'type'
        mapping:
            b: 'App\Domain\Entity\B'

App\Domain\Entity\B:
    attributes:
        b:
            groups: ['test']
```

```
$container->get('serializer')->deserialize('{"type": "b", "a": 1000, "b": 2000 }', App\Entity\A::class, 'json', ['groups' => ['test']]);

Will return $b->getA() === 1000, $b->getB() === null
```

No more information I cant provide for you. I'm stuck. Few days of debugging and nothing finded to fix this problem.

Thanks.
