### ISSUE TITLE
FindBy ManyToMany

### ISSUE THREAD

**Issue by asleeguilez** [symfony/symfony#27743]
Hello
According to this link [https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-objects.html](url) in two entities related to ManyToMany, a search can be made by referring to the second entity.
This is my example:

```yaml
UsuariosBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: UsuariosBundle\Repository\UsersRepository
    manyToMany:
        espec:
            targetEntity: UsuariosBundle\Entity\Especialidad
            inversedBy: users
            joinTable:
                name: fos_user_espec
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    espc_id:
                        referencedColumnName: id
        grupos:
            targetEntity: UsuariosBundle\Entity\Grupo
            joinTable:
                name: fos_user_grupo
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    oneToMany:
        soli:
            targetEntity: SolicitudeBundle\Entity\Solicitudes
            mappedBy: user_creador
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50
        last_name:
            type: string
            length: 100
        foto:
            type: string
            length: 100
            nullable: TRUE
    lifecycleCallbacks: {  }
```

```
UsuariosBundle\Entity\Grupo:
    type: entity
    table: null
    repositoryClass: UsuariosBundle\Repository\RolesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
    fields:
        name:
            type: string
            length: 50
```

```
$grupo = $this->getDoctrine()
        ->getRepository(Users::class)
        ->findByGrupos(1);
```

error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fos_user_grupo.group_id' in 'where clause'
```

Thanks!
