### ISSUE TITLE
The default_entity_manager setting in packages\doctrine.yml is disregarded in prod

### ISSUE THREAD

**Issue by pluk77** [symfony/symfony#27769]
**Symfony version(s) affected**: 4.0.3

**Description**  
The default_entity_manager setting in doctrine.yml is disregarded if an environmental specific doctrine.yml file exists

**How to reproduce**  
- Add two entity_managers with two unique names (not default, eg man1 and man2) in config\packages\doctrine.yml
- Set default_entity_manager:man1
- In the DEV environment, there will be two entity managers created in cache, called man1 and man2 and man1 is the default.
- The application works as expected.
- In PROD environment, a third entity manager, called default, will be created and this empty one is now the default.
- The application fails with "The class 'xxxxx' was not found in the chain configured namespaces
- Add default_entity_manager:man1 to doctrine.yml in config\packages\prod\doctrine.yml
- In PROD environment, there will now only be two entity managers man1 and man2, and man1 is the default.

**Possible Solution**  
- Either document that the default entity manager setting is ignored if there is an environment specific doctrine.yml file, or ensure it it not disregarded.
- Document that there always has to be one entity manager with the name 'default'

**Additional context**  
DoctrineBundle\DependencyInjection\Configuration->addOrmSection

**Comment by iltar** [comment]
Do you have a reproducer for this issue?

**Comment by stof** [comment]
what id your prod-specific doctrine config ? could you have some entity manager configuration set there for a different entity manager than the one you want ?

**Comment by xgrn** [comment]
@stof I have a similar issue (the one @pluk77 referenced). My prod config sets cache configuration. Entity manages are configured for production separately too but as the application is multidomain I have 4 different files configuring entity managers. One of them is selected on kernel boot depending on the request.

The issue is each configuration file is normalised and than merged. Normalisation adds an empty 'default' manager if the configuration has an 'orm' section without 'entity_managers' or 'default_entity_manager' sections. After that this empty manager merged into the other configurations.

I could move the production cache configuration to the files I configure my entity managers. But I need to copy them 4 times which is weird.

**Comment by pluk77** [comment]
The following setup works in DEV, but gives errors in PROD as a third entity manager is created, named default.

config/packages/doctrine.yml

```
orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: main
        entity_managers:
            main:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: prehmis_main
                mappings:
                    entity_main:
                        mapping: true
                        type: annotation
                        dir: "%kernel.root_dir%/Entity/Main"
                        prefix: App\Entity\Main
                        alias: EntityMain

```

config/packages/prod/doctrine.yml

```
doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.result_cache_provider
```

**Comment by xgrn** [comment]
@pluk77 You need to name your entity manager in the production config. Try this:

```yaml
config/packages/prod/doctrine.yml

doctrine:
    orm:
        entity_managers:
            main:
                metadata_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                result_cache_driver:
                    type: service
                    id: doctrine.result_cache_provider
```

This won't create the 'default' manager and will be merged correctly. See the closing comment in my issue you've referenced above for details.

And yes: you have to copy the cache configuration for each manager you have.

```yaml
config/packages/prod/doctrine.yml

doctrine:
    orm:
        entity_managers:
            main:
                metadata_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                result_cache_driver:
                    type: service
                    id: doctrine.result_cache_provider
            
            secondary:
                metadata_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                result_cache_driver:
                    type: service
                    id: doctrine.result_cache_provider
```

I don't know if there's a way to define some global config being applied to all the defined entity managers. It'd be convenient (e.g. I have copy-pasted lists of filters and functions 4 times and more to go).
