### ISSUE TITLE
[Cache] Redis Adapter: Default TTL not configurable

### ISSUE THREAD

**Issue by Majkl578** [symfony/symfony#27833]
**Description**  
There doesn't seem to be any easy way to configure default TTL for the redis adapter, therefore all entries (especially those in `system` cache) have `0` TTL.
This makes it hard to use in incremental deployment scenarios where cache key is seeded with deployment id/version - it fills the storage without cleaning up and leftovers of previous versions are kept _forever_.
This wouldn't be an issue for file cache, but in case of memory-based storages, it leaks memory.

**Example** 
Something like this would rock:
```yaml
framework:
    cache:
        default_redis_ttl: 1209600
```

I am currently using a rather ugly workaround:
```php
final class CacheLifetimePass implements CompilerPassInterface
{
    private const SERVICE_NAME = 'cache.adapter.redis';
    private const LIFETIME = 60 * 60 * 24 * 14; // 2 weeks

    public function process(ContainerBuilder $container) : void
    {
        /** @var Definition $redisAdapter */
        $redisAdapter = $container->getDefinition(self::SERVICE_NAME);
        $redisAdapter->setArgument(2, self::LIFETIME);
    }
}
```

**Comment by nicolas-grekas** [comment]
You should be able to do it using the default_lifetime option:
```yaml
framework:
  cache:
    app: 
    pool:
      app.cache.redis:
        adapter: cache.adapter.redis
        default_lifetime: XXXXX
```

then you can use `app.cache.redis` as "adapter" for any pool you'd like, including system pools (framework.cache.system: app.cache.redis).

Note that to me, the definition of system caches are the ones that are "sourced" by the app's repository (either PHP or other file sitting there). With this definition, there is no better storage than `PhpFilesAdapter`, which is the default one already. And since you clear the cache at each deploy, this leak does not exist when using this strategy.
