### ISSUE TITLE
_instance of in Bundle's services.yaml doesn't work

### ISSUE THREAD

**Issue by HEKET313** [symfony/symfony#27843]
**Symfony version(s) affected**: 4.1

**Description**  
I made a bundle. There's following interface: `Optimax\HealthCheckBundle\Service\HealthInterface`
I want add tag `health.service` to every service which implements this interface. I added following code into my Bundle's `services.yaml`:
```
services:
  _instanceof:
    Optimax\HealthCheckBundle\Service\HealthInterface:
      tags: [!php/const Optimax\HealthCheckBundle\Service\HealthInterface::TAG]
  Optimax\HealthCheckBundle\Controller\HealthController:
    autowire: true
    public: false
    autoconfigure: true

  health.controller: '@Optimax\HealthCheckBundle\Controller\HealthController'
```
Alias `health.controller` creates properly but `_instanceof` doesn't work
If I add same code to the projects `config/services.yaml`, it works perfectly.

**How to reproduce**  

1. Create bundle
2. Add same config to the bundle.
3. Add bundle to project
4. Create service which implements `HealthInterface`
5. Look at service's tags
