### ISSUE TITLE
Twig extension's runtime is not automatically registered as service and is not tagged with twig.runtime tag

### ISSUE THREAD

**Issue by kniziol** [symfony/symfony#27896]
**Symfony version(s) affected**: 4.1.1

**Description**  
If the runtime class is not registered as service and tagged with `twig.runtime` tag manually an error occurs:

```
Unable to load the "App\Twig\ApplicationRuntime" runtime.
```

Runtime class of Twig, used to create lazy-loaded Twig extension, requires registration in `services.yaml`, but, according to [documentation](https://symfony.com/doc/current/templating/twig_extension.html#creating-lazy-loaded-twig-extensions), it shouldn't.

**How to reproduce**

Here are main actors of the problem:

* default of configuration services: `config/services.yaml`
* custom Twig extension: `src/Twig/ApplicationExtension.php`
* runtime for the extension: `src/Twig/ApplicationRuntime.php`

```yaml
# config/services.yaml

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: '%env(APP_DEFAULT_LOCALE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```

```php
// src/Twig/ApplicationExtension.php

<?php

namespace App\Twig;

use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class ApplicationExtension extends AbstractExtension
{
    /**
     * {@inheritdoc}
     */
    public function getFunctions(): array
    {
        $functions = [
            1 => [
                ApplicationRuntime::class,
                'getDescriptor',
            ],
        ];

        return array_merge(parent::getFunctions(), [
            new TwigFunction('meritoo_common_application_descriptor', $functions[1]),
        ]);
    }
}
```

```php
<?php
// src/Twig/ApplicationRuntime.php

declare(strict_types=1);

namespace App\Twig;

use Meritoo\CommonBundle\Application\Descriptor;
use Meritoo\CommonBundle\Service\ApplicationService;

class ApplicationRuntime
{
    /**
     * Serves application
     *
     * @var ApplicationService
     */
    private $applicationService;

    /**
     * Class constructor
     *
     * @param ApplicationService $applicationService Serves application
     */
    public function __construct(ApplicationService $applicationService)
    {
        $this->applicationService = $applicationService;
    }

    /**
     * Returns descriptor of application
     *
     * @return Descriptor
     */
    public function getDescriptor(): Descriptor
    {
        return $this
            ->applicationService
            ->getDescriptor();
    }
}
```

**Possible Solution**

If add this part of code:

```yaml
# config/services.yaml

(...)

services:

    (...)

    # Runtime classes required to create lazy-loaded Twig Extension
    App\Twig\:
        resource: '../src/Twig/*Runtime.php'
        public: false
        tags: ['twig.runtime']
```

the error is gone.

**Additional context**

(Documentation)[https://symfony.com/doc/current/templating/twig_extension.html#creating-lazy-loaded-twig-extensions] says that:

> If you're using the default services.yaml configuration, this will already work! Otherwise, create a service for this class and tag your service with twig.runtime.

I'm using default services.yaml configuration, auto wire is enabled and Twig extension with runtime class are created exactly as described in the docs. So, the documentation is lying or maybe I'm doing something wrong?
