### ISSUE TITLE
[WORKFLOW] [RFC] Pass context/metadata in the entire workflow process

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#27925]
**Description**  

Hi

We are using the workflow component to redesign our internal processing of some business entities.

We are now facing some logic we did not know how to deal with on our code port.

Previously we were doing on our entities status change this logic:

```php
$entity->setStatus(Entity::STATUS_X, $specificComment); // comment can be a tech comment, a context comment, or anything else
```

and the setStatus() method is like this

```php
public function setStatus(int $status, ?string $comment = null)
{
        $this->status = $status;
        $this->addStatusLogRecord(new StatusLog($this, $comment));

        return $this;
}
```

We were storing a statusLog on every status change with the new status, the date of change, the user (blameable) and an optionnal comment => for log/debug/history purpose

But now with the workflow, it is our internal marking store that call the `setStatus()` (mapping of the current place to our internal status because we store an int not a string), 
and unfortunately we are not able to pass some other metadata.

**Feature Request**  

Discussion on the availability to have a workflow business context to allow the developper to pass some context in the workflow process, 
and get this context inside the workflow process, all workflow events and in the workflow marking store logic as well.
Is this a feature that can be usefull for this component? giving some possibility to developpers?
Or maybe developpers are already dealing differently for this kind of purpose?

Obviously we can add an in memory property on the entity for storing the comment and if it is not null, get it for the `addStatusLogRecord()` but this design is not pleasant at all.

Many thank for your time and thank you for this component that helps us a lot

**Comment by lyrixx** [comment]
What about adding `WorkflowInterface::apply($transitionName, array $context = [])`

**Comment by noniagriconomie** [comment]
@lyrixx yesit was my first idea but kind of hack :/

do you think it could be a nice additional feature?

**Comment by Padam87** [comment]
https://github.com/symfony/symfony/pull/20789/files

**Comment by noniagriconomie** [comment]
Interesting PR, thank you for posting it
I really think this use case could be a very usefull option for devs as i explained in the description
It allows to do things properly imo
And in a correct way of coding and not « hacking » way

**Comment by lyrixx** [comment]
@Padam87 The intent is different here. In your case, it was done to control things.
Here it's just extra information during the save.

**Comment by Padam87** [comment]
My intent was exacly the same. :) The ability to pass parameters. https://github.com/symfony/symfony/issues/20774

If by control you mean that the parameters were also passed to the can method that is because if passing parameters is enabled, then guards should also have access to them.

**Comment by lyrixx** [comment]
IMHO, this contest should on by used my the marking store, to store more information. 
So, This context should not goes through the `workflow::can` method

**Comment by noniagriconomie** [comment]
in my example the context was intended to be passed to the whole workflow, but of course for getting data to set, not validation with the can (guard)

**Comment by Padam87** [comment]
Hm, I don't know. On one hand it makes sense to allow the dev to deal with this outside of the workflow, on the other that could lead to this:

```php
if ($someParam === 'someValue' && $workflow->can($object, 'transition')) {
    $worflow->apply($object, 'transition', ['someParam' => $someParam])
}
```

Now the decision is made at 2 places, guard and controller. I don't like that.

Anyway, event params would be nice, even if it is just for the `apply` method.

**Comment by stlrnz** [comment]
+1 for this idea from my side.
Also, I'd love to see the additional data in guard events. As for today we cannot perform all required checks in the guards. We have to define some of them in our controllers.

**Comment by alexhaker** [comment]
+1
That feature allows us to use Workflow component for our business processes in the system.
It would be very useful to have additional data in transition events.

**Comment by Nyholm** [comment]
Is anyone willing to provide a PR for this feature?

**Comment by SulivanDotEu** [comment]
+1
I'm facing many cases where I miss this feature.

Here is an example:

Let's take an auction as exemple described in _workflow.yaml_ below. The auction is simple, user can create an auction but only an admin can start the auction. After that, each user can bid only one to an auction. Also, to be able to bid, you must have an active membership. pretty simple business logic.

```
framework:
    workflows:
        auction:
            type: state_machine
            marking_store:
                type: single_state
                arguments:
                    - status
            supports:
                - App\Entity\Auction
            places:
                - draft
                - started
                - ended
            transitions:
                start:
                    from: draft
                    to:     submitted
                    metadata:
                        roles: [ROLE_ADMIN, ROLE_SUPERADMIN]
                make_an_offer:
                    from: started
                    to:     started
                    metadata:
                        roles: [ROLE_USER]
```


Thanks to the metadata, I can specify which role is required to start an auction. Fine it as been put in place.
Secondly, I would like to validate that a user can "make an offer". For that, I will use the method `Workflow::can($auction, 'make_an_offer', ['user' => $user])` .
From there, I can create a guard that will check if that current user already bid or not on the auction.
I really miss this feature and any alternative seems to be so expensive so far. Still thinking about alternatives.

**Comment by lyrixx** [comment]
#29146 is not merged. You can test it and give me some feedback. Thanks

**Comment by SulivanDotEu** [comment]
@lyrixx do you still need help on this? Do you have any advice on how to test this?

**Comment by lyrixx** [comment]
It's in symfony 4.3 😁 everything works fine. Thanks

**Comment by brizzz** [comment]
@SulivanDotEu you can handle your use case using custom Security Voter and 'guard' property of transition. Like that:
```yaml
...
            transitions:
                start:
                    guard: "is_granted('ROLE_ADMIN', subject) or is_granted('ROLE_SUPERADMIN', subject)"
                    from: draft
                    to:     submitted
                make_an_offer:
                    guard: "is_granted('ALLOW_TO_BID', subject)"
                    from: started
                    to:     started
```
ALLOW_TO_BID - is your custom security voter where you can check if the current user have rights to create a new bid.
