### ISSUE TITLE
Matched route triggering "No route found" error

### ISSUE THREAD

**Issue by SvetlinStaev** [symfony/symfony#27932]
**Symfony version(s) affected**: 4.1.1

**Description**  
I have recently added a feature in one of my projects where a user which has a personal page on the site with route like `/profile/{userId}` can get a subdomain with a given name like `user.test.dev` pointing to that same controller which answers to `/profile/{userId}`. In Symfony 3.4 it works perfectly fine but when I upgrade to 4.1 with the new routing improvements it breaks some of the existing routes. When I try to open a given route `/обяви/автомобили.html` on the site given the following route pattern:

```
category:
    path: /обяви/{categorySlug}.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        categorySlug: "[\\D]+"
```

I get an NotFoundHttpException but when I open the Routing tab on the debug toolbar it has matched the route (finishes the matching with Route Matches!).

I am tried to isolate the problem and it looks like it is related to the `host` key which I add to some of the routes to restrict whether they are to be shown on the main site (`www.test.dev`) or on a subdomain of the site (`username.test.dev`). When I remove all the host requirements from the routes it works on 4.1. If I put even a single route with a host requirement it breaks.

**How to reproduce**  
I have made a sample branch illustrating the issue, it is available here - https://github.com/SvetlinStaev/symfony/tree/test/utf_routing_issue. In the Resources folder I have added a `_routing.yml` which has no host requirements on the routes and it will work fine.
