### ISSUE TITLE
[RFC][Router] Add a global switch to always generate URLs with HTTPS

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#28017]
**Description**  
Something I miss in Symfony apps is a simple way to always generate HTTPS URLs when using `path()`, `url()` or `$urlGenerator->generate()`, no matter which is the scheme of the current page. In addition to the added security, it's a simple way to force your visitors use HTTPS.

Today I'm doing things like this in my services to implement this idea:

```php
public function __construct(RouterInterface $router)
{
    $router->getContext()->setScheme('https');
    $this->router = $router;
}
```

**Example**  
Could we add instead a global config under `framework.router` to always force HTTPS when generating routes? (Ideally when generating routes on the console too):

```yaml
framework:
    router:
        # ...
        force_https: true
```

If you agree, we'd need a great name for this option; `force_https` is just a quick proposal.

**Comment by ciaranmcnulty** [comment]
A way to indicate HSTS might complement this

**Comment by ostrolucky** [comment]
There already is `router.request_context.scheme` parameter option.

**Comment by Saphyel** [comment]
I always used with security...

Anyway use ssl is basic. I think symfony should always try to use https and http as a fallback. No config.

**Comment by ktherage** [comment]
Just a simple idea, what about this:
```
framework:
    router:
        # ...
        force_scheme: 'https' # or 'http' to get wider
```
