### ISSUE TITLE
Route is missing from collection after loading from cache

### ISSUE THREAD

**Issue by flack** [symfony/symfony#28024]
**Symfony version(s) affected**: 4.1.1

**Description**  

I'm using the routing component standalone like this:

```php
$loader = new YamlFileLoader(new FileLocator);
$config = [
    'cache_dir' => '/tmp/',
    'debug' => true
];
$router = new Router($loader, $resource, $config);
```

`$resource` contains among others this route:

```yml
project-new:
    path: /project/new/
    defaults: { _controller: 'org_openpsa_projects_handler_project_crud::create' }
```

When I call `$router->generate('project-new')`, it works the first time, but the second time (i.e. when the route file is loaded from cache), I get an exception  `Unable to generate a URL for the named route "project-new" as such route does not exist.` When I open the generated cache file, I can't see the route in the `$routes` array

**How to reproduce**  

The code above together with this file https://github.com/flack/openpsa/blob/master/lib/org/openpsa/projects/config/routes.yml does it for me (I'm sure it could be reduced further)
