### ISSUE TITLE
[DI] error for unused binding on controller action

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#28041]
**Symfony version(s) affected**: 3.4.13 (and other new patch releases for 4.0 & 4.1)

**Description**  
I just updated my app from `3.4.12` to `3.4.13` and have an error with a service configuration.

**How to reproduce**  
Add a binding by variable name for an argument of a controller action.

I have a controller like this:

```php
class LegacyAdminController extends Controller
{
    /**
     * @Route("/{path}", requirements={"path"=".+"})
     */
    public function proxyAction(
        ServerRequestInterface $request,
        LegacyUserMapper $legacyUserMapper,
        Client $legacyProxyClient
    ) {
```

And the config:

```yaml
    App\Controller\LegacyAdminController:
        tags: ['controller.service_arguments']
        bind:
            $legacyProxyClient: '@ca_admin.legacy_proxy_client'
```

Now I get this error:

```
In ResolveBindingsPass.php line 48:
                                                                                                     
  Unused binding "$legacyProxyClient" in service "CA\AdminBundle\Controller\LegacyAdminController".
```

**Possible Solution**  
As just discussed with @nicolas-grekas  the problem was introduced in https://github.com/symfony/symfony/pull/27834/files.

**Comment by nicolas-grekas** [comment]
Please confirm #28052 fixes the issue.

**Comment by Tjeerd** [comment]
Confirmed this fixes the issue for me on 4.1.2!

**Comment by dmaicher** [comment]
@nicolas-grekas also fixed for me :+1: thx!

**Comment by Diwatt** [comment]
It also fixed an other issue:
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
          $contentEntityManager: '@doctrine.orm.default_entity_manager'
          $userEntityManager: '@doctrine.orm.ugo_user_entity_manager'
```

```
    public function getUserAction(
        EntityManagerInterface $userEntityManager,
        EntityManagerInterface $contentEntityManager,
        UserInterface $user
    ) {
```

The 2 variables were bound to the default entity manager $contentEntityManager.

I manage to fix that by reverting manually this bugfix (reverting to sf 3.4.12) https://github.com/symfony/symfony/pull/27834
