### ISSUE TITLE
Autobinding to controllers failed

### ISSUE THREAD

**Issue by MathieuMindid** [symfony/symfony#28077]
**Symfony version(s) affected**: 4.1.2

**Description**  
Since i update from 4.1.1 to 4.1.2, default binding from controllers failed : 

Controller "App\Controller\Admin\KitController::edit()" requires that you provide a value for the "$customDir" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.

custom_dir is defined in env, i try to rollback to 4.1.1 and it works.

**How to reproduce**  
service.yml
```
services:
    # default configuration for services in *this* file
    _defaults:
        bind:
            $customDir: '%custom_dir%'
```
Controller : 

```
public function edit($customDir) {
// ... 
}
```
