### ISSUE TITLE
Doctrine Event Subscribers are always registered before Event Listeners

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony#28090]
The `RegisterEventListenersAndSubscribersPass` Compiler Pass will always handle Event Subscribers first and then look for Event Listeners ([here](https://github.com/symfony/symfony/blob/81eb54eb78072e77fb23240228bebc38eaa86b3a/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L57-L58)).

The result is that subscribers will *always run before* listeners, *regardless of the given priority*. The priority will only affect the execution order of subscribers and listeners in their particular group (does that make it clear?).

This can cause surprising side effects when switching an implementation from a subscriber to a listener or vice versa.

IMO, there should be no such difference, and I also could not find any documentation or other hint that this difference was intended.

I can try to come up with a PR if those with enough karma to decide agree that this should be fixed.

**Comment by dmaicher** [comment]
Indeed that is the current behavior.

The question would be how to specify the priorities for subscribers?

Maybe something like this?

```yaml
- { name: doctrine.event_subscriber, priorities: { prePersist: 5, postPersist: 3 }}
```
Then we would have to sort the priorities together with the listeners and add the register calls one by one per subscribed event on the EventManager.

**Comment by mpdude** [comment]
I think there can be only one priority for the subscriber as a whole.

**Comment by dmaicher** [comment]
> I think there can be only one priority for the subscriber as a whole.

Hmm I don't think is a real solution then as I cannot control the priority for individual events then and so it still behaves different than listeners.

**Comment by mpdude** [comment]
It seems there have been major changes to the `RegisterEventListenersAndSubscribersPass` class between at least 2.8 and 3.4. Merging a fix from to 2.8 into the higher branches might be a real pain.

@fabpot and @nicolas-grekas What would be your favorite approach? Have a PR for 2.8 and sorting out the merge conflict yourselves? Maybe backporting the 3.4 code to 2.8 in order to avoid merge conflicts? Prepare different PRs for 2.8 and 3.4? Please advise.

**Comment by dmaicher** [comment]
@mpdude actually I don't think this can be treated as a bugfix. If we merge this into an existing release branch then I guess all subscribers will be treated with priority=0 which can cause weird behavior changes and would be a BC break I think.

**Comment by mpdude** [comment]
Well, every bugfix changes existing behavior... I think the question is what the intended (or expected) behavior is and to make things consistent with it.

**Comment by fabpot** [comment]
I would not treat as a bug fix either. Should be done and documented in master instead.

**Comment by kevinpapst** [comment]
This was already discussed in the past, see #6979 and is still an open issue.
For the next person with the problem and until this might be solved in the framework, here is a workaround: you can switch the tag in your service definition, as both are handled the same way internally by Doctrine. 

I couldn't find that in the docs, so here is an example with the popular DoctrineExtensions:
```
    Gedmo\Loggable\LoggableListener:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: loadClassMetadata }
            - { name: doctrine.event_listener, event: postPersist }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```
can also be written as 
```
    Gedmo\Loggable\LoggableListener:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```
