### ISSUE TITLE
Cannot use hyphen in symfony asset package name

### ISSUE THREAD

**Issue by damaya** [symfony/symfony#28122]
**Symfony version(s) affected**: 3.4.14

**Description**  
When using hyphen in symfony asset package name, the following error is shown: 
>"An exception has been thrown during the rendering of a template ("There is no "frontend-app" asset package.")."

**How to reproduce**  
``` yaml
framework:
        packages:
            frontend-app:
                base_path: '/'
```
NOTE: in this example, when removing the hyphen or replacing hyphen with underscore, it works as expected, for example:
``` yaml
framework:
        packages:
            frontendapp:
                base_path: '/'
```
or this
``` yaml
framework:
        packages:
            frontend_app:
                base_path: '/'
```
