### ISSUE TITLE
[Messenger] Impossible to specify routing_key during publishing a message

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#28133]
**Symfony version(s) affected**: 4.1

**Description**  
`routing_key` parameter is always `null` [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php#L101)

**Additional context**  
I want to use `messenger` to send messages to a third party application, so I cant modify the way the messages will be consumed

**Comment by sroze** [comment]
@BoShurik my question is similar that for #28053: would a transport-wide configuration fit your requirements (i.e. all the messages for the given transport would be sent to a given `routing_key`)?

```
framework:
  messenger:
    transports:
      default: amqp://[...]?routing_key=abc
```

**Note:** don't try to use this example, it is not implemented 🙃
