### ISSUE TITLE
Route with subdomain breaks any other routers with dot in path.

### ISSUE THREAD

**Issue by SebastianGrzymala** [symfony/symfony#28142]
**Symfony version(s) affected**: 4.1.1

**Description**  
Route with subdomain breaks any other routes with dot in path.

**How to reproduce**  
The page /static/sample.html return NotFoundHttpException although Route Matching Logs presents route matching as successful. Removing subdomain route make it working back.
```
#routes.yaml

subdomain:
  path: /
  host: test.mydomain.com
  controller: App\Controller\Single::show

static_page:
  path: /static/{symbol}.html
  controller: App\Controller\StaticPage::show
  requirements:
      symbol:'[a-z_-]+'
```

**Additional context**  
Get NotFoundHttpException although route match.
![symfony profiler](https://user-images.githubusercontent.com/26069708/43705500-ef90489c-9962-11e8-957c-409f4e81f100.png)
