### ISSUE TITLE
[Dotenv] Incompatible use of dynamic environment variables

### ISSUE THREAD

**Issue by jhonatanTeixeira** [symfony/symfony#28165]
**Symfony version(s) affected**: ^4.1

**Description**  

when clearing the cache or trying to run builtin server command i get the following message:

```
In Compiler.php line 112:

  Incompatible use of dynamic environment variables "LIIP_DRIVER" found in parameters.


In DriverCompilerPass.php line 32:

  Specified driver 'liip_imagine.%env(LIIP_DRIVER)%' is not defined.
```

**How to reproduce**  
I've done the following configuration for the liip imagine bundle:

```yml
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: '%env(LIIP_DRIVER)%'
```

**Possible Solution**  
Using the good old parameters.yml style solved the issue
