### ISSUE TITLE
Unexpected MySQL error with doctrine - SQLSTATE[HY000] [2002]

### ISSUE THREAD

**Issue by fabienlem** [symfony/symfony#28191]
**Symfony version(s) affected**: 4.1.3

**Description**  

Since 2 days, I get one totally arbitrary mysql error very often: 

> request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [2002] Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée. " at C:\www\vine-back\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 113

It occurs on a local installation of Symfony (WAMP / Windows 10). I didn't perform any change on my local installation.

In my ```.env``` file, I have:

```
DATABASE_URL=mysql://root:@127.0.0.1:3306/vine
```

That worked until now.

I also tried with:

```
DATABASE_URL=mysql://root:@localhost:3306/vine
```

**How to reproduce**  
Don't know.

**Possible Solution**  
Don't know.

**Additional context**  

Here is my dbal config:

```
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
```

Do you have any idea of what could be wrong? Any hints of what can I check?

Best regards,
Fabien
