### ISSUE TITLE
[Lock] Why RedisStore always generates a new random token?

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#28208]
**Symfony version(s) affected**: v4.1.2

**Description**  

```yaml
services:
    app.lock.factory:
        class: Symfony\Component\Lock\Factory
        arguments:
            - !service
                class: Symfony\Component\Lock\Store\RetryTillSaveStore
                arguments:
                    - !service
                        class: Symfony\Component\Lock\Store\RedisStore
                        arguments:
                            - "@redis"
                            - 10
                    - 100
                    - 50
```

If you run this twice (two different scripts):
```php
$this->get('app.lock.factory')->createLock('sasa', 100)->acquire(true);
```

You will get:
```
redis-cli monitor
1534415918.363780 [0 127.0.0.1:16431] "EVAL" "\n            if redis.call(\"GET\", KEYS[1]) == ARGV[1] then\n                return redis.call(\"PEXPIRE\", KEYS[1], ARGV[2])\n            else\n                return redis.call(\"set\", KEYS[1], ARGV[1], \"NX\", \"PX\", ARGV[2])\n            end\n        " "1" "sasa" "2odGKUWQ/cq2WMmjZOcfWL9mVTdOkwicnMIsPlbk0hs=" "2000"
1534415918.363952 [0 lua] "GET" "sasa"
1534415918.363976 [0 lua] "set" "sasa" "2odGKUWQ/cq2WMmjZOcfWL9mVTdOkwicnMIsPlbk0hs=" "NX" "PX" "2000"
1534415918.364436 [0 127.0.0.1:16431] "EVAL" "\n            if redis.call(\"GET\", KEYS[1]) == ARGV[1] then\n                return redis.call(\"PEXPIRE\", KEYS[1], ARGV[2])\n            else\n                return 0\n            end\n        " "1" "sasa" "2odGKUWQ/cq2WMmjZOcfWL9mVTdOkwicnMIsPlbk0hs=" "100000"
1534415918.364507 [0 lua] "GET" "sasa"
1534415918.364550 [0 lua] "PEXPIRE" "sasa" "100000"
1534415918.365108 [0 127.0.0.1:16431] "GET" "sasa"
1534415918.365725 [0 127.0.0.1:16431] "EVAL" "\n            if redis.call(\"GET\", KEYS[1]) == ARGV[1] then\n                return redis.call(\"DEL\", KEYS[1])\n            else\n                return 0\n            end\n        " "1" "sasa" "2odGKUWQ/cq2WMmjZOcfWL9mVTdOkwicnMIsPlbk0hs="
1534415918.365857 [0 lua] "GET" "sasa"
1534415918.365886 [0 lua] "DEL" "sasa"
1534415918.366444 [0 127.0.0.1:16431] "GET" "sasa"
1534415919.006364 [0 127.0.0.1:38761] "EVAL" "\n            if redis.call(\"GET\", KEYS[1]) == ARGV[1] then\n                return redis.call(\"PEXPIRE\", KEYS[1], ARGV[2])\n            else\n                return redis.call(\"set\", KEYS[1], ARGV[1], \"NX\", \"PX\", ARGV[2])\n            end\n        " "1" "sasa" "XMKBlIOhUbu2gXrgBlBMxVKi7e66hKPekR+yNAfc+O4=" "2000"
1534415919.006531 [0 lua] "GET" "sasa"
1534415919.006556 [0 lua] "set" "sasa" "XMKBlIOhUbu2gXrgBlBMxVKi7e66hKPekR+yNAfc+O4=" "NX" "PX" "2000"
1534415919.006971 [0 127.0.0.1:38761] "EVAL" "\n            if redis.call(\"GET\", KEYS[1]) == ARGV[1] then\n                return redis.call(\"PEXPIRE\", KEYS[1], ARGV[2])\n            else\n                return 0\n            end\n        " "1" "sasa" "XMKBlIOhUbu2gXrgBlBMxVKi7e66hKPekR+yNAfc+O4=" "100000"
1534415919.007377 [0 lua] "GET" "sasa"
1534415919.007409 [0 lua] "PEXPIRE" "sasa" "100000"
1534415919.007787 [0 127.0.0.1:38761] "GET" "sasa"
1534415919.008606 [0 127.0.0.1:38761] "EVAL" "\n            if redis.call(\"GET\", KEYS[1]) == ARGV[1] then\n                return redis.call(\"DEL\", KEYS[1])\n            else\n                return 0\n            end\n        " "1" "sasa" "XMKBlIOhUbu2gXrgBlBMxVKi7e66hKPekR+yNAfc+O4="
1534415919.008724 [0 lua] "GET" "sasa"
1534415919.008746 [0 lua] "DEL" "sasa"
1534415919.009014 [0 127.0.0.1:38761] "GET" "sasa"
```

As seen above https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Lock/Store/RedisStore.php#L152 is always generating new random token, which leads to lock always being recognized as released.

**Possible Solution**  
@jderusse Shouldn't it always generate same token for the same resource given? Like other stores.
