### ISSUE TITLE
[Messenger] shouldn't the default bus service be public?

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#28215]
Given the following configuration

```yaml
framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - SendinBlue\Middleware\EventBusMiddleware

            messenger.bus.events:
                middleware:
                    - Symfony\Component\Messenger\Middleware\AllowNoHandlerMiddleware
```

I expected to be able to use `ControllerTrait::dispatchMessage` but the call fails because the container can't access `message_bus`.

Adding

```php
$container->getAlias('message_bus')->setPublic(true);
```

in a compiler pass solves the issue but it seems weird to me.
