### ISSUE TITLE
file:// is not a valid url for asset embedding

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#28238]
**Symfony version(s) affected**: 3.4.12 (think currently all published symfony versions affected)

**Description**  

I want to use `file://` as `base_urls` in the `framework` `asset` configuration as this is a lot faster when generating pdfs from html.

**How to reproduce**  

`config.yml`:

```yaml
framework:
    assets:
        packages:
            pdf:
                base_urls: 'file://%kernel.project_dir%/web'
```

Twig:

```twig
{{ asset('test.jpg', 'pdf') }}
```

Ends up in:

```
(1/3) InvalidArgumentException"file:///Users/alex/development/symfony.lo/web" is not a valid URL
```
