### ISSUE TITLE
Confusing exception when using action injection + casing mismatch in routing file

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#28254]
Having such action:
```php
public function index(Request $request, PostRepository $posts): Response
```
and such routing:
```yaml
index:
    path: /en/blog
    controller: App\Controller\BlogController::Index
```

yields
> Controller "App\Controller\BlogController::Index()" requires that you provide a value for the "$posts" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.

This is because user made a typo in routing and used BlogController::**I**ndex, instead of BlogController::**i**ndex
