### ISSUE TITLE
Intermittent DB resolve issues

### ISSUE THREAD

**Issue by HTMLGuyLLC** [symfony/symfony#28287]
**Symfony version(s) affected**: 4.1

**Description**  
The issue is an inability to resolve the DB host but it's not persistent. The reason I'm posting this on Symfony is because I suspect it's relevant to the new environment variables "resolve".

Environment:
AWS EC2 Ubuntu 16.04
Nginx (issue also occurs on Apache)
Symfony 4.1
MYSQL 5.7 RDS

This started just after an upgrade from 3.4 to 4.1 (but I also upgraded from Ubuntu 14.04 to 16.04).
It works probably 99/100 tries, but then fails and throws this exception: `An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known`. 

It appears that it stems from this in doctrine.yaml: `url: '%env(resolve:DATABASE_URL)%'`. 

Stack trace:
```
#0 /var/www/CRM/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(184): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/CRM/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /var/www/CRM/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException))
#3 /var/www/CRM/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'my user', 'my pass', Array)
#4 /var/www/CRM/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1464): Doctrine\DBAL\Connection->connect()
#5 /var/www/CRM/var/cache/prod/ContainerNfDq29P/getSessionService.php(22): Doctrine\DBAL\Connection->getWrappedConnection()
#6 /var/www/CRM/var/cache/prod/ContainerNfDq29P/srcProdProjectContainer.php(608): require('/var/www/CRM/va...')
#7 /var/www/CRM/var/cache/prod/ContainerNfDq29P/getSecurity_Csrf_TokenStorageService.php(13): ContainerNfDq29P\srcProdProjectContainer->load('getSessionServi...')
#8 /var/www/CRM/var/cache/prod/ContainerNfDq29P/srcProdProjectContainer.php(608): require('/var/www/CRM/va...')
#9 /var/www/CRM/var/cache/prod/ContainerNfDq29P/getSecurity_Firewall_Map_Context_MainService.php(28): ContainerNfDq29P\srcProdProjectContainer->load('getSecurity_Csr...')
#10 /var/www/CRM/var/cache/prod/ContainerNfDq29P/srcProdProjectContainer.php(608): require('/var/www/CRM/va...')
#11 /var/www/CRM/var/cache/prod/ContainerNfDq29P/srcProdProjectContainer.php(1273): ContainerNfDq29P\srcProdProjectContainer->load('getSecurity_Fir...')
#12 /var/www/CRM/vendor/symfony/dependency-injection/ServiceLocator.php(64): ContainerNfDq29P\srcProdProjectContainer->ContainerNfDq29P\{closure}()
#13 /var/www/CRM/vendor/symfony/security-bundle/Security/FirewallMap.php(83): Symfony\Component\DependencyInjection\ServiceLocator->get('security.firewa...')
#14 /var/www/CRM/vendor/symfony/security-bundle/Security/FirewallMap.php(54): Symfony\Bundle\SecurityBundle\Security\FirewallMap->getFirewallContext(Object(Symfony\Component\HttpFoundation\Request))
#15 /var/www/CRM/vendor/symfony/security-bundle/EventListener/FirewallListener.php(44): Symfony\Bundle\SecurityBundle\Security\FirewallMap->getFirewallConfig(Object(Symfony\Component\HttpFoundation\Request))
#16 /var/www/CRM/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Symfony\Bundle\SecurityBundle\EventListener\FirewallListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#17 /var/www/CRM/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#18 /var/www/CRM/vendor/symfony/http-kernel/HttpKernel.php(125): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#19 /var/www/CRM/vendor/symfony/http-kernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#20 /var/www/CRM/vendor/symfony/http-kernel/Kernel.php(188): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /var/www/CRM/public/index.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#22 {main}
```

config/packages/doctrine.yaml
```
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

**How to reproduce**  
Randomly occurs
