### ISSUE TITLE
[DI] ServiceContainer build error after upgrading to 4.1.4

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#28296]
**Symfony version(s) affected**: 4.1.4

**Description**

After upgrading to v4.1.4 the following error shown when container tries to build.

RuntimeException Cannot dump definitions which have method calls.

<details>
<summary>Tace</summary>
RuntimeException Cannot dump definitions which have method calls.  
 [Symfony\Component\DependencyInjection\Exception\RuntimeException]  
  Cannot dump definitions which have method calls.                    

Exception trace:
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->dumpValue() at /var/www/html/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:614
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServiceMethodCalls() at /var/www/html/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:516
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServiceInlinedDefinitions() at /var/www/html/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:792
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addService() at /var/www/html/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:827
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServices() at /var/www/html/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:194
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() at /var/www/html/vendor/symfony/http-kernel/Kernel.php:704
 Symfony\Component\HttpKernel\Kernel->dumpContainer() at /var/www/html/vendor/symfony/http-kernel/Kernel.php:541
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/html/vendor/symfony/http-kernel/Kernel.php:123
 Symfony\Component\HttpKernel\Kernel->boot() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:65
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:39
</details>

possibly BC break
possibly caused by: #28060 
(or maybe i missed something and used it wrong)

**How to reproduce**  
I have a monolog handler that requires EntityManagerInterface and a doctrine EventSubscriber that needs the monolog logger with the handler. It works fine when I downgrade to symfony/dependency-injection to v4.1.3

Files that requre to reproduce:

<details>
<summary>src/Monolog/DoctrineDBHandler.php</summary>

```php

namespace App\Monolog;

use Doctrine\ORM\EntityManagerInterface;
use Monolog\Handler\AbstractProcessingHandler;

class DoctrineDBHandler extends AbstractProcessingHandler
{
    private $entityManager;

    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct();
        $this->entityManager = $em;
    }

    protected function write(array $record): void
    {
        // write log to db
    }
}
```
</details>

<details>
<summary>src/EventSubscriber/DoctrineLogSubscriber.php</summary>

```php

namespace App\EventSubscriber;

use Doctrine\Common\EventSubscriber;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Monolog\Logger;

class DoctrineLogSubscriber implements EventSubscriber
{
    private $logger;

    public function __construct(Logger $logger)
    {
        $this->logger = $logger;
    }

    public function getSubscribedEvents(): array
    {
        return ['postPersist'];
    }

    public function postPersist(LifecycleEventArgs $args): void
    {
        $this->logger->addInfo('create');
    }
}
```
</details>

<details>
<summary>config/services.yaml</summary>

```yaml

parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\DoctrineLogSubscriber:
        arguments: ['@monolog.logger.demo']
        tags:
            - { name: doctrine.event_subscriber }

```
</details>

<details>
<summary>config/packages/dev/monolog.yaml</summary>

```yaml

...
monolog:
    channels: ['demo']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        demo:
            channels: ['demo']
            level: INFO
            type: service
            id: App\Monolog\DoctrineDBHandler

```
</details>

**Comment by nicolas-grekas** [comment]
Hello, thanks for the report.
Can you please create a small app app we could clone to reproduce the issue? That would help a lot. Thanks.

**Comment by mmarton** [comment]
Hello.
It's here: https://github.com/mmarton/symfony-di-error-poc

**Comment by codedmonkey** [comment]
We have this problem in 3.4.15, I'll check if I can work out a small reproduction.

**Comment by dmaicher** [comment]
@nicolas-grekas seems its indeed caused by https://github.com/symfony/symfony/pull/28060

for some service definitions with method-calls this condition + continue here now prevents them from being added to `$this->definitionVariables`:

https://github.com/symfony/symfony/pull/28060/files#diff-f7b23d463cba27ac5e4cb677f2be7623R509

So they are not dumped here:

https://github.com/nicolas-grekas/symfony/blob/e843bb86c88c9a52a6c9d3a98afb11f796624abe/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1767

Which leads to the Exception. Unfortunately I don't fully understand all that logic so I cannot fix it :smile: :see_no_evil:

**Comment by Webonaute** [comment]
Also have some issue. if services have calls method but are public: false, it throw exception.

**Comment by franzwilding** [comment]
Can confirm, that a simple `composer require symfony/dependency-injection:4.1.3` solves the problem for the moment.

**Comment by nicolas-grekas** [comment]
It looks like `composer require symfony/proxy-manager-bridge` fixes the issue.

**Comment by hal869** [comment]
@nicolas-grekas 

```
composer require symfony/proxy-manager-bridge
composer show | grep symfony/ | egrep "dependency|proxy"
	symfony/dependency-injection             v4.1.4     Symfony DependencyInjection Component
	symfony/proxy-manager-bridge             v4.1.4     Symfony ProxyManager Bridge

composer update
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Package operations: 0 installs, 1 update, 0 removals
	Generating autoload files
	ocramius/package-versions:  Generating version class...
	ocramius/package-versions: ...done generating version class

	Executing script cache:clear [KO]
	 [KO]
	Script cache:clear returned with error code 1
	!!
	!!  In PhpDumper.php line 1543:
	!!
	!!    Cannot dump definitions which have method calls.
	!!
	!!
	!!
	Script @auto-scripts was called via post-update-cmd
```

**Comment by mmarton** [comment]
It fixes my original problem. I'm just not sure, that adding a new dependency is the right way to fix a bug introduced in a patch release.

**Comment by hal869** [comment]
@mmarton 

You no longer see the "Cannot dump ..." error?

Did you in-fact also remove the DI 4.1.3 instance, allowing update back to 4.1.4?

**Comment by mmarton** [comment]
@hal869

yes, it fixes my demo repository here: https://github.com/mmarton/symfony-di-error-poc

> $ bin/console cache:clear
 // Clearing the cache for the dev environment with debug true                                                          
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

>  $ composer show | grep symfony/ | egrep "dependency|proxy"
symfony/dependency-injection        v4.1.4  Symfony DependencyInjection Component
symfony/proxy-manager-bridge        v4.1.4  Symfony ProxyManager Bridge

**Comment by hal869** [comment]
@mmarton 

> yes, it fixes my demo repository

well, then, hm :-/  still 'here', clearly.  poking around for 'why' ...

**Comment by fmata** [comment]
I can confirm that requiring symfony/proxy-manager-bridge fixes the issue.

**Comment by frostieDE** [comment]
I cannot confirm that `composer require symfony/proxy-manager-bridge` fixes the problem:

```
PS D:\Dev\Web\idp> composer require symfony/proxy-manager-bridge
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/proxy-manager-bridge (v4.1.4): Downloading (100%)
Writing lock file
Generating autoload files
Endroid Installer detected project type "symfony"
- Configuring endroid/qr-code-bundle
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In PhpDumper.php line 1543:
!!
!!    Cannot dump definitions which have method calls.
!!
!!
!!
```

**Comment by nicolas-grekas** [comment]
Thanks to the reproducer, I managed to reduce the reproducer to a config like:
```yaml

services:
    foo:
        class: c
        public: true
        arguments:
            - '@bar'
            - !service
                class: c
                properties:
                    p: !service
                        class: c
                        properties:
                            p: !service
                                class: c

    bar:
        class: c
        public: true
        properties:
            p: !service
                class: c
                arguments: ['@foo']
```

Indirectly related to proxy-manager indeed. On it now...
