### ISSUE TITLE
[DI] Parent service when overriding

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#28308]
I am trying to override a service from a bundle and keep argument definition of the original service.

This seems to make an infinite loop (PHP Fatal error:  Allowed memory size of...):
``` yaml
bundle.service.id:
    class: App\Service\ServiceClass
    parent: 'bundle.service.id'
```

Using `decorates`, everything works fine:
``` yaml
App\Service\ServiceClass:
    decorates: 'bundle.service.id'
    parent: 'bundle.service.id'
```
