### ISSUE TITLE
Error "It's a requirement to specify a Metadata Driver..." after Upgrade to 4.1.4

### ISSUE THREAD

**Issue by ThomasTr** [symfony/symfony#28304]
**Symfony version(s) affected**: 4.1.4

**Description**  
After Upgrade from 4.1.3 to 4.1.4 i get the following error:

It's a requirement to specify a Metadata Driver and pass it to Doctrine\ORM\Configuration::setMetadataDriverImpl().

Trace:
```
in ORMException.php line 38
--
at ORMException::missingMappingDriverImpl()in EntityManager.php line 845
at EntityManager::create(object(Connection), object(Configuration))in srcDevDebugProjectContainer.php line 698
at srcDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()in Container.php line 242
at Container->make('doctrine.orm.default_entity_manager', 1)in Container.php line 222
at Container->get('doctrine.orm.default_entity_manager')in ManagerRegistry.php line 35
at ManagerRegistry->getService('doctrine.orm.default_entity_manager')in AbstractManagerRegistry.php line 200
at AbstractManagerRegistry->getManagers()in ProxyCacheWarmer.php line 49
at ProxyCacheWarmer->warmUp('E:\\www\\ltgsc\\var\\cache\\dev')in CacheWarmerAggregate.php line 57
at CacheWarmerAggregate->warmUp('E:\\www\\ltgsc\\var\\cache\\dev')in Kernel.php line 562
at Kernel->initializeContainer()in Kernel.php line 123
at Kernel->boot()in Kernel.php line 183
at Kernel->handle(object(Request))in index.php line 34
````
To be updated:
```
composer outdated --direct
friendsofphp/php-cs-fixer         v2.12.2            v2.13.0            A tool to automatically fix PHP code style
symfony/browser-kit               v4.1.3             v4.1.4             Symfony BrowserKit Component
symfony/console                   v4.1.3             v4.1.4             Symfony Console Component
symfony/css-selector              v4.1.3             v4.1.4             Symfony CssSelector Component
symfony/debug-bundle              v4.1.3             v4.1.4             Symfony DebugBundle
symfony/dotenv                    v4.1.3             v4.1.4             Registers environment variables from a .env file
symfony/expression-language       v4.1.3             v4.1.4             Symfony ExpressionLanguage Component
symfony/flex                      v1.0.89            v1.1.0             Composer plugin for Symfony
symfony/form                      v4.1.3             v4.1.4             Symfony Form Component
symfony/framework-bundle          v4.1.3             v4.1.4             Symfony FrameworkBundle
symfony/lock                      v4.1.3             v4.1.4             Symfony Lock Component
symfony/maker-bundle              v1.5.0             v1.6.0             Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/phpunit-bridge            v4.1.3             v4.1.4             Symfony PHPUnit Bridge
symfony/polyfill-apcu             v1.8.0             v1.9.0             Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/security-bundle           v4.1.3             v4.1.4             Symfony SecurityBundle
symfony/templating                v4.1.3             v4.1.4             Symfony Templating Component
symfony/translation               v4.1.3             v4.1.4             Symfony Translation Component
symfony/validator                 v4.1.3             v4.1.4             Symfony Validator Component
symfony/var-dumper                v4.1.3             v4.1.4             Symfony mechanism for exploring and dumping PHP variables
symfony/web-server-bundle         v4.1.3             v4.1.4             Symfony WebServerBundle
symfony/yaml                      v4.1.3             v4.1.4             Symfony Yaml Component
```
Update:
```
composer update && composer dump-autoload --optimize
Loading composer repositories with package information                                                                                                                                                           Updating dependencies (including require-dev)

Prefetching 41 packages
  - Downloading (100%)

Package operations: 1 install, 58 updates, 0 removals
  - Updating symfony/flex (v1.0.89 => v1.1.0): Loading from cache
  - Updating symfony/dotenv (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/cache (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/polyfill-apcu (v1.8.0 => v1.9.0): Loading from cache
  - Updating symfony/expression-language (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/polyfill-ctype (v1.8.0 => v1.9.0): Loading from cache
  - Updating symfony/inflector (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/property-access (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/polyfill-php70 (v1.8.0 => v1.9.0): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.8.0 => v1.9.0): Loading from cache
  - Updating symfony/options-resolver (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/intl (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/polyfill-intl-icu (v1.8.0 => v1.9.0): Loading from cache
  - Updating symfony/event-dispatcher (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/form (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/lock (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/http-foundation (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/debug (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/http-kernel (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/routing (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/finder (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/filesystem (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/dependency-injection (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/config (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/framework-bundle (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/console (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/maker-bundle (v1.5.0 => v1.6.0): Loading from cache
  - Updating symfony/security (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/security-bundle (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/templating (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/translation (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/validator (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/yaml (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/stopwatch (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/process (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/polyfill-php72 (v1.8.0 => v1.9.0): Loading from cache
  - Updating composer/xdebug-handler (1.1.0 => 1.2.1): Loading from cache
  - Updating friendsofphp/php-cs-fixer (v2.12.2 => v2.13.0): Loading from cache
  - Updating symfony/dom-crawler (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/browser-kit (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/css-selector (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/var-dumper (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/twig-bridge (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/debug-bundle (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/phpunit-bridge (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/web-server-bundle (v4.1.3 => v4.1.4): Loading from cache
  - Updating doctrine/cache (v1.7.1 => v1.8.0): Loading from cache
  - Updating doctrine/persistence (v1.0.0 => v1.0.1): Loading from cache
  - Updating symfony/doctrine-bridge (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/twig-bundle (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/web-profiler-bundle (v4.1.3 => v4.1.4): Loading from cache
  - Updating symfony/serializer (v4.1.3 => v4.1.4): Loading from cache
  - Installing markbaker/complex (1.4.6): Loading from cache
  - Updating phpoffice/phpspreadsheet (1.3.1 => 1.4.0): Loading from cache
  - Updating egulias/email-validator (2.1.4 => 2.1.5): Loading from cache
  - Updating knplabs/knp-components (1.3.8 => v1.3.9): Loading from cache
  - Updating symfony/monolog-bridge (v4.1.3 => v4.1.4): Loading from cache
  - Updating zendframework/zend-code (3.3.0 => 3.3.1): Loading from cache
  - Updating ocramius/proxy-manager (2.2.0 => 2.2.1): Loading from cache
```

My Doctrine Config:
```
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            XXXX:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'XXXX\Entity'
                alias: XXXX
```

**Comment by koddistortion** [comment]
I can confirm this issue after upgrading from Symfony 3.4.14 to 3.4.15.

**Comment by poethrenoff** [comment]
Also had same trouble while upgrading from 4.1.3 to 4.1.4.

**Comment by xabbuh** [comment]
Can one of you create a small example application that allows to reproduce?

**Comment by ThomasTr** [comment]
It happens on a bigger closed source project, i am working on. I'm currently trying to figure out the cause by updating each package individually. I hope to be able to give more details soon.

**Comment by nielsvandermolen** [comment]
+1 Confirming that downgrading the dependency injection package to 4.1.3 resolved the issue.

**Comment by romeodeb** [comment]
I had exactly the same error while upgrading Symfony 3.4.13 to 3.4.15. When disabling doctrine tag "doctrine.orm.entity_listener" on the services that used it, there's no more errors (not a solution but a diagnose). In my case cache:clear failed and the entire project is broken so i'm staying in 3.4.13.

**Comment by nicolas-grekas** [comment]
Can anyone provide a reproducer, and maybe also find the commit which introduced this?

**Comment by nicolas-grekas** [comment]
Does `composer require symfony/proxy-manager-bridge` fix the issue?

**Comment by ThomasTr** [comment]
For me it's also the "doctrine.orm.entity_listener" from 2 doctrine event listener i use. After commenting them out it works  (also not a solution but a diagnose).

And yes, with suggested "symfony/proxy-manager-bridge" it works (with doctrine event listener). 

Will try to build a small reproducer.

**Comment by nicolas-grekas** [comment]
Can you please report if applying #28366 fixes your issue?

**Comment by phansys** [comment]
I left some context from `appLocalDebugProjectContainer` at https://github.com/symfony/symfony/issues/28304#issuecomment-418521487.

**Comment by nicolas-grekas** [comment]
I think I now understand where the issue comes from. It's unrelated to #28366 indeed. The issue is that in some situations, in order to resolve some circular loops, we call setters on inline services *after* injecting the instance into their consumer. This doesn't play well with runtime checks like the one done in `EntityManager`.

The fix, for now at least, is to `composer require symfony/proxy-manager-bridge`, because the situation I'm referring to happens only when this package is not installed (installing it enables some superpower of the DI container, namely to instantiate some services lazily - you definitely want it on real world apps.)

I fear a real fix might be out of reach for 3.4/4.1 but I'll have a better look.

**Comment by ThomasTr** [comment]
Ok, this solution works for me. Thank you for taking care of this problem.

**Comment by phansys** [comment]
Confirmed, thank you!

**Comment by phansys** [comment]
I can confirm adding dependency for `symfony/proxy-manager-bridge` also fixes this https://github.com/symfony/symfony/issues/26778#issuecomment-378947283.

**Comment by nicolas-grekas** [comment]
I'm reopening to keep track of the issue. I've a local reproducer where the reordering leads to a fatal error.

**Comment by ThomasTr** [comment]
Is ok, since for me it seems there is another issue (these comes only, when the listener is used, the issue above was on every page even when the listener was not used): After upgrading symfony/dependency-injection to 4.1.4 and installing symfony/proxy-manager-bridge i got the following error with my listener:

```
Too few arguments to function XXX\EventListener\EntityListener::__construct(), 0 passed in \vendor\doctrine\doctrine-bundle\Mapping\ContainerAwareEntityListenerResolver.php on line 76 and exactly 3 expected

  at src\EventListener\EntityListener.php:26
  at XXX\EventListener\EntityListener->__construct()
     (vendor\doctrine\doctrine-bundle\Mapping\ContainerAwareEntityListenerResolver.php:76)
  at Doctrine\Bundle\DoctrineBundle\Mapping\ContainerAwareEntityListenerResolver->resolve('LTGSC\\EventListener\\RmaEntityListener')
     (vendor\doctrine\orm\lib\Doctrine\ORM\Event\ListenersInvoker.php:110)
  at Doctrine\ORM\Event\ListenersInvoker->invoke(object(ClassMetadata), 'preUpdate', object(Rma), object(PreUpdateEventArgs), 7)
     (vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php:1151)
  at Doctrine\ORM\UnitOfWork->executeUpdates(object(ClassMetadata))
     (vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php:392)
  at Doctrine\ORM\UnitOfWork->commit(null)
     (vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php:359)
  at Doctrine\ORM\EntityManager->flush(null)
     (var\cache\dev\Container2Y6TS4n\EntityManager_9a5be93.php:125)
  at EntityManager_9a5be93->flush()
     (src\Controller\ExportController.php:40)
  at XXX\Controller\ExportController->exportServiceReportAction(object(RmaProduct), object(Request), object(EntityManager_9a5be93), object(Serializer))
     (vendor\symfony\http-kernel\HttpKernel.php:149)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\http-kernel\HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\http-kernel\Kernel.php:188)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public\index.php:34)
```

The constructor injection doesn't work anymore.

This is my constructor for the entity listener:
```
use XXX\DependencyInjection\Mail;
use XXX\Entity\XXX;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Symfony\Component\Translation\TranslatorInterface;

  public function __construct(Mail $mail, TranslatorInterface $translator, $config)
    {
        $this->mail = $mail;
        $this->translator = $translator;
        $this->config = $config;
    }
```

And this is the service configuration:
```
    XXX\EventListener\EntityListener:
        lazy: true
        arguments:
            $config: '%mail%'
        tags:
            - { name: "doctrine.orm.entity_listener", entity: XXX\Entity\XXX, event: preUpdate }
```

**Comment by nicolas-grekas** [comment]
Could you please try #28385 (@hal869 also?)

**Comment by hal869** [comment]
@nicolas-grekas 

```
composer show | egrep "dependency-injection|proxy-manager-bridge"
	symfony/dependency-injection             v4.1.4             Symfony DependencyInjectio...

composer update
	...
	Executing script cache:clear [KO]
	 [KO]
	Script cache:clear returned with error code 1
	!!
	!!  In PhpDumper.php line 1543:
	!!
	!!    Cannot dump definitions which have method calls.
	!!
	!!
	!!
	Script @auto-scripts was called via post-update-cmd


git remote add nicolas-grekas-di-fix https://github.com/nicolas-grekas/symfony
git fetch nicolas-grekas-di-fix
git cherry-pick ccb6e1b5bfde8216f20b9b5026269c5fa59b39e2
composer update
	...
	Executing script cache:clear [KO]
	 [KO]
	Script cache:clear returned with error code 1
	!!
	!!  In FileLoader.php line 168:
	!!
	!!    The autoloader expected class "App\Symfony\Component\DependencyInjection\Du
	!!    mper\PhpDumper" to be defined in file "/dev/www/test/vendor/compo
	!!    ser/../../src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php".
	!!    The file was found but the class was not in it, the class name or namespace
	!!     probably has a typo in /dev/www/test/config/services.yaml (which
	!!     is loaded in resource "/dev/www/test/config/services.yaml").
	!!
	!!
	!!  In DebugClassLoader.php line 288:
	!!
	!!    The autoloader expected class "App\Symfony\Component\DependencyInjection\Du
	!!    mper\PhpDumper" to be defined in file "/dev/www/test/vendor/compo
	!!    ser/../../src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php".
	!!    The file was found but the class was not in it, the class name or namespace
	!!     probably has a typo.
	!!
	!!
	!!
```

**Comment by nicolas-grekas** [comment]
Same as before @hal869, that's not how the patch should be applied. Not that the reproducer you gave to me is fixed for me.

**Comment by ThomasTr** [comment]
Will try next week, having problems aplying this patch under windows.

**Comment by hal869** [comment]
@nicolas-grekas 

> that's not how the patch should be applied.

ok.  then, what _is_ the correct method?

can't 'simply' update to 4.1@dev, yet, as #28385 is closed, but not merged ...

**Comment by nicolas-grekas** [comment]
This is now merged in 3.4, 4.1 and master, please report back if you still experience any issue. You should be able to remove proxy-manager-bridge if you didn't need it before.

**Comment by Laulibrius** [comment]
@nicolas-grekas The issue is still present when the resource is a directory. cf configuration below:
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Listener\Entity\:
        resource: '../src/Listener/Entity'
        tags:
            - { name: doctrine.orm.entity_listener }

    App\Listener\Entity\MediaEntityListener:
        tags:
            - { name: doctrine.orm.entity_listener, priority: 100 }
```
It's working when i comment the App\Listener\Entity\ service declaration and keep MediaEntityListener. 
It's ok with the proxy-manager-bridge also.

**Comment by ThomasTr** [comment]
What's the best way to get this piece of code in an symfony 4.1.4 installation to get it tested?

**Comment by nicolas-grekas** [comment]
since it's merged now, you can just require `~4.1.6@dev` (and maybe also set minimum-stability: dev)

**Comment by ThomasTr** [comment]
Ok, done this, but the error persists.
Unlike @Laulibrius i get the error also with this config:

(Commented to services out for testing, but error still exists)
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    XXXX\EventListener\:
        resource: '../src/EventListener/*'

#    XXXX\EventListener\DoctrineEventListener:
#        tags:
#            - { name: doctrine.event_listener, event: onFlush }

#    XXXX\EventListener\XXXXEntityListener:
#        lazy: true
#        arguments:
#            $config: '%mail%'
#        tags:
#            - { name: "doctrine.orm.entity_listener", entity: XXXX\Entity\XXXX, event: preUpdate }
#
    XXXX\EventListener\XXXXEntityListener:
        lazy: true
        arguments:
            $config: '%mail%'
        tags:
            - { name: "doctrine.orm.entity_listener", entity: XXXX\Entity\XXXX, event: preUpdate }
```
