### ISSUE TITLE
symfony messenger memory

### ISSUE THREAD

**Issue by konradja100** [symfony/symfony#28350]
Hi, i'm using symfony 4.1, messenger with RabbitMQ, and i have some problems with allocated memory - it keeps growing with every consumed message, slowing down whole proccess. 

![screenshot_6](https://user-images.githubusercontent.com/28842587/45015562-6d10e300-b022-11e8-84a9-cef25a51b8b6.png)

When i use memory_get_usage() function, it shows that on every message consumed something stay in memory:
![screenshot_7](https://user-images.githubusercontent.com/28842587/45015682-b6f9c900-b022-11e8-886a-7c76cc8d5e6f.png)

So i've tried to clear EntityMenager with this:

```
$this->em->clear();
```
but it has no effect, also I found a way to do this by setting sql logger to null:
```
$this->em->getConnection()->getConfiguration()->setSQLLogger(null);
```

but it helps releasing memory only by half. So anyone has struggled with this issue? Is this caused by doctrine, cache or something else?

**Comment by konradja100** [comment]
yes, on production performance is even worst.

**Comment by Koc** [comment]
@konradja100 try using https://github.com/LongRunning/LongRunning for releasing memory

**Comment by konradja100** [comment]
Any ideas how to use it in symfony 4.1? Service long_running.delegating_cleaner is private.

**Comment by konradja100** [comment]
Ok, so this problem must me related to symfony/messenger or symfony/amqp-pack which i'm using also. I've switched off my logic, and leave only consumming messages by messanger itself - and I get infinite memory leak. Used memory is increasing endless. This is my MessageHandler:

```
<?php

namespace App\MessageHandler;
use App\Message\TrackerEventMessage;

class TrackerEventHandler
{
    public function __construct()
    {
    }

    public function __invoke(TrackerEventMessage $message)
    {
        echo memory_get_usage().PHP_EOL;
    }
}
```

and my configuration:
```
framework:
    messenger:
        transports:
               event: 'amqp://%env(RABBITMQ_USER)%:%env(RABBITMQ_PASS)%@%env(RABBITMQ_HOST)%:%env(RABBITMQ_PORT)%/%2f/event'

      routing:
           'App\Message\TrackerEventMessage': event

```

So there is no overriding or overloading any part of this two symfony packages, everything is set up by default configuration, and I get this issue, any ideas? I don't know what is kept in memory, or where/how to find it.

**Comment by konradja100** [comment]
I've created an empty project with this two packages, you can reproduce this issue:
https://github.com/konradja100/rabbit

So what i'm missing here? Messenger is not clearing messeges from memory?

**Comment by iltar** [comment]
Make sure there's not a monolog logger with an in_memory log/a logger that processes its contents on kernel shutdown (or CLI variant).

**Comment by konradja100** [comment]
Ok, so I play along with monolog, i've changed my configuration to non-buffering handler - "stream" as long as expected behaviour of finger_crossed is to store log entries in memory, i've also tried this configuration with setting buffer_size to limited value:

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            buffer_size:  30
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
```
and nothing has changed.
 
You can notice that in prod env profiler is disabled, so it shouldn't store anything in memory.

Running worker with --no-debug flag isn't working either.
