### ISSUE TITLE
Calling validation checks manually with a custom validation constraint

### ISSUE THREAD

**Issue by sdespont** [symfony/symfony#28389]
Using Symfony 3.4.15, calling validation checks manually like sugested [here  ](https://github.com/symfony/symfony/issues/11895#issuecomment-55188164) with a custom validation constraint is not working : the validation service dependency (Doctrine in this case) are not initialized.

Am I missing something?

**Entity validation call**
```
        $validator = \Symfony\Component\Validator\Validation::createValidatorBuilder()
            ->addYamlMapping(__DIR__.'/../Resources/config/validation.yml')
            ->getValidator();
        $errors = $validator->validate($entity, null, 'case1');
```

**validation.yml**
```
Company\DocumentBundle\Entity\Report:
    properties:
        edition_date:
            - NotBlank:
                message: "not.blank.error.message"
                groups: [case1, case2]
    constraints:
        - Company\ToolBoxBundle\Validator\Constraints\DateLock:
            groups: [case1]
```

**service.yml**
```
    company.validator.date_lock_check:
        class: Company\ToolBoxBundle\Validator\Constraints\DateLockValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator }
```

**custom validation constraint class**
```
class DateLockValidator extends ConstraintValidator
{
    private $em;

    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    public function validate($entity, Constraint $constraint)
    {
        ...
    }
}
```

**Error**
Type error: Too few arguments to function `Company\ToolBoxBundle\Validator\Constraints\DateLockValidator::__construct()`
