### ISSUE TITLE
[Router] Issues when using two domains like : dev.app.com and apidev.app.com on the same codebase

### ISSUE THREAD

**Issue by guillaume-a** [symfony/symfony#28381]
Hello, 

I'm using last version of flex.

I currently have a project with 1 codebase for 2 subdomains.

My config is like this : 

.env
```
[...]
DOMAIN_API=apilocal.app.com
DOMAIN_WWW=local.app.com
```

services.yaml
```
parameters:
    domain.api: '%env(resolve:DOMAIN_API)%'
    domain.www: '%env(resolve:DOMAIN_WWW)%'
```

routes/annotations.yaml
```
api:
    host: '%domain.api%'
    resource: ../../src/Controller/api
    type: annotation
    prefix: /

www:
    host: '^%domain.www%'
    resource: ../../src/Controller/www
    type: annotation
    prefix: /
```

With this configuration, symfony can't find all "DOMAIN_API" routes.
But it works when i do this : 

```
[...]
DOMAIN_API=localapi.app.com
DOMAIN_WWW=local.app.com
```

In Example 1, we have (api)local.app.com as regexp for domain which may be the root of the problem.

Regards.

**Comment by stof** [comment]
Route requirements cannot be read at runtime from env variables, as the matcher is generated during cache warmup (and making the generated code read env variables to get some of the info is not possible, as that would not allow us to apply most of the optimizations we apply during the code generation).
Such parameters cannot be dynamic ones (i.e. they cannot involve `%env()%`).

**Comment by goatfryed** [comment]
To elaborate more on the answer by @stof 
You can't use `%env()%` in the route's definition, since it won't  be resolved.
But if you alias an env var with a normal parameter name as provided in the example (domain.www, domain.api), it will be resolved at cache warmup. Change will not be detected, if you decide to change the env var without cache clear. As long as you are aware of that fact, it's fine.

> In Example 1, we have (api)local.app.com as regexp for domain which may be the root of the problem.
Host isn't resolved as a regexp. It's always considered to be an exact match, or, if you add a placeholder wildcard, to  have only the placeholder as a degree of freedom.

`host: '^%domain.api%'` will resolve to `'^apilocal.localhost' === $host`, which won't match.

If you check `bin/console debug:router`, you'll notice that all hosts with regexp won't match.

**Comment by guillaume-a** [comment]
Okay, I think I over explained my issue.

Let's get simpler

routes/annotations.yaml

```
api:
    host: 'apidev.domain.com'
    resource: ../../src/Controller/api
    type: annotation
    prefix: /

www:
    host: 'dev.domain.com'
    resource: ../../src/Controller/www
    type: annotation
    prefix: /
```
routes defined in api are in conflict with routes define in www, if the url is the same.

Ex : 

src/Controller/api/DefaultController.php

`@Route("/", name="home_api")`

src/Controller/www/DefaultController.php

`@Route("/", name="home_www")`

If I go to `apidev.domain.com/` Symfony used home_www route instead of home_api.

I changed my domains since this discover. I'll try to make a quick proof very soon :)
