### ISSUE TITLE
add alias to existing service not working

### ISSUE THREAD

**Issue by videni** [symfony/symfony#28413]
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
   App\AppBundle\Checker\PromotionCouponEligibilityChecker: ~
  
   App\Bundle\AppBundle\Checker\Eligibility\PromotionCouponEligibilityCheckerInterface:
        alias:  “@App\AppBundle\Checker\PromotionCouponEligibilityChecker”

```
As you can see the alias and its service are at same file, but it gives a error when autowire the interface in a class constructor.

```
ymfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "“@App\AppBundle\Checker\PromotionCouponEligibilityChecker”". in /Users/www/AppBundle/vendor/symfony/dependency-injection/ContainerBuilder.php:1001
```

**Comment by videni** [comment]
I change it to this , it works now
```
   App\Bundle\ AppBundle\Checker\Eligibility\PromotionCouponEligibilityCheckerInterface: '@App\ AppBundle\Checker\PromotionCouponEligibilityChecker'

```

**Comment by xabbuh** [comment]
When being explicit by using the `alias` option, you must omit the `@` character. This means the following configuration would work as well:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
   App\AppBundle\Checker\PromotionCouponEligibilityChecker: ~
  
   App\Bundle\AppBundle\Checker\Eligibility\PromotionCouponEligibilityCheckerInterface:
        alias:  “App\AppBundle\Checker\PromotionCouponEligibilityChecker”
```

I close here as this is not a bug.
