### ISSUE TITLE
Yaml type problem when using array type parameters

### ISSUE THREAD

**Issue by emr** [symfony/symfony#28425]
**Symfony version**: 4.1

Throwing `InvalidTypeException` when trying to pass the parameter defined as an array in bundle configuration.

Config
```yaml
# config/packages/my_bundle.yaml
parameters:
    array_parameter: ["a", "b", "c"]

my_bundle:
    my_array_node: '%array_parameter%'
```

Configuration tree
```php
// ... 
->arrayNode('my_array_node')
    ->scalarPrototype()->end()
->end()
// ...
```

Error
```
InvalidTypeException
Invalid type for path "my_bundle.my_array_node". Expected array, but got string
```

When I changed the node type for debug:
```php
// ... 
->scalarNode('my_array_node')->end()
// ...
```

😄 Error: 
```
InvalidTypeException
Invalid type for path "my_bundle.my_array_node". Expected scalar, but got array.
```

My makeshift solution:
```php
// ... 
->variableNode('my_array_node')->end()
// ...
```
The value comes as array while node type is `variable`.
