### ISSUE TITLE
Expectations when string value "might" contain $'s (or when it definitely will)

### ISSUE THREAD

**Issue by simensen** [symfony/symfony#28435]
I just spent half an hour trying to figure out why the bcrypt encoding wasn't working on my in-memory provider when the bcrypt password was coming from the environment.

(The following bcrypt value is "test" without the quotes if anyone wants to try it out)

Example `security.yaml`:

```
parameters:
    env(ADMIN_USERNAME): ~
    env(ADMIN_PASSWORD): ~

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    '%env(ADMIN_USERNAME)%':
                        password: '%env(string:ADMIN_PASSWORD)%'
                        roles: 'ROLE_ADMIN'
```

Example broken `.env`:

```
ADMIN_USERNAME=beau
ADMIN_PASSWORD=$2y$12$1SK0b68aiyglJwXiJ4RTb.xhNbKFxRwSgACss7Q6TknVxZrEZRwsm
```

When I changed it to be single quoted, it worked. Even double quoted, did not.

```
ADMIN_USERNAME=beau
ADMIN_PASSWORD='$2y$12$1SK0b68aiyglJwXiJ4RTb.xhNbKFxRwSgACss7Q6TknVxZrEZRwsm'
```

----

Is this expected behavior? Is it documented? If yes to either, what did I miss? I thought I had a broken configuration with encoders since I was never able to login with bcrypt encoder.

**Comment by simensen** [comment]
Alright, right after I submitted this issue (literally), it started to work after I removed the single quotes. No idea why. Or how. But I have video proof of this not working for 30 minutes. I even wrote a simple command to consume the env variable and it was empty except when I finally tried it with single quotes. Any ideas what might have been the cause or how it cleared up on its own?

My services:

```
services:
    App\Command\DebugEnvCommand:
        arguments:
            $adminPassword: '%env(ADMIN_PASSWORD)%'
```

My command:

```
class DebugEnvCommand extends Command
{
    private $adminPassword = 'not set';
    protected static $defaultName = 'DebugEnvCommand';

    public function __construct($adminPassword)
    {
        $this->adminPassword = $adminPassword;
        parent::__construct();
    }

    protected function configure()
    {
        $this
            ->setDescription('Add a short description for your command')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io = new SymfonyStyle($input, $output);
        $io->note(sprintf('Your admin password is: %s', $this->adminPassword));
        // ...
    }
}

```

**Comment by ro0NL** [comment]
dont you need to escape `$` as `\$` in environment variables?

https://askubuntu.com/questions/755033/dollar-sign-in-environment-variables-value

**Comment by xabbuh** [comment]
Indeed, that's what the Dotenv component does in `resolveVariables()`: https://github.com/symfony/symfony/blob/deae538245655b2ef6123b729c095a54238c6113/src/Symfony/Component/Dotenv/Dotenv.php#L351-L395

This method is called for double quoted and not quoted strings.

**Comment by simensen** [comment]
Indeed, after looking at what was going on, I discovered that I needed to quote this specific string differently and things started to work. I'm not sure it was made clear enough in the docs that this would be required? Maybe this is a docs issue.

However, it doesn't explain the fact that it is actually now working both with quotes and without. Now that I know the expected behavior, I'm confused because my original code is working again, even though I still have `$` in my variables without it being quoted.

It is possible that it is something else in the string that made it work sometimes and not others. I did generate many bcrypt values to ensure that I was doing it right. Is it possible some specific bcrypt output would be fine unquoted and others wouldn't? Number of `$`? The existence of a `.` at the end? Some other character that only exists sometimes?

**Comment by simensen** [comment]
After working through this with @nicolas-grekas, it looks like perhaps the string wasn't *empty*, it just wasn't the full string. So, in those cases, the bcrypt password would never match what I was entering.

So, with the following bcrypt password, all of the characters after any `$` are numbers. This means they will not be replaced by other environment variables. `$2`, `$1`, `$1`, so the password check would pass.

`$2y$12$1SK0b68aiyglJwXiJ4RTb.xhNbKFxRwSgACss7Q6TknVxZrEZRwsm`

However, with the following bcrypt password, one of the `$` is followed by a letter. This means dotenv will attempt to replace that big by an environment variable. In this case, dotenv looks for the value of `$AQFegH4ws` in the environment.

`$2y$13$AQFegH4ws.Ev4nYbpkcTae9XuT6K9T37W2aloPBdI0/TBZ0zqgWMi`

Since `$AQFegH4ws` does not exist as an environment variable, the actual value passed into the environment is:

`$2y$13.Ev4nYbpkcTae9XuT6K9T37W2aloPBdI0/TBZ0zqgWMi`

This explains why I wasn't able to log in with the correct password as there is no way any correct password I would enter would pass.

Once I got to the point that I was using other values like "TEST" and outputting those values on the CLI, I was able to see the problem as soon as I tried "TE$ST" or "$TEST" as the value. When I returned to using a bcrypt string, I generated a new bcrypt string (the one listed above) that didn't have any letters following `$` so it worked when double-quoted. *It also worked while not quoted at all!* Leading to much confusion.

Even as-is, I'm still not sure why I don't have to single-quote `$` in all cases, but at least it works.

**Comment by jawira** [comment]
### To summarize

PHP (or Symfony?) tries to do variable interpolation when possible. Because in PHP [variables cannot start with a number](https://www.php.net/manual/en/language.variables.basics.php), only chunks with a letter or an underscore after the `$` dollar symbol are replaced.

```ini
# .env
MY_HASH=$2y$10$YXpo2rBBol8mRB4JGMn99utQ5tWenR2k/Fz.jSqPKsLIRXsLsL64e
```

An empty string is used to do the replacement because that specific "variable" doesn't exists.  
Later, `MY_HASH` is interpreted as `$2y$10/Fz.jSqPKsLIRXsLsL64e`.

```yaml
# config/packages/security.yaml
security:
  # ...
  providers:
    users_in_memory:
      memory:
        users:
          bob: {
            password: '%env(MY_HASH)%', # $2y$10/Fz.jSqPKsLIRXsLsL64e
            roles: [ 'ROLE_USER' ]
          }
```

### The solution

Use **single quotes** in `.env` file.

```ini
# .env
MY_HASH='$2y$10$YXpo2rBBol8mRB4JGMn99utQ5tWenR2k/Fz.jSqPKsLIRXsLsL64e'
```

Please correct me if I'm wrong :)
