### ISSUE TITLE
Memcached Cache Adapter prefix/namespace

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#28558]
**Symfony version(s) affected**: 4.1.4 

Hi,

I am following [this documentation/blog](https://symfony.com/blog/new-in-symfony-3-3-memcached-cache-adapter) to implement memcached cache adapter. The problem is, when we use the configuration pool as suggested, it seems like there is no such option called `prefix`/`namespace`. As a result the cache key is not searchable in terminal because it is prefixed with a random string. What should I do in order to add a specific prefix/namespace to cache keys? e.g. I like to use  `'API_%kernel.environment%_'`.

Thanks

**framework.yaml**

```
framework:
    cache:
        default_memcached_provider: 'memcached://localhost:11211'
        pools:
            app.cache.memcached:
                adapter: cache.adapter.memcached
                public: false
```

I've set two key+value pairs `key1 => value1` and `key2 => value2`. As you can see below, the keys have random prefixes.

**Terminal**

```
$ telnet 127.0.0.1 11211

stats items # Check how many items we have in the cache
STAT items:1:number 2

get key1 # Try to get the value of "key1". It cannot be found :(
END

stats cachedump 1 100 # Let's see what keys we have in the cache. Oh dear :(
ITEM Pux1j2qAhF%3A1%3Akey1 [6 b; 1537646690 s]
ITEM Pux1j2qAhF%3A1%3Akey2 [6 b; 1537646690 s]
END

get Pux1j2qAhF%3A1%3Akey1 # Try to get the value of "Pux1j2qAhF%3A1%3Akey1". Found it :) :(
value2
END
```

**Comment by nicolas-grekas** [comment]
That's correct, this is by design: the prefix is computed for you using various uniqueness-providing parameters that are hashed together to generate the final prefix.

**Comment by BentCoder** [comment]
So there is no solution to it if we use config. Correct?

**Comment by BentCoder** [comment]
I've removed the `pool` config and used the one below to prefix the keys which works. However, the key still has a random string `%3A1%3A` right after the prefix. Is this still part of the "design"? I really need to get rid of this thing.


```
    memcached:
        class: Memcached
        calls:
            - ['addServer', ['localhost', '11211']]

    app.cache.memcached:
        class: Symfony\Component\Cache\Adapter\MemcachedAdapter
        arguments:
            $client: '@memcached'
            $namespace: 'api_%kernel.environment%_'
```

**Result**

```
ITEM api_dev_%3A1%3Akey2 [6 b; 1537650669 s]
ITEM api_dev_%3A1%3Akey1 [6 b; 1537650669 s]
```

**Comment by BentCoder** [comment]
`AbstractTrait::getId()` should simply ignore running the current logic if the user manually sets a namespace and return namespace instead. e.g.

```
AbstractTrait::getId()
{
   if ($this->namespace) {
      return $this->namespace;
   }

   Continue with the current logic
   ....
}
```

**Comment by nicolas-grekas** [comment]
the extra prefix is part of the versioning strategy that allows clearing a specific cache pool without clearing the full memcached server.
You can opt-out from versioning (and thus opt-out from being able to clear a specific pool) by calling `enableVersioning(false)` on the adapter.
I'm closing since you resolved everything yourself and there is no bug here :)

**Comment by BentCoder** [comment]
@nicolas-grekas Looks like this is still not resolved. Please check what I do and let me know if I am missing something. It still sticks `%3A` (`:`) in the key name. Thanks.


```
    memcached:
        class: Memcached
        calls:
            - ['addServer', ['localhost', '11211']]

    app.cache_pool.products:
        class: Symfony\Component\Cache\Adapter\MemcachedAdapter
        arguments:
            $client: '@memcached'
            $namespace: 'api_%kernel.environment%_products_'
        calls:
            - ['enableVersioning', [false]]

    # SERVICE
    App\Service\ProductService:
        arguments:
            $cachePool: '@app.cache_pool.products'
```

```
use Symfony\Component\Cache\Adapter\MemcachedAdapter;

class ProductService
{
    private $cachePool;

    public function __construct(MemcachedAdapter $cachePool)
    {
        $this->cachePool = $cachePool;
    }

    public function saveItem(string $key, string $value, int $expiration): bool
    {
        $item = $cachePool->getItem($key);
        $item->expiresAfter($expiration);
        $item->set($value);

        // $cachePool->enableVersioning(false); Even manually calling this this doesn't change anything

        return $cachePool->save($item);
    }
}
```

**TEST**
```
ProductService::saveItem('key', 'value', 123);
```

**RESULT**

```
ITEM api_dev_products_%3Akey [7 b; 1537662634 s]
```
