### ISSUE TITLE
cache:pool:clear command creates random items in memory

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#28560]
**Symfony version(s) affected**: 4.1.4

Hi,

Running `bin/console cache:pool:clear <cache-pool-name>` creates a cache item in memory and stores a weird value against it such as `3:`, `2:`. The memory item should not be created in first place.

Regards

**CONFIG**
```
framework:
    cache:
        default_memcached_provider: 'memcached://localhost:11211'
        pools:
            app.cache_pool.products:
                adapter: cache.adapter.memcached
                public: false
```

**TEST**

No memory item.
```
stats items
STAT items:1:number 0

stats cachedump 1 100
END
```

Run command.
```
$ bin/console cache:pool:clear app.cache_pool.products

// Clearing cache pool: app.cache_pool.products                                                                        

[OK] Cache was successfully cleared.
```

Now there is 1 memory item!
```
stats items
STAT items:1:number 1

stats cachedump 1 100
ITEM %407Hwh2pFwMd%3A [2 b; 1537649823 s]
END

get %407Hwh2pFwMd%3A
2:
END
```
