### ISSUE TITLE
With Encore, Asset doesn't create the right url  (missing prefix) when using manifest.json

### ISSUE THREAD

**Issue by pfleu** [symfony/symfony#28612]
Symfony 4.1.4

In dev, using WebpackEncore, when I load my page, the browser tries to load assets (css and js generated in build) with paths where the "project_name/public" part is missing.
**Wrong path:** http://localhost/build/app.js
**Should be:** http://localhost/project_name/public/build/app.js

If I comment the content of assets.yaml, it works as expected:
```yaml
framework:
    assets:
#        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
```
