### ISSUE TITLE
Routing to support %env substitution

### ISSUE THREAD

**Issue by danaki** [symfony/symfony#28613]
Allow to set routing prefixes directly from ENV variables. This doesn't work:
```
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /%env(resolve:ADMIN_URL)%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /%env(resolve:ADMIN_URL)%
```

However this works:
```
parameters:
    admin_prefix: '%env(resolve:ADMIN_URL)%'
```

```
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /%admin_prefix%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /%admin_prefix%
```
