### ISSUE TITLE
How to toggle Locale

### ISSUE THREAD

**Issue by devkbsc** [symfony/symfony#28700]
SF : 3.4
Hello, 
I created a field which toggle the site language! But it doesn't change anything. I coudn't figure out the fault to change it!

here is my code of the action : 

```
public function indexAction(Request $request) {
        $defaultData = array('FR' => 'fr');

        $lang_form = $this->createFormBuilder($defaultData)
                ->add('locale', ChoiceType::class, array('label' => false,
                    'choices' => array(
                        'FR' => false,
                        'IT' => 'it',
                        'EN' => 'en',
                    ),
                    'attr' => array('class' => 'form-control', 'style' => "margin-bottom:5px;color:#929292;"),
                ))
                ->getForm();
        $lang_form->handleRequest($request);

        if ($lang_form->isSubmitted()) {
            $locale = $lang_form['locale']->getData();
            if($locale ="fr"){
                $request->setLocale('fr');
            }elseif($locale ="it"){
                $request->setLocale('it');
            }else{
                $request->setLocale('en');
            }
            
            dump($locale);
            die();
        }
        
        return $this->render('lang/index.html.twig', array(
                    //'locale' => $locale,
                    'lang_form'=> $lang_form->createView()
        ));
    }
```

```
Config.yml:
-------------
lexik_translation:
    #(required) default locale(s) to use
    fallback_locale: [%locale%] 
    #(required) locales that the bundle has to manage
    managed_locales: [en, fr, it] 
    
    storage:
        type: orm
        
    base_layout: "LexikTranslationBundle::layout.html.twig"
    grid_input_type: text
    grid_toggle_similar: true
    
    exporter:
        json_hierarchical_format: true
    
    resources_registration:
        type: all
        managed_locales_only: true
    
    auto_cache_clean: false
    auto_cache_clean_interval: 600
    
    dev_tools:
        enable: true
        create_missing: true
        file_format: yml
```
