### ISSUE TITLE
[FrameworkBundle][Cache] Cant create cachepool via config for custom adapter

### ISSUE THREAD

**Issue by ivoba** [symfony/symfony#28734]
**Symfony version(s) affected**: 3.4.15

**Description**  
I tried to create a cache pool with frameworkBundle config for a PdoAdapter but couldnt get it to work.

**How to reproduce**  
I defined the adapter service:

```
  cache.adapter_pdo:
    class: Symfony\Component\Cache\Adapter\PdoAdapter
    public: true
    arguments:
      - 'mysql:host=%database_host%;dbname=%database_name%'
      - 'namespace-'
      - '%cache.ttl%'
      - db_username: '%database_user%'
        db_password: '%database_password%'
```

And tried to define the cache pool with the framework bundle:

	pdo_cache:
	    adapter: 'cache.adapter_pdo'
	    public: true
	    default_lifetime: '%cache.ttl%' 

This leads to this error:

	Symfony\Component\Cache\Exception\InvalidArgumentException: Cache key must be string, "integer" given

So somehow the ttl is set as the namespace argument in the PdoAdapter in the container.

Further when i tag the adapter as cache.pool while not using the bundle config it also stops working:

```
  booking_cache:
    class: Symfony\Component\Cache\Adapter\PdoAdapter
    public: true # only for tests
    arguments:
      - 'mysql:host=%database_host%;dbname=%database_name%'
      - 'booking-'
      - '%booking_cache.ttl%'
      - db_username: '%database_user%'
        db_password: '%database_password%'
    tags: ['cache.pool']
```

When just using a service definition for the cachepool everything is fine.
But the profiler doesnt show any information on this cache.

**Possible Solution**  
I guess the argument replacement in FrameworkBundle/DependencyInjection/Compiler/CachePoolPass.php:85
is not accurate.

Or i did not understand how to use the cache pool config here, then please explain how to achieve this.
And we should update the docs accordingly.

**Additional context**  
Another occurence of this problem i found here:
https://stackoverflow.com/questions/47270162/symfony3-cache-component-pool-definition

**Comment by nicolas-grekas** [comment]
You either define services yourself, or use config only. Mixing both is more complex and not required.
Can't you use the first "cache.adapter_pdo" service directly instead? I'd recommend it (but the name should be made backend-agnostic: it's not the "where it's stored" that matters, it's "what is stored".

**Comment by ivoba** [comment]
@nicolas-grekas yes thats what i am doing atm, using the defined services directly.  
Names were just for this ticket, dont worry:)

But still then i dont have this cache in the profiler, as i would have it when the cache would be defined via config.
I actually thought this would be the case when the service is tagged as 'cache.pool'

And is it generally possible to define f.e. a PdoAdapter via config?
Or is it limited to` 'doctrine', 'psr6', 'redis', 'memcached'`?

**Comment by nicolas-grekas** [comment]
That'll be possible in 4.2, see https://github.com/symfony/symfony/pull/27694/files#diff-1754c5372532c2b324d500472dd5df66 for inspiration.
Yes it's possible to define your own service tagged `cache.pool`, but this requires configuring the first 3 arguments of the constructor using tag attributes. See linked xml.

**Comment by ivoba** [comment]
Ok, thats good news for 4.2.

 > but this requires configuring the first 3 arguments of the constructor using tag attributes

This means arguments have to be in this order: provider, namespace, ttl ?
And they will be mandatorily replaced by the tag attributes?

I tried this :

```
  domain_cache:
    class: Symfony\Component\Cache\Adapter\PdoAdapter
    arguments:
      - 'mysql:host=%database_host%;dbname=%database_name%' # will be replaced by compiler pass?
      - 'namespace-' # will be replaced by compiler pass?
      - '%cache.ttl%'
      - db_username: '%database_user%'
        db_password: '%database_password%'
    tags:
      - {name: cache.pool, provider: 'mysql:host=%database_host%;dbname=%database_name%', namespace: 'namespace-'}
```

But seems not possible for DSNs:

> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "booking_cache" has a dependency on a non-existent service "mysql:host=%database_host%;dbname=%database_name%".

**Comment by nicolas-grekas** [comment]
the host should be defined in the config, not in the service  definition
I'd recommend marking the service as abstract in services.yaml, and give the concrete name + provider in the config

**Comment by ivoba** [comment]
ok, next try :)
services.yaml:

```
  domain.cache_adapter.pdo:
    class: Symfony\Component\Cache\Adapter\PdoAdapter
    abstract: true
    arguments:
      - ''
      - ''
      - '%booking_cache.ttl%'
      - db_username: '%database_user%'
        db_password: '%database_password%'
```

config.yaml:
```
  domain_cache:
        adapter: 'domain.cache_adapter.pdo'
        public: true
        default_lifetime: '%booking_cache.ttl%'
        provider: 'mysql:host=%database_host%;dbname=%database_name%'
```
With DSN i get the same error:

> The service "domain_cache" has a dependency on a non-existent service "mysql:host=mysql;dbname=weekengo-web".

I actually doubt that DSN will work in 4.2 too.
Dont having to include doctrine and just using Pdo for a simple cache was my motivation to chose PdoAdapter here, when using doctrine Dbal i would have directly chosen `doctrine` as adapter.
So DSN support here would be nice.
