### ISSUE TITLE
[Messenger] Debug toolbar stops display messages when multiple buses defined

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#28740]
**Symfony version(s) affected**: 4.1.6

**Description**  
I've defined multiple buses and after this messenger debug section has go away.

**How to reproduce**  
```yaml
framework:
    messenger:
        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Model\Message\Event\TransportableEvent': amqp

        default_bus: messenger.bus.commands

        buses:
            messenger.bus.commands:
                middleware:
                    - doctrine_transaction_middleware
            messenger.bus.events:
                default_middleware: false
                middleware:
                    - logging
                    - route_messages
                    - allow_no_handler
                    - call_message_handler
```

**Additional context**  

```
console debug:container | grep messenger.bus
  Symfony\Component\Messenger\MessageBusInterface                                                     alias for "debug.traced.messenger.bus.commands"                                         
  debug.traced.messenger.bus.commands                                                                 Symfony\Component\Messenger\TraceableMessageBus                                         
  debug.traced.messenger.bus.commands.inner                                                           Symfony\Component\Messenger\MessageBus                                                  
  debug.traced.messenger.bus.events                                                                   Symfony\Component\Messenger\TraceableMessageBus                                         
  debug.traced.messenger.bus.events.inner                                                             Symfony\Component\Messenger\MessageBus                                                  
  message_bus                                                                                         alias for "debug.traced.messenger.bus.commands"                                         
  messenger.bus.commands                                                                              alias for "debug.traced.messenger.bus.commands"                                         
  messenger.bus.commands.messenger.handler_resolver                                                   Symfony\Component\Messenger\Handler\Locator\ContainerHandlerLocator                     
  messenger.bus.commands.middleware.call_message_handler                                              Symfony\Component\Messenger\Middleware\HandleMessageMiddleware                          
  messenger.bus.commands.middleware.doctrine_transaction_middleware                                   alias for "app.command_bus.doctrine_transaction_middleware"                             
  messenger.bus.commands.middleware.logging                                                           alias for "app.command_bus.long_running_middleware"                                     
  messenger.bus.events                                                                                alias for "debug.traced.messenger.bus.events"                                           
  messenger.bus.events.messenger.handler_resolver                                                     Symfony\Component\Messenger\Handler\Locator\ContainerHandlerLocator                     
  messenger.bus.events.middleware.allow_no_handler                                                    Symfony\Component\Messenger\Middleware\AllowNoHandlerMiddleware                         
  messenger.bus.events.middleware.call_message_handler                                                Symfony\Component\Messenger\Middleware\HandleMessageMiddleware                          
  messenger.bus.events.middleware.logging                                                             Symfony\Component\Messenger\Middleware\LoggingMiddleware                  
```

![default](https://user-images.githubusercontent.com/191082/46542077-41557700-c8c6-11e8-9b13-1345025003be.png)
![default](https://user-images.githubusercontent.com/191082/46542092-49adb200-c8c6-11e8-8d80-9ca1d0cb62a2.png)
