### ISSUE TITLE
[Workflow] Add colors to workflow dumps

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#28874]
**Description**  
The PR _[Workflow] Add a MetadataStore to fetch some metadata #26092_ has been merged so we can add some metadata to our workflows.

The text of the PR shows an example with `color: grey`, so it looks like the support of color was planned.

When I [dump the workflow](https://symfony.com/doc/current/workflow/dumping-workflows.html) with both formats, there are no color on the images, like the examples in the documentation.

How can we add colors to the dumped workflow? Is the feature implemented yet?

See also https://github.com/symfony/symfony-docs/pull/9476 if it needs it be documented.

**Example**  

I use `symfony/workflow:4.1.3` (the problem is the same with `4.1.6`).

I have a workflow like this:

```yaml
framework:
    workflows:
        my_entity:
            type: 'state_machine'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'state'
            supports:
                - App\Entity\MyEntity
            initial_place: created
            places:
                created:
                    metadata:
                        description: Entity created, waiting for next step
                        color: green
            # …
```

And the output doesn't use the colors or the description.

**Comment by alexislefebvre** [comment]
When I run `bin/console workflow:dump my_entity` without passing to a graph tool through a piple, the output is the same with and without metadata. There are neither `description` nor `color` in output, that's why the images have default values.

So it looks like the metadata is not dumped.

**Comment by alexislefebvre** [comment]
I identified 3 possible solutions for the configuration:

## Define every option:

```
blog_publishing:
    transitions:
        to_review:
            metadata:
                label: Submit for review
                arrow_color: "Blue"
                label_color: "MediumBlue"
```

Pros:
- Simple to write for users

Cons:
- May require lot of work on the dumper to treat every option

## Define output format directly

```
blog_publishing:
    transitions:
        to_review:
            metadata:
                label: Submit for review
                arrow_style: "[#Blue]"
                label_prefix: "<font color=MediumBlue>"
```

Pros:
- Users can define every option they want and it will be added in output file *as is*

Cons:
- Will work for only dot or PUML output and break the other format

## Define output format specifically for dot or puml

```
blog_publishing:
    transitions:
        to_review:
            metadata:
                label: Submit for review
                puml_format
                    arrow_style: "[#Blue]"
                    label_prefix: "<font color=MediumBlue>"
```

Pros:
- Users can define every option they want and it will be added in output file *as is*
- Users can define options for dot, PUML or both formats

Cons:
- Users must write configuration two times but I think that users will choose dot or PUML formats instead of styling both outputs
