### ISSUE TITLE
LDAP: Get more informations from account

### ISSUE THREAD

**Issue by henri9813** [symfony/symfony#28873]
**Description**  
Actually, the ldap security component described here: https://symfony.com/doc/current/security/ldap.html

return only a username.

It could be funny to get more data like, email address, or other..

**Example**  
```
providers:
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: "ou=MyOU,ou=Users,dc=myldap,dc=com"
                search_dn: "cn=MyOU,dc=mydap,dc=com"
                search_password: "mySuperPassword"
                default_roles: ROLE_USER
                uid_key: cn

               #Additionnal data 
               email_field: email
               first_name: firstname
               last_name: lastname
```

Example in twig: 
```
<a href="/profile">{{ app.user.firstname }} {{ app.user.lastname }} 
```

A cool things that i wanna done if that could exist, it to load gravatar images from the email that this new feature could give me..
 

Thank you ! :)
