### ISSUE TITLE
Form does not apply required attribute

### ISSUE THREAD

**Issue by jwmwalrus** [symfony/symfony#28894]
**Symfony version(s) affected**: 3.4.15, 3.4.16, 3.4.17

**Description**

In Symfony 3.4.x, the validation attributes regarding required form elements are being ignored.

Given the fact that there are way too many elements involved (form_widget, Field Type Guesser,  OptionsResolver, Form Bridge for Doctrine, etc.), I'm not really sure which one gets the blame.

When the intended type is explicitly passed to the second argument of the ```$builder->add``` method, the form works as expected (i.e., the ```'required' => true``` option is assumed by default).

Downgrading the patch version, I noticed that in Symfony 3.4.16 and 3.4.15 the behavior is the same ---I couldn't go any lower, because of conflicts with Twig and PHP 7.x versions.

**How to reproduce**  

Having the following form:

```php
<?php

namespace MyVendor\MyBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
// ...
use Symfony\Component\OptionsResolver\OptionsResolver;

class InventoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // ...
        $builder->add('inventorytype', null, ['placeholder' => 'Select an option']);
        // ...
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'MyVendor\MyBundle\Entity\Inventory',
        ]);
    }

    public function getBlockPrefix()
    {
        return 'inventory';
    }
}
```

With the following entity:

```php
<?php

namespace MyVendor\MyBundle\Entity;

class Inventory
{
    protected $id;

    // ...

    protected $inventorytype;

    // ...

    public function getId()
    {
        return $this->id;
    }

    // ...

    public function setInventorytype(InventoryType $inventorytype)
    {
        $this->inventorytype = $inventorytype;

        return $this;
    }

    public function getInventorytype()
    {
        return $this->inventorytype;
    }

    // ...
}
```

With the following mapping in Resources/config/doctrine:

```yaml
MyVendor\MyBundle\Entity\Inventory:
    type: entity
    table: Inventory
    repositoryClass: MyVendor\MyBundle\Entity\InventoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        # ...
    manyToOne:
        inventorytype:
            targetEntity: MyVendor\MyBundle\Entity\InventoryType
            joinColumns:
                inventorytype_id:
                    referencedColumnName: id
        # ...
```
And the following validation in Resources/config/validation:

```yaml
MyVendor\MyBundle\Entity\Inventory:
    constraints:
        # ...

    properties:
        # ...
        inventorytype:
            - NotBlank: ~
        # ...

```

I'm sending the form from the controller's action as:

```php
    public function editAction($id, Request $request, EntityManagerInterface $em, FlashBagInterface $flashbag)
    {
        // ...

        $form = $this->createForm(InventoryType::class, $inventory);

        if ($request->isMethod('POST')) {
            // ...
        }

        return $this->render('@My/Inventory/edit.html.twig', [
            'myform' => $form->createView(),
            // ...
        ]);
    }
```

The relevant portion in the twig template is:

```twig
{{ form_start(myform, { 'attr': {'class': 'smart-form', 'id':'formgen', 'autocomplete':'off'} }) }}
{# ... #}
<fieldset>
    {# ... #}
        <section class="col col-4">
            <label class="label">Type for the general inventory</label>
            <label class="select">
                {{ form_widget(myform.inventorytype) }}
                <i></i></label>
        </section>
    {# ... #}
    </div>
    {# ... #}
</fieldset>
{{ form_widget(myform._token) }}
{{ form_end(myform, {'render_rest': false}) }}
```

The generated HTML element does not have a ```required``` attribute ---i.e., it's completely ignoring the ```NotBlank``` set in the validation.
