### ISSUE TITLE
[Webpack Encore] Allow multiple manifest.json files

### ISSUE THREAD

**Issue by bpolaszek** [symfony/symfony#28903]
Hello there,

I stumbled upon a minor issue when running Webpack Encore with [multiple configurations](https://symfony.com/doc/current/frontend/encore/advanced-config.html#defining-multiple-webpack-configurations).

Let's craft a sample `webpack.config.js` with 2 configurations:

```js
Encore
    .setOutputPath('public/build/main-app/')
    .setPublicPath('/build/main-app')
    .addEntry('app', './assets/main-app/app.js')
    .enableVersioning(Encore.isProduction())
    .enableSourceMaps(!Encore.isProduction())
;

const mainApp = Encore.getWebpackConfig();
mainApp.name = 'main-app';

Encore.reset();
Encore
    .setOutputPath('public/build/another-app/')
    .setPublicPath('/build/another-app')
    .addEntry('app', './assets/another-app/app.js')
    .enableVersioning(Encore.isProduction())
    .enableSourceMaps(!Encore.isProduction())
;

const anotherApp = Encore.getWebpackConfig();
anotherApp.name = 'another-app';

module.exports = [
    mainApp, 
    anotherApp
];
```

When running `yarn run encore production`,  a `manifest.json` file, containing paths to the versioned assets, will be created in both `/public/build/main-app` and `/public/build/another-app`.

The problem is, we can specify **only one path** in Symfony's configuration:

```yaml
framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/main-app/manifest.json'
```

One can think it's useless since most modern apps are single-page apps in a single entrypoint, but I can expand my use case if needed.

For the moment, I have disabled versioning and my app runs well, but I think this should be improved.

What are your thoughts?

**Comment by alexander-schranz** [comment]
@bpolaszek you can use different asset packages:

```
framework:
    assets:
         packages:
               package_one:
                   json_manifest_path: '%kernel.project_dir%/public/build/main-app/manifest.json'
               package_two:
                   json_manifest_path: '%kernel.project_dir%/public/build/main-app/manifest.json'
```

and use then:

```
{{ asset('main.js', 'package_one') }}
{{ asset('main.js', 'package_two') }}
```
