### ISSUE TITLE
How to override Twig_Environment?

### ISSUE THREAD

**Issue by rubenrubiob** [symfony/symfony#29024]
Hi!

Due to https://github.com/twigphp/Twig/issues/2761 , I want to override `Twig_Environment` temporarily in my Symfony application.

I have tried to do so decorating the service,, with a service decoration following https://symfony.com/doc/current/service_container/service_decoration.html and with this configuration:

```yml
    Twig\Environment:
        class: Infrastructure\Twig\Environment\Environment
        decorates: twig
        decoration_inner_name: twig.inner
        arguments: ['@twig.inner']
        autowire: false
```

But it does not work.

I have also tried making my `Twig_Environment` class a child of the `twig` service, but it does not use my class, it still uses the original `Twig_Environment` class. The configuration that I tried (one of them) is:

```yml
    Twig_Environment:
        parent: Twig\Environment
        autoconfigure: false
        public: true
        class: Infrastructure\Twig\Environment\Environment
        autowire: false
```

Is there any way to do so? I want to avoid passing all the parameters to the constructor, as it is only a temporary solution and I do not want to interfere with the original class.

Thank you!

Regards!
