### ISSUE TITLE
Auto Password Encoder

### ISSUE THREAD

**Issue by ben29** [symfony/symfony#29066]
For password encoder we still use:
https://symfony.com/doc/current/doctrine/registration_form.html#handling-the-form-submission

why not making it auto?

by auto he will get the form password, and will encrypt it.

with using this parameters:

```
security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt
      cost: 12
```

so he can know how the password will be encoded.

Thanks!
