### ISSUE TITLE
Importing multilingual routes only for specified locales

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#29144]
**Description**  
Currently when importing a multilingual route and using a prefix per locale, prefixes for all locales defined on the imported route must be specified.
`Route "fos_user_security_login.ru" with locale "ru" is missing a corresponding prefix when imported`
I suggest to either remove this constraint and import routes only for the locales defined in the prefix locales or to add a different way to constraint the imported locales.

**Example**  

Let's say I have a bundle with predefined route for login
```xml
<route id="fos_user_security_login" methods="GET POST">
    <default key="_controller">fos_user.security.controller:loginAction</default>
    <path locale="en">/login</path>
    <path locale="de">/einloggen</path>
    <path locale="cs">/prihlaseni</path>
    <path locale="sk">/prihlasenie</path>
    <path locale="ru">/avtorizovatsya</path>
</route>
```

And I want to import this route only for `en` and `cs` locale having the `en` locale unprefixed.

Importing 
```yaml
_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:
        en:
        cs: /cs
# Uncommenting the prefixes I don't want to support makes it work but I don't want to support these locales and I don't want to redefine all the routes just to get rid of these locales.
#      de: /de
#      sk: /sk
#      ru: /ru
```

The only way which works for my case is this
```yaml
_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:
        en:
        cs: /cs
        de: /{unsupported}
        sk: /{unsupported}
        ru: /{unsupported}
    requirements: {unsupported: '\z'}
```

But it would be better to get rid of the unsupported locales entirely. Or is there another way to achieve this?
I could make a PR but I would like to know which way I should implement it first.

Thanks

**Comment by maryo** [comment]
Maybe just a boolean flag defined either globally or per route/import?

global
```config.yml
framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yaml"
        strict_locale_imports: false
```

per route/prefix
```
_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:
        en:
        cs: /cs
    strict_locale_imports: false
```

Or perhaps with a better name?
