### ISSUE TITLE
[RFC] enable PropertyNormalizer by default for Messenger's serializer

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#29162]
Using Messenger with a basic message object, it first didn't work.
I had to add this to my config/services.yaml file:
```yaml
services:
    Symfony\Component\Serializer\Normalizer\PropertyNormalizer:
        tags: [serializer.normalizer]
```
It was preceded by some WTF moments because the error felt unrelated.
Did that happen to others? I feel like this should work by default: create a message class and that's enough: it gets through the bus. That wasn't my experience for now.
WDYT?
