### ISSUE TITLE
[RFC] Simplify wiring of service locators

### ISSUE THREAD

**Issue by zmitic** [symfony/symfony#29203]
@nicolas-grekas  on [Twitter](https://twitter.com/nicolasgrekas/status/1061724799536414720) asked me to create RFC. And when Symfony core member makes a call, you answer that call :smile:   

Is it possible to have autowiring for Service Locator? Example:

```php
interface CustomizedServiceNameInterface
{
    public static function getName(): string;
}

interface TagCollectionInterface
{
    public static function getTagName(): string;
}
```

Because components need custom name instead of FQCN, programmer has to implement interface (otherwise, it works as usual FQCN as name):

```php
class HeaderComponent implements CustomizedServiceNameInterface, ComponentInterface
{
    public static function getName(): string
    {
        return 'header';
    }
}
```

so when I make class that implements TagCollectionInterface:

```php
class MyCollectionOfTaggedServices extends ServiceLocator implements TagCollectionInterface
{
    public static function getTagName(): string
    {
        return ComponentInterface::class;
    }
}
```

$factories is populated as 

```php
array [
  HeaderComponent::getName() => new Reference(HeaderComponent::class),
 // just an example, I know these are callables
];
```

instead of

```php
array [
  HeaderComponent::class => new Reference(HeaderComponent::class),
];
```

Right now I have to write a compiler pass:

![image](https://user-images.githubusercontent.com/1964158/48431873-1981ea80-e773-11e8-84d0-7248158990b7.png)

It is pretty messy code, but the thing is that I make array of components where key is read from ``ComponentInterface::getName()`` static method. The rest (like $map variable) is irrelevant to Symfony.

Anyway, tell me what you think. This idea will be scraped, I have better idea now (using annotations on controller + kernel.view event), define route tree just like NG and it will be good to go. It will not change the speed but will clean the code.

**Comment by Tobion** [comment]
Sorry but your description is not understandable to me. What kind of feedback are you asking for in this RFC?

**Comment by nicolas-grekas** [comment]
You're creating service locators using a convention to generate its keys. It's pretty easy right now to get collections of services without using any DI pass (eg with `!tagged`), but it doesn't work for locators. The deep reason for this current impossibility is that we don't know which keys we should give to the services in the collection (for `!tagged`, we don't need special keys - an increasing number is enough.)

So, here, you're seeking for a way to express how the keys should be generated. A custom tag + DI pass does the job, but you're wondering if some more generic mechanism could allow reducing the need for custom code.

At least that's what I understood so far :)

**Comment by zmitic** [comment]
@nicolas Exactly, thanks, I didn't know how to ask correctly. If I used tagged services, all would be instantiated and I would loose speed. In real site, having 50+ components is likely expected.

Even if ``$factories`` can be autowired as ``$id => new Reference($id)`` , it would be enough. The best solution is probably using ``@param`` like  [this issue](https://github.com/symfony/symfony/pull/27172) but I see it is closed.

**Comment by nicolas-grekas** [comment]
I removed the first part in your description because I think it's not needed to explain your point. Reopening.

**Comment by yceruto** [comment]
I recently asked @roONL about this possibility that `!tagged` returned the collection indexed by the `id` of the service and make `ServiceLocatorTagPass` support `TaggedIteratorArgument`.

Basically:
> [...] wondering if some more generic mechanism could allow reducing the need for custom code. [...]

I would like something like this:
```yaml
services:
    task_worker_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments: ['!tagged task_worker']
        tags: ['container.service_locator']
```
instead of actual:
```php
class WorkerCompilerPass implements CompilerPassInterface
{
    use PriorityTaggedServiceTrait;

    public function process(ContainerBuilder $container)
    {
        $definition = $container->findDefinition('task_worker_locator');

        $services = [];
        foreach ($this->findAndSortTaggedServices('task_worker', $container) as $reference) {
            $services[(string) $reference] = $reference;
        }

        $definition->replaceArgument(0, $services);
    }
}
```
later we can do this `$this->workerLocator->get(TaggedTaskWorkerSrv::class)`

**Comment by yceruto** [comment]
I recently asked @ro0NL about this possibility that `!tagged` returned the collection indexed by the `id` of the service and make `ServiceLocatorTagPass` support `TaggedIteratorArgument`.

Basically:
> [...] wondering if some more generic mechanism could allow reducing the need for custom code. [...]

I would like something like this:
```yaml
services:
    task_worker_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments: ['!tagged task_worker']
        tags: ['container.service_locator']
```
instead of actual:
```php
class WorkerCompilerPass implements CompilerPassInterface
{
    use PriorityTaggedServiceTrait;

    public function process(ContainerBuilder $container)
    {
        $definition = $container->findDefinition('task_worker_locator');

        $services = [];
        foreach ($this->findAndSortTaggedServices('task_worker', $container) as $reference) {
            $services[(string) $reference] = $reference;
        }

        $definition->replaceArgument(0, $services);
    }
}
```
later we can do this `$this->workerLocator->get(TaggedTaskWorkerSrv::class)`

**Comment by nicolas-grekas** [comment]
Also: `foo_locator: !service_locator !tagged foo_tag`. BUT I'm wondering if indexing by service id is legitimate: it looks like another form of "by convention" binding - ie something that works just "by chance" because the configuration happens to be OK. How can a consumer then know about the keys that exist in such a locator? FQCN is the only possible way right now. But service ids don't have to be FQCN, so that !tagged might gather non-FQCN-identified services.
We should figure out this before.

**Comment by ciaranmcnulty** [comment]
This would be useful for me too, I'm doing something like:

```
  my.user_repositories:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    arguments:
    -
      memory: '@My\InMemory\UserRepository'
      mysql: '@My\Doctrine\UserRepository'
    tags: ['container.service_locator']
```

(A factory uses this to select service at runtime using an env DSN)

So in my case I want to get a specific key for each service that isn't just the ID. Maybe there's a convention we can use like:

```
My\InMemory\UserRepository:
   tags:
      { name: 'my.user.repository', service-key: 'memory'}

  my.user_repositories:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    arguments: ['!tagged-keys my.user.repository']
    tags: ['container.service_locator']
```
?

Then we could do something app-specific with Autoconfiguration to generate those keys
