### ISSUE TITLE
Symfony 4 The route is wrongly configured

### ISSUE THREAD

**Issue by barricade86** [symfony/symfony#29294]
**Symfony version(s) affected**: 4.1.7

**Description**  
We have the next route:
```
$path = '/{siteSection}/{categoryPath}/';
        $defaults = [
            '_controller' => 'SiteBundle\Controller\Category:index',
        );
        $requirements = array(
            'siteSection' => 'catalog',
            'categoryPath' => '([\d\w-]+\/*?){2,4}'
        );
        $route = new Route($path, $defaults, $requirements);

        // add the new route to the route collection
        $routeName = 'catalog.category_controller';
        $routes->add($routeName, $route);       
```
For example, we have the next URI:
1) /catalog/large_and_small_appliances/large_appliances/
2) /catalog/large_and_small_appliances/
On Symfony 4.0 there was no issues with these URI. They' re worked as expected. When i updated symfony on 4.1, i got issues with them. The first URI in browser gives me an error: The route is wrongly configured. The second one is OK.
Command: php bin/console router:match --host=my_host/catalog/large_and_small_appliances/ --scheme=https
shows the route catalog.category_controller(as expected). Any ideas, what's chaged?

**Additional context**  
They're both ok on Symfony 4.0

**Comment by nicolas-grekas** [comment]
what's in routing.yml? can yoo share a small app reproducing the issue with instructions to experience it? does #29298 change anything?

**Comment by barricade86** [comment]
> what's in routing.yml? can you share a small app reproducing the issue with instructions to experience it? does #29298 change anything?
routing.yml
```
catalog.category_controller:
    path: /{siteSection}/{categoryPath}/
    defaults:
        _controller: 'SiteBundle\Controller\Category:index'        
    requirements:
        siteSection: "catalog|discount"
        categoryPath: '%regexp.category_path%'
```
parameters.yml
```
regexp.category_path: '([\d\w-]+\/*?){2,4}'
```
