### ISSUE TITLE
[Bug][BC break][DependencyInjection] Resolve arguments of service broken in 4.2

### ISSUE THREAD

**Issue by peterrehm** [symfony/symfony#29412]
**Symfony version(s) affected**: 4.2

**Description**  
After the upgrade from 4.1 to 4.2 I am getting the error:

'The service "twig" has a dependency on a non-existent service "mopa_bootstrap.navbar_renderer".'

This is due to the following service definition in an external bundle:

````yaml
services:
    mopa_bootstrap.navbar_renderer:
        class: Mopa\Bundle\BootstrapBundle\Navbar\Renderer\NavbarRenderer
        arguments: [ '@service_container', [] ]
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.renderer, alias: navbar }

    mopa_bootstrap.navbar.twig.extension:
        class: Mopa\Bundle\BootstrapBundle\Navbar\Twig\NavbarExtension
        arguments: [ '@mopa_bootstrap.navbar_renderer' ]
        tags:
            -  { name: twig.extension }
````

If I add public: true to `mopa_bootstrap.navbar_renderer` it works as expected.
This seems strange as it is properly injected. Any idea?

**How to reproduce**  
-

**Possible Solution**  
-

**Additional context**  
-

**Comment by tgalopin** [comment]
https://github.com/symfony/symfony/pull/29393 may have fixed the problem, could you apply the patch and try building the container? If it's working as expected, the next patch release will include the fix.

**Comment by peterrehm** [comment]
I have just tried it and it fixes the issue with the specific bundle but new issues are arising.

Now I am getting the error:

````
You have requested a non-existent service "security.authentication.session_strategy.api".
````

This seems to be realted with my api section of the firewall:

````yaml
security:
   firewalls:
        api:
            pattern:    ^/api
            simple-preauth:
                provider: fos_userbundle
                authenticator: App\Security\AuthTokenAuthenticator
            anonymous: ~
            stateless: true
````

If I remove the api section of the firewalls the error changes to 

````
You have requested a non-existent service "router.default".
````
