### ISSUE TITLE
[Bug][BC break][Workflow] Workflow metadata has disappeared since symfony/framework-bundle 4.1.8

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#29427]
**Symfony version(s) affected**: `symfony/framework-bundle` 4.1.8+

**Description**
I'm working on a command that use `metadata` for adding style to workflow dumps.

The configuration is:

```yaml
framework:
    workflows:
        pull_request:
            # …
            transitions:
                submit:
                    from: start
                    to: travis
                    metadata:
                        title: transition submit title
                        style:
                            label: 'My custom label'
                            arrow_color: '#0088FF'
                            label_color: 'Red'
                # …
```

And I get metadata with `$this->workflowMetadata->getMetadata('style', $transition)`: https://github.com/alexislefebvre/SymfonyWorkflowStyleBundle/blob/ce5d5923cedd2a3b41e51386faf56a9888880739/src/Symfony/Component/Workflow/Dumper/PlantUmlDumper.php#L191

It worked one week ago but it is broken today: no data is returned.

I identified that it comes from `symfony/framework-bundle`, it breaks if I install `v4.1.8` or `v4.2.0`.

**How to reproduce**
Clone https://github.com/alexislefebvre/SymfonyWorkflowStyleBundle, install dependencies and run tests:

```
git clone git@github.com:alexislefebvre/SymfonyWorkflowStyleBundle.git
cd SymfonyWorkflowStyleBundle/
composer install -vvv --profile --no-progress
php ./vendor/bin/phpunit
```

Tests pass.

Now remove `conflict` from `composer.json`, update dependencies and run tests again: Tests will fail because data in `metadata` is not available, so the PUML lacks the expected style.

**Possible Solution**

The problem is probably in one of these commits: https://github.com/symfony/framework-bundle/compare/v4.1.7...v4.1.8

Only 2 commits were related to Workflow: https://github.com/symfony/framework-bundle/commit/0647c5aeb0f3ce9914b066967ef7a75f4039b3a0 ([PR](https://github.com/symfony/symfony/pull/29137)) and https://github.com/symfony/framework-bundle/commit/1c1f86be45ee553169bd0c928822de8b1b42b7b0 ([PR](https://github.com/symfony/symfony/pull/28769))

**Additional context**

We can see logs on Travis CI:

- job from 7 days ago: https://travis-ci.org/alexislefebvre/SymfonyWorkflowStyleBundle/jobs/459487618 →test passed
- job from today: https://travis-ci.org/alexislefebvre/SymfonyWorkflowStyleBundle/jobs/462429106 →test failed

The base code of my bundle has not been changed between these 2 jobs (¹), the only difference is that Symfony 4.1.8 and 4.2 have been released and these versions were installed today.

(¹) I only changed the configuration of failing jobs on Travis CI
