### ISSUE TITLE
Infinite redirects between routes with and without slash

### ISSUE THREAD

**Issue by emodric** [symfony/symfony#29438]
**Symfony version(s) affected**: 4.2.0

**Description**  

I have two routes, one without slash, one with the slash, and with 4.2.0 and 4.1.8 (latest 3.4 and 4.1.7 work fine), there is an infinite redirect loop between the two. https://github.com/symfony/symfony/pull/29380 also does not fix the issue.

**How to reproduce** 

The following routes cause the problem:

```
test_route_no_slash:
    path: /foo
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: test_route
        permanent: true

test_route:
    path: /foo/
    methods: [GET]
    defaults:
        _controller: "App\\Controller\\FooController"
```

Reproducer is available at  https://github.com/emodric/sf_route_redirect_bug

Start the server and open `/foo` to get the infinite redirects.
