### ISSUE TITLE
[Workflow] Workflow definition build is incorrect when using transition metadata

### ISSUE THREAD

**Issue by sgehrig** [symfony/symfony#29453]
**Symfony version(s) affected**: 4.2.0

**Description**  
When building the workflow definition for the DI container, the transition instances are not reused for both the definition and the metadata store. Instead separate instances are created for the workflow definition and the metadata store. This results in `\Symfony\Component\Workflow\Metadata\InMemoryMetadataStore::getTransitionMetadata` being unable to retrieve the transition metadata because the instances do not match and the transition metadata is stored in an `\SplObjectStorage`.

**How to reproduce**  
Create a simple workflow like this e.g.:

```
framework:
    workflows:
        article_publishing:
            type: 'workflow'
            audit_trail: true
            marking_store:
                type: 'single_state'
                arguments:
                    - 'currentState'
            supports:
                - App\Domain\Model\Article\Article
            initial_place: draft
            places:
                - draft
                - published
            transitions:
                submit:
                    from: draft
                    to: published
                    metadata:
                        title: Publish
```

The resulting service definition in the compiled container looks like:

```
    protected function getWorkflow_ArticlePublishingService()
    {
        $a = new \SplObjectStorage();
        $a->attach(
            new \Symfony\Component\Workflow\Transition('submit', [0 => 'draft'], [0 => 'published']),
            ['title' => 'Publish']
        );

        return $this->services['workflow.article_publishing'] = new \Symfony\Component\Workflow\Workflow(
            new \Symfony\Component\Workflow\Definition(
                [0 => 'draft', 1 => 'published'],
                [
                    0 => ($this->privates['workflow.article_publishing.transition.0'] ?? $this->privates['workflow.article_publishing.transition.0'] = new \Symfony\Component\Workflow\Transition(
                            'submit', [0 => 'draft'], [0 => 'published']
                        )),
                ],
                'draft',
                new \Symfony\Component\Workflow\Metadata\InMemoryMetadataStore(
                    [],
                    [],
                    $a
                )
            ),
            new \Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore('currentState'),
            ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()),
            'article_publishing'
        );
    }
```

The transition instance inside the transition metadata store is a different one than the transition in the workflow definition. 

**Possible Solution**  
I assume that the error is in `symfony/framework-bundle/DependencyInjection/FrameworkExtension.php:549-552`. Instead of passing a `\Symfony\Component\DependencyInjection\Reference` to the transition service id (`$transitionId`) to the `attach` method call, the code uses the `\Symfony\Component\DependencyInjection\Definition` instance. This leads to a new definition begin created inline the `attach` call. The fix could be as easy as

```
$transitionsMetadataDefinition->addMethodCall('attach', array(
    new Reference($transitionId), // instead of $transitionDefinition,
    $transition['metadata'],
));
```
