### ISSUE TITLE
Can't mock public service

### ISSUE THREAD

**Issue by bogdan-dubyk** [symfony/symfony#29455]
**Symfony version(s) affected**: 4.2.0

**Description**  
I'm using codeception with symfony module (https://codeception.com/docs/modules/Symfony) as my testing framework and I want to mock Symfony service as I'm usually doing with creating a new class and wire it in the `services_test.yml` where all services are public. 

**services.yml**

```
parameters:
    locale: 'en'
    app_path: '%kernel.project_dir%/src'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Interfaces\Controllers\:
        resource: '../src/Interfaces/Controllers'
        tags: ['controller.service_arguments']

```

and **services_test.yml**

```
services:
    _defaults:
        public: true

    App\Tests\Functional\Api\Mock\GuzzleApiClient: ~
    App\Infrastructure\Api\HttpClients\HttpClientInterface: '@App\Tests\functional\Api\Mock\GuzzleApiClient'

    App\Tests\Functional\Apps\Mock\AppMetadataDownloaderFactory: ~
    App\Domain\Apps\Factories\AppMetadataDownloaderFactoryInterface: '@App\Tests\Functional\Apps\Mock\AppMetadataDownloaderFactory'
```

 
As you can see I want to mock `HttpClientInterface` and `AppMetadataDownloaderFactoryInterface` wiring them to mock objects `App\Tests\functional\Api\Mock\GuzzleApiClient` and `App\Tests\Functional\Apps\Mock\AppMetadataDownloaderFactory` accordingly

Working part of test:

```
    /** @var GuzzleApiClient $apiClient */
        $apiClient = $I->getSymfonyService(HttpClientInterface::class);
       $apiClient->mockResponse($fakeRepsponse);

        $I->setSymfonyService($apiClient, HttpClientInterface::class);
```

Not working part:
```
        /** @var AppMetadataDownloaderFactory $factory */
        $factory = $I->getSymfonyService(AppMetadataDownloaderFactoryInterface::class);
        $factory->mockScraper($scraper);
        $I->setSymfonyService($factory, AppMetadataDownloaderFactoryInterface::class);
```

Not working part throwing error like:

>   [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException] The "App\Domain\Apps\Factories\AppMetadataDownloaderFactoryInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

I do not know where is the issue but looks like for some reason app recognizing AppMetadataDownloaderFactoryInterface as a private service, but same technique working for `HttpClientInterface`.
