### ISSUE TITLE
[symfony/workflow] Transaction from two or more states

### ISSUE THREAD

**Issue by DeRain** [symfony/symfony#29472]
**Symfony version(s) affected**: 4.1. symfony/workflow: 4.2

**Description**  
Hello. I've faced an issue when I placing two or more values in `from` section at transitions description in config. As far as I know, this is allowed, right? 

So I'm getting false negative results when trying to apply for state transfer with allowed `from` values.

**How to reproduce**  
After some research, I believe that the problem is in the following `buildTransitionBlockerListForTransition` method. The method just iterates all over places and creates `TransitionBlockerList` on first false condition. But as far as I get - method have to iterate over all forms and only then create `TransitionBlockerList` if needed.

Here is the reference on code that I've described above.
https://github.com/symfony/workflow/blob/master/Workflow.php#L247

**Possible Solution**  
Iterate over all places and create `TransitionBlockerList` only if `$marking->has($place)` have returned false for every `$place`

**Additional context**  
My workflow config
```yaml
framework:
    workflows:
        payment:
            type: 'workflow'
            supports:
                - App\Entity\Payment
                - App\Entity\RecurringPayment
            initial_place: new
            marking_store:
                type: 'single_state'
                arguments:
                    - 'status'
            places:
                - new
                - accepted
                - error
                - declined
                - pending
                - refunded
                - cancelled
            transitions:
                pending:
                    from: new
                    to: pending
                accepted:
                    from: [new, pending, accepted]
                    to: accepted
                refunded:
                    from: accepted
                    to: refunded
                cancelled:
                    from: [new, pending, accepted]
                    to: cancelled
                error:
                    from: [new, pending]
                    to: error
                declined:
                    from: [new, pending]
                    to: declined
```
