### ISSUE TITLE
Redirect with trailing slash

### ISSUE THREAD

**Issue by Groonya** [symfony/symfony#29477]
**Symfony version(s) affected**: 4.1.8, 4.2.0

**Description**  
I have 2 configured routes:
/foo
/foo/
The aim is to return 200 code in both cases.
Also from documentation:
> If your application defines different routes for each path (/foo and /foo/) this automatic redirection doesn't take place and the right route is always matched.

But since update to 4.1.8 or 4.2.0 one of them returns 301 redirect to another one.

**How to reproduce**  
My Yaml config:

```
foo:
  path: /foo/
  controller: App\Controller\MyController::action
foo_2:
  path: /foo
  controller: App\Controller\MyController::action
```
