### ISSUE TITLE
multi database use raw sql query: Unknown Entity namespace

### ISSUE THREAD

**Issue by lcp0578** [symfony/symfony#29496]
**Symfony version(s) affected**: 3.3.18

**Description**  

config.yml

```
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: 'UTF8'
            water:
                driver: pdo_mysql
                host: '%database_host_water%'
                port: '%database_port_water%'
                dbname: '%database_name_water%'
                user: '%database_user_water%'
                password: '%database_password_water%'
                charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    AdminBundle: ~
                    AppBundle: ~
                    BaseBundle: ~
                    SystemBundle: ~
            water:
                connection: water
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    WaterBundle: ~
                dql:
                    string_functions:
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat # only for DATE_FORMAT
           
```
WaterBundle/Repository/PayOrderRepository.php
```
return $this->getEntityManager()
        ->getConnection()
        ->executeQuery($sql , $param)
        ->fetchAll();
```
ORMException:
Unknown Entity namespace alias 'WaterBundle'.
![image](https://user-images.githubusercontent.com/10859621/49641753-0ac5e500-fa4c-11e8-80fe-da238e5e37ea.png)
