### ISSUE TITLE
[DependencyInjection] method calls with two EntityManagerInterefaces

### ISSUE THREAD

**Issue by thomas2411** [symfony/symfony#29548]
**Symfony version(s) affected**: 4.2.0

**Description**  
When I try to define calls via services.yaml for a Trait with two EntityManagerInterefaces, where each of them has different connections, both of them are called with default EntityManager.

**How to reproduce**  
```
trait StatisticsTrait
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * @required
     * @param EntityManagerInterface $entityManager
     */
    public function setEntityManager(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @var EntityManagerInterface
     */
    private $entityStatsManager;

    /**
     * @required
     * @param EntityManagerInterface $entityStatsManager
     */
    public function setEntityStatsManager(EntityManagerInterface $entityStatsManager)
    {
        $this->entityStatsManager = $entityStatsManager;
    }
}
```
```

services:
    App\Controller\Commont\StatisticsTrait:
        calls:
            - method: setEntityStatsManager
              arguments:
                  - '@doctrine.orm.stats_entity_manager'
            - method: setEntityManager
              arguments:
                  - '@doctrine.orm.default_entity_manager'
```

This service: ```@doctrine.orm.stats_entity_manager``` has different connection to different database than the ```@doctrine.orm.default_entity_manager```.

Unfortunately ```setEntityStatsManager``` passes ```@doctrine.orm.default_entity_manager``` instead of ```@doctrine.orm.stats_entity_manager```

When I make the same situation when passing those two managers to Controller, everything is OK but not for the Trait.
