### ISSUE TITLE
No working form authentication on a pattern

### ISSUE THREAD

**Issue by wuppiboy9** [symfony/symfony#29551]
I got multiple firewalls with different providers.
When I try to use my secured_area auth type as form_login it always redirects me to the login form with no error messages.

**my security.yml file:**
        

```
 secured_area:
             pattern: ^/admin
             provider: in_memory
             form_login:
                 login_path: app_login
                 check_path: app_login
             guard:
                 authenticators:
                     - App\Security\LoginFormAuthenticator
```
 

I've used the maker-Bundle to create the Controller and Security component.
It takes me to http://my-site.local/login instead of /admin/login.

When I try to change the routing manually chromes throws an exception for redirection too often.

What am I doing wrong in the security.yml file?
