### ISSUE TITLE
Symfony 4 Route Error. The route is wrongly configured

### ISSUE THREAD

**Issue by barricade86** [symfony/symfony#29557]
**Symfony version(s) affected**: 4.2.1

**Description**  
17 days ago i've posted bug(https://github.com/symfony/symfony/issues/29294)
Unfortunately the problem is solved partially:
1) URI is OK: /catalog/large_and_small_appliances/
2) URI os not OK:/catalog/large_and_small_appliances/large_appliances/

**How to reproduce**  
Repo:https://github.com/barricade86/symfony_bug_reproducing
Controller:https://github.com/barricade86/symfony_bug_reproducing/blob/master/src/Controller/CatalogController.php#L9
Route:https://github.com/barricade86/symfony_bug_reproducing/blob/master/config/routes.yaml#L9

**Comment by chiqui3d** [comment]
```
catalog_route:
    path: /{siteSection}/{categoryPath}/
    controller: App\Controller\CatalogController::index
    requirements:
        siteSection: 'catalog|discount'
        catgeoryPath: '([\d\w-]+\/*?){2,4}'
```

Check that the problem is not that it is misspelled categoryPath in requirements
