### ISSUE TITLE
[DI] Add Tags Conditionally 

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#29638]
Sometimes we want to register an event subscriber only on a specific environment (e.g. prod). The natural way to accomplish this is to inject the environment to the subscriber and check if the listener should be executed in that environment. If isn't 
the case of execute that listener, two things happen: a) the listerner is unnecessary registered on dispatcher service b) the listener is unnecessary dispatched and will be listed as a dispatched listener on profiler

**Suggestion:**

Add tags for services conditionally like this:

```yml
My\\ProductionOnly\\EventSubscriber:
    auto_configure: false
    tags:
        - {name: "event.subscriber", condition: "@=parameter('kernel.env') === 'prod'"}

My\\DevAndTestOnly\\RequestEventListener:
    auto_configure: false
    tags:
        - {name: "event.listener", event:"kernel.request", condition: "@=parameter('kernel.env') in ['dev','test']"}
```

With this configuration a compiler pass could remove from the service the tags that not match the condition. The result of this is a cleaner container (the service probably will be removed from the container) and less overhead. The same approach can be used to twig extensions, monolog handlers or any else service that could be registered conditionally.

If this suggestion makes sense, I'd like to contribute with this by opening a PR.
