### ISSUE TITLE
DateTime Validation: migration from 4.1. to 4.2

### ISSUE THREAD

**Issue by Narcotic** [symfony/symfony#29646]
Hello,

I am struggling to migrate some DateTime validations rules to version 4.2 of symfony/validator component. I would like to know the way to migrate this part:

```
App\Model\Person:
  properties:
    birthdate:
      - DateTime:
          format: d.m.Y
```
Thank you
