### ISSUE TITLE
[Messenger] send_and_handle does not work with enqueue transport

### ISSUE THREAD

**Issue by tkocjan** [symfony/symfony#29666]
**Symfony version(s) affected**: 4.2.1

**Description**  
I have a messenger.yaml configuration that works properly and calls two handlers when no routing is specified.
```
framework:
    messenger:
        transports:

        routing:
```

I then reconfigure messenger.yaml to just route message to RabbitMQ through enqueue transport and that works fine.
```
framework:
    messenger:
        transports:
            amqp: enqueue://default

        routing:
            'App\Core\Domain\Message\CreateSalesOrder':
                senders: [amqp]
                #send_and_handle: true
```

When I uncomment the send_and_handle line, the message goes to RabbitMQ but the handlers do not get called and I get the following error:
```No handler for message \u0022Interop\\Amqp\\Impl\\AmqpMessage\u0022.```

As you can see above, the message class is changed by going through enqueue.

The handlers are automatically hooked up to message through services.yaml:
```
    App\Core\Application\MessageHandler\:
        resource: '../src/Core/Application/MessageHandler'
        tags: ['messenger.message_handler']
```

Source code branch is available here if you need to look at anything:
https://github.com/tkocjan/Symfony4-Messenger-Async-Jobs/tree/add_enqueue
