### ISSUE TITLE
Support php 7.1 session options in 3.4 LTS

### ISSUE THREAD

**Issue by pravdinalex** [symfony/symfony#29830]
**Symfony version(s) affected**: 3.4.21

**Description**  
in php 7.1. new session options - sid_length, sid_bits_per_character were added.
http://php.net/session.configuration

There are closed / merged issues that should handle this changes
https://github.com/symfony/symfony/issues/21606
https://github.com/symfony/symfony/pull/23128 
but I can still reproduce error in version 3.4 LTS with php 7.2.13 on Ubuntu 16.04

**How to reproduce**  
1. clear install with symfony installer, create empty project
https://symfony.com/doc/3.4/setup.html

2. add framework.session.sid_length or sid_bits_per_character properties in /app/config/config.yml
```
framework:
	...
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        sid_length: 64
```
3. execute from console from project root
`php bin/console cache:clear --env=prod`
(or open index page in browser)

got: 

```
In ArrayNode.php line 307:
  Unrecognized option "sid_length" under "framework.session"
```

**Possible Solution**  
Only file affected in https://github.com/symfony/symfony/issues/21606 is NativeSessionStorage.php. I see changes in my local file, but anyway I got this error.

```
    public function setOptions(array $options)
    {
        ...
        $validOptions = array_flip(array(
            ...
            'sid_length', 'sid_bits_per_character', 'trans_sid_hosts', 'trans_sid_tags',
        ));
```

**Additional context**  

use_only_cookies is "Unrecognized option" too
