### ISSUE TITLE
Combination of excluded_http_codes and passthrough_level for monolog is confusing

### ISSUE THREAD

**Issue by rpkamp** [symfony/symfony#29904]
**Symfony version(s) affected**: 4.1+

**Description**  
When configuring a fingers crossed logger in Monolog that has both `excluded_http_codes` as well as a `passthrough_level` that is =< ERROR the http exceptions will be logged anyway because they are flushed in `\Monolog\Handler\FingersCrossedHandler::flushBuffer` due to their level being >= ERROR.

**How to reproduce**  
Put the following in `config/packages/prod/monolog.yaml`:
```
monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      passthru_level: notice
      handler: nested
      excluded_http_codes: [404]
```

**Expected result**
HTTP 404 exceptions should _not_ be logged

**Actual result**
HTTP 404 exceptions _are_ logged

**Possible Solution**  
Either:

1. Make this work, so suppress the exceptions regardless of the `passthru_level` - this probably won't be easy to do, but if this isn't done then at least:
2. A warning should be added to the docs https://symfony.com/doc/current/logging/monolog_exclude_http_codes.html (and also https://symfony.com/doc/4.1/logging/monolog_regex_based_excludes.html) that the combination doesn't work.
