### ISSUE TITLE
custom driver_class config for doctrine not work

### ISSUE THREAD

**Issue by lichnow** [symfony/symfony#29993]
my config in `doctrine.yml`
```
doctrine:
    dbal:
        # configure these for your database server
        driver_class:  App\Exts\Doctrine\DBAL\Driver
        server_version: '5.7'
        charset: utf8mb4
        options:
             do: yes
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
```
when I dump `$this->em->getConnection()->getDriver()`,result is `Doctrine\DBAL\Driver\PDOMySql\Driver`,can not found my custom driver_class config,but others config like `options` can be found use `$this->em->getConnection()->getParams()`

is it a bug?
