### ISSUE TITLE
Autowiring services in multiple config files 

### ISSUE THREAD

**Issue by christoschiliz** [symfony/symfony#30015]
Hey All,

I am using Symfony **4.2.2** and I stuck on a weird issue.

I am separating the services.yaml files under `config/services/` directory but is not autowiring bundle services.

First things first, I have a bundle that autogenerates based on a config file some services 

eg. in 
`config/packages/my_bundle.yaml`
I have
```
my_bundle:
  service1:
    argument1: '@dependency1' 

  service2:
    argument1: '@dependency2'          
```

The above services are generated correctly and can be used inside the main symfony project if the services that they using it are all inside the `config/services.yaml`. 

In case I separate them and move some of the services inside  `config/services/*.yaml` files it gets back with the following error:
 ```Cannot autowire service "App/Service1": argument "$interface" of method "__construct()" references interface "Bundle/Interface" but no such service exists. You should maybe alias this interface to one of these existing services: service1, service2```

services that implement the interface. 

The most weird thing is that is working in one file but not if I separate them it doesn't so I am not quite sure if I haven't configured something correctly.
  
Full example below:
**config/packages/my_bundle.yaml**
```

my_bundle:
  service1:
    argument1: '@dependency1' 

  service2:
    argument1: '@dependency2'          

```

**config/services/service1.yaml**
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

       App/Service1:
           bind:
                $service: '@service1' 
```

**config/services/service2.yaml**

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

       App/Service2:
           bind:
                $service: '@service2' 

```

Thank in advance for your help or suggestions.

**Comment by xabbuh** [comment]
Where do you define the service definition or the alias for `Bundle/Interface`?

**Comment by christoschiliz** [comment]
I initially defined it inside the Bundle but I've also tried to define it inside the main symfony project. When I did that with a `~`  ```Bundle\Interface: ~``` I got the same error. When I defined as a specific service eg. ```Bundle\Interface: '@service1'``` it worked but every dependency was an instance of `service1` even though I specified in the arguments the `service2`.

Thank you

**Comment by xabbuh** [comment]
I honestly do not follow your explanations. Can you show how your config looked like when it used to work (i.e. before the split)?

**Comment by christoschiliz** [comment]
ok so the below is the bundle config file:
**config/packages/my_bundle.yaml**
```my_bundle:
  service1:
    argument1: '@dependency1' 

  service2:
    argument1: '@dependency2'```

and this was the working version of services.yaml
```
parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

        App\:
            resource: '../src/*'
            exclude: '../src/{Entity,Migrations,Kernel.php}'

        App\Controller\:
             resource: '../src/Controller'
             tags: ['controller.service_arguments']     
        
        App/Service1:
            argument:
                $service: '@service1'

        App/Service2:
            bind:
                $service: '@service2' 
```

Everything is exactly the same except of the names and of course more services defined below.

I hope this makes more sense

**Comment by xabbuh** [comment]
I don't see where with that config `Bundle\Interface` would be defined.

**Comment by christoschiliz** [comment]
I didn't had to define it in this implementation again as it is defined in the bundle already.

**Comment by xabbuh** [comment]
Where and how in your bundle is that done?

**Comment by christoschiliz** [comment]
Inside the bundle I require the DependencyInjection Component and I do the below:
```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bundle\:
    resource: '../src/*'
    exclude: '../src/{DepedencyInjection}'
```
