### ISSUE TITLE
Internationalized routes in translation files

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#30098]
Hello,

It seems to be possible to translate routes only from routes configurations files.

Is there any reason that this was not implemented to be part of the translator so routes could be translated into translation files (including xliff)?

**Comment by nicolas-grekas** [comment]
There is always one reason you can be certain of: because nobody sent a PR to achieve so :)
If you want to give it a try, PR welcome as usual!

**Comment by sstok** [comment]
Now that it's part of the routing component it should not be to hard anymore, in the past bundles that provided this had to replace the routing service.

----

If you traverse all the collected routes and look-up their name in a translation service you can determine the translated values and update the route definitions accordingly. And don't forget about about default values!

Thinking of something like this for the translation file (per locale):

```yaml
# routes.en.yaml
route_name:
   path: # translated path
   defaults: {  } # note: these are merged into a single string like "route_name.defaults.name"
```

_I am leaving these notes here as an idea for anyone who wants to work on this, I don't have the time to do it myself._
