### ISSUE TITLE
[Validator] Load configuration file for array

### ISSUE THREAD

**Issue by vasilvestre** [symfony/symfony#30287]
**Description**  
Allow develop to configure an array constraint through YAML PHP or XML. It's actually possible to specify class so it gets bind to the class, but it could be useful to make it work with more data structure. 

**Example**  
```yaml
fields:
    foo:
        - Required:
            - NotBlank: ~
            - Email: ~
```
And kind of this : 
```php
$validator = Validation::createValidator();
$fileLocator = new FileLocator($configDirectories);
$yamlUserFiles = $fileLocator->locate('user.validator.yaml', null, false);

$fooArray = ['foo' => 'foo@dummy.tld];
$validator->validate($box, $yamlUserFiles);
```
