### ISSUE TITLE
[YAML] Bogus { } is not treated as an error 

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#30298]
**Symfony version(s) affected**: 4.2.3

**Description**  
Given the following YAML:
```yaml
access_control:
    - test: abc,
      ips:
        - 127.0.0.1
        - ::1
    - {
        test: abc
        ips:
          - 127.0.0.1
          - ::1
      }
    - {
        test: abc
        ips:
            - 127.0.0.1
            - ::1
      }
```

The output should be an error, while instead the code is parsed info

**How to reproduce**  
```php
dd(Yaml::parse("access_control:
    - test: abc,
      ips:
        - 127.0.0.1
        - ::1
    - {
        test: abc
        ips:
          - 127.0.0.1
          - ::1
      }
    - {
        test: abc
        ips:
            - 127.0.0.1
            - ::1
      }
"));
```

**Possible Solution**  
I'm not confident to dig into the YAML component parser ;)

**Additional context**  
The actual output looks like the following:

![image](https://user-images.githubusercontent.com/1227834/52977239-26296680-3392-11e9-8dc4-a72831beaa11.png)

This combined with the fact security component doesn't validate IPs caused a small headache ;)
