### ISSUE TITLE
SYMFONY 4.2.3 [Security] JSON login is not working as expected

### ISSUE THREAD

**Issue by Rbtsv2** [symfony/symfony#30378]
**Symfony version(s) affected**: 4.2.3

**Description**

In the POSTMAN software I write in the body the identifiers and password in json format to receive a JWT security token. Recently, I receive this type of message:

_The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned null. Did you forget to add a return statement somewhere in your controller?_

**How to reproduce**  
Controller APIController  : 

```php
    /**
    * @return Response
    **/
    public function login(Request $request)
    {
    }
```

My security.yaml : 

```yaml
login_json:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login: 
                check_path:               /api/login
                success_handler:        lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
```

My route.yaml file : 

```yaml
login_check:
    path: /api/login
    controller: App\Controller\APIController::login
    methods:  [POST]
```
