### ISSUE TITLE
Parse YAML file and inject it at build time

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#30386]
**Description**  

I saw many application with YAML parsing at runtime. I think we could help people with that, by parsing the file for them and inject the result instead.

**Example**  
```yaml
services:
    Foo\Bar:
        arguments:
            - !php/yaml path/to/yaml
```

WDYT ?
