### ISSUE TITLE
[Messenger] PhpSerializer with AmqpExt transport

### ISSUE THREAD

**Issue by bigfoot90** [symfony/symfony#30455]
**Symfony version(s) affected**: `dev-master`

**Description**  
Trying to use php's native serializer https://github.com/symfony/symfony/pull/29958 with amqp transport.
But ending with error 
```json
{
    "code": 0,
    "message": "Notice: Undefined index: headers",
    "file": "/srv/vendor/symfony/symfony/src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php",
    "line": 46
}
```

**How to reproduce**  
Configuration **messenger.yaml**:
```yaml
framework:
    messenger:
        serializer: messenger.transport.native_php_serializer

        transports:
            command: '%env(RABBITMQ_DSN)%/commands'
```
