### ISSUE TITLE
[FramworkBundle][Messenger] Not possible to overwrite transport options 

### ISSUE THREAD

**Issue by keulinho** [symfony/symfony#30463]
**Symfony version(s) affected**: 4.2.x

**Description**  
It is not possible to overwrite transport options for different environments. As the option config node is an aray node, the config values are deep merged resulting in array that can not be resolved by the OptionResolver.

**How to reproduce**  
overwrite transport options for a specific environment e.g. test:
```yaml
# in framework.yaml
framework
    messenger:
        transports:
            default:
                options:
                    receiveTimeout: 1000
```
```yaml
# in test/framework.yaml
framework
    messenger:
        transports:
            default:
                options:
                    receiveTimeout: 200
```
**Possible Solution**  
add `performNoDeepMerging()` to the array node solves the problem for me, but i don't know if that has any downsides or if the root cause of the problem is something else.
Maybe there are more config nodes this problem applies to.

**Additional context**  
Log looks like this:
```
Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException : The option "0" does not exist. Defined options are: "delayStrategy", "deliveryDelay", "priority", "queue", "receiveTimeout", "timeToLive", "topic".
 /app/vendor/symfony/options-resolver/OptionsResolver.php:747
```
The passed Options array looks like:
```php
[
    'receiveTimeout' => 1000,
    0 => 200
]
```

**Comment by sroze** [comment]
Indeed, it wouldn't work. We don't use the `performNoDeepMerging` option at all within the FrameworkBundle configuration for the simple reason that if the expected behaviour of "merging" will be different depending on the use-case.

Instead, you have two options:
1. Use a parameter and change it on test.
```yaml
# framework.yaml
parameters:
  receiveTimeout: 100
framework:
    messenger:
        transports:
            default:
                options:
                    receiveTimeout: "%receiveTimeout%"


# test/framework.yaml
parameters:
  receiveTimeout: 20
```

2. Copy again the entire options in your test YAML file.
