### ISSUE TITLE
[Routing] Implement host per locale

### ISSUE THREAD

**Issue by remmel** [symfony/symfony#30617]
**Description**  
Be able to configure host per locale in the same way that we can configure prefix per locale.
Thus we will be able to indicate that the 
- url beginning with www.website.es matches the locale **es** (spanish)
- url beginning with www.website.be/nl/ matches the locale is **nl_BE** (dutch of BELGIUM)

**History**  
[Prefix/path per locale is possibe from Symfony 4.1](https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing). Development has been done in that [PR](https://github.com/symfony/symfony/pull/26143).

**Vocabulary used**
In www.website.be/nl/offers/index.html :
- host:  `www.website.be`
- path-prefix: `/nl` (can be also named path/folder/directory/prefix)
- full-prefix: www.website.be/nl (host + path-prefix = full-prefix)

**Configuration**
Below are 2 examples of how to configure that, can we agree with one and how it will work ?

1. **Host + path-prefix in same configuration**
Set both the host and path-prefix (full-prefix) : 
```yaml
site:
    resource: '../src/Controller/'
    prefix:
        en: '/site'
        es: '://www.website.es'
        nl_BE: '://www.website.be/nl/'
    type: annotation
```
That above code without `es: '://www.website.es'` row and `://www.website.be` is working in Symfony 4.1

Note that we are using **://** to be able to detect later that the configuration is using a full-prefix and not only a prefix-path.

Questions:

- Must it begin with :// or //  ?
- Extract host from configuration :
  - starts with ":// => it's a full-prefix (host + path-prefix)
  - otherwise => it's only a path prefix
  - in the really specific case that we want to have the following url possible  www.website.com/://www.website.com/site/index.html only specifying the path-prefix the conf will be
```yaml
[...]
    prefix:
        en: '/://www.website.com/site'
```
  - Others solutions to detect that the conf starts with a host ?
    - regex?
    - the conf can only starts with
      - "/" for a path-prefix
      - "://" for a host or full-prefix
      - otherwise, it throws a configuration error
- What happens when the host is also on the non locale level ? (Eg: `@Route(host="www.website.com")` or `host: www.website.com`)
- Should we rename `prefix:`?
- In the above configuration what happens if url starts with `www.website.es/site` ? Throws a configuration error ? Thus mixing configurations will be possible if there is no "host" only configuration.

2. **Host in separate configuration**
```yaml
site:
    resource: '../src/Controller/'
    prefix:
        en: '/site'
        es: '/sitio'
    host:
        es: 'www.website.es'
    type: annotation
```
Questions:
- What happens when both the locale host and non locale host are set  ? Use the 1. locale host - 2. non locale host - 3. Throws an exception

Quick code to implement the feature with 1) conf :
YAMLFileLoader:197
```php
const URL_KEY = '://';
//if the it starts with ://
if (substr($localePrefix, 0, strlen(self::URL_KEY)) === self::URL_KEY) {
  $posFirstSlash = strpos($localePrefix, '/', strlen(self::URL_KEY));
  $localeHost = substr($localePrefix, strlen(self::URL_KEY), $posFirstSlash-strlen(self::URL_KEY));
  $localePrefix = substr($localePrefix, $posFirstSlash);
  $localizedRoute->setHost($localeHost);
}
```

Related with : 
- https://github.com/symfony/symfony/pull/26143
- https://symfony.com/doc/current/routing/hostname_pattern.html
- https://github.com/remmel/JMSI18nRoutingBundle

**Comment by ampaze** [comment]
I think, that **Host in separate configuration** is the way to go:

I don't use the prefix at all, as every language has its own domain. This already works good, as often the translation for the same url differs. But there are cases when they don't. 

If two languages share the same url, then the first matching language ist used, which of course is wrong.

To work around this, I wrote a custom HostFromLocaleYamlFileLoader that alway puts the current locales url on top of the list.

If I could defined the host per locale, when importing all routes then it would be much cleaner.
For example
```
routes:
    resource: "@...resource.yml"
  host:
    de: beispiel.de
    en: example.com
```

Also the domain should be matched with subdomains in mind. E.g. www.example.com and example.com.

**Comment by remmel** [comment]
> I don't use a prefix at all, as every language has its own domain

The option  **1. Host + path-prefix in same configuration** would also be possible:
```yml
site:
  resource: "@...resource.yml"
  prefix:
    de: '://beispiel.de'
    en: '://example.com'
```

> Also the domain should be matched with subdomains in mind. E.g. www.example.com and example.com

Currently Symfony matches with the [host](https://symfony.com/doc/master/routing/hostname_pattern.html) (sub-domain + domain), thus for the following configuration, calling _http://**www**.example.com_ won't match.
```yml
site:
    resource: ../../src/Controller/
    type: annotation
    host: "example.com"
```
You should open new issue, if you wan't to change that as this is not related to that new feature. Moreover if you want to match subdomain, you won't be able to handle that case : es.website.com / be.website.com / ...
