### ISSUE TITLE
routers.yaml   resource: 'my.yaml'   Symfony\Bundle\FrameworkBundle\Controller\TemplateController no work

### ISSUE THREAD

**Issue by githublirui** [symfony/symfony#30636]
//config/router.yaml
```yaml
app_file:
    resource: 'my.yaml'
    prefix: /router
    trailing_slash_on_root: false
```

//config/my.yaml
```yaml
no_controller_static:
    path: /page/static
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: twig/static.html.twig
    methods: GET
```
