### ISSUE TITLE
[RFC][DX][Workflow] Configuration of initial places and marking store

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony#30656]
**Description**  
1. In #30551, the marking store has been "simplified" internally, but the configuration is now more confusing (ref https://github.com/symfony/symfony/pull/30551#pullrequestreview-218035923).

2. In #30468, `initial_place` has been renamed `initial_places` but still supports passing one place that will be normalized to an array despite this single example in the [upgrade file](https://github.com/symfony/symfony/pull/30468/files#diff-037d6271f0e4d8020133ec3798988488R148). Also, this naming is now a bit confusing too, whether we can use it with one place is not obvious anymore.

**Proposition**  
1. Simplify the `method` type configuration which is the only one built-in we want to support now, and infer the single state from the type of the workflow, this leaves one argument to configure, the property name:
   ```yaml
   framework:
    workflows:
        article:
            type: state_machine # or workflow for multiple states
            marking_store:
                type: method # this line can be removed in Symfony 5.0
                property: state
   ```
   Instead of inferring we can use another key: `state` (single or multiple) along with `property`,
   or use a boolean as suggested by @pbowyer in the review linked above.

2. We could rename `initial_places` to something invariant like `initial_marking` or `initial_state`.

Any other suggestions? What do you think? ping @javiereguiluz @lyrixx
