### ISSUE TITLE
The default message bus name should start with `messenger.`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#30670]
Currently, the default bus name in the container is `message_bus`. It should probably be `messenger.message_bus`.

WDYT @sroze @weaverryan

**Comment by weaverryan** [comment]
The internal id is really not that important anymore (thanks to autowiring). So, this is definitely fine with me. But, what about `messenger.bus`... in case the user 

But, there is some other inconsistent maybe we should handle now:

```yml
framework:
    messenger:
        default_bus: bus1
        buses:
            bus1: ~
            bus2: ~
```

This creates the following services:
* `bus1`
* `bus2`
* `message_bus` (alias to `bus1`).

Perhaps it should be:

* `messenger.message_bus.bus1`
* `messenger.message_bus.bus2`
* `messenger.message_bus` (alias to `messenger.message_bus.bus1`).
