### ISSUE TITLE
Encoder not configure

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#30724]
**Symfony version(s) affected**: 4.2.4

The encoder "App\Encoder\Sha1SaltedEncoder" was not configured.

```php
security:
    encoders:
        sha1salted:
            id: 'App\Encoder\Sha1SaltedEncoder'

        'App\Entity\User': 'App\Encoder\Sha1SaltedEncoder'
```
not work

**Comment by chalasr** [comment]
It should be:

```yaml
security:
    encoders:
        sha1salted:
            id: App\Encoder\Sha1SaltedEncoder
        App\Entity\User: sha1salted
```
