### ISSUE TITLE
[DI] Compiler pass : can't replace a parameter with inheritance of services

### ISSUE THREAD

**Issue by FabienSalles** [symfony/symfony#30732]
**Symfony version(s) affected**: 3.4

**Description**  
I have some services which I want to override with a compiler pass. The services are defined in an external packages and contain an array parameter injected in the constructor. I just want to add a value in the array. Everything works fine except for a service that uses inheritance of services.

When I call the `getArguments()` method in the compiler pass I access only to the parameter inject in my child service (parameters defined in the parent service are not presents) so the index used for the replacement can't be correct.

**How to reproduce**  
I created a small project that contains the bug => https://github.com/FabienSalles/symfony-bug-on-compiler-pass

I have 3 services : 
```yaml
app.root_class:
    class: AppBundle\Example\MyRootClass
    arguments:
        - '@logger'

app.first_bugged_sub_class:
    class: AppBundle\Example\MySubClass
    parent: app.root_class
    arguments:
        - ['a first parameter', 'a second parameter']

app.second_bugged_sub_class:
    class: AppBundle\Example\MySubClass
    parent: app.root_class
    arguments:
        $additionalParameter: ['a first parameter', 'a second parameter']
```
When I launch the `bin/console debug:container` command on one of my child service I can see all parameters : 

```
Information for Service "app.first_bugged_sub_class"
====================================================

 ---------------- ------------------------------ 
  Option           Value                         
 ---------------- ------------------------------ 
  Service ID       app.first_bugged_sub_class    
  Class            AppBundle\Example\MySubClass  
  Tags             -                             
  Public           no                            
  Synthetic        no                            
  Lazy             no                            
  Shared           yes                           
  Abstract         no                            
  Autowired        no                            
  Autoconfigured   no                            
  Arguments        Service(monolog.logger)       
                   Array (2 element(s))
```

But if I want to use the compiler pass in order to change the second parameter (with an index of 1) I have an OutOfBoundsException because the argument does not exist (I just have 1 argument with an index of '0' instead of 2 with the method `getArguments()`

And if I use the '0' index I have another exception, a `ContextErrorException` because I try to insert an array instead of an object expected in my php class.

**Possible Solution**  
When we call the `getDefinition()` method of the `ContainerBuilder` class we should have access to the full definition of the service (with the parent instead of just the child definition).

**Additional context**  
I would like to use the compiler pass in order to override properly my services instead of redefining them in yaml and be linking to the whole definition of these services defined in an external package.
