### ISSUE TITLE
[Security] Interactive login event dispatched even with pre-authenticated token

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#30733]
**Symfony version(s) affected**: 3.4.23

**Description**  
I implemented an API auth mechanism [following the docs](https://symfony.com/doc/3.4/security/api_key_authentication.html), extending `SimplePreAuthenticatorInterface` and defining a stateless firewall for my `^/api` routes. This triggers a `security.interactive_login` event each time that an API is called, with obvious drawbacks in connection with FOSUserBundler, because it has [a listener that updates the user's last login timestamp](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/1049935edd24ec305cc6cfde1875372fa9600446/EventListener/LastLoginListener.php#L65-L68), hammering the DB with locks on the same rows.

**How to reproduce**  
[following the docs](https://symfony.com/doc/3.4/security/api_key_authentication.html) on API key auths:
 * Create an authenticator extending `SimplePreAuthenticatorInterface`
 * Return a `PreAuthenticatedToken` on auth success
 * Register a stateless firewall:
```yaml
    api:
      pattern: ^/api/
      stateless: true
      simple_preauth:
        authenticator: 'Acme\My\ApiKeyAuthenticator'
```

Do I have any way to avoid this behavior? Is this a bug or am I wiring something wrong?
