### ISSUE TITLE
[DependencyInjection] Add a "list" EnvProcessor

### ISSUE THREAD

**Issue by epourail** [symfony/symfony#30775]
**Description**  
Errors excepted, I did not see an EnvProcessor to convert a comma-separated list as an array.

**Example**
The following configuration :
```yaml
services:
  App\MyNamepsace\MyService:
    $arguments : 
        $myarray: %env(list:val1,val2,val3)%
```
should be inject as an array
```php
class MyService {
  public function __contruct(array $myarray) {
    ...
  }
}
```
where `$myarray = ["val1","val2","val3"]`

**Question/Suggestion** 
It should be better to control the separation character, but I don't see how to do that
