### ISSUE TITLE
Service configuration cannot distinguish between command bus and queries bus

### ISSUE THREAD

**Issue by lichnow** [symfony/symfony#30809]
**Symfony version(s) affected**: 4.2.x

**Description**  
I config the services for per bus,but command `bin/console debug:messenger` can not distinguish between command bus and queries bus
configure
```yaml
# services.yml
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    command_handlers:
        namespace: App\Message\Handler\Command\
        resource: '%kernel.project_dir%/src/Message/Handler/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    query_handlers:
        namespace: App\Message\Handler\Query\
        resource: '%kernel.project_dir%/src/Message/Handler/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.queries }

```
```
# messenger.yml
parameters:
    messenger.transport.default_serialization_context: {groups: [messenger]}
framework:
    messenger:
        transports:
            amqp_mailer: '%env(MESSENGER_TRANSPORT_DSN_MAILER)%'
            amqp_default: '%env(MESSENGER_TRANSPORT_DSN)%'
            # Uncomment the following line to enable a transport named "amqp"
#             amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
#             'App\Message\EmailNotification': amqp
            'App\Message\Interfaces\MailerInterface': amqp_mailer
            '*': amqp_default

        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - validation
                    - doctrine_transaction
            messenger.bus.queries:
                middleware:
                    - validation
            messenger.bus.events:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
```
the command response
```
Messenger
=========

messenger.bus.commands
----------------------

 The following messages can be dispatched:

 ------------------------------------------------------------------------
  App\DataPool\Transport\Auth\ValidationCode\MailCodeInput
      handled by App\Message\Handler\Command\SendRegistrationMailHandler
  App\DataPool\Transport\Auth\MailRegistrationInput
      handled by App\Message\Handler\Query\RegistrationByMailHandler
 ------------------------------------------------------------------------

messenger.bus.queries
---------------------

 The following messages can be dispatched:

 ------------------------------------------------------------------------
  App\DataPool\Transport\Auth\ValidationCode\MailCodeInput
      handled by App\Message\Handler\Command\SendRegistrationMailHandler
  App\DataPool\Transport\Auth\MailRegistrationInput
      handled by App\Message\Handler\Query\RegistrationByMailHandler
 ------------------------------------------------------------------------

messenger.bus.events
--------------------

 The following messages can be dispatched:

 ------------------------------------------------------------------------
  App\DataPool\Transport\Auth\ValidationCode\MailCodeInput
      handled by App\Message\Handler\Command\SendRegistrationMailHandler
  App\DataPool\Transport\Auth\MailRegistrationInput
      handled by App\Message\Handler\Query\RegistrationByMailHandler
 ------------------------------------------------------------------------
```
Is my configuration incorrect?
