### ISSUE TITLE
[RFC] env processor language

### ISSUE THREAD

**Issue by sukei** [symfony/symfony#30849]
**Description**  
While reading the blog post about the nice addition of the `url` and `query_string` env processor, I have spotted that the syntax was quite hard to read. There is two main issues IMHO: 

* The processors are wrote and chained from left-to-right while read by the user from right-to-left. `%env(key:user:url:MONGODB_URL)%` is written as "fetch the *key* named *user* from the parsed *url* of the env var named *MONGODB_URL*" while it seems easier to reason about it in the other direction.
* Some processors accepts parameters but uses the same lexeme to separate the processor name from the argument list as the one used to chain processors (`:`). Using both like `%env(key:user:url:MONGODB_URL)%` is ambiguous and requires a good understanding of every env processors to be read.

I propose to change this syntax to the following: `%env(MONGODB_URL|url|key:user)%` where the pipe char (`|`) is used to chain env processors (turning them into filters) and the colon char (`:`) to list and separate arguments.

**Example**  
```yaml
# before
mongo_db_bundle:
    clients:
        default:
            username: '%env(key:user:url:MONGODB_URL)%'
            connectTimeoutMS: '%env(int:key:timeout:query_string:MONGODB_URL)%'
```

```yaml
# after
mongo_db_bundle:
    clients:
        default:
            username: '%env(MONGODB_URL|url|key:user)%'
            connectTimeoutMS: '%env(MONGODB_URL|query_string|key:timeout|int%'
```

WDYT?
