### ISSUE TITLE
Exception: "You must configure the check path to be handled by the firewall using form_login in your security firewall configuration."

### ISSUE THREAD

**Issue by RSalo** [symfony/symfony#30856]
**Symfony version(s) affected**: 4.2.5

**Description**  
Hi. I try to do simply auth with guard without form_login as described in manual.
Exception:
```
You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.
```
and redirect to /login_check

**How to reproduce**  
```
security:
  encoders:
    FOS\UserBundle\Model\UserInterface: argon2i
  providers:
    main_provider:
      id: fos_user.user_provider.username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main_firewall:
      pattern: ^/admin/.*
      guard:
        authenticators: [App\Security\Authenticator\MainAuthenticator]
    site_firewall:
      pattern: ^/.*
      anonymous: true

  access_control:
     - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
```

**Possible Solution**  
Idk
