### ISSUE TITLE
[DI] Have a better DX for excluded resources

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#30865]
**Description**  

This [configuration](https://github.com/symfony/recipes/blob/1b63c59684594dad836e277eac931c04993afa6e/symfony/framework-bundle/3.3/config/services.yaml#L17-L21)  does not scale very well.

We end up creating smaller section by feature.
```yaml
AppBundle\Feature\:
    resource: '../../../src/Feature/*'
```

But At some point, it becomes complicated to maintain and we finish with something like:
```yaml

AppBundle\Feature\:
    resource: '../../../src/Feature/*'
    exclude: '../../../src/Feature/{Model,Foobar.php,Bar/Bar.php,James/James.php,James/Url.php,James/Link.php,James/Queue.php,James/Download.php}'
```

Instead, I could be nice to be able to use such syntax: 
```yaml
AppBundle\Feature\:
    resource: '../../../src/Feature/*'
    exclude:
        - '../../../src/Feature/Model/
        - '../../../src/Feature/Foobar.php
        - '../../../src/Feature/James/{James.php,Url.php,Link.php,Queue.php,Download.php}'
```

---

So to make it simple:
excludes should accept a string or an array of string.

WDYT ?
