### ISSUE TITLE
Provide alternative config options for deprecated templating options

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#30874]
**Description**  
In #21035 templating was deprecated, so we need to provide alternatives for some config options such as `framework.templating.hinclude_default_template`.

This is the full config dump of `templating`:

```yaml
framework:
    # templating configuration
    templating:
        enabled:              false
        hinclude_default_template: null
        cache:                ~
        form:
            resources:

                # Default:
                - FrameworkBundle:Form
        engines:              # Required

            # Example:
            - twig
        loaders:              []
```
