### ISSUE TITLE
[ProxyManagerBridge] Lazy services declaring the same class are not being constructed properly

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#31120]
**Symfony version(s) affected**: 4.2.5

**Description**  
Lazy services declaring the same class are not being constructed properly with `symfony/proxy-manager-bridge`

**How to reproduce** 
[Reproducer ref.](https://github.com/phansys/skeleton/blob/3d9e50194d33377a85ef57b7d9d5f624249c1621/config/services.yaml#L29-L41).
```yaml
services:
    App\Service\Foo:
        class: App\Service\BazInterface
        factory: ['App\Service\Qux', factory]
        arguments:
            - foo
        lazy: true

    App\Service\Bar:
        class: App\Service\BazInterface
        factory: ['App\Service\Qux', factory]
        arguments:
            - bar
        lazy: true
```

You can also checkout the reproducer and execute [this test](https://github.com/phansys/skeleton/blob/3d9e50194d33377a85ef57b7d9d5f624249c1621/tests/LazyServiceTest.php#L19).

**Additional context**  
```
$ bin/phpunit
#!/usr/bin/env php
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Testing Project Test Suite
F                                                                   1 / 1 (100%)

Time: 402 ms, Memory: 20.00MB

There was 1 failure:

1) LazyServiceTest::testFooService
Failed asserting that BazInterface_223af7b Object (...) is an instance of class "App\Service\Foo".
```

If I remove the requirement against `symfony/proxy-manager-bridge` or if I make these services non lazy, everything works as expected.

I previously proposed #31097 as a workaround for this problem, but since yet I'm not sure if this is just an autowiring problem or if this can affect non class based ids too, I think it deserves more analysis. I'll try to debug this issue by my side too.

Thank you.
