### ISSUE TITLE
[DI] Service defined in separate file is ignored

### ISSUE THREAD

**Issue by proArtex** [symfony/symfony#31150]
**Symfony version(s) affected**: 4.2.5

**Description**  
Issue is related to #30854
A Service defined in separate file (but not services_{env}.yaml) loose to autowiring in services.yaml

**How to reproduce**  
```
# config/services/extra.yaml
services:
    _defaults:
          autowire: true
          autoconfigure: true

    App\Foo:
        arguments:
            $bar: 'string'
```

```
# config/services.yaml
imports:
    - {resource: 'services/extra.yaml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```
Then I got a message `Cannot resolve argument $foo of "App\Controller\DefaultController::index()": Cannot autowire service "App\Foo": argument "$bar" of method "__construct()" is type-hinted "string", you should configure its value explicitly`

**Additional context**  
In same time moving  services/extra.yaml to services_dev.yaml will solve the problem. @nicolas-grekas [said](https://github.com/symfony/symfony/issues/30854#issuecomment-479569049) it depends on definition order but I would really expect autowiring has less priority than services defined by hands.
