### ISSUE TITLE
[DI] Give services defined by hands higher priority than wildcard defined ones.

### ISSUE THREAD

**Issue by proArtex** [symfony/symfony#31163]
**Description**  
This feature request is related to #31150.
Semantically I expect services defined by hands in any loaded file (independently from order) to override wildcard definition, because that services defined for a reason.

**Example**  
This will cause an exception, because wildcard defined service win as defined last. Same applies to hand definition in separate file (again because of the order) if we use imports.
```
# services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Foo:
        arguments:
            $bar: 'string'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
```

You would say "Change Kernel's loading order and feel good", but
wildcard construction semantically means "defaults" and that is why it placed at the beginning of the file. So why shouldn't we make it act as "defaults"? I'd like to hear Symfony users' opinion about it.

**Comment by linaori** [comment]
I expect the first defined to be the first configured, anything after that would override the existing definitions. To add this kind of configuration override priority would make things feel like magic; _"why is my service not as I configure it to be?"_. It adds a lot of complexity to the source as well. Right now if you want to override it, define it below the wildcard definition, this is clear behavior to me.

**Comment by ro0NL** [comment]
> wildcard construction semantically means "defaults" 

or not, i.e. today it means "a group of defined services" (hence the exclude option makes sense)

**Comment by stof** [comment]
> wildcard construction semantically means "defaults" and that is why it placed at the beginning of the file.

it is only placed at the beginning of the file if you do it like that. You can put such wildcard loading anywhere you want.

**Comment by Taluu** [comment]
I'm still :+1: on that. If you add a config in the `packages` directory (which is loaded before hand, as after all I'm developping a package more or less, which can have its own services definition, config, ... and so on), instead of adding more and more exclude rules, detecting that a service is already defined (by classname) would be a great thing IMO.

**Comment by mbabker** [comment]
You also then have to distinguish between a service "defined by hand" versus something where you're filling in a detail that can't be autowired.  I have a class with this constructor:

```php
namespace App\Mail;

final class MailSender
{
    private $contactEmail;
    private $mailer;

    public function __construct(\Swift_Mailer $mailer, string $contactEmail)
    {
        $this->mailer = $mailer;
        $this->contactEmail = $contactEmail;
    }
}
```

Because of autowiring, my "defined by hands" config only fills in the non-wired scalar param:

```yaml
App\Mail\MailSender:
    arguments:
        '$contactEmail': '%env(MAILER_SENDER_ADDRESS)%'
```

How does that work in the scenario you're trying to describe?
