### ISSUE TITLE
Resetabble services removed from container if not used

### ISSUE THREAD

**Issue by zmitic** [symfony/symfony#31176]
**Symfony version(s) affected**: 4.2

**Description**  
If service is not used anywhere but only autoconfigured via ResetInterface (or ResettableInterface), ~~it gets removed from container and~~ is not called during ``kernel.reset`` process

**How to reproduce**  
I used [swoole bundle](https://github.com/k911/swoole-bundle) and the results are impressive:
![image](https://user-images.githubusercontent.com/1964158/56387187-f37ddc00-6223-11e9-864d-a80838ef269d.png)

On the left side it is running ``server:run --env=prod``; swoole is on the right side.

This is my SPA bundle that doesn't require any frontend framework; I basically hijack all requests and render partial blocks like Angular. It is WIP, no caching (that's probably why speed diff is so big) but demo app can be downloaded from https://github.com/zmitic/spa-demo; keep in mind that code is bad but works.

I found the bug when CSS stopped rendering on full-page refresh, probably related to https://github.com/symfony/webpack-encore-bundle/issues/31

So to make quick fix, I made this service:

```php
 class EMResetter implements ResetInterface, ResettableInterface
{
    private $entryPointLookup;

    public function __construct(EntrypointLookupInterface $entryPointLookup)
    {
        $this->entryPointLookup = $entryPointLookup;
    }

    public function reset()
    {
        var_dump(123);
        $this->entryPointLookup->reset();
    }
}
```

but nothing happened, my page didn't get any CSS on page reload and nothing is dumped to console. 

But when I added this ``EMResetter`` as useless parameter to controller:
```php
/**
 * @Route("/", name="default")
 *
 * @Outlet(parent=null)
 */
public function index(CarRepository $carRepository, EMResetter $EMResetter): Response
{
    return $this->render('default/index.html.twig', [
        'cars' => $carRepository->findAll(),
    ]);
}
```

everything started to work.

Is there better way of doing this?

**Comment by stof** [comment]
the service resetter will not reset services if they haven't been instantiated already, as the intended usage would be that it resets itself, not that it is a services dedicated to resetting another service.

The solution here would be that the EntrypointLookup's reset method should be wired directly with `kernel.reset` instead (reported as https://github.com/symfony/webpack-encore-bundle/issues/62 as that totally makes sense).

But maybe we should also add a way to mark a resetter as needing to be a strong reference in case it would reset something else. What do you think @nicolas-grekas ?

**Comment by nicolas-grekas** [comment]
> mark a resetter as needing to be a strong reference in case it would reset something else

I'm not sure there is any use case for that. Especially because reset is called before the next request (not after finishing one). Fixing the bug in maker-bundle is the correct thing to do.

**Comment by zmitic** [comment]
>the service resetter will not reset services if they haven't been instantiated already, as the intended usage would be that it resets itself, not that it is a services dedicated to resetting another service.

That is the issue. Here is a bug in bundle and I am sure many other bundles would have same issue of not setting ``kernel.reset``.

The idea would be to allow users to make quick fixes, without waiting for fix in the bundle itself. For example; I have to leave this ugly solution (or empty ``kernel.terminate`` in same service) until https://github.com/symfony/webpack-encore-bundle/issues/62 is resolved.

Maybe something like ``HardResetInterface`` that will always be called, even when not instantiated. 

I am aware it is ugly solution but it will take some time till all developers think of PHP in long-running process so we need a patch.

**Comment by nicolas-grekas** [comment]
Wouldn't decorating the faulty service work?

**Comment by zmitic** [comment]
@nicolas-grekas 

Thank you, I wasn't thinking of that.

It worked so I am closing the issue. If someone stumbles on same problem:
 
```yaml
services:
    App\EventSubscriber\KernelReset\Resetter:
        decorates: 'webpack_encore.entrypoint_lookup[_default]'
```

```php
class Resetter implements ResetInterface, EntrypointLookupInterface
{
    private $lookup;

    public function __construct(EntrypointLookupInterface $lookup)
    {
        $this->lookup = $lookup;
    }

    public function reset(): void
    {
        $this->lookup->reset();
    }

    public function getJavaScriptFiles(string $entryName): array
    {
        return $this->lookup->getJavaScriptFiles($entryName);
    }

    public function getCssFiles(string $entryName): array
    {
        return $this->lookup->getCssFiles($entryName);
    }
}
```

**Comment by stof** [comment]
As the EncoreBundle service already supports being reset, it might be even better to use a compiler pass to add the missing tag on the service rather than using decoration. this way, you don't have the overhead of the decorator.

**Comment by zmitic** [comment]
@stof I tried that, it didn't work but there might be a problem in my code. 

This is what I used:

```php
// Kernel.php
protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
{
    $container->addCompilerPass(new class implements CompilerPassInterface {
        public function process(ContainerBuilder $container): void
        {
            $definition = $container->getDefinition('webpack_encore.entrypoint_lookup[_default]');
            $definition->addTag('kernel.reset', ['method' => 'reset']);
        }
    });
}
```

Container result:

![image](https://user-images.githubusercontent.com/1964158/56429737-4dce7980-62c4-11e9-81e4-d043cf46698f.png)

**Comment by zmitic** [comment]
Things are even weirder now. I forgot that I put this in Kernel:

```php
$container->getDefinition(Resetter::class)
    ->addTag('kernel.reset', ['method' => 'reset']);
```

Without that line, reset is not working. 

So decorating service and adding ``ResetInterface`` is not enough for ``kernel.reset`` to work, it must be manually tagged.

So I removed code from Kernel (for consistency) and updated ``services.yaml`` like this:

```yaml
services:
    App\EventSubscriber\KernelReset\Resetter:
        decorates: 'webpack_encore.entrypoint_lookup[_default]'
        tags:
            - { name: 'kernel.reset', method: 'reset' }
```

So maybe there is a bug after all. Should the issue be reopen?

**Comment by nicolas-grekas** [comment]
It's not a bug: the tag is added by auto-configuration, which need to be enabled.

**Comment by zmitic** [comment]
It is, I just didn't paste entire services.yaml. It is here, comments removed:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventSubscriber\KernelReset\Resetter:
        decorates: 'webpack_encore.entrypoint_lookup[_default]'
        tags:
            - { name: 'kernel.reset', method: 'reset' }
```
