### ISSUE TITLE
Loading a specific service class for a specific environment

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#31205]
I am not sure if this is a bug or an intended behaviour so keeping it as a "support question".

When my app is in `another` env mode, it should use services defined in `config/packages/another/services.yaml` rather than the ones in `config/services.yaml`. Currently the same service definitions are being overridden by `config/services.yaml` because it gets loaded last in `vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:load` - as a result `RealService` is being used in all envs.

- First of all is this an intended behaviour? To me env specific definitions shouldn't be overriden if user manually defined them. There is a purpose why he/she does.
- Second, how can I enforce (_in a clever way, not a duplicated way like parameters does (I could do it myself)_) `FakeService` class being used in `another` env only? All the other services should stick with `RealService`.

**structure**
```
config
  - packages
    - dev
      - services.yaml
    - test
      - services.yaml
    - another
      - services.yaml
  services.yaml
```

**config/services.yaml**
```
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\MyServiceInterface: '@App\Service\RealService'
```

**config/packages/another/services.yaml**
```
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\MyServiceInterface: '@App\Service\FakeService'
```

```
interface MyServiceInterface {}
class RealService implements MyServiceInterface {}
class FakeService implements MyServiceInterface {}
```
