### ISSUE TITLE
Folder exclusion won't work under `services:App\:exclude` key

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#31229]
Hi,

Left the comments in the code to make it easier to pinpoint the case for you. Technically I want to exclude `../src/Service/Mock` folder if the app is not in `mock` mode (`APP_ENV`). Wonder if this is bug or not? If not, is there a `if` solution for excluding folders?

Thanks

```yaml
parameters:
    app_env: '%env(resolve:APP_ENV)%'

services:
    # This won't work so the `../src/Service/Mock` folder is not being excluded
    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
            - '@=parameter("app_env") !== "mock" ? "../src/Service/Mock" : ""'
            - '@=container.getParameter("app_env") !== "mock" ? "../src/Service/Mock" : ""'

    # This works as `../src/Service/Mock` is the value passed to the service.
    App\Service\MyService:
        arguments:
            $exc1: '@=parameter("app_env") !== "mock" ? "../src/Service/Mock" : ""'
            $exc2: '@=container.getParameter("app_env") !== "mock" ? "../src/Service/Mock" : ""'
```

**Comment by BoShurik** [comment]
Workaround (or the right way?) would be:
```yaml
#services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Service/Mock,Kernel.php}'
```
```yaml
#services_mock.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Service\Mock\:
        resource: '../src/Service/Mock/*'
```
