### ISSUE TITLE
[HttpClient] Allow env variables in scoped_client base_uri

### ISSUE THREAD

**Issue by Devristo** [symfony/symfony#31223]
**Description**  
Currently it is not allowed to use env variables in the `base_uri` for `scoped clients`. Until now I used https://github.com/php-http/HttplugBundle. This bundle allows environment variables to easily target different endpoints. For example to target the staging environment for a micro-service.

**Example**  
It would be nice if it were supported in the symfony/http-client integration as well:

```yaml
framework:
  http_client:
        scoped_clients:
            http_client.demo:
                base_uri: "%env(DEMO_BASE_URI)%"
```
Is it desirable to support this?
