### ISSUE TITLE
[Messenger] deserialize third-party messages into a generic class for consumption

### ISSUE THREAD

**Issue by dvc** [symfony/symfony#31230]
Hello everybody!

**Description**  
I want to receive and handle messages **from 3rd party publishers** without required headers. 
May be some "global" fallback, and/or default type for every transport.

Can i?

**Example**  

Simple message with payload and without ['headers']['type'] throws error:
`'Encoded envelope does not have a "type" header.'`

**Comment by weaverryan** [comment]
Hey @dvc!

What you need for this is a custom transport serializer. Without the `type` header, we just can't know what type of object you want to deserializer into.

But, two more things:

1) In Symfony 4.3, you will be able to specify the serializer on a transport-by-transport basis. In 4.2 and earlier, there is only one "global" serializer for all transports.

2) Indeed, we *could* add some sort of feature to make this easier, so that you don't need to create a custom serializer for every situation. I'm not sure exactly how that should look.

**Comment by dvc** [comment]
Hello @weaverryan !

Thanks for comment. I don't think about custom serializer.  I can configure custom transport (for transport level customization ) to use custom Receiver logic (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpReceiver.php#L66).

But! It is interesting idea to support default deserialization type by Serializer configuration (concrete class, some generic object with array payload inside or just  stdClass/array).  Imho, it could be useful for some use cases. 

And after that allow to set/override this default in some messenger config. For example:

```
# config/packages/messenger.yaml
framework:
    messenger:
        default_type: 'array'
        transports:
            amqp: 
                 dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                 default_type: 'App\Entity\Message'
```

**Comment by weaverryan** [comment]
We can see if other people are also interested in something like this. It can already be accomplished currently (as we discussed), so it's a question of: is this common enough that we should make it *easier* to accomplish :).

Cheers!

**Comment by dvc** [comment]
Agree. Request for comments...

**Comment by sroze** [comment]
Indeed, creating your own serializer (decorating the default one for simplicity) is the best thing to do IMHO. Did you manage to do this? If so, can you share your piece of code so that others can get inspired?

**Comment by dvc** [comment]
May be serializer is best extension point. I have no work code yet.

In 4.2 default serializer has public static constructor: https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpReceiver.php#L35

So, i have to extend Symfony\Component\Messenger\Transport\Serialization\Serializer and override decode-method with some logic to set default type. Something like this:

```
<?php
declare(strict_types=1);

namespace App\Serializer;

use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Transport\Serialization\Serializer;

final class SerializerWithDefaultDecodeType extends Serializer
{
    /**
     * @var string
     */
    private $defaultDecodeType;

    public function setDefaultDecodeType(string $defaultDecodeType): void
    {
        $this->defaultDecodeType = $defaultDecodeType;
    }

    public function decode(array $encodedEnvelope): Envelope
    {
        if ($this->defaultDecodeType && empty($encodedEnvelope['headers']['type'])) {
            $encodedEnvelope['headers']['type'] = $this->defaultDecodeType;
        }
        parent::decode($encodedEnvelope);
    }
}
```

```
framework:
    messenger:
        transports:
            amqp.in: '%env(MESSENGER_TRANSPORT_DSN)%/rsa-request'
            amqp.out: '%env(MESSENGER_TRANSPORT_DSN)%/rsa-response'

        routing:
            'App\Rsa\Dkbm\Message\SayHello': amqp.in
            'App\Rsa\Dkbm\Message\SayHelloResponse': amqp.out

services:
    messenger.transport.amqp.in.symfony_serializer:
        arguments:
            - '@serializer'
        calls:
            - method: setDefaultDecodeType
                arguments:
                    - 'App\Rsa\Dkbm\Message\SayHello'

    messenger.transport.amqp.factory:
        arguments:
            $serializer: '@messenger.transport.amqp.in.symfony_serializer'
```

But this configuration affects also **amqp.out** transport and all amqp. Because of using Transport factory. Looks like serializer is not the best point in souch case.
