### ISSUE TITLE
[DIC] Improve error message when a service is badly configured

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#31265]
When make this typo:
```yaml
    App\Word\WordChecker:
        arguments:
            checkers:
                - '@App\Word\Checker\StaticWordChecker'
                - '@App\Word\Checker\BannedWorldListChecker'
```

The error is the following:

```
Invalid service "App\Word\WordChecker": the value of argument "checkers" of method "__construct()" must be null, an instance of Symfony\Component\DependencyInjection\Reference or an instance of Symfony\Component\DependencyInjection\Definition, array given.
```

Honestly, I don't understand the error. IMHO, we could improve it

We could add `Did you forgot to prefix $ to checkers` ?

(Question: Did you get the error at the first glance ? :joy: )
