### ISSUE TITLE
[FrameworkBundle] Controller resolver doesn't inject container for invokable controller (no specified method in route)

### ISSUE THREAD

**Issue by andrew-demb** [symfony/symfony#31271]
**Symfony version(s) affected**: 3.4.26

**Description**  

Got fatal `Call to a member function has() on null` due to not injected container (service locator) in controller, extended from `Symfony\Bundle\FrameworkBundle\Controller\AbstractController`.
Actual when in route I use DI service id for invokable controller.

**How to reproduce**  

Create controller
```php
<?php

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends AbstractController
{
    public function __invoke()
    {
        $hasRouter = $this->has('router');

        $response = $hasRouter ? 'router exists' : 'router not found';

        return new Response($response);
    }
}
```
Register in services:
```yaml
services:
    app.index_controller:
        class: IndexController
        public: true
```
Use in route:
```yaml
index:
    path: /
    controller: app.index_controller
```

Go to `/` path.

**Possible Solution**  
Change if statement to work with route without `:`-notation, and not only with array-callables.
https://github.com/symfony/symfony/blob/2774705c397778ae1bb4819a747cd8218d058e11/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L45

Workaround for me:
```yaml
index:
    path: /
    controller: app.index_controller:__invoke
```

**Additional context**
