### ISSUE TITLE
Improve a confusing error about fragments/hinclude/templating

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#31393]
**Symfony version(s) affected**: all

**Description**  
I'm updating a Symfony app to 4.2 + Flex. I'm converting the old app/config/config.yml into the new config/packages/*.yaml

When browsing the app, I saw this error:

![image](https://user-images.githubusercontent.com/73419/57221522-defd5a00-6fff-11e9-9a08-a42a53fd215f.png)

I had this in `config/packages/framework.yaml`:

```yaml
framework:
    # ...

    fragments:
        enabled: true
        path: '...'
```

There's no other config option to enable/disable "hinclude" specifically ... so I didn't know what to do.

Then, luckily, I remembered that I had deleted this when doing the config file conversion:

```yaml
framework:
    # ...
    templating:
        engines: ['twig']
```

Adding that solved the problem. But we should improve the error message, because it's very confusing and doesn't help find the solution. Thanks!
