### ISSUE TITLE
[Messenger] Message not sent to AMQP failure transport

### ISSUE THREAD

**Issue by raresserban** [symfony/symfony#31455]
**Symfony version(s) affected**: 4.3-beta1

**Description**  
After handling a message which fails, it will be retried 3 times. If all of those retries fail, then the message should be added to the failure transport (as explained here: https://symfony.com/blog/new-in-symfony-4-3-messenger-failure-transport)
However, for me at least, this is not the case.

I use the following configuration, but after the 3rd retry I can see this in the logs in this order:
`messenger.WARNING: An exception occurred while handling message CLASS... at vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:82 at MY_HANDLER_CLASS.`
`messenger.INFO: Rejected message CLASS will be sent to the failure transport failed.`
`messenger.INFO: Sending message CLASS with "Symfony\Component\Messenger\Transport\AmqpExt\AmqpTransport"...`
`messenger.CRITICAL: Rejecting CLASS (removing from transport). at vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:82 at MY_HANDLER_CLASS`

From what I see, the last `messenger.CRITICAL` error seems to come from the messenger component trying to call my handler again for some reason but I am not sure why. I use routing keys and also amqp for the failed queue, this is my configuration:

```yaml
messenger:
    failure_transport: failed
    transports:
        amqp:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            options:
                exchange:
                    type: topic
                    name: topic
                queues:
                   QUEUE:
                        binding_keys: ['KEY.#']
        failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        type: topic
                        name: topic
                    queues:
                        QUEUE_FAILED:
                            binding_keys: ['#']
```

I am really not sure why this does not work. What I also found out is that when the Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener is called, it does not remove the DelayStamp from the envelope, so when the message arrives in the Symfony\Component\Messenger\Transport\AmqpExt\Connection class, the `publishWithDelay` function will be called, which will publish the message again to the delay queue (`delay_queue_KEY.TEST_4000` in this case), with the exchange being `delay` and the routing key `delay_queue_KEY.TEST_4000`. Moreover, the delay queue is setup in the same way, with the routing key being my initial routing key `KEY.TEST` and the exchange name being `topic`, so the message will get published to the `QUEUE` queue not to the `QUEUE_FAILED` queue because of the routing key.

So how can this be prevented?Shouldn't the routing key be set to null before publishing to the `failed` transport, so that way I can put the QUEUE_FAILED to be bound for the null key? Or should I create an AmqpStamp using a middleware in this case, and add a new routing key for the failed transport?But then, why does the `failure_transport` config option even exist if it does not work properly?

**How to reproduce**  
Use routing keys for messages, have the handler fail 3 times and see the results. The message will not be added to the failure transport as intended.

**Possible Solution**  
Ignore all routing keys, exchanges etc when using the `failure_transport` config option when the message fails after the set number of retries, and have the failure_transport and no other transports be used for this situation.

**Comment by Tobion** [comment]
Can you test if it is enough to remove the DelayStamp in the SendFailedMessageToFailureTransportListener?

**Comment by Tobion** [comment]
Or maybe the better solution is to add a new DelayStamp with delay zero. So that the history is kept.

**Comment by raresserban** [comment]
I think I found the problem, according to the RabbitMQ docs, in order for the delay queue to work, there needs to be a subscriber active fore the destination queue:
https://www.cloudamqp.com/docs/delayed-messages.html

So in this case, I need to run the consume command for the failed transport and have it running for this to work.

The fix would be, like @Tobion said, to remove the DelayStamp in this case since it is not needed, since the message will be published to another transport and another queue.

**Comment by weaverryan** [comment]
@raresserban Just to verify that the fix, could you try it?

After this line: https://github.com/symfony/symfony/blob/e19db439d86bce4dd5f6e328cc435702b12e7a42/src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php#L69

Add `->withoutAll(DelayStamp::class)`

That may not be how we actually fix this - but that would verify that we're understanding the problem properly.

**Comment by weaverryan** [comment]
Btw, I added the `DelayStamp(0)` in #31425

**Comment by raresserban** [comment]
Hello, I tested with both `->withoutAll(DelayStamp::class)` and with `DelayStamp(0)` and I seem now to get a weird behavior. Each time the message fails and is added to a delay queue, it is also added to the failed queue.
And the message is for some weird reason processed 8 times instead of the 3 retries, so for one message I have 8 messages in the failed queue.
Might be because of me using routing keys, so maybe I can create a middleware for failed messages and change the routing key for them.

Anyways, the fix you did seems to fix the original issue.

**Comment by weaverryan** [comment]
Indeed, due to your routing keys, I'm not exactly sure what might be going on. What was the reason for adding all `binding_keys`?

**Comment by raresserban** [comment]
I found the problem, is was because I tested with `binding_keys: ['#']`, so all messages published were also published to this queue. I changed this to `binding_keys: ['FAILED.#']` and use a middleware to change the routing key for failed messages.

**Comment by weaverryan** [comment]
Ok great! In general, for future readers, you should not need to do any binding key or routing key setup to get the failure transport to work: it manages setting all of that up correctly internally.

**Comment by shubaivan** [comment]
@raresserban could you provide please middleware example with `middleware` config please ?

**Comment by raresserban** [comment]
@shubaivan 
This is my middleware:
```php
class AmqpMiddleware implements MiddlewareInterface
{
    /**
     * Add the AmqpStamp to envelopes containing a BaseMessage object.
     *
     * @param Envelope $envelope
     * @param StackInterface $stack
     *
     * @return Envelope
     */
    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        $message = $envelope->getMessage();

        if ($message instanceof BaseMessage) {
            $envelope = $envelope->with(
                new AmqpStamp(
                    $message->getRoutingKey(),
                    AMQP_NOPARAM,
                    $message->getAttributes()
                )
            );
        }

        return $stack->next()->handle($envelope, $stack);
    }
}
```

BaseMessage is a DTO which has a routing key and attributes properties.

The middleware is just simply included like in the docs:

```yaml
messenger:
    buses:
        messenger.bus.default:
            middleware:
                - 'Automotive\MessagePublisherBundle\Middleware\AmqpMiddleware'
```
