### ISSUE TITLE
[Logger] Allow to handle stdout logging in a better way

### ISSUE THREAD

**Issue by eliecharra** [symfony/symfony#31556]
**Description**  
Since PHP 7.3, following bugs are now fixed in FPM, wich allow us to log worker output to stdout in a better "12 factor" way. 

* Logs are truncated when message length exceed 1024 https://bugs.php.net/bug.php?id=69031
* FPM prepend a warning string to worker output https://bugs.php.net/bug.php?id=71880

So, we could use Monolog `StreamHandler` when working with docker containers :

```
# config/packages/monolog.yaml
monolog:
    handlers:
        stdout:
            type: stream
            level: info
            path: 'php://stdout'
```

It works well (with a bit of [fpm config](https://github.com/kibatic/symfony-docker/blob/master/7.3/rootfs/etc/php/7.3/fpm/pool.d/www_kibatic.conf)) BUT ... in some case it cause several issues.

In some case a Symfony console command logs its output using the logger service instead of `OutputInterface`.
In that case the `ConsoleHandler` could be configured like below, and will allow to pass verbosity flags to commands (-v|vv|vvv) to have a fine grained control over command output.

```
# config/packages/monolog.yaml
monolog:
    handlers:
        stdout:
            type: stream
            level: info
            path: 'php://stdout'
        console:
            type: console
            level: info
            process_psr_3_messages: false
```

Above configuration **should not be used** as it could generated duplicate records to stdout.
`ConsoleHandler` is optional here, as the `stdout` handler will output to stdout too. 
But in that case, verbosity arguments passed to CLI are not taken into account.

When using `ConsoleHandler` beside a stream handler on stdout, when a console command is launched logs are output on stdout twice.

I tried to use only the console handler, but it logs nothing coming from http request through fpm.

**Problem: **

We cannot log to stdout and use `ConsoleHandler` in a proper way side by side.

**Possible improvements : **

* Like finger crossed handler, maybe we could allow to setup an activation strategy on stream handler to activate a given stream handler only in a web context (using SAPI const) ? But it look like a workaround rather than a real solution.
* Improve symfony documentation to offer a clean way to logs our app to stdout as more and more people are using containers.

Could we think about it to find a better way to handle this ?

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by carsonbot** [comment]
Just a quick reminder to make a comment on this. If I don't hear anything I'll close this.

**Comment by roslov** [comment]
It would be good to handle this somehow.

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by carsonbot** [comment]
Could I get a reply or should I close this?

**Comment by RafaelKr** [comment]
bump to prevent closing

**Comment by zoka123** [comment]
Would something like this do the job? Ignoring logs from the `console` channel in the `stdout` handler as these should be picked up by the `console` handler

```diff
# config/packages/monolog.yaml
monolog:
    handlers:
        stdout:
            type: stream
            level: info
            path: 'php://stdout'
+           channels: ["!console"]
        console:
            type: console
            level: info
            process_psr_3_messages: false
```

**Comment by mathroc** [comment]
ideally when executing a command with the console, I'd like monolog to only use the console handler. I could always use a type "group" handler if I want to log to multiple place from the console too (eg:a stream to "%kernel.logs_dir%/%kernel.environment%.log")

I know this is a BC break so I don't know how this could be handled nicely however

**Comment by ro0NL** [comment]
this is seriously annoying :)

**Comment by dkarlovi** [comment]
The idea I had was to have something like this

```yaml
monolog:
    handlers:
        console:
            type: console
            level: info
            process_psr_3_messages: false
            stop_propagation: true  # new
        stdout:
            type: stream
            level: info
            path: 'php://stdout'
```

This would mean the console handler would trigger in console (interactive or not). It could decide to "eat" the message (if it handles it) or pass it through, even if invoked. The verbosity flags would work too and you could in theory have it run or not depend on interactivity and verbosity.

**Comment by ro0NL** [comment]
there's already a `bubble: false` option to achieve that IIUC

the main issue in our case is we lose logging persistence from a dedicated stream handler (now writing to stderr) that uses JSON format

in that sense our use case is: always log some channels, while still using the console handler for on-demand display usage in LINE format

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by zerkms** [comment]
Not stalled.

**Comment by ro0NL** [comment]
using https://github.com/relaxart/monolog-docker-handler/blob/master/src/DockerMonologHandler.php worked well for us

**Comment by toby-griffiths** [comment]
I'd like to see something done around this as well as this is a challenge I was trynig to wrap my head around late last night.

Sometimes we want to run a command in a terminal and see the output in human form.  In some cases not log to stderr of the Docker container to have it picked up in the Docker logs, but maybe have the option to somehow.

Sometimes we want to run scheduled tasks, where we're not sat in front of the console, and so want the output to be send to the logging platform/Docker logs, in JSON format (as per out standard stream handler format) to browse at a later date.

I've thought about an event listener that adds global cmd options to allow this to be specified at runtime, but it's just an idea with not enough time to test right now.

**Comment by romaricdrigon** [comment]
I have exactly the same issue, and how to solve it is not straightforward.

Regarding proposed solutions from above, excluding `console` channel as suggested by @zoka123 does not seem to work. And I thought of using `bubble: false`, a bit like @dkarlovi suggested, no use either. So another solution is still needed :(
I believe it has to be implemented Symfony-land, maybe in monolog-bundle, as only Symfony knows its context - web or console. Still I find challenging to imagine something working in all use cases.

**Comment by renepupil** [comment]
```YAML
# config/services.yaml
when@prod:
    # Overwrite the 'monolog.handler.console' service to get "console" logs in HTTP request context:
    App\Monolog\Handler\AppConsoleHandler:
      decorates: 'monolog.handler.console'
```

```PHP
<?php

declare(strict_types=1);

namespace App\Monolog\Handler;

use Symfony\Bridge\Monolog\Handler\ConsoleHandler;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Output\StreamOutput;

class AppConsoleHandler extends ConsoleHandler
{
    /**
     * @param array<string, string> $verbosityLevelMap
     * @param array<string, mixed> $consoleFormatterOptions
     */
    public function __construct(
        ?OutputInterface $output = null,
        bool $bubble = true,
        array $verbosityLevelMap = [],
        array $consoleFormatterOptions = []
    ) {
        // In case of a normal HTTP request, use stream output.
        $output ??= new StreamOutput(
            fopen('php://stdout', 'w'),
            OutputInterface::VERBOSITY_VERY_VERBOSE # Necessary to get all logs from level INFO and upwards, see https://symfony.com/doc/5.x/logging/monolog_console.html
        );
        parent::__construct($output, $bubble, $verbosityLevelMap, $consoleFormatterOptions);
    }
}
```
