### ISSUE TITLE
[DI] ChildDefinition and getArguments

### ISSUE THREAD

**Issue by er1z** [symfony/symfony#31561]
**Symfony version(s) affected**: dev-master and below (AFAIK)

**Description**  
If you create a definition with parent arguments overrides, any `CompilerPass` that depends on arguments mangling with fail if they are fetched via `getArguments` on `Definition`.

**How to reproduce**  
create a service with parent, for example:
```
parent:
    abstract: true
    class: SomeClass
    arguments: ['me', 'you']

child:
    parent: 'parent'
    class: SomeClass
    arguments:
        index_0: 'ME'
        index_1: 'YOU'
```

Then playing with definition in compiler pass produces:
```
$def = $container->getDefinition('child');
$def->getArgument(0);  // 'ME'
$def->getArguments()[0]; // 'me' (???)
```

**Possible Solution**  
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ChildDefinition.php#L74
Create overriden `getArguments` in `ChildDefinition` which will take into account its new arguments values first (as `getArgument` does).

**Additional context**  
This issue makes creation of admin prototypes in Sonata unusable because it relies on `getArguments` which ignores overriden arguments.

I can try to make adequate pull request if it's bug. Tried to figure it out on Slack but no one answered.

**Comment by xabbuh** [comment]
Reading the code I'd say something like this works as expected:

```yaml
parent:
    abstract: true
    class: SomeClass
    arguments: ['me', 'you']

child:
    parent: 'parent'
    class: SomeClass
    arguments:
        $foo: 'ME'
        $bar: 'YOU'
```

@er1z Can you confirm this? In this case I would say that this bug report is valid.
