### ISSUE TITLE
Monolog config option `excluded_http_codes` has no effect

### ISSUE THREAD

**Issue by pavlepredic** [symfony/symfony#31576]
**Symfony version(s) affected**: 4.2.8

**Description**  
Even after configuring monolog to exclude 404 errors, they still appear in the log.

**How to reproduce**  
`composer create-project symfony/skeleton symfony`
`cd symfony`
`composer require --dev symfony/web-server-bundle`
`composer require symfony/monolog-bundle`
```
cat <<'EOF' > config/packages/dev/monolog.yaml
monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_http_codes: [403, 404]
    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
EOF
```

`./bin/console server:run`

`curl http://127.0.0.1:8000/foo`
`cat var/log/dev.log`

Expected result: no log entries.
Actual result: 404 error appears in log.

**Additional context**  
Monolog version: 1.24.0
