### ISSUE TITLE
[DI] Misleading error when using php const in yml file

### ISSUE THREAD

**Issue by nfragnet** [symfony/symfony#31601]
**Symfony version(s) affected**: 3.4.21

**Description**  
I just had this small DX problem when using php const in validation yml files. 

The error encountered `The file "xxxxx" does not contain valid YAML.` : after several minutes I discovered that the yml was in fact valid but I had a typo in my const.

The exception is thrown in `vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/YamlFileLoader.php line 127`

**How to reproduce**  
```
# config/validator/validation.yaml
App\Entity\Participant:
    properties:
        firstName:
            - Length:
                min: !php\const App\Entity\Participant::MIN_LENGTH # this const does not exist
```

**Possible Solution**  
For a better understanding of the problem and DX improvement, it would be nice to have a more precise error (`Undefined class constant` for example) instead of malformed yml message.

The same occurs if I misspell the class FQCN : in this case I would expect a classic `Class not found` for example.
