### ISSUE TITLE
ValidatorException on Doctrine Proxy (Auto Validation Mapping?)

### ISSUE THREAD

**Issue by fabstei** [symfony/symfony#31715]
**Symfony version(s) affected**:
4.3 (Beta2 & RC1)

**Description**  
Handling a request with a form that has an assigned Entity seems to wrongly trigger a ValidatorException.

**How to reproduce** 
My apologies for the missing reproducer - I'm having issues creating it. since 4.3.0-RC1 is affected I thought sharing even without one could help.

```
        $entityManager = $this->getDoctrine()->getManager();
        $person = $entityManager->getRepository(Person::class)->findOneBy(['id' => $id]);

        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);
```
triggers
```
ValidatorException: Property "xyz" does not exist in class "Proxies\__CG__\App\Entity\Person"
```
in [PropertyMetadata.php#L39-L41](https://github.com/symfony/symfony/blob/v4.3.0-BETA2/src/Symfony/Component/Validator/Mapping/PropertyMetadata.php#L39-L41)

The stacktrace is here: https://gist.github.com/fabstei/ee254c7945ebc79fd3fed75cf4de82db

**Possible Solution**  
None so far. After uncommenting [PropertyMetadata.php#L39-L41](https://github.com/symfony/symfony/blob/v4.3.0-BETA2/src/Symfony/Component/Validator/Mapping/PropertyMetadata.php#L39-L41) everything works as expected, but it's obviously not a solution.

**Additional context**  
- Mac OS Mojave 10.14.5
- PHP 7.3.5

**Comment by ThomasTr** [comment]
Same for me, recently upgraded to 4.3.0, form with a EntityType, for now on, the properties of these entity must be public to avoid this exception?!?

**Comment by xabbuh** [comment]
Did you enable the new `auto_mapping` feature (see #27735) or does it also happen without doing so?

**Comment by pbowyer** [comment]
It happens without enabling `auto_mapping`. For my project it's been a straight switch of `4.2.*` to `4.3.*` in `composer.json`; only other changes are to clean up deprecations with the Workflow component.

**Comment by ThomasTr** [comment]
For me, auto_mapping was already enabled without any issues prior to 4.3.0

**Comment by pbowyer** [comment]
> Did you enable the new auto_mapping feature

I can't find any docs on how this new feature is enabled/disabled; the only `auto_mapping` I find is in `doctrine.yaml` which in my project is:
```
doctrine:
    orm:
        auto_mapping: true
```
This was auto-generated when first creating the project using Symfony 4.2.2.

**Comment by xabbuh** [comment]
I mean the new `framework.validation.auto_mapping` option (see https://github.com/symfony/symfony/blob/4.3/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L850).

**Comment by pbowyer** [comment]
I have not set it, and it isn't present in the config files. 

Running `bin/console debug:config framework` gives:
```
framework:
    # ...
    validation:
        email_validation_mode: html5
        enabled: true
        enable_annotations: true
        static_method:
            - loadValidatorMetadata
        translation_domain: validators
        mapping:
            paths: {  }
        not_compromised_password:
            enabled: true
            endpoint: null
        auto_mapping: {  }
```
