### ISSUE TITLE
Error: Method ReflectionMethod::__toString() must not throw an exception, caught ErrorException: Warning: Use of undefined constant STDERR - assumed 'STDERR' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by k00ni** [symfony/symfony#31727]
**Symfony version(s) affected**: 4.2.8, 4.3

## Description
I have a controller calling an action and showing some HTML using Twig. When changing something in `src` i get 2 errors, each after a reload, before the site works again.

## How to reproduce

**Steps to reproduce:**
* i change something in my src folder and reload the page
* it shows me the first error, as pictured in the *Additional Context* section
* After a reload, it shows me the second error, as pictured in the *Additional Context* section
* After the third reload the site works fine

**Further notes about my setup:**
* no changes in Kernel.php or public/index.php
* files are minimal, no further external references i can think of
* i used major files from an old Symfony 4.0 project, maybe i forgot important adaptions?
* PHP 7.2.12, with xdebug

**Controller**

```php
<?php

class Places extends AbstractController
{
    /**
     * @Route("/admin/places/place/update/{id}", name="admin-places-place-update", defaults={"id": null})
     */
    public function update(string $id = null): Response
    {
        $manager = $this->getDoctrine()->getManager();

        return $this->render('admin/places/place/update.html.twig', [
        ]);
    }
}

```

**update.html.twig Template**

```html

{% extends 'admin/base.html.twig' %}

{% block body %}

<br/>
<br/>
<br/>

<h1>Neue Einrichtung aufnehmen</h1>

<form action="" method="post">
    <button type="submit" class="btn btn-primary">Speichern</button>
    <input type="hidden" name="mode" value="TODO">
</form>

{% endblock %}
```

**services.yaml**

```yaml

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    #
    # System ----------------------------------------------------------------------------------
    #

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    #
    # Core ------------------------------------------------------------------------------------
    #

    # makes classes available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Localdetails\:
        resource: '../src/Localdetails/*'
        # exclude: '../src/{Tests}'

    Curl\Curl:
        public: false

    # https://www.doctrine-project.org/projects/annotations.html
    Doctrine\Common\Annotations\AnnotationReader:
        public: true

    #
    # Crawler detection
    #
    Jaybizzle\CrawlerDetect\CrawlerDetect:
        public: true
        class: Jaybizzle\CrawlerDetect\CrawlerDetect

    #
    # FYI:
    # https://github.com/thephpleague/iso3166
    #
    League\ISO3166\ISO3166:
        public: true

    Monolog\Logger:
        public: true
        class: Monolog\Logger
        arguments: ['app']
    # doublicate of Monolog\Logger
    # this allows usage of $this->getContainer()->get('logger') inside a Console command
    logger:
        public: true
        class: Monolog\Logger
        arguments: ['app']

    Monolog\Formatter\JsonFormatter:
        public: true
        class: Monolog\Formatter\JsonFormatter

    #
    # Psr related configuration
    #
    Psr\Log\LoggerInterface:
        public: true
        class: Monolog\Logger

    #
    # Symfony
    #
    Symfony\Component\Console\Input\ArrayInput:
        public: false
        arguments: [[]]

    Symfony\Component\Console\Output\NullOutput:
        public: false

    Symfony\Component\HttpFoundation\ParameterBag:
        public: false

```

**composer.json**:

```json
{
    "authors": [
        {
            "name": "xxx",
        }
    ],
    "require": {
        "php": "^7.2.12",
        "ext-iconv": "*",
        "doctrine/annotations": "^1.6.1",
        "jaybizzle/crawler-detect": "^1.2",
        "league/iso3166": "^2.1.1",
        "php-curl-class/php-curl-class": "^8.5.0",
        "pietercolpaert/hardf": "^0.1.3",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "^4.2.1",
        "symfony/cache": "^4.2.1",
        "symfony/console": "^4.2.1",
        "symfony/dotenv": "^4.2.1",
        "symfony/flex": "^1.2",
        "symfony/framework-bundle": "^4.2.1",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "^1.0",
        "symfony/property-access": "^4.2.1",
        "symfony/translation": "^4.2.1",
        "symfony/twig-bridge": "^4.2.1",
        "symfony/twig-bundle": "^4.2.1",
        "symfony/validator": "^4.2.1",
        "symfony/yaml": "^4.2.1",
        "twig/extensions": "^1.5",
        "twig/twig": "^2.10"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^2.14",
        "php-mock/php-mock": "^2.0",
        "php-mock/php-mock-phpunit": "^2.1",
        "phpunit/phpunit": "^7.3",
        "symfony/maker-bundle": "^1.11",
        "symfony/stopwatch": "^4.2.1",
        "symfony/web-profiler-bundle": "^4.2.1",
        "symplify/easy-coding-standard": "*",
        "wmde/psr-log-test-doubles": "^2.2"
    },
    "prefer-stable": true,
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "Localdetails\\": "src/Localdetails/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Localdetails\\Tests\\": "tests/Localdetails/"
        }
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "id": "xxxx",
            "allow-contrib": false
        }
    }
}

```

## Possible Solution / Workaround

When i add the following code:

```php
if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'r'));
if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'w'));
if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'w'));
```

 **before** [ReflectionClassResource->generateSignature](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Resource/ReflectionClassResource.php#L144) gets called, like in `index.php`, no error occurs!

Idea from: https://stackoverflow.com/questions/17769041/notice-use-of-undefined-constant-stdout-assumed-stdout

## Additional context

First time i get this error page:

![first-time](https://user-images.githubusercontent.com/381727/58623245-daaa2100-82cd-11e9-9604-debefe3f76fa.png)

---

After the reload i get:

![second-time](https://user-images.githubusercontent.com/381727/58623273-e5fd4c80-82cd-11e9-8825-8423ab955f8d.png)

---

Thanks for your time!
