### ISSUE TITLE
[Mailer][DX] Unable to set global sender email

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#31733]
Currently looks like its not possible to set global sender without setting sender in message
I tried to set sender globally with:
```yaml
Symfony\Component\Mailer\EventListener\EnvelopeListener:
    arguments:
        $sender: '%sender%'
```
and create message with:
```php
$message = new Email();
$message
    ->to($email)
    ->text('Hello world')
;
```
but got `Cannot send message without a valid envelope. (Unable to determine the sender of the message.)` because `MessageEvent` dispatched after `SmtpEnvelop` created in [AbstractTransport](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Mailer/Transport/AbstractTransport.php#L60-L69)

so I need to fill sender with a dummy email:
```php
$message = new Email();
$message
    ->from('noreply@example.com')
    ->to($email)
    ->text('Hello world')
;
```
