### ISSUE TITLE
[Mailer] Add a way to intercepts emails and save them in filesystem

### ISSUE THREAD

**Issue by Kocal** [symfony/symfony#31819]
**Description**  
My team and I are running E2E tests with [Cypress](https://www.cypress.io/) and we are checking if an email has been _sent_ (intercepted and saved on the filesystem) by checking the filesystem.

It works fine with SwiftMailer ([Spool Using a File](https://symfony.com/doc/2.5/cookbook/email/spool.html#spool-using-a-file)), but we have planned to migrate to the Mailer component and we don't see anything similar in the [documentation](https://symfony.com/doc/current/mailer.html).

**Example**  

Add support for `file` protocol, the next part is the directory where emails will be stored: 

```yaml
# config/packages/test/mailer.yaml
framework:
    mailer:
        dsn: 'file://%kernel.cache_dir/emails'
```

What do you think?
Thanks!
