### ISSUE TITLE
[Validator] Using new Positive constraint throw exception

### ISSUE THREAD

**Issue by lucraraujo** [symfony/symfony#31829]
**Symfony version(s) affected**: 4.3.0

**Description**  
When I tried to use the new Positive [Documentation](https://symfony.com/doc/current/reference/constraints/Positive.html) validation constraint in a yaml validation file, an exception is thrown.
```
[2019-06-03 14:20:41] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 2 passed to Symfony\Component\Validator\Mapping\ClassMetadata::addPropertyConstraint() must be an instance of Symfony\Component\Validator\Constraint, string given, called in pathToProject/vendor/symfony/validator/Mapping/Loader/YamlFileLoader.php on line 176" at pathToProject/vendor/symfony/validator/Mapping/ClassMetadata.php line 213 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 2 passed to Symfony\\Component\\Validator\\Mapping\\ClassMetadata::addPropertyConstraint() must be an instance of Symfony\\Component\\Validator\\Constraint, string given, called in pathToProject/vendor/symfony/validator/Mapping/Loader/YamlFileLoader.php on line 176 at pathToProject/vendor/symfony/validator/Mapping/ClassMetadata.php:213)"} []
```
When I add a tilde after the constraint, the problem vanishes, but the validation doesn't work, accepting non positive values.

**How to reproduce**  
```yaml
App\Entity\SomeEntity:
  properties:
    somePositiveInteger:
      - NotBlank: ~
      - Type: integer
      - Positive
```

**Additional context**  
When I add a tilde '~' after the constraint, the problem no longer occur, but the validation doesn't work, accepting non positive values.

**Comment by xabbuh** [comment]
The first error is caused by the YAML syntax not being valid. The correct notation would be this:

```yaml
App\Entity\SomeEntity:
  properties:
    somePositiveInteger:
      - NotBlank: ~
      - Type: integer
      - Positive: ~
```

I have submitted symfony/symfony-docs#11655 to fix the documentation.

But apart from that I cannot observe any issues. Could you please create a small reproducer application if you still experience any issues?
