### ISSUE TITLE
Restrict Handlers per Bus still not restricting

### ISSUE THREAD

**Issue by verschoof** [symfony/symfony#31909]
**Symfony version(s) affected**: 4.3.?

**Description**  
I register 2 command busses:
```
    default_bus: messenger.bus.commands
    buses:
      messenger.bus.commands:
        middleware:
          - doctrine_transaction
      messenger.bus.events:
        default_middleware: allow_no_handlers
```

`bin/console debug:messenger`
```
Messenger
=========

messenger.bus.commands
----------------------


 [WARNING] No handled message found in bus "messenger.bus.commands".


messenger.bus.events
--------------------


 [WARNING] No handled message found in bus "messenger.bus.events".


```

Looks good, now I go register the messages:

```
  App\EventSubscriber\:
    resource: './Application/EventSubscriber/*Subscriber.php'
    tags:
      - { name: messenger.message_handler, bus: messenger.bus.events }
```

result:
```
Messenger
=========

messenger.bus.events
--------------------

 The following messages can be dispatched:

 -----------------------------------------------
  App\Subscribers\Test
      handled by App\Subscribers\TestSubscriber
      handled by App\Subscribers\TestSubscriber
 -----------------------------------------------

messenger.bus.commands
----------------------

 The following messages can be dispatched:

 -----------------------------------------------
  App\Subscribers\Test
      handled by App\Subscribers\TestSubscriber
 -----------------------------------------------
```

I expect to get the result:
```
Messenger
=========

messenger.bus.events
--------------------

 The following messages can be dispatched:

 -----------------------------------------------
  App\Subscribers\Test
      handled by App\Subscribers\TestSubscriber
 -----------------------------------------------

messenger.bus.commands
----------------------

 [WARNING] No handled message found in bus "messenger.bus.events".

```

**How to reproduce**  
I created a repo: https://github.com/verschoof/symfony-messenger-bug
2 commmits; 1 setup default symfony 2 setup buses

**Comment by jvasseur** [comment]
This is because of the `autoconfigure` feature that automatically add the `messenger.message_handler` to class implementings the `MessageHandlerInterface` interface.

This is why your `TestSubscriber` is registered twice for the `messenger.bus.events` bus.

You should either disable `autoconfigure` when registering your handler:
```
  App\EventSubscriber\:
    resource: './Application/EventSubscriber/*Subscriber.php'
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: messenger.bus.events }
```

Or use plain classes for your message handlers instead of implementing the `MessageHandlerInterface` interface.
