### ISSUE TITLE
Can not provide explicit argument when autowire

### ISSUE THREAD

**Issue by zim32** [symfony/symfony#32087]
**Symfony version(s) affected**: 4

**Description**  
Hey guys, really annoying DI stuff. Spend three hours with no success.

I have separate file config/packages/custom_security.yml
which I imported from config/services.yaml like this

```
imports:
    - { resource: packages/custom_security.yml }
```

Content of config/packages/custom_security.yml:

```
services:
    Symfony\Component\Ldap\LdapInterface: '@Symfony\Component\Ldap\Ldap'

    App\Security\LdapUserProviderAdapter:
      autowire: true
      autoconfigure: true
      arguments:
        $password: 'ASDSD'
```

But got error:

**Cannot autowire service "App\Security\LdapUserProviderAdapter": argument "$password" of method "__construct()" is type-hinted "string", you should configure its value explicitly**

If I move same configuration to config/services.yaml, DI doesn't complain.

**How to reproduce**  
Create separate services files, import it from main services file, and try explicit argument

**Possible Solution**  

**Additional context**
