### ISSUE TITLE
[Workflow] Custom property in Marking Store not taken into account for State Machine

### ISSUE THREAD

**Issue by AirBair** [symfony/symfony#32084]
**Symfony version(s) affected**: 4.3.1

**Description**  
The _'property'_ attribute of the workflow marking store isn't taken into account when defining a state machine.

**How to reproduce**  

```
framework:
    workflows:
        writing_validation:
            type: 'state_machine'
            supports:
                - App\Entity\WritingHeader
            marking_store:
                type: 'method' # Same behavior when setted to single_state
                property: 'state'
```

Produce:
> The method "App\Entity\WritingHeader::getMarking()" does not exists.

But with deprecated attributes from the SF 4.2, _'arguments'_ **AND** _'type'_ forced to _'single_state'_ , no more error: 
```
framework:
    workflows:
        writing_validation:
            type: 'state_machine'
            supports:
               - App\Entity\WritingHeader
            marking_store:
                type: 'single_state'
                arguments:
                    - 'state'
```

Am i misunderstood something ? Thanks for your time.

**Comment by lyrixx** [comment]
Oups, it looks like a bug indeed ! I will fix it ASAP :) 
Thanks for the report !

**Comment by lyrixx** [comment]
Hello. I checked and I can not found a bug.

I tried to reproduce it with https://github.com/lyrixx/SFLive-Paris2016-Workflow 
I hit a bug, but legit since I hardcoded `{{ article.marking }}` in my template.
Once I update the template, everything goes fine.
I think you have the same issue in your code :)

I'm gonna clos this issue because there a no issue to me.
But If you thing there is, please give me a simple reproducer and I will have a look at it.

Thanks

**Comment by AirBair** [comment]
Hello,

I was able to reproduce the same error on your demo project but but I think it comes from a misunderstanding on my side about the default behavior.

I did not set the attribute '_type'_ under _'marking_store'_ and thought that the default value was _'method'_ since the other two (_'single_state'_ & _'multiple_state'_) are deprecated.

But it seems that _'single_state'_ is still the default and using it at the same time as the _'property'_ attribute causes the error. Is it the expected behavior ?

If my explanation is not clear, here is the commit with the modifications to reproduce the error: https://github.com/AirBair/SFLive-Paris2016-Workflow/commit/43f52bf6bc7d43fa59d79c841f9a0fa1145df348

The guide for the workflow in the documentation does not show the use of the new parameters instead of deprecated ones. I can try to make a pull request on docs but i want to be sure that i understood well the behavior.

Thanks for your time.

**Comment by lyrixx** [comment]
Actually, `type` and `property` could not work together.
It's document in the [upgrade file](https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.3.md#workflow):

---


 * `MultipleStateMarkingStore` is deprecated. Use `MethodMarkingStore` instead.

   Before:
   ```yaml
   framework:
       workflows:
           type: workflow
           article:
               marking_store:
                   type: multiple
                   arguments: states
   ```

   After:
   ```yaml
   framework:
       workflows:
           type: workflow
           article:
               marking_store:
                   type: method
                   property: states
   ```

 * `SingleStateMarkingStore` is deprecated. Use `MethodMarkingStore` instead.

   Before:
   ```yaml
   framework:
       workflows:
           article:
               marking_store:
                   arguments: state
   ```

   After:
   ```yaml
   framework:
       workflows:
           type: state_machine
           article:
               marking_store:
                   type: method
                   property: state
   ```
