### ISSUE TITLE
"Twig extension not enabled" error, even when extension functions are being found

### ISSUE THREAD

**Issue by toby-griffiths** [symfony/symfony#32097]
**Symfony version(s) affected**: 4.2.2

**Description**  
I've created an extension that include the `admin_menu()` function, and the autowiring is working to the extent that twig is not reporting that the `admin_menu()` function doesn't exist (which happens if I remove the parent class), however Twig it then reporting `extension is not enabled`, for some reason

**How to reproduce**  
```php
<?php
declare(strict_types=1);

namespace App\Twig\Extension;

use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class AdminMenuExtension extends AbstractExtension
{
    public function getFunctions(): array
    {
        return [
            new TwigFunction('admin_menu', [$this, 'renderAdminMenu']),
        ];
    }


    public function renderAdminMenu(): string
    {
        return 'admin_menu';
    }
}
```

… and don't include the class in your services.yaml file

**Possible Solution**  
Adding the class to your service.yaml file seems to resolve the problem…

```yaml
services:
    App\Twig\Extension\AdminMenuExtension: ~
```

**Additional context** 
n/a

**Comment by xabbuh** [comment]
I am not sure I understand your issue. Which parent class are you talking about?

**Comment by Simperfit** [comment]
@toby-griffiths could you please past the whole service.yaml ?

**Comment by xabbuh** [comment]
@toby-griffiths Do you have some update for us?

**Comment by Matts** [comment]
The error he saids is occurring is coming from the ExtensionSet::getExtension method

Maybe he is trying to fetch the Extension from a controller or something?

**Comment by cilefen** [comment]
The extension above works perfectly well in an ordinary Symfony app.

**Comment by toby-griffiths** [comment]
Apologies I've not responded sooner.  Here's the full `service.yaml` file, adn in so doing, wonder whether this is caused by my lazy load default…

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Service for storing user sessions in d/b
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }
            - { lock_mode: 1 }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DataFixtures,DependencyInjection,Entity,Migrations,TemplateData,Tests,ValueObject,Kernel.php}'
        lazy: true

    App\Config\Cookies\CookiesConfig:
        arguments:
            - security:
                  - name:           '%cookies.session.name%'
                    required:       true
                    lifespan_class: 'App\Config\Cookies\Lifespan\SessionLifespan'
                  - name:           'sf_redirect'
                    required:       true
                    lifespan_class: 'App\Config\Cookies\Lifespan\SinglePageLoadLifespan'
              personal_preferences:
                  - name:           '%cookies.display.name%'
                    required:       false
                    lifespan_class: 'App\Config\Cookies\Lifespan\DateIntervalLifespan'
                    lifespan_args:
                        - '1 year'
                  - name:           '%cookies.shortlist.name%'
                    required:       false
                    lifespan_class: 'App\Config\Cookies\Lifespan\DateIntervalLifespan'
                    lifespan_args:
                        - '1 year'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        lazy: false # DO NOT SET TO true, otherwise annotations don't work

    App\Controller\Service\EditServiceController:
        arguments:
            $session: '@Symfony\Component\HttpFoundation\Session\SessionInterface'
        tags: ['controller.service_arguments']

    App\DataFixtures\ORM\:
        resource: '../src/DataFixtures/ORM/{Common,Production}/*'

    App\Doctrine\PostGIS\Event\DBALSchemaEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Doctrine\ORM\Listener\SearchableEntityListener:
        tags:
            - name:  'doctrine.event_listener'
              event: 'onFlush'

    App\Event\Listener\AdminBarListener:
        tags:
            - name:    'kernel.event_listener'
              event:   'kernel.view'
              method:  'addAdminBarContent'
              priority: 99

    App\Google\Maps\GoogleMapsClient:
        arguments:
            $apiKey: '%env(GOOGLE_MAPS_API_SERVER_KEY)%'

    App\Http\Cookies\CookieManager:
        tags:
            - name:   'kernel.event_listener'
              event:  'kernel.response'
              method: 'onKernelResponseSetCookies'
        lazy: true

    App\Preferences\Shortlist\ShortlistManager:
        factory: 'App\SymfonyBridge\Shortlist\ShortlistManagerFactory::buildShortlistManager'
        lazy: true

    App\Repository\TaxonomyTermRepository:
        factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
        arguments:
            - 'App\Entity\TaxonomyTerm'

    App\Security\Sodium:
        arguments:
            - '%env(SODIUM_HASHED_KEY)%'
        lazy: true

    App\SymfonyBridge\EventListener\AccessDeniedListener:
        arguments:
            $session: '@session'
        tags:
            - name:   'kernel.event_listener'
              event:  'kernel.exception'
              method: 'onAccessDeniedExceptionRedirectToHomepage'


    # For some reason we need to manually include this otherwise we get an 'Extension is not enabled' error 
    # Bug: https://github.com/symfony/symfony/issues/32097
    App\Twig\Extension\AdminMenuExtension: ~

    App\UserPreference\Listener\NotifyOnUpdateListener:
        tags:
            - name:   'kernel.event_listener'
              event:  'user_preference.value_updated'
              method: 'offerToUseCookie'

    App\UserPreference\Type\DisplayUserPreferences:
        arguments:
            $sessionKey: 'display_preferences'
            $cookieName: '%cookies.display.name%'
        lazy: true

    App\UserPreference\Type\ShortlistPreference:
        arguments:
            $sessionKey: 'shortlist'
            $cookieName: '%cookies.shortlist.name%'
        lazy: true

    App\UserPreference\UserPreferenceManager:
        arguments:
            $userPreferences:
                - '@App\UserPreference\Type\DisplayUserPreferences'
                - '@App\UserPreference\Type\ShortlistPreference'
        lazy: true
```
