### ISSUE TITLE
The server:log command does not show logs

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#32111]
**Symfony version(s) affected**: 4.2

**Description**  
The logs are not shown while we launch `server:log`. The only way to show them is to add `-vvv` option.

**How to reproduce**  

```
// config/packages/dev/monolog.yaml
monolog:
    handlers:
        server_log:
            type: server_log
            host: 0:9911
```

And run `server:log`.

**Possible Solution** 

The ConsoleHandler checks the verbosity level. By default the normal verbosity maps to the warning level log. IMO, the `--filter` option should be the only one responsible of the level.

https://github.com/symfony/symfony/blob/dca9325e61cbe616ec2d5c83e83af0e948eba3a5/src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php#L146

**Additional context**
