### ISSUE TITLE
must be an instance of TraceableAdapter, instance of MemcachedAdapter given

### ISSUE THREAD

**Issue by zied-ellouze** [symfony/symfony#32134]
**Symfony version(s) affected**: 4.2.4
                                                                              
**Description**  
I have this error " Argument 2 passed to App\Repository\xxxxxRepository::__construct()   
  must be an instance of Symfony\Component\Cache\Adapter\TraceableAdapter, in  
  stance of Symfony\Component\Cache\Adapter\MemcachedAdapter given, called in  
   /var/www/html/symfony/var/cache/ppd/ContainerFVa8dFa/getxxxxxRepos  
  itoryService.php on line 16" when clear cache.

**How to reproduce**  
When use memache with dev environnement I don't have this error but when I change environnement to prod I have this error.

**Comment by xabbuh** [comment]
It looks you type-hinted an argument of your class constructor with `TraceableAdapter` which is not used in the `prod` environment. Changing the type-hint to `Symfony\Component\Cache\Adapter\AdapterInterface`, `Symfony\Contracts\Cache\CacheInterface`, or `Psr\Cache\CacheItemPoolInterface` should solve the issue.

**Comment by zied-ellouze** [comment]
Thank you @xabbuh 
What is weird that the same code used in several class, but this error is only raised for 2 classes.

**Comment by popnikos** [comment]
**Symfony version 3.4.28**

I have a similar issue, but with other instances, I've just follow instructions at https://symfony.com/doc/3.4/cache.html

-----
notice the cache.adapter.filesystem
```yml
# app/config/config.yml
framework:
    cache:
        app: cache.adapter.filesystem
```
-----

```yml
# app/config/parameters.yml
xxxxx:
        sw_host: 'http://any.hostdoma.in'
        dictionary:
            uri: /anyuri.php
            user: myusername
            password: astring
```

-----
```yml
# app/config/services.yml
app.xxxxx:
        class: AppBundle\Service\XxxxxService
        arguments:
            $xxxxx: "%xxxxx%"
            $cache: "@cache.app"
        public: true
```
-----

and my Service class in `src/AppBundle/Service/XxxxxService` : 
```php
namespace AppBundle\Service;

use Symfony\Component\Cache\Adapter\AbstractAdapter;

class XxxxxService
{
// ...
    public function __construct($xxxxx, AbstractAdapter $cache)
    {
        $this->params = (object)$xxxxx;
        $this->cache = $cache;
    }
}
```
-----

In `dev` environment I got the following `ContextErrorException` :
`Argument 2 passed to AppBundle\Service\SitimmoService::__construct() must be an instance of Symfony\Component\Cache\Adapter\AbstractAdapter, instance of Symfony\Component\Cache\Adapter\TraceableAdapter given, called in home/web/project_root/var/cache/dev/ContainerQ4xjyqq/getApp_SitimmoService.php on line 8 and defined at src/AppBundle/Service/XxxxxService.php:19`

I've tried the `php bin/console cache:pool:clear cache.app` and `php bin/console cache:clear` commands without any effect.

In prod environnement everything works fine, even after `cache:clear` console command

I'm stuck wondering why my cache.app is a TraceableAdapter
