### ISSUE TITLE
[Cache] Cannot configure chain adapter

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#32139]
**Symfony version(s) affected**: 3.4.x

**Description**  
When trying to configure a cache `ChainAdapter` I get the following error: 
```
Argument 1 passed to Symfony\Component\Cache\Adapter\ChainAdapter::__construct() must be of the type array, string given, called in /project/root/var/cache/dev/ContainerMdWoD6O/getCache_GlobalClearerService.php on line 20  
```

If I look in my container dump I see the following: 
```
$this->services['cache.app'] = new \Symfony\Component\Cache\Adapter\ChainAdapter('y7VTFBCVw+', 2419200))
```

**How to reproduce**  

```
composer create-project symfony/skeleton cache-issue
```
Add the following contents to `cache.yaml`:

```yaml
framework:
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name
        app: cache.chain
        pools:
            cache.chain:
                adapter: app.cache.adapter.chain

            cache.array:
                adapter: cache.adapter.array

            cache.apcu:
                adapter: cache.adapter.apcu


services:
    app.cache.adapter.chain:
        class: Symfony\Component\Cache\Adapter\ChainAdapter
        arguments:
            - [ '@cache.array', '@cache.apcu']
            - 2419200 # One month
```

**Possible Solution**  
I've debugged some but I cannot figure out a good solution nor the cause.

**Comment by dmaicher** [comment]
Seems this is related to this one?

https://github.com/symfony/symfony/issues/26954

**Comment by Nyholm** [comment]
Thank you. 

Yes. I think so. I’ll test and confirm. I’ll make sure to update the docs if fixed.

**Comment by Nyholm** [comment]
Hm.. There is definitely some weird behaviour here: 

This is my (semi) working example
```yaml
framework:
    cache:
        pools:
            cache.array:
                adapter: cache.adapter.array

            cache.apcu:
                adapter: cache.adapter.apcu

services:
    cache.app:
        class: Symfony\Component\Cache\Adapter\ChainAdapter
        arguments:
            - [ '@cache.array', '@cache.apcu']
            - 2419200 # One month
```

But if I try to add the `cache.pool` tag to my `cache.app` service then I'll get the same error. 

> Argument 1 passed to Symfony\Component\Cache\Adapter\ChainAdapter::__construct() must be of the type array, string given,

This is indeed because of [CachePoolPass line 109](https://github.com/symfony/symfony/blob/v4.3.1/src/Symfony/Component/Cache/DependencyInjection/CachePoolPass.php#L109)

This would be fine (but strange).. however, [other services](https://github.com/symfony/symfony/blob/v4.3.1/src/Symfony/Bundle/FrameworkBundle/Resources/config/cache.xml#L43) are using `cache.app` as their parent. And because of that I get an error again.

**Comment by Nyholm** [comment]
So with some help from Symfony Slack, I now know the following: 
- Not all adapters support being tagged with `cache.pool`
- ChainAdapter is one of those pools. 
- You can decorate the pool with ProxyAdapter to make sure it can be tagged. 


So, I can do something like this: 

```yaml
framework:
    cache:
        app: cache.chain
        pools:
             cache.chain:
                adapter: cache.adapter.psr6 # ProxyAdapter
                provider: my_chain_provider

            cache.array:
                adapter: cache.adapter.array

            cache.apcu:
                adapter: cache.adapter.apcu

services:
    my_chain_provider:
        class: Symfony\Component\Cache\Adapter\ChainAdapter
        arguments:
            - [ '@cache.array', '@cache.apcu']
            - 2419200 # One month
```

I've updated the PR to the docs: https://github.com/symfony/symfony-docs/pull/11813

Thank you for the help.
