### ISSUE TITLE
[Validation] Automatic validation for boolean columns

### ISSUE THREAD

**Issue by phpdev** [symfony/symfony#32168]
**Symfony version(s) affected**: 4.3.*

**Description**  
I try to enable "Automatic validation" feature but its not working well for me.
If column type is boolean, form component creating a html checkbox. After enable "Automatic validation", it's set to required. I cant select for "false". So, it will always "true".

https://symfony.com/blog/new-in-symfony-4-3-automatic-validation

**How to reproduce**  
Symfony 4.3 + EasyAdmin Bundle

**Possible Solution**  
If input type is checkbox(doctrine type boolean), it should be not required.

**Additional context**  
- "symfony/property-info" is installed.
```yaml
framework:
    secret: -secret-
    profiler: { only_exceptions: false }
    validation:
        auto_mapping:
            App\Entity\: []
```
```php
    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;
```
<img width="760" alt="Screen Shot 2019-06-25 at 13 51 47" src="https://user-images.githubusercontent.com/7759682/60092759-73f31880-9750-11e9-894e-3c8e02be165f.png">

If this issue is same with https://github.com/symfony/symfony/issues/32070, sorry.
