### ISSUE TITLE
InstanceOf visibility is ignored without default visibility

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#32193]
**Symfony version(s) affected**: 4.3.x (and previous I think)

**Description**  
I'm actually migrating from symfony 3.4 to symfony 4.3.
During this, I encountered a weird bug.

In symfony 4, in `services.yaml` the default value for public is `false` so I had to set `public: true` for some classes extending the same interface. I tried to use the feature `_instanceof`. But it seems like setting `public: true` does nothing if I don't set `public: false` as default value.

**How to reproduce**  
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false # Remove this line to create the bug

    _instanceof:
        MyInterface:
            public: true

    # Register all classes in these directories as services
    App\:
        resource: ../src/{Action,Command,EventSubscriber,Twig}
```

Remove the default value `public: false`
Service extending MyInterface won't be public.
