### ISSUE TITLE
[Bug] SF4 packages/services does not override services definition

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#32252]
**Symfony version(s) affected**: 4.3.x

**Description**  
I have a SmsApiClientInterface, implemented by an SmsApiClient and SmsApiClientMock.
In dev/preprod/prod I want the SmsApiClientInterface to be autowired with SmsApiClient but in tests I don't to.

So I added
```
AssuranceVie\ApiClient\SmsApiClientInterface: '@AssuranceVie\ApiClient\SmsApiClient'
```
In my services.yaml

And I create a package/test/services.yaml with
```
AssuranceVie\ApiClient\SmsApiClientInterface: '@AssuranceVie\ApiClient\Mocks\SmsApiClientMock'
```

But the override is ignored and the ApiClient is still used.

**How to reproduce**  
config/services
```
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Default visibility (needed to allow instanceof override)

# makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AssuranceVie\:
        resource: ../src/*
        exclude: ../src/{Admin,DataFixtures,Entity,Event,Exception,Migrations,Kernel.php}

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    AssuranceVie\Controller\:
        resource: ../src/Controller
        tags: [controller.service_arguments]

    AssuranceVie\ApiClient\SmsApiClientInterface: '@AssuranceVie\ApiClient\SmsApiClient'
```

packages/test/services
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AssuranceVie\ApiClient\SmsApiClientInterface: '@AssuranceVie\ApiClient\Mocks\SmsApiClientMock'
```
