### ISSUE TITLE
[Router] Router does not correctly detect and reject env vars within parameters

### ISSUE THREAD

**Issue by bendavies** [symfony/symfony#32366]
**Symfony version(s) affected**: 3.2 - master

**Description**  
Using env vars in routing configuration is not supported and actively denied:

https://github.com/symfony/symfony/pull/20687

https://github.com/symfony/symfony/blob/e3927b62942057bc45e88798134589f72b761ca7/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L163-L165

However, if we use indirection with a parameter we can avoid this error, but routing will not work as expected.

**How to reproduce** 
This will be denied correctly, as described above:
```yaml
# config.yaml
parameters:
    env(route_prefix): 'default'

# routes.yaml
some_route:
  path:       /%env(route_prefix)%/contact
  controller: App\Controller\MainController::contact
```

However, this will not throw an error:
```yaml
# config.yaml
parameters:
    env(route_prefix): 'default'
    route_prefix: '%env(route_prefix)%'

# routes.yaml
some_route:
  path:       /%route_prefix%/contact
  controller: App\Controller\MainController::contact
```

This will allow the container to boot, but defining a different `route_prefix` env var will never have any effect.

**Possible Solution** 
For good and non confusing DX, detect if parameters are pointing to env vars and deny building routes up front.
