### ISSUE TITLE
security.interactive_login  and security.authentication.success events fired twice

### ISSUE THREAD

**Issue by bravik** [symfony/symfony#32381]
**Symfony version(s) affected**: 4.3

**Description**  
During form-based login:
`security.authentication.success` and `security.interactive_login` are fired twice.
![image](https://user-images.githubusercontent.com/1075618/60693980-bae6c800-9f1f-11e9-8b3f-ec1b97ffff2e.png)

First by:
https://github.com/symfony/security-guard/blob/c64285b5c19c2fa0e2235909fd1cca5463132aa5/Firewall/GuardAuthenticationListener.php#L142
https://github.com/symfony/security-guard/blob/c64285b5c19c2fa0e2235909fd1cca5463132aa5/GuardAuthenticatorHandler.php#L65

Second by:
https://github.com/symfony/security-http/blob/8a93196dec0a136f817063c99eee20cd44e3615a/Firewall/AbstractAuthenticationListener.php#L208

I believe there should be only 1 event fired.

Noticed, when tried to save last user login time on interactive_login event. There were duplicate DB requests.

**How to reproduce**  
Implement a login form as described in official Symfony Docs.
My example `security.yaml`:
```yaml
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin.*
            anonymous: ~
            provider: app_user_provider
            guard:
                authenticators:
                     - App\Admin\Controller\Security\LoginFormAuthenticator
            form_login:
                login_path: admin.security.login
                check_path: admin.security.login
                default_target_path: admin.dashboard.index
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /admin/logout
                target: /
        main:
            anonymous: true
```
