### ISSUE TITLE
[Messenger] Usecase for Doctrine middlewares

### ISSUE THREAD

**Issue by bendavies** [symfony/symfony#32436]
This is a follow on discussion that I had with @weaverryan on Slack.

Messenger comes with some optional [Doctrine related middle-wares](https://github.com/symfony/symfony/tree/4.4/src/Symfony/Bridge/Doctrine/Messenger). It seems to me, unless i'm missing something, that all of these do not make sense as middlewares, and would be better suited as EventListeners for consumption purposes.

I've reimplemented 3 of these for my project as EventListeners in my project, as they are unusable as middleware.

Let's have a look.

#### `DoctrineClearEntityManagerMiddleware`
Automatically Clears the EntityManager in an effort to prevent memory leaks.

I can't imagine a use-case where this would be beneficial when dispatching messages. Messages are most likely dispatched in a request context, in which case you really don't want your Entity Manager cleared as all your entities will become un managed, which will just result in errors or unintended consequences when the EntityManager is eventually flushed.

However, clearing the EntityManager **is** obviously beneficial when consume messages, to prevent memory leaks in a long running process.

It seems this middleware should be a Listener on consumption, listening on some combination `WorkerMessageHandledEvent`/`WorkerMessageFailedEvent`/`WorkerMessageReceivedEvent`

#### `DoctrineTransactionMiddleware`
Automatically calls EntityManager `flush`.

Again, exactly the same as above really. 
1. As the developer, I want to be in control of calling when flush in a request context.
2. This middleware will not work at all and will throw an exception if you are dispatching messages during an existing `flush` i.e. subscribing to various doctrine events. (yes, you could debate here if this is a good idea or not).

It seems this middleware should be a EventListener, listening on  `WorkerMessageHandledEvent`.

#### `DoctrineCloseConnectionMiddleware`
Closes the database connection.

More of the same really. This seems better suited to a long running background processes, i.e the consumer.

#### `DoctrinePingConnectionMiddleware`
Checks the database connection is alive, reconnecting and resetting the entity manger if not.

More of the same really. This seems better suited to a long running background processes, i.e the consumer.

**Comment by weaverryan** [comment]
@Koc can you comment about DoctrineClearEntityManagerMiddleware - it also doesn't make sense to me. At the very least, I think it should only clear on "received" messages (which is what the original issue #29662 mentioned)

*DoctrineTransactionMiddleware* I think the idea here is you (for example with an event bus) have 4 handlers for 1 message and (as a design pattern) each handler does some work, but does not flush. The flush is then done at the end with the middleware. Also (probably more important), all 4 handlers are wrapped in the same transaction and are rolled back together. 

*DoctrineCloseConnectionMiddleware* & *DoctrinePingConnectionMiddleware* I agree again with @bendavies about these. I believe what we're trying to accomplish with these is to (A) close the connection between message handling to avoid having many open connections to the database that are doing nothing and (B) in case the connection was closed by the database server (e.g. "MySQL gone away"), re-open the connection. It seems these are better suited as event listeners on the worker. Ping @insidestyles (from PR #31061)

**Comment by insidestyles** [comment]
@Koc I agreed with @bendavies about DoctrineTrasactionMiddleware. I prefer keeping it as middleware. To me,  as listeners the other 3 middlewares do their jobs  too, so no objection. Would you please consider just about the component's definition: middleware vs listener. Are those middlewares  more related to the events like WorkerMessageHandledEvent or the whole process of the component? For example, with WorkerMessageHandlerEvent, I think about listeners like: trackHandledMessages, ... In your case we have to set up close connection listener to 2 events WorkerMessageHandlerEvent, WorkerMessageFailedEvent ...

**Comment by Koc** [comment]
Indeed some of current middlewares could be transformed into event listeners (`DoctrineClearEntityManagerMiddleware`, `DoctrineCloseConnectionMiddleware`, `DoctrinePingConnectionMiddleware`). But we should provide possibility to enable/disable and configure this listeners.

```
# config/packages/messenger.yaml
framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    - doctrine_transaction: ['custom']
```

So maybe we need new node, like `event_listeners`. IMHO this adds more complexity than benefits.

**Comment by bendavies** [comment]
can they all be converted to event listeners in 4.3? in 4.3 they are still experimental right so no BC break?

**Comment by weaverryan** [comment]
> can they all be converted to event listeners in 4.3?

Even experimental, we don't break BC on the patch releases - only minor releases (and hopefully we can really minimize the BC breaks for 4.4).

> Indeed some of current middlewares could be transformed into event listeners (DoctrineClearEntityManagerMiddleware, DoctrineCloseConnectionMiddleware, DoctrinePingConnectionMiddleware). But we should provide possibility to enable/disable and configure this listeners.

@Koc you said "could be transformed". Is it "could be" or do you agree that it's a "should be" (and that they don't make much sense as middlewares)? Just making sure we're not missing some perspective that you have. From my perspective, these more or less don't work at all as middlewares.

> So maybe we need new node, like event_listeners. IMHO this adds more complexity than benefits

Indeed, the config for this could get ugly. But, is there a use-case for enabling these for some buses and disabling for others? The 3 questionable middleware - clear, close & ping only makes sense in the context of "async workers" and they serve only to make things more reliable. 

Cheers!

**Comment by Koc** [comment]
> Is it "could be" or do you agree that it's a "should be"

to be honest - I'm not sure. Lets ask @sroze / @nicolas-grekas what they think about.

> The 3 questionable middleware - clear, close & ping only makes sense in the context of "async workers" and they serve only to make things more reliable.

`DoctrineClearEntityManagerMiddleware` makes sense for sync handling too: prevent memory leak when handle large amount of commands + prevent side effects like flushing outdated entities state.

`DoctrineCloseConnectionMiddleware` and `DoctrinePingConnectionMiddleware` actual for async handling.

**Comment by bendavies** [comment]
> `DoctrineClearEntityManagerMiddleware` makes sense for sync handling too: prevent memory leak when handle large amount of commands + prevent side effects like flushing outdated entities state.
I don't agree with that really, for the reasons laid out in my OP.

**Comment by insidestyles** [comment]
> > `DoctrineClearEntityManagerMiddleware` makes sense for sync handling too: prevent memory leak when handle large amount of commands + prevent side effects like flushing outdated entities state.
> 
> I don't agree with that really, for the reasons laid out in my OP.
IMO
For nginx/php-fpm: no sense
For swoole/reactphp: yes

**Comment by B-Galati** [comment]
See PR #32614 that add a new worker event that could help

**Comment by B-Galati** [comment]
When I tried messenger for the the 1st time with an async transport I was not expecting my message to trigger alll my Middlewares. I was expecting them to be called only at the moment the message is consumed. Does it make sense?

**Comment by B-Galati** [comment]
Would it make sense to change the workflow of Messenger?
Like:
Message dispatched -> sender -> receiver -> Middlewares -> handler.

Managing everything with a Middlewares is perhaps overkill? Why one would one would not want to use the HandleMessageMiddleware for example? 

Messenger is a message bus library but it feels like PSR-15 sometimes.

**Comment by maks-rafalko** [comment]
After upgrading to 4.3 we got a very weird error because of `DoctrineCloseConnectionMiddleware`, unfortunately.

We have a code that dispatches messages on `postPersist()`, in a opened transaction, and this middleware breaks EntityManager with the following error message: `There is no active transaction`

```php
public function postPersist(LifecycleEventArgs $eventArgs): void
{
    // ...
    $this->messageBus->dispatch(new SomeMessage());
    // ...
}
```

So, the flow is the following

```
START TRANSACTION
INSERT INTO ...
dispatch to MessageBus
close connection (from DoctrineCloseConnectionMiddleware)
ROLL BACK <---------  this is because Entity Manager is closed while transaction was not yet commited
```

We have to disable this middleware as it is too dangerous and does not look right.

**Comment by Koc** [comment]
I think that you have configured wrong priorities for middlewares. Can you share your config?

**Comment by maks-rafalko** [comment]
@Koc sure

```yaml
framework:
    messenger:
        failure_transport: failed
        serializer:
            default_serializer: messenger.transport.symfony_serializer
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
        transports:
            failed:
                dsn: 'doctrine://default?queue_name=failed'
            notification:
                dsn: enqueue://default?topic[name]=%env(NOTIFICATION_QUEUE)%&queue[name]=%env(NOTIFICATION_QUEUE)%
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
        routing:
            'Core\Message\Notification\ApiNotificationInterface': notification
            'Core\Message\Notification\EmailNotificationInterface': notification

```

**Comment by Koc** [comment]
This is strange. Personally I don't using close connection middleware, but my app using pretty similar clear entity manager middleware. My config looks like

```yaml
framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                default_middleware: false
                middleware:
                    - App\Common\Infrastructure\Messenger\ProcessMonologHandlersMiddleware
                    - validation
                    - # try locate close connection here
                    - App\Common\Infrastructure\Messenger\DoctrineClearEntityManagerMiddleware
                    - App\Common\Infrastructure\Messenger\DispatchDomainEventsMiddleware
                    - doctrine_ping_connection
                    - doctrine_transaction
                    - send_message
                    - handle_message
```

Will try test it with close connection also.

**Comment by insidestyles** [comment]
@maks-rafalko The configuration should be
>middleware:
>                     - doctrine_ping_connection
>                     - send_message
>                     - handle_message
>                     - doctrine_close_connection

I don't remember if we can configure after/before middlewares

**Comment by insidestyles** [comment]
@maks-rafalko IC, it does not work in your case (. The middleware works in the bus context (working process is put in the bus cycle). In your case, the bus is put in the working process. The solutions may be using different buses.

**Comment by maks-rafalko** [comment]
@insidestyles you are right.

So, when I use the code from the [documentation](https://symfony.com/doc/current/messenger.html#middleware-for-doctrine), it literally says the following:

```yaml
framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    - doctrine_transaction
                    - doctrine_ping_connection
                    - doctrine_close_connection
```

which resolves to the next middleware stack (8 middlewares, including default):

```
add_bus_name_stamp_middleware
dispatch_after_current_bus
failed_message_processing_middleware

doctrine_transaction
doctrine_ping_connection
doctrine_close_connection

send_message
handle_message
```

and [this does not work](https://github.com/symfony/symfony/issues/32436#issuecomment-514274275). I would at least suggest to update the documentation, saying for example to disable default middlewares (`defaulte_middleware: false`) and to order them differently:


```yaml
framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    - doctrine_transaction
                    - doctrine_ping_connection
                    - send_message
                    - handle_message
                    - doctrine_close_connection
```

But even with this config, when `doctrine_close_connection` middleware is the last one, when I have a `sync` transport and the message is being handled **immediately** during the opened transaction, EntityManager's connection is being closed after it, leading to `ROLLBACK`

So, anyway, the current state of the doc with suggested `doctrine_close_connection` is quite dangerous.

**Comment by insidestyles** [comment]
@maks-rafalko see the order of middlewares in @Koc 's comment. I don't use doctrine_close_connection in Sync. I thought you called bus command in another bus or process. The close connection is put in finnally block, so it should be called firstly

**Comment by weaverryan** [comment]
Question: Why not automatically/always perform some sensible doctrine-related actions at the beginning and end of handling each message in the work?

A) worker is about to start looking for a message
B) ping all open connections
C) clear all entity managers
D) find & handle the message
E) (optionally? configurable?) close all open connections

(B) & (C) seem sensible to me in all situations. Or am I missing something? We could add 2 new event listeners into core that just handle this automatically for users.

**Comment by mareksuscak** [comment]
Encoutered the same issue as @maks-rafalko and I also followed messenger's setup guide. It's just confusing.

**Comment by maks-rafalko** [comment]
It runs in both contexts, that's why we are using 2 different message buses, one for the sender, one for the receiver (worker).

And only worker context has `doctrine_ping_connection`

```yaml
buses:
  messenger.bus.default:
    middleware:
      - ...
      # Override the bus name that should receive and handle messages (bus name:  consumer.bus)
      - App\Messenger\Middleware\AddConsumerBusNameStampMiddleware

  consumer.bus:
    middleware:
      - ...
      - doctrine_ping_connection
```

To make it work, we've added another middleware that overrides consumer bus name so that worker can use different bus (not a default one `messenger.bus.default`). It looks like a workaround, but this is what we came up with, also discussed it with @weaverryan on the slack

```php
final class AddConsumerBusNameStampMiddleware implements MiddlewareInterface
{
    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        $envelope = $envelope->with(new BusNameStamp('consumer.bus'));

        return $stack->next()->handle($envelope, $stack);
    }
}
```
