### ISSUE TITLE
[Translations] locale is always needed now 

### ISSUE THREAD

**Issue by skytorner** [symfony/symfony#32515]
Hi to all

I'm using Symfony 4 for a project and I recently did a composer update.

Since that moment, I have to give the locale to the _trans_ method in the template to avoid the translator to get the fallback translation.

Now, when I looked at the profiler, the translation always get the default one whatever locale I call in my URL, event if in the request, the locale is the one in the URL.

Before the update I've already created a event subscriber to get the locale sticky, following [symfony documentation](https://symfony.com/doc/current/session/locale_sticky_session.html)

How I used to to get translation 
```
{{ 'trad1'|trans({}, 'test') }}
```

Now I have to to do it this way  to get it working

```
{{ 'trad1'|trans({}, 'test', app.request.locale) }}
```

I've noticed that `symfony/translation`upgrade from `4.2.4` to `4.3.2`

My `translation.yaml` config file

```
framework:
    default_locale: 'en'
    translator:
        paths:
            ['%kernel.project_dir%/translations']
        fallbacks:
            ['en']
```

I've crawled the symfony's issues and seen that there's a lot of discussions about the Translator but I can't really tell if it's linked or not

Thanks! 

UPDATE : 

I've just did a fresh install of Symfony and I got the same problem

**Comment by javiereguiluz** [comment]
How strange. We use translation for example in the "Symfony Demo" app (https://github.com/symfony/demo) and we don't have to pass the current locale to get the right translation. We don't have anything special either to make the locale sticky and it works. Can you please check the "Symfony Demo" code/config to see if you spot any difference with your own app? Thanks.

**Comment by skytorner** [comment]
I know ! It's crazy ! 

Here's the different config I have in my project (I couldn't find any relevant difference between symfony/demo config and mine, but who knows, I could have missed something obvious)

services.yaml

```yaml
parameters:
    locale: 'en'
    app_locales: 'en|fr|de'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
        bind:
            $rootDir: '%kernel.project_dir%'
..... 
## all services config follo
```

translation.yaml

```yaml
framework:
    default_locale: '%locale%'
    translator:
        paths:
            ['%kernel.project_dir%/translations']
        fallbacks:
            ['%locale%']
```

Here's my composer.json,  could help 

```json
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "a2lix/translation-form-bundle": "^3.0",
        "beberlei/doctrineextensions": "^1.1",
        "egyg33k/csv-bundle": "^1.0",
        "friendsofsymfony/ckeditor-bundle": "^1.0",
        "friendsofsymfony/jsrouting-bundle": "^2.2",
        "friendsofsymfony/user-bundle": "^2.1",
        "gregwar/image-bundle": "^2.2",
        "jmose/command-scheduler-bundle": "^2.0",
        "jms/i18n-routing-bundle": "^3.0",
        "knplabs/doctrine-behaviors": "^1.5",
        "knpuniversity/oauth2-client-bundle": "^1.27",
        "league/oauth2-facebook": "^2.0",
        "league/oauth2-google": "^3.0",
        "lexik/translation-bundle": "^4.0",
        "ninsuo/symfony-collection": "^2.1",
        "nmure/crawler-detect-bundle": "^2.0",
        "predis/predis": "^1.1",
        "sensio/framework-extra-bundle": "^5.1",
        "snc/redis-bundle": "^2.1",
        "snilius/twig-sort-by-field": "^0.1.5",
        "stof/doctrine-extensions-bundle": "^1.3",
        "suncat/mobile-detect-bundle": "^1.1",
        "symfony/asset": "^4.0",
        "symfony/console": "^4.0",
        "symfony/expression-language": "^4.0",
        "symfony/flex": "^1.1",
        "symfony/form": "^4.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "^4.0",
        "symfony/security-bundle": "^4.0",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.2.*",
        "symfony/twig-bundle": "^4.0",
        "symfony/validator": "^4.0",
        "symfony/web-link": "^4.0",
        "symfony/webpack-encore-bundle": "^1.1",
        "symfony/webpack-encore-pack": "*",
        "symfony/yaml": "^4.0",
        "twig/extensions": "^1.5",
        "vich/uploader-bundle": "^1.8",
        "whichbrowser/parser": "^2.0",
        "whiteoctober/breadcrumbs-bundle": "^1.4",
        "willdurand/js-translation-bundle": "^2.6"
    },
    "require-dev": {
        "symfony/apache-pack": "^1.0",
        "symfony/browser-kit": "^4.0",
        "symfony/css-selector": "^4.0",
        "symfony/debug-pack": "*",
        "symfony/dotenv": "^4.0",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^4.0",
        "symfony/profiler-pack": "*",
        "symfony/web-server-bundle": "^4.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false
        }
    }
}

```
