### ISSUE TITLE
[RFC][Validator] Validation based on Route

### ISSUE THREAD

**Issue by ProtonScott** [symfony/symfony#32528]
### The What

I propose the ability to leverage the Validators Yaml API so it will match *routes* instead of just *properties on objects*

### The Why

I currently work on a project that has to dynamically generate forms based on uploaded CSV/excel files. The uploaded files are then parsed into rows in a database, and from that forms must be generated (they're effectively turned into questionnaires). The fields have various requirements for validaiton, which are known at parse time, but because of these factors:

1. The validations must be dynamic, as they may not always be required
2. The questionnaires are non-linear, in that some are skipped entirely based on the answers given
3. This means the traditional way of using the symfony/forms API to build the fields incurs a cost: either we have to create all the validations and all the form fields at run-time (which can be very slow). From everything I've tried to do, I can't seem to cache the Constraints Reliably (and its discouraged to use the constraints directly on a form anyway), nor can I seem to cache the entire form (serialization fails). Due to many factors (including business need), everything has to been done on submit.

### Example Work Around Of Issue Described

The work around that works well for us, but is a very ugly hack that incurs its own isssues, is the following:

1. We have a `MagicObject` class that looks like this:

```php
<?php

abstract class MagicObject
{
   private $formAnswers;

    public function __construct(array $formAnswers)
    {
        $this->formAnswers = $formAnswers;
    }

    public function __get($name)
    {
        return $this->formAnswers[$name];
    }

    public function __set($name, $value)
    {
        $this->formAnswers[$name] = $value;
    }

    public function __isset($name)
    {
        return array_key_exists($name, $this->formAnswers);
    }

    public function __unset($name)
    {
        unset($this->formAnswers[$name]);
    }
}
```

With that, we have a template php file that just extends this object, so we end up with a bunch of generated classes that just look like this:

```php
<?php

namespace App\Model\Generated\SomeRandomlyGeneratedName

use App\Model\MagicObject;

class SomeRandomlyGeneratedName extends MagicObject
{
}
```

and a corresponding Yaml File gets generated into `config/validator/validations/some_class_name.yaml`

```yaml
# this is just a simple example I took from the site
App\Model\Generated\SomeRandomlyGeneratedName:
    properties:
        formAnswers:
            - Collection:
                fields:
                    question_1:
                        - Email: ~
                    question_2:
                        - NotBlank: ~
                        - Length:
                            max:   100
                            maxMessage: Your short bio is too long!
                allowMissingFields: true.
```

This works, but its very convoluted, and as a system grows, we worry that this may over time become extremely fragile.

Building an `Assert\Collection` constraint also proved to be problematic at run-time.

### The Proposal

So I propose, since *form data is already submitted as an array thanks to php's build in name="value[]" structure*,  that we be able to short cut all this and assign validations like so:

1a. Have the ability to assign validations based on the Route (either by using the Controller Name or Controller Method Name the Route is controlled by, or using the route name (like questionnaire_forms, or whatever you put inside the `@Route(name="some_thing")` annotation

1b. Once that relationship is defined, have the ability to define validations as key, value pairs that would be treated as Optional on submitted data implicitly, so validations only happen if those fields exist. Alternatively, one could easily just import the needed validations using [Service Container Expressions](https://symfony.com/doc/current/service_container/expression_language.html)

Perhaps there is a more effective method (like using JSON Schema or OpenAPI Schema to infer what needs to be done), but it would greatly simplify the work and cut out the need to create endless data  mapping classes just for validations.

What do you guys think? Did I miss something in programming 101? Is this a good idea? I didn't see any post RFCs/issues posted along these lines, so if I missed that and this discussion has already been had, please feel free to let me know.
