### ISSUE TITLE
Working with serializer and DateTime

### ISSUE THREAD

**Issue by zim32** [symfony/symfony#32551]
Hi everyone.

Can't figure out how to use serializer. I need to handle DateTime properties inside objects. When I add DateTimeNormalizer it works for serialization, but DateTimeNormalizer is not called during deserialization and I get error.

Argument 1 passed to Project::setCreatedAt() must be an instance of DateTime, string given.
Documentation lacks information.

I inject serializer in controller action method like

`public function postProjects(Request $request, SerializerInterface $serializer)...`

In my services.yml I have:
```
    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        public: false
        tags:
          - { name: 'serializer.normalizer' }

    Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        public: false
        tags:
          - { name: 'serializer.normalizer' }`
```
Thanks everyone.
