### ISSUE TITLE
Redis connection failed (No such file or directory)

### ISSUE THREAD

**Issue by abarke** [symfony/symfony#32597]
**Symfony version(s) affected**: 4.3.2

**Description**  
Incompatible Redis PHP Extension 5.0.0 with RedisTrait.php
GitHub: https://github.com/symfony/cache/blob/master/Traits/RedisTrait.php#L170

We had some issues with the new PHP Redis Extension 5.0.0... it reaped havoc in our deployment system heroku and took a while to track down. Our version constraint in composer.json was "ext-redis": "*" which automatically installed the new version 5.0.0 on triggering a new build. This broke the connectivity with Redis on on builds with v5.0.0 PHP extension. 

**How to reproduce**  
1. composer require ext-redis:5.0.0
2. using following config in framework.yaml
3. php bin/console cache:pool:clear cache.global_clearer

```
framework:
    # https://symfony.com/doc/current/cache.html
    # https://symfony.com/doc/current/reference/configuration/framework.html#pools
    # https://symfony.com/doc/current/reference/configuration/framework.html#default-redis-provider
    cache:
        default_redis_provider: "%env(REDIS_URL)%"
        app: cache.adapter.redis
        system: cache.adapter.redis
```

**Possible Solution**  
I fixed the issue with "ext-redis": "^4.0".

**Additional context**  
```
[2019-07-16 17:35:00] cache.WARNING: Failed to clear the cache {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\InvalidArgumentException(code: 0): Redis connection failed (No such file or directory): redis://x:xxxxx@redis.com:xxxxx at /tmp/build_ca50b6cc1d12879d260459f7f168668e/vendor/symfony/cache/Traits/RedisTrait.php:161)"}
```
