### ISSUE TITLE
local ENV vars are not overrided by ENV defined at server level

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#32655]
**Symfony version(s) affected**: 4.3.2

**Description**  
I defined ENV parameters at server level to override the .env file but the parameters are not used.

```
# echo $DATABASE_URL
mysql://myUser:myPassword@MYSQL/myDatabase
# php -r "echo getenv('DATABASE_URL');"
mysql://myUser:myPassword@MYSQL/myDatabase
```

But when I run
```
php bin/console debug:container --env-vars

Symfony Container Environment Variables
=======================================

 No environment variables are being used.
```

At runtime only values in .env are used.

**Comment by ro0NL** [comment]
Hi @raziel057 the command only displays env vars referenced by the DI container, can you confirm it's the case?

**Comment by raziel057** [comment]
Yes I have a Doctrine config like this and currently it takes the config defined in .env file:

```yaml
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        url: '%env(resolve:DATABASE_URL)%'
        charset: UTF8
```
