### ISSUE TITLE
Symfony 3.4 Advanced environment variable from string to int casting

### ISSUE THREAD

**Issue by legalvisio-schillermann** [symfony/symfony#32670]
**Symfony version(s) affected**: x.y.z

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by legalvisio-schillermann** [comment]
I've set a string "011" env and cast it as int and get 9.
That happen always with nginx env.
Why that?
```
# nginx
fastcgi_param ID "011";
```

```
# parameters.yml
id: '%env(int:ID)%'
```

```
services:
  App\Controller\DefaultController:
      arguments:
        $id: '%id%'
```
class DefaultController
{
    public function __construct($id)
    {
        var_dump($id);
    }
}
```
