### ISSUE TITLE
Doctrine listener registration in separate file

### ISSUE THREAD

**Issue by versh23** [symfony/symfony#32732]
**Symfony version(s) affected**: 4.3

**Description**  
I try to move DoctrineListener to separate file and import this in services.yaml
but listener dont work

this is not work
```
    App\DoctrineListener\FileListener:
        tags:
            - { name: doctrine.orm.entity_listener }
```

but this is work.
```
    file_listener:
        class: App\DoctrineListener\FileListener
        tags:
            - { name: doctrine.orm.entity_listener }
```

is it bug ? because if i write a 
```
    App\DoctrineListener\FileListener:
        tags:
            - { name: doctrine.orm.entity_listener }
```

directly in services.yaml - its work
