### ISSUE TITLE
Synthetic service cannot be define if binds are present

### ISSUE THREAD

**Issue by noemi-salaun** [symfony/symfony#32874]
**Symfony version(s) affected**: tested with 3.4 and 4.3

**Description**  

If I define a synthetic service in my service.yaml config file where binds are already defined, I get the error

> Invalid service "my_synthetic_service": class "" does not exist. 

**How to reproduce**  

1. Create a new app: 
```sh
symfony new my-app
```
2. Add the service definition and the bind in `config/services.yaml`
```yaml
services:
    _defaults:
        # ...
        bind:
            $someBind: someValue

    # ...

    my_synthetic_service:
        synthetic: true
        public: true
```
3. Run any console command
```sh
./bin/console debug:container my_synthetic_service
```
4. Get the full error
>  Unused binding "$someBind" in service "my_synthetic_service".       
>   Could be related to:                                                 
>    - Invalid service "my_synthetic_service": class "" does not exist.

_This error is a little more understandable than the first one, but I have to try finding the minimal failing exemple to get this error_

5. Add some service that use the bind
```php
<?php
namespace App\Service;
class SomeService
{
    public function __construct(string $someBind) {  }
}
```

6. Re-run the console command
7. Get the minimal error
> Invalid service "my_synthetic_service": class "" does not exist.

_This error is way worse to debug the real problem_

**Comment by xabbuh** [comment]
What is the real name for the service that you used? So far it seems to me that you just forgot to configure its class.

**Comment by noemi-salaun** [comment]
I do not have to declare my service class if I follow the documentation for synthetic services.

See https://symfony.com/doc/current/service_container/synthetic_services.html :

```yaml
# config/services.yaml
services:
    # synthetic services don't specify a class
    app.synthetic_service:
        synthetic: true
```

If I remove the bind declaration, everything works fine.

Another exemple of synthetic service is the `kernel` service. If you look at its definition, you can see that it does not define its class.

https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/FrameworkBundle/Resources/config/services.xml#L48

```xml
<service id="kernel" synthetic="true" public="true" />
```
