### ISSUE TITLE
Messenger envelope doesn't serialized properly in the logs

### ISSUE THREAD

**Issue by Spy-Seth** [symfony/symfony#32883]
**Symfony version(s) affected**: 4.3

**Description**  
Messenger envelope doesn't serialized properly in the logs:

```
[2019-08-02 12:20:26] messenger.INFO: Message MyApp\Seller\Domain\LotPriceUpdated handled by MyApp\CustomerArea\UI\LotPriceUpdatedHandler::__invoke {"message":"[object] (MyApp\\Seller\\Domain\\LotPriceUpdated: {})","class":"MyApp\\Seller\\Domain\\LotPriceUpdated","handler":"MyApp\\Customer\\UI\\LotPriceUpdatedHandler::__invoke"} []
```

**How to reproduce**  

```yaml
# messenger.yaml

framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands: ~
            messenger.bus.events:
                default_middleware: false
        transports: ~
        routing: ~
```

```php
<?php
# UpdateLotPriceCommand.php

namespace MyApp\Seller\Application;

class UpdateLotPriceCommand
{
    /**
     * @var string
     */
    private $lotId;

    /**
     * @var float
     */
    private $price;

    /**
     * @param string $lotId
     * @param float $price
     */
    public function __construct(string $lotId, float $price)
    {
        $this->lotId = $lotId;
        $this->price = $price;
    }

    /**
     * @return string
     */
    public function getLotId(): string
    {
        return $this->lotId;
    }

    /**
     * @return float
     */
    public function getPrice(): float
    {
        return $this->price;
    }
}
```

And I call:
```php
<?php

// On my bus `messenger.bus.commands`
$commandBus->dispatch(new UpdateLotPriceCommand('1234', 42.2));

```

**Additional context**  
If I use directly the  service `serializer`, my object `UpdateLotPriceCommand` is well formatted
