### ISSUE TITLE
[Messenger] Do not perform deep merging

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#32953]
**Description**  
I followed the [doc to send email async](https://symfony.com/doc/current/mailer.html#sending-messages-async).
It works well, but I don't want to add an extra consumer in test.
So in my `config_test.yml` I did that:

```yaml

framework:
    messenger:
        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': sync # instead of rabbitmq (called async in the doc)
```

But this is the resolved configuration:

```
routing:
    Symfony\Component\Mailer\Messenger\SendEmailMessage:
        senders:
            - rabbitmq
            - sync
```

IMHO, We should get only `sync` without `rabbitmq`
