### ISSUE TITLE
[DI] Allow class-defined priority when using _instanceof + tags

### ISSUE THREAD

**Issue by gitomato** [symfony/symfony#32976]
**Description**  
Let's use a sample similar to the doc:
```yml
services:
  _instanceof:
    App\Handler:
      tags:
        - { name: 'app.handler', priority: 20 }

  App\HandlerCollection:
    arguments: [!tagged app.handler]
```
All instances of `App\Handler` will have the same priority.

I would like to define a different priority for each handler.

**Example**  
This might not be the cleanest solution but you get the point.

```yml
services:
  _instanceof:
    App\Handler:
      tags:
        - { name: 'app.handler', priority: 'getPriority' }
```

```php
namespace App;

class MyHandler implements Handler {
  public static function getPriority(): int {
    return 10;
  }
}
```
