### ISSUE TITLE
EnvVarProcessor default combination with unresolved file gives error

### ISSUE THREAD

**Issue by leroy0211** [symfony/symfony#33125]
**Symfony version(s) affected**: 4.3.x

**Description**  
When using the combination of `default` without fallback paramater and `file` to a file which does not exists, the error `array_key_exists() expects parameter 2 to be array, null given` occurs. 

**How to reproduce**  
This is the setup

```
parameters:
    env(CONFIG_FILE): '/data/option_enabled'
    option_enabled: '%env(bool:default::file:CONFIG_FILE)%'
```

make sure the file does not exists.

**Additional context**  
When I **do** use a fallback property, everything works just fine. So I've worked around it like so: 

```
parameters:
    env(CONFIG_FILE): '/data/option_enabled' 
    default_config: 'false'
    option_enabled: '%env(bool:default:default_config:file:CONFIG_FILE)%'
```

However, when using default I might want to default it to a string instead of an existing parameter like so.

```
parameters:
    env(CONFIG_FILE): '/data/option_enabled'
    option_enabled: '%env(bool:default:false:file:CONFIG_FILE)%'
```
