### ISSUE TITLE
NotFoundHttpException: Unable to find the controller for path "....". The route is wrongly configured.

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#33170]
**Symfony version(s) affected**: 4.3.3

**Description**  
Route definition without a controller produces `NotFoundHttpException: Unable to find the controller for path "/api/v1/token". The route is wrongly configured.`.

This happens when header is set to `Content-Type: application/x-www-form-urlencoded` and contains `grant_type=password` payload. However, if the header is changed to `Content-Type: application/json` or just `grant_type=password` is changed as `grant_type=something_else`, it does work.

So, `Content-Type: application/x-www-form-urlencoded` with `grant_type=password` together won't work if route definition doesn't have a specific controller defined.

**How to reproduce**  

**routes.yaml**
```yaml
token_create:
   path: /api/{version}/token
   methods: [POST]
   defaults:
      version: v1
```

**security.yaml**
```yaml
security:

    role_hierarchy:
        ROLE_USER: ROLE_USER

    providers:
        token:
            id: App\Security\Token\UserProvider

    firewalls:
        token:
            pattern: ^/api/v1/token
            stateless: true
            guard:
                provider: token
                authenticators:
                    - App\Security\Token\Authenticator

    access_control:
        - { path: ^/api/v1/token, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
```

---

#### Failure
```bash
curl -X POST \
  https://localhost/api/v1/token \
  -H 'Authorization: Basic Fzc3dvcmQ=' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d grant_type=password
```
#### Fine
```bash
curl -X POST \
  https://localhost/api/v1/token \
  -H 'Authorization: Basic Fzc3dvcmQ=' \
  -H 'Content-Type: application/json' \
  -d grant_type=password
```
```bash
curl -X POST \
  https://localhost/api/v1/token \
  -H 'Authorization: Basic Fzc3dvcmQ=' \
  -H 'Content-Type: application/json' \
  -d grant_type=something_else
```
```bash
curl -X POST \
  https://localhost/api/v1/token \
  -H 'Authorization: Basic Fzc3dvcmQ=' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d grant_type=something_else
```
