### ISSUE TITLE
[Cache] Using tags and autowire will not work

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#33201]
**Symfony version(s) affected**: 4.3.3

**Description**  

When Im autowiring my services they dont respect the `tags` config. 

**To reproduce**
In the following examples Im using this cache config
```yaml
framework:
    cache:
        pools:
          my_taggable_pool:
            adapter: cache.adapter.array
            tags: true

```

#### Attempt 1) Using `controller.service_arguments`
```yaml
services:
    App\Controller\StartpageController:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
```

With a controller like: 

```php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Cache\CacheInterface;
use Symfony\Contracts\Cache\ItemInterface;
use Symfony\Contracts\Cache\TagAwareCacheInterface;

final class StartpageController extends AbstractController
{
    /**
     * @Route("", name="startpage", methods={"GET"})
     */
    public function startpage(CacheInterface $myCachePool): Response
    {
        $myCachePool->get('foo', function(ItemInterface $item) {
            $item->tag('foo');

            return 'bar';
        });

        return $this->render('startpage.html.twig');
    }
}
```

This will lead to 
> Cache item "foo" comes from a non tag-aware pool: you cannot tag it.

Because `$myCachePool` is not a `TagAwareAdapter`. 

#### Attempt 2) Using autowrire and constructor injection

Same thing happens if you autowire things based on service id: 

```yaml
services:
    App\Controller\StartpageController:
        autowire: true
        autoconfigure: true
```

```php 
final class StartpageController extends AbstractController
{
    private $cache;

    public function __construct(CacheInterface $myCachePool)
    {
        $this->cache = $myCachePool;
    }

    /**
     * @Route("", name="startpage", methods={"GET"})
     */
    public function startpage(): Response
    {
        $this->cache->get('foo', function(ItemInterface $item) {
            $item->tag('foo');

            return 'bar';
        });

        return $this->render('startpage.html.twig');
    }
}
```

#### Attempt 3) Dont use autowire

The way I can avoid the problem is by defining the service properly: 

```yaml
services:
    App\Controller\StartpageController:
        arguments: ['@my_taggable_pool']
```

**Comment by nicolas-grekas** [comment]
Shouldn't you type hint TagAwareCacheInterface?

**Comment by Nyholm** [comment]
Sure, I **could** do that. And that fixes the issue. But is that really needed?

**Comment by Nyholm** [comment]
Hm, so if Im not type hint for `TagAwareCacheInterface`, then the autowire system will think: 
"oh, there is no service that fits `CacheInterface $myCachePool`, I better create one new". 

Is that correct?

**Comment by nicolas-grekas** [comment]
Aliases exist before they're used, but the CacheInterface alias points to the undecorated service, while the tag aware points to the tag-decorated one.
This makes sense, from a SOLID pov, don't you think? You cannot use tags if you didn't ask for them without breaking the abstraction on CacheInterface to me.

**Comment by Nyholm** [comment]
I agree, it makes sense. And what you describe is correct. 

But it also means that the config `tags: true` has no effect. 

```yaml
framework:
    cache:
        pools:
          my_taggable_pool:
            adapter: cache.adapter.array
            tags: true|false
```

No matter if I use true of false for the `tags` config. This class will always get a `TagAwareCacheInterface`

```php
class ServiceUsingCache
{
    private $cache;

    public function __construct(TagAwareCacheInterface $myTaggablePool)
    {
        $this->cache = $myTaggablePool;
    }
}
```

Same thing with this class. No matter the value, I will always get a pool which I cannot use tags: 

```php
class ServiceUsingCache
{
    private $cache;

    public function __construct(CacheInterface $myTaggablePool)
    {
        $this->cache = $myTaggablePool;
    }
}
```
