### ISSUE TITLE
[Doctrine] XML mapping of entity stored in subdirectory

### ISSUE THREAD

**Issue by kniziol** [symfony/symfony#33296]
**Symfony version(s) affected**: 4.3.3
**DoctrineBundle version(s) affected**: 1.11.2

**Description**  
XML mapping of entity stored in `src/Entity/<subdirectory>` is not "visible"

**How to reproduce**  
1. Run `symfony new my_project` to install new project
2. Run `symfony composer require symfony/orm-pack` to install Doctrine
3. Run `symfony composer require --dev symfony/maker-bundle` Maker
4. Open `.env` and set valid database connection in `DATABASE_URL` variable
5. Run `symfony console make:entity OrangePizza` to create `OrangePizza` entity or create `src/Entity/OrangePizza.php` manually:

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrangePizzaRepository")
 */
class OrangePizza
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}
```

6. Open `config/packages/doctrine.yaml` and modify `doctrine.orm.mappings.App` to load XML mappings stored in `config/doctrine_mappings` directory

Before:

```yaml
doctrine:
            # ...
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

After:

```yaml
doctrine:
            # ...
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine_mappings'
                prefix: 'App\Entity\Lorem'
                alias: App
```

7. Run `mkdir -p config/doctrine_mappings`
8. Create file `config/doctrine_mappings/OrangePizza.orm.xml`:

```xml
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping">
    <entity name="App\Entity\OrangePizza" repository-class="App\Repository\OrangePizzaRepository">
        <id name="id">
            <generator/>
        </id>
    </entity>
</doctrine-mapping>
```

9. Edit `App\Entity\OrangePizza` entity and replace with:

```php
<?php

namespace App\Entity;

class OrangePizza
{
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}
```

10. Run `symfony console make:migration`. Everything is OK.
11. Run `mkdir -p config/doctrine_mappings/Lorem` *<----- problem starts here*
12. Run `mv config/doctrine_mappings/OrangePizza.orm.xml config/doctrine_mappings/Lorem`
13. Move class `App\Entity\OrangePizza` to namespace `App\Entity\Lorem\OrangePizza` (`Lorem\` was added)
14. Run `symfony console make:migration`. Result:
`No mapping file found named 'OrangePizza.orm.xml' for class 'App\Entity\Lorem\OrangePizza'` *<----- this is the problem*

**Main question**
Is it possible to load mappings of entity from namespace `App\Entity\Lorem\` when `prefix` is defined as `'App\Entity'`?

**Possible solution**
1. Change `doctrine.orm.mappings.App.prefix` parameter: from `'App\Entity'` to `'App\Entity\Lorem'`
2. Run `mv config/doctrine_mappings/Lorem/OrangePizza.orm.xml config/doctrine_mappings && rm -rf config/doctrine_mappings/Lorem`
3. Run `symfony console make:migration`. Result: `Success!`

**Comment by xabbuh** [comment]
I am not sure that I really understand the issue here. Is this related to how the MakerBundle works or how mapping information is read from the configuration by Doctrine? Also the error message refers to `App\Entity\Lorem\OrangePizza` while based on your code the FQCN seems to be `App\Entity\OrangePizza`.

**Comment by kniziol** [comment]
It's related to how mapping information is read from the configuration by Doctrine.

Mapping of entity `App\Entity\Lorem\OrangePizza` stored in `config/doctrine_mappings/Lorem/OrangePizza.orm.xml` is invisible by Doctrine if `prefix` in `config/packages/doctrine.yaml` configuration file is set to `'App\Entity'`:

```yaml
doctrine:
            # ...
            App:
                # ...
                prefix: 'App\Entity'
```
