### ISSUE TITLE
Yaml dump - missing new line after TaggedValue

### ISSUE THREAD

**Issue by Selion05** [symfony/symfony#33354]
**Symfony version(s) affected**: x.y.z
symfony/yaml                       v4.3.4  Symfony Yaml Component

**Description**  
If you dump an array with a high inline value  an new line is missing after `TaggedValue`

**How to reproduce**  
```php
<?php

require __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Yaml\Yaml;

$yaml = <<<YAML
services:
    service.id:
        arguments: [!tagged my.tag]
    service.id.2:
YAML;

$services = Yaml::parse($yaml, Yaml::PARSE_CUSTOM_TAGS);

$dumped = Yaml::dump($services, 8);

echo  $dumped;
```
results in 
```yaml
services:
    service.id:
        arguments:
            - !tagged
              my.tag    service.id.2: null
```

**Possible Solution**
Add a new line [here](https://github.com/symfony/symfony/blob/545d38a037098f0f21b11b380912151488acfac7/src/Symfony/Component/Yaml/Dumper.php#L87)
