### ISSUE TITLE
[DI] bind under _default does not support parameter resolving

### ISSUE THREAD

**Issue by tom10271** [symfony/symfony#33365]
**Symfony version(s) affected**: 4.3.2

**Description**  
In dependency injection, `bind` under `_default` only detect if value passed is array or not making developer setting it by parameter impossible.

The reasons why I want to use parameter to set value for `bind` is I want to add additional set of binding hints for test environment.

**How to reproduce**  
parameters.yaml
```yaml
parameters:
    # Used by DEV and PROD
    services_binding_map: &services_binding_map
        $env: '%kernel.environment%'
        $environment: '%kernel.environment%'
        $locales: '%store.locales%'

    # Used by TEST
    services_binding_map.test:
        <<: *services_binding_map
        $projectRootDir: '%kernel.project_dir%'
        # For DataFixtureContext used in Behat test cases to reset DB
        $dbHost: '%env(DATABASE_HOST)%'
        $dbName: '%env(DATABASE_NAME)%'
        $dbUser: '%env(DATABASE_USER)%'
        $dbPassword: '%env(DATABASE_PASSWORD)%'
```

services.yaml
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind: '%services_binding_map%'
```

**Possible Solution**  
Detect if `$defaults['bind']` in https://github.com/symfony/dependency-injection/blob/master/Loader/YamlFileLoader.php#L283 is string and found in container's parameters bag and its value is array, then replace `$defaults['bind']` with specified parameter

`$this->container->hasParameter($defaults['bind'])`

**Additional context**
