### ISSUE TITLE
[Profiler] could not access logs in tests

### ISSUE THREAD

**Issue by massimilianobraglia** [symfony/symfony#33384]
**Symfony version(s) affected**: 4.3.4 (upgrading from 4.2.5)

**Description** 
https://github.com/symfony/symfony/pull/30339
This PR disabled the debug logger in `cli`. During the execution of my functional tests with PHPUnit I cannot access the logs contained in the profiler's logger collector 
```php
        $collector = $profile->getCollector('logger');
        $logs = $collector->getLogs()->getValue(true);
```
these lines gathered also the logs made by a GuzzleHttp client instance (I can dump the log messages).

I need to check those logs in order to be sure that the GuzzleClient makes the right requests needed by my application.

How can I access those logs? Is there another way to do that?

Thank you in advance! 😄

**Comment by ogizanagi** [comment]
I think the best way for you to access the logs in functional tests is not using the profiler, but to add the [Monolog test handler](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/TestHandler.php) in your test env:

```yml
# config/packages/test/monolog.yaml

monolog:
         [...]

        # Test handler allows to perform assertions on logs:
        test:
            type: test
            level: debug
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
```

Declaring an alias to the service:

```yml
# config/packages/test/monolog.yaml

services:
    Monolog\Handler\TestHandler:
        public: true # to be accessible from tests
        alias: monolog.handler.test
```

you could access it in tests from the client container, and use its assertions methods.
