### ISSUE TITLE
[Mailer] Sending Messages Async with json serializer does not work

### ISSUE THREAD

**Issue by TheRatG** [symfony/symfony#33394]
**Symfony version(s) affected**: symfony/mailer: 4.3.4

**Description**  
Sending Messages Async with json serializer does not work with SendEmailMessage.

```
Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException : Cannot create an instance of Symfony\Component\Mime\RawMessage from serialized data because its constructor requires parameter "message" to be present.
/home/vagrant/www/fxbackoffice.local/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php:505
 ...
```

**How to reproduce**  
```
framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage':  async
```
