### ISSUE TITLE
[Messenger] [Redis] options object is not used

### ISSUE THREAD

**Issue by marcoreni** [symfony/symfony#33425]
**Symfony version(s) affected**: 4.3.4

**Description**  
According to the documentation, Redis should be configurable using the `options` object, but this seems not to work. 

**How to reproduce**  
```yaml
framework:
  messenger:
    transports:
      mytransport:
        dsn: "redis://localhost:6379"
        options:
          stream: "stream-name"
          group: "worker-group"
          auto_setup: true
```
Messages should be posted into the `stream-name` stream, and consumed using `worker-group` group. However, messages are posted into `messages` stream, and consumed using `symfony` group name - you can check this on redis-cli: `XPENDING messages worker-group`  yields `"NOGROUP No such key 'messages' or consumer group 'worker-group'"`.

Using querystring parameters to configure the same options works just fine.
