### ISSUE TITLE
[Serializer] allow more default context configuration via yaml

### ISSUE THREAD

**Issue by rimas-kudelis** [symfony/symfony#33420]
**Description**  
Serializer context may have numerous keys, but only a handful are configurable via yaml:
```yaml
    # serializer configuration
    serializer:
        enabled:              true
        enable_annotations:   true
        name_converter:       ~
        circular_reference_handler: ~
        max_depth_handler:    ~
        mapping:
            paths:                []
```
It would be nice if other options were supported. In particular, I find it quite inconvenient that while I can configure `max_depth_handler` via yaml config, I cannot `enable_max_depth` that same way. Without the latter, the former appears to me hardly useful.

**Example**  
```yaml
    # serializer configuration
    serializer:
        enabled:              true
        enable_annotations:   true
        enable_max_depth:     true
        (...other options?..)
        name_converter:       ~
        circular_reference_handler: ~
        max_depth_handler:    ~
        mapping:
            paths:                []
```
