### ISSUE TITLE
[Security] LdapBindAuthenticationProvider not retrieving previously built User

### ISSUE THREAD

**Issue by janisVincent** [symfony/symfony#33458]
**Symfony version(s) affected**: 4.3.4
**Description**  

When logging with LDAP, `uid_key` specified within provider configuration will successfully populate `Symfony\Component\Security\Core\User\User::$username` property.

But `LdapBindAuthenticationProvider::checkAuthentication()` will then match `{username}` with `$request->headers->get('PHP_AUTH_PW')` rather than `User::$username`.

**How to reproduce**  

```yaml
# config/packages/security.yaml
security:
    providers:
        custom_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: dc=whatever_dn,dc=com
                search_dn: "CN=whatever_cn,DC=whatever_dc,DC=com"
                search_password: '%env(LDAP_PWD)%'
                filter: 'sAMAccountName={username}'
                uid_key: distinguishedName
                default_roles: ROLE_USER
    firewalls:
        ...
        main:
            http_basic_ldap:
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'DC=whatever_dc,DC=com'
                query_string: 'distinguishedName={username}'
```
User will be found on LDAP at first, but `checkAuthentication` will fail trying to authenticate with 'distinguishedName' equaling `$request->headers->get('PHP_AUTH_PW')`

**Possible Solution**  

In Symfony\Component\Security\Core\Authentication\Provider, line 74, replace :
`$username = $token->getUsername();`
with :
`$username = $user->getUsername();`

**Additional context**
