### ISSUE TITLE
[DependencyInjection] Issue with EntityManagerDecorator

### ISSUE THREAD

**Issue by fabienlem** [symfony/symfony#33474]
**Symfony version(s) affected**: 3.4.31

**Description**  
Since upgrade to 3.4.31, entity managers injected throught EntityManagerDecorator are always the default entity manager :/

**How to reproduce**  
Here is an example:

services.yml
```yaml
    App\Service\AnotherEntityManager:
        arguments:
            $wrapped: '@doctrine.orm.another_entity_manager'
```

Entity manager wrapper
```php
namespace App\Service;

use Doctrine\ORM\Decorator\EntityManagerDecorator;

class AnotherEntityManager extends EntityManagerDecorator
{
}
```

Dump of injected AnotherEntityManager service
```php
AnotherEntityManager {#1527 ▼
  #wrapped: EntityManager {#1032 …11} <--- default entity manager, not another_entity_manager
}
```

This code worked as excepted with the previous versions of Symfony.

Regards!
