### ISSUE TITLE
[Config] Recursive merge of variable nodes

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#33598]
**Description** 
A simple way to allow VariableNode to recursively merge its content rather than simply overriding it.
There would be two modes:
- Simple overriding (default and current behavior);
- Recursive merge where associative array keys are merged, integer array keys are appended and litterals are overrided.

**Example** 
Such as:
```
my_variable_node:
  foo:
    bar: 1
    baz:
      - 2
      - 3
```
```
my_variable_node:
  foo:
    bar: 5
    baz:
      - 7
      - 8
```
would merge to:
```
my_variable_node:
  foo:
    bar: 5
    baz:
      - 2
      - 3
      - 7
      - 8
```

**Implementation**
I am willing to work on it if there is some interest.
