### ISSUE TITLE
MySQL and Oracle database in one application exception

### ISSUE THREAD

**Issue by lcp0578** [symfony/symfony#33638]
**Symfony version(s) affected**: 3.4.30

**Description**  
<!-- A clear and concise description of the problem. -->
```
# php bin/console doctrine:schema:update --dump-sql

In AbstractMySQLDriver.php line 79:
                                                                                                                                                                                                                                                
  An exception occurred while executing 'ALTER SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' N  
  LS_NUMERIC_CHARACTERS = '.,'':                                                                                                                                                                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NL  
  S_DATE_FORMAT = 'YYYY-MM-DD HH24:MI' at line 1                                                                                                                                                                                                

In PDOConnection.php line 43:
                                                                                                                                                                                                                                                
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NL  
  S_DATE_FORMAT = 'YYYY-MM-DD HH24:MI' at line 1                                                                                                                                                                                                                                                              
In PDOConnection.php line 41:
                                                                                                                                                                                                                                                
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NL  
  S_DATE_FORMAT = 'YYYY-MM-DD HH24:MI' at line 1                                                                                                           
doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**How to reproduce**  
<!-- Code and/or config needed to reproduce the problem. If it's a complex bug,
     create a "bug reproducer" as explained in:
     https://symfony.com/doc/current/contributing/code/reproducer.html -->
```
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                logging: '%kernel.debug%'
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #path: '%database_path%'
            oracle:
                driver: oci8
                host: '%database_oracle_host%'
                port: '%database_oracle_port%'
                dbname: '%database_oracle_name%'
                user: '%database_oracle_user%'
                password: '%database_oracle_password%'
                #servicename: '%database_oracle_servicename%'
                #sessionMode: 4
                charset: AL32UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                dql:
                    string_functions:
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat # only for DATE_FORMAT
                        FIND_IN_SET: DoctrineExtensions\Query\Mysql\FindInSet
                        TO_DATE: DoctrineExtensions\Query\Oracle\ToDate
                filters:
                    base.area_filter: BaseBundle\Doctrine\Filter\AreaFilter
                    base.organization_filter: BaseBundle\Doctrine\Filter\OrganizationFilter
                    organ.organ_filter: OrganBundle\Doctrine\Filter\OrganFilter
            oracle:
                connection: oracle
                mappings:
                    SwapBundle: ~
```
**Possible Solution**  
<!--- Optional: only if you have suggestions on a fix/reason for the bug -->

**Additional context**  
<!-- Optional: any other context about the problem: log messages, screenshots, etc. -->
