### ISSUE TITLE
Internationalized routing for security.check_path

### ISSUE THREAD

**Issue by indapublic** [symfony/symfony#33669]
**Description**  
I have API app and two languages.
Thanks for [documentation](https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing), it's successfully working now. But seems like check_path doesn't support internationalized routing

```yaml
firewalls:
    api_login:
        pattern:  ^/(en|ru)/v1.0/auth/login
        stateless: true
        anonymous: true
        json_login:
            provider: user_provider
            check_path: /en/v1.0/auth/login
    #                    en: /en/v1.0/auth/login
    #                    ru: /ru/v1.0/auth/login
            username_path: email
            success_handler: lexik_jwt_authentication.handler.authentication_success
            failure_handler: lexik_jwt_authentication.handler.authentication_failure
        provider: user_provider
```
