### ISSUE TITLE
No way of embedding encore built images in Mailer's templated emails

### ISSUE THREAD

**Issue by mikemix** [symfony/symfony#33679]
**Description**  

Mailer should integrate with Encore easily, something like:

`<img src="{{ email.image(asset('build/images/logo.png')) }}">`

should work. But it doesn't of course.

**Comment by yceruto** [comment]
As documentation says: define a Twig namespace that points to whatever directory your images are stored in, for example:

```yaml
# config/packages/twig.yaml
twig:
    paths:
        # point this wherever your images live
        public/build/: build
```
next, in your email template:

```twig
{# '@build/' refers to the Twig namespace defined earlier #}
<img src="{{ email.image('@build/logo.png') }}" alt="Logo">
<img src="{{ email.image('@build/subdir/logo.png') }}" alt="Logo">
```
this will not work if the constructed image has some random suffix, e.g. when `.enableVersioning()` is defined in `webpack.config.js` config file.

---

If you have enabled the versioning strategy, you can do the follows:
```yaml
# config/packages/twig.yaml
twig:
    paths:
        public/: public
```
and build the template name using the string concat operator `~`:
```twig
{# '@public' refers to the Twig namespace defined earlier #}
<img src="{{ email.image('@public' ~ asset('build/logo.png')) }}" alt="Logo">
```
