### ISSUE TITLE
AbstractController don't get correct container without autowiring

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#33755]
**Symfony version(s) affected**: 4.3.4

**Description**  

When currently using the AbstractController in a Bundle where you normally don't use autowiring the AbstractContoller does contain the full Container and not only the subscribed services.

**How to reproduce**

```yaml
# services.yaml

services:
    _defaults:
        autowire: false # Disabled
        autoconfigure: false

    App\Controller\DefaultController:
        tags: ['container.service_subscriber']
```

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class DefaultController extends AbstractController
{
    /**
     * @Route("/default", name="default")
     */
    public function index()
    {
        $has = $this->has('translator');

        return new Response(
            $has
                ? '<span style="color: red">Should not contain translator</span>'
                : '<span style="color: green">Ok</span>'
        );
    }

    public static function getSubscribedServices()
    {
        $services = parent::getSubscribedServices();
        // $services['translator'] = TranslatorInterface::class;

        return $services;
    }
}
```

**Possible Solution**  

Not sure there seems to be logic in the autowiring which should be on the `container.service_subscriber` tag.

**Additional context**  

Service without autowiring:

```
  Service ID       App\Controller\DefaultController
  Class            App\Controller\DefaultController
  Tags             container.service_subscriber
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
```

Service with autowiring:

```
  Service ID       App\Controller\DefaultController
  Class            App\Controller\DefaultController
  Tags             container.service_subscriber
  Calls            setContainer
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   no
```

As you see the autowiring does add a `Calls setContainer` this should not be something which should be added only when using autowiring I think. This should be added by the compilerpass for all `container.service_subscriber` tagged services.

**Comment by nicolas-grekas** [comment]
For the compiler pass, that's expected behavior to me: the pass that deals with `container.service_subscriber` cannot discover the injection point as that's not its job.

But I think we should autoconfigure calling setContainer for AbstractController.
That wouldn't fix your example since you also disabled autoconfiguration.

But if you disable both autowiring and autoconfiguration, it means you opt-out from automation: declare the call explicitly then:
```yaml
    App\Controller\DefaultController:
        calls: ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags: ['container.service_subscriber']
```

**Comment by alexander-schranz** [comment]
@nicolas-grekas Ok I understand but when creating a bundle its recommended not using autowire or autoconfigure in it. Maybe we can extend the `container.service_subscriber` with e.g. a inject_method e.g.:

```yaml
    App\Controller\DefaultController:
        calls: ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - {name: 'container.service_subscriber', inject_method: 'constructor'}

    App\Controller\DefaultController:
        calls: ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - {name: 'container.service_subscriber', inject_method: 'setter'}
```
