### ISSUE TITLE
[SecurityBundle] Profiler collect Voter decisions even when security is disabled

### ISSUE THREAD

**Issue by tyx** [symfony/symfony#33908]
**Symfony version(s) affected**: 4.3.5

**Description**  

When profiler is enabled, we try to collect data on access decision voters even on routes where security is disabled.

For example, I have an internal route `/_monitoring` and I don't want to run any security operation on it.

![Screenshot_2019-10-08 Screenshot](https://user-images.githubusercontent.com/245494/66387383-1fed0680-e9c4-11e9-83ed-7800ad78c2b9.png)

I expect my PreviewModeVoter not to be loaded.

**How to reproduce**  
```yaml
security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        monitoring:
            pattern: ^/_monitoring
            security: false
            stateless: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            stateless: true
        main:
            anonymous: true
            guard:
                authenticators:
                    - Oxatis\UserAuthentication\Infra\LegacyAuthenticator
            stateless: true # Allow to read session from legacy on every request
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/, roles: [PREVIEW_MODE] } # Triggered by a custom voter
```

**Possible Solution**  

I test to not collect voter decisions when security on firewall is disabled. It works but I'm not sure of the impact. 

If you are ok on this change, I can make a PR.
