### ISSUE TITLE
SameSite cookie option could not be set to "none"

### ISSUE THREAD

**Issue by ihmels** [symfony/symfony#33926]
**Symfony version(s) affected**: 4.3.*

**Description**  
The PR #31475 allows to set the samesite cookie flag to "none", but it is not allowed in the `framework.session.cookie_samesite` or `remember_me.samesite` config.

**How to reproduce**  

```yaml
# framework.yml
framework:
    session:
        cookie_samesite: 'none'

# or packages/security.yml
security:
    firewalls:
        main:
            remember_me:
              samesite: 'none'
```

**Additional context**  

```
The value "none" is not allowed for path "framework.session.cookie_samesite".
Permissible values: null, "lax", "strict"
```
