### ISSUE TITLE
Using nullable env params in services

### ISSUE THREAD

**Issue by Gonzalo1987** [symfony/symfony#33934]
I can't get the same result that using
```yaml
services: 
    bundle_1:
        param_1: null
```

First I've tried use a env param like 'param1=null' in my .env file, and I've seen that env params only can be used for strings (I've read about it). So I've seen about the params preprocessor and I've tried with: 
```yaml
services: 
    bundle_1:
        param_1: '%env(default::my_inexistent_param)%'
```
But it doesn't work neither, it throws an error because the param_1 accepted types are: 
bool, string, float, and int, and the return types, are bool, string, float, int, and array...

I've read in other issue that I needed to put explicitly the type, with:
```yaml
services: 
    bundle_1:
        param_1: '%env(string:default::my_inexistent_param)%'
```

And the error is gone, moreover I can get the null value from my Controller when I request that param, everything seems to be ok! but... If I use that """null""" value in the service, it doesn't behave like a real null. 
I want to say, my 'bundle_1' doesn't make the same with:

```yaml
services: 
    bundle_1:
        param_1: '%env(string:default::my_inexistent_param)%'
```
than with
```yaml
services: 
    bundle_1:
        param_1: null
```
I could use too: 

```yaml
services: 
    bundle_1:
        param_1: ~
```
 but definitely using '%env(string:default::my_inexistent_param)%' I don't get my expected behavior

Could someone help me please? I need use the default config value in specific machine and I can't achieve this.

Thank you very much!

**Comment by Gonzalo1987** [comment]
My especific case is: 

```
fos_rest:
    exception:
        enabled: true
        exception_controller: '%env(string:default::my_inexistent_param)%'
```

If I put there null or ~ in the param 'exception_controller' I get: 
{"code":403,"message":"Forbidden"} 

But with '%env(string:default::my_inexistent_param)%' I get:
```
{
    "error": {
        "code": 403,
        "message": "Forbidden",
        "exception": [
            { stack trace... }}}
```

I think that is a symfony related problem because I understand that I should be able to obtain the default behavior in some machines and other specific using .env parameters... (With the old parameters.yml files I could, simply using (it works, I've checked it):

parameters:
    my_param1: null

```
fos_rest:
    exception:
        enabled: true
        exception_controller: '%my_param1%'
```

**Comment by nicolas-grekas** [comment]
I reproduced by creating a project with the serialize + friendsofsymfony/rest-bundle, then in `config/packages/fos_rest.yaml`:
```yaml
fos_rest:
    exception:
        enabled: true
        exception_controller: '%env(default::my_inexistent_param)%'
```

This makes `Config/Definition/BaseNode` throw with:
> Invalid type for path "fos_rest.exception.exception_controller". Expected one of "bool", "int", "float", "string", but got one of "bool", "int", "float", "string", "array".

I'm not sure this exception is correct: we could require a non-empty intersection here instead of a full inclusion.

In `BaseNode.php` I changed this:
```diff
-        if ($validTypes && array_diff($knownTypes, $validTypes)) {
+        if ($validTypes && $knownTypes && !array_intersect($knownTypes, $validTypes)) {
```

But then `ScalarNode` fails because the placeholder we use is an empty array.

@ro0NL would you be able to have a look? We might be able to choose a placeholder that matches the intersection?

**Comment by ro0NL** [comment]
the exception message seems correct as `default` may provide an array which is not allowed in `fos_rest.exception.exception_controller`

**Comment by ro0NL** [comment]
if i understand well, we need a nullable caster to cast to `string` or preserve `null`

**Comment by nicolas-grekas** [comment]
I really think we should allow non-empty intersections. We should be conservative up to the point that legit config fail...

**Comment by ro0NL** [comment]
actually i think `exception_controller: '%env(string:default::my_inexistent_param)%'` is the right syntax already.

the container is compiled as such: `new \FOS\RestBundle\EventListener\ExceptionListener($this->getEnv('string:default::my_inexistent_param'),`

and then we hit

https://github.com/symfony/symfony/blob/38b9a27976d36c4ffbfeb9e666319d77ffc8b3c0/src/Symfony/Component/DependencyInjection/EnvVarProcessor.php#L121-L124

i can confirm `null` is produced during runtime.

Re-reading the issue, it's confusing what you are actually doing. If u use 

```yaml
services: 
    bundle_1:
        param_1: '%env(string:default::my_inexistent_param)%'
```

i get the expected `The configuration key "param_1" is unsupported for definition "bundle_1"`
