### ISSUE TITLE
Symfony v3.4.6 - cannot autowire service

### ISSUE THREAD

**Issue by dancostinel** [symfony/symfony#33975]
**Symfony version(s) affected**: 3.4.6

**Description**  
I'm trying to autowire the request_stack into a class, but it fails with the following error message:

```
FatalThrowableError   HTTP 500 Internal Server Error
Type error: Return value of AppBundle\Helper\AbstractBaseHelper::getRequestStack() must be an instance of Symfony\Component\HttpFoundation\RequestStack, null returned.
```

**How to reproduce**  
app/config/services.yml:
```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    app.abstract_base_helper:
        class: AppBundle\Helper\AbstractBaseHelper
        public: true
        calls:
            - ['setRequestStack', ['@request_stack']]
```

src/AppBundle/Helper/AbstractBaseHelper:
```php
<?php

namespace AppBundle\Helper;

use Symfony\Component\HttpFoundation\RequestStack;

abstract class AbstractBaseHelper
{
    private $request;

    #USING AUTOWIRE
    public function setRequestStack(RequestStack $requestStack): self
    {
        $this->request = $requestStack;

        return $this;
    }

    public function getRequestStack(): RequestStack
    {
        return $this->request;
    }
}
```

src/AppBundle/Services/QuizService.php
```php
<?php

namespace AppBundle\Services;

use Symfony\Component\HttpFoundation\JsonResponse;
use AppBundle\Helper\AbstractBaseHelper;

class QuizService extends AbstractBaseHelper
{
    private $request;

    public function processSuccess(): JsonResponse
    {
       # GETTING THE ERROR HERE WHEN CALLING ->getRequest()
        /** @var int $domainID */
        $domainID = (int)$this->getRequestStack()->getCurrentRequest()->get('domain');
        dump($domainID);die;
    }
}
```

Any help is much appreciated!
