### ISSUE TITLE
[Messenger][BC-break] Sync transport can no longer be configured by env variable

### ISSUE THREAD

**Issue by Devristo** [symfony/symfony#34115]
**Symfony version(s) affected**: 4.4.x-dev
**Description**  
Since https://github.com/symfony/symfony/pull/34069 the `sync://` transport is handled differently. 
The case when the transport name is defined using an environment variable is broken.

Works:
```
framework:
   messenger:
     transports:
       default: "sync://"
```

Broken case:
```
parameters:
  env(MESSENGER_TRANSPORT): sync://

framework:
   messenger:
     transports:
       default: "%env(MESSENGER_TRANSPORT)%"
```

Yields `No transport supports the given Messenger DSN "sync://"` when dispatching a message.

**How to reproduce**  
See https://github.com/Devristo/sf4.4-messenger-bug for a reproducer.

**Possible Solution**  

 * Document this BC-break
 * Fix the BC-break: If someone could give me some pointers I am willing to implement a fix.
