### ISSUE TITLE
[Cache] Cannot use env vars to setup RedisAdapter

### ISSUE THREAD

**Issue by oldskool** [symfony/symfony#34143]
**Symfony version(s) affected**: 4.3.3
**Symfony Cache version(s) affected**: 4.3.5

**Description**  

When trying to set up the RedisAdapter as a service, you can not use environment variables to pass as arguments for creating the connection with the `RedisAdapter::createConnection` static method. Apparently the environment variable is always passed as a quoted string, but the RedisAdapter cannot seem to handle this currently.

**How to reproduce**  

Define a service and connection like this in the `services.yaml` file:
```yaml
app.cache:
  class: 'Symfony\Component\Cache\Adapter\RedisAdapter'
  arguments:
    $redisClient: '@app.cache.redis'

app.cache.redis:
  class: '\Redis'
  factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
  arguments:
    $dsn: '%env(REDIS_DSN)%'
```

Set the `REDIS_DSN` env var in your `.env` or `.env.local` file like this:
```
REDIS_DSN=redis://redis:6379
```

**Additional context**  

The error thrown is:
> Invalid Redis DSN: 'redis://redis:6379' does not start with "redis:" or "rediss".

So apparently the DSN is a kind of double quoted when passed through an env var, but the internal check does a very strict positional check to see if the string starts with `redis:`, while apparently in env var context it is `'redis:`.

**Comment by nicolas-grekas** [comment]
Are you using docker-compose? Then you should up vote https://github.com/docker/compose/pull/6923

**Comment by oldskool** [comment]
> Are you using docker-compose? Then you should up vote [docker/compose#6923](https://github.com/docker/compose/pull/6923)

I am. Thanks for that tip, just upvoted that. Guess it's a compose issue rather than a Symfony issue then, so I'll close this issue.

**Comment by oldskool** [comment]
Just in case someone runs into this issue as well, I've been able to work around it by defining the problematic env var separately (on top of the dotenv include) in my `docker-compose.yaml` file:

```yaml
    env_file:
      - .env.local
    environment:
      REDIS_DSN: redis://redis:6379
```

This does work as expected.
