### ISSUE TITLE
EnvNotFoundException on variables declared in "parameters" section when using "default" processor

### ISSUE THREAD

**Issue by szoper** [symfony/symfony#34237]
**Symfony version(s) affected**: 4.3.5

**Description**  
Env vars declared in `parameters` section are not available in other parameter declarations (_EnvNotFoundException_) but only when using `default` processor.

**How to reproduce**  
This works:

```yaml
# config/packages/sentry.yaml
parameters:
  env(VERSION_JSON): '%kernel.project_dir%/version.json'
  env(APP_VERSION): '%env(key:version:json:file:resolve:VERSION_JSON)%'
sentry:
    options:
      environment: '%kernel.environment%'
      release: '%env(APP_VERSION)%'
```

And this does not - `APP_VERSION` is null. The only difference is the use of `default` processor.  
Extracting `key:version:json:file:resolve:VERSION_JSON` into separate env var is useless.

```yaml
parameters:
  env(VERSION_JSON): '%kernel.project_dir%/version.json'
  env(APP_VERSION): '%env(default::key:version:json:file:resolve:VERSION_JSON)%'
sentry:
    options:
      environment: '%kernel.environment%'
      release: '%env(APP_VERSION)%'
```

**Additional context**  
![no-env-var](https://user-images.githubusercontent.com/2564066/68212745-76a52a80-ffda-11e9-8386-51a1130ccc3f.png)
