### ISSUE TITLE
[DIC] Simplify service overloading / specialization 

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#34259]
**Description**  

In some application, there are many workflows / state machine. And in order to simplify DI, I use the following pattern:

```php
namespace App\Reservations;

use Symfony\Component\Workflow\StateMachine;

class ReservationWorkflow extends StateMachine
{
}
```

with this configuration:

```yaml
services:
    App\Reservations\ReservationWorkflow:
        parent: state_machine.reservation
```

This allow me to "require" a `ReservationWorkflow` in another service, and I get the right workflow.

(If you wonder, it's not possible to alias  ReservationWorkflow to `@state_machine.reservation`, because the type hint check will fail at run time)

I wondering if we can do something in Symfony to simplify this experience because

1. writing this code is boring
1. it's not obvious we can do that
1. since the service `App\Reservations\ReservationWorkflow` has a parent, it can not be declared in the main `services.yml` (`_instanceof` is not compatible with `parent`)

**Example**  

It could be nice if we could do that:

```yaml
services:
    App\Reservations\ReservationWorkflow:
        specialize: state_machine.reservation
        # or any better name
````

And that all. Symfony will create the class_alias, or generate the code (for autocomplete in IDE)

WDYT ?

**Comment by stof** [comment]
Why relying on autowiring a child class rather than relying on named bindings for the autowiring ? Defining an alias `Symfony\Component\Workflow\StateMachine $reservationWorkflow: @state_machine.reservation` would let you write constructor with arguments `StateMachine $reservationWorkflow` which would select the right workflow to implement (you could switch that to use the interface in the alias and the typehint btw). And that would not require any weird magic about class aliases (which might not be discovered by your IDE btw, and are tricky to define at the right time).

Btw, FrameworkBundle 4.4 (maybe also 4.3 but I haven't checked) already automatically defines such autowiring typehints for the WorkflowInterface and an argument named with your workflow id (`$reservation` in your example).

**Comment by lyrixx** [comment]
> Why relying on autowiring a child class rather than relying on named bindings for the autowiring

No, I don't want that. I want to rely on the parent class definition. That's why I use the `parent` key. Did I miss something?

>  would let you write constructor with arguments StateMachine $reservationWorkflow which would select the right workflow to implement

Symfony could not know, except if you use something like
```yaml
services:
    _defaults:
        Symfony\Component\Workflow\StateMachine $reservationWorkflow: @state_machine.reservation
```

> Btw, FrameworkBundle 4.4 (maybe also 4.3 but I haven't checked) already automatically defines such autowiring typehints for the WorkflowInterface and an argument named with your workflow id ($reservation in your example).

I forgot about that. Indeed, It could fix indeed my issue. I have to try
