### ISSUE TITLE
Cache: Set cache namespace directly from cache configuration

### ISSUE THREAD

**Issue by MiroslavMerinsky** [symfony/symfony#34277]
**Description**  
Nowadays there is one way to influence namespace (key prefix) to set the prefix_seed parameter.  When a shared cache is needed, especially on AWS, each EC2 have different namespace computed and shared cache can not be used.

Could you implement possibility to set namespace directly? I know, there is another way how to configure it, but it is not a clear way as this proposal. 

**Example**  
```
framework:
    cache:
       namespace: foo.eu
       app: cache.adapter.redis
```
