### ISSUE TITLE
DI BC break for integer service ids since 3.4.27 & 4.2.9, >4.3

### ISSUE THREAD

**Issue by bburnichon** [symfony/symfony#34296]
**Symfony version(s) affected**: since 3.4.27

**Description**  

If using a ServiceLocator with ids that looks like integers, given offset is ignored.

**How to reproduce**  

```yaml
service:
    my_service_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        public: false
        tags: ['container.service_locator']
        arguments:
            -
                '16': '@my_service1'
                '32': '@my_service2'
```

In my usecase, I want a different service based on a computation over data. (a string length). It was working fine with version 3.4.27 but doing the upgrade, system is now broken without changing the dependency injection configuration

**Possible Solution**  

Issue occurs since https://github.com/symfony/symfony/commit/7146b95303187d5859110741be07f88cda83919c#diff-af68f8fbd009fd8de36403795ea0cf0aR52

**Additional context**
