### ISSUE TITLE
[RFC][DI] Autowire collections of implementations without yaml

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony#34314]
**Description**  

Injecting an autowired collection of implementations based on an interface already is powerful, and a matter of a couple of lines of yaml:

```yaml
services:
    _defaults:
        bind:
            $repositories: !tagged 'app.search_repository'

    _instanceof:
        App\ReadModel\SearchRepositoryInterface:
            tags: ['app.search_repository']
```

Would it be possible to move this out of yaml entirely? That would make autowiring a collection of implementations even easier.

**Example**  

Would the container on compilation be able to detect the need for a collection of implementations, for instance via the argument typehints?

... or by detecting that the constructor argument uses the splat operator?

```php
function __construct(SearchRepositoryInterface $repositories = [])

function __construct(SearchRepositoryInterface ... $repositories)
```

... or by implementing a helper interface?

```php
use Symfony\Component\DependencyInjection\BindImplementationsOfInterface;

class Searcher implements BindImplementationsOfInterface 
{
    function __construct(SearchRepositoryInterface $repositories = [])

    function bindInterfaces()
    {
        return SearchRepositoryInterface::class;
    }
}
```

... or by annotation

```php
class Searcher
{
    /*
     * @ParamConverter("!implements SearchRepositoryInterface")
     */
    function __construct(SearchRepositoryInterface $repositories = [])
}
```
