### ISSUE TITLE
[RFC][Messenger] Ability to configure queue via yaml config

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#34454]
I have following DSN and config:
`MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/requests'`
```yaml
transports:
    rabbitmq:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
            queues:
                requests: #hardcoded
                    arguments:
                        x-max-priority: 10
```
I want explicitly set `x-max-priority` arguments regardless of used queue in DSN. Currently I need to hardcode queue name
Something like this would be great:
```yaml
transports:
    rabbitmq:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
            queue: #default config for queues
                arguments:
                    x-max-priority: 10
```
