### ISSUE TITLE
[Messenger] Looks like default retry_strategy drops my messages in RabbitMQ queue. And i can't cancel it.

### ISSUE THREAD

**Issue by dvc** [symfony/symfony#34461]
**Symfony version(s) affected**: v4.3.8

**Description**  

```php
# 
framework:
    messenger:
        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            App\Message\Event\TestEvent: async
        default_bus: bus
        buses:
            bus:
```
RabbitMQ "messages" exchange is fanout by default. All RabbitMQ entities created by Symfony Messenger.

**Actual**

After last symfony update (v4.3.4 to v4.3.8) my messages drops from queue after 1-2 seconds. It's very very bad defaults!

And i have no idea, how to cancel this angry helper. It's always active with very small TTL. 

**Expected**

IMHO retry policy must check connect with RabbitMQ, not delivery to subscriber(s). My consumer can't use persistent connect and gets messages by cron.

**Additional context**  

publish some messages (no active consumers in queue):

![image](https://user-images.githubusercontent.com/588564/69215155-5650a080-0b82-11ea-8495-91a80e425216.png)

after couple of seconds:

![image](https://user-images.githubusercontent.com/588564/69215221-826c2180-0b82-11ea-81dc-2c9c44f6bc8a.png)

**Comment by dvc** [comment]
I found workaround how to not use retry policy: using custom queue name not equal to "messages":

```yaml
           async: 
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
               options:
                   exchange:
                       name: test # !!! should be != messages if you want not fanout type
                       type: direct
                   queues:
                       test: # !!! should be != messages
                           durable: true
                           arguments:
                               delivery_mode: 2
```

And i can create "direct" exchange if name != "messages". Default name always creates fanout exchange.


But it is... not friendly defaults. And not covers by documentation. Looks like a bug.
