### ISSUE TITLE
Cache-Adapter not replaced in environment configuration

### ISSUE THREAD

**Issue by alxndrbauer** [symfony/symfony#34488]
**Symfony version(s) affected**: 4.4

**Description**  
I've added a cache pool in config/cache.yaml

```
### config/packages/cache.yaml
framework:
    cache:
        pools:
            cache.test_cache:
                adapter: cache.adapter.filesystem
```
When i try to overwrite the adapter in dev environment, the second adapter just gets added and not replaced

```
### config/packages/dev/cache.yaml
framework:
    cache:
        pools:
            cache.test_cache:
                adapter: cache.adapter.array
```
`bin/console debug:config framework` produces following output:
```
framework:
    router:
        resource: 'kernel::loadRoutes'
        type: service
        enabled: true
        utf8: true
        http_port: 80
        https_port: 443
        strict_requirements: true
    cache:
        pools:
            cache.test_cache:
                adapters:
                    - cache.adapter.filesystem
                    - cache.adapter.array
                tags: null
                public: false
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
        default_redis_provider: 'redis://localhost'
        default_memcached_provider: 'memcached://localhost'
        default_pdo_provider: database_connection
```
in 4.3 the adapter has been replaced and not added
