### ISSUE TITLE
[Monolog Bridge] ErrorException: Accessing static property $sendHeaders as non static

### ISSUE THREAD

**Issue by Sander-Toonen** [symfony/symfony#34505]
**Symfony version(s) affected**: 4.4
The problem started after updating SF4.3 to 4.4 but I'm not really sure why earlier versions would not be affected. I am running php 7.3.11.

**Description**  
When using the ``ChromePHPHandler`` the following error may occur:

> Notice: Accessing static property Symfony\Bridge\Monolog\Handler\ChromePhpHandler::$sendHeaders as non static in ChromePhpHandler.php line 62

To replicate add the following to the monolog configuration: 
```yaml
monolog:
    handlers:
        chromephp:
            type: chromephp
            level: debug
```

I think we can replace the `$this->sendHeaders` on lines 44 and 62 with `self::$sendHeaders` without any problem since the ``sendHeaders`` property is static in both version 1.25.1 and 2.x of monolog. 

PR is on its way.
