### ISSUE TITLE
Having a session issue after updating to 4.4

### ISSUE THREAD

**Issue by xoniq** [symfony/symfony#34568]
I'm having a `EventListener/LocaleListener.php` which contains these lines:

```php
if (($locale = $request->attributes->get($session_name)) !== null) {
    $request->getSession()->set($session_name, $locale);
} elseif ($locale = $request->getSession()->get($session_name)) { /* Exception trace points here, explicit: Session->get('_locale') */
    $locale = $request->getSession()->get($session_name);
    $request->setLocale($locale);
} elseif ($locale = $request->attributes->get('locale')) {
    $request->getSession()->set($session_name, $locale);
    $request->setLocale($locale);
} else {
    $request->setLocale($request->getSession()->get($session_name, $this->defaultLocale));
}
```

But in the middle of my homepage, I get this error:

```
Failed to start the session because headers have already been sent by "vendor/symfony/http-foundation/Response.php" at line 363.
```

How can I fix this? I'm not doing anything special here, and it worked up until 4.4.

**Comment by chr-hertel** [comment]
hey @xoniq, can you please share additional details
- on which kernel event is your listener executed?
- how does your security firewall config looks like if there is one?
- do you use sub requests?

**Comment by xoniq** [comment]
Hello @chr-hertel 

The implement:
`class LocaleListener implements EventSubscriberInterface`

The `services.yml` section:
```yaml
    app.locale_listener:
        class: App\MyBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }
```

My `security.yml`:
```yaml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: auto

    access_denied_url: /login

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory: ~

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true
            provider: fos_userbundle

        admin_secured_area:
            pattern:   ^/admin
            anonymous: ~
            provider: fos_userbundle
            form_login:
                provider: fos_userbundle
                use_referer: true
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin
            logout:
                path:   /admin/logout
                target: /admin
            switch_user: true
            context: primary_auth
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                domain:   ~

        user_secured_area:
            pattern:   ^/portal
            anonymous: ~
            provider: fos_userbundle
            form_login:
                provider: fos_userbundle
                use_referer: true
                login_path: /portal/login
                check_path: /portal/login_check
                default_target_path: /portal
            logout:
                path:   /portal/logout
                target: /portal
            switch_user: true
            context: primary_auth
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                domain:   ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            context: primary_auth

        main:
            anonymous: ~
            http_basic: false
            switch_user: true
            provider: fos_userbundle
            context: primary_auth

    access_control:
        - { path: ^/admin/lostpassword, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/portal/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/portal/lostpassword, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/portal/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/portal/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/portal, role: [ROLE_STUDENT,ROLE_TEACHER,ROLE_OWNER] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
```

I don't know what you mean by sub requests..
