### ISSUE TITLE
Workflow component should auto-support if name matches FQCN

### ISSUE THREAD

**Issue by Steveb-p** [symfony/symfony#34628]
**Description**  
Similarly to how dependency injection works, if workflow is defined using FQCN instead of name, it could automatically assume that it is the only class that it should handle, unless defined otherwise.

**Example**  
For example consider following `workflow.yaml`:
```yaml
framework:
  workflows:
    App\Entity\PaymentRequest:
      type: state_machine
      marking_store:
        type: method
        property: status
      places: []
      transitions: []
```

It could automatically resolve into:
```yaml
framework:
  workflows:
    App\Entity\PaymentRequest: # <-- Name being a FQCN
      type: state_machine
      marking_store:
        type: method
        property: status
      supports:
        - AppBundle\Entity\PaymentRequest # <-- is set automatically as supported class (unless set otherwise)
      places: []
      transitions: []
```

Similarly to how in `services.yaml`
```yaml
services:
  App\Util\SomeService:
```

resolves to (when encountering FQCN):
```yaml
services:
  App\Util\SomeService:
    class: App\Util\SomeService
```
