### ISSUE TITLE
[DependencyInjection][Yaml] Injecting DateTime[Immutable] instances

### ISSUE THREAD

**Issue by chr-hertel** [symfony/symfony#34634]
**Description**  
sometimes i use a service for abstracting the system clock and usually inject strings to manipulate "now"
```yaml
parameters:
    env(NOW): 'now'

services:
    App\System\Clock:
        $now: '%env(NOW)%'
```
see: https://github.com/chr-hertel/symfonycon-bot/blob/master/config/services.yaml#L41-L44

in this example i need to have a constructor like this
```php
class Clock
{
    public function __construct(string $now)
    {
          $this->now = new \DateTimeImmutable($now);
    }
}
```

a nice step to ease this kind of clock abstraction in symfony would be to inject DateTime[Immutable] instances already

**Example**  
```yaml
parameters:
    env(NOW): 'now'

services:
    App\System\Clock:
        $now: !datetime '%env(NOW)%'
```

```php
class Clock
{
    public function __construct(\DateTimeImmutable $now)
    {
          $this->now = $now;
    }
}
```

was thinking about an implementation but unsure if this would fit into DependencyInjection as custom tag or in Yaml?

**Comment by stof** [comment]
your suggestion of using a YAML tag won't work here, as you expect using an env placeholder here. But the YAML parser won't see the datetime string. It will see `%env(NOW)%`, which is not a validate datetime value.
If you want this to be usable with env placeholders, you would need to use an env processor for the conversion, not a YAML feature.

**Comment by chr-hertel** [comment]
so we have those two options?

```yaml
    App\System\Clock:
        $now: !datetime '%env(NOW)%'
    App\System\Clock:
        $now: !datetime '%env(NOW)%'

**Comment by ro0NL** [comment]
and one existing option :)

```yaml
parameters:
    env(NOW): 'now'

services:
    _defaults:
        bind:
            'DateTimeInterface $now': !service
                class: \DateTimeImmutable
                arguments: ['%env(NOW)%']
```

`echo NOW=yesterday >> .env && 🚀`
