### ISSUE TITLE
Session storage always empty

### ISSUE THREAD

**Issue by darkiron** [symfony/symfony#34651]
**Symfony version(s) affected**: 4.4

**Description**  
session data always empty

**How to reproduce**  
config framework.yaml : 
```
    session:
        # enabled: true
        # cookie_secure: auto
        # cookie_samesite: null
        # cookie_lifetime: 0
        # use_cookies: true
        # storage_id: session.storage.php_bridge
        # handler_id: ~
        enabled: true
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: null
```

```
 if (!$request->hasSession()) throw new \Exception('pas de session');
    else print_r($request->getSession()->get('already_answered'));
       
    $serveurSession = $request->getSession();
        
    generate_id: $id = rand(1, 25);

    if (!$serveurSession->has('already_answered')) $serveurSession->set('already_answered', []);

    if ($serveurSession->get('current_question') !== $id && !in_array($id, $serveurSession->get('already_answered')))
        $serveurSession->set('current_question', $id);
    else 
        goto generate_id;

           
    print_r($request->getSession()->get('already_answered'));
    echo sprintf('%s est la question courrante <br>',$request->getSession()->get('current_question'));
```

**Possible Solution**  
--

**Additional context**  
I have add listener on RequestEvent:
```
public function onKernelRequest(RequestEvent $event) {
        $request = $event->getRequest();

        // var_dump(get_class_methods($request));
        if (!$request->hasSession()) {
            $sessionStorage = new NativeSessionStorage([], new NativeFileSessionHandler());
            $session = new Session($sessionStorage);

            $session->start();

            $request->setSession($session);
        }
        
        else {
           // var_dump($request->getSession()->all());die('toto');
        }

        return $request;
    }
```
