### ISSUE TITLE
Error message using virtual properties

### ISSUE THREAD

**Issue by 12rambau** [symfony/symfony#34691]
**Symfony version(s) affected**: 
Symfony 4.2

**Description**  
I'm currently working with the 2.3 version of the easy-admin bundle in Symfony 4.
The [bug referenced here](https://github.com/EasyCorp/EasyAdminBundle/issues/3005) come from symfony.

I try to create a virtual property for the new view. I have the following configuration: 
``` yaml
easy-admin:
    entities:
        FieldTemplate:
            class: App\Entity\FieldTemplate                  
            edit: 
                fields:
                    - { property: toto, type_options: { block_prefix: 'field_to_fill'} }
```

according to [this question](https://stackoverflow.com/a/58710631/6734243) and the [documentation](https://symfony.com/doc/master/bundles/EasyAdminBundle/book/edit-new-configuration.html#virtual-properties), I need to add setter and getter to the virtual entity which I did :
``` php
//src/Entity/FieldTemplate.php

/**
 * @ORM\Entity(repositoryClass="App\Repository\FieldTemplateRepository")
 */
class FieldTemplate
{
    //virtual functions to display the image of the fieldTemplate in easyadminbundle
    
    public function getToto()
    {
        return $this->getImage();
    }

    public function setToto()
    {
        //do nothing
        return $this;
    }
```

The field is displayed properly so the `getter` is found but when I save I get the following error, which suggest that there is no `setter` for my virtual property. 

>Could not determine access type for property "toto" in class "App\Entity\FieldTemplate": Neither the property "toto" nor one of the methods "addTotol()"/"removeToto()", "setToto()", "toto()", "__set()" or "__call()" exist and have public access in class "App\Entity\FieldTemplate".

**Possible Solution**  
find the solution and post it [here](https://stackoverflow.com/a/59068797/6734243)

Not an easy one for me... When the form is handled, it send something to the 
`setToto()` property.
 
> even if the `toto` property is a virtual property and doesn't send anything to the db

So even if it does nothing, add a dummy argument to your `setter` such as
```php
setToto($dummy){
    // do nothing 
    return $this
}
```
and it will work like a charm 

What make this bug complicated to catch is that the error message doesn't describe the problem accurately. Would it be possible to update it ? (considering that the use of virtual property is directly illustrated in the symfony Doc)
