### ISSUE TITLE
[Security] Passwords are not encoded when algorithm set to "true"

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#34725]
**Symfony version(s) affected**: 4.3.8

**Description**  

When the algorithm is set to `true`, the passwords are not encoded at all (they are stored as plaintext). I would expect to get an exception instead.

```
security:
    encoders:
        App\User\User:
            algorithm: true
```

**Additional context**  
When you mistype the `algorithm` (e.g. `bcryp` or `aut`), an exception is thrown as expected.
