### ISSUE TITLE
[symfony/workflow] Allow Multiple configuration files

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#34730]
**Description**  

I like that the serialization component allows for separate files per entity, or combined into a single file.  I'd like to do the same with the workflow component.

**Example**  

```yaml
# workflows/Article.yaml
framework:
    workflows:
         article_workflow: 
             type: 'state_machine'
```
And another

```yaml
# workflows/Author.yaml
framework:
    workflows:
         author_workflow: 
             type: 'state_machine'
```

etc.  If there's already a way to do this, can the documentation be updated?  I've tried a few ways.
