### ISSUE TITLE
SF5: Unable to find file "@TwigBundle/Resources/config/routing/errors.xml

### ISSUE THREAD

**Issue by Unlik** [symfony/symfony#34748]
**Symfony version(s) affected**: 5.0.1

**Description**  
Updated from SF 4.4.0 to 5.0.1 just now and got an error:
In FileLoader.php line 173: Unable to find file "@TwigBundle/Resources/config/routing/errors.xml"
and
In Kernel.php line 254:  Unable to find file "@TwigBundle/Resources/config/routing/errors.xml"

**How to reproduce**  
Update via composer

**Possible Solution**  
copied the missing resource folder with error.xml from 4.4 and works again.

**Comment by xabbuh** [comment]
The file has been moved to the FrameworkBundle. You need to load it from there now:

```yaml
_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix: /_error
```

**Comment by B9M** [comment]
in which files !!!

**Comment by B9M** [comment]
in the file : config/routes/dev/twig.yaml

**Comment by melroy89** [comment]
> The file has been moved to the FrameworkBundle. You need to load it from there now:
> 
> _errors:
>     resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
>     prefix: /_error

Just for info..

Today you should use: 

```yaml
_errors:
  resource: '@FrameworkBundle/Resources/config/routing/errors.php'
  prefix: /_error
```
