### ISSUE TITLE
Symfony Composer error symfony/http-kernel v4.4.1 requires symfony/error-handler ^4.4

### ISSUE THREAD

**Issue by nerdusMaximus** [symfony/symfony#34753]
**Symfony version(s) affected**: 4.4.1 (symfony/http-kernel v4.4.1)

**Description**  
After the release of Symfony 4.4 i have tried to update my project to `"minimum-stability": "stable"`. With an `composer update --dry-run` i ran into this Problem

```
Problem 1
      - symfony/http-kernel v4.4.1 requires symfony/error-handler ^4.4 -> no matching package found.
      - sonata-project/doctrine-orm-admin-bundle 3.12.0 requires symfony/http-kernel ^2.8 || ^3.2 || ^4.0 -> satisfiable by symfony/http-kernel[v4.4.1].
      - Installation request for sonata-project/doctrine-orm-admin-bundle ^3.0 -> satisfiable by sonata-project/doctrine-orm-admin-bundle[3.12.0].
```
Later i have noticed that this problem is still existent with "dev" as minimum-stability.

**How to reproduce**  
Installation with this composer.json should reproduce the issue:
```yaml
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "sonata-project/admin-bundle": "^3.0",
        "sonata-project/doctrine-orm-admin-bundle": "^3.0",
        "symfony/asset": "4.4.*",
        "symfony/console": "4.4.*",
        "symfony/dotenv": "4.4.*",
        "symfony/expression-language": "4.4.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "4.4.*",
        "symfony/framework-bundle": "4.4.*",
        "symfony/http-client": "4.4.*",
        "symfony/intl": "4.4.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "4.4.*",
        "symfony/security-bundle": "4.4.*",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.4.*",
        "symfony/twig-bundle": "4.4.*",
        "symfony/validator": "4.4.*",
        "symfony/web-link": "4.4.*",
        "symfony/yaml": "4.4.*"
    },
    "require-dev": {
        "sonata-project/easy-extends-bundle": "^3.0@dev",
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*",
        "symfony/web-server-bundle": "4.4.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.4.*"
        }
    }
}
```
