### ISSUE TITLE
Cannot autowire services from imported file in SF 4

### ISSUE THREAD

**Issue by ITtoponline** [symfony/symfony#34804]
Hi !

I have this file.

```
//services.yaml
imports:
    - { resource: services/rgpd.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


```

And this one
```
//services/rgpd.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\RGPD\Cryptopo:
        arguments:
           - '%kernel.root_dir%'
```

And it gives me this error 
Cannot autowire service "App\RGPD\Cryptopo": argument "$rootDir" of method "__construct()" has no type-hint, you should configure its value explicitly.

But if I put the service definition in the services.yaml file, it is ok !

How can I divide my services definition in multiple files and make it working ?

**Comment by xabbuh** [comment]
The services defined in `services.yaml` override the service defined in the imported files (if any defintion conflicts). The quick fix for your example would be to ignore the `RGPD` directory:

```yaml
services:
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,RGPD,Tests,Kernel.php}'
```

But you will have to that for every directory that is handled by one of the imported files. So if you have more of them, you will probably want to remove the `App\` resource completely.
