### ISSUE TITLE
[routing] route definition with both condition and requirements does not match

### ISSUE THREAD

**Issue by domnuprofesor** [symfony/symfony#34853]
**Symfony version(s) affected**: 5.0

**Description**  
route definition as follows:
```
product_list:
  path: /{prefix_string}/brands/{brand_name}/{id}.html
  controller: 'App\Web\Controller\Brand\ProductListController::index'
  condition: "request.attributes.get('brand_name') == '%config.parameter%'"
  requirements:
    prefix_string: 'optionA|optionB'
```

**How to reproduce**  
define a route as above and define a config parameter to make the route a successful match.
the result is that the route will not match for a correct URL
