### ISSUE TITLE
[Messenger] Dispatch message to different transport or vhost

### ISSUE THREAD

**Issue by dschiffel** [symfony/symfony#34876]
**Description**  
It would be great if we could choose transport or vhost for dispaching messages.

**Example**  
```
framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        transports:
            wendy:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/wendy'
                options:
                    exchange:
                        name: wendy
                        type: direct
                    queues:
                        virtual_hosts:
                            durable: 1
                            binding_keys: ['virtual_hosts']
                        ftp:
                            durable: 1
                            binding_keys: ['ftp']
            stan:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/stan'
                options:
                    exchange:
                        name: stan
                        type: direct
                    queues:
                        virtual_hosts:
                            durable: 1
                            binding_keys: ['virtual_hosts']
                        ftp:
                            durable: 1
                            binding_keys: ['ftp']

        routing:
            # Route your messages to the transports
            'App\Message\VirtualHostNotification': [wendy, stan]
```
For example:
```
            $this->messageBus->dispatch(
                new VirtualHostNotification($virtualHost), [
                    new AmqpStamp( 'virtual_hosts', AMQP_NOPARAM),
                    new AmqpTransport($domain->getWebServer()),
                ]
            );
```

**Comment by Nyholm** [comment]
If Im not misstaken, you can do this already: 

```yaml
framework:
    messenger:
        transports:
            wendy:
                dsn: 'amqp://127.0.0.1/vhost_wendy/workqueue'
            stan:
                dsn: 'amqp://127.0.0.1/vhost_stan/workqueue'
        routing:
            # Route your messages to the transports
            'App\Message\VirtualHostNotification': [wendy, stan]
```

This will create two transport, they will dispatch `VirtualHostNotification` to both. The transports will go to the same AMQP message broker but to different vhosts. 

Or have I misunderstood your question?
