### ISSUE TITLE
[security] Error when calling isPasswordValid() method

### ISSUE THREAD

**Issue by ElGecko76** [symfony/symfony#34882]
**Symfony version(s) affected**: 5.0.1

**Description** 
After implementing the check Credentials method in my UserAuthenticator, I wanted to use the isPasswordValid() function of the UserPasswordEncoderInterface which needs an instance of UserInterface in first parameter and a string in second parameter that corresponds to the passwordPlain. The variables I pass as parameters are indeed an instance of UserInterface and a string but I get this error: 

> Argument 1 passed to Symfony\Component\Security\Core\Encoder\MigratingPasswordEncoder::isPasswordValid() must be of the type string, null given, called in /var/www/project/vendor/symfony/security-core/Encoder/UserPasswordEncoder.php on line 47

This error looks like that: https://github.com/symfony/symfony/issues/34824

**How to reproduce**  
Just create an Authenticator and put this code in the checkCredentials method :

```
public function checkCredentials($login, UserInterface $user): bool
{
        return $this->userPasswordEncoder->isPasswordValid($user, $login->getPasswordPlain());
}
```

**Additional context**  
The code of my security.yaml : 

```
security:
    providers:
        admin:
            entity:
                class: App\Entity\Admin
                property: username
        user:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\Admin: auto
        App\Entity\User: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: ^/
            provider: user
            anonymous: true
            guard:
                authenticators:
                    - App\Helper\Security\UserAuthenticator
            user_checker: App\Helper\Security\AbstractUserChecker
            remember_me:
                remember_me_parameter: login_user[rememberMe]
                secret: '%env(string:APP_SECRET)%'
            logout:
                path: app_security_logout
                target: site_front_home
                invalidate_session: false

        site:
            pattern: ^/
            anonymous: true

    role_hierarchy:
        ROLE_USER: [IS_AUTHENTICATED_ANONYMOUSLY]
        ROLE_ADMIN: [ROLE_USER]

    access_control:
        - { path: ^/administration, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

```
