### ISSUE TITLE
[router] optional prefix on routes does not work

### ISSUE THREAD

**Issue by domnuprofesor** [symfony/symfony#34891]
**Symfony version(s) affected**: 4.4

**Description**  
when importing routes from a resource file with a ```prefix```, symfony will not match a valid route 
with an allowable empty ```prefix``` unless the URL has a double ```/``` in it (```//```).

**How to reproduce**  
Given this setting:
```
web:
  resource: '_routes.yaml'
  prefix: /{route_prefix?}
  requirements:
    route_prefix: valueA|valueB
```

and _routes.yaml:
```
product_list:
  path: '/brands/{brand_name}/{id}.html'
  controller: App\Controller\Brand\ProductController::index
```

the router will match:
`/valueA/brands/{brand_name}/{id}.html` and
```/valueB/brands/{brand_name}/{id}.html``` but **will not match**
```/brands/{brand_name}/{id}.html``` unless you provide the URL like this:
```//brands/{brand_name}/{id}.html```

**Possible Solution**  
Allow for optional prefix values when importing routes.
