### ISSUE TITLE
Change PHPSESSID on each request

### ISSUE THREAD

**Issue by cristobal85** [symfony/symfony#34958]
**Symfony version(s) affected**: 4.3.9

**Description**  
The PHPSESSID value is changed on each request. If I logged in without remember-me cookie enabled, response is redirect to login page. When I do reload the login page the PHPSESSID doesn't change but in other pages (logged), the PHPSESSID change the value on each reload.
I have tried with SSL lets encrypt certificate and without SSL certificate. 

This is my security.yaml:

```yaml
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\AuthAuthenticator
            logout:
                path:   app_logout
                
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/map/*, roles: ROLE_ADMIN, methods: [POST, PUT] }
        - { path: ^/, roles: ROLE_USER }
```

and framework.yaml:

```yaml
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: es

    session:
        enabled: true
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

```
