### ISSUE TITLE
Misleading warning (?) cache.WARNING: Failed to save key "mystringtags" of type integer.

### ISSUE THREAD

**Issue by rbaarsma** [symfony/symfony#34962]
**Symfony version(s) affected**: 4.4.1

**Description**  
I see this warning in the logs:

```
cache.WARNING: Failed to save key "stream.thiemo_sysnat_e9_v4-publish-1573137262tags" of type integer. {"key":"stream.thiemo_sysnat_e9_v4-publish-1573137262\u0000tags\u0000","exception":null}
```

The real problem is probably (?) that I'm trying to invalidateTags where the tag does not exist, but the warning message is not even close to telling me that.

**How to reproduce**  
I'm using both doctrine ORM and doctrine ODM, and re-using the doctrine ORM cache pool to store ODM result cache manually

```yaml
framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapters:
                    - cache.adapter.array
                    - cache.adapter.apcu
                    - cache.adapter.redis
                tags: true
```

At some point I invalidate tags, but it is possible that the tag has not been created
```php
        $this->doctrineResultCachePool->invalidateTags([
            sprintf('%s-%s-%d', $code, $type, null), // latest version
            sprintf('%s-%s-%d', $code, $type, $revision), // specific revision
        ]);
```

That's when this message shows up.

Interestingly enough I get 4 warnings, two for each tag. Perhaps the tag was in redis, but not in this pod?

**Possible Solution**  
Improved warning message that I've tried to invalidate a tag that does not exist.

**Comment by nicolas-grekas** [comment]
I'm not able to reproduce the warning. When an item is not found, invalidating it doesn't trigger the warning unless the tag cannot we written (invalidating writes to the pool).
Can you provide a reproducer we could clone locally? That'd allow understanding what's going on.

Status: needs feedback

**Comment by rbaarsma** [comment]
I've just got reports that the cache is not invalidating properly. I'm afraid that the tags are indeed not saved. Possibly the warning is correct, although I've yet to find out why the cache entries are written correctly, but the tag cache entries are not. Perhaps one of the caches is not able to process the `null` byte (`\u0000`)? 

Perhaps the bug description is wrong, but it's a bug in saving tags instead.

I'll try to further debug this later this week.

**Comment by rbaarsma** [comment]
I've found the issue.

*Using a cache chain with tags is not a good idea without using a cache_pool*

When I introduced a cache_pool for the tags, all was ok.

```
framework:
    cache:
        pools:
            my_taggable_cachepool:
                adapters:
                    - cache.adapter.array
                    - cache.adapter.apcu
                    - cache.adapter.redis
                tags: tag_pool
            tag_pool:
                adapters:
                  - cache.adapter.array
                  - cache.adapter.apcu
                  - cache.adapter.redis
```

Perhaps it's a good idea to either introduce an error message when trying to configure a cache pool with `tags: true` and multiple adapters, and/or add a warning to the docs.
