### ISSUE TITLE
Symfony Cache using redis adapter with password in provider dsn failing with non existing service

### ISSUE THREAD

**Issue by Bavragor** [symfony/symfony#35063]
**Symfony version(s) affected**: 4.4.1

**Description**  & **How to reproduce**  
When using a configuration like this:
```yaml
cache.redis.pool:
      adapters:
           - {name: cache.adapter.redis, provider: 'redis://password@localhost' }
```
I got this error:
![image](https://user-images.githubusercontent.com/7630518/71256356-c5abe280-2330-11ea-8f2e-f406d2cc5f42.png)

Seems to be a problem when using the @ in the provider dsn for redis.
Already tried to use @@, but not working.

Also updated symfony/cache to 4.4.2 to make sure that it is not an already fixed bug.

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by carsonbot** [comment]
Could I get an answer? If I do not hear anything I will assume this issue is resolved or abandoned. Please get back to me <3

**Comment by xabbuh** [comment]
This looks like a configuration issue to me. Something like this will work as expected:

```yaml
services:
    app_cache_redis_provider:
        class: 'Symfony\Component\Cache\Adapter\RedisAdapter'
        factory: ['Symfony\Component\Cache\Adapter\AbstractAdapter', 'createConnection']
        arguments:
            - 'redis://password@localhost'
            - lazy: true

framework:
    cache:
        pools:
            cache.redis.pool:
                adapter: cache.adapter.redis
                provider: 'app_cache_redis_provider'
```

Therefor I am closing here. If you think that this can somehow be clarified in the documentation, please do not hesitate to open an issue in the documentation repository.
