### ISSUE TITLE
Symfony 4.2 upgrade and migration to Guard

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#35102]
In https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md it says:

`SimpleAuthenticatorInterface`, `SimpleFormAuthenticatorInterface`, `SimplePreAuthenticatorInterface`,
   `SimpleAuthenticationProvider`, `SimpleAuthenticationHandler`, `SimpleFormAuthenticationListener` and
   `SimplePreAuthenticationListener` have been deprecated. Use Guard instead.

There is no information about the migration process:

- How to change security configuration?
- Will sessions be preserved or it will log users out like https://github.com/symfony/symfony/issues/33473?
- How to disable this deprecated interfaces and force using of Guard?

There seem to be lack of upgrade information here. All I can find is https://symfony.com/doc/4.2/security/form_login_setup.html and https://symfony.com/doc/current/security/guard_authentication.htm, but I feel that https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md can be imroved with some before and after code snippets.

**Comment by umpirsky** [comment]
I added:

```
# security.yaml
security:
    # ...

    firewalls:
        main:
            # ...
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
```

But I still get deprecation messages.

Am I missing something?
