### ISSUE TITLE
messenger:supervisor command

### ISSUE THREAD

**Issue by zorn-v** [symfony/symfony#35112]
Inspired by laravel horizon. 

Command that will run `messenger:consume` commands with parameters from config and watch that commands is running and start they if needed.
Maybe should use `symfony/lock` component for this.

**Comment by zorn-v** [comment]
Config may be like
```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        supervisor:
            queue-1: ~
            queue-2:
                receivers: [receiver-1, receiver-2]
                memory-limit: 128M
                time-limit: 3600
                sleep: 1
                bus: mybus

```
