### ISSUE TITLE
lint:twig does produce error when using custom twig functions/tests

### ISSUE THREAD

**Issue by MaxValEh** [symfony/symfony#35110]
I am using the command `php.exe bin/console lint:twig templates --env=prod` to check my templates

When using a custom test it produces the following error:
```
ERROR  in templates\something.html.twig (line 13)
...
  >>  13     {% if image_name is defined and image_name is valid_image_name %}
  >> Unknown "valid_image_name" test.
...
 [WARNING] 30 Twig files have valid syntax and 1 contain errors.
```

The test works when the template is rendered.
Using the same code as a custom twig function produces the same result.

Any possibility to allow `lint:twig` to recognize a custom twig test or to disable this specific error?

**Comment by xabbuh** [comment]
Did you maybe just register the test in the `dev` environment so that when linting in the `prod` environment it won't be found?

**Comment by MaxValEh** [comment]
thank you for your help @xabbuh i did not test that

It is correct that the error is not present with `--env=dev` and `--env=test` but i did not specifically register the service besides the standard src folder autowire
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
```
Test:
```php
<?php

namespace App\Twig;

use Twig\Extension\AbstractExtension;
use Twig\TwigTest;

class ImageFileNameExtensionsTest extends AbstractExtension
{
    private $imageFileExtensions;

    public function __construct(array $imageFileExtensions = ['jpg', 'png', 'jpeg'])
    {
        $this->imageFileExtensions = $imageFileExtensions;
    }
    public function getTests()
    {
        return [
            new TwigTest('valid_image_name', [$this, 'checkImageFileExtensions']),
        ];
    }
    public function checkImageFileExtensions(?string $imageName): bool { ... }
}
```
