### ISSUE TITLE
Define which controller to execute when linking using the path twig function

### ISSUE THREAD

**Issue by Mdz-dev** [symfony/symfony#35145]
**Description**  

It would be awesome to be able to define which controller to execute when linking in twig.

There are some a problems with the routing priority (first defined route wins) as discussed in this issue #18415.

I believe that this features will solve those problems, check out this example :

**Example**  

```
bar:
    path: "/foo/{slug}"
    defaults:
        _controller: AppBundle:Default:bar
```

```
baz:
    path: "/foo/{slug}"
    defaults:
        _controller: AppBundle:Default:baz
```

These two route are identical and the the first route `bar` is going to match first.

By when linking to either of these two routes we can use something like

`{{path('baz', {'_controller': 'AppBundle:Default:baz', 'slug': 'foo'})}}`
