### ISSUE TITLE
Event-subscriber runs after [Security] firewall

### ISSUE THREAD

**Issue by milikamel** [symfony/symfony#35320]
**Symfony version(s) affected**: 4.2
**Description**  
The main idea is I have preflight requests I made an event subscriber to check if method = OPTIONS  send 200 to access certain API but seems to be wrong when I log the subscriber is never executed for AuthGaurd protected routes.  

**How to reproduce**  
I've created a `CORSSubscriber`
```
class CORSSubscriber implements EventSubscriberInterface {
        public function onKernelRequest(GetResponseEvent $event)
    {    
            if($event->getRequest()== 'OPTIONS'){
            $this->logger->info('stop');
            $response = new Response();
            $event->setResponse($response);
       };
}
```
and auth implementation of the `AbstractGuardAuthenticator` from https://symfony.com/doc/current/security/guard_authentication.html 
```
class TokenAuthenticator extends AbstractGuardAuthenticator
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    public function supports(Request $request)
    {
        return $request->headers->has('X-AUTH-TOKEN');
    }
..
...
}
``` 
and finally implemented the config this way 
```
    firewalls:
        api:
            pattern: ^/api/reports
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            stateless: true
```

**Additional context**
log:  
```
[2020-01-13 11:23:30] request.INFO: Matched route "reports". {"route":"reports","route_parameters":{"_route":"reports","_controller":"App\\Controller\\ReportsApi\\ReportController::getReports"},"request_uri":"http://localhost:8000/api/reports","method":"OPTIONS"} []
// should display stop in logger but goes straight to the firewall
[2020-01-13 11:23:30] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
```
