### ISSUE TITLE
[DependencyInjection] Support multiple tags for ServiceLocator

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#35326]
It would be interesting to have the option of tagging multiple time a service added to a locator indexed by some key.

```
my_service:
  tags:
    - { name: tag, alias: 'key-1' }
    - { name: tag, alias: 'key-2' }

my_consumer:
  arguments: [!tagged_locator { tag: 'tag', index_by: 'key' }]
```

And one could get both `key-1` and `key-2` referring to the same service.
