### ISSUE TITLE
[DependencyInjection] Parameters are not expanded in indexed !tagged_locator

### ISSUE THREAD

**Issue by rpkamp** [symfony/symfony#35337]
**Description**  
When using a `!tagged_locator` with an `index_by` value, we can not use parameters inside those `index_by` values.

**Example** 
**parameters.yaml**
```yaml
parameters:
    foo: bar
```

**services.yaml**
```yaml
services:
    service1:
        class: Foo\Bar
        tags:
            - { name: 'foo', key: '%foo%' }

    service2:
        class: Foo\BarLocator
        arguments:
            - !tagged_locator { tag: 'foo', index_by: 'key' }
```

**Expected behaviour**
I expect to be able to call the tagged_locator with the `bar` service (because `%foo%` is `bar`)

**Actual behaviour**
The service locator throws an exception that the service `bar` does not exist, only the service `%foo%` exists.
