### ISSUE TITLE
Access Control List is ignored if no firewall is being matched

### ISSUE THREAD

**Issue by njutn95** [symfony/symfony#35330]
**Symfony version(s) affected**: 5.0.2

**Description**  
Not sure if this is a bug or documentation issue (because in documentation it's stated otherwise). As I said in the title of the issue, if there's no firewall that's matching a request, access control list is being ignored. In most cases, that should be the case, but a relatively common scenario is when you want to restrict the access to whole application if a user is not logged in, and only provide him access to the login form. If a firewall is configured to not allow anonymous users to `^/` and an access control list is configured to `{ path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }` (just like it's stated in the [documentation](https://symfony.com/doc/current/security/form_login_setup.html#generating-the-login-form)), one would expect that an anonymous user would be able to access the `/login` page, while instead only logged in users would be able to access it and anonymous users will fall into a redirection loop.

**How to reproduce**  
Using the following configuration will cause a redirection loop to `/login`. Guard Authenticator is unmodified version from the `make:auth` command

 `security.yaml`
```
security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: false
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

The following `security.yaml` does work though:
```
security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
```

**Possible Solution**  
Reason for this happening is probably because no firewall is being matched for this request (because of `anonymous: false`), so ACL gets ignored. While it does make sense to not proceed if there's no firewall matched, and if it's done by intention, then a [documentation](https://symfony.com/doc/current/security/form_login_setup.html#generating-the-login-form) needs to be updated because there is no mention of when ACL is being read and it says the following: 

_Edit the `security.yaml` file in order to allow access for anyone to the `/login` route:_

```
# config/packages/security.yaml
security:
    # ...

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # ...
```

**Additional context**
