### ISSUE TITLE
[PropertyAccessor::createCache] Deprecation warning on Symfony 4.4

### ISSUE THREAD

**Issue by gnutix** [symfony/symfony#35346]
**Symfony version(s) affected**: 4.4.x

**Description**  
After deploying my newly upgraded application, I get the following deprecation warning from our logging system : 

> User Deprecated: Passing null as "$defaultLifetime" 2nd argument of the "Symfony\Component\PropertyAccess\PropertyAccessor::createCache()" method is deprecated since Symfony 4.4, pass 0 instead.

Here's the stacktrace : 

```
var/cache/prod/ContainerPDtkYiq/srcApp_KernelProdContainer.php:887,
var/cache/prod/ContainerPDtkYiq/srcApp_KernelProdContainer.php:1067,
var/cache/prod/ContainerPDtkYiq/srcApp_KernelProdContainer.php:700,
var/cache/prod/ContainerPDtkYiq/getLoginAuthenticatorService.php:15,
var/cache/prod/ContainerPDtkYiq/srcApp_KernelProdContainer.php:409,
var/cache/prod/ContainerPDtkYiq/getSecurity_Firewall_Map_Context_MainService.php:38,
var/cache/prod/ContainerPDtkYiq/srcApp_KernelProdContainer.php:409,
vendor/symfony/dependency-injection/Container.php:433,
vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40,
vendor/symfony/security-bundle/Security/FirewallMap.php:83,
vendor/symfony/security-bundle/Security/FirewallMap.php:54,
vendor/symfony/security-bundle/EventListener/FirewallListener.php:50,
vendor/symfony/event-dispatcher/EventDispatcher.php:304,
vendor/symfony/event-dispatcher/EventDispatcher.php:264,
vendor/symfony/event-dispatcher/EventDispatcher.php:239,
vendor/symfony/event-dispatcher/EventDispatcher.php:73,
vendor/symfony/http-kernel/HttpKernel.php:127,
vendor/symfony/http-kernel/HttpKernel.php:68,
vendor/symfony/http-kernel/Kernel.php:198,
public/index.php:33
```

I couldn't find any occurrence of "createCache" in our code. The only part in the stacktrace that is part of the project's code is `var/cache/prod/ContainerPDtkYiq/getLoginAuthenticatorService.php:15,`, which is a class extending `\Symfony\Component\Security\Guard\AbstractGuardAuthenticator` (using the serializer, a messenger's command bus and a Doctrine repository).

Unfortunately, I don't have access to `var/cache/prod/ContainerPDtkYiq` (it was replaced by a new one).

Any idea where this one might come from ? Will it break if I upgrade to 5.0 without tracking it down ?

**Comment by xabbuh** [comment]
Would you be able to provide a small example application that allows to reproduce it? Maybe just extracting your security config and your authenticator is enough to do that.

**Comment by gnutix** [comment]
I'll wait for our 4.4 version of the app to be deployed to more clients and try to report more accurate stacktraces. Can't really take time right now to try and extract a reproducible sample.

**Comment by xabbuh** [comment]
Could you in the meanwhile share your security config?

**Comment by gnutix** [comment]
Here's an anonymized version.

```yaml
# config/packages/security.yaml
security:
    providers:
        users:
            id: 'App\...\UserRepository'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: users
            switch_user: true
            guard:
                authenticators:
                    - App\...\LoginAuthenticator
                    - App\...\SomeOtherLoginAuthenticator
                entry_point: App\...\LoginAuthenticator
            logout:
                path: app_logout
                success_handler: App\...\LogoutSuccessHandler

    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false
```
