### ISSUE TITLE
[Messenger] Close Doctrine Connexion

### ISSUE THREAD

**Issue by xfifix** [symfony/symfony#35352]
**Symfony version(s) affected**: 4.4.2
**Description**  
When i dispatch Message in the event bus, 5 times out of 10 event in BDD failed with the message Doctrine connection close .... 

i have this error in my consumer : 
```
8 ERROR     [messenger] Error thrown while handling message App\Domain\Pricing\Event\Message\WasUpsertedFrenchSellingPriceEvent. Sending for retry #1 using 1000 ms delay. Error: "Resetting a non-lazy manager service is not supported. Try running "composer require symfony/proxy-manager-bridge"."
```

In my messenger.yaml:
```yaml

framework:
    messenger:
        # The bus that is going to be injected when injecting MessageBusInterface
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - validation
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            messenger.bus.queries:
                middleware:
                    - validation
            messenger.bus.events:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            messenger.bus.mailer:
        failure_transport: failed
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                    # override all of this with a service that
                    # implements Symfony\Component\Messenger\Retry\RetryStrategyInterface
                    # service: null
            async-event:
                dsn: 'event-transport://'
            import-pricing-selling:
                dsn: 'import-pricing-transport://'
                options:
                    type: selling
            import-pricing-discount:
                dsn: 'import-pricing-transport://'
                options:
                    type: discount
            import-pricing-sale:
                dsn: 'import-pricing-transport://'
                options:
                    type: sale
            countryRate:
                dsn: 'update-product-pricing-countryRate-transport://'
                options:
                    queue_name: pricing
            failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Domain\Pricing\Event\Message\WasUpdatedPricingCountryRateEvent': countryRate
            'App\Application\Pricing\Command\Message\UpdateProductPricingByCountryCommand': async
            'App\Domain\Pricing\Event\Message\WasReceivedImportSellingFileEvent': import-pricing-selling
            'App\Domain\Pricing\Event\Message\WasReceivedImportDiscountFileEvent': import-pricing-discount
            'App\Domain\Pricing\Event\Message\WasReceivedImportSaleFileEvent': import-pricing-sale
            'App\Domain\Pricing\Event\Message\WasDeletedFrenchDiscountPriceEvent': async
            'App\Domain\Pricing\Event\Message\WasDeletedFrenchProductVariationPricingEvent': async
            'App\Domain\Pricing\Event\Message\WasDeletedFrenchSalePriceEvent': async
            'App\Domain\Pricing\Event\Message\WasUpsertedFrenchRecommendedRetailPriceEvent': async
            'App\Domain\Pricing\Event\Message\WasUpsertedFrenchSellingPriceEvent': async
            'App\Domain\Pricing\Event\Message\WasUpdatedInternationalRecommendedRetailPriceEvent': async
            'App\Domain\Pricing\Event\Message\WasUpdatedInternationalSellingPriceEvent': async
            'App\Domain\Pricing\Event\Message\WasUpsertedFrenchDiscountPriceEvent': async
            'App\Domain\Pricing\Event\Message\WasUpsertedFrenchProductVariationPricingEvent': async
            'App\Domain\Pricing\Event\Message\WasUpsertedFrenchSalePriceEvent': async
            'App\Domain\SearchEngine\Event\Message\WasUpsertedIndexedProductEvent': async

```
