### ISSUE TITLE
If a db error occurs the entity manager is closed for all future messages

### ISSUE THREAD

**Issue by elzozo13** [symfony/symfony#35360]
**Symfony version(s) affected**: x.y.z

**Description**  
This is kind of related with https://github.com/symfony/symfony/issues/29662. The entity manager is correctly cleared if everything goes fine. But for example if something goes wrong from mysql (like for example a constraint fails, or a duplicate key appears, etc.), the entity will remain closed.

This in turn results in failure of all messages that come after this one.

**How to reproduce**  
This of course is not a real life case, but is the simplest way to reproduce the issue.

```
public function __invoke(SomeMessage $message) {
        $a = $this->em->getRepository(SomeEntity::class)->find(1);
        $this->em->clear();
        $this->em->persist($a);
        $this->em->flush();
}
```

Results in:

> "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '21187557' for key 'PRIMARY'  ""","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
> 14:34:42 ERROR     [messenger] Error thrown while handling message App\Message\OrderPort. Sending for retry #1 using 1000 ms delay. Error: "The EntityManager is closed." ["message" => App\Message\OrderPort^ { …},"class" => "App\Message\OrderPort","retryCount" => 1,"delay" => 1000,"error" => "The EntityManager is closed.","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
> 14:34:42 ERROR     [messenger] Error thrown while handling message App\Message\OrderPort. Sending for retry #1 using 1000 ms delay. Error: "The EntityManager is closed." ["message" => App\Message\OrderPort^ { …},"class" => "App\Message\OrderPort","retryCount" => 1,"delay" => 1000,"error" => "The EntityManager is closed.","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
> 14:34:42 ERROR     [messenger] Error thrown while handling message App\Message\OrderPort. Sending for retry #1 using 1000 ms delay. Error: "The EntityManager is closed." ["message" => App\Message\OrderPort^ { …},"class" => "App\Message\OrderPort","retryCount" => 1,"delay" => 1000,"error" => "The EntityManager is closed.","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
> 14:34:42 ERROR     [messenger] Error thrown while handling message App\Message\OrderPort. Sending for retry #1 using 1000 ms delay. Error: "The EntityManager is closed." ["message" => App\Message\OrderPort^ { …},"class" => "App\Message\OrderPort","retryCount" => 1,"delay" => 1000,"error" => "The EntityManager is closed.","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]

**Possible Solution**  
My current solution to the problem is to wrap everything in a try catch block and kill the consumer like this (I could regenerate the manager or something like that but... I am restarting the consumer every couple of thousands of messages anyway so that was good enough for me at this point):

```
public function __invoke(SomeMessage $message) {
       try {
            $a = $this->em->getRepository(SomeEntity::class)->find(1);
            $this->em->clear();
            $this->em->persist($a);
            $this->em->flush();
       }
       catch (ORMException $exception) {
            // No codes no nothing... no comment
            if ($exception->getMessage() === 'The EntityManager is closed.') {
                dd('Closed because entity manager needed to be reset');
            }
            throw $exception;
       }
}
```

The problem with this is that I keep dragging that try catch block around for no other reason than catching that error (that is not specified as thrown either so the ide screams at me that is not thrown even though it is :) ).

I could ofc add an abstraction layer for that but I consider is the middleware business to deal with this (correct me if I'm wrong), when is clearing the entity as defined here https://github.com/symfony/symfony/issues/29662.

**Additional context**  
I am using a rabbit + messenger environment.

**Comment by Nyholm** [comment]
I really dislike this "The EntityManager is closed" exception. I get it time to time in my applications too. And now and then I search the internet for a good solution but I keep coming back to a Github thread where the final conclusion is: 

> Make sure you write your code so it checks for duplicate entries before you insert.

Writing code like in your example is just putting duct tape to the problem Im afraid. 😕

**Comment by elzozo13** [comment]
@Nyholm I'm sorry but with all the respect I guess you really didn't understand the post. I never suggested writing code like that, that was exactly my problem. I don't want to write code like that. It is indeed duct tape and being forced to write it hurts my soul (hence the post here) and I did mentioned that in the post:

> (The problem with this is that I keep dragging that try catch block around for no other reason than catching that error).


This 

> Make sure you write your code so it checks for duplicate entries before you insert.

is NOT a solution. I just described the SIMPLEST way to reproduce the issue. There are hundreds of possible ways to stumble into this issue. Basically any exception that comes after the orm will generate that. Some string length become too big after re-encoding? All future  messages fail. Db server gone away for a second? All future messages fail. Any constraint fail? All future messages fail. And the list may go on. There are hundreds of possible scenarios and without dragging horrible code like the one above or extending the messenger is impossible to treat all of them.

Maybe I'm seeing it the wrong way (and pls. correct me if that is true), but the whole point of messanger is to "enable" the responsibility segregation pattern (and I love the implementation overall, I love how easy it is to be used and made async, having different transports, etc.). **But having 1 message affecting others is surely not the way it was intended to work** (and yes, I see why it affects and I can guess why it was implemented like that, but that doesn't matter).

I did find multiple ways to solve the problem without affecting messenger code but none of them was satisfying (yes, they work but is ugly, unmaintainable long term and I'm trying to get rid of that code).

The linked issue (https://github.com/symfony/symfony/issues/29662) treats a similar problem (the fact that em is shared between messages was resulting in a memory leak; I'm guessing someone noticed the memory leak there and fixed it like that). I like the implementation (it helped us to get rid of an $em->clear() at the end of each of our handlers; ty for that) and I consider that is the place the failure should be treated also.

If you don't think the problem should be treated in a similar way with the linked one I'm all for another solution, and if you can explain why it shouldn't be treated there I would love to try help another one but please, I'm sure you know there is a bigger problem than "check for duplicates" here. Pls. reopen and lets find a real solution.

**Comment by Tobion** [comment]
There are three solutions:
1. try to prevent the error from happening which is hard
2. in case the entity manager is closed, create a new one and continue the worker
3. stop the worker so a new worker process has a new entity manager

The easiest solution is 3) and could also be useful in other cases. But that is a duplicate of #34414

**Comment by elzozo13** [comment]
Epic, https://github.com/symfony/symfony/issues/34414 would work perfect for me, and I see it already has a pull request. Tyvm guys, really appreciate it.

**Comment by remif25** [comment]
Hello,,

I got the same problem and I found out this middleware which solve the problem for me : 
```yml
framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    # each time a message is handled, the Doctrine connection
                    # is "pinged" and reconnected if it's closed. Useful
                    # if your workers run for a long time and the database
                    # connection is sometimes lost
                    - doctrine_ping_connection
```

More information on the official documentation : https://symfony.com/doc/current/messenger.html#middleware-for-doctrine

**Comment by Warxcell** [comment]
> Hello,,
> 
> I got the same problem and I found out this middleware which solve the problem for me :
> 
> ```yaml
> framework:
>     messenger:
>         buses:
>             command_bus:
>                 middleware:
>                     # each time a message is handled, the Doctrine connection
>                     # is "pinged" and reconnected if it's closed. Useful
>                     # if your workers run for a long time and the database
>                     # connection is sometimes lost
>                     - doctrine_ping_connection
> ```
> 
> More information on the official documentation : https://symfony.com/doc/current/messenger.html#middleware-for-doctrine

This will prevent the issue, but not solving it.
Basically what's happening on your side is: worker is keeping connection open without sending anything for a long time, then when it receives new message, its doing query, but connection is already closed by SQL server and you get that error.

This middleware basically sends dummy requests to SQL server just to keep the connection alive, but it won't save you to recover from other SQL exceptions like `Duplicate entry exception` or `Column cannot be null`.

**Comment by maximehuran** [comment]
I injected `ManagerRegistry $managerRegistry;` then work like this in my message handler : 

```php
        try {
            $this->entityManager->beginTransaction();
            $this->entityManager->persist($object);
            $this->entityManager->flush();
            $this->entityManager->commit();
        } catch (\Exception $exception) {
            $this->logger->error('import_error', ['object_code' => $object->getCode(), 'exception' => (string) $exception]);
            $this->entityManager->rollback();
            $this->managerRegistry->resetManager();
            throw $exception;
        }
```

This allows my workers to continue to use the entity manager correctly.
My messages in error are moved on the Symfony messenger failed transport according to my configuration : 

```yaml
framework:
    messenger:
        transports:
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: 'failed'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: failed
                retry_strategy:
                    max_retries: 3
                    delay: 1000 # milliseconds delay
                    multiplier: 2 # causes the delay to be higher before each retry, e.g. 1 second delay, 2 seconds, 4 seconds
                options:
                    queue_name: 'async'
        buses:
            async.bus:
                middleware:
                    - 'doctrine_ping_connection'
```

The class which use the bus autowire it using `MessageBusInterface $asyncBus`
