### ISSUE TITLE
Symfony Messenger memory leak while dispatching issue

### ISSUE THREAD

**Issue by ludofleury** [symfony/symfony#35426]
**Symfony version(s) affected**: 4.4

**Description**  
Memory leak while dispatching event at https://github.com/symfony/symfony/blob/9f93a38fffd2d57595b2732a3eadeb12d0af0892/src/Symfony/Component/Messenger/Middleware/SendMessageMiddleware.php#L68

**How to reproduce**  
Dispatch a lot of message in the event bus, this logging line affect the memory. (despite env prod etc...)

**Possible Solution**  
unsure ?

**Comment by dmaicher** [comment]
How is your logger (Monolog?) configured for the `prod` environment? Is it buffering all logs somehow?

**Comment by Nyholm** [comment]
This is a classic case of monolog leak =)

You probably have the fingers_crossed handler or maybe buffer handler, right?
That basically means that you store all logs in memory and when an exception happens, we write everything to the logger. 

If something interesting (error) never happens then monolog is just collecting logs forever and you have a memory leak. 

You need to make sure to set a `buffer_size`. 

```yaml
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            buffer_size:  30
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
```
