### ISSUE TITLE
[security] There is no user provider for user

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/symfony#35435]
**Symfony version(s) affected**: 4.4.3

**Description**  
After update to 4.4.3 i have a RuntimeException "There is no user provider for user"

**How to reproduce**  
if you have custom provider update to 4.4.3

Sample
```yml
security:
    providers:
        custom-security:
            id: custom.user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            security: false
        secured_area:
            pattern: ^/
            guard:
                authenticators:
                    - custom.authentificator
                entry_point: custom.authentificator
            logout:
                path: /logout
```

**Possible Solution**  
Problem is on the file  Symfony/Component/Security/Http/Firewall/ContextListener.php method refreshUser
