### ISSUE TITLE
Error handling is different from previous versions in 4.4 and 5.0.

### ISSUE THREAD

**Issue by siganushka** [symfony/symfony#35445]
**Symfony version(s) affected**: 4.4 & 5.0

**Description**  
Error handling behaves differently from previous versions in 4.4 and 5.0.

**How to reproduce** 

in my services.yaml (using default):

```yaml
// ./config/services.yaml

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

```

in my controller:

```php
// ./src/Controller/DefaultController.php

class DefaultController extends AbstractController
{
    /**
     * @Route("/default", name="default")
     */
    public function index()
    {
        $var = 'syntax error with no semicolon' // syntax error
    }
}
```
When a syntax error occurs, error messages are displayed in versions 4.3 and earlier, including the number of lines where the error occurred:

![image](https://user-images.githubusercontent.com/45844370/72956212-d2ad6d00-3dd9-11ea-9a56-8330892d7d39.png)

But in 4.4 and 5.0, when a syntax error occurs, it shows that the class cannot be found:

![image](https://user-images.githubusercontent.com/45844370/72956312-36d03100-3dda-11ea-9c8d-cf4682b39ef0.png)

I'm not sure if the problem is from `dependency-injection` or `error-handler`.
