### ISSUE TITLE
[Doctrine bridge] Break BC in DoctrineType form type on minor update

### ISSUE THREAD

**Issue by peter-gribanov** [symfony/symfony#35493]
**Symfony version(s) affected**: 3.4.36 -> 3.4.37

**Description**  

On minor update `3.4.36` to `3.4.37` i get error:

```
Cannot autowire service "App\Form\Type\SetOfWeekType": argument "$registry" of method "Symfony\Bridge\Doctrine\Form\Type\DoctrineType::__construct()" has no type-hint, you should configure its value explicitly.
```

```php
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class SetOfWeekType extends EntityType
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        parent::configureOptions($resolver);
        $resolver->setDefaults([
            'class' => SetOfWeek::class,
            'choice_label' => 'name',
        ]);
    }
}
```

```yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Form\Type\SetOfWeekType: ~
```

Perhaps this is a duplicate, but i could not find a similar issues.
