### ISSUE TITLE
Error to use Protocol AMQP

### ISSUE THREAD

**Issue by bambalimahim** [symfony/symfony#35504]
Symfony : 7.2

```
When i dispatch a message in the handler i have this error:
Could not connect to the AMQP server. Please verify the provided DSN. ({\"host\":\"localhost\",\"port\":5672,\"vhost\":\"\\/\",\"login\":\"guest\",\"password\":\"********\"}
```

```yaml
messenger.yml
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            amqp: "%env(MESSENGER_TRANSPORT_DSN)%"
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Services\Transactions\TransactionMessage': amqp
```

.env
```bash
###> symfony/messenger ###
# Choose one of the transports below
MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/transaction
#MESSENGER_TRANSPORT_DSN=doctrine://default
#MESSENGER_TRANSPORT_DSN=redis://localhost:6379/messages
###< symfony/messenger ###
```
