### ISSUE TITLE
[Dependency Injection] Possible issue on "_instanceof" feature

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#35581]
**Symfony version(s) affected**: 4.4.4

**Description**  
A small use case of composition can cause a infinite loop inside the service container.

**How to reproduce**  
Lets say I have an abstraction called `FooInterface` and I want to tag all its implementation with `app.foo`. So what I need to do is declare the interface and its implementation and add the section `_instanceof` in my `services.yaml` file. Now I want to add a new implementation of this interface that holds all others implementations and use this implementation in my application.

```php
class FooComposite implements FooInterface {
    private $foos;
    public function __construct(iterable $foos) { $this->foos = $foos; }
}
```

The problem comes after this, because the container will include the `FooComposite` in the list of `$foos` and this will cause an infinite loop when the application tries to get `FooComposite` from the container. I know that Symfony cant guess (and shouldn't) what implementation should be out of the list, but I've tried to manually clear the tags of `CompositeFoo` to avoid the infinite loop but didn't work. Follow a simple version of the `services.yaml` file describing the situation:

```yaml
services:
    _instanceof:
        FooInterface:
            tags: [{name: "app.foo"}]
    
    FooComposite:
        arguments: [!tagged app.foo]
        tags: []

    FooInterface: '@FooComposite'
```

I've created a gist to add some more info: https://gist.github.com/tsantos84/772fa2fcd3765fc6d77cccb2db2a5f2a

**Possible Solution**  
Maybe adding an exclude option to `_instanceof` could solve the problem:

```yaml
services:
    _instanceof:
        FooInterface:
            tags: [{name: "app.foo"}]
            exclude: 
                - FooComposite
                - '../src/ExcludedPath/*'
```
