### ISSUE TITLE
lint:container throws InvalidParameterTypeException when using memcached pool

### ISSUE THREAD

**Issue by qconer** [symfony/symfony#35599]
**Symfony version(s) affected**: 5.0.4

**Description**  
InvalidParameterTypeException while running lint:container command with memcached pool config

**How to reproduce**  
1. create new project
`composer create-project symfony/website-skeleton my_project_name`
2. modify your config/packages/cache.yaml:
```
framework:
    cache:
        pools:
            my.dedicated.cache:
                adapter: cache.adapter.memcached
```
3. run 
`php bin/console lint:container`

```
In CheckTypeDeclarationsPass.php line 263:

Invalid definition for service "my.dedicated.cache": argument 1 of "Symfony\Component\Cache\Adapter\MemcachedAdapter::__construct" accepts "Memcached", "Symfony\Component\Cache\Adapter\AbstractAdapter" passed.
```

**Possible Solution**  
-

**Additional context**  
-

**Comment by fancyweb** [comment]
Status: reviewed

This bug is related to factory usage. The 1st argument is using a factory but the definition class is not correctly set to the object class the factory will return. When a definition uses a factory, I guess we cannot know what it will return without actually executing it, so we can only ignore validating such cases isn'it? ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
If we cannot know, we need to skip yes.

**Comment by Aerendir** [comment]
Same problem here...

I have a class `MyClass`:tThis class is like a small container.

I need to configure it in four different ways, so I created a factory class for each one.

I configured them this way:

```yaml
services:
    _defaults:
        autoconfigure: true
        autowire: true
    # This is a non-static factory: first create a service for the factory itself
    # https://symfony.com/doc/current/service_container/factories.html#non-static-factories
    'App\My\Namespace\MyClassFactory1': ~
    # This is bind in services.yaml
    my.class.1:
        class: 'App\My\Namespace\MyClassFactory1'
        factory: ['@App\My\Namespace\MyClassFactory1', 'create']

    'App\My\Namespace\MyClassFactory2': ~
    # This is bind in services.yaml
    my.class.2:
        class: 'App\My\Namespace\MyClassFactory2'
        factory: [ '@App\My\Namespace\MyClassFactory2', 'create' ]

    'App\My\Namespace\MyClassFactory3': ~
    # This is bind in services.yaml
    my.class.3:
        class: 'App\My\Namespace\MyClassFactory3'
        factory: ['@App\My\Namespace\MyClassFactory3', 'create']
```

This configuration causes this error when linting the container:

```console
[ERROR] Invalid definition for service ".messenger.handler_descriptor.Xsa96aJ": argument 5 of                          
         "App\My\Namespace\AClassThatUsesTheClassGeneratedByTheFactory::__construct(
         )" accepts "App\My\Namespace\MyClassInterface",                                                              
         "App\My\Namespace\MyClassFactory1" passed.    
```
