### ISSUE TITLE
[Lock] Blocking locks error

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#35607]
**Symfony version(s) affected**: v4.2.12

**Description**  

Lock factory is defined like this:

```yaml
services:
    lock.factory:
        public: true
        class: Symfony\Component\Lock\Factory
        arguments:
            - !service
                class: Symfony\Component\Lock\Store\RetryTillSaveStore
                arguments:
                    - !service
                        class: Symfony\Component\Lock\Store\RedisStore
                        arguments:
                            - "@redis"
                            - 2
                    - 100
                    - 50
```

According to [docs](https://symfony.com/doc/4.2/components/lock.html#blocking-locks):

> To wait (indefinitely) until the lock can be created, pass true as the argument of the acquire() method. 

Code:

```php
$this->get('lock.factory')->createLock('lock-to-block', 3, false)->acquire(true);
$this->get('lock.factory')->createLock('lock-to-block', 3, false)->acquire(true);
```
fails with:

```
In Lock.php line 106:
                                                                  
  [Symfony\Component\Lock\Exception\LockAcquiringException]       
  Failed to acquire the "lock-to-block" lock.  
                                                                  

Exception trace:
 () at vendor/symfony/symfony/src/Symfony/Component/Lock/Lock.php:106
 Symfony\Component\Lock\Lock->acquire() at MyCommand.php:31
 MyCommand->execute() at vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:935
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:269
 Symfony\Component\Console\Application->doRun() at vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:145
 Symfony\Component\Console\Application->run() at app/console:30

In ExpiringStoreTrait.php line 27:
                                                                
  [Symfony\Component\Lock\Exception\LockExpiredException]       
  Failed to store the "lock-to-block" lock.  
                                                                

Exception trace:
 () at vendor/symfony/symfony/src/Symfony/Component/Lock/Store/ExpiringStoreTrait.php:27
 Symfony\Component\Lock\Store\RedisStore->checkNotExpired() at vendor/symfony/symfony/src/Symfony/Component/Lock/Store/RedisStore.php:71
 Symfony\Component\Lock\Store\RedisStore->save() at vendor/symfony/symfony/src/Symfony/Component/Lock/Store/RetryTillSaveStore.php:66
 Symfony\Component\Lock\Store\RetryTillSaveStore->waitAndSave() at vendor/symfony/symfony/src/Symfony/Component/Lock/Lock.php:73
 Symfony\Component\Lock\Lock->acquire() at MyCommand.php:31
 MyCommand->execute() at vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:935
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:269
 Symfony\Component\Console\Application->doRun() at vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:145
 Symfony\Component\Console\Application->run() at app/console:30
```

Shouldn't it wait instead of erroring?

**Additional context**  
This locks can be created from two different PHP processes in the real world scenario.
