### ISSUE TITLE
read error on connection (redis)

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#35603]
**Symfony version(s) affected**: 4.4.4

**Description**  
Since the update from 4.4.3 to 4.4.4 i get an error when i flush the redis database with the command line `./bin/console redis:flushall`

**How to reproduce**  
These are the redis bundles i'm using: snc/redis-bundle and predis/predis
Config settings:

```yaml
# config/packages/cache.yaml
framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        system: cache.adapter.redis
```

```yaml
# config/packages/snc_redis.yaml
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: '%env(REDIS_DOCTRINE_URL)%'
            logging: '%kernel.debug%'
            options:
                connection_timeout: 0
                read_write_timeout: 0
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%env(REDIS_DOCTRINE_URL)%'
            logging: '%kernel.debug%'
            options:
                connection_timeout: 0
                read_write_timeout: 0
```

**Additional context**  
When i look on this error most posts say it's a timeout issue but i already changed the php ini default_socket_timeout to -1 but this didn't helped and i've set the connection timeout in snc_redis to 0 but didn't helped either
