### ISSUE TITLE
Allow for route and/or controller deprecation

### ISSUE THREAD

**Issue by bigfoot90** [symfony/symfony#35627]
**Description**  

I'm updating my API and I would like to mark a route and/or controller or action as deprecated,
this should then **add a header in the response** to inform clients that they should update as soon as possible.

**Example**  

**routing.yaml**
```yml
deprecated_route:
    path: /old/path
    controller: App/Controller/DeprecatedController::old_method
    deprecated: Use /new/path instead
```
or by controller or single action only
```php
/**
 * @deprecated Use /new/path instead
 */
class DeprecatedController
{
    /**
     * @deprecated Use /new/path/action instead
     */
    public function old_method()
    {
        ...
    }
}
```
What do you think?
