### ISSUE TITLE
[Security] Allow usage of custom per-user in memory provider for the salt

### ISSUE THREAD

**Issue by jmjjg** [symfony/symfony#35621]
**Description**  

I stumbled upon [this stack overflow question](https://stackoverflow.com/questions/23848168/using-sha512-encoder-with-symfony2-in-memory-security-provider), trying to use a (per-user) salt in the memory provider.

Maybe I'm missing something ?

**Example**  
In `config/packages/security.yaml`

```yml
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:            pbkdf2
            # Name of hashing algorithm for PBKDF2 (i.e. sha256, sha512, etc..) See hash_algos() for a list of supported algorithms.
            hash_algorithm:       sha512
            key_length:           40
    providers:
        my_memory_provider:
            memory:
                users:
                    foo:
                        password: i7AoApTpfwq1NotxAQKqnUBUlRnL009S5Z3AKzIkaN5yVPUnEXNM6Q==
                        roles: ROLE_USER
                        # I'd like to add the line below
                        salt: jH0clmD0AaOdGnjjVOb88TV9i2UeD36y+gCXEz+6
```

**Comment by linaori** [comment]
If you'd use a `password_hash()` function, you wouldn't need a salt value afaik.

**Comment by HeahDude** [comment]
This is not a solution to this issue. When defining an encoding mode as above, running `bin/console security:encode-password` generates a salt which is not usable with a memory provider.

**Comment by linaori** [comment]
@HeahDude hthis works just fine when you use a different encoder. As example, I took bcrypt:

```yml
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
```

And the result of the command:
```
$ bin/console security:encode-password

Symfony Password Encoder Utility
================================


 For which user class would you like to encode a password? [...]:
  [0] [...]
  [1] Symfony\Component\Security\Core\User\User
 > 1

 Type in your password to be encoded:
 > 

 ------------------ --------------------------------------------------------------- 
  Key                Value                                                          
 ------------------ --------------------------------------------------------------- 
  Encoder used       Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder  
  Encoded password   $2y$13$68sD31HhsuW.42BMdNOWQ.q5EgGV/ByXtbk4FiGQzy6ncAnMUfQmO   
 ------------------ --------------------------------------------------------------- 

 ! [NOTE] Self-salting encoder used: the encoder generated its own built-in salt.                                       

                                                                                                                        
 [OK] Password encoding succeeded                                                                                       
                                                                                                                        
```

I don't think support for the other versions needs to be added, this would complicate the in-memory user even more while there are better hashing algorithms available.
