### ISSUE TITLE
Different redis DB in CLI and Web at specified configuration

### ISSUE THREAD

**Issue by wkwkgit** [symfony/symfony#35631]
**Symfony version(s) affected**: 4.4.4

**Description**  

**How to reproduce**  

You should configure redis for different services like this. In this case - CLI will use the db0 in app.cache.provider.redis and the web will use db2 for app.cache.provider.redis. 

```yaml
app.cache.provider.redis:
        class: \Redis
        public: true
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - 'redis://%env(REDIS_IP)%/'
            - { retry_interval: 2, tcp_keepalive: 5, timeout: 10, persistent : 1 }

app.session.provider.redis:
        class: \Redis
        public: true
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - 'redis://%env(REDIS_IP)%/2'
            - { retry_interval: 2, tcp_keepalive: 5, timeout: 10, persistent : 1, compression: false}
```

**Possible Solution**  
You should strictly set both databases IDs in config. It will fix this problem. But its look like variable at configuration overwrites, so i think its a bug.
