### ISSUE TITLE
Bug Sessions (double file)

### ISSUE THREAD

**Issue by wolpheus** [symfony/symfony#35634]
**Symfony version(s) affected**: 5.0.4
Php 7.4

**Description**  
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time

**How to reproduce**  
In the framework.yaml add save_path on session. If modify a file, error reloaded. Force reload for show site and symfony create 2 files session, one empty and one with session info. Config my file php.ini session.seave_path is empty. I have all tested, not find solution for my problem.

**Possible Solution**  
BAZOOKA XD
Remove save_path or add condition 

**Additional context**  

![Capture](https://user-images.githubusercontent.com/9884398/74033903-6a54b300-49b7-11ea-9b59-879f6420b370.JPG)

**Comment by michelerota** [comment]
I also have "2 files session, one empty and one with session info", but no ini_set() error or my side. Could you provide a minimal, reproducible source code so I can try to reproduce the error on my dev environment?

**Comment by wolpheus** [comment]
Hi yes no problem ...
framework.yaml

```
framework:
    secret: '%project.secret.key%'
    csrf_protection: true
    http_method_override: true
    trusted_hosts: ['%project.domain%', '%project.domain.account%']

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: 'session.handler.native_file'
        cookie_samesite: strict
        cookie_secure: true
        cookie_httponly: true
        cookie_lifetime: 7200
        save_path: '%kernel.project_dir%/var/sessions'

    esi: true
    fragments: true
    php_errors:
        log: true
```

normaly autowire by prudence add in service.yaml

```
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
      $AppProjectLang:          '%project.default.lang%'
      $AppProjectLangFallback:  '%project.fallback.lang%'
      $AppProjectLangList:      '%project.list.lang%'

  App\Event\Subscriber\LocaleSubscriber:
    arguments: ['%kernel.default_locale%']

```
and follow tuto for event/subscriber/LocalSubscriber and UserLocaleSubscriber for use in my services.php => services.yaml

```
$Locale = (new Symfony\Component\HttpFoundation\Session\Session)->get('_locale') ?: App::LANG_PROJECT;
    $container->loadFromExtension('framework', [
        'translator' => [
            'path' => ['%kernel.project_dir%/translations/' . $Locale]
        ],
    ]);
```

Regards ;)
Thx
