### ISSUE TITLE
Container lint command 

### ISSUE THREAD

**Issue by flug** [symfony/symfony#35678]
PHP VERSION: 7.4
I recently updated my dependencies with [symfony/framwork 5.0.2 to 5.0.4 ](https://github.com/symfony/framework-bundle/compare/v5.0.2...v5.0.4)

and while executing my order for the container lint I get this error. 
  ```php 
Invalid definition for service ".messenger.handler_descriptor.yvkwZqc": argument 1 of "Symfony\Component\Messenger\Handler\HandlerDescriptor::__construct" accepts "callable", "callable" passed.  
```
I'm in autowiring with no configuration other than the basic one. 

```
symfony/asset                        v5.0.4  Symfony Asset Component
symfony/browser-kit                  v5.0.4  Symfony BrowserKit Component
symfony/cache                        v5.0.4  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts              v2.0.1  Generic abstractions related to caching
symfony/config                       v5.0.4  Symfony Config Component
symfony/console                      v5.0.4  Symfony Console Component
symfony/css-selector                 v5.0.4  Symfony CssSelector Component
symfony/debug-bundle                 v5.0.4  Symfony DebugBundle
symfony/debug-pack                   v1.0.7  A debug pack for Symfony projects
symfony/dependency-injection         v5.0.4  Symfony DependencyInjection Component
symfony/doctrine-bridge              v5.0.4  Symfony Doctrine Bridge
symfony/dom-crawler                  v5.0.4  Symfony DomCrawler Component
symfony/dotenv                       v5.0.4  Registers environment variables from a .env file
symfony/error-handler                v5.0.4  Symfony ErrorHandler Component
symfony/event-dispatcher             v5.0.4  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts   v2.0.1  Generic abstractions related to dispatching event
symfony/expression-language          v5.0.4  Symfony ExpressionLanguage Component
symfony/filesystem                   v5.0.4  Symfony Filesystem Component
symfony/finder                       v5.0.4  Symfony Finder Component
symfony/flex                         v1.6.2  Composer plugin for Symfony
symfony/form                         v5.0.4  Symfony Form Component
symfony/framework-bundle             v5.0.4  Symfony FrameworkBundle
symfony/http-client                  v5.0.4  Symfony HttpClient component
symfony/http-client-contracts        v2.0.1  Generic abstractions related to HTTP clients
symfony/http-foundation              v5.0.4  Symfony HttpFoundation Component
symfony/http-kernel                  v5.0.4  Symfony HttpKernel Component
symfony/inflector                    v5.0.4  Symfony Inflector Component
symfony/intl                         v5.0.4  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                       v5.0.4  Symfony Mailer Component
symfony/maker-bundle                 v1.14.3 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                    v5.0.4  Symfony Messenger Component
symfony/mime                         v5.0.4  A library to manipulate MIME messages
symfony/monolog-bridge               v5.0.4  Symfony Monolog Bridge
symfony/monolog-bundle               v3.5.0  Symfony MonologBundle
symfony/notifier                     v5.0.4  A library to notify messages
symfony/options-resolver             v5.0.4  Symfony OptionsResolver Component
symfony/orm-pack                     v1.0.8  A pack for the Doctrine ORM
symfony/phpunit-bridge               v5.0.4  Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme       v1.13.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu            v1.13.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn            v1.13.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.13.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.13.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73               v1.13.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                      v5.0.4  Symfony Process Component
symfony/profiler-pack                v1.0.4  A pack for the Symfony web profiler
symfony/property-access              v5.0.4  Symfony PropertyAccess Component
symfony/property-info                v5.0.4  Symfony Property Info Component
symfony/routing                      v5.0.4  Symfony Routing Component
symfony/security-bundle              v5.0.4  Symfony SecurityBundle
symfony/security-core                v5.0.4  Symfony Security Component - Core Library
symfony/security-csrf                v5.0.4  Symfony Security Component - CSRF Library
symfony/security-guard               v5.0.4  Symfony Security Component - Guard
symfony/security-http                v5.0.4  Symfony Security Component - HTTP Integration
symfony/serializer                   v5.0.4  Symfony Serializer Component
symfony/serializer-pack              v1.0.2  A pack for the Symfony serializer
symfony/service-contracts            v2.0.1  Generic abstractions related to writing services
symfony/stopwatch                    v5.0.4  Symfony Stopwatch Component
symfony/string                       v5.0.4  Symfony String component
symfony/test-pack                    v1.0.6  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                  v5.0.4  Symfony Translation Component
symfony/translation-contracts        v2.0.1  Generic abstractions related to translation
symfony/twig-bridge                  v5.0.4  Symfony Twig Bridge
symfony/twig-bundle                  v5.0.4  Symfony TwigBundle
symfony/twig-pack                    v1.0.0  A Twig pack for Symfony projects
symfony/validator                    v5.0.4  Symfony Validator Component
symfony/var-dumper                   v5.0.4  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                 v5.0.4  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                     v5.0.4  Symfony WebLink Component
symfony/web-profiler-bundle          v5.0.4  Symfony WebProfilerBundle
symfony/webpack-encore-bundle        v1.7.3  Integration with your Symfony app & Webpack Encore!
symfony/yaml                         v5.0.4  Symfony Yaml Component
```
```yaml 
Current configuration for "FrameworkBundle"
===========================================

framework:
    property_info:
        enabled: true
    serializer:
        enabled: true
        enable_annotations: true
        mapping:
            paths: {  }
    router:
        resource: 'kernel::loadRoutes'
        type: service
        enabled: true
        utf8: true
        http_port: 80
        https_port: 443
        strict_requirements: true
    assets:
        json_manifest_path: /srv/website/public/build/manifest.json
        enabled: true
        version_strategy: null
        version: null
        version_format: '%%s?%%s'
        base_path: ''
        base_urls: {  }
        packages: {  }
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
        default_redis_provider: 'redis://localhost'
        default_memcached_provider: 'memcached://localhost'
        default_pdo_provider: database_connection
        pools: {  }
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        enabled: true
        storage_id: session.storage.native
        cookie_httponly: true
        gc_probability: 1
        save_path: '%kernel.cache_dir%/sessions'
        metadata_update_threshold: 0
    php_errors:
        log: true
        throw: true
    mailer:
        dsn: '%env(MAILER_DSN)%'
        enabled: true
        transports: {  }
    messenger:
        transports:
            sync:
                dsn: 'sync://'
                serializer: null
                options: {  }
                retry_strategy:
                    service: null
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
        routing: {  }
        buses:
            command_bus:
                middleware:
                    -
                        id: doctrine_ping_connection
                        arguments: {  }
                    -
                        id: doctrine_transaction
                        arguments: {  }
                default_middleware: true
        enabled: true
        serializer:
            default_serializer: messenger.transport.native_php_serializer
            symfony_serializer:
                format: json
                context: {  }
        failure_transport: null
        default_bus: null
    notifier:
        channel_policy:
            urgent:
                - email
            high:
                - email
            medium:
                - email
            low:
                - email
        admin_recipients:
            -
                email: admin@example.com
                phone: ''
        enabled: true
        chatter_transports: {  }
        texter_transports: {  }
        notification_on_failed_messages: false
    default_locale: en
    translator:
        default_path: /srv/website/translations
        fallbacks:
            - en
        enabled: true
        logging: false
        formatter: translator.formatter.default
        cache_dir: '%kernel.cache_dir%/translations'
        paths: {  }
    validation:
        email_validation_mode: html5
        enabled: true
        enable_annotations: true
        static_method:
            - loadValidatorMetadata
        translation_domain: validators
        mapping:
            paths: {  }
        not_compromised_password:
            enabled: true
            endpoint: null
        auto_mapping: {  }
    profiler:
        only_exceptions: false
        enabled: true
        collect: true
        only_master_requests: false
        dsn: 'file:%kernel.cache_dir%/profiler'
    http_method_override: true
    ide: null
    trusted_hosts: {  }
    error_controller: error_controller
    csrf_protection:
        enabled: null
    form:
        enabled: true
        csrf_protection:
            enabled: null
            field_name: _token
    esi:
        enabled: false
    ssi:
        enabled: false
    fragments:
        enabled: false
        hinclude_default_template: null
        path: /_fragment
    workflows:
        enabled: false
        workflows: {  }
    request:
        enabled: false
        formats: {  }
    annotations:
        enabled: true
        cache: php_array
        file_cache_dir: '%kernel.cache_dir%/annotations'
        debug: true
    property_access:
        magic_call: false
        throw_exception_on_invalid_index: false
        throw_exception_on_invalid_property_path: true
    web_link:
        enabled: true
    lock:
        enabled: false
        resources:
            default:
                - flock
    disallow_search_engine_index: true
    http_client:
        enabled: true
        scoped_clients: {  }
    secrets:
        enabled: true
        vault_directory: '%kernel.project_dir%/config/secrets/%kernel.environment%'
        local_dotenv_file: '%kernel.project_dir%/.env.%kernel.environment%.local'
        decryption_env_var: 'base64:default::SYMFONY_DECRYPTION_SECRET'


```
