### ISSUE TITLE
[Lock] FlockStore does not create the directory

### ISSUE THREAD

**Issue by nikophil** [symfony/symfony#35697]
**Symfony version(s) affected**: all

**Description**  
The `FlockStore` does not create the directory if it does not exist.
I don't know if it is made on purpose...

When declaring the lock system with framework bundle:
```yaml
# /packages/framework.yaml
framework:
    lock:
        file: 'flock://%kernel.project_dir%/var/lock'
```
This results in `The directory "/path/to/var/lock" is not writable.` althought the `./var` directory is writable.
Why don't we check if the directory exists, and create it if it doesn't?

**How to reproduce**  
Declare the lock with the given yaml, when directory `./var/lock` does not exist.

**Possible Solution**  
Create the directory if it doesn't exist, in the `FlockStore` constructor
