### ISSUE TITLE
Unable to enable/disable security using environment variable

### ISSUE THREAD

**Issue by nursultanturdaliev** [symfony/symfony#35719]
**Symfony version(s) affected**: v4.4.4
**Symfony Security Bundle(s) affected**: v4.2.12

**Description**  
I would like to enable or disable symfony security by using environment variables. In order to do that, my current approach is as follows:

```
security:
  firewalls:
    api:
      security: '%env(bool:ENABLE_AUTH)%'
      stateless: true
      guard:
        authenticators:
          - App\Application\Security\Guard\OAuth2Authenticator
  access_control:
    - { path: ^/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```

**How to reproduce**  
Simply use the configuration above and create `ENABLE_AUTH` variable. 

**Additional context**  

If I use `false` directly, it works fine.

Thanks!
