### ISSUE TITLE
YAML error parsing

### ISSUE THREAD

**Issue by palomamtnez** [symfony/symfony#35763]
**Symfony version(s) affected**: symfony/yaml: 5.0.4

**Description**  

YAML fails at parsing, throws an error but in http://www.yamllint.com/ it is valid:

```yaml
entries:
  - step: Verify element is visible to sync test
    time: 2020-01-27T20:01:14.566811946+13:00
    message: 'failed to select elements from selection ''Android UIAut.: new UiSelector().className("android.widget.ImageButton").resourceId("nz.co.lmidigital:id/promo_play_button")
        [0]'': request unsuccessful: An unknown server-side error occurred while processing
        the command. Original error: Could not proxy command to remote server. Original
        error: Error: socket hang up'
```

**How to reproduce**  
In a file with that content, try to parse it as the following way:

```php
$yamlContents = Yaml::parse($file);
```
