### ISSUE TITLE
Doctrine multiple databases doctrine.yaml reading order

### ISSUE THREAD

**Issue by avgustine** [symfony/symfony#35813]
**Symfony version(s) affected**: 4.2.11

**Description**  
I was trying to setup multiple databases connections as described in official manual [here](https://symfony.com/doc/4.2/doctrine/multiple_entity_managers.html) and I encountered weird behavior. No matter what I did it always used default connection instead of second connection I configured.

**How to reproduce**  
```
parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ""

doctrine:
  dbal:
    default_connection: asterisk
    connections:
      default:
        # configure these for your database server
        driver: "pdo_postgresql"
        server_version: "9.5"
        charset: utf8
        default_table_options:
          charset: utf8
          collate: utf8_general_ci
        schema_filter: /^cstmr.requisite_view$/
        mapping_types:
          enum: string
          set: string
          _bpchar: string
          name: string
        url: "%env(resolve:DATABASE_URL)%"
      asterisk:
        url: "%env(resolve:ASTERISKDB_CONNECTION_URL)%"
        driver: "pdo_mysql"
        server_version: "5.5"
        charset: utf8mb4
  orm:
    default_entity_manager: asterisk
    auto_generate_proxy_classes: true
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        second_level_cache:
          enabled: true
          region_cache_driver:
            type: memcached
          log_enabled: true
          region_lock_lifetime: 10
          regions:
            my_entity_region:
              type: default
              lifetime: 10
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
      asterisk:
        connection: asterisk
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
        
```
This config I made using official documentation page. And than in my code I was trying to use it like this:
`dump($this->getDoctrine()->getManager('asterisk')->getRepository(Record::class)->findAll();`
But it's always was using **default** connection.

**Possible Solution**  
As it turns out after about 4  hours of googling I accidentally wrote my second connection first and default one later and I did the same with entity managers' config and it worked. So my final working config was looking like:
```

parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ""

doctrine:
  dbal:
    default_connection: asterisk
    connections:
      asterisk:
        url: "%env(resolve:ASTERISKDB_CONNECTION_URL)%"
        driver: "pdo_mysql"
        server_version: "5.5"
        charset: utf8mb4
      default:
        # configure these for your database server
        driver: "pdo_postgresql"
        server_version: "9.5"
        charset: utf8
        default_table_options:
          charset: utf8
          collate: utf8_general_ci
        schema_filter: /^cstmr.requisite_view$/
        mapping_types:
          enum: string
          set: string
          _bpchar: string
          name: string
        url: "%env(resolve:DATABASE_URL)%"
      
  orm:
    default_entity_manager: asterisk
    auto_generate_proxy_classes: true
    entity_managers:
      asterisk:
        connection: asterisk
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        second_level_cache:
          enabled: true
          region_cache_driver:
            type: memcached
          log_enabled: true
          region_lock_lifetime: 10
          regions:
            my_entity_region:
              type: default
              lifetime: 10
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App

        
```
