### ISSUE TITLE
[doctrine-bridge] Configuration not applied

### ISSUE THREAD

**Issue by flaushi** [symfony/symfony#35838]
**Symfony version(s) affected**: 4.3.9

**Description**  
I have configured the second level cache as follows:
```
framework:
    cache:
        default_redis_provider: 'redis://%env(REDIS_HOST)%/%env(REDIS_DB)%'
        pools:
            doctrine.query_cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 0
            doctrine.metadata_cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 0
            doctrine.slc_cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 0
doctrine:
    orm:
        second_level_cache:
            regions:
                default:
                    lifetime: 0
                    cache_driver:
                        type: pool
                        id: doctrine.slc_cache_pool
            region_cache_driver:
                type: pool
                id: doctrine.slc_cache_pool
            region_lifetime: 0
            log_enabled:          true
            enabled:              true
        metadata_cache_driver:
            type: pool
            id: doctrine.metadata_cache_pool
        query_cache_driver:
            type: pool
            id: doctrine.query_cache_pool
```
However, inspecting the redis server, **no entries are created.**    

**Possible Solution**  
Before changing to `type: pool`, I created a service for each pool and had `type: service` and gave the service id. As soon as I revert to this settings, the cache entries start being  written again.

**Additional context**  
I found this problem while inspecting other problems with the second level cache. When calling `$this->getDoctrine()->getManager()->getCache()->evictEntityRegions()`, I found that **no entries were being deleted.** Only issuing `$this->getContainer()->get('doctrine.slc_cache_pool)->clear()`does really clear the redis namespace.
