### ISSUE TITLE
[Workflow] Add possibility for the visualization to translate the places and transitions

### ISSUE THREAD

**Issue by Defcon0** [symfony/symfony#35955]
Hello,

I'm currently using the workflow component (which is great!!) and generate the state machine to a png.

Since I'm from Germany, it would be great to have the opportunity to translate both places and transitions so that I can use the image in the user manual as well without the need to redraw it.

Also adding additional annotations to the transitions (in my case something like "Send email to auditor") would be awesome.

Is one or both of that already possible or thinkable for the future?

Thanks in advance.

Bye Defcon0

**Comment by lyrixx** [comment]
This is something very specific. I don't really see how this could be integrated to the core.
Do you have an idea?

If it can not be generic enough, you can implement your own Dumper. This is quite easy

**Comment by Defcon0** [comment]
Thanks for your quick reply. I'd "simply" extend the workflow yml configuration as follows:

```
framework:
  workflows:
    my_state_machine:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'single_state'
        arguments:
          - 'state'
      supports:
        - Contao\Model
      initial_place: in_progress
      places:
        - {name: in_progress, translation: some.trans.in_progress}
        - {name: in_progress, translation: some.trans.waiting_for_audit}
      transitions:
        submit:
          from: in_progress
          to: waiting_for_audit
          translation: some.trans.submit
          annotation: "An email is sent."
```

Of course, the fallback would be to not pass an object but a string (-> no translation in this case).

What do you think?
