### ISSUE TITLE
[RFC][DI] Automatically register interfaces as tags

### ISSUE THREAD

**Issue by dborsatto** [symfony/symfony#35974]
**Description**
In most scenarios where I want to use/inject a collection of tags, I find myself defining an interface, registering a tag for it, and injecting that tag:

```yaml
services:
    _instanceof:
        App\MyInterface:
            tags: ['app.my_interface']


    App\SomeClass:
        arguments: [!tagged app.my_interface]
```

One possible optimization would be to automatically register interfaces as tags, so this would be possible:

```yaml
services:
    App\SomeClass:
        arguments: [!tagged App\MyInterface]
```
Because there's a risk of this being an unwanted behavior (although pretty unlikely, I would say), it would rely on a `autotag` configuration being defined in the `_defaults` section, with the default value being `false` on Symfony 5, and `true` on Symfony 6, so adoption would be opt-in until the next BC break is available:

```yaml
services:
    # On Symfony 5
    _defaults:
        autowire: true
        autoconfigure: true
        autotag: false
```

I've checked some past issues covering similar topics, and I believe this is smaller in scope, as it focuses only on providing a more convenient way of defining tags which can then be used in service definitions, rather than engineering a complex way of automatically requiring certain interfaces. The FrameworkBundle itself has [a lot of configuration code](https://github.com/symfony/symfony/blob/2265a5778ef5c8e68ff6580dae70f30feccddb6a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L408-L489) which basically relies on a 1:1 relation between marker interfaces and tags, and providing a way to automatically use such interfaces as tags would remove the need for the extra step.

The only downside I can think of is that this would go in the direction of "classes as services" rather than "services as classes" (making configuration more coupled to the actual implementation rather than having an abstraction layer between the two), but I believe Symfony has been going in this direction since the introduction of autowiring with the FQCN being the conventional way of defining services instead of IDs, so moving tags to be some sort of FQCN seems to me the natural next step. Obviously this would not prevent in any way the definition of custom tags, it would be something built entirely on top of what already exists and is available.

In this simplest form (no magic, fully opt-in rather than opt-out, no new behavior) I think this would be a good way of simplifying configuration and removing the need for needless tags.

What does everyone think?

**Comment by javiereguiluz** [comment]
I've needed this lots of times ... and I've thought about this idea too ... and I agree on the problems you mentioned.

So, here's another proposal: what about providing a way of injecting all services whose classes implement a given interface? It would solve the problem without introducing the tag as an intermediary.

In action:

```yaml
# BEFORE
services:
    _instanceof:
        App\MyInterface:
            tags: ['app.my_interface']


    App\SomeClass:
        arguments: [!tagged app.my_interface]

# AFTER
services:
    App\SomeClass:
        arguments: [!instanceof App\MyInterface]
```

**Comment by dborsatto** [comment]
That could work, and it has the extra advantage of supporting the injection using abstract classes, too (I wouldn't say that would be a good practice, but it's besides the point). I suppose that would also be easier to implement, as it would look really similar to the `!tagged` implementation. Nice idea!

**Comment by ogizanagi** [comment]
I'm wondering: what would be the scope of this `!instanceof`? The whole container? The services declared in the same file?
The `autotag` solution at least gives a bit of control, as well as relying on an existing way to carry the information (tags).

**Comment by javiereguiluz** [comment]
@ogizanagi this feature would work exactly the same as tagging:

This only tags the services created in this file:

```yaml
services:
    _instanceof:
        App\MyInterface:
            tags: ['app.my_interface']
```

Bu this injects all tagged services, created in this file or not:

```yaml
services:
    App\SomeClass:
        arguments: [!tagged app.my_interface]
```

So, this would inject all "interfaced" services, created in this file or not:

```yaml
services:
    App\SomeClass:
        arguments: [!instanceof App\MyInterface]
```
