### ISSUE TITLE
[security-bundle]  Invalid param for anonymous node in firewall settings

### ISSUE THREAD

**Issue by judimator** [symfony/symfony#35981]
**Affected version:** 4.4/5

Hi there. It says here https://symfony.com/doc/4.4/security/json_login_setup.html that to set up your firewall you should add the following code:
```yml
...
        main:
            anonymous: lazy
            json_login:
                check_path:    login
                username_path: security.credentials.login
                password_path: security.credentials.password
...
```
I added and when I send POST request to `/login` an error occurred like `Invalid type for path "security.firewalls.main.anonymous". Expected array, but got string.
`

Thanks!
