### ISSUE TITLE
Deprecation Notices Missing from Toolbar and Logs

### ISSUE THREAD

**Issue by jsfgreen** [symfony/symfony#36009]
**Symfony version(s) affected**: 4.4.*

**Description**  
All deprecation notices are somehow being suppressed intermittently.  Some symfony deprecation notices show up but none from my own app show up in the symfony toolbar.  When I look at the logs there are no logs for `php.INFO`.  

**How to reproduce**  
**config/packages/dev/monolog.yaml**
```
monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event']
```

**Anywhere in src/**
```
trigger_error('Something is deprecated.', E_USER_DEPRECATED);
```

Expected output in dev.log:
```
[YYYY-MM-DD hh:mm:ss] php.INFO: User Deprecated: Something is deprecated. {}[]
````

Actual output: nothing

**Possible Solution**  
None that I'm aware.

**Additional context**  
This all happened after I changed my configs from the Symfony 3 style to the Symfony 4 style.
