### ISSUE TITLE
[Env] Inheritance

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#36012]
**Description**  
Hi everyone 👋 

Small question about env inheritance, is there any inheritance "logic" when it comes to envs? 

Here's the idea, what if I use a `staging` env (mainly for performances benchs or E2E tests (using optimised cache, etc)) and I want to use configuration from the prod env (maybe assets cache, etc) without copying the file content of importing it? 

**Example**  
I'm not sure about the usage but I was thinking about something like this: 

```yaml
# webpack_encore.yaml
inherit:
    env: 'prod || test' # In case of failure or if the file does not exist?
```

I know that we can use imports: 

```yaml
imports:
    - { resource: '../prod/webpack_encore.yaml' }
```

But maybe it could be more friendly to be able to specify an env (or a set of envs in case of failures) and let Symfony merge the env? 

Any feedbacks? 🤔
