### ISSUE TITLE
Autowire error not logged in monolog

### ISSUE THREAD

**Issue by younessof2m** [symfony/symfony#36028]
**Symfony version(s) affected**: 5.0.5

**Description**  
When I autowire an not exist class in construct of my command, I get error in console but the error is not logged in monolog file. I absolutely want log this error in monolog file.

**How to reproduce**
Try to autowire non existent class in construct function.

Example of construct:
``` php
public function __construct(SomeClass $someClass)
{
    parent::__construct();
}
```
my monolog.yaml:
``` yaml
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: notice
            channels: ["!event", "!app"]
        app:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-app.log"
            level: notice
            channels: ["app"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
```

Error message display in console:
`Cannot autowire service "App\Command\SomeCommand": argument "$someClass" of method "__construct()" has type "App\SomePath\SomeClass" but this class was not found.`

**Additional context**  
**php version**: 7.3
