### ISSUE TITLE
[YAML]  !include tag support

### ISSUE THREAD

**Issue by drzraf** [symfony/symfony#36043]
**Description**  
[SymfonyCloud's configuration supports]( https://symfony.com/doc/master/cloud/cookbooks/https.html) a YAML `!include` "custom" tag.

It would be useful as part of the YAML component.

**Example**  
```yaml
tls:
    client_certificate_authorities:
        - !include
            type: string
            path: file1.key
```
