### ISSUE TITLE
Add a configuration parameter to allow hand-defined services (from ALL files) to take priority when compiling the container 

### ISSUE THREAD

**Issue by pkly** [symfony/symfony#36055]
**Description**  
Currently as seen in multiple issues like https://github.com/symfony/symfony/issues/31150 and a few related ones it can be rather frustrating to declare custom services, after all at least sometimes we all know better than symfony what we want to do.
Currently the only working way (as of 4.4.5) of getting "manual" definitions of services working is the following syntax:

```yaml
service_id:
    class: ClassName
    arguments:
        - '@something'
```

This applies to services that are being imported from another file, as services defined in services.yaml work fine. Yet then why even have the import functionality in the first place if everything gets overriden in some cases by autoconfigure and autowire.

However this creates another issue - services that are marked with an ID that is not the class name make it so that subscribers/listeners and such could get attached to the events twice - once under the ID and once under the class name.

There's a few ways out, one is to define services with an id and class as seen above, but that cannot be used for subscribers, as they're defined twice, besides you run into a bunch of names and aliases that could be simply never used in the first place, instead referring to a proper class identifier.
The other one is to simply define all services in services.yaml or equivalent, but then that's also not a great idea as no one wants to read a 4k+ loc file.
The last one is to add compiler passes, which is the only sensible way I found, but it's still tedious and takes away from the fact that the container compiler should already be doing this work to begin with.

Enter: a non-BC breaking solution - new function/yaml parameter - no_redefine.

**Example**  
The default symfony services.yaml looks something like this

```yaml
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        no_redefine: true
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
```

We could add a new parameter - no_redefine that'd prevent symfony from re-creating services already defined by hand in other .yaml files (or equivalent), by working like the exclude path but automatically appending each file that has already been defined by this point, while still allowing manual overrides after this declaration (like before)

No BC breaks should occur as the default setting could simply be 'false' - no functionality change.
I could look into writing a pull request for this feature at a later point, I also don't believe a major amount of work would be needed simply because you could leverage the exclude functionality which already supports files.

**Comment by linaori** [comment]
Having helped people with this issue often enough on slack, it's something I'd like to see solved, though not as you proposed. In the end it's the order of loading files that's confusing, because the primary file loads the additional files _first_.

> The other one is to simply define all services in services.yaml or equivalent, but then that's also not a great idea as no one wants to read a 4k+ loc file.

I have worked with some pretty big applications, and ever since autowiring these files barely reached 500 lines. Having that mine lines of config sounds like there's another issue at play, and different solutions would be possible to reduce that size.

> We could add a new parameter - no_redefine that'd prevent symfony from re-creating services already defined by hand in other .yaml files (or equivalent), by working like the exclude path but automatically appending each file that has already been defined by this point, while still allowing manual overrides after this declaration (like before)

This would imo complicate both the design and usability.

> Add a configuration parameter to allow hand-defined services (from ALL files) to take priority when compiling the container 

This would effectively mess with the order of loading. 

Perhaps instead of including or importing different config (which imo should be top down in priority), a new type of config could be added? 

```
# services_dev.yaml
services:
    App\ExampleService:
        $theArgument: true

# services_dev.yaml
services:
    extends: services.yaml

    App\ExampleService:
        $theArgument: false
```

The concept of inheritance is that you override a "parent", where twig is a nice example as it totally redefined how we structure our templates. By having a design where you can extend other config files, you'd clearly understand the loading order. In terms of processing though, there could be 2 children that extend `services.yaml`, so you'd still have a loading sequence issue here.
