### ISSUE TITLE
[HttpFoundation] Support for PHP7+ "read_and_close" option support for Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage

### ISSUE THREAD

**Issue by DocFX** [symfony/symfony#36060]
**Description**  

Offer the additional option of PHP 7.0 `read_and_close` for the native session handler `::Start()` -using [`session_start()`](https://www.php.net/manual/en/function.session-start.php)- to still provide the session mechanic to PHP scripts without offering the write abilities to it, therefore allowing concurrent scripts (i.e. Symfony calls, notably) to be executed at the same time.

**Explanation & quick ideas** 

This option is totally userland, and might be customizable per action one day (maybe through annotations), but this FR is only about implementing the option globally to a Symfony project, without overriding the `NativeSessionStorage` handler. 
Though you wouldn't usually need to use this for many cases, some readonly API websites could benefit this, even though they should probably need not to use sessions but direct, per call auth mechanics like tokens. This is just a (poor) example.

This would avoid massive calls to [session_write_close](https://www.php.net/manual/en/function.session-write-close.php) to compensate this pitfall.
(A classic article on how it works can be found [here](https://ma.ttias.be/php-session-locking-prevent-sessions-blocking-in-requests/).)

This follows the open discussions left behind after #24875.

**Example**  

Ideal call would be something like:

```yaml
# config/packages/framework.yaml
framework:
    session:
        # ...
        storage_id: 'session.storage.native'
        # this whole configuration is of course a debate, this is just an idea :) 
        options:
            start:
                read_and_close: true
```

As found in `NativeSessionStorage.php:150` on *master*: 

```php
        // There be Dragons :3 
        if (!session_start()) {
            throw new \RuntimeException('Failed to start the session');
        }
```

Of course, this would lead to updates in the Symfony Doc, in HttpFoundation docs, especially.
https://symfony.com/doc/current/reference/configuration/framework.html#config-framework-session
