### ISSUE TITLE
Cache cleared exclude sessions

### ISSUE THREAD

**Issue by ForcaBarcaDev** [symfony/symfony#36098]
Sessions deleted after SncRedisBundle cleared cache. But for cache and sessions I use different dsn.
How can I clear cache in redis excluding session?
```
framework:
    session:
        gc_maxlifetime: 1500
        handler_id: snc_redis.session.handler
```

```
snc_redis:
    clients:
        cache_local:
            type: phpredis
            alias: cache_local
            dsn: 'redis://%redis-local%/1'
            logging: '%kernel.debug%'
        cache_local_session:
            type: phpredis
            alias: cache_local_session
            dsn: 'redis://%redis-local%/2'
            logging: '%kernel.debug%'
    session:
        client: cache_local_session
        prefix: session
```
```
class CacheClearer implements Symfony\Component\HttpKernel\CacheClearer\CacheClearerInterface
{
    /**
     * @var CacheItemPoolInterface
     */
    private $cache;

    public function __construct( Psr\Cache\CacheItemPoolInterface $cache)
    {
        $this->cache = $cache;
    }

    public function clear($cacheDir): void
    {
        $this->cache->clear();
    }
}
```
```
    app.cache.local:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@snc_redis.cache_local'
            - "%kernel.environment%"
        calls:
            - [setLogger, ['@app.cache.logger']]
```
