### ISSUE TITLE
Chain of Responsibilty in service definition

### ISSUE THREAD

**Issue by Florian-Merle** [symfony/symfony#36116]
**Description**  
I think the Chain of Responsibility design pattern can be really useful, but I have often seen it implemented in an odd way.

Usually a main service will get a list of other services (each chain links) and iterates over them in order to create the "chain". Also the chain links have 2 methods: `public function supports(Context $context): bool` and `public function execute()`.

I think that it could be useful to provide an easy and quick way to define chains within the service definition of Symfony.

**Cases**
I can think of 3 different cases :
* Each service gets called one after the other
* Services are called one by one until one of them can handle (supports) the context
* Similarly to middleware, each service is called  one after the other but its context is equals to the response of the previous service

**Example** 
It could be used in the following way:

```yaml
# config/services.yaml

services:
    # invoking this service will return what is returned by the first service of
    # the chain returning true to supports
    app_chain_first:
        chain:
           supporst_method: supports
            type: first
            services: some_tag

    # returns an array of what is returned by all of the services
    app_chain_each:
        chain:
            type: each
            services: some_tag

    # returns what the last service of the chain returns
    app_chain_middleware:
        chain:
            type: middleware
            services: some_tag
```

**Final thoughts**
This probably needs to be refined.
Also, I am not sure that that kind of functionalities should be implemented in Symfony. But at the same time, [factories](https://symfony.com/doc/current/service_container/factories.html) are so it could be a nice addition.
