### ISSUE TITLE
[Serializer] The annotation does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by Sengorius** [symfony/symfony#36263]
**Symfony version(s) affected**: I am working with 4.4.6

**Description**  
Same problem as described in https://github.com/symfony/symfony/issues/1402. I have tried the ideas mentioned in this issue.

**The configuration:**

```yaml
# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true

    # ...

    validation:
        enabled: true
        enable_annotations: true
        email_validation_mode: 'html5'

    annotations:
        enabled: true
```

```json
# composer.json
{
    "require": {
        "php": "^7.2.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "symfony/console": "*",
        "symfony/dotenv": "*",
        "symfony/flex": "*",
        "symfony/form": "*",
        "symfony/framework-bundle": "*",
        "symfony/mailer": "*",
        "symfony/messenger": "*",
        "symfony/orm-pack": "^1.0",
        "symfony/process": "*",
        "symfony/security-bundle": "*",
        "symfony/serializer": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/twig-bundle": "*",
        "symfony/validator": "*",
    },
    "require-dev": {
        "symfony/debug-pack": "*",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "4.4.*"
        }
    }
}
```

**The Code:**

```php
# src/Entity/NoteEntity.php
class NoteEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Id
     */
    private $id = null;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="text", nullable=false)
     */
    private $title = null;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description = null;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="created", type="datetime", nullable=false)
     */
    private $created = null;


    /**
     * NoteEntity constructor.
     *
     * @throws Exception
     */
    public function __construct()
    {
        $this->created = new DateTime('now');
    }

    // getter & setter ...
}
```

```php
# src/Service/LoggingService.php
class LoggingService
{
    /**
     * @param object $to
     * @param object $from
     * @param array  $spareKeys
     *
     * @return array
     */
    public function objectCompare(object $to, object $from, array $spareKeys = []): array
    {
        // configuration to read `@SerializedName("...")` annotation from objects
        $classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
        $metadataAwareNameConverter = new MetadataAwareNameConverter($classMetadataFactory);

        // setup the normalizer
        $nameConverterNormalizer = new ObjectNormalizer($classMetadataFactory, $metadataAwareNameConverter);

        // setup the serializer
        $serializer = new Serializer([$nameConverterNormalizer]);

        // normalize both objects and calculate changes
        $normalizedTo = $serializer->normalize($to);
        $normalizedFrom = $serializer->normalize($from);

        return $this->arrayCompare($normalizedTo, $normalizedFrom, $spareKeys);
    }

    // ...
}
```

```php
# src/Controller/Logging/LoggingController.php
class LoggingController extends AbstractController
{
    private $loggingService;

    /**
     * @param LoggingService $loggingService
     */
    public function __construct(LoggingService $loggingService)
    {
        $this->loggingService = $loggingService;
    }

    public function loggingServiceTest(): Response
    {
        $realObj1 = (new NoteEntity())
            ->setId(5)
            ->setTitle('Note from User 1')
            ->setDescription('qwert')
        ;

        $realObj2 = (new NoteEntity())
            ->setId(6)
            ->setTitle('Note from User 2')
            ->setDescription('asdf')
        ;

        $this->loggingService->objectCompare($realObj1, $realObj2);

        // response ...
    }
}
```

**The error message:**

```
[Semantical Error] The annotation "@Doctrine\ORM\Mapping\Column" in property App\Entity\NoteEntity::$id does not exist, or could not be auto-loaded.
```

**Additional context**  

Changing the annotation parameters did not work, like mentioned in https://stackoverflow.com/questions/19444044/symfony-2-the-annotation-in-property-does-not-exist-or-could-not-be-auto-load.

```php
/**
 * @var int
 *
 * @ORM\Column(name="id", type="integer", nullable=false)
 * @ORM\GeneratedValue(strategy="IDENTITY")
 * @ORM\Id
 */
private $id = null;
```

**But:** It works if the cache is empty! Deleting the whole cache directory lets the code just work fine (`php bin/console cache:clear` is not enough). Reloading the page then fails with the error every time...

**Comment by blowski** [comment]
What do you get when you run the following on the command line?

```
bin/console config:dump-reference FrameworkBundle annotations
```

**Comment by Sengorius** [comment]
So, as I am working with Docker Containers, the cache is moved away from the project folder into the docker container. This speeds up the access time when running the project locally.

It's done via `Kernel.php`:
```
class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    private const CONFIG_EXTS = '.{php,xml,yaml,yml}';

    // ...

    public function getCacheDir(): string
    {
        if (false !== isset($_ENV['APP_CACHE_DIR']) && !empty($_ENV['APP_CACHE_DIR'])) {
            return $_ENV['APP_CACHE_DIR'].'/'.$this->environment;
        }

        return $this->getProjectDir().'/var/cache/'.$this->environment;
    }

    // ...
}
```

```yaml
# root@ee5bf5d5546e /var/www/html # bin/console config:dump-reference FrameworkBundle annotations
# Default configuration for "FrameworkBundle" at path "annotations"

# annotation configuration
annotations:
    enabled:              true
    cache:                php_array
    file_cache_dir:       '%kernel.cache_dir%/annotations'
    debug:                true
```

The directory looks like this:
```shell
root@ee5bf5d5546e /var/www/html # ll /tmp/cache/dev/
total 620
drwxrwxrwx  7 www-data www-data   4096 Mar 30 15:08 .
drwxr-xr-x  4 www-data www-data   4096 Mar 30 13:21 ..
drwxrwxrwx  2 www-data www-data  20480 Mar 30 15:08 Container6PYF12O
-rw-rw-rw-  1 www-data www-data   5028 Mar 30 13:21 UrlGenerator.php
-rw-rw-rw-  1 www-data www-data   3066 Mar 30 13:21 UrlGenerator.php.meta
-rw-rw-rw-  1 www-data www-data   6161 Mar 30 13:21 UrlMatcher.php
-rw-rw-rw-  1 www-data www-data   3066 Mar 30 13:21 UrlMatcher.php.meta
-rw-rw-rw-  1 www-data www-data     98 Mar 30 15:08 annotations.map
drwxrwxrwx  3 www-data www-data   4096 Mar 30 13:21 doctrine
drwxrwxrwx 10 www-data www-data   4096 Mar 30 13:21 pools
drwxrwxrwx  5 www-data www-data   4096 Mar 30 13:51 profiler
-rw-rw-rw-  1 root     root        785 Mar 30 15:08 srcApp_KernelDevDebugContainer.php
-rw-rw-rw-  1 www-data www-data      0 Mar 30 15:08 srcApp_KernelDevDebugContainer.php.lock
-rw-rw-rw-  1 root     root      49331 Mar 30 15:08 srcApp_KernelDevDebugContainer.php.meta
-rw-rw-rw-  1 root     root     324310 Mar 30 15:08 srcApp_KernelDevDebugContainer.xml
-rw-rw-rw-  1 root     root      47987 Mar 30 15:08 srcApp_KernelDevDebugContainer.xml.meta
-rw-rw-rw-  1 www-data www-data 122129 Mar 30 15:08 srcApp_KernelDevDebugContainerCompiler.log
-rw-rw-rw-  1 www-data www-data      6 Mar 30 15:08 srcApp_KernelDevDebugContainerDeprecations.log
drwxrwxrwx 54 www-data www-data   4096 Mar 30 13:51 twig
```

**Comment by blowski** [comment]
🤔 

Ah, I'm guessing there's a bug in your `getCacheDir()` method. Try setting that to a fixed value (i.e. no conditionals in there) and see what happens then.

As a side-note, I've run into the same performance problems as you with the cache. Instead of moving the cache folder, I use Docker's `cached` volume directive - https://docs.docker.com/compose/compose-file/#caching-options-for-volume-mounts-docker-for-mac.

**Comment by Sengorius** [comment]
Hmm, but it worked pretty well until today. Good, I've tried the following:
- reset the `getCacheDir()` to it's default
- restarted the Docker environment
- first try went well and was executed as expected, as there was no cache
- after reloading I got the same issue
- then used `chown -R www-data:www-data var/cache/` to fix access issue (if any)
- still the same issue
- removed the cache with `rm -rf var/cache/dev/*` (from project directory)
- first try went well and was executed as expected
- next try brought the same issue, again

**Comment by blowski** [comment]
I've run into similar issues, where the CLI is warming the cache in one place and the FPM is trying to load it from another. I can't say that's definitely what's happening here, but it at least has similar symptoms. That's why I thought relying on Symfony's `getCacheDir()` method would fix the problem, so I'm really surprised there.

Just for a sanity check, the `vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Column.php` is definitely there?

**Comment by Sengorius** [comment]
Check!
![DoctrineColumnClass](https://user-images.githubusercontent.com/7498666/77930062-abc45900-72aa-11ea-995a-2898ae7b1830.png)

Well, I never ran into the cache warming case, as with the `getCacheDir()` controlled from the `.env`, it rests at the same place as long as the container is running.

PS: Thanks for the hint with the Caching Options in Docker, but I'm using Linux ;-)

**Comment by blowski** [comment]
When you run the CLI app, do you know if your shell is parsing the `.env` file and loading the values as environment variables? Have you done anything recently like changed to ZSH or Fish?

**Comment by Sengorius** [comment]
The `.env` is just included via `docker-compose.yml` and loaded with the `symfony/dotenv` component internally. There is only `sh` and `bash` within the container.
```shell
root@d9a0636deb23 /var/www/html # echo $APP_ENV
dev

root@d9a0636deb23 /var/www/html # echo $MAILER_DSN
null://localhost
```

But it seems, you partially have a point here. Symfony profiler says, anything is defined as regular env variables.
![Screenshot_2020-03-30 Symfony Profiler](https://user-images.githubusercontent.com/7498666/77935408-acacb900-72b1-11ea-8157-c227393a7f44.png)

But does this matter?

**Comment by blowski** [comment]
Where do you run the the Symfony CLI - on your host system, or in the Docker container?

**Comment by Sengorius** [comment]
What Symfony CLI do you mean? I'm running a pretty simple `docker-compose` setup:
```yaml
volumes:
    data-db:

services:
    web:
        image: ngnix:latest
        container_name: project-web
        env_file: .env
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
            - 443:443

    php:
        image: php:7.4-fpm
        container_name: project-app
        env_file: .env
        volumes:
            - .:/var/www/html
        links:
            - db

    db:
        image: mysql:5.7
        container_name: project-db
        env_file: .env
        ports:
            - 3306:3306
        volumes:
            - data-db:/var/lib/mysql
            - ./var:/var/project
```

Okay, so I stopped my Docker environment and just `php -S localhost:8080 -t public/` from the projects directory. Worked fine the first time, then I got the same issue again.
