### ISSUE TITLE
[RFC] disable langs in Internationalized routing and redirecting

### ISSUE THREAD

**Issue by hectorprats** [symfony/symfony#36266]
**Description**  
By creating a website, I have discovered that I need to temporarily hide a language.
But to delete all the routes in the controllers (annotations) and to put them back in the future seems absurd to me.

I am designing a new feature to be able to close a language completely (http code 404) or that you can make a temporary redirection to another language.

It can be very useful for SEO.

For this reason, I beg you to contribute ideas and suggestions to improve it. I would like to finish it as soon as possible.

**Example**  
```
#config\packages\routing.yaml
framework:
    router:
        utf8: true
        langs:
            disabled:
                pt:
                    http_code: 307
                    lang_destiny: en
                es:
#           disabled: 'es'                (simple method getting 404 code in Spanish pages)
```

With this yaml, you can redirect 307 from the Portuguese version to the English version and 404 to the Spanish version.

**Comment by blowski** [comment]
Sounds good, though I'm not an expert in i18n or SEO so can't comment.

One tiny bit of feedback, though - I think you want `lang_destination` instead of `lang_destiny`.

**Comment by hectorprats** [comment]
> Sounds good, though I'm not an expert in i18n or SEO so can't comment.
> 
> One tiny bit of feedback, though - I think you want `lang_destination` instead of `lang_destiny`.

Thanks. I changed it.

**Comment by rosier** [comment]
How about using `redirect_to` instead of `lang_destination` ?

And is `http_code: 307` the default config if a temporary redirection to another language is enabled?

**Comment by hectorprats** [comment]
> How about using `redirect_to` instead of `lang_destination` ?
> 
> And is `http_code: 307` the default config if a temporary redirection to another language is enabled?

The default http_code is 404.

**Comment by hectorprats** [comment]
Finally works with any of this three methods:

```
framework:
    router:
        utf8: true
        langs:
#            disabled:
#                es:
#                    http_code: 307
#                    redirect_to: en
#                pt:
#                nl:
#            disabled: ['nl', 'pt']
#            disabled: pt
```

What else? :-)
