### ISSUE TITLE
PUT Request empty FileBag

### ISSUE THREAD

**Issue by Cypaubr** [symfony/symfony#36307]
**Symfony version(s) affected**: 4.4.6

**Description**  
I have an API route waiting for PUT requests where you can update your profile picture. Using postman I send a PUT request with my picture in its form-data. On the server side I just `var_dump` the request and the FileBag is empty. Event when just sending a string the ParameterBag is empty.

**How to reproduce**  
My route:
```yaml
api_edit_user:
  path: /api/user/me/edit
  controller: App\Controller\UserController::editAction
  methods: ['PUT']
```

The controller:
```php
public function editAction(DocumentManager $dm,
                               SerializerInterface$serializer,
                               UserPasswordEncoderInterface $encoder,
                               Request $request,
                               ModeratorService $moderatorService): JsonResponse
    {
        var_dump($request -> files);
    }
```
