### ISSUE TITLE
Autowire improvement in the form of 'instanceof_iterator'

### ISSUE THREAD

**Issue by HarasimowiczKamil** [symfony/symfony#36330]
**Description**  

I suggest you add a mechanism similar to [reference-tagged-services](https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services). But based on interfaces.

**Example**  

In yaml config file (similarly xml and php):

```yaml
App\HandlerCollection:
        # inject all services tagged with app.handler as first argument
        arguments:
            - !instanceof_iterator App\HandlerInterface
```

Service:

```php
<?php
// src/HandlerCollection.php
namespace App;

use App\HandlerInterface;

class HandlerCollection
{
    /**
     * @param HandlerInterface[]
     */
    public function __construct(iterable $handlers)
    {
    }
}
```

**Comment by fancyweb** [comment]
I agree on the idea. We would need "instanceof_localtor" too. Currently I have to do:
```yaml
services:
    _instanceof:
        App\MyInterface
            tags:
                - "app.my_tag"

    App\MyService:
        arguments:
            - !tagged_locator "app.my_tag"

```
