### ISSUE TITLE
[DI] Add instanceof support to resource loader

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#36374]
**Description**  

You might want to be specific about loading code (and adding tags to it).

For example, I'm working on an ETL extractor which contains recipes for multiple applications, like

```yaml
Specification\
    AppA\
    AppB\
    AppC\
    AppASpecification.php
    (etc.)
```

What I want to be able to do is load all the services implementing a specific interface `DefinitionFactor` from `AppA` and inject them into `AppASpecification` (via tags, most likely).

So they need to be **both** in a certain namespace / folder and instances of a specific interface to be considered.

**Example**  
```yaml
    Importer\Specification\AppA\:
        resource: '../../src/Importer/Specification/AppA/*'
        __instanceof:
            Importer\DefinitionFactory:
                tags: ["importer.specification.app_a.definition_factory"]
        arguments:
            $count: 100

    Importer\Specification\AppASpecification:
        arguments:
            $factories: !tagged "importer.specification.app_a.definition_factory"
        tags: ["importer.specification"]
```

**Comment by dkarlovi** [comment]
Of course, it would be pretty fun if you could do something like:

```yaml
    Importer\Specification\{app}\:
        resource: '../../src/Importer/Specification/{app}/*'
        __instanceof:
            Importer\DefinitionFactory:
                tags: ["importer.specification.{app}.definition_factory"]
        arguments:
            $count: 100

    Importer\Specification\{app}Specification:
        arguments:
            $factories: !tagged "importer.specification.{app}.definition_factory"
        tags: ["importer.specification"]
```

Maybe with PHP config?

**Comment by javiereguiluz** [comment]
This might be related to #36330 and #35974 ?

**Comment by dkarlovi** [comment]
@javiereguiluz TBH I'm not sure it does? This seems like opposite od #35974 since it's trying to autoconfigure **less** than by default.

Maybe I should have called the issue something else because I might be promoting an XY problem here. My goal is to **tag all services from a specific namespace (and recursively) and implementing an interface with a specific tag**, the issue is my suggested solution for that, but if you have a different solution for that, that works too.

**Comment by nicolas-grekas** [comment]
I think you can already do this, but you need to split loading the namespace in a dedicated file, isn't it?

**Comment by dkarlovi** [comment]
@nicolas-grekas could you give an example? I'm not sure how I can enforce both the sub-namespace and interface at the same time.

**Comment by nicolas-grekas** [comment]
```
services:
    _instanceof:
        Importer\DefinitionFactory:
            tags: ["importer.specification.app_a.definition_factory"]

    Importer\Specification\AppA\:
        resource: '../../src/Importer/Specification/AppA/*'
        arguments:
            $count: 100
```
