### ISSUE TITLE
[Cache] Apcu adapter in CLI

### ISSUE THREAD

**Issue by ossinkine** [symfony/symfony#36399]
**Description**  

APCu cache adapter works when `apc.enabled` is on, however, in CLI mode with the` apc.enable_cli` turned off, the adapter generates a lot of messages like `Failed to save key`.
For the system cache, this was fixed in https://github.com/symfony/symfony/pull/23390 by installing `NullLogger` in the adapter.
However, the problem persists for example in this configuration:
```yaml
framework:
    cache:
        pools:
            cache.default:
                adapters:
                    - cache.adapter.apcu
                    - cache.adapter.redis
```

I suggest checking the `apc.enable_cli` option in each method, and do nothing in CLI mode, don't try to call acpu functions.
Something like this:
```php
protected function doFetch(array $ids)
{
    if ('cli' === \PHP_SAPI && !filter_var(ini_get('apc.enable_cli'), FILTER_VALIDATE_BOOLEAN)) {
        return [];
    }

    ...
}
```

If this is a good solution, I will create a PR. If not, what decision do you think would be good?
