### ISSUE TITLE
Allow array return from Twig workflow_metadata()

### ISSUE THREAD

**Issue by gisostallenberg** [symfony/symfony#36391]
**Description**  
The workflow metadata store can contain not only strings, but setting nested metadata results in an error when workflow_metadata() is used in Twig.
![image](https://user-images.githubusercontent.com/11526270/78815329-6998c700-79d0-11ea-8bd6-611832df4e99.png)

**Example**  
This example is made up, but I had a case in my project where I expected this working, but got an error. In some issues reported in Symfony I see people using deeper nested metadata (but apparently they do not use the Twig function, yet...)
```yaml
framework:
    workflows:
        blog_publishing:
                # ...
            transitions:
                to_review:
                    from: draft
                    to:   review
                    metadata:
                        publish:
                            label: Publish
                            icon: paper
```

I suggest removing the return type at https://github.com/symfony/symfony/blob/168574db2961ad693dec6ed3fe09b4278c2bcc55/src/Symfony/Bridge/Twig/Extension/WorkflowExtension.php#L98, or some other change which avoids an error in Twig.
