### ISSUE TITLE
Translation: curly braces not removed from parameters

### ISSUE THREAD

**Issue by gnutix** [symfony/symfony#36461]
**Symfony version(s) affected**: 5.0.7

**Description**  
Given a translation defined in `translations/messages.fr.yaml` : 
```yaml
product:
    add:
        success: 'Le produit {id} a été ajouté!'
```
Translated using : `$translator->trans('product.add.success', ['id' => 1234]);`
I would except the message `Le produit 1234 a été ajouté!', but the result was `Le produit {1234} a été ajouté!`.

Apparently, I'm not the only one: https://stackoverflow.com/questions/59708205/symfony-translation-ignores-curly-braces-in-parameters
