### ISSUE TITLE
Problem with multiple doctrine connection 

### ISSUE THREAD

**Issue by AllanFousse** [symfony/symfony#36486]
**Symfony version(s) affected**: 5.1

**Description**  
In symfony 5.1, the default connection name need to be default in case of multiple connection.
Works fine in 5.0

**How to reproduce**  
In the documentation example, just change default to something other

**Possible Solution**  

**Additional context**  
The exact error :
The service "doctrine.migrations.dependency_factory" has a dependency on a non-existent service "doctrine.dbal.default_connection".

**Comment by xabbuh** [comment]
What chapter of the documentation do you refer to? Is this a pure documentation issue or is there also something that needs to be fixed in the code?

**Comment by AllanFousse** [comment]
https://symfony.com/doc/master/doctrine/multiple_entity_managers.html

This is the documentation for 5.1 and all works fine. But if you change the name of the default connection "default" with something other, there are a bug in the code with this exception  

>  The service "doctrine.migrations.dependency_factory" has a dependency on a non-existent service "doctrine.dbal.default_connection".

```
doctrine:
    dbal:
        default_connection: SOMETHING
        connections:
            SOMETHING:
                # configure these for your database server
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            customer:
                # configure these for your database server
                url: '%env(DATABASE_CUSTOMER_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: SOMETHING
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            customer:
                connection: customer
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Customer'
                        prefix: 'App\Entity\Customer'
                        alias: Customer
```
