### ISSUE TITLE
Service Subscriber on alias does not longer work

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#36495]
**Symfony version(s) affected**: 5.0.7 (4.4 it did work)

**Description**  

When I update to Symfony 5 a controller extending from AbstractController does not longer work and ends with:

> "App\Controller\TestController" has no container set, did you forget to define it as a service subscriber?

**How to reproduce**  

```yaml
# config/services.yaml

services:
    _defaults:
        # no autowire as its inside a bundle
        autowire: false
        autoconfigure: false

    test_controller:
        class: 'App\Controller\TestController'
        tags: ['controller.service_arguments', 'controller.service_subscriber']
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    App\Controller\TestController:
        alias: 'test_controller'
```

```yaml
static:
    path: /static-route
    controller:  App\Controller\TestController::test
```

```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class TestController extends AbstractController
{
    public function test(Request $request)
    {
        return new Response('test');
    }
}
```

**Possible Solution**  

Could not find why the set container is not called in this case, but it has todo with the usage of `alias`.

**Additional context**  

 --
