### ISSUE TITLE
Deploying 7.4 with redis extension throws error & then cannot re-deploy

### ISSUE THREAD

**Issue by toby-griffiths** [symfony/symfony#36554]
**Symfony version(s) affected**: Symfony CLI version v4.14.1

**Description**  
Attempting to deploy an application using PHP 7.4 + redis extension fails with the following error…

```
    Found 1 new commit

    Building application 'app' (runtime type: php:7.4, tree: f8e4059)
      Generating runtime configuration.
        W: Traceback (most recent call last):
        W:   File "/etc/platform/commands/generate-build-configuration", line 9, in <module>
        W:     service.generate_build_configuration(**kwargs)
        W:   File "/usr/lib/python2.7/dist-packages/platformsh_app/service.py", line 425, in generate_build_configuration
        W:     self.generate_application_configuration(app)
        W:   File "/usr/lib/python2.7/dist-packages/platformsh_app_php/__init__.py", line 224, in generate_application_configuration
        W:     extension = _validate_extension(extension)
        W:   File "/usr/lib/python2.7/dist-packages/platformsh_app_php/__init__.py", line 209, in _validate_extension
        W:     raise Exception("Extension '%s' is unknown." % extension)
        W: Exception: Extension '{'configuration': {}, 'name': u'redis'}' is unknown.

      E: Error building project: Unable to generate runtime configuration files for the application.

    E: Error: Unable to build application, aborting.
```

```yaml
# .symfony.cloud.yaml
name: app

type: php:7.4

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_pgsql
        - redis

build:
    flavor: none

relationships:
    database: 'db:postgresql'
    redis: 'rediscache:redis'

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 512

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

```

**How to reproduce**  
1. With the above `.symfony.cloud.yaml` file, run…

        $ symfony deploy

1. See error as above
1. Attempt to re-dploy by running…

        $ symfony deploy

1. See `Everything up-to-date` in response

**Possible Solution**  
1. Fix support for redis extension on PHP 7.4; or
1. Fix issue with false reporting of environment being up-to-date, and allow re-deploying

**Additional context**  
This is using the example in the Symfony 5 - The Fast Track book, only using PHP 7.4, rather than 7.3.
