### ISSUE TITLE
Can't override _defaults using nested YAML files for routes

### ISSUE THREAD

**Issue by hildebro** [symfony/symfony#36605]
We're using nested YAML files for routes:
```
- routes.yml
- - routes_category_1.yml
- - - routes_category_1_1.yml
- - - routes_category_1_2.yml
- - routes_category_2.yml
```

This is what we use in `routes.yml` to include other route files:
```
# routes.yml
category_1:
    resource: 'routes_category_1.yml'
    defaults:
        _roles: Path\To\Role\Role::CATEGORY_1
    prefix: /category_1
```

We use the `_roles` parameter to restrict access to certain pages. So anyone who wants to access routes for category 1 needs the matching role. When trying to further restrict access to sub categories, we would like to use the following:
```
# routes_category_1.yml
category_1_1:
    resource: 'routes_category_1_1.yml'
    defaults:
        _roles: Path\To\Role\Role::CATEGORY_1_1
    prefix: /category_1_1
category_1_2:
    resource: 'routes_category_1_2.yml'
    prefix: /category_1_2
```

With this setup, we would think that anything inside `routes_category_1_1.yml` should now require the specialized role `Role::CATEGORY_1_1` while any route we define in `routes_category_1_2.yml` keeps the default value of its parent `Role::CATEGORY_1`.

However, the defaults we define in child YAML files fail to override their parent's values. When we call ` $request->attributes->get('_roles');`, we always get the highest role in a nesting rather than the lowest one.
