### ISSUE TITLE
Login lost after setting logout_on_user_change: true

### ISSUE THREAD

**Issue by rayrigam** [symfony/symfony#36671]
**Symfony version(s) affected**: 3.4.*
**Description**  
I have a Symfony application with a custom user provider since I use Propel to connect to the database. The authentication/login is working fine, unless I add to security.yml config the following line (as requested by a deprecation notice): `logout_on_user_change: true`. That results in users no longer being able to login (the login is lost with the first redirect). These are the logs that show up: 

> security.DEBUG: Cannot refresh token because user has changed. {"username":"xyz","provider":"MyApp\\MyAppBundle\\Security\\UserProvider"}

> security.DEBUG:Token was deauthenticated after trying to refresh it.

**How to reproduce**  
security.yml:
```
security:
    providers:
        main_user_provider:
            id: my_app.user_provider
    encoders:
        MyApp\MyAppBundle\Model\User:
            algorithm: bcrypt
firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous:    ~
            pattern: ^/
            form_login:
                provider: main_user_provider
                csrf_token_generator: security.csrf.token_manager
                login_path: /
                use_referer: true
                success_handler: authentication_handler
                failure_handler: authentication_handler
            logout:
                path:   /logout
                target: /
            logout_on_user_change: true
            guard:
                authenticators:
                    - my_app.form_login_authenticator
    access_control:
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%uri_scheme%' }
```

My custom UserProvider implements UserProviderInterface with loadUserByUsername, refreshUser and supportClass methods.

My User class implements AdvancedUserInterface, EquatableInterface, \Serializable with serialize, unserialize and isEqualTo methods.

I checked all of those methods based on documentation and cannot solve the issue.
