### ISSUE TITLE
Cannot use a custom UserPasswordEncoder

### ISSUE THREAD

**Issue by LucaGallinari** [symfony/symfony#36703]
**Symfony version(s) affected**: 4.4

**Description**  
I am trying to implement a custom UserPasswordEncoder (https://symfony.com/doc/4.4/security/named_encoders.html) that extends the MessageDigestPasswordEncoder in order to override the mergePasswordAndSalt method. But my custom class is ignored. See the "Additional context" section below for more info.

**How to reproduce** 
The user has "App\Encoder\MyPasswordEncoder" as "encoder_name" value on DB.

config/packages/security.yaml
```
security:
    encoders:
        myencoder:
            class: App\Encoder\MyPasswordEncoder
            algorithm: md5
            hash_algorithm: md5
            encode_as_base64: false
            iterations: 1
```

src/Encoder/MyPasswordEncoder.php
```
class MyPasswordEncoder extends MessageDigestPasswordEncoder
{
    protected function mergePasswordAndSalt($password, $salt)
    {
        if (empty($salt)) {
            return $password;
        }
        return $salt . $password;
    }

    protected function demergePasswordAndSalt($mergedPasswordSalt)
    {
        throw new \LogicException('It\'s not possible to demerge password and salt with this Encoder.');
    }
}
```

**Possible Solution**  
...

**Additional context**  
The new encoder is properly loaded from configuration as i can see by debugging the  EncoderFactory class but eventually the "getEncoderConfigFromAlgorithm" method will always return an array with "MessageDigestPasswordEncoder" FQCN as "class" value (https://github.com/symfony/security/blob/4.4/Core/Encoder/EncoderFactory.php#L205), and not my custom class FQCN. So the "createEncoder" method will create a new instance of "MessageDigestPasswordEncoder" instead of mine at this line:
https://github.com/symfony/security/blob/4.4/Core/Encoder/EncoderFactory.php#L81

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by LucaGallinari** [comment]
Nevermind, i was using a wrong configuration. In order to use your custom class you need to specify the FQCN of the encoder as "id" in the encoder config.
So the security.yaml file will have:

```
security:
    encoders:
        myencoder:
            id: App\Encoder\MyPasswordEncoder
```

And in the services.yaml i define the new encoder as a service if i want to pass some arguments:
```
services:
    App\Encoder\MyPasswordEncoder:
        arguments: ....
```

The user must have "myencoder" as "encoder_name" value on DB.
