### ISSUE TITLE
_instanceof: Not setting public to true from yaml-config

### ISSUE THREAD

**Issue by andreknieriem** [symfony/symfony#36782]
**Symfony version(s) affected**: 4.4.0

**Description**  
I've added the _instanceof: key in my services.yaml and added to one interface a tag and public:true. The Tag get's added when I look at bin/console debug:container 'Classname' but public is set to false. I've asked in the slack channel and they think, my config should work. So I believe it is a bug. 

**How to reproduce**  
Add in the default services.yaml an _instanceof with for example:

```yaml
services:
     _defaults:
        autowire: true      
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}' 

  _instanceof:
        App\Test\Service\TestInterface:
            public: true
            tags: ['test.testtest']
```

Now the service gets the tag but public is no.
