### ISSUE TITLE
CSRF exception for LogoutListener Firewall isn't handled

### ISSUE THREAD

**Issue by davispuh** [symfony/symfony#36814]
**Symfony version(s) affected**: v5.0.8 (and git master)

**Description**  
Currently when you use CSRF validation for logout then when invalid CSRF is submitted HTTP 500 will be returned and exception logged.
But this isn't correct because maybe user has wrong state (in which case we should inform them to refresh token) or even if it's attacker then we don't care about it (it's not server error, so HTTP 500 is wrong) as it's expected behavior.

**How to reproduce**  

In `security.yaml`
```yaml
security:
    firewalls:
        main:
            logout:
                path: logout
                csrf_token_generator: security.csrf.token_manager
```
Then make request to logout with wrong CSRF token.

**Possible Solution**  
In Firewall `ExceptionListener` there is `handleLogoutException` it could check if it's CSRF exception and set response to redirect.

**Additional context**  

Log
```
May 13 23:41:32 |INFO | PHP    A LogoutException was thrown. 
May 13 23:41:32 |ERROR| PHP    Uncaught PHP Exception Symfony\Component\Security\Core\Exception\LogoutException: "Invalid CSRF token." at /mnt/code/proj/vendor/symfony/security-http/Firewall/LogoutListener.php line 89 
```

**Comment by davispuh** [comment]
Currently I'm using this workaround:

In `services.yaml`
```yaml
services:
    App\Listener\LogoutListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
```

`App\Listener\LogoutListener`:
```php
<?php

namespace App\Listener;

use Symfony\Component\HttpKernel\Event\ExceptionEvent;
use Symfony\Component\Security\Core\Exception\LogoutException;
use Symfony\Component\HttpFoundation\RedirectResponse;

class LogoutListener
{
    public function onKernelException(ExceptionEvent $event)
    {
        $exception = $event->getThrowable();
        do {
            if ($exception instanceof LogoutException) {
                $this->handleLogoutException($event, $exception);
                return;
            }
        } while (null !== $exception = $exception->getPrevious());
    }

    private function handleLogoutException(ExceptionEvent $event, LogoutException $exception): void
    {
        // CSRF errors are normal so for those we just redirect page
        if ($exception->getMessage() !== 'Invalid CSRF token.') {
            return;
        }

        try {
            $event->setResponse(new RedirectResponse('/'));
            $event->allowCustomResponseCode();
        } catch (\Exception $e) {
            $event->setThrowable($e);
        }
    }
}
```
