### ISSUE TITLE
_instanceof vs registerForAutoconfiguration - different behavior

### ISSUE THREAD

**Issue by tebaly** [symfony/symfony#36827]
**Symfony version(s) affected**: 4.4.8

**Description**  

In the bundle settings:
```yaml
services:
  _defaults:
    autowire: true 
    autoconfigure: true 

  _instanceof:
    Vendor\SomeBundle\Services\SomeInterface:
      tags: ['some_tag']
```
I tried to do so. To automatically add a tag to **application services** using the specified interface. By loading a Yaml `services` file **inside a bundle**.

This did not work. The tag is not configured. Then I tried in the same place - in DI, configure extensions through the method `registerForAutoconfiguration` (the code is the same, only this method was added):

```php
    public function load(array $configs, ContainerBuilder $container)
    {
        $container->registerForAutoconfiguration(SomeInterface::class)
            ->addTag('some_tag'); // only this string was added
        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__ . '/../Resources/config'));
        $loader->load('services.yaml');
    }
```
Auto configuration(`autoconfigure: true`) is also set in the application setup level.

Now the tag has appeared. But the service remains private (by default).

This does not work:

```yaml
  _instanceof:
    Vendor\SomeBundle\Services\SomeInterface:
      tags: ['some_tag']
      private: false
      public: true
```

```php
        $container->registerForAutoconfiguration(SomeInterface::class)
            ->addTag('some_tag')
            ->setPrivate(false)
            ->setPublic(true); 
```

**How to reproduce**  

**Possible Solution**  

Only setup inside the code works.
```php
    public function process(ContainerBuilder $container)
    {
        foreach ($container->findTaggedServiceIds('some_tag') as $serviceId => $tags) {
            $container->getDefinition($serviceId)->setPublic(true);
        }
    }
```
**Additional context**  

There is not a word in the documentation about this behavior. Maybe this is a bug.
PS: Maybe the error is that it works?
