### ISSUE TITLE
Definition of a service affects another one

### ISSUE THREAD

**Issue by Nommyde** [symfony/symfony#36841]
**Symfony version(s) affected**: 5.0.8

**Description**  
I've added a custom serializer with a static factory. It uses another datetime format. Now default serializer implicitly switched to the new format too. I know, that I can disable autoconfiguration of the new service, but I think even in autoconfiguraion mode it shouldn't affect existing service or there should be some warnning.
If it is not a bug, please explain me, how it happens.

**How to reproduce**  
- install https://github.com/Nommyde/demo
- run app:problem command
- now both serializer outputs the same new format
- try to disable autoconfiguration of the new service:
```
    app.custom_serializer:
        autoconfigure: false
        class: Symfony\Component\Serializer\Serializer
        factory: ['App\SerializerFactory', 'create']

```
- now only new serializer uses new format
