### ISSUE TITLE
Encore manifest.json, assets package base_path

### ISSUE THREAD

**Issue by plashenkov** [symfony/symfony#36844]
**Symfony version**:
5.0.7

**Description**  
`assets.packages.base_path` is not used with `json_manifest_path`.

For example, this is my `manifest.json`:
```json
{
  "build/admin/admin.js": "/build/admin/admin.b991d27f.js",
  "build/admin/runtime.js": "/build/admin/runtime.2dd405e4.js"
}
```
This is my `assets.yaml`:
```yaml
framework:
    assets:
        packages:
            admin:
                base_path: /build/admin
                json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'

```
When I call `asset()` function from Twig, omitting the `base_path` prefix, `manifest.json` is ignored:

```twig
<!-- Twig: -->
<script src="{{ asset('admin.js', 'admin') }}"></script>

<!-- I expect (please note the b991d27f postfix): -->
<script src="/build/admin/admin.b991d27f.js"></script>

<!-- I really get: -->
<script src="/build/admin/admin.js"></script>
```

If to provide full path to `asset()` function, it renders the correct file name (with postfix).
I.e. if I want to use `manifest.json` I have to specify a full path regardless of `base_path` provided.

**Comment by GromNaN** [comment]
Is it a side effect of https://github.com/symfony/symfony/pull/35762 ?

**Comment by mzzovko** [comment]
Confirming this happens in 5.1.3

`config/packages/assets.yaml`

```
framework:
    assets:
        base_path: '/build'
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
```

`config/packages/prod/assets.yaml`

```
framework:
  assets:
    base_path: '/dist'
    json_manifest_path: '%kernel.project_dir%/public/dist/manifest.json'
```

`public/dist/manifest.json` - trimmed for readability
```
{
  ...,
  "dist/icons/apple-icon-180x180.png": "/dist/icons/apple-icon-180x180.7927522e.png",
  "dist/icons/apple-icon-57x57.png": "/dist/icons/apple-icon-57x57.4699adf7.png",
  "dist/icons/apple-icon-60x60.png": "/dist/icons/apple-icon-60x60.c013af87.png",
  ...
}
```
We use different asset folders for prod & dev, and after I've added different base_path for dev & prod (code above), in prod env version is not added to path (it seems that it only applies base_path but not version), in dev mode everything works, because there is no version, so there isnt problem.

example
`<link rel="apple-touch-icon" sizes="57x57" href="{{ asset('icons/apple-icon-57x57.png') }}">`
in prod env returns
`<link rel="apple-touch-icon" sizes="57x57" href="/dist/icons/apple-icon-57x57.png">`

and I expect 
`<link rel="apple-touch-icon" sizes="57x57" href="/dist/icons/apple-icon-57x57.4699adf7.png">`
