### ISSUE TITLE
[EventDispatcher] Register listener for security.interactive_login omitting the event name

### ISSUE THREAD

**Issue by reanim8ed** [symfony/symfony#36840]
**Symfony version(s) affected**: 4.4.5

**Description**  
If the kernel.event_listener tag doesn't define event, the method whose name is on + CamelCased event name should be executed. Tried it with `security.interactive_login` but it doesnt work.

**How to reproduce**  
1. Register all event listeners at once with:
```
services:
    App\EventListener\:
        resource: ../src/EventListener/*
        tags: [kernel.event_listener]
```
2. Create new listener class
3. If method `__invoke` is used - listener is executed correctly:
```
public function __invoke(InteractiveLoginEvent $event): void
{
   // code to execute
}
```
4. Should be working the same with `onSecurityInteractiveLogin` method name too.

**Additional context**  
Related to pull request: [33851](https://github.com/symfony/symfony/pull/33851)
