### ISSUE TITLE
[DX][Mailer] Simplify the feature to send emails to some address in dev environment

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#36877]
**Description**  
This nice option is very useful while working with emails in `dev`.

**In Symfony 4.2 and earlier** versions, you enabled it as follows:

```yaml
# config/packages/dev/swiftmailer.yaml
swiftmailer:
    delivery_addresses: ['someone@example.com']
```

**In Symfony 4.3 and newer**, using the new Mailer, you enable it as follows:

```yaml
# config/services_dev.yaml
services:
    mailer.dev.set_recipients:
        class: Symfony\Component\Mailer\EventListener\EnvelopeListener
        tags: ['kernel.event_subscriber']
        arguments:
            $sender: null
            $recipients: ['someone@example.com']
```

If technically possible, could we please make this feature as beautiful and simple as before? Thanks!
