### ISSUE TITLE
Wrong not authenticated response on tests with symfony Guard

### ISSUE THREAD

**Issue by soullivaneuh** [symfony/symfony#36955]
**Symfony version(s) affected**: 4.4.8

**Description**  

With my custom security guard, I end with this expected 401 response:

```
❯ http localhost:32776/api/user "accept: application/json"
HTTP/1.1 200 OK
Cache-Control: no-cache, private
Connection: keep-alive
Content-Type: application/json
Date: Mon, 25 May 2020 12:17:03 GMT
ETag: "c18f518eb0bd099e597cd03fe7724f79"
Server: nginx/1.17.10
Transfer-Encoding: chunked
Vary: Accept
X-Debug-Token: ed5c03
X-Debug-Token-Link: http://localhost:32776/_profiler/ed5c03
X-Powered-By: PHP/7.4.3
X-Robots-Tag: noindex

{
    "error": "invalid_grant",
    "error_description": "Authentication Required"
}
```

But on a web test case, the request response is not the same: It's a 200 status code containing: `A Token was not found in the TokenStorage.`

**How to reproduce**  

Here is the related `ApiKeyAuthenticator` class:

```php
namespace App\Security\Guard;

use AppBundle\Manager\ApiKeyManager;
use FOS\OAuthServerBundle\Model\AccessTokenManagerInterface;
use Lexik\Bundle\JWTAuthenticationBundle\Exception\JWTDecodeFailureException;
use Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken;
use Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Guard\AbstractGuardAuthenticator;

/**
 * Handles oauth, JWT and simple private tokens.
 */
class ApiKeyAuthenticator extends AbstractGuardAuthenticator
{
    private const HEADER_NAME = 'Authorization';
    private const KEY_PREFIX = 'Bearer';
    private const KEY_REGEX = '/^'.self::KEY_PREFIX.'\s+([a-zA-Z0-9]+)$/';

    /**
     * @var ApiKeyManager
     */
    private $apiKeyManager;

    /**
     * @var AccessTokenManagerInterface
     */
    private $accessTokenManager;

    /**
     * @var JWTTokenManagerInterface
     */
    private $JWTTokenManager;

    public function __construct(ApiKeyManager $apiKeyManager, AccessTokenManagerInterface $accessTokenManager, JWTTokenManagerInterface $JWTTokenManager)
    {
        $this->apiKeyManager = $apiKeyManager;
        $this->accessTokenManager = $accessTokenManager;
        $this->JWTTokenManager = $JWTTokenManager;
    }

    /**
     * {@inheritdoc}
     */
    public function supports(Request $request): bool
    {
        return (bool) \preg_match(
            self::KEY_REGEX,
            \trim($request->headers->get(self::HEADER_NAME, '')),
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getCredentials(Request $request)
    {
        if ((bool) \preg_match(
                self::KEY_REGEX,
                \trim($request->headers->get(self::HEADER_NAME, '')),
                $matches
            )) {
            return $matches[1];
        }

        throw new \LogicException('The header should be correctly set at this point.');
    }

    /**
     * {@inheritdoc}
     */
    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        // FOSOAuth system
        $token = $this->accessTokenManager->findTokenByToken($credentials);

        if ($token !== null) {
            return $token->getUser();
        }

        // JWT system
        try {
            $jwtToken = new JWTUserToken();
            $jwtToken->setRawToken($credentials);
            $payload = $this->JWTTokenManager->decode($jwtToken);

            if (\is_array($payload) && isset($payload['username'])) {
                return $payload['username'];
            }
        } catch (JWTDecodeFailureException $e) {
        }

        // Private key system
        return $this->apiKeyManager->getUserForToken($credentials);
    }

    /**
     * {@inheritdoc}
     */
    public function checkCredentials($credentials, UserInterface $user)
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        return new JsonResponse([
            'error' => 'invalid_grant',
            'error_description' => 'Invalid or malformed token. Should be "'.self::HEADER_NAME.': '.self::KEY_PREFIX.' your_token"',
        ], Response::HTTP_UNAUTHORIZED);
    }

    public function start(Request $request, ?AuthenticationException $authException = null)
    {
        return new JsonResponse([
            'error' => 'invalid_grant',
            'error_description' => 'Authentication Required',
        ]);
    }

    public function supportsRememberMe()
    {
        return false;
    }
}
```

Its implementation on the `security.yaml` file (`api` firewall):

```yaml
security:
  # ...
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|error|trans)|css|images|js)/
      security: false

    open:
      pattern: ^/(misc|\.well-known)/
      security: false

    oauth_token:
      pattern: ^/oauth/v2/token
      security: false

    login:
      pattern: ^/jwt/login
      stateless: true
      anonymous: true
      form_login:
        check_path: /jwt/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false

    api:
      pattern: ^/api/(?!docs(\.[a-z]+)?$)
      stateless: true
      guard:
        authenticators:
          - App\Security\Guard\ApiKeyAuthenticator

    main:
      pattern: ^/
      entry_point: App\Security\EntryPoint\FormAuthenticationEntryPoint
      form_login:
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
        login_path: /login
        check_path: /login_check
      two_factor:
        auth_form_path: 2fa_login
        check_path: 2fa_login_check
      anonymous: ~
      logout:
        path: /logout
      switch_user:
        parameter: "%switch_user_parameter%"

    # ...
```

And then the test: 

```php
namespace Tests\AppBundle\Controller\Api;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

final class ApiControllerTest extends WebTestCase
{
    public function testNoTokenIsInvalid(): void
    {
        $client = self::createClient();
        $client->request('GET', '/api/user');
        $this->assertSame(401, $client->getResponse()->getStatusCode());
    }
}
```

**Possible Solution**  

**Additional context**
