### ISSUE TITLE
[Messenger] Provides a safe single handler strategy

### ISSUE THREAD

**Issue by gquemener** [symfony/symfony#36958]
**Description**  
(This discussion is following https://github.com/symfony/symfony/pull/29167)

Single handler strategy is common when using a command bus (as a command should be handled by one and only one handler).
Currently, the only way to enforce this strategy is through the [`HandleTrait`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/HandleTrait.php) which performs the check **after** the message has been handled (which can have harmful consequences).

I propose to implement a safe (meaning that prevents any handler to be called) check.
Once this is implemented, I don't see any reason to keep the `HandleTrait`.

So far, I see a few ways to achieve that.

## Add a `allowMultipleHandlers` flag to the `HandleMessageMiddleware`. 
Then it would be a matter of 
```php
        $handlers = $this->handlersLocator->getHandlers($envelope);
        if (!$this->allowMultipleHandlers && count($handlers) > 1) {
            throw new TooManyHandlersForMessageException(sprintf('Too many handlers are registered for message "%s".', $context['class']));
        }
        foreach ($handlers as $handlerDescriptor) {
```
This flag should be `true` by default to be BC.

## Add a new implementation of `HandlersLocatorInterface`
This implementation would throw an exception when more than one handler is located. The correct implementation would most likelly be injected through the `MessengerPass` or the  `FrameworkExtension`.

## Add the check during compilation
The check could even live in the `MessengerPass` or the `FrameworkExtension` itself. The drawback is that this would couple it with the framework and prevent single handler strategy to be used without the framework.

**Comment by gquemener** [comment]
Here's an implementation example that follows the idea behind the second option : https://github.com/prooph/service-bus/blob/master/src/Plugin/Router/SingleHandlerRouter.php.

The only difference is that it does not throw an exception, but instead provides the latest defined handler for a message (by overriding and existing value).

**Comment by ogizanagi** [comment]
> Once this is implemented, I don't see any reason to keep the HandleTrait.

The `HandleTrait` exists in order to ease implementing query buses as well, thus accessing the handler returned value. Ensuring there is only one result, meaning one handler responded, is a consequence of the desire to access a single result.

Regarding this feature request, as we probably want to detect the issue as soon as possible, I'd recommend performing the check during compilation. But if we go here, the same kind of feature should be available to check messages have at least one handler as well, while this is only checked at runtime right now (in the middleware).

**Comment by gquemener** [comment]
> The HandleTrait exists in order to ease implementing query buses as well, thus accessing the handler returned value. Ensuring there is only one result, meaning one handler responded, is a consequence of the desire to access a single result.

I see, it does make sense indeed. However, I'd probably rather have this piece of code live within my codebase, rather than vendor, but that's up to anyone I guess.

In the end, I would be in favor of both having these checks within the component (to be able to use it as a standalone component and raise errors at runtime) and to have some integrations through the Framework bundle (to early detect errors through compilation).

If I had to pick one, then I would personally prefer the runtime check.

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by gquemener** [comment]
Indeed dear bot, I haven't use symfony/messenger as a command bus for a while.
Is there any news @ogizanagi ?

**Comment by ogizanagi** [comment]
No, nothing has been contributed in this regard from what I know.

**Comment by gquemener** [comment]
Ok, I'll just leave some notes here for my future self:

Consider defining a command bus as follow:
```yaml
framework:
    messenger:
        # The bus that is going to be injected when injecting MessageBusInterface
        default_bus: command.bus
        buses:
            command.bus:
                default_middleware: exactly_one_handler # That part is new
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
```
