### ISSUE TITLE
Importing routes with wildcard (Glob pattern) behaves differently than if there are none

### ISSUE THREAD

**Issue by esynaps** [symfony/symfony#37006]
**Symfony version(s) affected**: 5.0.8

**Description**  

Importing routes with wildcard behaves differently than if there are none

**How to reproduce**  

```
api:
    resource: ../../src/Api/Controller/
    type: annotation

resources_v1:
    resource: ../../src/Resources/V1/**/Controller/
    type: annotation
    prefix: /v1/
```

![image](https://user-images.githubusercontent.com/30432290/83259914-2df0d100-a1b9-11ea-9586-7f510461a079.png)

I expect these 2 routes declared in controller "\App\Resources\V1\User\Controller\UsersController" to be listed but this is not the case :
"app_resources_v1_user_users_find"
"app_resources_v1_user_users_update"
<del>"app_api_documentation_documentation"</del>
<del>"app_api_documentation_operations"</del>

**Possible Solution**  

Add a wildcard at the end of the resource path

```
api:
    resource: ../../src/Api/Controller/
    type: annotation

resources_v1:
    resource: ../../src/Resources/V1/**/Controller/*
    type: annotation
    prefix: /v1/
```

![image](https://user-images.githubusercontent.com/30432290/83259867-20d3e200-a1b9-11ea-89a3-b2f81771d634.png)
