### ISSUE TITLE
[Validator] Inform developer if componant is missing

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#37012]
**Symfony version(s) affected**: 5.0.8

**Description**  
I started a new Symfony 5 project and I wanted to enable the [automatic validation](https://symfony.com/blog/new-in-symfony-4-3-automatic-validation) feature in my validator config file:

``` yaml
framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        auto_mapping:
            App\Entity\: []
```

But automatic validation was not working after that.
This was because as mentioned in [the blog post](https://symfony.com/blog/new-in-symfony-4-3-automatic-validation), this feature require `PropertyInfo` component to work.

Maybe we should trigger an exception to informed the developer if this option is enabled but the component is not installed?
