### ISSUE TITLE
Yaml::parse() error on double single quote - malformed inline string

### ISSUE THREAD

**Issue by palomamtnez** [symfony/symfony#37037]
**Symfony version(s) affected**:   "symfony/yaml": "^5.0"

**Description**  
I get an error when trying to parse a Yaml file with the function Yaml::parse()
My file contains this text:

 ```
entries:
  - message: 'No emails received before timeout - Address: ''test@testemail.company.com''
        Keyword: ''Your Order confirmation'' ttl: 50'
    outcome: failed
```

And this is the error message:

```
Malformed inline YAML string: "'No emails received before timeout - Address: ''test@testemail.company.com''" at line 149 (near "message: 'No emails received before timeout - Address: ''test@testemail.company.com''")..
```

Does anyone has any ideas of how to solve this? 
Thank you
