### ISSUE TITLE
[MonologBridge] There is no handler class defined for handler "mailer"

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#37043]
**Symfony version(s) affected**: 5.1.0

**Description**  
In the latest post about 5.1improvements (https://symfony.com/blog/new-in-symfony-5-1-misc-improvements-part-3#mailer-log-handler) it said that there is a MailerHandler for symony mailer. Just like swiftmailerhandler to send logs via email. The class exists (https://github.com/symfony/symfony/blob/5.1/src/Symfony/Bridge/Monolog/Handler/MailerHandler.php) but when I try to use it it sais:

> Fatal error: Uncaught InvalidArgumentException: There is no handler class defined for handler "mailer". in /var/www/html/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php:976

**How to reproduce**  
with config
```yaml
monolog:
    handlers:
        email:
#            type: swift_mailer # works
            type: mailer # doesn't work :(
            content_type: text/html
            from_email: 'from@email.com'
            to_email: 'to@email.com'
            subject: 'Exception %%message%%'
            level: debug
            formatter: monolog.formatter.html
```

**Possible Solution**  
Add mailer to the MonologExtension::getHandlerClassByType method
