### ISSUE TITLE
[Messenger] There are not way to disable use_notify

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#37070]
**Symfony version(s) affected**: 5.0.1

**Description**  
use_notify cause some troubles #37069 and #37067 so I wanted to disable it and I can not find a way to disable it.

I have try 
```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: 'pdo_mysql://%database_user%:%database_password%@%database_host%/%database_name%?use_notify=false'
```

and also:
```yaml
framework:
    messenger:
        transports:
            failed: "doctrine://default?queue_name=failed&use_notify=false"
```

But the value is always `true`

And this feature is not documented 

cc @dunglas

**Comment by alexismarquis** [comment]
You can disable it this way : 
```yaml
framework:
    messenger:
        transports:
            failed:
                dsn: '[DSN]'
                options:
                    use_notify: false
```
