### ISSUE TITLE
Authentication request could not be processed due to a system problem due to user entity not in default_entity_manager

### ISSUE THREAD

**Issue by starcodeconqueror** [symfony/symfony#37080]
**Symfony version(s) affected**: 5.0.x

**Description**  

error : Authentication request could not be processed due to a system problem
raise when user entity not in default entity manager

in this case may user entity is in secondary entity manager

**How to reproduce**  

doctrine.yaml
```yaml
orm:
        auto_generate_proxy_classes: false
        default_entity_manager: main
        entity_managers:
            main:
                connection: main
                mappings:
                    Frtnde:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main\'
                        alias: Main
            secondary:
                connection: secondary
                mappings:
                    Frrbac:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Secondary'
                        prefix: 'App\Entity\Secondary\'
                        alias: Secondary  
```

**Possible Solution**  

will raise error
```        
default_entity_manager: main
```

change to make it work
```        
default_entity_manager: secondary
```

**Additional context**  

```log
security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): The class 'App\\Entity\\Secondary\\Users' was not found in the chain configured namespaces App\\Entity\\Main\\ at /Users/johndoe/Sites/symfony-api-platform/vendor/symfony/security-core/Authentication/Provider/DaoAuthenticationProvider.php:96)\n[previous exception] [object] (Doctrine\\Persistence\\Mapping\\MappingException(code: 0): The class 'App\\Entity\\Secondary\\Users' was not found in the chain configured namespaces App\\Entity\\Main\\ at /Users/johndoe/Sites/symfony-api-platform/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/MappingException.php:23)"} []
```
