### ISSUE TITLE
AbstractGuardAuthenticator / supports give full access to user if false returned

### ISSUE THREAD

**Issue by rehoehle** [symfony/symfony#37135]
**Symfony version(s) affected**: 4.4.9

**Description**  
AbstractGuardAuthenticator not working as expected. When supports return "true" or "null" user has automatically full access

**How to reproduce**  
```
public function supports(Request $request) {
    return true; // Working
    return false; // Not working
    return $request->headers->has('X-AUTH-TOKEN'); // not working
}
```
```
api:
    host: "%host_api%"

    guard:
         authenticators:
               - App\Security\TokenAuthenticator
```

So when the `X-AUTH-TOKEN` is not set the user has automatically full access. The problem appeared after the last composer update to 4.4.9. 

And normally you got "Authentication required" that isn't called anymore. So there is something really strange. I get only "User not found" because that function is called.
