### ISSUE TITLE
check for parameter type in BaseNode.php seems to do wrong in %env(...)%

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony#37173]
**Symfony version(s) affected**: 4.4, 5.0.8

**Description** 

When using `%env(default:...)` in the config, I get a failure.
```
Invalid type for path "framework.session.cookie_path". Expected one of "bool", "int", "float", "string", but got one of "bool", "int", "float", "string", "array ". 
```
First, I do not understand the message. Which type was passed? All of this 5 at once? Possibly all of this 5?
Second, I disagree that this is a failure. The value is a string, which is allowed (checked with dumping the parameter value).

**How to reproduce**  
(you may create a new app with "symfony new" for this, or use any existing)
add this in config/packages/framework.yaml:
```yaml
parameters:
    router.request_context.base_url: /
    testing_router_request_baseurl: '%router.request_context.base_url%' # parameters with . can be used in %env(default:...)% only after sy5.1
    testing_cookie_path: '%env(default:testing_router_request_baseurl:resolve:COOKIE_PATH)%'

framework:
    session:
        cookie_path: '%testing_cookie_path%'
```

```console
$ bin/console xxx # v4.4
In BaseNode.php line 544:
                                                                                                                                                                    
  Invalid type for path "framework.session.cookie_path". Expected one of "bool", "int", "float", "string", but got one of "bool", "int", "float", "string", "array ". 
```

When commenting out `framework:cookie_path` and dumping `testing_cookie_path`, I see it is "/" (of type string) as expected.

**Possible Solution**  
At least improve the text of the error message.

**Additional context**
