### ISSUE TITLE
[DependencyInjection] Manually Wiring Arguments does not work when service id is not class name

### ISSUE THREAD

**Issue by jaredm4** [symfony/symfony#37274]
**Symfony version(s) affected**: symfony/dependency-injection 5.1.1

**Description**  
When using autowiring, a custom service id, and defining the class name specifically in the definition, wired scalar arguments aren't handled.

**How to reproduce**  
```yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Foo\:
    resource: './src/*'

  custom.service.id:
    class: Foo\MyClass
    arguments:
      $someScalar: 'custom message'
```
```php
$foo = $container->get('custom.service.id');
echo $foo->getScalar().PHP_EOL;
```
**Expected**
`custom message`
**Actual**
`Cannot autowire service "Foo\MyClass": argument "$someScalar" of method "__construct()" has no type-hint, you should configure its value explicitly.`

**Possible Solution**  
Manually wired scalars should be handled regardless if using a custom service ID or the class name as the service ID.
Also of interest, these 2 kludges can get it to work:
kludge 1: Disable default autowiring and set it on the service itself. Not a great solution.
```yaml
services:
  _defaults:
#    autowire: true
    autoconfigure: true
    public: true

  Foo\:
    resource: './src/*'

  custom.service.id:
    class: Foo\MyClass
    # Only works if autowire is NOT set in _defaults
    autowire: true
    arguments:
      $someScalar: 'custom message'
```
kludge 2: ALSO define the original class and let it autowire. Then both services work and have different scalar values.
```yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Foo\:
    resource: './src/*'

  custom.service.id:
    class: Foo\MyClass
    arguments:
      $someScalar: 'custom message'
  Foo\MyClass:
    arguments:
      $someScalar: 'hello world'
```
```php
$foo = $container->get('custom.service.id');
echo $foo->getScalar().PHP_EOL;
$foo = $container->get('Foo\MyClass');
echo $foo->getScalar().PHP_EOL;
```
```
$ php foo.php
custom message
hello world
```
**Additional context**  
Here's all the files I used to repro outside of my existing project.
composer.json:
```json
{
  "require": {
    "php": "^7.4",
    "symfony/dependency-injection": "^5.1",
    "symfony/config": "^5.0",
    "symfony/yaml": "^5.0"
  },
  "autoload": {
    "psr-4": {"Foo\\": "src/"}
  }
}
```
services.yaml:
```yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Foo\:
    resource: './src/*'

  custom.service.id:
    class: Foo\MyClass
    arguments:
      $someScalar: 'custom message'
```
foo.php:
```php
<?php

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

require __DIR__.'/vendor/autoload.php';

// Create the container
$container = new ContainerBuilder();
$loader = new YamlFileLoader($container, new FileLocator(__DIR__));
$loader->load('services.yaml');
$container->compile();

$foo = $container->get('custom.service.id');
echo $foo->getScalar().PHP_EOL;
```
src/MyClass.php
```php
<?php

namespace Foo;

class MyClass
{
    private ?string $someScalar;

    public function __construct($someScalar)
    {
        $this->someScalar = $someScalar;
    }
    public function getScalar()
    {
        return $this->someScalar;
    }
}
```

**Comment by jaredm4** [comment]
I think I just realized what's happening. The config and yaml loader are trying to load up not only custom.service.id, but also the original Foo/MyClass. This is why it works if I tell it to not globally autowire. Now that I understand why it's behaving that way, at least I can find a solution to the right problem. Disregard this ticket. :)

**Comment by xabbuh** [comment]
When using PSR-4 resources, you can exclude files or directories like this:

```yaml
services:
  _defaults:
    autoconfigure: true
    public: true

  Foo\:
    resource: './src/*'
    exclude: 'src/MyClass.php'
```
