### ISSUE TITLE
Service "security.logout.listener.cookie_clearing.web" must implement interface "Symfony\Component\EventDispatcher\EventSubscriberInterface".

### ISSUE THREAD

**Issue by leevigraham** [symfony/symfony#37282]
**Symfony version(s) affected**: 5.1.1

**Description**  

Adding `delete_cookies` to a firewall throws and error: `Service "security.logout.listener.cookie_clearing.web" must implement interface "Symfony\Component\EventDispatcher\EventSubscriberInterface".`

I believe this is becuase `vendor/symfony/security-http/Logout/CookieClearingLogoutHandler.php` does not implement `EventSubscriberInterface`

**How to reproduce**  

Reproduction: https://github.com/leevigraham/symonfy_delete_cookies_bug

1. Create a new skeleton app with the security component
```
composer create-project symfony/skeleton bug_app
cd bug_app
composer require symfony/security-bundle
```

2. Add delete_cookies to the firewall config

```
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users_in_memory
            logout:
                delete_cookies:
                    jwtSig: { path: null, domain: null }
                    jwtPayload: { path: null, domain: null }

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
```

3. Run `bin/console cache:clear`

**Additional context**  

![image](https://user-images.githubusercontent.com/25124/84611913-7111aa80-af02-11ea-871e-319b64ab27cf.png)

![image](https://user-images.githubusercontent.com/25124/84611923-75d65e80-af02-11ea-8fac-2b7cb544e119.png)
