### ISSUE TITLE
[Messenger] Support SQS Transport with QueueUrl as DSN

### ISSUE THREAD

**Issue by starred-gijs** [symfony/symfony#37305]
**Description**  
The Amazon SQS Transport now only supports a DSN that starts with `sqs://`, 
but especially with CloudFormation the QueueUrl could be provided as an environment variable.

See https://github.com/brefphp/symfony-messenger/pull/30#issuecomment-644228492

**Example** 
```
MESSENGER_TRANSPORT_DSN=https://sqs.us-east-2.amazonaws.com/123456789012/ab1-MyQueue-A2BCDEF3GHI4
```

**Comment by mnapoli** [comment]
To expand on this, this is very valuable when creating serverless applications via `serverless.yml` or any kind of "Infrastructure as Code" tool.

Here is an example where we can very simply put the queue URL returned by SQS into an environment variable:

```yaml
provider:
    ...
    environment:
        APP_ENV: prod
        SQS_URL:
            Ref: AlertQueue

resources:
    Resources:
        AlertQueue:
            Type: AWS::SQS::Queue
```

Without that feature, we would have to transform the queue URL to match Symfony's prefix (`sqs://`), which is hard to do here.

Solving that issue would allow to merge Bref's Symfony Messenger bridge with the official SQS driver.

FYI SQS URLs are distinguishable via a prefix, this is what is done in Bref:

https://github.com/brefphp/symfony-messenger/blob/3ee64570ba6b5693052e4e8eb601ee8d2765392a/src/Service/Sqs/SqsTransportFactory.php#L29

```php
    public function supports(string $dsn, array $options): bool
    {
        return preg_match('#^https://sqs\.[\w\-]+\.amazonaws\.com/.+#', $dsn) === 1;
    }
```

**Comment by gmponos** [comment]
Can I bring another perspective here...

If I was allowed to tag a service as a Transport.. Then would I be able to initialize my SqsService with the plain URL?

AFAIK I can't tag services as transports and avoid factories.. Allowing the above.. I could declare my own connect and my own transport.. Then use it into routing..

**Comment by ck-developer** [comment]
hello I would like to share a use case 

case: 1
.env.dist
```
MESSENGER_TRANSPORT_DSN=sqs://localhost
```
config/packages/messenger.yaml
```
framework:
    messenger:
        transports:
            queue_1:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: 'queue_1'
            queue_2:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: 'queue_2'
```

in this case when I setup transport I have empty queue names.

case: 2
I think that this problem is also linked to the priority of the dsn https://github.com/symfony/symfony/issues/37293
