### ISSUE TITLE
Allow array parameters for route configuration

### ISSUE THREAD

**Issue by Khartir** [symfony/symfony#37316]
**Description**  
Symfony 5.1 added different hosts per locale (https://symfony.com/blog/new-in-symfony-5-1-different-hosts-per-locale)
This is a very nice feature, however those hosts are usually different per environment. Since route configurations are not merged, this would require to duplicate the configuration for every environment.
The solution is obviously to use a container parameter. However this also doesn't work because the parameter resolver can not handle array parameters:
https://github.com/symfony/symfony/blob/6f6e4cefe40e45a1813af6a3b8e3aeeb7a9d01c8/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L183-L193
Currently the only option is to define a parameter per locale which is not ideal.
It would be nice, if we could simply define an array parameter containing the host array.

**Example**  
I would like to do something like this:

```
# config/packages/dev/parameters.yaml
parameters:
  routing.hosts:
          en_US: example.com
          de_DE: example.de
```

```
# config/routes/annotations.yaml
controllers:
  resource: '../../src/Controller/'
  type: annotation
  host: '%routing.hosts%'
```
However, this currently throws an exception: `The container parameter "routing.hosts", used in the route configuration value "%routing.hosts%", must be a string or numeric, but it is of type "array".`
