### ISSUE TITLE
[Cache] 4.4.3 to 4.4.4 upgrade igbinary_unserialize_header: unsupported version

### ISSUE THREAD

**Issue by raalderink** [symfony/symfony#37390]
**Symfony version(s) affected**: 4.4.4+

**Description**  
After upgrading to Symfony Cache 4.4.4 or 4.4.5, we are getting the following error:
```
Warning: igbinary_unserialize_header: unsupported version: 83886080, should be 1 or 2 (wrong endianness?)
Warning: igbinary_unserialize_header: unsupported version: 100663296, should be 1 or 2 (wrong endianness?)
```
This did not happen before the upgrade, but is consistent after upgrading. We're having trouble figuring out why this issue happens exactly, as our server configuration has not changed, and we're only updating the package.

Our igbinary config is as such:
```
igbinary support => enabled
igbinary version => 3.1.2
igbinary APCu serializer ABI => 0
igbinary session support => yes
igbinary.compact_strings => On => On
Available serializers => php, json, igbinary, msgpack
Registered serializer handlers => php_serialize php php_binary igbinary msgpack
```

The error comes up with just doing a getItem:
```
$cacheItem = $this->cache->getItem('cache key');
```

**Comment by nicolas-grekas** [comment]
Just looking at the version numbers, this might be related to #35428
Can you try reverting it locally to see if this has any effect on your issue?

**Comment by raalderink** [comment]
We did revert back to 4.4.3, which solves the issue

**Comment by raalderink** [comment]
So since we reverted back to 4.4.3 and it not being an issue, whereas 4.4.4+ is an issue, we cannot upgrade the Cache component. Currently, we're on Symfony 4.4.5, and would like to have the Cache component in line with the other Symfony packages. Is there anything else we can do to troubleshoot or fix this?

**Comment by nicolas-grekas** [comment]
I'm not able to reproduce the issue. Tests pass locally.

In order to help debug the issue:
- Does this happen with an empty pool or with a pool that is already filled with values? If with a filled pool, can you try emptying it and reproduce?
- Can you provide a full reproducer I could clone and run locally?

**Comment by leongersen** [comment]
I took over this issue for us internally. The issue seems to happen when using the `TagAwareAdapter` outside of a symfony cache pool.

We had the `TagAwareAdapterInterface` wired as a service, like so:

```yaml
services:
    Symfony\Component\Cache\Adapter\RedisAdapter:
        factory: [Framework\Redis\RedisAdapterFactory, createRedisAdapter]
        arguments:
            - '%env(REDIS_URL)%'
            - '%env(REDIS_CLUSTER)%'

    Symfony\Component\Cache\Adapter\TagAwareAdapterInterface:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments:
            - '@Symfony\Component\Cache\Adapter\RedisAdapter'
            - '@Symfony\Component\Cache\Adapter\RedisAdapter'

    Psr\Cache\CacheItemPoolInterface: '@Symfony\Component\Cache\Adapter\TagAwareAdapterInterface'
```

Instead, we configured the built-in redis provider, set it for the `cache.app` pool, and had Symfony create the service to implement `TagAwareCacheInterface`. (I simplified the following a bit, we're conditionally using `\Redis` or `\RedisCluster`.)

```yaml
services:
    app.redis_provider:
        class: \RedisCluster
        factory: ['Framework\Redis\RedisProviderFactory', 'createConnection']
        arguments:
            - '%env(REDIS_URL)%'
            - '%env(REDIS_CLUSTER)%'

    Symfony\Component\Cache\Adapter\TagAwareAdapterInterface: '@Symfony\Contracts\Cache\TagAwareCacheInterface'

framework:
    cache:
        default_redis_provider: 'app.redis_provider'
        app: cache.adapter.redis
```

Deploying this change and clearing the `app.cache` pool solved this issue for us.

I think our initial setup didn't make much sense, so I'd say this issue can be closed. It is worth noting that Symfony will never clear the Redis cache when the cache components are autowired like this, and in this case the `DefaultMarshaller` (I think) doesn't come in to play to abstract away the usage of `igbinary`.
