### ISSUE TITLE
Manually Wiring Arguments doesn't work

### ISSUE THREAD

**Issue by haine-amine** [symfony/symfony#37399]
**Symfony version(s) affected**: 5.1.0

**Description**  

when i want to pass a value to a custom argument in a constructor of a custom service, this message is displayed :

`Cannot autowire service "App\Alert\Manager\AlertFileManager": argument "$alertFileManagers" of method "__construct()" has no type-hint, you should configure its value explicitly. `

**How to reproduce**  

my service.yaml

```
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Alert\Manager\AlertFileManager\:
        resource: '../src/Alert/Manager/AlertFileManager.php'
        arguments:
            $alertFileManagers: ['a', 'b', 'c']
```

constructor of AlertFileManager.php

```
public function __construct(SerializerInterface $serializer, $alertFileManagers)
    {
        $this->serializer = $serializer;
        $this->alertFileManagers = $alertFileManagers;
    }
```

**Possible Solution**  

**Additional context**
