### ISSUE TITLE
Too few arguments / Override HandleMessageMiddleware  

### ISSUE THREAD

**Issue by tamert** [symfony/symfony#37406]
**Symfony version(s) affected**: 5.0.1
php  7.2.3

**Description**  

`Too few arguments to function App\MessageHandler\LoginMessageHandler::__invoke(), 1 passed in vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php on line 63 and exactly 4 expected`

**How to reproduce**  
```yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
        routing:
          'App\Message\LoginMessage':  async
```

**Additional context**  
```php
namespace App\Message;

class LoginMessage
{
    private $user;

    public function __construct(int $user)
    {
        $this->user = $user;
    }

    public function getUser(): int
    {
        return $this->user;
    }
}
```

```php
namespace App\MessageHandler;

use App\Message\LoginMessage;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

class LoginMessageHandler implements MessageHandlerInterface
{
    public function __invoke(LoginMessage $message)
    {
       sleep(100);
    }
}
```
