### ISSUE TITLE
[Security] 5.1 Firewall\ExceptionListener constructor gets argument of wrong type

### ISSUE THREAD

**Issue by rapliandras** [symfony/symfony#37456]
**Symfony version(s) affected**: 5.1.x

**Description**  

With the new security enabled, the internal exception handling fails with type error.

> Argument 5 passed to Symfony\Component\Security\Http\Firewall\ExceptionListener::__construct() must be an instance of Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface or null, instance of App\Authenticator\JWTAuthenticator given, called in /home/andrasrapli/projects/rapliandras/jwt-symfony/var/cache/dev/ContainerLibqJJy/getSecurity_Firewall_Map_Context_MainService.php on line 38

**How to reproduce**  

Call any endpoint for which the firewall is enabled.

```
 security:
    enable_authenticator_manager: true
    firewalls:
        main:
            lazy: true
            logout: ~
            guard:
                authenticators:
                    - App\Authenticator\JWTAuthenticator
```

**Possible Solution**  

**Additional context**
