### ISSUE TITLE
why factory method is called before  the factory service regular method call invoked by addMethodCall.

### ISSUE THREAD

**Issue by videni** [symfony/symfony#37477]
# Situation

```
 ezpublish.api.storage_engine.factory:
        class: eZ\Bundle\EzPublishCoreBundle\ApiLoader\StorageEngineFactory
        arguments:
            - "@ezpublish.api.repository_configuration_provider"

    ezpublish.api.storage_engine:
        class: eZ\Publish\SPI\Persistence\Handler
        factory: ["@ezpublish.api.storage_engine.factory", buildStorageEngine]
        public: false
        
```

Add registerStorageEngine call to  ` ezpublish.api.storage_engine.factory` service with compiler pass.
```
class RegisterStorageEnginePass implements CompilerPassInterface
{
    /**
     * Performs compiler passes for persistence factories.
     *
     * Does:
     * - Registers all storage engines to ezpublish.api.storage_engine.factory
     *
     * @param \Symfony\Component\DependencyInjection\ContainerBuilder $container
     *
     * @throws \LogicException
     */
    public function process(ContainerBuilder $container)
    {
        if (!$container->hasDefinition('ezpublish.api.storage_engine.factory')) {
            return;
        }

        $storageEngineFactoryDef = $container->getDefinition('ezpublish.api.storage_engine.factory');
        foreach ($container->findTaggedServiceIds('ezpublish.storageEngine') as $id => $attributes) {
            foreach ($attributes as $attribute) {
                if (!isset($attribute['alias'])) {
                    throw new LogicException('ezpublish.storageEngine service tag needs an "alias" attribute to identify the storage engine.');
                }
                // Register the storage engine on the main storage engine factory
                $storageEngineFactoryDef->addMethodCall(
                    'registerStorageEngine',
                    [
                        new Reference($id),
                        $attribute['alias'],
                    ]
                );
            }
        }
    }
}
```

will be transformed to 
```
  <service id="ezpublish.api.storage_engine.factory" class="eZ\Bundle\EzPublishCoreBundle\ApiLoader\StorageEngineFactory">
      <argument type="service" id="ezpublish.api.repository_configuration_provider"/>
      <call method="registerStorageEngine">
        <argument type="service" id="ezpublish.spi.persistence.legacy"/>
        <argument>legacy</argument>
      </call>
    </service>
    <service id="ezpublish.api.storage_engine" class="eZ\Publish\SPI\Persistence\Handler" public="false">
      <factory service="ezpublish.api.storage_engine.factory" method="buildStorageEngine"/>
    </service>
```

The generated php code
```
 /**
     * Gets the private 'ezpublish.api.storage_engine' shared service.
     *
     * @return \eZ\Publish\SPI\Persistence\Handler
     */
    protected function getEzpublish_Api_StorageEngineService()
    {
        $a = new \eZ\Bundle\EzPublishCoreBundle\ApiLoader\StorageEngineFactory(($this->services['ezpublish.api.repository_configuration_provider'] ?? $this->getEzpublish_Api_RepositoryConfigurationProviderService()));

        $this->privates['ezpublish.api.storage_engine'] = $instance = $a->buildStorageEngine();

//this method is supposed to be called before the above line.
        $a->registerStorageEngine(($this->services['ezpublish.spi.persistence.legacy'] ?? $this->getEzpublish_Spi_Persistence_LegacyService()), 'legacy');

        return $instance;
    }
```
as you can see the `buildStorageEngine` factory method is called before method `registerStorageEngine`

# Environment 

symfony 5.1
