### ISSUE TITLE
[FrameworkBundle][Router] Unable to use a array parameter as host value

### ISSUE THREAD

**Issue by welcoMattic** [symfony/symfony#37535]
**Symfony version(s) affected**: 5.1.2

**Description**  
The `host` option under `controllers` in `annotations.yaml` can not take a array parameter as value.

**How to reproduce**  
I load dynamically either `europe.yaml` or `china.yaml` according to a environment variable in .env file.
```
// europe.yaml
parameters:
    domains:
        fr: 'www.%root_domain%'
        en: 'www.en.%root_domain%'

// china.yaml
parameters:
    domains:
        cn: 'www.cn.%root_domain%'

// annotations.yaml
controllers:
    resource: ../../src/Controller/
    type: annotation
    host:
        fr: 'www.%root_domain%'
        en: 'www.en.%root_domain%'
        cn: 'www.cn.%root_domain%'
    // host: '%domains%' => It doesn't work, it throws the following exception
```
`The container parameter "domains", used in the route configuration value "%domains%", must be a string or numeric, but it is of type "array".`
The exception is thrown by `symfony/framework-bundle/Routing/Router::resolve`, which doesn't seem to resolve array values.

**Possible Solution**  
Since `host` option accepts array as plain value (handled by HostTrait::addHost), we should be able to resolve an array parameter in Router::resolve
