### ISSUE TITLE
5.1 phpunit Name already in use

### ISSUE THREAD

**Issue by hjanuschka** [symfony/symfony#37541]
**Symfony version(s) affected**: 5.1.x

**Description**  
since upgrade to 5.1.x - tests fail.
we are using Mockery::mock to overload services

that used to work quiet well. but since 5.1 the Kernel loads the container and instaniates the service
and mockery fails to overload because it already exists

**How to reproduce**  

dependency: `"mockery/mockery": "^1.4",`

test:

```php
<?php
namespace Tests;

use \Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use \Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use KRNApiBundle\Controller\PostsController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\BrowserKit\Cookie;
use KRNAuthBundle\Security\KRNUser;
use KRN\BridgeBundle\Services\KrnBridge;
use KRN\BridgeBundle\Interfaces\KrnBridgeBrowserInterface;
use Nyholm\Psr7\Response as BuzzResponse;

use Mockery;
use Mockery\Matcher;

/**
 * @runInSeparateProcess
 * @preserveGlobalState disabled
 */
class BridgeStub implements KrnBridgeBrowserInterface
{
    const API_ENDPOINT_POSTS_PAGE = "posts/page";
    public function get(string $url, array $headers = array())
    {
    }
}

/**
 * @runTestsInSeparateProcesses
 */

class Article extends WebTestCase
{
    private $client = null;
    protected function setUp(): void
    {
       
        if (null === $this->client) {
            $this->client = static::createClient();
        }


    }
    protected function tearDown(): void
    {
        $this->client->restart();
        Mockery::close();
    }


    /**
     * @test
     * @preserveGlobalState disabled
     */
    public function testArticle()
    {

        # MOCKED KRN/API Response
        $mocked_resp = new BuzzResponse(
            200,
            ["Content-Type" => "application/json"],
            file_get_contents(__DIR__ . "/fixtures/article.json")
        );

        $this->api = Mockery::mock('overload:KRN\BridgeBundle\Services\KrnBridgeBrowser', "Tests\BridgeStub"); //Here it fails!

        $this->api->shouldReceive("addMiddleware")->withAnyArgs()->andReturn(null);
       //More testing logic
       
    }
}


```

service:
```yaml
    krn_bridge.browser:
        class: KRN\BridgeBundle\Services\KrnBridgeBrowser
        public: true
        arguments: ["@krn_bridge.browser.client.curl", "@buzz_response_factory"]
        calls:
            - ['addMiddleware', ['@krn_bridge.browser.history']]
            - ['addMiddleware', ['@krn_bridge.jaeger']]
            - ['addMiddleware', ['@krn_bridge.wpsec']]

```

error:

```
 PHPUnit\Framework\Exception: Fatal error: Cannot declare class KRN\BridgeBundle\Services\KrnBridgeBrowser, because the name is already in use in /builds/KRN/FRONTEND/src/KRN/BridgeBundle/Services/KrnBridgeBrowser.php on line 8
```

adding `lazy:true` - fixes the test on first run! any idea, what we'd need to refactor? i am  bit lost, we have sooo many tests built around that `::mock()` idea.

**Comment by hjanuschka** [comment]
as a workaround, to get our pipelines working again, i subclassed `WebTestCase`  and ensured that `bootKernel`  removes `var/cache/test`


without a precompiled class list, the mockery `overload:`  works - correctly, however, as there is no cache, each test now takes seconds vs ms prev.



any ideas, what possible change from 5.0 to 5.1 could have introduced that diff. behaviour?

**Comment by hjanuschka** [comment]
so after a day of sadness 😵  -i did a bisect between 5.0.10 and 5.1.1 -> the commit here: https://github.com/symfony/dependency-injection/commit/e5b9248ad640a9e9b56c293dab27024522cfc129

introduces the change, is there a  chance to disable the inline_class_loader in debug mode?

**Comment by nicolas-grekas** [comment]
You should be able to set the `container.inline_class_loader` to `false` in your services.yaml file for example.

**Comment by hjanuschka** [comment]
awesome! thx it worked


for the reference, this is how i needed to set it in `services_test.yaml`


```yaml
parameters:
    container.dumper.inline_class_loader: false
services:
 ......
....
...
```
