### ISSUE TITLE
Service with dots in names can't be used for service subscription

### ISSUE THREAD

**Issue by grikdotnet** [symfony/symfony#37613]
**Symfony version(s) affected**: 4.x.x, 5.x.x

**Description**  
According to the [coding standards](https://symfony.com/doc/current/contributing/code/standards.html#service-naming-conventions) multiple services for the same class can be divided in groups separated with dots, e.g. _something.service_name_

But for service subscribers there is [a regular expression](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php#L73) that does not allow dots, so aliases can't be used as types,
and a check that service type as FQCN [exists](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php#L86)

I have >20 services with same interface and different aliases, but there is no "main service" to assign an interface for - they are equal.

If I use a combination of an existing alias and an FQCN as a service type in a service subscriber while interface is not registered as a service, compiler throws an exception
The service "My\CommandBus" has a dependency on a non-existent service "[FQCN]".

Do I have to declare a boilerplate stub as service record with FQCN just to pass the check?   

There are several hundreds of developers in a project, declaring an interface as a service will create unpredictable side effects for those who use it as a parameter type already.

**How to reproduce**  
1. declare a service by FQCN and an alias with different parameters with dots in a name
```yaml
  my.sorted_set:
    class: DataStructures\Implementations\MysqlSortedSet
    arguments:
    - "dbServerName"
  re.sorted_set:
    class: DataStructures\Implementations\RedisSortedSet
    arguments:
    - "redisServerName"

```
2. Declare a service subscription with 
```
class CommandBus implements \Symfony\Contracts\Service\ServiceSubscriberInterface
{
    public static function getSubscribedServices()
    {
        return ['my.sorted_set'=>\DataStructures\SortedSetInterface::class];
    }
}
```
