### ISSUE TITLE
session.storage.php_bridge makes session_status() report incorrect status

### ISSUE THREAD

**Issue by domnuprofesor** [symfony/symfony#37625]
**Symfony version(s) affected**: 4.4.10

**Description**  
I am `using session.storage.php_bridge` to bridge session data from a legacy app. I am using the following `framework.yaml` configuration:

```
session:
  enabled: true
  storage_id: session.storage.php_bridge
  handler_id: session.handler.native_file
  use_cookies: true
  cookie_secure: auto
  cookie_samesite: lax
```

The legacy php code runs in this maner: `legacy_code() -> symfony_code() -> legacy_code()`
In symfony code everything works as expected but when I check for `session_status()` in the last legacy_code() call, `session_status()` reports an incorrect value of `PHP_SESSION_NONE` instead of `PHP_SESSION_ACTIVE`.
Symfony code only does some reading of legacy session data and the legacy code is not altered in any way. So, after the Symfony code is executed and I get back to the legacy code I get an incorrect session status of `PHP_SESSION_NONE`

This behavior only applies if I use the `framework.yaml` configuration.
If I do the configuration part in the code (see below) `session_status()` returns the correct value.

In my custom `SessionListener`:
```
/* get Symfony to interface with this existing session */
$session = new Session(new PhpBridgeSessionStorage());

/* symfony will now interface with the existing PHP session */
$session->start();
$event->getRequest()->setSession($session);
```

**How to reproduce**  
Already explained above.
