### ISSUE TITLE
[Security] Always Return to Login After Authenticated

### ISSUE THREAD

**Issue by ad3n** [symfony/symfony#37673]
**Symfony version(s) affected**: 5.1.3

**Description**  

PHP: 7.4.3

I have skeleton in https://github.com/KejawenLab/SemartApiSkeleton/tree/3.0 that want to implement multiple guard (Api and Login Form)

The `security.yaml`

```yaml
security:
    encoders:
        KejawenLab\ApiSkeleton\Security\User:
            algorithm: auto
    providers:
        user_provider:
            id: KejawenLab\ApiSkeleton\Security\Service\UserProviderFactory
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|img|js|lib|fonts|bundles)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: true
            lazy: true
            provider: user_provider
            guard:
                authenticators:
                    - KejawenLab\ApiSkeleton\Security\AdminAuthenticator
            logout:
                path: admin_logout
        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            lazy: true
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api_doc:
            pattern: ^/api/doc$
            methods: ['GET']
            security: false
        api_public_media:
            pattern: ^/api/medias/public
            methods: ['GET']
            security: false
        api_public_setting:
            pattern: ^/api/settings/public
            methods: ['GET']
            security: false
        api_public:
            pattern: ^/api/public
            security: false
        api_home:
            pattern: ^/api$
            security: false
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['POST'] }
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['GET', 'POST'] }
        - { path: ^/api/doc$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['GET'] }
        - { path: ^/api/medias/public, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['GET'] }
        - { path: ^/api/settings/public, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['GET'] }
        - { path: ^/api/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_USER }

```

The `User` class

```php
<?php

declare(strict_types=1);

namespace KejawenLab\ApiSkeleton\Security;

use KejawenLab\ApiSkeleton\Security\Model\AuthInterface;
use KejawenLab\ApiSkeleton\Security\Model\GroupInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @author Muhamad Surya Iksanudin<surya.kejawen@gmail.com>
 */
final class User implements UserInterface
{
    private GroupInterface $group;

    private string $id;

    private string $username;

    private string $password;

    private string $class;

    public function __construct(AuthInterface $user = null)
    {
        if ($user) {
            $this->id = $user->getRecordId();
            $this->group = $user->getGroup();
            $this->username = $user->getIdentity();
            $this->password = $user->getCredential();
            $this->class = get_class($user);
        }
    }

    public function getGroup(): GroupInterface
    {
        return $this->group;
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    public function getRoles(): array
    {
        return ['ROLE_USER'];
    }

    public function getClass(): string
    {
        return $this->class;
    }

    public function getSalt()
    {
    }

    public function eraseCredentials()
    {
    }
}
```

When login via Api, all function is fine but when i try to use Form Login, the user is authenticated but after redirect to admin page, token change from `PostAuthenticationGuardToken` to `AnonymousToken` (screeenshot below) and Listeners Section in Profiler is empty

**How to reproduce**  

Login using user: `admin` and password: `admin` using Form Login

**Additional context**  

![Screenshot from 2020-07-27 00-55-41](https://user-images.githubusercontent.com/7464920/88486106-9388f000-cfa5-11ea-8447-0e52a36b6f33.png)

![Screenshot from 2020-07-27 00-56-16](https://user-images.githubusercontent.com/7464920/88486115-9c79c180-cfa5-11ea-8ac1-f17d6d20e844.png)

![Screenshot from 2020-07-27 00-56-31](https://user-images.githubusercontent.com/7464920/88486116-a26fa280-cfa5-11ea-8116-752f06ad8f35.png)
