### ISSUE TITLE
PHP server exited unexpectedly: signal: killed After user Auth

### ISSUE THREAD

**Issue by heardofdezz** [symfony/symfony#37684]
Symfony version v4.18.1

Hey guys i'm on CLI 7.4.8
The server was running perfectly before i initialized my logging protocol.
Sorry for sending so much information below, just want to make sure yall understand the context.

The application console log : 

```
[Application    ] Jul 27 10:14:44 |INFO | SECURI User has been authenticated successfully. username="Loua H"
Shut down, bye!
```

After logging in i get on my console : 

`PHP server exited unexpectedly: signal: killed`

I'm using for the auth : 
`Symfony\Component\Security\Http\Authentication;`
with all the required component 'My IDE inserted them automatically'.

My `security.yaml` is setup this way with a default_target_path.

```
security:
    encoders:
        App\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
      database_users:
          entity: { class: App\Entity\User, property: email}
```

```
form_login:
                check_path: security_login
                login_path: security_login
                default_target_path: theme_add
```
A basic login function in my security controller :

```
public function login(AuthenticationUtils $authenticationUtils){
            return new Response($this->twig->render(
                'security/login.html.twig',
                [
                    'last_username' => $authenticationUtils->getLastUsername(),
                    'error' => $authenticationUtils->getLastAuthenticationError()
                ]
            ));
    }
```

btw i'm a js dev, recently moved to Symfony php. 
My user seems to be authenticated, the browser is waiting on locahost then crashes right after....
