### ISSUE TITLE
_instanceof overriding services definitions

### ISSUE THREAD

**Issue by pejkosz94** [symfony/symfony#37699]
**Symfony version(s) affected**: 4.4.10

**Description**  
Services from `services.yaml::_instanceof` (main file) are taken. Services from `services_A.yaml::_instanceof` are overrode (in this case totally deleted, because only last values are taken).

**How to reproduce**  
Structure:
```
--services/
----services_module_A.yaml
--services.yaml
--services_test.yaml
```
Register all services from `service` directory in `Kernel.php` with code:
```
        $loader->load($confDir . '/{packages}/*' . self::CONFIG_EXTS, 'glob');
        $loader->load($confDir . '/{packages}/' . $this->environment . '/**/*' . self::CONFIG_EXTS, 'glob');
        $loader->load($confDir . '/{services}' . self::CONFIG_EXTS, 'glob');
[register-->]  $loader->load($confDir . '/services/*' . self::CONFIG_EXTS, 'glob'); [<---register] 
        $loader->load($confDir . '/{services}_' . $this->environment . self::CONFIG_EXTS, 'glob');
```

services_module_A.yaml:
```
services:
    _instanceof:
        App\ModuleA\ModuleAService:
            tags: ['tag.module_a_service']
```

services.yaml: (main one)
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            int $tokenTtl: '%env(int:tokenTtl)%'
    _instanceof:
        App\Shared\SharedService:
            tags: ['tag.shared_service']

    App\:
        resource: '../src/*'
        exclude: '../src/**/{DependencyInjection,DataFixtures,Entity,Migrations,Tests,Kernel.php}'
```

**Possible Solution**  
Services from `_instanceof` section from all services files should be merged to one final array of services.

**Additional context**
