### ISSUE TITLE
Cache clear doesn't work with a different cache adapter then filesystem

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#37735]
**Symfony version(s) affected**: 5.1.3

**Description**  
When you are using an other cache system like for example the `cache.adapter.redis` and your dowing a symfony cache clear it will not clear the system cache so when your doing a cache warmup it will just use the cache routing that is had which is a really annoying bug to find in prod.

**How to reproduce**  
- config/packages/cache.yaml
```yaml
framework:
    cache:
        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        system: cache.adapter.redis
```
Do a warmup and run your website 
```sh
./bin/console cache:clear --env=prod
./bin/console cache:warmup --env=prod
```
Make a change for example in routing, make an new route and do a new cache clear and warmup and try to access the new route.
The cache isn't cleared and the route doesn't exists but the new route is in the code

**Possible Solution**  
Clear the designated cache pools when doing a cache:clear

**Additional context**  
To fix the bug above you also have to use `./bin/console cache:pool:clear cache.global_clearer --env=prod`
