### ISSUE TITLE
symfony 4 impersonate across different hosts

### ISSUE THREAD

**Issue by nuryagdym** [symfony/symfony#37819]
Hi,
This question was asked on [Stackoverflow](https://stackoverflow.com/questions/41153988/symfony-impersonate-across-different-hosts) but no solutions provided. I hope I will get answer here. 
I configured 3 different firewalls, each has its own hostname (example.com, admin.example.com and affiliate.example.com).
with my current configuration logging in withing the same firewall/host works, but can not get it work across firewalls/hosts.

When I try to impersonate user I am redirected to the login page.

Here is my configuration
`config/package/security.yaml`:
```
security:
    encoders:
        App\Entity\User: bcrypt
    providers:
        database_users:
            entity: {class: App\Entity\User, property: username}

    firewalls:
        main:
            pattern: ^/
            user_checker: App\Security\UserChecker
            anonymous: true
            host: ^%main_domain_name%\.%tld%$
            switch_user: true
            context: common

        admin:
            pattern: ^/
            user_checker: App\Security\UserChecker
            anonymous: true
            host: ^%admin_subdomain_name%\.%main_domain_name%\.%tld%$
            switch_user: true
            context: common

        affiliate:
            pattern: ^/
            user_checker: App\Security\UserChecker
            anonymous: true
            host: ^%affiliate_subdomain_name%\.%main_domain_name%\.%tld%$
            switch_user: true
            context: common

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
```

Thanks in advance
