### ISSUE TITLE
Retrieving original ID of a service for ServiceLocator does not work according documentation

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#37842]
**Symfony version(s) affected**: 4.4.11, 5.1.0

**Description**  
[code snipet in documentation](https://symfony.com/doc/4.4/service_container/service_subscribers_locators.html#defining-a-service-locator) says `# if the element has no key, the ID of the original service is used`. 

This does not work. User gets error `Service "legacy_service" not found: the container inside "App\Controller\BlogController" is a smaller service locator that only knows about the "0" service.`

**How to reproduce**  
services.yaml:
```yaml
legacy_service:
    class: stdClass

App\Controller\BlogController:
    arguments:
        - !service
            class: Symfony\Component\DependencyInjection\ServiceLocator
            arguments:
              -
                - '@legacy_service'
```
BlogController.php
```php
class BlogController extends AbstractController
{
    public function __construct(ServiceLocator $locator)
    {
        $locator->get('legacy_service');
    }
```

**Comment by ostrolucky** [comment]
And now, even when fixing this, by doing

```diff
legacy_service:
    class: stdClass

App\Controller\BlogController:
    arguments:
        - !service
            class: Symfony\Component\DependencyInjection\ServiceLocator
            arguments:
              -
-                - '@legacy_service'
+                legacy_service: '@legacy_service'
```

then there is another problem:
```
Error:
Function name must be a string

  at vendor/symfony/service-contracts/ServiceLocatorTrait.php:70
  at Symfony\Component\DependencyInjection\ServiceLocator->doGet('legacy_service')
     (vendor/symfony/dependency-injection/ServiceLocator.php:39)
  at Symfony\Component\DependencyInjection\ServiceLocator->get('legacy_service')
     (src/Controller/BlogController.php:42)
  at App\Controller\BlogController->__construct(object(ServiceLocator))
     (var/cache/dev/ContainerAeoXYaU/getBlogController2Service.php:23)
  at ContainerAeoXYaU\getBlogController2Service::do(object(App_KernelDevDebugContainer), true)
     (var/cache/dev/ContainerAeoXYaU/App_KernelDevDebugContainer.php:448)
  at ContainerAeoXYaU\App_KernelDevDebugContainer->load('getBlogController2Service.php')
     (vendor/symfony/dependency-injection/Container.php:246)
```

cc @nicolas-grekas

**Comment by stof** [comment]
@ostrolucky do you have autoconfiguration applied on your inline service ? If no, you are missing the `container.service_locator` tag

**Comment by ostrolucky** [comment]
I do, but it looks like it's not applied to anonymous service. Changing above to 

```yml
legacy_service:
        class: stdClass

    locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                legacy_service: '@legacy_service'

    App\Controller\BlogController:
        arguments: ['@locator']
```

or to

```yml
legacy_service:
        class: stdClass

    App\Controller\BlogController:
        arguments:
            - !service
                class: Symfony\Component\DependencyInjection\ServiceLocator
                arguments:
                  -
                    legacy_service: '@legacy_service'
                tags: [container.service_locator]
```

fixes the issue. Is it expected that autoconfigure is not applied to anonymous services?
