### ISSUE TITLE
[Security] access_control require firewall on same URL to work

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#37875]
**Symfony version(s) affected**: 5.0.8

**Description**  
It looks like `access_control` option has no effect if no firewall match the pattern of the `access_control` item.

**How to reproduce**  
I followed [the documentation](https://symfony.com/doc/current/security/force_https.html) to enable https globally on my application, by configuring my `access_control` with this config:
``` yaml
access_control:
    - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```

But only URL starting by `/admin` was redirected to HTTPS.
All other URL was still displayed on HTTP without redirection.

This is because I had no firewall attached to the root web folder `/`, my firewall configuration was:
``` yaml
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin  # this firewall is applied to /admin urls only
            anonymous: lazy
            # ...
```

After updating my `firewalls` configuration to this
``` yaml
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: lazy
            # ...
        default:
            pattern: ^/
            anonymous: lazy
```
It finally works and all URL are now redirected to HTTPS.

Is it normal that `access_control` depends on `firewalls` configuration to work?
