### ISSUE TITLE
[Messenger] Retrying failed messages when using a message interface as the handler __invoke type-hint

### ISSUE THREAD

**Issue by marcortola** [symfony/symfony#37905]
**Symfony version(s) affected**: 4.4.11

**Description**  
I'm using the Symfony Messenger component in a Symfony 4.4 application. I'm processing the messages async through RabbitMQ and storing the failed ones in a database through the Doctrine transport.

Everything is working before facing any message failure. The problem starts showing after failing when trying to retry or show the failed messages. Let's try the ```php bin/console messenger:failed:show``` command:

Result:

```
In PhpSerializer.php line 64:
                                                                               
  Cannot instantiate interface App\SampleMessageInterface                                                            
```
I guess that Symfony needs to unserialize the failed message, previously serialized and stored in the database, but can't do it because it's an interface. The failed message is stored in the database as a ```SampleMessageInterface```not as the ```SampleMessageInterface``` implementation.

Is it a bug or the expected behavior?

**How to reproduce**  
Configure the messenger component like this:

```yml
framework:
    messenger:
        failure_transport: failed

        buses:
            command_bus:
                middleware:
                    - doctrine_ping_connection

        transports:
            failed: 'doctrine://default?queue_name=failed'
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 2000
                    max_retries: 5
                    multiplier: 2
                options:
                    exchange:
                        name: high
                    queues:
                        messages_high: ~

            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 3000
                    max_retries: 3
                    multiplier: 2
                options:
                    exchange:
                        name: low
                    queues:
                        messages_low: ~

        routing:
            'App\SampleMessageButHighPriority': async_priority_high
            'App\SampleMessageInterface': async_priority_low
            'App\OtherMessage': async_priority_low
```
And create a sample handler that handler messages imlpementing the ```SampleMessageInterface``` interface:

```php
final class SampleMessageHandler implements MessageHandlerInterface
{
    private ProjectRepository $projectRepository;

    public function __construct(ProjectRepository $projectRepository)
    {
        $this->projectRepository = $projectRepository;
    }

    public function __invoke(SampleMessageInterface $message): void
    {
        $project = $this->projectRepository->find($message->getProjectId()->toString());

        if ($project === null) {
            return;
        }

        $this->someProcessor->__invoke($project);
    }
}
```

**Possible Solution**  
A simple solution would be not using the interface for type-hinting the handler ```__invoke``` method param, but then we wouldn't benefit from creating only one handler to handle all the ```SampleMessageInterface``` messages.
