### ISSUE TITLE
Support inheritance in Workflow component

### ISSUE THREAD

**Issue by benjaminmal** [symfony/symfony#37919]
**Description**  
It would be nice to implement workflow inheritance. It can be useful when you want to create a workflow with an entity that extends an entity which already has a workflow. The idea, you got it, is to have all places and transitions of the parent workflow in the child class by inheritance. 

**Work around**
- What do you think of transitions and initial_marking overriding ?
- Maybe not guessing the inheritance with the class inheritance but with a new option `inherit: 'workflow_name'` ?

**Example**  
Let's say you have a Parent entity and its child :
```php
class Parent {
    protected $state;
}

class Child extends Parent {
}
```
The idea is to get from this :
```yaml
# workflow.yaml
framework:
    workflows:
        parent_workflow:
            type: 'workflow'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Parent
            initial_marking: initial
            places:
                - initial
                - expired
            transitions:
                expire:
                    from: initial
                    to: expired

        child_workflow:
            type: 'workflow'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Child
            initial_marking: initial
            places:
                - initial
                - expired
                - done
            transitions:
                do:
                    from: initial
                    to: done
                expire:
                    from: initial
                    to: expired
```
To this :
```yaml
# workflow.yaml
framework:
    workflows:
        parent_workflow:
            type: 'workflow'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Parent
            initial_marking: initial
            places:
                - initial
                - expired
            transitions:
                expire:
                    from: initial
                    to: expired

        child_workflow:
            type: 'workflow'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Child
            initial_marking: initial
            inherit: parent_workflow # Not implemented
            places:
                - initial
                - done
            transitions:
                do:
                    from: initial
                    to: done
```
Last child_workflow :
![graph](https://user-images.githubusercontent.com/58468686/90962478-9990c480-e4b0-11ea-8602-ab7639d9d050.png)

It is feasible ? Or maybe I am missing something and it's already possible ;)

**Thanks**
Thanks for your work !
