### ISSUE TITLE
[DI] Stack decorator does not work with named service

### ISSUE THREAD

**Issue by tyx** [symfony/symfony#37930]
**Symfony version(s) affected**: 5.1.3

**Description**  

When using stack decorator (https://symfony.com/blog/new-in-symfony-5-1-stack-decorators) with named service, I get a `ServiceCircularReferenceException`

![image](https://user-images.githubusercontent.com/245494/91026060-8ab62900-e5fa-11ea-8e1d-1f89f3354aa6.png)

**How to reproduce**  

With a code like 
```
services:
  apaleo.api.client:
      stack:
        - class: 'Gogaille\Shared\Infra\LogResponseTimeHttpClient'
          arguments:
            - '@.inner'
        - '@apaleo.api.client'
```

and

```
framework:
  http_client:
    scoped_clients:
      apaleo.api.client:
        base_uri: https://api.apaleo.com
```

**Possible Solution**  

When taking a look to the test https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Tests/Loader/YamlFileLoaderTest.php#L963 I just realized, that `@service` will look for another stack.

It looks a weird default behavior. And I did not see any clue to use a named service. I guess we need to find a way to differentiate reference to another stack, and reference to real service.

I could help on this subject, but I should admit I have no idea how all this stuff work.

**Additional context**  

In my case I want to benefit from scoping_client stuff of http-client component  (and getting a named service) and adding a (multiple) decorator on it.

**Comment by nicolas-grekas** [comment]
The definition you posted defines a circular loop so that the exception is expected and tells precisely what happens...

**Comment by tyx** [comment]
Hi ! I'm using exemple from this blog post https://symfony.com/blog/new-in-symfony-5-1-stack-decorators

So How am I supposed to work with stack decorator ? Create it and then alias it ? 

Because for now it doesn't look that stack replaces first service as decorator does.

For example:
```yaml
  response_time_http_client.apaleo_api.decorator:
    class: 'Gogaille\Shared\Infra\LogResponseTimeHttpClient'
    decorates: apaleo.api.client
    arguments:
      - '@.inner'
```

I still using `apaleo.api.client`, the decorator just replace my service. Stack could do the same job ?
