### ISSUE TITLE
TagAwareCache not using native redis sets

### ISSUE THREAD

**Issue by flaushi** [symfony/symfony#37945]
I am trying to use this feature: https://symfony.com/blog/new-in-symfony-4-4-redis-cache-improvements
I am using Symfony 4.4, and have a configuration like this:
```
cache:
        default_redis_provider: 'redis://%env(REDIS_HOST)%/%env(REDIS_DB)%'
        pools:
            tagged_data_cache:
                adapter: cache.adapter.redis
                default_lifetime: 0
                tags: true
services:
    _defaults:
        bind:
            $taggedDataCache: '@tagged_data_cache'
```
I am using the redis extension redis-4.3.0.
If I execute this code:
```
function bla(AdapterInterface $taggedDataCache)
{
    if($taggedDataCache->has('minmaxdate-0111669a-41cb-46f8-b598-8dbb1f9997ba)) {
        return $taggedDataCache->getItem('minmaxdate-0111669a-41cb-46f8-b598-8dbb1f9997ba)->get();
    }
    $i = $taggedDataCache->getItem('minmaxdate-0111669a-41cb-46f8-b598-8dbb1f9997ba);
    $i->set(...);
    $i->tag('0111669a-41cb-46f8-b598-8dbb1f9997ba');
    $taggedDataCache->save($i);
}
```
Then these commands are printed on redis-cli's MONITOR command:
```
1597997874.233465 [0 172.18.0.5:41714] "EXISTS" "cflIDBi3cW:minmaxdate-0111669a-41cb-46f8-b598-8dbb1f9997ba"
1597997874.233797 [0 172.18.0.5:41714] "MGET" "PVj5Gcu1j-:%5B4ecb6b0180cbbd8397e04aad594ea33b%5D%5B1%5D"
1597997877.025024 [0 172.18.0.5:41714] "MGET" "cflIDBi3cW:\x00tags\x00minmaxdate-0111669a-41cb-46f8-b598-8dbb1f9997ba" "cflIDBi3cW:minmaxdate-0111669a-41cb-46f8-b598-8dbb1f9997ba"
1597997877.025375 [0 172.18.0.5:41714] "SET" "cflIDBi3cW:minmaxdate-0111669a-41cb-46f8-b598-8dbb1f9997ba" "a:2:{i:0;O:13:\"Carbon\\Carbon\":3:{s:4:\"date\";s:26:\"2020-01-01 00:00:00.000000\";s:13:\"timezone_type\";i:3;s:8:\"timezone\";s:3:\"UTC\";}i:1;O:13:\"Carbon\\Carbon\":3:{s:4:\"date\";s:26:\"2020-07-01 00:00:00.000000\";s:13:\"timezone_type\";i:3;s:8:\"timezone\";s:3:\"UTC\";}}"
1597997877.025532 [0 172.18.0.5:41714] "MGET" "cflIDBi3cW:0111669a-41cb-46f8-b598-8dbb1f9997ba\x00tags\x00"
1597997877.025781 [0 172.18.0.5:41714] "SET" "cflIDBi3cW:\x00tags\x00minmaxdate-0111669a-41cb-46f8-b598-8dbb1f9997ba" "a:1:{s:36:\"0111669a-41cb-46f8-b598-8dbb1f9997ba\";i:0;}"
```
Question: are the native tags used here? I do not see any set commands like `sadd`.
Thanks in advance!
