### ISSUE TITLE
Routes Breaking Changes

### ISSUE THREAD

**Issue by Nerogee** [symfony/symfony#37957]
**Symfony version(s) affected**: 5.1.2

**Description**  

Inside routes.yaml, I have following setting

```
home:
    path:
        zh-hk: /
        others: /{_locale}/
    controller: App\Controller\IndexController::index
    requirements:
        _locale: zh-hk|zh-cn|en-us

```

**How to reproduce**  

create corresponding controller and simply return JsonResponse object.

I expect I can access home page via following url
**mydomain.com**
**mydomain.com/zh-hk**
**mydomain.com/zh-cn
mydoman.com/en-us**

But only the **mydomain.com** works. The other routes failed. 

**Possible Solution**  

```
homepage:
    path: /
    controller: App\Controller\IndexController::index

homepage_others:
    path: /{_locale}/
    controller: App\Controller\IndexController::index
    requirements:
        _locale: zh-hk|zh-cn|en-us
```
**Additional context**  

I have the same routes setting in symfony 4.2.8. It works fine with above settings and produces expected results.

**Comment by ro0NL** [comment]
AFAIK you'll need to list all locales under path: https://symfony.com/doc/current/routing.html#localized-routes-i18n

Unless `path.others` was made to work, which im unaware off.

**Comment by Nerogee** [comment]
Those examples provided in official doc are very week.  like this one
```
about_us:
    path:
        en: /about-us
        nl: /over-ons
    controller: App\Controller\CompanyController::about
```
what if I need to suppose a dozen of languages? I had the possible solution (see the question) which does not need to enumerate all locales. But still there are some duplication. Comparing the what I can do in symfony 4.2.8, I thought the localized Routes in 5.1.2 is degenerated.
