### ISSUE TITLE
Get metadata configuration from Transition without having to inject the whole graph

### ISSUE THREAD

**Issue by rapliandras** [symfony/symfony#37955]
**Description**  
Get metadata configuration directly from Transition without having to inject the whole graph

**Example**  

Configuration:

```
transitions:
  publish:
    from: x
    to: y
    metadata:
      privileges: ["ROLE_PUBLISH"]
```
Current workaround:
```
class TransitionManager
{
    /**
     * @var Definition
     */
    private $definition;

    public function __construct(Definition $definition)
    {
        $this->definition = $definition;
    }

    public function getRequiredPrivileges(Transition $transition) : array
    {
        return $this->definition->getMetadataStore()->getTransitionMetadata($transition)["privileges"];
    }
}
```
Requested new method in Transition class:

```
class Transition
{
  // ...
  public function getMetadata() : MetadataStoreInterface
  {
  // ... 
  }
}
```
