### ISSUE TITLE
[messenger] Failed message never delivered to failed queue after retry

### ISSUE THREAD

**Issue by jmhoueg** [symfony/symfony#37985]
**Symfony version(s) affected**: 5.1.3

**Description**  
Using messenger with RabbitMQ, after a message fails and is retried 2 times, the message should be sent to the failed queue but it doesn't happen for me. This is my messenger.yaml:
```yaml
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: amqp_create_order_error
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            amqp_create_order:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'ms.customer-order'
                        type: topic
                    queues:
                        ms.customer-order;onestock_create_order:
                            binding_keys:
                                - 'create_order'
                retry_strategy:
                    max_retries: 2
            amqp_create_order_retry_30000:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'ms.customer-order'
                        type: topic
                    queues:
                        ms.customer-order;create_order_retry_30000:
                            binding_keys:
                                - 'create_order_retry_30000'
            amqp_create_order_error:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'ms.customer-order'
                        type: topic
                    queues:
                        ms.customer-order;create_order_error:
                            binding_keys:
                                - 'create_order_error'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
        routing:
            # Route your messages to the transports
            'App\Message\CreateOneStockOrderMessage': amqp_create_order
```

I read https://github.com/symfony/symfony/issues/31455 and according to what was said it should work without trouble. What can i do please?

**How to reproduce**  
Use my messenger.yaml, create a handler which fails and see what happens
