### ISSUE TITLE
  Cannot create an instance of "Symfony\Component\Messenger\Stamp\BusNameStamp" from serialized data because its constructor requires parameter "busName" to be present. 

### ISSUE THREAD

**Issue by cbm-jpsaulnier** [symfony/symfony#37991]
**Symfony version(s) affected**: 4.4

**Description**  
I know a similar issue has been marked as resolved earlier but even after trying the different solutions, the problem remains.

I tried the messenger component this week-end with RabbitMQ.

So I created a class, sent it with the AMQP stamp and everything worked well. 

```
config/packages/messenger.yaml

framework:
    messenger:
        default_bus: messenger.bus.default
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: gallery
                        type: topic
                    queues:
                        gallery-gallery-email:
                            binding_keys:
                               - gallery.account_created_to_validate_email.sent
                               - gallery.confirm_order_email.sent
                               - gallery.new_account_created_email.sent
                               - gallery.out_of_stock_product_email.sent
                               - gallery.request_password_email.sent

            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Event\PushNotificationEventInterface': async
```

When I tried to consume it, it was ok too. Then I found the native PHP serialization wasn't pleasant to read so I decided to use the symfony serializer in json with groups.

```
config/packages/messenger.yaml

framework:
    messenger:
        default_bus: messenger.bus.default
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { groups : ['notification'] }

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: gallery
                        type: topic
                    queues:
                        gallery-gallery-email:
                            binding_keys:
                               - gallery.account_created_to_validate_email.sent
                               - gallery.confirm_order_email.sent
                               - gallery.new_account_created_email.sent
                               - gallery.out_of_stock_product_email.sent
                               - gallery.request_password_email.sent

            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Event\PushNotificationEventInterface': async
```

```
config/packages/framework.yaml

framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    esi: true
    fragments: true
    php_errors:
        log: true

    serializer:
        enable_annotations: true
        enabled: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
        mapping:
            paths:
                - "%kernel.project_dir%/config/serialization"
```

```
config/serialization/pushNotificationEvent.yaml

App\Event\PushNotificationEventInterface:
  attributes:
    data:
      groups: ['notification']
    mailType:
      groups: ['notification']
```

My rabbitMQ message arrived in the queue with an empty X-Message-Stamp-Symfony\Component\Messenger\Stamp\BusNameStamp header:

```
X-Message-Stamp-Symfony\Component\Messenger\Stamp\BusNameStamp: [[]]
```
When I tried to consume it, I had the error message in the subject of this issue.

On the other [issue](https://github.com/symfony/symfony/issues/31490), I found those tricks:
- install symfony/property-access
- configure name_converter to false

```    
config/packages/framework.yaml

serializer:
        enable_annotations: true
        enabled: true
        name_converter: false
        mapping:
            paths:
                - "%kernel.project_dir%/config/serialization"
```

I even tried to manually add the busName but it remained empty

```
    public function publishResourceStatusNotification(PushNotificationEventInterface $event): void
    {
        $envelope = new Envelope($event, [
            new BusNameStamp('messenger.bus.default'),
            new AmqpStamp(
                sprintf('gallery.%s_email.sent', $event::getMailType()),
                AMQP_DURABLE,
                [
                    'content_type' => 'application/json',
                    'delivery_mode' => 2,
                ]
            ),
        ]);

        $this->bus->dispatch($envelope);
    }
```

It didn't work out so I came back to the ancien code:

```
$this->bus->dispatch(
            $event,
            [
                new AmqpStamp(
                    sprintf('gallery.%s_email.sent', $event::getMailType()),
                    AMQP_DURABLE,
                    [
                        'content_type' => 'application/json',
                        'delivery_mode' => 2,
                    ]
                )
            ],
        );
```

**How to reproduce**  
- Create a new sf4.4 project
- Create an entity
- Configure the messenger.yaml to use rabbitMQ (see above)
- Configure serialization in config/serialization folder
- Dispatch a message
- Consume it in your terminal

**Possible Solution**  
Maybe a custom transport serializer could work but I do think there is a way to make it work without it.

**Additional context**  
![image](https://user-images.githubusercontent.com/46447770/91657950-9bb4dd80-eac5-11ea-8001-dbc68576458a.png)

Could someone, who uses messenger component with Symfony serializer in json, give me a hint? I tried for hours and don't know what to do to make it work. Thanks in advance.

**Comment by sroze** [comment]
I can confirm the issue when using the Symfony serializer 👍

**Comment by samijnih-igraal** [comment]
I have the same issue

**Comment by alterphp** [comment]
We managed to work around this issue by defining a specific serializer used by messenger for our entire platform. Default config for serializer no more applies for deserialization of messenger transports.

```yaml
framework:
    messenger:
        serializer:
            default_serializer: 'platform_wide.messenger_serializer'

services:
    platform_wide.messenger_serializer:
        class: Symfony\Component\Messenger\Transport\Serialization\SerializerInterface
        factory:
            - 'Platform\Messenger\MessengerSerializerFactory'
            - 'createSerializer'
```
```php
<?php

declare(strict_types=1);

namespace Platform\Messenger;

use Symfony\Component\Messenger\Transport\Serialization\Serializer;
use Symfony\Component\Messenger\Transport\Serialization\SerializerInterface;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer as SymfonySerializer;

final class MessengerSerializerFactory
{
    public function createSerializer(): SerializerInterface
    {
        $normalizers = [
            new ArrayDenormalizer(),
            new DateTimeNormalizer(),
            new ObjectNormalizer(),
        ];
        $encoders = [new JsonEncoder()];
        $serializer = new SymfonySerializer($normalizers, $encoders);

        return new Serializer($serializer);
    }
}

```

We think that messenger transports should use their own serializer instead of depending of default serializer configured on a project. Indeed transport serialization may be shared by many applications, so application-wide serializer config should not apply to transport serializer.

**Comment by next-sentence** [comment]
Hi, recent I had similar issue.
The problem was with context groups here:


```
config/packages/messenger.yaml

framework:
    messenger:
        default_bus: messenger.bus.default
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { groups : ['notification'] }
```

Fixed by dispatching event with serializer stamp and remove in the config file context key:

```
        $this->bus->dispatch(
            (new Envelope($event))->with(new SerializerStamp([
                'groups' => ['notification'],
            ]))
        ); 
```
