### ISSUE TITLE
doctrine mongodb bundle, usage of two databases

### ISSUE THREAD

**Issue by apapilov-sc** [symfony/symfony#38018]
I configured mongodb bundle so that I could get two connections and two document mannegers.

/config/packages/doctrine_mongodb.yaml
```
doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
        meteo:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
            connection: default
        meteo:
            database: '%env(resolve:MONGODB_DB_METEO_NAME)%'

```

then I created class implementing "ServiceSubscriberInterface", (this example was discribed in documentation - https://symfony.com/doc/current/service_container/service_subscribers_locators.html#aliased-services) 
it requires to implement ServiceSubscriberInterface::getSubscribedServices() method, and specify services as and arrayy of alias => Service::class  to be able to use them inside service locator. 
     if I write "dm" => Documentmanager::class I will get default document manager, but how can i specify second  mocument manager in service locater since i do not know what class it is?

```
class GrapqlTypesFactoryOne implements ServiceSubscriberInterface
{

    private $locator;

    public function getDm() {
        return $this->locator->get('doctrine_mongodb.odm.meteo_document_manager');
    }

    public static function getSubscribedServices()
    {
        return [
            // ...
            'place' => PlaceRepository::class,
            'DocumentManger' => DocumentManager::class,
            'MeteoDocumentManager' => ???????
        ];
    }
}
```
