### ISSUE TITLE
Impossible to replace the default router (Cannot load resource "kernel::loadRoutes".)

### ISSUE THREAD

**Issue by Microtribute** [symfony/symfony#38032]
**Symfony version(s) affected**: 5.1.3

**Description**  
I am trying to override the default Symfony router with my custom route generator for my Doctrine entities.  When I do this, I get the following error:

```
Cannot load resource "kernel::loadRoutes".
```

Screenshot:
![Screenshot from 2020-09-02 10-13-03](https://user-images.githubusercontent.com/46481195/91962779-eec8a380-ed04-11ea-9977-31b79c20edeb.png)

**How to reproduce**  

I re-defined the service in the app config file at `app/config/services.yml`. I just copied the configuration from `routing.xml` of the Framework Bundle, and added the following files.

- `config/services.yml`

```yml
services:
    # default configuration for services in *this* file
    ... ...

    router.default:
        class: App\Routing\Router

        tags:
            - { name: monolog.logger, channel: router }
            - { name: container.service_subscriber, id: routing.loader }

        arguments:
            - '@Psr\Container\ContainerInterface'
            - '%router.resource%'
            -
                cache_dir: '%kernel.cache_dir%'
                debug: '%kernel.debug%'
                generator_class: App\Routing\Generator\UuidAwareUrlGenerator
                generator_dumper_class: Symfony\Component\Routing\Generator\Dumper\CompiledUrlGeneratorDumper
                matcher_class: Symfony\Bundle\FrameworkBundle\Routing\RedirectableCompiledUrlMatcher
                matcher_dumper_class: Symfony\Component\Routing\Matcher\Dumper\CompiledUrlMatcherDumper

            - '@router.request_context'
            - '@parameter_bag'
            - '@logger'
            - '%kernel.default_locale%'

        calls:
            - [ setConfigCacheFactory, [ '@config_cache_factory' ] ]
```

- `src/Routing/Router.php`

```php
<?php

namespace App\Routing;

use Symfony\Bundle\FrameworkBundle\Routing\Router as DefaultRouter;

class Router extends DefaultRouter
{

}
```

- `src/Routing/Generator/UuidAwareGenerator.php`

```php
<?php
namespace App\Routing\Generator;


use App\Uuid\BinaryUuidInterface;
use Symfony\Component\Routing\Generator\CompiledUrlGenerator;
use function array_map;

class UuidAwareUrlGenerator extends CompiledUrlGenerator
{
    public function generate(string $name, array $parameters = [], int $referenceType = self::ABSOLUTE_PATH)
    {
        $parameters = array_map(fn ($value) => $value instanceof BinaryUuidInterface ? $value->format() : $value, $parameters);

        return parent::generate($name, $parameters, $referenceType);
    }
}

```

**Possible Solution**  

**Additional context**
