### ISSUE TITLE
keepQueryParams not working with route attributes

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#38069]
When using `keepQueryParams: false`, I am expecting to not have query param in my redirection, but if the redirected path has an attribute, the redirect URL will contain it in the query.

Example:

``` yaml
legacy.route.name:
    path: /{myparam}/my-legacy-url.php
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: my_new_route
        permanent: true
        keepQueryParams: false
```

This result in a redirection to: `/my/new/route?myparam=xxx`

When I am expecting `/my/new/route`

**Comment by xabbuh** [comment]
I am not able to reproduce this. Can you please create a small example application that allows to do so?

**Comment by malteschlueter** [comment]
I think the option _keepQueryParams_ works correct. See https://github.com/malteschlueter/test-redirect/blob/master/tests/Controller/RedirectTest.php.

If you add a query parameter in the old url, it will removed in the redirect url.

In your case you configured a url param which is not existing in the new url. So the router is adding (not keeping) the parameter as a query param.

I added another case, like if your new url has the same parameter in the url. Then the router is setting the param in the url and is not adding it as a query param.

**Comment by xabbuh** [comment]
Let's close for now. We can always reopen once we are able to reproduce.

**Comment by Seb33300** [comment]
I am still able to reproduce the issue even after updating Symfony to 5.0.11

I can reproduce the issue using with `route` or `path` redirection:

```
legacy.route:
    path: /{country}my-old-url.php
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    requirements:
        country: .*
    defaults:
        path: /new-url
        permanent: true
```

If I try to access to `/my-old-url.php?test`
I am redirected to `/new-url?test`

**Comment by Seb33300** [comment]
@malteschlueter I can see that your test is reproducing the issue.

``` php
$client->request('GET', '/aParam/my-legacy-url.php?additional-param=foo&another-param=bar');
$this->assertTrue($client->getResponse()->isRedirect('http://localhost/?myparam=aParam'));
```

The new route does not have `myparam` param.
So it should be considered as an extra param and correct redirection should be `http://localhost/`.

**Comment by xabbuh** [comment]
In your first example, the `urlRedirectAction()` method is used which doesn't support the `keepQueryParams ` option. Adding support for it would be a new feature. In your second example you would also have to set the `ignoreAttributes` option to `true` to get the desired outcome.

**Comment by Seb33300** [comment]
Ok, `ignoreAttributes` is missing in the documentation: https://symfony.com/doc/current/routing.html#redirecting-to-urls-and-routes-directly-from-a-route

But using it will also ignore my new route attribute and fails to generate the URL:

> Some mandatory parameters are missing ("slug") to generate a URL

``` yaml
legacy.route:
    path: /{country}my-old-url.php
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    locale: fr
    requirements:
        country: .*
    defaults:
        route: my_route
        slug: my-route-slug  # my_route require slug attribute
        permanent: true
        keepQueryParams: false
        ignoreAttributes: true
```
