### ISSUE TITLE
[HttpClient] Add method `->getName()` for scoped clients

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#38065]
**Description**  
... might be useful for debugging sometimes.

**Example**  
With
```yaml
http_client:
    scoped_clients:
        foobar.client:
            # ...
```
... there should be a method like `$client->getName()`, returning "foobar" (or "foobar.client")
