### ISSUE TITLE
[Routing] Support for env variables when configuring locale based on host

### ISSUE THREAD

**Issue by Wirone** [symfony/symfony#38210]
**Description**  
I've followed #30617 (and symfony/symfony-docs#13571) for configuring support for locales based on host. Unfortunately, it does not support for env variables for hosts and in my opinion it makes this feature unusable, non-friendly at least:

- routes must be defined differently for DEV and PROD
- moving app between domains requires changes in codebase

Would be great if hosts could be passed as env variables.

**Example**  
```
foo:
    resource: routes/foo.yaml
    prefix: /
    defaults:
        _format: html
    host:
        en: '%env(APP_HTTP_HOST)'
        pl: '%env(APP_HTTP_HOST_PL)'
```

With config above it does not work, even considering #38209 is fixed and host-related rules are checked.

---

CC: @odolbeau

**Comment by fabpot** [comment]
Why not use a container parameter (which can be difference in dev and prod)? Env vars are only useful for values that need to be changed dynamically without flushing the cache, I don't think this is needed here.

**Comment by Wirone** [comment]
@fabpot when application is served with Docker and image is pre-built in CI, it's not desirable to recreate cache inside running container. It should be "black box", retrieving required data from the outside (env variables).

Of course, it's possible to build images differently for local/dev/prod instances but even with that it won't be possible to run application (container) under different hosts without changing code/CI config and going through build process. Personally I think it would be much friendly with env vars support.

**Comment by Guikingone** [comment]
@Wirone Container parameters can be based on environment variables if the container cache is an issue.

**Comment by chalasr** [comment]
I'm closing this issue as it didn't receive much attraction since it has been opened (~3 months), which hints that the current alternatives are good enough in most cases. Feel free to comment or reopen if you think otherwise. 
Thanks.

**Comment by janklan** [comment]
> @Wirone Container parameters can be based on environment variables if the container cache is an issue.

When you set a parameter value using an environment variable and then move the application somewhere else, all the compiled routes will use the environment variable value present when the cache is warming up. 

I'm in the same boat with @Wirone. The end effect is that if you build a Docker container and then run it somewhere else, you need to flush & warm up the cache when the container starts; otherwise, your app's routing breaks.

At the very least, the need to warm up the cache prevents the Symfony application from running on a read-only file system. 

--

On @fabpot's comment:

> Why not use a container parameter (which can be difference in dev and prod)? Env vars are only useful for values that need to be changed dynamically without flushing the cache, I don't think this is needed here.

In our case, we run the same code, the same `prod` environment on different servers and under different hostnames. We also use the `host` routing value to differentiate between global routes (ie. `app.example.com`) and customer-specific routes (i.e. `customer-slug.app.example.com`). The exact same code & built Docker image is deployed on several different hostnames, which is a business requirement in our case - some customers want to self-host our application on their own domain names.

The important snippets of configuration are:

`routing.yml`

```yaml
parameters:
    default_host: '%env(hostname:DEFAULT_ENDPOINT_URL)%'

framework:
    router:
        default_uri: '%env(DEFAULT_ENDPOINT_URL)%'
```

`routes.yml`

```yaml
controllers:
    resource: ../src/Controller/
    type: annotation
    host: '%default_host%'
```

`security.yml`:

```yaml
security:
    firewalls:
        public:
            host: '^.+\.%env(preg_quote:hostname:DEFAULT_ENDPOINT_URL)%$'
        main:
            (no host defined - catch all firewall)
```

The `hostname` processor does just `parse_url($env, PHP_URL_HOST)`

The default value (at the time we build the image in CI), the environment has `DEFAULT_ENDPOINT_URL=https://local.dev.example.com`.

One of the consequences is that when the customer opens any protected URL on `https://app.example.com`, Symfony attempts to redirect to the authentication entry point on an incorrect hostname, `https://local.dev.example.com/login`.

Warming the cache up in the target environment (where `DEFAULT_ENDPOINT_URL` is valid for that environment) fixes the problem, but it's not ideal for reasons I wrote above.
