### ISSUE TITLE
[Yaml] valid comment crashes

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#38223]
**Symfony version(s) affected**: 5.1

Given e.g.

```yaml
foo:
    bar:
        baz:
            access_key: 'literal'#'%env(ACCESS_KEY)%'
```

it crashes with `Unexpected characters near "#'%env(ACCESS_KEY)%'"` (note the quotes around `literal`)

but is succesfully parses at http://www.yamllint.com/

adding a space before `#` solves it in Symfony, but i was too lazy :)
