### ISSUE TITLE
Detect with `lint:container` if env vars or parameters are not correctly injected into services

### ISSUE THREAD

**Issue by Kocal** [symfony/symfony#38261]
**Description**  
Sometimes, you can forgot a `%` when injecting a environment variable or parameter into a service and it can lead to weird behavior. 

**Example**  

For example, given the following service definition:
```
services:
  App\MyGoogleService:
    arguments:
      $apiKey: '%env(GOOGLE_API_KEY)'
```

It will literally inject `%env(GOOGLE_API_KEY)` instead of throwing is an issue.

I would expect `lint:container` to throw an error `Argument "$apiKey" of service "App\MyGoogleService" is not correctly configured.`, or something like this.

I would also expect `%parameter` to fail, if a `%` is missing and `parameter` is a known container parameter. 

What do you think?
Thanks!
