### ISSUE TITLE
Decorate interface

### ISSUE THREAD

**Issue by GameplayJDK** [symfony/symfony#38286]
**Symfony version(s) affected**: 5.1.5

**Description**  

I've tried to decorate an alias of an interface. But it doesn't seem to be supported by the container to decorate an interface alias. I could not find anything about this problem in the documentation.

```bash
PS D:\Project\example> php bin/console about -vvv

In ContainerBuilder.php line 982:
                                                                                                                         
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                             
  You have requested a non-existent service "@App\Repository".  
                                                                                                                         

Exception trace:
  at D:\Project\example\vendor\symfony\dependency-injection\ContainerBuilder.php:982
 Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() at D:\Project\example\vendor\symfony\dependency-injection\ContainerBuilder.php:1014
 Symfony\Component\DependencyInjection\ContainerBuilder->findDefinition() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\AutowirePass.php:150
 Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireCalls() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\AutowirePass.php:126
 Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\AutowirePass.php:72
 Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\AbstractRecursivePass.php:81
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\AutowirePass.php:103
 Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\AutowirePass.php:72
 Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\AbstractRecursivePass.php:46
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\AutowirePass.php:54
 Symfony\Component\DependencyInjection\Compiler\AutowirePass->process() at D:\Project\example\vendor\symfony\dependency-injection\Compiler\Compiler.php:91
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at D:\Project\example\vendor\symfony\dependency-injection\ContainerBuilder.php:736
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at D:\Project\example\vendor\symfony\http-kernel\Kernel.php:533
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at D:\Project\example\vendor\symfony\http-kernel\Kernel.php:131
 Symfony\Component\HttpKernel\Kernel->boot() at D:\Project\example\vendor\symfony\framework-bundle\Console\Application.php:168
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at D:\Project\example\vendor\symfony\framework-bundle\Console\Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\Project\example\vendor\symfony\console\Application.php:140
 Symfony\Component\Console\Application->run() at D:\Project\example\bin\console:43

2020-09-23T23:39:00+00:00 [info] Deprecated: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
2020-09-23T23:39:00+00:00 [info] Deprecated: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

```

**How to reproduce**  

services.yaml

```yaml
parameters:

services:
  App\:
    resource: '../src/'
    exclude:
      - '../src/Model'

  # Configure service:

  App\Repository:
    calls:
      - setup: 'setup value'

  # Configure alias:

  App\RepositoryInterface:
    alias: '@App\Repository'

  # Configure proxy:

  App\Proxy\Repository:
    autowire: true
    # Decoration:
    decorates: App\RepositoryInterface
    decoration_priority: 10

```

RepositoryInterface

```php
namespace App;
interface RepositoryInterface {
}
```

Repository

```php
namespace App;
class Repository implements RepositoryInterface {
    public function setup(string $name): void {
        echo $name, PHP_EOL;
    }
}
```

Proxy/Repository

```php
class Repository implements RepositoryInterface {
}
```

**Possible Solution**  

When I'm using the following configuration the error does not occur.

services.yaml

```yaml
parameters:

services:
  App\:
    resource: '../src/'
    exclude:
      - '../src/Model'

  # Configure service:

  App\Repository:
    calls:
      - setup: 'setup value'

  # Configure alias:

  App\RepositoryInterface:
    alias: '@App\Repository'

  # Configure proxy:

  App\Proxy\Repository:
    autowire: true
    # Decoration:
    decorates: App\Repository
    decoration_priority: 10

```

So my question is why this isn't supported and if that is on purpose.

Thanks

**Comment by xabbuh** [comment]
There is an error in your alias configuration. It should look like this:

```
App\RepositoryInterface:
    alias: 'App\Repository'
```

or this:

```
App\RepositoryInterface: '@App\Repository'
```

**Comment by GameplayJDK** [comment]
Oh, seems like I mixed things up there...

You're right, I've changed it as you suggested and everything works fine.

If I remember correctly, at first I didn't use the separate `alias` entry. After adding that, I didn't remove the `@` there. Thank you for pointing that out. This was driving me crazy...

**Comment by xabbuh** [comment]
Nice, let's close here then. :)

**Comment by MatthieuCutin** [comment]
Hi, I'm facing an issue a little bit different. I have 4 services implementing the same interface (I'm using pattern strategy).

I want to decorate every of these 4 services with another.

I can't achieve this with this config :
```yaml
App\Decorator:
    decorates: App\Service1
App\Decorator:
    decorates: App\Service2
App\Decorator:
    decorates: App\Service3
App\Decorator:
    decorates: App\Service4
```
Because of multiple App\Decorator definition

Neither with this one :
```yaml
App\Decorator:
    decorates: App\ServiceInterface
```
Because I got this error : The service "App\Decorator" has a dependency on a non-existent service "App\ServiceInterface" which I totally understand.

What is the correct way to decorate an interface implemented by multiple services ?

**Comment by derrabus** [comment]
Hello @MatthieuCutin and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

**Comment by GameplayJDK** [comment]
Hello @MatthieuCutin,

as I was brought back here by the email notification, I might as well stay and try to answer your question, thought the comment from @derrabus is true, that this matter would better be served on StackOverflow or the slack channels.

Well, as you pointed out, defining multiple services going by the same id is no good option to achieve this. And of course defining a decorator on the interface will only work if that definition exists and has an alias to the interface.

Consider the statement from the [docs](https://symfony.com/doc/current/service_container/service_decoration.html):

> The decorates option tells the container that the App\DecoratingMailer service replaces the App\Mailer service. If you’re using the default services.yaml configuration, the decorated service is automatically injected when the constructor of the decorating service has one argument type-hinted with the decorated service class.

This means that, regardless of the service id ([current convention](https://symfony.com/doc/current/contributing/code/standards.html#service-naming-conventions) is to use the class name as service id to aid the autowiring feature) the service set after `decorates` will be replaced, to my understanding. But this doesn't mean you cannot choose your own custom service id. I'd argue it makes sense to do so in this case. So one way of doing this would be:

```yaml
services:

  app.decorator_for.service1:
    class: App\Decorator
    decorates: App\Service1

  app.decorator_for.service2:
    class: App\Decorator
    decorates: App\Service2

  app.decorator_for.service3:
    class: App\Decorator
    decorates: App\Service3

  app.decorator_for.service4:
    class: App\Decorator
    decorates: App\Service4

```

⚠️ Untested code!

But in a real world use case a CompilerPass would provide more flexibility, since you can automatically tag services based on the interface(s) implemented. In the compiler pass you could then automatically do the decoration of each class implementing your `App\ServiceInterface`.

```yaml
services:

  _instanceof:

    tags: ['app.custom_tag']

```

Note that this will not work globally, but only in your application itself. To achieve automatic tagging behavior across bundles, have a look at [Autoconfiguring Tags](https://symfony.com/doc/current/service_container/tags.html#autoconfiguring-tags) (second paragraph).
