### ISSUE TITLE
[DX] TestContainer should expose a getServiceByTag() method

### ISSUE THREAD

**Issue by bpolaszek** [symfony/symfony#38341]
### Description

Hello there,

In order to improve DX when testing injected services with `!tagged_iterator`, I suggest that `TestContainer` should expose a specific method allowing to retrieve services matching a tag.

### Example

Currently, when we want to test a service, it's quite easy since the `TestContainer` exposes all services as public. 

Consider a service requiring another service and a config:

```php
class SomeService {
    public function __construct(EntityManagerInterface $entityManager, array $config) {
        // ...
    }
  
    public function doStuff(): void {
        // ...
    }
}
```

We can test easily test several instances of that service with a different configuration:

```php
/** @var TestContainer $container */
$em = $container->get(EntityManagerInterface::class);
$configs = [
    ['foo' => 'bar'],
    ['foo' => 'baz'],
];

foreach ($configs as $config) {
    $service = new SomeService($em, $config);
    $service->doStuff();
    // assert something's good or wrong
}
```

Now, what if my service requires an iterable of services?

```php
class SomeService {
    public function __construct(iterable $fooServices, array $config) {
        // ...
    }
  
    public function doStuff(): void {
        // ...
    }
}
```

```yaml
# config/services.yaml
services:
    _defaults:
        bind:
            iterable $fooServices: !tagged_iterator app.foo
```

Currently, the only way to inject `$fooServices` at runtime (unless I didn't figure something out), is to create a service locator in the middle:
```php
<?php

namespace App\Tests\Services;

final class ServicesByTagLocator
{
    /**
     * @var array
     */
    private $services;

    public function __construct(array $services = [])
    {
        foreach ($services as $tag => $service) {
            if (!\is_iterable($service)) {
                throw new \InvalidArgumentException(\sprintf('Provided services for `%s` are not iterable.', $tag));
            }
            $this->services[$tag] = $service;
        }
    }

    public function getServicesByTag(string $tag, bool $throw = true): iterable
    {
        if (!isset($this->services[$tag]) && $throw) {
            throw new \InvalidArgumentException(\sprintf('Unknown tag `%s`.', $tag));
        }

        return $this->services[$tag] ?? [];
    }
}
```

```yaml
# config/services_test.yaml
services:
    _defaults:
        public: true

    App\Tests\Services\ServicesByTagLocator:
        arguments:
            $services:
                app.foo: !tagged_iterator app.foo

```

```php
/** @var TestContainer $container */
$foos = $container->get(ServicesByTagLocator::class)->getServicesByTag('app.foo');
$configs = [
    ['foo' => 'bar'],
    ['foo' => 'baz'],
];

foreach ($configs as $config) {
    $service = new SomeService($foos, $config);
    $service->doStuff();
    // assert something's good or wrong
}
```

Would it make sense that it could be the `TestContainer`'s responsibility?

Thank you,
Ben
