### ISSUE TITLE
Unknown/Invalid parameter in YAML causes php fatal error

### ISSUE THREAD

**Issue by Robsangar** [symfony/symfony#38340]
Symfony CLI 4.16.3

Using an unknown variable or value in a YAML-file cause a php fatal error, while in prod environment

```
eight_points_guzzle:
    clients:
        cha_si:
            # Write here the host where to do requests
            base_url: "%cha.api.base.uri%"xxx
``` 
```
 eight_points_guzzle:
    clients:
        cha_si:
            # Write here the host where to do requests
            base_url: "%cha.api.base.urixxx%"
```

Both cause a fatal error when in prod. In dev and test environment a symfony exception is thrown, as expected. 

Is this possibly a symfony problem, as YAML errors are not handled properly? 

Here is the error displayed in the browser:

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "bal.cha.api.base.urixxx". Did you mean this: "bal.cha.api.base.uri"? in D:\Apps\Apache\bal\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php on line 98
--

**Comment by stloyd** [comment]
You should use Slack channel for such support questions.

Correct value:
```yaml
eight_points_guzzle:
    clients:
        cha_si:
            # Write here the host where to do requests
            base_url: "%cha.api.base.uri%xxx"
```
