### ISSUE TITLE
[Messenger] Logging: With a fingers_crossed strategy, if one message fails, every logs of every messages are reported

### ISSUE THREAD

**Issue by numerogeek** [symfony/symfony#38381]
**Symfony version(s) affected**: 5.1

**Description**  

I have the following strategy for logging : 

```
#config/monolog.yaml
monolog:
  channels: [ messenger_audit ]
#config/prod/monolog.yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            tag: 'Exporter'
        nested:
            type: loggly
            token: '%env(resolve:LOGGLY_TOKEN)%'
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
```
It's supposed to send to loggly every log in case one error is threw.

The problem is : I have a worker set like that : `bin/console mess:cons async_operations -vv --time-limit 3600`

**I figured out that if one message is processed and throw an error, Monolog will shoot to loggly all the logs information, as expected, but also all the log information (INFO etc..) for the following messages, even if they do not fail.**

My guess is that my worker is a single process, so Monolog considers that the whole worker is in error, not only the message, as expected, so it sends everything.

**How to reproduce**  

```
<?php

namespace App\Message\Command;

class Test
{
    /**
     * @var bool
     */
    private $error;

    public function __construct(bool $error)
    {

        $this->error = $error;
    }

    /**
     * @return bool
     */
    public function isError(): bool
    {
        return $this->error;
    }

    /**
     * @param bool $error
     * @return Test
     */
    public function setError(bool $error): Test
    {
        $this->error = $error;
        return $this;
    }

}
```
```
<?php

namespace App\MessageHandler\Command;

use App\Message\Command\Test;
use Symfony\Component\Messenger\Exception\UnrecoverableMessageHandlingException;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

class TestHandler implements MessageHandlerInterface
{


    public function __invoke(Test $message)
    {
        if ($message->isError()) {
            throw new UnrecoverableMessageHandlingException("Unrecoverable MEssage Exception for Test. Sorry");
        }

        return true;
    }
}
```

Send a message with no error, then send with an error, then a no error again, and you'll see the useless logs.

Any idea to have it working as I expect it : habing full logs of a message logged only if it's in error ? 

Thank you
