### ISSUE TITLE
[HttpKernel] Logger makes nginx choke

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#38462]
**Symfony version(s) affected**: probably every including https://github.com/symfony/symfony/pull/36855

**Description**

Now that [HttpKernel’s logger](https://github.com/symfony/symfony/blob/559ebe35fee2ebda9b09aa586f13e8b8207c3ec6/src/Symfony/Component/HttpKernel/Log/Logger.php) uses `error_log` by default, it will make nginx choke with

> upstream sent too big header while reading response header from upstream

if it sends some, using the default php-fpm and nginx docker images.

**How to reproduce**  
1. Start from symfony/skeleton
```bash
composer create-project symfony/skeleton symfony
cd symfony
```

2. Add `docker-compose.yml`
```yml
version: "3"

services:
  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - 80:80
    volumes:
      - ./www.conf:/etc/nginx/conf.d/www.conf:ro
      - ./public:/usr/share/nginx/html:ro

  php:
    image: php:7.4.11-fpm-alpine3.12
    volumes:
      - ./:/var/www/html
```

3. Add `www.conf`
```
server {
    server_name domain.test;
    root /usr/share/nginx/html;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location = /index.php {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;

        internal;
    }
}
```
4. Require some packages
```bash
composer require symfony/security-bundle symfony/stopwatch symfony/web-profiler-bundle
```
5. Start services
```bash
docker-compose up -d
```
6. Make `domain.test` resolve to 127.0.0.1
7. Access http://domain.test/
