### ISSUE TITLE
[Messenger] Option to never remove a message from a transport

### ISSUE THREAD

**Issue by arjanfrans** [symfony/symfony#38497]
**Description**  
As far as I understand a 'max_retries' is always set. What I want to achieve is that any messsages that land in the 'failed' transport will not have a 'max_retries'. 

My use case is that during development, or finding problems on a production system, I need to debug messages. Messages can fail due to a problem in the code. After fixing the problem in the code, I want to retry a message and see if it works again. However, I can only retry 3 times (at least with the default setup). As a workaround I can set the 'max_retries' value a high number. But it would be nice if I just could disable 'max_retries', which having to write a custom retry strategy.

Currently my workflow of dealing failed messages is manually retrying them, mostly one-by-one to be sure. I am wondering if anyone else has a use case for disabling the 'max_retries' limit?

**Example**  
```yaml
framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    disable_max_retries: true # <---------------------------------
                options:
                    queue_name: failed
```
