### ISSUE TITLE
Bind argument was not found in any of the services error

### ISSUE THREAD

**Issue by yellow1912** [symfony/symfony#38569]
**Symfony version(s) affected**: 4.4.15

**Description**  

I have a controller service with a __construct method that expects a parameter passed to it. The parameter is $storeId.

The __construct method looks like this:

```
/**
     * @param ResourceConfigHelperInterface $resourceConfigHelper
     * @param ArrayTransformerInterface $arrayTransformer
     * @param string $storeId
     */
    public function __construct(
        ResourceConfigHelperInterface $resourceConfigHelper,
        ArrayTransformerInterface $arrayTransformer,
        string $storeId
    )
    {
        $this->resourceConfigHelper = $resourceConfigHelper;
        $this->arrayTransformer = $arrayTransformer;
        $this->storeId = $storeId;
    }
```

The controller service is automatically generated (inside a Bundle's Extension's `load` method) (It should be noted that I'm still using the Bundle structure migrated from Symfony 3, not the new recipe in Symfony 4). 
The generated service is set to be autowired, autoconfigured, and with the tag `controller.service_arguments`

```
$definition
            ->setAutowired(true)
            ->setAutoconfigured(true)
            ->addTag('controller.service_arguments');
```

In my services.yml configuration file, I set something like this:

```
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.
    bind:
      $storeId: '%store_id%' # store_id is a defined parameter.
```

And when I run the code, I keep getting the following error:

> You have a "bind" configured for an argument named $storeId. But, this argument was not found in any of the services it was applied to. The bind may be unused and can be removed. Or, the bind may have a typo.

I see that this issue is mentioned already and appears to be fixed: https://github.com/symfony/symfony/issues/28041

I'm unsure what I'm doing wrong here.

**Comment by Nyholm** [comment]
When you are using the `_defaults` key then it is only "defaults" for that file. Not globally. 

If you write something liket his, then it will work: 


```yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    bind:
      $storeId: '%store_id%' # store_id is a defined parameter.

    AppBundle\Controller\DefaultController: ~
```

**Comment by Nyholm** [comment]
You can also add more stuff with wild cards: 

```yaml
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migration,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```
