### ISSUE TITLE
$opsLimit must be 3 or greater for legacy encoder with low time_cost. 

### ISSUE THREAD

**Issue by jazzzpor** [symfony/symfony#38570]
**Symfony version(s) affected**: 4.4.15

**Description**  
When using a time_cost < 3 for a legacy encoder, \Symfony\Component\Security\Core\Encoder\NativePasswordEncoder throws an InvalidArgumentException "$opsLimit must be 3 or greater.".
It is now seemingly impossible to migrate passwords from this legacy encoder. 

**How to reproduce**  
Use the following config in security.yaml:

```
security:
    encoders:
        legacy:
            algorithm: argon2i
            memory_cost: 1024
            time_cost: 2
            threads: 2

        App\Entity\User:
            algorithm: auto
            migrate_from:
                - legacy
```

**Possible Solution**  
Allow $opsLimit < 3 for legacy encoders.

**Comment by wouterj** [comment]
Hi @jazzzpor! Thanks for creating an issue.

I'm not sure if I can completely follow you. The `time_cost` and `memory_cost` are used when *hashing* passwords, not when *verifying* them (the encoder will use the options specified in the password hash).

In fact, the `auto` encoder is able to handle all argon and bcrypt passwords and migrate to the latest settings. So I think the following config is enough for you:

```
security:
    encoders:
        App\Entity\User:
            algorithm: auto
```

(btw I would strongly recommend to increase the default memory costs to fit your server)
