### ISSUE TITLE
[Messenger] Consume a queue from fanout exchange

### ISSUE THREAD

**Issue by redayoub** [symfony/symfony#38630]
**Description**  
I have a microservice 1 from where I need to dispatch a command and then consume it from different microservices 2, 3, ... using different handler logic. The most convinient way to achive this is to use a rabbitmq exchange of type fanout that will dispatch the message to every queue linked to that exchange. This is my config for this:

```yaml
framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        failure_transport: failed

        transports:
            ms:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: ms
                    queues:
                        ms1: ~
                        ms2: ~
                        ms3: ~                        
            failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
            # sync: 'sync://'

        routing:
            'App\Message\Command\PublishMessageCommand': ms
```
The problem is that symfony messenger only allow us to consume from a transport using this command:

```shell
php bin/console messenger:consume ms
```

Running this will consume all messages in the queues (ms1, ms2 and ms3). It there a way to consume from a specific queue inside an exchange using messenger because I know this is possible in other languages like nodejs.

The only solution for this is to create a transport for every microservice using this config:

```yaml
framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        failure_transport: failed

        transports:
            ms1: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=ms1'                      
            ms2: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=ms2'                      
            ms3: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=ms3'                      
            failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
            # sync: 'sync://'

        routing:
            'App\Message\Command\PublishMessageCommand': [ms1, ms2, ms3]
```

**Comment by Nyholm** [comment]
Thank you for a detailed issue. 

If I understand you correctly. You have a producer application A that puts messages to exchange "ms". That exchange is "fanning out" messages to queue "ms1", "ms2" and "ms3". What I fail to understand is why application A would also need to consume these messages form the queue. Isn't that the job for application B, C and D?

> The only solution for this is to create a transport for every microservice using this config

Yes, that seams about right. But your microservice application B will only have this config, right?

```diff
 framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        failure_transport: failed

        transports:
            ms1: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=ms1'                      
-           ms2: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=ms2'                      
-           ms3: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=ms3'                      
-           failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
+           failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed_ms1'
            # sync: 'sync://'

-        routing:
-            'App\Message\Command\PublishMessageCommand': [ms1, ms2, ms3]

```

--------

Remember that in AMQP terminology you are always publishing to an exchange and consuming for a queue.

**Comment by redayoub** [comment]
@Nyholm You're right, I don't need to consume the message from application A. The application B will almost have the same config as what you specified but I don't understand why you removed the routing section, I think it's required to have it if I want to consume the PublishMessageCommand message in the Application B.

I do understand that we always consume from a queue, but what I don't understand if why when using the above config, all queues inside the exchange are consumed at once.

```yaml
transports:
    ms:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
            exchange:
                name: ms
            queues:
                ms1: ~
                ms2: ~
                ms3: ~                        
    failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
```

I think it would be more convenient to be allowed to specify the queue in the consume command using something like.

```shell
php bin/console messenger:consume ms --queue=ms1

```
