### ISSUE TITLE
[Security][BC] Erroneous and inconsistent behaviour of authentication with anonymous users

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/symfony#38657]
**Symfony version(s) affected**: 5.1+, using the new "authenticator" system

**Summary**  

When using the new authenticator based system, and `http_basic` firewall, User who did not provide any credentials get an `AccessDeniedException` instead of an `AuthenticationCredentialsNotFoundException`.
HTTP side, it means User will get a 403 "Forbidden" error instead of a 401 "Unauthorized" error. So no auth prompt will be triggered.

**How to reproduce**  

Config to trigger the issue:
```yaml
# security.yaml
security:
    enable_authenticator_manager: true 

    encoders:
        App\Entity\User: ~

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            http_basic: ~
            pattern: /api
            stateless: true
```

To compare with old behaviour, set `enable_authenticator_manager` to `false`.

**Thoughts**  

The old system was declining anonymous users in the authentication layer, but if `anonymous` firewall was enabled.
In my understanding, in the new system, anonymous users are always accepted, and the authorization layer will block them. I think it is not a safe default, it is "leaky", if you configure a firewall, you don't want user to be able to ever reach authorization layer (as you may forget the `Security` annotation on a controller for instance), and on top of that, Security exceptions are loosing a lot of semantic.
The way around would be for the new system to be more strict, and to re-implement `anonymous` firewall for scenario as #37523 

**Going further: inconsistent behaviour**

While playing around this issue, I tried to implement my own authenticator, such as:
```php
/**
 * This class is not doing anything, just re-extending the provided authenticator.
*/ 
class MyHttpBasicAuthenticator extends HttpBasicAuthenticator
{
    public function __construct(UserProviderInterface $userProvider, ?LoggerInterface $logger = null)
    {
        parent::__construct('My API', $userProvider, $logger);
    }
}
```

```yaml
# security.yaml
security:
    enable_authenticator_manager: true 
    # ...

    firewalls:
        # ...
        api:
            custom_authenticators:
                - App\User\Security\Authenticator\MyHttpBasicAuthenticator
            pattern: /api
            stateless: true
```

And in that case, the issue is fixed: anonymous users will get 401 instead of 403. That's quite surprising and then it creates an inconsistency.
