### ISSUE TITLE
Issue with workflow calling every transitions

### ISSUE THREAD

**Issue by nathan-de-pachtere** [symfony/symfony#38960]
Hey guys ! 

I'm working with Workflow 4.4.16 (SF 4.4), here is the workflow declared in the workflow.yaml file. 

```yaml 
signature:
  type: 'state_machine'
  audit_trail:
     enabled: true
  marking_store:
     type: 'method'
     property: 'state'
  initial_marking: created
  supports:
    - App\Entity\Signature
  places:
    - created
    - code_sent
    - signed
  transitions:
     send_code:
       from: created
       to: code_sent
     sign:
       from: code_sent
       to: signed
```

**Issue** 

When I use $workflow->apply($signature, 'send_code') the SendCode transition is called but after that it automatically call the next onGuard event on Sign (the next transition). And it throw an error because of the code inside the Guard ... That's create beacause my logic is working but I don't want the _sign_ transition trigerred just after the _code_send_

It seems to be the apply() function which test each transition guard and dispatch them. 

Do you have any idea what is happening ?
