### ISSUE TITLE
Maximum function nesting level of '256' reached with retryable http client and mailer handler

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#38970]
**Symfony version(s) affected**: 5.2.0-BETA3

**Description**  
```
monolog:
    handlers:
        mail:
            type: fingers_crossed
            action_level: error
            excluded_http_codes: [ 400, 403, 404 ]
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: mailer
        mailer:
            type: symfony_mailer
            from_email: '%env(resolve:EMAIL_SENDER)%'
            to_email: '%env(EMERGENCY_EMAIL)%'
            subject: 'An Error Occurred! %%message%%'
```
and
```
framework:
    http_client:
        default_options:
            retry_failed:
                http_codes: [ 429 ]

```

leads to 
```
 Maximum function nesting level of '256' reached, aborting!
```
on
```bash
bin/console cache:clear --env=prod
```
**How to reproduce**  
https://github.com/BoShurik/retriyable-http-client-issue
