### ISSUE TITLE
[DI]decorate, access to decorated service argument

### ISSUE THREAD

**Issue by Grummfy** [symfony/symfony#39090]
**Description**  
When you decorate a service, a nice feature would be to have access to the argument of the decorated service. Today, we can only set argument (through \Symfony\Component\DependencyInjection\Loader\Configurator\Traits\ArgumentTrait ).

This allow to decorate a service with some arguments from the decorated service, even if it is build with some "complex" code.

**Example**  

in my services.php

```php
return function(ContainerConfigurator $configurator) {
    $services = $configurator->services();
    // ...
    $services->set(MySendersLocator::class)
        ->decorate('messenger.senders_locator')
        ->args(
            [
                service('@.inner'),
                service('@.innerargs.1')
            ]
        );
```
or service.yaml
```yaml
    Services\MySendersLocator:
        decorates: messenger.senders_locator
        arguments:
            - '@.inner'
            - '@.innerargs.1'
```
Here, I decorate the service 'messenger.senders_locator' who is build ( \Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension::registerMessengerConfiguration ) with some code definition.

So the change will probably need to be done inside \Symfony\Component\DependencyInjection\Compiler\DecoratorServicePass

thanks
