### ISSUE TITLE
Current directory incorrect for Symfony %env(require:PHP_FILE)%

### ISSUE THREAD

**Issue by bbesseling** [symfony/symfony#39149]
The Symfony 5.1 documentation provides an example of setting a configuration parameter from the output of a PHP script:

```yaml
parameters:
  env(PHP_FILE): '../config/.runtime-evaluated.php'
app:
  auth: '%env(require:PHP_FILE)%'
```

Where the content of .runtime-evaluated.php is e.g.:

```php
<?php
$today = new \DateTime();
$spring = new \DateTime('March 1');
$summer = new \DateTime('June 1');
$fall = new \DateTime('September 1');
$winter = new \DateTime('December 1');
if ($today >= $spring && $today < $summer) {
return 'spring';
} else if ($today >= $summer && $today < $fall) {
return 'summer';
} else if ($today >= $fall && $today < $winter) {
return 'fall';
} else {
return 'winter';
}
?>
```

In a number of console commands the current directory is set so that the file is not found.

E.g. in php bin/console cache:clear --env=test:
```
	In EnvVarProcessor.php line 118:                                                                    
	File "../config/.runtime-evaluated.php" not found (resolved from "PHP_FILE").
```

E.g. in php bin/phpunit:
```
	Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\EnvNotFoundException: "File "../config/.runtime-evaluated.php" not found (resolved from "PHP_FILE")."
```

Using Apache and in a few other console commands this works fine:

E.g. in php bin/console make:entity --regenerate 'App\Entity' --env=dev
	but this fails again in --env=prod

E.g. in php bin/console doctrine:schema:update --force --env=dev
	And this one works in --env=prod and --env=test as well

It would be better if EnvVarProcessor.php function getEnv always prepended the application directory unless the path starts with '/'.

**Comment by nicolas-grekas** [comment]
you should use the `resolve:` processor together with DI parameters here:

```yaml
parameters:
  env(PHP_FILE): '%kernel.project_dir%/config/.runtime-evaluated.php'
app:
  auth: '%env(require:resolve:PHP_FILE)%'
```

Please send a PR to the doc if you see something to improve there.
