### ISSUE TITLE
Validator: Allow to define validation rules in YAML or XML for ArrayAccess object .

### ISSUE THREAD

**Issue by videni** [symfony/symfony#39176]
Currently  if we want to validate array, we can only define rules using pure [php code](https://symfony.com/doc/current/validation/raw_values.html),  maybe we can use another altenative.  for example, we  have a `CreateProjectCommand` class which implements  ArrayAccess. 

```
class CreateProjectCommand implements \ArrayAccess
{
    protected $_data = [];

    public function offsetSet($offset, $value)
    {
        $this->_data[$offset] = $value;
    }
   
    public function offsetExists($offset)
    {
        return isset($this->_data[$offset]) || array_key_exists($offset, $this->_data);
    }

    public function offsetUnset($offset)
    {
        unset($this->_data[$offset]);
    }

    public function offsetGet($offset)
    {
        if (isset($this->_data[$offset])) {
            return $this->_data[$offset];
        }
        return null;
    }
}
```
then we can add rules as following
```
App\CreateProjectCommand:
    keys:
        title:
            - Optional:
              - NotBlank:  ~
              - Length:
                  max: 50
        propertyDeveloperId:
            - NotBlank:  ~
        masterImage:
            - File: {maxSize: 5M }
        status:
            - Choice:  ['published', 'draft']
        isCommentable:
            - Type:
                type: bool
                groups: ['Default']
        isVotable:
            - Type:
                type: bool
                groups: ['Default']
        publishedAt:
            - DateTime:
                format: 'Y-m-d H:i:s'
                groups: ['Default']
        permalink:
            - Type:
                type: string
                groups: ['Default']
        tags:
            - Type: 
                type: array
            - All:
                constraints:
                    - Type:
                        type: string
        attributes:
            - Type: 
                type: array
        location:
            - Valid: ~
```

these constaints under keys  are fields of Collection constraint.

# Feature request:

* For GetterMetadata, a getter must exists, for PropertyMetadata, it requires a property, but for array, we can ignore constraints if key is missing.
*  Define validation rules for array using yaml or xml
