### ISSUE TITLE
[BUG] Symfony Yaml 5.2 component reports errors on valid yaml 

### ISSUE THREAD

**Issue by BeyerJC** [symfony/symfony#39229]
**Symfony version(s) affected**: 5,2

**Description**  
I just updated a project to 5.2 and encountered problems with my yaml configuration files. 

Configs that did work before are not failing with an yaml parse error.

```
    App\SwaggerUi\UuidTypeFactory:
        decorates: 'api_platform.json_schema.type_factory'
        arguments: [ '@App\SwaggerUi\UuidTypeFactory.inner' ]  
```
for example now has an error

```
!!  In Inline.php line 94:
!!                                                                                                                  
!!    Unexpected characters near " ]" at line 74 (near "arguments: [ '@App\SwaggerUi\UuidTypeFactory.inner' ]  ").    
```             
Also 
```
elao_enum:
    doctrine:
        types: {}           <--- This one          
```       
Now reports invalid yaml.
                                                                      

**How to reproduce**  
Add one of the configurations above in the config.

**Possible Solution**  
Not yet.

**Comment by Nyholm** [comment]
Hm.. I cannot reproduce. 

```php
    public function testForIssue39229()
    {
        $yaml = <<<YAML
services:
    App\SwaggerUi\UuidTypeFactory:
        decorates: 'api_platform.json_schema.type_factory'
        arguments: [ '@App\SwaggerUi\UuidTypeFactory.inner' ]
YAML;
        $this->assertSame(
            [
                'services' => [
                    'App\SwaggerUi\UuidTypeFactory' => [
                        'decorates' => 'api_platform.json_schema.type_factory',
                        'arguments' => ['@App\SwaggerUi\UuidTypeFactory.inner'],
                    ],
                ],
            ],
            $this->parser->parse($yaml)
        );
    }
```

Maybe you could make a PR with a failing test?

**Comment by BeyerJC** [comment]
Funny enough, your test is already my reproducer :P Not sure if it matters but im on Windows with PHP 7.4.12.
The config didnt change in a while and started failing after my `composer update`.

Executing the test fails in my projects ( i tested on both projects i updated)
```
PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: Unexpected characters near " ]" at line 74 (near "arguments: [ '@App\SwaggerUi\UuidTypeFactory.inner' ]  "). in Project\vendor\symfony\yaml\Inline.php:94
Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Unexpected characters near " ]" at line 74 (near "arguments: [ '@App\SwaggerUi\UuidTypeFactory.inner' ]  "). in Project\vendor\symfony\config\Loader\FileLoader.php on line 173
Stack trace:

Symfony\Component\Config\Exception\LoaderLoadException: The file "Project\src\../config/services.yaml" does not contain valid YAML: Unexpected characters near " ]" at line 74 (near "arguments: [ '@App\SwaggerUi\UuidTypeFactory.inner' ]  ") in Project\src\../config/services.yaml (which is being imported from "Project\src\Kernel.php"). in C:\Development\Projekte\php-apiplatform-product-catalog-service\vendor\symfony\config\Loader\FileLoader.php on line 173
#0 Project\vendor\symfony\yaml\Parser.php(758): Symfony\Component\Yaml\Inline::parse(''@App\\SwaggerUi...', 768, Array)
```

**Comment by xabbuh** [comment]
Can you show the output of `composer show` and also the full contents of your `services.yaml` file?

**Comment by BeyerJC** [comment]
Composer show
```
api-platform/api-pack                v1.3.0     A pack for API Platform
api-platform/core                    v2.5.7     Build a fully-featured hypermedia or GraphQL API in minutes
brick/math                           0.9.1      Arbitrary-precision arithmetic library
composer/package-versions-deprecated 1.11.99.1  Composer plugin that provides efficient querying for installed package versions (no runtime IO)
composer/semver                      3.2.4      Semver library that offers utilities, version constraint parsing and validation.
composer/xdebug-handler              1.4.5      Restarts a process without Xdebug.
doctrine/annotations                 1.11.1     Docblock Annotations Parser
doctrine/cache                       1.10.2     PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                 1.6.7      PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      3.0.2      PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, persistence interfaces, proxies, event system and much more.
doctrine/data-fixtures               1.4.4      Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        2.12.1     Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle             2.2.1      Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle  3.0.1      Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1      The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   1.4.3      PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                1.4.0      A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.1      PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  3.0.1      PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it. It is a very easy to use and a powerful tool.
doctrine/orm                         2.7.4      Object-Relational-Mapper for PHP
doctrine/persistence                 2.1.0      The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter               1.1.1      a PHP SQL highlighting library
elao/enum                            v1.12.2    Enumerations for PHP and frameworks integrations
fig/link-util                        1.1.1      Common utility implementations for HTTP links
firebase/php-jwt                     v5.2.0     A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
friendsofphp/php-cs-fixer            v2.16.7    A tool to automatically fix PHP code style
fzaninotto/faker                     v1.9.1     Faker is a PHP library that generates fake data for you.
guzzlehttp/guzzle                    7.2.0      Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.4.0      Guzzle promises library
guzzlehttp/psr7                      1.7.0      PSR-7 message implementation that also provides common utility methods
hautelook/alice-bundle               2.8.0      Symfony bundle to manage fixtures with Alice and Faker.
justinrainbow/json-schema            5.2.10     A library to validate a json schema.
laminas/laminas-code                 3.5.0      Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager         3.3.0      Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge 1.1.1      Alias legacy ZF class names to Laminas Project equivalents.
league/oauth2-client                 2.6.0      OAuth 2.0 Client Library
monolog/monolog                      2.1.1      Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                    1.10.2     Create deep copies (clones) of your objects
nelmio/alice                         3.7.3      Expressive fixtures generator
nelmio/cors-bundle                   2.1.0      Adds CORS (Cross-Origin Resource Sharing) headers support in your Symfony application
nikic/php-parser                     v4.10.2    A PHP parser written in PHP
ocramius/proxy-manager               2.10.0     A library providing utilities to generate, instantiate and generally operate with Object Proxies
php-cs-fixer/diff                    v1.3.1     sebastian/diff v2 backport support for PHP5.6
phpdocumentor/reflection-common      2.2.0      Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.2.2      With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver          1.4.0      A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                     1.12.1     Highly opinionated mocking framework for PHP 5.3+
phpspec/prophecy-phpunit             v1.1.0     PhpUnit test case integrating the Prophecy mocking library
phpstan/extension-installer          1.0.5      Composer plugin for automatic installation of PHPStan extensions
phpstan/phpstan                      0.12.58    PHPStan - PHP Static Analysis Tool
phpstan/phpstan-doctrine             0.12.25    Doctrine extensions for PHPStan
phpstan/phpstan-phpunit              0.12.16    PHPUnit extensions and rules for PHPStan
phpstan/phpstan-symfony              0.12.11    Symfony Framework extensions and rules for PHPStan
plusnet/keycloak                     1.5.0      Plusnet Keycloak Authentication Bundle
psr/cache                            1.0.1      Common interface for caching libraries
psr/container                        1.0.0      Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0      Standard interfaces for event handling.
psr/http-client                      1.0.1      Common interface for HTTP clients
psr/http-message                     1.0.1      Common interface for HTTP messages
psr/link                             1.0.0      Common interfaces for HTTP links
psr/log                              1.1.3      Common interface for logging libraries
ralouphie/getallheaders              3.0.3      A polyfill for getallheaders.
ramsey/collection                    1.1.1      A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                          4.1.1      A PHP library for generating and working with universally unique identifiers (UUIDs).
ramsey/uuid-doctrine                 1.6.0      Allow the use of ramsey/uuid as a Doctrine field type.
roave/security-advisories            dev-master Prevents installation of composer packages with known security vulnerabilities: no API, simply require it
sebastian/comparator                 4.0.6      Provides the functionality to compare PHP values for equality
sebastian/diff                       4.0.4      Diff implementation
sebastian/exporter                   4.0.3      Provides the functionality to export PHP variables for visualization
sebastian/recursion-context          4.0.4      Provides functionality to recursively process PHP variables
symfony/asset                        v5.2.0     Symfony Asset Component
symfony/browser-kit                  v5.2.0     Symfony BrowserKit Component
symfony/cache                        v5.2.0     Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts              v2.2.0     Generic abstractions related to caching
symfony/config                       v5.2.0     Symfony Config Component
symfony/console                      v5.2.0     Symfony Console Component
symfony/css-selector                 v5.2.0     Symfony CssSelector Component
symfony/debug-bundle                 v5.2.0     Symfony DebugBundle
symfony/debug-pack                   v1.0.9     A debug pack for Symfony projects
symfony/dependency-injection         v5.2.0     Symfony DependencyInjection Component
symfony/deprecation-contracts        v2.2.0     A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.2.0     Symfony Doctrine Bridge
symfony/dom-crawler                  v5.2.0     Symfony DomCrawler Component
symfony/dotenv                       v5.2.0     Registers environment variables from a .env file
symfony/error-handler                v5.2.0     Symfony ErrorHandler Component
symfony/event-dispatcher             v5.2.0     Symfony EventDispatcher Component
symfony/event-dispatcher-contracts   v2.2.0     Generic abstractions related to dispatching event
symfony/expression-language          v5.2.0     Symfony ExpressionLanguage Component
symfony/filesystem                   v5.2.0     Symfony Filesystem Component
symfony/finder                       v5.2.0     Symfony Finder Component
symfony/flex                         v1.10.0    Composer plugin for Symfony
symfony/framework-bundle             v5.2.0     Symfony FrameworkBundle
symfony/http-client                  v5.2.0     Symfony HttpClient component
symfony/http-client-contracts        v2.3.1     Generic abstractions related to HTTP clients
symfony/http-foundation              v5.2.0     Symfony HttpFoundation Component
symfony/http-kernel                  v5.2.0     Symfony HttpKernel Component
symfony/maker-bundle                 v1.24.2    Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bridge               v5.2.0     Symfony Monolog Bridge
symfony/monolog-bundle               v3.6.0     Symfony MonologBundle
symfony/options-resolver             v5.2.0     Symfony OptionsResolver Component
symfony/orm-pack                     v2.0.0     A pack for the Doctrine ORM
symfony/phpunit-bridge               v5.2.0     Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme       v1.20.0    Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer     v1.20.0    Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.20.0    Symfony polyfill for the Mbstring extension
symfony/polyfill-php72               v1.20.0    Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73               v1.20.0    Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.20.0    Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                      v5.2.0     Symfony Process Component
symfony/profiler-pack                v1.0.5     A pack for the Symfony web profiler
symfony/property-access              v5.2.0     Symfony PropertyAccess Component
symfony/property-info                v5.2.0     Symfony Property Info Component
symfony/routing                      v5.2.0     Symfony Routing Component
symfony/security-bundle              v5.2.0     Symfony SecurityBundle
symfony/security-core                v5.2.0     Symfony Security Component - Core Library
symfony/security-csrf                v5.2.0     Symfony Security Component - CSRF Library
symfony/security-guard               v5.2.0     Symfony Security Component - Guard
symfony/security-http                v5.2.0     Symfony Security Component - HTTP Integration
symfony/serializer                   v5.2.0     Symfony Serializer Component
symfony/serializer-pack              v1.0.4     A pack for the Symfony serializer
symfony/service-contracts            v2.2.0     Generic abstractions related to writing services
symfony/stopwatch                    v5.2.0     Symfony Stopwatch Component
symfony/string                       v5.2.0     Symfony String component
symfony/test-pack                    v1.0.7     A pack for functional and end-to-end testing within a Symfony app
symfony/translation-contracts        v2.3.0     Generic abstractions related to translation
symfony/twig-bridge                  v5.2.0     Symfony Twig Bridge
symfony/twig-bundle                  v5.2.0     Symfony TwigBundle
symfony/validator                    v5.2.0     Symfony Validator Component
symfony/var-dumper                   v5.2.0     Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                 v5.2.0     A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                     v5.2.0     Symfony WebLink Component
symfony/web-profiler-bundle          v5.2.0     Symfony WebProfilerBundle
symfony/workflow                     v5.2.0     Symfony Workflow Component
symfony/yaml                         v5.2.0     Symfony Yaml Component
theofidry/alice-data-fixtures        1.3.0      Nelmio alice extension to persist the loaded fixtures.
twig/twig                            v3.1.1     Twig, the flexible, fast, and secure template language for PHP
webimpress/safe-writer               2.1.0      Tool to write files safely, to avoid race conditions
webmozart/assert                     1.9.1      Assertions to validate method input/output with nice error messages.
willdurand/negotiation               v2.3.1     Content Negotiation tools for PHP provided as a standalone library.
```

services.yaml (propably unrelated since the test also fails)

```
parameters:
    app.api_base_path: '%env(API_BASE_PATH)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    lifecycle_marking_store:
        class: App\Workflow\LifecycleMarkingStore

    App\PathResolver\CamelCaseOperationPathResolver: ~

    App\Serializer\DefaultSerializerContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        autoconfigure: false
        autowire: true

    ApiPlatform\Core\Bridge\RamseyUuid\Identifier\Normalizer\UuidNormalizer:
        tags:
            - { name: api_platform.identifier.denormalizer }

    Elao\Enum\Bridge\Symfony\Serializer\Normalizer\EnumNormalizer:
        public: false
        tags: [ 'serializer.normalizer' ]

    App\SwaggerUi\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.api_gateway'
        arguments: [ '@App\SwaggerUi\SwaggerDecorator.inner', '%app.api_base_path%' ]
        autoconfigure: false

    App\SwaggerUi\UuidTypeFactory:
        decorates: 'api_platform.json_schema.type_factory'
        arguments: [ '@App\SwaggerUi\UuidTypeFactory.inner' ]  
```

**Comment by BeyerJC** [comment]
This one did also fail, i made a comment to the lines with errors

```
elao_enum:
    doctrine:
        types: {}       <--- Causing yaml error
    translation_extractor:
        paths:
            App\Enum: '%kernel.project_dir%/src/Enum'
        domain: enum
        filename_pattern: '*.php' 
        ignore: []  <--- caused also a yaml error
    js:
        base_dir: '%kernel.project_dir%/assets/js/symfony/enum'
        lib_path: '%kernel.project_dir%/assets/js/lib/Enum.js'
        paths:
            App\Enum\ValueType: 'ValueType.js'
            App\Enum\UnitOfMeasure: 'UnitOfMeasure.js'
            App\Enum\CharacteristicValueType: 'CharacteristicValueType.js' 
```

**Comment by jvancoillie** [comment]
Hello, I have the same behavior in version 4.4.17 my yaml file which was valid is the following.
```
  services:
    ctuser.user_provider:
        class: AcPoitiers\CTUserBundle\Security\UserProvider
        arguments: ['@ctuser.user_manager', '%ctuser.allow_auto_create%']

    ctuser.token_authenticator:
        class: AcPoitiers\CTUserBundle\Security\TokenAuthenticator
        arguments: [  '@security.token_storage', '@ctuser.credential_extractor' ]
    
    ctuser.credential_extractor:
        class: AcPoitiers\CTUserBundle\Credential\CredentialsExtractor

    ctuser.agent_credential_extractor:
        class: AcPoitiers\CTUserBundle\Credential\AgentCredentialExtractor
        arguments: [ '%ctuser.http_header%', '%ctuser.cookie%' ]
        tags:
            -  { name: ctuser.credential_extractor } 
                    
    ctuser.security.interactive_login_listener:         
        class: AcPoitiers\CTUserBundle\EventListener\LastLoginListener
        arguments: [ '@ctuser.user_manager' ]         
        tags:
            - { name: kernel.event_subscriber }

    ctuser.security.switch_user_listener:
        class: AcPoitiers\CTUserBundle\EventListener\SwitchUserListener         
        arguments: [ '@twig', '@security.token_storage', '@security.authorization_checker' ]         
        tags:             
            - { name: kernel.event_subscriber }
```

which now generates the error
```
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\DependencyInjection\Definition::setArguments() must be of the type array, string given, called in vendor/symfony/dependency-injection/Loader/YamlFileLoader.php on line 449 
```
When I "dump" the services of my yaml we see that the arguments and tags are not correctly parsed.
```
^ array:1 [▼
  "services" => array:6 [▼
    "ctuser.user_provider" => array:2 [▶]
    "ctuser.token_authenticator" => array:2 [▶]
    "ctuser.credential_extractor" => array:1 [▶]
    "ctuser.agent_credential_extractor" => array:3 [▼
      "class" => "AcPoitiers\CTUserBundle\Credential\AgentCredentialExtractor"
      "arguments" => array:2 [▼
        0 => "%ctuser.http_header%"
        1 => "%ctuser.cookie%"
      ]
      "tags" => array:1 [▼
        0 => "name: ctuser.credential_extractor }" <-------------
      ]
    ]
    "ctuser.security.interactive_login_listener" => array:3 [▼
      "class" => "AcPoitiers\CTUserBundle\EventListener\LastLoginListener"
      "arguments" => "r.user_manager' ]"
      "tags" => array:1 [▼
        0 => array:1 [▼
          "name" => "kernel.event_subscriber"
        ]
      ]
    ]
    "ctuser.security.switch_user_listener" => array:3 [▼
      "class" => "AcPoitiers\CTUserBundle\EventListener\SwitchUserListener"
     "arguments" => ",'@security.token_storage', '@security.authorization_checker' ]" <-------------
      "tags" => array:1 [▼
        0 => array:1 [▼
          "name" => "kernel.event_subscriber"
        ]
      ]
    ]
  ]
]
```

**Comment by Nyholm** [comment]
The CI on Windows did not fail in https://github.com/symfony/symfony/pull/39234.

**Comment by BeyerJC** [comment]
```
    App\SwaggerUi\UuidTypeFactory:
        decorates: 'api_platform.json_schema.type_factory'
        arguments: [ '@App\SwaggerUi\UuidTypeFactory.inner' ]  

```
I just noticed that i have 2 whitespaces after the arguments part. If i remove them, the yaml is parsed successfully. Feels strange and im not sure how to describe further. ~The test still fails and does not have those whitespaces.~

Edit: My fault... The test is successful! So the whitespaces in my services.yaml seem to cause the problem. Sorry for the confusion
Edit2: Adding a single whitespace is enough to make the test fail

**Comment by jvancoillie** [comment]
> I just noticed that i have 2 whitespaces after the arguments part. If i remove them, the yaml is parsed successfully. Feels strange and im not sure how to describe further. The test still fails and does not have those whitespaces.

Same for me, when I remove the spaces it works, that was the problem. however the yaml: lint validates my file

**Comment by BeyerJC** [comment]
The whitespace seems to be only a problem when its the EOL. if you make whitespaces and add a comment its fine.

**Comment by rp3e11** [comment]
I have the same problem after updating symfony/yaml to 5.1.9. Thanks for the fix.

**Comment by xabbuh** [comment]
see #39241

**Comment by chris-tip** [comment]
Not sure if related, but also experiencing errors on previously valid yaml:
```yaml
parameters:
    test: 'test\'
services:
```
Results in `InvalidArgumentException` on line 2:
```
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: 
The file does not contain valid YAML: Malformed inline YAML string at line 2 (near "test: 'test\'")
```
It's interesting to see that if line 3 is blank or contains a comment, the error will be reported as `ParseException` on line 3:
```
Symfony\Component\Yaml\Exception\ParseException: 
Malformed inline YAML string at line 3 (near "#services:")
```
