### ISSUE TITLE
Ability to use a placeholder/pattern in routing annotation setting (Yaml)

### ISSUE THREAD

**Issue by xthiago** [symfony/symfony#39369]
**Description**  

I divided my app in some packages and currently I have to add one setting for each package into  `config/routes/annotations.yaml` in order to load all my controllers using Annotations. 

```yaml
# config/routes/annotations.yaml
package1_controllers:
  resource: '../../src/Package1/Controllers'
  type: annotation

package2_controllers:
  resource: '../../src/Package2/Controllers'
  type: annotation
```

New comers doesnt know that and often need help to register controllers of new packages.

It would be very usefull if I could import all controllers using a placeholder or pattern in a single setting like that:

```yaml
# config/routes/annotations.yaml
app_controllers:
  resource: '../../src/*/Controllers'
  type: annotation
```

It would load:

- `../../src/PackageA/Controllers` 
- `../../src/PackageB/Controllers` 
- `../../src/Etc/Controllers`
