### ISSUE TITLE
LDAP complains about missing method

### ISSUE THREAD

**Issue by ipf** [symfony/symfony#39374]
**Symfony version(s) affected**: 5.2.0

**Description**  
After upgrading from 5.1 to 5.2.0 the error `Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\Security\Factory\HttpBasicLdapFactory::registerEntryPoint() in /app/vendor/symfony/security-bundle/DependencyInjection/Security/Factory/HttpBasicLdapFactory.php:48` occurs.

**How to reproduce**  
Upgrade from 5.1 to 5.2 with LDAP Configuration.
security.yaml:

```yaml
security:
  providers:
    admin_provider:
      entity:
        class: App\Entity\Admin\User
        property: username
    user_provider:
      id: App\Security\UserProvider
    my_ldap:
      ldap:
        service: Symfony\Component\Ldap\Ldap
        base_dn: 'OU=Foo,dc=bar,dc=example,dc=com'
        search_dn: 'CN=user,OU=Foo,DC=example,DC=example,DC=com'
        default_roles: ROLE_ADMIN
        search_password: '%env(LDAP_PASSWORD)%'
        uid_key: 'sAMAccountName'
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|fragment)|css|images|js)/
      security: false
    admin:
      provider: my_ldap
      anonymous: true
      lazy: true
      pattern:    ^/admin
      http_basic_ldap:
        service: Symfony\Component\Ldap\Ldap
        dn_string: 'EXAMPLE_DOMAIN\{username}'
        provider: my_ldap
      logout:
        path:   /logout
        target: /admin
    main:
      provider: user_provider
      anonymous: true
      lazy: true
      pattern:    ^/
      form_login:
        login_path: _homepage
        check_path: login
        provider: user_provider
        username_parameter: login_form[_username]
        password_parameter: login_form[_password]
      logout:
        path:   /logout
      guard:
        authenticators:
          - App\Security\IpAuthenticator
        provider: user_provider
        entry_point: App\Security\IpAuthenticator
[...]

```

**Additional context**  

![grafik](https://user-images.githubusercontent.com/557076/101459011-fae18400-3937-11eb-8e87-aa5de5881d73.png)
