### ISSUE TITLE
[FrameworkBundle] Can't use a service as a lock resource

### ISSUE THREAD

**Issue by nesk** [symfony/symfony#39392]
**Symfony version(s) affected**: 5.1+ (didn't try on lower versions)

**Description**  
When using the [service parameters](https://symfony.com/doc/current/service_container.html#service-parameters) syntax `@service_name` with the lock configuration, the string is left as is and is not replaced by the service referenced by the string.

For example, since [the `StoreFactory` supports `RedisCluster` connections](https://github.com/symfony/symfony/blob/fda67f5c3d6a51502f412e0c39df3b6d30ecb347/src/Symfony/Component/Lock/Store/StoreFactory.php#L42), I expect to be able to provide a service parameter referencing a `RedisCluster` instance.

**How to reproduce**  

Install Symfony and the Lock component:
```
composer create-project symfony/website-skeleton:"5.2.x@dev" lock-config
composer require symfony/lock
```

Add a service you want to use with the lock, for example:

```yaml
# config/services.yaml

redis:
    class: Redis
    calls:
        - connect: ['localhost', 6379]
```

Use the service in the lock configuration:

```yaml
# config/packages/lock.yaml

framework:
    lock: '@redis'
```

Then create a lock somewhere, in a controller or a command:

```php
$this->lockFactory->createLock('lock.key')
```

You will get the following error:

```
Unsupported Connection: "@redis".
```
