### ISSUE TITLE
One config.yaml file for 1 package with multiple extentions

### ISSUE THREAD

**Issue by ZED-Magdy** [symfony/symfony#39483]
**Description**  

I've tried to make a socail oauth package so i built the core provider , models and abstract classes for oauth1/oauth2 
i made a twitter and facebook providers etc, but I want to make the providers to be separated into a several packages so user can choose what providers he will use,
the problem is I want 1 config.yaml file to have all the clients for all the extensions is it possible cause I've been searching alot for a solution and didnt find anything
**Example**  

```yaml
oauth_providers:
              client1:
                        client_id:
                        client_secret:
                        redirect_url:
              client2:
                        client_id:
                        client_secret:
                        redirect_url:
```
