### ISSUE TITLE
Messenger message can not be handled by 2 handlers which are registered to a different busses?

### ISSUE THREAD

**Issue by BonBonSlick** [symfony/symfony#39481]
```
Messenger
=========

command.bus
-----------

 The following messages can be dispatched:

 ---------------------------------------------------------------------------------------------------------------         
  App\Application\CQRS\User\Command\UseCase\AuthenticateUser                                                     
      handled by App\Application\CQRS\User\Command\Handler\AuthenticateUserHandler      

event.bus
---------

 The following messages can be dispatched:

 ------------------------------------------------------------------------------------------ 
  App\Domain\UserPack\User\Events\UserRegistered                                            
      handled by App\Infrastructure\EventSourcing\MessageBus\RegisteredNotificationHandler
```

Only the second event.bus handler is called

```

framework:
  messenger:
    default_bus: command.bus

    buses:
      command.bus: # DI = $messageBus
        middleware:
          - validation
          - doctrine_ping_connection
          - doctrine_close_connection
          - doctrine_transaction

      query.bus: # DI = $queryBus
        middleware:
          - validation
      event.bus: # DI = $eventBus,
        default_middleware: allow_no_handlers
        middleware:
          - validation
    transports:
      sync: 'sync://'
      async: 'sync://'
      async_priority_high: 'sync://'
    routing:
```
```

"symfony/cache": "^5.2-dev",
    "symfony/config": "^5.1",
    "symfony/console": "^5.1",
    "symfony/dependency-injection": "^5.1",
    "symfony/event-dispatcher": "^5.1",
    "symfony/filesystem": "^5.1",
    "symfony/finder": "^5.1",
    "symfony/http-foundation": "^5.1",
    "symfony/mailer": "^5.2",
    "symfony/mailgun-mailer": "^5.2",
    "symfony/messenger": "^5.1",
    "symfony/mime": "^5.2",
    "symfony/monolog-bundle": "^3.5",
    "symfony/options-resolver": "^5.1",
    "symfony/psr-http-message-bridge": "^2.0-dev",
    "symfony/requirements-checker": "^2.0.x-dev",
    "symfony/routing": "^5.1",
    "symfony/security-acl": "^v3.0.4",
    "symfony/security-bundle": "^5.1",
    "symfony/security-core": "^5.1",
    "symfony/security-guard": "^5.1",
    "symfony/security-http": "^5.1",
    "symfony/serializer": "^5.1",
    "symfony/templating": "^5.1",
    "symfony/translation": "^5.1",
    "symfony/translation-contracts": "^2.3",
    "symfony/validator": "^5.1",
    "symfony/yaml": "^5.1"
```
 

Solved by  impl-ing more interfaces, but it is a little messy and logic mixing. Thanks for awesome packages.

```
inal class AuthenticateUserHandler implements SubscriberCommandHandlerInterface, EventHandlerInterface {
   public static function getHandledMessages(): iterable {
        // handle this message on __invoke
        yield AuthenticateUser::class;

        // also handle this message on userRegistered event
        yield UserRegistered::class => [
            'method' => 'userRegistered',
            //'priority' => 0,
            //'bus' => 'messenger.bus.default',
        ];
    }
```
