### ISSUE TITLE
constants are not parsed in concated strings in yaml

### ISSUE THREAD

**Issue by c33s** [symfony/symfony#39501]
**Symfony version(s) affected**:^ 4.4

**Description**  
maybe it works as intended but `!php/const` values are not parsed inside a concated string or within `%`. 

**How to reproduce**  

`services.yaml`
```yaml
parameters:
    news.img_dir_suffix: !php/const App\Entity\News::IMG_DIR_SUFFIX

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $imagePath: '%kernel.cache_dir%/!php/const App\Entity\News::IMG_DIR_SUFFIX' # does not work
            string $imagePath: '%kernel.cache_dir%/%!php/const App\Entity\News::IMG_DIR_SUFFIX%' # does not work
            string $imagePath: '%!php/const App\Entity\News::IMG_DIR_SUFFIX%' # does not work
            string $imagePath: !php/const App\Entity\News::IMG_DIR_SUFFIX # works
            string $imagePath: '%kernel.cache_dir%/%news.img_dir_suffix%' # works
```
