### ISSUE TITLE
Permissive regular expression in router has different behavior with GET and POST method

### ISSUE THREAD

**Issue by milabron** [symfony/symfony#39516]
Hello!

Symfony Version: 4.4.15

The problem started when I saw in Google Analytics a route with double slash with my root domain, that is:

`domain.com//`

I've started researching and when I do a GET I get a 404, but if I do a POST I get a valid route.

This is the configuration of my routes:

```
app_controllers:
  resource: '../src/CMS/Controller/'
  type: annotation

app_front_controllers:
  path: /{slug}
  requirements:
    slug: .+
```
`app_front_controllers `in handled through `onKernelRequest `when there is no controller handling that route.

Path to home page with annotations from `app_controllers`:

```
 /**
     * @param Request $request
     *
     * @return Response
     * @Route("/", name="index")
     */
    public function __invoke(Request $request): Response
```

It is as if the GET method is managed internally by Symfony, but the POST method is not.

I think it should have the same behavior either 404 for both methods or a valid route.

Or I don't know if there is something I don't understand, I hope you can help me.

Thanks!
