### ISSUE TITLE
[Security] 'entry_point' could accept a route as well, for convenience

### ISSUE THREAD

**Issue by aleksblendwerk** [symfony/symfony#39520]
**Description**  

It would be convenient if the `entry_point` setting in `security.yaml` would accept a route to redirect to instead of an `AuthenticationEntryPointInterface` implementation as well. I could imagine most of the time those are just redirecting anyway.

**Example**  

Before:

```yaml
# security.yaml
security:
    firewalls:
        main:
            entry_point: App\Security\MainEntryPoint
```

```php
# src/Security/MainEntryPoint.php
<?php

declare(strict_types=1);

namespace App\Security;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface;

class MainEntryPoint implements AuthenticationEntryPointInterface
{
    protected RouterInterface $router;

    public function __construct(RouterInterface $router)
    {
        $this->router = $router;
    }

    public function start(Request $request, AuthenticationException $authException = null): Response
    {
        return new RedirectResponse($this->router->generate('login'));
    }
}
```

After:

```yaml
# security.yaml
security:
    firewalls:
        main:
            entry_point: login
```

Maybe this needs or should have an extra configuration key though, what do you think?

Also routes that need parameters could be a problem I guess.
