### ISSUE TITLE
[Routing] "exclude" option ignored when "resource" doesn't end with "*?{["

### ISSUE THREAD

**Issue by inmarelibero** [symfony/symfony#39588]
**Symfony version(s) affected**: 4.4.*

**Description**  

As described in [Routing docs (v4.4)](https://symfony.com/doc/4.4/routing.html#route-groups-and-prefixes), adding the `exclude` option should be possible when defining routes as annotations.
But, looking at https://github.com/symfony/config/blob/4.4/Loader/FileLoader.php#L81, it seems that `exclude` option is handled only when `resource` options ends with `*?{[`

To note:
- I encountered this (to be confirmed) bug during development, I didn't run many tests
- code in branch [FileLoader.php v5.*](https://github.com/symfony/config/blob/5.x/Loader/FileLoader.php#L85) has changed, so I don't know if the bug still exists in `5.*`

**How to reproduce**  
Very simple routes configuration:
```
# config/routes/annotations.yaml
app:
    resource: '../../src/Controller/'
    type: annotation
    exclude: '../../src/Controller/ExcludedController.php'
```

**Comment by fancyweb** [comment]
Status: reviewed

It's actually working but the resource has to be a glob, `resource: '../../src/Controller/*'` in your case. But it's definitely not intuitive. I think it should work without the /*.

**Comment by inmarelibero** [comment]
@fancyweb but I want `resource: '../../src/Controller/'`, because `resource: '../../src/Controller/*'` would mean to consider only child classes of `../../src/Controller/`, but not the subfolders, while `resource: '../../src/Controller/'` means all classes inside, including subfolders (which is the behaviour I expect)

**Comment by Jeroeny** [comment]
What's the status of this issue? I was planning on opening one before I found this (already had [a reproducer](https://github.com/Jeroeny/reproduce/tree/excl)). 

I assume it's more than just removing the check here: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Config/Loader/FileLoader.php#L74? Otherwise I can contribute a PR.

**Comment by inmarelibero** [comment]
hi @Jeroeny it's still open from my pow, but I guess that from Sf side it's still in "needs review"

I spotted this bug in Sf 4.* but your reproducer may confirm this behaviour also in Sf 5.*, can you confirm?

you are welcome to provide a PR or contribute in any way, I wasn't going to think about a solution before the issue was "certified".

**Comment by Jeroeny** [comment]
Hi @inmarelibero, indeed it's present in Symfony 5.x. I'll create a PR and just see what comes of it.

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by carsonbot** [comment]
Hello? This issue is about to be closed if nobody replies.

**Comment by Jeroeny** [comment]
> Hey, thanks for your report!
> There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

Yes the bug is still there.

**Comment by chr-hertel** [comment]
for my case it worked to go with this glob:

```yaml
controllers:
    resource: ../../src/Controller/**/*
    exclude: ../../src/Controller/Blog
    type: annotation

blog:
    resource: ../../src/Controller/Blog
    type: annotation
    name_prefix: blog_
    prefix: /blog/
```

**Comment by chr-hertel** [comment]
so i think we have two options here:

**option a:** exclude only works with glob patterns (current behavior)
-> documentation should be updated, potentially a warning at runtime/config as well?

**option b:** implement an exclude mechanism for annotations while loading entire directories
-> change FileLoader to handle exclude - AnnotationDirectoryLoader potentially not needed anymore
-> extend LoaderInterface to know about exclude and tackle it in AnnotationDirectoryLoader
-> apply the exclude in YamlFileLoader after RoutingCollection is loaded

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by carsonbot** [comment]
Could I get a reply or should I close this?

**Comment by Jeroeny** [comment]
@carsonbot judging from the comments and duplicate issue, it seems people are still bumping into this.

**Comment by mdeboer** [comment]
@Jeroeny can confirm, this is still a "bug" in 6.1. Just ran into this and glad I found this issue. I think the easiest way is to update the documentation for the time being.

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by mdeboer** [comment]
Came back here again today:

This does not work:
```yaml
controllers:
    resource: ../../src/Controller
    exclude: ../../src/Controller/Blog
    type: annotation

blog:
    resource: ../../src/Controller/Blog
    type: annotation
    name_prefix: blog_
    prefix: /blog/
```

But this does:
```patch
controllers:
-   resource: ../../src/Controller
+   resource: ../../src/Controller/**/*
    exclude: ../../src/Controller/Blog
    type: annotation

blog:
    resource: ../../src/Controller/Blog
    type: annotation
    name_prefix: blog_
    prefix: /blog/
```

Imho the loader should be fixed to either append `/**/*` (so resource is always a glob) or fix the exclude mechanism. I haven't looked into any code yet but this really gets on my nerves and I might spend some of my weekend on this.
