### ISSUE TITLE
Issue when trying to set a service as a global variable (2nd level of nesting)

### ISSUE THREAD

**Issue by LacourQuentin** [symfony/symfony#39654]
**Symfony version(s) affected**:  5.2.0

**Description**  
Encountered an error with the creation of a twig global variable. If you want to get a service as global variable then it has to be at the first level in the twig.yaml file, if you set it at a second level then it won't work anymore

**How to reproduce**  
Twig.yaml file where you will encountered error : 

```
globals:
    application:
        name: 'My app name'
        version: 'My app version'
        description: 'My app description'
        appUsers: '@App\Manager\UserManager'
 ```
        
Twig.yaml file which works fine : 

```
globals:
    application:
        name: 'My app name'
        version: 'My app version'
        description: 'My app description'
    appUsers: '@App\Manager\UserManager'
```
