### ISSUE TITLE
[RateLimiter] [Security] Invalid error message when max login attempts has been reached

### ISSUE THREAD

**Issue by COil** [symfony/symfony#39663]
**Symfony version(s) affected**: 5.2.1

**Description**  

I get the following response: 

```
{
    "code":401,
    "message":"Too many failed login attempts, please try again in %minutes% minute."
}
```

The message should be :  

> Too many login attempts, please try again in 1 minute.

As this feature work for success or failed login attempts, the "failed" word should be removed.

**How to reproduce**  

config/packages/security.yaml: 

    security:
        login:
            pattern:  ^/api/login
            stateless: true
            login_throttling:
                max_attempts: 5
            json_login:
                provider:        app_user_provider
                check_path:      /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

**Possible Solution**  

Missing key + placeholder handling.

**Additional context**  

Using a `json_login` and the lexik_jwt_authentication handlers.

Login via a curl command : 

```
curl -X POST -H "Content-Type: application/json" https://127.0.0.1:8000/api/login_check -d '{"username":"reader","password":"test"}'
```

**Comment by wouterj** [comment]
Ah, I think this works only when translation is enabled (See #38037).

Would you be open to submit a PR to 5.2 that does str_replace/strtr when `null === $this->translator`, to make sure we always replace the message data?

**Comment by shvlv** [comment]
@wouterj Should we encapsulate this behavior in `AuthenticationException`, for example implementing `AuthenticationException::__toString` method?
```php
public function __toString()
{
        return strtr($exception->getMessageKey(), $exception->getMessageData());
}
```

**Comment by YaFou** [comment]
I think it is useless @shvlv. As you can see [here](https://github.com/symfony/symfony/blob/29b88afeb717c3f993c4282a55679e5278084b9f/src/Symfony/Component/ErrorHandler/Exception/FlattenException.php#L54), the error handler will create a flatten exception and will use the `getMessage` method to generate the message. However, we can't override the method because of the final scope. So I don't know how to force the authentication exception to generate the valid message without using the translator.

**Comment by geoffroyp** [comment]
I would like to reopen this ticket because I'm still having this problem with symfony 6.0.8

Here's my firewall config from security.yaml
```
        login:
            provider: app_user_provider
            user_checker: App\Security\KsChecker
            pattern: ^/api/login_check
            stateless: true
            login_throttling:
                max_attempts: 3
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```

Let me know if you need any additional information
