### ISSUE TITLE
[Messenger] RedisTransport can not use both DSN and preconfigured parameters

### ISSUE THREAD

**Issue by edefimov** [symfony/symfony#39834]
**Symfony version(s) affected**: >=5.1.0

**Description**  
Trying to configure redis transport in messenger component via both framework bundle configuration `framework.messenger.transports.*.options` and query parameters in DSN leads to drop of options defined in `framework.messenger.transports.*.options`. 

**How to reproduce**  
1. Configure messenger bundle as follows:
```yaml
framework:
    messenger:
        transports:
            tasks:
                dsn: '%env(APP_REDIS_DSN)%'
                options:
                    stream: my.tasks
                    group: app
                    consumer: app
                    delete_after_ack: true
```
2. Define env variable `APP_REDIS_DSN` with query string
```
APP_REDIS_DSN=redis://localhost?dbindex=2
```
3. Start a consumer
```bash
bin/console messenger:consume tasks
```
4. As a result only dbindex=2 will be passed into redis Connection. Parameters from `framework.messenger.transports.tasks.options` are lost

**Possible Solution**  
Replace [this line](https://github.com/symfony/symfony/blob/729e21c65356880bd9488588e726aa8735dcb52f/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L103) with
```php
parse_str($parsedUrl['query'], $queryOptions);
$redisOptions += $queryOptions;
```

**Additional context**
