### ISSUE TITLE
[Messenger][AmazonSqs] Auto-setup does not work for fifo queues

### ISSUE THREAD

**Issue by starred-gijs** [symfony/symfony#39837]
**Symfony version(s) affected**: 5.x

**Description**  
When you want the AmazonSqs transport to create the queue on the fly and you have a fifo queue, the parameters are wrong, and a regular queue is created.

**How to reproduce**  
Use a queue name with a `.fifo` suffix and make sure the queue does not exists yet, eg:
```yaml
framework:
  messenger:
    transports:
      fifo_queue:
        dsn: 'sqs://localhost:9494/messages.fifo'
```

**Possible Solution**  
Fix the parameter structure for the `createQueue` method. (PR will be submitted soon)
