### ISSUE TITLE
[Messenger] Messenger transport options are merged with numbers as keys

### ISSUE THREAD

**Issue by svitiashchuk** [symfony/symfony#39846]
**Symfony version(s) affected: 4.4**

**Description**
Messenger config `options` array merged wrong. Values inside specific environment config of `options` array are merged to common config with numbers as keys.

**How to reproduce**

1. Create `messenger.yaml` in `config/packages/` with following contents:

```yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            options:
                auto_setup: false
```

2. Then, create another, for example, for the test environment `config/packages/test/` and add options there:
```yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            options:
                wait_time: 60
```

3. Run console debug:config:
```bash
console debug:config framework
```

```bash
#...
messenger:
    transports:
        async:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            options:
                auto_setup: true
#...
```

4. Run console debug:config for test-environment:
```bash
APP_ENV=test console debug:config framework
```
Output for test-environment:
```bash
#...
messenger:
    transports:
        async:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            options:
                auto_setup: true
                0: 60
#...
```

**Additional context**

That's happened because in ConfigTree options are defined as `arrayNode` and has a `prototype('variable')`. So for combining config together `PrototypedArrayNode::mergeValues()` would be called. And there is an issue. For those `PrototypedArrayNode` that have not `$keyAttribute` `$rightSide` values added without keys:
```php
foreach ($rightSide as $k => $v) {
    // prototype, and key is irrelevant, append the element
    if (null === $this->keyAttribute) {
        $leftSide[] = $v;
        continue;
    }
```

**Possible soultion**
So the solution is to add `useAttributeAsKey` inside ConfigTree for arrayNode('options'). PR will be submitted soon
