### ISSUE TITLE
cache.adapter.phpfiles missing

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#39879]
**Description**  
Although Symfony ships with services for most cache adapters, the equivalent service that should exist under `cache.adapter.phpfiles` representing an instance of `Symfony\Component\Cache\Adapter\PhpFilesAdapter`, is missing.

Moreover, specifying the service manually is non-trivial. The following definition will fail to compile:

```yaml
# services.yaml
cache.adapter.phpfiles:
  class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
```

>Service "cache.app": Cannot replace arguments if none have been configured yet.

Although not at all intuitive, it is required to redeclare the first argument's default.

```yaml
# services.yaml
cache.adapter.phpfiles:
  class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
  arguments:
    - ''
```

Shipping the service definition with Symfony would solve these issues.

**Example**  
```yaml
# cache.yaml
framework:
  cache:
    app: cache.adapter.phpfiles
```
