### ISSUE TITLE
upgrade to dependency-injection 5.1.9 leads to error

### ISSUE THREAD

**Issue by elvodian** [symfony/symfony#39877]
**Symfony version(s) affected**: 5.1

**Description**  
When I upgrade the `symfony/dependency-injection` bundle from 5.1.8 to 5.1.9 our Symfony project fails with this error:
```
It's a requirement to specify a Metadata Driver and pass it to Doctrine\ORM\Configuration::setMetadataDriverImpl().
```

When I debug into the compiled container I can see that the calls to the setter methods for `\Doctrine\ORM\Configuration` are missing completely, which have been there before the upgrade. It seems there has been a change in the PhpDumper that makes it ignore them. (I tracked this down by manually reverting all other changes between the two versions.)

I tried with upgrading all packages to Symfony 5.2 and from Doctrine 2 to 3 but the error remains the same.

**How to reproduce**  
Doctrine configuration:
```
doctrine:
  dbal:
    driver: '%env(DATABASE_DRIVER)%'
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    dbname: '%env(DATABASE_NAME)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
    server_version: '%env(DATABASE_VERSION)%'

    charset: utf8mb4
    default_table_options:
      collate: utf8mb4_unicode_ci
    options:
      1002: 'SET CHARACTER SET utf8mb4;'

    mapping_types:
      enum: string

  orm:
    auto_generate_proxy_classes: FILE_NOT_EXISTS
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    metadata_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.app_cache_pool
```

Just calling `bin/console` gives the error already.

Locking down the version of `symfony/dependency-injection` to `5.1.8` works perfectly, any version higher than that produces the described behaviour.
