### ISSUE TITLE
[RateLimiter] TypeError when using "no_limit" policy

### ISSUE THREAD

**Issue by Jontsa** [symfony/symfony#39899]
**Symfony version(s) affected**: 5.2

**Description**  
When using "no_limit" policy with rate limiter, for example during tests, [NoLimiter](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/RateLimiter/Policy/NoLimiter.php#L37) passes `\INF` as constructor argument to [RateLimit](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/RateLimiter/RateLimit.php#L28) which expects integer and this will result in TypeError.

`TypeError: Argument 1 passed to Symfony\Component\RateLimiter\RateLimit::__construct() must be of the type int, float given, called in /home/jontsa/Code/demo/vendor/symfony/rate-limiter/Policy/NoLimiter.php on line 37`

**How to reproduce**  
Install symfony/rate-limiter component and configure limit using no_limit policy

```
# config/packages/rate_limiter.yaml
framework:
  rate_limiter:
    anonymous_api:
      policy: 'no_limit'
      limit: 10
      interval: '1 minute'
```

Then attempt to consume one token using this limiter:

```
    private function checkAnonymousRateLimit(Request $request, RateLimiterFactory $anonymousApiLimiter) : void
    {
        $limiter = $anonymousApiLimiter->create($request->getClientIp());
        $limit = $limiter->consume(1);
        if (false === $limit->isAccepted()) {
            throw new TooManyRequestsHttpException();
        }
    }
```

**Possible Solution**  

**Additional context**
