### ISSUE TITLE
Impersonate user header doesn't work

### ISSUE THREAD

**Issue by Viktor-Bredihin** [symfony/symfony#39907]
**Symfony version(s) affected**: 5.2.0

**Description**  
https://symfony.com/doc/current/security/impersonating_user.html
the documentation says 
`Instead of adding a _switch_user query string parameter, you can pass the username in a HTTP_X_SWITCH_USER header.` however it doesn't work, so I have to use query parameter _switch_user

**How to reproduce**  
set up new symfony project and follow instruction from the documentation https://symfony.com/doc/current/security/impersonating_user.html using header solution instead of query parameter

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by OskarStark** [comment]
Do you get any errors or log entries?

**Comment by stof** [comment]
the implement seems to expect a `_switch_user` header (same name than the query param), not a `x_switch_user` one.

**Comment by Viktor-Bredihin** [comment]
@stof 
thanks for reply, but I tried it too and it doesn't work as well

@OskarStark 
I didn't have time to prepare example yet

**Comment by jorissae** [comment]
In your security.yaml you can do it:

```yaml       
main:
          pattern: ^/
          switch_user:
              parameter: 'HTTP_X_SWITCH_USER'
```

In the listener there is: (Symfony\Component\Security\Http\Firewall\SwitchUserListener)

```php
$username = $request->get($this->usernameParameter);
        if (null === $username || '' === $username) {
            $username = $request->headers->get($this->usernameParameter);
        }
```


why not do something close to that (to comply with the doc):

```php
$username = $request->get($this->usernameParameter);
        if (null === $username || '' === $username) {
            $username = $request->headers->get($this->usernameParameter, $request->headers->get('HTTP_X_SWITCH_USER'));
        }
```

**Comment by fbourigault** [comment]
The documentation is weird on this point. As `ServerBag` removes `HTTP_` prefixes from server variables, you have to provide, with the default configuration a `_Switch-User` header.

Which translate to `$_SERVER['HTTP__SWITCH_USER']` (note the double `_` here).

If you configure `parameter: HTTP_X_SWITCH_USER` (which translate to `$_SERVER['HTTP_HTTP_X_SWITCH_USER`), you have to send a `Http-X-Switch-User` header to get impersonation working.

I used to configure `parameter: x_switch_user` so I can use `X-Switch-User` header.

**Comment by Gu3** [comment]
yep, works for me too if, in my config : 

       switch_user:
                parameter: X-Switch-User
                
PS : If you use nelmios_cors, think to update the config too : 

```
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Authorization', 'x-switch-user']
        
```
