### ISSUE TITLE
[Messenger] multiple custom middleware on my bus

### ISSUE THREAD

**Issue by xfifix** [symfony/symfony#39922]
**Symfony version(s) affected**: 4.4.17

**Description**  
I put two middleware on my messenger bus and when i try it with xdebug i enter juste one middleware and not in the second !

**How to reproduce**  
```yaml
            messenger.bus.events:
                default_middleware: false
                middleware:
                    - 'App\Bundle1\Middleware\Middleware1'
                    - 'App\Bundle2\Middleware\Middleware2'
```

And here is the content of the middleware to test

```php

class Middleware1 implements MiddlewareInterface
{

    public function __construct()
    {
    }

    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        return $stack->next()->handle($envelope, $stack);
    }

}
```

On my debug console, they are well declared. 

a quick example : [example](https://github.com/xfifix/middleware-exemple)
