### ISSUE TITLE
Translation domain overrides no longer being used

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#40014]
**Symfony version(s) affected**: 4.4.19

**Description**  
After upgrading from 4.4.18 to 4.4.19, my custom translation messages for the `security` domain is no longer being used.

**How to reproduce**  
1. Create `translations/security.en.yml` with the following contents:
    ```yaml
    "Invalid credentials.": Custom Message!
    ```
2. My translator config looks like the following:
    ```yaml
    framework:
        default_locale: en
        translator:
            default_path: '%kernel.project_dir%/translations'
            fallbacks:
                - en
    ```
3. In a twig template:
    ```twig
    {{ 'Invalid credentials.'|trans([], 'security') }} {# resolves to "Invalid credentials." but expected "Custom Message!" #}
    ```

**Possible Solution**  
I looked though the changes from 4.4.18 to 4.4.19 but couldn't pinpoint exactly what caused this bug.

**Additional context**  
~I can work on a reproducer.~ Reproducer: https://github.com/kbond/symfony-reproducer/tree/bug/trans-domain:
- [Commit demonstrating issue on 4.4.19](https://github.com/kbond/symfony-reproducer/commit/c87fd1b94780b92b98e097dae16ba99640acc2ea)
- [Commit that fixes issue (by downgrading to 4.4.18)](https://github.com/kbond/symfony-reproducer/commit/0c4364822b43b62c333b02c01e84b6fcb30bf1f7)
