### ISSUE TITLE
[Mailer] Add CC / BCC to mailer envelope configuration

### ISSUE THREAD

**Issue by grimabe** [symfony/symfony#40013]
**Description**  
In the **Mailer Component** we can configure the **recipients** list of the envelope in order to override the recipients which is really useful in dev environment. 
I am looking to have the same behaviour for CC and BCC fields and I don't think it is possible yet.

**Main reason?** It avoids sending emails to CC or BCC address In DEV environment 

**Example**  

**Before (Current configuration)**

```yaml
# config/packages/dev/mailer.yaml
framework:
    mailer:
        envelope:
            recipients: ['youremail@example.com']
```

**After with CC and/or BCC**
```yaml
# config/packages/dev/mailer.yaml
framework:
    mailer:
        envelope:
            recipients: ['youremail@example.com']
            cc: ['youremail@example.com']
            bcc: ['youremail@example.com']
```

**Or simply by removing CC and BCC**
```yaml
# config/packages/dev/mailer.yaml
framework:
    mailer:
        envelope:
            recipients: ['youremail@example.com']
            cc: []
            bcc: []
```

I'll be glad to come up with a PR to update the different transports if this is something that people would go for.
Thanks for the feedback.
