### ISSUE TITLE
HttpClient Bearer

### ISSUE THREAD

**Issue by ericc70** [symfony/symfony#40085]
**Symfony version(s) affected**: 5.2.3

**Description**  
HttpClient does not authenticate through the Bearer method.
$ -client-> request ('METHOD', 'uri') return a 401 error and  "www-authenticate: Bearer realm =" Doorkeeper ", error =" invalid_token ", error_description =" The access token is invalid ""

The configuration parameters are in the framework.yaml file.

**Comment by xabbuh** [comment]
If you think that you discovered a bug, please provide more detailed information that allow to reproduce your issue.

**Comment by nicolas-grekas** [comment]
Maybe you have a space in your bearer? That's not allowed (see #38647)

**Comment by ericc70** [comment]
In framework.yaml
```
http_client:
        scoped_clients:
            mamot_api:
                base_uri: '%env(MASTODON_INSTANCE)%'
                auth_bearer: '%env(MASTODON_JETON)%' 
```
In my class 

```
class MastodonApiService{

    private $getParam;

    public function __construct(ParameterBagInterface $getParams, HttpClientInterface $mamotApi )
    {
        $this->getParams = $getParams;
        $this->client = $mamotApi ;
    }

    public function test(){

 
        $jeton = "Bearer ". $this->getParams->get('MASTODON_JETON');
        
```
it's works
```
         $response=$this->client->request('GET', "https://mamot.fr/api/v1/accounts/verify_credentials"
         ,[
            'headers' => [
                 'Authorization' => $jeton
             ],

         ] );

```
it doesn't work,  it gives me error 401 
```
    $response=$this->client->request('GET', 'api/v1/accounts/verify_credentials');

```
it works with endpoints without authentication 
and the same example function under symfony 4.4 

Sample Repository : https://github.com/ericc70/HttpClientSample.git

**Comment by Nyholm** [comment]
Try send a request to here: https://requestbin.com/r

That way you can inspect what you actually are sending.

**Comment by xabbuh** [comment]
@ericc70 Did https://github.com/symfony/symfony/issues/40085#issuecomment-774503037 give you any more insight?

**Comment by ericc70** [comment]
the error comes from the base url, (www.) 

with symfony 4.4
```
#.env

MASTODON_INSTANCE='https://www.mamot.fr/' # it work
MASTODON_INSTANCE='https://mamot.fr/' # it work
```

with symfony 5.2
```
#.env

MASTODON_INSTANCE='https://www.mamot.fr/' # don't work
MASTODON_INSTANCE='https://mamot.fr/' # it work
```

**Comment by Nyholm** [comment]
Interesting. This seams like a feature. 

When you are redirected to a different domain, then authentication should not be copied to the new request. We discussed this in Guzzle. There is a potential security risk by spreading authentication around over different domains.

**Comment by nicolas-grekas** [comment]
Oh, of course. Then why does this work on 4.4? Which version of 4.4 exactly in case one would like to investigate?

**Comment by stof** [comment]
Could it be that a different implementation of the HttpClient is selected (and that they have different behavior here) ?

@ericc70 please add a `var_dump(get_class($this->client));` to see it in each case.

**Comment by ericc70** [comment]
Indeed, I had several implementations of HttpClient on version 4.4. 
Sorry for this issue and thank you to you.

**Comment by nicolas-grekas** [comment]
Can you please tell us which ones? Because maybe there is a bug as I'm not sure why two different clients would work diferently.

**Comment by ericc70** [comment]
```
    http_client:
        scoped_clients:
            mamot_api:
       
                base_uri: 'https://www.mamot.fr'
         
          
            mamotApi:
                
                base_uri: 'https://mamot.fr'
          
````
