### ISSUE TITLE
Allow extra fields on memory users config.

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony#40091]
**Description**  
Actually, if you use memory provider, you can only define few attributes (username, password, roles).
It will be nice, if you can define custom attributes.

**Example**
security.yml
```
security:
    providers:
        app_provider:
            memory:
                users:
                    adrien:  { password: pwd, roles: ['ROLE_USER'], extra: {gender: m} }

```
Somewhere.php
`  $user->getExtraFields()['gender'];`
Class `Symfony\Component\Security\Core\User\User` already has $extraFields attribute.
