### ISSUE TITLE
Infobip notifier UnsupportedSchemeException "The infobip scheme is not supported"

### ISSUE THREAD

**Issue by zohurul-portonics** [symfony/symfony#40095]
**Symfony version(s) affected**: 5.2.1
notifier: 5.2.2
infobip-notifier: 5.2.2

**Description**  
Unable to send the notification through infobip
always throw UnsupportedSchemeException "The infobip scheme is not supported".

**How to reproduce**  
```
$notification = (new Notification('New Invoice', ['sms']))
            ->content('You got a new invoice for 15 EUR.');

        // The receiver of the Notification
        $recipient = new Recipient(
            "z***@****.com",
            "***9"
        );

        // Send the notification to the recipient
        $sentMessage = $notifier->send($notification, $recipient);
```
**Additional context**   
```
#config/packages/notifier.yaml
framework:
    notifier:
        chatter_transports:
            rocketchat: '%env(ROCKETCHAT_DNS)%'
        texter_transports:
            infobip: '%env(INFOBIP_DSN)%'

        channel_policy:
            # Use SMS, Slack and email for urgent notifications
            urgent: ['sms', 'chat/rocketchat', 'email']

            # Use Slack for highly important notifications
            high: ['chat/rocketchat']
```
