### ISSUE TITLE
[Cache][DI] Autowiring priority of default pools vs customs

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#40109]
```yaml
framework:
    cache:
        pools:
            app.cache.redis.tag_aware:
                adapter: "cache.adapter.redis"
                provider: "%env(REDIS_URL)%/1"
                tags: true
```

```php
<?php

namespace App;

use Symfony\Contracts\Cache\TagAwareCacheInterface;

final class MyService
{
    private TagAwareCacheInterface $cache;

    public function __construct(TagAwareCacheInterface $cache)
    {
        $this->cache = $cache;
    }
}
```

With autowiring on, I really expected that the $cache that would be injected in my service would be my custom one, not the default one (`cache.app.taggable`). I noticed the same problem with `CacheInterface` and `cache.app`. Firstly, shouldn't there be an autowiring conflict since there are several definitions for `TagAwareCacheInterface`? Secondly, shouldn't we prioritize the custom pools? I noticed this only after a deployment :sweat_smile:
