### ISSUE TITLE
[Security][Authenticator-based] Multiple providers

### ISSUE THREAD

**Issue by mpiot** [symfony/symfony#40158]
**Symfony version(s) affected**: 5.2.3

**Description**  
When using the new Authenticator-based Security with multiple providers, the `UserBadge` do not use the provider config in the firewall.

```yml
security:
    enable_authenticator_manager: true

    encoders:
        App\Entity\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\User: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

        logbook_user_provider:
            memory:
                users:
                    logbook:
                        password: '%env(APP_LOGBOOK_USER_PASSWORD)%'
                        roles: 'ROLE_LOGBOOK_USER'

    firewalls:
        logbook:
            host: '%logbook_subdomain%'
            pattern: ^/logbook-entry
            provider: logbook_user_provider
            http_basic: ~

        main:
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AppLoginAuthenticator
            logout:
                path: app_logout
```

In that exemple, when I use the `UserBadge` in `App\Security\AppLoginAuthenticator`, the Badge try to retrieve the user in the `logbook_user_provider` and not in `app_user_provider`.

I can use a callback as second argument in the `UserBadge`, and it works. But I think, because we define the Entity provider as provider in the firewall, we expect to use automatically that provider.

**Comment by wouterj** [comment]
Hi @mpiot! Thanks for filling in a bug report.

If I'm looking at the code, it should take into account the firewall provider (line 345 & 350): https://github.com/symfony/symfony/blob/907ef311bf789f5641dfc718a5a59dcd9fd5ace4/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L341-L351

Are you maybe able to create a minimal application that reproduces this issue? That would help a lot in debugging this :)

**Comment by mpiot** [comment]
Hi @wouterj, I can share you the branch where I try to use the new Authenticator : 
https://github.com/mpiot/avirontours/tree/feature/security-authenticator-based-update

I’ll watch tonight in the part of code you shared, if I find something. At the moment I’ve just dump and die in the UserBadge the provider and see that it is the in_memory one.

And if needed, do a little app that just handle authentication.

**Comment by mpiot** [comment]
@wouterj It seems the symfony/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php is executed on cache generation then never trigger after (I think it's logical with caching and it's why we want).
But, because we have 2 firewall that use 2 differents providers, at the initiation we enter twice in the definition of the provider, if I dump after the definition of the provider I have:

```
^ "security.user.provider.concrete.logbook_user_provider"
^ "security.user.provider.concrete.app_user_provider"
```

Then it only keep one of them ? (strangely, not the last)
If I define 2 providers, but don't have a firewall entry that use the second, I've not this problem. Maybe because each one set its own provider ?

**Comment by franzwilding** [comment]
I can confirm the same problem: 
- Defining one provider and using it for two different firewalls works fine
- Defining two providers but only using one of them works fine
- Defining two providers and using both on different firewalls will use the wrong provider for the firewall

When trying to use the `FormLoginAuthenticator` on the `api_admin` firewall, I can see in the logs that the security system uses the `event_embed_code` user provider instead of `users`
```
providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'username'
        event_embed_code:
            entity:
                class: 'App\Entity\EventEmbedCode'
                property: 'token'

firewalls:
   api_event:
            pattern: ^/api/event
            provider: event_embed_code
            stateless: true
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
                - 

   api_admin:
            pattern:   ^/api
            context: admin
            provider: users
            custom_authenticators:
                - App\Security\FormLoginAuthenticator
```

**Comment by franzwilding** [comment]
I think the problem is, that `Symfony\Component\Security\Http\EventListener\UserProviderListener` sets the first defined userProvider to all passports. Instead of that, the listener should do some checking to see if the provider is defined for the given passport.

**Comment by jrushlow** [comment]
I had a similar issue today - just out of curiosity - do your authenticators have a `UserProviderInterface::class` as a constructor arg?

If so and if you haven't already tried doing so:

```yaml
#config/services.yaml

services:
    App\Security\AuthenticatorA:
        arguments:
            $userProvider: '@security.user.provider.concrete.user_provider_a'

    App\Security\AuthenticatorB:
        arguments:
            $userProvider: '@security.user.provider.concrete.user_provider_b'
```
