### ISSUE TITLE
[RFC] Support env-dependent config in one yaml file

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#40215]
Inspired by https://github.com/symfony/symfony/pull/40214

For routing/DI, it might be worth merging per-env yaml files (as found in recipes) in one, don't you think?

My proposal would be to go with a suffix:

```yaml
services@dev:
    App\FooForDev: ~

framework:
    secret: '%env(APP_SECRET)%'

framework@test:
    test: true
    session:
        storage_factory_id: session.storage.mock_file
```

WDYT?

**Comment by nicolas-grekas** [comment]
Alternative, using yaml tags:
```yaml
prod: !env
    services:
        App\FooForDev: ~

framework:
    secret: '%env(APP_SECRET)%'

test: !env
    framework:
        test: true
        session:
            storage_factory_id: session.storage.mock_file
```

**Comment by kaznovac** [comment]
imho this is not worth the implementation effort - it's somewhat burdensome (as it requires developer to learn extra micro-syntax), and it's not substantially better than the folder solution already in place.

here are my 2 penny worth on the somewhat more flexible but more verbose yaml syntax:
```yaml
services:
    App\FooForDev:
        class: ~
        condition: '@=container.getEnv('APP_ENV') == "test"' # symfony expression

framework:
    secret: '%env(APP_SECRET)%'

conditional:
    condition: '@=container.getEnv('APP_ENV') == "test"' 
        framework:
            test: true
            session:
                storage_factory_id: session.storage.mock_file
```


in the long run i'd like to see symfony strive to use **php configuration** more (and phase out yaml/xml) - it's simply more ide friendly and easier to parse in run/compile time, and i personally find it easier to understand (it's more concise and has deterministic meaning) and with less cognitive load.

**Comment by javiereguiluz** [comment]
Here's a proposal for an alternative notation: use `@dev`, `@prod`, `@test` as the special prefixes under which you can define services/params only for dev/prod/test:

```yaml
framework:
    secret: '%env(APP_SECRET)%'

@dev:
    services:
        App\FooForDev: ~

@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.mock_file
```
