### ISSUE TITLE
Consuming from failed transport not checking for all busses

### ISSUE THREAD

**Issue by vladanzivanovic** [symfony/symfony#40274]
**Symfony version(s) affected**: 4.4

**Description**  

In service.yaml I have handler with this configuration

`app.messenger.handler.event.abacus.order_invoice:`
        `class: App\MessageHandler\AdapterAbacusOrderInvoiceMessageHandler`
        `tags: [{ name: messenger.message_handler, bus: app.kafka_consumer_bus }]`

If I remove bus: app.kafka_consumer_bus from tag everything is fine when running messenger:failed:retry command,
but with bus option it's not working because it cannot find handler. This is error message
"No handler for message "App\Message\AdapterAbacusOrderInvoiceMessage"."

**How to reproduce**  

Create a service and set bus option in tag for handler. Send message in failed transport and try to retry with command. Message will be redeliver into failed transport again because it cannot find handler. You can check in log file.

**Possible Solution**  

So, there should be additional param for failed command to set bus, or it should look for all busses and also maybe error message should be changed according to the error that happens.

Add bus option to command like this:
`messenger:failed:retry --bus app.kafka_consumer_bus`
**Additional context**

**Comment by derrabus** [comment]
Please provide steps to reproduce your problem.

**Comment by vladanzivanovic** [comment]
Well I found what is the problem, in service.yaml I have handler with this configuration
```yaml
app.messenger.handler.event.abacus.order_invoice:
        class: App\MessageHandler\AdapterAbacusOrderInvoiceMessageHandler
        arguments:
            - '@monolog.logger.messenger-consume'
            - '@app.repository.order_invoice'
            - '@sylius.repository.order'
            - '@app.factory.order_invoice'
            - '@app.manager.order_invoice'
            - '@sylius.email_sender'
            - '@app.media.api.client'
        tags: [{ name: messenger.message_handler, bus: app.kafka_consumer_bus }]
```

If I remove `bus: app.kafka_consumer_bus` from tag everything is fine when running `messenger:failed:retry` command,
but with bus option it's not working because it cannot find handler. This is error message 
"No handler for message "App\Message\AdapterAbacusOrderInvoiceMessage"."

So, there should be additional param for failed command to set bus, or it should look for all busses and also maybe error message should be changed according to the error that happend.

For eg. messenger:failed:retry --bus app.kafka_consumer_bus
