### ISSUE TITLE
[Security][Authenticator-based] hide_user_not_found is not supported in the authenticator-based security

### ISSUE THREAD

**Issue by mynameisbogdan** [symfony/symfony#40275]
Since it's a security concern I'm filling this as bug report.

**Symfony version(s) affected**: 5.2.x

**Description**  
`FormLoginAuthenticator` doesn't have support for [`hide_user_not_found`](https://symfony.com/doc/current/reference/configuration/security.html#hide-user-not-found) so we're getting `Username could not be found.` on the login page.

**How to reproduce**  
```yaml
#  config/packages/security.yaml
security:
    enable_authenticator_manager: true
```
Input a wrong username in the form login and submit the form.

**Additional context**  
![Screenshot 2021-02-23 at 10 54 36](https://user-images.githubusercontent.com/707714/108820951-94c6dd80-75c5-11eb-8bf1-cd98ad568d73.jpg)
