### ISSUE TITLE
Permit integer type for default_index_method in tagged locators

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#40319]
**Description**
Currently, [tagged locators](https://symfony.com/doc/current/service_container/service_subscribers_locators.html#indexing-the-collection-of-services) using the `default_index_method` static method name pointer [must point to a method whose return type is `string`](https://github.com/symfony/symfony/blob/v5.2.3/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php#L143). However, my objects expose integer keys. Rather than rewrite my application to fit Symfony (where string does not make sense to the application), I think it better that Symfony should accept integer keys and internally convert them to string if so needed.

**Example**
```yaml
  MyService:
    arguments:
      $foo: !tagged_locator
        tag: my_tag
        default_index_method: myStaticMethod # returns integer
```
