### ISSUE TITLE
Add Username and Password in Mailer configuration tree

### ISSUE THREAD

**Issue by MAGlCUS** [symfony/symfony#40329]
### Description

Currently the configuration of the Mailer component is done through a "dsn" parameter in the environment file or in the configuration file "mailer.yml". This configuration must include both the user and the password of the mail server in case it is authenticated. For example:
_env(file):_ 
`MAILER_DSN=smtp://user:pass@host:port.`

However, the configuration of the database connection allows these parameters (username and password) in the "dsn" and can also be in the configuration of the "doctrine.yml" file as independent parameters. This allows the "Secrets" functionality to be used to securely store this data.

We can have either:
_env(file):_
`DATABASE_URL="mysql://user:pass@host:port/dbname"`

o
_env(file):_
`DATABASE_URL="mysql://user@host:port/dbname"`
and the password parameter in the doctrine file using encryption through the "Secrets" functionality:
```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        password: '%env(DATABASE_PASSWORD)%'.

```
It would be interesting to keep the same philosophy to keep more secure the configuration used by symfony in its different components.

**Comment by Nyholm** [comment]
Thank you for this suggestion. 

The "DSN" concept is very new relative the DoctrineBundle. That is why Doctrine have both DSN and username/password. 
Why don't you store the full DSN in your Secret Vault? Wound't that solve your issue?

**Comment by MAGlCUS** [comment]
Good morning Nyholm.

Yes, what you propose could be an option. What I had proposed is not a bug or an error, but an improvement of the mailer component. 

Although you could think from a more global point of view and add the functionality to the "resolve" filter, which already changes the %var% variables in the dsn by those in the "Parameters" configuration. However, there is no way to take into account the variables that are in the "Secret Vault" without doing a lot of work.

I mean, if I do the following:
_env(file):_
`DATABASE_URL="mysql://user:%dbpass%@host:port/dbname"`

```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

parameters:
   dbpass: '%env(DATABASE_PASSWORD)%'.
```

I can use the "Secret Vault", but it seems a bit complicated. 

Anyway, thank you very much for your comment.
