### ISSUE TITLE
YAML service configuration cannot call a method called "method"

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#40349]
**Symfony version(s) affected**: 5.2.3

**Description**
If a service has a method called ***method***, such as [Zebra_Pagination](https://stefangabos.github.io/Zebra_Pagination/Zebra_Pagination/Zebra_Pagination.html#methodmethod) has, it is not possible to declare calls to such a method in YAML.

**How to reproduce**
```yaml
services:
  Zebra_Pagination:
    class: Zebra_Pagination
    calls:
      - method:
        - url
      - padding:
        - false
```

Note the call syntax is correct because the call to `padding()` alone (and others) succeeds, only the call to `method()` fails because Symfony interprets the configuration differently for a key called `method` for some (legacy?) reason.

The specific error thrown is:
>Invalid service "Zebra_Pagination": method "url()" does not exist.
>dependency-injection\Compiler\AbstractRecursivePass.php (line 186)

**Comment by stof** [comment]
The Yaml format has 2 syntax for calls:

- an array with keys `method` (required) and `arguments` (optional, defaults to an empty list)
- an single-value array with the method name as key and the arguments as value.

If your method is named `method`, you will need to use the first syntax, as a key `method` is what detects which syntax is used.

**Comment by Bilge** [comment]
Isn't it the case that one of those formats is [undocumented](https://symfony.com/doc/current/service_container/calls.html)? In which case, shouldn't it either be documented or removed?

**Comment by xabbuh** [comment]
see #40350

**Comment by stof** [comment]
hmm, looks like the documentation has removed entirely the older format when the new one was documented.

Removing the older format would be a BC break. We cannot just do it like that.

**Comment by Bilge** [comment]
For what it's worth, I cannot get the old format to work.

```yaml
services:
  Zebra_Pagination:
    class: Zebra_Pagination
    calls:
      - method:
        arguments:
          - url
```

>Invalid call for service "Zebra_Pagination": the method must be defined as the first index of an array or as the only key of a map in "config/services.yaml" in config/services.yaml (which is being imported from "src\Kernel.php").

**Comment by xabbuh** [comment]
```yaml
services:
  Zebra_Pagination:
    class: Zebra_Pagination
    calls:
      - method: method
        arguments:
          - url
```

This should work.
