### ISSUE TITLE
Locale prefix with trailing_slash_on_root option incorrectly rendered in templates

### ISSUE THREAD

**Issue by herbyxxx** [symfony/symfony#40357]
**Symfony version(s) affected**: 5.2.3

**Setup**
Basically I set up my locale prefix:
```
//annotations.yaml
controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    trailing_slash_on_root: false //issue here
    requirements:
        _locale: '%locales%' //defined in services.yaml       
    defaults:
        _locale: '%locale%' //defined in services.yaml

fallback:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        route: home_index
        permanent: true
```
services.yaml
```
parameters:
    locale: 'en'
    locales: en|de
```
HomeController.php
```
/**
 * @Route("/", name="home_")
 */
class HomeController extends AbstractController
{
    /**
     * @Route(name="index")
     */
    public function home_index() {  /*render twig*/ }
}
```

**Issue**
As expected I can now use urls like `www.domain.example/en` or `www.domain.example/de` instead of  `www.domain.example/en/` (trailing slash). However when I use `{{ path('home_index') }}` in my twig templates it generates following url `www.domain.example` (without the locale).

**Expected outcome**
When rendering the url inside the twig template the locale should be provided `{{ path('home_index') }}`  => `www.domain.example/en`
