### ISSUE TITLE
Zulip notifier UnsupportedSchemeException "The "zulip" scheme is not supported."

### ISSUE THREAD

**Issue by big-r81** [symfony/symfony#40374]
**Symfony version(s) affected**: 5.2.4

**Description**

I'm testing the zulip notifier package. If I inject the ChatterInterface to send a chat message then I'm always getting a 500 error with the message "The "zulip" scheme is not supported".

**How to reproduce**

See [complete](https://stackoverflow.com/questions/66490075/testing-the-zulip-notifier-results-in-a-500-error-after-injecting-chatterinterfa) steps.

```/**
     * @Route("/", name="home")
     */
    public function index(ChatterInterface $chatter): Response
    {
        $message = new ChatMessage('Test-Message');
        $zulipOptions = (new ZulipOptions())
            ->topic('Test-Topic');
        $message->options($zulipOptions);
        $sendMessage = $chatter->send($message);

        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/HomeController.php',
        ]);
    }
```

**Additional context**

`notifier.yaml:`
```
framework:
    notifier:
        chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
            zulip: '%env(ZULIP_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
```
`.env`
```
ZULIP_DSN=zulip://symfony-****-bot@zulip.***.com:BLf4a7********5B9GrN4g2Hy******uKh6K@zulip.***.com?channel=test
```

`composer show | grep notifier`
```
symfony/notifier                   v5.2.4  Sends notifications via one or more channels (email, SMS, ...)
symfony/zulip-notifier             v5.2.4  Symfony Zulip Notifier Bridge
```
