### ISSUE TITLE
Doctrine migrations : the "amqp" extension is not installed.

### ISSUE THREAD

**Issue by rsereir** [symfony/symfony#40433]
**Symfony version(s) affected**: 5.2.1

**Description**
On Symfony 5.2 with php 8, it's not possible to play migration without php amqp extension but this extension is not available on php 8. I can't find link with doctrine migrations bundle and amqp extension... 

**How to reproduce**
```
php bin/console doctrine:migration:migrate
```

**Additional context**
Screenshot of error:
![Screenshot 2021-03-10 at 10 51 56](https://user-images.githubusercontent.com/43849341/110610549-a34cf180-818e-11eb-9c06-b72dbe97896e.png)

Messenger configuration:
```
framework:
    messenger:
        transports:
            failed: 'doctrine://default?queue_name=failed'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 5

        failure_transport: failed

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            App\Message\ChargeTransferMessage: async
```

Doctrine configuration:
```
parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        auto_commit: false
        driver: 'pdo_pgsql'
        server_version: '13.1'
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            numeric_functions:
                rand: App\Core\Doctrine\Query\Mysql\Rand
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'

    connection: default

    organize_migrations: 'BY_YEAR_AND_MONTH'
```

.env:
```
DATABASE_URL=pgsql://root@database/main
MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/messages
```
