### ISSUE TITLE
[Workflow] Question how transitions are identified as Enabled

### ISSUE THREAD

**Issue by AyrtonRicardo** [symfony/symfony#40447]
**Description**
Currently I have a workflow like this: 
```yaml
        example:
            type: 'workflow'
            supports:
                - App\Entity\ExampleEntity
            places:
                - new
                - sent
                - saved_order_id
                - in_progress
                - order_complete
                - activated
                - complete
                - failed
            marking_store:
                type: 'method'
                property: 'places'
            initial_marking:
                - new
            transitions:
                send:
                    from: new
                    to: sent
                save_order_id:
                    from: sent
                    to: saved_order_id
                check:
                    from: saved_order_id
                    to: in_progress
                complete_order:
                    from: in_progress
                    to: order_complete
                activate:
                    from: order_complete
                    to: activated
                complete:
                    from: activated
                    to: complete
                fail:
                    from: [ 'new', 'sent', 'saved_order_id', 'in_progress', 'order_complete', 'activated' ]
                    to: failed
```
Example code showing my usage of this workflow:
```php
$entity = new ExampleEntity();

echo $this->exampleWorkflow->can($entity, 'send') ? 'true' : 'false', PHP_EOL;// true; it's OK.
echo $this->exampleWorkflow->can($entity, 'save_order_id') ? 'true' : 'false', PHP_EOL;// false; It's OK.
echo $this->exampleWorkflow->can($entity, 'fail') ? 'true' : 'false', PHP_EOL;// false; But it should be, doesn't? Since my workflow says it can go from anywhere to `failed`
```
The output of the code above is like:
```
true
false
false
# List of available transitions:
^ array:1 [
  0 => Symfony\Component\Workflow\Transition^ {#87
    -name: "send"
    -froms: array:1 [
      0 => "new"
    ]
    -tos: array:1 [
      0 => "sent"
    ]
  }
]
```

* I've used `failed` as one example in my workflow, because my question is more related to why I cannot move from state `new` to `failed` using one transition with several `froms`? 
* In this scenario do I need to have 1 transition per each possible state combination in the example above?

I read that the component is based in Petri Net, but I could not find a suitable explanation why it only accept if all places in my entity are in "froms" of the transition. I only saw the information `A transition is enabled if all places connected to it as inputs contain at least one token` or `i.e. there are sufficient tokens in all of its input places; when the transition fires, it consumes the required input tokens, and creates tokens in its output places.` but I could not see any blocking in the design of Petri to no have accepted transitions when 1 or more places match.

Could someone explain for me how is it determined to enable the transitions from the theory? 
The code part which is blocking me from doing so: https://github.com/symfony/workflow/blob/5.x/Workflow.php#L322 

Since I'm not anywhere close to be well known in this subject, I gladly would accept your advice.

Source of my quotes: https://en.wikipedia.org/wiki/Petri_net (link provided in the workflow docs)
