### ISSUE TITLE
Messenger worker consumer is not stopped on deployment with Capistrano

### ISSUE THREAD

**Issue by soullivaneuh** [symfony/symfony#40477]
**Symfony version(s) affected**: 

- symfony/messenger: v4.4.19
- symfony/cache: v4.4.8

**Description**

Each Capistrano deployment correctly triggers the `messenger:stop-workers` command:

```
01:56 deploy:after_published
      01 php /var/www/n-admin/prod/shared/cachetool.phar opcache:reset
    ✔ 01 n-admin@10.11.2.1 0.132s
      02 php bin/console --no-interaction messenger:stop-workers
      02
      02  [OK] Signal successfully sent to stop any running workers.
      02
    ✔ 02 n-admin@10.11.2.1 0.299s
```

However, the consumers are not stopped at all.

This is because the cache key namespace is changed during the deployment (the cache folder is re-built from scratch) as you can see on the redis monitor result:

```bash
$ redis-cli MONITOR | grep workers.restart_requested_timestamp
1615823757.118584 [0 127.0.0.1:52648] "MGET" "Nt-xREZj47:workers.restart_requested_timestamp"
1615823758.119622 [0 127.0.0.1:52648] "MGET" "Nt-xREZj47:workers.restart_requested_timestamp"
# The messenger:stop-workers command sets a different cache key
1615823758.613583 [0 127.0.0.1:53094] "MGET" "Vsj+ARmV-4:workers.restart_requested_timestamp"
1615823758.613968 [0 127.0.0.1:53094] "SET" "Vsj+ARmV-4:workers.restart_requested_timestamp" "d:1615823758.613628;"
# The current consumer continues to fetch the old one.
1615823759.120560 [0 127.0.0.1:52648] "MGET" "Nt-xREZj47:workers.restart_requested_timestamp"
1615823760.121420 [0 127.0.0.1:52648] "MGET" "Nt-xREZj47:workers.restart_requested_timestamp"
```

Wee tried the `prefix_seed` keys that looks to be the solution:

```yaml
framework:
  cache:
    app: cache.adapter.redis
    default_redis_provider: snc_redis.default
    # Here is our custom prefix
    prefix_seed: 'project_%kernel.environment%'
```

But it has absolutely no effect to the key used by the cache pool.
Plus, we didn't see any impact on our whole project.

**How to reproduce**

1. Setup a capistrano deployment configuration that will trigger the `messenger:stop-workers` command at the end of releasing:

```ruby
SSHKit.config.command_map[:composer] = "php #{shared_path.join('composer.phar')}"
SSHKit.config.command_map[:console] = 'php bin/console --no-interaction'

namespace :deploy do
  before :starting, 'composer:install_executable'

  after :published, :after_published do
    on release_roles :all do
      within current_path do
        execute :console, 'messenger:stop-workers'
      end
    end
  end
end
```

Note: Any deployment tool that rely on releases building system should have the same issue.

2. Setup the consumer service and launch it (see systemd config below):

```
[Unit]
Description=Symfony consumer for project asynchronous messages 
After=network.target
[Service]
Type=simple
User=n-admin
# Current is a symlink to the current release directory
ExecStart=/var/www/project/current/bin/console messenger:consume --limit=100 %i
Restart=always
# The install section is needed to use
# `systemctl enable` to start on boot
# For a user service that you want to enable
# and start automatically, use `default.target`
# For system level services, use `multi-user.target`
[Install]
WantedBy=multi-user.target
```

3. Run the deployment

```
bundle exec cap production deploy
```

**Possible Solution**

If the `prefix_seed` goal is not to set a fixed namespace, an option should be added for that or the messenger component behavior should be changed to use something else than the app cache.

Our current workaround is to create a custom cache adapter that will by-pass the namespace key definition:

```php
<?php

namespace App\Cache;

use Symfony\Component\Cache\Adapter\RedisAdapter;
use Symfony\Component\Cache\Marshaller\MarshallerInterface;

final class RedisFixedNamespaceAdapter extends RedisAdapter
{
    public function __construct($redisClient, string $namespace = '', int $defaultLifetime = 0, MarshallerInterface $marshaller = null)
    {
        parent::__construct(
            $redisClient,
            'my-namespace',
            $defaultLifetime,
            $marshaller,
        );
    }
}
```

```yaml
services:
  App\Cache\RedisFixedNamespaceAdapter:
    # Arguments are required here to not make Symfony kernel yelling.
    arguments:
      - snc_redis.default
      - ''
    tags:
      - name: cache.pool
        provider: cache.default_redis_provider
        clearer: cache.default_clearer
        reset: reset
```

And configure it to the related messenger cache pool:

```yaml
framework:
  cache:
    app: cache.adapter.redis
    default_redis_provider: snc_redis.default
    pools:
      cache.messenger.restart_workers_signal:
        adapter: App\Cache\RedisFixedNamespaceAdapter
```

If this is not a bug but a miss-configuration issue, maybe the documentation should be updated for that kind of cases.

Thanks for the reading and the (I hope) future feedback. :slightly_smiling_face:

**Comment by alexsegura** [comment]
Been there, done that. 

Here is an alternate solution that doesn't require a custom class 

See [docs](https://symfony.com/doc/current/cache.html#creating-custom-namespaced-pools)

> If you need the namespace to be interoperable with a third-party app, you can take control over auto-generation by setting the namespace attribute of the cache.pool service tag.

```yaml
services:

    restart_workers_signal.cache:
        parent: cache.adapter.redis
        tags:
            - { name: cache.pool, provider: snc_redis.default, namespace: my-namespace }

    cache.messenger.restart_workers_signal: '@restart_workers_signal.cache'
```
