### ISSUE TITLE
Doctrine filter and EntityType query cache

### ISSUE THREAD

**Issue by KamilPesek** [symfony/symfony#40520]
**Symfony version(s) affected**: 5.2.*

**Description**
When using doctrine filter together with form EntityType and query_cache_driver, it results with caching EntityType query on first visit and then using always and ignoring filter.

**How to reproduce**
Set doctrine caching 
```
doctrine:
    orm:
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
```

Create doctrine filter, eg.
```
doctrine:
    orm:
        filters:
            platform_product_filter:
                class: App\Filter\PlatformProductFilter
                enabled: true
```
```
<?php

namespace App\Filter;

use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Query\Filter\SQLFilter;

class PlatformProductFilter extends SQLFilter
{

    /**
     * Gets the SQL query part to add to a query.
     *
     * @param ClassMetaData $targetEntity
     * @param string $targetTableAlias
     *
     * @return string The constraint SQL if there is available, empty string otherwise.
     */
    public function addFilterConstraint(ClassMetadata $targetEntity, $targetTableAlias): string
    {
           return $targetTableAlias . '.platform_product = ' . PLATFORM_PRODUCT_ID;
    }
}
```
Create entity type
```
       $formBuilder->add('packages', EntityType::class, [
            'class' => Package::class,
        ]);
```

Then create two URLs. One, called _URL_0_ on which you will set constant PLATFORM_PRODUCT_ID = 0 and second _URL_1_ on which you will set constant PLATFORM_PRODUCT_ID = 1

If you will access _URL_0_ as first, query will be cached with ` .platform_product  = 0`.  
When accesing _URL_1_ , you won't get  anything for EntityType because it will use already cached query.

If you will remove `query_cache_driver` then everything works as expected.
Workaround is having EntityType defined like:

   ```
     $this->em->getFilters()->disable('platform_product_filter');
        $formBuilder = $this->formFactory->createNamedBuilder('packagesFrom');
        $formBuilder->add('packages', EntityType::class, [
            'class' => Package::class,
            'query_builder' => function (EntityRepository $er) {
                return $er->createQueryBuilder('package')
                    ->andWhere('package.platformProduct = :platformProduct')
                    ->setParameter('platformProduct', PLATFORM_PRODUCT_ID);
            },
        ]);
        $form = $formBuilder->getForm();
        $formView = $form->createView();
        $this->em->getFilters()->enable('platform_product_filter');
```
NOTE: filter has to be disabled to make it work
