### ISSUE TITLE
Option in symfony/messenger DoctrineTransport configuration to leave consumed message in database table

### ISSUE THREAD

**Issue by st0at** [symfony/symfony#40551]
**Description**
Now when DoctrineTransport is used, every consumed message is deleted. There could be option in transport configuration to leave that message even after it is consumed. Like `delete_after_ack` in RedisTransport. This would be very useful for debugging purposes of consumed messages.

**Example**
```
framework:
    messenger:
        transports:
            doctrine:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    delete_after_ack: false
```
