### ISSUE TITLE
PSR18Client doesn't use the HttpClient defined headers

### ISSUE THREAD

**Issue by rrajkomar** [symfony/symfony#40592]
**Symfony version(s) affected**: 4.4.20

**Description**
When using a PSR18Client to send request to an API, the PSR18Client does not take into account the headers defined in the configuration of the underlying HttpClient.

**How to reproduce**
```yaml
http_client:
        default_options:
            timeout: 5
            headers:
                'Accept': application/json
                'Content-Type': application/json
        scoped_clients:
            my.client:
                base_uri: "%env(MY_BASE_URL)%"
```
Assume the following :
- dependency injection is correct
- uri is correct
- serialized body is correct

```php
$request = $this->myClient
                ->createRequest('POST', '/my_uri')
                ->withBody(
                    $this->myClient->createStream(''
                        $this->serializer->serialize($someObject, 'json')
                    )
                );
```

The resulting PSR Request doesn't have any of the headers defined in the configuration
