### ISSUE TITLE
CachingHttpClient looses base_uri from ScopedHttpClient

### ISSUE THREAD

**Issue by jbfewo** [symfony/symfony#40644]
**Symfony version(s) affected**: 5.2.5

**Description**
I've got working code using a scoped client with a configured base_uri. After decorating it with the CachingHttpClient the requests fail with an invalid URL scheme error because of the missing base_uri parts.

**How to reproduce**
* Create a scoped http client:
```yaml
framework:
    http_client:
        scoped_clients:
            foo.client:
                base_uri: '%env(FOO_CLIENT_URL)%'
```
* Decorate this client with the CachingHttpClient:
```php
<?php

namespace App\MyNamespace;

use Symfony\Component\HttpClient\CachingHttpClient;
use Symfony\Component\HttpKernel\HttpCache\Store;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class MyClass
{
    public function __construct(public HttpClientInterface $fooClient)
    {
    }

    public function index()
    {
        /** This works fine */
        $content = $this->fooClient->request('GET', '/bar.json')->toArray();

        $store = new Store('/data/var/cache/foobar');
        $this->fooClient = new CachingHttpClient($this->fooClient, $store);

        /** This misses the base_uri */
        $content = $this->fooClient->request('GET', '/bar.json')->toArray();
}

```

**Comment by stof** [comment]
Well, this is a case of a wrong decoration order. As the ScopedHttpClient decorator is finalizing the URL, it should be the one decorating the CachingHttpClient rather than the opposite, so that CachingHttpClient receives the full URL (as the cache key must be the full URL)

**Comment by jbfewo** [comment]
I agree that the cache key needs to get the full URL.

And, you're right, if I do your recommendation in general like:
```yaml
    cached.http_client:
        class: Symfony\Component\HttpClient\CachingHttpClient
        decorates: http_client
        arguments:
            - '@.inner'
            - '@http_cache.store'
```
then my example works fine. But _every_ cachable request will be cached now, which may lead to unexpected results in existing applications.            

Afaik there is no chance to specify the passed client at the scoped clients configuration.

For me the error occurs because the CachingClient doesn't gets the base_uri as an option. But I'm not deep enough in the code to say if there is a simple way to do so.

**Comment by OskarStark** [comment]
> For me the error occurs because the CachingClient doesn't gets the base_uri as an option. But I'm not deep enough in the code to say if there is a simple way to do so.

I am running into the same issue:
![CleanShot 2021-05-05 at 16 45 28@2x](https://user-images.githubusercontent.com/995707/117160417-6170ae00-adc1-11eb-9ce7-bf94cb94a6e0.png)

I have different scoped clients and want to wrap them into a CachingHttpClient.

Any idea were this needs to be fixed?

cc @nicolas-grekas @Nyholm

**Comment by nicolas-grekas** [comment]
But @stof is right, there is nothing to fix here, the caching decorator must be put after the URL is fully resolved.

**Comment by stof** [comment]
@OskarStark what you should do is having multiple scoped clients wrapping a CachingHttpClient instead (they could even wrap the *same* caching client so that the cache can be shared)

**Comment by Gemorroj** [comment]
```php
$httpClient = HttpClient::createForBaseUri('https://maps.googleapis.com', [
    'query' => [
        'key' => $apiKey,
    ],
    'headers' => [
        'Accept' => 'application/json',
        'Content-Type' => 'application/json',
    ],
]);

$store = new Store(\sys_get_temp_dir().'/google-maps');
$httpClient = new CachingHttpClient($httpClient, $store, [
    'default_ttl' => 1000,
    // 'base_uri' => 'https://maps.googleapis.com', // whithout this, it doesnt work,
    // 'query' => [
    //    'key' => $apiKey, // whithout this, it doesnt work,
    // ],
]);
```

**Comment by stof** [comment]
@Gemorroj here is the way to have them decorated in the right order

```php
$httpClient = HttpClient::create();

$store = new Store(\sys_get_temp_dir().'/google-maps');
$httpClient = new CachingHttpClient($httpClient, $store, [
    'default_ttl' => 1000,
]);

$httpClient = ScopingHttpClient::forBaseUri($httpClient, 'https://maps.googleapis.com', [
    'query' => [
        'key' => $apiKey,
    ],
    'headers' => [
        'Accept' => 'application/json',
        'Content-Type' => 'application/json',
    ],
]);
```

@nicolas-grekas I think this `HttpClient::createForBaseUri` shortcut is the main source of confusion here, because it hides the fact that the scoping client is a decorator and forbids injecting intermediate decorators.

**Comment by OskarStark** [comment]
I agree, while reading this @stof it makes sense.
Before you can use an easy yaml to define different scoped clients, now you need to do a lot of work in the services.yaml to combine all these things together. Its straightforward in PHP but not in yaml.

I am thinking about a new option for the scoped_clients section `cache_store: '@http_cache.store'` which gets me the correct decorated `ScopingHttpClient` client as `CachingHttpClient`.

Does that make sense or am I missing something ?

**Comment by OskarStark** [comment]
I get it (almost) working with the following code:
```yaml
# services.yaml
    app.http_client:
        class: Symfony\Component\HttpClient\CachingHttpClient
        arguments:
            - '@http_client'
            - '@http_cache.store'
            - { default_ttl: 1000 }

    app.http_client.datenabfragen:
        class: Symfony\Component\HttpClient\ScopingHttpClient
        factory: ['Symfony\Component\HttpClient\ScopingHttpClient', 'forBaseUri']
        arguments:
            - '@app.http_client'
            - '%env(DATENABFRAGEN_API_BASE_URI)%'
            - { auth_basic: '%env(DATENABFRAGEN_API_USERNAME)%:%env(DATENABFRAGEN_API_PASSWORD)%' }
```

It results in:
![CleanShot 2021-05-07 at 08 06 29@2x](https://user-images.githubusercontent.com/995707/117405035-41e59c80-af0b-11eb-8396-aec9b8015836.png)

As far as I can tell this looks correct, but nothing is written to the store 🤔
