### ISSUE TITLE
[DI] CSV env var processor does not work like an ordinary array

### ISSUE THREAD

**Issue by stollr** [symfony/symfony#40654]
**Symfony version(s) affected**: 5.2.6

**Description**
I am trying to setup monolog with a symfony_mailer handler. I want to configure the `to_email` with an ENV variable and usage of the csv processor so that I can add multiple receivers.

**How to reproduce**
I have the `monolog.yaml` looking like that:
```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: symfony_mailer
        symfony_mailer:
            type:         symfony_mailer
            from_email:   '%env(MAILER_FROM)%'
            to_email:     '%env(csv:MAILER_ERRORLOG_TO)%'
            subject:      'Error! %%message%%'
            formatter:    monolog.formatter.html
            content_type: text/html
```
And the `.env.local` looks like that:
```
MAILER_ERRORLOG_TO=john@example.com,chris@example.com
```

This results in an InvalidTypeException
> Invalid type for path "monolog.handlers.symfony_mailer.to_email.0". Expected one of "bool", "int", "float", "string", but got "array".

When I replace the env var with a real array, for instance
```yaml
to_email:     ['john@example.com', 'chris@example.com']
```
the error is resolved. But as you can imagine this is no real solution.

I already have tried to figure out, what the problem is, but without real result. In Symfony's config definition `BaseNode` there is a normalizer method, which seem to replace the env variable with a nested array [[]] and this results in the error described above. 

If you need more details please tell me.
