### ISSUE TITLE
[RateLimiter] Feature - multiple rate limits check at same time

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#40705]
**Description**
Sometimes we have more than one rate limit condition. For example:
10 requests/sec
100 requests/hour
1000 requests/day

We should consume() or not consume() all three rate limits at once. But what if some of this rate limits exceeded, and some not exceeded? I mean:

```php
$rateLimit1->consume(); // accepted
$rateLimit2->consume(); // accepted
$rateLimit3->consume(); // not accepted

// what should we do now? $rateLimit1->consume(-1) and $rateLimit2->consume(-1)?
```

**Comment by Nyholm** [comment]
This is a good feature. So basically all rate limiters needs to allow consumption to proceed.

**Comment by wouterj** [comment]
If I understand correctly, this feature already exists as [`CompoundLimiter`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/RateLimiter/CompoundLimiter.php). However, there is not yet a way to use this limiter in the FrameworkBundle's config.

You might use it like this in Symfony <5.4:

```yaml
framework:
    rate_limiter:
        one:
            policy: 'sliding_window'
            limit: 10
            interval: '1 sec'
        two:
            policy: 'sliding_window'
            limit: 100
            interval: '1 hour'
        three:
            policy: 'sliding_window'
            limit: 1000
            interval: '1 day'

services:
    app.main_limiter:
        class: Symfony\Component\RateLimiter\CompoundLimiter
        arguments:
            - ['@limiter.one', '@limiter.two', '@limiter.three']
```
