### ISSUE TITLE
[DependencyInjection] Decorate synthetic service

### ISSUE THREAD

**Issue by Firtzberg** [symfony/symfony#40784]
Is it possible to decorate a synthetic service (set at runtime)?
When I try to do so I get the error message `A synthetic service ("Vendor\Product\Decorator.inner") must be public.`

Here's the YAML file
```
services:
  Vendor\Product\Synthetic:
    public: true
    synthetic: true
  Vendor\Product\Decorator:
    class: stdClass
    decorates: Vendor\Product\Synthetic
    public: true
```

**Comment by stof** [comment]
I don't think it is, as setting the service would then have to actually set the inner one (while the call does not know the inner id).
Synthetic services are not managed by the container but set externally (and so they should be quite rare), so this limits which features can be done with them.

@nicolas-grekas should we add a dedicated error in the resolution of service decoration when trying to decorate a synthetic service to give a better error message ?

**Comment by nicolas-grekas** [comment]
A more specific error message would be nice yes. Up to give it a try @Firtzberg?

**Comment by Firtzberg** [comment]
I'm fine with a more detailed error message or a compiler pass which prevents this. Whatever you consider best.
I would like this limitation of synthetic services to be documented. You could possibly mention the workaround below.
Please close the issue when you please.

In case someone stumbles upon this, I am using a workaround.
```
services:
  RuntimeInjection:
    synthetic: true
  Vendor\Product\Interface:
    class: Vendor\Product\Delegator
    arguments: ['@RuntimeInjection']
  Vendor\Product\Decorator:
    decorates: Vendor\Product\Interface
```
The `Delegator` just forwards all method calls to the instance provided at runtime. `Vendor\Product\Interface` can be used anywhere and decorated as needed.

After bulding the container:
```
$container->set('RuntimeInjection', $instance);
```
