### ISSUE TITLE
Unable to serialize dates when the snake_case converter is enabled

### ISSUE THREAD

**Issue by PaulCombal** [symfony/symfony#40818]
**Symfony version(s) affected**: 5.2.*

**Description**
Briefly: When I enable the json snake_case converter, my dates are normalized as empty arrays.

I first described another related issue on [this SO thread](https://stackoverflow.com/questions/67092209/symfony-serializes-dates-as-empty-arrays), which lead to this issue.

**How to reproduce**

I enable the converter this way

services.yaml (snippet)
```yaml
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer:
    public: true
    arguments: [ '@serializer.mapping.class_metadata_factory', '@serializer.name_converter.camel_case_to_snake_case' ]
    tags: [ serializer.normalizer ]
```

More information on the StackOverflow thread above.

**Possible Solution**

My guess is that the GetSetConverter is chosen in the Chain of Responsibility, and does the name conversion, but will not proceed to normalize the date as intended.

**Additional context**

Example responses:
![image](https://user-images.githubusercontent.com/5382590/114727645-ab282480-9d3e-11eb-9057-eeea1bbb200c.png)
![image](https://user-images.githubusercontent.com/5382590/114727712-bb400400-9d3e-11eb-9d41-9fd907c08eeb.png)

Please let me know if you need any information from me

**Comment by PaulCombal** [comment]
This issue is very important to me, that's why I decided to investigate further. I made a PoC repository regarding this issue. It turns out the issue only occurs when the `groups` option is present in the context. 
Feel free to explore this repository: https://github.com/PaulCombal/symfony-serialization-issue-poc
If you remove the snake_case conversion in the services.yaml, you will see that the issue disappears. I believe this behavior is not intended.

EDIT: Furthermore, using the annotation @SerializedName("custom_name") on the entity property has no effect when using the snake_case converter

**Comment by PaulCombal** [comment]
This issue is really slowing down the development. Either we've totally missed the correct way to serialize the data, or this issue makes the snake_case converter barely usable. In the meantime, I've implemented a PoC of what I thought the normal behavior would be.

[Current branch snippet:](https://github.com/symfony/serializer/blob/fc663b9e90c50cfbc0df70d8439a6335ea4c7742/Serializer.php#L152)
```php
// If a normalizer supports the given data, use it
if ($normalizer = $this->getNormalizer($data, $format, $context)) {
       return $normalizer->normalize($data, $format, $context);
}
```

This code is not viable but removes the serialization difference:
```php
// If a normalizer supports the given data, use it
if ($normalizer = $this->getNormalizer($data, $format, $context)) {
     if (is_a($normalizer, 'Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer') && is_a($data, \DateTime::class)) {
        $normalizer = new \Symfony\Component\Serializer\Normalizer\DateTimeNormalizer();
    }
    return $normalizer->normalize($data, $format, $context);
}
```

Please feel free to have a look yourself, and let me know what you think.

EDIT: It also looks like this affects date deserialization

**Comment by Heyfara** [comment]
I stumbled upon the exact same issue. Datetime objects were serialized as empty arrays when using groups.
The issue comes from the declaration of ` Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer`. Once removed it works as expected. I tried this solution in the repository you linked above and I get the expected result.

Not sure why you declare the GetSetMethodNormalizer though. If it's only for enabling the name converter you should instead add the [required config](https://symfony.com/doc/current/serializer.html#enabling-a-name-converter) : 
```
framework:
    # ...
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
```

Hope it helps.
