### ISSUE TITLE
The given value "127.0.0.1,127.0.0.2" in the "security.access_control" config option is not a valid IP address

### ISSUE THREAD

**Issue by zidaneus** [symfony/symfony#40864]
**Symfony version(s) affected**: 5.2.6

**Description**
https://symfony.com/doc/current/security/access_control.html#matching-options
ip or ips: netmasks are also supported (can be a comma-separated string)

But if you specify ip with a comma separator, then we get an error: "The given value "127.0.0.1,127.0.0.2" in the "security.access_control" config option is not a valid IP address" in \Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::createRequestMatcher
**How to reproduce**
config/packages/security.yaml

```
security:
  ...
  access_control:
      -
         path: "^/some/path/.*$"
         ips: '127.0.0.1,127.0.0.2'
         roles: ["IS_AUTHENTICATED_ANONYMOUSLY"]
         methods: ["POST"]
```

Validate security bundle configuration.

**Comment by xabbuh** [comment]
The documentation is misleading (the code example does it right though). Your config should be like this:

```yaml
security:
  access_control:
      -
         path: "^/some/path/.*$"
         ips: ['127.0.0.1', '127.0.0.2']
         roles: ["IS_AUTHENTICATED_ANONYMOUSLY"]
         methods: ["POST"]
```

Closing here as there is no bug in the code.

Can you please open an issue in the documentation repository about this or send a PR that improves the current wording?
