### ISSUE TITLE
[SecurityBundle] Comma separated ips for security.access_control

### ISSUE THREAD

**Issue by fvilpoix** [symfony/symfony#40881]
**Symfony version(s) affected**: 5.2.6

**Description**
Hi,
I tried to use the new feature in 5.2.0 from #38149.
The comma separated value is rejected by the SecurityExtension

**How to reproduce**

```yaml
security:
    # ...
    access_control:
         - { path: ^/profile, roles: ROLE_USER, ips: [::1, '%trusted_ips%'] }


parameters:
    trusted_ips: '127.0.0.1,127.0.0.2'
```

Then, I get a LogicException

![image](https://user-images.githubusercontent.com/1503147/115424520-12424f00-a1ff-11eb-9947-9b375c4bd435.png)
