### ISSUE TITLE
notifier: chat/slack + email leads to UnsupportedSchemeException

### ISSUE THREAD

**Issue by drzraf** [symfony/symfony#40978]
**Symfony version(s) affected**: 5.2

**Description**
Running the `chat/slack` notification channel in combination with `email` and a custom MAILER_DSN (`ses+smtp`) leads to an `UnsupportedSchemeException`.

**How to reproduce**
- Install `symfony/slack-notifier` and `symfony/amazon-mailer`
- Env:
```
SLACK_DSN=null://null
MAILER_DSN=ses+smtp://foo:bar@default?region=eu-west-1
```
- Config:
```yaml
framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
            email: '%env(MAILER_DSN)%'
```
- Code:
```php
        $recipient = new Recipient('foo@example.com');
        $notification = (new Notification('notif', ['email', 'chat/slack']))->content('notif');
        $this->notifier->send($notification, $recipient);
```

- Backtrace:
```
Symfony\Component\Notifier\Exception\ UnsupportedSchemeException
in vendor/symfony/notifier/Transport.php (line 126) 
```

**Possible Solution**
dunno

**Additional context**
The combination email + sms (OVH cloud) does not lead to such exception.
