### ISSUE TITLE
RedirectException although max_redirects not reached

### ISSUE THREAD

**Issue by codedge** [symfony/symfony#41277]
**Symfony version(s) affected**: 5.1

**Description**
When using the `max_redirects` option for a scoped client, set it to `1` and call `$request->getHeaders()` I would expected to not get a `RedirectingException` thrown when the first redirect happens.

I know, that calling `getHeaders` leads to exceptions, as [stated in the docs](https://symfony.com/doc/current/http_client.html#handling-exceptions), but shouldn't it fire an exception when the maximum is reached and not before?

Background is, that `getHeaders` needs to called but _one_ redirect should be allowed.

But currently I get the exception, regardless what I set.

**framework.yaml**

```yml
framework:
    # ...
    http_client:
            default_options:
                max_redirects: 1
            scoped_clients:
                abc_client:
                    base_uri: 'https://www.abc.def'
```

Exception:

```
In CommonResponseTrait.php line 182:

  [Symfony\Component\HttpClient\Exception\RedirectionException (301)]
  HTTP/2 301  returned for "https://www.abc.com/account/123456".


Exception trace:
  at /usr/src/app/vendor/symfony/http-client/Response/CommonResponseTrait.php:182
 Symfony\Component\HttpClient\Response\AsyncResponse->checkStatusCode() at /usr/src/app/vendor/symfony/http-client/Response/AsyncResponse.php:105
 Symfony\Component\HttpClient\Response\AsyncResponse->getHeaders() at /usr/src/app/src/Bundle/ProcessBundle/Downloader/AbstractRestDownloader.php:187
 App\Bundle\ProcessBundle\Downloader\AbstractRestDownloader->writeResponse() at /usr/src/app/src/Bundle/ProcessBundle/Downloader/AbstractRestDownloader.php:111
 App\Bundle\ProcessBundle\Downloader\AbstractRestDownloader->downloadFile() at /usr/src/app/src/Bundle/LendableBundle/Downloader/LoanHtmlDownloader.php:57
```

When I catch the `RedirectingException` then I cannot check how many redirects already happened (and throw an exception after `X` redirects).

Is that something I do wrong or an issue in the client?
