### ISSUE TITLE
Validator not using cache

### ISSUE THREAD

**Issue by syurchen** [symfony/symfony#41280]
**Symfony version(s) affected**: 5.2.3

**Description**
I have found out that framework.validator.cache is not being used. 

I'm getting Symfony\Component\Validator\Validator\TraceableValidator via Symfony\Component\Validator\Validator\ValidatorInterface (tried both from container and from DI). And Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory that is being build inside of it has $cache = null despite me configuring it. 

**How to reproduce**
**You can actually just put any noncense in framework.validation.cache. Looks like it is not used at all!**
But here are configs on mine:
validator.yaml
```yaml
    framework:

        validation:
            enabled: true
            email_validation_mode: html5
            cache: cache.default_redis_provider
```
cache.yaml
```yaml
framework:
    cache:
        app: cache.adapter.filesystem
        default_redis_provider: '%env(REDIS_CACHE_URL)%'
```
The .env var is set correctly.

```php
namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class TestORMCommand extends Command
{
    protected static $defaultName = 'TestORM';

    public function __construct(string $name = null, private ValidatorInterface $validator)
    {
        parent::__construct($name);
    }

    protected function configure()
    {
        $this
            ->setDescription('Add a short description for your command')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        return Command::SUCCESS;
    }
}
```

and put following line in vendor/symfony/validator/Mapping/Factory/LazyLoadingMetadataFactory.php:

```
echo get_class($cache);
```

Then launch this newly crate command, and it will throw an error, because $cache = null.

*Edit 21.05.21* I added APP_DEBUG=0 to .env.debug. But it it using PhpArrayAdapter instead of RedisAdapter I have configured
