### ISSUE TITLE
[Cache] Redis cache cannot be created when tagged as cache.pool

### ISSUE THREAD

**Issue by pmishev** [symfony/symfony#41459]
**Symfony version(s) affected**: 4.4.24

**Description**
In my bundle I have the following cache definition:
```
    cache.sfes:
        parent: 'cache.system'
        autowire: false
        autoconfigure: false
        public: false
        tags:
            - { name: cache.pool } # Seems the only reason for this is to see the pool in the Symfony toolbar
```
It works fine and is caching in the filesystem.

Now, in my app, I want to override this with Redis cache, so I'm doing:
```
    cache.sfes:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@snc_redis.cache' # a Predis\Client instance
            - '%deploy_env_prefix%es_cache'
```
Works fine, and caches in Redis, but I no longer see the cache pool in Symfony toolbar.
So I add the `cache.pool` tag:
```
    cache.sfes:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@snc_redis.cache' # a Predis\Client instance
            - '%deploy_env_prefix%es_cache'
        tags:
            - { name: cache.pool }
```

And now I get an error:
```
Argument 2 passed to Symfony\Component\Cache\Adapter\AbstractAdapter::createConnection() must be of the type array, string given, called in /blabla/ContainerUkKHm0d/srcApp_KernelDevDebugContainer.php on line 26206
```

![image](https://user-images.githubusercontent.com/5188763/120178073-fe780880-c200-11eb-9ff2-3aac6dfb47a3.png)

Looks like some hash string is passed instead of the Predis\Client instance for some reason.

**Comment by nicolas-grekas** [comment]
You cannot override a `cache.pool` service this way. At least it's not supported.
I think you should use the `provider` option if you want to configure a specific connection.

**Comment by pmishev** [comment]
Could you elaborate a bit please, which part is not supported? How should I specify the provider option?

I did also try adding this in the app config instead of trying to override the service:
```
framework:
	cache:
        pools:
            cache.sfes:
                adapter: cache.adapter.redis
                provider: snc_redis.cache
```

According to the docs (https://symfony.com/doc/current/cache.html#creating-custom-namespaced-pools), this should create a `cache.sfes` service.
And since `cache.sfes` is already created inside the bundle, I thought that this config would either override it or give an error that such service already exists. However none of that happened and `cache.sfes` remained with its original definition.

Perhaps the cache pool should be defined differently in the bundle, so it can be more easily overridable?

**Comment by nicolas-grekas** [comment]
`cache.pool` is not really a "userland" tag. It can be added to services only if they have a specific list of constructor arguments for example (I can't recall the details.)

I'm not sure what you want to achieve. e.g. Predis is already automatically used if installed, you don't need snc-redis-bundle.
If your bundle declares a service, and you also define the service, the latest will override the previous one. Since you don't really control the order, you cannot reliably rely on this.

I'm going to close this issue because we use this issue tracker for bugs and feature requests.
Please use [other community channels](https://symfony.com/support) for support.

**Comment by pmishev** [comment]
I found a way to achieve what I want for the most part:
I added a config key in my bundle to specify the name of a cache pool to use and then in the bundle's Extension class, I replace the `Symfony\Contracts\Cache\CacheInterface $cache` argument of the service that uses it.

Therefore, I'm now able to do this in my App:
```
framework:
    cache:
        pools:
            sfes.metadata_cache_pool:
                adapter: cache.adapter.redis
                provider: snc_redis.cache

sineflow_elasticsearch:
    metadata_cache_pool: sfes.metadata_cache_pool
```
or to avoid any confusion that the snc_redis bundle has anything to do with this issue, I can also do this:
```
services:
    app.es.metadata_cache_provider:
        class: 'Symfony\Component\Cache\Adapter\RedisAdapter'
        factory: ['Symfony\Component\Cache\Adapter\AbstractAdapter', 'createConnection']
        arguments:
            - '%env(REDIS_DB1_DSN)%'

framework:
    cache:
        pools:
            sfes.metadata_cache_pool:
                adapter: cache.adapter.redis
                provider: app.es.metadata_cache_provider

sineflow_elasticsearch:
    metadata_cache_pool: sfes.metadata_cache_pool
```


The only thing I cannot do is control the namespace of the cache as documented (https://symfony.com/doc/current/cache.html#creating-custom-namespaced-pools):

> If you need the namespace to be interoperable with a third-party app, you can take control over auto-generation by setting the namespace attribute of the cache.pool service tag. For example, you can override the service definition of the adapter:
>
> ```
> # config/services.yaml
> services:
>     app.cache.adapter.redis:
>         parent: 'cache.adapter.redis'
>         tags:
>             - { name: 'cache.pool', namespace: 'my_custom_namespace' }
> ``` 

So it seems `cache.pool` is kind of a userland tag after all, but it only works if you apply it to the cache `adapter` and not on the `provider`.
So following the exact example given, in order to change the namespace, I can now write:
```
services:
    app.es.metadata_cache_provider:
        class: 'Symfony\Component\Cache\Adapter\RedisAdapter'
        factory: ['Symfony\Component\Cache\Adapter\AbstractAdapter', 'createConnection']
        arguments:
            - '%env(REDIS_DB1_DSN)%'

    app.es.cache.adapter.redis:
        parent: 'cache.adapter.redis'
        tags:
            - { name: 'cache.pool', namespace: '%deploy_env_prefix%es_cache' }

framework:
    cache:
        pools:
            sfes.metadata_cache_pool:
                adapter: app.es.cache.adapter.redis
                provider: app.es.metadata_cache_provider

sineflow_elasticsearch:
    metadata_cache_pool: sfes.metadata_cache_pool
```

This works and the namespace is set correctly, **BUT**, as the adapter has the `cache.pool` tag, it is also shown (empty) in the Symfony profiler:

![image](https://user-images.githubusercontent.com/5188763/120695286-21294c00-c4a3-11eb-883b-43b3e132b1c5.png)



So I still believe there is a problem here, although not sure whether:
- The fact that you cannot set a `cache.pool` tag on your cache provider service, without messing up its arguments?
- The fact that you cannot control the cache namespace in a way other than tagging your adapter as `cache.pool`, which causes it to be unnecessarily displayed in Symfony profiler?
