### ISSUE TITLE
Doctrine\ORM\Cache\DefaultCacheFactory broken

### ISSUE THREAD

**Issue by Ne-Lexa** [symfony/symfony#41506]
**Symfony version(s) affected**: 5.2.*
**DoctrineBundle affected**: 2.4.1

**Description**
After the `сomposer update` and updates `doctrine/doctrine-bundles` to 2.4, there is a fatal error.  
Before updating the error package was not.

**How to reproduce**
```yaml
// config/packages/cache.yaml
framework:
    cache:
        # Redis
        app: cache.adapter.redis_tag_aware
        default_redis_provider: redis://localhost
```

```yaml
// config/packages/doctrine_second_cache.yaml
doctrine:
    orm:
        second_level_cache:
            enabled: true
            region_cache_driver:
                type: pool
                pool: doctrine.second_level_cache_pool

framework:
    cache:
        pools:
            doctrine.second_level_cache_pool:
                adapter:          cache.app
                default_lifetime: 60
```

**Additional context**
```bash
$ bin/console cache:clear
TypeError {#568
  #message: "Argument 2 passed to Doctrine\ORM\Cache\DefaultCacheFactory::__construct() must implement interface Doctrine\Common\Cache\Cache, instance of Symfony\Component\Cache\Adapter\TraceableTagAwareAdapter given, called in /tmp/sf5.2/var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php on line 665"
  #code: 0
  #file: "./vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php"
  #line: 65
  trace: {
    ./vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php:65 { …}
    ./var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php:665 {
      ContainerVpzExal\App_KernelDevDebugContainer->getDoctrine_Orm_DefaultEntityManagerService($lazyLoad = true)^
      › $b->setCacheLogger($c);
      › $b->setCacheFactory(new \Doctrine\ORM\Cache\DefaultCacheFactory($d, ($this->privates['doctrine.second_level_cache_pool'] ?? $this->getDoctrine_SecondLevelCachePoolService())));
      › $b->setRegionsConfiguration($d);
    }
    ./var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php:612 { …}
    ./var/cache/dev/ContainerVpzExal/EntityManager_9a5be93.php:239 { …}
    ./var/cache/dev/ContainerVpzExal/EntityManager_9a5be93.php:239 { …}
    ./vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:54 { …}
    ./vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:98 { …}
    ./vendor/symfony/http-kernel/Kernel.php:580 { …}
    ./vendor/symfony/http-kernel/Kernel.php:780 { …}
    ./vendor/symfony/http-kernel/Kernel.php:121 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
    ./vendor/symfony/console/Application.php:166 { …}
    ./bin/console:43 { …}
  }
}
2021-06-01T20:38:15+00:00 [critical] Uncaught Error: Argument 2 passed to Doctrine\ORM\Cache\DefaultCacheFactory::__construct() must implement interface Doctrine\Common\Cache\Cache, instance of Symfony\Component\Cache\Adapter\TraceableTagAwareAdapter given, called in /tmp/sf5.2/var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php on line 665
```
