### ISSUE TITLE
[5.3 ]concrete service no more generate for  security.authentication.rememberme.services.simplehash.$firewallName

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#41671]
**Symfony version(s) affected**:5.3.0
**Description**
Implementation of security.authentication.rememberme.services.simplehash.$firewallname does not exist anymore 

as per https://stackoverflow.com/questions/67604938/auto-remember-me-after-register
I used this to manually trigger the remember me feature 

however the service does not exist anymore , only the abstract one 

in symfony 5.2

```
 security.authentication.rememberme.services.simplehash                                Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices                         
  security.authentication.rememberme.services.simplehash.company_admins                 Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices                         
  security.authentication.rememberme.services.simplehash.endusers                       Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices                         
  security.authentication.rememberme.services.simplehash.rosaly_admins                  Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices      
```

in symfony 5.3, only: 

```
  security.authentication.rememberme.services.simplehash                                Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices                     
```

**How to reproduce**
 * create a symfony app
 * in security.yaml add

```
    firewalls:
        users:
            pattern: ^/
            provider: users
            remember_me:
                secret: '%kernel.secret'
                lifetime: 604800 # 1 week in seconds
                path: /
                always_remember_me: true

```

run `console debug:container`  ->    `security.authentication.rememberme.services.simplehash.users` is not present

**Possible Solution**

**Additional context**
