### ISSUE TITLE
Calling Languages::getNames() getting ResourceBundleNotFoundException

### ISSUE THREAD

**Issue by sajixavier** [symfony/symfony#41708]
Hi,

While calling Symfony\Component\Intl\Languages::getNames(), following exception is getting thrown. I have checked the vendor folder and it doesn't have 'root.php' file under languages folder. But the same file exists in currencies folder. 

Uncaught exception 'Symfony\Component\Intl\Exception\ResourceBundleNotFoundException' with message 'The resource bundle "/srv/api/vendor/symfony/intl/Resources/data/languages/root.php" does not exist.' in /srv/api/vendor/symfony/intl/Data/Bundle/Reader/PhpBundleReader.php:39

Symfony version : 5.3

Contents in translations.yaml

```
framework:
    default_locale: 'en'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['en']
```

Any idea what I am doing wrong here.
