### ISSUE TITLE
Authenticator - Multiple firewalls

### ISSUE THREAD

**Issue by adrienlamotte** [symfony/symfony#41724]
**Symfony version(s) affected**: 5.3

**Description**
I just migrated to the new authenticator manager and I have multiple firewalls for differents sections of my app.
Now when I'm logging in one of my firewalls, the user is authenticated in **ALL** of the firewalls. That was not the case before.
I want a separation between my FRONT and my CMS, so a user should not be authenticated in my FRONT if he has logged in in the CMS.

**How to reproduce**
Here is my security.yaml

```yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        cms:
            pattern: ^/cms
            provider: users
            login_throttling:
                max_attempts: 3
            form_login:
                check_path: cms_login
                login_path: cms_login
                enable_csrf: true
            logout:
                path: cms_logout
                target: cms_login

        main:
            lazy: true
            provider: users
            login_throttling:
                max_attempts: 3
            json_login:
                check_path: front_user_login
            form_login:
                check_path: front_page_home
                login_path: front_page_home
                default_target_path: front_page_home
                always_use_default_target_path: true
                enable_csrf: true
            logout:
                path: front_user_logout
                target: front_page_home

    access_control:
        - { path: ^/cms/, roles: [ROLE_ADMIN], requires_channel: '%requires_channel%' }
        - { path: ^/, roles: PUBLIC_ACCESS, requires_channel: '%requires_channel%' }

```

Is this a bug, or do I need to change anything in my security.yaml ?
