### ISSUE TITLE
[DI] Decorate injected not shared service

### ISSUE THREAD

**Issue by Firtzberg** [symfony/symfony#41721]
**Symfony version(s) affected**: 4.4.17, likely others

**Description**
Injected, not shared services cannot be decorated.

**How to reproduce**

Suppose the following service definitions with a shared service, a service which is not shared and a public service which depends on the other two. While the shared service can be easily decorated causing the public service to receive a decorated instance, it seems impossible to achieve the same behavior for the service which isn't shared.

The order of decoration doesn't concern us here. We could half the number of decorators to make this more readable, but 4 of them are defined to show that the `shared` option of the decorator service definition has no impact on the behavior.

```yml
services:
  NotShared:
    class: stdClass
    public: false
    shared: false
    properties:
      name: 'NotShared'
  Shared:
    class: stdClass
    public: false
    shared: true
    properties:
      name: 'Shared'
  NotSharedDecoratingNotShared:
    class: stdClass
    public: false
    shared: false
    decorates: NotShared
    properties:
      name: 'NotSharedDecoratingNotShared'
      inner: '@NotSharedDecoratingNotShared.inner'
  NotSharedDecoratingShared:
    class: stdClass
    public: false
    shared: false
    decorates: Shared
    properties:
      name: 'NotSharedDecoratingShared'
      inner: '@NotSharedDecoratingShared.inner'
  SharedDecoratingNotShared:
    class: stdClass
    public: false
    shared: true
    decorates: NotShared
    properties:
      name: 'SharedDecoratingNotShared'
      inner: '@SharedDecoratingNotShared.inner'
  SharedDecoratingShared:
    class: stdClass
    public: false
    shared: true
    decorates: Shared
    properties:
      name: 'SharedDecoratingShared'
      inner: '@SharedDecoratingShared.inner'
  Public:
    class: stdClass
    public: true
    shared: false
    properties:
      shared: '@Shared'
      notShared: '@NotShared'

```
I would assume both the properties of the `Public` service would be decorated. What happens instead only the shared property is decorated, while the notShared property is not.
Here are the corresponding lines from the built container.

```php
    /**
     * Gets the public 'Public' service.
     *
     * @return \stdClass
     */
    protected function getPublicService()
    {
        $instance = new \stdClass();

        $a = new \stdClass();
        $a->name = 'NotShared';

        $instance->shared = ($this->services['SharedDecoratingShared'] ?? $this->getSharedDecoratingSharedService());
        $instance->notShared = $a;

        return $instance;
    }
```
The shared property is decorated by its both decorators, while the notShared isn't decorated by either.
Is this expected behavior?
