### ISSUE TITLE
HttpClient scoped_clients  scope does not match by URL

### ISSUE THREAD

**Issue by 99hops** [symfony/symfony#41734]
**Symfony version(s) affected**: 5.3 (tested)

**Description**
When injecting `HttpClientInterface` without respect to `scoped_clients` name definition (ex. $someApi) or by using `HttpClient::create()` **scope** URL does not match when making calls and additional parameters are not applied.
For example if `HttpClientInterface $client` is injected into class constructor and then used to make calls to different URLs 
**scope** should be able to match the URL and apply additional configuration options but it doesn't.

**How to reproduce**
```
config/packages/framework.yaml
framework:
    http_client:
        scoped_clients:
            some_api:
                scope: 'https://example\.com'
                headers:
                    x-random-id: '123'
```
```
$httpClient = HttpClient::create();
$request = $httpClient->request('GET',  'https://example.com/endpoint');
```
OR 
```
class SomeController extends AbstractController
{
    function x(HttpClientInterface $httpClient) {
        $request = $httpClient->request('GET',  'https://example.com/endpoint');
    }
}
```
**x-random-id header not sent**

Works if name matches definition
```
function x(HttpClientInterface $someApi) {
    $request = $someApi->request('GET',  'https://example.com/endpoint');
}
```

**Additional context**
I found this article which claims this should work as expected https://blog.mathieu.dumoutier.fr/custom-symfony-http-client-with-scoping-client/

**Comment by fancyweb** [comment]
Status: works for me

`HttpClient::create();` creates a new instance so it's normal.

When you use `HttpClientInterface $httpClient`, I think you get the "default" (created by FrameworkBundle) http client, not your scoped client.

**Comment by 99hops** [comment]
@fancyweb Right, I agree with both statements but then what's the point of having a "scope" that matches by URL if it can't be used in that manner (like in the example link)? How am I supposed to get advantage of this scope option, say I want to have 50 scoped clients in microservice env that I don't want to inject and apply different options to them when making a call just by matching the scope expression. HttpClient::create(); doesn't allow to specify scoped client neither HttpClientInterface injection besides the variable name parameter with is not convenient in my case. Which of these two methods works for you?

**Comment by 99hops** [comment]
Here is what I am trying to achieve in the end

```
framework:
    http_client:
        default_options:
            # self-signed cert
            verify_peer: false
            verify_host: false
        scoped_clients:
            # only requests matching scope will use these options (as per doc)
            some.client:
                # only requests matching scope will use these options (as per doc)
                scope: 'https://some.client' 
                headers:
                    custom-header: '1234'
            other.client:
                # only requests matching scope will use these options (as per doc)
                scope: 'https://other.client' 
                headers:
                    custom-header: '4321'
```
```
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class TestController extends AbstractController
{
    #[Route('/')]
    public function index(
        HttpClientInterface $client
    ): Response {
        $response = $client->request('GET', ''https://some.client'); -> match scope and send custom-header: '1234'
    }
}
```
Result is **custom-header: '1234'** not send. Now if HttpClientInterface `$someClient` is injected everything is fine.
My question is how does one inject *generic* client that applies options (headers in this case) just by  matching the scope, is this doable or I am doing something wrong? 

Long story short I am trying to make a chained method HttpClient wrapper bundle to be shared between projects where you can do `$client->someClient()->request('GET', '/')` where `someClient() returns $this` and sets the $baseUrl internally in the class by private $baseUrl (and has HttpClientInterface  $client in the constructor) 

What options are left? Doing `$client->someClient(HttpClientInterface $someClient)` without passing HttpClientInterface (like $client->someClient()->request()) is near impossible by any means of DI (at least from everything I've tried: injection setter, service locator, etc)

At this point I really don't understand is this something I am doing wrong or this is just how thing are or it's a bug, please advice (:
