### ISSUE TITLE
`json_login_ldap` in chain with `json_login` and new authenticator

### ISSUE THREAD

**Issue by oliverreese** [symfony/symfony#41892]
**Symfony version(s) affected**: 5.3.2

**Description**
a combination of json_login_ldap and json_login will not work when the new authentication manager is enabled. They both
on their own work properly but not in combination. When new authentication manager is disabled they work properly together
in a chain.

**How to reproduce**
see attached repository with 4 different configuration cases to reproduce: 
https://github.com/oliverreese/symfony-security-ldap-login

**Possible Solution**

**Additional context**

**Comment by OskarStark** [comment]
cc @wouterj

**Comment by raphaelriehl** [comment]
Hi, maybe it's another issue, but I encounter same thing with `form_login` and `form_login_ldap`.
When I disable the new authentication manager it's works.
Same problem describe [here](https://stackoverflow.com/questions/68131217/how-to-use-the-ldap-form-login-and-form-login-on-symfony-5-3-with-the-new-authen).

**Comment by diversantvlz** [comment]
[here](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LdapFactoryTrait.php#L42) when the parent method is called, the base authenticator is replaced another with a different config. Parent method have hardcoded service id

**Comment by B4rb4ross4** [comment]
I can reproduce this issue aswell. I have the following firewall config:

```
main:
            lazy: true
            provider: app_user_provider
            user_checker: Some\Namespace\Infrastructure\Security\UnconfirmedUserChecker
            entry_point: 'form_login_ldap'
            form_login:
                login_path: login
                check_path: login
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'MyOrganization\{username}'
                login_path: login
                check_path: ldap_login_check
            logout:
                path: logout
```

Then you can see that the wrong options are injected into the "normal" form login authenticator.

```
array (
  'username_parameter' => '_username',
  'password_parameter' => '_password',
  'check_path' => 'ldap_login_check',
  'post_only' => true,
  'form_only' => false,
  'enable_csrf' => false,
  'csrf_parameter' => '_csrf_token',
  'csrf_token_id' => 'authenticate',
  'login_path' => 'login',
  'use_forward' => false,
  'require_previous_session' => false,
)
```

**Comment by franzwilding** [comment]
I also can produce the problem with SH 6.0.1: When using only the `form_login_ldap` authenticator, everything is working, however if I also add `form_login` (entry_point: 'form_login_ldap') the LDAP authenticator is not called.

**Comment by B4rb4ross4** [comment]
The problem is exactly in the place @diversantvlz linked. There is an [optimization ](https://github.com/B4rb4ross4/symfony/blob/6.1/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginFactory.php#L73)in place which shares the form_login config for all authenticators for all firewalls and that simply does not work and it breaks all the ldap decorators aswell.

**Comment by B4rb4ross4** [comment]
With symfony/security-bundle v6.0.3 the same error now occurs when disabling the new authentication manager.

**Comment by wiser** [comment]
Same problem here chaining `form_login`and `form_login_ldap` with symfony/security-bundle v5.4.5 (LTS).

~~Somebody else describes the same issue here : https://stackoverflow.com/questions/71576619/symfony-6-security-login-from-two-providers-entity-and-ldap~~ => The post has been deleted...

For now I changed back for the old way to configure it disabling the `authenticator manager`...

**Comment by wiser** [comment]
Does it take a big effort to solve this issue ?
I don’t realize how difficult it could be.
It seems a piece of code is shared for optimization, so is it "just" the upper linked part by @diversantvlz which needs to be reviewed ?

**Comment by raphaelriehl** [comment]
Is there any news about fix this problem ?

**Comment by chalasr** [comment]
Talking for myself, the reasons for not looking into this "naturally" are that I don't suffer from this bug and it's about ldap which I don't use and for which I don't have the required setup to reproduce locally. If you can, please have a look into this so you can come up with a patch to propose in a PR.

**Comment by Padam87** [comment]
@B4rb4ross4 's example is good.

`LdapFactoryTrait` calls the parent method, which overrides the service added by the `form_login` part, because it has the same name.

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LdapFactoryTrait.php#L38

Changing `$firewallName` to `$firewallName.'_ldap'` fixes it by avoiding the override.

@chalasr This is not really an LDAP issue, just a naming clash... Solutions:
1. Add a suffix to the firewall name like above - hacky
2. Remove the parent call - a lot of code duplication
3. Add a parameter for service name - breaking 

(Nr 1 might not be an option, as it would break success and failure handlers)

**Comment by wouterj** [comment]
If I read correctly, the issue is not adding a `_ldap` suffix to `$kid` here, resulting in the same service ID for both LDAP and non-LDAP authenticator: https://github.com/symfony/symfony/blob/ae3b07818fb3c5ea2d76cd4b5d75d7a2e22319be/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LdapFactoryTrait.php#L49

Anyone up for a PR?

**Comment by Padam87** [comment]
@wouterj Unfortunately it is not that easy. The line you mentioned is fine, because `$key` already has an ldap suffix, and works fine.

The problem is that the `LdapAuthenticator` is a wrapper around another auhtenticator, passed as the 1st argument.
https://github.com/symfony/symfony/blob/bc5fea4e2190f00a207871115a83dd7df03d7637/src/Symfony/Component/Ldap/Security/LdapAuthenticator.php#L45

The inner authenticator is created here: https://github.com/symfony/symfony/blob/ae3b07818fb3c5ea2d76cd4b5d75d7a2e22319be/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LdapFactoryTrait.php#L42

Which makes sense, always call the parent, either form_login, json_login etc, but this created inner service will have the same name as a regular form_login authenticator.

`$authenticatorId = parent::createAuthenticator($container, $firewallName, $config, $userProviderId);`
`$authenticatorId = parent::createAuthenticator($container, $firewallName.'_ldap', $config, $userProviderId);`

This change fixes it, but the `$firewallName` parameter is also used for actual firewall related code, so that whould break for example success and failure handlers.
There is no other way to change the name of the inner service.

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginFactory.php#L70

**Comment by wouterj** [comment]
Thanks for the explanation, this is clear to me now.

I've written a failing test case showing what is going wrong: https://github.com/symfony/symfony/compare/6.3...wouterj:symfony:issue-41892/ldap-decoration Let us know in this thread if you're working on fixing this in Symfony (you can use my commit as a start) :)

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by etiennerousseau** [comment]
Hi,
For me the bug is still relevant. 

I find a workaround by developing a custom  `LoginFormAuthenticator` which test if he can (in my context) do the authentification (with the `supports()` method). If not the authentification is done by the Ldap Authenticator.

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by chalasr** [comment]
Anyone up to work on this?

**Comment by MatTheCat** [comment]
Is changing authenticators ID a BC break? Else I guess we could suffix them by a hash computed from their options :thinking:

**Comment by opiredev** [comment]
@nabby27 created a $50.00 reward using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by MindfulPol** [comment]
Hello there 👋🏿 ,
@xopino and myself have been pair programming a bit. Together we came up with a possible approach to resolve the issue.

We've iterated the test provided by @wouterj , thnx for that, please let us know what you think :)

**Comment by opiredev** [comment]
🔥 The user @MindfulPol has claimed all rewards for this issue using [Opire](https://opire.dev).
🎯 You can see the PR [here](https://github.com/symfony/symfony/pull/57215)
💰 @nabby27 you can pay the related rewards [here](https://app.opire.dev/dashboard/creator/rewards?platform=GitHub&platformId=932366037)

**Comment by MindfulPol** [comment]
Closing the first pull request to fix the bug on the earlier mantained branch, aKa 5.4 **🤗**

There's one issue about the test, given the `enable_authenticator_manager` parameter was [removed](https://github.com/symfony/symfony/pull/47890), tests will break starting at 6.2, by removing the param it will work fine again, how should we take that into account?

**Comment by vasanth-kumar-m-y** [comment]
Is there a way to implement both **form_login** for in memory users and **form_login_ldap** for ldap users on same firewall
using Symfony 6.4

@MindfulPol  @oliverreese @franzwilding @wouterj @Padam87 @OskarStark

**Comment by luggesexe** [comment]
Having the same issue on 6.3.12 as @vasanth-kumar-m-y, the authenticator does not seem to work with both in place. The form_login sets the fail response and no later authenticator is called. That way in_memory and LDAP can not co-exist.

**Comment by keichitokuna** [comment]
Hello,
I spend two days trying to understand why form_login wasn't working with form_login_ldap.

I have this security.yaml:
```yaml
providers:
        local_users:
            entity:
                class: App\Entity\User
                property: username
        ldap_users:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(LDAP_BASE_DN)%'
                search_dn: '%env(LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'
                uid_key: "uid"
        all_users:
            chain:
                providers: ['ldap_users', 'local_users']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            entry_point: form_login
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                dn_string: '%env(LDAP_BASE_DN)%'
                query_string: '(uid={user_identifier})'
                search_dn: '%env(LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
```

But everytime, form_login sets the fail response and the form_login_ldap is never called...

Anyone succeeded with that ?
Thanks
