### ISSUE TITLE
[Translation] locales always need be be specified when pulling translations from provider

### ISSUE THREAD

**Issue by ymc-thum** [symfony/symfony#41901]
**Symfony version(s) affected**: 5.3.0

**Description**
When pulling translations using `bin/console translation:pull`, the `--locale` option always needs to be specified even if locales have been defined in `translation.yaml`

**How to reproduce**
- configure a valid translation provider in `translation.yaml`, e.g. for loco
```yaml
        providers:
            loco:
                dsn: "%env(LOCO_DSN)%"
                domains:
                    - default
                locales:
                    - de-DE
```
- run the ` bin/console translation:pull --force`

Expectation: translation files should be downloaded into the translations directory
Actual: no files are downloaded

When using `bin/console translation:pull --force --locales de-DE`, everything works as expected.

**Possible Solution**

Instead of intersecting the locales given in the cli with the ones provided in the configuration, `\Symfony\Component\Translation\Provider\FilteringProvider::read` should first check, if locales are provided in the cli. E.g. like this:

```php
    public function read(array $domains, array $locales): TranslatorBag
    {
        $domains = !$this->domains ? $domains : array_intersect($this->domains, $domains);
        $locales = 0 === count($locales) ? $this->locales : array_intersect($this->locales, $locales);
        return $this->provider->read($domains, $locales);
    }
```
