### ISSUE TITLE
Route not found with UTF-8 parameter name

### ISSUE THREAD

**Issue by TeLiXj** [symfony/symfony#41909]
**Symfony version(s) affected**: 5.3.2 (at least)

**Description**
Routes with an UTF-8 parameter name can't be found. 

**How to reproduce**
In YAML
```yaml
informes:
    path: /informes/{año}
    controller: App\Controller\InformesController::anual
```
or attributes
```php
#[Route("/informes/{año}", name: "informes")]
public function anual(string $año)
{
    dd($año);
}
```
**Possible Solution**
I don't know, I suppose that is a regression because I remember using this on Symfony 2 many years ago.

**Additional context**
I have tried with YAML, annotations and attributes and only in the last 5.3 version. 
Any route with UTF-8 characters works fine, only fails with UTF-8 parameters name.
The `routing.yaml` have 
```yaml
framework:
    router:
        utf8: true
```
And add `utf8: true` to route options doesn't work either
