### ISSUE TITLE
[Twig] Namespaced paths mistaken for service name

### ISSUE THREAD

**Issue by numediaweb** [symfony/symfony#42157]
**Symfony version(s) affected**: 5.2.11

**Description**
When I reference one of my bundle templates inside the `services.yaml` as a parameter: Symfony thinks it is a service!
This causes an error

**How to reproduce**
Following the docs on [bundle templates](https://symfony.com/doc/current/templates.html#bundle-templates), I have a template inside my bundle's `templates` folder that I can reference inside my controllers as `@myBundle/Email/Confirmation.html.twig`. Now, I want to reference this template as a parameter inside my services yaml file and pass it to my service:
```
# myBundle/config/services.yml
parameters:
    email_tpl.confirmation: '@myBundle/Email/Confirmation.html.twig'

services:
    myBundle\Mailer:
        arguments:
            - { confirmation: '%email_tpl.confirmation%'}
```

But this results in the error:

```
The service "myBundle\Mailer" has a dependency on a non-existent service "myBundle/Email/Confirmation.html.twig".
```
