### ISSUE TITLE
`.env.local` configuration values not loaded for SwiftMailer bundle

### ISSUE THREAD

**Issue by nowiko** [symfony/symfony#42225]
**Symfony version(s) affected**: 5.1.*

**Description**
I have added `.env.local` file to store there vars with sensitive data: mailer configuration and AWS SDK configuration.
Here is how `.env` file looks like:
```
MAILER_HOST=MAILER_HOST
MAILER_PORT=MAILER_PORT
MAILER_USER=MAILER_USER
MAILER_API_KEY=MAILER_API_KEY
MAILER_ENCRYPTION=MAILER_ENCRYPTION
```
These values are proprely set in the `.env.local`.

Switmailer configuration:
```yml
swiftmailer:
    host: '%env(MAILER_HOST)%'
    port: '%env(MAILER_PORT)%'
    encryption: '%env(MAILER_ENCRYPTION)%'
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_API_KEY)%'
```

I am constantly getting this error: `The MAILER_ENCRYPTION encryption is not supported`.

Meanwhile the config values for AWS SDK are properly set from the `.env.local`. Here is the configuration of AWS SDK service:
```yml
    app.s3_client:
        lazy: true
        class: Aws\S3\S3Client
        arguments:
            - version: '2006-03-01'
              region: "%env(AWS_REGION)%"
              credentials:
                  key: "%env(AWS_KEY)%"
                  secret: "%env(AWS_SECRET)%"
```
And this part works as expected. Besides, when I run :
```bash
composer dump-env`
```
It also generates `.env.local.php` with proper values. The only case it starts working as expected is when I move `MAILER_*` values into `.env`.

Is there anything I might be doing wrong or this is some kind of bug?
