### ISSUE TITLE
Circular reference detected for service

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#42288]
sf 5.3

User Deprecated: Since symfony/framework-bundle 5.3: The "session.storage.native" service is deprecated, use "session.storage.factory.native" instead.

and 
`
Circular reference detected for service "session.storage.factory.native", path: "session.storage.factory.native -> session.storage.factory.native".
`

`    
session:
        enabled: true
        handler_id: 'session.storage.factory.native' #session.storage.native
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
`

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by allfreelancers** [comment]
@xabbuh can you install sf 5.3 and past session settings:
`

    session:
        enabled: true
        handler_id: 'session.storage.factory.native' #session.storage.native
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 604800
`

**Comment by xabbuh** [comment]
```yaml
session:
    enabled: true
    handler_id: null
    storage_factory_id: 'session.storage.factory.native'
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    cookie_secure: auto
    cookie_samesite: lax
    cookie_lifetime: 604800
```

Does it work if you change your config like this?

**Comment by allfreelancers** [comment]
@xabbuh thx its work!
I dont see what in documentation
![image](https://user-images.githubusercontent.com/2994432/127278777-a54d424d-3a22-4a89-88ab-8cb82cc7c836.png)

**Comment by Nykilor** [comment]
You don't need to change the whole config only one line:

framework.yaml
````
session:
        storage_factory_id: session.storage.factory.native
````

Btw the docs specify that by version 5.3 it defaults to this value but it appears it does not https://symfony.com/doc/current/reference/configuration/framework.html#storage-factory-id

I won't admit how much time I wasted for this :/

**Comment by xabbuh** [comment]
Would anyone like to propose a PR improving the documentation and/or the deprecation message?

**Comment by Evgeny1973** [comment]
Have same problem:
![image](https://user-images.githubusercontent.com/20745667/134430128-81892716-7a39-473d-b966-99bc2e1a2355.png)

What should I write in `storage_factory_id:` if i use 
`handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler`

**Comment by pdevillard** [comment]
@Evgeny1973, you can let the following configuration:

```
framework:
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        storage_factory_id: session.storage.factory.native
```

The storage & the handler are two different things, we used to manipulate the handlers but now there is a new layer to dynamically provide an handler (or no session handler at all) depending on the request. 

Have a look at `NativeSessionStorageFactory`. It creates a `NativeSessionStorage` which passes your `handler_id`.
