### ISSUE TITLE
[Testing] loginUser Failed to start the session because headers have already been sent

### ISSUE THREAD

**Issue by crtl** [symfony/symfony#42305]
**Symfony version(s) affected**: 5.3

**Description**
Following the testing guide from https://symfony.com/doc/current/testing.html#functional-tests
when using  `loginUser` in test case I get following error:

```
There was 1 error:

1) Test\Controller\Api\ProfileControllerTest::testGetProfile
RuntimeException: Failed to start the session because headers have already been sent by "D:\dev\projects\project\vendor\phpunit\phpunit\src\Util\Printer.php" at line 104.

D:\dev\projects\project\vendor\symfony\http-foundation\Session\Storage\NativeSessionStorage.php:152
D:\dev\projects\project\vendor\symfony\http-foundation\Session\Storage\NativeSessionStorage.php:323
D:\dev\projects\project\vendor\symfony\http-foundation\Session\Session.php:257
D:\dev\projects\project\vendor\symfony\http-foundation\Session\Session.php:279
D:\dev\projects\project\vendor\symfony\http-foundation\Session\Session.php:83
D:\dev\projects\project\vendor\symfony\framework-bundle\KernelBrowser.php:136
D:\dev\projects\project\tests\Controller\Api\ProfileControllerTest.php:29

```

**How to reproduce**
```
class ProfileControllerTest extends WebTestCase
{

    public function testGetProfile()
    {

        $client = static::createClient();

        /** @var UserRepositoryInterface $repository $repository */
        $repository = static::getContainer()->get(UserRepositoryInterface::class);

        // Get first user
        $user = $repository->find(1);

        $client->loginUser($user, "api");

        $client->request("GET", "/api/v1/profile");

        $body = ControllerTestHelper::parseAndAssertResponse($this, $client->getResponse());
   }
}
```

Removing ` $client->loginUser($user, "api");` fixes issue but then request is not authenticated and test fails.

**Additional context**
I am using new authentication system with firebase token authenticator:
```yaml
security:
    enable_authenticator_manager: true
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\Authenticator\FirebaseTokenAuthenticator
```

**Comment by dmaicher** [comment]
it seems your test environment is using native php sessions (`NativeSessionStorage`)?

Probably its better to use a mock file storage.

This is also configured in the framework-bundle recipe: https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.3/config/packages/framework.yaml#L24

**Comment by xabbuh** [comment]
@crtl Can you confirm that a configuration like the one @dmaicher linked to solves your issue?

**Comment by bmupex** [comment]
I was having the same issue following an upgrade from 5.2 to 5.3 and the suggestion from @dmaicher has fixed it for me 👍

**Comment by crtl** [comment]
Running `php bin/console debug:config --env test` prints:
```
session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        enabled: true
        storage_id: session.storage.mock_file
        cookie_httponly: true
        gc_probability: 1
        save_path: '%kernel.cache_dir%/sessions'
        metadata_update_threshold: 0
```

Im already running 5.3
```
# cat composer.json | grep symfony/
        "symfony/console": "5.3.*",
        "symfony/dotenv": "5.3.*",
        "symfony/event-dispatcher": "5.3.*",
        "symfony/filesystem": "5.3.*",
        "symfony/flex": "^1.1",
        "symfony/form": "5.3.*",
        "symfony/framework-bundle": "5.3.*",
        "symfony/intl": "5.3.*",
        "symfony/mime": "5.3.*",
        "symfony/monolog-bundle": "^3.3",
        "symfony/orm-pack": "^2.1",
        "symfony/psr-http-message-bridge": "^2.1",
        "symfony/runtime": "5.3.*",
        "symfony/security-bundle": "5.3.*",
        "symfony/serializer": "5.3.*",
        "symfony/swiftmailer-bundle": "^3.2",
        "symfony/translation": "5.3.*",
        "symfony/twig-bundle": "5.3.*",
        "symfony/validator": "5.3.*",
        "symfony/webpack-encore-bundle": "^1.5",
        "symfony/yaml": "5.3.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
        "symfony/symfony": "*"
        "symfony/browser-kit": "5.3.*",
        "symfony/css-selector": "^5.3",
        "symfony/maker-bundle": "^1.11",
        "symfony/phpunit-bridge": "^5.3",
        "symfony/profiler-pack": "^1.0",
        "symfony/var-dumper": "5.3.*"
```

**Comment by COil** [comment]
This is weird, it was OK with PHP 7.4 but when I switched to PHP 8 I also faced this error. I had to fix my `framework.yaml` test file (Symfony 5.3): 

```
framework:
    test: true
    session:
        # storage_id: session.storage.mock_file
        storage_factory_id: session.storage.factory.mock_file
```
