### ISSUE TITLE
`Symfony\Config\FrameworkConfig` not found (phpstan error)

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#42342]
**Symfony version(s) affected**: 5.3.6

**Description**
With this being my `config/packages/mailer.php`:
```php
<?php declare(strict_types=1);

use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $framework): void
{
    $framework->mailer()
        ->transport(...)
    ;
};
```
... phpstan is reporting:
> Parameter $framework of anonymous function has invalid typehint type Symfony\Config\FrameworkConfig.

**Possible Solution**
There's a similar issue over at phpstan, with a proposed solution:
https://github.com/phpstan/phpstan/issues/5189#issuecomment-863821592

**Comment by Nyholm** [comment]
That file is not autoloaded with PSR-4. You need to tell PHPStan to scan the cache directory. 

```
includes:
    - ./phpstan-baseline.neon

parameters:
  level: 5
  reportUnmatchedIgnoredErrors: false
  scanDirectories:
    - %currentWorkingDirectory%/var/cace/dev/Symfony/Config
```
