### ISSUE TITLE
Config builders do not support variable array nodes

### ISSUE THREAD

**Issue by mbabker** [symfony/symfony#42359]
**Symfony version(s) affected**: 5.3

**Description**
I'm updating one of our app configs to make use of the new config builders.  That app uses `FOSCKEditorBundle`, and its config has a variable prototype for the `fos_ck_editor.configs` key.  From what I can see from the dumped builder class, it isn't possible to configure this variable node.

**How to reproduce**
Create a SF 5.3 app and install `FOSCKEditorBundle`, use this config for the bundle:

```yaml
fos_ck_editor:
    default_config: simple_toolbar
    configs:
        simple_toolbar:
            extraAllowedContent: 'a span(*); div(*); svg(*); h2[*]; h3(*); svg title[*]; svg path[*]'
            toolbar:
                - ['Format', 'Bold', 'Italic', 'Strike', 'Link', 'Unlink', '-', 'RemoveFormat']
                - ['BulletedList', 'NumberedList', '-', 'Outdent', 'Indent']
                - ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Source']
```

Then try to switch this config from YAML to PHP using the config builder.

Relevant parts of the dumped builders for quick reference:

<details>
<summary>FosCkEditorConfig class</summary>

```php
<?php

namespace Symfony\Config;

require_once __DIR__.\DIRECTORY_SEPARATOR.'FosCkEditor'.\DIRECTORY_SEPARATOR.'ConfigsConfig.php';

use Symfony\Component\Config\Loader\ParamConfigurator;
use Symfony\Component\Config\Definition\Exception\InvalidConfigurationException;


/**
 * This class is automatically generated to help creating config.
 *
 * @experimental in 5.3
 */
class FosCkEditorConfig implements \Symfony\Component\Config\Builder\ConfigBuilderInterface
{
    private $defaultConfig;
    private $configs;
    
    /**
     * @default null
     * @param ParamConfigurator|mixed $value
     * @return $this
     */
    public function defaultConfig($value): self
    {
        $this->defaultConfig = $value;
    
        return $this;
    }
    
    public function configs(string $name, array $value = []): \Symfony\Config\FosCkEditor\ConfigsConfig
    {
        if (!isset($this->configs[$name])) {
            return $this->configs[$name] = new \Symfony\Config\FosCkEditor\ConfigsConfig($value);
        }
        if ([] === $value) {
            return $this->configs[$name];
        }
    
        throw new InvalidConfigurationException('The node created by "configs()" has already been initialized. You cannot pass values the second time you call configs().');
    }
    

}
```
</details>

<details>
<summary>ConfigsConfig Class</summary>

```php
<?php

namespace Symfony\Config\FosCkEditor;


use Symfony\Component\Config\Definition\Exception\InvalidConfigurationException;


/**
 * This class is automatically generated to help creating config.
 *
 * @experimental in 5.3
 */
class ConfigsConfig 
{
    
    public function __construct(array $value = [])
    {
    
        if ([] !== $value) {
            throw new InvalidConfigurationException(sprintf('The following keys are not supported by "%s": ', __CLASS__).implode(', ', array_keys($value)));
        }
    }
    
    
    public function toArray(): array
    {
        $output = [];
    
        return $output;
    }
    

}
```
</details>
