### ISSUE TITLE
translation path should overwrite default_path

### ISSUE THREAD

**Issue by h2Entwicklung** [symfony/symfony#42404]
**Description**
We want to use alternative texts in our app.
For this use case we want to use the translation bundle to overwrite the default texts.
The idea is that in the default_path the translation:update command is updateing the default texts. But when the "path" in the translation.yaml is set then if the translation is found there as well, then the text from the default_path should be overwritten.
The mechanism now already works as expected with several paths in the "path" variable in the translation.yaml.

So my idea is now the change the priority of the default_path from highest to lowest.

```
framework:
    default_locale: de
    translator:
        default_path: '%kernel.project_dir%/translations/default'
        path:
            - '%kernel.project_dir%/translations/'
            - '%kernel.project_dir%/translations/custom'
        fallbacks:
            - de
```
Now our workflow is:
1.  moving the messages+intl-icu.de.xlf to the default directory
2. making the translation:update command
3. moving the messages+intl-icu.de.xlf back to the translations folder so the default folder is empty again and the paths are used.

**Example**
### now:
priority:
path:[path1, path2] --> default_path

### feature Request:
priority:
default_path --> path: [path1, path2]

**Comment by carsonbot** [comment]
Thank you for this issue.
There has not been a lot of activity here for a while. Has this been resolved?

**Comment by welcoMattic** [comment]
@h2Entwicklung Hi do you still have a concern about this issue?

I think your workflow is quite special compare to the aim of the Translator component, did you find any workaround for it?

**Comment by h2Entwicklung** [comment]
Hello @welcoMattic,
```
translation.yaml
framework:
    default_locale: de
    translator:
        default_path: '%kernel.project_dir%/translations/default'
        path:
            - '%kernel.project_dir%/translations/'
            - '%kernel.project_dir%/translations/custom'
        fallbacks:
            - de
```

The default directory is empty, and the default files lives in the root.
When I add some new texts, `trans:up de --force` I move the files which are changed to the  `defaut` directory. After the command was sucessfull, I move them back to the root directory. Custom files are living in `custom` directory.
