### ISSUE TITLE
RabbitMQ streams

### ISSUE THREAD

**Issue by AhmedSamy** [symfony/symfony#42411]
**Description**
Messenger to support the new rabbitMQ streams in 3.9
https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview/

**Example**
```
framework:
    messenger:
        transports:
            amqp:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    //stream related options 
```

Parameter Name | Description | Default
-- | -- | --
stream | The stream to publish to. | No default, mandatory setting.
name | The logical name of the producer. Specify a name to enable message deduplication. | null (no deduplication)
batchSize | The maximum number of messages to accumulate before sending them to the broker. | 100
subEntrySize | The number of messages to put in a sub-entry. A sub-entry is one "slot" in a publishing frame, meaning outbound messages are not only batched in publishing frames, but in sub-entries as well. Use this feature to increase throughput at the cost of increased latency and potential duplicated messages even when deduplication is enabled. | 1 (meaning no use of sub-entry batching)
maxUnconfirmedMessages | The maximum number of unconfirmed outbound messages. Producer#send will start blocking when the limit is reached. | 10,000
batchPublishingDelay | Period to send a batch of messages. | 100 ms
confirmTimeout | Time before the client calls the confirm callback to signal outstanding unconfirmed messages timed out. | 30 seconds
enqueueTimeout | Time before enqueueing of a message fail when the maximum number of unconfirmed is reached. The callback of the message will be called with a negative status. Set the value to Duration.ZERO if there should be no timeout. | 10 seconds.

May be that's already possible, but I couldn't make it work, feel free to advice please
