### ISSUE TITLE
[Security] Unable to require authentication to certain firewall with the new authenticator system

### ISSUE THREAD

**Issue by njutn95** [symfony/symfony#42520]
**Symfony version(s) affected**: 5.3.6 (probably all 5.3.x)

**Description**
When creating an API firewall, we used to do the following check in the `supports()` method:

```php
    public function supports(Request $request): bool
    {
        return $request->headers->has('X-AUTH-TOKEN');
    }
```

which would then fall back to the `start()` method which looked like:

```php
    public function start(Request $request, AuthenticationException $authException = null)
    {
        $data = [
            'message' => 'Authentication Required',
        ];

        return new JsonResponse($data, Response::HTTP_UNAUTHORIZED);
    }
```

A result of that would be that the user would be presented with a message `Authentication Required` if the header was missing.

However, in the new authentication system `start` method only exists as part of the `Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator` (and `Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface`), but it does not exist as part of the `Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator` which is what makes sense to use for the API authenticator (and is used as an example in the [docs](https://symfony.com/doc/current/security/authenticator_manager.html#creating-a-custom-authenticator)). This leads to an end-result of, if the authenticator is skipped, the request will continue even though authentication is required. This used to be handled with the `anonymous: false` parameter in the `security.firewall.api` section, which is now removed from use.

**How to reproduce**
`security.yaml`:
```yaml
security:
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
            provider: user_provider
```

`src/Security/ApiTokenAuthenticator.php`:
```php
<?php

namespace App\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\PassportInterface;

class ApiTokenAuthenticator extends AbstractAuthenticator
{
    public function supports(Request $request): ?bool
    {
        return false;
    }

    public function authenticate(Request $request): PassportInterface
    {
        throw new \Exception('This won\'t be reached');
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        throw new \Exception('This won\'t be reached');
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        throw new \Exception('This won\'t be reached');
    }
}
```

`src/Controller/ApiController.php`:
```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/api")
 */
class ApiController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function test()
    {
        return new Response('ok');
    }
}
```

Visit `/api` endpoint, and instead of getting restricted access, you'll be allowed to access it. 

**Possible Solution**

**Additional context**

**Comment by n0rbyt3** [comment]
@njutn95 The docs are a bit tricky. There is only a comment to describe what you need to do.

In security.yaml:
```yaml
# remember to also configure the entry_point if the
# authenticator implements AuthenticationEntryPointInterface
# entry_point: App\Security\CustomFormLoginAuthenticator
```

You need to implement ```AuthenticationEntryPointInterface``` and configure it as entry point for your firewall.

**Comment by njutn95** [comment]
@n0rbyt3 I have tried that as well, but it doesn't work. I'm not sure if I'm doing something wrong here?

Changed the authenticator to 
```php
class ApiTokenAuthenticator extends AbstractAuthenticator implements AuthenticationEntryPointInterface
{
    ...

    public function start(Request $request, AuthenticationException $authException = null)
    {
        $data = [
            'message' => 'Authentication Required',
        ];

        return new JsonResponse($data, Response::HTTP_UNAUTHORIZED);
    }
}
```

And `security.yaml` to 
```yaml
security:
    firewall:
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
            provider: user_provider
            entry_point: App\Security\ApiTokenAuthenticator
```

however, I'm still getting back the Controller's response
