### ISSUE TITLE
Locale not detected when priority is set

### ISSUE THREAD

**Issue by christophrahe1** [symfony/symfony#42663]
**Symfony version(s) affected**: 5.2.6

**Description**
In my annotations.yaml I set different locales based on different hosts and prefixes. When I set the "priority" in a route the locale is not detected in some situations.

**How to reproduce**
_annotations.yaml_
```
controllers_frontend:
resource: ../../src/Controller/Frontend
type: annotation
host:
  'de-DE': example.de
  'de-AT': example.at
  'de-CH': example.ch
  'fr-CH': example.ch
prefix:
  de-DE: '' # don't prefix URLs for German
  de-AT: ''
  de-CH: '/de'
  fr-CH: '/fr'

```
This works perfectly for route "some-route" in Controller A:
```
example.de/some-route -> locale = de-DE
example.at/some-route -> locale = de-AT
example.ch/de/some-route -> locale = de-CH
```

When I set a priority in a route as follows:

```
 /**
     * @Route("/some/other/route", priority="10", name="some_other_route")
     */
```
the locales are not being detected for de-DE and de-AT, see here:

```
example.de/some/other/route-> locale not detected, it goes back to the fall back locale
example.at/some/other/route -> locale not detected, it goes back to the fall back locale
example.ch/de/some/other/route -> locale = de-CH
```
