### ISSUE TITLE
Custom TokenVerifierInterface implementation ignored

### ISSUE THREAD

**Issue by 537mfb** [symfony/symfony#42775]
**Symfony version(s) affected**: 5.4.x@dev

**Description**

I'm adding `RememberMe` functionality with a database in the back - so I followed the instructions in [here](https://symfony.com/doc/current/security/remember_me.html#remember-me-token-in-database).

However, in my use case the email isn't enough to identify the user (I have custom registration and login already working) so I created a custom `TokenProvider` that implements both `TokenProviderInterface` and `TokenVerifierInterface`, and changed the `token_provider` to be my `TokenProvider`, and added my `TokenProvider` to the `services.yaml` in replacement of `DoctrineTokenProvider`.

I also removed the `property: email` line from the `User Provider` configuration and made my `UserRepository` implement `UserLoaderInterface` as instructed [here](https://symfony.com/doc/current/security/user_provider.html#security-entity-user-provider)

When I login with the `Remember Me` checkbox on, it calls `createNewToken` in my custom `TokenProvider`, that creates a new entry in my database and the `POST` response has a `set-cookie` for `REMEMBERME`.

However, after the redirect that occurs after the authentication process, there's no `REMEMBERME` cookie in the `request` anymore.

Tests in `PersistentRememberMeHandler` show that the constructor gets an instance of `CacheTokenVerifier` that can't verify my tokens and tries to use that.

What am I missing to make it use my implementation of `TokenVerifierInterface`? Do i need to register it somewhere (it's already in `services.yaml`)?

**How to reproduce**

Create a site with a custom `TokenProvider`/`TokenVerifier`

**Possible Solution**

In `PersistentRememberMeHandler`, if the `TokenProvider` implements `TokenVerifierInterface` use it and ignore the `TokenVerifier` argument.

Currently this is already done if `TokenVerifier` is `null`.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by 537mfb** [comment]
@xabbuh 'small' am not sure if i can - it will need a custome authenticator a database, etc

but i'll see what a minimum example can be like and get back to you later today

**Comment by 537mfb** [comment]
@xabbuh  https://github.com/537mfb/Bug dev branch

**Comment by xabbuh** [comment]
@537mfb Sorry for not coming back earlier. Looking into it a bit I think this is rather a configuration issue. If I update your firewall config like this, everything seems to work as expected:

```yaml
security:
    # ...

    firewalls:
        main:
            # ...

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                token_provider: 'App\Security\RememberMe\TokenProvider'
                token_verifier: 'App\Security\RememberMe\TokenProvider'

    # ...
```

So I am going to close here. But please let me know if you do not agree and we can reconsider.
