### ISSUE TITLE
[Messenger] Child class not being handled when configuring messenger manually

### ISSUE THREAD

**Issue by jcerrada** [symfony/symfony#42785]
**Symfony version(s) affected**: 5.2.12

**Description**
When configuring multiple buses manually in order to restrict the messages that are sent to each bus, child classes are not being handled by the handler of their parent class. This behaviour doesn't happen if our handlers just extend the `MessageHandlerInterface` and we don't restrict the messages per bus.

**How to reproduce**
Lets say we configure our handlers like this:
```yaml
framework:
    messenger:
        default_bus: query.bus
        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
# ...

services:
    _instanceof:
        App\MessageHandler\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\MessageHandler\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
```

And then we have our commands:

```php
class FooCommand {

}

class FooChildCommand extends FooCommand {

}

class FooHandler implements App\MessageHandler\CommandHandlerInterface {
        public function __invoke(FooCommand $command) {
           //...
       }
}
```

Following this configuration, the `FooCommand` will be handled, but the `FooChildCommand` won't.
