### ISSUE TITLE
Profiler Performance section empty after changes structure of src

### ISSUE THREAD

**Issue by Mausino** [symfony/symfony#42829]
**Symfony version(s) affected**: 5.3.7  -> WebProfilerBundle latest
**Description**

I extended symfon src/ folder for another section of controller an entity and the Performance Section stop working
All other sections are working/showing data as before.. only performance is affected

No timing events have been recorded. Check that symfony/stopwatch is installed and debugging enabled in the kernel.

symfony/stopwatch is installed
Note: all my recipes in this time are updated to latest versions
[
![Snímka obrazovky z 2021-09-01 15-42-02](https://user-images.githubusercontent.com/5773777/131682320-0e6cb26d-56ca-4986-8392-8159aa538183.png)
](url)

config/packages/dev/web_profiler.yaml

```
web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
```

**How to reproduce**

i changed this in for new folder structure:

in config/packages/doctrine.yaml 

```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            System:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/System/Entity'
                prefix: 'App\System\Entity'
                alias: App
```

in config/services.yaml

```
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/System/Entity/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    App\System\Controller\:
        resource: '../src/System/Controller/'
        tags: ['controller.service_arguments']
```

**Possible Solution**

**Additional context**
