### ISSUE TITLE
LdapBadge not usable due to defunct CheckLdapCredentialsListener

### ISSUE THREAD

**Issue by moebiusband73** [symfony/symfony#42874]
**Symfony version(s) affected**: 5.3.7

**Description**
I want to use LdapBadge in a custom authenticator in the new Security Authenticator system.
In LdapBadge you have to provide a  string `$ldapServiceId`.
After manually setting up a CheckLdapCredentialsListener an Exception is thrown `\LogicException(sprintf('Cannot check credentials using the "%s" ldap service, as such service is not found. Did you maybe forget to add the "ldap" service tag to this service?'`. The method that causes this exception simply checks if the id is set in the array of factories.
And there is no such factory. I think the deeper problem here is that the documentation is still mixed, the ldap docs refer to the old system but the code is already (in parts) for the new system.

I am unsure how this should work? I tried to reverse engineer the LdapFormLogin, but this links to the legacy `LdapBindAuthenticationProvider`. 

**How to reproduce**
Create a custom authenticator using LdapBadge. This one tries to authenticate to the local DB provider if a password is set and authenticates to ldap otherwise. That is at least the plan.
```
  public function authenticate(Request $request): PassportInterface
    {
        $credentials = $this->getCredentials($request);

        $user = $this->userProvider->loadUserByIdentifier($credentials['username']);
        $dbPassword = $user->getPassword();
        $passport = new Passport(
            new UserBadge($credentials['username'], [$this->userProvider, 'loadUserByIdentifier']),
            new PasswordCredentials($credentials['password'])
        );

        if ( empty($dbPassword) ) {
            $configuration = new Configuration($this->_em);
            $dnString = $configuration->getValue('ldap_user_base');
            $searchDn = $configuration->getValue('ldap_search_dn');
            $searchPassword = getenv('LDAP_PW');
            $queryString = $configuration->getValue('ldap_user_filter');
            /* I tried many things as service Id, but I think it cannot work as there is no Factory for it */
            $passport->addBadge(new LdapBadge('ldap', $dnString));
            /* $passport->addBadge(new LdapBadge('ldap', $dnString, $searchDn, $searchPassword, $queryString)); */
        }
        $passport->addBadge(new CsrfTokenBadge('authenticate', $credentials['csrf_token']));

        return $passport;
    }
```
You need to setup the `CheckLdapCredentialsListener` in `services.yaml`:
```
    Symfony\Component\Ldap\Security\CheckLdapCredentialsListener:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\CheckPassportEvent }
```

**Possible Solution**
The issue is that the user of LdapBadge is bothered providing a magical Ldap service Id.
Still all the magic must be setup beforehand for this to work. A Factory seems to be missing for the low level ldap service provider.  Do I have to provide one one my own? I was thinking it should be easy to use the LdapBadge. But I am no expert. Still as a developer  I can say this is not simple and not transparent.
The default everybody wants should be simple and straightforward to use.

**Additional context**

**Comment by wouterj** [comment]
Hi @moebiusband73! The documentation indeed is outdated on this part - it's a work in progress at the moment.

What you need to do for LDAP:

1. Create an LDAP client service as described in https://symfony.com/doc/current/security/ldap.html#configuring-the-ldap-client e.g:
   ```yaml
   services:
       app.ldap:
           class: 'Symfony\Component\Ldap\Ldap'
           arguments: ['@app.ldap_adapter']
           tags: [ldap]  # <-- this is important!

       app.ldap_adapter:
           class: 'Symfony\Component\Ldap\Adapter\ExtLdap\Adapter'
           arguments:
               -   host: my-server
                   port: 389
                   encryption: tls
                   options:
                       protocol_version: 3
                       referrals: false
   ```
2. Add an `LdapBadge` in your authenticator:
   ```php
   $passport = new Passport(
       new UserBadge($credentials['username'], [$this->userProvider, 'loadUserByIdentifier']),
       new PasswordCredentials($credentials['password']),
       // "app.ldap" is the name of the "Symfony\Component\Ldap\Ldap" service defined in (1)
       [new LdapBadge('app.ldap', $dnString)]
   );
   ```

So you don't need to manually configure the `CheckLdapCredentialsListener` service. Looking at the error you pasted, it seems like you forgot to add the `ldap` tag to your LDAP client service configuration.

**Comment by moebiusband73** [comment]
Hi @wouterj,
thanks for the quick response!
This unfortunately does not solve the problem. And yes I set the ldap tag (in multiple ways) on the service.
I tried your suggestion and there seems to be something different now. But it is still not working.
When I remove the `CheckLdapCredentialsListener` in my `service.yaml` I have a very strong feeling the service is not triggered. This is kind of difficult to diagnose because the event listener does not show up when doing `php bin/console debug:event-dispatcher` .  But I put an exception in `CheckLdapCredentialsListener` for quick and dirty debugging and it is not thrown.

I already wondered before that when I register the Listener explicitly two Listeners are setup:
```
Symfony\Component\Ldap\Security\CheckLdapCredentialsListener::onCheckPassport()                                         144 
Symfony\Component\Ldap\Security\CheckLdapCredentialsListener::onSymfonyComponentSecurityHttpEventCheckPassportEvent()   0
```

Still `onSymfonyComponentSecurityHttpEventCheckPassportEvent` is not in `CheckLdapCredentialsListener` and I also cannot find it anywhere using a source code grepper. So the string maybe constructed in the source code somewhere or my source code grepper fails me.

What is different now when I against your recommendation  still set up the Listener explicitly I get an error that `onSymfonyComponentSecurityHttpEventCheckPassportEvent` is not available in `CheckLdapCredentialsListener`.
Do you have any suggestion where `onSymfonyComponentSecurityHttpEventCheckPassportEvent` comes from?

I will further debug, maybe I can give you more insight soon.
Best Regards,
Jan

PS:
If you are interested to see the setup in  the full environment: https://github.com/ClusterCockpit/ClusterCockpit/tree/develop .
I also have a Docker compose setup available (unfortunately it is currently also work in progress :-): 
https://github.com/ClusterCockpit/cc-docker

**Comment by wouterj** [comment]
Aah, I see now. It indeed seems like we don't register the listener when using custom authenticators (thanks for linking the project, that helps a lot!).

I guess this config should work:

```yaml
Symfony\Component\Ldap\Security\CheckLdapCredentialsListener:
    arguments: ['@security.ldap_locator']
    tags:
        - { name: kernel.event_subscriber, dispatcher: security.event_dispatcher.main }
        - { name: kernel.event_subscriber, dispatcher: security.event_dispatcher.api }
```

(maybe you can remove one of the 2 tags, if you only need ldap for one firewall)

We should probably introduce something like `ldap: true` to automate registering the listener for the firewall.
