### ISSUE TITLE
[DI] Cannot autowire service... You should maybe alias this class...

### ISSUE THREAD

**Issue by d42ohpaz** [symfony/symfony#42880]
**Symfony version(s) affected**: 5.3.7

**Description**
I have a bundle that implements an abstract service for an abstract class. There is also a trait provided that uses a `@required` setter that type-hints using the abstract class. In 5.3.4, I simply defined a concrete service that `decorates` the abstract class with my concrete implementation and DI was happy. But when upgrading to 5.3.7, I get the following error:

> Cannot autowire service “….“: argument “$argument” of method “setArgument()” references class “My\AbstractClass” but this service is abstract. You should maybe alias this class to the existing “app.concrete.implementation" service.

**How to reproduce**
### Bundle services.yaml:

```yaml
services:
    _defaults:
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        autowire: true      # Automatically injects dependencies in your services.
        public: false       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    My\AbstractClass: '@my.abstract_class.helper'

    my.abstract_class.helper:
        abstract: true
        class: My\AbstractClass
```

### Bundle Trait

```php
namespace My\Helper;

use My\AbstractClass;

trait MyTrait
{
    private $helper;

    public function getHelper(): AbstractClass
    { return $this->helper; }

    /**
     * @required
     */
    public function setHelper(AbstractClass $helper): void
    { $this->helper = $helper; }
}
```

### App services.yaml:

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        autowire: true      # Automatically injects dependencies in your services.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    app.concretete.implementation:
        arguments:
            $configs: '%my_config%'
        class: My\ConcreteImplementation
        decorates: My\AbstractClass
```

**Possible Solution**
N/A

**Additional context**
N/A
