### ISSUE TITLE
[HttpClient] RetryableHttpClient doesn't retry on idle timeout

### ISSUE THREAD

**Issue by mynameisbogdan** [symfony/symfony#42919]
**Description**

`RetryableHttpClient` doesn't retry on idle timeout throwing a `Symfony\Component\HttpClient\Exception\TimeoutException` with the message `Idle timeout reached for "..."`.

Would be nice if it did.

**Comment by nicolas-grekas** [comment]
I played with `RetryableHttpClient` recently and it did retry on timeouts.
Can you please provide a reproducer?

**Comment by mynameisbogdan** [comment]
I really don't know how to reproduce a network timeout.

I'm getting errors quite often even with max 5 retries.

I'm using the following configuration:
```yaml
retry_failed:
    http_codes:
        0: true # for transport exceptions
        500: true
        502: true
        503: true
    delay: 1500
    max_retries: 5
    max_delay: 10000
```

The exception:
```json
{
  "exception": {
    "class": "Symfony\\Component\\HttpClient\\Exception\\TimeoutException",
    "message": "Idle timeout reached for \"https://...\".",
    "code": 0,
    "file": "/home/www/app/releases/20210906100117Z/vendor/symfony/http-client/Chunk/ErrorChunk.php:65",
    "trace": [
      "/home/www/app/releases/20210906100117Z/vendor/symfony/http-client/Response/AsyncResponse.php:77",
      "/home/www/app/releases/20210906100117Z/vendor/symfony/http-client/Response/CommonResponseTrait.php:155",
      "/home/www/app/releases/20210906100117Z/vendor/symfony/http-client/Response/CommonResponseTrait.php:44",
      "/home/www/app/releases/20210906100117Z/vendor/symfony/http-client/Response/CommonResponseTrait.php:83"
      ...
    ]
  }
}
```
