### ISSUE TITLE
[DX][Router] Configure trailing slash on root globally

### ISSUE THREAD

**Issue by flohw** [symfony/symfony#43059]
**Description**
Create a global option to allow configuration of the `trailing_slash_on_root` option at route level.

As I am building an api, I never need the trailing slash and I have to mention the option on a lot of place with the `false` value. As for me `false` should be the default value and I don't remember if I need to configure at the leaf route level or if I can define at the parent level (root level seems to not work), I would like to have a `framework.router.trailing_slash_on_root` configuration (name has to be defined) could be an improvement on this.

The option appears 53 times in my code, always with false value.

**Example**
```yaml
# a-lot-of-my-routes-configuration-files.yaml
api_route_resource:
  resource: ./route-resource.yaml
  prefix: /route
  name_prefix: routes_
  trailing_slash_on_root: false

# Possible new config/packages/routing.yaml content
framework:
    router:
        trailing_slash_on_root: false

# new-a-lot-of-my-routes-configuration-files.yaml
api_route_resource:
  resource: ./route-resource.yaml
  prefix: /route
  name_prefix: routes_
```

I hope this idea can help some people and I am not the only one concerned. Also I hope to not have missed something in the documentation. ;-)

Thank you.

**Comment by Tobion** [comment]
i don't think the name of `trailing_slash_on_root` makes sense on a global route config. the "root" means the root of the import (only consisting of the prefix). at the global level there is no "root". it would would probably require a different name. 
And I think it was already discussed at the original issue/pr of this feature.

**Comment by flohw** [comment]
Yes, I agree that the name is not ideal. I choose to use it only for a better comprehension. It can be changed.

Maybe `trailing_slash` would be enough?

**Comment by carsonbot** [comment]
Thank you for this issue.
There has not been a lot of activity here for a while. Has this been resolved?

**Comment by carsonbot** [comment]
Friendly ping? Should this still be open? I will close if I don't hear anything.

**Comment by flohw** [comment]
No, it shouldn't I think.

If anyone can point somewhere to look and try to implement it would be nice.

Unfortunately I won't be available until July, then will make my best to implement it.

Thank you.

**Comment by carsonbot** [comment]
Thank you for this issue.
There has not been a lot of activity here for a while. Has this been resolved?

**Comment by aarong416** [comment]
I am also having this issue.

I previously had

```yaml
options:
    content_type: application/json
```

in my `config/routes.yaml` file to set a default content type for every route, and then when a route required a different content type, one could be specified by overriding `content_type` like:

```yaml
app_logo:
  path:       /logo
  controller: App\Controller\LogoController::upload
  methods:    [POST]
  options:
    content_type: 'multipart/form-data'
```
but this unfortunately does not seem to work. It seems as if the option does not get overridden if it already exists.

The alternative I had to go with to restrict all routes to a content type of `application/json` by default, and then require a different content type on specific routes was to set the content type to `application/json` if the `content_type` option was not specified on the route (using an event subscriber in my case):

```php
$allowedContentType = $router->hasOption('content_type') ? $router->getOption('content_type') : 'application/json';
```
