### ISSUE TITLE
Logger autowiring takes precedence over explicit configuration

### ISSUE THREAD

**Issue by petr-buchyn** [symfony/symfony#43061]
**Symfony version(s) affected**: 5.3.3

**Description**
I have a default Monolog configuration, and than I define some channels:
```yaml
#packages/dev/monolog.yaml
monolog:
    channels:
        - foo
```

In my class I define a logger as a constructor argument:

```php
namespace App;

use Psr\Log\LoggerInterface;

class MyService
{
    public function __construct(LoggerInterface $logger)
    {
    }
}
```

Then I configure my class in `services.yaml` to receive `@monolog.logger.foo` instead of default logger:

```yaml
App\MyService:
    arguments:
        $logger: '@monolog.logger.foo'
```

After logging messages from `MyService` I see them in a log like `app.Info`.

I understand that I can autowire logger as a `$fooLogger` in my service, but I don't want to wire my code to specific logger, and I want to have an ability to replace logger in a future. 

I also think that explicit configuration must take precedence over autowiring, therefore I consider this behavior as a bug.

**How to reproduce**
Described in a previous step.

**Possible Solution**
Allow service configuration to take precedence over logger autowiring.

**Additional context**
