### ISSUE TITLE
Messagenger logs INFO log level in prod.log

### ISSUE THREAD

**Issue by zim32** [symfony/symfony#43077]
**Symfony version(s) affected**: 5.2.6

**Description**
I have a lot of log message in my prod.log file

```
[2021-09-17T12:48:31.459929+02:00] messenger.INFO: Message App\Message\SomeMessage handled by App\MessageHandler\SomeHandle::__in
....

```

Event if I have monolog config that prevents loging this level

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
```
As I understand this configuration tells that fingers_crossed will be activated only on error level and go to neseted handler.
Why I have INFO messages in my prod.log file?
