### ISSUE TITLE
[DependencyInjection] Wrong decorated cache definition

### ISSUE THREAD

**Issue by Warxcell** [symfony/symfony#43084]
**Symfony version(s) affected**: 5.3.7

**Description**
I got

```
framework:
   cache:
      app: 'cache.adapter.redis'
      pools:
         request_cache:
         adapter: cache.adapter.array

services:
    App\Core\Cache\Adapter\RequestArrayAdapter:
        decorates: 'request_cache'
```

With Version 5.3.4 I receive

```
TraceableAdapter
- SentryTraceableAdapter
-- RequestArrayAdapter
--- ArrayAdapter
```

When I upgraded to 5.3.7 I receive

```
TraceableAdapter
- SentryTraceableAdapter
-- RequestArrayAdapter
--- TraceableAdapter
---- RedisAdapter
```

**How to reproduce**
See the config in **Description** + I will write a test case for it, when I have time.

**Possible Solution**

When I return `DecoratorServicePass` to line 65 - it's all good

https://github.com/symfony/dependency-injection/commit/a665946279f566d94ed5eb98999cfa65c6fa5a78#diff-4e3797760c55382ae836394041059ba08670d225bfebfc27602e26036476c61fL65

**Additional context**
