### ISSUE TITLE
Firewall: Restrict access to web profiler (_profiler) for other users than ROLE_ADMINSTRATOR

### ISSUE THREAD

**Issue by christianostrem** [symfony/symfony#43256]
**Symfony version(s) affected**: 5.3.7

**Description**
Restrict access to web profiler (_profiler) for other users than ROLE_ADMINSTRATOR

**How to reproduce**
In security.yaml set following settings:

```yaml
security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|build)/
            security: true

    access_control:
        - { path: ^/_profiler, roles: [ROLE_ADMINISTRATOR] }
```

**Additional context**
If you login and have the role ROLE_ADMINISTRATOR you will not get access to the profiler
and the web profiler says that you are not logged in ROLE_ADMINISTRATOR

If you change the role access in the config to:

```yaml
security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|build)/
            security: true

    access_control:
        - { path: ^/_profiler, role: PUBLIC_ACCESS }
```

It will tell you that you have role ROLE_ADMINISTRATOR and you will get access.
