### ISSUE TITLE
HttpClient panel in the Web Profiler not displaying all request headers

### ISSUE THREAD

**Issue by ankahla** [symfony/symfony#43348]
**Symfony version(s) affected**: 5.3.2

**Description**
As menstionned here #33311 (comment) guzzle output the request headers (including default headers in configuration).
Unfortunatly even with this PR #35407 we still not collecting all headers : headers defined in configuration are missing!

**How to reproduce**
```
#config/packages/framework.yaml
http_client:
        default_options:
            headers:
                Accept: application/json
                User-Agent: "app_web"
        scoped_clients:
            http.client.api:
                base_uri: '%api_uri%'
                headers:
                    CustomHeader: "%api_host%"
```

**Possible Solution**
Exposing `$defaultHeaders` attribute and get it from `HttpClientTrait` directly as an attribute.

**Additional context**
![image](https://user-images.githubusercontent.com/4787799/136229541-593603ad-ba9d-4109-b5fd-f78d488c4765.png)
