### ISSUE TITLE
Make PropertyAccessor more extensible

### ISSUE THREAD

**Issue by BigChicChicken** [symfony/symfony#43646]
**Description**
Change private methods of `Symfony\Component\PropertyAccess\PropertyAccessor` to protected for make the class overwritable.

**Example**

```yaml
# config/servces.yaml

    property_accessor:
        class: App\PropertyAccess\PropertyAccessor
```

```php
<?php

namespace App\PropertyAccess;

use Symfony\Component\PropertyAccess\PropertyAccessor as BasePropertyAccessor;
use Symfony\Component\PropertyInfo\PropertyWriteInfo;

class PropertyAccessor extends BasePropertyAccessor
{
    protected function writeCollection(array $zval, string $property, iterable $collection, PropertyWriteInfo $addMethod, PropertyWriteInfo $removeMethod)
    {
        // My new logic
    }
}
```
