### ISSUE TITLE
Unable to connect to database using unix domain socket

### ISSUE THREAD

**Issue by Roysten** [symfony/symfony#43809]
I have a Symfony 5.3 project in which I would like to connect to a Postgres database using unix domain sockets. In doctrine the pgsql driver does not support setting the unix domain socket information in `$DATABASE_URL`, therefore one has to configure it using a `doctrine.yaml`.
I have the following configuration in config/packages/prod/doctrine.yaml:
```yaml
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     '%env(DB_HOST)%'
        port:     '%env(DB_PORT)%'
        dbname:   symfony
        user:     '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        server_version: '%env(DB_VERSION)%'

    orm:
        auto_generate_proxy_classes: false
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
```
When I run `php bin/console debug:configuration doctrine` I get the following output:
```
Current configuration for extension with alias "doctrine"
=========================================================

doctrine:
    dbal:
        types:
            datetime_ms:
                class: App\Entity\DoctrineType\DateTimeMs
        default_connection: default
        connections:
            default:
                url: ''
                driver: pdo_pgsql
                host: '%env(DB_HOST)%'
                port: '%env(DB_PORT)%'
                dbname: symfony
                user: '%env(DB_USER)%'
                password: '%env(DB_PASSWORD)%'
                server_version: '%env(DB_VERSION)%'
                logging: false
                profiling: false
                profiling_collect_backtrace: false
                profiling_collect_schema_errors: true
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                replicas: {  }
                shards: {  }
    orm:
        auto_generate_proxy_classes: false
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: <snip>
                        prefix: App\Entity
                        alias: App
                        mapping: true
                query_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                result_cache_driver:
                    type: pool
                    pool: doctrine.result_cache_pool
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        proxy_dir: <snip>
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```
This seems alright to me. Unfortunately when starting the server it will ignore these values and use the DATABASE_URL from my `.env` file instead. If I remove the DATABASE_URL from the `.env` file I get the following error:
```json
{
	"message": "Uncaught PHP Exception Symfony\\Component\\DependencyInjection\\Exception\\EnvNotFoundException: \"Environment variable not found: \"DATABASE_URL\".\" at /vendor/symfony/dependency-injection/EnvVarProcessor.php line 172",
	"context": {
		"exception": {
			"class": "Symfony\\Component\\DependencyInjection\\Exception\\EnvNotFoundException",
			"message": "Environment variable not found: \"DATABASE_URL\".",
			"code": 0,
			"file": "vendor/symfony/dependency-injection/EnvVarProcessor.php:172"
		}
	},
	"level": 500,
	"level_name": "CRITICAL",
	"channel": "request",
	"datetime": "2021-10-29T07:09:53.792800+02:00",
	"extra": {}
}
```
How can I force Symfony to use the values from the `doctrine.yaml` file? I also asked this on the official Slack, but got no replies unfortunately (maybe nobody uses unix domain sockets?).
