### ISSUE TITLE
Pass client as argument to ElasticsearchLogstashHandler 

### ISSUE THREAD

**Issue by benblub** [symfony/symfony#43806]
### Symfony version(s) affected

5.3.0

### Description

If you pass as Argument in your services.yaml the http_client or a scoped client the Handler perform hundreds Requests until he runs in an error like OutOfMemoryError

### How to reproduce

Set in your services.yaml 

a http_client
```yaml
Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler:
    arguments:
        $client: '@http_client'
```

OR a scoped client
```yaml
Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler:
    arguments:
        $client: '@elastic.client'
```

for the scoped client in framework.yaml
```yaml
http_client:
    scoped_clients:
        elastic.client:
            base_uri: 'https...'
            auth_basic: 'user:pw'
```

From the LOGs/Debugger
From Logs there is over hundreds of Requests until a 500 OutOfMemoryError is thrown
`http_client.INFO: Request: "POST https://...URL" [] []`

```log
[2021-10-28T17:08:40.529024+00:00] php.CRITICAL: Fatal Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) at /app/vendor/symfony/http-client/HttpClientTrait.php:406)"} []
```

### Possible Solution
I didnt get this fixed but i wrote some litte workaround that i can pass defaultOptions via argument. With that we didnt need to pass any http client. We can just work the CurlHttpClient which gets instantiated in ElasticsearchLogstashHandler.

services.yaml (That its possible to add defaultOptions like Auth)
```yaml
    Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler:
        arguments:
            $defaultOptions: {
                    timeout: 1,
                    auth_basic: 'user:pw',
            }
```

ElasticsearchLogstashHandler.php use defaultOptions
```php
    public function __construct(array $defaultOptions = [])
    {
        $this->client = HttpClient::create($defaultOptions);
    }
```

_No response_

### Additional Context
To work on ENVs with different Options like Auth its important we can use different http clients or we need the Option to pass defaultOptions to the http_client

Without passing the http_client or scoped client it works. Passing other arguments works too.
