### ISSUE TITLE
[Security] login_throttling not work

### ISSUE THREAD

**Issue by karaka200** [symfony/symfony#43911]
I install `symfony/rate-limiter` and use `login_throttling` in my `security.yaml`:

```
security:
    firewalls:
        secured_area:
            login_throttling:
                max_attempts: 3
                interval: '10 minutes'
```

But after entering the wrong username and password more than 3 times, when I enter the username and password correctly, it enter and does not restrict.
is it a Bug?
