### ISSUE TITLE
Two equivalent syntax of yaml-Collections produce different output for the same values

### ISSUE THREAD

**Issue by gorenstein** [symfony/symfony#44019]
### Symfony version(s) affected

Tested and reproduced on 4.4 and 5.3

### Description

In case the first character of the string is ampersand ```&```, then two equivalent syntax of YAML-Collections produce different output for the same values.

### How to reproduce

Add YAML parameters like:

```
parameters:
    # Correct values in console output  -> ["&string1","&string2","&string3"]
    collection_output_correct:
        - '&string1'
        - "&string2"
        - !!str &string3

    # Wrong values in console output -> ["","","",""]
    collection_output_wrong: ['&string1', "&string2", !!str &string3, &string4 ]
```

Run ```bin/console debug:container --parameters``` and compare output for 'collection_output_correct' and 'collection_output_wrong' parameters.

**Comment by xabbuh** [comment]
Can you please try #44034?

**Comment by gorenstein** [comment]
Work fine now for quoted string, but still broken for ```!!str``` 
```
parameters:
    # Correct output
    #
    # bin/console debug:container --parameters
    # output -> ["&string"]
    collection_output_correct:
        - !!str &string

    # Wrong output
    #
    # bin/console debug:container --parameters
    # output -> [""]
    collection_output_wrong: [!!str &string]
```

**Comment by xabbuh** [comment]
You are right. There was an issue with how we handled quoted scalars tagged with `!!str`. #44131 will fix that and your YAML should look like this then to work as expected:

```yaml
parameters:
    # Correct output
    #
    # bin/console debug:container --parameters
    # output -> ["&string"]
    collection_output_correct:
        - !!str '&string'

    # Wrong output
    #
    # bin/console debug:container --parameters
    # output -> [""]
    collection_output_wrong: [!!str '&string']
```

**Comment by gorenstein** [comment]
> 

But what about ```!!str &string```  - ```!!str``` _without_ quoted scalars with the first character ```&```?

Still two equivalent syntax of yaml-Collections produce different output:
```
parameters:
    collection_1:
        - !!str &string

    collection_2: [!!str &string]
    
    # parser output collection_1: ["&string"]
    # parser output collection_2: [""]
```
