### ISSUE TITLE
Unable to override autoconfigure for specific service

### ISSUE THREAD

**Issue by surikman** [symfony/symfony#44126]
### Symfony version(s) affected

5.3.10

### Description

Hi, `autoconfigure` does not work properly when I need to override service in same `service.yml` when `autoconfigure: true` is configured under `_defaults`

### How to reproduce

My Configuration is:
```
services:
  _defaults:
    autoconfigure: true

  _instanceof:
    SomeSuperSpecialInterface:
      tags: ['my_tag']

  MySuperSpecialFallback:
    autoconfigure: false
  
 SuperManager:
    arguments:
      $services: !tagged_iterator my_tag
      $fallback: '@MySuperSpecialFallback'
```

I expected, that `MySuperSpecialFallback` service will not have `my_tag` but it has.
