### ISSUE TITLE
[Messenger] [AMQP] Add arguments to delay queues

### ISSUE THREAD

**Issue by GavrilovicAleksa** [symfony/symfony#44186]
### Description

Currently, amqp-messenger doesn't support input arguments for delay queues. It would be useful if we could add additional arguments.

### Example

```yaml
options:
    delay:
        arguments:
            argument: value
```
