### ISSUE TITLE
Support Enum as workflow places

### ISSUE THREAD

**Issue by stof** [symfony/symfony#44211]
### Discussed in https://github.com/symfony/symfony/discussions/44203

<div type='discussions-op-text'>

<sup>Originally posted by **stephanvierkant** November 22, 2021</sup>
I've tried the new Enum in PHP 8.1 and I love that Symfony supports this new feature in the Form component.

I'd love to have this support in the Workflow component as well. 

I've changed my status attribute from a string to an Enum field and now this doesn't work anymore:

`$workflow->can($entity, $transition->getName()`

I'd be great is Symfony would support Enum in the Workflow Component as well! </div>

**Comment by alexandre-daubois** [comment]
Looking into it. :+1: 
Started to work on 6.0 branch while waiting 6.1 branch (as mentioned in the original issue, this feature is most likely to be included in 6.1). It's coming up together, trying to bring support of both `UnitEnum` and `BackedEnum`. Adding final tests right now.

**Comment by sxsws** [comment]
Generally, this is the problem of another component other than the workflow component.

I have a working example of this for yaml. It's relatively simple to monkey-patch.

At the moment, I have this example working:

My enum:

```php
enum Suit: string
{
    case Clubs = 'c';
    case Hearts = 'h';
    case Spades = 's';
    case Diamonds = 'd';
}
```

and part of my workflow.

```yaml
places:
        !php/enum App\Enum\Suit::Hearts.name:
            metadata:
              - description: !php/const App\Enum\Suit::Spades

...
transitions:
    to_review:
        from: !php/enum App\Enum\Suit::Hearts.name
        to:   reviewed
```

The place name is the name string of the enum `Hearts`. If I change it to `.value`, it'd give, from above, `h`.
The value for description gives the instance of Suit::Spades just for fun.

Of course, this is only for yaml. It will of course work outside of the workflow component
