### ISSUE TITLE
A more expressive way to configure the handling of Workflow transitions

### ISSUE THREAD

**Issue by mathielen** [symfony/symfony#44304]
### Description

The Workflow component is great but I am missing an expressive way to define the "handling"-part of a transition.

So, when looking in the workflow configuration, one could see what the actual reaction of a transition is meant to be. Right now you would have to dig into EventListeners and EventSubscribers to find these (if I dont miss anything).

We are using https://github.com/winzou/StateMachineBundle which has a notion of callbacks that describes what services the workflow is calling when a transition was done (after) or is about to do (before). Imho, it is great to see this in the workflow configuration at a glance.

The callback-definitions could be handled by a single config-based EventSubscriber provided by the Workflow component.
Is this something worth considering? If yes, I could try to build a PR for this - when I get the time.

### Example

```yaml
...
transitions:
  process:
    guard: "someGuard.allowedToProcess(subject)"
    from: [pending]
    to: processing
    callbacks:
      enter: "someHandler.doSomething(subject)"
      #ofc, also allow multiple callbacks
      completed:
        - "someHandler.doCompletedTask(subject)"
        - "someOtherHandler.doSomethingAdditionally(subject)"
...
```
