### ISSUE TITLE
REMEMBER_ME cookie has path '/' by default even when application lives under directory

### ISSUE THREAD

**Issue by php4fan** [symfony/symfony#44320]
### Symfony version(s) affected

5.4.0

### Description

Similar to issue 44318, the "Remember Me" feature also doesn't work properly out of the box when the application "lives under a directory", e.g. `https://mydomain.com/some/path`.

In `security.yaml`:
```
security:
    # ...

    firewalls:
        # ...
        main:
            #...
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                # <<<<<<<<<<<<<<<<<<<<<<<<NOTE I have NOT explicitly set a value for 'path'
```

I know I can set `path: '/some/path'` under `remember_me:` but I shouldn't need to do that like I don't need to have a configuration parameter with the domain name. Having the path of the cookie be the same as the app's root folder path should be the default.

Note that having `/` as the path regardless of the app's root path (i.e. the current behavior) is also an option that one should be able to set if they want to (not that I can immediately think of a use case but that should never be a reason to assume there isn't one). So, I do _not_ suggest that the value '/' mean "the root path of the application" (because then you'd have to define a special value other than "/" that would mean "litelarry '/'" which would be counterintuitive af). Rather, I suggest that a special value like `null` or `false` or something is taken to mean the root path of the application, and that that value becomes the default.

I don't know whether this is a more general problem with cookies or if this is specific to the remember_me cookie.
Actually, I see the `PHPSESSID` cookie shares the same issue.

### How to reproduce

- deploy the application under a directory
- enable remember_me
- log in with remember_me
- look at the cookie path
