### ISSUE TITLE
[symfony/doctrine-bridge] 5.4 : auto mapping not working at all

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony#44355]
### Symfony version(s) affected

5.4

### Description

Auto mapping of vendor entity not working anymore.

### How to reproduce

My doctrine config :
```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

With symfony/doctrine-bridge 5.3.11, Entity living on directory `vendor/foolib/foobundle/src/Entity` was registered.
With symfony/doctrine-bridge 5.4.0, Entity got error : 
`The class 'Foo\FooBundle\Entity\BarEntity' was not found in the chain configured namespaces App\Entity`

### Additional Context

I am not sure bug is from `symfony/doctrine-bridge`, but add `"symfony/doctrine-bridge": "5.3.*",` on composer.json solve the problem

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by mmarton** [comment]
I had the same issue, I tought because I moved to attributes + new bundle structure on my bundles. Addig the mapping info into my doctrine config solved it for me:

```yaml
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            AdminBundle:
                is_bundle: true
                type: attribute
                dir: src/Entity
```
