### ISSUE TITLE
[Messenger] Could not acknowledge redis message with BatchHandlerInterface 

### ISSUE THREAD

**Issue by zip-fa** [symfony/symfony#44400]
### Symfony version(s) affected

5.4.0, 6.0.0

### How to reproduce

I have MessengerHandler which makes http requests (_**with only one parallel consumer**_):

messenger.yaml:
```
transports:
  test:
    dsn: '%env(MESSENGER_TRANSPORT_DSN)%/test'
    options:
      delete_after_ack: true
      consumer: '%env(MESSENGER_CONSUMER_NAME)%'
    retry_strategy:
      max_retries: 0

routing:
     'TestMessage': test
```

TestMessageHandler.php:
```
<?php
class TestMessageHandler implements MessageHandlerInterface, BatchHandlerInterface
{
    use BatchHandlerTrait;

    public function __construct(
        private HttpClientInterface $client
    ) { }

    public function __invoke(TestMessage $message, Acknowledger &$ack = null)
    {        
        return $this->handle($message, $ack);
    }
    
    private function shouldFlush(): bool
    {
        return 5 <= \count($this->jobs);
    }

    private function process(array $jobs): void
    {
        $responses = [];
        
        foreach ($jobs as [$job, $ack]) {          
            try {
                [$headers, $content] = prepareRequest();
                
                $responses[] = $this->client->request('POST', $job->getEndpoint(), [
                    'headers' => $headers,
                    'body' => $content
                ]);

                $ack->ack($job);
            } catch (\Exception $e) {
                $ack->nack($e);
            }
        }
        
        if(0 === count($responses)) {
          return;
        }

        foreach ($this->client->stream($responses) as $response => $chunk) {
            if ($chunk->isFirst()) {
                var_dump($response->getStatusCode());
            } else if ($chunk->isLast()) {
            }
        }
    }
}
```

cli:

```MESSENGER_CONSUMER_NAME=test php bin/console messenger:consume test```

Code works okay, but when i hit ctrl+c before script finished and start it again, it throws me an error:

```
In Connection.php line 441:

  Could not acknowledge redis message "1638374074049-0".
```

I noticed that after consumer crashes or i hit ctrl+c, same message comes to __invoke a few times. When removing BatchHandlerInterface it starts to work as excepected without any issue.

### Possible Solution 1 (a bad one)

1) Add uuid to every Message
2) Destroy Acknowledger and create replacement for it (HandleMessageMiddleware.php:88)

Test.php:
```
class Test
{
  public function isAcknowledged()
  {
    return false;
  }
}
```

TestMessageHandler.php:
```
public function __invoke(SendPushMessage $message, Acknowledger &$ack = null)
{
    $uid = $message->getUuid();
    
    if(isset($this->jobs[$uid])) {
      $this->flush(true);
      
      try {
        $ack = null;
        unset($ack);
      } catch(\Exception) { }
      
      $ack = new Test();

      return 0;
    }
    
    return $this->handle($message, $ack);
}

private function handle(object $message, ?Acknowledger $ack)
{
    $uid = $message->getUuid();

    if (null === $ack) {
        $ack = new Acknowledger(get_debug_type($this));
        $this->jobs[$uid] = [$message, $ack];
        $this->flush(true);

        return $ack->getResult();
    }

    $this->jobs[$uid] = [$message, $ack];
    if (!$this->shouldFlush()) {
        return \count($this->jobs);
    }

    $this->flush(true);

    return 0;
}
```

### Possible Solution 2

Comment __destruct in Symfony\Component\Messenger\Handler\Acknowledger.php

Handler.php:

```
public function __invoke(SendPushMessage $message, Acknowledger $ack = null)
{
    $uid = $message->getUuid();
    
    if(isset($this->jobs[$uid])) {
      $this->flush(true);
    
      return 0;
    }
    
    return $this->handle($message, $ack);
}

private function handle(object $message, ?Acknowledger $ack)
{
    $uid = $message->getUuid();

    if (null === $ack) {
        $ack = new Acknowledger(get_debug_type($this));
        $this->jobs[$uid] = [$message, $ack];
        $this->flush(true);

        return $ack->getResult();
    }

    $this->jobs[$uid] = [$message, $ack];
    if (!$this->shouldFlush()) {
        return \count($this->jobs);
    }

    $this->flush(true);

    return 0;
}
```

**Comment by rvanlaak** [comment]
Same here, could this have something to do with what is stated about `MESSENGER_CONSUMER_NAME` in the documentation when using Redis as transport in combination with Supervisor?

In our infra we have Supervisor run 4 instances of the `bin/console messenger:consume` command.

**Comment by zip-fa** [comment]
Any news @xabbuh?

**Comment by rvanlaak** [comment]
@zip-fa since I've properly configured the Supervisor application to register to Redis on a unique DSN this issue seems resolved for me.

After translating [this Russian blogpost](https://medium.com/@alshenetsky/symfony-messenger-redis-%D0%BF%D0%BE%D0%B4%D0%B2%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%BC%D0%B5%D0%BD%D1%8C-43f1dbcb8d86) by Алексей Альшенецкий I've came to the following configuration:

```yaml
# messenger.yaml
parameters:
    env(CONSUMER_ID): '0'

framework:
    messenger:
        transports:
            async: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/messages/symfony/consumer-%env(CONSUMER_ID)%?auto_setup=true"
```

```ini
# supervisor.conf
[program:messenger-consume]
command=php /var/www/html/bin/console messenger:consume async
numprocs=10
autostart=true
autorestart=true
environment = CONSUMER_ID=%(process_num)d
```

## Relevant details

* You need to know that Symfony Messenger for working with Redis uses a special data type that appeared in Redis 5.0 - streams (Streams)
* All consumers that we want to run in parallel must have a unique name so as not to conflict while “parsing” messages.
* In the above example, symfony is the name of the consumer group. The auto-setup flag allows Redis to create it automatically. 
* In this group, we dynamically (based on the **CONSUMER_ID** environment variable) generate the name of the consumer so that each has a unique name (consumer-0, consumer-1, consumer-2, e.t.c). 
* Above, in parameters, we declare a default value for the CONSUMER_ID variable so that the application does not throw an error when parsing messenger.yaml if you use the same application image outside of the messenger:consume process.

**Comment by dkarlovi** [comment]
We're also seeing this issue with only two workers on Azure managed Redis.

This is the current config:

```yaml
framework:
    messenger:
        buses:
            messenger.bus.pimcore-core:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
        transports:
            pimcore_core:
                dsn: '%env(file:MESSENGER_DSN_FILE)%'
                options:
                    delete_after_ack: true
                    stream: '%env(MESSENGER_GROUP)%'
                    consumer: '%env(HOSTNAME)%'
            pimcore_maintenance:
                dsn: '%env(file:MESSENGER_DSN_FILE)%'
                options:
                    delete_after_ack: true
                    stream: '%env(MESSENGER_GROUP)%'
                    consumer: '%env(HOSTNAME)%'
            pimcore_image_optimize:
                dsn: '%env(file:MESSENGER_DSN_FILE)%'
                options:
                    delete_after_ack: true
                    stream: '%env(MESSENGER_GROUP)%'
                    consumer: '%env(HOSTNAME)%'
```

1. DSN looks like `rediss://password@host?dbindex=0`, it doesn't define stream, group or consumer
2. `MESSENGER_GROUP` is the current Kubernetes namespace (we share the same Redis server for multiple instances of the app, it's a [review app deployment](https://docs.gitlab.com/ee/ci/review_apps/) sort of thing), so `preview-branch`, `preview-other-branch`, etc
3. `HOSTNAME` is the container hostname, we're using the K8s `StatefulSet` object so the hostnames are fixed and look like `worker-0`, `worker-1` etc

It **mostly** works, but then something happens and the messages consistently cannot be acknowledged, breaking workers for a while.
