### ISSUE TITLE
[Router] Route attribute containing kernel parameters generated on build time

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#44504]
### Symfony version(s) affected

5.4.0

### Description

We are using Heroku to run our application. Recently we needed to add a new route using a controller that requires a path as an attribute and uses the parameter `kernel.project_dir`.

Since Heroku builds the app inside a folder then moves it to another... The path generated inside the routing endup being wrong.

### How to reproduce

I'm using this route with [Melodiia](https://github.com/Swagindustries/Melodiia) to make my documentation live:

```yaml
api_documentation:
    path: /documentation
    controller: 'melodiia.documentation'
    defaults:
        documentation_file_path: '%kernel.project_dir%/swagger.yaml'
```
