### ISSUE TITLE
Default route annotations defined twice when adding ORM to project

### ISSUE THREAD

**Issue by leonboot** [symfony/symfony#44588]
### Symfony version(s) affected

6.0.0

### Description

Not sure if this issue was introduced since Symfony 6, but I noticed when adding ORM to my project (`composer require orm`), the doctrine/annotations package was added and the default routing configuration was added to config/routes/annotations.yam, while it was already present in config/routes.yaml.

### How to reproduce

- Create a new Symfony 6 project: `symfony new my-project --version=6.0`
- Notice the presence of config/routes.yaml with the following content:
   ```yaml
    controllers:
        resource: ../src/Controller/
        type: annotation
    
    kernel:
        resource: ../src/Kernel.php
        type: annotation
   ```
- Add ORM to the project (`composer require orm`)
- Notice that Symfony Flex has created config/routes/annotations.yaml with the following content:
   ```yaml
    controllers:
        resource: ../../src/Controller/
        type: annotation
    
    kernel:
        resource: ../../src/Kernel.php
        type: annotation
   ```
In my case, this caused confusion when changing the controllers routing definition.

### Possible Solution

I don't know what's the best course of action here, either changing it in the Flex recipe, or somewhere in the Symfony bundle.
