### ISSUE TITLE
The `exclude` option does not seem to have any effect in annotation routing definitions

### ISSUE THREAD

**Issue by leonboot** [symfony/symfony#44590]
### Symfony version(s) affected

5.*, 6.0

### Description

When trying to exclude certain controllers from being parsed for routing annotations using the `exlude` option, it does not seem to have any effect; the routes are still added.

### How to reproduce

- Create a new Symfony 6 project: `symfony new my-project --version=6.0`
- Add annotations support (`composer require doctrine/annotations`)
- Remove or remark the contents of the **config/routes.yaml** file (see #44588)
- Create the following two controllers:
  - **src/Controller/DefaultController.php**:
     ```php
      <?php
      
      namespace App\Controller;
      
      use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
      use Symfony\Component\HttpFoundation\Response;
      use Symfony\Component\Routing\Annotation\Route;
      
      class DefaultController extends AbstractController
      {
      
          /**
           * @Route("/", name="home")
           *
           * @return Response
           */
          public function index(): Response
          {
              return new Response("I'm the index action of the default controller!");
          }
      }
     ```
   - **src/Controller/Security/GoogleOauthController.php**:
     ```php
      <?php
      
      namespace App\Controller\Security;
      
      use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
      use Symfony\Component\HttpFoundation\Response;
      use Symfony\Component\Routing\Annotation\Route;
      
      /**
       * @Route("/google", name="google_")
       */
      class GoogleOauthController extends AbstractController
      {
      
          /**
           * @Route("/connect", name="connect")
           *
           * @return Response
           */
          public function connect(): Response
          {
              return new Response("Connecting to Google...");
          }
      }
     ```
- Exclude the controllers in Security from the main routing definition and add a separate, prefixed definition. Update the **config/routing/annotations.yaml** file as follows:
    ```yaml
    controllers:
        resource: ../../src/Controller/
        exclude: '../../src/Controller/Security/{GoogleOauthController}.php'
        type: annotation
    
    security_controllers:
        resource: ../../src/Controller/Security/
        type: annotation
        prefix: "/auth"
        name_prefix: "auth_"
    
    kernel:
        resource: ../../src/Kernel.php
        type: annotation
    ```

The expected routes here would be:
- `/` (home)
- `/auth/google/connect` (auth_google_connect)

Both these routes are present in the actual list of routes, with the addition of the route `/google/connect` (name: google_connect). This 

### Possible Solution

Not sure. It might not be a bug but a misunderstanding of how the `exlude` option is implemented (although I have tried several notations; with and without accolades, with an asterisk, or just by providing a directory path). If I am incorrectly implementing it, additional documentation might be useful since I could not find a decent example in the documentation regarding the routing configuration.
