### ISSUE TITLE
[YAML] Access enum value (php 8.1) like is already possible for constants using !php/const by adding e.g. !php/enum syntax

### ISSUE THREAD

**Issue by AndreasA** [symfony/symfony#44612]
### Description

Hi,

now that PHP has enum support it would be nice, if one could access its value like one can already do with constants using `!php/const`.

### Example

```php

namespace App\Enums;

enum CartType: string
{
    case Truck = 'truck';
}
```

```yaml
    App\Validator\CartValidator:
        arguments:
            $defaultType: !php/enum App\Enum\CartType::Truck
```

or similar
