### ISSUE TITLE
security.token_storage only available when using autowire

### ISSUE THREAD

**Issue by Martin-P** [symfony/symfony#44735]
### Symfony version(s) affected

6.0.1

### Description

When `autowire` is set to `false` and you manually inject the `service_container`, the `security.token_storage` service is not available in `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` and causes a LogicException:

```
The SecurityBundle is not registered in your application. Try running "composer require symfony/security-bundle".
```

When `autowire` is set to `true` all is fine again and works as expected.

### How to reproduce

/config/services.yaml:
```yaml
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\HomeController:
        tags: [controller.service_arguments]
        calls:
            - setContainer: ['@service_container']
```

/src/Controller/HomeController.php:
```php
<?php declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
   public function index()
   {
        // $user = $this->getUser(); // throws above mentioned LogicException
        $status = $this->container->has('security.token_storage');

        return new Response(sprintf(
            '<pre>%s<br /><br />security.token_storage available: %s</pre>',
            __METHOD__,
            $status ? 'true' : 'false'
        ));
   }
}
```

Output:
```
App\Controller\HomeController::index

security.token_storage available: false
```

### Possible Solution

It looks likes Symfony adds additional services to the `service_container` when `autowire` is set to `true` and that these additional services are skipped when manually injecting `service_container` using the `setContainer` method.

### Additional Context

![The SecurityBundle is not registered in your application](https://user-images.githubusercontent.com/1311879/146832901-415d252d-e9d5-4707-a91c-c22db7090799.png)
