### ISSUE TITLE
[DependencyInjection] Enums doesn't works when they are binded

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#44834]
### Symfony version(s) affected

Any version from 4.4 and PHP 8.1

### Description

Use syntax `!php/const` with an enum as parameter doesn't work properly when you want to bind the parameter.

### How to reproduce

```php
<?php
namespace App;

enum Status: string {
    case Draft =  'draft';
    case Deleted =  'deleted';
    case Published = 'published';
}
```

```yaml
# services.yaml
parameters:
    my_param: !php/const App\Status::Deleted
services:
    _defaults:
        autowire: true     
        autoconfigure: true
        bind:
            $myParam: '%my_param%'
```
```php
dd($container->getParameter('my_param')); // is OK output the enum
```
but
```php
    /**
     * @Route("/foo", name="foo")
     */
    public function index(EntityManagerInterface $entityManager, $myParam): Response
``` 
output
![image](https://user-images.githubusercontent.com/13260307/147616168-5b245c21-0f48-4b6b-a9f2-981f7d079da0.png)

**Comment by ogizanagi** [comment]
Actually enums are not supported properly in the DI parameters (yet?), while being supported in injection:

```yaml
# services.yaml
services:
    _defaults:
        autowire: true     
        autoconfigure: true
        bind:
            $myParam: !php/const App\Status::Deleted
```

works, right?

Moreover, the `ParameterBagInterface` is not allowing objects, so won't accept enums:

https://github.com/symfony/symfony/blob/6d9991cdc9ef791a088cc10e2d17ff639b2e05b2/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBagInterface.php#L48

https://github.com/symfony/symfony/blob/6d9991cdc9ef791a088cc10e2d17ff639b2e05b2/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBagInterface.php#L60
