### ISSUE TITLE
AuthorizationChecker still uses $this->authenticationManager (while not set) when token isn't authenticated

### ISSUE THREAD

**Issue by Lyrinta** [symfony/symfony#44919]
### Symfony version(s) affected

5.4

### Description

In the AuthorizationChecker `isGranted` `$this->authenticationManager->authenticate($token)` is called when the token is not authenticated. `$this->authenticationManager` however is only set in an if-statement in the constructor, leading to a situation where it can be called while not set. 

This happens specifically with a http_basic user without roles, for which `$token->isAuthenticated` will return false.

### How to reproduce

Set up a http_basic memory user: 
```
    providers:
        http_basic:
            memory:
                users:
                    username:
                        password: password
```

Set up a firewall using this provider:
```
    firewalls:
        healthcheck:
            pattern: ^/testcheck
            http_basic:
                provider: http_basic
```

Call the endpoint, using an `isGranted('IS_AUTHENTICATED_REMEMBERED')` (or another attribute) to decide if the user is allowed access to the endpoint.

The `$accessDecisionManager` in the `AuthorizationChecker` will be a `TraceableDecisionManager` which is not an instance of `AuthenticationManagerInterface` so `$this->authenticationManager` will not be set.

However on line 85 `$this->authenticationManager->authenticate()` will be called.

### Additional Context

![image](https://user-images.githubusercontent.com/97174357/148230541-3de9dae2-a900-4d12-a0b8-8022e538ff52.png)

**Comment by Lyrinta** [comment]
The workaround we have used is to add a (fake) role to our provider, during which the `$token->isAuthenticated()` will return true and skip the call to `$this->authenticationManager`: 

```
    providers:
        http_basic:
            memory:
                users:
                    username:
                        password: password
                        roles: ['fake_role']
```
