### ISSUE TITLE
symfony/notifier "+" (plus) character leading a parameter's value is stripped

### ISSUE THREAD

**Issue by drzraf** [symfony/symfony#44973]
### Symfony version(s) affected

5.4.0

### Description

Some notifiers' DSN make use of custom parameter, eg Twilio and the **from** parameter.
This parameter may require an international phone number (starting with a "+")
Eg: `twilio://foo:bar@default?from=+148011111111`

Such a leading "+" (plus) is currently silently stripped by the query-string parsing logic.

### How to reproduce

Sample configuration

```yaml
framework:
    notifier:
        texter_transports:
            sms: 'twilio://foo:bar@default?from=+148011111111'
```

Result:
`Error: "Handling "Symfony\Component\Notifier\Message\SmsMessage" failed: The "From" number " 148011111111" is not a valid phone number, shortcode, or alphanumeric sender ID."`

Sample inline reproducer:
```php
<?php
require('vendor/autoload.php');
use Symfony\Component\Notifier\Transport\Dsn;
$dsn = new Dsn('twilio://foo:bar@default?from=+148011111111');
var_dump($dsn->getRequiredOption('from'))
```

Result:
`string(12) " 148011111111"`
