### ISSUE TITLE
[Security] ContextListener misbehavior with multiple UserProviders

### ISSUE THREAD

**Issue by zeqfreed** [symfony/symfony#4498]
I'm implementing an application that needs to have separate sets of users for its different sections. For instance, we create Admin and Front sections. For each of the sections I define a firewall rule in security config and a different user provider:

``` yaml
providers:
    provider_admin:
        id: acme.shmundle.my_user_provider.admin

    provider_front:
        id: acme.shmundle.my_user_provider.front

firewalls:
    admin:
         provider: provider_admin
         ....

    front:
         provider: provider_front
         ....
```

Now, the provider ids reference two different services of the same class that implements UserProviderInterface configured to use different user storages, but same user class.

This setup leads to a problem in ContextListener. After user logs in, the ContextListener attempts to validate user token and refresh user by iterating over every user provider and calling its refreshUser method. If current user provider does not support the user class it throws UnsupportedUserException and ContextListener continues to the next user provider, but if it does and can't actually find the user it throws UsernameNotFoundException which interrupts the iteration and returns null essentially forcing the user to log out.

One solution that would work here is to make sure a different user class used for every user provider, so the iteration always reaches the provider that can refresh user token. But this solution seems quirky, non-obvious and moreover is a kind of side effect depending on the internal implementation of ContextListener.

Another solution is obviously to implement my own ContextListener that will iterate through every user provider regardless of the exceptions thrown. This is the approach I think I will have to take if you confirm that this behavior is actually intended and my use case doesn't lie within symfony's design philosophy.

Please refer to the [ContextListener source](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L139) for the problematic code.

**Comment by BboyKeen** [comment]
Any news on this one ? I just ran into the same issue today

**Comment by MlleDelphine** [comment]
I am "stuck" with the same behavior. 
I have two memory providers.
In my concerned firewall settings, in security.yml, I have precised the provider.
security.yml: 

```
    providers:
        memory_users:
            memory:
                users: "%fsonline.users%"
        backend_users:
            memory:
                users: "%fsonline_backend_users%"
[...]

 backend:
            pattern:    ^/
            host:       "%app_backend_host%"
            provider: backend_users
            anonymous:  ~
            form_login:
            logout:
                path:   /logout
                target: /
```
Nevertheless, when I am unable to login. Stacktrace during ONE try :

```
[2016-08-31 15:25:46] security.INFO: User has been authenticated successfully. {"username":"admin"} []
[2016-08-31 15:25:46] security.WARNING: Username could not be found in the selected user provider. 
```
My questions are :+1: 

- Why "provider" in my backend firewall is not taken into account in ContextListener?
- Why ContextListener does check only the first provider ? Don't understand why a "UsernameNotFoundException" breaks the code while the final response of refresheUser method is "There is **no user provider** for user "%s".', get_class($user)" as it has checked ALL providers defined in security.yml whila actually, it did not..

I bypass this behavior with "chain_provider" but it does not make sense for me..

**Comment by mahald181** [comment]
I have the same problem with the following configuration:
```
    providers:
        admin_user_provider:
            id: app.security.admin_user_provider
        passwordless_user_provider:
            id: app.security.passwordless_user_provide

[...]

        backend:
            pattern: ^/backend
            provider: admin_user_provider
            anonymous: true
            form_login:
                login_path: _backend_security_login
                check_path: _backend_security_login_check
            logout:
                path: _backend_security_logout
                target: _backend_security_login
                invalidate_session: false

        frontend:
            pattern: ^/(?!backend)
            provider: passwordless_user_provider
            anonymous: true
            simple_preauth:
                authenticator: app.security.passwordless_authenticator
            logout:
                path: _frontend_user_logout
                target: _frontend_project_list
                invalidate_session: false
```
Both providers use the same class buth only return users with specific roles.
As I understood from the docs, every firewall uses one provider. But my frontend firewall uses the first specified provider and not the one I defined in the firewall.
I solved this temporarily also with a chain_provider. Thanks to @MlleDelphine.
