### ISSUE TITLE
[Cache][RateLimiter][FrameworkBundle] Redefining a framework-provided cache pool in config gets silently overwritten

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#44984]
### Symfony version(s) affected

5.3.x, probably earlier

### Description

Framework-provided cache pools take priority over those defined in the cache config by user, and do so without warning.

### How to reproduce

While setting up the rate limiter, [I saw](https://symfony.com/doc/current/rate_limiter.html#storing-rate-limiter-state) that it uses the cache.rate_limiter pool by default. This pool extends the cache.app one as per https://github.com/symfony/symfony/blob/6b9fafb2c0ef84bfa7d17b3b37737c5da710bd0e/src/Symfony/Bundle/FrameworkBundle/Resources/config/rate_limiter.php#L18-L20

I wanted to make sure all rate limiters get stored somewhere else than the app cache, so it seemed obvious to me that I could redefine the `cache.rate_limiter` pool in the config and get this to be written somewhere else:

```yaml
framework:
    cache:
        # [...]
        pools:
            cache.rate_limiter:
                adapter: cache.adapter.redis
                provider: '%redis_rate_limiter_dsn%'
```

Then a few months later I now realize this does not work at all. It seems like the service definition in FrameworkBundle/rate_limiter.php overwrites my cache pool silently, and so everything is still dumped in the app cache.

### Possible Solution

A few alternatives I see to improve things:

1. The best solution to me would be that if a pool is defined already then FrameworkBundle would not recreate that service.
2. If redefining framework pools is frowned upon, then maybe [the reserved list](https://github.com/symfony/symfony/blob/6b9fafb2c0ef84bfa7d17b3b37737c5da710bd0e/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1105-L1108) could be expanded a bit to include other `cache.x` pools.
