### ISSUE TITLE
[Workflow] Guards events too "greedy"

### ISSUE THREAD

**Issue by kissifrot** [symfony/symfony#45172]
### Symfony version(s) affected

5.4.2

### Description

Hello,

As a follow up of #38960, when a transition is made, a guard event is sent for every possible transition we are getting from.

However in our case those guard event listeners are quite resource-intensive (lots of checks are made in the DB). 
Would there a way to not fire all of them when we know we will be doing only one transition?

### How to reproduce

A sample I borrowed in #38960

```yaml
signature:
  type: 'state_machine'
  audit_trail:
     enabled: true
  marking_store:
     type: 'method'
     property: 'state'
  initial_marking: created
  supports:
    - App\Entity\Signature
  places:
    - created
    - code_sent
    - signed
  transitions:
     send_code:
       from: created
       to: code_sent
     sign:
       from: code_sent
       to: signed
```

And the listener:
```php
<?php

namespace App\Workflow\Guard;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Workflow\Event\GuardEvent;

class ReservationInProgressGuard implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            'workflow.reservation.guard.send_code' => 'OnEvent',
            'workflow.reservation.guard.sign' => 'OnEvent',
        ];
    }

    public function OnEvent(GuardEvent $event): void
    {
        // Some heavy process which should be done only once per transition
    }
}
```

### Possible Solution

It is stated in the doc guard events are always fired, but wouldn't it be possible to not fire them, or have an info in the even which states "OK I was called for the transition you listened to, let's not continue further" ?

**Comment by alexislefebvre** [comment]
Possible workaround: add a property in `ReservationInProgressGuard`, define it after the first call, then check that it's not defined before calling the checks. This would be similar to the `// Make sure we're not called twice` code shown for [API Platform](https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-on-a-per-item-basis).

**Comment by lyrixx** [comment]
Can you create a small reproducer please?

**Comment by kissifrot** [comment]
Here it is:

Workflow YAML config :
```yaml
framework:
  workflows:
    test:
      type: state_machine
      supports:
        - App\Entity\MyEntity
      marking_store:
        type: method
        property: marking
      initial_marking: 'created'
      places:
        - 'created'
        - 'in-progress'
        - 'confirmed'
        - 'abandonned'
      transitions:
        - name: 'initialize'
          from: 'created'
          to: 'in-progress'
          metadata:
            title: Initialize
        - name: 'abandon'
          from: 'in-progress'
          to: 'abandonned'
          metadata:
            title: Abandon
        - name: 'confirm'
          from: 'in-progress'
          to: 'confirmed'
          metadata:
            title: Confirm
```

Guard Listener:
```php
<?php

namespace App\Workflow\Guard;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Workflow\Event\GuardEvent;

class TestInProgressGuard implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            'workflow.test.guard.initialize' => 'onInProgress',
            'workflow.test.guard.confirm' => 'onInProgress',
        ];
    }

    public function onInProgress(GuardEvent $event): void
    {
        dump('I should be called only once if possible as I am heavy');
    }
}
```

Then in the code
```php
<?php
class DetailsController extends AbstractController
{
    public function __invoke(WorkflowInterface $testWorkflow)
    {
        $data = new MyEntity();
        $testWorkflow->apply($data, 'initialize');
        // ...
    }
}
```

You will see two dumps in the profiler
