### ISSUE TITLE
Route different HTTP verbs to different methods, with the same route name, with annotations

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#45218]
### Description

Symfony supports routing different HTTP verbs to the _same_ method with the same route name, but not _different_ methods with the same route name.

```php
    /**
     * @Route("/foo", name="foo", methods={"GET", "POST"})
     */
     public function __invoke() {}
```

However, if we want to split this out into two methods, this is not possible.

```php
    /**
     * @Route("/foo", name="foo", methods={"GET"})
     */
     public function get() {}

    /**
     * @Route("/foo", name="foo", methods={"POST"})
     */
     public function post() {}
```

In this case, the latter definition overwrites the former, since they have the same name. Yet the same name _is permitted for different verbs_, provided they are backed by the same controller method. In my view this is problematic because Symfony routing limitations should not hamstring the implementation.

**Comment by stof** [comment]
That's expected: having a single route with multiple values in the `methods` array is totally not the same than having 2 routes. and the controller reference is part of the route definition, so if you need 2 different controllers, they cannot be the same route.

**Comment by stof** [comment]
here is the same config in Yaml format, that makes it clear that you have 2 routes with different configs in the second case:

```yaml
foo:
  path: /foo
  methods: [GET, POST]
  controller: 'App\Controller\FooController::__invoke'
```

```yaml
foo:
  path: /foo
  methods: [GET]
  controller: 'App\Controller\FooController::get'

foo: # not actually valid Yaml, as duplicate keys are forbidden at the Yaml level too
  path: /foo
  methods: [POST]
  controller: 'App\Controller\FooController::post'
```

As you can see, the `controller` config is different between the 2 routes, and so we really need to register 2 routes.
