### ISSUE TITLE
AnnotationDirectoryLoader raises type error for abstract classes

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#45259]
### Symfony version(s) affected

6.0.4

### Description

`AnnotationDirectoryLoader::load()` has a return type `RouteCollection`, but it may return `null` in some situations
https://github.com/symfony/symfony/blob/4a31c2952e5f5ed3c4a374b833cc75d2f793851f/src/Symfony/Component/Routing/Loader/AnnotationDirectoryLoader.php#L28-L31

Because it calls parent::load(), which is `AnnotationFileLoader::load()`, which has return type `?RouteCollection`
https://github.com/symfony/symfony/blob/4a31c2952e5f5ed3c4a374b833cc75d2f793851f/src/Symfony/Component/Routing/Loader/AnnotationFileLoader.php#L45

### How to reproduce

1. have an abstract class that extends `\Symfony\Bundle\FrameworkBundle\Controller\AbstractController` (e.g. `abstract class AdminController extends AbstractController`)
2. have `config/routes/annotations.yaml` similar to:

```yaml
controllers:
    resource: '../../src/**/*Controller.php'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

```
3. upgrade from 5.4.4 to 6.0.4
4. `Symfony\Component\Routing\Loader\AnnotationDirectoryLoader::load(): Return value must be of type Symfony\Component\Routing\RouteCollection, null returned`

### Possible Solution

Change the return type of `AnnotationDirectoryLoader::load()` to `?RouteCollection`
