### ISSUE TITLE
[Routing] The stateless property of a route cannot be changed in included routes

### ISSUE THREAD

**Issue by ampaze** [symfony/symfony#45300]
### Symfony version(s) affected

5.4

### Description

I want all my routes to be stateless by default and only mark routes that are not stateless as such.

This currently requires to mark every single route explicitly, as routes included via `resource` cannot override that property; declaring `stateless: false` has not effect.

I even tried to do it via `defaults`, which also does not work.

### How to reproduce

routes.yml
```yaml
routes:
    resource: "routing/routing.yml"
    stateless: true
```
routing/routing.yml
```yaml
route_a:
    path: /a
    controller: xxx
    stateless: false

route_b:
    path: /b
    controller: xxx
    defaults:
        _stateless: false
```
