### ISSUE TITLE
Translation Extract error

### ISSUE THREAD

**Issue by Elvandarysalys** [symfony/symfony#45372]
### Symfony version(s) affected

5.4.3

### Description

Hello

I think I have found a bug in the `translation:extract` command. Let me explain:

I wanted to extract one of my bundle translations inside this bundle `Resources/translations` folder (standard configuration)

I used the following command:

`bin/console translation:extract fr BundleName --force --clean`

This resulted in my translations being extracted in the project `/translations` folder.

### How to reproduce

Create a bundle using standard practices
Ensure there are something to translate.

Then, using this configuration:

```yaml
framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
```

use the `bin/console translation:extract fr BundleName --force --clean` command to extract the translations files

Expected: the translations should be in the `BundleName\Resources\translations` folder
Resulted: the translations should be in the `Project\translations` folder

### Additional Context

Investigating this, i found this piece of code in the `TranslationUpdateCommand.php` (lines 297 to 301):

```php
foreach ($transPaths as $path) {
    if (is_dir($path)) {
        $bundleTransPath = $path;
    }
}
```

which results in the 'default_path' always being selected as the translation path.

My framework-bundle is on the 5.4.4 version
