### ISSUE TITLE
`rememberme_token` table not created by DoctrineMigrationsBundle

### ISSUE THREAD

**Issue by PF4Public** [symfony/symfony#45393]
### Symfony version(s) affected

6.0.4

### Description

`rememberme_token` table not created by DoctrineMigrationsBundle and the existing one is dropped

### How to reproduce

Enabling "Remember Me" Login Functionality as it is described in [documentation](https://symfony.com/doc/current/security/remember_me.html):
```yaml
  token_provider:
                    doctrine: true
```
results in a "Remember Me" Login Functionality, that works, but contrary to the documentation stating:

> This also instructs Doctrine to create a table for the remember me tokens. If you use the DoctrineMigrationsBundle, you can create a new migration for this:
> …

DoctrineMigrationsBundle generates following migration:

```php
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE rememberme_token');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE rememberme_token (series VARCHAR(88) NOT NULL, value VARCHAR(88) NOT NULL, lastused TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, class VARCHAR(100) NOT NULL, username VARCHAR(200) NOT NULL, PRIMARY KEY(series))');
    }
```

**Comment by ghost** [comment]
Thank you @PF4Public for creating this bug report! Currently i can't reproduce this bug.
I have created a project based on symfony/website-skeleton, which shows that the doctrine migration file was created and the table "rememberme_token" was created if you execute the command `php bin/console doctrin:migrations:diff`.
See repository: https://github.com/denisfuchs/bug_doctrine_remember_me

I can only reproduce your described behavior if i do the following:

- Create an entity (already created in the repository)
- Implement remember me in security.yaml (already in repository; see last commit)
- Migrate
- Remove the remember me block in the security.yaml
- Migrate

Now i get the same migration file, which you have shown us obove.

So more information necessary.

Status: Reviewed

**Comment by PF4Public** [comment]
@denisfuchs Thanks for your reply and analysis.

In my security.yaml I have:
```yaml
            remember_me:
                token_provider:
                    doctrine: true
                secret:   '%env(APP_SECRET)%'
                #lifetime: 604800 # 1 week in seconds
                path:     /
```
But I doubt this changes anything.

I also have this:
```yaml
    providers:
        our_db_provider:
            entity:
                class: App:User
                property: username
…snip…
            provider: our_db_provider
```
Could this interfere somehow?
