### ISSUE TITLE
[Messenger] NOGROUP No such key or consumer group 'symfony' in XREADGROUP with GROUP option

### ISSUE THREAD

**Issue by zip-fa** [symfony/symfony#45489]
### Symfony version(s) affected

6.0.4

### Description

I have multiple consumers supervised by supervisor, running in Docker container.
All of them configured as below:

supervisor:

```
[program:test-messenger]
command=/usr/local/bin/php /var/www/backend/bin/console messenger:consume test -q -e prod --time-limit=3600 --no-debug
autostart=true
autorestart=true
startsecs=0
numprocs=1

stdout_events_enabled=true
stderr_events_enabled=true
```

messenger.yaml:

```
test:
    dsn: '%env(MESSENGER_TRANSPORT_DSN)%/test'
    options:
      consumer: '%env(default:default_consumer:MESSENGER_CONSUMER_NAME)%'
      delete_after_ack: true
    retry_strategy:
      max_retries: 3
      multiplier: 1
      delay: 30000
```

redis.conf:

```
maxmemory 1024mb
maxmemory-policy allkeys-lru
maxclients 50000
save ""
tcp-backlog 262144
```

They all crash at the same time somehow (probably, because of redis' maxmemory-policy). Sample log from two different consumers:

"message":"NOGROUP No such key 'test1' or consumer group 'symfony' in XREADGROUP with GROUP option","code":0,"file":"/var/www/backend/vendor/symfony/redis-messenger/Transport/Connection.php:382","datetime":"2022-02-19T23:18:48.313141+00:00"

"message":"NOGROUP No such key 'test2' or consumer group 'symfony' in XREADGROUP with GROUP option","code":0,"file":"/var/www/backend/vendor/symfony/redis-messenger/Transport/Connection.php:382","datetime":"2022-02-19T23:18:48.697896+00:00"

etc...

### How to reproduce

1) Run consumer
2) Delete stream from redis manually
3) Receive error

### Possible Solution

```
if (false === $messages) {
    if ($error = $this->connection->getLastError() ?: null) {
        $this->connection->clearLastError();
    }

    if(str_starts_with($error, 'NOGROUP')) {
        $this->autoSetup = true;

        return $this->get();
    } else {
        throw new TransportException($error ?? 'Could not read messages from the redis stream.');
    }
}
```

**Comment by zip-fa** [comment]
Also got new warning:

Warning: foreach() argument must be of type array|object, bool given
symfony/redis-messenger/Transport/Connection.php:294

**Comment by db306** [comment]
@zip-fa did you find any further information on this matter ? I seem to be experiencing the same behaviour on 5.4

**Comment by zip-fa** [comment]
@db306 check out my solution. I've created custom RedisMessenger with this fix and it seems to be ok for me

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by carsonbot** [comment]
Hello? This issue is about to be closed if nobody replies.

**Comment by carsonbot** [comment]
Hey,

I didn't hear anything so I'm going to close it. Feel free to comment if this is still relevant, I can always reopen!

**Comment by jameskitt616** [comment]
I am facing this issue right now. Are there any known fixes yet?
Using Symfony 6.2, deploying one or multiple workers via supervisor in my docker container, using redis with symfony messenger

`/etc/supervisor/conf.d/messenger-worker.conf`
```
[program:messenger-consume]
command=php /srv/app/bin/console messenger:consume async --time-limit=3600
user=www-data
numprocs=20
startsecs=0
autostart=true
autorestart=true
startretries=10
stopwaitsecs=5
stopsignal=INT
process_name=%(program_name)s_%(process_num)02d
environment=MESSENGER_CONSUMER_NAME=messenger-consume_%(process_num)02d
```

`messenger.yaml`
```
framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%?stream=transcode_queue"
                options:
                    stream: transcode_queue
                    consumer: '%env(MESSENGER_CONSUMER_NAME)%'
```

It does not happen always, on my dev environment it works, when deploying on prod it starts crashing, i couldnt figure out why. Symfony `APP_ENV` do not seem to have influence on this behaviour.
