### ISSUE TITLE
Allow multiple "when@" above a config

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#45506]
### Description

It would be great if we could define configuration for multiple environments when using "when@".

I find myself repeating a lot of config now that configuration is starting to move to a single config files (which I love).

On every project I will have a staging and production. Our staging will usually mirror production so we end up with something like:

```yaml
when@staging:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

```

It would be great if we could define this as:

```yaml
when@prod:
when@staging:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

```

or

```
when@[staging|prod]:
    ...
```

Alternatively, if we could define the staging environment to cascade from "prod" would be good too.

**Comment by nicolas-grekas** [comment]
This is how you should do it:
```yaml
when@prod: &prod
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@staging: *prod
```

**Comment by trsteel88** [comment]
Thanks @nicolas-grekas. Are there docs about this that I have missed?

**Comment by nicolas-grekas** [comment]
I'm not sure, this is yaml syntax, nothing specific to Symfony.
But if you feel like sending a PR to the doc, it'll be very welcome!

**Comment by trsteel88** [comment]
Oh I didn't realise. Thanks for the info. I'll see if I can find a nice spot to slot it into the Symfony docs.

**Comment by trsteel88** [comment]
For anyone else that comes across this, if you can also merge and update the config for another envinroment

```yaml
when@prod: &prod
    doctrine:
        foo1: bar1
        foo2: bar2


when@staging:
    <<: *prod
    doctrine:
        foo2: bar3
```

Result for prod:

foo1: bar1
foo2: bar2

Result for staging:
foo1: bar1
foo2: bar3

**Comment by wouterj** [comment]
@trsteel88 if you want to document this somewhere, you can maybe add a very small example to the `when@` example in https://symfony.com/doc/current/configuration/#configuration-environments

```yaml
# config/packages/webpack_encore.yaml
webpack_encore:
    # ...
    output_path: '%kernel.project_dir%/public/build'
    strict_mode: true
    cache: false

# cache is enabled only in the "prod" environment
when@prod:
    webpack_encore:
        cache: true

# disable strict mode only in the "test" environment
when@test:
    webpack_encore:
        strict_mode: false

# you can also use "Yaml anchors" to share config (e.g. make prod and staging the same)
when@prod: &webpack_prod
    webpack_encore:
        # ...
when@staging: *webpack_prod
```

**Comment by rvanlaak** [comment]
The same applies regarding documenting that defaults (e.g. autowiring) are not considered within a `when@...` either. Would be great to also document that as well (note to self).

**Comment by sovetski** [comment]
Very weird, I have 0 errors, but it does not work:

In `config\packages\framework.yaml`:

```yaml
when@dev: &dev
    framework:
        # Disable SSL certificate verification
        http_client:
            default_options:
                verify_host: false
                verify_peer: false

when@test:
    <<: *dev
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```

When I am on `dev`, the `default_options` is ok, the SSL is ignored, but not on `test`
