### ISSUE TITLE
Doctrine Migrations generates Messenger Doctrine Transport while auto_setup is true

### ISSUE THREAD

**Issue by jeremyhalin** [symfony/symfony#45530]
### Symfony version(s) affected

6.0.3

### Description

I've added a new entity to a Symfony project and did a `bin/console make:migration` to automatically generate migration.
The problem is that it creates a table for the Messenger Doctrine transport for failed messages, while I've set in `messenger.yaml` configuration file `auto_setup: true`.

I expect Messenger component to handle creation of the table automatically, and Doctrine Migrations to **not** create migrations since it could conflict with the one created automatically.

I'm not sure if this is a bug or expected behavior. But this seems odd.
In [documentation](https://symfony.com/doc/current/messenger.html#doctrine-transport), it says:
> Or, to create the table yourself, set the auto_setup option to false and [generate a migration](https://symfony.com/doc/current/doctrine.html#doctrine-creating-the-database-tables-schema).

### How to reproduce

1. install `symfony/messenger`
2. install `doctrine/doctrine-migrations-bundle`
3. configure messenger like so:
```yaml
framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            failed:
                dsn: 'doctrine://default'
                options:
                    table_name: 'schema.failed_messages'
                    use_notify: false
                    auto_setup: true # this is the default value

            custom_messages:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\YourMessageSerializer
                options:
                    auto_setup: false
                    exchange:
                        name: your_exchange_name
                        type: direct
                        default_publish_routing_key: your_routing_key
                    delay:
                        exchange_name: your_exchange_name
                    queues:
                        your_queue:
                            binding_keys: [your_routing_key]
                                # default configuration
```
4. create a new Doctrine Entity
5. try to create a new migration for this entity with `bin/console make:migration`

You should have the definition of `schema.failed_messages` in your migration file, whereas you don't want it.

### Possible Solution

Makes the `auto_setup: true` option in `messenger.yaml` disable creation of table in migration.
