### ISSUE TITLE
I can not get the session id under the login process 

### ISSUE THREAD

**Issue by kolossa** [symfony/symfony#45641]
### Symfony version(s) affected

6.0, 5.4

### Description

Hello!
There is a session migration when you login your symfony application. 
When I try to get the session id, I get the old one instead of the new (session id after the migration).
I can only get the new session id in a controller.

I tried several way.

Thank you for whatever you might be able to do!

### How to reproduce

LoginListener: 
```
namespace App\Event;

use Psr\Log\LoggerInterface;
use Symfony\Component\Security\Http\Event\LoginSuccessEvent;

class LoginListener
{
    private LoggerInterface $logger;

    /**
     * LoginListener constructor.
     */
    public function __construct(LoggerInterface $logger)
    {
        $this->logger=$logger;
    }

    public function onSymfonyComponentSecurityHttpEventLoginSuccessEvent(LoginSuccessEvent $event){
        $this->logger->info(get_class($this).' sessionId: '.$event->getRequest()->getSession()->getId());
    }
}
```

LoginSubscriber
```
namespace App\EventSubscriber;

use Psr\Log\LoggerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Security\Http\Event\InteractiveLoginEvent;
use Symfony\Component\Security\Http\SecurityEvents;

class LoginSubscriber implements EventSubscriberInterface
{
    private LoggerInterface $logger;

    /**
     * LoginSubscriber constructor.
     */
    public function __construct(LoggerInterface $logger)
    {
        $this->logger=$logger;
    }

    public static function getSubscribedEvents()
    {
        // return the subscribed events, their methods and priorities
        return [
            SecurityEvents::INTERACTIVE_LOGIN => [
                ['process', 0],
            ],
        ];
    }

    public function process(InteractiveLoginEvent $event)
    {
        $this->logger->info(get_class($this).' sessionId: '.$event->getRequest()->getSession()->getId());
    }
}
```

custom_authenticator:
```
namespace App\Security;

use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;

class Authenticator extends AbstractLoginFormAuthenticator
{
    private UrlGeneratorInterface $router;
    private LoggerInterface $logger;

    public function __construct(UrlGeneratorInterface $router, LoggerInterface $logger)
    {
        $this->router=$router;
        $this->logger=$logger;
    }

    protected function getLoginUrl(Request $request): string
    {
        return $this->router->generate('login');
    }

    public function authenticate(Request $request): Passport
    {
        $userName=$request->request->get('_username');
        $password=$request->request->get('_password');
        return new Passport(
            new UserBadge($userName),
            new PasswordCredentials($password)
        );
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        $this->logger->info(get_class($this).' sessionId: '.$request->getSession()->getId());

        return new RedirectResponse('test');
//        return null;
    }

    public function supports(Request $request): bool
    {
        return $request->isMethod('POST') && $this->getLoginUrl($request)===$request->getRequestUri();
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): Response
    {
        return parent::onAuthenticationFailure($request, $exception);
    }
}
```

security.yaml

```
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory:
            memory:
                users:
                    admin: { password: 'admin', roles:['ROLE_ADMIN']}
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            custom_authenticator: App\Security\Authenticator
            logout:
                path: app_logout

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```
services.yaml

```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Event\LoginListener:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LoginSuccessEvent, dispatcher: security.event_dispatcher.main }
    App\Event\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
```

and my TestController:

```
namespace App\Controller;

use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class TestController extends AbstractController
{
    /**
     * @Route("/test", name="test")
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(Request $request, LoggerInterface $logger): Response
    {
        $logger->info(get_class($this).' sessionId: '.$request->getSession()->getId());
        return $this->render('base.html.twig', [
        ]);
    }
}
```

result of the log:
[2022-03-04T20:51:39.717750+01:00] app.INFO: App\Security\Authenticator sessionId: a86dvo3f0rfln3vun2ngjlcavu [] []
[2022-03-04T20:51:39.816750+01:00] app.INFO: App\EventSubscriber\LoginSubscriber sessionId: a86dvo3f0rfln3vun2ngjlcavu [] []
[2022-03-04T20:51:39.832750+01:00] app.INFO: App\Event\LoginListener sessionId: a86dvo3f0rfln3vun2ngjlcavu [] []
[2022-03-04T20:51:40.128750+01:00] app.INFO: App\Controller\TestController sessionId: 9kdn2no2klg9gochhajlfc3v0a [] []

### Possible Solution

Those events should triggered after the session migration.

### Additional Context

result of the log:
[2022-03-04T20:51:39.717750+01:00] app.INFO: App\Security\Authenticator sessionId: a86dvo3f0rfln3vun2ngjlcavu [] []
[2022-03-04T20:51:39.816750+01:00] app.INFO: App\EventSubscriber\LoginSubscriber sessionId: a86dvo3f0rfln3vun2ngjlcavu [] []
[2022-03-04T20:51:39.832750+01:00] app.INFO: App\Event\LoginListener sessionId: a86dvo3f0rfln3vun2ngjlcavu [] []
[2022-03-04T20:51:40.128750+01:00] app.INFO: App\Controller\TestController sessionId: 9kdn2no2klg9gochhajlfc3v0a [] []
