### ISSUE TITLE
Support for constants in collection keys in XML config

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#45708]
### Description

This works with yaml

```yaml
App\Example:
    calls:
      - method: addOptions
        arguments:
          - key_1: "value_1"
            !php/const App\Example::CONSTANT_1: 'value_0'
```

I can use constant in a collection entry key. I'd like to use the same with XML config.

### Example

Currently I can use constant for value but not a key

```xml
<argument type="collection">
    <argument type="constant" key="Symfony\Component\Serializer\Normalizer\DateTimeNormalizer::FORMAT_KEY">DATE_ATOM</argument>
</argument
```
