### ISSUE TITLE
[WebProfiler] Add a limit how many profiles should be saved

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#45831]
### Description

I let run the profiler for a while and have now 80k profiles saved.  It would be nice if we could set a limit of max profiles should be set and delete older ones to save disk

### Example

```yaml
framework:
  profiler:
    max_profiles: 100
```

**Comment by alamirault** [comment]
Does anyone know how to implement it ? Is there native/efficient way to manage this ?



(I'm very interested by this feature and can help to the PR)

**Comment by fabpot** [comment]
I think it should be part of `FileProfilerStorage` (I would not add an interface for that for now as we don't want to support more than one storage anyway).

Instead of a max number of profiles, I would remove the oldest ones, which could be done during a call to `write`.
I would not make it configurable, though. Profiles are ephemeral by nature. The number of days is debatable, but I don't see any cases where you would have to have a look at a profiler older than a day, to be honest. So, let's say 2 days? Maybe 3 max?

**Comment by 94noni** [comment]
Can we use https://symfony.com/doc/current/reference/events.html#kernel-terminate ?
Defining a DevEvent if the config is present, event responsible to purge old profiles > `max_retention_days`

Given such config:

```yaml
framework:
  profiler:
    max_retention_days: 3 # number of days to keep local profile files
```
