### ISSUE TITLE
Optional parameter $inflector declared before required parameter $timeOfRecordingFormat is implicitly treated as a required parameter

### ISSUE THREAD

**Issue by andreo-code** [symfony/symfony#46208]
### Symfony version(s) affected

6.1 

### PHP version
8.1

### Description

My logs;

[2022-04-27T21:54:30.890774+02:00] deprecation.INFO: Deprecated: Optional parameter $inflector declared before required parameter $timeOfRecordingFormat is implicitly treated as a required parameter {"exception":"[object] (ErrorException(code: 0): Deprecated: Optional parameter $inflector declared before required parameter $timeOfRecordingFormat is implicitly treated as a required parameter at /var/app/var/cache/dev/ContainerPvGa6ak/DefaultHeadersDecorator_3a25962.php:54)"} []

### How to reproduce

**service:**

```
class DefaultHeadersDecorator implements MessageDecorator
{
    private ClassNameInflector $inflector;
    private Clock $clock;

    public function __construct(
        ClassNameInflector $inflector = null,
        Clock $clock = null,
        private string $timeOfRecordingFormat = Message::TIME_OF_RECORDING_FORMAT,
    )
    {
        $this->inflector = $inflector ?: new DotSeparatedSnakeCaseInflector();
        $this->clock = $clock ?: new SystemClock();
    }
//...
}
```
**services.yaml**

```
 EventSauce\EventSourcing\DefaultHeadersDecorator:
        class: EventSauce\EventSourcing\DefaultHeadersDecorator
        public: false
        lazy: true # if lazy has been deleted, everything is fine
        arguments:
            - '@EventSauce\EventSourcing\ClassNameInflector'
            - '@EventSauce\Clock\Clock'
            - !php/const EventSauce\EventSourcing\Message::TIME_OF_RECORDING_FORMAT
```

**Comment by n0rbyt3** [comment]
This is not a Symfony bug but a new feature of PHP 8: https://php.watch/versions/8.0/deprecate-required-param-after-optional.

Since your last parameter is an instance variable, it is treated as a required parameter (even if it has a default value!). If you are using PHP 8.1, you can also define the other parameters as instance variable with a default value. Otherwise just change the order (instance variables first followed by other required parameters, then all optional ones.

```php
public function __construct(
    private string $timeOfRecordingFormat = Message::TIME_OF_RECORDING_FORMAT,
    ClassNameInflector $inflector = null,
    Clock $clock = null
)
{
    $this->inflector = $inflector ?: new DotSeparatedSnakeCaseInflector();
    $this->clock = $clock ?: new SystemClock();
}
```

Edit: Your service definition redefines the default value for the ```$timeOfRecordingFormat``` parameter. If you have autowiring enabled, you can simply define your service as:

```yaml
services:
    EventSauce\EventSourcing\DefaultHeadersDecorator:
        lazy: true
```
