### ISSUE TITLE
[FtpClient] Manage and preconfigure FTP connexion with an abstraction for all protocols

### ISSUE THREAD

**Issue by ThomasBeauchataud** [symfony/symfony#46345]
### Description

I am currently building an application exchanging files by FTP to different servers and accounts.

The use of native PHP functions is boring, and creates a strong dependency between the protocol used and the business logic, so it’s complicated to evolve the protocol once installed.

Also, when we must reuse a connection in different parts of the application, we have to recreate a connection each time and re-inject the credentials.

My proposal would be to open an "FtpClient" component allowing to easily manage the creation of ftp connections threw different protocols: FTP , SFTP , FTPS , SCP.

All these protocols would be implemented behind a single interface.

```
interface FtpClientInterface
{

    public function download(string $remoteFilePath, string $localFilePath): void;

    public function upload(string $localFilePath, string $remoteFilePath): void;

    public function rename(string $oldFilePath, string $newFilePath): void;

    public function exists(string $filePath): bool;

    public function delete(string $filePath): void;

    public function mkdir(string $directoryPath): void;

    public function scan(string $directoryPath = '.'): array;

    public function isFile(string $filePath): bool;

}
```

Then we could preconfigure these connections as with ftp_client config and inject them into our services

```
framework:
    ftp_client:
        app1:
            host: 'your@domain1.com'
            user: 'user01'
            password: '...'
            port: '22'
            protocol: 'ftp'
        app2:
            host: 'your@domain1.com'
            user: 'user02'
            password: '...'
            port: '2222'
            protocol: 'sftp'
        app3:
            host: 'your@domain2.com'
            user: 'user01'
            password: '...'
            port: '22'
            protocol: 'ftps'
```
```
public function __construct(#[Target('app1.ftp_client')] FtpClientInterface $ftpClient)
{
        
}
```

Or of course create one ourself 
```
$ftpClient = new FtpsClient('host', 'user', 'password', 'port');
```
