### ISSUE TITLE
Issue with autoconfigure bindings and PHP compatibility

### ISSUE THREAD

**Issue by fritzmg** [symfony/symfony#46420]
### Symfony version(s) affected

5.4, 6.x

### Description

If you are not using `symfony/flex`, but you want to dump the `.env.local.php` you will need to register the command manually like so:

```yaml
services:
    Symfony\Component\Dotenv\Command\DotenvDumpCommand:
        autoconfigure: true
```

However, due to the usage of the `Autoconfigure` attribute this will only work in PHP 8, otherwise the bindings will be missing. 

_But_, if you instead register the service like this:

```yaml
services:
    Symfony\Component\Dotenv\Command\DotenvDumpCommand:
        autoconfigure: true
        arguments:
            - '%kernel.project_dir%'
            - '%kernel.environment%'
```

so that it works in PHP 7 - it won't work in PHP 8 as the following error will occur:

```
In ResolveBindingsPass.php line 84:
                                                                                                                                                      
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                          
  A binding is configured for an argument named "$projectDir" under "_instanceof" in file "vendor\symfony\dotenv\Command\DotenvDumpCommand.php", but no corresponding argument has been found. It may be unused and should be removed, or it may have a typo.
```

So essentially there is no way to properly register a service that happens to use the

```
#[Autoconfigure(bind: …)]
```

attribute so that it still works both with PHP 7.4 and 8.x.

Shouldn't the bindings be ignored instead, if the arguments were specifically set in the service configuration?

### How to reproduce

In a non-flex Symfony project, register the `dotenv:dump` command like so:

```yaml
services:
    Symfony\Component\Dotenv\Command\DotenvDumpCommand:
        autoconfigure: true
        arguments:
            - '%kernel.project_dir%'
            - '%kernel.environment%'
```

Then execute `cache:warmup` with a PHP 8 CLI. This will reproduce the aforementioned error.

**Comment by wouterj** [comment]
Is there a use-case in running an application on both PHP 7.4 and 8.x?

**Comment by fritzmg** [comment]
In this case the live environment of a project still runs under PHP 7.4 but my local development environment runs PHP 8. Granted, this is more or less only a nuisance and I would have to adjust my local environment accordingly. But still - I would expect bindings to be ignored if their arguments were already provided.

**Comment by nicolas-grekas** [comment]
I agree they should be ignored since explicit config took over. Can you have a look at a fix?

**Comment by fritzmg** [comment]
I can give it a shot, though I have limited experience with these components. The question is where to leverage this. For instance, should the `ResolveBindingsPass` ignore any such `unusedBindings` that have been detected? Or should we prevent these bindings being added as unused in the first place?

**Comment by nicolas-grekas** [comment]
I thought I could have a quick look and I submitted #46425 as a result. Does it fix the issue?

**Comment by fritzmg** [comment]
As far as I have tested, yes, now the following works in PHP 7 and PHP 8:

```yaml
services:
    Symfony\Component\Dotenv\Command\DotenvDumpCommand:
        autoconfigure: true
        arguments:
            - '%kernel.project_dir%'
            - '%kernel.environment%'
```
