### ISSUE TITLE
Monolog with firephp handler doesn't work

### ISSUE THREAD

**Issue by tarlepp** [symfony/symfony#46474]
### Symfony version(s) affected

6.1.0

### Description

After I updated to Symfony 6.1.0 I get following error:

```
Typed property Symfony\Bridge\Monolog\Handler\FirePHPHandler::$response must not be accessed before initialization
```

My `config/packages/dev/monolog,yaml`:
```yaml
monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            channels: ['!event']
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
```

Which seems to be correct according to recipe - https://github.com/symfony/recipes/blob/main/symfony/monolog-bundle/3.3/config/packages/dev/monolog.yaml

And if I comment out that `firephp` handler there all works as expected.

### How to reproduce

Use following monolog configuration:
```yaml
monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            channels: ['!event']
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
```
