### ISSUE TITLE
[HtmlSanitizer] allowed_link_hosts and allowed_media_hosts are empty array instead of null when not set

### ISSUE THREAD

**Issue by plfort** [symfony/symfony#46647]
### Symfony version(s) affected

6.1.*

### Description

According to HtmlSanitizerConfig documentation, **allowLinkHosts** and **allowMediaHosts** default value must be null to allow any hosts:
https://github.com/symfony/symfony/blob/013857adf4548e5dd07cd4e5ad96bbdc66235b6c/src/Symfony/Component/HtmlSanitizer/HtmlSanitizerConfig.php#L171-L185

https://github.com/symfony/symfony/blob/013857adf4548e5dd07cd4e5ad96bbdc66235b6c/src/Symfony/Component/HtmlSanitizer/HtmlSanitizerConfig.php#L213-L227

These values are set from FrameworkBundle configuration where we use arrayNode to describe them, so we get an empty array instead of null.

The result is that every URLs are filtered by default

### How to reproduce

Configure a basic sanitizer 
```yaml
framework:
  html_sanitizer:
    sanitizers:
        app.default_sanitizer:
            allow_safe_elements: true
```

```php

$sanitized = $appDefaultSanitizer->sanitize('<a href="https://symfony.com">hello</a>');
// <a>hello</a>
```

**Comment by berkut1** [comment]
even if you set it to null:
```
framework:
   html_sanitizer:
        sanitizers:
            default:
                allow_safe_elements: true
                allowed_link_schemes: ['https', 'http']
                allowed_link_hosts: ~

```
It still uses an empty array.
Also by default `allowed_link_schemes` is an empty array, instead of `['http', 'https', 'mailto', 'tel']`
