### ISSUE TITLE
[Notifier] multiple chatter transports for the same channel

### ISSUE THREAD

**Issue by bechir** [symfony/symfony#46695]
### Description

Actually we can use only one chatter transport for each channel. I could be useful to have multiple.

### Example

For example, if we have 2 telegram groups, one for sending messages to admins and the other for deliverers (a food delivery app), we can get this kind of config:

```yml
framework:
    notifier:
        chatter_transports:
           telegram:
            deliverer: '%env(TELEGRAM_DSN)%'
            admin: '%env(TELEGRAM_DSN_ADMIN)%'
```

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by wooly-booly** [comment]
+1

**Comment by wucherpfennig** [comment]
+1

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by bechir** [comment]
I have no idea on how to do it. Is it an easy pick task, @xabbuh ?

**Comment by xabbuh** [comment]
@bechir I don't know. Maybe it's as easy as implementing a chain transport. I guess you will have to give it a try to find out.

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by carsonbot** [comment]
Could I get an answer? If I do not hear anything I will assume this issue is resolved or abandoned. Please get back to me <3

**Comment by carsonbot** [comment]
Hey,

I didn't hear anything so I'm going to close it. Feel free to comment if this is still relevant, I can always reopen!

**Comment by Santttal** [comment]
Yes that would be nice!

**Comment by ksn135** [comment]
Why was it closed?

**Comment by ksn135** [comment]
### It's ALREADY implemented!
And it's VERY simple. 

```yaml
framework:
    notifier:
        chatter_transports:
            default: '%env(TELEGRAM_DSN)%'
            admin: '%env(TELEGRAM_DSN_ADMIN)%'
```
Usage:
```php
use Symfony\Component\Notifier\ChatterInterface;
use Symfony\Component\Notifier\Message\ChatMessage;

/*...*/
    $message = new ChatMessage($subject);
     /** @var ChatterInterface $chatter */
    $chatter->send($message); // send to first chatter (to channel "default")
    $chatter->send($message->transport('admin')); // send to channel "admin"
/*...*/

```
