### ISSUE TITLE
Rate limit with pattern

### ISSUE THREAD

**Issue by webmake** [symfony/symfony#46696]
### Description

Hello,
Now neither fixed_window nor sliding_window nor token_bucket doesn't solve the flood, because having 
```
        authenticated_api:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }
```
user can make 5k calls in the first second, then after 15mins 500.
Would it be possible to rate with pattern, like:
100req/s 50 times (per first 15mins), and then 15mins with 100req/s (in total 5 times per 15min)
It could look
```
        authenticated_api:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }
            interval: '1 second'
            amount: 100
```

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by webmake** [comment]
Hello,
yes, would be great, because now we 2custom locking mechanism to rate limit, instead of having done through the symfony package itself

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by webmake** [comment]
Hello, well yes, because now we have our custom rate limitation, would be nice to use it from symfony and throw our code

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by carsonbot** [comment]
Friendly ping? Should this still be open? I will close if I don't hear anything.

**Comment by webmake** [comment]
Yes, would be nice to have feature out of the box from symfony framework

**Comment by xabbuh** [comment]
@webmake PR welcome I think

**Comment by carsonbot** [comment]
Thank you for this suggestion.
There has not been a lot of activity here for a while. Would you still like to see this feature?

**Comment by carsonbot** [comment]
Could I get an answer? If I do not hear anything I will assume this issue is resolved or abandoned. Please get back to me <3

**Comment by carsonbot** [comment]
Hey,

I didn't hear anything so I'm going to close it. Feel free to comment if this is still relevant, I can always reopen!

**Comment by Nyholm** [comment]
I just saw this issue. I know it is old and I am sure the author already solved their problem. But for future reference:

One can solve the flooding by using two rate limiters. One with a short time and one with a long time. Example: 


```yaml
        authenticated_api:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }
        authenticated_api_throttle:
            policy: 'sliding_window'
            limit: 100
            interval: '10 seconds'
```

This will use your make sure you never get more than 100 request per (any) 10 seconds (prevent floods) and it allows you to do up to 5000 request per 10 minutes.
