### ISSUE TITLE
Messenger : only one handler with the same "name" will be called

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#46791]
### Symfony version(s) affected

6

### Description

When having many message handler services (tagged) using the same class and method - only the first will be called.

The `HandlerDescriptor` generates the same name for all handlers.
The `HandlersLocator` filters out the other handlers.
The `HandleMessageMiddleware` also filters out called handlers by name.

The `debug:messenger` command shows all handlers being registered.

The use case for this is a handler configured using a strategy pattern.
Generic handler with various processing steps that can be used for the same message.

### How to reproduce

Create two services from the same handler and register them both.

`
some_handler_a:
  class: SomeHandler
  tags: [{name: messenger.message_handler, handles: SomeMessage}]
some_handler_b:
  class: SomeHandler
  tags: [{name: messenger.message_handler, handles: SomeMessage}]
`

Only some_handler_a will be invoked.

### Possible Solution

The easiest fix is probably to add some unique element to the "name" generation for `HandlerDescriptor`.

**Comment by melihovv** [comment]
I also encountered this issue, but my use case is different.
I have event and several handlers that interacts with database. In order each handler was independent I created EventHandlerTransactionalDecorator (analog of \Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware)
```
final class EventHandlerTransactionalDecorator
{
    public function __construct(
        private EntityManagerInterface $entityManager,
        private object $innerEventHandler,
    ) {
    }

    public function __invoke(object $event): void
    {
        $this->entityManager->getConnection()->beginTransaction();

        try {
            $this->innerEventHandler->__invoke($event);

            $this->entityManager->flush();
            $this->entityManager->getConnection()->commit();
        } catch (Throwable $exception) {
            $this->entityManager->getConnection()->rollBack();

            if ($exception instanceof HandlerFailedException) {
                // Remove all HandledStamp from the envelope so the retry will execute all handlers again.
                // When a handler fails, the queries of allegedly successful previous handlers just got rolled back.
                throw new HandlerFailedException(
                    $exception->getEnvelope()->withoutAll(HandledStamp::class),
                    $exception->getNestedExceptions(),
                );
            }

            throw $exception;
        }
    }
}
```

And register event handlers this way
```
    $services
        ->set(
            SomeEventHandler::class . '.transactional',
            EventHandlerTransactionalDecorator::class,
        )
        ->decorate(SomeEventHandler::class)
        ->arg(
            '$innerEventHandler',
            service(SomeEventHandler::class . '.transactional.inner'),
        )
    ;

    $services
        ->set(
            AnotherEventHandler::class . '.transactional',
            EventHandlerTransactionalDecorator::class,
        )
        ->decorate(AnotherEventHandler::class)
        ->arg(
            '$innerEventHandler',
            service(AnotherEventHandler::class . '.transactional.inner'),
        )
    ;
```

The debug:messenger command also shows all handlers being registered. But only one handler is invoked.

I use symfony 5.4

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by carsonbot** [comment]
Friendly ping? Should this still be open? I will close if I don't hear anything.

**Comment by jkbmdk** [comment]
Same problem as @melihovv described, messenger graps handlers by unique class names instead of service name
```YAML
// events.yaml
services:
  MyService\FirstEventHandler:
    class: MyService\FirstEventHandler
    arguments: 
      - '@repository'

  event-handler.first:
    class: MyService\LogDecorator
    decorates: MyService\FirstEventHandler
    arguments:
      - '@logger'
      - '@.inner'
    tags:
      - name: messenger.message_handler
        bus: event.bus
        handles: MyService\Event

  MyService\SecondEventHandler:
    class: MyService\SecondEventHandler
    arguments: 
      - '@dependency'

  event-handler.second:
    class: MyService\LogDecorator
    decorates: MyService\SecondEventHandler
    arguments:
      - '@logger'
      - '@.inner'
    tags:
      - name: messenger.message_handler
        bus: event.bus
        handles: MyService\Event
```
`debug:messanger` displays both handlers
```
  MyService\Event
      handled by event-handler.first                        
      handled by event-handler.second
```
but consuming with `-vv` option pass only through first handler
```
11:44:10 INFO      [messenger] Received message MyService\Event ["class" => "MyService\Event"]
11:44:10 INFO      [messenger] Message MyService\Event handled by MyService\LogDecorator::__invoke ["class" => "MyService\Event","handler" => "MyService\LogDecorator::__invoke"]
11:44:10 INFO      [messenger] MyService\Event was handled successfully (acknowledging to transport). ["class" => "MyService\Event"]
```
without decorators it pass through both handlers

I'm working with `symfony/messenger: 6.2.0`

**Comment by jkbmdk** [comment]
Ok, I've found a solution, to fix it you have to pass  `decoration_inner_name` for each decorated handler, in above case it should be
```YAML
// events.yaml
services:
  MyService\FirstEventHandler:
    class: MyService\FirstEventHandler
    arguments: 
      - '@repository'

  event-handler.first:
    class: MyService\LogDecorator
    decorates: MyService\FirstEventHandler
    decoration_inner_name: event-handler.first // <-- add this
    arguments:
      - '@logger'
      - '@.inner'
    tags:
      - name: messenger.message_handler
        bus: event.bus
        handles: MyService\Event

  MyService\SecondEventHandler:
    class: MyService\SecondEventHandler
    arguments: 
      - '@dependency'

  event-handler.second:
    class: MyService\LogDecorator
    decorates: MyService\SecondEventHandler
    decoration_inner_name: event-handler.second // <-- and this
    arguments:
      - '@logger'
      - '@.inner'
    tags:
      - name: messenger.message_handler
        bus: event.bus
        handles: MyService\Event
```
then it works like a charm

**Comment by jkbmdk** [comment]
Ok, I've found a solution, to fix it you have to pass  `decoration_inner_name` for each decorated handler, in above case it should be
```YAML
// events.yaml
services:
  MyService\FirstEventHandler:
    class: MyService\FirstEventHandler
    arguments: 
      - '@repository'

  event-handler.first:
    class: MyService\LogDecorator
    decorates: MyService\FirstEventHandler
    decoration_inner_name: event-handler.first.inner # <-- add this, remember to choose a different name from the name of service
    arguments:
      - '@logger'
      - '@.inner'
    tags:
      - name: messenger.message_handler
        bus: event.bus
        handles: MyService\Event

  MyService\SecondEventHandler:
    class: MyService\SecondEventHandler
    arguments: 
      - '@dependency'

  event-handler.second:
    class: MyService\LogDecorator
    decorates: MyService\SecondEventHandler
    decoration_inner_name: event-handler.second.inner # <-- and this
    arguments:
      - '@logger'
      - '@.inner'
    tags:
      - name: messenger.message_handler
        bus: event.bus
        handles: MyService\Event
```
then it works like a charm
