### ISSUE TITLE
[DependencyInjection] when@dev does not inherit defaults + autoconfigure does not work

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#46803]
Hello

I faced something strange.
I wanted to add a data collector on a service. So I made a decorator.

My initial file:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\AgentProxy\:
        resource: '../../../src/AgentProxy/*'
        exclude:
            - '../../../src/AgentProxy/**/Exception/*'
            - '../../../src/AgentProxy/**/Model/*'

    AppBundle\AgentProxy\ClientInterface: '@AppBundle\AgentProxy\Client'
```

So I blindly added

```yaml
when@dev:
    services:
        AppBundle\AgentProxy\ClientCollector:
            decorates: AppBundle\AgentProxy\ClientInterface
```

It does not work for **2 reasons**

1.  Autowire does not work even if it's in the **same file**. I need to add `_defaults: { autowire: true}` in the `when@dev` section
2. So I also added `autoconfigure: true`, but does not work. I need to manually tag the service.

<details>
<summary>The final configuration that works</summary>

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\AgentProxy\:
        resource: '../../../src/AgentProxy/*'
        exclude:
            - '../../../src/AgentProxy/**/Exception/*'
            - '../../../src/AgentProxy/**/Model/*'

    AppBundle\AgentProxy\ClientInterface: '@AppBundle\AgentProxy\Client'

when@dev:
    services:
        _defaults:
            autowire: true
            autoconfigure: true # useless

        AppBundle\AgentProxy\ClientCollector:
            decorates: AppBundle\AgentProxy\ClientInterface
            tags:
                -
                    name: data_collector
                    id: 'AppBundle\AgentProxy\ClientCollector'
```

<details>

**Comment by alexislefebvre** [comment]
In the first example, the items of the collection are defined with `*` instead of `-`, is it a typo?

**Comment by lyrixx** [comment]
@alexislefebvre Oh, this is a bad copy paste (via slack) I guess. I fixed it. Thanks

**Comment by nicolas-grekas** [comment]
> Autowire does not work even if it's in the same file. I need to add _defaults: { autowire: true} in the when@dev section

There is some rightfulness in the current behavior. `when@foo` defines another yaml tree and merging them from the pov of DI looks edgy. We could give it a try of course. The alternative is to merge this in yaml, using yaml references.

> So I also added autoconfigure: true, but does not work. I need to manually tag the service.

That is strange. Can you create a small reproducing app so that we can inspect this behavior please?

**Comment by lyrixx** [comment]
Here you go:

https://github.com/lyrixx/test/tree/symfony-reproducer-46803-dic-tag

**Comment by nicolas-grekas** [comment]
Thanks. I found #30417 which explains this behavior for decorators.

**Comment by nicolas-grekas** [comment]
This should be the way to go:

```yaml
services:
    _defaults: &defaults
        autowire: true
        autoconfigure: true

    AppBundle\AgentProxy\:
        resource: '../../../src/AgentProxy/*'
        exclude:
            - '../../../src/AgentProxy/**/Exception/*'
            - '../../../src/AgentProxy/**/Model/*'

    AppBundle\AgentProxy\ClientInterface: '@AppBundle\AgentProxy\Client'

when@dev:
    services:
        _defaults: *defaults
        AppBundle\AgentProxy\ClientCollector:
            decorates: AppBundle\AgentProxy\ClientInterface
```

Alternatively:
```yaml
services: &services
    _defaults: 
        autowire: true
        autoconfigure: true

    AppBundle\AgentProxy\:
        resource: '../../../src/AgentProxy/*'
        exclude:
            - '../../../src/AgentProxy/**/Exception/*'
            - '../../../src/AgentProxy/**/Model/*'

    AppBundle\AgentProxy\ClientInterface: '@AppBundle\AgentProxy\Client'

when@dev:
    services:
        <<: *services
        AppBundle\AgentProxy\ClientCollector:
            decorates: AppBundle\AgentProxy\ClientInterface
```

Closing as I doubt this can go anywhere.

**Comment by jdreesen** [comment]
Is this right?
```yaml
when@dev:
    _defaults: *defaults
    services:
        AppBundle\AgentProxy\ClientCollector:
            decorates: AppBundle\AgentProxy\ClientInterface
```

Shouldn't it be like this instead?

```yaml
when@dev:
    services:
        _defaults: *defaults
        AppBundle\AgentProxy\ClientCollector:
            decorates: AppBundle\AgentProxy\ClientInterface
```
