### ISSUE TITLE
Entity listener not firing when repository is called with an absolute named entity

### ISSUE THREAD

**Issue by Tofandel** [symfony/symfony#46837]
### Symfony version(s) affected

6.1.0

### Description

Doctrine entity listeners do not fire when a user is not logged in, but fire correctly when a user is logged in

### How to reproduce

I declare my entity listeners in `services.yaml` like so:

 ```yaml
 
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Abstracts/'
      - '../src/Kernel.php'
      
  App\Listeners\CaseFolderListener:
    tags:
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postUpdate'
        entity: 'App\Entity\CaseFolder'
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postRemove'
        entity: 'App\Entity\CaseFolder'
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postPersist'
        entity: 'App\Entity\CaseFolder'
        
```

```php
<?php

namespace App\Listeners;

use App\Entity\CaseFolder;

class CaseFolderListener
{

    public function postPersist(CaseFolder $changed): void
    {
        dd($changed);
    }

    public function postRemove(CaseFolder $caseFolder): void { 
        dd($caseFolder);
    }

    public function postUpdate(CaseFolder $changed): void
    {
        dd($changed);
    }
}
```

When logged in, if I update a `CaseFolder` in a controller the listener will fire, if I do the same action while not logged in, the listener doesn't fire

### Additional Context

I've been digging through symfony and doctrine's code and really can't figure out why it's the case
