### ISSUE TITLE
[Messenger] Make default config for retry strategy

### ISSUE THREAD

**Issue by NikitaKharkov** [symfony/symfony#46860]
### Description

So, let's assume we have more than 20 transports and they use Kafka.

And assume I don't need to have a retry strategy and failed queue at all. In this case I have to write my own RetryStrategy and inside EACH transport configure it! So instead of one simple string with dns I should write expanded config. It's really annoying.

I didn't find any chance to change it because this piece of code:
```php
# Symfony/framework-bundle/DependencyInjection/FrameworkExtension.php
            if (null !== $transport['retry_strategy']['service']) {
                $transportRetryReferences[$name] = new Reference($transport['retry_strategy']['service']);
            } else {
                $retryServiceId = sprintf('messenger.retry.multiplier_retry_strategy.%s', $name);
                $retryDefinition = new ChildDefinition('messenger.retry.abstract_multiplier_retry_strategy');
                $retryDefinition
                    ->replaceArgument(0, $transport['retry_strategy']['max_retries'])
                    ->replaceArgument(1, $transport['retry_strategy']['delay'])
                    ->replaceArgument(2, $transport['retry_strategy']['multiplier'])
                    ->replaceArgument(3, $transport['retry_strategy']['max_delay']);
                $container->setDefinition($retryServiceId, $retryDefinition);

                $transportRetryReferences[$name] = new Reference($retryServiceId);
            }
```
straightly determine that if no config will be a default one.

At the same time in **symfony/messenger/EventListener/SendFailedMessageForRetryListener.php** we see that absent RetryStrategy is okey and could be null:
```php
    public function onMessageFailed(WorkerMessageFailedEvent $event)
    {
        $retryStrategy = $this->getRetryStrategyForTransport($event->getReceiverName());
        ...
        $shouldRetry = $retryStrategy && $this->shouldRetry($throwable, $envelope, $retryStrategy);

        $retryCount = RedeliveryStamp::getRetryCountFromEnvelope($envelope);
        if ($shouldRetry) {
            $event->setForRetry();
        ...
     }
```
So my suggestion is **to provide a default RetryStrategy config section for ALL transports** and move it to messenger section (maybe create a new section under "messenger", name it "default" and put under it).

### Example

```yaml
framework:
    messenger:
        transports:
            kafka1: 'dns:// (...)'
            kafka2: 'dns:// (...)'
            ...
            kafka22: 'dns:// (...)'
    default:
        retry_strategy:
            max_retries: 3
            delay: 1000
            service: ....
            # etc
```
