### ISSUE TITLE
[Mailer] `mailer.envelope.recipients` configuration does not work with sendmail

### ISSUE THREAD

**Issue by alexey-muzyka-1** [symfony/symfony#46877]
### Symfony version(s) affected

5.4.9

### Description

Symfony/Mailer : The recipients feature ("Always Send to the same Address") does not work with sendmail. **PHP 8.0**

### How to reproduce

add to: config/packages/dev/mailer.yaml
```yaml
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            recipients: ['valid@example.com']
            sender: 'no-reply@test.com'
```

Create any Email sender
```php
class EmailSender
{
    public function __construct(
        private MailerInterface $mailer,
    ) {
    }

    /**
     * @throws TransportExceptionInterface
     */
    public function send(): void
    {
        $email = (new TemplatedEmail())
            ->to('invalid@test.com')
            ->subject('Test Email)
            ->htmlTemplate('email/template.html.twig');

        $this->mailer->send($email);
    }
}
```

Process email. I've used mailhog to catch emails. So response is:

![image](https://user-images.githubusercontent.com/49100406/177784346-7c29360f-0b77-4e3b-8931-d7dbfaf213d6.png)

As you could see. The **sender** was retrieved from the configurations, but the **recipient** is not

### Additional Context

It was fixed in [this issue](https://github.com/symfony/symfony/issues/41149)
