### ISSUE TITLE
[DoctrineMessenger, Postgres] can't specify schema when configurate messenger table_name

### ISSUE THREAD

**Issue by thamine-cleverside** [symfony/symfony#46984]
### Description

I am trying to configure messenger dsn as doctrine and  i am using Postgres database.
I want to set the option `table_name` and specify the schema like the example below

I have the error bellow when trying to `doctrine:schema:update` 

`SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  schema "notify_property_management" does not exist ` 

Because the framework [here](https://github.com/symfony/doctrine-messenger/blob/ecf8a43154456767957f63384961fb34707bd706/Transport/PostgreSqlConnection.php#L124) tries to create to create a function in the DB  and the sprintf consider that the option `table_name` has no schema.

I would suggest :

- add the option `schema_name`
- Or making the option `table_name` support a schema name 

### Example

```
messenger:
        transports:
            transport_plan_2d_marked_as_delivered:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_DOCTRINE)%'
                options:
                    table_name: property_management.queue_plan_2d_marked_as_delivered
```
