### ISSUE TITLE
Add Support of Enums for Tagged Service Key

### ISSUE THREAD

**Issue by vlacour97** [symfony/symfony#47027]
### Description

It's impossible to use method returning Enum for define key of a service locator. 

### Example

services.yaml
   ``` yaml
 _instanceof:
        App\File\Definition\Configuration\FileDefinitionConfiguratorInterface:
            tags: ['app.file.definition.configurator']

    App\TemplateConfiguration\Definition\FileDefinitionManager:
        arguments:
            $configuratorLocator: !tagged_locator {tag: app.file.definition.configurator, default_index_method: getType}
```
```
interface FileDefinitionConfiguratorInterface
{
    public function configureBuilder(NodeBuilder $builder): void;
    public static function getType(): FileDefinitionType;
}
```
![image](https://user-images.githubusercontent.com/10577568/180448806-aed7f761-a6e3-4b60-a054-386c2c571a32.png)
