### ISSUE TITLE
[Messenger] Default middleware: false *and* allow_no_handlers

### ISSUE THREAD

**Issue by alejgr** [symfony/symfony#47198]
### Description

It is possible to have both options at the same time?

```yaml
event.bus:
    default_middleware: allow_no_handlers|false
    middleware:
        - validation
```

### Example

Maybe it should be rewrite to allow something like this:

```yaml
event.bus:
    default_middleware: false
    allow_no_handlers: true
    middleware:
       - validation
```

**Comment by wazum** [comment]
@alejgarciarodriguez hm, I think you can do that already, the following below is the equivalent to
```yaml
      event.bus:
        default_middleware: allow_no_handlers
```

you have to add the `handle_message` (and other) middleware yourself though …

```yaml
      event.bus:
        default_middleware: false
        middleware:
          - add_bus_name_stamp_middleware:
            - "event.bus"
          - reject_redelivered_message_middleware
          - dispatch_after_current_bus
          - failed_message_processing_middleware
          - send_message
          - handle_message:
            - true
```
(the `true` as argument for `handle_message` is the flag to allow no handlers when handling the message)
