### ISSUE TITLE
MemcachedAdapter fails when used with inter-pod K8s deployment

### ISSUE THREAD

**Issue by 0fca** [symfony/symfony#47245]
### Symfony version(s) affected

5.4

### Description

The problem lays somewhere in the MemcachedAdapter class itself or somewhere around there.
It just does not want to store or ready anything when deployed in pod on k8s, whereas the pod with memcached instance is a separate one.

### How to reproduce

To reproduce the issue:
- create the simple Symfony 5.4 project with symfony/cache and configure it to use memcached - no special configuration, just use app pool configured with memcached adapter.
- create simple, basic cluster with 1 or more nodes on k8s,
- deploy an app to one pod and the memcached to another one, command I used to run memcached was: memcached -m64 -vvv so nothing special. To fully reproduce the thing: set up TLS, set up some resource quotas (I used Burstable QoS), route ports through k8s Ingress and what is most important **do set up** the pods in the same namespace, not the different ones,
- try to read anything from the controller using such setup - it should return connection failure such as:
```
MemcachedAdapter client error: server has failed and is disabled until timed retry
```
RedisAdapter with default configuration and exact same config of deployments on k8s and node configuration works perfectly fine.
The thing is: I checked telneting from app's container and it worked. Memcached php driver also could connect and the cache stored values, but MemcachedAdapter from symfony/cache had problem despite anything I have tried.
I used FQDN to set up connection to memcached instance.

### Additional Context

app-deployment.yaml file looks like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: someapp-name 
  labels:
    app: someapp-name 
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: someapp-name 
  template:
    metadata:
      labels:
        app: someapp-name 
    spec:
      containers:
        - image: eu.gcr.io/some-namespace/someimage-app
          name: ts-apache
          imagePullPolicy: Always
          args: [ "./entrypoint_apache.sh" ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
              name: tr-port
        - image: eu.gcr.io/some-namespace/someimage-app
          name: ts-ws
          imagePullPolicy: Always
          args: [ "./entrypoint_ws.sh" ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          ports:
            - containerPort: 1337
              name: tr-ws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-memcached
  labels:
    app: distributed-memcached
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: distributed-memcached
  template:
    metadata:
      labels:
        app: distributed-memcached
    spec:
      containers:
        - image: memcached:1.6-alpine
          name: memcached
          command:
            - memcached
            - "-m 64"
            - -v
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "400m"
          ports:
            - containerPort: 11211
              name: tr-memcached
---
apiVersion: v1
kind: Service
metadata:
  name: someapp-name 
  labels:
    app: someapp-name 
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp-80
    - port: 443
      targetPort: 443
      protocol: TCP
      name: tcp-443
    - port: 1337
      targetPort: 1337
      protocol: TCP
      name: tcp-1337
  externalTrafficPolicy: Cluster
  selector:
    app: someapp-name 
---
apiVersion: v1
kind: Service
metadata:
  name: distributed-memcached
  labels:
    app: distributed-memcached
spec:
  type: NodePort
  ports:
    - port: 11211
      name: memcached-port
      targetPort: 11211
      protocol: TCP
  externalTrafficPolicy: Cluster
  selector:
    app: distributed-memcached
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-fanout
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-tempdev"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: someapp-name 
    nginx.org/websocket-services: someapp-name 
spec:
  tls:
    - hosts:
        - somedomain.example.com 
      secretName: all-hosts-tls1
  rules:
    - host: somedomain.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: someapp-name 
                port:
                  number: 80
          - path: /ws
            pathType: ImplementationSpecific
            backend:
              service:
                name: someapp-name 
                port:
                  number: 1337
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-tempdev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mail@example.com
    privateKeySecretRef:
      name: letsencrypt-tempdev
    solvers:
      - http01:
          ingress:
            class: nginx
```

My composer.json looks like:
```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "composer/package-versions-deprecated": "1.11.99.4",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.5",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.10",
        "galbar/jsonpath": ">=2.0",
        "gos/pubsub-router-bundle": "^2.7",
        "gos/web-socket-bundle": "^3.12",
        "haydenpierce/class-finder": "^0.4.3",
        "matomo/device-detector": "^4.3",
        "nelmio/cors-bundle": "^2.1",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.2",
        "sensio/framework-extra-bundle": "^6.1",
        "symfony/asset": "5.4.*",
        "symfony/console": "5.4.*",
        "symfony/dotenv": "5.4.*",
        "symfony/expression-language": "5.4.*",
        "symfony/flex": "^1.17|^2",
        "symfony/form": "5.4.*",
        "symfony/framework-bundle": "5.4.*",
        "symfony/http-client": "5.4.*",
        "symfony/intl": "5.4.*",
        "symfony/mailer": "5.4.*",
        "symfony/messenger": "5.4.*",
        "symfony/mime": "5.4.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "5.4.*",
        "symfony/process": "5.4.*",
        "symfony/property-access": "5.4.*",
        "symfony/property-info": "5.4.*",
        "symfony/proxy-manager-bridge": "5.4.*",
        "symfony/runtime": "5.4.*",
        "symfony/security-bundle": "5.4.*",
        "symfony/serializer": "5.4.*",
        "symfony/string": "5.4.*",
        "symfony/translation": "5.4.*",
        "symfony/twig-bundle": "5.4.*",
        "symfony/validator": "5.4.*",
        "symfony/web-link": "5.4.*",
        "symfony/webpack-encore-bundle": "^1.13",
        "symfony/yaml": "5.4.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0",
      "ext-pdo": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5",
        "symfony/browser-kit": "5.4.*",
        "symfony/css-selector": "5.4.*",
        "symfony/debug-bundle": "5.4.*",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^6.0",
        "symfony/stopwatch": "5.4.*",
        "symfony/web-profiler-bundle": "5.4.*"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.4.*"
        }
    }
}
```
