### ISSUE TITLE
[FrameworkBundle] lint:container does not report services for missing classes

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#47258]
### Symfony version(s) affected

5.4

### Description

Command `lint:container` does not report services for missing classes. Consider this example:
```yaml
services:
    App\Service\MissingClass:
        arguments:
            - '@eight_points_guzzle.client.external_api'
```

The class `App\Service\MissingClass` does not exist but this is not reported. 

### How to reproduce

see description

### Possible Solution

I would expect that the `lint:container` command will report that I try to register a service for a class that doesn't exist.
