### ISSUE TITLE
CSRF Token is not kept when session is renewed with REMEMBERME

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#47276]
### Symfony version(s) affected

6.1.X

### Description

CSRF tokens by default are stored and bound to the session and have no expiration per se.  However when using the REMEMBER-ME feature,  when the session is renewed, the csrf token is not kept,  causing invalid form

### How to reproduce

1. create a symfony project with a login form and remember me activated

```
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        endusers:
            id: 'App\Provider\EndUserProvider'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        endusers:
            host: app.*
            pattern: ^/
            provider: endusers
            lazy: true
            remember_me:
                secret: '%kernel.secret'
                # 2 months in seconds, the goal is to have the user logged-in
                # enough time to start to appreciate the service, so that he will
                # care about doing 'forgot password'
                lifetime: 5356800
                secure: true
                path: /
                always_remember_me: true
                token_provider: 'Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider'
            form_login:
                login_path: end_users_login
                check_path: end_users_login
                enable_csrf: true
                default_target_path: end_users_login
```

2. create an other form that is behind the `endusers` firewall ,  nothing special , let symfony manage it completly

### now as a user 

1.  login
2. open the page with the form
3. do noting during 24 minutes and 1 seconds , or at least session.gc-maxlifetime + 1 seconds ( https://www.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime )
4. submit the form
=>  you get a `Invalid CSRF token`

## Expected the behaviour 

As the session is recreated by remember-me ,  the csrf should be kept

### Possible Solution

When creating the remember-me cookie,  the csrf token should be stored in it,  so that when recreating the session, the csrf token can be kept
