### ISSUE TITLE
[Notifier] Global from header not being picked up for emails, or error message incorrect

### ISSUE THREAD

**Issue by jdelaune** [symfony/symfony#47313]
### Symfony version(s) affected

6.1.0

### Description

We have setup a global From header for emails like the documentation asks e.g.

``` yaml
# config/packages/dev/mailer.yaml
framework:
    mailer:
        headers:
            From: 'Fabien <fabien@example.com>'
```

However when we go to send an email via the notifier component we get this error:

> To send the "X" notification by email, you should either configure a global "from" header, set a sender in the global "envelope" of the mailer configuration or set a "from" header in the "asEmailMessage()" method.

We have done the first option of _configure a global "from" header_ yet we get this error and the email doesn't send.

Is there a bug in the notifier component or is this intended and the error message is wrong?

### How to reproduce

Set a global from header:

``` yaml
# config/packages/dev/mailer.yaml
framework:
    mailer:
        headers:
            From: 'Fabien <fabien@example.com>'
```

Send a notification via email using the Notifier component. e.g.

``` php
// src/Controller/InvoiceController.php
namespace App\Controller;

use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Notifier\Recipient\Recipient;

class InvoiceController extends AbstractController
{
    #[Route('/invoice/create')]
    public function create(NotifierInterface $notifier)
    {
        // ...

        // Create a Notification that has to be sent
        // using the "email" channel
        $notification = (new Notification('New Invoice', ['email']))
            ->content('You got a new invoice for 15 EUR.')
        ;

        // The receiver of the Notification
        $recipient = new Recipient(
            $user->getEmail(),
            $user->getPhonenumber()
        );

        // Send the notification to the recipient
        $notifier->send($notification, $recipient);

        // ...
    }
}
```

**Comment by fredericlesueurs** [comment]
Hi, 
This is not a bug, the message says that you have to fill in the mailer.envelope.sender key to define a global "From" header for notifier.
This is an exemple: 
```yaml
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'notifications@example.com'
```
