### ISSUE TITLE
[FrameworkBundle] lint:container should not lint services that are removed

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#47413]
### Description

Let's consider this example:
```yaml
services:
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

```
All the classes in src/ **are available** as services and this is nice because we get the plug and play experience. However it's obvious that not everything inside src/ is a service (models, messages, value objects, dto etc). This breaks the lint:container command. In my opinion this command should not lint services that are removed from the container. We don't have to lint something that will be removed.
Of course developer could be more granular when defining resources but when application is not small then this begins burdensome.
