### ISSUE TITLE
Exception  InvalidArgumentException('No CA certificate has been provided...') is thrown even if the option verify is false

### ISSUE THREAD

**Issue by tidbo** [symfony/symfony#47493]
### Symfony version(s) affected

5.3.12

### Description

I am trying to use rabbitmq with ssl support, i use an url in the format amqps://username:password@domain:port, and even if i add the option verify: false in the transport section in messanger.yaml i alway get this exception
`            throw new InvalidArgumentException('No CA certificate has been provided. Set "amqp.cacert" in your php.ini or pass the "cacert" parameter in the DSN to use SSL. Alternatively, you can use amqp:// to use without SSL.');`
by diving a little bit in the code i do not see any check of the verify option before throwing the exception above, if i understand well if the option verify is false there is no need to provide cacert.

### How to reproduce

1. Configure the section transport in messenger.yaml to use rabbitmq with ssl support (amqps://username:password@domain:port)
2.  Configure the verify option with the value false in messenger.yaml in the transport section
3. Try to publish a message to rabbitmq

### Possible Solution

In the file `https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php`  
replace the following code
```
      if ($useAmqps && !self::hasCaCertConfigured($amqpOptions)) {
            throw new InvalidArgumentException('No CA certificate has been provided. Set "amqp.cacert" in your php.ini or pass the "cacert" parameter in the DSN to use SSL. Alternatively, you can use amqp:// to use without SSL.');
        }
```
with something like
```
      if ($useAmqps &&  !(isset($amqpOptions['verify']) && $amqpOptions['verify'] === false)  && !self::hasCaCertConfigured($amqpOptions)) {
            throw new InvalidArgumentException('No CA certificate has been provided. Set "amqp.cacert" in your php.ini or pass the "cacert" parameter in the DSN to use SSL. Alternatively, you can use amqp:// to use without SSL.');
        }
```

**Comment by xabbuh** [comment]
The comment about the `verify` option in the `Connection` class reads like this:

> Enable or disable peer verification. If peer verification is enabled then the common name in the server certificate must match the server name. Peer verification is enabled by default.

This is something different than skipping CA validation, isn't it?

**Comment by tidbo** [comment]
yes i think you are right i closed it

**Comment by tidbo** [comment]
> The comment about the `verify` option in the `Connection` class reads like this:
> 
> > Enable or disable peer verification. If peer verification is enabled then the common name in the server certificate must match the server name. Peer verification is enabled by default.
> 
> This is something different than skipping CA validation, isn't it?

yes i think you are right i closed it

**Comment by sterrien** [comment]
> > The comment about the `verify` option in the `Connection` class reads like this:
> > > Enable or disable peer verification. If peer verification is enabled then the common name in the server certificate must match the server name. Peer verification is enabled by default.
> > 
> > 
> > This is something different than skipping CA validation, isn't it?
> 
> yes i think you are right i closed it

Hello, I just found your closed issue.

My question is : shouldn't the following configuration work ?

```yaml
framework:
    messenger:
        transports:
            async:
                dsn: 'amqps://guest:guest@localhost:5672/my-vhost/my-queue'
                options:
                    exchange:
                        name: 'my-exchange'
                        type: 'fanout'
                    queues:
                        'my-queue': ~
                    verify: false
                    vhost: 'my-vhost'
```

I use **amqps**, I do not give a **cacert**, I disable the **peer verifcation**.
