### ISSUE TITLE
Symfony 5.4 inconsistent behaviour with Custom Authenticator, Giving Full authentication is required exception

### ISSUE THREAD

**Issue by naveen-23** [symfony/symfony#47532]
### Symfony version(s) affected

5.4.9

### Description

I am working on Symfony 5.4, but facing an issue in authentication.

I get Full authentication is required  when doing an ajax call to below endpoint

> /getOtb 

> /getPoints

In the screenshot attached you can see that ajax call is giving Full Auth required Exception but working sometimes. 

>Full authentication is required to access this resource.

```yaml
    # security.yaml

      security:
         # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
         enable_authenticator_manager: true
         providers:
            redis_auth:
                id: app.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #anonymous: true
            pattern: ^/
            provider: redis_auth
            custom_authenticators:
                - redis_security_provider
    access_control:
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/otb, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/getOtb, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/getPoints, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*, roles: IS_AUTHENTICATED_FULLY }`
```

  ```php
    // TokenAuthenticator   

        <?php   

       namespace App\Security;
        
    

    class TokenAuthenticator extends AbstractAuthenticator
    {
        const TOKEN_KEY = 'authorization';
        CONST ACCESS_TOKEN = 'access_token';
     
        private $_skipRouteNames = ['login','auth'];
     
        public function __construct($router)
        {
            $this->_router = $router;
        }   
    

        
        public function supports(Request $request):?bool
        {
            $route = $request->get('_route');   

            if (in_array($route, $this->_skipRouteNames)) {
                return false;
            }   

            return $request->getSession()->has(self::TOKEN_KEY);
                    
        }
     
        public function authenticate(Request $request): PassportInterface
        {
            $authToken = $request->getSession()->get(self::TOKEN_KEY);
            $accessToken = $request->getSession()->get(self::ACCESS_TOKEN);
                

            if (null === $authToken) {
                // The token header was empty, authentication fails with HTTP Status
                // Code 401 "Unauthorized"
                throw new DefaultException("  No Auth Token", AppException::CONTROLLER_401);
            }
            
            return new SelfValidatingPassport(new UserBadge($authToken));
          
        }   

      
        public function onAuthenticationSuccess(Request $request, 
            TokenInterface $token, 
            $providerKey
        ): ?Response {
            // on success, let the request continue
            return null;
        }
     
        public function onAuthenticationFailure(Request $request, 
            AuthenticationException $exception
        ): ?Response {
            $url = $this->_router->generate('error');
            return new RedirectResponse($url);
        }   

    }
```      

```php
    //  App\Security\UserProvider   

    <?php
     
    namespace App\Security\User;
    use Symfony\Component\Security\Core\User\UserInterface;
    use Symfony\Component\Security\Core\User\UserProviderInterface;
    use App\Entity\User;
    use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
    use Symfony\Component\HttpFoundation\RequestStack;
     
    class WebserviceUserProvider implements UserProviderInterface
    {   

     
        public function __construct( $requestStack)
        {
            $this->_requestStack = $requestStack;
        }   

       
        public function loadUserByIdentifier(string $authorization)
        {
            $user = new User(); 

            $session = $this->_requestStack->getSession();  

            if ($session->has('authorization') && $session->has('access_token')) {
                $user->setAuthToken($session->get('authorization'));
                $user->setAccessToken($session->get('access_token'));
                return $user;
            }   

            throw new UsernameNotFoundException('User not found ');
        }
        
        public function loadUserByUsername($username): User
        {
            return $this->loadUserByIdentifier($username);
        }
     
        public function refreshUser(UserInterface $user)
        {
            return $user;
        }
        
        
        public function supportsClass(string $class)
        {
            return true;
        }   

         public function getRoles(): array
        {
            $roles = $this->roles;
            // guarantee every user at least has ROLE_USER
            $roles[] = 'ROLE_USER'; 

            return array_unique($roles);
        }   
    

    }
```

How can i resolve this issue ?

![errors-fullauth](https://user-images.githubusercontent.com/14973697/189363270-65acac5c-ff3b-4871-a54a-acf9ac487f96.jpg)
![working-V](https://user-images.githubusercontent.com/14973697/189363301-b5f3db25-15de-4eaf-8230-cfccad13c4cb.jpg)

### How to reproduce

Using a custom authenticator as described above with Symfony 5.4.9
