### ISSUE TITLE
Cannot have a form_login and a form_login_ldap on the same firewall

### ISSUE THREAD

**Issue by samuel-sol** [symfony/symfony#47785]
### Symfony version(s) affected

6.1.x

### Description

My application has multiple login possibilities, either through LDAP, a local user on a database, or a login user. Both can give access to the application fully (the local is a fallback in case LDAP is offline). So I was making this firewall

```
security:
  providers:
    # base local provider
    app_user_provider:
      entity:
        class: App\Entity\User\User

    custom_provider:
      id: App\Security\Provider\LdapUserProvider

    # chain
    all_users:
      chain:
        providers: ['custom_provider', 'app_user_provider']

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      entry_point: form_login_ldap
#      context: main

      # login for the ldap
      form_login_ldap:
        provider: all_users
        enable_csrf: true
        default_target_path: app_homepage
        login_path: app_login
        check_path: app_login
        service: Symfony\Component\Ldap\Ldap
        username_parameter: username
        password_parameter: password
        dn_string: xxxx
        query_string: xxxx
        search_dn: xxxxx
        search_password: xxxxx

      # login for the local entity
      form_login:
        provider: all_users
        enable_csrf: true
        default_target_path: app_homepage
        login_path: app_login_local
        check_path: app_login_local
        username_parameter: username
        password_parameter: password

      # login link used for fallback
      login_link:
        provider: all_users
        check_route: login_check
        check_post_only: true
        max_uses: 2
        lifetime: 86400 # 24 hours
        signature_properties: ['username']

      # logout
      logout:
        path: app_logout
        target: app_login
```

So here is the issue. If I comment on of `form_login` **OR** `form_login_ldap`, that method together with the `login_link` work. But if I uncomment both the login stops working, it always throws an **Invalid Credentials** error

### How to reproduce

have a firewall with both a form_login and a form_login_ldap on the config and you can't log in again.
