### ISSUE TITLE
Support object construction as a service argument in the Service Container

### ISSUE THREAD

**Issue by someniatko** [symfony/symfony#47888]
### Description

https://symfony.com/doc/current/service_container.html#manually-wiring-arguments article describes how to manually wire service arguments which are scalars or services themselves. However, sometimes it is required to pass a parameter which is neither scalar nor a service, but an object (e.g. DTO or a Value Object).

The current workaround for it is to register such an object as a service, make it private, and reference it as an argument. However I find it awkward and semantically incorrect.

I wish there would be a way of defining such objects, preferably in-line, without the need of creating a service.

### Example

For instance, instead of

```yaml
my_object:
    class: App\MyValueObject
    arguments: { $value: 'the-value' }

App\MyService:
    arguments: 
        $valueObject: '@my_object'
```

I with to use something like that:

```yaml
App\MyService:
    arguments:
        $valueObject:
            class: App\MyValueObject
            arguments: { $value: 'the-value' }
```

This could be implemented as a syntax sugar for creating a private service with some random name, I don't mind.
