### ISSUE TITLE
[Messenger] Message sent to sync and async transport is processed synchronously in async handlers

### ISSUE THREAD

**Issue by jokaorgua** [symfony/symfony#48025]
### Symfony version(s) affected

6.1.4

### Description

If some message is sent to transport async and sync transport at the same time the handler configured with 'from_transport' is processed synchronously

### How to reproduce

```php

class MyEvent {}

class MyEventHandler implements  MessageHandlerInterface
{
  public static function getHandledMessages(): iterable
    {
        yield MyEvent::class => [
            'from_transport' => 'async',
        ];
    }
    
    public function __invoke(MyEvent $message){
        dd(__CLASS__);
    }
}
```

```yaml
framework:
    messenger:
        failure_transport: failed

        transports:
            failed: 'doctrine://default?queue_name=failed'

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

            sync: 'sync://'

        routing:
            App\MyEvent: [async, sync]
```

```php
$messageBus->dispatch(new MyEvent());
```

as a result we will get the class name from __invoke method synchronously
