### ISSUE TITLE
[Messenger] Exception when specifying command.bus in messenger.yaml

### ISSUE THREAD

**Issue by gnito-org** [symfony/symfony#48118]
### Symfony version(s) affected

6.1.7

### Description

When I add the following configuration to messenger.yaml:

```
framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection

        # rest of config
```

Messenger fails with an `InvalidArgumentException` in `vendor/symfony/messenger/RoutableMessageBus.php` on line 63 with `Bus named messenger.bus.default does not exist`. 

I do the normal injection of `Symfony\Component\Messenger\MessageBusInterface`.

The docs at https://symfony.com/doc/current/messenger/multiple_buses.html say nothing about anything more that needs to be done.

This happens only in the `prod` environment. The exception does not occur in the `dev` environment.

When I do this:

```
framework:
    messenger:

        # rest of config
```
The exception disappears and it works. The exception does not occur in the `dev` environment.

Every time after changing the `messenger.yaml` file, I do the following:

1. `./bin/console cache:clear --env prod --no-debug; ./bin/console cache:warmup --env=prod`
2. Reset the PHP opcache.
3. `sudo supervisorctl restart all`

I've also tried deleting `var/cache/prod` in  Step 1 to no avail. Rebooting the server also does not help.

### How to reproduce

See Description.
