### ISSUE TITLE
[DependencyInjection] Defaults are not used for ContainerInterface controller argument

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#48192]
### Symfony version(s) affected

many

### Description

With this configuration:
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Psr\Container\ContainerInterface $workflowsLocator2: !tagged_locator { tag: workflow, index_by: name }
```

and this controller:

```php
    public function debug(ContainerInterface $workflowsLocator2)
    {
        dd([
            'workflowsLocator2' => $workflowsLocator2,
        ]);
    }
```

I expect to have all workflows, but it's not the case.

Fun fact

1. it works with iterator
2. but not locator
3. if I use a constructor, it's OK
