### ISSUE TITLE
delivery addresses list for mailer

### ISSUE THREAD

**Issue by y4roc** [symfony/symfony#48221]
### Description

For our staging server, it would be helpful to have a whitelist of email addresses that only sends mails to certain recipients, similar to what Swiftmailer does.

Is it just me, or are there others here who miss this feature?

### Example

```yaml
framework:
    mailer:
        delivery_addresses:
            - 'mail@example.com'
        delivery_whitelist:
            - '/@example.com$/'
```
