### ISSUE TITLE
[DependencyInjection] Configurator not called on lazy services ?

### ISSUE THREAD

**Issue by geoffrey-brier** [symfony/symfony#48255]
### Symfony version(s) affected

6.2.0-BETA3

### Description

Hi :wave: 

I am trying to upgrade my app in symfony 6.2 & I spotted a bug on configurators.
Indeed when a service using a configurator is declared as lazy then the configurator is not called.

### How to reproduce

```yaml
    # services.yaml
    
    App\Services\PaymentManagerConfigurator:
        arguments:
            $key: '%env(STRIPE_API_KEY)%'
            
    App\Services\PaymentManager:
        configurator: '@App\Services\PaymentManagerConfigurator'
# If I comment this line, the configurator is called, else it won't
#        lazy: true
 ```
