### ISSUE TITLE
Beta3 to RC1 composer update fails with logout csrf Uncaught Error

### ISSUE THREAD

**Issue by ChrisRiddell** [symfony/symfony#48339]
### Symfony version(s) affected

6.2.0RC1

### Description

When doing composer update from 6.2 beta3 to RC1 it throws an Uncaught Error

```shell
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!   // Clearing the cache for the dev environment with debug true                  
!!  
!!  
!!  In LogoutUrlGenerator.php line 50:
!!                                                                                 
!!    Symfony\Component\Security\Http\Logout\LogoutUrlGenerator::registerListener  
!!    (): Argument #5 ($csrfTokenManager) must be of type ?Symfony\Component\Secu  
!!    rity\Csrf\CsrfTokenManagerInterface, Symfony\Component\Security\Csrf\TokenG  
!!    enerator\UriSafeTokenGenerator given, called in /Users/chris/Desktop/xxxx/var/cache/dev/ContainerBakDEKc/App_KernelDevDebugContainer.php on   
!!    line 1267 
```

### How to reproduce

security.yml

```yaml
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

            remember_me:
                secret:   '%kernel.secret%' # required
                lifetime: 604800 # 1 week in seconds

            logout:
                path: app_logout
                enable_csrf: true
```

composer.json

```json
    "require": {
        "php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.7",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.13",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.13",
        "symfony/console": "6.2.*",
        "symfony/dotenv": "6.2.*",
        "symfony/flex": "^2",
        "symfony/form": "6.2.*",
        "symfony/framework-bundle": "6.2.*",
        "symfony/property-access": "6.2.*",
        "symfony/property-info": "6.2.*",
        "symfony/proxy-manager-bridge": "6.2.*",
        "symfony/rate-limiter": "6.2.*",
        "symfony/runtime": "6.2.*",
        "symfony/security-bundle": "6.2.*",
        "symfony/serializer": "6.2.*",
        "symfony/twig-bundle": "6.2.*",
        "symfony/validator": "6.2.*",
        "symfony/webpack-encore-bundle": "^1.16",
        "symfony/yaml": "6.2.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
```

This should work following 
https://symfony.com/blog/new-in-symfony-6-2-security-improvements-part-2#simpler-logout-csrf-protection
