### ISSUE TITLE
Custom PasswordHasher block migration of passwords

### ISSUE THREAD

**Issue by thisismeonmounteverest** [symfony/symfony#48348]
### Symfony version(s) affected

5.4

### Description

My project needs a LegacyPasswordHasher to verify old MYSQL passwords and the security configuration should make sure that these passwords are migrated to a newer algorithm. Unfortunately this fails.

### How to reproduce

Configure the `legacy` password hasher in `security.yaml`:

```
        legacy:
            id: 'App\Security\PasswordHasher\LegacyPasswordHasher'

        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            migrate_from:
                - legacy
```

Implement the `PasswordHasherAwareInterface` on the user entity checks and make it return 'legacy' to trigger that password hasher:

```
public function getPasswordHasherName(): ?string
{
    if (preg_match('/^\*[0-9A-F]{40}$/', $this->getPassWord())) {
        return 'legacy';
    }

    return null;
}
```

### Additional Context

The culprit is in `vendor/symfony/security-http/EventListener/PasswordMigratingListener.php::onLoginSuccess` when creating the new password hash it calls `LegacyPasswordhasher` instead of the expected default password hasher.

**Comment by MatTheCat** [comment]
I’m not sure but I don’t think you need to implement `PasswordHasherAwareInterface` for the migration to work.

**Comment by stof** [comment]
If you use PasswordHasherAwareInterface, you will not go through the default hasher, which is the migrating hasher configured with the modern algorithm and your legacy fallback, but you will force to use the legacy fallback directly. So you should indeed not use it to support the migration.

**Comment by chalasr** [comment]
As explained above. A PR to mention this in the docs wouldn't hurt I guess.

**Comment by thisismeonmounteverest** [comment]
The documentation is rather misleading then... 

Is there a standard configuration that would apply to the MYSQL old password structure that would be picked up by the default hasher?

I tried

```
legacy:
    algorithm: '*'
    hash_algorithm: 'sha1'
    iterations: 2
```

But that didn't work.
