### ISSUE TITLE
[DI] Empty tags get lost in instanceof conditionals

### ISSUE THREAD

**Issue by ausi** [symfony/symfony#48404]
### Symfony version(s) affected

5.4.16, 6.0.16, 6.1.8, 6.2.0

### Description

With the changes from #48027 empty tags get swallowed if a non-empty tag with the same name already exists. This causes issues because empty tags sometimes have a different meaning like with the `container.service_subscriber` tag.

The tag that gets set in https://github.com/symfony/symfony/blob/205cb5ac550f25c5fc07ff0778e811d57a6eb213/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L540-L541 is skipped by this if there is an existing non-empty tag wich causes the following exception: https://github.com/symfony/symfony/blob/205cb5ac550f25c5fc07ff0778e811d57a6eb213/src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php#L88

The `container.service_subscriber` tag has a different meaning if it is empty as we can see in: https://github.com/symfony/symfony/blob/205cb5ac550f25c5fc07ff0778e811d57a6eb213/src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php#L43

### How to reproduce

```
services:
    _instanceof:
        Some\Vendor\Interface:
            tags:
                - { name: container.service_subscriber, id: my.id }
                - { name: container.service_subscriber }
```

_(the second tag does not get applied)_

### Possible Solution

Revert #48027 and solve #48019 differently.
