### ISSUE TITLE
[DI] Implement instanceof_locator and instanceof_iterator

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#48443]
### Description

Since Symfony 4.3 we can use `!tagged_locator` and `!tagged_iterator` keywords to inject either a ServiceLocator or an `iterable` with a list of services with a specific tag.

In my experience, this is most often used to inject a list of services of a similar type, which almost always implies a list of services implementing a specific interface. This can be achieved with the following configuration:
```yaml
    _instanceof:
        Foo\Bar\SomeInterface:
            tags: [ 'foo.bar' ]
    Foo\SomeManagerClass:
        arguments:
            $handlers: !tagged_locator
                tag: 'foo.bar'
                default_index_method: 'getSomeSortOfKey'
```
Since this is one of the most common uses for the tagged locators, why are we writing 8 lines of config here to achieve a single result? If you have multiple `_instanceof` requirements you cannot even put them together like this.

We could easily cut it down by half and improve both readability and verbosity. I propose introducing the `instanceof_locator` and `instanceof_iterator` keywords:
```yaml
    SomeManagerClass:
        arguments:
            $handlers: !instanceof_locator
                instanceof: Foo\Bar\SomeInterface
                default_index_method: 'getSomeSortOfKey'
```
