### ISSUE TITLE
messenger on quiet

### ISSUE THREAD

**Issue by douglasjam** [symfony/symfony#48528]
### Symfony version(s) affected

5.4.3

### Description

when you have multiple receivers, and do not specify one with the quiet command, the system enters a while true without outcome

if you pass without --quiet it waits you to inform one, then it knows a receiver and works properly

loop with empty array can be found at
vendor/symfony/messenger/Worker.php:97

### How to reproduce

sample messenger.yaml
```
framework:
    messenger:
        routing:
            'Company\Message\Recommendation': recommendations-sqs
            'Company\Dto\Event\PartnerChangedEvent': partner-changed-events

        transports:
            recommendations-sqs:
                dsn: 'custom-trnasporter-1://'
                retry_strategy:
                    max_retries: 0
                options:
                    queueUrl: '%env(SQS_MY_QUEUE)%'

            partner-changed-events:
                dsn: 'custom-transporter-2://'
                retry_strategy:
                    max_retries: 0
                options:
                    queueUrl: '%env(SQS_MY_OTHER_QUEUE)%'
                    classToDeserialize: 'Company\Dto\Event\PartnerChangedEvent'
```

how to run
```
/var/www/php # ./bin/console messenger:consume

                                                                                                                        
 Which transports/receivers do you want to consume?                                                                     
                                                                                                                        

Choose which receivers you want to consume messages from in order of priority.
Hint: to consume from multiple, use a list of their names, e.g. recommendations-sqs, partner-changed-events

 Select receivers to consume: [recommendations-sqs]:
  [0] recommendations-sqs
  [1] partner-changed-events
 > 
/var/www/php # ./bin/console messenger:consume --quiet


```

### Possible Solution

Throw an exception when on quiet and can not identify the receiver, or add a short circuit in the loop
