### ISSUE TITLE
Bool environment variables are not resolved in package yaml config files

### ISSUE THREAD

**Issue by henryfoster** [symfony/symfony#48574]
### Symfony version(s) affected

5.4.12

### Description

I tried to use an env variable in a config yaml file to configure a package more dynamically.

```
fos_elastica:
    clients:
        default: { host: '%env(ELK_HOST)%', port: '%env(ELK_PORT)%', username: '%env(ELK_USER)%', password: '%env(ELK_PASS)%' }
    indexes:
        customer:
            index_name: 'customer_%env(ELK_INDX)%'
            persistence:
                driver: orm
                model: App\Entity\Customer
                provider: ~
                finder: ~
                repository: App\Services\Elastic\Repository\ElasticCustomerRepository
                listener:
                    insert: false
                    update: false
                    delete: '%env(ELK_LISTENER_ENABLED)%'
            properties:
                email:
                    type: keyword
                name: ~
```

.env.local
ELK_LISTENER_ENABLED=false

.env
ELK_LISTENER_ENABLED=false

The variable ELK_LISTENER_ENABLED is not resolved, causing this error to appear in the console when I clean the cache:

  Environment variables "ELK_LISTENER_ENABLED" are never used. Please, check your container's configuration.  

This error makes no sense because the variable is clearly used. The most funny thing is that if I hardcode delete: true or false everything works fine, and no error appears even tho the variable is definitely not used then (:

Other variables in the same config file work and are resolved correctly.

I tried different syntaxes as well:
 '%env(bool:ELK_LISTENER_ENABLED)%'
 '%env(resolve:ELK_LISTENER_ENABLED)%'
  "%env(bool:ELK_LISTENER_ENABLED)%"
  
  e.t.c.

### How to reproduce

I'm not sure this is caused by the fos_elastica bundle because from my understanding Symfony is responsible for resoling env variables and not a bundle.

But as this seems to only happen here.

- install symfony 5.4.12

- require symfony elastica bundle

- set up the config like I have in the description
- variabilize a boolean field like delete: 
- create the variable in your .env 
- try to run bin/console ca:cl
