### ISSUE TITLE
Login programmatically not working without 

### ISSUE THREAD

**Issue by LeamasRein** [symfony/symfony#48595]
### Symfony version(s) affected

6.2

### Description

The new ability to programmatically login does not work if at least one authenticator is not declared in config.

### How to reproduce

1. Create auth controller with $security (Symfony\Bundle\SecurityBundle\Security) and u user repo.
2. Fetch any profile from repo and use $security->login($user).
3. Catch exception "Call to a member function getProvidedServices() on null" in vendor/symfony/security-bundle/Security.php:122.

### Possible Solution

I "solved" the problem by adding an empty authenticator to the project.
```
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: false
            provider: app_user_provider
            custom_authenticators:
                - App\Security\EmptyAuthenticator
```

**Comment by chalasr** [comment]
Out of curiosity, can you show what your empty authenticator looks like? 
(The limitation is on purpose, though we probably need a more meaningful error)

**Comment by LeamasRein** [comment]
```
<?php
declare(strict_types=1);
namespace App\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;

class EmptyAuthenticator extends AbstractAuthenticator
{
    /** @override */
    public function supports(Request $request): ?bool
    {
        return false;
    }

    /** @override */
    public function authenticate(Request $request): Passport
    {
    }

    /** @override */
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        return null;
    }

    /** @override */
    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        return null;
    }
}
```

**Comment by wouterj** [comment]
This looks expected by me. Authenticators are the main driver of security (at least in Symfony). If all you do is programatic login, the place where you do programatic login should be refactored to be an authenticator.

Can you share a use-case where this reasoning no longer holds true?

**Comment by LeamasRein** [comment]
> The limitation is on purpose

Shouldn't there be an authenticator check in this case?

> Can you share a use-case where this reasoning no longer holds true?

I want to use a service for authorization and similar actions with users. I understand that the auth verification logic in the service is an anti-pattern for the Symfony.

I am using the [docs example](https://symfony.com/doc/current/security.html#login-programmatically) and call a login with authenticator class:
`$security->login($user, ExampleAuthenticator::class);`
But if I don't describe an ExampleAuthenticator in the firewall conf, it will throw an exception "Call to a member function has() on null" in vendor/symfony/security-bundle/Security.php:134.

Why don't I want to write it down there? Authenticator support will be checked every time, even when it is not required. I.e. an authenticator can't be used as a provider for on-demand authorization.

**Comment by wouterj** [comment]
> Shouldn't there be an authenticator check in this case?

Agreed, hence the "[...] though we probably need a more meaningful error". I think we should also check for `null === $firewallAuthenticatorLocator` for this exception: https://github.com/symfony/symfony/blob/dc803d75ee93f7b47eee072fc3971222112fdb29/src/Symfony/Bundle/SecurityBundle/Security.php#L122-L126

> Why don't I want to write it down there? Authenticator support will be checked every time, even when it is not required. I.e. an authenticator can't be used as a provider for on-demand authorization.

If you define your firewall as lazy (using `lazy: true`), authenticators won't be called unless you fetch the user or do authentication checks.

**Comment by LeamasRein** [comment]
> If you define your firewall as lazy (using lazy: true), authenticators won't be called unless you fetch the user or do authentication checks.

I've tried. But it doesn't work as expected. Maybe need to force the pages to not require privileges?

I changed the security config (lazy false to true):
```
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\EmptyAuthenticator
```

Check that the changes have been applied:
```
php bin/console debug:firewall main

Firewall "main"
===============

 ----------------------- --------------------------------------------------- 
  Option                  Value                                              
 ----------------------- --------------------------------------------------- 
  Name                    main                                               
  Context                 main                                               
  Lazy                    Yes                                                
  Stateless               No                                                 
  User Checker            security.user_checker                              
  Provider                security.user.provider.concrete.app_user_provider  
  Entry Point                                                                
  Access Denied URL                                                          
  Access Denied Handler                                                      
 ----------------------- --------------------------------------------------- 

Authenticators for firewall "main"
==================================

 --------------------------------- 
  Classname                        
 --------------------------------- 
  App\Security\EmptyAuthenticator  
 ---------------------------------
```

Added throw exception to lazy authenticator (supports method):
```
class EmptyAuthenticator extends AbstractAuthenticator
{
    public function supports(Request $request): ?bool
    {
        throw new Exception("No lazy");
        return false;
    }

    // ...
```

Open page from simple page controller:
```
class PageController extends AbstractController
{
    #[Route("/")]
    public function index(): Response
    {
        return $this->render("index.twig");
    }
}
```

And I got my exception. What did I do wrong?
