### ISSUE TITLE
[FrameworkBundle] "Ghost" services when excluding non-matches

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#48607]
### Symfony version(s) affected

6.2.1

### Description

I have a bundle with a service `MyBundle\SystemInformation\SystemInformation` that I would like to include.
So I now edit my `services.yaml` and add an invalid exclusion rules, as I forgot the star:

```yaml
services:
    _defaults:
        autoconfigure: true
        autowire: true

    MyBundle\:
        resource: ../src/*
        exclude:
            - ../src/SystemInformation #oops
```

If I now do a `debug:container` in the main application, it lists a non-existant service:

![CleanShot 2022-12-12 at 11 52 59](https://user-images.githubusercontent.com/1032411/207027666-a7663040-2042-40ca-a789-4dfdc247f1f6.png)

![CleanShot 2022-12-12 at 11 53 19](https://user-images.githubusercontent.com/1032411/207027676-9667e777-3ae6-45ce-b056-5d73d8472973.png)

One thing to not here is that the original service is gone now. So maybe the dummy excluded service that is added due to https://github.com/symfony/symfony/pull/46279 just uses the wrong id?

### How to reproduce

See above

### Possible Solution

This will be fixed if #48606 is implemented. Not sure if this has more consequences somewhere else.

**Comment by nicolas-grekas** [comment]
Does #48606 fix this one?

**Comment by apfelbox** [comment]
@nicolas-grekas can't reproduce right now, so seems to be fixed.

**Comment by shude** [comment]
I catch this issue now too. I will say more, ghost services appear not only with a non-existent exclusion path, but also in general on any folder that we exclude. For example:
```yaml
    App\:
        resource: ../src/*
        exclude:
            - '../src/Dto/'
            - '../src/Entity/'
```

If excluded paths is exists then we have two ghost services in a container:  
```
Serivece ID                                               Class name
App\Dto                                                    App\Dto
App\Entity                                                 App\Entity
```
