### ISSUE TITLE
Php configuration doesn't work like Yaml

### ISSUE THREAD

**Issue by TonySma** [symfony/symfony#48620]
### Symfony version(s) affected

6.2

### Description

Hello, 

I'm trying to convert my yaml configuration files to php. 
I'm facing something strange with php tag auto configuration using _instanceof keyword (see after)

While using yaml, my classes are correctly tagged, and I can see them using the `debug:container` command. 
Soon as I switch to php, all disappear, no class, no tag

Thanks for your help

### How to reproduce

```yaml
services:
    _instanceof:
        App\Document\Processor\DocumentProcessorInterface:
            tags: [ 'app.document.processor' ]
```

Corresponding php file who doesn't work

```php
<?php

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use App\Document\Processor\DocumentProcessorInterface;

return static function (ContainerConfigurator $containerConfigurator): void {

    $services = $containerConfigurator->services();

    $services->instanceof(DocumentProcessorInterface::class)
            ->tag('app.document.processor');
};
```
