### ISSUE TITLE
Localized routes generated without a prefix in 6.2

### ISSUE THREAD

**Issue by NovakHonza** [symfony/symfony#48664]
### Symfony version(s) affected

6.2

### Description

I ran into a bug when generating localized routes in Symfony 6.2. UrlGenerator ignores the prefix setting and generates only the route part from the definition in the Controller

### How to reproduce

```
# config/routes/annotations.yaml
controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        cs: ""
        en: "/en"
        de: "/de"
```

```
# Controller
/**
 * @Route({
 *      "cs": "/o-nas",
 *      "en": "/about-us",
 *      "de": "/ueber-uns"
 *  }, name="about")
 * @return Response
 */
public function about(): Response
{
    ...
```

```
# Twig
{{ path('about', {'_locale': 'en') }}
```

Expected result as in Symfony 6.1: `/en/about-us`
Real result in Symfony 6.2: `/about-us`
