### ISSUE TITLE
TagAwareCacheInterface doesn't contain getItem()/saveDeferred()/...

### ISSUE THREAD

**Issue by samspinoy** [symfony/symfony#48675]
### Symfony version(s) affected

5.4

### Description

Symfony\Contracts\Cache\TagAwareCacheInterface seems to be missing some methods.

### How to reproduce

I am running symfony 5.4, and have set up a Redis cache adapter.

```
framework:
        default_redis_provider: 'redis://rediscache:6379/0'
        pools:
            my.cache:
                adapter: cache.adapter.redis_tag_aware
                provider: 'redis://rediscache:6379/1'
```

I autowire it in my service classes, typehinting Symfony\Contracts\Cache\TagAwareCacheInterface. All is working fine (the incoming service is indeed a Symfony\Component\Cache\Adapter\RedisTagAwareAdapter Object etc), but my IDE and code checker keep complaining about undefined methods, f.ex. when using methods like $this->myCache->getItem() or saveDeferred(). Which makes sense, since TagAwareCacheInterface extends CacheInterface, which only has the get() and delete() methods defined.
I tried typehinting Symfony\Component\Cache\Adapter\TagAwareAdapterInterface instead but then I get an error that this service does not exist.
Again, all is working fine (I can call methods getItem & saveDeferred), but it would be nice to not have to suppress my codechecker errors each time I use caching in my code.
What am I missing here? Do I need to define an extra service or something?
