### ISSUE TITLE
Cookie expiration time is not updated on session lifetime resetting.

### ISSUE THREAD

**Issue by ahmed-bhs** [symfony/symfony#48755]
### Symfony version(s) affected

5.4

### Description

Hello there 👋 
On successful authentication, the firewall store the token in the session. This triggers a change in the session lifetime and deliver a response with the set-cookie header and an expiration time of the cookie depending on the `framework.session.cookie_lifetime` value.
But when accessing another time the same secured page, the session lifetime is resetted, without delivering a new set-cookie header. This means that a user will be kicked out, after his cookie lifetime expires, even his session lifetime still alive.

I understand that the session ttl is refreshed depending on the last request and the 
`framework.session.cookie_lifetime` value, but why there's no refreshing of the cookie expiration time same as we do for the session lifetime ?

In this case, what is the point of refreshing the lifetime of the user's session after each request?

### How to reproduce

* Authenticate a use user on a secure page
* Configure your framework.session.handler  in a way that we can access the lifetime of the session. I'm using snc redis handler.

```
session:
        enabled: true
        handler_id: snc_redis.session.handler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 50
```

* Authenticated the user on a secured page.
* Refresh the page after 10 seconds, for example, you will notice that the expiration time of the cookie is not updated unlike the lifetime ttl of the session on redis which is updated.
