### ISSUE TITLE
Web developer toolbar fails to load with security-bundle

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#48911]
### Symfony version(s) affected

6.2.4

### Description

The web developer toolbar fails to load with security-bundle 6.2.3.

>Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "authenticatorManagerEnabled" nor one of the methods "authenticatorManagerEnabled()", "getauthenticatorManagerEnabled()"/"isauthenticatorManagerEnabled()"/"hasauthenticatorManagerEnabled()" or "__call()" exist and have public access in class "Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector"." at symfony\security-bundle\Resources\views\Collector\security.html.twig line 7

### How to reproduce

Seems to occur with the following security configuration:

```yaml
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      stateless: true # comment this out to avoid the bug
```

### Additional Context

Does not happen with Symfony 5.4.
