### ISSUE TITLE
Profiler menu icons have incorrect background colour

### ISSUE THREAD

**Issue by kriswillis** [symfony/symfony#48925]
### Symfony version(s) affected

6.2.4

### Description

The profiler navigation menu icons do not have a transparent background.

![Screenshot_2023-01-09_12-48-11](https://user-images.githubusercontent.com/2786947/211313666-66638b78-2483-48a1-b87e-7e75fb5b6398.png)

symfony/web-profiler-bundle: 6.2.4

Google Chrome: 108.0.5359.124 (Official Build) (64-bit) - Linux

### How to reproduce

Open the profiler.

### Possible Solution

The following CSS rules appear to be affecting this:

```css
#menu-profiler li a .label .icon svg path,
#menu-profiler li a .label .icon svg .sf-svg-path {
    fill: #DDD;
}

#menu-profiler li.selected a .icon svg path,
#menu-profiler li.selected a .icon svg .sf-svg-path,
#menu-profiler li a:hover .icon svg path,
#menu-profiler li a:hover .icon svg .sf-svg-path {
    fill: #fff;
}
```
