### ISSUE TITLE
[DependencyInjection] Allow an easy decorator on multiple services

### ISSUE THREAD

**Issue by Neirda24** [symfony/symfony#48991]
### Description

The goal would be to easily decorate multiple services. Let's say I have two services `A` & `B` that respectively implement `AInterface` & `BInterface`.
I'd like to be able to create a service `C` that implement both `AInterface` & `BInterface` that will decorate `A` & `B` at the same time.

### Example

Given the following classes :

```php
interface AInterface
{
	public function doStuff();
}

class A implements AInterface
{
	public function doStuff()
	{
		//
	}
}

interface BInterface
{
	public function doSomething();
}

class B implements BInterface
{
	public function doSomething()
	{
		//
	}
}

class C implements AInterface, BInterface
{
	public function __construct(
		private readonly AInterface $a,
		private readonly BInterface $b,
	) {
		//
	}


	public function doStuff()
	{
		//
	}

	public function doSomething()
	{
		//
	}
}
```

with the following config (syntax TBD) :
```yaml
services:
    A:
        class: A

    AInterface: '@A'

    B:
        class: B

    BInterface: '@B'

    C:
        decorates: # Syntax TBD. Missing : priority
            - AInterface: ~
            - BInterface: ['@.inner']
```

In the container it should be dumped as

```php
$this->services[A::class] = new C(new A(), new B());
$this->aliases[AInterface::class] = A::class;
$this->aliases[B::class] = A::class;
$this->aliases[BInterface::class] = A::class;
```
Everything is inlined.

However if we add a D class that decorates only AInterface. It would look like :

```php
class D implements AInterface
{
	public function __construct(
		private readonly AInterface $a,
	) {
		//
	}


	public function doStuff()
	{
		//
	}
}
```

```yaml
services:
    D:
        decorates: 'AInterface'
```

with a dumped container like this :

```php
private function get_C(): C
{
        static $c = new C(new A(), new B()); // here "static" is only to represent that it is still the same instance.
	return $c;
}

$this->services[A::class] = new D($this->get_C());
$this->aliases[AInterface::class] = A::class;

$this->services[B::class] = $this->get_C();
$this->aliases[BInterface::class] = B::class;
```

It won't be inlined anymore.

WDYT ?
