### ISSUE TITLE
Symfony 6.2.4 multiple state workflow not working

### ISSUE THREAD

**Issue by tonyellow** [symfony/symfony#49061]
### Symfony version(s) affected

6.2.4

### Description

I want to configure a workflow with multiple states. While having no problem configuring a single state workflow there is no way i can get a workflow with multiple state to validate any transition. 

### How to reproduce

This is my workflow configuration:

```
        cataloguing:
            type: 'workflow'
            marking_store:
                property: 'cataloguingStatus'
                type: 'method'
            supports:
                - App\Entity\Artwork
            places:
                - todo
                - described
                - photographed
                - translated
                - reviewed
                - ready
            initial_marking: todo
            transitions:
                to_describe:
                    from: [todo, photographed, translated]
                    to: described
                to_translate:
                    from: [described]
                    to: translated
                to_photograph:
                    from: [todo, described, translated]
                    to: photographed
                to_review:
                    from: [described, photographed, translated]
                    to: reviewed
                ready_to_publish:
                    from: [reviewed]
                    to: ready
```

This is my Artwork entity:

```
    #[ORM\Column(type:"json", nullable: true)]
    private array $cataloguingStatus = [];

    public function getCataloguingStatus(): array
    {
        return $this->cataloguingStatus;
    }

    public function setCataloguingStatus(?array $cataloguingStatus): self
    {
        $this->cataloguingStatus = $cataloguingStatus;
        return $this;
    }
```
Database structure: 
![Screenshot 2023-01-22 at 11 56 07](https://user-images.githubusercontent.com/8984917/213912265-ac50ab05-d8b5-4f59-bf26-668af242524f.png)

Here is a dump of the workflow:

![Screenshot 2023-01-22 at 11 53 18](https://user-images.githubusercontent.com/8984917/213912147-99640960-dbc8-48e4-9cf3-38b2380d0667.png)

In my database the artwork.cataloguingStatus has the following initial cataloguing value:

![Screenshot 2023-01-22 at 11 54 16](https://user-images.githubusercontent.com/8984917/213912224-a3d2d97d-ffec-4efa-a547-8ac2e0f82656.png)

Now I dump the enabled transitions with getEnabledTransitions:

```
$artwork = $entityManager->getRepository('App\Entity\Artwork')->find('0185d55e-e571-7614-87e9-18dce959960d');
dump($cataloguingWorkflow->getEnabledTransitions($artwork));
```
This returns an empty array whilst the artwork has the initial status of todo and from todo there are many transitions:
![Screenshot 2023-01-22 at 12 09 54](https://user-images.githubusercontent.com/8984917/213912766-7264aefb-187a-4ddd-9c85-63b562ed57f0.png)

Lets try to apply transition to_describe:

![Screenshot 2023-01-22 at 12 04 56](https://user-images.githubusercontent.com/8984917/213912591-b36da2ab-ef57-4430-a5e5-1eaffdbd25a8.png)

The only way i can get everything to work is when I configure the froms in my workflow without array, but then it just acts like a singleState workflow and this is not what I am looking for.

To me it seems like a bug.
