### ISSUE TITLE
Doctrine Migration Bundle (bin/console make:migration ?) runs its own checks for the Messenger component settings

### ISSUE THREAD

**Issue by DavidGarciaCat** [symfony/symfony#49120]
### Symfony version(s) affected

5.4.12

### Description

Good day,

As per my report here https://github.com/doctrine/DoctrineMigrationsBundle/issues/485 it seems this issue I am experiencing with the Doctrine Bundle and the Messenger component working with the AMQP implementation are caused by this pull request https://github.com/symfony/symfony/pull/36655

It seems the Messenger.yaml file works file when warming up the cache but it throws an error with the Doctrine Bundle and generating migrations - the lines that cause the error seem to be:

```yaml
                options:
                    exchange:
                        name: async
                        type: direct
```

Any ideas here?

According to `bin/console --version` I am running Symfony 5.4.12

Thanks,

### How to reproduce

I have a project including the Messenger AMQP vendor as well as the Doctrine Pack.

I get the error when I set up the AMQP transport with the `options.exchange` key and try to generate a `diff` migration:

```yaml
                options:
                    exchange:
                        name: async
                        type: direct
```

### Possible Solution

I'm open to suggestions, but based on https://github.com/doctrine/DoctrineMigrationsBundle/issues/485 it seems to be an issue with the update merged here https://github.com/symfony/symfony/pull/36655
