### ISSUE TITLE
Unable to use Sessions: "Cannot find any session data."

### ISSUE THREAD

**Issue by panvid** [symfony/symfony#49140]
### Symfony version(s) affected

6.2.5

### Description

Since hours I have lots of trouble with Symfony starting session. Whole Kernel works perfect, I use PHP 8.2.1, Session can be startetd manually without any problem.

### How to reproduce

- Symfony Framework / Runtime 6.2.5
- PHP 8.2.1
- PHP Session Support enabled
- session.auto_start disabled
- session.save_path is read- and writeable, PHPs session_start() works

Session-Config
```yml
framework:
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
```

I call the Session with:
```php
\Symfony\Component\HttpFoundation\Request::createFromGlobals()->getSession();
```

This will throw an exception every time:
*Cannot find any session data.* thrown in *Symfony\Component\HttpFoundation\Request::getSession()*.

I used he session in local development stage. Project is under "http://localhost:8000".
