### ISSUE TITLE
[Messenger] AddBusNameStampMiddleware is not correctly registered if default_middleware has been disabled

### ISSUE THREAD

**Issue by andreo-code** [symfony/symfony#49160]
### Symfony version(s) affected

6.3.x-dev

### Description

Hi, 

Disabling the default middleware configuration and redefining `add_bus_name_stamp_middleware`  it throw an exception.
The rest middleware works corectly.

Regards

### How to reproduce

```yaml
framework:
    messenger:
        # ...
        default_bus: commandBus
        buses:
            commandBus: ~
            eventBus:
                default_middleware: false
                middleware: 
                    - 'add_bus_name_stamp_middleware' 
                    - 'dispatch_after_current_bus'
                    - 'failed_message_processing_middleware'
                    - 'send_message'
                    - 'custom_middleware'
                    - 'handle_message'
```

Then I sent a message and received an error:

500: Too few arguments to function Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::__construct()
0 passed and exactly 1 expected

**Comment by MatTheCat** [comment]
Hi,

indeed default middlewares are only configured when enabled: https://github.com/symfony/symfony/blob/a08a41c65fbb61cbc2e9b5d4d9d12e5b1bce6287/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2020-L2028

So `send_message` and `handle_message` are impacted as well.

Are you up for a PR? In the meantime you can work around this by configuring your own middleware from `messenger.middleware.add_bus_name_stamp_middleware`.

**Comment by andreo-code** [comment]
I could try PR, unfortunately I don't know when I would find time for it.

**Comment by MatTheCat** [comment]
After some digging it seems rather to be a documentation issue as you can configure arguments for your middlewares yourself. This has been mentioned as the way to go: https://github.com/symfony/symfony/pull/28945#discussion_r227355107

So, you’re supposed to write something like

```yaml
framework:
    messenger:
        # ...
        default_bus: commandBus
        buses:
            commandBus: ~
            eventBus:
                default_middleware: false
                middleware: 
                    - 'add_bus_name_stamp_middleware': ['eventBus']
                    - 'dispatch_after_current_bus'
                    - 'failed_message_processing_middleware'
                    - 'send_message'
                    - 'custom_middleware'
                    - 'handle_message'
```
