### ISSUE TITLE
[Messenger] Allow of one handler method for "Handling Multiple Messages" with AsMessageHandler attribute

### ISSUE THREAD

**Issue by andreo-code** [symfony/symfony#49163]
### Description

Hi

I need handle multiple messages based on https://symfony.com/doc/current/messenger.html#handling-multiple-messages, but i would like use single method for this. When it configure multiple messages to one method it gets an error `AsMessageHandler attribute cannot declare a method on ...`, but when the configuration has been created manually, the exception is not thrown.
I don't understand why not leave the decision to configure the handler to one method to the programmer. This may be useful in some cases.

### Example

```php

<?php

// It throws exception: AsMessageHandler attribute cannot declare a method on ...
// EventConsumer has handle method and it has some logic. Next calls original method of handler.
final class FooProjection extends EventConsumer
{
    #[AsMessageHandler(
        method: 'handle',
        handles: FooCreated::class
    )]
    public function onFooCreated(FooCreated $fooCreated): void
    {
    }

    #[AsMessageHandler(
        method: 'handle',
        handles: BarCreated::class
    )]
    public function onBarCreated(BarCreated $barCreated): void
    {
    }
}
```
```yaml
    App\FooProjection: # it works fine
        tags:
            -
                name: 'messenger.message_handler'
                method: 'handle'
                handles: App\Event\FooCreated
            -
                name: 'messenger.message_handler'
                method: 'handle'
                handles: App\Event\BarCreated
```
