### ISSUE TITLE
Allow customizing path pattern in Psr4DirectoryLoader (Routing)

### ISSUE THREAD

**Issue by speller** [symfony/symfony#49177]
### Description

Currently, only configurations like the following are allowed to load routes from attributes or annotations:

```yaml
controllers:
  resource:
    path: ../src/
    namespace: App\
```

It would be also nice to have the possibility to set up the path pattern that is passed in the `Symfony\Component\Routing\Loader\Psr4DirectoryLoader::loadFromDirectory()` method to the `DirectoryResource`:

```php
    private function loadFromDirectory(string $directory, string $psr4Prefix): RouteCollection
    {
        $collection = new RouteCollection();
        $collection->addResource(new DirectoryResource($directory, '/\.php$/'));
```

Instead of looking up all PHP files with the `/\.php$/` pattern, I would like to define a custom one.

### Example

```yaml
controllers:
  resource:
    path: ../src/
    path_pattern: /Controller\.php$/ # <--- new configuration key
    namespace: App\
```
