### ISSUE TITLE
Enhance security by issuing a Clear-Site-Data header on logout

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#49266]
[`Clear-Site-Data`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data#sign_out_of_a_web_site) is a header that we can use to tell browsers to remove some client-side state (see link for details.)

What about sending this header on logout, so that the "Back" button cannot be used to see the logged-in state after a logout?

**Comment by maxbeckers** [comment]
What you mention here is the example https://www.w3.org/TR/clear-site-data/#example-signout ... I have a few cases in mind where this really makes sense. Therefore, this would be a good option to configure it for the logout to suit the needs.

IMHO it could look like this in config:
```
security:
    # ...
    firewalls:
        main:
            # ...
            logout:
                path: app_logout
                clear_site_data: true // could be as well '*' or a sublist of 'cache', 'cookies', 'storage', 'executionContexts'
```
or it could be a headers field in the logout config where the header could be configured?
