### ISSUE TITLE
[Workflow] New lines (\n) results in partially coloured label in image generated from PUML dump

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#49311]
### Symfony version(s) affected

5.4+

### Description

When I use `\n` in the label of a transition, the PNG file generated from the PUML file shows text with and without the color applied.

<del>Using quotes breaks the generation of the PNG image, but it may be the expected behaviour of the YAML Component.</del>

### How to reproduce

```
                symfony_test:
                    from: [pending, created, scheduled]
                    to: courierconfirmed
                    metadata:
                        color: 'DarkGreen'
                        arrow_color: 'DarkGreen'
                        label: "Lorem ipsum\n(hey)"
```

Here is the result:

> ![image](https://user-images.githubusercontent.com/2071331/217781444-0a4c13e2-2828-453f-bca5-c4213dcf45f8.png)

### Possible Solution

Close the `<font>` tag before `\n` and reopen it after that new line.

### Additional Context

See also #49174
