### ISSUE TITLE
Implements Enum->name in Symfony\Component\Yaml\Inline

### ISSUE THREAD

**Issue by info-droid** [symfony/symfony#49373]
### Description

Hi,

With `!php/enum` in yaml files, we have 2 possibilities:
- `!php/enum Foo\Bar::VALUE` : it will create the `Bar` enum with `VALUE` value
- `!php/enum Foo\Bar::VALUE->value` : it will create the Bar enum with `VALUE` value, then call `->value` on it

But we can't use `->name`, as we can with `->value`.

So we can't use `!php/enum` when we have an UnitEnum, and want the name (not the instance of the enum).

See it here: [RoleEnum](https://github.com/symfony/yaml/blob/6.2/Inline.php#L631)

### Example

```yaml
security:
    firewalls:
        main:
            form_login:
                # We can use BackedEnum with ->value
                login_path: !php/enum App\Routing\Route\SecurityRouteEnum::LOGIN->value
                # We can't use UnitEnum
                login_path: !php/enum App\Routing\Route\SecurityRouteEnum::LOGIN->name
```
