### ISSUE TITLE
[SecurityBundle] Can not use decorated service for success/failure handler

### ISSUE THREAD

**Issue by astronom** [symfony/symfony#49457]
### Symfony version(s) affected

5.4.19+, 6.2.5+

### Description

The PR #48937 breaks the opportunity to use decorated success/failure handler services. If you check DI using `debug:container lexik_jwt_authentication.handler.authentication_success` it will show that the service is decorated.

### How to reproduce

```yaml

    services:
        App\Security\Http\Authentication\AuthenticationSuccessHandlerDecorator:
           decorates: lexik_jwt_authentication.handler.authentication_success
           arguments:
                $decoratedSuccessHandler: '@.inner'

    firewalls:
        auth:
            pattern: ^/auth/
            json_login:
                check_path: auth_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```
