### ISSUE TITLE
Rate Limiter Message: Don't Output Minutes

### ISSUE THREAD

**Issue by TheDevick** [symfony/symfony#49458]
### Symfony version(s) affected

6.2.6

### Description

I'm Following the [**Security - Limiting Login Attempts**](https://symfony.com/doc/6.3/security.html#limiting-login-attempts) page.

### How to reproduce

Adding the following code on `config/packages/security.yml`:

```yml
security:

    firewalls:
        # ...

        main:
            # ...

            # configure the maximum login attempts
            login_throttling:
                max_attempts: 3          # per minute ...
                # interval: '15 minutes' # ... or in a custom period
```

The Limit Login Attempts works correctly. But the error message shows:
```
Too many failed login attempts, please try again in %minutes% minute.
```

Note that it has `%minutes%`, where the minutes should be displayed (For example, `5`)

### Possible Solution

I don't have sure, but maybe use a funcion like `sprintf()`, or something similar. 

### Additional Context

You can reproduce the bug cloning the **Nystron Solar | Web** Repository, on commit [**feat: add Symfony Rate Limiter for Login Route**](https://github.com/NystronSolar/Web/tree/c6cc78b4b66d1903b12944f7321f88f91e97f05b), and acessing the `/security/login` Route.
