### ISSUE TITLE
[Workflow] Allow transitions for multiple places with same name

### ISSUE THREAD

**Issue by tomme87** [symfony/symfony#49521]
### Description

If I have a two (or more) transitions with the same name and one of the froms is present in both transitions I get the error  `All transitions for a place must have an unique name. Multiple transitions named "to_place_4" where found for place "place_2" in workflow "test".`

But I think this should be allowed, since not *all* froms is in the same transition.
I agree with the error if *all* froms is the same for both transitions.

Now I need to have 2 transitions for each combination of from, like `to_place_4_from_place_2_and_3` and `to_place_from_place_2` And I need to have some logic to the check which transition I need to do based on the places I'm in. I would like to avoid this.

### Example

This should be allowed:
```yaml
framework:
  workflows:
    test:
      type: 'workflow'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'currentStates'
      supports:
        - App\Entity\Test
      initial_marking: place_1
      places:
        - place_1
        - place_2
        - place_3
        - place_4
      transitions:
        -
          name: to_place_2
          from: place_1
          to: place_2
        -
          name: to_place_2_and_3
          from: place_1
          to:
            - place_2
            - place_3
        -
          name: to_place_4
          from:
            - place_2
            - place_3
          to: place_4
        -
          name: to_place_4
          from: place_2
          to: place_4      
```

With this I can do
```php
$workflow->apply($test, 'to_place_4')
```
If I'm in `place_2` and `place_3` (at the same time) and in only `place_2`.
