### ISSUE TITLE
RouterListener loops through all files in project

### ISSUE THREAD

**Issue by signor-pedro** [symfony/symfony#49668]
### Symfony version(s) affected

6.2.7

### Description

Recently, we switched route declarations to attributes.

Immediately, our production server went dead.

This is how we defined our routes in `attributes.yaml`:
```yaml
controllers:
  resource: '../../{apps,src}/**/*Controller.php'
  type: 'attribute'
```

Focus on `{apps,src}` - after a lot of investigation, we found out that the `RouterListener` was actually looping through all the files **in all folders**.

Since our `public/uploads` folder is a 300GB nfs mount, the server died whenever the routes cache was being warmed.

### How to reproduce

Use curly braces notation in the `resource` section of route declaration.

### Possible Solution

The workaround is to declare the routes separately, e.g.

```yaml
apps_controllers:
  resource: '../../apps/**/*Controller.php'
  type: 'attribute'

src_controllers:
  resource: '../../src/**/*Controller.php'
  type: 'attribute'
```
