### ISSUE TITLE
Bug on symfony/validation Regex

### ISSUE THREAD

**Issue by tavaresmatheus** [symfony/symfony#49860]
### Symfony version(s) affected

6.2

### Description

I'm having some problem here with password validation. I'm using the Regex property validation with `symfony/validation` and having this issue:
validation.yaml
```
App\Entity\User:
    properties:
        name:
            - Type: string
            - Length:
                min: 2
                max: 255
                minMessage: 'Your name must have at least two characters long.'
                maxMessage: 'Your name must have less than 255 characters long.'
        email:
            - Email:
                mode: html5
                message: 'The email you are trying to use is not valid.'
        password:
            - Regex:
                pattern: '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z])(?=.*[a-zA-Z])(?=.*\W).{11,30}$/'
                message: 'Your password must have a number, a lowercase letter, a uppercase letter, a special character, eleven characters and 30 characters maximum.'
```
If I put the regex used on validation.yaml, password property and execute it on vanilla PHP it simply works (and any other regex site validator). But if i put it the validaion.yaml it simply doesn't work. The Regex is never matched. Above an example of the pattern working on https://regexr.com/, but it also works on PHP's `preg_match` fine.
![image](https://user-images.githubusercontent.com/77064814/228552263-4b3b254a-8bdb-42f4-bcbe-1987728c1792.png)

Also, on Slack Support channel, there was some comment that on v5.2 it works fine, the same example.

### How to reproduce

On valdation.yaml, just put the content:
```
App\Entity\User:
    properties:
        name:
            - Type: string
            - Length:
                min: 2
                max: 255
                minMessage: 'Your name must have at least two characters long.'
                maxMessage: 'Your name must have less than 255 characters long.'
        email:
            - Email:
                mode: html5
                message: 'The email you are trying to use is not valid.'
        password:
            - Regex:
                pattern: '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z])(?=.*[a-zA-Z])(?=.*\W).{11,30}$/'
                message: 'Your password must have a number, a lowercase letter, a uppercase letter, a special character, eleven characters and 30 characters maximum.'
```
And validate the input:
```
        $validationErrors = $this->validator->validate($user);
        $errorQuantity = count($validationErrors);
        if ($errorQuantity > 0) {
            $errors = [];
            for ($counter = 0; $counter < $errorQuantity; $counter++) {
                $errors[$validationErrors->get($counter)->getPropertyPath()] = $validationErrors->get($counter)->getMessage();
            }

            return [
                'errors' => $errors
            ];
        }
```
