### ISSUE TITLE
JsonEncode options don't work now

### ISSUE THREAD

**Issue by tebaly** [symfony/symfony#49955]
### Symfony version(s) affected

6.2.8

### Description

Symfony\Component\Serializer\Encoder\JsonEncoder::__construct(): Argument #1 ($encodingImpl) must be of type ?Symfony\Component\Serializer\Encoder\JsonEncode, Symfony\Component\Serializer\Debug\TraceableEncoder given, called in ***/var/cache/dev/ContainerPjV32Ta/App_KernelDevDebugContainer.php on line 1415

### How to reproduce

 ```yaml
app.json_encoder:
    class: Symfony\Component\Serializer\Encoder\JsonEncode
    arguments:
      - { "json_encode_options": !php/const JSON_UNESCAPED_UNICODE }

  serializer.encoder.json:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
    arguments:
      - '@app.json_encoder'
```

### Possible Solution

Please check it

### Additional Context

# Before with 5.4.* it works
