### ISSUE TITLE
[Notifier] If all transports fail when using failover transport, retries with messenger fails

### ISSUE THREAD

**Issue by tomme87** [symfony/symfony#50162]
### Symfony version(s) affected

6.2.9

### Description

If I configure multiple transports [using the failover transport](https://symfony.com/doc/current/notifier.html#configure-to-use-failover-or-round-robin-transports) and all the transports fail, the (messenger) message will fail. And then messenger will retry the message (3 times by default), but these retries will always fail, since the transports are marked as dead.

### How to reproduce

```yaml
framework:
    notifier:
        texter_transports:
            main: '%env(DSN_THAT_WILL_ALWAYS_FAIL_1)% || %env(DSN_THAT_WILL_ALWAYS_FAIL_2)%'
```

now when you send a notification that will get handled by Symfony messenger, you can see that it will try the first transport then the second and fail the message. then messenger will retry the message and it will fail without even trying any of the transports.

### Possible Solution

Make `RoundRobinTransport` / `FailoverTransport` implement `ResetInterface` and clear the list of dead transports on reset?
