### ISSUE TITLE
[Intl] IntlExtension - monetary_grouping_separator

### ISSUE THREAD

**Issue by florianhuber81** [symfony/symfony#50171]
### Description

Configuring the number formatter with the thousands_separator has effect on numbers, but not on currencies. According to php docs there is a special constant NumberFormatter::MONETARY_GROUPING_SEPARATOR_SYMBOL for currencies. It would be nice, if we could configure this as well. 

### Example

```
number_format:
     decimals: 2
     decimal_point: '.'
     thousands_separator: "'"
     monetary_grouping_separator: "'"
```
