### ISSUE TITLE
[Routing] `exclude` property configuration not working

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony#50318]
### Symfony version(s) affected

6.2.10

### Description

The `exclude` property (https://symfony.com/doc/current/routing.html#route-groups-and-prefixes) does not seem to be working as expected for me. Below is an example configuration where the ` controllers` definition is still including routes from the API directory, even though they should be excluded. However, these routes do not have API prefixes.

### How to reproduce

```
# config/routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    exclude: ../src/Controller/Api

api:
    prefix:     /api
    name_prefix: api_
    type: attribute
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
```

` php bin/console debug:router`
