### ISSUE TITLE
CSV env doesn't work with framework.enabled_locales

### ISSUE THREAD

**Issue by jdupouyes** [symfony/symfony#50323]
### Symfony version(s) affected

5.4.22

### Description

I cannot use _CSV_ variable (`%env(csv:XXX)%`) with `framework.enabled_locales` option: it crashes my application.
But this same variable work if I use it with my services (I retrieve a string array) and I don't find use restriction in [the documentation](https://symfony.com/doc/5.4/configuration/env_var_processors.html).

### How to reproduce

In the .env file, add the next variable:
```
IHM_LANGUAGES="fr,da,de,en,es,fi,it,nl,pt,ro"
```

In the /config/packages/translation.yaml, add the next configuration:
```yml
framework:
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    enabled_locales: '%env(csv:IHM_LANGUAGES)%'
```
Call any endpoint, you get the next error:
![capture](https://github.com/symfony/symfony/assets/91727581/62727bf2-7fce-43e6-8117-dfb692256d52)
