### ISSUE TITLE
InstanceOf Tagging not working in php config

### ISSUE THREAD

**Issue by amr-degheidy** [symfony/symfony#50329]
### Symfony version(s) affected

service.php.config

### Description

Hello,
currently, i am updating my config from yaml to php

i had this as yaml config

```yaml
# service auto tagging
    _instanceof:
        # default component types
        src\Component\AbstractComponent:
            tags:
                - 'default..component'
```

now after updating to php it goes like this

 ```
$services->instanceof(AbstractComponent::class)
        ->tag('default.component');
```

the problem is tagging not working in php config
and when I run debug:container 

i got **no tags found that match default.component**

### How to reproduce

Hello,
currently, i am updating my config from yaml to php

i had this as yaml config

```yaml
# service auto tagging
    _instanceof:
        # default component types
        src\Component\AbstractComponent:
            tags:
                - 'default..component'
```

now after updating to php it goes like this

 ```
$services->instanceof(AbstractComponent::class)
        ->tag('default.component');
```

the problem is tagging not working in php config
and when I run debug:container 

i got **no tags found that match default.component**
