### ISSUE TITLE
Env var processor examples for arrays don't work

### ISSUE THREAD

**Issue by uncaught** [symfony/symfony#50341]
### Symfony version(s) affected

symfony/dependency-injection 6.2.10

### Description

I'm trying to configure `trusted_headers`/`trusted_hosts` via environment variables, but neither the [`json` nor the `csv` example](https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors) work.

All I get is:

```
Invalid type for path "framework.trusted_hosts.0". Expected one of "bool", "int", "float", "string", but got "array".
```

I've seen https://github.com/symfony/symfony/issues/28599 and https://github.com/symfony/symfony/issues/27683, but I can't find a solution in them.

Am I missing some component or is the documentation wrong?

### How to reproduce

Use one of these in your framework.yaml:

```yaml
parameters:
    env(TRUSTED_HOSTS): '["10.0.0.1", "10.0.0.2"]'
framework:
    trusted_hosts: '%env(json:TRUSTED_HOSTS)%'
```

```yaml
parameters:
    env(TRUSTED_HOSTS): "10.0.0.1,10.0.0.2"
framework:
   trusted_hosts: '%env(csv:TRUSTED_HOSTS)%'
```

### Additional Context

I've also switch to symfony/flex, so I might miss a component, but the installed EnvVarProcessor seems to include the `json`/`csv` handling.

**Comment by nicolas-grekas** [comment]
Did you try this?
```
parameters:
    env(TRUSTED_HOSTS): "10.0.0.1,10.0.0.2"
framework:
   trusted_hosts: '%env(TRUSTED_HOSTS)%'
```

**Comment by uncaught** [comment]
The container build doesn't complain with your example anymore, but the array is not resolved:

```php
var_dump($container->getParameter('kernel.trusted_hosts'));
// array(1) { [0]=> string(17) "10.0.0.1,10.0.0.2" }
```

And the same for the CLI:

```
bin/console debug:container --parameter=kernel.trusted_hosts

 ---------------------- --------------------------
  Parameter              Value
 ---------------------- --------------------------
  kernel.trusted_hosts   ["%env(TRUSTED_HOSTS)%"]
 ---------------------- --------------------------
```

And if I try to configure `trusted_headers` the same way, I still get the error:

```
The value "x-forwarded-for,x-forwarded-host,x-forwarded-proto,x-forwarded-port" is not allowed for path "framework.trusted_headers.0". Permissible values: "forwarded", "x-forwarded-for", "x-forwarded-host
  ", "x-forwarded-proto", "x-forwarded-port", "x-forwarded-prefix"
```

**Comment by nicolas-grekas** [comment]
My example doesn't contain any array.

**Comment by uncaught** [comment]
Okay, so is the documentation wrong and this cannot be done with the `json` or `csv` processor?

**Comment by stof** [comment]
Environment placeholders are not supported for all bundle semantic configuration. It depends whether the bundle processes them or passes them as is to the ContainerBuilder. They are supported only when passed as-is (as their value is not known at compile time so any node processing the value is likely to fail or do weird stuff)

**Comment by nicolas-grekas** [comment]
The documentation is completely wrong yes :)
It's wrong because if uses the env var in a way that doesn't work, and it's also wrong because trusted hosts is expected to be a list of regular expressions. This page is correct:
https://symfony.com/doc/current/reference/configuration/framework.html#trusted-hosts

Can you please a PR to the doc to fix this? I suppose we need to find another example.

**Comment by uncaught** [comment]
I went through our whole project, but I can't find anything useful as an example. I'd have to make one up 😄 

Maybe some arbitrary list of language codes:

```yaml
parameters:
  env(ALLOWED_LANGUAGES): '["en","de","es"]'
  app_allowed_languages: '%env(json:ALLOWED_LANGUAGES)%'
```
