### ISSUE TITLE
Env vars dont resolve in CLI unless they are parameters

### ISSUE THREAD

**Issue by rijnhard** [symfony/symfony#50359]
### Symfony version(s) affected

6.2.10

### Description

This appears to only affect the CLI, because composer install with flex succeeds.

Setting env vars directly in config don't resolve when running 
```sh
./bin/console  debug:container --env-vars
```

So it seems to just vanity, but it does make things difficult, just spent 2 hours trying to fix something that's technically working but I couldn't see that.

### How to reproduce

When placing an env var directly in config:
```yaml
# config/packages/prod/monolog.yaml
monolog:
    handlers:
        sentry:
           type: sentry
           level:  '%env(SENTRY_LOG_LEVEL)%'
           hub_id: Sentry\State\HubInterface
```

```sh
./bin/console  debug:container --env-vars
SENTRY_LOG_LEVEL                n/a             ""
```

But when placing it as a parameter, it resolves. 
`config/services.yaml`
```yaml
parameters:
    mk.sentry.log_level: '%env(SENTRY_LOG_LEVEL)%'
```

```yaml
# config/packages/prod/monolog.yaml
monolog:
    handlers:
        sentry:
           type: sentry
           level: '%mk.sentry.log_level%'
           hub_id: Sentry\State\HubInterface
```

```sh
./bin/console  debug:container --env-vars
SENTRY_LOG_LEVEL                n/a             "DEBUG"
```

### Additional Context

Env var was set in a docker container at a container level.
