### ISSUE TITLE
Monolog\Logger is considered as final, but it's been extended in Symfony\Bridge\Monolog\Logger

### ISSUE THREAD

**Issue by mehrud** [symfony/symfony#50373]
### Symfony version(s) affected

6.1.*

### Description

We are using symfony/monolog-bundle, and since it's integrated with monolog/monolog package via symfony/monolog-bridge, we're facing this warning in our production mode:
```
User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger".
```

### How to reproduce

I'm creating a service in services.yml like this:
```
  my_logger.logger:
    public: public
    class: MyCompany\LoggerBundle\Client\LoggerInterface
    factory: ['MyCompany\LoggerBundle\Client\LoggerFactory', 'make']
    arguments: [ '@monolog.logger' ]
  MyCompany\LoggerBundle\Client\LoggerInterface:
    alias: my_logger.logger
    public: false
```

Then, im creating the my logger instance:
```
<?php

namespace MyCompany\LoggerBundle\Client;

use Psr\Log\LoggerInterface as PsrLoggerInterface;

class LoggerFactory
{
    public static function make(PsrLoggerInterface $loggerInterface)
    {
        return new MyLogger($loggerInterface);
    }
}
```
