### ISSUE TITLE
Environment variable typecast processors return null when used in conjunction with default:

### ISSUE THREAD

**Issue by melkamar** [symfony/symfony#50415]
### Symfony version(s) affected

5.4.22

### Description

When typecast env-var processors (e.g. `bool:`) are used together with `default`, the expression may evaluate to `null`. 

When `OPTIONAL_ENV_VAR` is undefined in the following example, the `default:` processor will assign `null` to the result, and the `bool:` processor will pass it through, even though [the documentation](https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors) states the return type is `bool`. This is a problem when the value is passed as an non-nullable argument to a strictly-typed class.

```yaml
\EnvironmentService:
  arguments:
    $boolFlag: '%env(bool:default::OPTIONAL_ENV_VAR)%'
```

This is not indented and the processor should be strictly non-nullable, as per the initial discussion here https://github.com/symfony/symfony-docs/pull/18283 .

### How to reproduce

Pass the following as an argument to a Symfony service. Do not set the value of `OPTIONAL_ENV_VAR`.

```php
final class EnvironmentService
{
    public function __construct(
        private bool $boolFlag,
    ) {}
}
```

```yaml
# services.yaml
\EnvironmentService:
  arguments:
    $boolFlag: '%env(bool:default::OPTIONAL_ENV_VAR)%'
```

Symfony container build will fail due to `null` being passed as the `$boolFlag` which has to be a `bool`.

**Comment by fancyweb** [comment]
Looking at the code, it looks more intended than a bug.

**Comment by fancyweb** [comment]
I'd like to close this one. `null` is a "special" value that is not cast by casting env var processors. WDYT @nicolas-grekas?

You should use an explicit default fallback param instead of trying to rely on casting `null`:
```yaml
parameters:
    bool_flag_default_value: false

services:
    \EnvironmentService:
        arguments:
            $boolFlag: '%env(bool:default:bool_flag_default_value:OPTIONAL_ENV_VAR)%'
```
Plz close the issue if it works (I didn't test it :sweat_smile:) and if you think it's good enough :smile:
