### ISSUE TITLE
[Messenger] NOGROUP No such key or consumer group 'symfony' in XREADGROUP with GROUP option

### ISSUE THREAD

**Issue by jameskitt616** [symfony/symfony#50422]
Using Symfony 6.2, deploying one or multiple workers via supervisor in my docker container, using redis with symfony messenger

`/etc/supervisor/conf.d/messenger-worker.conf`
```
[program:messenger-consume]
command=php /srv/app/bin/console messenger:consume async --time-limit=3600
user=www-data
numprocs=20
startsecs=0
autostart=true
autorestart=true
startretries=10
stopwaitsecs=5
stopsignal=INT
process_name=%(program_name)s_%(process_num)02d
environment=MESSENGER_CONSUMER_NAME=messenger-consume_%(process_num)02d
```

`messenger.yaml`
```
framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%?stream=transcode_queue"
                options:
                    stream: transcode_queue
                    consumer: '%env(MESSENGER_CONSUMER_NAME)%'
```

`.env`
```
MESSENGER_CONSUMER_NAME=00
MESSENGER_TRANSPORT_DSN=redis://message_transport:6379/messages/symfony/messenger-consume_%env(MESSENGER_CONSUMER_NAME)%)%?auto_setup=true
```

When building the prod docker container it crashes when i deploy it on my server, if deploying on my workstation, it works (Fedora Server vs Fedora Workstation). I couldnt figure out why. Symfony `APP_ENV` do not seem to have influence on this behaviour.
If you need me to do additionally testing, let me know.

_Originally posted by @jameskitt616 in https://github.com/symfony/symfony/issues/45489#issuecomment-1557774064_
