### ISSUE TITLE
Check for unused routing requirements

### ISSUE THREAD

**Issue by alamirault** [symfony/symfony#50461]
### Description

It would be great if we can detect that parameter requirement does not match path parameters.

```yaml
foo_url:
  path:      /foo-url/{clientId}
  methods:   [ GET ]
  defaults:  { _controller: App\Controller\FooController }
  requirements:
    client: '\d+' // <------------- client does not exist, good name is clientId
```

In this case `client` parameter does not exist, so a deprecation or a warning will avoid validation error. 

WDYT ?
