### ISSUE TITLE
The default MonologBundle configuration using STDERR leads to `console` handler not making any sense

### ISSUE THREAD

**Issue by someniatko** [symfony/symfony#50638]
### Symfony version(s) affected

I use 6.3.x, but it might affect earlier versions

### Description

This is not a bug per se, but rather a somewhat deep internal design issue IMO.

Let's say we have this recommended default configuration, 12-factor-ish and stuff, where we write nothing into an internal `var` directory of the project, but output our logs to the STDERR instead.

```yaml
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
```

The issue is however now hidden behind the fact that by default no logs will be output due to the `fingers_crossed` handler who is preventing logs to be output unless an ERROR-leveled message has appeared. Let's remove this handler from the stack. This might be a feasible idea to monitor not only errors, but e.g. warnings or even infos on production. For these illustration purposes we'll watch all messages including DEBUG. I have also changed the location of `deprecation` handler to also do it the recommended "12-factor" way. The `console` handler will use a `line` formatter to visually differentiate its messages from JSON-formatted messages of other handlers:

```yaml
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
```

Now let's launch a symfony command. We can just launch bare `php bin/console` which lists all available commands. And what do we see? Stuff like this at the start of the output:

```
[2023-06-12T15:02:27.413070+00:00] event.DEBUG: Notified event "{event}" to listener "{listener}". {"event":"console.command","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand"} []
{"message":"Notified event \"console.command\" to listener \"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand\".","context":{"event":"console.command","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand"},"level":100,"level_name":"DEBUG","channel":"event","datetime":"2023-06-12T15:02:27.413070+00:00","extra":{}}
```

This particular message clearly comes from the `main` handler and not the `console` handler. Notice that if we launch the command with `-vvv` flag, `php bin/console -vvv`, this message will not appear twice, because `console` handler is not used at this point - the ConsoleHandler was not initialized yet and thus it skips the records coming to it.

In my particular case I also use a thirdparty bundle which has some deprecations to it, and if I launch the command like this: `php bin/console`, I will see a single deprecation message:

```
{"message":"User Deprecated: Method \"ProxyManager\\Factory\\RemoteObject\\AdapterInterface::call()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Ecotone\\Messaging\\Config\\EcotoneRemoteAdapter\" now to avoid errors or add an explicit @return annotation to suppress this message.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Method \"ProxyManager\\Factory\\RemoteObject\\AdapterInterface::call()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Ecotone\\Messaging\\Config\\EcotoneRemoteAdapter\" now to avoid errors or add an explicit @return annotation to suppress this message.","code":0,"file":"/var/app/vendor/symfony/error-handler/DebugClassLoader.php:337"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2023-06-12T15:20:58.844048+00:00","extra":{}}
```

However, if I launch it with the `-vvv` flag: `php bin/console -vvv`, the message will be duplicated, because at this point `console` handler also works!

```
[2023-06-12T15:25:43.410389+00:00] deprecation.INFO: User Deprecated: Method "ProxyManager\Factory\RemoteObject\AdapterInterface::call()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Ecotone\Messaging\Config\EcotoneRemoteAdapter" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"ProxyManager\\Factory\\RemoteObject\\AdapterInterface::call()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Ecotone\\Messaging\\Config\\EcotoneRemoteAdapter\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/app/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
{"message":"User Deprecated: Method \"ProxyManager\\Factory\\RemoteObject\\AdapterInterface::call()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Ecotone\\Messaging\\Config\\EcotoneRemoteAdapter\" now to avoid errors or add an explicit @return annotation to suppress this message.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Method \"ProxyManager\\Factory\\RemoteObject\\AdapterInterface::call()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Ecotone\\Messaging\\Config\\EcotoneRemoteAdapter\" now to avoid errors or add an explicit @return annotation to suppress this message.","code":0,"file":"/var/app/vendor/symfony/error-handler/DebugClassLoader.php:337"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2023-06-12T15:25:43.410389+00:00","extra":{}}
```

Also, at the end of the output there are again some logs greeting us:
```
{"message":"Notified event \"console.terminate\" to listener \"Symfony\\Component\\Console\\EventListener\\ErrorListener::onConsoleTerminate\".","context":{"event":"console.terminate","listener":"Symfony\\Component\\Console\\EventListener\\ErrorListener::onConsoleTerminate"},"level":100,"level_name":"DEBUG","channel":"event","datetime":"2023-06-12T15:25:43.421566+00:00","extra":{}}
{"message":"Notified event \"console.terminate\" to listener \"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onTerminate\".","context":{"event":"console.terminate","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onTerminate"},"level":100,"level_name":"DEBUG","channel":"event","datetime":"2023-06-12T15:25:43.421657+00:00","extra":{}}
```

We can partially mitigate the problem by settings `console`'s handler `priority` to be higher then other handlers (by the way this `priority` property isn't documented anywhere, even in the respective Configuration class of the MonologBundle!), and then setting it's `bubble` property to false.

But still we get the log messages (in my particular case, deprecations) coming from the `main` handler:

```
{"message":"User Deprecated: Method \"ProxyManager\\Factory\\RemoteObject\\AdapterInterface::call()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Ecotone\\Messaging\\Config\\EcotoneRemoteAdapter\" now to avoid errors or add an explicit @return annotation to suppress this message.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Method \"ProxyManager\\Factory\\RemoteObject\\AdapterInterface::call()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Ecotone\\Messaging\\Config\\EcotoneRemoteAdapter\" now to avoid errors or add an explicit @return annotation to suppress this message.","code":0,"file":"/var/app/vendor/symfony/error-handler/DebugClassLoader.php:337"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2023-06-12T15:20:58.844048+00:00","extra":{}}
```

However, if we set the appropriate verbosity: `php bin/console -vv` or `-vvv`, now the `console` handler comes into play and takes responsibility of the message, and will render it as a line instead of JSON.

```
[2023-06-12T15:25:43.410389+00:00] deprecation.INFO: User Deprecated: Method "ProxyManager\Factory\RemoteObject\AdapterInterface::call()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Ecotone\Messaging\Config\EcotoneRemoteAdapter" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"ProxyManager\\Factory\\RemoteObject\\AdapterInterface::call()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Ecotone\\Messaging\\Config\\EcotoneRemoteAdapter\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/app/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
```

So, depending on the verbosity level given to a console command, the log message will be rendered either by the `console` handler, or by the `main` handler, **but it will be rendered regardless**. This situation actually takes away control of log level verbosity from the user of the console command - whatever he provides, `-v`, `-vv`, `-vvv` or nothing - does not matter, the log will be shown to him regardless, if we use this `php://stderr` recommended path for the `main` handler logs.

### How to reproduce

Basically, follow the steps from the description.

### Possible Solution

First, in my opinion, if `bubble: false` is used, I think the `console` should not forward log messages to other handlers, even if the log message's verbosity level does not match the given verbosity by the user of a console command. Or at least there should be an option to configure that. As a command line user, I want to have full control over the verbosity of the log messages. This should be easy to "fix", or "alter" if you wish.

Second, there should be some solution of how not to output messages from other handlers if the ConsoleHandler is not yet initialized with a OutputInterface (basically, if the ConsoleHandler does not yet know that we are in the context of a console command). Basically I would like to strictly separate my handlers for HTTP API runtime and for CLI runtime somehow. This might be harder and deeper to solve, and may be not needed. Maybe ConsoleHandler should buffer messages until it's initialized with an OutputInterface, dunno.
