### ISSUE TITLE
[Symfony/Mailer] mailer.envelope.recipients configuration does not work with SMTP

### ISSUE THREAD

**Issue by nbennett25** [symfony/symfony#50732]
### Symfony version(s) affected

6.2.10

### Description

Similarly to https://github.com/symfony/symfony/issues/41149, I'm seeing the same behavior (`recipients` not being recognized) using STMP

### How to reproduce

Mailer config:

```
config/packages/mailer.yaml:

when@dev:
    framework:
        mailer:
            envelope:
                sender: 'sender@example.com'
                recipients: ['recipients@example.com']
```

Controller class:
```

// src/Controller/MailerController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;

class MailerController extends AbstractController
{
    #[Route('/email')]
    public function sendEmail(MailerInterface $mailer): Response
    {
        $email = (new Email())
            ->to('actual-recipient@example.com')
            ->subject('Time for Symfony Mailer!')
            ->text('Sending emails is fun again!')
            ->html('<p>See Twig integration for better HTML integration!</p>');

        $mailer->send($email);

        dump('sent');die;

        // ...
    }
}
```

Email headers received after hitting `/email` url in browser:

```
To: actual-recipient@example.com
Subject: Time for Symfony Mailer!
Sender: sender@example.com
```
