### ISSUE TITLE
[Security] access_control bypassed when url does not matches any firewall pattern

### ISSUE THREAD

**Issue by alcalyn** [symfony/symfony#50927]
### Symfony version(s) affected

5.4, 6

### Description

When configuring firewalls like this:

``` yml
    firewalls:
        main:
            pattern: ^/api/.+$
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
```

If I forgot to add a firewall for urls other than `/api/`, the `access_control` part is simply not used, and the `/admin/` routes are not secured.

It seems to be unexpected, and silently crash in the debug profiler.

Although it appears obvious is this simple exemple we can fix it by adding a catch-all firewall, it is risky on large projects, with more firewalls, access_control with different criteria (roles, trusted ips...)

### How to reproduce

I can reproduce on Symfony 5.4 and 6.

``` bash
symfony new project --version=5.4
cd project/

composer require symfony/security-bundle
composer require --dev symfony/profiler-pack
```

Let's add 2 api routes, and 1 admin route:

`src/Controller/AppController.php`
``` php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class AppController extends AbstractController
{
    #[Route('/api/public', name: 'app_api_public')]
    public function public(): JsonResponse
    {
        return $this->json(['message' => 'hello public']);
    }

    #[Route('/api/private', name: 'app_api_private')]
    public function private(): JsonResponse
    {
        return $this->json(['message' => 'hello private']);
    }

    #[Route('/admin', name: 'app_admin')]
    public function admin(): JsonResponse
    {
        return $this->json(['message' => 'private admin']);
    }
}
```

Now we will secure the api routes: by default deny all, and accept only the ones we want. Also add `/admin` route for users with admin role:

`security.yml`
``` yml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/api/.+$
            lazy: true
            provider: users_in_memory

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:

        # admin
        - { path: ^/admin, roles: ROLE_ADMIN }

        # allowed api routes
        - { path: ^/api/public, roles: PUBLIC_ACCESS }

        # deny all others
        - { path: .*, roles: ACCESS_DENIED }
```

For symfony 5 only, just add this to fix php attributes:

`config/routes/annotations.yaml`
``` yml
controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
```

Then try:

- <http://127.0.0.1:8000/api/public> I can access, works as expected
- <http://127.0.0.1:8000/api/private> 401, works as expected
- <http://127.0.0.1:8000/admin> I can access, but I expected a 401...

After the last try, check in the debug profiler, the `/admin` request, menu "Security":

- On Symfony 5 it crashes, we get `Impossible to access an attribute ("security_enabled") on a null variable.`
- On Symfony 6, we can go on Security menu, navigate through tab, but the "Firewall" one is empty.

### Possible Solution

- Always use `access_control`
- Or find a way to make it obvious when an access_control rule won't be used because no matching firewall.

I think not using security for urls not behind firewall is expected, but it may be not obvious when configure `access_control` as a whitelist, like blocking all urls except only the ones we want.

So always using access_control, even for urls not behind firewall is maybe not a solution, but this case should be handled better, more obvious, instead of silently crash in debug profiler.
