### ISSUE TITLE
[Cache] Namespace changes when changing the adapter of a pool

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#51059]
### Symfony version(s) affected

6.3.1

### Description

We needed to migrate a lot of caches from one Redis server to another and tried to use the ChainAdapter.

```yaml
# config/packages/framework.yaml
framework:
    cache:
        pools:
            cache.mycache:
                adapter: cache.adapter.redis
                provider: old_redis_connection
```

```yaml
framework:
    cache:
        pools:
            cache.mycache:
                adapters: 
                    - { name: cache.adapter.redis, provider: new_redis_connection }
                    - { name: cache.adapter.redis, provider: old_redis_connection }
```

We thought this would work great. But to our surprise, the namespace of our pool changed because the adapter changed from RedisAdapter to ChainAdapter.

This is caused by 
https://github.com/symfony/symfony/blob/bd04cdaf6fc479a6f5602b862c190940b38a633e/src/Symfony/Component/Cache/DependencyInjection/CachePoolPass.php#L71-L73

This caused our all our caches to miss, and basically making our effort in safely migrating for nothing. 

### How to reproduce

See above

### Possible Solution

1. Do not change the namespace when the adapter changes
2. Allow configuring the namespace using the framework cache configuration (I know it's possible to manually register cache pools using DI tags, but that's not as convenient as using the config).
