### ISSUE TITLE
[Cache] Redis::select(): Argument #1 ($dbindex) must be of type int, string given

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#51212]
### Symfony version(s) affected

6.3.1

### Description

Passing a cache DSN like this:

```
redis://redis.redis-cluster?dbindex=2
```

I get

```json
{
    "message":"Redis::select(): Argument #1 ($dbindex) must be of type int, string given",
    "code":0,
    "file":"/app/vendor/symfony/cache/Traits/RedisTrait.php:260"
}
```

Syntax

```
redis://redis.redis-cluster/2
```

seems to work correctly.

### How to reproduce

Set up like this

```yaml
services:
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            $redis: "@cache.default_redis_provider"

framework:
    cache:
        default_redis_provider: "%env(file:CACHE_DSN_FILE)%"
```

provided if Redis being used for sessions is relevant.
