### ISSUE TITLE
More precise Translation Provider Pull Command

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#51356]
### Description

**TL;DR**

`translation:pull` command for translation providers need a --delete-missing parameter, separated from the --force parameter (which is currently doing both a --force and a --delete-missing job)

This is usefull if you want to keep local new keys not pushed yet, but want to get new values of already existing keys from the distant provider (be aware that currently this is impossible).

---

With translation providers, you can push and pull translations towards a specific provider, or even your own one. This is an incredible feature, but something is missing.

Indeed, in order to push translations, you have a command `translation:push`, which can be used like this : 

```
php bin/console translation:push yourcustomprovider
```

Two parameters are *very* usefull in order to manage properly the way pushed translations will overwrite or not the already existing translations : 

```
--delete-missing : Will delete the translations present in the distant translation provider which are not
 in the current payload of translations being pushed (but this will not overwrite the existing ones)

--force : Will overwrite already existing translations
```

This is very usefull and everybody is happy 👍 

*Code of the translation:push command :* [link here](https://github.com/symfony/symfony/blob/d6d233b8ee93f1baa4d2e24232882124b28ebe2b/src/Symfony/Component/Translation/Command/TranslationPushCommand.php#L33)

---

The problem in my opinion is more on the `translation:pull` command. This command will pull translations from a given provider depending on the queried locales and domains. For example : 

```
php bin/console translation:pull yourcustomprovider --locales fr en de --domains messages errors forms
```

But here, there is only one parameter that you can use to customise the way pulled translations will interract with your local translations : 

```
--force : Will overwrite already existing translations AND remove local translations which are not in the payload sent by the provider
```

*Code for the translation:pull command :* [link here](https://github.com/symfony/symfony/blob/d6d233b8ee93f1baa4d2e24232882124b28ebe2b/src/Symfony/Component/Translation/Command/TranslationPullCommand.php#L33)

---

Here is the problem I am facing : 

With the pull command, you can push translations in all these differents usecases : 
- Just append new translations
- Append new translations and overwrite existing ones
- Append new translations and delete the ones not in the current payload
- Everything described above at the same time
- (There is missing something which would not append new keys but I think this is pretty pointless)

With the pull command, you can pull translations in all these differents usecases :
- Just append new translations to your local ones
- Append new translations, overwrite AND remove already existing ones (with --force)
- (Missing a pointless --no-append parameter)

But as you can see, you cannot chose to either just remove missing, or just overwrite (the most important one in my eyes).

For me, the fact that you cannot choose to overwrite local translations AND at the same time keep some translations you may not have push yet is really not something good. Apparently, the --force is doing also the job of a missing --delete-missing parameter, which shouldn't be the case.

So the suggestion is the following :

**Add a --delete-missing parameter for the translation:pull command, and remove this part from the --force parameter.**

### Example

I have the following translations in my local files : 

**Local files**
```yaml
user: Utilisateur
admin: Old value which will be changed by the provider
new.local.key: A new translation that I didn't push yet but I want to keep
```

In my provider, I have the following translations (in a mariadb but let's assume it's yaml) : 

**Distant provider**
```yaml
user: Utilisateur
admin: New value to change in the local files
new.distant.key: New key added in the distant provider that I want to append to the local files
```

When I use the translation:pull command, without the --force parameter, I will keep my new unpushed key but I will not get the new value from the distant provider : 

```yaml
user: Utilisateur
admin: Old value which will be changed by the provider
new.local.key: A new translation that I didn't push yet but I want to keep
new.distant.key: New key added in the distant provider that I want to append to the local files
```

When I use the translation:pull command with the --force parameter, I will get the new value, but I will lose my new unpushed key : 

```yaml
user: Utilisateur
admin: New value to change in the local files
new.distant.key: New key added in the distant provider that I want to append to the local files
```

**There is no way to keep the local new keys AND get the new values from already existing keys.**
