### ISSUE TITLE
[Messenger]: failed message goes to every failure_transport

### ISSUE THREAD

**Issue by gnumoksha** [symfony/symfony#51449]
### Symfony version(s) affected

6.3

### Description

I have three transports, each one has its own failure_transport. When a message fails, it goes to the three transports instead to only the configured one.

### How to reproduce

Using the following configuration, send a message to transport where the message handler will fail.

messenger.yaml
```yaml
#
# Notes:
#   - Execute "messenger:setup-transports" after changing this file.
#

framework:
    messenger:
        # after retrying, messages will be sent to the "failed" transport
        #failure_transport: failed_event

        transports:
            # https://symfony.com/doc/current/messenger.html
            event_async:
                dsn: '%env(MESSENGER_TRANSPORT_ASYNC_EVENT_DSN)%'
                failure_transport: failed_event
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 5
                    max_delay: 0
                # https://symfony.com/doc/current/messenger.html#amqp-transport
                options:
                    connection_name: cdp-events
                    connect_timeout: 30
                    read_timeout: 30
                    write_timeout: 30
                    vhost: cdp
                    exchange:
                        name: cdp-events
                        type: topic
                    queues:
                        cdp-events:
                            arguments:
                                x-queue-type: quorum
                                #x-dead-letter-exchange: cdp-events-dlx
            failed_event:
                dsn: '%env(MESSENGER_TRANSPORT_ASYNC_EVENT_DSN)%'
                options:
                    vhost: cdp
                    queues:
                        cdp-events-dlx:
                            arguments:
                                x-queue-type: quorum

            job_async:
                dsn: '%env(MESSENGER_TRANSPORT_ASYNC_JOB_DSN)%'
                failure_transport: failed_job
                retry_strategy:
                    max_retries: 1
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 5
                    max_delay: 0
                # https://symfony.com/doc/current/messenger.html#amqp-transport
                options:
                    connection_name: cdp-jobs
                    connect_timeout: 30
                    read_timeout: 30
                    write_timeout: 30
                    vhost: cdp
                    exchange:
                        name: cdp-jobs
                        type: topic
                    queues:
                        cdp-jobs:
                            arguments:
                                x-queue-type: quorum
                                #x-dead-letter-exchange: cdp-jobs-dlx
            failed_job:
                dsn: '%env(MESSENGER_TRANSPORT_ASYNC_JOB_DSN)%'
                options:
                    vhost: cdp
                    queues:
                        cdp-jobs-dlx:
                            arguments:
                                x-queue-type: quorum

            interchangeable_event:
                dsn: '%env(MESSENGER_TRANSPORT_INTERCHANGEABLE_EVENT_DSN)%'
                failure_transport: failed_interchangeable_event
                serializer: messenger.transport.cdp_json_serializer
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 100
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                options:
                    vhost: cdp
                    connection_name: cdp-events-interchangeable
                    connect_timeout: 30
                    read_timeout: 30
                    write_timeout: 30
                    exchange:
                        name: cdp-events-interchangeable
                        type: topic
                    queues:
                        cdp-events-interchangeable:
                            arguments:
                                x-queue-type: quorum
                                #x-dead-letter-exchange: cdp-events-interchangeable-dlx

            failed_interchangeable_event:
                dsn: '%env(MESSENGER_TRANSPORT_INTERCHANGEABLE_EVENT_DSN)%'
                options:
                    vhost: cdp
                    queues:
                        cdp-events-interchangeable-dlx:
                            arguments:
                                x-queue-type: quorum

        routing:
            # Route your messages to the transports
            'App\Libs\Messaging\Message\Event\AsyncEvent': event_async
            'App\Libs\Messaging\Message\Job\AsyncJob': job_async
            'App\Libs\Messaging\Message\Event\InterchangeableEvent': interchangeable_event

        # https://symfony.com/doc/current/messenger.html#serializing-messages
        serializer:
            # The Symfony Serializer can not serialize/unserialize all kinds of data out-of-the-box,
            # so, I will not enable it as the default serializer.
            #default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                event_async: 'in-memory://'
                failed_event: 'in-memory://'
                job_async: 'in-memory://'
                failed_job: 'in-memory://'
                interchangeable_event: 'in-memory://'
                failed_interchangeable_event: 'in-memory://'
```

env vars:
```
MESSENGER_TRANSPORT_ASYNC_EVENT_DSN=amqp://cdp:cdp@rabbitmq:5672/%2f
MESSENGER_TRANSPORT_ASYNC_JOB_DSN=amqp://cdp:cdp@rabbitmq:5672/%2f
MESSENGER_TRANSPORT_INTERCHANGEABLE_EVENT_DSN=amqp://cdp:cdp@rabbitmq:5672/%2f
```

### Additional Context

![image](https://github.com/symfony/symfony/assets/696797/a3d2788c-3aa2-4e83-a87a-136a00a7f224)

**Comment by krciga22** [comment]
Hi @gnumoksha, I've taken a look into this and was able to recreate the same issue using your configuration. After a lot of digging, I found that the default exchange name and type used by the messenger component are `messages` and [fanout](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-fanout). Since your 3 failure transports don't specify any exchange details explicitly, all three are using the default exchange name and type. You can actually see this by reviewing the exchanges and bindings in RabbitMQ after executing `messenger:setup-transports`:

`rabbitmqadmin list exchanges`
![image](https://github.com/symfony/symfony/assets/1588202/52b5597f-e721-4dc9-b72b-31a4a5f2c3e0)

`rabbitmqadmin list bindings`
![image](https://github.com/symfony/symfony/assets/1588202/91907c5b-056c-4f2c-96e0-6813227737d9)

With this setup, when your message fails and is sent via one of the three failure transports, RabbitMQ receives it and fans it out to all 3 failure queues.

To fix this, one solution that I've tried which works is to specify an exchange for each of the three failure transports and set the exchange type to `direct` or `topic` depending on your need. Also, make sure to set `binding_keys` correctly for the failure queues (see example below).

```yaml
failed_event:
    dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
    options:
        exchange:
            name: cdp-failures
            type: direct
        queues:
            cdp-events-dlx:
                arguments:
                    x-queue-type: quorum
                binding_keys: [cdp-events]
```

This should result in the following exchange and bindings in RabbitMQ:

`rabbitmqadmin list exchanges`
![image](https://github.com/symfony/symfony/assets/1588202/e6a9134f-af4a-41dd-b12b-7c8478999ea5)

`rabbitmqadmin list bindings`
![image](https://github.com/symfony/symfony/assets/1588202/fa84fdf4-7b71-401f-81dd-2ec1859105b1)
