### ISSUE TITLE
[Translation] extract-option 'as-tree' creates empty property keys in Yaml

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/symfony#51536]
### Symfony version(s) affected

5.2.0 and higher

### Description

When generating yaml translation files and using the `--as-tree=3` option on the `translation:extract` command, the Translation component generates a tree of translatable strings. Therefore, it [explodes the translatable string by the `.`](https://github.com/symfony/symfony/blob/73a6b4b8ad315d294fe18c03012019694863daa9/src/Symfony/Component/Translation/Util/ArrayConverter.php#L39), which can result in odd behavior when the user is not using translation keys, but full sentences. For example, a lot of validation error messages end in with a dot, resulting in yaml like this:

```yaml
'This value should be false':
    '': 'This value should be false.'
'This value should be true':
    '': 'This value should be true.'
'This value should be of type {{ type }}':
    '': 'This value should be of type {{ type }}.'
```

While it's impossible to prevent this behavior when dots are in the middle of a strings, I think dots at the start and end of a translation key are supposed to be trimmed.

### How to reproduce

`symfony create --webapp` and then `bin/console translation:extract --force --format=yaml --as-tree=3 en`

**Comment by stof** [comment]
> While it's impossible to prevent this behavior when dots are in the middle of a strings, I think dots at the start and end of a translation key are supposed to be trimmed.

they should not be trimmed (as that would change the translation key). but we could indeed decide to merge that back to avoid the split.

**Comment by javleds** [comment]
Hi, I am interested into solve this issue, but before proposing any solution, I see there are 2 possible approaches to use transaltions:
1. The dot notation.
```yml
# Exmample:
symfony:
    is:
        # id is symfony.is.great
        great: Symfony is great
        # id is symfony.is.amazing
        amazing: Symfony is amazing
another.good.example: Another good example
``` 

2. The explicit natural language.
```yml
# Example
'Symfony is great': Symfony is great
'Another good example': Another good example
```

Is it possible to have dot notation using spaces?
```yml
# Something like
'Symfony is great':
        'And developer fieldly': Symfony is great and, developer friendly
'Another good example.using spaces': Another good example using spaces
```

Based on the answer I think we can define any proposal, what I have in mind is:
- If combining spaces and dots is allowed, solution proposed by @stof on merging arrays sounds good.
- Otherwhise, we may prevent all processing if the string contains spaces, and just return the `[$key => $value]` in the `ArrayConverter::expandToTree` method.
