### ISSUE TITLE
Messenger wildcard routing doesn't work

### ISSUE THREAD

**Issue by speller** [symfony/symfony#51580]
### Symfony version(s) affected

6.2.7

### Description

I'm trying to use wildcards to route all messages from a specific namespace to the same transport:

```yml
framework:
    messenger:
        routing:
            'App\Admin\Application\Message\Foo\*': foo
```

But this doesn't work, the container compilation fails with the following error:

```none
$ bin/console

In FrameworkExtension.php line 2158:

  Invalid Messenger routing configuration: class or interface "App\Admin\Application\Message\Foo\*" not found.
```

At the same time, the documentation for v 6.2 clearly states:

> You may use a partial PHP namespace like 'App\Message\*' to match all the messages within the matching namespace.

### How to reproduce

Try using the wildcard as a part of the FQCN.
