### ISSUE TITLE
[Mailer] Email are sent to initial recipients even if `framework.mailer.envelope.recipients` is configured

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony#51590]
### Symfony version(s) affected

5.4

### Description

Config :
```yaml
framework:
    mailer:
        dsn: 'sendinblue+smtp://xxxxxxx....'
        envelope:
            recipients: ['x@y.com']
```

With this config email are send to initial recipients AND "x@y.com" .

### How to reproduce

symfony/mailer : 5.4.22
symfony/sendinblue-mailer : 5.4.28
