### ISSUE TITLE
In testing environment (mock_file), calling repositories throw ini_set(): Session ini settings cannot be changed after headers have already been sent

### ISSUE THREAD

**Issue by Didadams** [symfony/symfony#51600]
### Symfony version(s) affected

6.3.4

### Description

Running PhpUnit 9.6.11 with Symfony 6.3.4 we have an error when calling doctrine

class ClaimControllerTest extends WebTestCase

In my function :         

$expenses = static::getContainer()->get(TestRepository::class)->findAll();

throws : 

```
ini_set(): Session ini settings cannot be changed after headers have already been sent

/data/src/vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php:49
/data/src/var/cache/test/ContainerPajbQeb/getSession_Handler_NativeFileService.php:24
/data/src/var/cache/test/ContainerPajbQeb/App_KernelTestDebugContainer.php:940
/data/src/vendor/symfony/dependency-injection/Container.php:408
/data/src/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40
/data/src/var/cache/test/ContainerPajbQeb/getApp_Session_HandlerService.php:26
/data/src/var/cache/test/ContainerPajbQeb/App_KernelTestDebugContainer.php:940
/data/src/var/cache/test/ContainerPajbQeb/getDoctrine_Orm_Listeners_PdoSessionHandlerSchemaListenerService.php:23
/data/src/var/cache/test/ContainerPajbQeb/App_KernelTestDebugContainer.php:940
/data/src/vendor/symfony/dependency-injection/Container.php:408
/data/src/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40
/data/src/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:181
/data/src/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:92
/data/src/vendor/gedmo/doctrine-extensions/src/SoftDeleteable/Filter/SoftDeleteableFilter.php:121
/data/src/vendor/gedmo/doctrine-extensions/src/SoftDeleteable/Filter/SoftDeleteableFilter.php:63
/data/src/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:2130
/data/src/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:1129
/data/src/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:937
/data/src/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:225
/data/src/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:207
/data/src/tests/Controller/Activity/ControllerTest.php:96
```
Who breaks all our tests with DB calls. 
Other tests passes.

Framework config for test : 
```
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```

Not reproducible in Symfony 6.2.x 
Not reproducible in dev environment (outside phpUnit) calling controllers.

### How to reproduce

In any PhpUnit TestCases when calling repositories through the container try to write into the session when the header is already sent. 

> $expenses = static::getContainer()->get(TestRepository::class)->findAll();

I didn't manage to reproduce it outside PhpUnit nor get the process who is sending the header before unfortunately.

It's happening in our CI/CD test env too so it's not a file permission issue on my dev environment.

**Comment by vasilvestre** [comment]
Same issue here, coming from APIP CI tests. Have you found a workaround @Didadams ?

**Comment by jsunier** [comment]
I had the same issue, but also when running PHPUnit on my local machine (Windows WSL2 / PHP 8.1 / Symfony 6.3.6 / PHPUnit 9.6.13).

But i found a workaround !

I have this configuration in my `config/packages/framework.yaml` :
```yaml
framework:
    # ...

    session:
        handler_id: 'session.handler.native_file'
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        storage_factory_id: session.storage.factory.native
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```

And i changed it to this

```diff
framework:
    # ...

    session:
        handler_id: 'session.handler.native_file'
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        storage_factory_id: session.storage.factory.native
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

when@test:
    framework:
        test: true
        session:
+           handler_id: null
            storage_factory_id: session.storage.factory.mock_file
```

And now it works like a charm !

But i'm not sure why it fixes the problem...
