### ISSUE TITLE
[Console]  strlen(): Argument #1 ($string) must be of type string, array given 

### ISSUE THREAD

**Issue by issamkhadiri1989** [symfony/symfony#51636]
### Symfony version(s) affected

6.3.4

### Description

Hello, 

When using a tag with some additional attribute of type array, I got error 

```
[TypeError]
strlen(): Argument #1 ($string) must be of type string, array given
```

### How to reproduce

With the config bellow

```
  App\Mail\SmtpTransport:
    arguments: ['%kernel.project_dir%']
    tags:
      - { name: 'app.mail_transport', alias: 'smtp'}

  App\Mail\SendmailTransport:
    tags:
      - { name: 'app.mail_transport', alias: ['sendmail', 'mail'] }
```

Try to debug the tag using the `php bin/console debug:container --tag=app.mail_transport` 

### Possible Solution

In the file [https://github.com/symfony/framework-bundle/blob/6.3/Console/Descriptor/TextDescriptor.php#L212](https://github.com/symfony/framework-bundle/blob/6.3/Console/Descriptor/TextDescriptor.php#L212)

first need to check whether the `$value` is a type of array.
