### ISSUE TITLE
[Asset] applyVersion getting wrong path

### ISSUE THREAD

**Issue by yassinefikri** [symfony/symfony#51875]
### Symfony version(s) affected

6.3

### Description

When using webpack-encore, and json-manifest-path along side with asset packages,
the applyVersion method of VersionStrategyInterface (in this case it's JsonManifestVersionStrategy) not receiving full path, but only the filename instead when using packages,

### How to reproduce

in configuration :
```
assets:
    json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    strict_mode: true
    packages:
        favicon:
            base_path: 'build/images/favicons/'
```

in twig:
`<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('icon-16.png', 'favicon') }}">`

example of manifest-file entry: 
`"build/images/favicons/icon-16.png": "/build/images/favicons/icon-16.png",`

expected html output:
`<link rel="icon" type="image/png" sizes="16x16" href="/build/images/favicons/icon-16.png">`
actual:
An exception has been thrown during the rendering of a template ("Asset "icon-16.png" not found in manifest "/var/www/html/public/build/manifest.json". Did you mean one of these? "build/images/favicons/icon-16.png".").

### Possible Solution

concat package basepath to path
```diff
    public function getUrl(string $path): string
    {
        if ($this->isAbsoluteUrl($path)) {
            return $path;
        }


+       if ($this->versionStrategy instanceof JsonManifestVersionStrategy) {
+           $basePath = $this->getBasePath();
+           // Only prepend basePath when using packages
+           if ($basePath !== '/') {
+               $basePath = substr($basePath,1);
+               $path = $basePath.$path;
+           }
+       }

        return $this->versionStrategy->applyVersion($path);
    }
```
