### ISSUE TITLE
Environment variables "bool:SYMFONY_PROFILER" are never used

### ISSUE THREAD

**Issue by vencakrecl** [symfony/symfony#52110]
### Symfony version(s) affected

6.3.5

### Description

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\EnvParameterException: Environment variables "bool:SYMFONY_PROFILER" are never used. Please, check your container's configuration. in /var/www/html/vendor/symfony/dependency-injection/Dumper/PhpDumper.php on line 417

### How to reproduce

```yaml
when@dev:
  parameters:
    env(SYMFONY_PROFILER): false

  framework:
    profiler:
      enabled: '%env(bool:SYMFONY_PROFILER)%'
```
