### ISSUE TITLE
Unable to find custom template for UX components with <twig:component> syntax

### ISSUE THREAD

**Issue by arnolem** [symfony/symfony#52154]
### Symfony version(s) affected

6.3

### Description

When i define a custom twig template of a component, it's ok where I called the component with the classic syntax but it's not possible to find the template with the new <twig:component> syntax.

### How to reproduce

```bash
composer req symfony/ux-twig-component
```
(Version v2.12.0)

1- Configure a new folder for Twig
```yaml
# config/packages/twig.yaml
twig:
    paths:
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/components'
```
2- Configure PHP classes autoload (❗dump-autoload)
```json
    "autoload": {
        "psr-4": {
            "App\\": "src/",
            "Component\\": "components/"
        }
    },
```
and
```yaml
services:

    Component\:
        resource: '../components/'
```
3- Create a folder `components/Button`
4- Create a PHP file
```php
<?php
namespace Component\Button;

use Symfony\UX\TwigComponent\Attribute\AsTwigComponent;

#[AsTwigComponent('button', template: 'button.twig')]
class ButtonComponent { }
```
5- Create a Twig file `components/button.twig`
```twig
<button>Wixiweb</button>
```

---

You can use this button like this : 
`{{ component('button') }}`

But you cannot use this button like this : 
`<twig:button></twig:button>`

> Unable to find template "button.twig" (looked into: /templates, /components, /templates) in [home/index.twig at line 13]

**Comment by smnandre** [comment]
What version of twig components are you using ?

**Comment by arnolem** [comment]
v2.12.0

**Comment by smnandre** [comment]
I'll try tonight to reproduce / fix .. 

In the meantine, could you re-open your issue in the [symfony ux](https://github.com/symfony/ux) repository ? (twig component related issues are handled there, sorry for the inconvenience)

**Comment by smnandre** [comment]
I think i may have found the problem... did you add your "Component" namespace in the services.yaml file ? 

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Component\:
        resource: '../components/'
```

By doing that, and after experiencing the same bugs you had, everything worked for me on a new Symfony 6.3 + TwigComponent 2.12 project

**Comment by arnolem** [comment]
I had configured the service.yaml  `service.yaml` correctly

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Infrastructure/Symfony/Kernel.php'

    Component\:
        resource: '../components/'
```
