### ISSUE TITLE
Unable to find custom template for UX components with <twig:component> syntax

### ISSUE THREAD

**Issue by arnolem** [symfony/symfony#52153]
### Symfony version(s) affected

6.3

### Description

When i define a custome twig template of a component, it's ok where I called the component with the classic syntax but it's note possible to find the template with the new <twig:component> syntax.

### How to reproduce

1- Configure a new folder for Twig
```yaml
# config/packages/twig.yaml
twig:
    paths:
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/components'
```
2- Configure PHP classes autoload (❗dump-autoload)
```json
    "autoload": {
        "psr-4": {
            "App\\": "src/",
            "Component\\": "components/"
        }
    },
```
3- Create a folder `components/Button`
4- Create a PHP file
```php
<?php
namespace Component\Button;

use Symfony\UX\TwigComponent\Attribute\AsTwigComponent;

#[AsTwigComponent('button', template: 'button.twig')]
class ButtonComponent { }
```
5- Create a Twig file `components/button.twig`
<button>Wixiweb</button>

---

You can use this button like this : 
`{{ component('button') }}`

But you cannot use this button like this : 
`<twig:button></twig:button>`

> Unable to find template "button.twig" (looked into: /templates, /components, /templates) in [home/index.twig at line 13]
