### ISSUE TITLE
[Messenger] Multiple handlers for message

### ISSUE THREAD

**Issue by maMykola** [symfony/symfony#52170]
The docs says that the message can have multiple handlers.

The question: does it allowed to have multiple handlers for the same message in the same transport?

Example:
```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        failure_transport: failed

        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

            failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\Command': async
```
For the `App\Message\Command` message there are two handlers:
* `App\MessageHandler\CommandHandler`
* `App\MessageHandler\AnotherCommandHandler`

When message consumed from the transport the both handlers will be executed for this message.

Suppose that handlers executed in the following order: `CommandHandler`, `AnotherCommandHandler`.

If `CommandHandler` failed for some reason the second one will not be executed.

Suppose that this message send to failed queue after 3 retries. If you want to retry this message with `messenger:failed:retry` command it'll be executed only for the first handler and the second one will be skipped.
