### ISSUE TITLE
[Serializer] `AbstractObjectNormalizer` is not honoring `default_context` configuration

### ISSUE THREAD

**Issue by bigfoot90** [symfony/symfony#52184]
### Symfony version(s) affected

6.3.5

### Description

**serializer.yaml**
```yaml
framework:
  serializer:
    enabled: true
    default_context:
      datetime_format: Y-m-d h:i:s
      enable_max_depth: true
      skip_null_values: false
```

**Actual result:**
```
In AbstractObjectNormalizer.php:
array:2 [▼
  "max_depth_counter" => 1
]
```

**Expected result:**
```
In AbstractObjectNormalizer.php:
array:5 [▼
  "datetime_format" => "Y-m-d h:i:s"
  "enable_max_depth" => true
  "max_depth_counter" => 1
  "skip_null_values" => false
]
```

### How to reproduce

Try to configure `default_context` in `framework.serializer`

**Comment by emancypage** [comment]
Hey, that's interesting. I was trying to reproduce it anyhow but always when I set the defaults in the framework.serializer config (regardless in framework.yaml directly or in separated file serializer.yaml) the defaults are showing up in the dump of the Normalizers objects. 
![image](https://github.com/symfony/symfony/assets/24941274/210d6c00-b9c5-4bf6-b423-0a5362000840)
![image](https://github.com/symfony/symfony/assets/24941274/c5a6855b-6c49-423d-a4d0-06375a73b598)

I also made a test with a datetime_format which you used here and it is working as well.

Could you provide more details about exact issue you have with it?

**Comment by bigfoot90** [comment]
I can provide a reproducer soon as I have free time

**Comment by xabbuh** [comment]
@bigfoot90 Do you have any update for us?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by gcrispyn** [comment]
Hey guys,

I think I reproduce this issue in SF 5.4 version :

Here is my configuration :

```
serializer:
    circular_reference_handler: 'App\Serializer\CircularReferenceHandler'
    default_context:
            ignored_attributes:
                - '__initializer__'
                - '__cloner__'
                - '__isInitialized__'
```

If I look at the dump of the serializer, as you can see, default context is injected except in some normalizers :

<img width="399" alt="image" src="https://github.com/symfony/symfony/assets/10343117/eb3e2c8a-d7f6-4887-8196-1ad5a7551ed3">

<img width="631" alt="image" src="https://github.com/symfony/symfony/assets/10343117/e761137c-85d5-491b-852c-e23442eea96a">
