### ISSUE TITLE
[HttpClient][CurlHttpClient] Compressed data is not decrypted

### ISSUE THREAD

**Issue by presscot** [symfony/symfony#52195]
### Symfony version(s) affected

6.3.5

### Description

Despite of sending the Accept-Encoding: 'gzip' header and receiving Content-Encoding: gzip, class CurlHttpClient return encrypted result. Adding `curl_setopt($ch, CURLOPT_ENCODING, '');` solves the problem.

PHP => 8.2.7
Symfony => 6.3.5
curl => 8.1.2
ZLib => 1.2.13

### How to reproduce

```
function(\Psr\Http\Client\ClientInterface $client, \Psr\Http\Message\RequestFactoryInterface $requestFactory)
{
    $request = $requestFactory->createRequest($method,$url);
    $request = $request->withHeader('Accept-Encoding', 'gzip');
    $response = $client->sendRequest($request);
    dump($response->getBody()->getContents());  // response is encrypted
}
```

### Possible Solution
```
framework:
    http_client:
        default_options:
            extra:
                curl:
                    !php/const CURLOPT_ENCODING: 'gzip'
            headers:
                Accept-Encoding: 'gzip'
```
