### ISSUE TITLE
Error Text in Bootstrap 4 Form Layout

### ISSUE THREAD

**Issue by asispts** [symfony/symfony#52352]
### Symfony version(s) affected

5.4

### Description

When adding a marker using CSS for required inputs and an error occurs, the marker will be shifted downward by the error text.

![symfony-error-1](https://github.com/symfony/symfony/assets/79239132/f2d7468d-343d-4d26-94bf-ef31cedfce10)

![symfony-error-2](https://github.com/symfony/symfony/assets/79239132/c98c1ea8-6585-4537-8952-b2b067a50e9a)

### How to reproduce

- Add `bootstrap_4_layout.html.twig` to twig form theme
- Add a marker for required inputs in your css. For example:
```css
label {
    &.required {
        &:after {
            content: " *";
            font-weight: bold;
            color: crimson;
            font-size: 0.9em;
        }
    }
}
```
- Create a form with a required input and submit it.

### Possible Solution

The error text should appear below the form label block.
