### ISSUE TITLE
[Workflow][RFC] Simplify workflow configuration

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#52378]
I have been thinking about this for a while, so it's time to open a RFC!

The workflow definition is redundant. You have to define the places twice:

* in the `places`
* in the `transitions`

Example:

```yaml
framework:
    workflows:
        article:
            places:
                - first
                - last
            transitions:
                go:
                    from: first
                    to: last
```

I think we could simplify it to:

```yaml
framework:
    workflows:
        article:
            transitions:
                go:
                    from: first
                    to: last
```

Indeed, all places could be guessed from the transitions `from`s et `to`s. If a
place is not reached by a transition, it become useless anyway.

## Pros

* Simpler configuration

## Cons

* If one made a typo between the `place` and the `transitions` transition, it's
  not caught anymore

---

WDYT ?

**Comment by alexandre-daubois** [comment]
Big yes to me!

Would it make sense to still keep `places` ? I like the fact you can define places thanks to an array of constants for example, then define transitions specifically. Just wondering if this would be a removal of `places` or just if it wouldn't be required anymore :slightly_smiling_face: 

About the con, I'm not sure it would be a big deal. Of course it's always cool to have some double check, but I don't think this is _necessary_, other than being nice for the DX.

**Comment by lyrixx** [comment]
> Would it make sense to still keep `places` ?

Not sure it's required anymore. But removing it required breaking the BC. (with BC layer etc, but still)

**Comment by hhamon** [comment]
It would be great!

**Comment by javleds** [comment]
This sound great, if we require support I can create a PR to achieve this.

I have 2 possible approaches in mind:

---
1. Infer the places based on the transitions in the `Wofkflow/Definition.php` always places is empty.
```php
# Definition.php

public function __construct(array $places, array $transitions, $initialPlaces = null, MetadataStoreInterface $metadataStore = null)
{
    if (empty($places)) {
        $places = $this->inferPlacesFromTransitions($transitions);
    }
    
    foreach ($places as $place) {
        $this->addPlace($place);
    }
    //...
}
```
##### Pros: 
  - The ones mentioned by @lyrixx 
  - Retrocompatibility
  - We still have the oportunity to define the places in the case we require validations.
##### Cons:
  - This is kind of "magic" approach.

---
2. We may add the `infer_places: [bool]` entry in the yaml configuration file in order to allow the developers to decide if they want to use the places for the additional validations. For example:

```yml
framework:
    workflows:
        article:
            infer_places: true
            transitions:
                go:
                    from: first
                    to: last
```
##### Pros: 
  - Same as first option.
  - Explicit behavior defined by the developer.
##### Cons:
  - Extra verbosity in configuration files.
