### ISSUE TITLE
[Cache] Using DSN with PDOAdapter

### ISSUE THREAD

**Issue by HypeMC** [symfony/symfony#52460]
### Symfony version(s) affected

`>=5.4`

### Description

According to [the docs](https://symfony.com/doc/5.4/cache.html) it should be possible to use DSN to configure the PDOAdapter, how an exception is thrown instead:

```
  Unsupported DSN: it does not start with "redis[s]:", "memcached:" nor "couchbase:".
```

This happens because the `AbstractAdapter::createConnection()` supports only certain adapters:

https://github.com/symfony/symfony/blob/58353d12dabe6c5aba30866f8e693d1ce0949126/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php#L127-L144

I'm not sure if this is a bug in the documentation (and possible new feature) or a bug in the code.

### How to reproduce

```yaml
framework:
  cache:
    pools:
      my.cache:
        adapter: cache.adapter.pdo
        provider: "pgsql:host=localhost;port=5432;dbname=postgres;user=postgres;password=pass"
```

```php
#[AsCommand('app:test')]
class TestCommand extends Command
{
    public function __construct(
        #[Autowire(service: 'my.cache')] private CacheInterface $cache,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        return Command::SUCCESS;
    }
}
```

### Possible Solution

Add the necessary logic to `AbstractAdapter::createConnection()`.
