### ISSUE TITLE
[Ldap] Add aliases for users extraFields in LDAP component

### ISSUE THREAD

**Issue by MarvinCrepin** [symfony/symfony#52543]
### Description

While currently using the Symfony LDAP component to retrieve users from my LDAP directory, I've encountered an issue. The extra_fields property of this component allows fetching additional fields in the LDAP user object.

However, in practice, when retrieving a user from LDAP, I often don't have control over the names of the fields defined in LDAP. For example, the field employeeID might be used, but I would like to be able to rename it locally to something like matricule.

Therefore, I suggest introducing a feature that allows configuring the names of these additional fields when retrieving users from LDAP.

### Example

```
security:
  providers:
    my_ldap:
      ldap:
        service: Symfony\Component\Ldap\Ldap
        base_dn: 'dc=example,dc=com'
        search_dn: 'cn=read-only-admin,dc=example,dc=com'
        search_password: password
        default_roles: ROLE_USER
        uid_key: uid
        extra_fields:
           - matricule: employeeId
``` 

I can make a PR if this is found useful.
