### ISSUE TITLE
AutoconfigureTag only works if interface is registered itself

### ISSUE THREAD

**Issue by uncaught** [symfony/symfony#52590]
### Description

Using an `#[AutoconfigureTag]` on an interface is nice, but it's only working if the interface is registered with the service container itself.

This is neither documented nor intuitive.

Furthermore, if you then think you can add the interface individually to the service definitions like:

```yml
services:
  _defaults:
    autoconfigure: true
    autowire: true

   App\MyInterface: ~
```

Then the tagging works, but you end up with the interface itself as a tagged services. So doing this:

```php
  public function __construct(
    /** @var MyInterface[] */
    #[TaggedIterator(MyInterface::class)]
    private readonly iterable $services,
  ) {
  }
```

Iterating over these `$services` will give you an error: `Cannot instantiate interface App\MyInterface`.

So you have to exclude the interface itself again, which is weird:

```php
  public function __construct(
    /** @var MyInterface[] */
    #[TaggedIterator(MyInterface::class, exclude: MyInterface::class)]
    private readonly iterable $services,
  ) {
  }
```

-----

For some reason, including the interface indirectly via a wildcard does not have these problems:

```yml
services:
  _defaults:
    autoconfigure: true
    autowire: true

   App\:
      resource: './*Interface.php'
```

-----

So, is it really necessary to have the interface registered at all? Could you not check the attributes on base classes and interfaces for the registered services themselves?

**Comment by stof** [comment]
If the interface is not registered in the container, the container won't know about it and so cannot read its tags. So yes, it is necessary.

The way the PSR-4 discovery works is that interfaces are defined as abstract services, not as concrete ones. And abstract services are excluded from tagged iterators.

**Comment by nicolas-grekas** [comment]
Doing the config explicitly, this means this should work:

```yaml
services:
  _defaults:
    autoconfigure: true
    autowire: true

  App\MyInterface:
    abstract: true
```

I'm closing because this works as expected.
