### ISSUE TITLE
[DependencyInjection] Allow multiple configurators

### ISSUE THREAD

**Issue by maelanleborgne** [symfony/symfony#52607]
### Description

Would you be open to add a `configurators` or `configurator_stack` option to the service definition to allow multiple configurators for a service ? Maybe using a priority property to resolve processing order ? 

(I stumbled upon this while making a #[WithConfigurator] attribute and wondering how to resolve conflicts)

### Example

```yaml
services:
  App\MyService:
    configurator_stack:
      - ['@App\MyConfigurator1']
      - ['@App\MyConfigurator2', 'methodName']
      - ['@App\MyConfigurator3', 'methodName', 10]
```
