### ISSUE TITLE
[Cache/DI] Can not autowire TagAwareAdapterInterface

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#52703]
### Symfony version(s) affected

6.4.0-RC1

### Description

When trying to inject a `RedisTagAwareAdapter` via `TagAwareAdapterInterface` will throw an error:
```
Cannot autowire service "App\Service\Price\PriceService": argument "$priceCachePool" of method "__construct()" references interface "Symfony\Component\Cache\Adapter\TagAwareAdapterInterface" but no such service exists. Try changing the type-hint to "Psr\Cache\CacheItemPoolInterface" instead.
```

According to https://symfony.com/doc/current/cache.html this should work.

### How to reproduce

Cache Pool Configuration:
```yaml
            price_cache_pool:
                adapter: cache.adapter.redis_tag_aware
                provider: snc_redis.price_cache
                tags: true
```
(Also doesn't work when tags are missing)

DI Part:
```php
readonly class PriceService
{
    public function __construct(
        private TagAwareAdapterInterface $priceCachePool,
    ) {}
```
