### ISSUE TITLE
[Serializer]  ignored_attributes key is ignored in Objectnormalizer when we use default_context configuration key

### ISSUE THREAD

**Issue by gcrispyn** [symfony/symfony#52776]
### Symfony version(s) affected

5.4.31

### Description

When I setup a default_context inside framework.yml, the array defined in ignored_attributes is not injected into ObjectNormalizer

### How to reproduce

Create that configuration in framweork.yml :

```
serializer:
    circular_reference_handler: 'App\Serializer\CircularReferenceHandler'
    default_context:
        ignored_attributes:
            - '__initializer__'
            - '__cloner__'
            - '__isInitialized__'
        enable_max_depth: true
```

If you dump the serializer, you will see this :

<img width="559" alt="image" src="https://github.com/symfony/symfony/assets/10343117/c63842b6-d616-46db-a816-a78951a286b1">
