### ISSUE TITLE
[Security] InMemoryUserProvider configuration missing "enabled" parameter

### ISSUE THREAD

**Issue by klkvsk** [symfony/symfony#52908]
### Symfony version(s) affected

*.*.*

### Description

While InMemoryUser [supports](https://github.com/symfony/symfony/blob/dc330b087e496d2851cf9461fe27b16e69a66c89/src/Symfony/Component/Security/Core/User/InMemoryUser.php#L64-L77) `enabled` parameter to block logins, the configuration scheme [does not support](https://github.com/symfony/symfony/blob/dc330b087e496d2851cf9461fe27b16e69a66c89/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/UserProvider/InMemoryFactory.php#L54-L59) it.

### How to reproduce

```
  providers:
    app_user_provider: ....
    system_user_provider: 
      memory:
        users:
          system_aaa: { enabled: false, roles: ["ROLE_SYSTEM"] }
          system_bbb: { enabled: false, roles: ["ROLE_SYSTEM"] }
    user_provider:
      chain:
        providers: [ system_user_provider, app_user_provider ]
```

### Additional Context

It was rejected before in #5845 due to missing a proper use-case scenario, so here's a valid one: 
- have a SomeHistoryLog entity with date, user (of type UserInterface) and message properties
- usually messages are added by real user from web interface, but some are added by console commands, where `user` is the system itself
- want to keep SomeHistoryLog.user as is, storing the system user identifier along with app user identifiers
- want to keep a list of system users in code, because 1) easier to refactor, 2) no migration is needed when adding system users for new subsystems
- but want to ensure that never nobody can log in as those users

---
Sidenote:
A possible workaround could be setting `password` to null, but here's a suspicious moment:
https://github.com/symfony/symfony/blob/dc330b087e496d2851cf9461fe27b16e69a66c89/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/UserProvider/InMemoryFactory.php#L30-L34
Why is InMemoryFactory defaults password to `container.build_id` param?
