### ISSUE TITLE
[Notifier][FakeSMS] Notifications don't appear in profiler

### ISSUE THREAD

**Issue by disstudio** [symfony/symfony#52919]
### Symfony version(s) affected

6.3.5

### Description

Notifications sent are visible in "Logs" and "Emails" tab
`New SMS on phone number: +123456`
Emails are successfully sent

But there is no records in "Notifications" tab

### How to reproduce

config/packages/notifier.yaml
```yaml
framework:
    notifier:
        chatter_transports:
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['sms/sms']
            high: ['sms/sms']
            medium: ['sms/sms']
            low: ['sms/sms']
        admin_recipients:
            - { email: admin@example.com }

when@dev:
    framework:
        notifier:
            texter_transports:
                sms: '%env(FAKE_SMS_DSN)%'
```

env.local
`FAKE_SMS_DSN=fakesms+email://default?to=my.email@gmail.com&from=${MAILER_FROM}`

Sending sms
```php
$notification = (new Notification($content, ['sms/sms']))
    ->content($content);

// The receiver of the Notification
$recipient = new Recipient('', $phone);

// Send the notification to the recipient
$this->notifier->send($notification, $recipient);
```
