### ISSUE TITLE
`translation:pull` multiline becomes single line

### ISSUE THREAD

**Issue by ganti** [symfony/symfony#53106]
### Symfony version(s) affected

6.4

### Description

When using `php bin/console translation:pull` multiline strings are not parsed as such.

### How to reproduce

foobar+intl-icu.en.yaml:
```yaml
foo:
    bar: |
        line1
        line2
        line3
    apples: >-
        {count, plural,
            =1    {# apple}
            other {# apples}
        }
```

Execute: 
```bash
php bin/console translation:push --force loco  
php bin/console translation:pull --format yaml --as-tree 10 loco
```

foobar+intl-icu.en.yaml:
```yaml
foo:
    bar: "line1\nline2\nline3\n"
    apple: "{count, plural,\n    =1    {# apple}\n    other {# apples}\n}"
```

Here is an example to reproduce:
https://github.com/ganti/symfony-translation-pull-multiline-example

### Possible Solution

if a translation string contains a linebreak, save this key as multiline translation
