### ISSUE TITLE
1 returned with $request->getLocale() with array path in route attribute.

### ISSUE THREAD

**Issue by cyraid** [symfony/symfony#53539]
### Symfony version(s) affected

7.0.2

### Description

`$request->getLocale()` will return `1` when there is an array in `#[Route]`:
```php
  #[Route(['/{_locale}/{path}', '/{path}'], requirements: ['path' => '.*'])]
  public function home(Request $request): Response {
    return $this->render("home/{$request->getLocale()}/index.html");
  } // Function //
```

When route is:
```php
  #[Route('/{_locale}/{path}', requirements: ['path' => '.*'])]
```

`$request->getLocale()` will return `en` as expected.

**framework.yaml:**
```yaml
framework:
    default_locale: en
    enabled_locales: ['en', 'fr']
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
```

### How to reproduce

Should be able to reproduce using the information in the description. You don't have to return a page, just print the result of `$request->getLocale()` if you need to.

### Possible Solution

Might be a bug in getLocale()? That or a locale listener if there is one. I suppose I could detect a number and use 'en' as default, but the method does not return a string, it returns a number which is a bug, as `getLocale()` is marked as `string` and it should return the actual locale and not an index?
