### ISSUE TITLE
Symfony Cloud: the DATABASE_VERSION automatically generated env variable does not respect the dbal config.

### ISSUE THREAD

**Issue by davidesigner** [symfony/symfony#53549]
### Symfony version(s) affected

6.4

### Description

I there 👋 

I'm new on Platform.sh and I don't understand why I have the following deprecated notice:
```
deprecation.INFO: User Deprecated: Support for MariaDB < 10.4 is deprecated and will be removed in DBAL 4. Consider upgrading to a more recent version of MariaDB. (AbstractMySQLDriver.php:50 called by TracingDriverForV3.php:97, https://github.com/doctrine/dbal/pull/6110, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Support for MariaDB < 10.4 is deprecated and will be removed in DBAL 4. Consider upgrading to a more recent version of MariaDB. (AbstractMySQLDriver.php:50 called by TracingDriverForV3.php:97, https://github.com/doctrine/dbal/pull/6110, package doctrine/dbal) at /app/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php:210)"} []
```

When I dump my env variables, I can see: `DATABASE_VERSION=8.0.0-MariaDB` (that seems to be autogenerated by the Symfony Build).

I have defined the server_version inside my dbal config:
```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        use_savepoints: true
       
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.0.33'
        driver: 'mysql'
        
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
```
as [the documentation indicate](https://docs.platform.sh/guides/symfony/faq.html#why-is-database_url-not-defined-during-the-build-hook) (only these 2 variables server_version & driver are taken into account).

My Platform.sh script that follow the documentation recommendations:
```yaml
hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash

        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e

        symfony-deploy
```

### Local reproduction:

When I try in my local environment, if I set this in my .env.local file:

```
DATABASE_VERSION=8.0.0-MariaDB
```

With the same doctrine.yaml config (`server_version: '8.0.33'` & `driver: 'mysql'`).

Doctrine does not show me the warning in my logs.

If I try to change the doctrine.yaml config for `server_version: '8.0.0-MariaDB',` the warning is shown like in production.

My _doctrine.yaml_ configuration seems to be ignored in the PlatformSh context?

If I try to remove the `server_version: '8.0.33'` from my _doctrine.yaml_ config with .env that contains `8.0.0-MariaDB`, the warning is not displayed, astonishingly.

### Conclusion:

Do you have any idea of the source of the problem?

Thanks for your help!

PS: I've already talk to the PlateformSh support that cannot help because it's a Symfony Cloud internal problem.

### How to reproduce

1. Add doctrine package.
2. Add `server_version` & `driver` inside the dbal config:
    ```yaml
    # config/packages/doctrine.yaml
    doctrine:
        dbal:
            url: '%env(resolve:DATABASE_URL)%'
            use_savepoints: true
           
            # IMPORTANT: You MUST configure your server version,
            # either here or in the DATABASE_URL env var (see .env file)
            server_version: '8.0.33'
            driver: 'mysql'
            
            profiling_collect_backtrace: '%kernel.debug%'
        orm:
    ```
3. Add a file `.platform/services.yaml`:
   ```yaml
   mysql:
      type: oracle-mysql:8.0
      disk: 1024
      configuration:
          schemas:
              - main
          endpoints:
              main:
                  default_schema: main
                  privileges:
                      main: admin
   ```
4. Add this default config (from the documentation recommendations) to the `.platform.app.yaml` file:
    ```yaml
    hooks:
        build: |
            set -x -e
    
            curl -fs https://get.symfony.com/cloud/configurator | bash
    
            NODE_VERSION=18 symfony-build
    
        deploy: |
            set -x -e
    
            symfony-deploy

    relationships:
        database:
            service: mysql
            endpoint: main
    ```
5. Then run the code on a PlateformSh.

### Additional Context

doctrine/dbal: 3.7.2
doctrine/orm: 2.17.2

Opened issue on Doctrine: https://github.com/doctrine/dbal/issues/6254
