### ISSUE TITLE
[symfony/messenger] Serializer Context Groups doesn't seems to be handle

### ISSUE THREAD

**Issue by agennari** [symfony/symfony#53553]
### Symfony version(s) affected

6.2

### Description

Trying to send entity User from microservice A to microservice B using Symfony/Messenger, and RabbitMQ transport, "automatically" serialized by Symfony Serializer

### How to reproduce

Setup two Symfony project, and a RabbitMQ.
Create User entity and a CreateUserNotification (dispatched after a user is created)

messenger.yaml: 

```
framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { groups: ['serialize-messenger'] }
        transports:
            sso:
                dsn: '%env(RABBITMQ_URL)%/sso'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: sso_fanout
                    queues:
                        sso_queue1: ~
        routing:
             'App\Message\CreatedUserNotification': sso
```

User entity: 
```

class User implements UserInterface {
    #[Groups(['serialize-messenger'])]
    private string $username;

...

```

CreatedUserNotification: 

```
readonly class CreatedUserNotification implements BaseMessageInterface {
    public function __construct(
        private User $content,
    ) {
    }

    public function getContent(): User
    {
        return $this->content;
    }
}
```

Try to dispatch the event.

When Serializer group is set: 

![image](https://github.com/symfony/symfony/assets/156677093/7cb900d6-dacd-4db7-abb5-872aec19412f)

When Serializer group is not set:

![image](https://github.com/symfony/symfony/assets/156677093/17a1176f-a3fd-4810-80fc-972c45045d75)

The issue is that groups context seems not to be handle by Symfony or something else...
