### ISSUE TITLE
Messenger transport with multiple rate limits

### ISSUE THREAD

**Issue by mustanggb** [symfony/symfony#53629]
### Description

It appears that [Rate Limited Transport](https://symfony.com/doc/current/messenger.html#rate-limited-transport) doesn't support either multiple rate limits (as an array) or a [CompoundLimiter](https://github.com/symfony/symfony/issues/40705#issuecomment-813903083) service.

It would be great to add support for this, probably CompoundLimiter compatibility is the way to go.

### Example

With:
```
framework:
  rate_limiter:
    async_messenger_transport_one:
      policy: 'sliding_window'
      limit: 60
      interval: '1 minute'
    async_messenger_transport_two:
      policy: 'sliding_window'
      limit: 5000
      interval: '1 day'

services:
  app.async_messenger_transport:
    class: Symfony\Component\RateLimiter\CompoundLimiter
    arguments:
      - ['@limiter.async_messenger_transport_one', '@limiter.async_messenger_transport_two']
```

Either:
```
framework:
  messenger:
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        rate_limiter: ['async_messenger_transport_one', 'async_messenger_transport_two']
```
```
[Symfony\Component\Config\Definition\Exception\InvalidTypeException]                                            
Invalid type for path "framework.messenger.transports.async.rate_limiter". Expected "scalar", but got "array".  
Hint: Rate limiter name to use when processing messages
```
Or:
```
framework:
  messenger:
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        rate_limiter: 'async_messenger_transport'
```
```
[Symfony\Component\ErrorHandler\Error\UndefinedMethodError]                                                     
Attempted to call an undefined method named "create" of class "Symfony\Component\RateLimiter\CompoundLimiter".
```
