### ISSUE TITLE
'Environment variables are never used' error while running tests with mocked service

### ISSUE THREAD

**Issue by nlinkevich-busuu** [symfony/symfony#53633]
### Symfony version(s) affected

6.3.0

### Description

I'm trying to mock http client service that have env vars in its configuration, but when I run tests I have an error `Environment variables are never used`

### How to reproduce

I have this http client in `framework.yaml` file:
```
framework:
    http_client:
        deployment.client:
            base_uri: '%env(DEPLOYMENT_SERVICE_URL)%'
            headers:
                Authorization: 'Bearer %env(DEPLOYMENT_SERVICE_TOKEN)%'
```

I am trying to mock this service in `services_test.yaml`:
```
services:
    deployment.client:
        class: Symfony\Component\HttpClient\MockHttpClient 
```

And then when I run something in test env I have this error: `Symfony\Component\DependencyInjection\Exception\EnvParameterException: Environment variables "DEPLOYMENT_SERVICE_URL", "DEPLOYMENT_SERVICE_TOKEN" are never used. Please, check your container's configuration.`

**Comment by Valmonzo** [comment]
Hi @nlinkevich-busuu, do you have those env var on .env.test ?

**Comment by nlinkevich-busuu** [comment]
Hello! I have them in .env file. And I tried to add and remove them from .env.test, it doesn't change anything

**Comment by Valmonzo** [comment]
Did you try a `bin/console debug:container deployment.client --env=test` to get more info ?

**Comment by nlinkevich-busuu** [comment]
<img width="1146" alt="image" src="https://github.com/symfony/symfony/assets/92434518/22a0856a-5bc0-4600-b15b-045dc92a594f">

**Comment by Valmonzo** [comment]
I reproduced your example, I think there is a typo in `framework.yaml` : 
```
framework:
    http_client:
        scoped_clients:
            deployment.client:
                base_uri: '%env(DEPLOYMENT_SERVICE_URL)%'
```

> Note: I don't use Token because Swapi doesn't need it

```
//.env

DEPLOYMENT_SERVICE_URL=https://swapi.dev/api/

//.env.test

DEPLOYMENT_SERVICE_URL=http://www.example.org

```
It works if I add an argument  in `services_test.yaml` :

```
services:
  deployment.client:
    class: Symfony\Component\HttpClient\MockHttpClient
    arguments:
      $baseUri: '%env(DEPLOYMENT_SERVICE_URL)%'
```

When i run test : 

```
Testing /app/tests
^ Symfony\Component\HttpClient\UriTemplateHttpClient^ {#4923
  -expander: null
  -defaultVars: []
  -client: Symfony\Component\HttpClient\MockHttpClient^ {#935
    -responseFactory: null
    -requestsCount: 0
    -defaultOptions: array:1 [
      "base_uri" => "http://www.example.org"
    ]
  }
}
```
I created a command to test if it works in env dev : 

```
<?php

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Contracts\HttpClient\HttpClientInterface;

#[AsCommand(name: 'app:test-deployment-client')]
class TestDeploymentClientCommand extends Command
{
    public function __construct(private readonly HttpClientInterface $deploymentClient)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $response = $this->deploymentClient->request(Request::METHOD_GET, 'people/1/');

        $output->writeln($response->getContent());

        return Command::SUCCESS;
    }
}
```
still works for me : 
```
❯ symfony console app:test-deployment-client
{"name":"Luke Skywalker","height":"172","mass":"77","hair_color":"blond","skin_color":"fair","eye_color":"blue","birth_year":"19BBY","gender":"male","homeworld":"https://swapi.dev/api/planets/1/","films":["https://swapi.dev/api/films/1/","https://swapi.dev/api/films/2/","https://swapi.dev/api/films/3/","https://swapi.dev/api/films/6/"],"species":[],"vehicles":["https://swapi.dev/api/vehicles/14/","https://swapi.dev/api/vehicles/30/"],"starships":["https://swapi.dev/api/starships/12/","https://swapi.dev/api/starships/22/"],"created":"2014-12-09T13:50:51.644000Z","edited":"2014-12-20T21:17:56.891000Z","url":"https://swapi.dev/api/people/1/"}
```
I hope it will help you 🙏🏽
