### ISSUE TITLE
Accessing User in Kernel Request before 'Matched route "{route}"'

### ISSUE THREAD

**Issue by cyraid** [symfony/symfony#53673]
### Symfony version(s) affected

7.0.2

### Description

Ever try to insert the Logged-In User into the `Matched route "{route}"` message in a Monolog Custom Processor? Token Storage User isn't available yet, so how does one do it? I've found a pretty hackish way to do it, but I'm sure it's not the only way to do it?

I really think it could be important to show us the User who accessed the resource instead of deducing from the IP and printing a message later.

I currently have a Request Identifier and Session ID inserted into the Request attributes, then printed later in Monolog Custom Processor. For now what I do is grab the PostAuthenticationToken from the Session and get the User from there.

### How to reproduce

This will always have `_user_id` as `null`, as it won't exist in Token Storage before 'Matched Route'.

```php
  public function __construct(private Security $security) {
  } // Constructor //

  #[AsEventListener('kernel.request', priority: 127)] // Priority 127 is carefully chosen.
  public function onKernelRequest(RequestEvent $ev): void {

    $req = $ev->getRequest();

    if (!$req->attributes->has('_user_id')) {
      $user = $this->security->getUser();
      $req->attributes->set('_user_id', $user ? $user->getUserIdentifier() : null);
    } // IF //

  } // Procedure //
```

### Possible Solution

```php
namespace App\EventListener;

//========[[ Imports ]]=======================================================//

use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken;

//****************************************************************************//
//========[[ ExtrasRequestListener Class
//****************************************************************************//

/**
 * The Kernel Request Listener before Route Matching to insert into Request Extras.
 * Note: Priority 127 is carefully chosen.
 */
#[AsEventListener('kernel.request', priority: 127, method: 'onKernelRequest')]
class ExtrasRequestListener {

  //========[[ Public Methods ]]==============================================//

  public function __construct(private Security $security) {
  } // Constructor //

  public function onKernelRequest(RequestEvent $ev): void {

    $req = $ev->getRequest();
    $session = $req->hasSession() ? $req->getSession() : null;

    $req->attributes->set('_sess_id', $session ? $session->getId() : null);

    // If we don't have '_user_id' in the Request yet, add it //

    if (!$req->attributes->has('_user_id')) {

      $user = $this->security->getUser();

      // No User yet? (mostly the case for Route Matching) //

      if (!$user && $session && $session->has('_security_main')) {

        // If the Session has the '_security_main', unserialize the token and use it //

        $token = unserialize($session->get('_security_main'));

        if ($token instanceof PostAuthenticationToken)
          $user = $token->getUser();

      } // IF //

      // Set the User ID if we have one //

      $req->attributes->set('_user_id', $user ? $user->getUserIdentifier() : null);

    } // IF //

  } // Procedure //

} // Class //
```

### Additional Context

My Custom Log Processor:

```php
namespace App\EventListener;

//========[[ Imports ]]=======================================================//

use Monolog\Attribute\AsMonologProcessor;
use Monolog\LogRecord;
use Monolog\Processor\ProcessorInterface;
use Symfony\Component\HttpFoundation\RequestStack;

//****************************************************************************//
//========[[ CustomLogProcessor Class
//****************************************************************************//

#[AsMonologProcessor]
class CustomLogProcessor implements ProcessorInterface {

  //========[[ Public Methods ]]==============================================//

  public function __construct(private RequestStack $requestStack) {
  } // Constructor //

  public function __invoke(LogRecord $record): LogRecord {

    $req = $this->requestStack->getCurrentRequest();

    if (!$req)
      return $record;

    $record->extra['_ip'] = $req->getClientIps();
    $record->extra['_uri'] = $req->getUri();
    $record->extra['_req_id'] = $req->attributes->get('_req_id');
    $record->extra['_user_id'] = $req->attributes->get('_user_id');
    $record->extra['_sess_id'] = $req->attributes->get('_sess_id');

    return $record;

  } // Function //

} // Class //
```

My config for it in `services.yaml`:
```yaml
    monolog.formatter.devlog_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%% [%%level_name%%] [%%context%%:%%extra%%] \r%%message%%\n"
            - "Y-m-d\\TH:i:s"
```

Using it in `monolog.yaml`:
```yaml
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                process_psr_3_messages: true
                include_stacktraces: true
                channels: ["!event", "!doctrine", "!security"]
                formatter: monolog.formatter.devlog_formatter
```

I *think* that may be all that's necessary? If anyone needs more info, feel free to ask. ^_^

**Comment by lyrixx** [comment]
Hello, Thanks for this issue.

This is not possible by design since the router comes before the firewall

```console
$ bin/console debug:event kernel.request --env=prod | grep ' Symfony'
[...]
  #11     Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest()                  32
[...]
  #19     Symfony\Bundle\SecurityBundle\EventListener\FirewallListener::onKernelRequest()               8
```

Changing that would be a huge BC break, and it has been done on purpose.

---

Instead, I would suggest to do something really different (We are a lot do that that):

1. Add a UidProcessor to monolog
2. All log for **one** request will  have the **same ID**
3. (You can even propagate this ID to sub http request, rabbitmq message, etc)
4. Then when you need to search something in your log, add this ID, and then yo'll have a full trace

**Comment by cyraid** [comment]
Thanks for the quick reply and the clarification! Another way I've been thinking is perhaps add a way to disable the match route messages only, and implement our own at the stage we like? Would that make sense?

**Comment by lyrixx** [comment]
This is only some logs, so adding a configuration flag for that seems overkill. But let's way for other feedback

**Comment by teamflp** [comment]
@cyraid I would propose this solution Using an Event Listener with Deferred Processing

1. Create a Security Event Listener:
   - Create a listener that subscribes to an event after user authentication, such as InteractiveLoginEvent or SecurityInteractiveLoginEvent. This event is triggered after the user has been authenticated and the Token Storage contains the user's token.

2. Store User Information:
   - In this event listener, retrieve the authenticated user and store their ID in an accessible location, for example, in the attributes of the session or the request.

3. Modify the Monolog Processor:
   - Adapt your custom Monolog processor to check if the user information is available. If it is not immediately available, configure the processor to retrieve this information as soon as it becomes available.
   - The processor can check for the presence of the user's ID in the request attributes and include it in the logs.

4. Handle Cases Where the User is Not Authenticated:
   - Ensure that your Monolog processor correctly handles cases where the user is not yet authenticated. In these cases, it could omit the user's ID or explicitly mark the user as unauthenticated.

5. Testing and Validation:
   - Test this solution in different scenarios to ensure that it works correctly. Specifically, verify that the user's ID is correctly recorded in the logs after their authentication.

**Comment by cyraid** [comment]
Thanks for all the great feedback guys, and taking the time to help out!

@teamflp Thank you for the well thought out and nicely formatted reply. I took what you suggested and mixed it with my own solution as well! I used the `LoginSuccessEvent`:
```php
#[AsEventListener(LoginSuccessEvent::class, method: 'onLoginSuccess')]
```

And then stored it in the Session. In my existing Request Listener I first check the request for the User ID, then the Session, then finally at worst case check the _security_main for the Post Authentication Token.

A nicer built-in solution would be great, but I do think I have what I need. If this was indeed intentional this isn't a bug, so should I close this report?

**Comment by teamflp** [comment]
@cyraid i'm delighted to hear that my suggestion was useful to you and that you were able to successfully integrate it into your own solution. It's always rewarding to see that collaboration can lead to innovative and effective solutions.

Regarding your question about closing the bug report, I think if your solution currently meets your needs and you consider the behavior not as a bug but as a feature of Symfony, it would be reasonable to close the issue. However, it might be useful for the community if you detailed in a final comment how you resolved the problem, including the steps you followed. This could help other developers facing a similar situation.

Finally, if you believe that the functionality you've implemented could be beneficial for other Symfony users, consider submitting a feature proposal or a pull request. It is through community contributions that frameworks like Symfony continue to evolve and improve.

Thank you again for your kind words and best of luck in your continued development with Symfony.

Sincerely,

**Comment by lyrixx** [comment]
I'm closing this issue for the reasons explained. Thanks

**Comment by cyraid** [comment]
@teamflp Thank you again for the help! That sounds like a pretty good idea, maybe this will help someone going forward.

So what I do:

  1) A Kernel Request that has the highest priority to stick in a randomly generated Request ID. This makes it easy if you display the Request ID on an error page for example, a User could give you the Request ID and you can locate it in the logs easier.

```php
#[AsEventListener('kernel.request', priority: 9999, method: 'onKernelRequest')]
class RequestIdRequestListener {

  //========[[ Public Methods ]]==============================================//

  public function onKernelRequest(RequestEvent $ev): void {
    $req = $ev->getRequest();
    $req->attributes->set('_req_id', str_replace('.', '-', uniqid(more_entropy: true)));
  } // Procedure //

} // Class //
```

  2) I listen for the LoginSuccessEvent and store the User ID in the Session and the Request.

```php
#[AsEventListener(LoginSuccessEvent::class, method: 'onLoginSuccess')]
class OnLoginEventListener {

  //========[[ Public Methods ]]==============================================//

  public function onLoginSuccess(LoginSuccessEvent $ev): void {

    $user = $ev->getUser();
    $userId = $user->getUserIdentifier();

    $req = $ev->getRequest();
    $session = $req && $req->hasSession() ? $req->getSession() : null;

    if ($session) {
      $session->set('user_id', $userId);
      $req->attributes->set('_user_id', $userId);
    } // IF //

  } // Procedure //

} // Class //
```

  3) I then have a Kernel Request at Priority 127 so I can beat the Matched route log (a bit hefty, but hopefully the comments will explain).

```php
/**
 * The Kernel Request Listener before Route Matching to insert into Request Extras.
 * Note: Priority 127 is carefully chosen.
 */
#[AsEventListener('kernel.request', priority: 127, method: 'onKernelRequest')]
class ExtrasRequestListener {

  //========[[ Public Methods ]]==============================================//

  public function __construct(private Security $security) {
  } // Constructor //

  public function onKernelRequest(RequestEvent $ev): void {

    $req = $ev->getRequest();
    $session = $req->hasSession() ? $req->getSession() : null;
    $userId = $req->attributes->get('_user_id');

    // If we don't have the User ID, retreive it //

    if (!$userId) {

      // Check if User Exists from Token Storage //

      $user = $this->security->getUser();

      if ($user) {

        $userId = $user->getUserIdentifier();

      } else if ($session) {

        // Try getting User ID from the Session //

        $userId = $session->get('user_id', null);

        // If no User ID in Session yet, last ditch effort to get it from _security_main //

        if (!$userId && ($token = $session->get('_security_main'))) {

          // If the Session has the '_security_main', unserialize the token and use it //

          $token = unserialize($token);

          if ($token instanceof PostAuthenticationToken) {
            $user = $token->getUser();
            $userId = $user ? $user->getUserIdentifier() : null;
          } // IF //

          // Save the ID into the Session for next time //

          if ($userId)
            $session->set('user_id', $userId);

        } // IF //

      } // Else IF //

    } // IF //

    // Set the User ID / Session ID into the Request //

    $req->attributes->set('_sess_id', $session ? $session->getId() : null);
    $req->attributes->set('_user_id', $userId);

  } // Procedure //

} // Class //
```

  4) Finally I have a Monolog Processor that uses all the information and prints it out.

```php
#[AsMonologProcessor]
class CustomLogProcessor implements ProcessorInterface {

  //========[[ Public Methods ]]==============================================//

  public function __construct(private RequestStack $requestStack) {
  } // Constructor //

  public function __invoke(LogRecord $record): LogRecord {

    $req = $this->requestStack->getCurrentRequest();

    if (!$req)
      return $record;

    $record->extra['_ip'] = join(',', $req->getClientIps());
    $record->extra['_uri'] = $req->getRequestUri();
    $record->extra['_req_id'] = $req->attributes->get('_req_id');
    $record->extra['_user_id'] = $req->attributes->get('_user_id');
    $record->extra['_sess_id'] = $req->attributes->get('_sess_id');

    return $record;

  } // Function //

} // Class //
```

If you wanna have some nice logs without the JSON stuffs, you can always do what I did and add the format to **config/services.yaml**:

```yaml
    monolog.formatter.devlog_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%% [%%level_name%%] [%%extra._ip%%; %%extra._user_id%%; %%extra._sess_id%%; %%extra._req_id%%; %%extra._uri%%] [%%extra%%] \r%%message%%\n"
            - "Y-m-d\\TH:i:s"

    monolog.formatter.debuglog_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%level_name%%] [%%extra._ip%%; %%extra._user_id%%; %%extra._sess_id%%; %%extra._req_id%%; %%extra._uri%%] %%message%%\n"
            - "Y-m-d\\TH:i:s"

    monolog.formatter.errorlog_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra._ip%%; %%extra._user_id%%; %%extra._req_id%%; %%extra._uri%%] %%message%%\n"
            - "Y-m-d\\TH:i:s"

    monolog.formatter.syslog_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%extra._req_id%%] %%message%%"
```

The `\r` is for my awk script which I `tail -f` the log file and print some nice colors in the log, and able to separate the message easier (for the RegExp).

Finally, using the formatters in the **config/packages/monolog.yaml**:

```yaml
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                process_psr_3_messages: true
                include_stacktraces: true
                channels: ["!event", "!doctrine", "!security"]
                formatter: monolog.formatter.devlog_formatter
```

Hopefully this will help others on the journey of printing User ID in your logs.
And whoever reads this and it helps you, I'm glad it helped, and good luck on your project!
