### ISSUE TITLE
[Scheduler] Compilerpass wrongly assumes every messenger receiver has an alias 

### ISSUE THREAD

**Issue by zluiten** [symfony/symfony#53811]
### Symfony version(s) affected

7.0.3

### Description

The [AddScheduleMessengerPass.php#L38-L40](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Scheduler/DependencyInjection/AddScheduleMessengerPass.php#L38-L40) wrongly assumes every service tagged with "messenger.receiver" has an alias, but the alias is technically optional: [MessengerPass.php#L266](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php#L266).

### How to reproduce

Add a messenger receiver to your application and just tag it without specifying an alias:

```yaml
App\Receiver\MyReceiver:
  class: App\Receiver\MyReceiver
  tags: [ { name: 'messenger.receiver' } ]
```

Then add the symfony/scheduler package to your project. The compiling of the container will fail with

```
In AddScheduleMessengerPass.php line 39:

  [ErrorException]
  Warning: Undefined array key "alias"
```
