### ISSUE TITLE
[Scheduler] Configuring a Schedule Provider via yaml configuration

### ISSUE THREAD

**Issue by zluiten** [symfony/symfony#53810]
### Symfony version(s) affected

7.0.3

### Description

Adding an implementation of the ScheduleProviderInterface and correctly tagging it is only possible using attributes.

A Schedule needs to have a name. Which can be configured like this via an attribute

```php
namespace App\Scheduling;

#[AsSchedule('some name')]
final class MyScheduleProvider implements ScheduleProviderInterface
```

The [FrameworkExtension.php#L693-L695](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L693-L695) makes sure the property "name" is added to the tag.

The [AddScheduleMessengerPass#L44](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Scheduler/DependencyInjection/AddScheduleMessengerPass.php#L44) then assumes the tag has a property "name".

Trying to achieve the same with just yaml configuration is not possible.

```yaml
services:
  App\Scheduling\MyScheduleProvider:
    class: App\Scheduling\MyScheduleProvider:
    tags: [ {  name: 'scheduler.schedule_provider' } ]
```

Compiling the container now fails with 

```
In AddScheduleMessengerPass.php line 44:

  [ErrorException]
  Warning: Undefined array key "name"
```

That is because the `name` keyword in the yaml configuration is used to specify the tag name. So now the Schedule implementation has no name.

### How to reproduce

Add an implementation of the ScheduleProviderInterface

```php
namespace App\Scheduling;

use Symfony\Component\Scheduler\Schedule;

final class MyScheduleProvider implements ScheduleProviderInterface
{
    public function getSchedule(): Schedule
    {
        return new Schedule();
    }
}
```

Configure the class using yaml configuration

```yaml
services:
  App\Scheduling\MyScheduleProvider:
    class: App\Scheduling\MyScheduleProvider:
    tags: [ {  name: 'scheduler.schedule_provider' } ]

```

### Possible Solution

The usage of the word "name" to name a Schedule is unfortunate. Maybe something like "id" would be better and it wouldn't interfer with "name" to specify the tag.

**Comment by HypeMC** [comment]
I think this should solve your problem: https://symfony.com/doc/current/service_container/tags.html#configuration-block-tabpanel-52d45a9c01035ac4ff756d76f7a40df4fb20dd51

> The name attribute is used by default to define the name of the tag. If you want to add a name attribute to some tag in XML or YAML formats, you need to use this special syntax:

```yaml
# config/services.yaml
services:
    MailerSmtpTransport:
        arguments: ['%mailer_host%']
        tags:
            # this is a tag called 'app.mail_transport'
            - { name: 'app.mail_transport', alias: 'smtp' }
            # this is a tag called 'app.mail_transport' with two attributes ('name' and 'alias')
            - app.mail_transport: { name: 'arbitrary-value', alias: 'smtp' }
```
