### ISSUE TITLE
[Lock] - pass redis connection

### ISSUE THREAD

**Issue by vencakrecl** [symfony/symfony#53845]
### Symfony version(s) affected

7.0.3

### Description

The StoreFactory can receive object or string but the lock configuration allow use only string. StoreFactory::create can use instance of connection (\Redis, \RedisCluster, etc.)

`public static function createStore(#[\SensitiveParameter] object|string $connection): PersistingStoreInterface`

### How to reproduce

```yaml
framework:
  lock:
    enabled: true
    resources:
      - '@cache.provider.redis'
      
services:
    cache.provider.redis:
      class: \Redis # no matter what the factory returns
      factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection' ]
      arguments:
        - 'redis://redis:6379'
```

### Possible Solution

[`\Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension::registerLockConfiguration`](https://github.com/symfony/framework-bundle/blob/7448883b512a703623a0fb40dcf0fcca9abe324a/DependencyInjection/FrameworkExtension.php#L1972) the extension should pass service here.
