### ISSUE TITLE
Add RequestClock

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#53903]
### Description

NativeClock interacts with the system clock which involves system calls and not always needed. For business events like user registration date the request time can be used.

The implementation could something like following.
```php
final class RequestClock implements ClockInterface
{

    public function now(): DatePoint
    {
        return new DatePoint::createFromFormat('U', $_SERVER['REQUEST_TIME_FLOAT']);
    }

}
```

**Comment by Chi-teck** [comment]
Alternatively, we could pass request time through clock constructor. So an application could implement a factory to create the clock from request object.

**Comment by athish-v** [comment]
Hello @xabbuh,
Can I work on this feature

**Comment by nicolas-grekas** [comment]
An idea to make this maybe more generic: we make MockClock accept a Closure instead of a value, and when this happens, we use the return value of that closure the first time the time is needed, and then we serve always the same time, until a MockClock::reset() method is called, which would signal that the closure should be called again on the next call.

WDYT? Then returning the request time would just be a matter of defining a service that wires all this.
@vpathish please go ahead!

**Comment by nicolas-grekas** [comment]
For the record, this weird yaml is defining a service that resolves to the request time:

<details>

```yaml
services:
    request_time:
        class: DateTimeImmutable
        factory: [null, 'createFromFormat']
        arguments:
            - 'U.u'
            - !service
                class: string
                factory: sprintf
                arguments:
                    - '@@%.6f'
                    - !service
                        class: float
                        factory:
                            - !service
                                class: Symfony\Component\HttpFoundation\ServerBag
                                factory: current
                                arguments:
                                    - !service
                                        class: array
                                        factory: array_column
                                        arguments:
                                            -
                                                - !service
                                                        class: Symfony\Component\HttpFoundation\Request
                                                        factory:
                                                            - '@request_stack'
                                                            - 'getCurrentRequest'
                                            - 'server'
                            - 'get'
                        arguments: ['REQUEST_TIME_FLOAT']
```

</details>

Then, you can inject this service into a MockClock and that will do the job:

```yaml
services:
    request_clock:
        class: Symfony\Component\Clock\MockClock
        arguments:
            - '@request_time'
```

Yet, there is one caveat, which is that if you run your app in a long-running process, the time should be reset between requests.

Doing so is not possible for now, but thanks to #57930, you'll be able to define the service like that instead, and job done:

```yaml
services:
    request_clock:
        class: Symfony\Component\Clock\MockClock
        arguments:
            - !service_closure '@request_time'
        tags: ['kernel.reset']
```
