### ISSUE TITLE
"No User Loader Configured" error with rate limiter in multi-firewall setup

### ISSUE THREAD

**Issue by oto-emo** [symfony/symfony#54026]
### Symfony version(s) affected

6.4.3

### Description

I am encountering an issue in my Symfony 6.4 application where the application throws an error related to the user loader configuration when the rate limiter fails. The exact error message is: "No user loader is configured, did you forget to register the 'Symfony\Component\Security\Http\EventListener\UserProviderListener' listener?"

### How to reproduce

**Description**:
In my Symfony 6.4 application, I have encountered a peculiar issue where configuring a single `login_throttling` within a multi-firewall setup leads to a "No user loader is configured" error. This error surfaces even though the user providers are correctly set up for each firewall in `security.yaml`. The problem seems to be specifically triggered by the rate limiter's failure mechanism in scenarios where multiple firewalls are present but only one has `login_throttling` configured.

**Steps to Reproduce**:
1. Set up two firewalls in `security.yaml`, each with its own user provider and custom authenticator.
2. Configure `login_throttling` for only one of the firewalls.
3. Attempt to authenticate through the firewall with `login_throttling` configured, exceeding the rate limit to trigger the failure condition.

**Expected Result**:
The rate limiter should function as intended, limiting login attempts for the specified firewall without affecting the user loading process or causing configuration errors in the security component.

**Actual Result**:
Upon triggering the rate limiter's failure condition, the application throws an error stating "No user loader is configured, did you forget to register the 'Symfony\Component\Security\Http\EventListener\UserProviderListener' listener?", despite the user providers being correctly configured for both firewalls.

**Configuration Snippet**:
```yaml
security:
    providers:
        firewall_one_user_provider:
            entity:
                class: App\Entity\UserOne
                property: email
        firewall_two_user_provider:
            entity:
                class: App\Entity\UserTwo
                property: email
    firewalls:
        firewall_one:
            pattern: '^/firewall_one_path'
            provider: firewall_one_user_provider
            custom_authenticator: App\Security\FirewallOneAuthenticator
            login_throttling:
                max_attempts: 5
                interval: '15 minutes'
        firewall_two:
            pattern: '^/'
            provider: firewall_two_user_provider
            custom_authenticator: App\Security\FirewallTwoAuthenticator
            # No login_throttling configured for firewall_two
```

### Additional Context

- The application utilizes distinct user entities and authenticators for each firewall, following Symfony's recommended practices.
- The issue specifically arises in a setup with multiple firewalls when login_throttling is applied to only one of them, suggesting a potential issue with how rate limiting is handled or conflicts with the security component in such configurations.
- This behavior is unexpected and seems to indicate a deeper issue with the interaction between the rate limiter and the security system in Symfony 6.4, particularly in complex security configurations.
