### ISSUE TITLE
[Workflow] Be able to execute more definition validator 

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#54034]
### Description

My client is a first class workflow user and has created custom definition validator. (Note : I should make a talk about this one day 😉)

### Example

```yaml
workflows:
    foobars:
        #... regular things
        definition_validators:
            - ClassThatImplementDefinitionValidatorInterface # cf https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Workflow/Validator/DefinitionValidatorInterface.php
```

---

If the feature is accepted, I'll take care of it
