### ISSUE TITLE
[RFC] display console diff when using `debug:config` & `config:dump-reference`

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#54056]
### Description

# Actually

```php
php bin/console config:dump-reference web_profiler
```

```
web_profiler:
    toolbar:              false
    intercept_redirects:  false
    excluded_ajax_paths:  '^/((index|app(_[\w]+)?)\.php/)?_wdt'
```

```php
php bin/console debug:config web_profiler
```

```
web_profiler:
    toolbar: true
    intercept_redirects: false
    excluded_ajax_paths: '^/((index|app(_[\w]+)?)\.php/)?_wdt'
```

# RFC

**We could imagine something like**

```php
php bin/console debug:config web_profiler --diff-reference-config
```

```diff
web_profiler:
+     toolbar: true
-     toolbar: false
    intercept_redirects: false
    excluded_ajax_paths: '^/((index|app(_[\w]+)?)\.php/)?_wdt'
```

---

Wdyt? do you think it may be doable? it may add lot of value for devs as having all the data locally instead of going to read doc

PS: for now I dont know nor have checked the doability of such things (diff tool, how to get separate command output and handle a smart diff (regarding comments on origin/override or reordering configs keys etc))

### Example

Same for example as https://symfony.com/blog/fast-smart-flex-recipe-upgrades-with-recipes-update
