### ISSUE TITLE
[CACHE] Never hits cache with TagAwareAdapter

### ISSUE THREAD

**Issue by AtCliffUnderline** [symfony/symfony#54097]
### Symfony version(s) affected

6.4.4

### Description

A bit similar to #53825

As in the code below, there is fetching several keys with `mget`. Keys are already exists in database. First fetch of keys with `mget` retrieves them all and create good `$bufferedItems`. 

But after that `getTagVersion` gets wrong tag (screenshot) and unseting them all (TagAwareAdapter.php:191). This bad tag have been stored by this adapter.
![image](https://github.com/symfony/symfony/assets/41080058/4a1a9c97-bd8d-451e-bda5-7e42beb082f1)

And after unset them all it creates items with hit: false.

### How to reproduce

```php
$cache = new TagAwareAdapter(
    new ChainAdapter(
        [
            new ArrayAdapter(300, false, 300),
            new RedisTagAwareAdapter(
                $this->redisConnectionPoolService->getClientByPoolName('cache'),
                'redis.tag.aware.symfony1',
                86400,
                new DefaultMarshaller(false),
            ),
        ],
        300,
    ),
);

$keys = ['key1', 'key2', 'key3'];
$tag = 'some_tag';
$notHitItems = [];
$items = $cache->getItems($keys);
foreach ($items as $item) {
    if (! $item->isHit() || ! is_array($item->get())) {
        $notHitItems[] = $item;
    }
}

foreach ($notHitItems as $item) {
    $item->set(['some_value']);
    $item->expiresAfter(3 * 24 * 60 * 60);
    $item->tag($tag);

    $cache->saveDeferred($item);
}

if (! empty($notHitItems)) {
    $cache->commit();
}
```

### Additional Context

Chain adapter is not really needed here. But this is my production setup.
Seems kinda critical imho

**Comment by AtCliffUnderline** [comment]
@nicolas-grekas Hello! Very sorry for bothering you. Could you have a look at this please? Could be cause of #53846

**Comment by nicolas-grekas** [comment]
Can you try to figure out what happens?

**Comment by AtCliffUnderline** [comment]
I'm trying, but tbh i'm a little bit confused with TagAwareAdapter code :)
Right now I understood that even `invalidateTags` is broken, it removes only tag itself from Redis, without removing KV pairs that belongs to it.

**Comment by stof** [comment]
I don't think `invalidateTags` is broken. See the phpdoc of the class which provides some explanation about its architecture.

**Comment by AtCliffUnderline** [comment]
Well, i compared with my current 5.4.34 and I agree that behaviour of `invalidateTags` is the same. But still something going wrong

**Comment by AtCliffUnderline** [comment]
![image](https://github.com/symfony/symfony/assets/41080058/2cf691a7-288f-43d5-97ba-d5186619927c)
Still not sure why do we compare tag of CacheItem, with version which is random 6 bytes (TagAwareAdapter.php:190). But I don't have enough understanding to conclude that this is a problem.

**Comment by AtCliffUnderline** [comment]
```
Index: vendor/symfony/cache/Adapter/AbstractTagAwareAdapter.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/symfony/cache/Adapter/AbstractTagAwareAdapter.php b/vendor/symfony/cache/Adapter/AbstractTagAwareAdapter.php
--- a/vendor/symfony/cache/Adapter/AbstractTagAwareAdapter.php	
+++ b/vendor/symfony/cache/Adapter/AbstractTagAwareAdapter.php	(date 1709196146551)
@@ -56,7 +56,7 @@
                 $item->isHit = $isHit;
                 // Extract value, tags and meta data from the cache value
                 $item->value = $value['value'];
-                $item->metadata[CacheItem::METADATA_TAGS] = isset($value['tags']) ? array_combine($value['tags'], $value['tags']) : [];
+                $item->metadata[CacheItem::METADATA_TAGS] = isset($value['tags']) ? $value['tags'] : [];
                 if (isset($value['meta'])) {
                     // For compactness these values are packed, & expiry is offset to reduce size
                     $v = unpack('Ve/Nc', $value['meta']);
@@ -107,7 +107,6 @@
                     foreach (array_diff_key($oldTags, $value['tags']) as $removedTag) {
                         $value['tag-operations']['remove'][] = $getId($tagPrefix.$removedTag);
                     }
-                    $value['tags'] = array_keys($value['tags']);
 
                     $byLifetime[$ttl][$getId($key)] = $value;
                     $item->metadata = $item->newMetadata;
```

wdyt? Saving and retrieving tags as associative array . Comparing is correct after this because we not losing these 6 random_bytes which are version.

**Comment by AtCliffUnderline** [comment]
Can I up this? Still thinks this is pretty critical

**Comment by tecbird** [comment]
+1

**Comment by Fahl-Design** [comment]
+1

**Comment by nicolas-grekas** [comment]
I would need more insights to be of any help.

I tried your reproducer @AtCliffUnderline but I miss an observer to tell which behavior is wrong. If I `dump($notHitItems)`, I don't see any difference between v6.4.3 and v6.4.4.

Note that your wiring is really strange: a RedisTagAwareAdapter inside a TagAwareAdapter?

**Comment by Fahl-Design** [comment]
@nicolas-grekas here is an other example, maybe even simpler to reproduce

I have the same issue with this config based on the docs of the chain adapter with redis tag aware i guess (should not matter at all, looks like a cache tag problem anyways)
```yaml
services:
    redis.provider.one:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisTagAwareAdapter', 'createConnection' ]
        arguments:
            - '%env(CACHE_REDIS_DSN_DEFAULT)%/6'

    redis.provider.two:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisTagAwareAdapter', 'createConnection' ]
        arguments:
            - '%env(WEBSHOP_REDIS_DSN_FLATDATA)%'
            - { retry_interval: 1, timeout: 10 }

    'cache.adapter.redis.one':
        parent: 'cache.adapter.redis_tag_aware'
        arguments:
            $redis: '@redis.provider.one'
            $namespace: 'fancy_namespace'
      
    'cache.adapter.redis.two':
        parent: 'cache.adapter.redis_tag_aware'
        arguments:
            $redis: '@redis.provider.two'
            $namespace: 'other_fancy_namespace'

framework:
    cache:
        pools:
            fancy_cache_pool:
                default_lifetime: 31536000  # One year
                adapters:
                    - cache.adapter.redis.one
                    - cache.adapter.redis.two
                tags: true

```

If you run this twice, it is build twice (or more)

```php
        $myCachedData = $this->cachePool->get(
            key: 'fancy_cache_key',
            callback: function (ItemInterface $item): string {
                dump($item->getKey() . ' was build ');
                $item->tag(['tag1', 'tag2']);

                return 'my cached value';
            });
```

> you will see the dump "was build" every time, meaning no cache at all

- clear your cache 
- now remove the tag 
- repeat and see expected 1 time "build"

```php
        $myCachedData = $this->cachePool->get(
            key: 'fancy_cache_key_2',
            callback: function (ItemInterface $item): string {
                dump($item->getKey() . ' was build ');
                // $item->tag(['tag1', 'tag2']); <-- no tags

                return 'my cached value';
            });
```
> cache works as expected

possible cause: 
the use of "TAGS_PREFIX" is inconsistent or just not named correct, sometimes it is used as prefix, sometime suffix. Redis gets data filled with "tags" as suffix and never has data with "tags" as prefix (getTagVersions can not work, because no data in redis with tags as prefix)

- prefix:
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php#L123
- suffix: 
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php#L339

v6.4
![image](https://github.com/symfony/symfony/assets/6690962/61aeffed-be11-4f14-b86c-539f2ef9ed9f)


I hope this may help to fix this

**Comment by nicolas-grekas** [comment]
Can you please put the reproducer in a small app I could clone ?

**Comment by Fahl-Design** [comment]
Of cause, give me a minute or 10 ;)

**Comment by Fahl-Design** [comment]
@nicolas-grekas here we go https://github.com/Fahl-Design/cache-issue-reproducer 

![image](https://github.com/symfony/symfony/assets/6690962/fadb0f53-f3b1-4869-b289-7a2bf7015787)


*edit: inside redis: "tags" is always set as a key suffix NOT prefix

![image](https://github.com/symfony/symfony/assets/6690962/0db2029a-fa39-448d-a100-7dfbd7cb5d9c)

https://github.com/Fahl-Design/cache-issue-reproducer *edit*: updated to make it more visible and symfony v7 as well can be reproduces in v6.4 and v7.0

![image](https://github.com/symfony/symfony/assets/6690962/f93620a7-74c5-474e-8b86-f734698a075f)

![image](https://github.com/symfony/symfony/assets/6690962/09b4fbe9-fc49-45a9-8dc4-4deefe334cea)

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer app @Fahl-Design

Now I'm confused. Is this issue new? For some reason, I had the understanding that this was introduced in 6.4.4, but it's not, right? The reproducer behaves the same with 7.0.0 or 7.0.4, or I missed something.

Could any of you tell me why you're putting a RedisTagAwareAdapter in a chain that's then given to TagAwareAdapter? This doesn't make any sense to me and that'd the other thing I'd need to clarify.

**Comment by Fahl-Design** [comment]
You'r welcome, I found this issue mainly by accident ;) I use 6.4 in an app and this was my first time using a tagged cache pool.
There is a 6.4 version in the reproducer version as well, after that i updated to 7.0 and still reproduce it.

> Could any of you tell me why you're putting a RedisTagAwareAdapter in a chain that's then given to TagAwareAdapter? This doesn't make any sense to me and that'd the other thing I'd need to clarify.

maybe the yaml don't make it clear ;) 
```yaml
...
    redis.provider.two:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisTagAwareAdapter', 'createConnection' ]
...
```
`redis.provider.two` is just the `\Redis` instance https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Cache/Traits/RedisTrait.php#L87



I guess that's from my understanding of the docs 
https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#working-with-tags
https://symfony.com/doc/current/cache.html#creating-a-cache-chain

isn't that how the pools should be set up to work?^^ 
I mean I don't get any autowiring issues and it doesn't look to bad

![image](https://github.com/symfony/symfony/assets/6690962/f4d88ed5-7266-43b8-8b0f-918f3d3859ea)
![image](https://github.com/symfony/symfony/assets/6690962/ed2b6c55-5701-416d-beba-70e5e206cc8f)
![image](https://github.com/symfony/symfony/assets/6690962/70144ca3-d0ce-45f5-bb0c-db239dc29e4c)

I attempt is to setup a cache pool with tags in a chain to fill a second redis instance for an other app. 
It works fine and as expected as long as i don't use the tags

when you run `bin/console app:cache-test --add-tags` you can see the pool will not give you the cached value, and calls the get callback every time.

I had a look at the corresponding code but man, that's not easy to follow (and when tags are involved)
any ideas?
