### ISSUE TITLE
[Messenger] Error "Cannot modify readonly property Doctrine\ORM\EntityManager::$conn" on messenger:consume

### ISSUE THREAD

**Issue by momocode-de** [symfony/symfony#54104]
### Symfony version(s) affected

7.0.4

### Description

The command "messenger:consume" aborts with the following error message:

```
In EntityManager.php line 114:
                                                                     
  [Error]                                                            
  Cannot modify readonly property Doctrine\ORM\EntityManager::$conn  
                                                                     

Exception trace:
  at /var/www/html/project/vendor/doctrine/orm/src/EntityManager.php:114
 Doctrine\ORM\EntityManager->__construct() at /var/www/html/project/var/cache/dev/ContainerYUQveN9/App_KernelDevDebugContainer.php:783
 ContainerYUQveN9\App_KernelDevDebugContainer::getDoctrine_Orm_DefaultEntityManagerService() at /var/www/html/project/var/cache/dev/ContainerYUQveN9/App_KernelDevDebugContainer.php:720
 ContainerYUQveN9\App_KernelDevDebugContainer::ContainerYUQveN9\{closure}() at /var/www/html/project/vendor/symfony/var-exporter/Internal/LazyObjectState.php:61
 Symfony\Component\VarExporter\Internal\LazyObjectState->initialize() at /var/www/html/project/vendor/symfony/var-exporter/LazyGhostTrait.php:118
 ContainerYUQveN9\EntityManagerGhostEbeb667->__get() at /var/www/html/project/vendor/doctrine/orm/src/EntityManager.php:529
 Doctrine\ORM\EntityManager->isOpen() at /var/www/html/project/vendor/doctrine/doctrine-bundle/Registry.php:80
 Doctrine\Bundle\DoctrineBundle\Registry->resetOrClearManager() at /var/www/html/project/vendor/doctrine/doctrine-bundle/Registry.php:66
 Doctrine\Bundle\DoctrineBundle\Registry->reset() at /var/www/html/project/vendor/symfony/http-kernel/DependencyInjection/ServicesResetter.php:57
 Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter->reset() at /var/www/html/project/vendor/symfony/messenger/EventListener/ResetServicesListener.php:34
 Symfony\Component\Messenger\EventListener\ResetServicesListener->resetServices() at /var/www/html/project/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116
 Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke() at /var/www/html/project/vendor/symfony/event-dispatcher/EventDispatcher.php:206
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /var/www/html/project/vendor/symfony/event-dispatcher/EventDispatcher.php:56
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /var/www/html/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:127
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() at /var/www/html/project/vendor/symfony/messenger/Worker.php:110
 Symfony\Component\Messenger\Worker->run() at /var/www/html/project/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:235
 Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() at /var/www/html/project/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /var/www/html/project/vendor/symfony/console/Application.php:1049
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/project/vendor/symfony/framework-bundle/Console/Application.php:125
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/project/vendor/symfony/console/Application.php:318
 Symfony\Component\Console\Application->doRun() at /var/www/html/project/vendor/symfony/framework-bundle/Console/Application.php:79
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/project/vendor/symfony/console/Application.php:169
 Symfony\Component\Console\Application->run() at /var/www/html/project/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/html/project/vendor/autoload_runtime.php:29
 require_once() at /var/www/html/project/bin/console:11

messenger:consume [-l|--limit LIMIT] [-f|--failure-limit FAILURE-LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [--queues QUEUES] [--no-reset] [--] [<receivers>...]
```

This is the message class:

```php
<?php

namespace MyBundle\Message;

class SimpleMessage
{
    public function __construct(
        protected string $string
    ) {
    }

    public function getString(): string
    {
        return $this->string;
    }
}
```

This is the message handler:

```php
<?php

namespace MyBundle\MessageHandler;

use App\Entity\Log;
use Doctrine\ORM\EntityManagerInterface;
use MyBundle\Message\SimpleMessage;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]
class SimpleMessageHandler
{
    public function __construct(
        protected EntityManagerInterface $entityManager
    ) {
    }

    public function __invoke(SimpleMessage $message): void
    {
        $log = new Log();
        $log->setEventType('test');
        $log->setEventData([]);

        $this->entityManager->persist($log);
        $this->entityManager->flush();
    }
}
```

This is my messenger config:

```yaml
framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            MyBundle\Message\SimpleMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
```

As transport I'm using redis: `MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages`
But with doctrine I had the same problem.

As you can see, it's a very basic case. That's why I don't understand why the error occurs. Does anyone have any ideas?

My PHP Version is 8.3

### How to reproduce

Please have a look at the files from the description and try to reproduce it.
