### ISSUE TITLE
[CACHE]  TagAwareAdapter with ChainAdapter as Cache Pool and RedisTagAwareAdapter as pool adapters dose not work with tagged CacheItems

### ISSUE THREAD

**Issue by Fahl-Design** [symfony/symfony#54160]
### Symfony version(s) affected

^6.4 || ^7.0

### Description

rel to #54097

It looks like using cache tags in a chain adapter is broken in `6.4` and `7.0`

```yaml
services:
    redis.provider.one:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisTagAwareAdapter', 'createConnection' ]
        arguments:
            - '%env(DSN_REDIS)%/1'

    redis.provider.two:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisTagAwareAdapter', 'createConnection' ]
        arguments:
            - '%env(DSN_REDIS)%/2'

    'cache.adapter.redis.one':
        parent: 'cache.adapter.redis_tag_aware'
        arguments:
            $redis: '@redis.provider.one'
            $namespace: 'fancy_namespace'

    'cache.adapter.redis.two':
        parent: 'cache.adapter.redis_tag_aware'
        arguments:
            $redis: '@redis.provider.two'
            $namespace: 'other_fancy_namespace'

framework:
    cache:
        pools:
            fancy_cache_pool:
                default_lifetime: 31536000  # One year
                adapters:
                    - cache.adapter.redis.one
                    - cache.adapter.redis.two # issue can be reproduced this only ONE adapter
                tags: true # already tried to use an other pool or redis adapter to store tags same same

```

https://github.com/Fahl-Design/cache-issue-reproducer/blob/main/src/Command/CacheTestCommand.php#L36-64

> @nicolas-grekas here we go https://github.com/Fahl-Design/cache-issue-reproducer
> 
> ![image](https://private-user-images.githubusercontent.com/6690962/309365507-fadb0f53-f3b1-4869-b289-7a2bf7015787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzQwMDIsIm5iZiI6MTcwOTYzMzcwMiwicGF0aCI6Ii82NjkwOTYyLzMwOTM2NTUwNy1mYWRiMGY1My1mM2IxLTQ4NjktYjI4OS03YTJiZjcwMTU3ODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTAxNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjlhZTZjOTllYTk2MTI0NmZjN2IzZDQ4ZDFhYTlkNGM5NjhmNTdmMTFjNTRmM2U5ZTRkNzdjZDk1NmNmZDZiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8bWs7sM6AgO8SLeyvlZXOLVlyCes2SBeH3TX_rV8JOg)
> 
> *edit: inside redis: "tags" is always set as a key suffix NOT prefix
> 
> ![image](https://private-user-images.githubusercontent.com/6690962/309367151-0db2029a-fa39-448d-a100-7dfbd7cb5d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzQwMDIsIm5iZiI6MTcwOTYzMzcwMiwicGF0aCI6Ii82NjkwOTYyLzMwOTM2NzE1MS0wZGIyMDI5YS1mYTM5LTQ0OGQtYTEwMC03ZGZiZDdjYjVkOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTAxNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ5ZGEyMWQwMTA1ZDFlMjUwYjZlMmVlMDVkYmY3Njg2Y2JmYzg4ZTNkZTlmNGExOWE5MGZlNTFhZDUyMjgzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NF_uIdj-sLy38hTLFVAhtVqnFNnds9jLHdEuJqodxMA)
> 
> https://github.com/Fahl-Design/cache-issue-reproducer _edit_: updated to make it more visible and symfony v7 as well can be reproduces in v6.4 and v7.0
> 
> ![image](https://private-user-images.githubusercontent.com/6690962/309376053-f93620a7-74c5-474e-8b86-f734698a075f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzQwMDIsIm5iZiI6MTcwOTYzMzcwMiwicGF0aCI6Ii82NjkwOTYyLzMwOTM3NjA1My1mOTM2MjBhNy03NGM1LTQ3NGUtOGI4Ni1mNzM0Njk4YTA3NWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTAxNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ3NjFlMTk4NzM2NzU2Y2E1OTAzMTdjNDMxNDQyODI2MTNlOGM3MTNhYjU1YjQyMzJmMWNmMzA3MGExNTM5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9kOQU3Kvv-OdvhXTJfKzAVuBL9EjeqediyypDD6HfFM)
> 
> ![image](https://private-user-images.githubusercontent.com/6690962/309376137-09b4fbe9-fc49-45a9-8dc4-4deefe334cea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzQwMDIsIm5iZiI6MTcwOTYzMzcwMiwicGF0aCI6Ii82NjkwOTYyLzMwOTM3NjEzNy0wOWI0ZmJlOS1mYzQ5LTQ1YTktOGRjNC00ZGVlZmUzMzRjZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTAxNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE1MTQwOGI0NDNjMmE5ZjYwNDJjYjhlNzRkZjBjMWQ2MDVlNzU4YjE2YjJhOWU2NTI4YWU5N2I2N2I1MmFlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._fTS5-5eb5agmY-Lbmx3rzWVpd-MZtlEY2MqWE0ikuI)

### How to reproduce

https://github.com/Fahl-Design/cache-issue-reproducer

expected output and more info see 

> https://github.com/symfony/symfony/issues/54097#issuecomment-1973782530

> https://github.com/symfony/symfony/issues/54097#issuecomment-1977477462 

### Additional Context

> You'r welcome, I found this issue mainly by accident ;) I use 6.4 in an app and this was my first time using a tagged cache pool. There is a 6.4 version in the reproducer version as well, after that i updated to 7.0 and still reproduce it.
> 
> > Could any of you tell me why you're putting a RedisTagAwareAdapter in a chain that's then given to TagAwareAdapter? This doesn't make any sense to me and that'd the other thing I'd need to clarify.
> 
> maybe the yaml don't make it clear ;)
> 
> ```yaml
> ...
>     redis.provider.two:
>         class: Redis
>         factory: [ 'Symfony\Component\Cache\Adapter\RedisTagAwareAdapter', 'createConnection' ]
> ...
> ```
> 
> `redis.provider.two` is just the `\Redis` instance https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Cache/Traits/RedisTrait.php#L87
> 
> I guess that's from my understanding of the docs https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#working-with-tags https://symfony.com/doc/current/cache.html#creating-a-cache-chain
> 
> isn't that how the pools should be set up to work?^^ I mean I don't get any autowiring issues and it doesn't look to bad
> 
> ![image](https://private-user-images.githubusercontent.com/6690962/309898226-f4d88ed5-7266-43b8-8b0f-918f3d3859ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzQwMDIsIm5iZiI6MTcwOTYzMzcwMiwicGF0aCI6Ii82NjkwOTYyLzMwOTg5ODIyNi1mNGQ4OGVkNS03MjY2LTQzYjgtOGIwZi05MThmM2QzODU5ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTAxNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY5MjkyMjYzOWIwYjE2YmZhZTU5NjFhYTdhOGU3NzI5ZjcyMWNhYjRlNDYzZmNhYmVhMDI0ODg3YjFjMTQxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vsIowtKPHElDiicNNN1OlYzx-VDRkKUyGVUpXb-Q-OE) ![image](https://private-user-images.githubusercontent.com/6690962/309898349-ed2b6c55-5701-416d-beba-70e5e206cc8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzQwMDIsIm5iZiI6MTcwOTYzMzcwMiwicGF0aCI6Ii82NjkwOTYyLzMwOTg5ODM0OS1lZDJiNmM1NS01NzAxLTQxNmQtYmViYS03MGU1ZTIwNmNjOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTAxNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM5OTFjYWZiMDkxMDJhOTUwODc1MGZlODMxMGMzOTg3YmM2YzlmZTUwZWRjN2I0OGIwYTkyM2M5NDliOTk0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vuPrr9O2Sn5m83ak4OMzulnWAxceEifrfgpZm-s35YA) ![image](https://private-user-images.githubusercontent.com/6690962/309898411-70144ca3-d0ce-45f5-bb0c-db239dc29e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzQwMDIsIm5iZiI6MTcwOTYzMzcwMiwicGF0aCI6Ii82NjkwOTYyLzMwOTg5ODQxMS03MDE0NGNhMy1kMGNlLTQ1ZjUtYmIwYy1kYjIzOWRjMjllNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTAxNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNmNjdlYzNiMjFjYzI5YTU1MTA0ZjFjMWQ3ZmY5OThhZTE0ZjU4ZTkzYWIyYTc5ZTUzYWMwYjJlMTllZDI5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UdCDil3nNVpkV3CI2kniVOYU3v3AYPe5OfBRaESTFbA)
> 
> I attempt is to setup a cache pool with tags in a chain to fill a second redis instance for an other app. It works fine and as expected as long as i don't use the tags
> 
> when you run `bin/console app:cache-test --add-tags` you can see the pool will not give you the cached value, and calls the get callback every time.
> 
> I had a look at the corresponding code but man, that's not easy to follow (and when tags are involved) any ideas?
