### ISSUE TITLE
undefined setFormatter

### ISSUE THREAD

**Issue by vdeville** [symfony/symfony#54166]
### Symfony version(s) affected

6.4

### Description

Hello,

I post this message because i have no more idea to solve my issue. Thanks in advance for your replies
When i switch my env to prod, i have this error, i can not find the cause. No error in dev and nothing in prod log.

When i do `bin/console cache:clear`:
```
In getMonolog_Logger_DeprecationService.php line 24:
                                                                                                      
  Attempted to call an undefined method named "setFormatter" of class "Monolog\Handler\NullHandler".  
                                                                                                      
```
Sentry catch this:
<img width="1043" alt="Capture d’écran 2024-03-05 à 19 39 40" src="https://github.com/symfony/symfony/assets/6104498/52740c48-d508-4e00-849d-729b2a7af08d">

Versions of packages:
```
behat/transliterator | v1.5.0
clue/stream-filter | v1.7.0
cocur/slugify | v4.5.1
composer/ca-bundle | 1.4.1
doctrine/annotations | 1.14.3
doctrine/cache | 2.2.0
doctrine/collections | 2.2.0
doctrine/common | 3.4.3
doctrine/dbal | 3.8.3
doctrine/deprecations | 1.1.3
doctrine/doctrine-bundle | 2.11.3
doctrine/doctrine-migrations-bundle | 3.3.0
doctrine/event-manager | 2.0.0
doctrine/inflector | 2.0.10
doctrine/instantiator | 2.0.0
doctrine/lexer | 2.1.1
doctrine/migrations | 3.7.3
doctrine/orm | 2.19.0
doctrine/persistence | 3.3.1
doctrine/sql-formatter | 1.2.0
egulias/email-validator | 4.0.2
friendsofphp/proxy-manager-lts | v1.0.16
friendsofsymfony/ckeditor-bundle | 2.5.0
gedmo/doctrine-extensions | v3.15.0
google/recaptcha | 1.3.0
gotenberg/gotenberg-php | v2.1.0
guzzlehttp/guzzle | 6.5.8
guzzlehttp/promises | 1.5.3
guzzlehttp/psr7 | 1.9.1
helios-ag/fm-elfinder-bundle | 12.5
hercule-tech/jours-feries-france | 1.4
http-interop/http-factory-guzzle | 1.2.0
imagine/imagine | 1.3.5
jean85/pretty-package-versions | 2.0.5
jms/metadata | 2.8.0
karser/karser-recaptcha3-bundle | v0.1.26
knplabs/knp-components | v3.6.0
knplabs/knp-paginator-bundle | v5.9.0
laminas/laminas-code | 4.13.0
laravel/pint | v1.14.0
league/csv | 9.15.0
liip/imagine-bundle | 2.12.2
masterminds/html5 | 2.8.1
mobiledetect/mobiledetectlib | 3.74.3
monolog/monolog | 3.5.0
nelmio/security-bundle | v3.1.1
nikic/php-parser | v5.0.1
php-http/client-common | 2.7.1
php-http/discovery | 1.19.2
php-http/guzzle6-adapter | v2.0.2
php-http/httplug | 2.4.0
php-http/message | 1.16.0
php-http/message-factory | 1.1.0
php-http/promise | 1.3.0
phpdocumentor/reflection-common | 2.2.0
phpdocumentor/reflection-docblock | 5.3.0
phpdocumentor/type-resolver | 1.8.2
phpstan/phpdoc-parser | 1.26.0
phpstan/phpstan | 1.10.59
presta/sitemap-bundle | v3.3.1
psr/cache | 3.0.0
psr/clock | 1.0.0
psr/container | 2.0.2
psr/event-dispatcher | 1.0.0
psr/http-client | 1.0.3
psr/http-factory | 1.0.2
psr/http-message | 1.1
psr/link | 2.0.1
psr/log | 3.0.0
ralouphie/getallheaders | 3.0.3
rector/rector | 1.0.2
scienta/doctrine-json-functions | 5.4.0
sentry/sdk | 3.6.0
sentry/sentry | 3.22.1
sentry/sentry-symfony | 4.14.0
stof/doctrine-extensions-bundle | v1.11.0
studio-42/elfinder | 2.1.65
symfony/apache-pack | v1.0.1
symfony/asset | v6.4.3
symfony/browser-kit | v6.4.3
symfony/cache | v6.4.4
symfony/cache-contracts | v3.4.0
symfony/clock | v6.4.5
symfony/config | v6.4.4
symfony/console | v6.4.4
symfony/css-selector | v6.4.3
symfony/debug-bundle | v6.4.3
symfony/dependency-injection | v6.4.4
symfony/deprecation-contracts | v3.4.0
symfony/doctrine-bridge | v6.4.5
symfony/dom-crawler | v6.4.4
symfony/dotenv | v6.4.4
symfony/error-handler | v6.4.4
symfony/event-dispatcher | v6.4.3
symfony/event-dispatcher-contracts | v3.4.0
symfony/expression-language | v6.4.3
symfony/filesystem | v6.4.3
symfony/finder | v6.4.0
symfony/flex | v1.21.6
symfony/form | v6.4.4
symfony/framework-bundle | v6.4.4
symfony/http-client | v6.4.5
symfony/http-client-contracts | v3.4.0
symfony/http-foundation | v6.4.4
symfony/http-kernel | v6.4.5
symfony/intl | v6.4.3
symfony/mailer | v6.4.4
symfony/maker-bundle | v1.56.0
symfony/mime | v6.4.3
symfony/monolog-bridge | v6.4.4
symfony/monolog-bundle | v3.10.0
symfony/notifier | v6.4.3
symfony/options-resolver | v6.4.0
symfony/password-hasher | v6.4.4
symfony/phpunit-bridge | v6.4.4
symfony/polyfill-intl-grapheme | v1.29.0
symfony/polyfill-intl-icu | v1.29.0
symfony/polyfill-intl-idn | v1.29.0
symfony/polyfill-intl-normalizer | v1.29.0
symfony/polyfill-mbstring | v1.29.0
symfony/polyfill-php80 | v1.29.0
symfony/polyfill-php83 | v1.29.0
symfony/process | v6.4.4
symfony/property-access | v6.4.4
symfony/property-info | v6.4.3
symfony/proxy-manager-bridge | v6.4.3
symfony/psr-http-message-bridge | v6.4.3
symfony/routing | v6.4.5
symfony/security-bundle | v6.4.5
symfony/security-core | v6.4.3
symfony/security-csrf | v6.4.3
symfony/security-http | v6.4.4
symfony/serializer | v6.4.4
symfony/service-contracts | v3.4.1
symfony/stopwatch | v6.4.3
symfony/string | v6.4.4
symfony/translation | v6.4.4
symfony/translation-contracts | v3.4.1
symfony/twig-bridge | v6.4.4
symfony/twig-bundle | v6.4.4
symfony/validator | v6.4.4
symfony/var-dumper | v6.4.4
symfony/var-exporter | v6.4.4
symfony/web-link | v6.4.3
symfony/web-profiler-bundle | v6.4.4
symfony/webpack-encore-bundle | v1.17.2
symfony/yaml | v6.4.3
twig/extensions | v1.5.4
twig/extra-bundle | v3.7.1
twig/twig | v2.16.0
ua-parser/uap-php | v3.9.14
vich/uploader-bundle | 2.3.1
webmozart/assert | 1.11.0


```

### How to reproduce

Switch to prod env

**Comment by HypeMC** [comment]
Could you show your monolog configuration?

**Comment by vdeville** [comment]
Hello, 
Of course, i found a old configuration when symfony recipes put null on config.
I remove it but, now i have logging loop.

```
20:36:18 WARNING   [mailer] A possible infinite logging loop was detected and aborted. It appears some of your handler code is triggering logging, see the previous log record for a hint as to what may be the cause.
{"message":"A possible infinite logging loop was detected and aborted. It appears some of your handler code is triggering logging, see the previous log record for a hint as to what may be the cause.","context":{},"level":300,"level_name":"WARNING","channel":"mailer","datetime":"2024-03-05T20:36:18.256259+00:00","extra":{}}
{"message":"Email transport \"Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport\" starting","context":{},"level":100,"level_name":"DEBUG","channel":"mailer","datetime":"2024-03-05T20:36:18.255914+00:00","extra":{}}
{"message":"Email transport \"Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport\" starting","context":{},"level":100,"level_name":"DEBUG","channel":"mailer","datetime":"2024-03-05T20:36:18.255644+00:00","extra":{}}
```

Monolog.yaml
```
monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - security

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: ["!event"]
      # uncomment to get logging in your browser
      # you may have to allow bigger header sizes in your Web server configuration
      #firephp:
      #    type: firephp
      #    level: info
      #chromephp:
      #    type: chromephp
      #    level: info
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      #            symfony_mailer:
      #                type: symfony_mailer
      #                from_email: 'security@xx.fr'
      #                to_email: 'xx@xx.fr'
      #                subject: 'Security alert xx! %%message%%'
      #                channel: security
      #                formatter: monolog.formatter.html
      #                content_type: text/html
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: stream
        path: php://stderr
        level: error
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: stream
        channels: ["deprecation"]
        path: php://stderr
        formatter: monolog.formatter.json
```
Do you want i open new issue about my monolog problem ?

Thanks
