### ISSUE TITLE
All resource exclude paths are completely ignored

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#54212]
### Symfony version(s) affected

6.4.3

### Description

Given the example in [the documentation](https://symfony.com/doc/current/routing.html#route-groups-and-prefixes):

```yaml
# config/routes/attributes.yaml
controllers:
    resource: '../../src/Controller/'
    type: attribute
    # this is added to the beginning of all imported route URLs
    prefix: '/blog'
    # this is added to the beginning of all imported route names
    name_prefix: 'blog_'
    # these requirements are added to all imported routes
    requirements:
        _locale: 'en|es|fr'

    # An imported route with an empty URL will become "/blog/"
    # Uncomment this option to make that URL "/blog" instead
    # trailing_slash_on_root: false

    # you can optionally exclude some files/subdirectories when loading attributes
    # (the value must be a string or an array of PHP glob patterns)
    # exclude: '../../src/Controller/{Debug*Controller.php}'
```

If one were to actually uncomment the `exclude` line, it would have no effect whatsoever.

### How to reproduce

Uncomment the exclude line.

```yaml
# config/routes/attributes.yaml
controllers:
    resource: '../../src/Controller/'
    type: attribute
    # this is added to the beginning of all imported route URLs
    prefix: '/blog'
    # this is added to the beginning of all imported route names
    name_prefix: 'blog_'
    # these requirements are added to all imported routes
    requirements:
        _locale: 'en|es|fr'

    # An imported route with an empty URL will become "/blog/"
    # Uncomment this option to make that URL "/blog" instead
    # trailing_slash_on_root: false

    # you can optionally exclude some files/subdirectories when loading attributes
    # (the value must be a string or an array of PHP glob patterns)
    exclude: '../../src/Controller/{Debug*Controller.php}'
```

### Possible Solution

This appears to be because of [this line](https://github.com/symfony/symfony/blob/5dbc82d477c684f69803044e282f1b54e368d10d/src/Symfony/Component/Config/Loader/FileLoader.php#L75), and more specifically, this condition:

```php
\strlen($resource) !== ($i = strcspn($resource, '*?{['))
```

This seems to imply that if the resource itself is not a glob then all exclusion processing will be dropped. This is not documented anywhere nor does it make any particular sense to me.

### Additional Context

Relates to #39588.
