### ISSUE TITLE
YAML routing host overrides annotations

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#54211]
### Symfony version(s) affected

6.4.3

### Description

Looking for a way to set the default hostname for routes, this [SO answer](https://stackoverflow.com/a/68128347/1041515) should be correct, but as [a comment notes](https://stackoverflow.com/questions/59410426/configure-a-default-host-for-routes-in-symfony-4#comment130995996_68128347), setting the host name in YAML clobbers any and all annotations parsed thereafter.

That is, YAML that defines an annotations/attributes resource must be parsed before the attributes:

```yaml
# config/routes/routes.yaml

controllers:
  resource:
    path: ../../src
    namespace: Foo\Bar
  type: attribute
  host: example.com
```

So it follows that logically that which is parsed later should override that which is declared earlier.

```php
#[Route(host: 'example.org')]
final class Foo extends AbstractController {}
```

Yet it does not: setting the host in YAML clobbers _all_ `Route()` attributes. Thus it appears impossible to set a default host since we are not in control of this parse order.

### How to reproduce

See above.
