### ISSUE TITLE
[RFC][Messenger] Remove ResetInterface from InMemory transport

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#54293]
### Description

Hi,

Im wondering if InMemoryTransport should implement ResetInterface actually.

It breaks functional testing thru `messenger:consume` which reboots the kernel, which resets the transports.

It seems reasonable to manage in memory transport using manual ack/reject, like transports in real life.

**Comment by onEXHovia** [comment]
Initially in #29097 there was an added `NullTransport`, im think there must be two transports `InMemoryTransport ` without implemented `ResetInterface` and `NullTransport`

I agree with the [comment](https://github.com/symfony/symfony/pull/29097#issuecomment-474918520) @stof 

> If you never flush your MemoryTransport, it would leak memory. So using it instead of a NullTransport looks wrong (having to flush something when you expect it to be a blackhole is not intuitive)

One example, we want the message to be retry(retry_strategy) and after max retries was not sent in global failed transport and was removed from the queue.

Сonfig  example, memory transport looks is not intuitive
```yaml
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            failed: 'doctrine://default?queue_name=failed'
            failed_memory: 'in-memory://'
            example:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/example'
                failure_transport: failed_memory
                retry_strategy:
                    max_retries: 5
```
