### ISSUE TITLE
X_FORWARDED_PREFIX not working with relative url (path)

### ISSUE THREAD

**Issue by barbuslex** [symfony/symfony#54457]
### Symfony version(s) affected

5.4.34

### Description

It seems there are a conflict on relative url with X_FORWARDED_PREFIX defined.

### How to reproduce

My symfony app respond like this : 
- In Intranet : http://www3.intranet/sfapp/
- In Extranet (reverse proxy) : https://extranet.domain.com/www3/sfapp/

I have override X_FORWARDED variables like this   : 
```php
# public/index.php
if(array_key_exists('HTTP_X_FORWARDED_SERVER', $_SERVER)) {
	$_SERVER['HTTP_X_FORWARDED_HOST'] = $_SERVER['HTTP_X_FORWARDED_SERVER'];
	$_SERVER['HTTP_X_FORWARDED_PROTO'] = 'https';
	$_SERVER['HTTP_X_FORWARDED_PORT'] = '443';
	$_SERVER['HTTP_X_FORWARDED_PREFIX'] = '/www3/';
}
```

```yaml
# config/packages/framework.yaml
framework:
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
```

In my twig file i have set 2 url like this : 
```twig
{# templates/admin_login.html.twig #}

{% set login_url = path('admin_login') %}
<form action="{{ login_url }}" method="post" role="form">
...
    <input type="hidden" value="{{ login_url }}">
    <input type="hidden" value="{{ url('admin_login') }}">
</form>
```

I have this on extranet endpoint (works perfectly in intranet) : 
```twig
{# WHY twice www3 here ??? #}
<form action="/www3/www3/sfapp/login" method="post" role="form">
    <input type="hidden" value="/www3/sfapp/login">
    <input type="hidden" value="https://extranet.domain.com/www3/sfapp/login">
</form>
```

I don't understand why i have twice www3 in form tag  ? I have same issue for assets url...

Could you have an explication or its a bug ?
