### ISSUE TITLE
twilio-notifier: SmsMessage::$options must not be accessed before initialization

### ISSUE THREAD

**Issue by drzraf** [symfony/symfony#54482]
### Symfony version(s) affected

6.4.x

### Description

I'm using a combination of messenger + notifier + twilio-notifier (among others) as [suggested](https://symfony.com/doc/current/messenger.html)

When the messenger is run with `messenger:consume` I started getting an error (with Symfony 6.4.x) that I didn't experienced previously with 5.4

(`/bin/console messenger:consume async`)

```
#0 /vendor/symfony/twilio-notifier/TwilioTransport.php(52): Symfony\\Component\\Notifier\\Message\\SmsMessage->getOptions()
#1 /vendor/symfony/notifier/Transport/Transports.php(59): Symfony\\Component\\Notifier\\Bridge\\Twilio\\TwilioTransport->supports()
#2 /vendor/symfony/notifier/Messenger/MessageHandler.php(32): Symfony\\Component\\Notifier\\Transport\\Transports->send()
#3 /vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(152): Symfony\\Component\\Notifier\\Messenger\\MessageHandler->__invoke()
#4 /vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(91): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->callHandler()
#5 /vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(71): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()
#6 /vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()
#7 /vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()
#8 /vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()
#9 /vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()
#10 /vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()
#11 /vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()
#12 /vendor/symfony/messenger/Worker.php(162): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()
#13 /vendor/symfony/messenger/Worker.php(109): Symfony\\Component\\Messenger\\Worker->handleMessage()
#14 /vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(238): Symfony\\Component\\Messenger\\Worker->run()
#15 /vendor/symfony/console/Command/Command.php(326): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()
#16 /vendor/symfony/console/Application.php(1096): Symfony\\Component\\Console\\Command\\Command->run()
#17 /vendor/symfony/framework-bundle/Console/Application.php(126): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /vendor/symfony/console/Application.php(324): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()
#19 /vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\\Component\\Console\\Application->doRun()
#20 /vendor/symfony/console/Application.php(175): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()
#21 /vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(49): Symfony\\Component\\Console\\Application->run()
#22 /vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\ConsoleApplicationRunner->run()
#23 /bin/console(15): require_once(\'...\')
#24 {main}
```

This is specific to this notifier: Disabling it make the others work.

### How to reproduce

```php
namespace App\MessageHandler;

use Psr\Log\LoggerInterface;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Notifier\Recipient\Recipient;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]


class NotificationHandler
{

    private NotifierInterface $notifier;

    public function __construct(NotifierInterface $notifier)
    {
        $this->notifier = $notifier;
    }

    public function __invoke(\stdClass $notifPayload): void
    {
        $notification = (new Notification('Foo', ['email', 'sms']));
        $recipient_obj = new Recipient($phone); // The SMS one
        $this->notifier->send($notification, $recipient_obj);
    }
}
```

```yaml
# config/packages/notifier.yaml
framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
            email: '%env(MAILER_DSN)%'
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
            ovhcloud: '%env(OVHCLOUD_DSN)%'
            sms: '%env(TWILIO_DSN)%'
```

```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        reset_on_message: true
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    delete_after_ack: true
                    delete_after_reject: false
                retry_strategy:
                    max_retries: 6
                    multiplier: 2
                    delay: 10000

        routing:
            # Route your messages to the transports
            '*': async
```

### Additional Context

```
symfony/messenger	v6.4.6
symfony/notifier	v6.4.3
symfony/ovh-cloud-notifier	v6.4.3
symfony/redis-messenger	v6.4.4
symfony/slack-notifier	v6.4.3
symfony/twilio-notifier	v6.4.3
```
