### ISSUE TITLE
[MESSENGER] #[AsMessageHandler(fromTransport: 'sync')] - The handler run with sync transport and async transport

### ISSUE THREAD

**Issue by devbysb** [symfony/symfony#54543]
### Symfony version(s) affected

6.4.6

### Description

Hi, I use symfony messenger with one bus and sync/async transport with doctrine.
When I dispatch a message it "go" on the 2 transports (It's my configuration), but the handler is configured to check the fromTransport and normally run only if the transport is sync.  The problem is the handler run for async and sync transport it doesn't consider the fromTransport.

### How to reproduce

My messenger.yaml

```yaml
framework:
    messenger:

        buses:
            bus.event:
                default_middleware:
                    enabled: true
                    # set "allow_no_handlers" to true (default is false) to allow having
                    # no handler configured for this bus without throwing an exception
                    allow_no_handlers: true

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: async
                retry_strategy:
                    max_retries: 3
                    delay: 60000
                    multiplier: 2
                    max_delay: 0
                serializer: messenger.transport.symfony_serializer

            failed: 'doctrine://default?queue_name=failed'

            sync: 'sync://'

        routing:
            # Route your messages to the transports
            App\Message\Event\MessageEventInterface: [async, sync]


when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'in-memory://'

```

And my handler 

```php
declare(strict_types=1);

namespace App\MessageHandler\Event\History\User;

use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler(fromTransport: 'sync')]
class HistoryUserEnabledEvent
{
    public function __invoke(UserEnabledEvent $UserEnabledEvent): void
    {
	// todo
    }
}
```
