### ISSUE TITLE
Unable to login in production when `getUserIdentifier` uses an entity and monolog fingers_crossed handler set to "error"

### ISSUE THREAD

**Issue by gremo** [symfony/symfony#54641]
### Symfony version(s) affected

7.0

### Description

I spent **literally days** to find out this bug. It was really a nightmare. Title may sound strange and if fact this bug is really odd.

## When

1. You are in production
2. You implement [`getUserIdentifier`](https://github.com/gremo/symfony-login-bug/blob/main/src/Entity/User.php#L102) using a related entity, in my example `User` has a many-to-one non-nullable relation to `AppProfile`:

```php
public function getUserIdentifier(): string
{
  return sprintf('%s@%s', $this->username, $this->profile->getCode());
}
```

3. In your [`monolog.yaml`](https://github.com/gremo/symfony-login-bug/blob/main/config/packages/monolog.yaml) configuration, you are using the "fingers_crossed" handler with an action_level set to "error"

```yaml
when@prod:
    monolog:
        handlers:
            filter_for_errors:
                type: fingers_crossed
                # if *one* log is error or higher, pass *all* to file_log
                action_level: error
                handler: file_log

            # now passed *all* logs, but only if one log is error or higher
            file_log:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
```

## What happens

1. You will not be able to login at all
2. There are no errors in `var/log/prod.log`, you can't figure out what's happening

## What I've tried

```php
public function getUserIdentifier(): string
{
  // Doesn't work anyways
  return sprintf('%s@%s', $this->username, (string) $this->profile->getCode());

  // No issues (this is not a problem related to null values passed to sprintf)
  return sprintf('%s@%s', $this->username, null);

  // No issues
  return $this->username;
}
```

## What's even stranger

In your `monolog.yaml` configuration set [`action_level`](https://github.com/gremo/symfony-login-bug/blob/main/config/packages/monolog.yaml#L47) to "debug" instead of "error" and login will always work.

### How to reproduce

https://github.com/gremo/symfony-login-bug

### Additional Context

Inside `getUserIdentifier`, when you click "login", the `$this->profile` member is actually a Doctrine Proxy:

```php
public function getUserIdentifier(): string
{
  dd($this->profile);
  return sprintf('%s@%s', $this->username, $this->profile->getCode());
}
```

![image](https://github.com/symfony/symfony/assets/1532616/9f91d9b5-182e-4252-9263-fcf84fb062a2)

My original issue on monolog-bundle repository: https://github.com/symfony/monolog-bundle/issues/476
