### ISSUE TITLE
Class "" used for service "security.listener.session.secured_area" cannot be found.

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#54672]
### Symfony version(s) affected

6.4.4

### Description

After updating from `v5.4` to `v6.4`, I'm getting this error:
```
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException:
Class "" used for service "security.listener.session.secured_area" cannot be found.

  at vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php:129
  at Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass->process(object(ContainerBuilder))
     (vendor/symfony/dependency-injection/Compiler/Compiler.php:80)
  at Symfony\Component\DependencyInjection\Compiler\Compiler->compile(object(ContainerBuilder))
     (vendor/symfony/dependency-injection/ContainerBuilder.php:767)
  at Symfony\Component\DependencyInjection\ContainerBuilder->compile()
     (vendor/symfony/http-kernel/Kernel.php:506)
  at Symfony\Component\HttpKernel\Kernel->initializeContainer()
     (app/AppKernel.php:137)
```

### How to reproduce

Hard to tell, since there is a lot of project specifics, but firewall looks something like this:

```yaml
secured_area:
    custom_authenticators:
        - my.security.login.login_form_authenticator
    user_checker: my.security.user.user_checker
    form_login:
        default_target_path: my_home
        login_path: my_login
        require_previous_session: false
```

### Additional Context

I looked at https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L425-L427 and in deed, the class is never set.
