### ISSUE TITLE
Undo bindings when they're unused?

### ISSUE THREAD

**Issue by janopae** [symfony/symfony#54693]
### Symfony version(s) affected

\>=3.4.0-BETA1

### Description

In `config_test.yaml`, I replaced service definitions with mocks. Now, a parameter binding defined in the general `config.yaml` is not needed anymore. Because of this, the Kernel doesn't compile and throws `InvalidArgumentException: A binding is configured for an argument of type "string" named … under "_defaults" in file…, but no corresponding argument has been found. It may be unused and should be removed, or it may have a typo`

It seems like I'm supposed to undo the bind in the testing config, but I can't undo yaml keys.

### How to reproduce

Bind a parameter by name and/or type and use it in a service:

```yaml
# services.yaml
services:
    _defaults:
        bind:
            string $mystring: 'Hello'
```

```php
public class MyClass {
    public function __construct(
        public readonly string $mystring;
    ){};
}
```

Overwrite the using service in your test config:

```yaml
# config_test.yaml
services:
    PHPUnit\Framework\MockObject\Generator\Generator: ~

    MyClass:
        factory: ['@PHPUnit\Framework\MockObject\Generator\Generator', 'testDouble']
        arguments:
            $type: '\MyClass'
            $mockObject: true
            $callOriginalConstructor: false
            $callOriginalClone: false
            $cloneArguments: false
            $allowMockingUnknownTypes: false
        public: true
```

See the mentioned error every time you use the container in a KernelTestCase.

### Possible Solution

Don't throw an exception when there are unused bindings – raise warning or info instead
