### ISSUE TITLE
Attempted to call an undefined method named "setCallbackWrapper" of class "Symfony\Component\Cache\Adapter\TraceableAdapter".

### ISSUE THREAD

**Issue by loevgaard** [symfony/symfony#54783]
### Symfony version(s) affected

6.4.*

### Description

I added this configuration:

```yaml
framework:
    cache:
        pools:
            async.cache:
                early_expiration_message_bus: messenger.default_bus
```

from this page: https://symfony.com/doc/current/cache.html#computing-cache-values-asynchronously

and got this exception:

```
[Symfony\Component\ErrorHandler\Error\UndefinedMethodError]
Attempted to call an undefined method named "setCallbackWrapper" of class "Symfony\Component\Cache\Adapter\TraceableAdapter".
```

The method `setCallbackWrapper` it's trying to call is defined in the `\Symfony\Component\Cache\Traits\ContractsTrait` and it might be therefore it's assumed that it's also present on the `TraceableAdapter`.

### How to reproduce

I _think_ by just adding the above configuration it will trigger the exception. I have not tried this on a fresh Symfony install.
