### ISSUE TITLE
[Messenger][AMQP] Allow to opt out to autosetup delay exchange in configuration

### ISSUE THREAD

**Issue by pierreboissinot** [symfony/symfony#54831]
### Description

It seems that we cannot configure symfony/messenger to prevent auto setup for delay exchange.

https://github.com/symfony/symfony/blob/616c58288cb3191cd13b025e362be2cb483a0244/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L113

When an application is just a publisher but doesn't consume any queue, there is no need to auto setup a delay exchange.

I'm actually working on a PR about this.

### Example

Proposal:
Add the option `auto_setup` for delay, default true.

```yaml
framework:
    messenger:
        transports:
            async_transport:
        [...]
       
                # https://symfony.com/doc/current/messenger.html#amqp-transport
                options:
                    delay:
                        auto_setup: false
                    queues: []
[...]
```

With this option, the delay exchange will not be declared there:
https://github.com/symfony/symfony/blob/616c58288cb3191cd13b025e362be2cb483a0244/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L470

Also, add a condition in Connection->setup to call setupDelayExchange only if delay exchange is not disabled (transport retry_strategy.max_retries equals 0 ? Not sure because delay may be use in other use cases than retry)
