### ISSUE TITLE
 [Security Bundle] Unable to log in via API 

### ISSUE THREAD

**Issue by danielpeci** [symfony/symfony#54873]
### Symfony version(s) affected

7.0.7

### Description

I'm currently working with Symfony 7.0 on the backend and React on the frontend. Additionally, I'm using API Platform and the Lexik JWT Authentication Bundle.

The authentication process should unfold as follows: when a registered user attempts to log in, if their credentials are valid, a token should be generated, granting them access to the dashboard.

Here's what I've accomplished thus far:

- I have created ApiController following [Symfony Documentation](https://symfony.com/doc/current/security.html#json-login)
- When I process the login, I only get 200 Status code with Token back. But the token isn't being saved in session or cookie, leaving the user unable to access the dashboard (The User is not authenticated) 

### How to reproduce

APIController.php
```php
class ApiLoginController extends AbstractController
{
    #[Route('/api/login', name: 'api_login', methods: ['POST'])]
    public function index(#[CurrentUser] $user, JWTTokenManagerInterface $tokenManager): Response
    {
        if (null === $user) {
            return $this->json([
                'message' => 'missing credentials',
            ], Response::HTTP_UNAUTHORIZED);
        }

        $token = $tokenManager->create($user);

        return $this->json([
            'user' => $user->getUserIdentifier(),
            'token' => $token,
        ]);
    }
}
```

security.yml
```yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: api_login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/
            stateless: true
            jwt: ~


    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY}
```

Login.jsx
```
const Login = () => {
    const handleSubmit = (e) => {
        e.preventDefault();
        const email = e.target.loginemail;
        const password = e.target.loginpassword;
        fetch('api/login', {
            credentials: 'same-origin',
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({

                email: e.target.loginemail.value,
                password: e.target.loginpassword.value
            }),
        })
            .then(response => {
                response.json().then((data) => {
                    if(data.user){
                        window.location.href="/dashboard"
                    }
                });
            });
    };
```

### Additional Context
Additionally I inserted into LoginController a `dump($this->isGranted('IS_AUTHENTICATED_FULLY'));` for debugging purposes, but I get always `false`, even after login

![Screenshot 2024-05-09 at 21 48 11](https://github.com/symfony/symfony/assets/36742635/d21dba80-be7c-422f-8c3c-077ec3ecadad)
![Screenshot 2024-05-09 at 21 48 26](https://github.com/symfony/symfony/assets/36742635/4a6a8f78-a513-441b-9b5b-a5c431cbba0a)
