### ISSUE TITLE
[VarExporter] Cannot access property starting with "\0"

### ISSUE THREAD

**Issue by ivanbogomoloff** [symfony/symfony#54905]
### Symfony version(s) affected

7.0.6

### Description

I have entity `App\Entity\Organization` 

```php
namespace App\Entity;

class Organization {
 #[ORM\Column(length: 255)]
    private ?string $title = null;

public function getTitle(): ?string
    {
        return $this->title;
    }
}
```
and form with `data_class` = `App\Entity\Organization`

and route like this

```php
#[Route('/{id}/edit', name: self::ROUTE_APP_ADMIN_ORGANIZATION_EDIT, methods: ['GET', 'POST'])]
    public function edit(Request $request, Organization $organization, EntityManagerInterface $entityManager): Response
    {
       form = $this->createForm(OrganizationForm::class, $organization);
    }
```

When i change fields in entity ( for example add new field ), add migration, migrate. Then if i don't reset cache manually or do not restart my php-fpm server, i get error `Cannot access property starting with "\0"`

```
Error:
Cannot access property starting with "\0"

  at vendor/symfony/var-exporter/LazyGhostTrait.php:207
  at Proxies\__CG__\App\Entity\Organization->__set()
     (vendor/symfony/var-exporter/Internal/Hydrator.php:156)
  at Proxies\__CG__\App\Entity\Organization->Symfony\Component\VarExporter\Internal\{closure}()
     (vendor/symfony/var-exporter/Hydrator.php:72)
  at Symfony\Component\VarExporter\Hydrator::hydrate()
     (vendor/symfony/var-exporter/Internal/LazyObjectState.php:58)
  at Symfony\Component\VarExporter\Internal\LazyObjectState->initialize()
     (vendor/symfony/var-exporter/LazyGhostTrait.php:120)
  at Proxies\__CG__\App\Entity\Organization->__get()
     (src/Entity/Organization.php:117)
  at App\Entity\Organization->getTitle()
     (vendor/symfony/property-access/PropertyAccessor.php:388)
  at Symfony\Component\PropertyAccess\PropertyAccessor->readProperty()
     (vendor/symfony/property-access/PropertyAccessor.php:99)
  at Symfony\Component\PropertyAccess\PropertyAccessor->getValue()
     (vendor/symfony/form/Extension/Core/DataAccessor/PropertyPathAccessor.php:80)
  at Symfony\Component\Form\Extension\Core\DataAccessor\PropertyPathAccessor->getPropertyValue()
     (vendor/symfony/form/Extension/Core/DataAccessor/PropertyPathAccessor.php:45)
  at Symfony\Component\Form\Extension\Core\DataAccessor\PropertyPathAccessor->getValue()
     (vendor/symfony/form/Extension/Core/DataAccessor/ChainAccessor.php:37)
  at Symfony\Component\Form\Extension\Core\DataAccessor\ChainAccessor->getValue()
     (vendor/symfony/form/Extension/Core/DataMapper/DataMapper.php:50)
  at Symfony\Component\Form\Extension\Core\DataMapper\DataMapper->mapDataToForms()
     (vendor/symfony/form/Form.php:319)
  at Symfony\Component\Form\Form->setData()
     (vendor/symfony/form/Form.php:408)
  at Symfony\Component\Form\Form->initialize()
     (vendor/symfony/form/FormBuilder.php:176)
  at Symfony\Component\Form\FormBuilder->getForm()
     (vendor/symfony/form/FormFactory.php:28)
  at Symfony\Component\Form\FormFactory->create()
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:323)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->createForm()
     (src/Controller/Admin/Organization/OrganizationController.php:98)
  at App\Controller\Admin\Organization\OrganizationController->edit()
     (vendor/symfony/http-kernel/HttpKernel.php:178)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:185)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/var/www/html/vendor/autoload_runtime.php')
     (public/index.php:5)                
```

If i change code without `ParamConverter` all works fine. I get `not proxied` entity and var exporter works fine

### How to reproduce

Create route with annotation with `#[Route('/{id}/edit', name: 'my_route', methods: ['GET', 'POST'])]` with `id` param to convert param to entity and make entity for this with `title` property. Then create form with `data_class` in `configureOptions`

PHP version is: `PHP 8.2.18 (cli) (built: Apr 11 2024 19:20:54) (NTS)`

Database is `postgresql`

Setttings for `doctrine.yaml`

```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: true
```

### Possible Solution

Custom ParamConverter or use manually finding entity by params

This works fine.

```php
#[Route('/{id}/edit', name: 'my_route', methods: ['GET', 'POST'])]
public function edit(Request $request, int $id, OrganizationRepository $organizationRepo, EntityManagerInterface $entityManager): Response
  {
$organizationRepo->find($id); 
}
```

### Additional Context

![sfbug7](https://github.com/symfony/symfony/assets/2998109/c60519e4-5e54-4d6e-a270-974810e22748)
