### ISSUE TITLE
Scoped http client applies retry logic for URLs not matching base_uri

### ISSUE THREAD

**Issue by mykolasjarasiunas** [symfony/symfony#54923]
### Symfony version(s) affected

6.4.0

### Description

In case a scoped http client is used for URLs which does not match base_uri, retrying options are still applied (while e.g. timeout or custom header options are not). 
The documentation states: `Options defined for scoped clients apply only to URLs that match [...] their base_uri [...]. Non-matching URLs always use default options.` https://symfony.com/doc/6.4/reference/configuration/framework.html
Not sure if this is a code bug or ambiguous documentation

### How to reproduce

Define http client config:
```
framework:
    http_client:
        default_options:
            retry_failed:
                max_retries: 1
        scoped_clients:
            my_test.client:
                base_uri: 'http://example.com/'
                retry_failed:
                    http_codes:
                        500: true
                    max_retries: 5
```
Directly inject scoped client:
```
services:
    App\Controller\TestController:
        arguments:
            - '@my_test.client'
```
Call website with different base uri:
```
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class TestController extends AbstractController
{
    public function __construct(
        private HttpClientInterface $httpClient,
    ) {
    }

    public function __invoke(): Response
    {
        $response = $this->httpClient->request('GET', 'http://httpstat.us/500');

        return new Response($response->getContent());
    }
}
```
If you measure controller response time, it should be ~5 times bigger than response time when scoped client max_retries = 1 (sorry for the poor way of proving retries are happening)
