### ISSUE TITLE
[Serializer] regression with attribute serialization

### ISSUE THREAD

**Issue by bendavies** [symfony/symfony#54983]
### Symfony version(s) affected

6.4.7

### Description

There appears to be a regression in v6.4.7 with serializing "nested" attributes with a property path.

### How to reproduce

Given a serialization config like:

```yaml
App\Entity\Foo:
  attributes:
    bar.id:
      serialized_name: bar_id
      groups: ['read']
```

where `Bar` is a relation on `Foo`, `bar_id` is not serialized in in v6.4.7, but was in v6.4.6.

### Additional Context

https://github.com/symfony/symfony/pull/52917 seems suspect to me.
