### ISSUE TITLE
[Workflow] Use Enum as places

### ISSUE THREAD

**Issue by kira0269** [symfony/symfony#57193]
### Description

Workflow yaml configuration waits for string values to configure places and transitions. Also, the marking store key needs a property/method to access.

Since enums exist, I think using them for workflows fits pretty well.
But the only way to achieve this is by following what's described here : https://www.strangebuzz.com/en/blog/using-php-enumerations-with-your-symfony-workflows

**Places**
I suggest to make enums compatible with the workflow component based on these rules:
- Only backed string enum or simple Enum could be used. For Enum, use the name of the case (snake case ?)
- An enum can be put as "places" config. Each value would be a place.
- The marking_store config section would accept a new type: 'enum'. In this case, a new EnumMarkingStore would be instantiated

**Transitions**
For transitions, maybe a new way to configure them could be better with enums.
_Before_
```yaml
framework:
    workflows:
        blog_publishing:
            transitions:
                to_review:
                    from: draft
                    to:   reviewed
                publish:
                    from: reviewed
                    to:   published
                reject:
                    from: reviewed
                    to:   rejected
```
_After_
```yaml
# config/packages/workflow.yaml
framework:
    workflows:
        blog_publishing:
            transitions:
                -  name: !php/enum BlogPublishingTransitions::REVIEW
                    from: draft
                    to:   reviewed
                -  name: !php/enum BlogPublishingTransitions::PUBLISH
                    from: reviewed
                    to:   published
                -  name: !php/enum BlogPublishingTransitions::REJECT
                    from: reviewed
                    to:   rejected
```

Please feel free to give me your point of view about this idea.
I would be glad to contribute on this feature if you think it's relevant 😃 

### Example

Example of new workflow config:

```yaml
# config/packages/workflow.yaml
framework:
    workflows:
        blog_publishing:
            type: 'workflow' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'enum'
                property: 'currentPlace'
            supports:
                - App\Entity\BlogPost
            initial_marking: draft
            places: App\BlogPostState
            transitions:
                -  name: !php/enum App\BlogPostTransition::REVIEW
                    from: !php/enum App\BlogPostState::DRAFT
                    to:   !php/enum App\BlogPostState::REVIEWED
                -  name: !php/enum App\BlogPostTransition::PUBLISH
                    from: !php/enum App\BlogPostState::REVIEWED
                    to:   !php/enum App\BlogPostState::PUBLISHED
                -  name: !php/enum App\BlogPostTransition::REJECT
                    from: !php/enum App\BlogPostState::REVIEWED
                    to:   !php/enum App\BlogPostState::REJECTED
```

```php
# src/BlogPostTransition.php
enum BlogPostTransition: string
{
    case REVIEW = 'review';
    case PUBLISH = 'publish';
    case REJECT = 'reject';
}
```
```php
# src/BlogPostState.php
enum BlogPostState: string
{
    case DRAFT = 'draft';
    case REVIEWED = 'reviewed';
    case PUBLISHED = 'published';
    case REJECTED = 'rejected';
}
```
