### ISSUE TITLE
Router removes double slash from parameter

### ISSUE THREAD

**Issue by flack** [symfony/symfony#57205]
### Symfony version(s) affected

7.0.7

### Description

I have a relocate controller which takes the target URL as a parameter, but when I call e.g. `/goto/http://mywebsite`, the parameter comes out as `http:/mywebsite`, i.e. the double slash is replaced by a single slash

### How to reproduce

The route defintion looks like this:

```yaml
goto:
    path: /goto-{url}
    defaults: { _controller: 'my_controller' }
    requirements: { url: '.*'}
```

when called with

 `/goto/http://mywebsite`

the `$url` parameter comes out as `http:/mywebsite`
