### ISSUE TITLE
You have requested a non-existent parameter "container.build_hash"

### ISSUE THREAD

**Issue by olivier1980** [symfony/symfony#57300]
### Symfony version(s) affected

7.1.0

### Description

Adding a login throttler in security.yaml for Symfony 7.1 results in error message `You have requested a non-existent parameter "container.build_hash"`. 

Example config:
```
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            login_throttling:
                max_attempts: 3
```

### How to reproduce

Replace 7.0.* with 7.1.* in composer.json, with login throttling enabled and the required `composer require symfony/rate-limiter` package installed.
