### ISSUE TITLE
Symfony's user login magic in WebTestCase not working

### ISSUE THREAD

**Issue by 4d4ch4u32** [symfony/symfony#57315]
### Symfony version(s) affected

6.6.7

### Description

As described in [the documentation](https://symfony.com/doc/current/testing.html#logging-in-users-authentication), I try to log-in the user in a WebTestCase.

### How to reproduce

The test class:

```php

class CreateStoreTest extends AbstractCrudTestCase
{

    // ...

    protected function setUp(): void
    {
        parent::setUp();

        $userRepository = $this->entityManager->getRepository(AppUser::class);
        $testUser = $userRepository->findOneByEmail('user@domain.de');
        $this->client->loginUser($testUser);
    }

    // ...

```

When I try to fetch the user from the current `security.token_storage`, there is a user object, the following test succeeds:

```php
    public function testIndex(): void
    {
        $token = $this->client->getContainer()->get('security.token_storage');
        $user = $token->getToken()->getUser();

        self::assertInstanceOf(AppUser::class, $user);
    }
```

But when I request the `/dashboard` url, the test failes:

```php
    public function testIndex(): void
    {
        $this->client->request("GET", '/dashboard');

        self::assertResponseIsSuccessful();
    }
```

In the logs I see the authenticator is not supported:

```
[2024-05-24T12:27:27.321169+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"frontend","authenticators":1} []
[2024-05-24T12:27:27.321253+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"frontend","authenticator":"App\\Security\\AppUserAuthenticator"} []
[2024-05-24T12:27:27.321321+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"frontend","authenticator":"App\\Security\\AppUserAuthenticator"} []
[2024-05-24T12:27:27.345638+00:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /srv/app/vendor/symfony/security-http/Firewall/AccessListener.php:87)"} []
[2024-05-24T12:27:27.346294+00:00] security.DEBUG: Calling Authentication entry point. {"entry_point":{"App\\Security\\AppUserAuthenticator":[]}} []
```

Here is the Authenticator:

```php
<?php

declare(strict_types=1);

namespace App\Security;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\CsrfTokenBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\RememberMeBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Http\SecurityRequestAttributes;
use Symfony\Component\Security\Http\Util\TargetPathTrait;

class AppUserAuthenticator extends AbstractLoginFormAuthenticator
{
    use TargetPathTrait;

    public const LOGIN_ROUTE = 'app_login';

    public function __construct(private UrlGeneratorInterface $urlGenerator)
    {
    }

    public function authenticate(Request $request): Passport
    {
        /** @var string $email */
        $email = $request->request->get('email', '');

        $request->getSession()->set(SecurityRequestAttributes::LAST_USERNAME, $email);

        /** @var string $password */
        $password = $request->request->get('password', '');

        /** @var string $csrfToken */
        $csrfToken = $request->request->get('_csrf_token');

        return new Passport(
            new UserBadge($email),
            new PasswordCredentials($password),
            [
                new CsrfTokenBadge('authenticate', $csrfToken),
                new RememberMeBadge(),
            ],
        );
    }

    /** @phpcsSuppress SlevomatCodingStandard.Functions.UnusedParameter */
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        $targetPath = $this->getTargetPath($request->getSession(), $firewallName);

        if (null !== $targetPath) {
            return new RedirectResponse($targetPath);
        }

        return new RedirectResponse($this->urlGenerator->generate('dashboard_index'));
    }

    /** @phpcsSuppress SlevomatCodingStandard.Functions.UnusedParameter */
    protected function getLoginUrl(Request $request): string
    {
        return $this->urlGenerator->generate(self::LOGIN_ROUTE);
    }
}
```

And the content of the `security.yaml`:

```yaml
security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  enable_authenticator_manager: true

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\AppUser
    backoffice_user_provider:
      entity:
        class: App\Entity\BackofficeUser
        property: email
    # used to reload user from session & other features (e.g. switch_user)
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    backoffice:
      pattern:   ^/backoffice
      lazy: true
      provider: backoffice_user_provider
      custom_authenticator:
        - App\Security\BackofficeAuthenticator
      logout:
        path: backoffice_logout

    frontend:
      pattern:   ^/
      lazy: true
      provider: app_user_provider
      custom_authenticator:
        - App\Security\AppUserAuthenticator
      logout:
        path: app_logout

  access_control:
    - { path: ^/backoffice/login, roles: PUBLIC_ACCESS }
    - { path: ^/backoffice, roles: ROLE_ADMIN }
    - { path: ^/dashboard, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      # By default, password hashers are resource intensive and take time. This is
      # important to generate secure password hashes. In tests however, secure hashes
      # are not important, waste resources and increase test times. The following
      # reduces the work factor to the lowest possible values.
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
```

In the `dev`-environtment (by clicking through the browser) both logins are working as expected.

Is there any magic only for the test-environment? If yes, where?

This is the whole test. The class extends `AbstractCrudTestCase` from EasyAdminBundle (but it's still a `WebTestCase`, see https://symfony.com/bundles/EasyAdminBundle/current/tests.html):

```php
<?php

namespace App\Tests\IntegrationTests\Dashboard;

use App\Controller\Dashboard\DashboardController;
use App\Controller\Dashboard\StoreCrudController;
use App\Entity\AppUser;
use EasyCorp\Bundle\EasyAdminBundle\Test\AbstractCrudTestCase;

class CreateStoreTest extends AbstractCrudTestCase
{

    protected function getControllerFqcn(): string
    {
        return StoreCrudController::class;
    }

    protected function getDashboardFqcn(): string
    {
        return DashboardController::class;
    }

    protected function setUp(): void
    {
        parent::setUp();

        $userRepository = $this->entityManager->getRepository(AppUser::class);
        $testUser = $userRepository->findOneByEmail('user@xyz.tld');
        $this->client->loginUser($testUser);
    }

    public function testIndex(): void
    {
        $this->client->request("GET", '/dashboard');

        self::assertResponseIsSuccessful();
    }
}
```

  [1]: https://symfony.com/doc/current/testing.html#logging-in-users-authentication

### Additional Context

Log:

```
[2024-06-04T15:11:18.715981+00:00] request.INFO: Matched route "dashboard_index". {"route":"dashboard_index","route_parameters":{"_route":"dashboard_index","_controller":"App\\Controller\\Dashboard\\DashboardController::index"},"request_uri":"http://localhost/dashboard","method":"GET"} []
[2024-06-04T15:11:18.725119+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"frontend","authenticators":1} []
[2024-06-04T15:11:18.725146+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"frontend","authenticator":"App\\Security\\AppUserAuthenticator"} []
[2024-06-04T15:11:18.725163+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"frontend","authenticator":"App\\Security\\AppUserAuthenticator"} []
[2024-06-04T15:11:18.740537+00:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /srv/app/vendor/symfony/security-http/Firewall/AccessListener.php:87)"} []
[2024-06-04T15:11:18.741169+00:00] security.DEBUG: Calling Authentication entry point. {"entry_point":{"App\\Security\\AppUserAuthenticator":[]}} []
[2024-06-04T15:11:18.759559+00:00] doctrine.INFO: Disconnecting [] []
```
