### ISSUE TITLE
[Workflow] 'supports' and 'support_strategy' are only used in Registry

### ISSUE THREAD

**Issue by kira0269** [symfony/symfony#57325]
### Symfony version(s) affected

6.4.*, 7.0.\*

### Description

Hello !

I don't know if this is a bug actually. But it's a weird behavior I'm facing right now.

I thought that the `supports` configuration key goal was to define which class a workflow can manage.
Based on this idea, I expect the method `$workflow->getEnabledTransitions($subject)` to return an empty array (or at least throw an exception) if I call it on an instance of a class different from the ones I put in my config.

But it appears that it's not working like this. 

The config values `supports` and `support_strategy` are retrieved only for configuring the `Registry` (in `Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension`).
When `getEnabledTransitions($subject)` is called, it will try to get the marking of the subject, based on `marking_store` configuration. At no time is the subject type checked. That could lead to unexpected behavior.

The only way I found to prevent this behavior is to setup a guard event listener for all transitions of a workflow and check if the subject has the expected type. But that also means to duplicate the the "class support" logic in several places.

WDYT ?

### How to reproduce

Example:

Trait and models
```php
trait WithStatus
{
    protected string $status = 'pending';
    
    public function getStatus: string
    {
        return $this->status:
    }
    
    public function setStatus(): string
    {
        $this->status = $status;
    }
}

class Order
{
    use WithStatus;
}

class PullRequest
{
    use WithStatus;
}
```

Configuration
```yaml
framework:
    workflows:
    
        order_workflow:
            type: 'state_machine'
            supports:
                - App\Entity\Order
            marking_store:
                type: 'method'
                property: 'status'
                
        pr_workflow:
            type: 'state_machine'
            supports:
                - App\Entity\PullRequest
            marking_store:
                type: 'method'
                property: 'status'
```

In use
```php
class MyController extends AbstractController
{
    public function showTransitions(WorflowInterface $prWorkflow)
    {
        $enabledTransitions = $prWorkflow->getEnabledTransitions(new Order());
        
        // $enabledTransitions is not empty ! So we can execute the code below:
        $prWorkflow->apply('some_transition', new Order());
    }

}
```

### Possible Solution

The `supports` and `support_strategy` should be known by the workflow it self, not only by the `Registry`.

This way, the subject type could be checked when `getMarking()` is called. That could also simplify  the `getGetter()` logic.

To avoid any BC, this behavior could be enabled in yaml configuration at first. If you agree. a deprecation can be thrown if the config key is missing. By default, it would be 'false' (to keep the actual behavior).
