### ISSUE TITLE
[HttpClient] ScopingClient does not support base_uri without ending `/`

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#57440]
### Symfony version(s) affected

6.3.2

### Description

The proper way to document API endpoints is to use a leading slash `/` and the beginning and this is how I then keep the endpoint string in my Request class model when I integrate with external APIs.
**Example:**
Endpoints:
  - endpoint 1
    path: /some/endpoint/1 
  - endpoint 2
    path: /some/endpoint2

```php
class Request
{
  public getUri()
  {
    return '/some/endpoint1';
  }
}
```

ScopingHttpClient does not support this.

This works:
```php
$client->request('GET', 'some/endpoint1'); // notice NO slash at the beginning of the url
```
```yaml
framework:
    http_client:
      scoped_clients:
        my_client:
          base_uri: 'http:/exaple.com/api/' # notice ending backslash
```

This **doesn't work**: 
The call is made to `http:/exaple.com/some/endpoint1`:
```php
$client->request('GET', '/some/endpoint1'); // notice slash at the beginning of the url
```
```yaml
framework:
    http_client:
      scoped_clients:
        my_client:
          base_uri: 'http:/exaple.com/api' # notice NO ending slash
```

This `if` is the source of a problem: https://github.com/symfony/symfony/blame/916718cf368381036ee6bf2ce21930bf7fb67ba2/src/Symfony/Component/HttpClient/HttpClientTrait.php#L581
Version 6.3.2 but I don't see any related changes in this trait since then.

### How to reproduce

.
