### ISSUE TITLE
[AssetMapper] Make JS/CSS vendor directory configurable

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#57446]
### Description

Currently third party libraries like hotwired or stimuls are embedded via the following URL:

 - `/assets/vendor/es-module-shims/es-module-shims.index-1391f0fdc091ef9124c046f313902438.js`
 - `/assets/vendor/@hotwired/stimulus/stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js`

And it would be nice to change the `/vendor/` directory to another url.

The background about this is that I block all requests containing `/vendor/` because there are a lot of Bots trying todo evil execution on things like `vendor/phpunit/phpunit/bin/...` or other security vulnerabilities. So my nginx returns for all kind of that requests `444` to directly close the connection.

While deploying a new project which did I stumbled over that I needed to edit my default vhost and remove that part to make sure the asset mapper works. So it would be nice to maybe make that part configurable or even if I'm not the only one change to something else (modules, esmodules, ...).

I tried to find out where that vendor dir comes from but I didn't find anything yet, so even not sure if its maybe part of the importmap standard and so not changeable?!?

**Comment by smnandre** [comment]
There is an option to configure the vendor directory. Never used it personally, but i guess this should work.

```yml
# config/packages/asset_mapper.yaml

framework:
    asset_mapper:
        paths:
            - assets/
            
        vendor_dir: '%kernel.project_dir%/assets/vnd'
```
