### ISSUE TITLE
loginUser() doesn't work with Memory User Provider

### ISSUE THREAD

**Issue by arcadeus** [symfony/symfony#57468]
### Symfony version(s) affected

7.1.1

### Description

When `security/firewalls/main` context uses Memory User Provider, `KernelBrowser::loginUser()` tries to login with database.

### How to reproduce

I have one user in memory:
```
// security.yaml
security:
    providers:
        users_in_memory:
            memory:
                users:
                    user: { password: '123', roles: ROLE_USER }
    firewalls:
        main:
            provider: users_in_memory
```
When I try to login in my `WebTestCase` test
```
use Symfony\Component\Security\Core\User\InMemoryUser;
...
$client = static::createClient();
$user = new InMemoryUser('user', '123', ['ROLE_USER']);
$client->loginUser($user);
```
I get
```
$ php bin/phpunit
...
An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'mydbname_test' (500 Internal Server Error)
```
What PHPUnit is trying to read the test database for?
