### ISSUE TITLE
[Cache] CachePoolPass accidentally overrides tags for ChainAdapter, causing container to ignore specific adapter variables

### ISSUE THREAD

**Issue by macr1408** [symfony/symfony#57698]
### Symfony version(s) affected

7.1.2

### Description

I was trying to enable cache in my app with the chain adapter, a basic chain with Redis + Filesystem. But due to specific reasons I needed to use a custom namespace (key prefix) for the redis adapter. I followed the documentation but my configuration wasn't working, after a couple of hours debugging I found this issue:

`symfony/cache/DependencyInjection/CachePoolPass.php:88` runs some specific logic for chained adapters, and stores the tags into `$chainedTags[0] += $t[0];` but the next lines use the `$tag` variable instead

```php
if (isset($tags[0]['namespace']) && !\in_array($adapter->getClass(), [ArrayAdapter::class, NullAdapter::class], true)) {
    $chainedPool->replaceArgument($i++, $tags[0]['namespace']);
}

if (isset($tags[0]['default_lifetime'])) {
    $chainedPool->replaceArgument($i++, $tags[0]['default_lifetime']);
}
```
Making the child/custom adapter to use the parent's provider settings. 

### How to reproduce

- in `config/services.yaml` create a custom adapter:

```yml
app.cache.adapter.my_redis_tag_aware:
  parent: 'cache.adapter.redis_tag_aware'
  tags:
    - { name: 'cache.pool', namespace: 'my_namespace', default_lifetime: 100 }
```

- in `config/packages/cache.yaml` configure a chained pool:

```yml
pools:
  my_tag_cache_pool:
    default_lifetime: 31536000
    tags: true
    adapters:
      - app.cache.adapter.my_redis_tag_aware
      - cache.adapter.filesystem
```

-  Now if you debug the constructor of `symfony/cache/Adapter/RedisTagAwareAdapter.php` it will be created 2 times:

1. With `lifetime: 100` and `namespace: 'my_namespace'`
2. With `lifetime: 31536000` and `namespace: '{random}'`. Because CachePoolPass overrides the previous definition with the tags from the parent (`cache.adapter.redis_tag_aware`)

### Possible Solution

I'm not 100% sure since I'm not too familiar with the source code, but this solved my problem

```php
if (isset($chainedTags[0]['namespace']) && !\in_array($adapter->getClass(), [ArrayAdapter::class, NullAdapter::class], true)) {
    $chainedPool->replaceArgument($i++, $chainedTags[0]['namespace']);
}

if (isset($chainedTags[0]['default_lifetime'])) {
    $chainedPool->replaceArgument($i++, $chainedTags[0]['default_lifetime']);
}
```
