### ISSUE TITLE
[Security] Security::login does not take into account custom user_checker

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/symfony#57706]
### Symfony version(s) affected

6.4.3

### Description

We have custom `user_checker` for main firewall and we have automatically called `Security::login` which does not take into account custom`user_checker` and calling `InMemoryUserChecker`

### How to reproduce

security.yaml
```
    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\User\UserChecker
```

after that just call `Security::login()` and UserChecker won't be called.

### Possible Solution

since already fetch `getFirewallConfig` we need to fetch userChecker and fetch it from container.
