### ISSUE TITLE
PdoSessionHandler with SQL Server and ODBC Driver 18 does not support option for TrustServerCertificate=yes

### ISSUE THREAD

**Issue by pauljura** [symfony/symfony#57743]
### Symfony version(s) affected

7.1.2

### Description

My application is connecting to a SQL Server database and also using it for session storage. I was using ODBC Driver 17 but recently upgraded to 18, which now defaults to enabling encryption.

Without any changes, I get the following error:

```SQLSTATE[08001]: [Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:0A000086:SSL routines::certificate verify failed:unable to get local issuer certificate]```

For Doctrine, I can make it work by adding a new option `TrustServerCertificate` to my `doctrine.yaml` file:
```
connections:
    default:
        url: '%env(resolve:DATABASE_URL)%'
        options:
            TrustServerCertificate: yes
```

But I still get the error when Symfony tries to connect to the database for the session.

I've tried everything I could think of to pass the `TrustServerCertificate` option to `PdoSessionHandler` but nothing seems to work. Here's the relevant portion of my `services.yaml` file:
```
 Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
     arguments:
         - '%env(DATABASE_URL)%'
         - { db_table: 'Session', db_id_col: 'ID', db_data_col: 'Data', db_time_col: 'Time', db_lifetime_col: 'ExpiresAt', lock_mode: 0, db_connection_options: { TrustServerCertificate: 'yes' } }
```
I've tried `TrustServerCertificate: 'yes'`, `TrustServerCertificate: 1`, `TrustServerCertificate: true`. I've added `?TrustServerCertificate=yes` (as well as `1` and `true`) to my database URL. Nothing I tried has worked.

Either I'm missing something or the extra options aren't taking any effect.

### How to reproduce

Connect to a SQL Server database for sessions using the ODBC Driver 18

### Possible Solution

The only way I've gotten the session connection to work was to manually edit the code in `PdoSessionHandler`, in the `buildDsnFromUrl` method, I add `$dsn .= ';TrustServerCertificate=yes';` right before it returns `$dsn`.

If you look at how Doctrine does it in `vendor/doctrine/dbal/src/Driver/PDO/SQLSrv/Driver.php`, all the extra options are appended to the DSN. So probably `PdoSessionHandler` could do something similar, e.g. if I have `?TrustServerCertificate=yes&Foo=bar` in my database URL then it could add `;TrustServerCertificate=yes;Foo=bar` to the DSN.

**Comment by pauljura** [comment]
In the meantime, I wrote this to get a working connection, it might be useful for someone.
```
class PdoSessionHandler extends \Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
{
    public function __construct(#[\SensitiveParameter] string $url, #[\SensitiveParameter] array $options = []) {
        // build dsn from url
        $params = parse_url($url);
        $params = array_map('rawurldecode', $params);
        $dsn = 'sqlsrv:server=';
        if (isset($params['user'])) {
            $username = $params['user'];
        } else {
            throw new \InvalidArgumentException('Session database connection URL requires a username');
        }
        if (isset($params['pass'])) {
            $password = $params['pass'];
        } else {
            throw new \InvalidArgumentException('Session database connection URL requires a password');
        }
        if (isset($params['host'])) {
            $dsn .= $params['host'];
        }
        if (isset($params['port']) && $params['port'] !== '') {
            $dsn .= ','.$params['port'];
        }
        if (isset($params['path'])) {
            $dbName = substr($params['path'], 1); // Remove the leading slash
            $dsn .= ';Database='.$dbName;
        }
        if (isset($params['query'])) {
            parse_str($params['query'], $queryParams);
            foreach ($queryParams as $queryOption => $queryValue) {
                $dsn .= sprintf(';%s=%s', $queryOption, $queryValue);
            }
        }
        $connectionOptions = $options['db_connection_options'] ?? [];
        $pdo = new \PDO($dsn, $username, $password, $connectionOptions);
        parent::__construct($pdo, $options);
    }
}
```
and then add this to services.yaml:
```
services:
    App\PdoSessionHandler:
        arguments:
            $url: '%env(DATABASE_URL)%'
            # set $options to be whatever you need...
            $options: { db_table: 'Session', db_id_col: 'ID', db_data_col: 'Data', db_time_col: 'Time', db_lifetime_col: 'ExpiresAt', lock_mode: 0 }
```
add this to framework.yaml:
```
framework:
    session:
        handler_id: App\PdoSessionHandler
```
and finally make sure you have `?TrustServerCertificate=yes` in your `DATABASE_URL`.

**Comment by xabbuh** [comment]
Can you please debug why the `db_connection_options` entry is not forwarded to PDO in your case? Reading the code I don't see why that should not happen (see https://github.com/symfony/symfony/blob/9c1e36257c4df0929179462d6b2bdd00453ac8aa/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L176 and https://github.com/symfony/symfony/blob/9c1e36257c4df0929179462d6b2bdd00453ac8aa/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L424).

**Comment by pauljura** [comment]
Hi @xabbuh the `db_connection_options` is being forwarded to PDO, but the `TrustServerCertificate` option has no effect when it's part of the $options parameter, it has to be part of the $dsn parameter.

```
// this does not work
$pdo = new \PDO('sqlsrv:server=host;Database=foo', $user, $pass, ['TrustServerCertificate' => 'yes']);

// this works
$pdo = new \PDO('sqlsrv:server=host;Database=foo;TrustServerCertificate=yes', $user, $pass, []);
```

**Comment by pauljura** [comment]
It might just be a quirk of how sqlsrv works, but it is what it is. If you look at Doctrine code: https://github.com/doctrine/dbal/blob/4.0.x/src/Driver/PDO/SQLSrv/Driver.php they put all options in the $dsn. I'm not sure what options, if any, truly need to be included in the $options parameter.

**Comment by xabbuh** [comment]
I see, as a workaround you can configure your service creating a `PDO` instance with the desired DSN and pass this as the first argument instead of the DSN.

**Comment by pauljura** [comment]
Yes, that is what I did :)

**Comment by xabbuh** [comment]
What I meant is that you don't need to create your own `PdoSessionHandler` class which extends the Symfony one.

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by pauljura** [comment]
Still relevant. Has a workaround, but ought to be properly supported, in my opinion.

**Comment by carsonbot** [comment]
Hey, thanks for your report!
There has not been a lot of activity here for a while. Is this bug still relevant? Have you managed to find a workaround?

**Comment by pauljura** [comment]
Hi, still relevant, please don't close this.

**Comment by nicolas-grekas** [comment]
Please consider sending a PR to improve the situation. Keeping the issue open won't make it fixed. Someone that needs that has to tackle the topic. Looks like you might the one ;)

**Comment by adatta02** [comment]
I was able to get this working using off the shelf Symfony 7.3.4 by making Doctrine's PDO object available as a service and then passing that to the PDO Session handler.

```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    app.session.pdo:
        class: PDO
        factory: ['@doctrine.dbal.default_connection', 'getNativeConnection']

    app.session.pdo_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - '@app.session.pdo'
```

I did have to configure Doctrine with YAML vs. a DSN as well:

```
doctrine:
    dbal:
        driver: 'pdo_sqlsrv'
        host: '%env(resolve:DB_HOST)%'
        port: 1433
        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        charset: 'UTF-8'
        options:
            Encrypt: yes
            TrustServerCertificate: no
```
