### ISSUE TITLE
[Messenger] messenger:consume doesn't use a logger for startup messages

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#57776]
### Symfony version(s) affected

7.1.2

### Description

The `messenger:consume` command is meant to be running in non-interactive worker scenarios, but the startup messages are not using the logger subsystem, they're instead produced to output directly, as so (note that shut down messages are correctly logged):

```
/app $ bin/console messenger:consume --all -vv --env prod --no-interaction

                                                                                                                        
 [OK] Consuming messages from transports "async_realtime, async_high_priority, async_normal_priority,                   
      async_low_priority".                                                                                              
                                                                                                                        

 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.       

 // Quit the worker with CONTROL-C.                                                                                     

^C{"@timestamp":"2024-07-19T09:12:03.609016+00:00","@version":1,"host":"f3e3b861766d","message":"Received signal 2.","type":"app","channel":"messenger","level":"INFO","monolog_level":200,"context":{"signal":2,"transport_names":["async_realtime","async_high_priority","async_normal_priority","async_low_priority"]}}
{"@timestamp":"2024-07-19T09:12:03.609719+00:00","@version":1,"host":"f3e3b861766d","message":"Stopping worker.","type":"app","channel":"messenger","level":"INFO","monolog_level":200,"context":{"transport_names":["async_realtime","async_high_priority","async_normal_priority","async_low_priority"]}}
```

### How to reproduce

1. Configure Monolog to use Logstash formatter to notice the difference, like so:

```yaml
monolog:
    handlers:
        main:
            type: stream
            path: "php://stderr"
            level: "warning"
            formatter: 'monolog.formatter.logstash'
            channels: ["!deprecation"]
        console:
            type: console
            formatter: 'monolog.formatter.logstash'
```

2. start the `messenger:consume` command like so

```
bin/console messenger:consume --all -vv --env prod --no-interaction
```

### Possible Solution

Repeat the messages to the logger too? Suppress the plain text messages in non-interactive mode? Both?

### Additional Context

_No response_

**Comment by wouterj** [comment]
Suppressing the plain text messages can be achieved by using the quiet verbosity as far as I can tell.

A contribution that adds a log message when starting the consumer sounds alright to me (as a feature).

**Comment by dkarlovi** [comment]
Quiet verbosity suppresses the logging too.

**Comment by wouterj** [comment]
It suppresses the `type: console` logger, but not the `type: stream` with a stream to `php://stderr` logging.

That is the exact set-up we're using in all of our containers:
```yaml
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: warning
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                level: debug
                formatter: monolog.formatter.logstash
                path: php://stderr
```

With the `SHELL_VERBOSITY=-1` env var (i.e. quiet verbosity) set in the container.
