### ISSUE TITLE
Add support to require ALL roles in access_control configuration, not just ANY OF the roles

### ISSUE THREAD

**Issue by michnovka** [symfony/symfony#57807]
### Description

The following configuration:
```yaml
security:
    access_control:
        - { path: ^/admin/(dashboard|users|stats), roles: [ ROLE_ADMIN, IS_AUTHENTICATED_FULLY ] }
        - { path: ^/admin, roles: ROLE_ADMIN }
```

will allow access to /admin/dashboard to any logged in user (due to `IS_AUTHENTICATED_FULLY`).

I propose 2 solutions:

1. we add new config option `roles_require_all`:
```yaml
security:
    access_control:
        - { path: ^/admin/(dashboard|users|stats), roles_require_all: [ ROLE_ADMIN, IS_AUTHENTICATED_FULLY ] }
        - { path: ^/admin, roles: ROLE_ADMIN }
```

2. we treat special way the full authentication and rememberme authentication:
```yaml
security:
    access_control:
        - { path: ^/admin/(dashboard|users|stats), roles: [ ROLE_ADMIN ], fully_authenticated: true, remembered: false }
        - { path: ^/admin, roles: ROLE_ADMIN }
```

WDYT?
