### ISSUE TITLE
[DIC] Factory + TaggedLocator does not work with defaultIndexMethod

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#57830]
### Symfony version(s) affected

5.4.40

### Description

Using a factory, and tagged locator does not work

```yaml
services:
    App\Jerome\JeromeInterface:
        factory: ['@App\Jerome\ImplemSelector', selectImplem]
```

```php
class ImplemSelector
{
    public function __construct(
        #[TaggedLocator(JeromeInterface::class, defaultIndexMethod: 'getNameStoredInDb')]
        private readonly ServiceLocator $serviceLocator
    ) {
    }

    public function selectImplem(): JeromeInterface
    {
        $name = ['first', 'second'][random_int(0, 1)];

        return $this->serviceLocator->get($name);
    }
}
```

### How to reproduce

[I made a reproducer](https://github.com/lyrixx/test/commit/4693f852583f3a40ed34c112e9cf46ddb1382cd4)
