### ISSUE TITLE
[Security] Unable to migrate passwords generated by custom hasher

### ISSUE THREAD

**Issue by guusfrenken-wk** [symfony/symfony#58053]
### Symfony version(s) affected

5.4

### Description

I can't seem to figure out how to migrate passwords generated by our custom hasher following the documentation.

This is my setup:
- My custom password hasher implement `PasswordHasherInterface`.
- My UserRepository implements `PasswordUpgraderInterface` with an `upgradePassword` method.
- As mentioned in the [newer Symfony docs](https://symfony.com/doc/6.4/security/passwords.html#dynamic-password-hashers), I have removed the `PasswordHasherAwareInterface` implementation from my User entity.
- My hashers are configured like this:
```yaml
security:
    password_hashers:
        legacy_mysql_password_encoder:
            id: 'App\Security\LegacyMySQLPasswordEncoder'
        App\Entity\User:
            algorithm: sha512
            migrate_from:
                - legacy_mysql_password_encoder
```

The issue is that now when I login using a legacy password, Symfony simply tries to verify the given password using the new hasher and obviously fails. I am not sure how Symfony is ever supposed to find my legacy custom hasher without the `PasswordHasherAwareInterface` implementation to help it.

When I re-add the `PasswordHasherAwareInterface` to my User entity, Symfony will re-hash the given password with the legacy hasher instead of the new hasher.

Am I doing something wrong? It seems that I am following the documentation correctly but Symfony is just not behaving as expected.

### How to reproduce

Configure Symfony as described above and try to log in using a user with a legacy password.

Expected behaviour: Legacy user's password is re-hashed using new hasher after succesful login

Actual behaviour: 
 a: Legacy user's password is verified with new hasher and login fails
 b: Legacy user's password is re-hashed with legacy hasher, no progress towards migrating old passwords.
