### ISSUE TITLE
AssetMapper influenced by framework.assets.version

### ISSUE THREAD

**Issue by tarjei** [symfony/symfony#58130]
### Symfony version(s) affected

6.4.x, 7.x?

### Description

When this is set in `config/packages.yaml`:
```yaml
framework:
    assets:
        version: "some-version"
```

Then "some-version" is appended to secondary imports which causes errors when trying to import them in dev.

### How to reproduce

Try to install the Symfony ux 2.x demo page: 
https://github.com/symfony/ux/blob/2.x/ux.symfony.com/README.md

And set in `config/packages.yaml`:
```yaml
framework:
    assets:
        version: "some-version"
```

And loading of some js files will fail.
