### ISSUE TITLE
Authenticator does not support the request. (No answer from discussion)

### ISSUE THREAD

**Issue by michaelt-94** [symfony/symfony#58176]
### Symfony version(s) affected

7.1

### Description

I have created a simple site that has a home page and an admin page. I used the webapp make:user authentication as described in the documentation. Everything worked at that point. I had some non related OS issues so I decided to re-OS my machine. I pushed my working website to bitbucket. After re-OS my machine, I cloned my repo and performed composer install to add all the packages from composer.json. Now, when I run symfony serve I get a blank white page at localhost:8000.
In the command terminal where server is running, I get this
[Application] Sep 3 19:41:38 |INFO | REQUES Matched route "home_page". method="GET" request_uri="http://localhost:8000/" route="home_page" route_parameters={"_controller":"App\Controller\HomeController::index","_route":"home_page"}
[Application] Sep 3 19:41:38 |DEBUG | SECURI Checking for authenticator support. authenticators=1 firewall_name="main"
[Application] Sep 3 19:41:38 |DEBUG | SECURI Checking support on authenticator. authenticator="Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator"
[Application] Sep 3 19:41:38 |DEBUG | SECURI Authenticator does not support the request.
My home page does not have a FormLogin login is located at /login. I haven't made any changes. Can someone point me in the right direction to resolve this?
BTW, I can create a whole new symfony --webapp and it works just fine. So its something that happens when the repo is cloned.

I have done a search for similar issues, but I can find none that pertain to this happening on such a basic set up and after using git.
![Screenshot from 2024-09-03 16-38-20](https://github.com/user-attachments/assets/a0598a05-0270-4204-b2c4-1e3ff0c3348a)

### How to reproduce

1. Create a new Symfony --webapp
2. Create a login/logout/registration (My site has a "home" page and an "admin" that is it) page using the standard symfony docs found in the symfony documentation pages.
3. Ensure all the features work.
4. At this point you have a basic standard non customized working web app
5. Add to a git repository and push to a remote repository
6. in a new location, clone the project do what is necessary to make it work (normally, create DB, composer install etc...)
7. Start the symfony server and go to the home page.

### Possible Solution

1. If there are configuration changes that inherently take place when pushing to a git repo, tell us about them and show us how to resolve them.
2. Perhaps the FormLoginAuthenticator needs some work?????

### Additional Context

Here is my firewall:
```
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                target: home_page
```
