### ISSUE TITLE
[Yaml] Add support for `!php/enum *::staticfunction` syntax

### ISSUE THREAD

**Issue by Crovitche-1623** [symfony/symfony#58484]
### Description

I think it could be a great feature if we could call a static function when using YAML.

### Example

```php
<?php

namespace Foo\Bar;

enum SupportedLocale: string
{
    case FR = 'fr';
    case DE = 'de';
    case IT = 'it';
    case EN = 'en';

    public static function getSupportedLocalesAsString(): string
    {
        return \implode('|', self::cases());
    }
}
```

```yml
# config/routes.yaml

foo_bar_controllers:
    resource:
        path: ../src/Controller/Foo/Bar
        namespace: App\Controller\Foo\Bar
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: !php/enum Foo\Bar\SupportedLocale::getSupportedLocalesAsString()
```
