### ISSUE TITLE
[Workflow] handle enum status properties

### ISSUE THREAD

**Issue by tdumalin** [symfony/symfony#58579]
### Description

If we take the Post sample from the doc: [https://symfony.com/doc/current/workflow.html](https://symfony.com/doc/current/workflow.html), it would be nice to define the currentPlace as an enum property 

### Example

```yaml
# config/packages/workflow.yaml
framework:
    workflows:
            marking_store:
                type: 'method'
                property: 'currentPlace'
                enum: true # maybe add a config key to specifiy if the property is an enum but idealy read property reflexion to autoset
```

```php
// src/Enum/BlogPostPlaces

namespace App\Enum;

enum BlogPostPlaces: string
{
    case Draft = 'draft';
    case Reviewed = 'reviewed';
    //...
}

```

```php
// src/Entity/BlogPost.php
namespace App\Entity;

class BlogPost
{
    // the configured marking store property must be declared
    private BlogPostPlaces $currentPlace = BlogPostPlaces::Draft;
}
```
