### ISSUE TITLE
Messenger worker : Transport priorities bypassed with PostgreSQL LISTEN/NOTIFY

### ISSUE THREAD

**Issue by benito103e** [symfony/symfony#58574]
### Symfony version(s) affected

7.1.5

### Description

When using PostgreSqlConnection as messenger transport with use_notify, priorities can be by ignored by worker.

### How to reproduce

I have 2 transports using Doctrine :
```yaml
async_priority_high:
    dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
    options:
        queue_name: high
async_priority_medium:
    dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
    options:
        queue_name: medium
```
My transport is a Postgresl table. I use the default configuration for the transport :
MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0&table_name=core_messenger_message

I run the consumer with `bin/console messenger:consume async_priority_high async_priority_medium`

Sometimes medium messages are received and handled before high messages, if a lot of medium messages are sent.

### Possible Solution

I don't see a very relevant solution, other than disabling use_notify.

**Comment by benito103e** [comment]
The reason for this issue is slightly more complex than a LISTEN which would remain on low priority and block the possibility of listening to higher priority messages.

**Explanations:**
the PostgreSqlConnection listen for a new message in the bus, if the notification does not concern it, it returns null.
```php
// \Symfony\Component\Messenger\Bridge\Doctrine\Transport\PostgreSqlConnection::get
if (
    // no notifications, or for another table or queue
    (false === $notification || $notification['message'] !== $this->configuration['table_name'] || $notification['payload'] !== $this->configuration['queue_name'])
    // delayed messages
    && (microtime(true) * 1000 - $this->queueEmptiedAt < $this->configuration['check_delayed_interval'])
) {
    usleep(1000);

    return null;
}
```

So here's the scenario that's causing problems:
1. Worker asks for messages on high priority transport : no message
2. Worker asks messages on medium priority transport : no message
3. N medium priority messages are pushed and one high priority message
4. Worker asks for message on high priority transport 
   - LISTEN gets a notification for a medium priority message : it returns null (Understood as, there is no message for high priority)
5. Worker asks for message on medium priority transport : 
   - LISTEN gets a notification for a medium priority message
   - The message is retrieved by \Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineReceiver::get()
   - The medium priority message is handled
6.  Repeat steps 4 to 5
7. Finally, worker asks for message on high priority transport and gets a notification for the high priority message

**In conclusion:** when ‘use_notify’ is activated, priority is completely bypassed and only the order of arrival of messages matters. 
For this to work as expected, we would use as many pgsql tables as we have transports.

**Comment by benito103e** [comment]
And the problem goes even further: the more queues we have on the same table, the less chance we have our messages being processed.

Ex.
```yaml
        transports:
            async_priority_1:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: one
            async_priority_2:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: two
            async_priority_3:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: three
            async_priority_4:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: four
            async_priority_5:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: five
```
We run the consumer `bin/console messenger:consume async_priority_1 async_priority_2 async_priority_3 async_priority_4 async_priority_5`

If we dispatch some messages, on each queue :
```php
$bus->dispatch(new MessageOne(date_create_immutable()));
$bus->dispatch(new MessageTwo(date_create_immutable()));
$bus->dispatch(new MessageThree(date_create_immutable()));
$bus->dispatch(new MessageFour(date_create_immutable()));
$bus->dispatch(new MessageFive(date_create_immutable()));
```

LISTEN/NOTIFY won't have expected queue and messages won't be processed.
Fortunately, check_delayed_interval will force message consumption after 60sec.
