### ISSUE TITLE
Add Support for Immediate Message Handling within the Same Consumer in Symfony Messenger

### ISSUE THREAD

**Issue by rodion-k** [symfony/symfony#58635]
### Description

Add the ability to handle messages immediately within the same consumer without sending them to the queue, while preserving the current functionality when messages are dispatched from external contexts.

**Current Behavior**: When a message A is handled by a consumer and dispatches a message B, both messages are sent to their respective queues as configured, regardless of their context.

**Proposed Behavior**:

Message B should be handled immediately if it is dispatched during the handling of message A within the same consumer.

If message B is dispatched from an external context (e.g., a web process), it should still be sent to its configured queue.

This feature would improve efficiency by reducing latency for message chains that are handled within the same consumer, without affecting external dispatches. It ensures that synchronous handling happens only when appropriate, maintaining the reliability and scalability benefits of the queue system for other contexts.

**Comment by ro0NL** [comment]
IIUC you can dispatch using the `sync` transport from your handler.

**Comment by rodion-k** [comment]
> IIUC you can dispatch using the `sync` transport from your handler.

It won't work if the message is dispatched from a component that is used in different contexts.

**Comment by yuukikuno** [comment]
If I understand your issue correctly, this should be possible using the `TransportNamesStamp` as per the Messenger documentation.

Something like:

```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            sync: sync://
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            App\Message\AMessage: async
            App\Message\BMessage: async
```

```php
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Messenger\Stamp\TransportNamesStamp;

#[AsMessageHandler]
class AMessageHandler
{
    public function __construct(MessageBusInterface $bus)
    {
    }

    public function __invoke(AMessage $message)
    {
        $this->bus->dispatch(
            new BMessage(),
            [new TransportNamesStamp(['sync'])]
        );
    }
}
```

Would this solve your issue?
