### ISSUE TITLE
doctrine type 'php' and 'staticphp' use wrong doctrine class name

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#58738]
### Symfony version(s) affected

7.2

### Description

I've set up my doctrine configuration to use php (and also staticphp), but the underlying code point to the wrong class.

```yaml
        mappings:
            App:
                type: php # also fails with staticphp
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

The cache generates this code:
```php

$b->addDriver(($container->privates['doctrine.orm.default_php_metadata_driver'] ??= 
new \Doctrine\ORM\Mapping\Driver\PHPDriver([(\dirname(__DIR__, 4).'/src/Entity')])), 'App\\Entity');        
```

But the actual name of the the class is not \Doctrine\ORM\Mapping\Driver\PHPDriver but should be

     not \Doctrine\ORM\Mapping\Driver\PHPDriver

     use \Doctrine\Persistence\Mapping\Driver\PHPDriver;

### How to reproduce

Create a new project using --version=next, run bin/console make:entity, set the driver in doctrine.yaml as above, create this entity and then run bin/console d:sch:update --dump-sql

```php
namespace App\Entity;

use App\Repository\TestRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Mapping\Builder\ClassMetadataBuilder;
#[ORM\Entity(repositoryClass: TestRepository::class)]
class Test
{

    public static function loadMetadata(ClassMetadata $metadata)
    {
        $builder = new ClassMetadataBuilder($metadata);
        $builder->createField('id', 'integer')->isPrimaryKey()->generatedValue()->build();
        $builder->addField('username', 'string');
    }
}
```
