### ISSUE TITLE
Cannot get rid of "Configure the logger on the wrapped HTTP client directly instead."

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#58759]
### Symfony version(s) affected

7.1

### Description

Since the 7.1 upgrade, we get this deprecation (coming from https://github.com/symfony/symfony/pull/54806), it seems like the autowiring just detects LoggerAwareInterface and maps setLogger() to be called on NoPrivateNetworkHttpClient & co, but this means we cannot get rid of the deprecation except if we redefine all http_client services ourselves to avoid autowiring.

### How to reproduce

Just request a NoPrivateNetworkHttpClient instance in an autowired service.

**Comment by stof** [comment]
Services defined by FrameworkBundle are neither autowired nor autoconfigured.

**Comment by Seldaek** [comment]
Ahh ok thanks for the hint. We have indeed one service defined as such:

```
    Symfony\Component\HttpClient\NoPrivateNetworkHttpClient:
      factory: App\HttpClientFactory::noPrivateNetworkHttpClient
      arguments:
        $privateIPv4: "%public_ipv4%"
        $privateIPv6: "%public_ipv6%"
```

And then it sets the logger on the resulting client because the class has the LoggerAwareInterface (I assume).

Adding `autoconfigure: false` to the service definition seems to fix it.
