### ISSUE TITLE
UUID not supported by default in serializer

### ISSUE THREAD

**Issue by pierrejoye** [symfony/symfony#58913]
### Symfony version(s) affected

7.1.8

### Description

Object with UUID are not serialized correctly using the default setup. For example the ::json() method from AbstractController returns [] for any UUID property.

### How to reproduce

Default project created using the symfony command. Add a simple controller method with a json response for an object with an UUID property.

```PHP
return $this->json(['data' => $obj]);

```

Where $obj has a property like:

```PHP
    use Symfony\Component\Uid\Uuid;
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    private ?Uuid $id = null;

```

will fail to be normalized correctly.

### Possible Solution

```PHP
        $encoders = ['json' => new JsonEncoder()];
        $normalizers = [new UidNormalizer(), new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        $data = $serializer->serialize($obj, 'json');
```
works but it is cumbersome to have to do that, and everywhere (traits but still). Reading https://symfony.com/blog/new-in-symfony-5-2-uid-serialization-and-validation, I was under the impression it is supported by default, but I am not sure I miss something. Adding it to the services.yaml fails as well as the normalizer can't be found.

**Comment by stof** [comment]
Do you actually have the serializer component enabled in your project or are you using the implementation using `json_encode` ? https://github.com/symfony/symfony/blob/975b5cd4e84c0394db45648ed96cc3a6754516f9/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L142-L158

**Comment by stof** [comment]
> Adding it to the services.yaml fails as well as the normalizer can't be found.

what do you mean by "the normalizer can't be found" ? which failure do you get ?

**Comment by pierrejoye** [comment]
@stof I tried to add it to the services.yaml

```YAML
Symfony\Component\Serializer\Serializer:
        arguments:
            $normalizers:
                - '@Symfony\Component\Serializer\Normalizer\UidNormalizer'
                - '@Symfony\Component\Serializer\Normalizer\ObjectNormalizer'
            $encoders:
                - '@serializer.encoder.json'
```

Thinking it may not be detected. But then calling the serializer fails with UidNormalizer can't be found.

But somehow I would rather have ::json handles uuid directly :)

Added the trait for now to do serialize "manually".
