### ISSUE TITLE
[Doctrine] : Fails to detect entities when mixing attribute and XML mappings in Symfony with same start namespace

### ISSUE THREAD

**Issue by HugoSEIGLE** [symfony/symfony#59081]
### Symfony version(s) affected

7.0.x

### Description

When mixing XML and attribute mappings in a Symfony project, entities with similar namespace names fail to load properly. Specifically, if two namespaces (e.g., App\Entity\Product and App\Entity\ProductCategory) have similar or overlapping names, Doctrine struggles to resolve the entities correctly.

For example:

    App\Entity\Product\Product is mapped using XML.
    App\Entity\ProductCategory\Category is mapped using attributes.

In this setup, Doctrine reports that it cannot find a mapping for App\Entity\ProductCategory\Category unless most of the other mappings are commented out in doctrine.yaml.

### How to reproduce

1. Set up a Symfony project with the following configuration in doctrine.yaml

```yaml
doctrine:
  orm:
    auto_mapping: false
    mappings:
      ProductMapping:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Core/Product'
        prefix: 'App\Entity\Product'
        alias: Product

      ProductCategoryMapping:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity/ProductCategory'
        prefix: 'App\Entity\ProductCategory'
        alias: ProductCategory
```

2. Create the following mapping and entity files

    - Product.orm.xml in the directory %kernel.project_dir%/config/doctrine/Core/Product

```xml
<?xml version="1.0" encoding="UTF-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping https://www.doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="App\Entity\Product\Product" table="products">
        <id name="id" type="integer" column="id">
            <generator strategy="AUTO"/>
        </id>
        <many-to-one field="category" target-entity="App\Entity\ProductCategory\Category" inversed-by="products">
            <join-column name="category_id" referenced-column-name="id" />
        </many-to-one>
    </entity>
</doctrine-mapping>

```

    - Category.php in the directory %kernel.project_dir%/src/Entity/ProductCategory
    
```php
namespace App\Entity\ProductCategory;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: "product_categories")]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private int $id;

    #[ORM\Column(type: "string", length: 255)]
    private string $name;

    #[ORM\OneToMany(targetEntity: "App\Entity\Product\Product", mappedBy: "category")]
    private Collection $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getProducts(): Collection
    {
        return $this->products;
    }
}

```

3. Run the following commands

```shell
php bin/console doctrine:mapping:info
php bin/console doctrine:mapping:validate
```

Observe that App\Entity\Category\Category is not detected, and you get an error similar to : 

No mapping file found named 'Category.orm.xml' for class 'App\Entity\ProductCategory\Category'.

4. Comment out most of the other mappings in doctrine.yaml and try again. Notice that the entity is then detected correctly or you can rename the ProductCategory by Foo.

### Possible Solution

Namespace conflict resolution
    - Doctrine should better handle namespaces with similar or overlapping names when mixing XML and attribute mappings

### Additional Context

Doctrine Orm version : 3.0
