### ISSUE TITLE
[AssetMapper] libraries are not imported from vendor_dir in dev environment

### ISSUE THREAD

**Issue by mhlozek** [symfony/symfony#59230]
### Symfony version(s) affected

6.4.6

### Description

In our project, we have disabled access to files in the `vendor` folder (at the Apache level) for security reasons.

For this reason, I wanted to install the libraries for asset mapper in the `vendors` folder (or any other name).

My asset_mapper.yaml file looks like this: 
```
framework:
    asset_mapper:
        vendor_dir: 'assets/vendors'
        # The paths to make available to the asset mapper.
        paths:
            - assets
        excluded_patterns:
            - '*/components/**/*.scss'
            - '*/svgicons/*'
            - '*/tokens/*'
        missing_import_mode: strict
when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
```

I created the entries in importmap.php via `importmap:require`, and installed the libraries via `importmap:install`
The libraries were (correctly) installed in `ROOT/assets/vendors`

In the production environment, after running `asset-map:compile`, everything works.

In the dev environment (after deleting the content in public/assets) I get an error 

> An exception has been thrown during the rendering of a template ("The "bootstrap" vendor asset is missing. Try running the "importmap:install" command.").

It seems that in the dev environment the libraries are searched in the vendor folder and the `vendor_dir` variable is not respected.

### How to reproduce

1. set `vendor_dir: 'assets/vendors'` in `asset_mapper.yaml`
2. install bootstrap via `importmap:require bootstrap`
3. import the bootstrap library e.g. via `import { Alert } from 'bootstrap';`
4. test the build on production - the application should work
5. test the application in the dev environment - the message _The "bootstrap" vendor asset is missing_ appears.

### Possible Solution

I haven't found a solution to make the libraries automatically imported from the folder set in the `vendor_dir` variable.
