### ISSUE TITLE
Command `lint:yaml` doesn't detect broken lists and invalid characters when list is made of brackets

### ISSUE THREAD

**Issue by PatNowak** [symfony/symfony#59259]
### Symfony version(s) affected

7.1.4 and most likely newer ones as well

### Description

It looks like using list in brackets is not validated enough. When passing the data with hyphens, it is. I found it when I saw trailing comma after the brackets got ignored.

### How to reproduce

The command will say this is valid syntax:

```yaml
App\:
        resource: '../src/'
        exclude: ['../src/DependencyInjection/', '../src/Entity/', '../src/Kernel.php'],@@fsdgrety4567y5687r56yhergtertgyertgert#@,
```
- The app will run properly with things after trailing comma when brackets are enclosed.

or this:

```yaml
    App\:
        resource: '../src/'
        exclude: ['../src/DependencyInjection/', '../src/Entity/', '../src/Kernel.php',@@fsdgrety4567y5687r56yhergtertgyertgert#@,
```
- The app will detect error due to unclosed brackets. But the linter won't.
