### ISSUE TITLE
[Webhook] Allow configuring headers for sending webhooks without overriding/decorating services.

### ISSUE THREAD

**Issue by faizanakram99** [symfony/symfony#59462]
### Description

Webhooks sent from symfony have these headers
- `Webhook-Event` (configured by `Symfony\Component\Webhook\Server\HeadersConfigurator`)
- `Webhook-Id` (configured by `Symfony\Component\Webhook\Server\HeadersConfigurator`)
- `Webhook-Signature` (configured by `Symfony\Component\Webhook\Server\HeaderSignatureConfigurator`)

In addition webhook is signed using `sha256` algo.

Both `HeaderConfigurator` and `HeaderSignatureConfigurator` accepts these values as constructor arguments but there is no way to change these values without overriding service definitions.

### Example

For example a config like this

```yaml
webhook:
    server:
        algo: sha256
        headers:
            event-header-name: Webhook-Event
            event-id-name: Webhook-Id
            signature-header-name: Webhook-Signature
```
