### ISSUE TITLE
[Cache] prefix_seed option by cache pool

### ISSUE THREAD

**Issue by LouisGrde** [symfony/symfony#59509]
### Symfony version(s) affected
5.4

### Description

Hello, I have a case where I have a redis common to 2 projects and I want to define a prefix_seed according to the pool because I already have a global prefix_seed on one of the 2 projects. The other project doesn't have a global prefix_seed, so I don't want to set the global prefix_seed for it, as I run the risk of breaking cache pools that shouldn't be broken. But I would like to define the prefix_seed only for a new cache pool so that it is common to both projects.

I quickly started modifying the vendors to add the option per pool. Do you think it's relevant for me to clean this up and do a PR?

This could lead to something like:

```
    property_cache_redis:
      adapter: cache.adapter.redis
      provider: snc_redis.persistent_cache
      default_lifetime: 86400
      custom_prefix_seed: 'cool'
```

in your `cache.yaml`

PS : Sorry for my english

**Comment by nicolas-grekas** [comment]
What you can do is create the service explicitly instead of using semantic configuration.

```yaml
services:
    my_cache:
        parent: cache.app
        tags:
            - cache.pool: { namespace: my_namespace }
```

There are a few other tag attributes that might be relevant depending on your use case, see src/Symfony/Component/Cache/DependencyInjection/CachePoolPass.php
