### ISSUE TITLE
Named serializer get default context from the default serializer

### ISSUE THREAD

**Issue by adri** [symfony/symfony#59639]
### Symfony version(s) affected

7.2.x

### Description

Hi! It looks like the default context is not used for some normalizers, instead the "default context" of the default serializer is used.

### How to reproduce

```yaml
    serializer:
        default_context:
            preserve_empty_objects: true

        named_serializers:
            my:
                default_context:
                    datetime_format: U
                    datetime_cast: int
                    yaml_indent: 1
```

The resulting container sets the `preserve_empty_objects` setting on the `my` version of the `serializer.normalizer.object` service. I'd expect it to use `datetime_format` etc. instead.

`var/cache/dev/App_KernelDevDebugContainer.xml`
```diff
+    <service id="serializer.normalizer.object.my" class="Symfony\Component\Serializer\Normalizer\ObjectNormalizer">
      <argument type="service" id="serializer.mapping.class_metadata_factory"/>
      <argument type="service" id="serializer.name_converter.metadata_aware"/>
      <argument type="service" id="property_accessor"/>
      <argument type="service" id="property_info" on-invalid="ignore"/>
      <argument type="service" id="serializer.mapping.class_discriminator_resolver" on-invalid="ignore"/>
      <argument>null</argument>
      <argument type="collection">
+        <argument key="preserve_empty_objects">true</argument>
      </argument>
      <argument type="service" id="property_info" on-invalid="ignore"/>
    </service>
```

### Additional Context

`SerializerPass` seems to correctly set the binding in `bindDefaultContext`. But something must change/overwrite it later.
<img width="1185" alt="Image" src="https://github.com/user-attachments/assets/119679a8-6f44-4df7-bd4b-60a17bbc167b" />
