### ISSUE TITLE
[Messenger] jitter and delay.queue_name_pattern cause multiple retry queue

### ISSUE THREAD

**Issue by Kleinast** [symfony/symfony#59709]
### Symfony version(s) affected

7.1

### Description

We upgrade symfony from  6.4 to 7.2, with our messenger config like this:
 ```
   retry_strategy:
          max_retries: '%env(int:default:default_worker_max_retries:WORKER_MAX_RETRIES)%'
          delay: 3000
          multiplier: 1
          max_delay: 0
        options:
          persistent: true
          auto_setup: false
          connect_timeout: '%env(int:default:default_connect_timeout:WORKER_CONNECT_TIMEOUT)%'
          delay:
            exchange_name: "%retry_exchange%"
            queue_name_pattern: "queue.solution.retry.%routing_key%.%delay%"
```
And we end up with dozens retry queue created like:
```
queue.solution.retry.queue.solution.command.2713_retry
queue.solution.retry.queue.solution.command.2714_retry
queue.solution.retry.queue.solution.command.2715_retry
...
```

After investigation, we try to set new 7.1 config jitter to 0 (it seem to be at 0.1 by default) and that fix our problem and create only one queue `queue.solution.retry.queue.solution.command.3000_retry`

I think it is not a wanted behavior, and we don't have problem to set jitter at 0 for now, but I think this is kind of bug isn't it ?

FYI: we use Amqp transport

### How to reproduce

Config transport with :
 ```
   retry_strategy:
          delay: 3000
          multiplier: 1
          max_delay: 0
          jitter: 0.1 (seem default value)
        options:
          persistent: true
          auto_setup: false
          connect_timeout: '%env(int:default:default_connect_timeout:WORKER_CONNECT_TIMEOUT)%'
          delay:
            exchange_name: "%retry_exchange%"
            queue_name_pattern: "queue.solution.retry.%routing_key%.%delay%"

```
And send multiple message that should end up on retry

### Possible Solution

I think the problem is located with in the Symfony\Component\Messenger\Retry\MultiplierRetryStrategy class where it set delay with jitter and this delay is used into srv/app/vendor/symfony/amqp-messenger/Transport/Connection.php:387 to create the retry/delay queues
