### ISSUE TITLE
[CSP] Conflict between bundles

### ISSUE THREAD

**Issue by DavidPetrasek** [symfony/symfony#59754]
### Symfony version(s) affected

7.1.9

### Description

This also needs to be reviewed by Vite's and Hotwire Turbo's developers.

**Affected environment:** dev

There is a conflict between Vite, Hotwire Turbo and Symfony WebDebugToolbar:

1. Vite requires a **script** nonce (https://github.com/vitejs/vite/pull/16052):
`<meta name="csp-nonce" content="{{ csp_nonce('script') }}">`
(But it works only when `strict-dynamic` is not used, because otherwise `https://127.0.0.1:5173` has no effect. See provided CSP config below)

2. Hotwire Turbo requires a **style** nonce (https://github.com/hotwired/turbo/pull/501):
`<meta name="csp-nonce" content="{{ csp_nonce('style') }}">`

The same name (csp-nonce) prevents me to satisfy both Vite and Hotwire Turbo.
I tried both combinations:
1. If `csp_nonce('script')` is used, the page loads without CSP errors, but they appear after navigating via Turbo Drive and WebDebugToolbar is missing. Here's a temporary solution for WebDebugToolbar: https://github.com/symfony/symfony/issues/58223#issuecomment-2351509377
2. If `csp_nonce('style')` is used, the page doesn't load properly because CSP doesn't allow the Vite's `updateStyle` function to dynamically add styles.

BTW, I am aware CSP is not needed in dev env, but IMHO it's better.

### How to reproduce

This happens when in dev environment and when CSP is used (see config below) and when also these bundles are used:
- symfony/ux-turbo                    2.21.0 
- pentatrion/vite-bundle              7.1.0  
- symfony/web-profiler-bundle         7.1.9  
- nelmio/security-bundle              3.4.2
- symfony/twig-bundle                 7.1.6

Related NPM packages:
├── vite-plugin-symfony@7.1.0
└── vite@6.0.11
├── @symfony/ux-turbo@0.1.0
├── @hotwired/turbo@8.0.12

NelmioSecurityBundle config:
```
    csp:
        hosts: []
        content_types: []
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            # report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            default-src:
                - 'none'
            style-src:
                - 'self'
                - https://www.gstatic.com https://fonts.googleapis.com                                # Google Fonts
            font-src:
                - 'self'
                - https://fonts.googleapis.com https://fonts.gstatic.com                              # Google Fonts
            img-src:
                - 'self' 
                - 'data:'
            form-action:
                - 'self'
            frame-src:
                - 'self'
                - 'blob:'
                - https://www.google.com
            frame-ancestors:
                - 'self'
            object-src:
                - 'self'
            media-src:
                - 'self'
            connect-src:
                - 'self' 
                - 'wss:'
            block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
            # upgrade-insecure-requests: true # defaults to false, upgrades HTTP requests to HTTPS transport

when@prod:
    nelmio_security:
        csp:
            enforce:
                script-src:
                    - 'strict-dynamic' # Works only in prod

when@dev:
    nelmio_security:
        csp:
            enforce:
                script-src: 
                    - https://127.0.0.1:5173
                style-src:
                    - 'unsafe-inline'
                img-src:
                    - https://127.0.0.1:5173
```

### Possible Solution

Both Vite and Hotwire Turbo should target a meta tag with a different name like this:

Vite: `csp-nonce-script`
Hotwire Turbo: `csp-nonce-style` (I already proposed that here: https://github.com/hotwired/turbo/issues/1315)

This can be done by temporarily targeting both names and by marking the current names as deprecated and to be removed in the next major release.
