### ISSUE TITLE
Upgrading to symfony/messenger 6.4+ causes major CPU spike (min 2x load) because of unnecessary gc_collect_cycles() on every message

### ISSUE THREAD

**Issue by YoYoShik** [symfony/symfony#59788]
### Symfony version(s) affected

6.4.0 - 7.*

### Description

Use gc_collect_cycles() after every message. Works exactly when connected symfony/messenger and symfony/redis-messenger

### How to reproduce
Tested with
php 8.1.8 + symfony/messenger 6.4.*  + (symfony/redis-messenger 6.3.* or 6.4.* ) 
php 8.4.3 + symfony/messenger 7.0.* + symfony/redis-messenger 7.0.*

You won't see the difference with one handler running. Therefore, I recommend running this all on an external environment in many instances. I have so many messages that I need to run 17 handlers at the same time.

For check that everything is fine on 6.3.* version:
Install symfony/messenger 6.3.* and symfony/redis-messenger 6.3.*

1.  Create class for dispatch

```
<?php

namespace App\Messenger\Message\Worker;

class TestMessage {}
```
2. Create empty handler only with return in __invoke()
```
<?php

namespace App\Messenger\MessageHandler\WorkerHandler;

use App\Messenger\Message\Worker\TestMessage;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]
class TestMessagesWorkerHandler
{
    public function __invoke(TestMessage $testMessage)
    {
        return;
    }
}
```

3. Config in messenger.yaml
```
framework:
    messenger:
        transports:
            test_message_worker:
                dsn: "%env(REDIS_DSN)%"
                options:
                    delete_after_ack: true
                    stream: "queues:test_messages_stream"
                    group: "test_messages_group"
                    consumer: "test_messages_group-%env(HOSTNAME)%"
        routing:
            'App\Messenger\Message\Worker\TestMessage': test_message_worker
```
4.  Implement message bus (MessageBusInterface $messageBus) in many places in you app and start dispatching
`$this->messageBus->dispatch(new TestMessage());
`
**And run bin/console messenger:consume test_message_worker** (many instances)

Result CPU you can see on picture with mark **P1**

5. I see symfony/messenger 6.4.0 Worker (Symfony\Component\Messenger\Worker). gc_collect_cycles() were added at 120 line. That's why i want test it on 6.3.0. Add it to our handler
```
<?php

namespace App\Messenger\MessageHandler\WorkerHandler;

use App\Messenger\Message\Worker\TestMessage;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]
class TestMessagesWorkerHandler
{
    public function __invoke(TestMessage $testMessage)
    {
        gc_collect_cycles();
        return;
    }
}
```
**Deploy and run bin/console messenger:consume test_message_worker** (many instances)

Result CPU you can see on picture with mark **P2**
6. Now upgrade packages symfony/messenger and symfony/redis-messenger to 6.4.0 (or 6.4.*). In fact, updating symfony/redis-messenger does not cause problems as long as the symfony/messenger package is <6.4.
And remove  gc_collect_cycles() from our handler. We already have it in Worker class line 120.
```
<?php

namespace App\Messenger\MessageHandler\WorkerHandler;

use App\Messenger\Message\Worker\TestMessage;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]
class TestMessagesWorkerHandler
{
    public function __invoke(TestMessage $testMessage)
    {
        return;
    }
}
```
**Deploy and run bin/console messenger:consume test_message_worker** (many instances)

Result CPU you can see on picture with mark **P3**

As you see **P2** and **P3** has same CPU results. And this result is higher than before on 6.3.*

<img width="1102" alt="Image" src="https://github.com/user-attachments/assets/2d01c4e0-72fe-4bf8-af38-1fb93430b753" />

Paragraph 5 were added to show what exactly gc_collect_cycles() affects performance

### Possible Solution

Perhaps add a new option to the messenger:consume command to ignore this behavior?
