### ISSUE TITLE
Full authentication required on /api/login_check after Symfony 6.4.18 upgrade

### ISSUE THREAD

**Issue by maximgubar** [symfony/symfony#59853]
### Symfony version(s) affected

6.4.18

### Description

**API Platform version(s) affected**: 3.2.13 → 3.4.16
**Symfony version(s) affected**: 6.4.18

After upgrading Symfony from v6.4.17 to v6.4.18, functional tests started failing when calling the /api/login_check endpoint. The user is created successfully, but the login request returns the following error:
```
Symfony\Component\HttpKernel\Exception\HttpException:  
Full authentication is required to access this resource.
```
Upgrading API Platform to v3.4.16 did not resolve the issue.

### How to reproduce

1. Set up API Platform v3.2.13 (or v3.4.16) with Symfony v6.4.18.
2. Configure `security.yaml` as follows:
```yaml
security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern: ^/api
            provider: app_user_provider
            stateless: true
            jwt: ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api(/.+), roles: [ROLE_ADMIN, ROLE_USER] }

```
3. Run the following functional test:
```php
<?php

declare(strict_types=1);

namespace App\Tests\Functional;

use ApiPlatform\Metadata\Post;
use App\Entity\User;
use App\Tests\ApiTestCase;
use Symfony\Component\HttpFoundation\Response;

class UserFunctionalTest extends ApiTestCase
{
    public function testCreateProfile(): void
    {
        $user   = $this->getAnyAdminProfile();
        $client = $this->createClientApi();
        $faker  = $this->getFaker();

        $country = $user->getCountryUsers()->first()->getCountry();

        $this->logInByUser($client, $user);

        $userPath = $this->findPathByOperation(User::class, new Post(), criteria: [
            'country' => \mb_strtolower($country->getCountryCode()),
        ]);

        $emailTest =  'test_'.$faker->numberBetween(10, 100);

        $client->request('POST', $userPath, [
            'json' => [
                'data' => [
                    'type'       => 'User',
                    'attributes' => [
                        'username'            => $emailTest,
                        'email'               => $emailTest.'@test.com',
                        'plainPassword'       => 'test',
                        'enabled'             => true,
                        'resourcePermissions' => [
                            'RESOURCE_WIDGET_BANNERS',
                            'RESOURCE_WIDGET_BANNERS_READ',
                            'RESOURCE_SETTINGS',
                        ],
                    ],
                ],
            ],
        ]);
        $this->assertResponseIsSuccessful();

        $this->logOut($client);

        $client->request('POST', '/api/login_check', [
            'json' => [
                'email'    => $emailTest,
                'password' => 'test',
            ],
        ]);
        $this->assertResponseIsSuccessful();
    }
}
```

**Expected behavior**  
The `/api/login_check` endpoint should return a valid JWT token upon successful login.

**Actual behavior**  
The request to `/api/login_check` fails with:
```
Symfony\Component\HttpKernel\Exception\HttpException:  
Full authentication is required to access this resource.
```

### Additional Context

Rolling back to Symfony 6.4.17 resolves the issue.
