### ISSUE TITLE
[RateLimiter][FrameworkBundle] Ability to configure `CompoundLimiter`

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#59925]
### Description

Under `framework.rate_limiter.limiters`, add the ability to configure a `CompoundLimiter`.

### Example

```yaml
framework:
    rate_limiter:
        two_per_minute:
            policy: 'fixed_window'
            limit: 2
            interval: '1 minute'
        five_per_hour:
            policy: 'fixed_window'
            limit: 5
            interval: '1 hour'
            lock_factory: null
        contact_form:
            policy: 'compound'
            limiters: [two_per_minute, five_per_hour]
```
