### ISSUE TITLE
[Cache] RedisAdapter `AUTH` failed: WRONGPASS invalid username-password pair or user is disabled

### ISSUE THREAD

**Issue by benjamindulau** [symfony/symfony#59986]
### Symfony version(s) affected

5.4.46

### Description

I think I tried everything but I can't seem to be able to create a connection with RedisAdapter cache adapter, Predis and SSL.

I have a Redis server (on Scaleway) that requires username, password and TLS.

My DSN is something like:

```
APP_REDIS_DSN_CACHE="rediss://username:password@XXX.XX.XX.X:6379/1?ssl[cafile]=/var/www/html/etc/ssl/SSL_redis-prod.pem&ssl[verify_peer]=1"
```

And cache is configured like the following:

```yaml
    cache:
        default_redis_provider: "%env(APP_REDIS_DSN_CACHE)%"
        app: cache.adapter.redis
        pools:
            cache.travel_factory:
                adapter: cache.adapter.redis
                default_lifetime: 108000 # 30 jours
```

But I get the following error:
```
12:47:26 WARNING   [cache] Failed to fetch items: `AUTH` failed: WRONGPASS invalid username-password pair or user is disabled. [tls://XXX.XX.XX.X:6379] ["keys" => ["\x00tags\x00f67cb46be3f7ba17a885fedbba9f126f" => "\x00tags\x00f67cb46be3f7ba17a885fedbba9f126f",0 => "f67cb46be3f7ba17a885fedbba9f126f"],"exception" => Predis\Connection\ConnectionException^ { …},"cache-adapter" => "Symfony\Component\Cache\Adapter\RedisAdapter"]
```

Please note that I also have the following service (not related to cache) that works perfectly fine with a similar DSN (just the database changes):
```xml
        <service id="App\Projection\Dictionary">
            <argument type="service">
                <service class="Dayuse\Istorija\DAO\Proxy\Buffer">
                    <tag name="istorija.dao.buffer" />
                    <argument type="service">
                        <service class="Dayuse\Istorija\DAO\Storage\PredisDAO">
                            <argument type="service">
                                <service class="Predis\Client">
                                    <argument type="string">%env(APP_REDIS_DSN_DICTIONARY)%</argument>
                                </service>
                            </argument>
                            <argument type="string">dictionary</argument>
                        </service>
                    </argument>
                </service>
            </argument>
        </service>
```

### How to reproduce

Create a Redis 7 server with ACL (both username & password) and TLS with certificate and tries to configure the cache adapter.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue? Without being able to reproduce we won’t be able to work on a fix (nor being able to determine if there is a bug at all).

**Comment by benjamindulau** [comment]
**Repro**:

```bash
git clone git@github.com:benjamindulau/symfony_issue_59986.git && cd symfony_issue_59986
```

```bash
composer install
```

```bash
docker compose up -d
```

```bash
bin/console debug:cache -v
```

Note that I found the issue. The problem is that in Symfony 5.4 the RedisTrait doesn't handle username properly. Well not at all in fact :)

If I replace this code from 5.4: https://github.com/symfony/cache/blob/5.4/Traits/RedisTrait.php#L108-L118

With the one from 7.2 which correctly constructs `$auth`: https://github.com/symfony/cache/blob/7.2/Traits/RedisTrait.php#L102-L116

Then everything works as expected.


Now, I'm not sure how I can override this adapter ?

**Comment by stof** [comment]
Redis 6 introduced a new way to authenticate with username+password (instead of only a password). Symfony 5.4 only supports the old way (the only way supported in Redis 5 and older).

My advice is to upgrade to Symfony 6.4 or 7.

**Comment by benjamindulau** [comment]
@stof Yeah that's the plan this year. But not an easy migration ATM so in the meantime I need a workaround so I can migrate my infrastructure.

Could you point me in the right direction so I can override the default RedisAdapter and create the connection properly?

I tried to override the service with my own `createConnection` implementation but decorating the service doesn't work because it can't be autowired and I suppose the service is defined in a certain way in the framework.

**Comment by benjamindulau** [comment]
Ok so that's what I did for now:

```php
<?php
namespace App\Cache;

use Predis\Client;

class RedisConnectionFactory
{
    public static function createConnection(string $dsn): Client
    {
        return new Client($dsn);
    }
}
````

services.yaml
```yaml
services:
    app.cache_redis_provider:
        class: Predis\Client
        factory: [ 'App\Cache\RedisConnectionFactory', 'createConnection' ]
        arguments:
            - '%redis_dsn%'
```

cache.yaml:
```yaml
cache:
    default_redis_provider: "app.cache_redis_provider"
    app: cache.adapter.redis
```

Not sure if that's a correct way to do it but it seems to work as expected.
