### ISSUE TITLE
[CSRF] CSRF Token always invalid

### ISSUE THREAD

**Issue by JuGid** [symfony/symfony#60206]
### Symfony version(s) affected

7.2.*

### Description

My CSRF token is always invalid. For pages that not require user connection, it's always wrong. 

### How to reproduce

Can't reproduce it as i'm using symfony as I should, but this is the code I use to make my forms : 

CalendarType.php
```php
class CalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('date_start', null, [
                'widget' => 'single_text',
            ])
            ->add('date_end', null, [
                'widget' => 'single_text',
            ])
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Calendar::class,
        ]);
    }
}
```

CalendarController.php
```php
final class CalendarController extends AbstractController
{
    public function __construct(
        private OrganisationContext $organisationContext, //My class to get current organization from session, not really important but we never know...
    ){}

    #[Route('/add-calendar', name: 'app_add_calendar')]
    public function add_calendar(Request $request, EntityManagerInterface $em): Response
    {
        $organisation = $this->organisationContext->getOrganisation();
        $calendar = new Calendar();
        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $organisation->addCalendar($calendar);

            $em->flush();
            $this->addFlash('success', 'Calendar created.');

            return $this->redirectToRoute('app_dashboard');
        }
        return $this->render('calendar/add_calendar.html.twig', [
            'form' => $form,
            'organization' => $organisation,
        ]);
    }
}
```

add_calendar.html.twig
```twig
<div class="flex flex-col w-full">
    {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.description) }}
        <div class="grid grid-cols-2 gap-4">
            {{ form_row(form.date_start) }}
            {{ form_row(form.date_end) }}
        </div>

        <div class="flex flex-row justify-end">
            <button type="submit" class="btn btn-success text-white rounded-lg transition transform hover:-translate-y-1 hover:shadow-lg duration-300"><twig:ux:icon name="ph:plus" class="h-6 w-6" /> Add calendar</button>
        </div>
    {{ form_end(form) }}
</div>
```

The form generated includes the csrf token as follow : 
```html
<input type="hidden" id="calendar__token" name="calendar[_token]" data-controller="csrf-protection" class="input input-bordered w-full" value="csrf-token">
```

Here is my csrf.yml config file
```yaml
# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
```
 And the error message : 
````
Message : The CSRF token is invalid. Please try to resubmit the form.
Origin : Unknown.
Cause : 
Caused by:
Symfony\Component\Security\Csrf\CsrfToken
{
  -value: "csrf-token"
  -id: "submit"
}
````
### Possible Solution

Reload the page where the form is.

**Comment by JuGid** [comment]
I found that there was a `csrf_protection_controller.js` in my `asset/controllers` and I don't know why. This was the problem. 
Without it, it works really well.

**Comment by JuGid** [comment]
For some reasons, my configuration into framework.yml was not modified by the recipe. I made the changes based on https://github.com/symfony/recipes/pull/1337/files and it works pretty well !

**Comment by JuGid** [comment]
So, I said it works pretty well but it is not... I tested my fixes on another app in Symfony 7.2 and the problem still the same.

I read this issue : https://github.com/symfony/symfony/issues/59065 , but I don't have reverse proxy as I'm working on local with `symfony server:start`, so trusted proxies didn't help.

To put it all in a nutshell this is what I have : 

In my assets/controllers folder, I have a file called csrf_protection_controller.js with the same code contained in https://github.com/symfony/recipes/pull/1337/files.

This is my framework.yml configuration : 
```yaml
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    # Note that the session will be started ONLY if you read or write from it.
    session:
        enabled: true
    form:
        csrf_protection:
            enabled: true
            token_id: 'submit'
    csrf_protection:
        stateless_token_ids: ['submit','authenticate','logout' ]
    serializer:
        default_context: 
            circular_reference_limit: 1
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```

I tried on a form that I printed with twig with `{{ form(form) }}` and it includes a hidden field _token like : 

```
<input type="hidden" id="intervenant__token" name="intervenant[_token]" data-controller="csrf-protection" class="input input-bordered w-full" value="csrf-token">
```

And I use the commande `php bin/console asset-map:compile` for my assets to work (as I also use the TailwindBundle).

The only workaround I found is to set the following options on every form type. And it's really annoying.
```php
public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SequenceConstraintDeeds::class,
            'calendar' => null,
            'csrf_protection' => true,
            'csrf_field_name' => '_token',
            'csrf_token_id' => 'constraint',
        ]);
    }
```
But, as i was trying to debug with `php bin/console debug:form` I found out that the default values are : 
```
csrf_protection : true
csrf_field_name : _token
csrf_token_id: submit
```

Can't find help on documentation or issues, so I assume that I'm the only one who's facing this issue ?
If you need more details, ask for it.

Thank you !

EDIT : It seems like, when I go to a page, the Javascript is not executed. I use a JS library to create Gantt graph and the library doesn't render the chart before F5 the page. May be I should look for this root cause ?
When I clear the console and go to the form page, the console is empty. When I reaload, I can see the csrf-protection controller lazy loaded.

EDIT 2 : It works when using `<body data-turbo="false">`
