### ISSUE TITLE
[HttpClient] "Value of type null is not callable" in CurlResponse

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#60219]
### Symfony version(s) affected

7.2.4

### Description

Callable passed is nullable, but it's not null checked before being used in

https://github.com/symfony/symfony/blob/d5b5581bf3681569f586f394e72e0799cead91aa/src/Symfony/Component/HttpClient/Response/CurlResponse.php#L431

### How to reproduce

```
framework:
    http_client:
        default_options:
            headers:
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36'
            max_redirects: 10
```

GET URL https://time.com/5552679/impeached-presidents/
