### ISSUE TITLE
[FrameworkBundle][RateLimiter] Missing 'limiters' in OptionsResolver

### ISSUE THREAD

**Issue by zavarock** [symfony/symfony#60306]
### Symfony version(s) affected

7.3.0

### Description

Looks like PR #60155 forgot to add the new 'limiters' config to configureOptions.

### How to reproduce

Update to 7.3.0 with a rate limiter configuration described on https://symfony.com/doc/current/rate_limiter.html#configuration

### Possible Solution

```php
define('limiters')->allowedTypes('string[]')
``` 
in https://github.com/symfony/symfony/blob/195f1f123d1328ef534f70e4605948049120ae73/src/Symfony/Component/RateLimiter/RateLimiterFactory.php#L76

**Comment by xabbuh** [comment]
I am not quite sure I follow what's wrong. Can you describe what actual issue you experience and how to reproduce it?

**Comment by zavarock** [comment]
@xabbuh 
There is a new 'limiters' option added for compound policies when updating to 7.3.0 version, but the problem is, this new option is missing when calling OptionsResolver in RateLimiterFactory class, therefore, when starting the application with a rate_limiter config in framework.yaml, it will show an exception page when accessing any route:

![Image](https://github.com/user-attachments/assets/542ce7b9-2952-4df8-aed1-6ea17326f6cf)

**Comment by xabbuh** [comment]
Please share the config that you used.

**Comment by zavarock** [comment]
Just a sample:

```yaml
framework:
    rate_limiter:
        test_limiter:
            policy: 'fixed_window'
            limit: 10
            interval: '1 minute'

    http_client:
        scoped_clients:
            test:
                scope: ^http?s://
                rate_limiter: 'test_limiter'

```
