### ISSUE TITLE
Mailer uses return-path as sending address when communicating with SMTP server

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#60527]
### Symfony version(s) affected

6.4.21

### Description

The remote SMTP server will be told the message comes from the `return-path` address, not the `from` address (unless `return-path` is not set).

### How to reproduce

```yaml
framework:
  mailer:
    headers:
      from: Foo <foo@bar.com>
      return-path: bounces@bar.com
```

### Possible Solution

Use `from` header instead.
