### ISSUE TITLE
Fatal error during upgrading to Symfony 7.3 and rebuilding container: Uncaught Error: First array member is not a valid class name or object

### ISSUE THREAD

**Issue by robiningelbrecht** [symfony/symfony#60585]
### Symfony version(s) affected

7.3.0

### Description

When running `composer update symfony/*` to upgrade from 7.2 to 7.3, all packages are downloaded and installed. When composer tries to clear the Symfony cache and the container is rebuilt, the following error is thrown:

<img width="530" alt="Image" src="https://github.com/user-attachments/assets/7e258471-84e6-4ced-bf43-8b2567cb5f33" />

Line 799 contains: 

```php
 return $container->privates['App\\Infrastructure\\ValueObject\\Measurement\\UnitSystem'] = [NULL, 'from']($container->get("app.config")->get("appearance.unit_system", ));
```

The error is thrown due to the first value in the array `NULL`. The reason for NULL being there is that my service is defined as:

```yml
    App\Infrastructure\ValueObject\Measurement\UnitSystem:
        factory: [ null, from ]
        arguments: ['@=app_config("appearance.unit_system")']
```

### How to reproduce

* Add an entry in `services.yaml` with a factory method on the class itself:

```yaml
    App\Namespace\To\Class
        factory: [ null, yourFactoryMethod ]
        arguments: ['your-argument']
```

* update `composer.json` and edit all Symfony packages from `7.2.*` to `7.3.*`
* Run `composer update symfony/*`

### Additional Context

The Symfony docs state that this approach should be possible: https://symfony.com/doc/current/service_container/factories.html#using-the-class-as-factory-itself

**Comment by HypeMC** [comment]
The main issue here is that `UnitSystem` is an **enum**. In #60095, the `container.excluded` tag was added to all enums, so the `ResolveFactoryClassPass` no longer resolves the class:

https://github.com/symfony/symfony/blob/e9f91a63c7045d7da58fbd0e230ede14737951c9/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php#L79-L81

Based on the [discussion](https://github.com/symfony/symfony/pull/60095/files#r2021037158) there, this was intentional, so I'm not sure it qualifies as a bug, even though it is technically a BC break.

**Comment by robiningelbrecht** [comment]
It makes sense that this does not work anymore if it has explicitly been removed. But I'd expect that minor upgrades do not introduce these kind of breaking changes?

**Comment by ro0NL** [comment]
> No need to support this, it'd be broken design :) (https://github.com/symfony/symfony/pull/60095/files#r2021037158)

so it's expected yes.

**Comment by robiningelbrecht** [comment]
It's indeed removed but

1. No clue why it was decided to introduce a breaking change between minor versions
2. Why it was decided that "it'd be broken by design" 
3. Why this breaking change is not mentioned in the docs

Anyway, worked my way around this by referencing the FQCN instead of `null` on enum factory methods

**Comment by nicolas-grekas** [comment]
As a workaround you can disable autoconfiguration for that definition:

```yaml
    App\Infrastructure\ValueObject\Measurement\UnitSystem:
        autoconfigure: false
        factory: [ null, from ]
        arguments: ['@=app_config("appearance.unit_system")']
```
