### ISSUE TITLE
`default_index_method` no longer works with contiguous integers since 7.0

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#60651]
### Symfony version(s) affected

7.2.7

### Description

Worked fine in 6.4, but now it seems to be completely ignored in 7.x. The tagged locator just uses the class name as the key now, ignoring the value returned by `default_index_method`, despite the fact that the method is still called at container compile time. In case it matters, my index method returns in `int`.

### How to reproduce

Tag some services.

```yaml
services:
  _instanceof:
    Org\AbstractUnpacker:
      tags:
        - unpacker
```

Inject services.

```yaml
services:
  Org\Unpacker:
    arguments:
      $unpackers: !tagged_locator
        tag: unpacker
        default_index_method: getVersion
```

```php
namespace Org;

abstract class AbstractUnpacker
{
    abstract public static function getVersion(): int;
}
```

**Comment by HypeMC** [comment]
@Bilge At first glance, your service definition seems to be incorrect. It should be:

```yaml
_instanceof:
    Org\AbstractUnpacker:
        tags:
            - unpacker
```

I've tested it, and it seems to work as expected. Here's the dumped container:

```php
public static function do($container, $lazyLoad = true)
{
    include_once \dirname(__DIR__, 4).'/src/Unpacker/Unpacker.php';

    return $container->privates['App\\Unpacker\\Unpacker'] = new \App\Unpacker\Unpacker(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
        10 => ['privates', 'App\\Unpacker\\BarUnpacker', 'getBarUnpackerService', true],
        5 => ['privates', 'App\\Unpacker\\FooUnpacker', 'getFooUnpackerService', true],
    ], [
        10 => 'App\\Unpacker\\BarUnpacker',
        5 => 'App\\Unpacker\\FooUnpacker',
    ]));
}
```

Could you create a [small example application](https://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs) to reproduce your issue?
