### ISSUE TITLE
[Serializer] Named Serializers do not work on intersection types

### ISSUE THREAD

**Issue by MarijnDoeve** [symfony/symfony#60682]
### Symfony version(s) affected

7.3.0, 7.2.0

### Description

Named Serializes are only injected when using `SerializerInterface`. When I use an intersection type like `SerializerInterface&DenormalizerInterface` I'm getting the default `Serializer`.

### How to reproduce

```yaml
#config/serializer.yaml
framework:
    serializer:
        named_serializers:
            somthing:
                name_converter: 'serializer.name_converter.camel_case_to_snake_case'
                default_context:
                    datetime_format: 'U'
```

```php
    public function __construct(
        protected SerializerInterface&DenormalizerInterface $somethingSerializer,
    ) {
    }
```
