### ISSUE TITLE
HttpClient: base_uri is not handled correctly

### ISSUE THREAD

**Issue by stbr0131** [symfony/symfony#60728]
### Symfony version(s) affected

7.3

### Description

When using base_uri the base_uri is not handled like in documentation.
Consider following configuration:
```
    http_client:
        default_options:
            retry_failed:
                max_retries: 3
        scoped_clients:
            shopware.api:
                base_uri: 'http://192.168.0.0/api'
```
The client uses only http://192.168.0.0 as base.
if you write 
`base_uri: 'http://192.168.0.0/api'/`
the base_uri for all requests is correct http://192.168.0.0/api'/ .

### How to reproduce
```
http_client:
        default_options:
            retry_failed:
                max_retries: 3
        scoped_clients:
            shopware.api:
                base_uri: 'http://192.168.0.0/api'
```
