### ISSUE TITLE
[Validator] Simplify XML and YAML syntax

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#7720]
I would like to propose simplifications for the XML and YAML syntax of the validator configuration. The implementation of these simplifications in the respective loaders MUST be BC.

##### YAML

For the YAML notation, I'd like to make the leading dashes of constraints optional to simplify both the multiline and inline notation of constraints. Listing a constraint twice (a rare edge case) can be achieved by nesting its configurations into an array.

###### Before

```yaml
Acme\BlogBundle\Entity\Author:
    properties:
        # Multiline example
        status:
            - NotNull: ~
            - Type: integer
            # Edge case
            - Range: { min: 0, groups: Admin }
            - Range: { min: 5 }
        # Inline example
        name: [{ NotBlank: ~ }, { Length: { min: 3 } }]
```

###### After

```yaml
Acme\BlogBundle\Entity\Author:
    properties:
        # Multiline example
        status:
            NotNull: ~
            Type: integer
            # Edge case
            Range: [
                { min: 0, groups: Admin },
                { min: 5 }
            ]
        # Inline example
        name: { NotBlank: ~, Length: { min: 3 } }
```

##### XML

In the XML notation, I'd like to add the "groups" attribute to the "constraint" element.

###### Before

```xml
<class name="Acme\BlogBundle\Entity\Author">
    <property name="profileData">
        <constraint name="NotBlank">
            <option name="groups">Profile</option>
        </constraint>
        <constraint name="Length">
            <option name="max">100</option>
            <option name="maxMessage">Your bio is too long!</option>
            <option name="groups">
                <value>Profile</value>
                <value>Signup</value>
            </option>
        </constraint>
    </property>
</class>
```

###### After

```xml
<class name="Acme\BlogBundle\Entity\Author">
    <property name="profileData">
        <constraint name="NotBlank" groups="Profile" />
        <constraint name="Length" groups="Profile Signup">
            <option name="max">100</option>
            <option name="maxMessage">Your bio is too long!</option>
        </constraint>
    </property>
</class>
```

Comments and/or PRs welcome.
