### ISSUE TITLE
Validation Errors are not mapped correctly to Form Fields if Case is different

### ISSUE THREAD

**Issue by naitsirch** [symfony/symfony#7959]
Hi.
Today I searched two hours for the reason why one validation error wasn't shown at the form field but at the root form.
My form builder class looked like that:

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('xfade', 'integer', array('required' => false));
}
```

My `validation.yml` looked like that:

``` yml
Streamserver:
    properties:
        xFade:
            - Range: { min: 0, groups: [ Default ] }
```

The validation error of the property _xFade_ wasn't mapped to the form field _xfade_ and that error was hard to find, because the value of the field was mapped correctly to the entity of course.

One possible solution would be:

When mapping violation to form child (in `Symfony\Component\Form\Extension\Validator\ViolationMapper\ViolationMapper->matchChild()`) do a case-insensitive comparison.

But maybe there are better ways.
