### ISSUE TITLE
[YAML] weird sequence-in-mapping error

### ISSUE THREAD

**Issue by indeyets** [symfony/symfony#8077]
This YAML code is parsed just fine:

```yaml
---
a:
- b: c
```

But this code:

```yaml
---
a:
-
  b: c
```

results in `Symfony\Component\Yaml\Exception\ParseException` with message `You cannot define a sequence item when in a mapping`

I believe, that both examples are correct
