### ISSUE TITLE
[YAML] more indentation weirdness

### ISSUE THREAD

**Issue by indeyets** [symfony/symfony#8093]
this works:

```yaml
---
test:
  me:
    - tenderly: please
      im: broken
```

this works too:

```yaml
---
test:
  me:
  - tenderly: please
```

this doesn't work:

```yaml
---
test:
  me:
  - tenderly: please
    im: broken
```

`Symfony\Component\Yaml\Exception\ParseException` with message `Unable to parse at line 5 (near "  im: broken").`
