### ISSUE TITLE
RedirectController::redirect() loses querystring parameters

### ISSUE THREAD

**Issue by Craige** [symfony/symfony#9242]
While RedirectController::urlRedirect() preserves the querystring parameters and passes them on to the redirected request, RedirectController::redirect() will lose them.

Expectation:
```
index_redirect:                                                                                                                                                                                                                                             
     path: /index.php                                                            
     defaults:                                                                   
         _controller: FrameworkBundle:Redirect:redirect                          
         route: home                                           
         permanent: true
other_redirect:                                                                                                                                                                                                                                             
     path: /foo.php                                                            
     defaults:                                                                   
         _controller: FrameworkBundle:Redirect:urlRedirect                          
         path: /bar                                           
         permanent: true

```

I would expect both of these to do the same thing, but the first one takes the route name. However, only the second route will preserve the querystring parameters on the request. The first one will drop them.
