### ISSUE TITLE
[Session] Empty session id after autologin with remember me.

### ISSUE THREAD

**Issue by athlan** [symfony/symfony#9255]
Case:

I want to know session id, so i call test code in controller:

``` php
var_dump($this->get('session')->getId());
```

The session id is returned properly.

As logged user with remember me option I just close browser's window. I open my browser again, the autologin mechanism works perfectly (security allows me to see the page), session received from Session object is empty string. After refresh page, the session id is available.

Info:
OS: Debian
PHP Version 5.4.4-14+deb7u4
with Zend OPcache v7.0.2
SF: symfony/symfony 2.3.x-dev 714d719

Configuration:

``` yaml
security:
    firewalls:
        secured_auth:
            pattern: ^/(account|auth|panel)
            security: true
            anonymous: true
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: /panel/website
            remember_me:
                key: FokusRememberMe
                lifetime: 5184000 # 60 days in seconds
                path: /
                domain: ~
            logout:
                path:   /auth/logout
                target: /panel/website
                invalidate_session: false
```
