### ISSUE TITLE
[Security] Logout from one firewall logouts from others

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#9543]
Consider security yml firewalls:

```yaml
        admin:
            pattern: ^/admin
            form_login:
                login_path:     admin_login
                check_path:     admin_login_check
            logout:
                path:           admin_logout
            anonymous:          true

        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
            anonymous:    true
```

I want to be logged in `admin` firewall by one user, and in `main` firewall by other user (simultaneously, so default switch user functionality is inappropriate). 

But logout listener of one firewall will invalidate session, so user will be logouted from other firewalls too.

Please fix this issue. I think best way - provide an option to use different sessions (different paths/domains in cookies). Also different sessions will prevent possible collisions
