### ISSUE TITLE
[Form] Support polymorphic collections

### ISSUE THREAD

**Issue by WishCow** [symfony/symfony#9835]
(@bschussek recommended opening a ticket for this, in the comments at http://williamdurand.fr/2013/12/16/enforcing-data-encapsulation-with-symfony-forms/)

Currently, there is no way to create forms for an entity, that has "polymorphic" relations. My definition for a polymorphic relation is, when an Entity has a -to-many relation to another entity, which has multiple subclasses:

``` php
abstract class Question {
    protected $id;
}

class OpenQuestion extends Question {
}

class ChoiceQuestion extends Question {
    private $choices = [];
    private $correctChoice;
}

class Assignment {
    private $id;
    private $name;
    private $questions; // ArrayCollection that can hold OpenQuestions and ChoiceQuestions
}
```

The Doctrine2 mapping, to make it clearer:

``` yml
Entity\Assignment:
    type: entity
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
    oneToMany:
        questions:
            targetEntity: Question
            mappedBy: assignment

Entity\Question:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn: { name: type, type: string }
    discriminatorMap: { choice: ChoiceQuestion, open: OpenQuestion }
    manyToOne:
        assignment:
            targetEntity: Assignment
            inversedBy: questions
            joinColumn:
                nullable: false
                onDelete: cascade

Entity\ChoiceQuestion:
    type: entity
    fields:
        choices:
            type: array
        correctChoice:
            type: integer

Entity\OpenQuestion:
    type: entity
```

As far as I know, there is no way to create a form for the Assignment entity, that could map the questions property. I'm familiar with how the prototype property works, when embedding multiple forms, but for this scenario I would need 2 prototypes to make this work (or N prototypes, in the general sense).

There is already a 3rd party bundle, https://github.com/infinite-networks/InfiniteFormBundle, that introduces a form type called "polycollection", and right now I'm in the process of implementing that, to see if it solves my case, but maybe it would be worthwhile to integrate that into the Form component? The docs are a bit lacking, but with the help of the author I managed to get it working, see the talk here: https://github.com/infinite-networks/InfiniteFormBundle/issues/10.
