### ISSUE TITLE
[Routing] Default locale in routes

### ISSUE THREAD

**Issue by MAXakaWIZARD** [symfony/symfony#9981]
Consider example from docs
```yaml
contact:
    path:      /{_locale}/contact
    defaults:  { _controller: AcmeDemoBundle:Contact:index, _locale: en }
    requirements:
        _locale: en|fr|de
```
As docs say it should apply default locale for path /contact
But it doesn't:
```bash
php app/console router:match /contact
None of the routes matches
```
However, it works for route (optional placeholder is last in path):
```yaml
wre_index:
    path:  /{_locale}
    defaults: { _controller: AcmeDemoBundle:Index:index, _locale: en }
    requirements:
        _locale: en|fr|de
``` 
This was checked on Symfony Standard 2.4.1 and 2.4.0
